### ISSUE TITLE
feat(patch): Video quality in portrait videos

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#1]
### Application

This patch is for applying  selected prefered video quality on portrait videos

### Issue

Video quality in portrait videos is distorded and this problem is present also in YouTube vanced 

### Patch

I would like a patch to solve this problem

### Motivation

This patch will be useful for all users

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Mohammed1520** [comment]
I don't mean short videos . I mean normal videos in portrait resolution.. the quality is always worse . For me it is always 144 and when i make it 720 it doesn't respond.. the proplem is present since YouTube Vanced..

**Comment by venkat2305** [comment]
This issue is raised in og revanced as well.
https://github.com/revanced/revanced-patches/issues/1329

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.158.1
