### ISSUE TITLE
question: save/watch later/fav

### ISSUE THREAD

**Issue by Dangln** [inotia00/ReVanced_Extended#100]
### Application

YouTube

### Description

Is there a way to make it remember last choice when choosing save/watch later or favorites?..
Like if I chose watch later it goes to watch later everytime until I change it . It always saves to favorites for some reason. 

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by venkat2305** [comment]
Yes. This would be a killer feature. I use that save button only to add videos to watch later but clicking it once never adds the video to watch later but instead adds it to the latest modified playlist. This is so annoying. It would be great if that option could add videos to watch later and can change its default action
