### ISSUE TITLE
feat(patch): hide video title in fulscreen mode(separate setting)

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1001]
### Application

YouTube

### Issue

i know the hide-fullscreen-panels patch already covers this, but it would be convenient to have a separate setting to hide the video title in fullscreen, just like the hide-collapse-button setting. the hide-fullscreen-panels patch limits functionality by disabling  ̶e̶n̶d̶s̶c̶r̶e̶e̶n̶ ̶c̶a̶r̶d̶s̶ **correction: endscreen overlay** which is why i think a separate patch for hiding video title would be great.

### Patch

![Screenshot_20230510-200213_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/87489540/0b5cecbf-86d1-4705-8224-eda67d8e1541)

a dedicated patch to hide video title in fullscreen mode

### Motivation

the hide-fullscreen-panels patch limits functionality by disabling endscreen overlay which is why i think a separate patch for hiding video title would be great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by S23u512** [comment]
There already is a patch for this, its called Show Fullscreen Title, just disable it. Please note that it wont work if you have tablet mode enabled.

**Comment by MondayNitro** [comment]
> There already is a patch for this, its called Show Fullscreen Title, just disable it. Please note that it wont work if you have tablet mode enabled.

no, not in rvx. you must be talking about revanced. hope inotia adds this patch in future releases

**Comment by S23u512** [comment]
Do you mean revanced extended?

**Comment by MondayNitro** [comment]
im sorry for commenting again here, can you add this patch if possible? fullscreen panels already have it but a patch to only hide fullscreen video title is needed. thanks for your efforts till now

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
