### ISSUE TITLE
bug: <title> HDR video bug

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1002]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube extended v18.16.39

### Bug description

When I playing the HDR video the brightness is not increasing it gives issue while playing low brightness videos.

### Steps to reproduce

Open YouTube 
Play HDR video

### Relevant log output

```shell
.
```

### Screenshots or videos

The recording not adding directly on github bcus long size,I am sending link of google drive :- 
https://drive.google.com/file/d/14NqGhKHz3hBmoF1gFcx2P1U2AwtFAwtA/view?usp=drivesdk

### Device Environment

Miui 14,android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
![siwpe](https://github.com/inotia00/ReVanced_Extended/assets/108592928/2e65bc1e-9614-4921-9d1c-cfdf207c41a4)

This is an old bug that existed in the official ReVanced.

To solve this old bug I tried various things.

And the `Enable swipe gesture brightness values in HDR vide` added to the Swipe controls setting fixes this old bug.

This setting is ON by default unless the user manually turns OFF.

**Comment by Adity1243** [comment]
OK it solved thanks.
