### ISSUE TITLE
Revanced extended is not updating and throwing error 

### ISSUE THREAD

**Issue by pauliestephen** [inotia00/ReVanced_Extended#1003]
### Application

YouTube

### Description

I have the revanced extended version 18.14.41. Now I am trying to update the application to version 18.16.39. But it is throwing error that app not installed as package conflicts with an existing package. I know by uninstalling and reinstalling the newer version will work, but I will loose all the changes and customizations I did in the settings. Is there any way to update this to new version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by pauliestephen** [comment]
I think i found the solution. There is a option to export my revanced extended settings to a jsob file and I can import it in newer version

**Comment by Kobewaxman** [comment]
> I think i found the solution. There is an option to export my revanced extended settings to a json file and then I can import it in newer version

Btw you are also able to export/import the SponsorBlock settings as well. There is an option in the SponsorBlock settings. When you tap on it, copy all of the contents to your clipboard. Then after you install the new YT ReVanced Extended you can replace the contents in that menu with the one you saved to your clipboard.

**Comment by inotia00** [comment]
This is because the signature of the newly patched app is out of date.

If you have reinstalled ReVanced Manager, this issue may occur

Make a backup of your keystore.

Revancify uses the same signature, so it is free from these issues.
