### ISSUE TITLE
question: <title>:  Youtube 18.18.34

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/ReVanced_Extended#1004]
### Application

YouTube

### Description

The current version of the YouTube app is 18.18.34.  The version provided to your website https://revancedextended.com/ko/ is 18.16.38 verjan.  I'm sorry I can't build it myself.  Please build with the latest version 18.18.34 (arm64 (v8a)).

please..

thank you !

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The currently supported version is YouTube v18.16.39.

Also you are trying to download from an illegal site.

I can't make any guarantees about your use of the prebuilt APK.
