### ISSUE TITLE
question: <title>: yoitube original 18.18.34..

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/ReVanced_Extended#1005]
### Application

YouTube

### Description

Are you saying revanced-extended is only supported on YouTube version 18.16.39?.  The YouTube original version on the Play Store is 18.18.34, does that mean revanced-extended can't be built on this version?  If so, when will the build with revanced-extend for 18.18.34 be released?

thank you !

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a list of currently supported versions.

v18.12.35
v18.13.38
v18.14.41
v18.15.40
v18.16.39

Please refer to the [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android))  for details
