### ISSUE TITLE
bug: No playlists shown

### ISSUE THREAD

**Issue by kevinr99089** [inotia00/ReVanced_Extended#1007]
### Tools used

CLI

### Application

YouTube rvx:18.16.39 (playlist not shown for the first and last patch released for version 18.16.39)
YouTube rvx: 18.18.34
YouTube Unpatched: 18.18.34 (playlists are shown)
YouTube ReVanced: 18.16.37 (playlists are shown)

### Bug description

When I want to add a video in a playlist, my playlists are not displayed, Even after deleting data and reinstall.

### Steps to reproduce

Play a video, add to a playlist, press and hold to change playlist, and no playlist is displayed.

### Screenshots or videos

![Screenshot_20230511_155930_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/93716347/5932d920-5c87-4b3c-a9d3-339dac038e1c)

### Solution

Use another Account

### Additional context

When I change my account, the playlist is displayed on the video
My playlists are still displayed in the Library tab (on the account where it is not displayed)
I have some playlists visible and some in private
I have about 40 playlists

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by kevinr99089** [comment]
I don't know if this can help you to understand the problem, but when I play a video already in a playlist, the button doesn't appear as "Saved", I have to keep pressing the button to update it

https://github.com/inotia00/ReVanced_Extended/assets/93716347/4b5fb066-32c6-4da6-8af0-1fd1f20fc1fd

**Comment by inotia00** [comment]
not reproduced
There have been similar issues before, so it looks like an A/B test.

**Comment by kevinr99089** [comment]
I just did the test using an old interface
(Referring to the issues with the label A/B Test) (17.41.37), the playlists are displayed correctly on a video, but when I switch back to the new interface, I have the same problem again.

**Comment by inotia00** [comment]
If so, it's an obvious A/B test

**Comment by inotia00** [comment]
In revanced-patches-v2.173.10, I added exceptions to some adblock filters.

Try the patch again with revanced-patches-v2.173.10 and check if the issue is reproduced

**Comment by inotia00** [comment]
Does the issue reproduce with revanced-patches-v2.181.1?

**Comment by kevinr99089** [comment]
No, the playlists are displayed correctly, thank you.

By the way, nice new logo!
