### ISSUE TITLE
feat(patch-request): hide ryd separator

### ISSUE THREAD

**Issue by Spacellary** [inotia00/ReVanced_Extended#101]
### Application

YouTube

### Issue

This is of course subjective but I prefer the way it was before the update, without the `|` after the like symbol.  I get it's supposed to "mirror" the other side and be symmetrical but it just looks off, and as long as both sides can't be completely equal the previous way was cleaner IMO... So I ask:

### Patch

RYD Related, Like Button Adjustment:
Remove the `|` after the like symbol in the Like Button Container

### Motivation

Previous implementation looks (subjectively) cleaner until there's proper symmetry, and the added `|` character doesn't match the counterpart in tbe slightest...

![Screenshot_2023-01-05-05-03-55-189_app rvx android youtube](https://user-images.githubusercontent.com/39604793/210733540-3aa7865c-719b-4cfb-83bb-484179308fcd.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Spacellary** [comment]
Heya! Sorry, should have added that!

Device: Xiaomi Redmi Note 11
Android: 12 (MIUI 13)
System font: MiSans (it's the default one)

**Comment by inotia00** [comment]
Unfortunately, this feature varies depending on the manufacturer of the device you use

The first person who suggested this function does not seem to support Xiaomi device

**Comment by Spacellary** [comment]
I tried 2 other fonts and I had the same results.
The `|` did look a bit different with each one, but still looks completely weird.

**Comment by inotia00** [comment]
Will be added in next build
(Already reflected in commit)

**Comment by inotia00** [comment]
added in revanced-patches-v2.152.6

**Comment by Spacellary** [comment]
Thanks for the quick and hard work as always @inotia00

**Comment by Spacellary** [comment]
I'll just report for future reference that with YouTube v18.01.33 (beta) and latest 1.152.6 patches the like/dislikes now look like this, so already better, even if I still prefer disabled for now...

![Screenshot_2023-01-07-02-13-36-939_app rvx android youtube](https://user-images.githubusercontent.com/39604793/211132395-e0495c8a-69f4-4207-a1af-55d285f69d7f.png)

**Comment by inotia00** [comment]
![ryd](https://user-images.githubusercontent.com/108592928/211132674-c7f4900f-5cc8-4740-a7bd-00900f3889a6.png)
@Spacellary Did you change this value to off?

**Comment by Spacellary** [comment]
> Did you change this value to off?

Just for the screenshot! I've changed it to ON now and it's fine! Should have been more clear xD

**Comment by Spacellary** [comment]
I'm testing other fonts now! Seems promising!

**Comment by inotia00** [comment]
goood

**Comment by Spacellary** [comment]
The font "OpenSans" seemed to work almost perfectly too when applied and after toggling the separator on and off. But upon further examination, after restarting the it doesn't stay that way, it reverted to the ugly way like before for me. So I'll give this up for now, honestly as long as you can hide the separator (thanks again for the quick Patch!) I'm happy.
Of course, I share any news and I'm always available if testing is needed.
