### ISSUE TITLE
Original Name of the apk 'Youtube' is better

### ISSUE THREAD

**Issue by farhankzs** [inotia00/ReVanced_Extended#1010]
### Application

YouTube

### Description

After the latest version installed, the app name on my phone is now 'Revanced Extended' where till the last version (18.15.xx) was 'Youtube'.

Can I revert back to that name with the newer version of this beautiful apk? Please show me a way

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by kevinr99089** [comment]
It is a patch that changes the name or not, disable: custom-branding-name

**Comment by farhankzs** [comment]
Where to find custom branding name? How can I change it?
