### ISSUE TITLE
bug(protobuf-spoof): Subtitles appear at top when you watch related shorts

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1011]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.16.39
ReVanced Patches v2.173.6

### Bug description

This is a big issue if like me you have `Hide auto captions` enabled, but for simplicity I left the option disabled while taking the video (if enabled you wouldn't have had to manually hide and show the subtitles to reproduce the bug).

https://github.com/inotia00/ReVanced_Extended/assets/127908708/3c000426-7a7c-4628-9822-5edf9c3cc66b

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by itzaritrik** [comment]
My phone is also having this problem

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.173.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.10)
