### ISSUE TITLE
Feed stops loading new videos while scrolling down on home screen

### ISSUE THREAD

**Issue by rtsbora** [inotia00/ReVanced_Extended#1012]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

18.02.33

### Bug description

While i am scrolling down on my home screen, after about 100 videos, stops loading new video?

But it should continue to load new videos until i stop scroll.

Can you fix this problem? Or advice a solution? 

### Steps to reproduce

idk

### Relevant log output

```shell
?
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
v18.02.33 is an unsupported version
