### ISSUE TITLE
question: <title>: remove me (@shion_yorigami) aka fame as Revanced extended admins (including subgroup related to rvx (revancify, rvx lite, etc))

### ISSUE THREAD

**Issue by HoriKyoukosimp** [inotia00/ReVanced_Extended#1014]
### Application

Other

### Description

since my school session has started, and i have found my own interest, i will rarely active in telegram (like very rare) so i thought if i just remove myself as an admin would be the best to ignore telegram and all that

so please, do me a favor

thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Wrong place to report issue

Also I am not owner of Revancify, rvx lite channel
PM the owners of such channels

**Comment by HoriKyoukosimp** [comment]
sure thing.

**Comment by inotia00** [comment]
I'm really sorry to lose a manager as diligent as you

But of course, your circumstances are more important, so you can stop your manager activities

If you want to be a manager even later, please tell me again anytime

Thank you for being the manager until now
