### ISSUE TITLE
question: hiding parts of the video 

### ISSUE THREAD

**Issue by Jinadequate** [inotia00/ReVanced_Extended#1015]
### Application

YouTube

### Description

I don't know how to turn of this. I searched through all settings and there are some but just about adds. It often skips lots of important parts of the video if there's no music, or there is but it's first seconds of the video. And I can't find settings for that. Please help, that's annoying and I can't even go back to that moment that the app skipped. It doesn't let me. These moments usually marked with orange color. They're not remindings,  or adds, or sponsors, they're part of the video. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Hennadz** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1009#issuecomment-1544396590

**Comment by inotia00** [comment]
thanks
