### ISSUE TITLE
bug: in app video minimization is laggy with chapters

### ISSUE THREAD

**Issue by ankitxcoding** [inotia00/ReVanced_Extended#1016]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.17.43

### Bug description

When I play any video with chapters and chapters are shown below in portrait mode then minimization of that video seems laggy but this will not happen with description or comments on in portrait mode.

### Steps to reproduce

Step 1. Play any video that have chapters
Step 2. Tap on chapters
Step 3. Try to minimize that video as shown in video.

### Relevant log output

```shell
.
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/103440538/7a9ec081-b525-4bb0-b7e7-9078422ab388

### Device Environment

Realme UI 3.0 w/ Android 12
Patch v2.173.8
Revanced manager v1.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by BoysGmNg** [comment]
**Yes, it lags a lot for me.**

**Comment by inotia00** [comment]
This is a reproducible issue, but one that cannot be fixed
