### ISSUE TITLE
bug: <is laggy on minimization video>

### ISSUE THREAD

**Issue by BoysGmNg** [inotia00/ReVanced_Extended#1017]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.17.43

### Bug description

Bugs often occur, namely laggy in the process of playing videos and minimized the lag

When I play any video with chapters and chapters are shown below in portrait mode then minimization of that video seems laggy but this will not happen with description or comments on in portrait mode.

### Steps to reproduce

Step 1. Play any video that have chapters
Step 2. Tap on chapters
Step 3. Try to minimize that video as shown in video.

### Relevant log output

```shell
.
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/87355984/d6e1216d-5b6e-415b-9645-d3f2083e7a83

Help Please fix this.

### Solution

Improved optimization to make it lighter and not lag when minimizing

### Device Environment

Android 11, XOS Dolphin 7.6.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1016
