### ISSUE TITLE
feat(patch): disable long press to seek

### ISSUE THREAD

**Issue by Blueaulo** [inotia00/ReVanced_Extended#1018]
### Type

Cosmetic

### Tools used

Revancify

### Application

Youtube 18.17.43

### Bug description

First of all I would like to clarify that this bug happens to me since like one year, so also with other versions of yt and in the meanwhile I switched from revanced (using revanced manager), revanced extended(using the no_name apk) and revancify (patching witch extended). So this thing should appear when you click for a long time so you can drag and go forward, but my yt sometimes register a long touch(before using revanced it wouldn't do it) in videos but also in shorts, since I don't use shorts maybe I am doing something wrong but I don't think so, I also asked the revanced team on discord in the past but they told me that It was not a bug but a feature, and if this is the case I would like to request a feature to disable this thing

### Steps to reproduce

I am using all the recommended patches but the background on the video player buttons.
I also tried  to enable and disable press-to-swipe gesture, in the swipe controls category, but it really didn't do anything and I don't know what it does(this thing doesn't even tell me to restart when I click it like the other ones).
To reproduce the bug you just have to open a video or short, and it will appear, sometimes twice a video, sometime you can watch 2 videos without getting it, it's just random from what I cam tell

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping custom-branding-music-afn-blue: Excluded by default 
INFO: Skipping custom-branding-music-afn-red: Excluded by default 
INFO: Skipping custom-branding-music-mmt: Excluded by default 
INFO: Skipping custom-branding-music-name: Excluded by default 
INFO: Skipping custom-branding-music-revancify-red: Excluded by default 
INFO: Merging inotia00-integrations-v0.107.8.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: amoled succeeded 
INFO: background-play succeeded 
INFO: bitrate-default-value succeeded 
INFO: certificate-spoof succeeded 
INFO: custom-branding-music-revancify-blue succeeded 
INFO: custom-package-name succeeded 
INFO: disable-auto-captions succeeded 
INFO: enable-black-navbar succeeded 
INFO: enable-color-match-player succeeded 
INFO: enable-compact-dialog succeeded 
INFO: enable-force-minimized-player succeeded 
INFO: enable-force-shuffle succeeded 
INFO: enable-landscape-mode succeeded 
INFO: enable-opus-codec succeeded 
INFO: enable-zen-mode succeeded 
INFO: exclusive-audio-playback succeeded 
INFO: hide-button-shelf succeeded 
INFO: hide-carousel-shelf succeeded 
INFO: hide-category-bar succeeded 
INFO: hide-get-premium succeeded 
INFO: hide-music-ads succeeded 
INFO: hide-music-cast-button succeeded 
INFO: hide-new-playlist succeeded 
INFO: hide-playlist-card succeeded 
INFO: hide-taste-builder succeeded 
INFO: hide-upgrade-button succeeded 
INFO: minimized-playback-music succeeded 
INFO: music-microg-support succeeded 
INFO: music-settings succeeded 
INFO: optimize-resource-music succeeded 
INFO: remember-video-quality succeeded 
INFO: share-button-hook succeeded 
INFO: spoof-app-version succeeded 
INFO: translations-music succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Aligning YouTube-Music-6.01.55.apk to YouTube-Music-Revanced-Extended-6.01.55_aligned.apk 
INFO: Signing YouTube-Music-Revanced-Extended-6.01.55_aligned.apk to YouTube-Music-Revanced-Extended-6.01.55_signed.apk 
INFO: Found existing keystore: revancify.keystore 
INFO: Copying YouTube-Music-Revanced-Extended-6.01.55_signed.apk to YouTube-Music-Revanced-Extended-6.01.55.apk 
INFO: Cleaned up cache directory 
INFO: Finished 



Variant: nonRoot
Arch: arm64-v8a
App: YouTube-Music-6.01.55.apk
CLI: inotia00-cli-v2.21.2.jar
Patches: inotia00-patches-v2.173.8.jar
Integrations: inotia00-integrations-v0.107.8.apk
Patches argument: -i amoled
-i background-play
-i bitrate-default-value
-i certificate-spoof
-i custom-branding-music-revancify-blue
-i custom-package-name
-i disable-auto-captions
-i enable-black-navbar
-i enable-color-match-player
-i enable-compact-dialog
-i enable-force-minimized-player
-i enable-force-shuffle
-i enable-landscape-mode
-i enable-opus-codec
-i enable-zen-mode
-i exclusive-audio-playback
-i hide-button-shelf
-i hide-carousel-shelf
-i hide-category-bar
-i hide-get-premium
-i hide-music-ads
-i hide-music-cast-button
-i hide-new-playlist
-i hide-playlist-card
-i hide-taste-builder
-i hide-upgrade-button
-i minimized-playback-music
-i music-microg-support
-i music-settings
-i optimize-resource-music
-i remember-video-quality
-i share-button-hook
-i spoof-app-version
-i translations-music
```

### Screenshots or videos

![photo_2023-05-13_10-38-31](https://github.com/inotia00/ReVanced_Extended/assets/57272391/0f3188ac-c5f5-416a-b74d-4f8a01e3c375)

### Device Environment

Android 13, One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
yeah this is an official youtube feature

`patch-request` label is more appropriate for what you want, so I'll change it

**Comment by Blueaulo** [comment]
Ok and I get it, but it's a bug that this happens because as I said before it wasn't happening.
So my main priority is still remove this bug or help me figure out why this happen, but if we can't figure out what it's causing this to just remove this youtube feature at all so it doesn't show up even if I want to use it

**Comment by Blueaulo** [comment]
Ok and I get it, but it's a bug that this happens because as I said before it wasn't happening.
So my main priority is still remove this bug or help me figure out why this happen, but if we can't figure out what it's causing this to just remove this youtube feature at all so it doesn't show up even if I want to use it.
Because the thing is not that I long press and it show up, but that I just click the screen once for like see the timestamp or other thing but it show up this annoying menu.
I hope that I clarify what is the bug.

**Comment by Blueaulo** [comment]
Ok and I get it, but it's a bug that this happens because as I said before it wasn't happening.
So my main priority is still remove this bug or help me figure out why this happen, but if we can't figure out what it's causing this to just remove this youtube feature at all so it doesn't show up even if I want to use it.
Because the thing is not that I long press and it show up, but that I just click the screen once for like see the timestamp or other thing but it show up this annoying menu.
I hope that I clarify what is the bug.
