### ISSUE TITLE
bug: hide info cards patch not working

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#1019]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.17.43

### Bug description

revanced patches v2.173.8
bug: hide info cards does not work

### Steps to reproduce

enable hide info cards and play a video that contains info cards

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
![051400345729781](https://github.com/inotia00/ReVanced_Extended/assets/108592928/10cc31e2-8330-426a-98db-5d5ef25410ad)
seems to work fine

**Comment by BrilliantlyEducated** [comment]
> ![051400345729781](https://github.com/inotia00/ReVanced_Extended/assets/108592928/10cc31e2-8330-426a-98db-5d5ef25410ad)
> seems to work fine

still not working, try this video: https://youtu.be/SDuwmU1a1kY

**Comment by inotia00** [comment]
Even tested with that link, it works fine

**Comment by BrilliantlyEducated** [comment]
> Even tested with that link, it works fine

thank you for testing, do you have protobuf spoof patch on too?

**Comment by BrilliantlyEducated** [comment]
> Even tested with that link, it works fine
> Please attach a screenshot of your settings and a screenshot of your video

![IMG_1.jpg](https://github.com/inotia00/ReVanced_Extended/assets/36302515/5c37abe5-3916-4ef8-9678-65c28352e82a)

![IMG_2.jpg](https://github.com/inotia00/ReVanced_Extended/assets/36302515/9d5826ea-4b59-4144-a629-f5e3a2723bff)

![IMG_3.jpg](https://github.com/inotia00/ReVanced_Extended/assets/36302515/e3e5ff7b-07a3-495d-8a0b-62bddb67010b)

![IMG_4.jpg](https://github.com/inotia00/ReVanced_Extended/assets/36302515/9a0a044f-664e-459c-a953-cf91b863dd43)

**Comment by inotia00** [comment]
It's weird. Even if protobuf spoof is turned on, it hides normally.

Can you export the settings json and then upload it?

**Comment by BrilliantlyEducated** [comment]
> It's weird. Even if protobuf spoof is turned on, it hides normally.
> 
> Can you export the settings json and then upload it?

how can i upload a file here, how about i send you the file on Telegram but you have to unblock me first

**Comment by inotia00** [comment]
I'm really sorry, but... where can I see who I've blocked on Telegram?

**Comment by BrilliantlyEducated** [comment]
> I'm really sorry, but... where can I see who I've blocked on Telegram?

go to settings > privacy and security > blocked users

**Comment by BrilliantlyEducated** [comment]
> I'm really sorry, but... where can I see who I've blocked on Telegram?

i accepted your apology 💙 thank you

**Comment by inotia00** [comment]
ok I cleared the block list, send me a DM
