### ISSUE TITLE
feat(patch): custom-seekbar-color

### ISSUE THREAD

**Issue by Variables2000** [inotia00/ReVanced_Extended#102]
### Application

YouTube

### Issue

An extension of ```return-old-seekbar-color``` patch.

### Patch

The patch should add a new value to the options.toml called ```custom-seekbar-color``` which takes a hex value like ```#FFFFFFFF``` or ```#FF00FF80``` and uses it to change the seekbar color. It could alternatively be added in the Revanced settings Layout sections (when a value is added will promt the user to restart ytrvx).

### Motivation

The patch should adds more customizability to revanced and enhance material you patch in certain cases.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
already reflected
