### ISSUE TITLE
subscribe button bug: <title>

### ISSUE THREAD

**Issue by k50ab** [inotia00/ReVanced_Extended#1022]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

18.15.40

### Bug description

If you use the function, display the subscribe button. The subscription button disappears. The subscribe button appears.

### Steps to reproduce

If you use the function, display the subscribe button. The subscription button disappears. The subscribe button appears.

### Relevant log output

```shell
how to get a log?
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
A lot of explanation is missing
Please update with the latest resources and reopen the issue.

**Comment by k50ab** [comment]
I don't know what to write anymore. Let the mistake remain.

сб, 13 мая 2023 г., 18:11 inotia00 ***@***.***>:
