### ISSUE TITLE
bug: <Video Buffer on Wi-Fi>

### ISSUE THREAD

**Issue by WrongSmadi** [inotia00/ReVanced_Extended#1023]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.11.36

### Bug description

I was watching my videos as usual until one day the video started to buffer, usually at the 40 second mark. I tried to figure out what was the problem and then I noticed that it only happened when I was connected to the Wi-Fi and the app would work just fine when I used mobile data, which I found odd. The video would play just fine then it would hit the 40 second mark (with the occasional outliers never above 4 minutes) and the screen would buffer then turn black up until which the video just refused to play.

*I am not very tech savvy and the filling out instructions were a bit difficult to understand so I have no idea if I filled this out right or not so I hope I won't be dismissed to quickly because of such.

### Steps to reproduce

Step 1: Select random video over 40 seconds
Step 2: Play

### Relevant log output

```shell
N/A
```

### Screenshots or videos

I tried to attach a video of the screen recording but it wouldn't work

### Solution

N/A

### Additional context

There's not much to add context wise as this is a relatively recwnt development.

### Device Environment

Galaxy S20 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
You are using an outdated version
(Also this is an outdated issue)

Please patch again with the latest resources
