### ISSUE TITLE
feat(patch):  disable `default-video-speed` for category:music

### ISSUE THREAD

**Issue by NeeRaj-2401** [inotia00/ReVanced_Extended#1024]
### Application

YouTube

### Issue

I always use default video speed 1.75x.
But its annoying when i play some music categorised video.

I mean who listens music on 1.75x ?

### Patch

The existing `default-video-speed` should be modified to detect category: music

And do not apply speed on that thode videos

### Motivation

It will basically automate the process of changing video speed back to normal every time we start playing music video.

Or changing settings for short period of time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/267
