### ISSUE TITLE
question: how do I build revanced extended source code?

### ISSUE THREAD

**Issue by aryanmaulana7636** [inotia00/ReVanced_Extended#1025]
### Application

YouTube

### Description

I want to know how to build revanced extended source code

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's not clear what you're curious about

Are you curious about a guide to building patches (jar) or integrations (apk)?

Or are you curious about the build guide for the ReVanced Extended apk?

**Comment by aryanmaulana7636** [comment]
I'm building patches.

**Comment by aryanmaulana7636** [comment]
because I want add support youtube version.

**Comment by inotia00** [comment]
This is a guide that is not provided in my documentations.

But essentially it's the same build method as the official ReVanced patches, so read the [documentations](https://github.com/revanced/revanced-documentation/tree/main/docs/revanced-development)  provided by the ReVanced Team.
