### ISSUE TITLE
question: <title>: create pc app

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1027]
### Application

YouTube

### Description

Does youtube revanced extended is available for pc windows ? If not can you create in future ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
ReVanced Extended only supports Android environment
