### ISSUE TITLE
bug: ReVanced Manager v1.3.7 and v1.3.8 don't work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1028]
### Type

Other

### Tools used

ReVanced Manager

### Application

ReVanced Manager both v**1.3.7** and v**1.3.8**

### Bug description

After changing the patch source to _inotia00_ and restarting the manager app, the app doesn't open.

### Steps to reproduce

Explained in bug description,

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
> After changing the patch source to _inotia00_ and restarting the manager app, the app doesn't open.

Refer to this issue on the Revanced manager .

https://github.com/revanced/revanced-manager/issues/982
