### ISSUE TITLE
bug: ReVancify app builds an app named YouTube, making it impossible to install

### ISSUE THREAD

**Issue by S23u512** [inotia00/ReVanced_Extended#1031]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube 18.24.37
Patches: 2.181.1

### Bug description

Cleared patches options file, uninstalled my YouTube app and uninstalled Revancify (cleared cache and data too). And then reinstalled Revancify, but in some reason Revancify builds the app and names it as YouTube, it somehow ignores custom app name set in the options file.

This bug started today after the latest patch.

### Steps to reproduce

Build an apk in Revancify, notice how the app is named as YouTube, not how its set in the options file.

### Relevant log output

```shell
[patch_log.txt](https://github.com/inotia00/ReVanced_Extended/files/11958874/patch_log.txt)

```

### Screenshots or videos

![Screenshot_20230705_171933_Package installer](https://github.com/inotia00/ReVanced_Extended/assets/138691006/12efa98d-2a78-4ddd-adf0-4d0617cd1c52)

### Device Environment

Android 13, OneUI 5.1.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
According to the patch log, you excluded the `custom-branding-youtube-name` patch.
Include the `custom-branding-youtube-name` patch
