### ISSUE TITLE
bug: keeps aborting when patching using revanced manager

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1032]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

ReVanced Manager 1.3.6
YouTube v18.24.37
ReVanced Patches v2.181.1

### Bug description

It keeps aborting when I try to patch.

![Screenshot_20230705_153721](https://github.com/inotia00/ReVanced_Extended/assets/127908708/9af1e59d-8572-407a-a942-5e1d015e16bf)

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Reiux** [comment]
The same thing happened to me but I got a sponsorblock error patch after that AbstractMethodError.

**Comment by KobeW50** [comment]
Same abort error as OP when patching 18.23.36 on manager 1.3.6

**Comment by KobeW50** [comment]
The exact same error also occurs for YTM and Reddit (versions 6.07.51, and 2023.21.0).

**Comment by inotia00** [comment]
I've released a manager compatible with my patch, so I'm closing the issue
https://github.com/inotia00/revanced-manager/releases/tag/v1.3.8
