### ISSUE TITLE
bug: `hide-shorts-component` patch does not hide shorts header

### ISSUE THREAD

**Issue by S23u512** [inotia00/ReVanced_Extended#1034]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.24.37
Patches 2.181.1

### Bug description

I dont know how I got this unclickable button there, check the screenshot. This bug started after 2.181.1 patch.

### Steps to reproduce

Maybe I got it by enabling/disabling tablet mode, Im not sure.

### Relevant log output

```shell
[patch_log.txt](https://github.com/inotia00/ReVanced_Extended/files/11958874/patch_log.txt)
```

### Screenshots or videos

![Screenshot_20230705_181740_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/138691006/15758229-439b-408e-8750-4c921930afde)

### Solution

When I turn tablet mode on it hides this button, when turned off it comes back.

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by S23u512** [comment]
You can close this bug if you want, Im not sure if this was an AB test or just a glitch in the matrix, but repatch/reinstall fixed it.

**Comment by inotia00** [comment]
Weird but... I got it
