### ISSUE TITLE
Revanced manager patching error

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1035]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube 18.24.37

### Bug description

It gives an error after almost applying all patches.

### Steps to reproduce

1. Open revanced manager
2. Select YouTube application
3. Select patches and start patching 

### Relevant log output

```shell
Applied hide-mix-playlists
Applied hide-music-button
Applied hide-navigation-buttons
Applied hide-navigation-label
Applied hide-pip-notification
Applied hide-player-button-background
Applied hide-player-flyout-panel
Applied hide-player-overlay-filter
Applied hide-previous-next-button
Applied hide-quick-actions
Applied hide-seek-message
Applied hide-seekbar
Applied hide-shorts-component
Applied hide-snack-bar
Applied hide-speed-overlay
Applied hide-suggested-actions
Applied hide-suggestions-shelf
Applied hide-time-stamp
Applied hide-tooltip-content
Applied hide-trending-searches
Applied hide-video-ads
Applied language-switch
Applied layout-switch
Applied materialyou
Applied microg-support
Applied optimize-resource
Applied overlay-buttons
Applied return-youtube-dislike
Applied settings
Applied sponsorblock
Applied spoof-app-version
Applied swipe-controls
Applied theme
Applied translations
An error occurred! Aborted
Error:
java.lang.AbstractMethodError: abstract method "void app.revanced.patcher.patch.Patch.close()"
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:368)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

![Screenshot_2023-07-05-20-29-34-330_app revanced manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/483757e8-d4ea-42d0-ab2c-d9affe556d3a)

### Solution

I don't know

### Additional context

I'm using Xiaomi 11T pro if it helps in any way 

### Device Environment

Android 13 MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by sssh7710** [comment]
I'm annoyed because I have the same symptoms

**Comment by sssh7710** [comment]
![Screenshot_20230706_003353](https://github.com/inotia00/ReVanced_Extended/assets/98168192/ccb6c3fc-3f5d-4b7f-8851-274b5e00c256)
[revanced-manager_patcher_20230706003408852188.log](https://github.com/inotia00/ReVanced_Extended/files/11959745/revanced-manager_patcher_20230706003408852188.log)
I'll attach the data, too

**Comment by sssh7710** [comment]
> Hopefully it gets fixed soon by inotia00. Till then, I'll be using revancify to build revanced extended and you also probably should give it a try as it gives no such errors.
> @sssh7710 

What is revampify?

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1032

**Comment by Adity1243** [comment]
Mine is worked with revanced manager v1.3.8 with youtube v18.20.39 but i didnt got revanced extended settings, i got general youtube revanced settings.

**Comment by KobeW50** [comment]
> Mine is worked with revanced manager v1.3.8 with youtube v18.20.39 but i didnt got revanced extended settings, i got general youtube revanced settings.

Your sources were set the regular ReVanced sources. It's impossible to set them to a custom source due to a bug.

**Comment by Adity1243** [comment]
How to patch extended version then ?

**Comment by KobeW50** [comment]
> How to patch extended version then ?

Currently there are issues with the Manager, so check the documentation for other patching methods (revanced builder, revancify, and clil

https://github.com/inotia00/revanced-documentation

**Comment by Adity1243** [comment]
I did with inotia build and i also got aborted issue it patched succesfully everything that i selected, it seem like there was a problem in building and signing apk file.
