### ISSUE TITLE
bug: `compact controls overlay` causes horizontal cropping of player settings in full-screen

### ISSUE THREAD

**Issue by anil-al** [inotia00/ReVanced_Extended#1036]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube 18.24.37 with the last patch 

### Bug description

In tablet, after opening a video full-screen, video player elements get cropped. This does not occur while opening the programme in multi-window.

### Steps to reproduce

- Switch on `compact controls overlay` patch

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20230705_182157_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/101948963/e73eb585-2124-43bc-b890-4298cac27b48)
![Screenshot_20230705_182418_YouTube Music](https://github.com/inotia00/ReVanced_Extended/assets/101948963/c6068fc4-951b-4314-bcf9-80e0e5ca7b04)
![Screenshot_20230705_183402_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/101948963/7733ca59-aa6e-4828-8985-ad69c9b8904b)

### Solution

-

### Device Environment

Android 13, Samsung Tab S8+

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
You are using Experimental Flags
