### ISSUE TITLE
Bottom player button container bug

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1039]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.24.37

### Bug description

Occasionally shows empty button containers after clicking on other buttons like download.

### Steps to reproduce

1. Play any video inside revanced extended
2. Click on any button on bottom container of the video player

### Relevant log output

```shell
No relevant logs
```

### Screenshots or videos

![Screenshot_2023-07-05-22-40-12-871_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/1a5a7f47-4478-4f3b-a381-22e0069c364e)

### Solution

Remove the user selected buttons altogether at all times (?)

### Additional context

Using Xiaomi 11T pro

### Device Environment

Android 13 MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by S23u512** [comment]
#1033

**Comment by Rairof** [comment]
@S23u512 are you sure it's the same issue?

**Comment by Rairof** [comment]
Alright then. Closing this post.
