### ISSUE TITLE
bug: Hide Create Button Failed to apply

### ISSUE THREAD

**Issue by giwrgosmant** [inotia00/ReVanced_Extended#104]
### Type

Error while patching

### Application

YouTube 18.01.32

### Bug description

Hide Create Button failed to apply in patches.

### Steps to reproduce

Include Hide Create Button in patches, while building in manager it will show an error.

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_ReVanced_Extended_Patching_Create Button](https://user-images.githubusercontent.com/51835189/210769293-4e44b182-a719-41e6-8293-653769fd1f81.jpg)

### Device Environment

Android 13, crDroid ROM

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/103
