### ISSUE TITLE
bug(sponsorblock): skip button appears on the screen

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#1040]
### Type

Error at runtime

### Tools used

CLI

### Application

Latest patches and youtube 

### Bug description

When returning to the app, when the video is running offscreen, if you skip forward or backward, the sponsorblock button appears on the screen for no reason 

### Steps to reproduce

1. Run a video
2. Minimize the app while the video keeps running
3. Open the app again
4. Skip backwards of forward
5. The sponsor button appears 

### Relevant log output

```shell
----
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
In [revanced-patches-2.190.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.4), SponsorBlock related code has been refactored.

Please re-patch with revanced-patches-2.190.4 and check if the issue still persists.

**Comment by inotia00** [comment]
After using it for a few days, it seems to have been fixed in the latest patches.
Close the issue.
