### ISSUE TITLE
bug(enable-tablet-mini-player): some space when minimized

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1042]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.24.37

### Bug description

Leaves a little gap on the right side of the tablet miniplayer. Nothing app breaking but annoying to look at.

### Steps to reproduce

1. Build revanced extended with tablet miniplayer patch applied
2. Enable it in revanced extended settings inside the app
3. Click on any video and minimise

### Relevant log output

```shell
No relevant logs
```

### Screenshots or videos

![Screenshot_2023-07-05-23-46-29-985_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/62ff0e75-cbc8-4b29-89bf-e58f8d7ca14c)

### Solution

Move miniplayer to furthest right side flush with the right side.

### Additional context

Using Xiaomi 11T pro phone

### Device Environment

Android 13 MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by anil-al** [comment]
This is the normal appearance of mini player. It is like that in tablet layout as well.

**Comment by inotia00** [comment]
I didn't know that because I rarely use a tablet.
Thank you for letting me know

**Comment by Rairof** [comment]
Oh I also didn't knew that but it doesn't exist on older revanced extended tablet miniplayer and vanced tablet miniplayer patches though

**Comment by Rairof** [comment]
> This is the normal behaviour of mini player. It is like that in tablet layout as well.

It's not a issue with older revanced and vanced app though 
![Screenshot_2023-07-06-09-40-25-856_com vanced android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/0b6172c2-95a6-4958-9be3-9b5b33ae902e)

**Comment by anil-al** [comment]
> > This is the normal behaviour of mini player. It is like that in tablet layout as well.
> 
> It's not a issue with older revanced and vanced app though @inotia00 
> ![Screenshot_2023-07-06-09-40-25-856_com vanced android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/0b6172c2-95a6-4958-9be3-9b5b33ae902e)
> 

YouTube changed mini player design recently in a couple of months ago, that's why the space doesn't exist in older version.

**Comment by Rairof** [comment]
> > > This is the normal behaviour of mini player. It is like that in tablet layout as well.
> > 
> > 
> > It's not a issue with older revanced and vanced app though @inotia00
> > ![Screenshot_2023-07-06-09-40-25-856_com vanced android youtube-edit](https://user-images.githubusercontent.com/107706560/251339748-0b6172c2-95a6-4958-9be3-9b5b33ae902e.jpg)
> 
> YouTube changed mini player design recently in a couple of months ago, that's why the space doesn't exist in older version.

So then a patch to revert back to old mini player design would solve it
