### ISSUE TITLE
Fullscreen player UI misaligned

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1043]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.24.37

### Bug description

The full-screen player goes too much further towards the centre and further from the edges of the screen making it prone to miss swipes and make it look claustrophobic and annoying. It would  be good to make the whole UI fit the whole screen rather then be fixed in a certain size.

### Steps to reproduce

1. Build revanced extended
2. Have relevant patches applied and enabled
3. Watch any video in fullscreen

### Relevant log output

```shell
No relevant logs
```

### Screenshots or videos

![Screenshot_2023-07-05-23-58-28-922_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/30e666bb-801c-49c2-8f69-87dee8ece017)

### Solution

Make the full screen player UI automatically fit the phone screen size.

### Additional context

Using Xiaomi 11T pro phone still.

### Device Environment

Android 13 MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/271
