### ISSUE TITLE
feat(patch): Unlock 'Play next in queue' feature

### ISSUE THREAD

**Issue by nochlab1** [inotia00/ReVanced_Extended#1046]
### Application

YouTube

### Issue

Unlock Premium Only feature of "Play next in queue" available on YouTube
& it can be seen on both YouTube OG & Revanced.
(I opened a request in November to unlock it when it was in testing but now its fully rolled out)

### Patch

Make the feature work even without premium

### Motivation

It is very useful

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Windows YouTube client and iOS YouTube client developers also tried to implement this, but without success.

It's a feature that heavily relies on the server side.
Therefore, it is a function that cannot be implemented.

**Comment by nochlab1** [comment]
on windows its free so it works

ok thanks
