### ISSUE TITLE
bug: `custom video speed` patch does not work in new layout

### ISSUE THREAD

**Issue by anil-al** [inotia00/ReVanced_Extended#1048]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube 18.24.37 with the latest patch

### Bug description

Custom video speed patch won't be applied whether it has default values or edited through its sub-setting. Edit: Obviously, it is mentioned in the changelog but will it be possible to apply it to the new flyout menu?

### Steps to reproduce

Enable `custom video speed` patch in settings.

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20230706_001536_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/101948963/7e77d20e-4639-4f61-ad3a-0c42af7c7a79)

### Device Environment

Android 13, Samsung Tab S8+

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
This issue is already noted in the patch release changelog.

**Comment by anil-al** [comment]
> This issue is already noted in the patch release changelog.

Thank you for reminding me, I forgot it. If inotia00 wish, it could be closed or stay for future reference to others.

**Comment by anil-al** [comment]
Apparently, it was mentioned that the old flyout panel was applied as a workaround for that, yet I haven't find a way to turn it on.

**Comment by KobeW50** [comment]
> Apparently, it was mentioned that the old flyout panel was applied as a workaround for that, yet I haven't find a way to turn it on.

I think v18.20.39 was added as a spoof option for this

**Comment by inotia00** [comment]
Fix is permanently impossible in the new layout

This is already mentioned in the release notes.

If you need it, spoof the app version as YouTube v18.20.39
