### ISSUE TITLE
bug: `old style quality layout` patch does not work

### ISSUE THREAD

**Issue by anil-al** [inotia00/ReVanced_Extended#1049]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube 18.24.37 with the latest patch

### Bug description

Enabling `old style quality layout` still calls the new style quality menu. If it is possible, can you fix it in a way that it will preserve the design and place of the new flyout menu instead of calling the menu coming from the bottom of the screen?

### Steps to reproduce

-

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20230706_003508_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/101948963/d5bc0422-2216-4c24-b64a-ecdf7f68d4bd)

### Device Environment

Android 13, Samsung Tab S8+

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Same as previous issue
Spoof the app version as v18.20.39

**Comment by anil-al** [comment]
> Same as previous issue
> Spoof the app version as v18.20.39

I thought patching this would be possible since there would not be any modification of the components of the menu unlike that in custom speed patch, and just skipping a menu and calling its sub-menu instead.
