### ISSUE TITLE
Doesn't show recommended version as v18.01.32

### ISSUE THREAD

**Issue by stillrinzler** [inotia00/ReVanced_Extended#105]
### Type

Error while patching

### Application

YouTube v18.01.32

### Bug description

I have imported the lastest patches which is V2.152.4 but when I'm about to patch the app, it shows the recommended version as v17.49.37 instead of v18.01.32

### Steps to reproduce

Steps
Select patcher and then click on the yt to patch, recommended and currect version will be shown where the recommended version is bugged 

### Relevant log output

```shell
There is no log output for this i suppose
```

### Screenshots or videos

![Screenshot_20230105-165645_ReVanced_Manager](https://user-images.githubusercontent.com/104838959/210769964-b30b8797-3720-4f9b-b924-a0732a6b9e00.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Perhaps, it's an issue with ReVanced Manager

This issue I can't fix for the following reasons:

1. I am not a maintainer of ReVanced Manager

2. ReVanced Manager is 'compatible' with my patch, not all features are supported
(For example, ReVanced Manager does not support editing `options.toml`)

For this reason, I cannot fix any issues related to ReVanced Manager

The method I recommend is to build using rvx-builder

**Comment by stillrinzler** [comment]
Ohh okay. Thanks 👍
