### ISSUE TITLE
feat(patch): Play Store links from YouTube to go directly into play store

### ISSUE THREAD

**Issue by Ahmadsha007** [inotia00/ReVanced_Extended#1050]
### Application

YouTube

### Issue

a very annoying and stupid issue from the side of google.

### Patch

Currently Play Store Links from YouTube Description Goes To Browser which is the default behaviour of YouTube i think,  it would be incredibly useful for anyone to those links to go directly into the appropriate app which is play store.

### Motivation

it's incredibly useful. would be a godsend if happened.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Since this is a part related to Android policy, it is impossible to patch in the app

Just register the YouTube native app as RVX
