### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by MaksNPC** [inotia00/ReVanced_Extended#1051]
### Application

YouTube

### Issue

The device has a light theme but the YouTube player shows a dark one

### Patch

https://github.com/inotia00/ReVanced_Extended/assets/55586822/badcc89d-a852-491a-a99b-701a4d26f4bf

### Motivation

This is a bug

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's a YouTube bug, not a bug in ReVanced Extended.
Report to Google
