### ISSUE TITLE
bug: the button container setting in the bottom menu of the player does not work.

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/ReVanced_Extended#1053]
### Type

Error while patching

### Tools used

rvx-builder

### Application

In the updated patch for 18.24.37

### Bug description

In the updated patch for 18.24.37, the button container setting in the bottom menu of the player does not work.  (turning off offline storage, etc.)

### Steps to reproduce

done

### Relevant log output

```shell
done
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1033
