### ISSUE TITLE
feat(patch): search functionality for ReVanced Extended Settings

### ISSUE THREAD

**Issue by kazimmt** [inotia00/ReVanced_Extended#1054]
### Application

YouTube

### Issue

There are lots of feature available for YouTube ReVanced Extended under 13 categories. Sometimes it's hard to find the correct settings for any patches for new users.

### Patch

A patch that adds search option inside ReVanced Extended Settings to find any setting easily.

### Motivation

Now it's like 100 features available in RVX. This option will make it easier to find settings for any RVX features.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/83
