### ISSUE TITLE
bug: Patch "Hide preview comment" Cant change to live comments

### ISSUE THREAD

**Issue by nochlab1** [inotia00/ReVanced_Extended#1055]
### Type

Cosmetic

### Tools used

CLI

### Application

Youtube v18.24.37

### Bug description

When enabling Patch "Hide preview comment" there is no way to switch between live comments and regular commnts

### Steps to reproduce

Step 1. enable Patch "Hide preview comment"
Step 2. go to video that was live and try accessing live comments

### Relevant log output

```shell
N/A
```

### Additional context

(This was broken for a long time just only encountered it recently)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1021
