### ISSUE TITLE
bug: Exported settings cannot be imported back

### ISSUE THREAD

**Issue by dumbdeniz** [inotia00/ReVanced_Extended#1056]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.24.37

### Bug description

I couldn't import my settings again after doing a clean install, turns out even exported settings on the latest version cannot be imported again, as they're grayed out.

Also on the older version, there was a bug that when you were to modify the files in any way, like moving them to a computer and back, they would not be recognized by the app. (same issue with grayed out files, but worked for newly exported - non-touched files)

### Steps to reproduce

Step 1. Export settings and close the app
Step 2. Re-open the app and try to import the settings (the file will be grayed out)

-- OTHER BUG --

Step 1. Export settings and close the app
Step 2. Move the exported json file directly (without zip) to another device by any means. (Neaby Share, Bluetooth, USB etc.)
Step 3. Move the file back to the phone and try to import it.

### Relevant log output

```shell
no logs
```

### Screenshots or videos

![Screenshot of the import file dialog, showing the bottom 2 settings files grayed out.](https://github.com/inotia00/ReVanced_Extended/assets/77262340/bef20ee6-0322-48ba-97ea-5adbffecfd1f)

### Solution

The code behind it doesn't look like there's anything wrong, so i'm guessing this is a bug with the built-in filepicker, or the file writing process.

To fix it, the mime type of the file could be set to "\*/\*" to allow all files. then the file validation could just be made simple as .endswith(".json") inside the onActivityResult() function.

Other solution is a seperate pop-up menu where we could type the filepath of the .json file we want to import.

### Device Environment

Android 9, OneUI 1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
The attached screenshot does not seem to be the Android default Storage Access Framework

Since the import and export process is designed based on Android's default Storage Access Framework, it is not guaranteed to work with other file manager apps

**Comment by dumbdeniz** [comment]
Im not %100 sure but it seems like it's the default Android 9 storage app

![SmartSelect_20230706-070026_Settings](https://github.com/inotia00/ReVanced_Extended/assets/77262340/266c0b7c-c794-43c2-beb0-4c4837835b5b)

I'm confused, does google's own storage app don't work with their own storage framework??

**Comment by inotia00** [comment]
nah.. that's the default SAF

It's been about 4 years since I used Android 9, so I think I'm confused

As you said, setting all filenames as targets might fix the issue.

The code is too complex to handle exceptions when a file other than json is imported, so I just want to keep the current method.

**Comment by dumbdeniz** [comment]
i just had another idea while importing sponsorblock settings, there can also be a second compatibility option showing a textbox popup where we paste the settings as json, like the sponsorblock one. If eveything else fails or doesn't work, that won't.

**Comment by inotia00** [comment]
Implementing that task requires code refactoring
It's difficult right now, but it seems to be implemented within a year

**Comment by dumbdeniz** [comment]
in that case allowing all filenames is a better fix for now

**Comment by Adity1243** [comment]
Mine is worked importing my settings my device is miui and i imported seetings via system files app.

**Comment by S23u512** [comment]
Mine worked correctly, export/import worked flawlessly.

This is on Android 13 / OneUI 5.1, samsung stock file app.

**Comment by dumbdeniz** [comment]
I can confirm setting the mime type to "\*/\*" fixed both the issue of not able to select & transferring to other devices

![Screenshot_20230707-162614_Files](https://github.com/inotia00/ReVanced_Extended/assets/77262340/ed5b278e-2857-4c6d-8553-94895c310672)

**Comment by odkate** [comment]
> mime type to "*/*"

Do you mean in the public.xml file?

**Comment by dumbdeniz** [comment]
> Do you mean in the public.xml file?

No, in the RevancedSettingsFragment.java file, the code calls for the built-in android filepicker with "application/json" mime type, but this is bugged on Android 9 (could also affect older & newer versions) which don't let you select the .json files.

I made a fork to test it out, calling the filepicker with "\*/\*" as mime type does fix it. The real implementation can be wrapped in an SDK version check for non-affected versions.

https://github.com/inotia00/revanced-integrations/commit/05f6c731b7d714db60d18521504777e9a9e6ee6a

**Comment by dumbdeniz** [comment]
I could've just submitted a PR this whole time
