### ISSUE TITLE
Whitelist With YouTube API v2

### ISSUE THREAD

**Issue by MaxCarthy** [inotia00/ReVanced_Extended#1057]
Both YouTube Vanced and ReVanced Extended use YouTube API v1

but YouTube API v1 was completely discontinued 3 years ago, and the API server was also closed a few days ago.
because of this, channel information can no longer be retrieved.

I have confirmed that the whitelist feature no longer works on YouTube Vanced too

Since YouTube API v2 requires a special token to access the API, we cannot use the same method as before.

If there doesn't seem to be a specific solution, I'll remove the whitelist patch

_Originally posted by @inotia00 in https://github.com/inotia00/ReVanced_Extended/issues/918#issuecomment-1529208128_

is there a way we can add our own token in options file when building the app?

**Comment by inotia00** [comment]
Unfortunately, the whitelist implementation has been abandoned.

Even if it could be implemented via the YouTube API v2, I don't plan to implement it again.

Use another YouTube client that comes with that feature.
