### ISSUE TITLE
feat(patch): external downloads

### ISSUE THREAD

**Issue by MoTem** [inotia00/ReVanced_Extended#1058]
### Application

YouTube

### Issue

It's in the base revamced but not in extended 

### Patch

Ability to download from downloaders like seal

### Motivation

To download videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I couldn't understand because of the lack of explanation
please add content

ReVanced Extended already offers the ability to download Seals

**Comment by MoTem** [comment]
Revanced doesnt allow me to change the default downloader from YTDL to something else like Seal (https://github.com/JunkFood02/Seal). This is a feature in the main branch called "external downloads" but is missing in the latest version. If memory serves me correctly, the last version of revanced extended did have this patch but it is gone now in the recent 2 versions.

**Comment by MoTem** [comment]
Closed accidentally

**Comment by MoTem** [comment]
My bad, thanks for pointing it out. And glad to have you back on the fork.
