### ISSUE TITLE
bug: custom branding icon patch applies even when excluded in YouTube Music 

### ISSUE THREAD

**Issue by blacktornadog7** [inotia00/ReVanced_Extended#1059]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube Music 6.08.50

### Bug description

custom branding icon patch (revancify blue to be exact) applies even when its excluded in YouTube Music when patching.
(I dont think this matters but i have custom-branding-music-name enabled)

### Steps to reproduce

1. only exclude custom branding icon patches when patching (custom-branding-icon-mmt, custom-branding-icon-revancify-blue, custom-branding-icon-revancify-red) ***(i also have custom-branding-music-name enabled)***
2. patch

### Relevant log output

```shell
No relevant log output
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Do you have a `branding` or `branding-music` directory in your path where the CLI is located?

**Comment by blacktornadog7** [comment]
I dont use CLI directly I actually use [this](https://github.com/blacktornadog7/ReVanced-Extended-APKs) (my fork) which is a fork of [this](https://github.com/NoName-exe/revanced-extended) which is a fork of [this](https://github.com/j-hc/revanced-magisk-module) which uses CLI to build the apks 
here is the raw build [logs](https://pipelines.actions.githubusercontent.com/serviceHosts/cede8d03-382d-452f-850e-4bc22de29687/_apis/pipelines/1/runs/109/signedlogcontent/9?urlExpires=2023-07-06T07%3A16%3A45.1599809Z&urlSigningMethod=HMACV1&urlSignature=o1lY8kgeO71cmkgz%2BzdoMKipkuTCNNjkTz78o0jOdzs%3D) 
you check them out also [here](https://github.com/blacktornadog7/ReVanced-Extended-APKs/actions/runs/5471975309/jobs/9963644014) "the relevant section would be Build modules/APKs"

**Comment by inotia00** [comment]
If you don't follow the guide provided by the documentations, I can't help you.
If you patch with the CLI method, please attach the patch log, not the Github Actions log.

**Comment by blacktornadog7** [comment]
sorry I'm a certified idiot, its not problem with CLI.
