### ISSUE TITLE
feat(patch): MicroG patch for Google Photos

### ISSUE THREAD

**Issue by xAffan** [inotia00/ReVanced_Extended#1061]
### Application

mMicroG

### Issue

With microG patch, https://github.com/revanced/revanced-patches/issues/2144 this would be possible. Allowing you to upload media unlimited WITHOUT ROOT.

### Patch

MicroG support for google photos, and optionally the patch linked above.

### Motivation

It will allow people to backup their media for free (unlimited) without root.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Shubhamkr4** [comment]
Still no response.
Although If the devs found a way, this would be a hit

**Comment by xAffan** [comment]
It's possible but somehow not the priority for revanced project.

**Comment by N0tAvai1able** [comment]
Hey devs, i just want to ask. Is this hard to do or just way too risky and may put the project in jeopardy?

**Comment by inotia00** [comment]
yeah.. contact the ReVanced Team

**Comment by N0tAvai1able** [comment]
> yeah.. contact the ReVanced Team

How exactly do i do this?
