### ISSUE TITLE
bug: Clicking video title to hide it makes video description to expand automatically

### ISSUE THREAD

**Issue by S23u512** [inotia00/ReVanced_Extended#1062]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.25.39
Patches 2.181.4

### Bug description

Clicking video title to hide it makes video description to expand automatically.

Check the screenshot, I took it after I backed out of fullscreen.

### Steps to reproduce

Make sure you have Show Fullscreen Title patch enabled, open a video and watch in fullscreen. Click the video title to hide it, back out of fullscreen and notice how video description is expanded.

### Relevant log output

```shell
[patch_log.txt](https://github.com/inotia00/ReVanced_Extended/files/11968859/patch_log.txt)

```

### Screenshots or videos

![Screenshot_20230706_164053_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/138691006/c06e97c7-a2e6-4623-8126-c924a89e3ef3)

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
This is the intended behavior. It is the same in the official app.
