### ISSUE TITLE
Anyways to disable this hold to seek?

### ISSUE THREAD

**Issue by User-noob2036876** [inotia00/ReVanced_Extended#1063]
### Application

YouTube

### Description

This feature is unnecessary;
![Screenshot_20230706-165537_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/117031829/db081c09-56b8-4862-a43b-747acf6c6d68)
Slide to seek. If we accidentally press and hold the screen, the video goes from start to finish etc. if we enable hide-seekbar patch slide to seek feature does not turn off.
This patch should be developed. I think.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by S23u512** [comment]
#711

**Comment by KobeW50** [comment]
Include the `Hde-message-seek` patch.

**Comment by KobeW50** [comment]
> > Include the `Hide-message-seek` patch.
> 
> ![Screenshot_20230706-195508_ReVanced Extended.jpg](https://github.com/inotia00/ReVanced_Extended/assets/117031829/25aca375-3c9b-4239-9a71-5404b8d9dd42)
> 
> 

Enable the setting in Settings > Revanced Extended > Player > Hide seek message.

**Comment by User-noob2036876** [comment]
> > > Include the `Hide-message-seek` patch.
> > 
> > 
> > ![Screenshot_20230706-195508_ReVanced Extended.jpg](https://user-images.githubusercontent.com/117031829/251519223-25aca375-3c9b-4239-9a71-5404b8d9dd42.jpg)
> 
> Enable the setting in Settings > Revanced Extended > Player > Hide seek message.
> 
> Close this issue if this solves it.

I found it but it hides only message
Seek still works
![Screenshot_20230706-201142_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/117031829/14078fac-c3c7-4441-8795-d10b54744e26)

**Comment by KobeW50** [comment]
> > > > Include the `Hide-message-seek` patch.
> > > 
> > > 
> > > ![Screenshot_20230706-195508_ReVanced Extended.jpg](https://user-images.githubusercontent.com/117031829/251519223-25aca375-3c9b-4239-9a71-5404b8d9dd42.jpg)
> > 
> > Enable the setting in Settings > Revanced Extended > Player > Hide seek message.
> > 
> > Close this issue if this solves it.
> 
> I found it but it hides only message
> Seek still works
> ![Screenshot_20230706-201142_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/117031829/14078fac-c3c7-4441-8795-d10b54744e26)
> 

My apologies. I misunderstood the issue.
