### ISSUE TITLE
question: <title>:Microg Patch dependencies

### ISSUE THREAD

**Issue by Hennadz** [inotia00/ReVanced_Extended#1064]
### Application

YouTube

### Description

Hi all.
Noticed a couple of patches being applied even if not selected.
spoof-app-version and custom-package-name.
I use Revancify.
In the support chat, they told me that these are dependencies on the Microg support patch. Previously, there were no problems with the selection of these items.
I have not come across any mention of this.
Is this a bug or a feature?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The `microg-support` patch contains a process that changes the app's package name.
So, including the `microg-support` patch also includes the `custom-package-name` patch

Issue with `old-quality-layout` patch and `custom-video-speed` patch not working on tablet devices

To solve this, I recommend using the `spoof-app-version` patch to spoof the app version to v18.20.39.

For this reason, if you include the `old-quality-layout` patch or `custom-video-speed`, the `spoof-app-version` patch is included.
