### ISSUE TITLE
question: <title>: why is there no setting when patching the root version via termux?

### ISSUE THREAD

**Issue by odkate** [inotia00/ReVanced_Extended#1065]
### Application

YouTube

### Description

For some reason, the "Spoofs player parameters to prevent playback issues" item is not in the settings when patching through Termux. Is the spoof-player-parameters patch included in any patch that is related to the microg version?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
It is in the MicroG Support patch.

**Comment by odkate** [comment]
> The patch is in the MicroG Support patch.

Why did to combine them? The root version also has problems with buffering
