### ISSUE TITLE
bug(reddit/hide-navigation-buttons): buttons are not hidden

### ISSUE THREAD

**Issue by leagueofperez** [inotia00/ReVanced_Extended#1068]
### Type

Error while patching

### Tools used

CLI

### Application

Reddit 2023.26.0

### Bug description

Patched Reddit with latest cli, patches and integrations, applied patches successfully but when i open reddit app the chat, create and discover button still showing
All other patches are working fine

### Steps to reproduce

- Download all necessary files
  - [com.reddit.frontpage.2023.26.0.apk](https://www.apkmirror.com/apk/redditinc/reddit/reddit-2023-26-0-release/reddit-2023-26-0-2-android-apk-download/)
  - [revanced-cli-2.21.6-all.jar](https://github.com/inotia00/revanced-cli/releases/download/v2.21.6/revanced-cli-2.21.6-all.jar)
  - [revanced-integrations-0.111.4.apk](https://github.com/inotia00/revanced-integrations/releases/download/v0.111.4/revanced-integrations-0.111.4.apk)
  - [revanced-patches-2.181.4.jar](https://github.com/inotia00/revanced-patches/releases/download/v2.181.4/revanced-patches-2.181.4.jar) 
- patch reddit apk with all patches enabled
  - `java -jar revanced-cli-2.21.6-all.jar -a com.reddit.frontpage.2023.26.0.apk -b revanced-patches-2.181.4.jar -m revanced-integrations-0.111.4.apk -o revanced-extended-reddit.apk`
- install apk

### Relevant log output

```shell
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Merging revanced-integrations-0.111.4.apk
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: disable-screenshot-popup succeeded
INFO: hide-ads succeeded
INFO: hide-chat-button succeeded
INFO: hide-create-button succeeded
INFO: hide-discover-button succeeded
INFO: open-links-directly succeeded
INFO: open-links-externally succeeded
INFO: premium-icon-reddit succeeded
INFO: reddit-settings succeeded
INFO: sanitize-sharing-links succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Aligning com.reddit.frontpage.2023.26.0.apk to revanced-extended-reddit_aligned.apk
INFO: Signing revanced-extended-reddit_aligned.apk to revanced-extended-reddit_signed.apk
INFO: Copying revanced-extended-reddit_signed.apk to revanced-extended-reddit.apk
INFO: Finished
```

### Screenshots or videos

| home                                                                                                       | settings                                                                                                        |
| ----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------- |
| ![home](https://github.com/inotia00/ReVanced_Extended/assets/51286451/907b5568-433b-4899-ae33-fad906555de0) | ![settings](https://github.com/inotia00/ReVanced_Extended/assets/51286451/eec7813f-d5cf-4c21-8af8-aeab96ce19ff) |

### Device Environment

# Phone
- Android 12
- MIUI 14.04 Global Stable

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
They are hidden "only when options.json values are specified..."

You can see more context in the [patch release notes](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.4).

However, I am unsure what the value should be. You can check out #1067 to see my misunderstanding/issue.

**Comment by leagueofperez** [comment]
The release notes mentions that revanced settings must be enabled in options.json, but doesn't mentions you need to change options.json to hide those buttons

I've changed options.json to enable revanced settings, but i don't know what do I need to change to hide those buttons
```
{
  "patchName" : "reddit-settings",
  "options" : [ {
    "key" : "AddRedditSettings",
    "value" : "true"
  } ]
},
```

**Comment by inotia00** [comment]
The latest v2023.26.0 seems to break the patch

Try with v2023.25.1

**Comment by inotia00** [comment]
The version I'm using is v2023.12.0, and the patch works on this version.

I'll update if I find a version with a patch that works.

**Comment by inotia00** [comment]
The last version the patch worked on seems to be v2023.16.1

**Comment by inotia00** [comment]
Temporarily I constrain to version 2023.16.1

https://github.com/inotia00/revanced-patches/commit/4bd27c0cfd6c707831102456984c8049843f6eb4#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870 f5

I'll close the issue for now
