### ISSUE TITLE
feat(hide-description-component): hide game sections and channel info section

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1069]
### Application

YouTube

### Issue

there are still components of description panel that i want hidden, if its possible.

### Patch

![Screenshot_20230706-175528_Trebuchet](https://github.com/inotia00/ReVanced_Extended/assets/87489540/49f386f1-9676-4392-8edd-9d303f249e43)

### Motivation

cleaner ui

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.182.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.182.1)
