### ISSUE TITLE
bug: unable to change brightness using swipe gesture after lock & unlock the screen

### ISSUE THREAD

**Issue by HoriKyoukosimp** [inotia00/ReVanced_Extended#107]
### Type

Other

### Application

Youtube

### Bug description

When you're watching the video, the brightness swipe gesture works fine but if you lock your screen and unlock it, swipe gesture will show HDR even tho the video arent HDR at all

### Steps to reproduce

1. Open a video
2. Put the video into full screen mode
3. Lock your devices screen
4. Unlock your devices screei
5. Swipe gesture locked as HDR (bug results)

### Relevant log output

```shell
https://t.me/goofyahhsharingshietchannel/4
```

### Screenshots or videos

https://t.me/revanced_extended_chat/155118

### Device Environment

https://www.gsmarena.com/xiaomi_poco_x3_gt-10949.php

Running android 12S with mii 13.0.7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.153.4
