### ISSUE TITLE
feat(patch): remove fundraiser and products tag

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1070]
### Application

YouTube

### Issue

fundraiser tag still appears in rvx 18.25.39, despite the crowdfunding patch. also, some videos show 'x products' under video title. 

### Patch

![22373](https://github.com/inotia00/ReVanced_Extended/assets/87489540/8d54f6fc-fde1-444d-aa23-b1a4056adaf4)
![Screenshot_20230704-135641_Trebuchet](https://github.com/inotia00/ReVanced_Extended/assets/87489540/b5e9c0a6-3280-4817-81db-e78c23c380c5)

### Motivation

cleaner ui

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
