### ISSUE TITLE
feat(patch): Add a refresh button to a video player

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#1071]
### Application

YouTube

### Issue

Ok so when I'm watching a video and there is a place for a SponsorBlock segment I could refresh and check if someone else has already added segment before me.

Also sometimes but rarely video doesn't play and I have to close and open video to fix it.

### Patch

Refresh button in video player.

### Motivation

This button would remove the need to close and open video to "refresh" it, making the app slightly more convenient to use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
