### ISSUE TITLE
suggestion: <please split the spoof-player-parameters patch and microg-support patch>: 

### ISSUE THREAD

**Issue by odkate** [inotia00/ReVanced_Extended#1073]
### Application

YouTube

### Description

Because there are also problems with buffering on the root version

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
not in plan
