### ISSUE TITLE
rotation after unlocking phone

### ISSUE THREAD

**Issue by mexon86** [inotia00/ReVanced_Extended#1075]
### Application

YouTube

### Description

idk what it is related and tied and if it something to do with samsung ui or youtube itself but at some point when i was in full screen in youtube and lock the phone and unlock it it was stay in full screen ready but now when i unlocked the phone app freeze for a second and rotate to portrait mode, well it not a big deal but if there can be patch about it it will be cool because it is annoying everytime i have to wait for app to rotate to portrait and i have to make it fullscreen again 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by S23u512** [comment]
Check this message: https://github.com/inotia00/ReVanced_Extended/issues/872#issuecomment-1526852650

**Comment by Vertuhai** [comment]
I tried many times to reproduce a similar situation, but everything works fine for me.
I think you need to enable (auto screen rotation) in the phone settings and your problem will be solved.

**Comment by inotia00** [comment]
dupplicate issue https://github.com/inotia00/ReVanced_Extended/issues/50

**Comment by mexon86** [comment]
so we cant have a patch for this to keep app in the last oriantation ?
