### ISSUE TITLE
bug: shorts shelfs are shown even if turn on hide shorts shelf

### ISSUE THREAD

**Issue by odkrys** [inotia00/ReVanced_Extended#1076]
### Type

Other

### Tools used

ReVanced Manager

### Application

youtube 18.25.39 / 2.181.4 /  0.111.4

### Bug description

My memory is not correct, but shorts were not searched for on tablets until a while ago. But now the shorts video is not searched on the phone, but on the tablet.

### Steps to reproduce

Search "blahblah shorts" on tablet. If you enable "Tablet Layout" on your phone, shorts will come up as a search result.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Vertuhai** [comment]
I advise you to use version 18.24.37

**Comment by inotia00** [comment]
I'm not sure what exactly you mean since you didn't attach a screenshot, but I'm guessing this is an A/B test

Try the following
- Turn on hide suggestions shelf
- Spoof with v18.20.39

**Comment by odkrys** [comment]
![tablet](https://github.com/inotia00/ReVanced_Extended/assets/20788200/8734c116-ba20-4f59-9641-6d1c637e93da)
![phone](https://github.com/inotia00/ReVanced_Extended/assets/20788200/5a2c3c6b-e58f-4228-93dd-b4a66eb56dc0)
![phone+tabletlayout](https://github.com/inotia00/ReVanced_Extended/assets/20788200/140a2d9c-3b0e-443c-a365-795911144229)

**Comment by odkrys** [comment]
tablet / phone / phone-tablet layout

The shorts videos are not searched on the phone, but the shorts videos are exposed on the tablet layout.

**Comment by inotia00** [comment]
oh this is normal
Because they are not shorts shelf

YouTube Vanced, a legacy of the distant past, also did not hide shorts videos in tablet layouts.
