### ISSUE TITLE
bug: is just Revanced Extended Bug or YouTube Bug?

### ISSUE THREAD

**Issue by aryanmaulana7636** [inotia00/ReVanced_Extended#1077]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube 18.25.39

### Bug description

When I watch video while my phone is turned off,
As soon I turn my phone on, the white background, meaning I can't see it

### Steps to reproduce

Step 1 Watch Any Video
Step 2 Turn off my phone
Step 3 turn on my phone
Step 4 there a white background

### Relevant log output

```shell
None
```

### Screenshots or videos

![Screenshot_20230707_085413_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/101686823/09a07bf5-9dc5-4c34-ac65-b7bf345990a5)

### Solution

None

### Additional context

None

### Device Environment

Android 13, One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Adity1243** [comment]
I didn't face this type of problem, try to use dark mode maybe it will fix

**Comment by Vertuhai** [comment]
Look for a problem in your phone.
I tried many times and many different variants of A13, and could not reproduce this situation..

**Comment by inotia00** [comment]
At least it doesn't seem to be an issue with Extended

**Comment by KobeW50** [comment]
@aryanmaulana7636 disable force dark on your device. It may be called something else depending on the ROM.

**Comment by Ox3rror** [comment]
I faced the same issue. Also, there is no force dark enabled.

Device : Oneplus 11
Youtube version : 18.25.40 
Patch : 2.182.1
