### ISSUE TITLE
Icon for Application.

### ISSUE THREAD

**Issue by Vertuhai** [inotia00/ReVanced_Extended#1078]
### Application

YouTube

### Description

I can send you a ready-made archive with icons for YouTube - Yoube Music so that you can add them to the patch.
Thank you.
They look like this:
![251510179-99cb9079-f040-4c11-b105-cedfffa78557](https://github.com/inotia00/ReVanced_Extended/assets/136680660/0ad39ba7-c259-4f72-bbd0-e1af1b3c27c3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
just open the pull request
