### ISSUE TITLE
feat(patch): auto full screen landscape feature

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1079]
### Application

YouTube

### Issue

Can you patch YouTube to use auto full screen landscape mode after start playing the video for first time click, when we press back button then it should go to portrait mode.

### Patch

.

### Motivation

No need to press full screen button on video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/50
