### ISSUE TITLE
Long pressing the copy link button should copy the link with time stamp 

### ISSUE THREAD

**Issue by venkat2305** [inotia00/ReVanced_Extended#108]
### Application

YouTube

### Issue

.

### Patch

Long pressing the copy link button should copy the link with time stamp

### Motivation

If this patch request is accepted, then we only need one button on the player making the ui a bit cleaner 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The explanation seems to be lacking

Please add a bit more explanation about the behavior you want

**Comment by venkat2305** [comment]
Right now , clicking the copy link button on the player copies the video link and there's another button which can copy the link with a time stamp. I'm suggesting, instead of two buttons we can have only one button which has two functionalities. Clicking the button should copy the URL and long press should copy the link with a time stamp. Does this make sense?

**Comment by inotia00** [comment]
yeah.. I understood

The current overlay button works like this:

Copy button (copy icon)
- short click

: Copy link of video

Timestamp copy button (timestamp copy icon)
- short click

: Copy link with video's current timestamp

- long click

: copy the video's current timestamp (e.g. 01:30:00)

The current motion is designed to match the icon and motion

If I implement the feature you want, an issue may be registered that the icon and the action do not match.
(e.g. Why does a link with a timestamp get copied to the clipboard when I long click the copy icon? In the past, Vanced didn't work like this!)

So I don't plan to implement this feature

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.164.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.24)
