### ISSUE TITLE
Patch to have an option to change between old and new tablet mini player

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1080]
### Application

YouTube

### Issue

In new tablet mini player, it leaves a small space when minimized. This patch can make it possible to revert back to old tablet mini player which doesn't have this issue.

### Patch

Just a toggle to change between old and new tablet mini player.

### Motivation

It's going to make tablet mini player look visually better and remove that visually annoying small space at right when minimized.
![Screenshot_2023-07-05-23-46-29-985_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/f7c29d7c-7cfc-4db0-a221-2cf2e0b48f7b)
(New tablet mini player)

![Screenshot_2023-07-06-09-40-25-856_com vanced android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/a2e263f7-ac97-4c7f-89c9-bb6b5a3a122e)
(Old tablet mini player)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unfortunately this is not possible

Your request is to revert Google's changes to YouTube's layout

just use the older version

**Comment by Rairof** [comment]
Well that's sad. Thanks anyways
