### ISSUE TITLE
Just ask 

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#1081]
### Application

Other

### Description

I just want to ask why mine is like this, did I do something wrong? Please answer me😣!!
![Screenshot_2023-07-07-12-35-54-317_app revanced manager flutter](https://github.com/inotia00/ReVanced_Extended/assets/125992636/b1bef69f-95fe-43ea-81a1-2e8f8216419f)
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It appears to be an issue with options.json probably.

Reinstall [Manager](https://github.com/inotia00/revanced-manager/releases)

**Comment by KimYo2** [comment]
Manager V 1.1.0 ?

**Comment by KimYo2** [comment]
Iam use non-root device

**Comment by inotia00** [comment]
nah... use this Manager ([RVX Manager v1.3.8](https://github.com/inotia00/revanced-manager/releases/tag/v1.3.8))
