### ISSUE TITLE
bug: `spoof-app-version` does not work on latest RVX versions

### ISSUE THREAD

**Issue by PhoenixAlpha204** [inotia00/ReVanced_Extended#1082]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube Music - tried multiple recent versions, all affected. Including 6.08.50, 6.05.51, 5.53.50.

### Bug description

The spoof-app-version patch does not work on the latest versions of RVX. Radio remains the only available option for playlists. The patch had previously been working on RVX 2.173.10.

### Steps to reproduce

Step 1. Include spoof-app-version patch
Step 2. Change location to Canada via VPN if necessary
Step 3. Attempt to play a playlist normally

### Relevant log output

```shell
N/A
```

### Device Environment

Galaxy S21 FE, Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Oops.... I forgot to add one line of code

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.181.6
