### ISSUE TITLE
feat(patch): Remove "Shorts remixing this video" section in the description.

### ISSUE THREAD

**Issue by xenophorm12** [inotia00/ReVanced_Extended#1083]
### Application

YouTube

### Issue

Remove "shorts remixing this video" section from video descriptions.

### Patch

![Screenshot_2023-07-07-10-34-50-382_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/58360189/ea5d5262-ebe5-4da6-ae25-5e7abf93440b)

### Motivation

It would make the description cleaner.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
