### ISSUE TITLE
bug: YouTube header, profile photo and notification button disappear on the Library page

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#1084]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v18.25.39
Patch v2.181.6

### Bug description

Pic 1: See that the YouTube header, profile photo and notification button appear on the home page.
![Screenshot_20230707-144657](https://github.com/inotia00/ReVanced_Extended/assets/125809686/ec8c0beb-b344-4a77-982d-152a4a42d791)

Pic 2: But they disappear on the library page.
![Screenshot_20230707-144700](https://github.com/inotia00/ReVanced_Extended/assets/125809686/d975bc4c-a588-4fd4-860d-03e850ffa355)

### Steps to reproduce

N.A.

### Relevant log output

```shell
N.A.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
tbh, this isn't a bug in RVX, it's a bug in YouTube
Even on unpatched stock YouTube, this bug is seen occasionally
