### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by MaksNPC** [inotia00/ReVanced_Extended#1087]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube Revanced Extende 18.24.37

### Bug description

feat(youtube): add language-switch patch inotia00/ReVanced_Extended#661
When changing the language in the application, the language does not change in the sections "ReVanced Extended, Return YouTube dislike, SponsorBlock"

### Steps to reproduce

1. General settings>App Language
2. ReVanced Extended settings, Return YouTube dislike, SponrosBlock

### Relevant log output

```shell
Absent
```

### Solution

Absent

### Additional context

Absent

### Device Environment

Android 11, MIUI 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
![Settings](https://github.com/inotia00/ReVanced_Extended/assets/108592928/67779ed9-ab7e-44b2-a907-a7b70966daa5)
Read
