### ISSUE TITLE
bug: Toast message error when changing video quality and set captions. 

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1089]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.25.39

### Bug description

When changing the video quality the toast message is not shown, it is shown if the collapse button is used even after several minutes.

### Steps to reproduce

Start the video.
Change the quality (e.g. 720p)
No messages are shown
Now use the collapse button and the quality change message will be shown.

### Relevant log output

```shell
Na
```

### Device Environment

Android 13. MIUI 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by jhon1282** [comment]
Same thing when activating subtitles from the flyout panel

**Comment by inotia00** [comment]
attach screenshot

**Comment by jhon1282** [comment]
https://github.com/inotia00/ReVanced_Extended/assets/125223735/dde46f0b-6d6a-44af-9a85-0f32ed1c5ce3


https://github.com/inotia00/ReVanced_Extended/assets/125223735/9faf1f1e-a2b2-4003-b83a-626dfc3aae14

**Comment by inotia00** [comment]
I think you enabled `Hide snack bar`

**Comment by inotia00** [comment]
never mind..
i checked the second video now

This issue also reproduces on unpatched YouTube
So.. Google should fix it

**Comment by jhon1282** [comment]
> non importa.. ho controllato il secondo video ora
> 
> Questo numero si riproduce anche su YouTube non inviato Così.. Google dovrebbe risolverlo

Yes you are right, I tested now.
Sorry youtube original i keep it disabled usually 🙏
Ty
