### ISSUE TITLE
Youtube layout

### ISSUE THREAD

**Issue by YuvrajMehta** [inotia00/ReVanced_Extended#109]
### Type

Error at runtime

### Application

YouTube v17.49.34

### Bug description

The YouTube player layout is still like old version. There's not an option to enable ambient mode and the layout isn't updated.

### Steps to reproduce

enable background play
hide video ads
enable sponsor block
enable revanced vanced settings page
enable swipe controls

### Relevant log output

```shell
i dont have any log output
```

### Screenshots or videos

![Uploading 1672987304782..jpg…]()

### Device Environment

Miui 14 Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The new layout follows your Google account status
(Not an issue in ReVanced Extended)
