### ISSUE TITLE
feat(patch): Remove "Can't Decide What to Watch?" box

### ISSUE THREAD

**Issue by tsujimoto-taro** [inotia00/ReVanced_Extended#1090]
### Application

YouTube

### Issue

This patch should remove the "Can't Decide What to Watch?" box in the home feed.

### Patch

Make it so that this box in the home feed no longer appears.

![Screenshot_20230707_091919](https://github.com/inotia00/ReVanced_Extended/assets/10093410/241ef360-75d9-41f9-8c57-5efe537eff85)

### Motivation

I think this box is a common annoyance that many people would like to see removed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Are these screenshots captured while using ReVanced Extended?

As I recall, it is already blocking

**Comment by tsujimoto-taro** [comment]
Yes, it's captured with revanced extended. Is there a setting I should double check for this? I have everything blocked in the Ads section.

**Comment by inotia00** [comment]
It should be `Hide feed servey` in the general settings

**Comment by tsujimoto-taro** [comment]
It might be that I missed a patch somewhere, because I didn't see that option at all. After repatching, everything looks to be working now. Thank you and sorry for the mixup! No idea what happened for me to miss this option originally.

**Comment by inotia00** [comment]
np. then I'll close issue
