### ISSUE TITLE
bug: `Disable playlist autoplay` loops video in minimised and PiP mode

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1092]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.25.39
ReVanced Patches v2.181.4

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/1e9e48ea-9bd8-4c6e-8725-e4eabf6b6af8

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by MondayNitro** [comment]
> ### Type
> Other
> 
> ### Tools used
> ReVanced Manager
> 
> ### Application
> YouTube v18.25.39 ReVanced Patches v2.181.4
> 
> ### Bug description
>  Screen_Recording_20230708.mp4 
> ### Steps to reproduce
> Shown in the video.
> 
> ### Relevant log output
> ```shell
> N/A
> ```
> 
> ### Screenshots or videos
> _No response_
> 
> ### Solution
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Device Environment
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new and no duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I filled out all of the requested information in this issue properly.
> * [x]  I have written the title and contents in English.
> * [x]  This issue does not reproduce on unpatched YouTube or YT Music.

where is this option to disable autoplay in playlists present?

**Comment by GUImodder** [comment]
Some feedback from the Dev/Team would be great on this issue. It is really annoying and it even spooked me in my car yesterday.
Does anybody know what version introduced this problem? I would be willing to downgrade in the meantime.
BTW: maybe this is a Samsung issue? I have a Samsung phone too...

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.186.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)
