### ISSUE TITLE
bug: `Hide join button` doesn't hide the button everywhere

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1093]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.25.39
ReVanced Patches v2.181.4

### Bug description

![Screenshot_20230708_012841_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/898ea5b0-f2c6-4921-9d74-763c7c0fb2ee)

### Steps to reproduce

1. Enable `Hide join button`
2. Go inside a channel

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Hide the join button is a setting in the Shorts player and layout component.

They hide the join button on the shorts player and the join button on the channel bar, respectively.
![IMG_20230708_132457_220](https://github.com/inotia00/ReVanced_Extended/assets/108592928/8146419c-8792-4e48-9475-338090d213a8)

It doesn't hide the join button in the channel information as in the attached screenshot

**Comment by Francesco146** [comment]
this is happening again
