### ISSUE TITLE
bug: Patching Errors due to Dependencies Issues(With Screenshots)) 

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#1094]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Youtube Versions
18.20.39
18.21.35
18.22.37
18.23.36
18.24.37
18.25.39

RVX Manager Version 1.3.8

### Bug description

Back in Patches v2.173.10 before the Hiatus. You can select which patches you like and it will work without any problem.

With the new Patch v1.181.6 using RVX Manager v1.3.8, I cannot pick only the patches that I want. If I select all the default 88 patches it would patch properly. But when I only selected the patches that I used to patch in older version plus 2 of the new patch feature it wouldn't patch due to errors in Dependency Issues. 

### Steps to reproduce

* Patch with all the Default Patches and It will work fine.
* But when I patch with only the patches I want it would have errors (See in the Screenshots below)
![IMG_20230708_140518_309](https://github.com/inotia00/ReVanced_Extended/assets/74855954/3b2d3e0e-9add-4f3e-8801-de577bee32a0)

### Relevant log output

```shell
Logs in Screenshots
```

### Screenshots or videos

![IMG_20230708_135626_693](https://github.com/inotia00/ReVanced_Extended/assets/74855954/bf191d50-2aa6-42a4-9b0c-d274147948c2)
![IMG_20230708_135625_705](https://github.com/inotia00/ReVanced_Extended/assets/74855954/34a555ba-128f-4419-a603-26f43707cb3b)
![IMG_20230708_135626_131](https://github.com/inotia00/ReVanced_Extended/assets/74855954/8b224efc-f632-477d-a499-59c862b6b855)
![IMG_20230708_135626_470](https://github.com/inotia00/ReVanced_Extended/assets/74855954/d070d658-0b4a-4bdc-95f9-6f8f0a3bf4c4)

### Solution

Solutions that I can think of:
1) Automatically include the Dependencies of a Patch when selected.
- I think the old patches works that way because there are options that I did not select but still gets included because the patches are dependent on the other.

2) List the Patch Features and its Dependencies / Group the patches that cannot work without the other features.

### Device Environment

Android 8.1.0, Oppo A5s (CPH1909)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1091
