### ISSUE TITLE
bug: Video Buffers While Watching Video

### ISSUE THREAD

**Issue by MInecrafterPictures** [inotia00/ReVanced_Extended#1096]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Youtube ReVanced Extended 18.17.43

### Bug description

I have a good connection, but somehow after watching a few seconds or so, basically up to 1 minute ish, it buffers indefinently for no reason and I cannot play the video until I restart ReVanced. And it still buffets after a few seconds or so of video playtime. 

### Steps to reproduce

Watch any video that is more than 1 minutes long

### Relevant log output

```shell
I have no logs
```

### Screenshots or videos

Various (+1 minute total length)

### Solution

Restart ReVanced, although it's only a temporary solution

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by S23u512** [comment]
Enable spoof player parameter patch and try again.

**Comment by MInecrafterPictures** [comment]
The closest thing I found is the pritobuf spoof.
But I still want to have end screen cards on videos. Are you sure this will work or are they any other alternatives?

**Comment by S23u512** [comment]
![Screenshot_20230708_151400_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/138691006/e336520b-5c54-4c5e-b828-baedf0b91945)

Maybe you didnt add this patch in, can you check if you added this patch in?

**Comment by MInecrafterPictures** [comment]
I have ReVanced Extended with MirrorG straight from the site without any extra patches installed and I've done the settings to have all features from the latest stock Youtube app (and site other astethic mods as well such as the YT Premium logo and green seek bar), except ads because they suck and I'm to poor for YT premium.

I don't see that option anywhere. At least in ReVanced's miscellaneous section.
It worked fine on a older version.

**Comment by inotia00** [comment]
v18.17.43 is an unsupported version
patch again with the latest resources

**Comment by MInecrafterPictures** [comment]
But I have downloaded the latest version of ReVanced and upgraded using Lucky Patcher

**Comment by MInecrafterPictures** [comment]
Just earlier today

**Comment by MInecrafterPictures** [comment]
On a site

**Comment by S23u512** [comment]
You downloaded a pre-made apk from illegal website? Inotia00 doesnt offer nor give any support for pre-made apks.

Heres a link for a guide how to build your own apk: https://github.com/inotia00/revanced-documentation

**Comment by S23u512** [comment]
I myself recommend you to use Revancify, its the most reliable way to build your own apk.
