### ISSUE TITLE
bug: Hide flyout suggestion shelf not working when spoofing.

### ISSUE THREAD

**Issue by Lolboykdld** [inotia00/ReVanced_Extended#1097]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.25.39

### Bug description

When spoofing to version 17.30.34 and below, the hide suggestion shelf patch does not work.

### Steps to reproduce

Step 1: Spoof to version 17.30.34 (or lower) with hide suggestion shelf patch on.

### Relevant log output

```shell
-
```

### Screenshots or videos

![IMG_20230707_220313](https://github.com/inotia00/ReVanced_Extended/assets/101134934/ec528c69-cd46-4566-b747-f6907d0c428a)

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`spoof-app-version` is a patch that forces a Google-deprecated version to load.

So this layout may have incompatible patches over time, I've classified the `spoof-app-version` patch as `Experimental Flags`

I am not receiving bug reports for issues with using `Experimental Flags` for this reason.
