### ISSUE TITLE
question: I want to find log export in the revanced extended settings that I installed with Revancify

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1098]
### Application

YouTube

### Description

I don't know if the menu has been moved as the version has changed or only the recommended patch has been installed, but I can't see log export
Can you tell me the item in a screenshot?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by sssh7710** [comment]
Did the menu move because I installed it as Revancify?

**Comment by S23u512** [comment]
Do you mean the patch log txt file thats created after patching? If yes then Revancify automatically createa that file and put it in your documents folder.

To be able to see this file you need to restart your phone after patching.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1085
