### ISSUE TITLE
question: <Where is this Youtube Settings Page specific string?>: 

### ISSUE THREAD

**Issue by innuendofloyd** [inotia00/ReVanced_Extended#1099]
### Application

YouTube

### Description

![photo_2023-07-08_13-53-25](https://github.com/inotia00/ReVanced_Extended/assets/8249663/5255bc34-cab1-4169-82f7-49191acc1738)

I'm trying to settings page as clean as possible and can't find the highlighted part anywhere, it's not in strings.xml in res/values or res/values-it. My idea is to delete that part.
Any help please?
Thank you, bye.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
it loads from server side
