### ISSUE TITLE
feat(patch): Force new UI/layout

### ISSUE THREAD

**Issue by Anonymous3641** [inotia00/ReVanced_Extended#11]
### Application

YouTube revanced extended

### Issue

Will able to enjoy new UI 

### Patch

Add a setting which forces new UI.

### Motivation

There are many people who are not getting UI from YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unlike in the past, new layout is now applied as default
