### ISSUE TITLE
bug: Shorts Video doesn't fill the space left by the removes "Shorts NavBar" 

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#1100]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

Youtube v18.25.39
RVX Manager v1.3.8

### Bug description

There is a Black Strip under the Shorts Video below the SeekBar. Not sure if this is because of the newer revanced extended patch version or maybe because newer Youtube version is built differently than the previous ones.

Back in Youtube v18.17.43 using Revanced Extended Patch v2.173.10 the video would fill the space left behind by the removed NavBar. 

### Steps to reproduce

1) Patch Youtube including "Hide Shorts Components" patch
2) Remove Shorts NavBar and Restart app.
3) Play Shorts and there is a black strip in the lower part of the screen. 

### Relevant log output

```shell
Screenshot Below
```

### Screenshots or videos

![Screenshot_20230708_214450](https://github.com/inotia00/ReVanced_Extended/assets/74855954/9ed14965-80bb-4419-92ba-844df6dec2b9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by S23u512** [comment]
#1041
