### ISSUE TITLE
question: <title>: can you now add the feature??

### ISSUE THREAD

**Issue by idontveapc** [inotia00/ReVanced_Extended#1101]
### Application

YouTube

### Description

i already asked it but now, is now custom font, see on many devices google sans is not a system font that youtube uses...

i know its not a patch/fix but a fequest.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
They are server side dependent

**Comment by inotia00** [comment]
It's not possible with my Android knowledge
If you can, please open a PR
