### ISSUE TITLE
feat(patch): shorts seekbar color

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1104]
### Application

YouTube

### Issue

Can you patch youtube shorts seekbar colour to custom seekbar colour that we use in general videos.

### Patch

![IMG_20230709_010805](https://github.com/inotia00/ReVanced_Extended/assets/131557644/2311210e-9536-41a2-af08-113444b38250)

### Motivation

More customizations.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.186.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)
