### ISSUE TITLE
feat(patch): hide-notification-badge-and-button

### ISSUE THREAD

**Issue by Francesco146** [inotia00/ReVanced_Extended#1106]
### Application

YouTube

### Issue

This patch should remove the notification counter, in the form of a badge, on the Home screen. It is purely useless and could be totally removed from the Home screen.

### Patch

As i said in the description, something like this is needed:

![Screenshot_20230709_084209_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/49027005/d737d760-987b-4d8d-883b-ae8ba092a900)

Note that there is no badge on the notification. A possible solution would be to give the option to remove that button.

### Motivation

Most people don't watch that section but open the video in the system notification section. So it's a waste of space.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
