### ISSUE TITLE
bug: every thumbnail on first page as scrolling is added to the history as seen video even if not watched

### ISSUE THREAD

**Issue by 0ldb34r** [inotia00/ReVanced_Extended#1107]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube Revanced 18.23.35

### Bug description

When i scroll down on the first page of YouTube Revanced, every video shown is added to my history. I don't click on it, i don't watch them but they are all added directly.

### Steps to reproduce

Go to the first page, scroll down. 
Go to library and look at the history : every thumbnail you've seen is shown as a viewed video.

### Relevant log output

```shell
Nothing special
```

### Device Environment

Android 13, Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It's YouTube bug.
Google should fix it

**Comment by ayushTNM** [comment]
I only have this from the 2.168.10 update after turning on the spoof player parameter setting. I don't have it if the setting is off.
