### ISSUE TITLE
About this issue regarding video quality on RVX

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#1108]
### Application

YouTube

### Description

https://github.com/inotia00/ReVanced_Extended/issues/1030
Regarding that issue 
I have the same issue . I have patched official Revanced 18.23.35 and don't find such that problem
Is that mean that the issue is related to RVX ?Or it is still linked to stock YouTube 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As previously answered, it is assumed to be a server side issue
Patch to YouTube v18.20.39 and check if the issue reproduces

**Comment by Mohammed1520** [comment]
Yes the issue still present in RVX 18.20.39

**Comment by inotia00** [comment]
Um.. I see
Anyway there is already a duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/321
so I will close this issue
