### ISSUE TITLE
bug: Can't see dislikes

### ISSUE THREAD

**Issue by broli95** [inotia00/ReVanced_Extended#111]
### Type

Other

### Application

Youtube 18.01.32

### Bug description

As the title says, I can see the likes but can't see the dislikes. The only "fix" I found so far is to enable the tablet layout option in Extended settings

### Steps to reproduce

Just open any YT video

### Relevant log output

```shell
Don't have one
```

### Screenshots or videos

![msg178136856-472288](https://user-images.githubusercontent.com/22918304/211087520-4766a270-9f3b-46ed-ba29-a4dc22fbb616.jpg)

### Device Environment

Android 13, Derpfest 13 ROM, Oneplus 7T Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Try enabling the Mirror API

**Comment by broli95** [comment]
> Try enabling the Mirror API

Tried, unfortunately nothing changes. Also this happens only with my main YT account, my alt accounts work perfectly

**Comment by inotia00** [comment]
Presumably this is an A/B test
(it follows your Google account status)
We'll have to wait until the A/B testing done by Google

**Comment by broli95** [comment]
> Presumably this is an A/B test
> (it follows your Google account status)
> We'll have to wait until the A/B testing done by Google

Is there a way to check this status?

**Comment by inotia00** [comment]
No longer reproducible in latest release
