### ISSUE TITLE
feat(spoof-player-parameters): switch to selectable patches

### ISSUE THREAD

**Issue by A7pr8** [inotia00/ReVanced_Extended#1110]
### Application

YouTube

### Description

it is just in root build the patch : spoof-player-parameters is excluded 

I use microg and I don't want to use the non-root build

if you could make it optional or include it in the root builds that would be great

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.184.3](https://github.com/inotia00/revanced-patches/releases/tag/v2.184.3)

**Comment by selfmusing** [comment]
> If you are using the ROOT environment, you do not need to use the `spoof-player-parameter` patch.
> 
> Even if you exclude the `spoof-player-parameter` patch, you can bypass the playback buffering issue by using the 'Disable signature verification' module
> 
> e.g. [LSPosed/CorePatch](https://github.com/LSPosed/CorePatch)

so maybe that's why i never faced buffering issue on my device ( coz I've been using core patch for more than 4 years)

**Comment by inotia00** [comment]
Playback issues occur when using microg build
Therefore, the playback issue is irrelevant to the YouTube Premium

You can just turn off via settings
Settings > Revanced Extended > Miscellaneous > Spoof player parameter (turn off)
