### ISSUE TITLE
feat(patch): playback in feeds but only in subscription page

### ISSUE THREAD

**Issue by mexon86** [inotia00/ReVanced_Extended#1111]
### Application

YouTube

### Issue

there is feature that automaticly play the videos in the feed but if i enable it, it also play the videos in home page and played videos get recorded in history so youtube will show more of this kind of videos so i want to enable this only for subs page, with that every random video not get in history and i wont see any more recomended videos that i dont want 

### Patch

enable playback in feeds for only subs page so in subs page videos automaticly start to play without opening them 

### Motivation

it allow me to use playbacks in feed feature inside the subs page without to worry about same type more recomended videos to show in home page 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
