### ISSUE TITLE
question: `Disable Shorts Player At App Startup` not working 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1112]
### Application

YouTube

### Description

Isn't the patch supposed to hide the shorts player from appearing in the first at the top in the homepage or is it not. I'm not sure but it's kind of annoying to have shorts at the top especially since the latest version have shorts appearing in a 2×2 grid manner.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
What the issue is:

https://github.com/revanced/revanced-patches/assets/117499019/b11665b9-0386-4306-a3ca-8af045a385dd

How the shorts UI is for some reason in the latest versions:
![Screenshot_20230710-022946~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/bc46b28e-6992-4983-8507-498fb4491af8)

**Comment by inotia00** [comment]
You are misunderstanding the description of the patch

The `Disable Shorts Player At App Startup` patch is a patch that prevents Shorts Player from opening instead of the home tab when YouTube is first launched.

If you use unpatched YouTube you will understand what this patch is.

**Comment by ILoveOpenSourceApplications** [comment]
> If you use unpatched YouTube you will understand what this patch is.

I have never experienced this whenever using the stock YouTube app. But do you know why this shorts is showing at the top of the homepage instead of a video.

**Comment by inotia00** [comment]
Whether videos, shorts, advertisements, survey banners or community posts are placed in the first view, it just depends on the YouTube algorithm.

it's not a bug

The patch to hide shorts is `Hide shorts shelf` in the `hide-shorts-component` patch.
