### ISSUE TITLE
feat(patch): hide shorts promotion banner

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1113]
### Application

YouTube

### Issue

Getting promotion banners of creators in shorts when opening the app

### Patch

![Screenshot_2023-07-10-14-15-39-889_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/107706560/78e6a288-204d-48e6-8fe0-03e12d61c6c0)
To remove banners like this

### Motivation

To have a ad free experience inside YouTube

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I don't see this banner

Maybe it's A/B tests or region ads

**Comment by Rairof** [comment]
But I had all ads removal patches and options toggled on though.

**Comment by inotia00** [comment]
I mean, this is supposedly a banner recently added by Google

Therefore, none of the current ad block filters will block this banner.

This banner doesn't appear on my device, so I'm assuming it's a new type of banner ad being tested on some users.

Debugging is much easier if this banner is exposed to all users, so we can block this banner.

**Comment by Rairof** [comment]
Oh alright. So anything I can do to give you the banner details and things you might need to add these banner on your ad filter list as I'm getting those type of banners on the app start up almost each time now. I suppose there is no opt out option from such tests by Google. By the way, thanks for your time and efforts.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
