### ISSUE TITLE
feat(patch): add "DeArrow" support.

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#1114]
### Application

YouTube

### Issue

.

### Patch

A patch to add support for [DeArrow](https://dearrow.ajay.app/)

### Motivation

It's very helpful to get aware of clickbait content.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by dumbdeniz** [comment]
I recently installed the extension on my browser and can say that it definitely has to be implemented. The difference is night & day...

![Before](https://github.com/inotia00/ReVanced_Extended/assets/77262340/525dd2e1-468d-47c1-a4d6-d4003b35ca1a)
![After](https://github.com/inotia00/ReVanced_Extended/assets/77262340/7bb93eb1-f46d-4a91-9444-e6c4a90b76a0)

It's developed by the same person who made sponsorblock, so the overall logic behind is almost indentical.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
