### ISSUE TITLE
feat(patch): hide recommend videos and recommend playlists

### ISSUE THREAD

**Issue by Suvam-007** [inotia00/ReVanced_Extended#1115]
### Application

YouTube

### Issue

![Screenshot_20230709-013801__01](https://github.com/inotia00/ReVanced_Extended/assets/122232607/4a1b7ff8-19e1-4ed3-9a8f-f6bfd36a6edb)
![Screenshot_20230709-014522](https://github.com/inotia00/ReVanced_Extended/assets/122232607/f8f9923c-316e-472f-8e3c-6dac3d6b36f9)

These are visible in playlist how to remove these.

### Patch

Remove recommend videos and recommend playlist from self created playlist.

### Motivation

For clean YouTube experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
