### ISSUE TITLE
question: Category bar is missing from home page

### ISSUE THREAD

**Issue by Suvam-007** [inotia00/ReVanced_Extended#1116]
### Application

YouTube

### Description

https://github.com/inotia00/ReVanced_Extended/assets/122232607/80d7f677-4e7b-4060-bd7f-f35674eed101

Category bar is missing from home page

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's supposed to be a bug on stock YouTube (unpatched YouTube)
Already a few months ago, stock YouTube had a strange bug where sometimes the category bar in the home feed was not visible
This is an issue Google needs to fix
