### ISSUE TITLE
suggestion: <title>: Update issue

### ISSUE THREAD

**Issue by NabeelJaved786** [inotia00/ReVanced_Extended#1117]
### Application

YouTube

### Description

When ever we open the app it asks for to update the youtube app with a pop up i have disabled auto update from youtube but stil aksing for it. There must be any option to block and stop the updates only Module updates should be working not the play store update

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Probably an issue with the Magisk module you are using
If you applied the patch correctly with Revanficy, rvx-builder, ReVanced Manager (RVX Manager), CLI this issue should not occur
