### ISSUE TITLE
suggestion: Can you please move Import/Export menu all the way down in the Settings

### ISSUE THREAD

**Issue by CriticalErrorInTheCode** [inotia00/ReVanced_Extended#1119]
### Application

YouTube

### Description

It's really difficult sometimes to spot this menu when you need it, it would be easier to spot if it was under the About section, and not in the middle of the Settings menu. This would make the Settings menu to look more well organized.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
well.. I refactored the setting structure once to reflect this request, so that's how it changed.
https://github.com/inotia00/ReVanced_Extended/issues/242

Just adapt to the new settings structure

**Comment by DabrahamLinkporn** [comment]
This was a great suggestion, I don't understand why it got denied. To me it looks really odd how this menu item is in the middle of Experimental flags section. Like OP suggested, this belongs in the About section.

OP didn't mean to overhaul the whole settings menu, he only wanted to move this one item in the About section where it rightfully belongs.

**Comment by DabrahamLinkporn** [comment]
It's weird how the dev thinks that import and export menu belongs in experimental flags section, there is nothing experimental about it, it's a stable structure of the app.

**Comment by inotia00** [comment]
Here's why Import/Export is flagged as Experimental Flags

: Activity execution through intent and execution result processing are performed in PreferenceFragment, not Activity

This may cause an exception or crash, and actually raises an exception in lower versions of Android

Since a fundamental refactoring of the code is still required, Import / Export is defined as an Experimental Flags
