### ISSUE TITLE
feat(patch): Seemless Downloading

### ISSUE THREAD

**Issue by miseryisland** [inotia00/ReVanced_Extended#112]
### Application

YouTube

### Issue

The in-app process for downloading videos is a tiny bit clunky and not seemless.

### Patch

Make the downloads area on the app able to watch videos from a device folder. Potentially make the downloads button functionally by automatically doing the share to downloader app functionality. 

### Motivation

It would make the app 100 percent complete and I think that would be cool. I can understand counter-motivations such as copyright infringement and whatnot though and further angering the google gods.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
