### ISSUE TITLE
feat(patch): YouTube Monet material UI theme

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1121]
### Application

YouTube

### Issue

![Screenshot_2023-07-10-20-50-41-432_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/131557644/cf640a1a-9a8e-47c9-86c2-6da8145ff229)

After applying material ui patch, it applies only to subscription and notification badges

### Patch

Can you patch the YouTube revanced extended to use material UI on light mode only and should apply to complete YouTube UI.

### Motivation

More Customization.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
When you apply that patch, besides the tint color, the white background color and the dark background color have also been changed to monet color.

Unfortunately, other themes cannot be implemented because they require the YouTube source code.

**Comment by wasifshaffaq** [comment]
i'm trying to patch spotify to support material ui theme, could you please let me know how you applied material you theme to youtube?

**Comment by inotia00** [comment]
RVX does not support Spotify patches
