### ISSUE TITLE
suggestion: SponsorBlock

### ISSUE THREAD

**Issue by Suvam-007** [inotia00/ReVanced_Extended#1123]
### Application

YouTube

### Description

![Screenshot_20230711-011941__01](https://github.com/inotia00/ReVanced_Extended/assets/122232607/16b9c1e0-9383-4649-9d96-b2683da2722e)

SponsorBlock is not auto hiding in screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Add youtube version, revanced-patches version, patch tool used, label appropriately and reopen issue.
