### ISSUE TITLE
bug: Revanced Extended Managaer 1.3.8 fetching update from wrong repository

### ISSUE THREAD

**Issue by Michael1999US** [inotia00/ReVanced_Extended#1124]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Revanced Extended Manager 1.3.8

### Bug description

The rvx manager doesn't check for updates from inotia00's repo, but from the official revanced team manager. So when you update, it only replaces the official Revanced Manager app.

### Steps to reproduce

1. Have rvx manager 1.3.8 (as tested).
2. Wait (it should check for available update, on this date it's 1.4.0)
3. Tap Update button
4. Resulting in downloading official revanced manager update not innotia00's rvx manager one

### Relevant log output

```shell
No log
```

### Screenshots or videos

![Screenshot_20230711_063046](https://github.com/inotia00/ReVanced_Extended/assets/56358359/a3ea7f8a-7fa7-4609-ac94-7c7abc56f092)
![Screenshot_20230711_063042_Package installer](https://github.com/inotia00/ReVanced_Extended/assets/56358359/a20332a8-6982-47a4-85d5-f9ecded095d7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
In dashboard tab we can't check patched RVX or see changelog of my patches

So I felt the dashboard tab was not needed in RVX Manager.

For this reason, I have removed the dashboard tab in RVX Manager v1.4.0.

ReVanced Manager is no longer available for download in the dashboard tab, so I'm closing the issue.
