### ISSUE TITLE
feat(patch): upgrade androidx/android compatibility.

### ISSUE THREAD

**Issue by idontveapc** [inotia00/ReVanced_Extended#1126]
### Application

YouTube

### Issue

youtube used to have androidx library's features like `emoji2` but now i see nothing like in meta.inf file. it means they stopped caring about old android version users specially >a11 users as they’ll either have to upgrade os or root if they want to see newer unicode characters.

> # `also to mention`

``there is no appcompat either it means app won't run on older android version?`

### Patch

if youtube really removed that feature you'd need to rebuild the app, adding the feature is simple it just needs the library checked on the android studio.

### Motivation

adding that will show newer emojis but you’d have to use `android studio` and build again, ofc, to add it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by idontveapc** [comment]
i think i didnt described it better :neckbeard:

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
