### ISSUE TITLE
feat(patch): hide tags in video player

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1128]
### Application

YouTube

### Issue

some videos have tags in their description which are also visible beside the video title. i request you to add a patch to hide them from view in the video player

### Patch

![Screenshot_20230711-121339_Evolution X Launcher](https://github.com/inotia00/ReVanced_Extended/assets/87489540/4ec77a4f-ac0d-4bf1-a3cb-26a2079396ff)

### Motivation

clean ui

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/521
