### ISSUE TITLE
bug: hiding `Hide` menu also hides `Hide this notification`

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1129]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40
ReVanced Patches v2.182.1

### Bug description

I want to hide only the `Hide` menu but when I add it inside the `Edit feed flyout menus filter` setting, it also hides the menu `Hide this notification`.

What menu I only want to hide:
![iMarkup_20230711_140408](https://github.com/inotia00/ReVanced_Extended/assets/127908708/751ec9dd-b757-4464-a8a9-d12341d7c96a)

What menu also gets hidden:
![iMarkup_20230711_140321](https://github.com/inotia00/ReVanced_Extended/assets/127908708/ebf6d8fb-b1fb-4165-8f57-25607de3b056)

### Steps to reproduce

Explained in description.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.184.3](https://github.com/inotia00/revanced-patches/releases/tag/v2.184.3)
