### ISSUE TITLE
question: <title>: Choose the specific categories that you don’t want to put in the SponsorBlock whitelist

### ISSUE THREAD

**Issue by EnzoDpch33** [inotia00/ReVanced_Extended#113]
### Application

YouTube

### Description

Hello I still have a suggestion in bulk if it is possible in the whitelist of SponsorBlock sa would be good to choose the categories for example pass the introduction specifically like that the other categories will not pass by the intro ect

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
channel whitelisting is removed in [revanced-patches-v2.173.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.1)
