### ISSUE TITLE
question: always auto repeat toggle

### ISSUE THREAD

**Issue by STEK1337** [inotia00/ReVanced_Extended#1132]
### Application

YouTube

### Description

Is it possible to bring back always auto repeat toggle?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
already exists

**Comment by inotia00** [comment]
If you mean, enable always repeat toggle, I have no plans
