### ISSUE TITLE
suggestion: Visual explanation what each patch does in RVX Manager

### ISSUE THREAD

**Issue by Michael1999US** [inotia00/ReVanced_Extended#1133]
### Application

Other

### Description

Considering the multitude of app patches available (which we sincerely appreciate), it seems like the perfect time to consider incorporating visual explanations in the RVX manager interface. This would allow users to visually comprehend the purpose of each patch, if feasible.

To implement this feature, you could introduce an information button right beside the patch selection box. Clicking on it would trigger the display of an image along with a descriptive text at the bottom.

Admittedly, implementing such a system could be quite labor-intensive, especially with an increasing number of patches. However, I strongly believe that offering visual explanations would greatly enhance the user experience for those who are unfamiliar with the patch functionalities but may find them beneficial.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Adity1243** [comment]
https://github.com/ReVanced-Extended-Community/Patches-Documentation

Watch here
