### ISSUE TITLE
bug: <title> theme patch bug and background playback bug

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1134]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

YouTube revanced extended v18.25.40
Revanced patches v2.184.3
Rvx builder v3.9.4

### Bug description

Issue 1 : When theme patch is applied while watching video, the video frontal description still stays dark colour.  

Issue 2 : when I turn my device off while video is playing the video didn't stops and keep playing and I can hear video voice, please make it stop when device screen is off, it never happens before.

### Steps to reproduce

Apply theme patch 
Open YouTube 
Play video

### Relevant log output

```shell
.
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/131557644/d1121629-ff54-4673-8113-71453b451e19

### Solution

Issue 1 : make theme apply on video description also. I don't know but I realised that when I didn't import my seetings the bug didn't appear but I import the sheeting then its appearing.

Issue 2 :- make video stop when device screen is off.

### Device Environment

Android 12 , MIUI 14.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Issue 1
: YouTube's theme combines client-side and server-side.

The current `theme` patch only changes the client-side theme.

server-side themes are immutable, so this request can never be accepted

default value for `theme` patches
- amoled works perfectly

Issue 2
: I don't know why this is flagged as a bug.
Settings - Background - Playback - Change to Off

**Comment by Adity1243** [comment]
I found the cause of theme bug the theme patch dosent support ambient mode, so if ambient mod is on the video title side will stay black where ambiend mode ui works, if i turn off ambient mode the theme patch works flawless.

> Issue 1 : YouTube's theme combines client-side and server-side.
> 
> The current `theme` patch only changes the client-side theme.
> 
> server-side themes are immutable, so this request can never be accepted
> 
> default value for `theme` patches (amoled) works perfectly
> 
> Issue 2 : I don't know why this is flagged as a bug. Settings - Background - Playback - Change to Off

**Comment by inotia00** [comment]
> Issue 1 : YouTube's theme combines client-side and server-side.
> 
> The current `theme` patch only changes the client-side theme.

ambient mode's theme is a force theme on the server side
