### ISSUE TITLE
suggestion: change the default value of `Hide expandable chip under video`

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#1135]
### Application

YouTube

### Description

The "product chip" should be hidden by default(switch with on by default) and a switch to hide "key moments chip" or not(switch with off by default). Because "product" chips are a part of promotion but "key moments" is a convenience feature.

Image for reference - 
![IMG_20230712_122801](https://github.com/inotia00/ReVanced_Extended/assets/64865031/f151c7cd-c57a-4582-aea4-cf2177f56de6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.186.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)
