### ISSUE TITLE
feat(patch): Remove bottom player label

### ISSUE THREAD

**Issue by nithya353** [inotia00/ReVanced_Extended#1136]
### Application

YouTube

### Issue

This patch should remove the labels for clip, remix, thanks, download, save (playlist) just same as navigation bar

### Patch

Please make an option in setting. Labels to remove is highlighted in red line in first picture. Second picture is for navigation bar reference. 

![IMG_20230712_113340](https://github.com/inotia00/ReVanced_Extended/assets/126687441/cf25d81c-23b0-46e3-9bf5-9c9a602fe656)
![Screenshot_2023_0712_113225](https://github.com/inotia00/ReVanced_Extended/assets/126687441/4bb76ad3-ebfd-4e7a-898d-071ffa210732)

### Motivation

By removing these labels, user can get uncluttered ui ie. only showing icons and really helpful for mobile users

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/966
