### ISSUE TITLE
bug: Videos keep skipping segments when played in background (w/o screen ind screen)

### ISSUE THREAD

**Issue by mindforger** [inotia00/ReVanced_Extended#1137]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

18.10.33

### Bug description

when plaing music mixes in background while connected via bluetooth for playback i experience skips in certains videos, but when i check the video later they do not seem to be segmented in any way so i would outrule it is a intended skip ... it is very dominant in certain videos but also appears on other videos frequently at what feels like random points

### Steps to reproduce

i will try to provide two videos with time index later the day but i need to have them in a looping mix as it does not always happen and i usually do not have the chance to just stop and check when it happens as the phone usually is tucked away and i am working or driving

### Relevant log output

```shell
ther is no log as far as i know or tell me how to produce helpful debug log please
```

### Additional context

"This issue does not reproduce on unpatched YouTube or YT Music. *" don't know, can't playback in background wihtout premium

### Device Environment

Pixel 4A 5G 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
v18.10.33 is an unsupported version

**Comment by mindforger** [comment]
oh, i will try if i can update

**Comment by mindforger** [comment]
i think i put the wrong app on my startpage but this reads 18.03.26 even older ?!

**Comment by mindforger** [comment]
@inotia00 is 18.03.26 the correct version or not? then i will continue to monitor

**Comment by mindforger** [comment]
nevermind, i misunderstood how the patcher works and my phone is not rooted so i can not use any more recent version unfortunate
