### ISSUE TITLE
bug: `MicroG Support` patch not recognised by ReVanced Manager for YT Music 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1138]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube Music (All)

### Bug description

For some reason when installing YT Music via the ReVanced Manager, the Manager throws the error that "Non-root install is not possible with the current selection of patches" even though the user has selected `MicroG Support`. The same is not happening when patching the YouTube app, as the patching and installation are successful. I believe the issue has something to do with ReVanced Manager not recognising that the user has selected the `MicroG Support` patch.

### Steps to reproduce

1) Download YT Music latest version.
2) Try to patch using ReVanced Manager.
3) Select `MicroG Support` patch as it's a non-root install.
4) Manager says you haven't selected the patch.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

![Screenshot_20230712-105633~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/4266fbca-0be4-4269-89d8-b656f1e43e39)

### Device Environment

Pixel 4a running Android 13.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by ILoveOpenSourceApplications** [comment]
Another change I noticed is how `MicroG Support` is written when patching YouTube & YT Music in the ReVanced Manager.

For YouTube:
![Screenshot_20230712-145632~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/d7163817-49bb-49b6-b52d-ba99205084ac)

For YT Music:
![Screenshot_20230712-105633~3](https://github.com/inotia00/ReVanced_Extended/assets/117499019/0b01a01c-4cd6-446f-ae75-c38698c57ac9)

**Comment by inotia00** [comment]
not reproduced

Check if you are using [RVX Manager 1.4.0](https://github.com/inotia00/revanced-manager/releases/tag/v1.4.0)

**Comment by inotia00** [comment]
> 

Anything off-topic should create a separate issue

**Comment by ILoveOpenSourceApplications** [comment]
That wasn't off-topic, I believe that's what's causing the issue. Also I'm talking about ReVanced Manager and not RVX Manager.

**Comment by inotia00** [comment]
It's an official ReVanced Manager issue

Starting from the last two patches, my patches are designed for compatibility with RVX Manager

Refer [RVX Manager v1.3.8 release notes](https://github.com/inotia00/revanced-manager/releases/tag/v1.3.8) 

close the issue

**Comment by ILoveOpenSourceApplications** [comment]
Like I have explained clearly, RVX YouTube is and can be installed without any issue. I do know that there was  an issue with custom sources in ReVanced Manager which was fixed in a later version. Which is ReVanced Manager v1.3.9  was working fine. Then in the latest version 1.4.0 they updated the hard-coded patch name from `microg-support` to `MicroG support`, which for some reason is conflicting with RVX YT Music's MicroG patch and thus ReVanced Manager not recognising the patch even though it's selected.

**Comment by inotia00** [comment]
> 
> Compatibility with the official ReVanced Manager is therefore no longer guaranteed
> 
read it

**Comment by ILoveOpenSourceApplications** [comment]
Yes, I read it when it launched and also used it personally. But I don't use both ReVanced & RVX at the same time and don't have any issues in changing the source if necessary. So after the official team fixed the custom sources issue, I came back to ReVanced Manager. Worked fine in 1.3.9 like I said, also works fine for YouTube in 1.4.0 but not for YT Music. Believes the issue is with the naming of MicroG patch specifically for YT Music.

**Comment by inotia00** [comment]
Does this issue reproduce in RVX Manager?
> Nope

Do my patches always have to be compatible with the official ReVanced Manager?
> Nope

So why is the issue valid?

**Comment by ILoveOpenSourceApplications** [comment]
I can see that RVX Manager changed its hard-coded patch name from:
```java
          _patches.any((p) => p.name.endsWith('MicroG support'));
``` 
to:
```java
          _patches.any((p) => p.name.endsWith('support'));
``` 
Whereas ReVanced Manager changed it from:
```java
          _patches.any((p) => p.name.endsWith('microg-support'));
``` 
to:
```java
          _patches.any((p) => p.name.endsWith('MicroG support'));
``` 
As I'm not a coder myself, I'm not sure but like I said I believe changing MicroG patch name for YT Music will fix the issue and will continue support for both Managers.
If you are someone who wants a separate manager to maintain their ReVanced & RVX patched files separately it's very convenient to have two Managers.

**Comment by ILoveOpenSourceApplications** [comment]
I can see this issue existed with RVX Manager 1.3.8, where the hard-coded patch name is the same as the current latest ReVanced Manager. By removing 'MicroG', and leaving 'support' was it fixed. So now editing RVX YT Music's 'Microg' to 'MicroG' will fix the same for ReVanced Manager as well. Please consider this issue.

**Comment by ILoveOpenSourceApplications** [comment]
Also, I believe that the support for ReVanced Manager should be returned as well. As the manager does provide the ability to use custom sources, which means depending on the user if they prefer something other than the official ReVanced to be used, they're allowed to do that.

**Comment by ILoveOpenSourceApplications** [comment]
As RVX was dependent on ReVanced Manager for a long time, I say it should continue to do that. The previous issue which cause RVX to fail via the Manager was the fault of manager of not supporting custom sources which was fixed. Now the current issue which is causing RVX YT Music to fail is with RVX YT Music patch name and needs to be fixed. So please reopen this issue until it's fixed and I still believe there are users still using ReVanced Manager out there.
