### ISSUE TITLE
bug(overlay-button): copy video URL does not work

### ISSUE THREAD

**Issue by A-of-Wonder** [inotia00/ReVanced_Extended#1139]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40
Patches v2.184.3

### Bug description

1. The order of the items on the RVX settings screen is disjointed. This bug has been happening since version 2.181.1.

2. Link copy on added overlay button is doesn't work properly. It will be copied to the clipboard, but any video and live will be "https://youtu.be/" and will not include the video ID. The same is true with time stamp.

### Steps to reproduce

1. No special operations are required.

2. 
Step 1: Include "overlay-buttons" patch.
Step 2: Enable the "Show copy link button" setting.
Step 3: Play the video and press the copy link button.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

(1)
![Screenshot_20230712-190932](https://github.com/inotia00/ReVanced_Extended/assets/128334768/c5b5a395-2765-4193-8352-43a6d174dd03)

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
1)
this is not a bug
that is the result of this request
https://github.com/inotia00/ReVanced_Extended/issues/242

2)
not reproduced

Please attach the url of the YouTube video in which the issue occurs or upload a screen video of the process in which the issue occurs.

**Comment by A-of-Wonder** [comment]
1. Understood. Thank you.

2.

**Comment by A-of-Wonder** [comment]
1. Understood. Thank you.

2. ex. https://youtu.be/dBN86y30Ufc

![Screenshot_20230712-225835](https://github.com/inotia00/ReVanced_Extended/assets/128334768/9dfe536c-8f07-4f97-8b93-84ab97d0fe29)
![Screenshot_20230712-225900](https://github.com/inotia00/ReVanced_Extended/assets/128334768/b341e3bb-c329-434d-91e7-438fa4f69e45)
![Screenshot_20230712-225908](https://github.com/inotia00/ReVanced_Extended/assets/128334768/04465bd3-42f3-4bd1-867e-d9a47142b3e0)

**Comment by inotia00** [comment]
umm.. the second issue is also not reproducible and works fine

I don't know why, but I guess something went wrong in the patching process

I recommend that you try patching with a different method.

**Comment by limonetas** [comment]
It works well for me, and you only have to press the copy button for 1 second, it also copies the

**Comment by A-of-Wonder** [comment]
Even link with time stamp doesn't includes an video ID either.
ex. https://youtu.be/?t=125

**Comment by limonetas** [comment]
> Even link with time stamp doesn't includes an video ID either. ex. https://youtu.be/?t=125

Well, it can be the android 12 or the language.
