### ISSUE TITLE
feat(patch): Add "max resolution" option

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#114]
### Application

YouTube

### Issue

In old Vanced, we have "Max Resolution" feature that allow to play 4K video on unsupported device. I think you should add it again to Revanced (because as I remembered, you are a dev of Vanced)

### Patch

None

### Motivation

A lot of user need it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Duplicate with the following issues https://github.com/inotia00/ReVanced_Extended/issues/16
(maximum resolution in Android YouTube is 4k resolution, so the same patch-request)
