### ISSUE TITLE
bug (microg-support): change `Microg support` to `MicroG support` for YT Music for name consistency

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1141]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube Music (All)

### Bug description

Currently for YouTube, the patch name is `MicroG support` whereas for YT Music it's `Microg support`. Please make it consistent across both apps as 'MicroG' is the standard format for the application, also given that the patch for the app `custom-branding-microg-name` defaults to 'MicroG'.

### Steps to reproduce

Nil

### Relevant log output

```shell
Nil
```

### Screenshots or videos

For YouTube:
![252924203-d7163817-49bb-49b6-b52d-ba99205084ac](https://github.com/inotia00/ReVanced_Extended/assets/117499019/225f5a49-a320-4aaf-a77f-0be3d10112e6)

For YT Music:
![Screenshot_20230712-203906~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/1222819c-b4cb-489f-b1d4-5b4892f4cbd4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.186.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)
