### ISSUE TITLE
feat(patch): allow us to choose which suggestions shelf to hide

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1142]
### Application

YouTube

### Issue

Currently, if you enable "hide suggestions shelf" it hides 5 shelves together, I would like to choose which shelf or shelves to hide

### Patch

A different toggle for each type of shelf

### Motivation

I would like to see "breaking news" and "continue watching" shelves and hide the rest

And also because one single option is hiding 5 things

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
