### ISSUE TITLE
question: Looking for menu to export app logs

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1143]
### Application

YouTube

### Description

![Screenshot_20230713_024601_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/98168192/5d099fbd-a2a4-4b12-9ee0-0c015e6af85e)

No log export in Miscellaneous menu
Do I need to patch it separately?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Enable debug logging` setting is in Miscellaneous,
only added when `enable-debug-logging` patch is included

check if you have included the `enable-debug-logging` patch

**Comment by sssh7710** [comment]
> `Enable debug logging`설정은 Micellaneous, 패치가 포함된 경우에만 추가됨`enable-debug-logging`
> 
> `enable-debug-logging`패치를 포함했는지 확인

How do I export that log?

**Comment by sssh7710** [comment]
> `Enable debug logging` setting is in Miscellaneous,
> only added when `enable-debug-logging` patch is included
> 
> check if you have included the `enable-debug-logging` patch

How do I export that log?
