### ISSUE TITLE
bug(sponsorblock): auto-skip multiple times under certain circumstances

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1144]
### Type

Other

### Tools used

Revancify

### Application

Youtube 18.25.40

### Bug description

I found it while watching a video of my favorite channel

### Steps to reproduce

1. Set automatic skip on videos introducing sponsors from the start of the video
2. Repeated indefinitely to skip that point

### Relevant log output

```shell
Unable to find menu to export logs
```

### Screenshots or videos

https://quickshare.samsungcloud.com/dAP3M7qRIa3c

https://github.com/inotia00/ReVanced_Extended/assets/98168192/45f31cbf-e8f3-4af5-b1c1-b1ae87c6bfa6

### Additional context

Strangely enough, it's normal if you turn on the access control

### Device Environment

Android 13, one ui 5.1
Galaxy a33

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.186.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)
