### ISSUE TITLE
Swipe controls not working

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1145]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube 18.25.40

### Bug description

Swipe gestures while in full screen doesn't work

### Steps to reproduce

1. Patch YouTube revanced extended with rvx manager
2. Use swipe controls
3. Watch any video in full screen and try those swipe gestures 

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://youtube.com/shorts/jIpnB4PEfkg?feature=share3

### Solution

Fixing swipe control patch

### Additional context

Using Xiaomi 11T pro device here

### Device Environment

Android 13 MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/517
