### ISSUE TITLE
question: remix & thanks button below player are not hidden

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1146]
### Application

YouTube

### Description

I thought there was some options on removing the remix and thanks tab in the button container below the player. If it wasn't available before then it would be nice to have the option to block them if possible.
![Screenshot_2023-07-13-07-25-45-069_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/190db639-198e-45b0-aadf-27394a7aa717)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Settings > Revanced Extended > Bottom player.

**Comment by Rairof** [comment]
![Screenshot_2023-07-13-11-59-37-304_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/f833fca6-9e9f-42b8-bf35-b66bbbb4270c)

**Comment by Adity1243** [comment]
It didnt got implimented still

**Comment by KobeW50** [comment]
> ![Screenshot_2023-07-13-11-59-37-304_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/f833fca6-9e9f-42b8-bf35-b66bbbb4270c)
> 

The hide action button hides them

**Comment by Rairof** [comment]
> > ![Screenshot_2023-07-13-11-59-37-304_app rvx android youtube-edit](https://user-images.githubusercontent.com/107706560/253184960-f833fca6-9e9f-42b8-bf35-b66bbbb4270c.jpg)
> 
> The hide action button hides them

Which button?

**Comment by KobeW50** [comment]
> > > ![Screenshot_2023-07-13-11-59-37-304_app rvx android youtube-edit](https://user-images.githubusercontent.com/107706560/253184960-f833fca6-9e9f-42b8-bf35-b66bbbb4270c.jpg)
> > 
> > The hide action button hides them
> 
> Which button? 

It's the toggle on the top of your screenshot.

**Comment by Rairof** [comment]
> > > > ![Screenshot_2023-07-13-11-59-37-304_app rvx android youtube-edit](https://user-images.githubusercontent.com/107706560/253184960-f833fca6-9e9f-42b8-bf35-b66bbbb4270c.jpg)
> > > 
> > > 
> > > The hide action button hides them
> > 
> > 
> > Which button?
> 
> It's the toggle on the top of your screenshot.

It hides remix, thanks button, yes. But it also hides the share button which I don't want it to be hidden

**Comment by Rairof** [comment]
I just want to hide the remix and thanks button

**Comment by KobeW50** [comment]
> > > > > ![Screenshot_2023-07-13-11-59-37-304_app rvx android youtube-edit](https://user-images.githubusercontent.com/107706560/253184960-f833fca6-9e9f-42b8-bf35-b66bbbb4270c.jpg)
> > > > 
> > > > 
> > > > The hide action button hides them
> > > 
> > > 
> > > Which button?
> > 
> > It's the toggle on the top of your screenshot.
> 
> It hides remix, thanks button, yes. But it also hides the share button which I don't want it to be hidden 

You can use the copy link overlay button for sharing, or make a request for the Hide action buttons toggle to not hide that (if it hasn't been requested already)

**Comment by Rairof** [comment]
> > > > > > ![Screenshot_2023-07-13-11-59-37-304_app rvx android youtube-edit](https://user-images.githubusercontent.com/107706560/253184960-f833fca6-9e9f-42b8-bf35-b66bbbb4270c.jpg)
> > > > > 
> > > > > 
> > > > > The hide action button hides them
> > > > 
> > > > 
> > > > Which button?
> > > 
> > > 
> > > It's the toggle on the top of your screenshot.
> > 
> > 
> > It hides remix, thanks button, yes. But it also hides the share button which I don't want it to be hidden
> 
> You can use the copy link overlay button for sharing, or make a request for the Hide action buttons toggle to not hide that (if it hasn't been requested already)

Well I don't use the in player button layout so I guess I have to create a patch request post on just having share button seperate from action button toggle?

**Comment by KobeW50** [comment]
> > > > > > > ![Screenshot_2023-07-13-11-59-37-304_app rvx android youtube-edit](https://user-images.githubusercontent.com/107706560/253184960-f833fca6-9e9f-42b8-bf35-b66bbbb4270c.jpg)
> > > > > > 
> > > > > > 
> > > > > > The hide action button hides them
> > > > > 
> > > > > 
> > > > > Which button?
> > > > 
> > > > 
> > > > It's the toggle on the top of your screenshot.
> > > 
> > > 
> > > It hides remix, thanks button, yes. But it also hides the share button which I don't want it to be hidden
> > 
> > You can use the copy link overlay button for sharing, or make a request for the Hide action buttons toggle to not hide that (if it hasn't been requested already)
> 
> Well I don't use the in player button layout so I guess I have to create a patch request post on just having share button seperate from action button toggle?

Yeah. And close this issue as well
