### ISSUE TITLE
feat(patch): Add custom video speed options for Shorts

### ISSUE THREAD

**Issue by xenophorm12** [inotia00/ReVanced_Extended#1147]
### Application

YouTube

### Issue

Add custom video speed options for Shorts similar to normal long-form videos.

### Patch

.

### Motivation

Some shorts just drag on and I would like to speed them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
