### ISSUE TITLE
feat(patch): Seperate hide share button from hide actions button patch

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1148]
### Application

YouTube

### Issue

Adds inconvenience to have in-player copy button enabled while the official share button works fine but just gets hidden from hide actions button toggle.

### Patch

A Seperate patch to add "hide share button" toggle within the bottom player catagory.

### Motivation

To have all required buttons such as "likes, dislikes, share and download buttons without any other unnecessary buttons hidden

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
> note #1103

I was asking for a separate hide share patch but sadly since it's going to be discontinued I'm hoping you remake or bring back this patch sometime in future when you find a way to do it.

**Comment by inotia00** [comment]
As noted in the comments, as of v18.21.35 it is no longer possible to identify each individual button without issues.

Therefore, in v18.21.35 and later, the ability to hide each individual button has been removed.

If you proceed with the patch to v18.20.39, you can use the function of hiding individual buttons as before without issues.

**Comment by Vasago** [comment]
Hello @inotia00 is this still the case for the version 18.29. 38? To separate Share button from others?

**Comment by Vasago** [comment]
![Screenshot_20230803_110758_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/241543/5a896b12-5d21-4e73-af64-b50cc5613f43)
![Screenshot_20230803_110745_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/241543/265711e6-fb87-4aea-9c0b-7d8f4eb0bf5d)
