### ISSUE TITLE
feat(patch): hide back button from search bar

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1149]
### Application

YouTube

### Issue

![Screenshot_20230713_133007_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/130296934/1d1ba5f0-4f18-449f-bcb3-798df63a9913)
![Screenshot_20230713_133023_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/130296934/c5c05a0a-8595-462f-8cef-18e33f7c88a0)

### Patch

A toggle to hide or show it

Also when the button is hidden, the search bar should increase its width on the left to not leave a blank space where the back button used to be

### Motivation

It would make YouTube more clean

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
