### ISSUE TITLE
feat(patch): Changeable postion for bottom layout in full screen 

### ISSUE THREAD

**Issue by rgv890** [inotia00/ReVanced_Extended#115]
### Application

YouTube

### Issue

During full screen video viewer we have bottom layout or controls (whatever it is) at the left side of the screen (highlighted area in screenshot) due to which you need to use both hands if you want to use those buttons "like" "dislike" etc. 
![Screenshot_20230107090031](https://user-images.githubusercontent.com/62609583/211141387-a3636049-facf-4647-9a4e-00ff83153820.jpg)

### Patch

If a patch can be applied with the help of which the position of bottom controls during full screen can be changed to right side or left side according to your hand preference then it'd be easy to interact with those options with one hand only. 

### Motivation

Currently when you have to like or open comments during full screen mode and you have phone in your right hand then you need to use both hands like you can show the layout by tapping on screen but to like and other controls you need to use your left hand because you can't stretch your thumb to left of the screen obviously and hence if the position becomes changeable then you can easily do it with one hand as in case of right hand users who can easily interact with that menu with right thumb by changing postion to right of the screen. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
