### ISSUE TITLE
feat(patch): Allow speeds higher than 9.9x in the settings

### ISSUE THREAD

**Issue by hwasiti** [inotia00/ReVanced_Extended#1150]
### Application

YouTube

### Issue

Thanks for the genius solution that you have made in the recent update. Now we can add speeds up to 9.9x.

But why the limit to 10x? A warning may suffice for low-end devices and let us experiment with higher speeds :)

### Patch

Unlimited speeds allowed 

### Motivation

Higher than 10x speeds may work fine with low-resolution videos like conference talks

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
playback speed could not be set beyond a certain value
buffering speed cannot overtake the playback speed

**Comment by hwasiti** [comment]
@inotia00 What does limit the buffering speed? 

If the internet speed or the device, there are high-end devices with high internet speeds that can do that for HD/FHD videos.
I tested speeds up to 50-60x on HTML video speedup on Windows without issues.
