### ISSUE TITLE
feat(patch): hide live chat components

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [inotia00/ReVanced_Extended#1151]
### Application

YouTube

### Issue

Live chat requests:

1. Remove "Community Guidelines"
2. Default to "All messages" instead of "Top messages"
3. Enable timestamps (this was present when original Vanced was active but was removed at some point by Google)
4. Remove heart icon

### Patch

![Screenshot_2023-07-13-18-51-29-351_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/1503339/ee7aa77c-cbb7-4d79-9a7e-51fd9c058aaa)

### Motivation

It'll make live chat experience more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.

**Comment by Bec-de-Xorbin** [comment]
Any hope to possibly revisit this since you are developing again? Thanks.

**Comment by Bec-de-Xorbin** [comment]
@inotia00 Seems like Google has removed the heart icon on live chat but for some reason it appears on RVX but not on official client or on original ReVanced. Is there some code that force enables that?

**Comment by Bec-de-Xorbin** [comment]
@inotia00 Any input on that heart icon? It's still present on v4.10.2 and YouTube 19.16.39.
