### ISSUE TITLE
ambient mode in full screen

### ISSUE THREAD

**Issue by mexon86** [inotia00/ReVanced_Extended#1153]
### Application

YouTube

### Description

i saw this post on reddit [reddit post ](https://www.reddit.com/r/revancedapp/comments/13lo2f3/how_can_i_get_rid_of_this_colour_gradient_lateral/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=2) and op say how to turn off ambiant mode in fullscreen and in photos it show ambiant mode in fullscreen where blackbar used to be but it kind a look like bugged or not implemented good yet ? idk, whatever quastion is do you know anything about that, is this was a/b test or just bug and if it test are we can get patch to enable this ? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I have no idea either
It might be YouTube's new A/B tests

I've never experienced it

**Comment by mexon86** [comment]
it is a good point have ambiant mode there too, instead fill to zoom and lost content or having just black bar. i hope it will be feature and not just bug
