### ISSUE TITLE
Improve setting naming and organization

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1154]
### Application

YouTube

### Description

A) The Overlay button menu should be renamed to "Overlay buttons".

B) The Description section within the General settings should be moved to the Bottom player settings (noticed by @hlytus)

C) The fullscreen settings can be renamed to "Fullscreen layout". 

This isn't necessary though, especially because the change can't also be made to the Player settings name (because the player settings contain the haptic feedback toggles, which arent layout components)

D) The Bottom player can be renamed to something to make it is easier to understand what it's for. Here are some suggestions:

1. Under player components (hlytus' and spacellary's pick)
2. Under player panel
3. Under player section
4. Below player
5. Under player
6. Section under player
7. Panel under player
8. Components under player

(I like 1 and 2)

Don't hesitate to pick a name that is 3 words. Many of the YT Settings have 3 word labels.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by DabrahamLinkporn** [comment]
Also make this change: #1119

**Comment by KobeW50** [comment]
@inotia00 I think I can fairly easily make a PR for suggestions A and D.

To change the setting category name, is it just one thing I'll need to rename or will I need to change it for all of the toggles within the Overlay button and Bottom player? (I haven't looked at the code yet)
