### ISSUE TITLE
question: The application name not showing up under patched applications 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1155]
### Application

Other

### Description

So I have noticed a few months back that in ReVanced and in RVX Manager v1.3.8, even if the user installs the patched version of RVX YT & RVX YTM, nothing shows up, well they show up for 1 frame and then disappear. For some time I thought it's because of the difference in package name. Because when I patched and installed mMicroG, the app showed up under patched applications. So my question is what's the culprits behind this issue? Does it have something to do with the manager or is it with the patched applications package name or something?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
The manager only searches for package names that have app.revanced in their package names.

Btw inotia00 removed the manager dashboard in RVX Manager 1.4.0, so this issue is no longer relevant to RVX.

**Comment by ILoveOpenSourceApplications** [comment]
> The manager only searches for apps that have app.revanced in their package names.

If that's the case then how does other applications with stock package name show up?
> 
> Btw inotia00 removed the manager dashboard in RVX Manager 1.4.0, so this issue is no longer relevant to RVX.

I know and that's why I mentioned specifically RVX Manager 1.3.8. Also I'm trying to get an idea about this situation. This is just a question.

**Comment by KobeW50** [comment]
> If that's the case then how does other applications with stock package name show up?

What stock apps show in the dashboard?

Also, this was with inoita00's mmicrog or ReVanced's microg?

> I know and that's why I mentioned specifically RVX Manager 1.3.8. Also I'm trying to get an idea about this situation. This is just a question.

👍

**Comment by inotia00** [comment]
As I said before, I no longer consider compatibility with the official ReVanced Manager.

I already forked RVX Manager for this compatibility issue.

My patch in the official ReVanced Manager is somewhat 'compatible', don't expect everything to work like the official patch.

no plans to fix it

**Comment by ILoveOpenSourceApplications** [comment]
> What stock apps show in the dashboard?

By stock I meant stock package names, because YouTube & YT Music are the only apps of which the package name is modified. But for reddit, Twitter, etc the package name isn't changed. But these apps are still being showed under patched applications right?

> 
> Also, this was with inotia00's mmicrog or ReVanced's microg?

I have also mentioned that I'm talking about mMicroG and ReVanced doesn't have a microG. Not till this post is made atleast.

**Comment by KobeW50** [comment]
> But for reddit, Twitter, etc the package name isn't changed. But these apps are still being showed under patched applications right?

Haven't ever seen them displayed.

> I have also mentioned that I'm talking about mMicroG and ReVanced doesn't have a microG.

Revanced does have a microg fork, and the package name for it is app.revanced so it consequently shows in the manager as a patched application. 

You can check the package name of your microg. I'm almost certain you have the ReVanced microg if it is showing as a patched app for you.

**Comment by ILoveOpenSourceApplications** [comment]
My question is who/what is the reason why RVX YT & RVX YTM doesn't show up under patched applications even in RVX Manager v1.3.8. mMicroG is showing up, which is not a supported app by official ReVanced but only by RVX. If this had something to do with their database, then mMicroG shouldn't have also shown up under patched applications but it is showing up for some reason. And that's what I want to know.

**Comment by KobeW50** [comment]
> My question is who/what is the reason why RVX YT & RVX YTM doesn't show up under patched applications even in RVX Manager v1.3.8. mMicroG is showing up, which is not a supported app by official ReVanced but only by RVX. If this had something to do with their database, then mMicroG shouldn't have also shown up under patched applications but it is showing up for some reason. And that's what I want to know.

Lmk what the package name for your microg is

**Comment by ILoveOpenSourceApplications** [comment]
> I'm almost certain you have the ReVanced microg if it is showing as a patched app for you.

Nope. mMicroG it is.
![Screenshot_20230714-133828~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/964f9d8e-db47-46f8-940f-172d45ba7281)

**Comment by KobeW50** [comment]
> 
> > I'm almost certain you have the ReVanced microg if it is showing as a patched app for you.
> 
> Nope. mMicroG it is.
> ![Screenshot_20230714-133828~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/964f9d8e-db47-46f8-940f-172d45ba7281)
> 
> 
> 

Check in the manager under patched applications.

**Comment by inotia00** [comment]
> My question is who/what is the reason why RVX YT & RVX YTM doesn't show up under patched applications even in RVX Manager v1.3.8.

It is estimated to be related to the Revanced API
That's why I removed the dashboard tab from RVX Manager 1.4.0

**Comment by ILoveOpenSourceApplications** [comment]
> It is estimated to be related to the Revanced API 

Then how come mMicroG showed up.

![Screenshot_20230714-152701~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/ad3eb97a-b8e9-461f-957a-2dae5f07d0a5)

**Comment by inotia00** [comment]
I don't even know, and I don't have plans to make it work normally
It is already removed from v1.4.0

**Comment by ILoveOpenSourceApplications** [comment]
I understand that. The fact that what's behind the issue is the thing that concerns me more than the fact that it's not working.

**Comment by KobeW50** [comment]
> 
> > It is estimated to be related to the Revanced API 
> 
> Then how come mMicroG showed up.
> 
> ![Screenshot_20230714-152701~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/ad3eb97a-b8e9-461f-957a-2dae5f07d0a5)
> 
> 
> 

Can you confirm that the one that shows up is not revanced's microg? They can both be installed simultaneously

**Comment by ILoveOpenSourceApplications** [comment]
> Can you confirm that the one that shows up is not revanced's microg? They can both be installed simultaneously. It shows the package name in the manager under "info".

I don't know anything about "ReVanced's microG".
> 
> I couldn't replicate mmicrog showing up.
> 
> And ofc refresh the dashboard page

I somehow got it to show up by just patching and installing. And please stop asking me whether it's some other microG. No it's not. The microG in the screenshot is mMicroG only.

**Comment by KobeW50** [comment]
> I somehow got it to show up by just patching and installing. And please stop asking me whether it's some other microG. No it's not. The microG in the screenshot is mMicroG only.

Im sorry for doubting you. My ego was strong.

I was able to reproduce mmicrog showing in the patched applications section (and regular vanced microg, as well as a random app)

The reason why it shows up is bec after patching that package name the first time the manager creates or adds to a file so it can keep track of which apps were patched

(This happens aside for checking for "revanced" in the package names of installed apps)

The bug is that the file seems to only function properly after u patch an app with that package name 2 times.

So i think u must've patched microg (whether it was vanced microg, mmicrog, or microg) once before.

Then when u patched mmicrog the file was completed and began functioning properly.

You can read my discussion with some revanced team members [here](https://discord.com/channels/952946952348270622/954147049832603748/1129540798699032656)
