### ISSUE TITLE
bug: <Unable to set tablet resolution above fixed and previous style video quality>

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1156]
### Type

Other

### Tools used

Revancify

### Application

Youtube 18.25.40

### Bug description

I was watching a high-definition video, and I noticed something wrong with the resolution

### Steps to reproduce

1. Install more than recommended patches on your tablet
2. Set wifi status resolution to maximum
3. Fixed and previous video quality cannot be set at 720p when playing video

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230714_190748_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/98168192/39073427-29bd-4915-a9ac-833cb26973f8)
![Screenshot_20230714_191051_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/98168192/2a97f61e-2606-448c-a7a9-cdd6ad9b0c5a)
![Screenshot_20230714_191108_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/98168192/61e6b986-6bd0-4a9d-a96d-9b8ffe363811)
![Screenshot_20230714_191134_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/98168192/8d3cf0b3-75bb-4efe-bcee-7e38a1e9cd99)

### Device Environment

Android 13,one ui 5.1
SM-X800

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
duplicate issues https://github.com/inotia00/ReVanced_Extended/issues/321
