### ISSUE TITLE
feat(patch): remove Join button in Shorts

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#116]
### Application

YouTube

### Issue

There is join button in Shorts of subscribed channels.

### Patch

Please add a patch to remove Join button from shorts too.

### Motivation

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Vipin2003** [comment]
![Uploading Screenshot_20230106-170150.png…]()

**Comment by Vipin2003** [comment]
![Screenshot_20230106-170150](https://user-images.githubusercontent.com/93650504/211146556-8fa7cb48-1bea-4cd7-8f6a-53978b070a4f.png)

**Comment by inotia00** [comment]
add the url of the shorts video

**Comment by Vipin2003** [comment]
https://youtube.com/shorts/T1rgWctMJOU?feature=share
In every shorts video

**Comment by Vipin2003** [comment]
Created a new Issue there.
