### ISSUE TITLE
bug: Lyrics not available 

### ISSUE THREAD

**Issue by Hooooooman** [inotia00/ReVanced_Extended#1160]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Youtube music v06.08.50

### Bug description

Whenever i go to the Lyrics section of a song it shows lyrics not available under every song, and it was not like this before, i tried to clear data/cache, removed ad blocker but none seemed to work.

### Steps to reproduce

I dont know how it happened but i cant revert it i have seen in the sertings/revanced settings, there is no toggle related to lyrics

### Relevant log output

```shell
Null
```

### Screenshots or videos

![Screenshot_20230715-025053_YouTube_Music](https://github.com/inotia00/ReVanced_Extended/assets/91048741/6d8a44e0-c08e-4510-ba6a-6830902ad89f)
![Screenshot_20230715-025058_YouTube_Music](https://github.com/inotia00/ReVanced_Extended/assets/91048741/a0be67fb-9c3b-480d-973e-c5b60aafbcab)
![Screenshot_20230715-025102_YouTube_Music](https://github.com/inotia00/ReVanced_Extended/assets/91048741/b1cf6475-eb1e-47f2-9a1f-57976cbf4e22)
![Screenshot_20230715-031843_YouTube_Music](https://github.com/inotia00/ReVanced_Extended/assets/91048741/39591867-3c56-446a-b8d7-49f1c854f4d9)

### Device Environment

Oneplus 7, using custom rom Derp A13 
July 5th, 2023 security update
Derpfest version: 13-Official-Tango-guacamoleb-20230709-1456

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [ ] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
I think this is a YTM issue and not an issue with patches

**Comment by s7san007** [comment]
Install YT Music v6.05.51. This is the latest version with lyrics.

**Comment by s7san007** [comment]
I installed v6.10.51 and spoofed the app version to 4.27.53 (for Canadians) to show lyrics.
![Screenshot_20230715_221306](https://github.com/inotia00/ReVanced_Extended/assets/130248949/49a57d76-483b-44d8-958f-05bcd6709e4d)
![Screenshot_20230715_221135](https://github.com/inotia00/ReVanced_Extended/assets/130248949/693043b1-69cd-408c-b72c-b0954b60fa17)
