### ISSUE TITLE
bug: bring back playback speed option 3x and up

### ISSUE THREAD

**Issue by gjguo** [inotia00/ReVanced_Extended#1161]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube ver. 18.25.40

### Bug description

After I installed new version from web site, the 3x, 5x playback speed options are gone, please bring them back.

### Steps to reproduce

Open setting or play a video

### Relevant log output

```shell
none
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
> After I installed new version from web site

It sounds like you got it from an unofficial source. You are supposed to patch it yourself.

And btw u can set a custom video option in the video settings.

**Comment by gjguo** [comment]
Thanks your reply, I will try it.  
  

-  
發送自 [MailTime](http://www.mailtime.com) 安卓客戶端

  

On 2023年7月15日 07:49:34 KobeW50 ***@***.***&gt; wrote:  

> > After I installed new version from web site

>

> It sounds like you got it from an unofficial source. You are supposed to
patch it yourself.

>

> And btw u can set a custom video option in the video settings.

>

> --  
> Reply to this email directly, [view it on
GitHub](https://github.com/inotia00/ReVanced_Extended/issues/1161#issuecomment-1636565278),
or [unsubscribe](https://github.com/notifications/unsubscribe-
auth/AANFNDXIWLDKVHEHXZROV53XQHLI5ANCNFSM6AAAAAA2K5DBN4).  
> You are receiving this because you authored the
thread.![](https://github.com/notifications/beacon/AANFNDRW7DWUFSVPJUGQGZDXQHLI5A5CNFSM6AAAAAA2K5DBN6WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTBRQAR4.gif)Message
ID: ***@***.***&gt;

**Comment by gjguo** [comment]
I add a custom video playback speed, and it works.
Thanks,
gj guo ***@***.***> 於 2023年7月15日 週六 09:06 寫道：

> Thanks your reply, I will try it.
>
> -
> 發送自 MailTime <http://www.mailtime.com> 安卓客戶端
>
