### ISSUE TITLE
feat(patch): Hide Recommended Videos below comment section

### ISSUE THREAD

**Issue by RoonMoonlight** [inotia00/ReVanced_Extended#1162]
### Application

YouTube

### Issue

This one is the follow-up of [this past issue](https://github.com/revanced/revanced-patches/issues/1117), as I closed down the issue due to problem with ReVanced team's ignorance.

Yep this issue is basically same with above mentioned issue, removing the recommended video section entirely below comment section.

### Patch

I would like to see the patch that removes recommended video section entirely, which shows below comment section of video.

### Motivation

The recommended video section can be sometimes annoying, when I try to click on comment section there is the case that I could misclick, leading to other videos being played and needs to close and open up same video again. This patch would be ideal for peoples like me who are annoyed by this recommended videos section.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by RoonMoonlight** [comment]
Also please note that this is NOT a duplicate of #1115 as this one is for playlist section.

**Comment by KobeW50** [comment]
You can use a custom filter to hide the videos.

Settings > Revanced Extended > General > (Enable custom filter, ON >) Edit custom filter 

Then on a new line, enter "related_video" (without the quotation marks)

Restart the app and then related videos won't load.

**Comment by AlpenMeister** [comment]
> You can use a custom filter to hide the videos.
> 
> Settings > Revanced Extended > General > (Enable custom filter, ON >) Edit custom filter
> 
> Then on a new line, enter "related_video" (without the quotation marks)
> 
> Restart the app and then related videos won't load.

Thank you so much! This is something I wanted forever.

**Comment by RoonMoonlight** [comment]
> You can use a custom filter to hide the videos.
> 
> Settings > Revanced Extended > General > (Enable custom filter, ON >) Edit custom filter
> 
> Then on a new line, enter "related_video" (without the quotation marks)
> 
> Restart the app and then related videos won't load.

This is the good idea, but I prefer simple way to block related videos entirely

**Comment by KobeW50** [comment]
> This is the good idea, but I prefer simple way to block related videos entirely, so I will be keeping this issue open

https://github.com/inotia00/ReVanced_Extended/issues/70#issuecomment-1367162548

**Comment by RoonMoonlight** [comment]
> [#70 (comment)](https://github.com/inotia00/ReVanced_Extended/issues/70#issuecomment-1367162548)

Interesting... If author doesn't want this feature to be added then I respect inotia's choice. So I will be closing this for now. @inotia00, would be great if you could pin [this comment](https://github.com/inotia00/ReVanced_Extended/issues/1162#issuecomment-1636967338).

**Comment by ARYAN-gif-creator** [comment]
But I want to know why is this not working now and now what to do to solve

**Comment by RoonMoonlight** [comment]
> But I want to know why is this not working now and now what to do to solve

See #2287

**Comment by ARYAN-gif-creator** [comment]
> > But I want to know why is this not working now and now what to do to solve
> 
> See #2287

I added both the filter but it is disabling the subscription videos too I want that

**Comment by ARYAN-gif-creator** [comment]
**@inotia00**
A very humble request can u please provide me a solution I want to hide search icon in youtube revanced app....any custom filter or anything 
Plz reply it would highly appreciated....

**Comment by inotia00** [comment]
The RVX project is just one of my hobbies

That's why I don't accept donations, and I don't accept feature requests for YouTube

If you want to contribute, feel free to open a PR

Or you can contact the ReVanced Team and make a feature request

And please stop spamming

**Comment by ARYAN-gif-creator** [comment]
Sorry for my previous childishness 

I respect ur time 

But u can just help me with 
hiding search icon on youtube revanced app I would use it properly to study the lectures without distracting 

It will mean a lot to me
