### ISSUE TITLE
I tried every settings but couldn't change the default video quality settings to 2160p please help bug: <title>

### ISSUE THREAD

**Issue by Funnyfiend1986** [inotia00/ReVanced_Extended#1163]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube revanced version 18.25.40

### Bug description

I tried every settings but couldn't change the default video settings to 2160p please help

### Steps to reproduce

Couldn't change the video quality

### Relevant log output

```shell
Couldn't change the video quality
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/321
