### ISSUE TITLE
in relation to resolution limitation

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1164]
### Application

YouTube

### Description

If the resolution fixing works normally in an app other than this app
I think it's possible to make it work again in the future

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by sssh7710** [comment]
In other words, I think there's a limit on the client, not the account

**Comment by inotia00** [comment]
duplicate issues have already been opened https://github.com/inotia00/ReVanced_Extended/issues/321
