### ISSUE TITLE
bug(sponsorblock): icons stays visible after double tap to seek

### ISSUE THREAD

**Issue by xenophorm12** [inotia00/ReVanced_Extended#1165]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40

### Bug description

When I double tap to seek, SponsorBlock icon stays visible even after all other buttons fade away. I have to manually tap the screen for it to go away.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/58360189/443ebf00-ba9d-404e-8543-48249651021f

### Device Environment

MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
After using it for a few days, it seems to have been fixed in the latest patches.
Close the issue.
