### ISSUE TITLE
feat(patch): allow us to hide "your videos" and "downloads" account menus

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1166]
### Application

YouTube

### Issue

![Screenshot_20230715_141504_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/130296934/1e3234aa-a661-4ad8-aa4b-5bb909ea8389)

### Patch

Allows us to hide those 2 menus by adding them inside "edit account menu filter"

### Motivation

It would make YouTube cleaner

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by AlpenMeister** [comment]
![Screenshot_20230716_113806_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/139682415/fe1ed054-11e3-4699-995c-1c8c8c69dba2)

Had the same idea if this could be turned of.  I do have different names. 

- Your video's
- Your downloads
- Your clips

If also these could be disabled in the "edit account menu filter" would be great 👍

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
