### ISSUE TITLE
bug: dislikes disappear after being minimized

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1167]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40
ReVanced Patches v2.184.3

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/a6994a53-93be-403d-9238-2f233664e72a

https://github.com/inotia00/ReVanced_Extended/assets/127908708/5ad10ff1-f371-4ae5-828b-6bed2a83f3d6

### Steps to reproduce

I'm not sure how exactly to reproduce this bug, it happens randomly.
Following the process shown above I was able to reproduce it twice, but not in a row.

I also did a clean reinstall but it keeps happening from time to time.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.186.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)
