### ISSUE TITLE
Screen Dimming bug

### ISSUE THREAD

**Issue by Kaplan-Rp** [inotia00/ReVanced_Extended#1168]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Youtubevanced

### Bug description

Whenever I switch my phone from vertical to horizontal while watching a video on YouTubevanced, the screen dims. 

Standard YouTube app works with no issue and so does everything else. 

### Steps to reproduce

Start video vertical, move to horizontal. 

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
The following forms are missing

- YouTube version
- revanced-patches version
- list of included or excluded patches
- screenshots or screen records for issues

Please fill out the following forms and reopen the issue.
