### ISSUE TITLE
feat(patch): Hide Incognito Mode

### ISSUE THREAD

**Issue by AnantMishra01** [inotia00/ReVanced_Extended#1170]
### Application

YouTube

### Issue

The issue that this patch should solve is the presence of the incognito mode feature in YT Vanced Extended. The goal is to hide or disable this feature within the application.

### Patch

The patch should modify the user interface of YT Vanced Extended to remove Turn on incognito option 

### Motivation

The proposed patch request to hide or disable the incognito mode feature in YT Vanced Extended holds value for the community due to the following reasons:

Child safety: By removing the incognito mode feature, the patch helps in creating a safer environment for children using YT Vanced Extended. It prevents kids from accessing content privately or engaging in potentially inappropriate browsing activities that might otherwise be hidden from parental supervision.
Parental control: The patch aligns with the concerns of parents who want to have more control over their children's online activities. By eliminating the incognito mode, parents can have better visibility and oversight of the content their children are accessing through YT Vanced Extended.

Promoting responsible usage: Disabling incognito mode encourages users to take more responsibility for their online actions. It fosters a sense of accountability by ensuring that users' search and watch histories are recorded, which can deter potentially harmful or malicious behavior.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by GucekPL** [comment]
I doubt that this patch will be accepted, as something like this can already be done using the account menu filter.

1. Go to Settings ➞ ReVanced Extended ➞ General
2. Enable "Hide account menu" option
3. Click "Edit account menu filter" and enter the name of sections of account menu you want to hide, separating them with a new line, e.g:

```
Turn on Incognito
YouTube Studio
YouTube Kids
YouTube Music
```

And voi la, it's all!

**Comment by AnantMishra01** [comment]
> I doubt that this patch will be accepted, as something like this can already be done using the account menu filter.
> 
> 1. Go to Settings ➞ ReVanced Extended ➞ General
> 2. Enable "Hide account menu" option
> 3. Click "Edit account menu filter" and enter the name of sections of account menu you want to hide, separating them with a new line, e.g:
> 
> ```
> Turn on Incognito
> YouTube Studio
> YouTube Kids
> YouTube Music
> ```
> 
> And voi la, it's all!

Thanks
