### ISSUE TITLE
question: <title>: v8a only buid

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/ReVanced_Extended#1172]
### Application

YouTube

### Description

I have no way to contact you, so I'm leaving it here.  Unlike the youtube music apk, the youtube apk distributed by https://revancedextended.com/en/ does not have a v8a-only build.  I can't build it separately, so if possible, I would sincerely appreciate it if you could upload the youtube apk as a v8a-only build.  please.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
That site is not official and potentially unsafe. Patching the apk yourself is the only official way to install any ReVanced Extended app.

You can check [this guide](https://www.reddit.com/r/revancedextended/comments/12vxggr/revanced_extended_guide_for_beginners/) for patching YT ReVanced Extended with the RVX Manager on your armv8 device.

You can also check [inotia00's documentation](https://github.com/inotia00/revanced-documentation#revanced-extended-documentation) for guides (although some of it is outdated)

You can also look the [r/revancedextended wiki](https://www.reddit.com/r/revancedextended/wiki/) for guides, help, and info.
