### ISSUE TITLE
suggestion: bump mMicroG version

### ISSUE THREAD

**Issue by hoang-himself** [inotia00/ReVanced_Extended#1174]
### Application

mMicroG

### Description

It looks like OxrxL force-pushed his mMicroG repo with a newer version. I have no idea what changed but that should be enough to create a new release.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Here is the answer
<img width="341" alt="image" src="https://github.com/inotia00/ReVanced_Extended/assets/70064328/a261f910-ca94-43d5-913b-81ed67c84a7b">
