### ISSUE TITLE
Play next in queue

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#1175]
### Application

YouTube

### Description

use the premium skill play next in queue for free

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Dup of #122

**Comment by KobeW50** [comment]
@speedlorenzo12 you can also follow this thread in the revanced github to be notified of any updates

https://github.com/ReVanced/revanced-patches/issues/1141
