### ISSUE TITLE
bug: `Double back timeout` doesn't work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1176]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40
ReVanced Patches v2.184.3

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/67d48e73-5498-4590-8f9c-f25847baf4dd

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/665
