### ISSUE TITLE
feat(patch): hide join button in the channel information

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1177]
### Application

YouTube

### Issue

![Screenshot_20230708_012841_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/898ea5b0-f2c6-4921-9d74-763c7c0fb2ee)

### Patch

A toggle to hide it and show it.

### Motivation

It will make YT cleaner.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by kazimmt** [comment]
It's already available

Go to General Settings & Find Hide join button.

For ref you can find it here: https://github.com/kazimmt/RVX-Features#general

**Comment by inotia00** [comment]
nah.. it hides the join button on the channel bar, not the join button on the channel info page

refer https://github.com/inotia00/ReVanced_Extended/issues/1093

**Comment by kazimmt** [comment]
Ah, i see
thanks for the clarification.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
