### ISSUE TITLE
Version 5.34.52 ad removal

### ISSUE THREAD

**Issue by harutoku** [inotia00/ReVanced_Extended#1179]
### Application

YouTube Music

### Issue

The "library" is an older version, version 5.34.52, which does not remove ads.

### Patch

I would like to see just ad removal implemented.

### Motivation

For those who want to use the old "library" specifications, please do so.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube Music SUPPORTS VERSIONS from V5.17.51 to v6.10.51

If you patched youtube music v5.34.52, but the ad is not removed, it is a bug

If you want to report the issues you are experiencing, please open it with the proper form and label

**Comment by harutoku** [comment]
My apologies.
