### ISSUE TITLE
feat(youtube): hide `more-like-this-video` chip under video

### ISSUE THREAD

**Issue by kazimmt** [inotia00/ReVanced_Extended#1180]
### Application

YouTube

### Issue

YouTube added a new `more like this video` chip under video in feed
These are unnecessary
![Screenshot_20230717-161641_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/82371061/05f5e0e0-3f05-4b54-8d7f-a8d697be15cb)

### Patch

A patch to hide these chip

### Motivation

I don't think these are necessary & takes some space in feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Spacellary** [comment]
@inotia00 https://github.com/ReVanced/revanced-patches/pull/2699

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.186.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.10)
