### ISSUE TITLE
bug: hide join button patch is not hiding the button

### ISSUE THREAD

**Issue by tempaccount666666** [inotia00/ReVanced_Extended#1181]
### Type

Cosmetic

### Tools used

Revancify

### Application

Youtube 18.25.40
Patches 2.184.3

### Bug description

When hidd join button patch is enabled its not hiding the button.

### Steps to reproduce

Enable hide join button patch
Go for a channel that has this button, like LTT
Notice how join button is visible

### Relevant log output

```shell
All patches included except language switch and translation
```

### Screenshots or videos

![Screenshot_20230717_135921_YouTube Premium](https://github.com/inotia00/ReVanced_Extended/assets/139658546/8fad8372-dea6-4bce-9f5c-5ed95a27b574)

### Solution

Fix this patch

### Device Environment

Android 13 / OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1093
