### ISSUE TITLE
bug: `hide-account-menu` doesn't hide specific menu items (in russian language mostly)

### ISSUE THREAD

**Issue by DiofyZz** [inotia00/ReVanced_Extended#1183]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40

### Bug description

Using `hide-account-menu` patch to hide "YouTube Studio", "YouTube Music" and "YouTube Kids" doesn't work, but it still can be used to hide most other menu items. Both original (english) and local (russian) spellings doesn't work. Tried to reproduce this issue in different languages with no problems, yet still sometimes had to correct spelling to match the local language in order for the patch to work. 

### Steps to reproduce

1. Include `hide-account-menu` patch;
2. Switch YouTube language to Russian;
3. Type either `Творческая студия YouTube, YouTube Music, YouTube Детям` or `YouTube Studio, YouTube Music, YouTube Kids` in edit account menu filter;
4. Switch YouTube language to any other and repeat previous step. 

### Relevant log output

```shell
No debug logs since it's not a fatal error
```

### Screenshots or videos

![Screenshot_20230717-220122](https://github.com/inotia00/ReVanced_Extended/assets/136701919/9f3a0944-f218-44d0-8d59-bece4cfc51d0)
![Screenshot_20230717-220044](https://github.com/inotia00/ReVanced_Extended/assets/136701919/a5ba8fc7-5806-42f9-9ae4-7d2fe3c42820)
![Screenshot_20230717-220220](https://github.com/inotia00/ReVanced_Extended/assets/136701919/f1a33ed6-546f-40e0-8ac6-044fbd8186fc)
![Screenshot_20230717-220205](https://github.com/inotia00/ReVanced_Extended/assets/136701919/a13ec2e2-ab49-44bd-96d8-b6abd5a95d84)

### Device Environment

Android 13, TQ3A.230705.001

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Might be an A/B test

**Comment by Hennadz** [comment]
> `Творческая студия YouTube, YouTube Music, YouTube Детям` or `YouTube Studio, YouTube Music, YouTube Kids`

Here it is enough to hit a single word in the filter to hide the entire line with it. Naturally, it must be in the program language.
Try writing like this:

> Premium
> Творческая
> Music
> Детям
<details><summary>This filter works great for me:</summary>
<p>

![Screenshot_20230718-084315_MyTube](https://github.com/inotia00/ReVanced_Extended/assets/130844239/252056cf-7696-47fd-abc8-5528321e5938)

</p>
</details>

**Comment by DiofyZz** [comment]
> Premium
Творческая
Music
Детям

Yes, it worked. Thanks.
