### ISSUE TITLE
bug(hide-music-ads): not working on v5.34.52

### ISSUE THREAD

**Issue by harutoku** [inotia00/ReVanced_Extended#1184]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube Music  v5.34.52

### Bug description

The "library" is an older version, version 5.34.52, which does not remove ads.

### Steps to reproduce

Step1 In revancify, select "recommended" and apply the patch.
Step 2 Play any of the songs.

### Relevant log output

```shell
No debug logs since it's not a fatal error
```

### Additional context

It is hard to say how reproducible the problem is in an unpatched application due to the nature of ad blocking.

### Device Environment

Android 11,ZenFone6

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by harutoku** [comment]
Thank you so much for your support of the old spec library in the latest version.
We have eagerly awaited your return.

**Comment by inotia00** [comment]
This issue is not actually fixed, but a workaround patch has been added, so I will close the issue
