### ISSUE TITLE
bug: <title>Default video quality on Mobile network doesn't work  

### ISSUE THREAD

**Issue by Bakchxd** [inotia00/ReVanced_Extended#1186]
### Type

Other

### Tools used

rvx-builder

### Application

Youtube revanced 18.25.40
![Screenshot_20230719-091931](https://github.com/inotia00/ReVanced_Extended/assets/139042928/910dd8dd-2cb3-457a-b3b2-6594d793edeb)

### Bug description

doesn't work  video quality save / save the video quality. The default video quality on mobile networks keeps changing automatically 

### Steps to reproduce

Solve this problem The default video quality on mobile networks keeps changing. Not save quality 

### Relevant log output

```shell
Solve this problem The default video quality on mobile networks keeps changing. Not save quality
```

### Additional context

![Screenshot_20230719-092703](https://github.com/inotia00/ReVanced_Extended/assets/139042928/01e26a22-c5f6-4a99-b391-6e19d304a251)

### Device Environment

Android 11. Realme ui

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/321
