### ISSUE TITLE
question: <title>: watched history

### ISSUE THREAD

**Issue by iboy212232** [inotia00/ReVanced_Extended#1187]
### Application

YouTube

### Description

howdy does anyone else have problem with history in revanced yt application ? 
my history only synch when im watchin something on my pc but not on my phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
works fine
Your adblock dns may be blocking the saving of watching history, so turn it off and test again
