### ISSUE TITLE
How's to use ambient mode

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#1188]
### Application

YouTube

### Description

ambient mode is still not working/running, how do you turn on ambient mode, even though when you first installed this apk ambient mode still working fine, did i do something wrong?

![Screenshot_2023-07-20-09-07-53-969_com miui powerkeeper](https://github.com/inotia00/ReVanced_Extended/assets/125992636/b2d1a619-7792-466c-8057-961d71d8c04d)
![Screenshot_2023-07-20-08-58-40-673_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125992636/d50b5249-84f7-4e48-a4e3-98e6a9196e48)
![Screenshot_2023-07-20-09-00-29-194_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125992636/7a5d50be-a74d-424b-a431-f8365fd0748a)
![Screenshot_2023-07-20-09-01-23-405_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125992636/d206cfdf-9737-488d-9523-8bc7130c1abe)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
If you enable spoof player parameter and set spoof player parameter type to incognito mode, ambient mode will not work (side effect)
