### ISSUE TITLE
Hide Film Strip Overlay: What does this option do?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#119]
### Application

YouTube

### Description

![IMG_20230108_082833](https://user-images.githubusercontent.com/91815107/211178945-bf1a52e7-c30c-49df-8f0a-e393e7dd6661.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![RDT_20230108_1540518599011732236427095](https://user-images.githubusercontent.com/108592928/211183905-f04449be-b310-4294-908e-c6be03d90d51.jpg)
hide this
