### ISSUE TITLE
feat(patch): Premium advertisement that appears often

### ISSUE THREAD

**Issue by bubuleur** [inotia00/ReVanced_Extended#1190]
### Application

YouTube

### Issue

Good morning,
I come to you I downloaded the latest version 18.25.40 but I often have this ad when starting the application
![2023-07-20_10-20-48](https://github.com/inotia00/ReVanced_Extended/assets/21688137/c3c0db16-2531-4419-b5b5-92e4682edc05)
and it is possible to delete it?
Thanking you for all
Good day

### Patch

stop seeing this ad

### Motivation

YouTube ReVanced Extended is an application not to have ads, this ad is one of the ads to remove

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As you say, no patch to remove it has been implemented

Because this banner is exposed quite rarely, it is not suitable for debugging

Therefore, it is estimated that it will take quite a long time until a patch that removes this banner is implemented and verified

**Comment by KobeW50** [comment]
> Because this banner is exposed quite rarely, it is not suitable for debugging

Would it eat my battery if I need on debugging and the logcat app running whenever I use YT RVX? Because I guess if you don't have it running until after an element appears, the litho won't show in the log, making it impossible to find the name of these types of components.

**Comment by bubuleur** [comment]
> Comme vous le dites, aucun correctif pour le supprimer n'a été implémenté
> 
> Parce que cette bannière est exposée assez rarement, elle ne convient pas au débogage
> 
> Par conséquent, on estime qu'il faudra beaucoup de temps avant qu'un patch qui supprime cette bannière soit implémenté et vérifié

c

**Comment by bubuleur** [comment]
> plemented and verified

Ok thank you for your answer
It happens to me about once a week

**Comment by kazimmt** [comment]
@inotia00 YT Premium is not available in my country (Bangladesh)
So whenever i connect vpn to a country where YT Premium is available, It shows me the banner (only once)
Any way I can help you to debug this issue?

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
