### ISSUE TITLE
feat(patch):  hide play / pause button

### ISSUE THREAD

**Issue by kikuok** [inotia00/ReVanced_Extended#1192]
### Application

YouTube

### Description

During playback in the player, you can remove almost all elements in the settings, but I want to make the pause and start button invisible. Everyone already knows what to press in the center of the screen to pause or start. Please make this button invisible.

I also want to ask for the ability to remove the top channel logo when going to the channel. This prevents you from immediately watching the video of the channel. You also need to first scroll through the "main" column and only then go to all the videos. Is it possible to automatically skip the "main" item and immediately see a list of all videos on the channel?

P.S. For some reason, my personal filter does not work, and the application crashes when I try to save the settings to a file. I have the latest version Magisk.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.

**Comment by StradivariusKane** [comment]
@inotia00 

Is it possible to hide it with custom filter?

**Comment by inotia00** [comment]
No it is not a litho component
That means you can't hide it with a custom filter.

This can theoretically be hidden, but if you do so, swipe gestures will not work.
