### ISSUE TITLE
suggestion: changes needed in `old quality layout`

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#1193]
### Application

YouTube

### Description

If `old quality layout` is enabled then in player flyout panel's quality row , only the currently applied resolution should be shown .

Current implementation -> Quality • Higher picture quality (1080p)
Correct way -> Quality • 1080p

Image for reference - 
Highlighted portion should be removed
![IMG_20230721_191801](https://github.com/inotia00/ReVanced_Extended/assets/64865031/e99b7f4c-98ef-43eb-9d6e-d73f25117433)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As far as I know, the second string displayed in the player flyout panel comes from the server side 🫠

**Comment by girshcatt** [comment]
No, inotia said this many times that he can't solve issues from server side or from clean yt
