### ISSUE TITLE
feat(patch): Hide Status and Navigation Bar

### ISSUE THREAD

**Issue by Thrifen** [inotia00/ReVanced_Extended#1194]
### Application

YouTube

### Issue

While, a minor issue, I would propose a patch to use an immersive mode similar to the one in Samsung Internet for OLED Burn-In Prevention.

[OLEDs suffer an issue that if a static image is displayed for a long period of time [hours to days] that static image is burned into the screen permanently]

### Patch

Essentially what I would like to ask is to hide the **_status bar_** and **_bottom navigation bar (Home, Subscriptions, Notifications and Library tabs at the bottom)_** to be **_hidden_**.

Here is a **_Samsung Internet_** Screenshot:
![Screenshot_20230721_151407_Samsung Internet](https://github.com/inotia00/ReVanced_Extended/assets/67480645/1c705905-186b-4e7c-a4fc-2a04cfb1c59c)

Here in Samsung Internet the status bar is hidden, but in the below screenshot the status bar is visible in RVX, if it is possible to add a patch where _**both**_ status and navigation bar are hidden. Unfortunately, both screenshots have the bottom navigation bar visible so I cannot demonstrate this with a screenshot, apologies. 

Here is an **_RVX_** Screenshot:
![SmartSelect_20230721_151525_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/67480645/56443b07-5b07-419e-ae62-104316bf94ef)

### Motivation

This would be helpful in preventing OLED Burn-In and it would allow more of the screen space to scroll, like _"**quality of life upgrade**"_, this would be useful to those with bigger screens and smaller screens alike. It also allows the user to use the full screen space.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with the following two issues
https://github.com/inotia00/ReVanced_Extended/issues/438 https://github.com/inotia00/ReVanced_Extended/issues/651
