### ISSUE TITLE
Next up screen 

### ISSUE THREAD

**Issue by Leomorningstar** [inotia00/ReVanced_Extended#1195]
### Application

YouTube

### Description

When a video end, a screen showin the next video apear, and i don't actually like it.
How can i make it stop?
![Screenshot_2023-07-21-17-24-20-445_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/140207506/98852986-94aa-4f37-bca7-f4d17077732a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
The issue is also in YT (in some cases). Probably A/B testing.

https://github.com/inotia00/ReVanced_Extended/assets/84587632/8ce0dcf0-576c-4483-866e-27a495eceea1

**Comment by Leomorningstar** [comment]
Well, is there any way to make this stop?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KobeW50** [comment]
I don't think so.

**Comment by Hennadz** [comment]
> this "Up next" screen only happens on one of my accounts and not the other.

The same situation.

**Comment by inotia00** [comment]
yep looks like an A/B test
