### ISSUE TITLE
microg_not_installed_notice

### ISSUE THREAD

**Issue by xShihaBx** [inotia00/ReVanced_Extended#1196]
### Type

Other

### Tools used

rvx-builder

### Application

18.25.40 magisk build

### Bug description

Though I flashed magisk module it alerts "microg_not_installed_notice"
and closes the apk
I installed microg from given link in the module discrimination but it remains same.
What should I do? 

### Steps to reproduce

Please fix this microg issue in root version 

### Relevant log output

```shell
I can't find log
```

### Screenshots or videos

![Screenshot_2023-07-22-05-00-55-434_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/106065024/7d35ddf3-384c-4e3d-9719-b655fce18db6)

### Device Environment

Android 13, Miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
I do not distribute the magisk module
