### ISSUE TITLE
feat(patch): disable next suggested video

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1197]
### Application

YouTube

### Issue

![Screenshot_20230722_023042_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/4fb03a8a-3c3c-43a7-886c-45b8ca5dd960)

### Patch

A toggle to disable it.

### Motivation

It is quite annoying because I keep playing the suggested video by accident.
And also because it will make YT cleaner.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Hennadz** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1195

**Comment by jhon1282** [comment]
I think it's a server side addition.
It also shows up in old versions 🤔

**Comment by jhon1282** [comment]
> I think it's a server side addition. It also shows up in old versions thinking A picture in picture option has also been added. ![IMG_20230722_212206](https://user-images.githubusercontent.com/125223735/255348002-723a5a17-0f77-4b58-9b9e-60da52559195.jpg)

I apologize, but why off topic?
The screenshot was taken at the end of a video reduced to picture in picture and concerns the same topic. The symbol highlighted by the arrow is equivalent to delete next video 🙄

**Comment by inotia00** [comment]
> I apologize, but why off topic?

Because it is literally off-topic

On the existing [issue page](https://github.com/inotia00/ReVanced_Extended/issues/1195), discussions have already been conducted on whether this is an A/B test or not, and we have drawn a conclusion about this
so.. this issue page is opened as a follow-up to [existing issues](https://github.com/inotia00/ReVanced_Extended/issues/1195) (patch-request)

Therefore, discussing whether this is an A/B test or not on this issue page can be seen as an off-topic

**Comment by jhon1282** [comment]
I apologize further then, mine just wanted to be an integration to the patch request, adding further information on the picture in picture player.
Thank you so much for your patience and your work, maximum respect ❤️

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.186.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.1)
