### ISSUE TITLE
question: <title>: rvx builder app version patch

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1198]
### Application

YouTube

### Description

Can we patch those version which are not marked as "recommended" and nor as "beta" ?

![Screenshot_2023-07-22-16-03-35-359_com microsoft emmx-edit](https://github.com/inotia00/ReVanced_Extended/assets/131557644/06cefdbf-faf2-482d-9a4b-b2be02dbc310)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You can try a patch with a non-recommended version (just for tests)
Of course, it doesn't guarantee normal operation

**Comment by Adity1243** [comment]
I tried and it causing error while patching that version.
