### ISSUE TITLE
question: <title>: The lower action bar in the player

### ISSUE THREAD

**Issue by Retarin** [inotia00/ReVanced_Extended#1199]
### Application

YouTube

### Description

I'm on the phone. At first I set up Youtube and the bottom bar of actions with a full-screen player disappeared somewhere, I went back to settings and found nothing, I didn't find anything in the usual Youtube settings either. I'll attach a picture of what I'm talking about now.
![303078730_d924ec07e0304eb9f779ac84db0c95ff_800](https://github.com/inotia00/ReVanced_Extended/assets/140263749/8ec9105d-25f7-4e8f-b64c-f8374a07e88c)
Version Vanced - 18.02.33 
Micro G - 0.2.23.220217
What to do? (sorry for my English)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] I have written the title and contents in English.

**Comment by inotia00** [comment]
v18.02.33 is an unsupported version
