### ISSUE TITLE
feat(patch): Player built-in video speed options

### ISSUE THREAD

**Issue by 11xjas** [inotia00/ReVanced_Extended#12]
### Application

ReVanced Extended

### Issue

Currently, Playback Speed option present at the bottom. It's uneasy to navigate everytime to the bottom to change the playback speed.

### Patch

Playback speed is the feature that we use often than any other features (i hope soo). But, currently the playback speed is present at the bottom.

### Motivation

So, it would be better if the "Playback Speed" option present somewhere in the middle or next to captions.

Just change the position to middle or next to captions.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Dhrubaof2002** [comment]
I think there is a better way of doing it , how about we add a small semi transparent icon at the bottom right corner of the video window which circles through a set of speeds

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)

**Comment by Spacellary** [comment]
Gotte say this is a pretty amazing patch haha
Thank you
