### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by laethy1** [inotia00/ReVanced_Extended#1200]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40

### Bug description

When I enabled the hook download button and pressed the download button, the video was downloaded in YouTube instead of externally and I tried restarting the app but to no avail.

### Steps to reproduce

1. Enable the hook download button and restart 
2. Go to a video and press the native download button
3. The video will be downloaded in the yt app instead of externally.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/121911559/40f82402-8a37-48f3-a121-16bb2f0d76da

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
You are using the Experimental Flags
