### ISSUE TITLE
bug: Sometimes copy link button isn't working properly

### ISSUE THREAD

**Issue by Dan-WiiU-Killer** [inotia00/ReVanced_Extended#1201]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40

### Bug description

Copy link (with timeline copy) sometimes goes buggy and copies only domain (and t=X) without direct link to the video.

Kinda frustrating when on Vanced this feature hasn't was happening this issue at all. It happened on earliest versions as well.

### Steps to reproduce

1) Watching some video, this feature sometimes works...
2) ...and sometimes is not. It's harder to produce, especially when I don't change any parameters in the settings.

### Relevant log output

```shell
(reporting via phone and it's closing browser with my all data, also I don't know how to do that)
```

### Screenshots or videos

![Screenshot_20230723_124258_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/40177282/8ff96b74-1f19-4205-b956-953d6c3262e5)
![Screenshot_20230723_124304_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/40177282/6bd72756-cacf-4072-8c4c-33104df41fea)
![Screenshot_20230723_124308_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/40177282/987c2d2f-ab2c-4297-a3db-0ca927089e11)

### Device Environment

STK-LX1 Huawei Honor, Android v10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Dan-WiiU-Killer** [comment]
Update: EMUI v12.0.0

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1139
