### ISSUE TITLE
bug(settings): feed flyout menus filter doesn't get imported

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1203]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.25.40
ReVanced Patches v2.184.3

### Bug description

When importing the exported RVX settings, it doesn't import the list inside the feed flyout menus filter.

I've checked that it does export the content inside the feed flyout menus filter in _json_, but for some reason it doesn't import it, leaving inside the filter the default "Report" and "Share".

### Steps to reproduce

Explained in description.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.186.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.10)
