### ISSUE TITLE
bug: Automatic translation not working

### ISSUE THREAD

**Issue by Layzalou** [inotia00/ReVanced_Extended#1204]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube Revanced 

### Bug description

Automatic translation provided in subtitles is not working.

### Steps to reproduce

Problem already described

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It's a YouTube bug, not a bug in ReVanced Extended
