### ISSUE TITLE
bug: `Disable playlist autoplay` applied to all videos

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1205]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.27.35
ReVanced Patches v2.186.1

### Bug description

`Disable playlist autoplay` is also applied to normal videos, videos that aren't played from inside a playlist.

### Steps to reproduce

1. Enable `Disable playlist autoplay`
2. Play a video **not** from inside a playlist, like directly from the homepage

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Ah, it doesn't just apply to the playlist

Always repeat button applies to both playlist and normal video

If you want it to apply only to the playlist, open issue with patch-request
