### ISSUE TITLE
feat(patch): apply `Disable autoplay` only to videos played from a playlist

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1206]
### Application

YouTube

### Issue

The feature `Disable playlist autoplay` is also applied to normal videos, videos that aren't played from inside a playlist.

### Patch

Apply the feature to only videos that are played from inside a playlist.

### Motivation

`Disable playlist autoplay`, as the name implies, should only be applied to videos that are played from inside a playlist.

I'm opening this request also because of this https://github.com/inotia00/ReVanced_Extended/issues/1205#issuecomment-1647470402.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
