### ISSUE TITLE
bug: Patching mMicroG failing

### ISSUE THREAD

**Issue by Spacellary** [inotia00/ReVanced_Extended#1207]
### Type

Error while patching

### Tools used

CLI
Revancify 

### Application

mMicroG `latest`

### Bug description

Patching mMicroG is failing with the [these errors](https://github.com/Spacellary/ReVanced-Extended-Automated-Builds/actions/runs/5642590811/job/15282743995#step:6:581).

With or [**without**](https://github.com/Spacellary/ReVanced-Extended-Automated-Builds/actions/runs/5642815685/job/15283420808#step:6:323) the MaterialYou patch there are issues.

### Steps to reproduce

Patch the latest mMicroG with Default patches.

### Relevant log output

```shell
revanced-builder | WARNING: error: resource style/Theme.Material3.DynamicColors.DayNight (aka com.mgoogle.android.gms:style/Theme.Material3.DynamicColors.DayNight) not found. 
revanced-builder | WARNING: error: resource style/Theme.Material3.DayNight.NoActionBar (aka com.mgoogle.android.gms:style/Theme.Material3.DayNight.NoActionBar) not found. 
revanced-builder | WARNING: /app/revanced-cache/res/values-v31/styles.xml:10: error: resource color/m3_sys_color_dynamic_dark_background (aka com.mgoogle.android.gms:color/m3_sys_color_dynamic_dark_background) not found. 
revanced-builder | WARNING: /app/revanced-cache/res/values-v31/styles.xml:11: error: resource color/m3_dynamic_dark_default_color_primary_text (aka com.mgoogle.android.gms:color/m3_dynamic_dark_default_color_primary_text) not found.
```

### Screenshots or videos

![Screenshot_2023-07-24-06-17-07-014_com termux](https://github.com/inotia00/ReVanced_Extended/assets/39604793/41e6db5c-5e38-4a93-b523-78c572f1bda3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Adity1243** [comment]
Here's screenshot of termux rvx builder error :-
![Screenshot_2023-07-24-20-28-50-293_com termux](https://github.com/inotia00/ReVanced_Extended/assets/131557644/f82eccab-b742-441f-95df-dbdaa2e1b0c2)

**Comment by inotia00** [comment]
So many different MicroG builds and MicroG patches confuse users

MicroG patches can also be provided by forking MicroG

So instead of fixing this issue, I will remove the MicroG patches in the next release

**Comment by Spacellary** [comment]
@inotia00 - Why not Target only your mMicroG fork?

I patch MicroG separately because I actually like the Revancify Red icon and now MMT's.

> MicroG patches can also be provided by forking MicroG

Will users need to fork or are you talking about your already existing fork (mMicroG)?

___

@hlytus What for you think?

**Comment by inotia00** [comment]
To maintain compatibility, mMicroG uses the same package name as Vanced MicroG

This is why we can't just target mMicroG

anyway.. I will later merge the features needed for the patch into the source of mMicroG, until then I will stop providing MicroG patches

**Comment by Spacellary** [comment]
> This is why we can't just target mMicroG

Ah, I meant _target_ the same way you target a version, not necessarily in a package name level, but to have it clear that users should patch your mMicroG or the old Vanced MicroG instead. Just in case having multiple sources is an issue.

👍

**Comment by inotia00** [comment]
> So many different MicroG builds and MicroG patches confuse users
> 
> MicroG patches can also be provided by forking MicroG
> 
> So instead of fixing this issue, I will remove the MicroG patches in the next release

patches have been removed temporarily
close the issue
