### ISSUE TITLE
feat(hide-shorts-component): hide sound button

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1209]
### Application

YouTube

### Issue

![Screenshot_20230724_002003_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/541c7d91-5d76-4642-912f-d4e507835efe)

### Patch

A toggle to hide and show it.

### Motivation

It would make the viewing of Shorts really clean, like complete full screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.

**Comment by Aryan-Chauhan** [comment]
> In case of YouTube, I have no plans to add new features.

Actually, this feature is already implemented in Alireza patches.

Or, one can just write "pivot" in their custom filters list.
