### ISSUE TITLE
question: How to change name of revanced_extended

### ISSUE THREAD

**Issue by KrishanMohanDev** [inotia00/ReVanced_Extended#121]
### Application

YouTube

### Description

Please tell me how to change name. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
If you are using ReVanced Manager, it is not possible

The package name or name of the app can be changed in `options.toml`

However, ReVanced Manager does not provide features to edit `options.toml`

If you are using rvx-builder you can

On Android (termux)...
0. You need to build rvx through rvx-builder at least once
1. In termux, type:
```
rvx-builder/options.timl
```
2. Change the value of `YouTube_AppName`
3. Save and start building through rvx-builder


https://user-images.githubusercontent.com/108592928/211184602-165f87b7-5d49-419a-a1b0-02ce97681740.mp4
attached video is how to changing the package name
Please refer it

※ Same for rvx-builder (Windows)
An `options.toml` file is created in the directory where rvx-builder.exe exists.
Open the file with a text editor and change `YouTube_AppName`
