### ISSUE TITLE
bug: Unselected patches also getting applied 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1210]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.27.35

### Bug description

As the title says when patching using RVX Manager, unselected patches are also showing up inside RVX Settings in YouTube.

### Steps to reproduce

1) Patch YouTube using RVX Manager.
2) Go into RVX YT settings and see unselected patches are there.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

Overlay button is not selected:
![Screenshot_20230724-170234~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/a795d88c-0f5e-44a1-95c1-363882d013ce)

Still present in settings:
![Screenshot_20230724-170203~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/69a8dde9-2b74-4c50-ad28-f61ffd105161)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Some patches are dependent

For example, if you include the patch `MicroG support`, the patch `Spoof player parameters` is included

If you include the `Hide Sugested Video Overlay` patch, the `Overlay butons` patch is included

The reason why it's dependent is because it requires a dependent patch to implement it

This is not a bug

**Comment by ILoveOpenSourceApplications** [comment]
What does `Hide Sugested Video Overlay` hide?
Also which all patches got dependency added to it?

**Comment by ILoveOpenSourceApplications** [comment]
Isn't it basically a modified `Hide Autoplay Preview Button`?

**Comment by inotia00** [comment]
There are so many patches that have dependencies that it's hard to enumerate

For example, every patch on YouTube is dependent on the `Settings` patch

All patches must have a switch added to `Settings` or added to `Patch Information`, so a `Settings` patch is required

The `Hide Sugested Video Overlay` patch is a patch that hides
https://github.com/inotia00/ReVanced_Extended/issues/1197

This patch is implemented as follows:
1. Add the ability to auto close the suggested video overlay when the first suggested video overlay is created
2. At the end of the video, detect the suggested video overlay and auto close it

The `Always Repeat` patch is required to recognize when the video is ended, and the `Always Repeat` patch belongs to `Overlay buttons` patch

Therefore, if you include the `Hide Sugested Video Overlay` patch, the `Overlay Buttons` patch is also included

**Comment by ILoveOpenSourceApplications** [comment]
> Isn't it basically a modified `Hide Autoplay Preview Button`?

Can you comment on this also if possible?

**Comment by inotia00** [comment]
> > Isn't it basically a modified `Hide Autoplay Preview Button`?
> 
> Can you comment on this also if possible?

'Hide Autoplay Preview' hides the following:
[ScreenShot](https://imgur.com/a/OhxdFY9)

If you need a screenshot for other all patches, go to the following documentation
[ReVanced-Extended-Community/Patches-Documentation](https://github.com/ReVanced-Extended-Community/Patches-Documentation#patches-with-screenshots)

**Comment by ILoveOpenSourceApplications** [comment]
> `Hide Autoplay Preview` hides the following: [ScreenShot](https://imgur.com/a/OhxdFY9)
Okay understood.
> 
> If you need a screenshot for other all patches, go to the following documentation [ReVanced-Extended-Community/Patches-Documentation](https://github.com/ReVanced-Extended-Community/Patches-Documentation#patches-with-screenshots)
I tried that. But apparently they're yet to update this based on the latest release.

Also, why overlay buttons? Whatever ` Hide Suggested Video Overlay` hides something within the YouTube app, whereas `Overlay Buttons` adds new buttons for extra features outside the YouTube app. I don't see why it had to be dependent on this patch specifically. It could've been linked with `Hide Autoplay Preview` as most people thought or it could be made like an individual patch just like all the other elements.

I have also noticed that `Spoof App Version` has a dependency on another patch, I believe it's 'Spoof Player Parameter` (correct me if I'm wrong). But why? It was working perfectly as an individual patch. Why add dependency now?

**Comment by inotia00** [comment]
> This patch is implemented as follows:
> 
> 1. Add the ability to auto close the suggested video overlay when the first suggested video overlay is created
> 2. At the end of the video, detect the suggested video overlay and auto close it
> 
> The `Always Repeat` patch is required to recognize when the video is ended, and the `Always Repeat` patch belongs to `Overlay buttons` patch
> 
> Therefore, if you include the `Hide Sugested Video Overlay` patch, the `Overlay Buttons` patch is also included

I have already provided enough explanations

**Comment by ILoveOpenSourceApplications** [comment]
> I have also noticed that `Spoof App Version` has a dependency on another patch, I believe it's 'Spoof Player Parameter` (correct me if I'm wrong). But why? It was working perfectly as an individual patch. Why add dependency now?

?

**Comment by inotia00** [comment]
If you include `Old Quality Layout` or `Custom Playback Speed` patch, the `Spoof App Version` patch is included.

In the tablet, the `Old Quality Layout` and `Custom Playback Speed` patches are not working in the new player flyout panel

Therefore, if a new player flyout panel is detected on the tablet, a suggestion is given to use the old player flyout panel by spoofing to v18.20.39 using the `spoofing app version`

This is why when you include 'Old Quality Layout' or 'Custom Playback Speed' patch, 'Spoof app version' is included

If you want to exclude the `Spoof app version` patch, you should exclude all of the following patches
- `Custom Playback Speed`
- `Old Quality Layout`
- `Spoof app version`

For the same reason, if you want to exclude 'Overlay buttons', you should exclude all of the following patches
- `Overlay buttons`
- `Hide Suggested Video Overlay`

**Comment by ILoveOpenSourceApplications** [comment]
Is it possible to have these patches implemented without these dependencies?

**Comment by ILoveOpenSourceApplications** [comment]
Thanks for your explanation. Hopefully everything turns out to be what the user wants and without dependency one day.

**Comment by inotia00** [comment]
yeah.. if I rewrite the overlay buttons patch later I will be able to separate it then

**Comment by ILoveOpenSourceApplications** [comment]
Till that day then.

**Comment by Narcissu-Moschus** [comment]
I hope you make Bilibili ReVanced! :)
