### ISSUE TITLE
question: <title>: Sponsor Block 

### ISSUE THREAD

**Issue by Death-q** [inotia00/ReVanced_Extended#1211]
### Application

YouTube

### Description

![Screenshot_20230721-235144](https://github.com/inotia00/ReVanced_Extended/assets/73420775/1640f28c-7070-49be-8806-38c50923c9de)
When i create a segment in a video and send.
Sometimes after 2 attempts, a segment appears, also with an error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The error is caused by the inability to access the SponsorBlock API literally in the toast message
Check if SponsorBlock's server is accessible
