### ISSUE TITLE
suggestion: Default speed option for YouTube Shorts

### ISSUE THREAD

**Issue by ray639** [inotia00/ReVanced_Extended#1213]
### Application

YouTube

### Description

Please add a default playback speed option for all YouTube shorts. This option  should be in the video settings section under the 'Default video speed' option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1147
