### ISSUE TITLE
feat(patch): placing of comments panel

### ISSUE THREAD

**Issue by javeedrahim** [inotia00/ReVanced_Extended#1214]
### Application

YouTube

### Description

Could you please change 'Add a comment' option to upside which is now below
![20230724_204454](https://github.com/inotia00/ReVanced_Extended/assets/136978675/429cc044-e3e1-4977-bad4-2a5a871f31b4)
. Its make difficult to read comments by placing it in below

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
