### ISSUE TITLE
suggestion: enable "play next in queue" feature 

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1216]
### Application

YouTube

### Description

Enables "play next in queue" feature to all users.
If it's possible then it would be nice to have it enabled since it's a just a simple queue option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
![Screenshot_2023-07-25-04-40-03-954_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/0fb60ecb-f77d-46d5-b6f3-d38deb616af4)

**Comment by Rairof** [comment]
After

> ![Screenshot_2023-07-25-04-40-03-954_app rvx android youtube-edit](https://user-images.githubusercontent.com/107706560/255684183-0fb60ecb-f77d-46d5-b6f3-d38deb616af4.jpg) Before

![IMG_20230725_044417](https://github.com/inotia00/ReVanced_Extended/assets/107706560/2be5bb85-1939-49a2-b2b9-31fb4094565d)
After

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/122
