### ISSUE TITLE
bug: RVX Manager doesn't sign APK correctly

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1217]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.27.35
ReVanced Patches v2.186.4

### Bug description

Trying to install YouTube RVX through RVX Manager always gives me this warning message:
![Screenshot_20230724_195804_Google Play Store](https://github.com/inotia00/ReVanced_Extended/assets/127908708/ff708e1e-cf66-4445-ab38-5e552cf26646)

I always chose to install anyway but whenever Play Store sent me a notification, YouTube just crashes.

So, I did some checking and found out that when the manager creates the APK, it doesn't sign it correctly.

This is the signature of the untouched YouTube APK:
![20230724_195157](https://github.com/inotia00/ReVanced_Extended/assets/127908708/13c40547-e3c1-4912-b60d-858f1f63da5a)

This is the signature of the APK created by RVX Manager where I get the warning message:
![20230724_194404](https://github.com/inotia00/ReVanced_Extended/assets/127908708/03e4a2e2-9fd9-435c-b848-dade94648989)

And this the signature of the APK created by RVX Manager which I signed it using an app used to sign APKs, and here I don't get any warning message:
![20230724_194917](https://github.com/inotia00/ReVanced_Extended/assets/127908708/d607e1bd-ed4c-4f10-83e7-80a46001f213)

### Steps to reproduce

Explained in description.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It is normal for the certificate owner to be marked only as ReVanced

Since only the developer has the original signature key, it is impossible to copy it

Google Play Protect warning is displayed simply because the signature is not registered in the Google Play developer account and is therefore not recognized by the developer

Google Play Protect alerts will no longer be exposed if you become fully aware of your signature over time
