### ISSUE TITLE
feat(patch): Audio equalizer for youtube extended

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1218]
### Application

YouTube

### Issue

Some videos has different volume levels.

### Patch

I already asked this patch while ago but that post i didnt saw now, so I'm asking again can you patch YouTube extended to use audio equalizer like used in MX player while playing the video we can adjust the sound effects.

![Screenshot_2023-07-25-01-08-36-751_com mxtech videoplayer ad-edit](https://github.com/inotia00/ReVanced_Extended/assets/131557644/d0d0d403-c0bc-4a67-ba01-3b4774d230d5)
![Screenshot_2023-07-25-01-11-38-974_com mxtech videoplayer ad](https://github.com/inotia00/ReVanced_Extended/assets/131557644/1ea08f7d-dfa0-409c-81a1-c9f9267c615b)
Like this 

![Screenshot_2023-07-25-01-09-36-214_app premium android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/131557644/7fcd4bc5-6ee0-4a05-8fff-c91259fd7635)
You can add that option on these side of places.

### Motivation

More control.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/397
