### ISSUE TITLE
feat(patch): Unlock queue system from premium to everyone

### ISSUE THREAD

**Issue by nochlab1** [inotia00/ReVanced_Extended#122]
### Application

YouTube

### Issue

youtube recently added a testing option for premium users adding a queue system, the page says available for testing till January 28 but it can still be a lot longer till youtube rolls it out for everyone

### Patch

Unlocking the queue feature for everyone 
![209454386-e85baa32-c984-4592-88a2-1d9c1501b336](https://user-images.githubusercontent.com/37608994/211184242-15469589-5f59-4791-aceb-451f4ac28bca.jpg)

### Motivation

Its already built in just has to be enabled for everyone and is a really great feature

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
