### ISSUE TITLE
question: <title>: Cards during video

### ISSUE THREAD

**Issue by gs775** [inotia00/ReVanced_Extended#1220]
### Application

YouTube

### Description

Hello I have been using RVX for a while and I noticed that clickable cards dont appear in the app unlike og YT

I would like to bring them back but I couldnt figure it out in its settings

How can I open clickable cards in the videos?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by gs775** [comment]
![2023-07-25 10_04_12](https://github.com/inotia00/ReVanced_Extended/assets/120893724/c4be0174-05bf-409b-998b-b5e032fef0fb)
Right forgot about image
As you can see cards appear normally in og youtube

But not in RVX

**Comment by inotia00** [comment]
![side_effect](https://github.com/inotia00/ReVanced_Extended/assets/108592928/e76f96d0-1098-4e67-80a3-900b4dac251d)

It is a side effect of the Spoof player parameter.

If you are using in ROOT environment simply turn off `Spoof player parameter`
