### ISSUE TITLE
bug(overlay-buttons): fullscreen icon does not match

### ISSUE THREAD

**Issue by MustafaErdqn** [inotia00/ReVanced_Extended#1221]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

YouTube v18.27.35

### Bug description

While watching any vertical video, the full screen maximize button appears as the original icon, even though the overlay button patch is installed, apart from that, after enlarging to full screen, the exit full screen button in the 2nd picture does not actually show the button suitable for vertical video, it shows the same button shown for normal videos.

Can you fix this problem?

### Steps to reproduce

Step 1. Open ReVanced
Step 2. Open any vertical video
Step 3. The zoom to full screen button will appear old style.

### Relevant log output

```shell
.
```

### Screenshots or videos

![IMG_01](https://github.com/inotia00/ReVanced_Extended/assets/126149028/5299597b-7152-4fe3-8e2f-50bec125e870)
![IMG_02](https://github.com/inotia00/ReVanced_Extended/assets/126149028/bb644dce-03cb-4f86-afef-38b0d4a1f973)

### Solution

Change icon file

### Device Environment

Android 13, One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It is reflected in the source, and will be applied to the next release

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.186.7](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.7)
