### ISSUE TITLE
feat(patch): Option to hide notify me button

### ISSUE THREAD

**Issue by ghost** [inotia00/ReVanced_Extended#1222]
### Application

YouTube

### Issue

I would like to have a setting that would hide Notify me button which appears under the premiere videos.

![Screenshot_20230725_191059_YouTube Premium](https://github.com/inotia00/ReVanced_Extended/assets/140536493/1abc71ec-bf9c-415a-b27d-6ca548f72a6e)

### Patch

Hide notify me button.

### Motivation

To hide a button that appears in between videos, useful for users who dont care about premiere stuff.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by MrNorthernLights** [comment]
Add reminder_button in the custom filter.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
