### ISSUE TITLE
feat(patch): hide NFL Primtime promotion

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1224]
### Application

YouTube

### Issue

It likely only pops up for americans

![Screenshot_20230725_132006_YT Extended](https://github.com/inotia00/ReVanced_Extended/assets/84587632/a5bcb08e-040f-400a-affa-2091be348c25)

### Patch

Add it to the ad filter.

When it appeared upon opening the app, I opened the logcat reader app and it seemed like this was the component.

Unfiltered (ID: null): image_centric_interstitial.eml|297d8edde71ae1dc|ContainerType|ScrollableContainerType|ContainerType|ContainerType|button.eml|d58dc95c2ec4305f|ContainerType|TextType|

![Screenshot_20230725_133547_Logcat Reader](https://github.com/inotia00/ReVanced_Extended/assets/84587632/bf56d96c-479d-49a5-8f30-1c7cce84e0bd)

### Motivation

Full screen promotions are annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This type of banner cannot be blocked with litho filter
Because even if we block litho component, there's a dark screen with nothing left

[related issue](https://www.reddit.com/r/revancedapp/comments/12w959l/revanced_darkens_on_open_cant_press_anything/)

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
