### ISSUE TITLE
App crashes after phone reboot

### ISSUE THREAD

**Issue by lijo807** [inotia00/ReVanced_Extended#1228]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.27.35

### Bug description

I just rebooted my phone and launched YouTube but it was just crashing wen launched 

### Steps to reproduce

Step 1: Patch YouTube on Revancify with root
Step 2: Open YouTube 
Step 3: Close YouTube
Step 4: Reboot your phone
Step 5: Try to open YouTube 

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/59694243/2f70ee87-d116-47b5-aa6d-8dfbe9ac06be

### Solution

You need to re-install YouTube Via Revancify

### Additional context

I just added a custon name but... i dont think that is causing the bug. Also YT Music work after the reboot 

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
The files associated with the root-type YouTube you installed before remains, and it causes crash

In other words, this is the issue of your side, not the issue of patches
I don't know which legacy is left in your ROM, so I can't help you

Look for the root-type YouTube you installed before and remove the legacy files manually
