### ISSUE TITLE
question: <title>: Full-screen player

### ISSUE THREAD

**Issue by Retarin** [inotia00/ReVanced_Extended#1229]
### Application

YouTube

### Description

I do not know if I could download YouTube on this site, but I downloaded it from another one, I hope it will not affect in any way.
Previously, I just had to click on any free space on the screen to close the pause button and the rest, but now I need to click on the cross in the top right corner of the screen, it's so unusual. So how do I get everything back to the way it was before? also, I do not understand how to remove 2 buttons for rewinding in the same player, that is, rewind to the button. Thank you in advance for the answer.
![IMG_20230726_140938](https://github.com/inotia00/ReVanced_Extended/assets/140263749/1abb5a67-1282-447f-80f0-92f8942ffade)
YouTube version - 17.33.42
MicroG - 0.2.24.220220
I apologize for asking questions so often and for my English And maybe I haven't fully looked through all the questions

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I do not distribute pre -built APK. Therefore, I can't judge whether the app you are using is Revanced Extended, so I can't help you
