### ISSUE TITLE
feat(patch): Sort By Oldest feature.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#123]
### Application

YouTube

### Issue

Many people like me are missing this sorting feature. So, kindly consider adding it.

### Patch

![IMG_20230108_132813](https://user-images.githubusercontent.com/91815107/211186559-0737bc4b-7f6b-447e-b7e8-55a2068feae3.jpg)

### Motivation

Lot of users that will actually use it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.171.4

**Comment by Aryan-Chauhan** [comment]
> reflected in revanced-patches-v2.171.4

I updated to 2.173.1 and could not find it

**Comment by inotia00** [comment]
![RVX1](https://user-images.githubusercontent.com/108592928/235977843-790b8928-f344-4ee5-8b9d-c447baeb038c.png)
1. You need to include the `spoof-app-version` patch
2. Settings > ReVanced Extended > Miscellaneous > Turn on Spoof app version
3. Select v17.06.35 in Spoof app version target

**Comment by Aryan-Chauhan** [comment]
>  
> ![RVX1](https://user-images.githubusercontent.com/108592928/235977843-790b8928-f344-4ee5-8b9d-c447baeb038c.png)
> 1. You need to include the `spoof-app-version` patch
> 2. Settings > ReVanced Extended > Miscellaneous > Turn on Spoof app version
> 3. Select v17.06.35 in Spoof app version target

Thank you.
