### ISSUE TITLE
bug(sponsorblock): video gets stuck at end of segments and keeps skipping

### ISSUE THREAD

**Issue by loustact** [inotia00/ReVanced_Extended#1230]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.29.38

### Bug description

It was just sudden. When Sponsorblock tried to skip the Sponsor and Self-Promotion segments, it gets stuck at the end of those segments and retries skipping multiple times as a result.

### Steps to reproduce

1. Go to a video
2. Wait until you reach a Sponsorblock segment
3. Seekbar gets stuck at the end of the segment and tries to skip multiple times

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://imgur.com/a/P05ToB9

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by lou-stro** [comment]
Hello, yeah. It is a bit weird. I tried tampering with the segments just now (since I set them to always skip) and now the issue's gone.

My patches version is `2.186.4`. Where do I find the `patch list`?

**Comment by lou-stro** [comment]
[inotia00-patches.txt](https://github.com/inotia00/ReVanced_Extended/files/12169831/inotia00-patches.txt)
I found the patches.json that Revancify uses. It should be this.

**Comment by inotia00** [comment]
If possible, I want to test it in the same environment.
Can you export the setting json?

You can export it in the following path
Settings> Revanced Extended> Miscellaneous> Import/Export Settings> Export Settings

**Comment by lou-stro** [comment]
Ok, but I have to rename it to a .txt since Github doesn't let me send the .json
[YouTube_v18.27.35_2023-07-26.txt](https://github.com/inotia00/ReVanced_Extended/files/12170310/YouTube_v18.27.35_2023-07-26.txt)

**Comment by lou-stro** [comment]
If it can't be replicated, I'll close down this issue. Though, this was a weird bug.

**Comment by lou-stro** [comment]
Issue seems to not persist after repatching through rvx-builder (since Revancify died)

**Comment by lou-stro** [comment]
Reopening issue again due to a better look at the bug. Video seems to skip at almost the end of segments, that's why it keeps skipping when segments are set to auto skip.


https://imgur.com/a/o3nckli

**Comment by inotia00** [comment]
Even though I found and tested the same video, the issue is not reproduced

**Comment by lou-stro** [comment]
Dang, that's weird indeed. May this be something like an isolated case? Kinda sucks that it isn't replicable...

**Comment by ayushTNM** [comment]
I have encountered this too in some cases
Usually when the video starts or ends with a segment that gets automatically skipped

**Comment by inotia00** [comment]
In [revanced-patches-2.190.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.4), SponsorBlock related code has been refactored.

Please re-patch with revanced-patches-2.190.4 and check if the issue still persists.

**Comment by loustact** [comment]
Yeap, seems there's no issues now! Thank you so much :D Ima close this issue now
