### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1231]
### Type

Cosmetic

### Tools used

Revancify

### Application

Youtube 18.27.35 - 18.20.39 with patches 2.186.1 and 2.186.4

### Bug description

This bug will appear in old layout 17.30.34. Like old layout user, after patching on 2.186.1+ i had bug with bottom panel of player when likes/dislikes doesn't show number and other buttons was from new layout, and buttons had wrong place

### Steps to reproduce

reccomended patches, not something unusual, like i patched always

### Relevant log output

```shell
i don't know what's this(
```

### Screenshots or videos

![Screenshot_20230726_123333_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/c2179f38-80f3-4cc8-b3e1-20caeac2f7a1)

### Solution

I don't have any solutions now

### Additional context

I tried to patch 18.20.39 this the same patches and the same bug. The same bug was this me on all my devices with new patches 2.186.1 and 2.186.4

### Device Environment

Tablet with Android 12, One Ui 4.1.1 and phone with Android 13, Miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
tbh this is an issue caused by YouTube's failure to load the layout normally from the server side

It has nothing to do with ReVanced, and it's an issue that Google needs to fix
