### ISSUE TITLE
feat(hide-layout-component): split the `hide community post in feed` into the `home feed` and `related videoes`

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1232]
### Application

YouTube

### Issue

![Screenshot_20230726_033707_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/61337f2d-d63e-422f-95a1-7b4f5ba56cfb)

### Patch

A toggle to hide and show them.

### Motivation

It would make YT cleaner.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
