### ISSUE TITLE
feat(overlay-buttons): add save to playlist button to overlay buttons

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1233]
### Application

YouTube

### Issue

The location of the Save button depends on the width of the likes and dislikes, so it's never in the same location, which is pretty annoying

### Patch

Make the Save button an overlay button

### Motivation

Explained in issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
