### ISSUE TITLE
Loop function

### ISSUE THREAD

**Issue by IvanOFC** [inotia00/ReVanced_Extended#1234]
### Application

YouTube

### Description

the loop function seems to be toggled even though I have it disabled , is there any other way to disable the loop function

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
There is not enough information about the issues you are experiencing
