### ISSUE TITLE
Videos freeze, with aloading black screen 

### ISSUE THREAD

**Issue by Timbbx** [inotia00/ReVanced_Extended#1235]
### Application

YouTube

### Description

My videos are not playing correct, they run a view seconds, cut off with a black screen and  the loading bar keeps on loading . I also can't click play animore on the Revanced version, it works fine if I just switch too normal YouTube. If I trie to skip a segment the video freezes completely.

Any recommendations how to fix this? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
use `spoof player parameter`

**Comment by Timbbx** [comment]
How do I find this? Is it in the settings somewhere or is it something that I have to install first?
