### ISSUE TITLE
feat(patch): hide "Shorts remixing this video" section from description

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1239]
### Application

YouTube

### Issue

![Screenshot_20230726_160947_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/130296934/2fb157b6-9dae-4cdb-96a8-31e72a8ef491)

### Patch

A toggle to show it and hide it

### Motivation

It would make Youtube cleaner

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1083
