### ISSUE TITLE
question: <title>: Is it possible to install older releases. 

### ISSUE THREAD

**Issue by fjdjyt** [inotia00/ReVanced_Extended#124]
### Application

YouTube

### Description

I'm being forced to install the most up-to-date version which doesn't work on my device. Is it possible to install an older release?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Depend on the situation
If you try to patch of too old version, it will probably be impossible
