### ISSUE TITLE
bug: Reddit patching error

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1240]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Reddit v2023.29.0

### Bug description

Gives multiple errors while applying patches 

### Steps to reproduce

Step 1. Download reddit app from apkmirror.com
Step 2. Get RVX manager installed and running
Step 3. Select reddit app and select all patches
Step 4. Click on done and start patching.

### Relevant log output

```Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Failed to apply Disable screenshot popup: 'Disable screenshot popup' depends on 'Reddit settings' but the following error was raised: 'Reddit settings' depends on 'SettingsBytecodePatch' but the following error was raised: Failed to resolve OssLicensesMenuActivityOnCreateFingerprint
Failed to apply Hide ads: 'Hide ads' depends on 'Reddit settings' but the following error was raised: 'Reddit settings' depends on 'SettingsBytecodePatch' but the following error was raised: 'SettingsBytecodePatch' did not succeed previously
Failed to apply Hide navigation buttons: 'Hide navigation buttons' depends on 'Reddit settings' but the following error was raised: 'Reddit settings' depends on 'SettingsBytecodePatch' but the following error was raised: 'SettingsBytecodePatch' did not succeed previously
Failed to apply Hide place button: 'Hide place button' depends on 'Reddit settings' but the following error was raised: 'Reddit settings' depends on 'SettingsBytecodePatch' but the following error was raised: 'SettingsBytecodePatch' did not succeed previously
Failed to apply Open links directly: 'Open links directly' depends on 'Reddit settings' but the following error was raised: 'Reddit settings' depends on 'SettingsBytecodePatch' but the following error was raised: 'SettingsBytecodePatch' did not succeed previously
Failed to apply Open links externally: 'Open links externally' depends on 'Reddit settings' but the following error was raised: 'Reddit settings' depends on 'SettingsBytecodePatch' but the following error was raised: 'SettingsBytecodePatch' did not succeed previously
Applied Premium icon
Failed to apply Reddit settings: 'Reddit settings' depends on 'SettingsBytecodePatch' but the following error was raised: 'SettingsBytecodePatch' did not succeed previously
Failed to apply Sanitize sharing links: 'Sanitize sharing links' depends on 'Reddit settings' but the following error was raised: 'Reddit settings' depends on 'SettingsBytecodePatch' but the following error was raised: 'SettingsBytecodePatch' did not succeed previously
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Screenshots or videos

None

### Solution

Fix all possible error while patching all patches

### Device Environment

Android 13 MIUI 14.0.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Rairof** [comment]
![Screenshot_2023-07-27-10-16-54-304_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/28a9f4c5-2d69-4c90-83d7-062f6f7f10a6)
![Screenshot_2023-07-27-10-20-47-171_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/56d60e3d-3635-4dd2-a133-974d9948cdbb)
![Screenshot_2023-07-27-10-21-19-348_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/0098f0c0-6647-47c0-9052-bd6527af1807)
![Screenshot_2023-07-27-10-21-28-488_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/c10740a4-7528-4323-9799-b1f615112ef3)

**Comment by Rairof** [comment]
It was successful in patching and repacking the apk but failed to patch most patches.

**Comment by inotia00** [comment]
It's not being reproduced
Uninstall the installed RVX Manager and reinstall it as [RVX Manager v1.4.3-2](https://github.com/inotia00/revanced-manager/releases/tag/v1.4.3-2)

And try again

**Comment by Rairof** [comment]
> It's not being reproduced Uninstall the installed RVX Manager and reinstall it as [RVX Manager v1.4.3-2](https://github.com/inotia00/revanced-manager/releases/tag/v1.4.3-2)
> 
> And try again

Issue still persists in RVX Manager v1.4.3-2
![Screenshot_2023-07-27-10-41-28-694_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/2226058b-d7ac-4289-93cc-e3e9220746d9)
![Screenshot_2023-07-27-10-41-37-647_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/7bafb11d-5a3e-40c8-ab9b-05a352ff7b8d)
![Screenshot_2023-07-27-10-41-43-186_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/298a105f-6db1-4d9e-82ec-7db3f098851f)

**Comment by Rairof** [comment]
Reinstalled RVX Manager instead of just updating it just to be sure but didn't worked.

**Comment by inotia00** [comment]
then i have no idea
try a different patch method

**Comment by Rairof** [comment]
> then i have no idea
> try a different patch method

Well alright I will try on revancify

**Comment by inotia00** [comment]
okay.. closing issue
