### ISSUE TITLE
bug: `shorts` related patches appearing in wrong order

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1241]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube v18.27.36

### Bug description

When patching the YouTube app via RVX Manager, the shorts patches, i.e, `Disable Shorts on startup` & `Hide Shorts components` appear in a non alphabetical order within the manager.

### Steps to reproduce

1) Patch YouTube with any `Shorts` related patch.
2) Notice that it's out of order alphabetically.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

![Screenshot_20230727-010048~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/44f73c30-2bd8-4d90-af1e-ac270194fe24)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
lol how did you find it

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.186.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.186.10)
