### ISSUE TITLE
question: <Questions about resolution issues>: 

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1242]
### Application

YouTube

### Description

Can pure and revanced extended versions have resolution issues using the same mcirog?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
nah.. not related to microg
And there is already a duplicate issue open
