### ISSUE TITLE
bug: Infinite buffering issue

### ISSUE THREAD

**Issue by chandamanab** [inotia00/ReVanced_Extended#1244]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.27.36

### Bug description

Facing infinite buffering issue on specific videos. I've tried everything mentioned in group but nothing seems to work even spoof player parameter, spoof player parameter type and spoof app version. None of them fixes the issue but when I use revanced more specifically revanced v18.23.35 there's no issue like that exists so could you please look into it and see if it can be fixed. This issue is really annoying and a deal breaker and many people are facing it so please look into it.

### Steps to reproduce

Open YT RVX > Open a video and you may or may not face the issue. Even doing everything mentioned in group doesn't fix it.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-07-27-20-29-50-49_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/inotia00/ReVanced_Extended/assets/103749965/45411ed3-6692-4db8-9a48-1a22e739fa34)

### Device Environment

Android 12, Realme 9 Pro+

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
duplicate with https://github.com/inotia00/ReVanced_Extended/issues/1238
