### ISSUE TITLE
Home screen feed loading stops

### ISSUE THREAD

**Issue by rtsbora** [inotia00/ReVanced_Extended#1245]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Revanced 18.17.43

### Bug description

While i am swiping down my home page, after 5-10 video loads, no new video comes. Feed stops. 

### Steps to reproduce

No

### Relevant log output

```shell
No
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
re-patch with latest resource
