### ISSUE TITLE
suggestion: <The revancify app disappears>: 

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1249]
### Application

YouTube

### Description

https://t.me/revancifychat/35696?single

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is the Revamped Extended repo, not the Revancify repo

Furthermore, I am not a maintener of Revanify, so there is nothing I can do even if you tell here

Suggestions to their group
