### ISSUE TITLE
Hide compact banners not working

### ISSUE THREAD

**Issue by Suvam-007** [inotia00/ReVanced_Extended#125]
### Application

YouTube

### Description

Hide compact banners option not working even after restarting the app. The COVID banners are still visible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
`Hide compact banners` setting does not hide Covid-19 information

to hide Covid-19 information, turn on `Hide info pannel` setting

**Comment by Suvam-007** [comment]
Then what "Hide compact banners" option does?

**Comment by inotia00** [comment]
That setting was added by ReVanced Team.
If you want to know exactly what part it removes, ask the ReVanced Team
