### ISSUE TITLE
bug: <Video stuck on 1:10 even with "spoof" setting>

### ISSUE THREAD

**Issue by mihaaairu** [inotia00/ReVanced_Extended#1250]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube V18.27.36

### Bug description

Video sticks every time on 1:10 time (±5sec). Loading circle appears and that's all. If the player was playing in blackground, the video picture will not be displayed and loading circle will be loading on a black screen. I've tested with reinstalled app (without any setup) and with "spoof player parameters" (already have used this setting, as long as very close problem appeared some time ago, but was successfully fixed with this setting). But this setting didn't help.  Plus it's not possible to scroll timeline. Every timecode after 1:10 will stuck. 
Also, I've searched this issue, but every time it was fixed with spoof setting, which stopped work for me...

### Steps to reproduce

Just start video and watch it a bit. After 1:10±5 sec video will stuck. 

### Relevant log output

```shell
Sorry, but where can I find it?
```

### Device Environment

Huawei Nova 3 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by neko-astolfo-uwu** [comment]
Same issue here on s23 ultra, checked multiple times, its not a network issue. Youtube probably did something.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1238

**Comment by trongkhanhcb102** [comment]
I changed the account and it worked, but I just want to use the old account to watch it.
