### ISSUE TITLE
bug: Fullscreen panel doesn't work on z fold4

### ISSUE THREAD

**Issue by Nobodyo2theg** [inotia00/ReVanced_Extended#1251]
### Type

Other

### Tools used

rvx-builder

### Application

Revanced: v 18.27.36
Rvx manager: 1.4.3-2

### Bug description

Even though I apply display fullscreen panels or disable it as some have mentioned, it won't display then panel in full screen and it's driving me nuts on my z fold4, one ui 5.1, android 13. 

### Steps to reproduce

Step 1. Add display fullscreen panel patch 2. Patch 3. Open revanced 4. Play any video in full screen/landscape and no panels appear. 

### Relevant log output

```shell
I don't know how to do that.
```

### Screenshots or videos

![Screenshot_20230728_050159_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/140780004/d05f97f4-4ee8-4701-a1d9-46d2c97b5524)

### Solution

Make it work? Lol.

### Device Environment

Android 13, One UI 5.1, Z Fold4 

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Fullscreen panels are not supported on tablet devices

This is the same for unpatched YouTube
