### ISSUE TITLE
suggestion: add the popup help/screenshot for each setting

### ISSUE THREAD

**Issue by Sappurit** [inotia00/ReVanced_Extended#1253]
### Application

YouTube

### Description

Since there are a ton of settings, I have been using RVX for 5 months but still don't know all the settings.
And I just saw good screenshots at https://github.com/ReVanced-Extended-Community/Patches-Documentation#youtube

Is it reasonable to add ⓘ or something to display the popup help/screenshot for each setting?

![Screenshot_2023-07-28-16-42-36-125_rvx google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/80998766/c07b0eef-a348-4b2c-ae4e-490a3b86cbc3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Inotia starred the people who made screenshot of every patch/setting, here the repo
https://github.com/ReVanced-Extended-Community/Patches-Documentation
