### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Paulfargeix** [inotia00/ReVanced_Extended#1254]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Youtube 18.02.33

### Bug description

Vidéos can't run anymore after more than 1:10 minutes, you can't also move the vidéos forward 

### Steps to reproduce

Watch a vidéo to more than 1:10 minutes, or just advance in any vidéo 

### Relevant log output

```shell
Idk what to write here
```

### Screenshots or videos

![Screenshot_20230728_112529_com vanced android youtube](https://github.com/inotia00/ReVanced_Extended/assets/140807077/7cc15a55-a43f-4b22-821c-0c58ce741ad0)
![Screenshot_20230728_112540_com vanced android youtube](https://github.com/inotia00/ReVanced_Extended/assets/140807077/1cf91abc-b295-4bd0-b7d1-fc7b4466fe96)

### Solution

Make vidéo able to run their full time

### Device Environment

EMUI 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Version that does not support
