### ISSUE TITLE
bug: Video is stop playing after few seconds

### ISSUE THREAD

**Issue by Shuhaib-basheer** [inotia00/ReVanced_Extended#1255]
### Type

Error while running 

### Tools used

ReVanced Manager

### Application

Version 18.14.40

### Bug description

Video will only play for first few seconds then show loading animation.
This is on every videoes larger than 1 minutes.shorts don't have problem even small videos less than 1minute.

### Steps to reproduce

Step 1: play any video

### Relevant log output

```shell
I don't know how to get it.
```

### Device Environment

Android 13 , realme ui 4.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
repatch with latest resource
