### ISSUE TITLE
All videos are blocking at 1min 09 bug: <title>

### ISSUE THREAD

**Issue by malikLeFou** [inotia00/ReVanced_Extended#1258]
![Screenshot_2023-07-28-17-10-44-646_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/66025660/9c113d59-0d9b-4ecb-bbe9-588f345b78e1)
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Youtube revanced 18.14.40
Revanced patch 2.168.36
Revanced integration 0.101.36

And after update
Youtube revanced 18.26.36
Revanced patch 2.186.8
Revanced integration 0.114.8

### Bug description

Good morning, i have an issue, all the videos that i want to watch are blocking at 1min09 
(The video is ok from 0:00 to 1:09 and after that, I have a black screen with the "buffering circle")

### Steps to reproduce

I just have to watch a video more than 1:09 minutes 

### Relevant log output

```shell
Iam not sure to know what is it
```

### Screenshots or videos

![Screenshot_2023-07-28-16-25-16-589_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/66025660/bd419024-0661-487b-af21-428a3d4299b8)

Screenshot of the issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Fkkbjnbhnb** [comment]
I have zero issues with my playback, all videos play normally. No buffering or pausing. Im using s23 ultra.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1238

**Comment by cookie9822** [comment]
Hey I had the same Problem with last Version I just now installed the latest YouTube  Revanced I can't log in or add my Google account to Sign in to the Revanced App it just says this account already exists on this device but  I can't add my Account did the previous Revanced Version get my Google account banned by simply using the Revanced App pls anybody help do I need to make a new Google account that would definitely suck ass pls help asap
