### ISSUE TITLE
feat(patch): Hide 'Get Yotube Premium' text from video description

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1259]
### Application

YouTube

### Issue

a patch to hide 'Get Youtube Premium' from video description

### Patch

![photo_6206121571584686639_w](https://github.com/inotia00/ReVanced_Extended/assets/87489540/564e113c-e427-41cf-b6c5-f3176985be46)

### Motivation

it's unnecessary

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
@MondayNitro Go to Setting --> General then scroll down to Description group and turn on Hide Music Section
