### ISSUE TITLE
Compact banners

### ISSUE THREAD

**Issue by Suvam-007** [inotia00/ReVanced_Extended#126]
### Application

YouTube

### Description

What is the work of "Hide compact banners" as it is not hiding COVID warnings then what does it do basically. Help me with a screenshot.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/125
