### ISSUE TITLE
feat(patch): Hide shorts player flyout menu components

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1260]
### Application

YouTube

### Issue

a patch to hide options presents in shorts player flyout menu

### Patch

![photo_6206121571584686638_w](https://github.com/inotia00/ReVanced_Extended/assets/87489540/ccd150b9-ec8b-489f-ad52-eb042d9549f3)

### Motivation

This patch will allow for removal of unwanted elements

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
