### ISSUE TITLE
Bug: Video buffering even though the internet is fast

### ISSUE THREAD

**Issue by Xhinmaranan** [inotia00/ReVanced_Extended#1261]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube Version 18.27.36

### Bug description

Yesterday it was working but when i wake up and use revance extended and watch one video and then like 1 minute if the video it buffered and cant play

### Steps to reproduce

Step 1: open the app
Step 2: play one video
Step 3: wait a couple of minutes until you see the buffer

### Relevant log output

```shell
Nothing
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/140836942/d04605f4-826f-4141-bffb-762c637b2b9f

### Solution

Turning on spoofing but it didn't work on me i am the most unluckiest teen in the world and the miserable one

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by madhusudhankm** [comment]
I am also facing same issue

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1238
