### ISSUE TITLE
question: <Is it true that you stop developing apps?>: 

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1262]
### Application

YouTube

### Description

What's the reason? Can we meet again later?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by User-noob2036876** [comment]
It will continue with another project. Do not be afraid.

**Comment by YT-Advanced** [comment]
@User-noob2036876 What's project are you mentioning ?

**Comment by User-noob2036876** [comment]
> @User-noob2036876 What's project are you mentioning ?

We don't know what his name will be.

**Comment by YT-Advanced** [comment]
@User-noob2036876 But he said that he will discontinued and didn't mention about continue

**Comment by hoang-himself** [comment]
I am out of the loop here. What happened?

**Comment by User-noob2036876** [comment]
> @User-noob2036876 But he said that he will discontinued and didn't mention about continue

Idk

**Comment by YT-Advanced** [comment]
Hmm, look like it is true. So I will continue it as much as I can !
