### ISSUE TITLE
Patching error

### ISSUE THREAD

**Issue by antoniosamantos** [inotia00/ReVanced_Extended#1264]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube version 18.29.38 (suggested version) 

### Bug description

 Can't patch, error while applying patches. 

### Steps to reproduce

Step 1 include default patches
Step 2 patch

### Relevant log output

```shell
Look up at screenshots
```

### Screenshots or videos

![Screenshot_20230730_134433_app revanced manager flutter](https://github.com/inotia00/ReVanced_Extended/assets/120720375/c31b7026-4b4e-4381-b80c-25631859081e)
![Screenshot_20230730_134439_app revanced manager flutter](https://github.com/inotia00/ReVanced_Extended/assets/120720375/ba2d6844-88f9-499d-8ff9-75eabc4d2598)
![Screenshot_20230730_134443_app revanced manager flutter](https://github.com/inotia00/ReVanced_Extended/assets/120720375/be79418c-4132-417e-b259-c6900170aa38)

### Device Environment

MIUI 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
update mamager
https://github.com/inotia00/revanced-manager/releases/tag/v1.4.3-2

**Comment by antoniosamantos** [comment]
Thank you so much!
