### ISSUE TITLE
suggestion: YouTube spoof: Keep both spoof player parameter and parameter type in setting 

### ISSUE THREAD

**Issue by shreyjain1998** [inotia00/ReVanced_Extended#1265]
### Application

YouTube

### Description

Can you please keep both the options in settings like before? Till v2.186.8, only Spoof player parameter use to fix the playback issue for many so we can disable the other one and can have seekbar thumbnail and ambient mode, etc. And for those who still face the buffering issues enable both.

Or would that be possible to add 'spoof-method' patch with the official revanced and revanced extended methods as the options?

![256641127-e7e8ee08-d0b4-4066-b07b-1f10d7700b41](https://github.com/inotia00/ReVanced_Extended/assets/107779107/7f21dfc3-6abc-4b60-8d3c-1f15d3356051)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by MondayNitro** [comment]
yes please sir. only a handful of users face that playback issue. my suggestion is keep incognito to default and allow switch to shorts

**Comment by MondayNitro** [comment]
> yes please sir. only a handful of users face that playback issue. my suggestion is keep incognito to default and allow switch to shorts

apparently its not an rvx issue, a lot of revanced users are facing playback issue as well and hence the point of removing short type spoof doesnt serve the intended purpose

**Comment by limonetas** [comment]
Just go rollback versión

**Comment by inotia00** [comment]
Unfortunately this is not in the plan

Previously, It was able to select the spoofing type in the settings.
For some reason, spoofing did not work normally for some people when it was implemented to be able to select the spoofing type.

https://github.com/inotia00/ReVanced_Extended/issues/1238

**Comment by shreyjain1998** [comment]
@inotia00  Thanks for the reply. I'm a big fan of your work and thanks for everything you have done so far.

Just wanted to know whether adding a 'spoof-method' makes sense? It can have official ReVanced as a default method but if we could select ReVanced extended split spoof method than it would be great too.

**Comment by shreyjain1998** [comment]
> Just go rollback versión

Unfortunately, I deleted the old apk and I don't even think we can patch with the older versions of revanced-patches or integrations. Please let me know if I'm wrong. Thanks.

**Comment by limonetas** [comment]
> > Just go rollback versión > > Unfortunately, I deleted the old apk and I don't even think we can patch with the older versions of revanced-patches or integrations. Please let me know if I'm wrong. Thanks.

if you leave your discord, I'll add you.

**Comment by shreyjain1998** [comment]
> if you leave your discord, I'll add you.
shreyjain98. Thanks.
