### ISSUE TITLE
feat(patch): hide some parts from description

### ISSUE THREAD

**Issue by thePJ23** [inotia00/ReVanced_Extended#1267]
### Application

YouTube

### Issue

Hide these parts from description as shown in image 

### Patch

![IMG_20230730_172908](https://github.com/inotia00/ReVanced_Extended/assets/118048756/0cd28b44-bb03-49d9-95b1-bb1ed8a2f122)

### Motivation

Unnecessary 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
