### ISSUE TITLE
Video Keeps Buffering 

### ISSUE THREAD

**Issue by Naveon** [inotia00/ReVanced_Extended#1268]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Yt Vanced 18.02.33

### Bug description

Video starts buffering after around 1 minutes of playback. Tried enabling/disabling vp9 codec spoofing but nothing worked. Help please.

### Steps to reproduce

Started automatically when playing any video

### Relevant log output

```shell
No logs available
```

### Screenshots or videos

![Screenshot_2023-07-30-18-01-42-84_7a4090f09f6554852d748ee9fd6f40d3](https://github.com/inotia00/ReVanced_Extended/assets/24990767/ac7da13f-436b-4048-b7ed-937c3bc339a1)

### Device Environment

Android 13, Realme UI 4.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Hennadz** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1238#issuecomment-1657091062
