### ISSUE TITLE
Home page video names bug

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1270]
### Type

Cosmetic

### Tools used

Revancify

### Application

Youtube 18.29.38

### Bug description

Just go in search and go out, and video names will dissappear. Had this bug from the day i started use rvx many months ago, it will appear at any settings at any version
![Screenshot_20230730_153622_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/88ca20c5-4c25-450c-840c-0a4b1bf443dd)

### Steps to reproduce

https://github.com/inotia00/ReVanced_Extended/assets/110785596/39aeb815-f6e9-4715-b5f8-8ac88aee6aae

### Relevant log output

```shell
idk how get log
```

### Screenshots or videos

![Screenshot_20230730_153622_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/cdd0f9bc-c3fc-4b32-a438-dce43aa78dab)

### Device Environment

Android 12 One ui 4.1.1, Android 13 MIUI 14.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
I know that this problem also in clean Youtube, but can you fix it with patch?

**Comment by inotia00** [comment]
Official YouTube bugs cannot be fixed on my side

Also, if you are using a tablet, patch to YouTube v18.20.39
