### ISSUE TITLE
seekbar thumbnails are hidden

### ISSUE THREAD

**Issue by cavidmammadov** [inotia00/ReVanced_Extended#1271]
### Application

YouTube

### Description

What should I do to keep it from being disabled?
![IMG_20230730_164625](https://github.com/inotia00/ReVanced_Extended/assets/121347981/66471c4a-369a-4b73-a2ad-30f37500771f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Hennadz** [comment]
Find a solution without this side effect. Write code and implement it in patches.

**Comment by vuongvan** [comment]
You can try old patches ver 2.186.8.
Seeker thumbnail not working on latest patches version

**Comment by CodElixer** [comment]
> You can try old patches ver 2.186.8.
> Seeker thumbnail not working on latest patches version

How to apply old patches like 2.186.8 to fix seekbar filmstrip in Revanced Manager Extended(https://github.com/inotia00/revanced-manager/releases/latest) app?

**Comment by vuongvan** [comment]
> > You can try old patches ver 2.186.8.
> > Seeker thumbnail not working on latest patches version
> 
> How to apply old patches like 2.186.8 to fix seekbar filmstrip in Revanced Manager Extended(https://github.com/inotia00/revanced-manager/releases/latest) app?

You must use CLI to apply old patches.
`Youtube apk: 18.27.36
CLI: inotia00/revanced-cli-2.22.2-all.jar
Integrations: inotia00/revanced-integrations-0.114.10.apk
Patches: inotia00/revanced-patches-2.186.10.jar`

Command sample:
`java -jar revanced-cli.jar -c -a com.google.android.youtube.apk -o youtube-revancedx.apk -b revanced-patches.jar --revanced-integrations.apk -i microg-support`

[How to use Revanced CLI for non-root users (](https://www.reddit.com/r/revancedapp/comments/11b6zy4/how_to_use_revanced_cli_for_nonroot_users_step_by/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button)
