### ISSUE TITLE
feat(patch): hide artist info in search results

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1272]
### Application

YouTube

### Issue

there's an artist info panel just above the search results. please add a patch to hide it.

### Patch

![photo_6213074599650899746_w](https://github.com/inotia00/ReVanced_Extended/assets/87489540/33590b80-6c70-4e25-b16f-b76feccb3f19)

### Motivation

makes ui better

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
already implemented

`Hide official header`
