### ISSUE TITLE
Lyrics not showing 

### ISSUE THREAD

**Issue by tuxnowar** [inotia00/ReVanced_Extended#1273]
### Type

Other

### Tools used

ReVanced Manager

### Application

Youtube Music 6.10.53

### Bug description

The patched app doesn't show lyrics, while normal app does.

### Steps to reproduce

just try to read lyrics from any song, even the most popular show no lyrics found

### Relevant log output

```shell
no log for this issue sorry
```

### Screenshots or videos

![Screenshot_2023-07-30-16-00-18-911_com google android apps youtube music](https://github.com/inotia00/ReVanced_Extended/assets/99463588/cba77f5d-5680-4375-8fb3-cfa1d1c0a36a)

### Device Environment

MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by s7san007** [comment]
Spoof app version to 4.27.53 for Canadians.

**Comment by inotia00** [comment]
bugs in official YouTube Music cannot be fixed on my side
