### ISSUE TITLE
Add color settings 

### ISSUE THREAD

**Issue by cavidmammadov** [inotia00/ReVanced_Extended#1274]
### Application

YouTube

### Description

Is it possible to add color options?  add color options like twitter for example?
![IMG_20230730_170410](https://github.com/inotia00/ReVanced_Extended/assets/121347981/97e58202-a49c-432c-b77a-ccdd0efe4f8c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/43
