### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by beloya9358inkin** [inotia00/ReVanced_Extended#1275]
### Application

YouTube

### Issue

Video stop and buffing issue 

### Patch

![Screenshot_20230730-205432_YouTube Vanced+](https://github.com/inotia00/ReVanced_Extended/assets/140965593/1c339cc0-d796-4baa-a022-3e98955cbd63)

### Motivation

To slove issue 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
repatch with latest resource
