### ISSUE TITLE
bug: buffering problem 

### ISSUE THREAD

**Issue by Danny11500** [inotia00/ReVanced_Extended#1276]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v0.102.5

### Bug description

Video stops playing and starts buffering at 1 min mark 

### Steps to reproduce

Fix buffering issue 

### Relevant log output

```shell
No idea what that's is
```

### Screenshots or videos

![Screenshot_20230730_202259_YouTube ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/140965243/af905fe3-64a6-441a-8f69-58b69e762256)

### Solution

Plz fix this issue 

### Additional context

Other then this issue love using your app

### Device Environment

Samsung galaxy S2 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
update with latest resource
