### ISSUE TITLE
bug: <sponsorblock and dislike/dislike icons don't disappear>

### ISSUE THREAD

**Issue by vordx** [inotia00/ReVanced_Extended#1277]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

All the last versions since you came back from the vacation:) 

### Bug description

When you're on Fullscreen, the sponsorblock and the dislike back module icon on the right top corner are shown the whole time watching the video which cause burn in.

### Steps to reproduce

Watch any video in full screen and skip 10 seconds forward or backwards and see the icons showing up and not disappearing again. 

### Relevant log output

```shell
No log needed
```

### Screenshots or videos

![Screenshot_20230730_182508_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/39927714/e8c0a85e-1274-4ddf-b5b8-a521424a43ef)

### Solution

Not sure how to hide them, you're the legend :)

### Device Environment

Android 13, Galaxy s22U snapdragon. One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1165
