### ISSUE TITLE
suggestion:Remove the reference to this page from the application

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1278]
### Application

YouTube

### Description

![IMG_20230730_170638](https://github.com/inotia00/ReVanced_Extended/assets/125223735/e47fecbc-3eb5-413b-b35b-10fea4d3ba69)
I know it will be useless by now, but if by any chance you decide to change your mind and continue with the project, I suggest you remove the reference to this page from the patches.
This would prevent those who download pre-compiled Apks from coming here to complain about various bugs.
I would put the reference to this page only on your official channels.
Thank you very much for your work and I hope to meet you again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
already reflected in the commit
will be applied in the next release

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.186.12
