### ISSUE TITLE
bug: little cosmetic bug with overlay buttons

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1279]
### Type

Cosmetic

### Tools used

Revancify

### Application

Youtube 18.29.38

### Bug description

When i tap at player and tap fullscreen overlay buttons appear on screen for 1 second

https://github.com/inotia00/ReVanced_Extended/assets/110785596/830e548f-07e0-4235-97e7-9e6395e67f18

![Screenshot_20230730_182408_Gallery](https://github.com/inotia00/ReVanced_Extended/assets/110785596/43b1e1ee-c644-47a7-abbb-4792d6542379)

### Steps to reproduce

all that i said in description

### Relevant log output

```shell
log needless in this situation
```

### Device Environment

Android 12 OneUi 4.1.1, Android 13 MIUI 14.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [x] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It cannot be solved because it is a issue that is not reproduced

**Comment by girshcatt** [comment]
This is issue that appears only in tablets(
