### ISSUE TITLE
feat(patch): Remove unnecessary options from shorts

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#128]
### Application

YouTube

### Issue

There are options like captions , use sound, etc. Please remove these.
Or if possible (which I think impossible), please map the 3-dot button to only open description of video.

### Patch

Pls add options for shorts to remove these unnecessary options like captions etc.

### Motivation

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/151
