### ISSUE TITLE
bug: <This is really big problem with shorts>

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1280]
### Type

Other

### Tools used

Revancify

### Application

Youtube 18.29.38

### Bug description

This bug appear more often on my phone, but sometimes on tablet too. When i open shorts from yt nav bar of srom shorts panel i see "video is not available" and it automatically goes next video, and next video appear on half a screen. When i go on first "not aviable video" and surprise, it plays normally. When i go on second "half a screen video" it plays normally too. This is really valid issue because i checked clean yt version, and all right, this is rvx problem, not server side

https://github.com/inotia00/ReVanced_Extended/assets/110785596/b106f28b-a6de-4d9b-a983-9eb4a76ffed7

https://github.com/inotia00/ReVanced_Extended/assets/110785596/8950c4cd-1ed0-4cf3-80db-7c98e7cc3eff

### Steps to reproduce

Written in description

### Relevant log output

```shell
.
```

### Device Environment

Android 13 MIUI 14.0.1, Android 12 OneUI 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
1. patch to YouTube v18.20.39
2. exclude `optimize-resource` patch

**Comment by girshcatt** [comment]
thanks
