### ISSUE TITLE
bug: <auto back problem>

### ISSUE THREAD

**Issue by Nitesh773** [inotia00/ReVanced_Extended#1281]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube revanced version 18.29.38
When we watch videos after 3 the app will auto closed in middle of the vedio
In Android 8

### Bug description

Please try to solve my problem 

### Steps to reproduce

Auto app close during operation 

### Relevant log output

```shell
Auto close
```

### Device Environment

Android 8.1
Device Vivo y93

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Nitesh773** [comment]
Close during the playing the vedio

**Comment by inotia00** [comment]
attach video
