### ISSUE TITLE
bug: two settings conflict

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1282]
### Type

Cosmetic

### Tools used

Revancify

### Application

Youtube 18.20.39

### Bug description

I found two settings conflict: shorts panel on home page shown and reccomendation section hide
When i did this settings on first restarts all was normal: all rec sections hidden and shorts panel shown, but after few restarts i didn't see shorts panel and see all rec sections.
I checked settings and didn't see any change
After many restarts i understood that this settings in conflict worked RANDOMLY, on some restart rec sections shown and shorts no, on other rec sections hidden and shorts shown

### Steps to reproduce

in description

### Relevant log output

```shell
don't need
```

### Device Environment

Android 13, MIUI 14.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by cookie9822** [comment]
Hey I just now installed the latest YouTube Revanced App now I can't log in or add my Google account to Sign in to the Revanced App it just says this account already exists on this device but I can't add my Account did the previous Revanced Version get my Google account banned by simply using the Revanced App pls anybody help do I need to make a new Google account that would definitely suck ass BTW the normal YouTube app works fine but obviously sucks ass compared to Revanced Version

**Comment by inotia00** [comment]
Attach a screenshot or video

**Comment by girshcatt** [comment]
![Screenshot_2023_07_30_22_05_24_575_app_rvx_android_youtube_edit](https://github.com/inotia00/ReVanced_Extended/assets/110785596/418d0c1c-8f26-4e92-b720-0b8c7484073f)
![Screenshot_2023_07_30_22_05_48_464_app_rvx_android_youtube_edit](https://github.com/inotia00/ReVanced_Extended/assets/110785596/8bb55783-1d6f-433d-a9da-b73507e40721)
![Screenshot_20230731_092112_Gallery](https://github.com/inotia00/ReVanced_Extended/assets/110785596/0a7e5c11-6d2e-473f-a66a-761dc8be15ee)

**Comment by inotia00** [comment]
This issue is already fixed
Perhaps you have applied the patch to the old version

patch again with the latest resource
