### ISSUE TITLE
delay live chat on miui 

### ISSUE THREAD

**Issue by afahme** [inotia00/ReVanced_Extended#1284]
### Application

YouTube

### Description

i use latest youtube vanced (non root edition) + microg.
i have a small issue with live chat, it's delay 5 second until 10 second. this is for example👇
same channel>>>
>device running aosp have 5 new messages in live chat
>device running miui no new messages (will show 5 second or later)

*i use stable network (wifi 5)
*i compare with 2 devices (1 aosp and 1 miui) 
*tested original youtube from playstore it's normal no delay on miui

please help, which settings need to turn off /turn on

thanks 🙏
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
1. You are on ReVanced extended issue repo.
2. This is not vanced issue centre.
3. Please join vanced server and state your issue in there relevant channel.
4. Please close this post of this helps you.
