### ISSUE TITLE
White Screen Freeze

### ISSUE THREAD

**Issue by matnvd** [inotia00/ReVanced_Extended#1285]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Revanced Extended YouTube v18.24.37

### Bug description

Sometimes when loading into the app after a long time, a white screen would cover the app and the app wouldn't be able to function until I quit the app and relaunch it. 

### Steps to reproduce

1. Open the app
2. put into split-screen mode with another app
3. you can adjust the app go full screen if u want but by now the app should have a white screen anyway

### Relevant log output

```shell
Don't have any
```

### Solution

Just quit the app and relaunch it

### Device Environment

Android 13, pixel 7a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
repatch with latest resource
