### ISSUE TITLE
feat(patch): bring back Spoof player parameters type Shorts

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#1289]
### Application

YouTube

### Issue

.

### Patch

Spoof player parameters type Shorts is working for me and i want it because it is the only way to bring back Seekbar thumbnails and Ambient mode, please make it optional to switch between Spoof player parameters type Shorts and Spoof player parameters type Incognito mode

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by jhon1282** [comment]
I join the request, it was nice to have the choice.

**Comment by inotia00** [comment]
Unfortunately this is not in the plan

Previously, It was able to select the spoofing type in the settings.
For some reason, spoofing did not work normally for some people when it was implemented to be able to select the spoofing type.

https://github.com/inotia00/ReVanced_Extended/issues/1238
