### ISSUE TITLE
feat(patch): Custom video quality/speed for each channel

### ISSUE THREAD

**Issue by kapchapka** [inotia00/ReVanced_Extended#129]
### Application

YouTube

### Issue

Youtube doesn't let its users change channels′ default video quality and speed individually.

### Patch

Create a patch that allows users to change each channel′s default video speed or quality. There would be an option in settings which allows youtube to remember each channel′s video quality and speed individually. It would also be great if users could see changes in ″Whitelist settings″

### Motivation

Some creators can talk slower or faster than others, and changing their speed each time is inconvenient. The same can be said about video quality settings, though custom video speed for each channel is much more essential. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
channel whitelisting is removed in [revanced-patches-v2.173.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.1)
