### ISSUE TITLE
feat(patch): Add option to remove microphone button in search menu

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1290]
### Application

YouTube

### Issue

N.A

### Patch

Please add function to remove micro button from search menu
1.how it now
![IMG_20230731_214006_769](https://github.com/inotia00/ReVanced_Extended/assets/110785596/4f1cc366-b0c7-4079-9661-9ec6b2e37990)
2.how it will look with patch
![Screenshot_20230731_221518_Picsart](https://github.com/inotia00/ReVanced_Extended/assets/110785596/5ef45d54-ba33-47e0-90ef-c9295b44a488)

### Motivation

It just give community more custom option

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by hlytus** [comment]
#617 duplicate issue

**Comment by inotia00** [comment]
thanks
