### ISSUE TITLE
bug: `hide comment component` keeps failing

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1291]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube v18.29.38

### Bug description

When patching YouTube via RVX Manager, this specific patch fails everytime.

### Steps to reproduce

1) Try patching with `hide comment component' patch included.
2) See that it's failing.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

![Screenshot_20230801-001312~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/c97f514c-c061-43a3-a7e3-19e5aac08cc8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.186.12
