### ISSUE TITLE
bug: RVX Manager is not following `MaterialYou` completely

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1293]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

RVX Manager 

### Bug description

When trying to back out after initialising the patching process, the user is shown a pop up container saying "Installer is still running, cannot exit...". But this is shown in a white box.

P.S:-This issue is not there in ReVanced Manager.

### Steps to reproduce

1) Try patching any application.
2) Try to blackout after the patching process has initialised.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

![Screenshot_20230801-001134~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/a3e9b648-b536-4261-acc2-66e45164261a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Unfortunately, it's not an issue I can fix

After the patch is completed, export the APK, then install the manually from the file manager or try another patch method

**Comment by ILoveOpenSourceApplications** [comment]
There's no patching issue actually. This is also there in the ReVanced Manager but the difference is it's shown in a more `MaterialYou`isk manner.
![Screenshot_20230801-121528~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/ea042680-c872-46c8-975e-a997feab3324)
 When removing some of the features, you might've accidentally removed an element related to this feature. Was just asking if it could be added back or not.
