### ISSUE TITLE
feat(patch): hide create button from tool bar

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1294]
### Application

YouTube

### Issue

N.A.

### Patch

Add function to remove cast button from home page
1.how it now
![IMG_20230731_220913_645](https://github.com/inotia00/ReVanced_Extended/assets/110785596/b4c38c73-b274-49dc-a6e7-f753ffd2e404)
2.how it need to be with patch
![Screenshot_20230731_221748_Picsart](https://github.com/inotia00/ReVanced_Extended/assets/110785596/f90a0387-aeaa-4fb5-8b7d-10b241959e2d)

### Motivation

new custom option

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.

**Comment by girshcatt** [comment]
Ok, i know, this was my old patch reqest
