### ISSUE TITLE
Show download question: <title>: 

### ISSUE THREAD

**Issue by Kronodile** [inotia00/ReVanced_Extended#1295]
### Application

YouTube

### Description

I enabled the option to hide download but after update I can't find it to disable. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Add the `revanced-patches version`, `YouTube version`, and the `screenshot` of the issue.
And please open the issue again
