### ISSUE TITLE
ReVanced  Youtube - Playback loop error

### ISSUE THREAD

**Issue by DarkAceiss** [inotia00/ReVanced_Extended#1296]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Youtube ReVanced versions: 18.29.38, 18.27.36, 18.24.37

### Bug description

I have updated to the latest version of the ReVanced app and since then, for every video i watch (either on streen, minimized window or locked) the content will end like there is no data service available and it can't download/stream the entire video. 
I have tried this on 5G, 4G and highspeed wifi connections (Wifi4 and Wifi6) that should have no issue in running any kind of content with data plans having enough data to spare; yet from videos ranging from 30 seconds up to hours long videos the same issue occurs. At around 80% of the content the upload bar will freeze and when the player reaches the border it will end up into an endless loop of loading the video.

I have tried to downgrade from version 18.29.38 to 18.27.36 (the last stable version i had till the 30th) and then to 18.24.37. The downgrades were not useful as the issue persists on the players after the downgrade.
I have tried this on 4 different phones in order to confirm that is not a phone issue; phone models used are: Motorola Edge 30 Ultra, Pocophone F2 Pro, Xiaomi Mi A2, Samsung A33.

### Steps to reproduce

Update to 18.29.38, play any video of your choice and wait for the uplink stream to reach ~80% where it will freeze, the player will enter a loading loop upon reaching that uplink hardpoint.

### Relevant log output

```shell
...
```

### Device Environment

Android 13, Android 12, MIUI 14 (Global), MIUI 11.0.28 (Global)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
did you enable `spoof player parameter`?

**Comment by DarkAceiss** [comment]
Yes, i do have the parameter enabled. Should i disable it?
Will also try with the standalone app if that helps; i'll uninstall the manager and install the ReVanced app as a solo.

Thank you for the response.

**Comment by inotia00** [comment]
Yes it must be enabled

If it is already enable..
try to disable it, restart the app, and enable it again

Nevertheless, if the playback issue persists, there is nothing that can provide help from my side
In this case, use the official ReVanced

**Comment by DarkAceiss** [comment]
LE: uninstalled the manager and tried the enable-disable-enable steps on the standalone app; it seems to have worked. Will reinstall the manager too. 
Thanks a lot for your involvement; top tier stuff!
