### ISSUE TITLE
suggestion: Update your Revancify documentation to match Revancify X

### ISSUE THREAD

**Issue by ghost** [inotia00/ReVanced_Extended#1298]
### Application

Revancify

### Description

Now that og Revancify is dead and took over by Revancify X and the new developer, I think you should update your Revancify documentation to match the new one.

Revancify X repo: https://github.com/kastentop2005/Revancify-X
Developer: kastentop2005

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Original-Steak9413** [comment]
Out of topic:

I also made a suggestion in Revancify X's repo asking the developer to rename Fetch Tools back to Update Resources, this is how it used to be back in the day for a long time.

**Comment by odkate** [comment]
Collects faster than other methods. I am delighted.🆕🔝

**Comment by inotia00** [comment]
Revancify still works
