### ISSUE TITLE
suggestion: Remove Telegram from your documentation

### ISSUE THREAD

**Issue by Original-Steak9413** [inotia00/ReVanced_Extended#1299]
### Application

Documentation

### Description

Revanced Extended Telegram chat was closed (according to [Reddit post](   https://www.reddit.com/r/revancedextended/comments/15dcd4z/revanced_extended_no_more/ju1zj46/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button)), there is no need for this app icon anymore.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Even after development is discontinued, the subreddit and telegram channels are planned to be operated for a while for support
