### ISSUE TITLE
feat(patch): Premium heading and player buttons background 

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#13]
### Application

It is for premium heading and player buttons background 

### Issue

There are 2 toggleable patches .. premium heading and player button background.. if we exclude one of them .. the toggle is useless .. so if it is possible to solve this problem and make the 2 patches toggleable (whenever excluding or including) 

### Patch

By the way , any patch that has toggle is more useful than excluding it

### Motivation

It will be beneficial 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Premium header has already been implemented in a switch.

Player button background is impossible to implement it as a switch due to the limit of app structure.
