### ISSUE TITLE
bug: seekbar time partially hidden when spoofed

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1300]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.29.38
Patches v2.186.10

### Bug description

![Screenshot_20230802_042326_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/12ab5352-09b8-4955-a07c-54f702bf970e)
![Screenshot_20230802_041408_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/58be3bf4-26c4-42d0-aa4e-87bfd0fec68d)

### Steps to reproduce

1. Enable `Spoof player parameter` and restart
2. Play a video and swipe the seekbar

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is a side effect of the Spoof player parameter (known issue)
This is an issue that cannot be fix
