### ISSUE TITLE
bug: <shorts>Disable shorts player at app startup ( doesn't work)  

### ISSUE THREAD

**Issue by Bakchxd** [inotia00/ReVanced_Extended#1301]
### Type

Other

### Tools used

Revancify

### Application

YouTube Extended 18:29:38

### Bug description

Shorts player is disabled at app startup is doesn't work sometimes. It's seems bug 
![Screenshot_20230802-095935](https://github.com/inotia00/ReVanced_Extended/assets/139042928/aa8f176f-59b1-4f81-9a63-7cb027a4a080)

### Steps to reproduce

I don’t have a video to show you, but it's a matter of fact.

### Relevant log output

```shell
nill
```

### Screenshots or videos

Nill

### Solution

Nill

### Additional context

Nill

### Device Environment

Android 11, Realme ui

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Do you understand what the Disable shorts player at app startup patch is?
If so, attach a video when it doesn't work

**Comment by Bakchxd** [comment]
okay

**Comment by inotia00** [comment]
Refer the issues that others have reported in the past : https://github.com/inotia00/ReVanced_Extended/issues/1112

Nevertheless, if you think that the issue is valid, please attach a screenshot or screen record and re-open it
