### ISSUE TITLE
bug: <Buy or rent video recommendation>

### ISSUE THREAD

**Issue by Nik401** [inotia00/ReVanced_Extended#1302]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.27.35

### Bug description

Sometime whenever I open any video, this type of video suggestion occurs under the video. 

### Steps to reproduce

Click on the three dots > "Not Interested" (but it will come again)

### Relevant log output

```shell
No
```

### Screenshots or videos

![IMG_20230802_104212](https://github.com/inotia00/ReVanced_Extended/assets/54033400/89062637-c68b-4fd3-b174-f73e8aaeed04)

### Device Environment

Android 12, MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Bakchxd** [comment]
same problem exactly I am facing now :(

**Comment by inotia00** [comment]
turn on:
`Settings > ReVanced Extended > General > Hide movies shelf`

**Comment by Nik401** [comment]
Thank you so much. 😊

**Comment by Bakchxd** [comment]
> turn on: `Settings > ReVanced Extended > General > Hide movies shelf`

It's means that we can't download video over 360p 🤕. It’s don’t work
