### ISSUE TITLE
question: <YouTube >: Downloading 

### ISSUE THREAD

**Issue by Bakchxd** [inotia00/ReVanced_Extended#1303]
### Application

YouTube

### Description

![Screenshot_20230802-111314](https://github.com/inotia00/ReVanced_Extended/assets/139042928/a38f71b9-fd53-4d21-ae3b-f405f12ecfa4)
In the Bangladesh region, YouTube officially announced YouTube Premium subscriptions on August 2, 2023. After that, downloading videos above 360p wasn't working. It seems to be a purchase YouTube premium subscription

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Issues not related to RVX
