### ISSUE TITLE
bug: Buffering Ring of Death 

### ISSUE THREAD

**Issue by DerHope** [inotia00/ReVanced_Extended#1304]
### Type

Error at runtime

### Tools used

Revancify

### Application

Have deleted everything, but I tried the [Automatic] option of Revancify and several others. 

### Bug description

After ~1MIN, YT videos stop, start buffering and never recovers

### Steps to reproduce

All variations of spoof player and app version 

### Relevant log output

```shell
None available, I'm no dev
```

### Device Environment

Oneplus Nord, Android v13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
follow this method https://github.com/inotia00/ReVanced_Extended/issues/1296
