### ISSUE TITLE
Play Store update notification for YT and YTM

### ISSUE THREAD

**Issue by jenaplisken** [inotia00/ReVanced_Extended#1305]
### Application

YouTube

### Description

IIt is possible to make the play store not ask me to update YT and YTM every time?
Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is not an issue related to RVX
