### ISSUE TITLE
Can't download videos

### ISSUE THREAD

**Issue by coccobello02** [inotia00/ReVanced_Extended#1309]
### Type

Other

### Tools used

ReVanced Manager

### Application

18.20.39 youtube 

### Bug description

Fhe video downloader Powertube only works for short videos. If I want a video of 10 minutes or more it doesn't work

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

.

### Solution

.

### Device Environment

Android

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by 7javed** [comment]
Powertube ia outdated, Use ytdlnis instead.

**Comment by coccobello02** [comment]
> Powertube ia outdated, Use ytdlnis instead.

How do I use ytdlnis and where I download it it from

**Comment by girshcatt** [comment]
from ytdlnis github

**Comment by coccobello02** [comment]
> from ytdlnis github

Can you send me the link

**Comment by coccobello02** [comment]
> from ytdlnis github

Powertube makes you download it directly from the button in the youtube app, that's why I use it

**Comment by 7javed** [comment]
you can also download with ytdlnis with the download buttion 
Settings > Revanced Extended > overlay Button > External Download manager > install and choose Ytdlnis

**Comment by girshcatt** [comment]
> > from ytdlnis github
> 
> Powertube makes you download it directly from the button in the youtube app, that's why I use it

link here https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.4
Ytdlnis have overlay menu like in powertube without leaving youtube
after you install go to Settings > Revanced Extended > overlay Button > External Download manager > install and choose Ytdlnis

**Comment by coccobello02** [comment]
> > > from ytdlnis github
> > 
> > Powertube makes you download it directly from the button in the youtube app, that's why I use it
> 
> link here https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.4
> Ytdlnis have overlay menu like in powertube without leaving youtube
> after you install go to Settings > Revanced Extended > overlay Button > External Download manager > install and choose Ytdlnis

Cab you send the link to download the apk of YouTube premium
