### ISSUE TITLE
 (patch): It tells me that I don't have internet, but I do.

### ISSUE THREAD

**Issue by Andherson000** [inotia00/ReVanced_Extended#1311]
### Application

YouTube

### Issue

![Screenshot_20230803_074718_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/141333425/3d6b89a4-3470-45fd-954d-a4a5f05764ae)

It appears that I don't have Internet... even if I have... even with wi-fi.

### Patch

Fix the required network issue.

### Motivation

Because the problem can occur in someone else.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Original-Steak9413** [comment]
You didn't mention these:

- The patch tool used
- Version of the patch and YouTube
- Which patches were included/excluded

And you used the wrong template, you should've used Bug template instead.
