### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by talhaazam** [inotia00/ReVanced_Extended#1312]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube version 18.30.36

### Bug description

After the update there are playback issues with the default player previously it use to work fine.
However i have turned on the spoof player parameters function in (setting/miscellaneous) but now i cannot see the thumbnails while scrolling (it was a useful feature).
I know it is mentioned in the known issues that but is there another way to fix this problem?
Thankyou 

### Steps to reproduce

Disable spoof player parameters 

### Relevant log output

```shell
N/a
```

### Device Environment

Galaxy a30 with android 11 installed 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
yes. It is marked as a known issue because it is an issue that cannot be fixed right now.
