### ISSUE TITLE
bug(spoof-player-parameter): videos previewed in feed get added to history

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#1313]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

YouTube 18.29.38
Patches 2.186.12

### Bug description

Scrolling through the feed on home tab, previewing the videos adds them to history.

### Steps to reproduce

Step 1. Include spoof player parameter patch
Step 2. Make sure the setting is turned on in settings
Step 3. Preview video in feed
Step 4. Check if added to history

### Relevant log output

```shell
None
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/78740080/f4537c6f-b8cf-4a79-bb2d-9544c89623bb

### Solution

A workaround would be to turn off feed playback in general settings of YouTube

### Device Environment

Android 13, Google

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Original-Steak9413** [comment]
#1107

**Comment by inotia00** [comment]
ok this is a valid issue

**Comment by inotia00** [comment]
Please check if it reproduces on unpatched YouTube

**Comment by ayushTNM** [comment]
Nope, not happening on stock yt 18.36.38 on my end

**Comment by inotia00** [comment]
I will disable spoofing when watch a preview in the feed to deal with this issue
(as @kitadai31 did: https://github.com/kitadai31/revanced-integrations/commit/0782adeb8e570e34e7d48ae40b8402bcbbb9526d)

But if you watch a preview in your feed for more than 1 minute, you will experience playback buffer issues

Most people won't watch more than a minute of previews in their feed, so this isn't a big deal

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)

**Comment by Sishdbds277** [comment]
Is this not possible to fix
