### ISSUE TITLE
feat(patch): The hide_shorts_player_navigation_bar patch should be restored to the way it worked in version 2.169.5

### ISSUE THREAD

**Issue by odkate** [inotia00/ReVanced_Extended#1314]
### Application

YouTube

### Issue

On newer versions, the patch does not work completely. A black bar remains at the bottom

### Patch

On version 2.169.5 the patch works as expected. Therefore, it is necessary to restore the principle of working patch as it used to work

### Motivation

There will be no black bar at the bottom, i.e. the video will be full screen

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You are using the `Experimental Flags`

**Comment by odkate** [comment]
> 

I know it's Experimental Flags. But why is it impossible to return the way Principle of work used to be?

**Comment by inotia00** [comment]
Because the target app version is different
YouTube version supported by revanced-patches-v2.169.5: v18.15.40
YouTube version supported by revanced-patches-v2.186.12: v18.29.38
