### ISSUE TITLE
feat(patch): Hide most replayed/viewed parts of a video

### ISSUE THREAD

**Issue by STEK1337** [inotia00/ReVanced_Extended#1315]
### Application

YouTube

### Issue

It will remove "waves" that appear above the seekbar slider

### Patch

Remove the "waves" and enjoy the video in clean fullscreen
![image](https://github.com/inotia00/ReVanced_Extended/assets/118012196/6fa99f63-4755-4e83-9cc2-95c7fa689e9b)

### Motivation

We have plenty of patches that hide fullscreen panels, seekbar preview, etc, so this should be implemented aswell resulting in clean fullscreen experience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
