### ISSUE TITLE
bug: video playback stops after 1min of playtime and keeps buffering

### ISSUE THREAD

**Issue by M3veronMast3r** [inotia00/ReVanced_Extended#1316]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Youtube ReVanced Extended 18.13.38

### Bug description

Suddenly every Youtube Video over every Internet Network starts buffering after 1min of playtime and gets stuck in buffering. I recognized it first about an hour ago and tried since it to fix and found also an reddit thread about this 3 months ago and they say it were because of "spoof app signature" is by default disabled. I checked the settings but it is enabled. I tried to disable it but no difference..

### Steps to reproduce

Can't write down steps to reproduce because it startet suddenly without of me changing anything

### Relevant log output

```shell
Dont know where to find the logs of Youtube ReVanced Extended.
```

### Screenshots or videos

It's just buffering on every youtube video without an error message after one minute of playtime. What should i add here? An prove that it starts and keeps buffering after one minute of playtime?

### Device Environment

Model: moto g 5G plus (XT2075-3)
Android-Version: 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
re-patch withv18.13.38 is an outdated version
Update to latest version according to [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-RVX-Manager-(Android))
