### ISSUE TITLE
bug: <Videos stop working after a minute>

### ISSUE THREAD

**Issue by SWEet22222** [inotia00/ReVanced_Extended#1317]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

ReVanced Extended V.18.14.41

### Bug description

It seems like this bug started out of nowhere. It was all working fine, I was watching a few videos and suddenly this bug.

Bug:
The video just goes black and the spinning loading wheel show-up.
This seems to usually occur 1:10 into the video for some reason.

I have tried (to no success) restarting my phone, as well as clearing the app's cache.

### Steps to reproduce

No idea, it seemed to appear out of nowhere.
Step 1: Watch a video.
Step 2: Done (bug appear usually 1:10 into any video).

### Relevant log output

```shell
Relevant log output? Is there a log file stored somewhere, or what does this mean?
```

### Screenshots or videos

![Screenshot_20230804-033051_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/39055382/148798e7-a654-466a-bc60-e79cc9c5f280)

### Solution

Not really a solution, but I found that this bug can be bypassed by either:
A - Turning on incognito mode within the app.
or
B - Using the normal YouTube app.

### Device Environment

Galaxy Note9 (SM-N960F)
Android 10
![Screenshot_20230804-035427_Settings](https://github.com/inotia00/ReVanced_Extended/assets/39055382/e19ada55-5864-4156-b8c9-46748c8cec71)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
v18.14.41 is an outdated version
Update to latest version according to [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-RVX-Manager-(Android))
