### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by Proxha08** [inotia00/ReVanced_Extended#1319]
### Application

YouTube

### Issue

Videos not loading even with 5G Wi-Fi 

### Patch

Videos loading normally 

### Motivation

From one hour to another the videos started to stop loading. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
thanks
