### ISSUE TITLE
feat(patch): Publication of short videos occurred only for the Subscriptions tab

### ISSUE THREAD

**Issue by mak7im01** [inotia00/ReVanced_Extended#132]
### Application

YouTube

### Issue

Adding functionality to short videos.

### Patch

Displaying two functions, the first one that is currently present, deleting short videos everywhere, and the second, which I ask you to add so that when enabled, short videos are displayed only in the Subscriptions tab.

### Motivation

I want to watch short videos of only those channels that I subscribe to, to view others there is a Short Videos button, in this case there is no need to spoil the Main Page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
