### ISSUE TITLE
Video chapters and lagging 

### ISSUE THREAD

**Issue by Mhmodhaha** [inotia00/ReVanced_Extended#1320]
### Type

Other

### Application

Youtube v18.27.40 

### Bug description

When i click on chapters in video and try to swipe video down it goes down very laggy and this lags increase with number of chapters in a video. It doesn't appear well in attached video but it is really laggy in RVX V18.27

I know it may not be a big problem but in official youtube it is very smooth not like the RVX so I hope you don't mind If I post this little bug .

https://github.com/inotia00/ReVanced_Extended/assets/141293135/178abf37-e146-457c-87d5-179bd5c5d3a0

### Steps to reproduce

In description 

### Relevant log output

```shell
Nothing
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Adity1243** [comment]
Bro you must be set video quality to high (for ex:- you device only supports 1080 then youtube set automatically 1440 quality since you are using wifi) and then your dont have capacity to render other graphics try lowering your video quality in revanced settings it will fix the issue).

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1016

**Comment by Mhmodhaha** [comment]
> Bro your device must be set video quality to high (for ex:- you device only supports 1080p then youtube set automatically 1440p quality bcus you are using wifi or max quality supported by your device) and then your device dont have capacity to render other graphics try lowering your video quality in revanced settings it will fix the issue.

@Adity1243 
Actually the attached video is playing on 144p the lowest  quality and my device supports to 2160p
So I think it is not that weak ...
And on official youtube it works well so the problem is in RVX ...
IN youtube vanced (if I didn't forget,) it wasn't  laggy..
