### ISSUE TITLE
question: <title>: I can't see the frame-by-frame rewind of the video, which is why I can't accurately move to the desired segment.

### ISSUE THREAD

**Issue by HikkiSadrot** [inotia00/ReVanced_Extended#1321]
### Application

YouTube

### Description

everything is in the question

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] I have written the title and contents in English.

**Comment by inotia00** [comment]
there are three possibilities

1. You are using `Spoof player parameter` to solve playback issues

2. You are using `Hide filmstrip ovflay`

3. You spoofed an older version with `Spoof app version`

**Comment by HikkiSadrot** [comment]
> есть три возможности
> 
> 1. Вынесения решений `Spoof player parameter`для решения проблем с населением
> 2. Ты используешь`Hide filmstrip ovflay`
> 3. Вы подделали старую версию с помощью`Spoof app version`

thanks, as it turned out, the first one is set automatically
