### ISSUE TITLE
bug(sponsorblock): when submeting segments small part of the video is not submitted

### ISSUE THREAD

**Issue by Sudeepxl20** [inotia00/ReVanced_Extended#1322]
### Type

Other

### Tools used

Revancify

### Application

18.29.38

### Bug description

Bug :

Sponcerblock :When submeting segments small part of the video is not submitted. (last part of the video)

### Steps to reproduce

Step1 go to any video
Step 2 start submiting segment
Step 3 create  the last part of the video example as end cards the end point should be end of the video
Step 4 after submitting we can see a small part 1or 2 secs of the segment is not submitted properly 

### Relevant log output

```shell
No log
```

### Screenshots or videos

![IMG_20230805_045124_660](https://github.com/inotia00/ReVanced_Extended/assets/111219466/a0b07cd1-9da1-4345-9c96-38536bafdbe7)

### Device Environment

Happend with my 2 devices

VIVO Y11 android 11 funtouch os
Redmi note 7 android 11 (coustom ROM) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
After using it for a few days, it seems to have been fixed in the latest patches.
Close the issue.
