### ISSUE TITLE
patch request:Prevent exit with the back button from libraries with old specifications.

### ISSUE THREAD

**Issue by harutoku** [inotia00/ReVanced_Extended#1323]
### Application

YouTube Music

### Issue

If you press the "Playlist", "Album", or "Song" button and then press the "Back" button in the system navigation, you will be returned to the home screen.

 YouTube version is 6.17.52, after applying "Enable old style library shelf".

### Patch

Modify the above, or make it possible to return by pressing the "Library" button on the navigation bar.

### Motivation

"Enable old style library shelf" can be applied to make the library easier to use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I did not specify the reason for closing the issue

In newer clients, no source exists for interactive behavior for older library tabs

Nonetheless, the patch sends a request on the server side for the browse ID for the old library tab

The client can receive requests for the old library tab, but cannot handle the interaction

implement in client-side requires the full code for YT Music, and a complete implementation in YT Music is not possible unless Google provides it

For this reason, it was implemented as an experimental patch, and it is clearly stated in the settings as an experimental patch

**Comment by harutoku** [comment]
I understand that it is difficult to implement.
I sent it twice by mistake, sorry.
