### ISSUE TITLE
feat(patch): remove button container labels

### ISSUE THREAD

**Issue by xenophorm12** [inotia00/ReVanced_Extended#1324]
### Application

YouTube

### Issue

Give us an option to remove button container labels just like in YT Music. 

### Patch

![IMG_20230906_073532](https://github.com/inotia00/ReVanced_Extended/assets/58360189/a6f6bf29-1171-480f-a623-e52668da9cc1)

### Motivation

This would make the UI less cluttered.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by StradivariusKane** [comment]
#894

**Comment by KobeW50** [comment]
894 is only to remove the labels in the navigation bar. This is to remove the labels in the bottom player buttons
