### ISSUE TITLE
feat(patch): Hide captions layout footer

### ISSUE THREAD

**Issue by xenophorm12** [inotia00/ReVanced_Extended#1325]
### Application

YouTube

### Issue

It only appears when you long press the captions button on the player menu.

### Patch

![IMG_20230906_074620](https://github.com/inotia00/ReVanced_Extended/assets/58360189/6b096aa4-2677-4465-a230-66ae1e3db7e1)

### Motivation

This would make the UI less cluttered.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
