### ISSUE TITLE
question: Hiding suggestions shelf

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#1327]
### Application

YouTube

### Description

If we go back to library tab from home tab by pressing back button, navbar index will be still zero and playlist shelf will be hidden. And vice versa, if go back to home tab from library tab, index will be 4, and suggestions shelves will be shown on home page.
 - Can you guide me toward the method to hook for back press? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a limitation of the current patch method

To solve this issue we need a more ideal way to hook the navbar index

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)
