### ISSUE TITLE
bug: <videos get stuck buffering after 30-40 sec if playing>

### ISSUE THREAD

**Issue by Apachxi** [inotia00/ReVanced_Extended#1328]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube 18.02.33

### Bug description

My version of app was the most useful but it gets stuck on buffering. I downloaded newer and other versions but they don't launch at all. 

### Steps to reproduce

Just play any video from search or from the channels page

### Relevant log output

```shell
I don't know where to find logs for the app
```

### Screenshots or videos

No need. It's just buffering

### Solution

I came.here for solutions 

### Additional context

Help

### Device Environment

Miui 14.0.3
Android 12 SKQ1.210908.001

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by MrNorthernLights** [comment]
You are using too old version, patch again and update your YouTube app to the latest supported version.

**Comment by Apachxi** [comment]
Hi there,

Thank you for the response.

I downloaded the manager and updated apps, it installed separate revanced
apps - there were two actually, neither worked. When I try to launch the
app it quits itself.

Can you provide me with the link of the working version? Because internet
is full of Vanced apps and reworks and all types of clones.

Thank you.

Regards,

**Comment by MrNorthernLights** [comment]
Download revanced manager: https://github.com/inotia00/revanced-manager/releases

Download YouTube apk from apkmirror: https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-31-40-release/

Then patch.

**Comment by Apachxi** [comment]
Hey thanks for helping me

So I downloaded manager - installed it, then downloaded YouTube and
couldn't install it error message -
App not installed for package appears to be invalid!

What should I do?

**Comment by KobeW50** [comment]
@Apachxi uninstall your old apks and start from scratch.

You can use [this guide](https://www.reddit.com/r/revancedextended/comments/12vxggr/revanced_extended_guide_for_beginners/) or [this guide](https://www.reddit.com/r/revancedextended/wiki/yt-guide/) to patch YT ReVanced Extended.

**Comment by Apachxi** [comment]
Those guides are hell to follow as they go back and forth in time and
branch out endlessly.

Never in the instructions did it say anything about downloading different
files for rooted devices.

**Comment by KobeW50** [comment]
> Those guides are hell to follow as they go back and forth in time and
> branch out endlessly.
> 
> Never in the instructions did it say anything about downloading different
> files for rooted devices.

There aren't special files to download for rooted installs. Also both of those guides are for non-root installs. I didn't realize you were rooted
