### ISSUE TITLE
feat(patch): An option to hide chapters next to the time indicator

### ISSUE THREAD

**Issue by MrNorthernLights** [inotia00/ReVanced_Extended#1329]
### Application

YouTube

### Issue

We can already hide chapters in the description but not from video player itself.

![image](https://github.com/inotia00/ReVanced_Extended/assets/143272767/79d7e2bb-da16-43cc-81f0-7c3743cbadab)

### Patch

Hide chapters from video player

### Motivation

To make the video player look more clean

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
in case of YouTube, no plans to add any more new features

**Comment by StradivariusKane** [comment]
Hiding it with custom filter is possible or not? @inotia00

**Comment by inotia00** [comment]
Since most of the player's internal components are not in litho view, it is impossible to hide them with custom filters
