### ISSUE TITLE
bug: rewind doesn't work if player controller is not visible

### ISSUE THREAD

**Issue by jezokshe** [inotia00/ReVanced_Extended#133]
### Type

Other

### Application

If you disable the brightness gesture and other gestures except for the volume gesture, then rewind only works when the player interface appears

### Bug description

Disable brightness control and other gestures

### Steps to reproduce

Disable brightness control and other gestures

### Relevant log output

```shell
fkfkffllfflfff
```

### Solution

ffkkffkfkfk

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
well.. this is a bug in official ReVanced
(Same bug exists in official ReVanced as well)

But someday i will fix it

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.153.6
