### ISSUE TITLE
bug: options stretch to full screen not working

### ISSUE THREAD

**Issue by electrifying** [inotia00/ReVanced_Extended#1330]
### Type

Other

### Tools used

rvx-builder

### Application

18.34.38

### Bug description

when you enable the option in the settings-general-stretch to full screen section, the function no longer works correctly.black bars remain on the sides and for the option to work, the video has to be stretched manually, this only works until the application is restarted, the problem appeared quite recently, apparently YouTube changed something on the backend side.

### Steps to reproduce

1.open youtube
2.tap to you avatar
3.open settings
4.open general
5.activate the option to stretch to full screen
6.open any video
7.switch to full screen video view

### Relevant log output

```shell
sorry
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/37656577/28ec3052-d02e-47f1-94b9-28c6971d55ba

### Solution

no solution, at least I couldn't find it

### Device Environment

oneplus 9r android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Version not supported
