### ISSUE TITLE
bug: RVX Manager - apps list is empty (unless source is original revanced repos)

### ISSUE THREAD

**Issue by kulmegil** [inotia00/ReVanced_Extended#1331]
### Type

Other

### Tools used

ReVanced Manager

### Application

RvX Manager v1.9.5

### Bug description

No apps appear on apps list selection in Patcher section.
This forces user to select .apk from storage, preventing use of root installation when patching is finished

### Steps to reproduce

1. Launch RvX Manager
2. Click "Select an application" in Patcher tab

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20230906-131837](https://github.com/inotia00/ReVanced_Extended/assets/570575/d2623f69-558e-4ccf-b263-b83dd240633a)

### Solution

[troublesome workaround]
1) temporary switching repos to revanced (don't restart manager app)
2) select app from the list
3) reset repos back to intotia00
4) continue patching
5) select root install

### Additional context

API url is set to `api.revanced.app/`

There is a [similar bug](https://github.com/ReVanced/revanced-manager/issues/1221#issuecomment-1703187299) opened at Revanced Manager. I'm not sure if it will reach proper conclusion since it "works right" when original revanced repos are selected.

### Device Environment

OnePlus 8T Android 11 (not releavant it)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Since my patch only supports three apps, there is no need to load a list of all the apps it supports.

The documentation also recommends importing the APK from , local storage.

So I have no plans to fix

**Comment by KobeW50** [comment]
> Since my patch only supports three apps, there is no need to load a list of all the apps it supports.
> 
> The documentation also recommends importing the APK from local storage.

What about root installs?

**Comment by inotia00** [comment]
Even in a ROOT environment, you just need to locally get the APK of the same version as the app installed on your device.

Because this screen is still displayed

![RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/108592928/22ec71c7-8eec-40a1-af02-87dea8604204)

Selecting an app from the list of installed apps takes slightly longer to patch, so I recommend pulling the APK locally

**Comment by inotia00** [comment]
This means pressing the ‘Storage’ button to select the APK downloaded from APKMirror.

If the user selects an incorrect version of the APK, this will appear:

![RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/108592928/5beb20cc-c2fb-47c6-b936-5105751a0130)

(Current version and Suggested version do not match)

This is what my documentation says: 

After downloading the APK from APKMirror, 'install it on the device'

and then, elect the APK by pressing the Storage button

**Comment by kulmegil** [comment]
0) Unpatched previous installation
1) Downloaded YT apk (18.34.40) from APKmirror
2) Installed it "on the device" (using standard android package manager)
3) Selected the very same apk using "Storage" button on Patcher page
4) Patch finished successful
5) Selected root installation type.... got error

- [Screenshot_20230907-005643](https://github.com/inotia00/ReVanced_Extended/assets/570575/5e411f0c-212c-4e91-b10f-ee69d06dda7b)
- [Screenshot_20230907-005758](https://github.com/inotia00/ReVanced_Extended/assets/570575/01733995-cdc8-44a5-a9da-7331cfad88c0)

**Comment by inotia00** [comment]
> I had already tried it in the past and it never worked. It doesn't work now with latest versions either...
> 
> 0. Unpatched previous installation
> 1. Downloaded YT apk (18.34.40) from APKmirror
> 2. Installed it "on the device" (using standard android package manager)
> 3. Selected the very same apk using "Storage" button on Patcher page
> 4. Patch finished successful
> 5. Selected root installation type.... got error
> 
> * [Screenshot_20230907-010514](https://github.com/inotia00/ReVanced_Extended/assets/570575/12e3fa23-4600-4feb-b41d-606706153400)
> * [Screenshot_20230907-005643](https://github.com/inotia00/ReVanced_Extended/assets/570575/5e411f0c-212c-4e91-b10f-ee69d06dda7b)
> * [Screenshot_20230907-005758](https://github.com/inotia00/ReVanced_Extended/assets/570575/01733995-cdc8-44a5-a9da-7331cfad88c0)

exclude MicroG support patch

**Comment by kulmegil** [comment]
I always excluded it for root installation. It was excluded in the screenshots above.

But it does nothing since the problem is RvX Manager refuses to install it as root at the end of patching.

**Comment by Neocray** [comment]
Same issue here. Patched APK also refuses to install as root.

**Comment by inotia00** [comment]
I am not using RVX Manager as my main tool, and I am not good at handling flutter, so when I first released RVX Manager, I declared that I would not fix any issues that users encounter.
(Because there are many other tools to build RVX besides RVX Manager)

But @oop7, thanks to you for providing very specific steps to reproduce the error, I was able to fix this issue. https://github.com/inotia00/ReVanced_Extended/issues/1357#issuecomment-1717035426

Fixed in RVX Manager v1.9.6

**Comment by KobeW50** [comment]
@inotia00, do you plan on changing step 5 in the [RVX Manager doc](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-RVX-Manager-(Android)#5-click-the-storage-button-and-select-the-youtube-apk-that-you-downloaded-from-apkmirror) that rooted installers should pick the YT application instead of from storage?

**Comment by kulmegil** [comment]
Has selecting ***from storage*** ever worked with root installation?
I tried a few times already with different versions and it never did for me, despite following those readme's and guides to the letter. Am I autistic and missed some very obvious step along the way?

That being said I can confirm 1.9.7 is working as expected for me. Thank You for fixing this.

**Comment by inotia00** [comment]
> @inotia00, do you plan on changing step 5 in the [RVX Manager doc](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-RVX-Manager-(Android)#5-click-the-storage-button-and-select-the-youtube-apk-that-you-downloaded-from-apkmirror) that rooted installers should pick the YT application instead of from storage?

Wiki needs to be updated
