### ISSUE TITLE
About Export and Import Sponsorblock settings 

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#1332]
### Application

YouTube

### Description

The export and import feature of Sponsorblock settings depends on copying your settings then pasting it once you need in the future. I inquire if there is another way for that purpose by exporting or importing json file like the way of RVX settings. As I see Json file method is better than copying and pasting 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Mohammed1520** [comment]
Ah. It seems that this feature cannot be replaced 
Thank you for your response.

**Comment by KobeW50** [comment]
There's pros and cons to each side. Lets see what inotia00 thinks.
