### ISSUE TITLE
Force VP9 Codec Patch 

### ISSUE THREAD

**Issue by MasterNinjaPT** [inotia00/ReVanced_Extended#1333]
### Application

YouTube

### Description

I want to ask if it is possible to update the Force VP9 Codec Patch my phones supports VP9 but it doesn't show up in the YouTube app nor revanced. 

Huawei P Smart Z Android 12 Emui 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is an experimental flag, and there are no plans to improve it.
