### ISSUE TITLE
question: Open rvx translations

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1334]
### Application

YouTube

### Description

Inotia00, please open rvx translations in crowdin again, and also give me proofreader role, you ignored me in crowdin messages, in crowdin i have the same nickname

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
no need to do that

in case of YouTube, I have no plans to add new features.

If you want to edit an existing translation, open the PR

**Comment by girshcatt** [comment]
Yes, i want to edit existing translation, but what is pr?

**Comment by girshcatt** [comment]
Maybe i can translate strings.xml manually and create a pull request?

**Comment by girshcatt** [comment]
Ahh, sorry i am dumb, pr - pull request, this is a way i can do this, as soon i will correct all incorrect ru translations i will open pr

**Comment by inotia00** [comment]
Please refer to the previously held PR
https://github.com/inotia00/revanced-patches/pull/1 https://github.com/inotia00/revanced-patches/pull/14
Opening a PR is not that difficult

**Comment by girshcatt** [comment]
But i have last question, rvx ru translations have much incorrect translations, i can done with them in next ~5 days maximum, Will I make it before your next departure?

**Comment by girshcatt** [comment]
> Please refer to the previously held PR [inotia00/revanced-patches#1](https://github.com/inotia00/revanced-patches/pull/1) [inotia00/revanced-patches#14](https://github.com/inotia00/revanced-patches/pull/14) Opening a PR is not that difficult

Of course i know how to do pull requests, not first day on github, but thanks for example

**Comment by inotia00** [comment]
don't be impatient

As I said, YouTube won't be adding any new features, so YouTube's translations won't be updated - unless someone opens a PR.

So it doesn't matter how long it takes you

Take your time and open your PR

**Comment by inotia00** [comment]
Crowdin EU translation has been reset.
After removing 10,000 duplicate strings that had been left unapproved for a long time, the project became accessible.
Please join the project again and send us a message on Crowdin.

**Comment by girshcatt** [comment]
Yeeep, thank you so much

**Comment by inotia00** [comment]
You can also just upload the `strings.xml` you were preparing to leave a PR on github to Crowdin

If you want to approve at the same time as uploading, obtain proofreader permission first before uploading

**Comment by girshcatt** [comment]
Only problem is that my translation was based on 2.190.1 patches, i dont know how to match them to latest patch

**Comment by inotia00** [comment]
When you just upload, only strings that exist in the target strings will be added to the server

After uploading without approval, you can review all strings again and then approve

**Comment by girshcatt** [comment]
Thanks for the info, i will do right the same that you said
