### ISSUE TITLE
bug(YouTube): video quality change toast

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1335]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube (all supported versions, not important in this situation)

### Bug description

Rvx quality change toast kinda broken, it appears on some versions and on some not appear
Can you just do switch in player settings to on/off rvx quality change toast? Defalut it will be off

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
Is your issue #1089?

Please share a screen recording or steps to reproduce

**Comment by girshcatt** [comment]
> Is your issue #1089?
> 
> Please share a screen recording and steps to reproduce

No, my issue about this toast on screenshot
![262806190-698bc566-45df-41c9-a8bf-a7d31dcb2d1d](https://github.com/inotia00/ReVanced_Extended/assets/110785596/ec82d9fd-e23b-4fc7-8e06-26f5bff5a12a)

**Comment by inotia00** [comment]
no plans to add

**Comment by girshcatt** [comment]
> no plans to add
At least what u think about on some of supported versions this toast appear and on something no?

**Comment by inotia00** [comment]
Even if it is a bug, it cannot be reproduced on my side, so I will just leave it as is
