### ISSUE TITLE
suggestion(YouTube): exclude optimize-resource patch by defalut

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1336]
### Application

YouTube

### Description

Check my issue https://github.com/YT-Advanced/YT-Advanced/issues/49 in rex and do the same for rvx, even arileza confirmed this problem as valid

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
You can just link to this

https://github.com/inotia00/ReVanced_Extended/issues/1280#issuecomment-1657220739

**Comment by girshcatt** [comment]
> You can just link to this
> 
> [#1280 (comment)](https://github.com/inotia00/ReVanced_Extended/issues/1280#issuecomment-1657220739)

Yes, but i think that it need to be excluded by defalut, because if new user will get this bug he won't know what he supposed to do

**Comment by inotia00** [comment]
The `optimize-resource` patch reduces the app size by about 5 MB, but it has side effects so there is no reason to keep the patch
And `optimize-resource` patch is quite old

I will remove this patch in the next release

**Comment by girshcatt** [comment]
Thanks, i fully agree that patch became old an have side effects, thats what i wanted to say

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)
