### ISSUE TITLE
bug(YouTube): `hide-suggestions-shelf` patch not working on tablets

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1337]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.31.40

### Bug description

Old bug with suggestion shelf, that was because u forgot to add horizontal_tile_shelf component in this patch, rex already fixed it https://github.com/YT-Advanced/ReX-integrations/commit/d60dd2ca8f5cdbdbb952726a48fb7f1ef57d313a

### Steps to reproduce

Include `hide-suggestions-shelf` and patch
Turn it on in settings and check home page, u will still see all suggestions

### Relevant log output

```shell
:/
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
I opened a pull request https://github.com/inotia00/revanced-integrations/pull/17

**Comment by girshcatt** [comment]
I opened a pull request https://github.com/inotia00/revanced-integrations/pull/17

**Comment by inotia00** [comment]
reflected in [revanced-patches-2.190.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.4)
