### ISSUE TITLE
feat(patch): add swipe controls for YT Music

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#1339]
### Application

YouTube Music

### Issue

It would be great to add brightness and volume swipes to YT Music in full screen mode.

### Patch

![Screenshot_20230906_231602_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/8f377b44-a43e-45df-bf1e-c1d0ef9b5330)

### Motivation

Swipe controls will allow you to easily adjust the brightness and volume while watching video clips and concerts in full screen mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
To implement this the YT Music app becomes overly heavy

Also, not many people watch videos in full screen on YT Music.

If you want to watch a video full screen, just use YouTube
