### ISSUE TITLE
feat(patch): sponsorblock chapters

### ISSUE THREAD

**Issue by venkat2305** [inotia00/ReVanced_Extended#134]
### Application

YouTube

### Issue

sponsor block has chapter support also. it would be great if it was implemented

### Patch

a patch to show the sponsor block chapters as normal chapters on the progress bar and chapter list 
![image](https://user-images.githubusercontent.com/55329452/211614168-58f18979-b398-407a-b7d0-21cfaab14993.png)

### Motivation

it improves user experience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Next time you write a new issue, please fill in the title

**Comment by venkat2305** [comment]
Sorry. I thought I did. It was an honest mistake.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
