### ISSUE TITLE
Use the same default downloader in YTM and YT 

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1340]
### Application

YouTube Music

### Description

Currently the default downloader in YTM is Seal, while the default in YT RVX is YTDLnis. It would make sense to use the same downloader for both (ie: change the YTM default to YTDLnis)

I think I once discussed this with you on reddit but forgot what you said.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
I can PR if you'd like

**Comment by inotia00** [comment]
This is already reflected in the private repo

**Comment by inotia00** [comment]
reflected in [revanced-patches-2.190.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.4)

**Comment by sleepingiv** [comment]
I suggest [Soundbound](https://play.google.com/store/apps/details?id=in.shabinder.soundbound) as default.
