### ISSUE TITLE
feat(YouTube Music): add `Hide double tap overlay filter` patch

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#1341]
### Application

YouTube Music

### Issue

Dark overlay filter is annoying on pause or when rewinding on full screen.

### Patch

res/layout/quick_seek_overlay.xml
```
<com.google.android.libraries.youtube.player.features.quickseek.overlay.CircularClipTapBloomView
        android:id="@id/tap_bloom_view"
        android:focusable="false"
        android:visibility="gone"
        android:layout_width="0.0dip"
        android:layout_height="0.0dip"
        android:contentDescription="@null"
        app:endColor="@color/quick_seek_bloom_end"
        app:startColor="@color/quick_seek_bloom_start" />
    <ImageView
        android:id="@id/dark_background"
        android:visibility="gone"
        android:layout_width="0.0dip"
        android:layout_height="0.0dip"
        android:src="@color/dark_transparent" />
```
res/layout/music_controls_overlay.xml
```
<View
            android:id="@id/player_control_screen"
            android:background="@android:color/transparent"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent" />
```

### Motivation

Full screen looks much better without the overlay filter while pausing or rewinding.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.210.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.210.1)
