### ISSUE TITLE
Patch Request:Prevent exit with the back button from libraries with old specifications.

### ISSUE THREAD

**Issue by harutoku** [inotia00/ReVanced_Extended#1345]
### Application

YouTube Music

### Issue

If you press the "Playlist", "Album", or "Song" button and then press the "Back" button in the system navigation, you will be returned to the home screen.

 YouTube version is 6.17.52, after applying "Enable old style library shelf".

### Patch

Modify the above, or make it possible to return by pressing the "Library" button on the navigation bar.

### Motivation

"Enable old style library shelf" can be applied to make the library easier to use.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1323
