### ISSUE TITLE
bug: Hiding Short Components aren't working after v2.190.1 upgrade.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1347]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

YouTube 18.34.37

### Bug description

Hiding Like, Dislike, Share, Remix, etc. aren't working after v2.190.1 upgrade.
![Screenshot_2023-09-07-07-28-33-06](https://github.com/inotia00/ReVanced_Extended/assets/91815107/aad41f0b-3fca-4d6f-af94-b55e4dd99fc1)
![Screenshot_2023-09-07-07-29-56-66_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/inotia00/ReVanced_Extended/assets/91815107/631d27c5-8f69-4fc8-9dcc-c692834a6f3b)

### Steps to reproduce

Just try to hide Like, Dislike, Share, Remix from Shorts. Then play some short.

### Relevant log output

```shell
No logs.
```

### Screenshots or videos

Given above.

### Device Environment

Realme 7 Pro, Android 12.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
The supported YT version is 18.31.40
