### ISSUE TITLE
mMicrog Patches

### ISSUE THREAD

**Issue by Mohammedibrahim15** [inotia00/ReVanced_Extended#1348]
### Application

mMicroG

### Description

Is there any intension to return mMicrog patches again?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
There are no plans to add it again, as it causes too much confusion for users

Also MicroG is an open source app, modifications can be made at the source code level without applying patches
