### ISSUE TITLE
feat(patch): Add Don't Recommend Channel button in shorts 

### ISSUE THREAD

**Issue by rks2000** [inotia00/ReVanced_Extended#135]
### Application

YouTube

### Issue

You have to go through the 3 dots button to access this Don't Recommend This Channel Button 

### Patch

![IMG_20230111_114506](https://user-images.githubusercontent.com/62375786/211732927-2fa49ee8-993f-4e66-85a6-bb2e8228ea9f.jpg)
![IMG_20230111_114839](https://user-images.githubusercontent.com/62375786/211732936-907ae93d-0975-4052-88cc-325d6bed23d2.jpg)

This patch will add direct button to the shorts player as shown in the image

### Motivation

This button is very useful to remove cringe youtube shorts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
