### ISSUE TITLE
bug: cannot submit new segments to sponsorblock 

### ISSUE THREAD

**Issue by thiswastheonlyavailableusername** [inotia00/ReVanced_Extended#1350]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.34.37

### Bug description

I create new segments as usual but when I press submit, nothing happens. Fyi works fine on regular revenced

### Steps to reproduce

Create segment start and end
Define type and preview it
Press submit
...
Nothing happens 

### Relevant log output

```shell
No relevant log
```

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
Try on the suggested YT version for RVX (18.31.40)

Also, im not entirely sure but I think the SponsorBlock patch is the same code as the revanced SponsorBlock. (A similar thing happened before where there was a bug in the RVX SponsorBlock that wasnt present in the ReVanced SponsorBlock)

**Comment by inotia00** [comment]
In [revanced-patches-2.190.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.4), SponsorBlock related code has been refactored.

Please re-patch with revanced-patches-2.190.4 and check if the issue still persists.

**Comment by thiswastheonlyavailableusername** [comment]
Yup, the new patches fix the issue. 
Thank you so much! 🙌
