### ISSUE TITLE
feat(YouTube Music): add `Hide action buttons` patch

### ISSUE THREAD

**Issue by harutoku** [inotia00/ReVanced_Extended#1351]
### Application

YouTube Music

### Issue

In the button container, only radio buttons can be removed.

### Patch

![Screenshot_20230909-120206975 (1)](https://github.com/inotia00/ReVanced_Extended/assets/123850345/7636acc8-9242-4fc1-8bf4-639cb7b808d1)
![Screenshot_20230909-120253189 (1)](https://github.com/inotia00/ReVanced_Extended/assets/123850345/77b8244e-745f-4d8e-ba87-d2d9adee09ce)

remove these

### Motivation

You will be able to press all buttons without scrolling.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by s7san007** [comment]
Also, remove the separator of the dislike button.
![Screenshot_20230909_102353](https://github.com/inotia00/ReVanced_Extended/assets/130248949/12ca41dc-234d-442e-b428-d231b118da07)

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.207.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.207.1)

If you have additional feature requests, please open a new issue

**Comment by harutoku** [comment]
Thank you !!
