### ISSUE TITLE
bug(YouTube Music): dislikes count not updates

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1353]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube Music 6.17.52

### Bug description

Likes count updates as normal: when you tap on like button count increase and when you tap again dislikes count decreasing. But dislikes count have bug: when you tap on dislikes button count increase, but when you tap again count not changing, it will change only if u refresh the track interface.

https://github.com/inotia00/ReVanced_Extended/assets/110785596/c00d02b1-e0e7-40e2-bcd3-882eb88bff82

### Steps to reproduce

I desdribed in bug description

### Relevant log output

```shell
:/
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is a bug that can only be reproduced under very special circumstances, and I have no plans to fix it.

**Comment by girshcatt** [comment]
I tried this on phone, same bug

**Comment by inotia00** [comment]
This issue is also reproduced in the phone layout, but there are no plans to fix it
