### ISSUE TITLE
feat(YouTube Music): add `Disable redirect action` patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1354]
### Application

YouTube Music

### Patch

Add `Disable redirect action` patch to disable redirect action when you tap dislike button and get redirected to next track

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
P.S. I suddenly remembered that this option can become much better if u will try to fix https://github.com/inotia00/ReVanced_Extended/issues/1353

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1)
