### ISSUE TITLE
feat(YouTube Music): add `enable-old-style-lyrics` patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1355]
### Application

YouTube Music

### Issue

This patch will add old style lyrics menu switch in settings (defalut off)
In last YTM versions google added "like spotify" lirycs menu, can you add feature to bring back old lyrics menu. This is most detailed description i can give, sorry.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by s7san007** [comment]
Add the patch to spoof the version to 6.08.50 or 6.10.52.
Something like that.
![Screenshot_20230909_144216_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/fcb87a76-d85e-4096-be4e-1740bebb5239)

YT Music 6.17.52 before spoofing.
![Screenshot_20230909_145445_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/93890400-5ab6-4c76-8f6d-2aac1adda9c6)

YT Music 6.17.52 after spoofing to 6.08.50 or 6.10.52.
![Screenshot_20230909_145524_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/b435daaa-b4ed-49ef-8699-3f2747ac1700)

**Comment by girshcatt** [comment]
Now this function really needed, ytm deleted much lyrics that not interactive

**Comment by s7san007** [comment]
@inotia00 

Can you add two spoofing versions?
1. v6.10.52 for lyrics in plain text.
2. v4.27.53 for Canadians.

Or give the option to put the version in yourself.

**Comment by girshcatt** [comment]
> @inotia00
> 
> Can you add two spoofing versions?
> 
> 1. v6.10.52 for lyrics in plain text.
> 2. v4.27.53 for Canadians.
> 
> Or give the option to put the version in yourself.

I think to improve `spoof-app-version` he need to make it like this:

Spoof app version (off/on)
6.10.52 - Restore lyrics in plain text (chosen by defalut)
4.27.53 - To make YT Music work for Canadians

Edit spoof app version

**Comment by inotia00** [comment]
I was informed of an issue of force close occurring related to the `spoof-app-version` patch, so it is difficult to reflect on this until the exact cause is confirmed

**Comment by girshcatt** [comment]
related to only spoof on old version like 4.27.53 or related to spoof app in general?

**Comment by inotia00** [comment]
I am the only one running the project, and there are so many things I have to do alone.

So implementation of this patch is not a priority

I'm not sure, but it will be implemented someday

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.193.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.4)
