### ISSUE TITLE
yt-music: Return YouTube Dislikes not working on phone

### ISSUE THREAD

**Issue by PikaGamer8** [inotia00/ReVanced_Extended#1359]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube Music / RVX Music (6.17.52)

### Bug description

I patched the YouTube Music app on version 6.17.52. I then exported it to both my Samsung A53 (phone) and Samsung Tab A7 Lite (tablet). Downloaded them both and only the tablet version has dislikes. I tried with another APK file, different versions of RVX music, and redownloaded the manager even. Still doesn't work.

### Steps to reproduce

1. include "Return YouTube Dislike"
2. open RVX Music
3. tap any song

### Relevant log output

```shell
Don't have any
```

### Screenshots or videos

**Tablet version of RVX Music**
![Screenshot_20230909_100639_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/77557847/317e8798-cf82-487a-907b-82319d171af8)

**Phone version of RVX Music**
![Screenshot_20230909_100640_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/77557847/c302a8c1-8092-4136-9dc2-1214a432f6dd)

### Additional context

Is this something on my end because it probably is, I just want to know how to fix it and yes Return YouTube dislikes is on.

### Device Environment

Android 13
One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
I also facing this issue on phone: Dislikes not appear, after some app restarts they appear

**Comment by PikaGamer8** [comment]
Fixed: had to ignore suggested version from the manager but because YouTube barely changed anything throughout that time, it works perfectly fine 😊
