### ISSUE TITLE
feat(patch): Can we get rid of this banner from the Homepage?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#136]
### Application

YouTube

### Issue

There's this banner on the Homepage (screenshot attached).
![IMG_20230111_132354](https://user-images.githubusercontent.com/91815107/211752292-a0ae9118-9a1a-461c-9908-1d5477ac9e98.jpg)

### Patch

A toggle to turn that banner on or off.

### Motivation

That banner is redundant.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.166.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.18)
