### ISSUE TITLE
bug(YouTube): Feed flyout related settings not work on tablets

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1360]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.31.40

### Bug description

Settings related to feed flyout menu not work on tablets cause of different ui
![Screenshot_20230909_200150_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/f6a74f1d-0254-42d0-b6d0-80f1a587a3b7)
For example phone feed flyout:
![IMG_20230909_200429_072](https://github.com/inotia00/ReVanced_Extended/assets/110785596/b408b31e-b149-4288-b4e6-d459dab4eb99)
And tablet feed flyout:
![Screenshot_20230909_200223_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/b36c3081-548c-4cd2-86f1-04f954b5afda)
Can you adapt these things to work on tablets?

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
Sorry for the question, but why u dont want to even comment these tablet ui problems? I not ask to new function, just to or mark these as valid issues or as known issues

**Comment by inotia00** [comment]
Since I no longer have the tablet, I can no longer fix issues that occur on the tablet, and I also do not receive reports of issues.
