### ISSUE TITLE
feat(patch): Ability to hide Account Menu Components.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1361]
### Application

YouTube Music

### Issue

Just like RVX, can we get the ability to hide components in Account Menu of RVX Music?

### Patch

Ability to hide these is what I'm requesting.
![Screenshot_2023-09-10-08-47-59-28_0ee52a21b47f2484ca705d66bfb85bda](https://github.com/inotia00/ReVanced_Extended/assets/91815107/1d892813-7762-430c-b224-17552bd25047)

### Motivation

1. Recently, inotia00 added many hiding features of RVX to RVX Music. That's why.

2. Cleaner look.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)
