### ISSUE TITLE
feat(patch): add custom overlay opacity patch from revanced

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1363]
### Application

YouTube Music

### Issue

i understand you not wanting to add any more features to yt, but can you please consider adding the feature for custom overlay opacity? https://github.com/ReVanced/revanced-patches/pull/2721 

### Patch

the patch allows user to select custom opacity for player background overlay, ranging from 0 to 255- 0 for transparent and 255 for opaque.
i think you can even remove hide player overlay patch because it will get covered by this patch.

### Motivation

i think its an awesome patch

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by johnconner122** [comment]
@inotia00 I'll open a PR, if you're willing?

**Comment by inotia00** [comment]
I have no plans to add new features other than fixing existing bugs

**Comment by MondayNitro** [comment]
> I have no plans to add new features to YouTube other than fixing existing bugs

now that you decided to add rex features, can you please include this feature from revanced? i really want to use this feature, but dont wish to shift to revanced just for this.
please reconsider sir!

**Comment by inotia00** [comment]
> > I have no plans to add new features to YouTube other than fixing existing bugs
> 
> now that you decided to add rex features, can you please include this feature from revanced? i really want to use this feature, but dont wish to shift to revanced just for this. please reconsider sir!

I still don't receive new `patch-request` suggestions for YouTube

Instead, if someone leaves a PR, I am merging it after sufficiently reviewing it
The reason the rex feature was merged is also because he opened PR

If you want that feature, simply open the PR

**Comment by inotia00** [comment]
> @inotia00 I'll open a PR, if you're willing?

A month ago I dismissed your comment because I thought it wouldn't add any features
Now, considering the efforts of the person who opened the PR, I am merging cases where the PR is opened as an exception
If you want it implemented, please open a PR

**Comment by MondayNitro** [comment]
> @inotia00 I'll open a PR, if you're willing?

bro, can you open a pr for this feature, i know nothing about github. i only created the account to report bugs and make feature requests on this repo : (
