### ISSUE TITLE
Merging ReX updates

### ISSUE THREAD

**Issue by Johny2074** [inotia00/ReVanced_Extended#1364]
### Application

YouTube

### Description

Hi sir 
I inquire about merging ReX changes that have been made as PR in patches repository
Will you merge them or this won't be done as you said that there won't be new features added to YouTube 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
For YouTube I have no plans to add any new features
