### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Bleblebleh** [inotia00/ReVanced_Extended#1366]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube Vanced 18.21.34

### Bug description

Can't watch more than 1:09 minutes of a video. Exactly at this time it stops and loads, for no reason, as if there were no connexion. Actually there is. 

### Steps to reproduce

Step 1 : open the app
Step 2 : click on any video
Step 3 : watch till it suddenly loads
Step 4 : check out your connexion
Step 5 : your connexion is fine but YouTube isn't working. You can cry now. 

### Relevant log output

```shell
Whats a log output
```

### Device Environment

Emui 12.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
I believe you are in the wrong repository.

If this is regarding YT ReVanced Extended, update to theblatest version and enable the Spoof player parameter toggle found in the Miscellaneous settings.
