### ISSUE TITLE
feat(patch): add `custom-playback-speed` patch for YouTube Music reopened

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1367]
### Application

YouTube Music

### Issue

https://github.com/inotia00/ReVanced_Extended/issues/1338#issuecomment-1720023471_ i reopened the issue, in tagged issue i explained all

### Patch

:/

### Motivation

:/

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)
