### ISSUE TITLE
How do i get this patch?

### ISSUE THREAD

**Issue by SOUL1INFINITY0** [inotia00/ReVanced_Extended#1368]
### Application

YouTube

### Description

I want to know how do i get this particular patch because it allowed me to play 4k so i really want this again
![Screenshot_2023-09-15-09-57-05-249_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/107400184/ec9daedb-19c0-4a21-b7d6-34d828e20ecd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
That patch was incorporated into the force vp9 codec patch

**Comment by SOUL1INFINITY0** [comment]
> That patch was incorporated into the force vp9 codec patch

so if i enable "force vp9 codec" it's gonna enable it?
