### ISSUE TITLE
suggestion: <title>: Regarding preview playback and history

### ISSUE THREAD

**Issue by paichikubeach** [inotia00/ReVanced_Extended#1371]
### Application

YouTube

### Description

I would like to go back to the time when thumbnail video previews did not remain in the history for a certain period of time. The moment a preview is played, it is left in the history, and the history that you don't remember playing increases, and even channels you don't need are displayed in the recommended list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a side effect of the Spoofing player parameter patch.

Turn off the spoofing player parameter or disable autoplay in your feed.

**Comment by KobeW50** [comment]
You can disable Playback in feeds. Settings > General > Playback in feeds, off
