### ISSUE TITLE
question: Plans for Readding MicroG patches

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1372]
### Application

mMicroG

### Description

Is there any future plans for re-adding MicroG patches again in rvx-builder. As you have removed it in last patch (i.e. august). As it helps us to hide MicroG from home and launcher. Just Asking. 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1348#issuecomment-1710503283
