### ISSUE TITLE
bug: <PANTALLA NEGRA PAUSADA AUTOMÁTICAMENTE>

### ISSUE THREAD

**Issue by inframundor** [inotia00/ReVanced_Extended#1373]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube V. 18.25.38

### Bug description

When I'm watching a video, suddenly the video screen goes black and no longer loads... The video stops watching and even if you close, open again or delete the data and watch that video again, the same thing always happens. Sometimes he lets me watch videos, but it's very common for it to happen and go black and stop watching the videos. 

### Steps to reproduce

Idk

### Relevant log output

```shell
Idk
```

### Screenshots or videos

![Screenshot_20230915-213441_YouTube ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/66843707/62282249-4847-40bc-84df-524ee74c91af)
![Screenshot_20230915-213423_YouTube ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/66843707/11daec6f-cd07-4cec-bb1c-e2c9e735a3f2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
Update to the latest version (18.31.40 for ReVancedExtended). Then enable the Spoof Player Parameter toggle in the Miscellaneous settings of YT ReVanced Extended
