### ISSUE TITLE
feat(YouTube Music): add `Player background color` patch

### ISSUE THREAD

**Issue by ZeroZero0011** [inotia00/ReVanced_Extended#1374]
### Application

YouTube Music

### Issue

.

### Patch

Is it possible to make the music player theme just black instead of a theme that changes based on the music album image?

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [x] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In the case of mini player, you can make it a black theme by turning off the following settings:

Settings > ReVanced Extended > Player > Enable color match player

But I don't completely understand what you mean, so I think attaching a screenshot would help me understand the issue

**Comment by ZeroZero0011** [comment]
-Current theme (Background changes automatically)-
![Screenshot_20230916-185859_ReVanced Extended Music~01](https://github.com/inotia00/ReVanced_Extended/assets/132404645/844c947d-359a-48a0-830b-579183f23a5d)

-Black Theme (Background is Only Black, Its Spotify Xmanager Amoled patched)-
![Screenshot_20230916-185945_Spotify~01](https://github.com/inotia00/ReVanced_Extended/assets/132404645/30faba1f-faa6-4628-8d0a-40c2630077fa)

**Comment by Aryan-Chauhan** [comment]
Good idea.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.8.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.4)
