### ISSUE TITLE
bug: "Disable shorts at startup" doesn't work

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1375]
### Type

Other

### Tools used

rvx-builder

### Application

YT 18.31.40

### Bug description

The "Disable Shorts at app startup" option doesn't work in latest version. It is broken currently in both RVX and REX. Can you try to fix this issue as it is completely broken. 

### Steps to reproduce

No steps

### Relevant log output

```shell
...
```

### Screenshots or videos

Not Required... If Dev asks, I'll try to provide it. 

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
looks like A/B tests

Currently my patch supports YouTube v18.19.36 to YouTube v18.31.40, temporarily you can use YouTube v18.19.36, which is the lowest supported version

**Comment by Vipin2003** [comment]
Ohh... That's the reason. And there are some options missing like option to hide autoplay button, caption button not hidden, etc. Is it also related to that ?

**Comment by inotia00** [comment]
It is difficult to help you if you do not explain the issue in detail
Open a separate issue and add a description

**Comment by Vipin2003** [comment]
Ohkk... I'll do it in 2-3 days. Well Thanks for quick response bro,

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)
