### ISSUE TITLE
feat(YouTube Music): add double tap to seek function

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1376]
### Application

YouTube Music

### Patch

Add double tap to seek in ytm like it was in yt, also add menu in patch options to change values

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
double tap to seek feature already exists
just double tap the album image while playing

**Comment by girshcatt** [comment]
No, i mean to change value of skip time

**Comment by girshcatt** [comment]
U understood wrong, maybe i wrote not detailed as needed
