### ISSUE TITLE
bug: <Can't patch YouTube version 18.19.36>

### ISSUE THREAD

**Issue by eaui1997** [inotia00/ReVanced_Extended#1377]
### Type

Error while patching

### Tools used

rvx-builder

### Application

v18.19.36

### Bug description

The error below appears on both rvx-builder and revancify near the end of the patching process.

### Steps to reproduce

Here from revancify

INFO: Compiling modified dex files 
INFO: Compiling modified resources 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/revanced-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537729984, --version-name, 18.19.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL2771407038468247370.tmp, -0, arsc, -I, /data/data/com.termux/files/home/revancify-data/revanced-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/revanced-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/revanced-resource-cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:232)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:207)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/revanced-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537729984, --version-name, 18.19.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL2771407038468247370.tmp, -0, arsc, -I, /data/data/com.termux/files/home/revancify-data/revanced-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/revanced-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/revanced-resource-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 13 more

### Relevant log output

```shell
Here from rvx-builder

[builder] brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/home/rvx-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/rvx-builder/revanced-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537729984, --version-name, 18.19.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL11270817903189977139.tmp, -0, arsc, -I, /data/data/com.termux/files/home/rvx-builder/revanced-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/rvx-builder/revanced-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/rvx-builder/revanced-resource-cache/build/resources.zip] at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246) at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391) at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126) at app.revanced.patcher.Patcher.get(Patcher.kt:232) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:207) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40) Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/home/rvx-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/rvx-builder/revanced-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537729984, --version-name, 18.19.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL11270817903189977139.tmp, -0, arsc, -I, /data/data/com.termux/files/home/rvx-builder/revanced-resource-cache/1.apk, --manifest, /data/data/com.termux/files/home/rvx-builder/revanced-resource-cache/AndroidManifest.xml, /data/data/com.termux/files/home/rvx-builder/revanced-resource-cache/build/resources.zip] at brut.util.OS.exec(OS.java:104) at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242) ... 13 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
please attach a full list of patches included or excluded

**Comment by eaui1997** [comment]
> vui lòng đính kèm danh sách đầy đủ các bản vá được bao gồm hoặc loại trừ
Rooted: false
Arch: arm64-v8a
App: YouTube v18.19.36
CLI: inotia00-cli-v3.1.2.jar
Patches: inotia00-patches-v2.190.4.jar
Integrations: inotia00-integrations-v0.117.4.apk
Patches argument: -i bypass-ambient-mode-restrictions
-i change-homepage
-i custom-branding-icon-mmt
-i custom-double-tap-length
-i custom-package-name
-i custom-playback-speed
-i custom-seekbar-color
-i default-playback-speed
-i default-video-quality
-i disable-quic-protocol
-i disable-shorts-on-startup
-i disable-auto-captions
-i disable-haptic-feedback
-i disable-hdr-video
-i disable-pip-notification
-i enable-compact-controls-overlay
-i enable-external-browser
-i enable-minimized-playback
-i enable-new-comment-popup-panels
-i enable-new-splash-animation
-i enable-new-thumbnail-preview
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-tablet-mini-player
-i enable-tablet-navigation-bar
-i enable-time-stamps-speed
-i enable-wide-search-bar
-i force-opus-codec
-i force-vp9-codec
-i header-switch
-i hide-account-menu
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-autoplay-preview
-i hide-button-container
-i hide-captions-button
-i hide-cast-button
-i hide-category-bar
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-collapse-button
-i hide-comment-component
-i hide-crowdfunding-box
-i hide-description-components
-i hide-end-screen-cards
-i hide-end-screen-overlay
-i hide-feed-flyout-panel
-i hide-filmstrip-overlay
-i hide-floating-microphone
-i hide-fullscreen-panels
-i hide-general-ads
-i hide-handle
-i hide-info-cards
-i hide-latest-videos-button
-i hide-layout-components
-i hide-load-more-button
-i hide-mix-playlists
-i hide-music-button
-i hide-navigation-buttons
-i hide-navigation-label
-i hide-player-button-background
-i hide-player-flyout-panel
-i hide-player-overlay-filter
-i hide-previous-next-button
-i hide-quick-actions
-i hide-seek-message
-i hide-seekbar
-i hide-shorts-components
-i hide-snack-bar
-i hide-speed-overlay
-i hide-suggested-actions
-i hide-suggested-video-overlay
-i hide-suggestions-shelf
-i hide-time-stamp
-i hide-tooltip-content
-i hide-trending-searches
-i hide-video-ads
-i language-switch
-i layout-switch
-i microg-support
-i optimize-resource
-i overlay-buttons
-i return-youtube-dislike
-i settings
-i sponsorblock
-i spoof-app-version
-i spoof-player-parameters
-i swipe-controls
-i theme
-i translations

**Comment by eaui1997** [comment]
Oh, sorry, The error occurred due to changing the theme color, sorry for wasting your time.
