### ISSUE TITLE
bug(youtube/materialyou): Splashscreen sometimes has wrong background

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#1380]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

YouTube 18.31.40 patches 2.190.4

### Bug description

In some rare cases, using the materialyou theme, the initial youtube splash screen is white (I have dark theme). I haven't tested the other way around. Only start splash screen has wrong background, splash animation is fine.

### Steps to reproduce

Step 1. Patch using materialyou theme

### Relevant log output

```shell
None
```

### Screenshots or videos

None, as hard to produce

### Device Environment

Android 13, pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
YouTube v18.36.39 is not a supported version.
You can only report issues that occurred in YouTube v18.19.36 ~ v18.31.40.

**Comment by ayushTNM** [comment]
Also happens on 18.31.40

**Comment by inotia00** [comment]
Change the version indicated in the content to v18.31.40 and reopen the issue.

**Comment by inotia00** [comment]
Also check if the issue reproduces when you exclude the `Material You` patch, and check if the issue reproduces on unpatched YouTube as well

For now, I'm just guessing it's a bug in YouTube.

**Comment by ayushTNM** [comment]
Unfortunately, you are correct. Stock youtube has same bug

**Comment by inotia00** [comment]
yeah... this is a bug that Google needs to fix
