### ISSUE TITLE
bug(YouTube): useless setting for tablets

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1382]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.31.40

### Bug description

Hide category bar in related video is useless setting for tablets, cause this category bar not exist in tablet ui, just block the switch for tablet users

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Whether the category bar appears depends on whether you have a tablet or not, whether the category bar is available in your country, and whether you are a test user or not.

There are too many cases for whether the category bar is shown, so I cannot enable or disable it for specific users.

**Comment by girshcatt** [comment]
If u didn't undersoot i say about not all category bars, i wrote about related videos category bar in tablet ui

**Comment by girshcatt** [comment]
This tested in same account if u not believe
phone
![IMG_20230917_194558_525](https://github.com/inotia00/ReVanced_Extended/assets/110785596/398a115d-8ce5-463a-870f-f80eac478ab4)
tablet
![Uploading Screenshot_20230917_194434_ReVanced Extended.jpg…]()
