### ISSUE TITLE
bug(YouTube/Overlay buttons): When entering fullscreen on a tablet device, overlay button does not hidden immediately

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1383]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.31.40

### Bug description

I have a tablet, my screen dpi is 360, u can try to reproduce issue on 360 dpi
When you go in fullscreen when video paused all normal, but when you in pause menu not paused go in fullscreen overlay buttons appear on a second on screen, sorry for so dumb explanation because of my English level, i think it will easier to understand by screen recordings
1.When video paused

https://github.com/inotia00/ReVanced_Extended/assets/110785596/11adcaba-ba3c-4413-876a-19b691acef36

2.When video in plays in pause menu

https://github.com/inotia00/ReVanced_Extended/assets/110785596/a68ec945-e047-4ca1-b3ce-391f6a465a77

I caught a time from screen recording and screenshoted it
![Screenshot_20230918_000652_Gallery](https://github.com/inotia00/ReVanced_Extended/assets/110785596/20919753-68e2-49f7-ad33-3d045fb3f7f0)

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/1450

**Comment by girshcatt** [comment]
Also sb vote button affected

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1)
