### ISSUE TITLE
bug(YouTube/Overlay buttons): Overlay button is hidden late even when not in fullscreen

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1384]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.31.40

### Bug description

Overlay buttons dissappear a little bit lately than all other player elements

https://github.com/inotia00/ReVanced_Extended/assets/110785596/14e10a47-3ccd-4b29-a357-b0f2400c5175

https://github.com/inotia00/ReVanced_Extended/assets/110785596/6440f8cb-6a90-49d6-a439-da83169b0e24

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/1450

**Comment by girshcatt** [comment]
Same with SponsorBlock create button, i will edit issue

**Comment by girshcatt** [comment]
Also sb vote button affected

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1)
