### ISSUE TITLE
bug(enable-old-style-library-shelf): can't return to the old library shelf

### ISSUE THREAD

**Issue by rx443** [inotia00/ReVanced_Extended#1386]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube Music v6.19.51

### Bug description

Clicking the 'X' button or using the back button does not return to the old library shelf.

### Steps to reproduce

1. Navigate to the Library tab.
2. Select an item from the list.
3. Attempt to return to the Library tab by clicking the "X" button or using the back button.

### Solution

- Hide the Category bar on the Library tab
- Add a back button
- Click the back button (in the app and system navigation bar) to return to the old library shelf

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
Same problem, 100% same
