### ISSUE TITLE
question: how can i use normal dark mode instead of amoled one in revanced extended?

### ISSUE THREAD

**Issue by KParthSingh** [inotia00/ReVanced_Extended#139]
### Application

YouTube

### Description

Amoled dark mode looks horrible in my devices is there any way to turn it off and use normal one instead?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
exclude `theme` patch and `materialyou` patch
