### ISSUE TITLE
suggestion(YouTube): add strings to translate some words in patches information section

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1390]
### Application

YouTube

### Description

Add strings to translate some words in patches information section. Words i say about: included, excluded

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
refer to the previous issue https://github.com/inotia00/ReVanced_Extended/issues/218

**Comment by girshcatt** [comment]
ok, i understood the reason, thanks
