### ISSUE TITLE
suggestion(YouTube): add "About" string to translations

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1392]
### Application

YouTube

### Description

I will try to explain the reason as simple as i can. In English word "About" not need any additional word. In SB and RYD as i understood you use internal youtube "About" string. But in dome languages like Russian "About" need some additional word like: About app or about integration. Internal YouTube About string that you use mean about app, and this is sounds incrorrect when we say about ryd, sb integrations.
Solution is to add rvx own "About" string like you did "revanced_ryd_about" string in YTM 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.190.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.12)
