### ISSUE TITLE
question: Where did the whitelist button go?: 

### ISSUE THREAD

**Issue by kyoforkshomebrews** [inotia00/ReVanced_Extended#1396]
### Application

YouTube

### Description

There used to be a button to whitelist sponsorblock and ads but now I can't find it any more. Is that on purpose or a bug?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
It was removed several months ago

https://github.com/inotia00/ReVanced_Extended/issues/918#issuecomment-1533244461

You may be referring to the whitelist feature in the ReX patches, which isn't associated with this repository
