### ISSUE TITLE
Suggestion for "Add to queue" feature on youtube

### ISSUE THREAD

**Issue by MirakuruSan** [inotia00/ReVanced_Extended#1397]
### Application

YouTube

### Description

I'm not a developer so this will sound dumb. Is there a way to hook the "add to queue" button to a script that just saves the link of the video added and then just redirect to that saved link after the current video ends? Cause we don't want that feature to work exactly like premium but just enough to get the job done ,just like being able to hook download button to an external app like newpie.

Sry if this annoys any developer I'm just dumb.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/122
