### ISSUE TITLE
bug: `hide-suggestions-shelf` does not work in tablet

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1398]
This is a limitation of the current patch method

To solve this issue we need a more ideal way to hook the navbar index

_Originally posted by @inotia00 in https://github.com/inotia00/ReVanced_Extended/issues/1327#issuecomment-1719083095_
            
After you changed hide suggestions patch it stopped to work right on tablets, now it create blank space instead of suggestion shelves like on this screen recording

https://user-images.githubusercontent.com/110785596/269413020-35245ccb-2f82-473d-8a7a-db720e74eb53.mp4

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.12)
