### ISSUE TITLE
feat(patch): remove other privotbar

### ISSUE THREAD

**Issue by Sp3eDaH** [inotia00/ReVanced_Extended#14]
### Application

□

### Issue

I would like to have a way to basically remove recommended videos from the app. Removing videos to scroll through makes people like me spend much less time watching stuff we might not really want to watch

### Patch

Patch to remove homepage / recommended tab (like the patch that removes the shorts tab)

Also maybe possibly removing recommended videos below the video player as well, either in a seperate patch or the same one

### Motivation

I would love you forever

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Zedroid** [comment]
in custom filter under revanced>ad settings add this word without quotations: "home" now i wont immediately be forced to see a potential channel I might bingewatch and I can finally focus on my homework!
![image](https://user-images.githubusercontent.com/14794946/217995660-fc764ffd-dd7f-43ed-b9d8-0c2fc9fdf381.png)

**Comment by Zedroid** [comment]
![Screenshot_20230316_071715_YouTube](https://user-images.githubusercontent.com/14794946/225645656-989bb59c-7329-4480-b661-4c1d2e839e69.jpg)

**Comment by Zedroid** [comment]
![Screenshot_20230316_071945_YouTube](https://user-images.githubusercontent.com/14794946/225646643-d57931f9-7dcb-4b93-98ad-91115f14d641.jpg)Bad news notifications won't show in the tab menu with new method

**Comment by Zedroid** [comment]
![Screenshot_20230415_070214_One UI Home](https://user-images.githubusercontent.com/14794946/232229183-d7993610-6d29-40ed-8364-4a0a33fdde23.jpg)
YouTube revanced don't launch home feed

1. Install Open link with app
2. Go to your channel 
3. Top right 3 dots click share in menu
4. Add your own channel to homescreen
5. Pick YouTube revanced
DONE! Now you can
Navigate with visible pivotbar to watch later or anywhere else

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.169.5](https://github.com/inotia00/revanced-patches/releases/tag/v2.169.5)

**Comment by ianmatt** [comment]
possible to also add an option/patch to remove Library tab?
