### ISSUE TITLE
question: is the base app downgraded to the old version?

### ISSUE THREAD

**Issue by nakpan8** [inotia00/ReVanced_Extended#1400]
### Application

YouTube

### Description

a few weeks ago I used yt rvx version 18.35.36. then in KernelSu there was an update notification which when I checked on github the latest version was 18.31.40.
is the base app downgraded to the old version? why?
...
and also is there no link to the telegram channel/group?
which will make it easier for users when there is an update, they will immediately know about it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
You say about ReX, not RVX, please clise your issue here and go to https://github.com/YT-Advanced/YT-Advanced/issues

**Comment by girshcatt** [comment]
Here ReX and RVX chat https://t.me/revanced_extended_chat

**Comment by girshcatt** [comment]
If you need RVX updates notification channel, it is here https://t.me/revanced_extended_repo

**Comment by girshcatt** [comment]
RVX channel https://t.me/revanced_extended
ReX channel https://t.me/ReXgroups
