### ISSUE TITLE
Remove 'Share' from the default feed flyout menu filter

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1402]
### Application

YouTube

### Description

The share option is hidden by default when the feed flyout menu filter is enabled. It's a common issue for users. I saw it asked about several times on the subreddit.

The share option is just as useful as many of the other options in the feed flyout menu so I don't see why it's hidden by default.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.190.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.12)
