### ISSUE TITLE
bug(YouTube Music): show comment count when action bar labels are hidden

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1403]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube Music 6.15.52 ~ 6.19.51

### Bug description

Hide action bar labels should hide only labels, not numbers. This function will be much better if it wont affect comment count, anyway this is not even label, this is a number

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
The comment counter is also the label of the button

At least, from a code perspective it does

**Comment by girshcatt** [comment]
If you think that this is a label, can you do one more related setting to show comment count? This will be great improvement

**Comment by inotia00** [comment]
Yeah.. I was just providing an explanation as to why this is not a `bug` label

If you open an issue with a request for an exception to the `hide-action-bar-label` patch with the `patch-request` label, it is a valid issue

**Comment by girshcatt** [comment]
Thanks for reply one more time, this will be really useful
