### ISSUE TITLE
feat(YouTube Music/Hide flyout menu): add unimplemented settings

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1404]
### Application

YouTube Music

### Patch

Add unimplemented settings, such as: `Hide stats for nerds`, `Hide shuffle play`, `Hide edit playlist`, `Hide delete playlist` and `Hide quality` menus

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by hlytus** [comment]
While er are at it, add `Quality` as well.

<img src="https://i.imgur.com/LX66EPX.jpg" width="400">

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.209.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.209.1)
