### ISSUE TITLE
bug(YouTube Music/Enable compact dialog): off this option by defalut and block this switch for tablets

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1405]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube Music 6.15.52 ~ 6.19.51

### Bug description

Because Enable compact dialog option was made to phones can you do it turned off by defalut and block switch in settings for the tablets?

I think that more correct to say not "block switch for tablets", more correct to say "block the switch to devices with DPI higher than DPI on which this option will work

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
no need to worry about it

When a tablet device is detected, patches are not applied to the tablet even if the switch is turned on
