### ISSUE TITLE
bug: info cards arent hidden anymore

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1406]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.25.40(present in supported versions list)

### Bug description

info cards arent hidden anymore

### Steps to reproduce

enable hide info cards
play a video to see info cards

### Relevant log output

```shell
.
```

### Screenshots or videos

![photo_6084716005906560954_w](https://github.com/inotia00/ReVanced_Extended/assets/87489540/131879af-b9d6-40d7-afc5-15e868a90f57)
![photo_6084716005906560955_w](https://github.com/inotia00/ReVanced_Extended/assets/87489540/cc6195ff-c98b-4556-b3bb-2030311d4695)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
Related issue in the ReVanced patches repo

https://github.com/ReVanced/revanced-patches/issues/2933

A commenter gave a component name you can filter and it supposedly hides the info card. I havent tested in rvx tho

**Comment by inotia00** [comment]
when the `A/B test` labels were added, they were already merged into the private repository

**Comment by root-kernelhacker** [comment]
I am also not hidden from REX and inotia00's RVX.

If you spoof the app version, it will be hidden, but there is a problem with other patches not working.

If you spoof the app version, infinite buffering will occur during video playback. (Infinite buffering does not occur unless you spoof the app version)

**Comment by MondayNitro** [comment]
> Related issue in the ReVanced patches repo
> 
> [ReVanced/revanced-patches#2933](https://github.com/ReVanced/revanced-patches/issues/2933)
> 
> A commenter gave a component name you can filter and it supposedly hides the info card. I havent tested in rvx tho

thank you, the filter works

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.12)
