### ISSUE TITLE
suggestion: some patch names and settings are not properly labeled

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1407]
### Application

YouTube

### Description

Correct these strings to match ReVanced Extended just by adding "Extended" after "ReVanced":
Import ReVanced settings from file or export ReVanced settings to file;
Save your ReVanced settings to file;
Fetch ReVanced settings from saved file;
Your SponsorBlock JSON configuration that can be imported/exported to ReVanced and other SponsorBlock platforms. This includes your private user id. Be sure to share this wisely

P.S. i forgot to say about patch descriptions, but they need changes too
YT:
`microg-support`	Allows ReVanced to run without root and under a different package name with MicroG.;
`settings`	Applies mandatory patches to implement ReVanced settings into the application.

YTM:
`microg-support`	Allows ReVanced Music to run without root and under a different package name with MicroG.;
`settings`	Adds settings for ReVanced to YouTube Music.

Reddit:
`reddit-settings` Adds ReVanced settings to Reddit.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
I edited issue and added what else need to be changed

**Comment by inotia00** [comment]
title is too long

**Comment by KobeW50** [comment]
@inotia00 if you didn't yet reflect this in your private repo, I can do this when I am free

**Comment by girshcatt** [comment]
I saw that @inotia00 corrected strings, but only three, he forgot about "Your SponsorBlock JSON configuration that can be imported/exported to ReVanced and other SponsorBlock platforms. This includes your private user id. Be sure to share this wisely"

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.190.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.18)

**Comment by girshcatt** [comment]
You again forgot, you didnt changed `settings`	Adds settings for ReVanced to YouTube Music.

**Comment by inotia00** [comment]
fixed https://github.com/inotia00/revanced-patches/commit/c6d8e460525e5e43c23d44f213b4c4a0b456c6c0
