### ISSUE TITLE
question(YouTube Music/Buttons under player/Settings): what options or patches affect this? these look like bugs 

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1408]
### Application

YouTube Music

### Description

I dont know what affect these things, it looks like bugs, because there is no patches and options i found that should do this, ok, just look at these screenshotes and compare
1.Separating lines in settings that hidden in rvx for unknown reason
1)YT Music
![Screenshot_20230922_181500_YouTube Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/45e9cc9d-bb0a-4504-856e-b6ce40f4eebe)
2)RVX Music
![Screenshot_20230922_181614_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/08807126-10a4-418d-a493-895a06faae7e)

2.For unknown reason RVX music do one button looks fatter than others
1)YT Music
![Screenshot_20230922_181532_YouTube Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/2b48dd30-40d2-428e-82f0-35fa4ce73647)
2)RVX Music
![Screenshot_20230922_181643_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/2b99cfd9-9e9b-40e5-b4ad-bdda70a3bb33)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
1 is intended behavior

Including the `Settings` patch will remove all dividers (separators between lines)

2 is not reproduced

Exclude all patches except only the `Settings` patch and the `MicroG Support` patch and proceed with the patch.
And test if it reproduces

**Comment by girshcatt** [comment]
I patched only `Settings` and `MicroG Support` patch, 1 issue is the same, but it no more issue, because u said that this work as expected, but there is no 2 issue

**Comment by inotia00** [comment]
Check if the versions of YouTube Music (stock) and RVX Music are the same

In my case, YouTube Music (stock) installed on my device was v6.20.51 and RVX Music was v6.19.51

In the case of YouTube Music, the layout is slightly different depending on the version

![0923025955810740](https://github.com/inotia00/ReVanced_Extended/assets/108592928/9b377bf4-239a-4dd8-a28b-0c70417d7b53)

left: new layout of YT Music v5.47.54
right: new layout of YT Music v6.10.51

**Comment by girshcatt** [comment]
I checked all on 6.19.51 stock and patched

**Comment by girshcatt** [comment]
On your screenshot patched ytm or not?

**Comment by girshcatt** [comment]
For example unpatched ytm and patched 6.19.51
unpatched:
![Screenshot_2023-09-23-09-58-30-866_com google android apps youtube music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/37afc453-0a70-47fa-85c6-fb950a8f461e)
![IMG_20230923_095946](https://github.com/inotia00/ReVanced_Extended/assets/110785596/bd625a68-21f4-4c66-99ba-341c9993daa1)
patched:
![Screenshot_2023-09-23-09-59-00-080_app rvx android apps youtube music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/6f7950de-89ae-4640-a9b8-71d67faa747b)
![IMG_20230923_095946](https://github.com/inotia00/ReVanced_Extended/assets/110785596/ac7e6de0-e63f-440b-ba02-53a6b48785c2)

**Comment by girshcatt** [comment]
in fact button is much fatter on patched ytm

**Comment by girshcatt** [comment]
i will try to understand what i need to do to reproduce this, what cause this weird thing

**Comment by girshcatt** [comment]
Finally i found what causes bigger button, when Enable force shuffle turned on this button become bigger, when it turned off button become normal
I think that this is not expected behaviour, at least this looks not perfect

**Comment by inotia00** [comment]
I didn't know you were talking about the shuffle button

If you change `Enable force shuffle` to ON, it will change the shuffle button in the player to always on.

this is intentional behavior 😅

**Comment by girshcatt** [comment]
Oh no, i so dumb, i just didn't use shuffl button, i thought that why it get bigger? I didn't expected that when this button on it will look more bigger😅

**Comment by inotia00** [comment]
Just click the shuffle button

When shuffle is ON, the button becomes fat, and when shuffle is OFF, the button becomes thin
