### ISSUE TITLE
Filltozoom bug: <fill to zoom>

### ISSUE THREAD

**Issue by es419** [inotia00/ReVanced_Extended#1409]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

Rvx and rex version 18.31.40

### Bug description

Fill to zoom not working. 

### Steps to reproduce

Enable fill to zoom feature after patch

### Relevant log output

```shell
None
```

### Solution

Change to version to lower then 18.31.40

### Additional context

Since version 18.31.40 fill to zoom not working

### Device Environment

One ui 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [ ] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This issue also appears on unpatched YouTube and is an issue that Google needs to fix.
