### ISSUE TITLE
feat(YouTube Music/YouTube): use "Quick download" option instead of usual for Seal downloader

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1411]
### Application

YouTube Music, YouTube

### Issue

Seal have two download options:
1.Usual download when your app closes and redirect you to Seal
2.Quick download option that open popup download window without app close
YouTube and YTM when you set `com.junkfood.seal` package as downloader it uses the usual download option. In fact first and second download options do the same work, but quick download is much easier for most of people.
Can you change that if you set Seal as downloader in YT or YTM it will redirect you to "Quick download" option instead of usual?

P.S. And yes, i know that you wont add any features to YT, just a little change if you agree with it :)
### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
You can set this the first time you use the download function with Seal. 

![Screenshot_20230924_042703_Android System.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/620abd2c-0b74-4e8d-b9f4-44b76afb636d)

If you want to get this prompt again so you can choose to always have the quick download option you can go to the App info of Seal > Set as default > Clear defaults. (May be slightly different on your device)

**Comment by girshcatt** [comment]
KobeW50, i have samsung too, i cleared Seal data, but nothing. If i right this choice dialog opened last time on 2.173.10

**Comment by girshcatt** [comment]
Now it automatically redirect me to usual Seal download

**Comment by inotia00** [comment]
Unfortunately, this patch cannot be implemented on YouTube or YouTube Music
