### ISSUE TITLE
 suggestion: Add compatibility to the latest versions of YouTube.

### ISSUE THREAD

**Issue by Karell2013** [inotia00/ReVanced_Extended#1412]
### Application

YouTube

### Description

A suggestion, it may be possible to add new compatibility with the latest versions of YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The latest version has many broken patches on the client side, so there are no plans to support it for the time being
