### ISSUE TITLE
bug: When the hook download button is enabled, YT Music randomly crashes after 3-5 minutes

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#1413]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

**Version**: v6.19.51, v6.20.51
**Patches**: 2.190.8, 2.190.12

### Bug description

When I leave the YTM window to go to another application (music plays in the background), it crashes instantly after about 3-4 minutes when I want to return to the application. I've had the problem since patches probably 2.190.8 and have no idea why this is happening.

### Steps to reproduce

1. Play any song
2. Go to other apliccation for a short while (3-5 minutes), leave app in the background
3. Return to YTM
4. Crash ;(

### Relevant log output

```shell
I don't have log output.
```

### Device Environment

**Device**: Huawei JNY-LX1
**Version**: EMUI 12
**Compilation number**: 12.0.0.285 GPU Turbo

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by GucekPL** [comment]
Ok, I will be checking patches after my school. I will you reply if I will find patch which causes the problem.

**Comment by inotia00** [comment]
To resolve your issue you must provide:
1. Export the settings and then paste them here
2. Tell me the language of the system in which the issue is reproduced

Or.. attach the logcat when the error occurred

**Comment by inotia00** [comment]
I've added changes in [revanced-patches-v2.190.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.15) to make patches slightly more safety
related commit: https://github.com/inotia00/revanced-integrations/commit/8565a432dd5ea0595e720d4a36afc6136babcca1

Since this issue does not reproduce on my side, I cannot confirm whether issue has been fixed.

Patch with revanced-patches-v2.190.15 and check if the issue reproduces

**Comment by GucekPL** [comment]
I confirm that safer method of applying the `hook-download-button` is working. YTM is not crushing now. Thanks for your hard work, nice day I wish!
