### ISSUE TITLE
question(YouTube): add link to YT translation in crowdin to patch releases description as before

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1415]
### Application

YouTube

### Description

Some time ago when your YT crowdin projects was abandoned you removed link in patch releases description, since you opened them again you can add it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected
