### ISSUE TITLE
bug(YouTube music):Hiding labels in the action bar does not work well.

### ISSUE THREAD

**Issue by harutoku** [inotia00/ReVanced_Extended#1416]
### Type

Error at runtime

### Tools used

Revancify

### Application

In YouTube music 6.20.51.

### Bug description

When the action bar label is hidden, there is a large gap between the buttons.

### Steps to reproduce

step. 1 Open the revanced extended settings,
player→enable new style player
step. 2 Action Bar→Hide action bar labels

### Relevant log output

```shell
、
```

### Screenshots or videos

![Screenshot_20230925-212042445](https://github.com/inotia00/ReVanced_Extended/assets/123850345/01b8095d-4b2a-4ebc-976d-ba9e16d70879)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Try a clean install of the app, or change new layout to off and then back on

This is a bug in new layout, and an issue that Google needs to fix
