### ISSUE TITLE
bug: Youtube v18.31.40 - Cast button not present

### ISSUE THREAD

**Issue by Theletha** [inotia00/ReVanced_Extended#1417]
### Type

Other

### Tools used

ReVanced Manager

### Application

Current recommended YT version for patching 18.31.40

### Bug description

There is no cast button in the app.

### Steps to reproduce

open app, connect to home wifi. 
Then the cast button should appear 

### Relevant log output

```shell
if needed i can provide
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
did you turn off the `Hide cast button`?

**Comment by Theletha** [comment]
> did you turn off the `Hide cast button`?

in the patcher or in the YT settings of the app?
