### ISSUE TITLE
feat(YouTube Music/Settings): add `Open MicroG` settings

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#1418]
### Application

YouTube Music

### Issue

No real issue

### Patch

Add open microg button to also be able to access microg through ytm

### Motivation

Mainly for if icon is hidden

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)
