### ISSUE TITLE
feat(YouTube Music/Settings): import/export as files

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#1419]
### Application

YouTube Music

### Issue

It is easier to just save config to file instead of copy pasting everytime

### Patch

Adjust the import/export to save/load a xml file like in YouTube rvx

### Motivation

Making saving and loading setting configs easier

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
I think that for now YTM has no too much settings to save them in file, text is much easier to editing, in YTM situation text import/export solution

**Comment by ILoveOpenSourceApplications** [comment]
Is the current import/export option not fully implemented for YT Music because it's broken currently.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)
