### ISSUE TITLE
feat(patch): Add option to change sample rate (audio output) to YouTube

### ISSUE THREAD

**Issue by nickarcade** [inotia00/ReVanced_Extended#142]
### Application

YouTube

### Issue

Add an option for Revanced Extended to allow a user to adjust the sample rate through the app for enhanced sound quality. I'm specifically requesting this for YouTube but could very well be extremely beneficial for YouTube Music also (I've never used Music so I'm not sure if that option is already there).

### Patch

Here are some screenshots through the Poweramp media player as an example
![Screenshot_20230111-221742_Poweramp](https://user-images.githubusercontent.com/110382828/211968001-96be5ad3-e0ae-4544-b321-5d1614b2558b.png)
![Screenshot_20230111-221755_Poweramp](https://user-images.githubusercontent.com/110382828/211968021-84905a14-1082-45f2-abd6-1dad48cabff5.png)
![Screenshot_20230111-221808_Poweramp](https://user-images.githubusercontent.com/110382828/211968076-b6695775-b9c0-4f4a-91b8-50de87ac830d.png)
![Screenshot_20230111-221815_Poweramp](https://user-images.githubusercontent.com/110382828/211968091-de4dff15-b6fe-436e-9d2b-f75f8a79ae2c.png)

### Motivation

I would love to be able to have my device use its internal sound chip to the best of it's full capability as well as when I connect it to a DAC that I paid money for. I've tried using Poweramp Equalizer, but you cannot change the sample rate through that app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
