### ISSUE TITLE
"Enable save playback speed" not working properly

### ISSUE THREAD

**Issue by towfikomar** [inotia00/ReVanced_Extended#1420]
### Type

Other

### Tools used

Revancify

### Application

Youtube v18.31.40

### Bug description

This option is not working if play a video and change the playback speed(suppose 1.5x) after that i play another video from recommendation panal of that video. Here 1.5x doesn't go back no normal.

But if i completely close a video after changing playback speed and play a video from Home page there is no problem.

revanced-patches-2.190.12
v18.31.40 
Tried spoof version doesn't fix.

### Steps to reproduce

1. Turn off Enable save playback speed & restart.
2. Play a video and change playback speed
3. Play another video from recommendation planal ( check SS)
![IMG_20230926_093510](https://github.com/inotia00/ReVanced_Extended/assets/114739840/73a7c4c4-be02-49ab-ab17-ee7fa6b1c949)

### Relevant log output

```shell
I don't know about that. Sorry
```

### Screenshots or videos

![IMG_20230926_093510](https://github.com/inotia00/ReVanced_Extended/assets/114739840/63791111-debf-4289-a343-0c7f36939940)
Video: https://drive.google.com/file/d/1KdOyKdY6ogbjLcpO1xlDLBxqaGVYqwyW/view?usp=drivesdk

### Device Environment

RMX2195, Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
'Enable save playback speed' is a feature that saves the playback speed as the default playback speed whenever the user changes the playback speed

That is, if 'Enable save playback speed' is off, only features that save playback speed will be turned off, but when the video starts, the default playback speed will be used

![description](https://github.com/inotia00/ReVanced_Extended/assets/108592928/a251862c-8832-4cbd-8a20-8514455106a5)

If you turn off the red arrow, the blue arrow value will be applied
