### ISSUE TITLE
question(YouTube/YT Music/Account menu):  

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1421]
### Application

YouTube

### Description

First see how looks account menu in YT/YTM on phones
1.YT
![IMG_20230926_164717_752](https://github.com/inotia00/ReVanced_Extended/assets/110785596/3fdb46cf-16ff-489b-99a4-a440037247b4)
2.YTM
![IMG_20230926_164717_701](https://github.com/inotia00/ReVanced_Extended/assets/110785596/6d86584e-37c8-496d-8144-f969dadfb6a1)

Now see how account menu looks on tablets
1.YT
![Screenshot_20230926_164529_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/f9eee4ac-0c50-49a9-8a63-fa21a5add298)
2.YTM
![Screenshot_20230926_164514_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/a4b823e3-b3c8-459f-8d6a-5c3b4b467dcc)

On tablet we cant use YT account menu filter, but in YTM we can.
I think this is weird because of very similar account menu structure on tablets
Why in YTM we can use account menu related things, but cant on tablets?

Account menu filter works
Phones
- [X] YT
- [X] YTM

Tablets:
- [ ] YT
- [X] YTM

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's simple
Compared to YouTube, YT Music has a much simpler structure.

Therefore, there is less chance of errors occurring and more customization is possible than on YouTube.

In the case of YouTube, a force close occurs if a server-side change is added when the same patch is applied.

So for YouTube, I designed the patch to force disabling when a fatal exception is detected.

**Comment by girshcatt** [comment]
I think that after i reproduced how this happens we can call this not like: it cannot work on tablets
we can call it just tablet side effect, maybe you can change revanced_hide_account_menu_summary string from this: Known issue: May not work in landscape mode or on high dpi devices
to this: Known issue: in landscape mode or on high dpi devices you need to hide enough components so that all the remaining ones fit on the screen

**Comment by inotia00** [comment]
If you try to force it to be hidden the traditional way, you will run into this issue: https://github.com/inotia00/ReVanced_Extended/issues/549#issuecomment-1627848602

Therefore, if a situation where a crash occurs, I changed it to not hide it

So it may not work on tablets
