### ISSUE TITLE
feat(YouTube/Hide account menu components): add 'Hide terms container' option

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1422]
### Application

YouTube

### Issue

Sorry for a little function request in YT, but this just needed function that relate to account menu that need to be added. If u dont want to add it on 1000000% just close the issue, i wont be sad:)
Can you add 'Hide terms container' option to YT, terms container cant be hidden by filter. Maybe it can remind you how you added 'Hide terms container' to YTM by the same reason.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
For YouTube, there are no plans to add any more new patches

**Comment by Aryan-Chauhan** [comment]
I hope this feature of RVX Music, comes to RVX one day.
