### ISSUE TITLE
bug(YouTube/Hide account menu filter): cant hide some components in some languages

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1423]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.31.40

### Bug description

Account menu filter supposed to hide almost components except 'Terms container' and 'Manage your Google Account'. And in English filter do all his work properly, but in Russian (surely i dont know how in other languages, but any other languages can be affected by this problem) many components cant be hidden:
Get YouTube Premium
YouTube Studio
YouTube Music
YouTube Kids

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
![accountfilter](https://github.com/inotia00/ReVanced_Extended/assets/108592928/5334f1cb-bd69-4849-8c35-8ceca9b8b003)
![result2](https://github.com/inotia00/ReVanced_Extended/assets/108592928/54775f07-7064-416a-a890-608695469234)

It seems to be working well

I'm leaving the filters I used so you can copy and paste just in case.

```
Творческая студия YouTube
YouTube Music
YouTube Детям
```

**Comment by girshcatt** [comment]
Thanks, sorry if wasted your time, i typed similar on 100% before and it wasnt work, with your copy pasted filter all work

**Comment by inotia00** [comment]
nah... it's okay
Even if there is only a slight typo, the filter will not work

If anyone asks about this on 4pda, please attach this link
