### ISSUE TITLE
suggestion(YouTube/YouTube Music/Hide account menu): add warning if user trying to hide `Settings` container

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1424]
### Application

YouTube, YouTube Music

### Description

Add warning if user trying to hide `Settings` container, this is useful to prevent people from extra confuse

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
refelcted in [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1)
