### ISSUE TITLE
bug(YouTube/SponsorBlock): 2.190.4+ unknown strings in import/export menu; thicker import/export menu in tablets

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1425]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.31.40

### Bug description

in 2.190.4+ patches after you did changes to sponsorblock integration two weird things appeared.
1.In import/export menu appeared 3 new strings, maybe more, I could have missed it:
sb_settings_copy; sb_settings_import_successful; sb_settings_import_failed
![20230926_204156](https://github.com/inotia00/ReVanced_Extended/assets/110785596/d239be5d-2e90-4493-aa53-cc5916027863)
![20230926_204217](https://github.com/inotia00/ReVanced_Extended/assets/110785596/2c63f82b-1ec7-44f3-ac23-cdce2efcc830)
![20230926_204239](https://github.com/inotia00/ReVanced_Extended/assets/110785596/16a4073c-a598-479b-8c99-886ac21e9e60)
2.On tablets SB import/export menu now looks much thicker
1)2.190.1
![Screenshot_20230926_202612_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/4c46e45a-51ce-41e2-aed0-d1f71cb57115)
2)and now in 2.190.4+
![20230926_203044](https://github.com/inotia00/ReVanced_Extended/assets/110785596/004f13bc-04e6-453a-8c80-f9731233ea3a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.15)
