### ISSUE TITLE
Copy SponsorBlock settings button is difficult to find in some scenarios 

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1426]
### Type

Cosmetic

### Tools used

Revancify

### Application

18.31.40

### Bug description

When there are many custom SponsorBlock settings, the text box will fill up most of the screen and only leave a small area on the bottom for the 'OK', 'Cancel', and 'SB_SETTINGS_COPY' buttons which you need to scroll through. This essentially hides the 'SB_SETTINGS_COPY' button.

The same thing happens when the screen is in landscape mode, but I don't expect this to be an issue for anyone.

### Steps to reproduce

1. Customize the SponsorBlock settings sl that the settings json text is large. Here are my settings

```{
  "isVip": false,
  "serverAddress": "https:\/\/sponsor.ajay.app",
  "dontShowNotice": true,
  "showTimeWithSkips": false,
  "minDuration": 0,
  "trackViewCount": true,
  "skipCount": 21,
  "minutesSaved": 7.474816799163818,
  "categorySelections": [
    {
      "name": "sponsor",
      "option": 3
    },
    {
      "name": "selfpromo",
      "option": 3
    },
    {
      "name": "interaction",
      "option": 3
    },
    {
      "name": "poi_highlight",
      "option": 0
    },
    {
      "name": "intro",
      "option": 3
    },
    {
      "name": "outro",
      "option": 1
    },
    {
      "name": "preview",
      "option": 1
    },
    {
      "name": "music_offtopic",
      "option": 1
    }
  ],
  "barTypes": {
    "sponsor": {
      "color": "#EBC968"
    },
    "selfpromo": {
      "color": "#EBC968"
    },
    "interaction": {
      "color": "#EBC968"
    },
    "poi_highlight": {
      "color": "#CF5FA4"
    },
    "intro": {
      "color": "#D54239"
    },
    "outro": {
      "color": "#D54239"
    },
    "preview": {
      "color": "#D54239"
    },
    "filler": {
      "color": "#7300FF"
    },
    "music_offtopic": {
      "color": "#FF9900"
    }
  }
}
```
2. Try exporting the settings by using the 'SB_SETTINGS_COPY' button

### Relevant log output

```shell
NA
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/84587632/9588b2db-202b-45c4-b2d5-224b9cc91623

### Solution

Change the orientation of the buttons to be a static horizontal bar at the bottom of the screen, which the text box wont overlap onto.

### Device Environment

Samsung S22+
Android 13
One UI 5.1
Non-root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
duplicate with https://github.com/inotia00/ReVanced_Extended/issues/1425
