### ISSUE TITLE
No prompt to restart app when importing YTM settings in some cases

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1427]
### Type

Cosmetic

### Tools used

Revancify

### Application

YTM 6.20.51

### Bug description

When importing settings into YTM, the changes don't take effect until the app is restarted. This is true for all toggles. 

The issue is that when importing settings for a toggle that normally doesn't need an app restart (such as the 'Hide Radio Button' in the Action Bar settings), there will not be a prompt to restart the app, even though a restart is needed to apply the changes.

### Steps to reproduce

1. Clear the data of YTM Extended to have a clean slate
2. Change a toggle that doesn't need an app restart to be applied (such as Action Bar > Hide Radio Button, On)
3. Go to the Export /Import settings and delete the text related to the toggle you just changed, and press 'Import' (no restart prompt will appear)
4. Go check the status of the toggle you changed in step 2. You will see that the toggle is in the position that you left it in (aka removing it from the Export /Import settings did not affect anything because the app wasn't restarted)

### Relevant log output

```shell
NA
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/84587632/a57486cb-8b16-4617-86e4-ae255c3e1382

### Solution

Always prompt the user to restart the app when importing settings or apply the changes immediately  for options that can be applied without a restart.

### Device Environment

Samsung S22+
Android 13
One ui 5.1
Non root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Unlike YT's settings, YT Music's settings have very limited source code customization.

Unlike YouTube, no code has been implemented to control whether or not the Preference switch is checked at the source code level.

Therefore, I think this issue will be impossible to fix.

But I'll leave a comment for others and still keep the issue open.

**Comment by inotia00** [comment]
As I mentioned before, due to the structural limitations of YT Music settings, this issue cannot be fixed in an ideal way

Instead, I can solve this issue by showing reboot dialog every time user imports settings

It's not the ideal way, but I think it's one of the ways to fix this issue

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.15)
