### ISSUE TITLE
(youtube) Return YouTube Dislike settings aren't included in settings export/imports

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1428]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube 18.31.40
Patches 2.190.12

### Bug description

I am not sure if this is intended, and I am aware this is an experimental flag. Im not %100 sure what your policy is on this but feel free to just close.

When exporting and importing settings from/to YouTube, the RYD settings are not included.

### Steps to reproduce

(Optional) 1. Clear the app data of YT RVX to have a clean slate
2. Export the settings to a json
3. Change some of the RYD settings 
4. Import the settings json from step 2 and restart the app
5. Check the RYD settings. They will still be how you set them in step 3 (instead of how they were at the time step 2 was completed)

### Relevant log output

```shell
NA
```

### Device Environment

Samsung s22
Android 13
Non-root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
If all experimental flag bugs shouldn't be reported, you can add an Acknowledgement for it in the bug submission form

**Comment by inotia00** [comment]
I've left comments before, but they are designed to only import/export items that exist in ReVanced Settings
(i.e. RYD, SponsorBlock settings are not included)
