### ISSUE TITLE
bug: ReVanced Extended setting page blank 

### ISSUE THREAD

**Issue by KPVADALIYA** [inotia00/ReVanced_Extended#143]
### Type

Other

### Application

ReVanced Extended v18.01.35

### Bug description

When opening ReVanced Extended setting showing blank page

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

https://user-images.githubusercontent.com/103434326/211974412-ef1f6303-e8f5-466e-a1c5-a23cd9b9be86.mp4

### Device Environment

Mi 11 lite ne 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
update

**Comment by KPVADALIYA** [comment]
A install from below link 2 time

 https://revanced.io/#download-apk

**Comment by KPVADALIYA** [comment]
I just downloaded new apk after 5 minutes setting page gone blank

**Comment by inotia00** [comment]
If you haven't patched according to the [documentations](https://github.com/inotia00/revanced-documentation/wiki) I provide, I can't help

**Comment by inotia00** [comment]
And.. revanced.io is illegal
I can't offer any more help
