### ISSUE TITLE
bug: <title> Screen gets locked automatically whenever I am trying to play a video 

### ISSUE THREAD

**Issue by SultanulKabir** [inotia00/ReVanced_Extended#1432]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

youtube-revanced-magisk-v18.32.39 
youtube-revanced-extended-v18.31.40
youtube-revanced-v18.32.39-all.apk

### Bug description

Whenever I play a video my screen gets locked automatically. If I unlock Then it becomes locked again unless I pause the video from lock screen.
It happens in background play too. 

### Steps to reproduce

N/A

### Relevant log output

```shell
https://bin.kv2.dev/~651648425de7ed6bfdb96f00
```

### Screenshots or videos

https://drive.google.com/file/d/1ujcABbNwFrj1W0JxcaUiwE9W1nYg4Nxo/view?usp=drivesdk

### Device Environment

Android 11.. Havoc official Rom v4. 19.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
> youtube-revanced-magisk-v18.32.39
> youtube-revanced-extended-v18.31.40
> youtube-revanced-v18.32.39-all.apk

This repo is only for revanced extended. Did you patch the YT ReVanced Extended apk yourself?

**Comment by inotia00** [comment]
wrong place to report issue
