### ISSUE TITLE
bug : Video paused after some time in Preview

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1433]
### Type

Other

### Tools used

rvx-builder

### Application

YT Supported version by rvx

### Bug description

Video playback in preview is paused after some time like 40 sec or 50 sec. I've tried both with spoofing  or w/o spoofing.

### Steps to reproduce

... 

### Relevant log output

```shell
...
```

### Device Environment

10

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1313#issuecomment-1722490956
