### ISSUE TITLE
bug: missing patches

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1434]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.32.39
Revancify

### Bug description

I saw that the extra features of ReX have been added
But I don't know if it is just me who can't find these features or they are just missing:

**1. Higher fullscreen seekbar height**
![Screenshot_20230929_194601_ReVanced Manager](https://github.com/inotia00/ReVanced_Extended/assets/130296934/4e2d210d-8745-4b6d-990c-54a88ee6866b)

**2. Whitelist options**
![Screenshot_20230929_200143_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/130296934/2a4363ae-1935-4894-9ba4-850c235f1de4)

### Steps to reproduce

NA

### Relevant log output

```shell
NA
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`Higher fullscreen seekbar`
: this patch does not exist in PR

`Whitelist`
: this patch was not merged because the code is too close to spaghetti code and requires overall refactoring
