### ISSUE TITLE
bug(YouTube/Overlay buttons): Overlay buttons are not hidden when swiping the seekbar with new thumbnail preview enabled

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1438]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.32.39
ReVanced Patches v2.190.15

### Bug description

![259389199-45931120-ad9d-4e44-865b-4f3425b77486](https://github.com/inotia00/ReVanced_Extended/assets/127908708/96d02789-c65f-4716-80de-f6e1936c9aca)
This bug is similar to https://github.com/inotia00/ReVanced_Extended/issues/504.

Additional info:
https://github.com/inotia00/ReVanced_Extended/issues/631

### Steps to reproduce

Swipe the seek bar of any video with new thumbnail preview enabled.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/1450

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.21](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.21)
