### ISSUE TITLE
bug: Little problem with Sleep Timer.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1439]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

YouTube Music v6.21.51
inotia00 patches v2.190.15

### Bug description

I did not select "Enable Sleep Timer" while patching but still I'm getting this Sleep Timer option in my flyout menu. Also, there is no option to hide it. So, please fix this when you get time.
![Screenshot_2023-09-30-08-29-24-05_0ee52a21b47f2484ca705d66bfb85bda](https://github.com/inotia00/ReVanced_Extended/assets/91815107/c5c07605-7571-45c0-a2b2-3ea1d35a860f)

### Steps to reproduce

Step 1. Exclude "Enable Sleep Timer" while patching.
Step 2. Play any song and check the flyout menu.

### Relevant log output

```shell
No logs.
```

### Device Environment

Realme 7 Pro, Android 12.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
The `sleep timer` menu is a server-side dependent function (A/B tests)

This means that if this test was applied to your Google account, it would have been enabled even without the patch.

So this is normal

If you want to force it to be hidden, include the `Enable sleep timer` patch and change it to off in the settings.

Just think of it as working similarly to the `Enable new splash animation` patch that exists on YouTube.

**Comment by Aryan-Chauhan** [comment]
LOL, why didn't I think of this earlier?

I already use the splash animation trick on YT.

Thanks, inotia.
