### ISSUE TITLE
bug: ReVanced Extended search history 

### ISSUE THREAD

**Issue by KPVADALIYA** [inotia00/ReVanced_Extended#144]
### Type

Other

### Application

ReVanced Extended v18.01.36

### Bug description

ReVanced Extended search history not showing 

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_2023-01-12-10-43-21-515_app rvx android youtube](https://user-images.githubusercontent.com/103434326/211982840-ac0c0549-7eab-4755-be34-95a4d7a58267.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
same. update

**Comment by sgnlnkt** [comment]
Having the same issue (April 15/23). Am signed out btw. Old vanced doesn't have this issue.
![Screenshot_20230416-171622_ReVanced Extended](https://user-images.githubusercontent.com/130892252/232279870-222f5c72-2dee-4d8a-805b-2051c81ea7b9.jpg)
