### ISSUE TITLE
bug: This setting is not importing from the .json file.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1440]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.32.39 (recommended).
inotia00 patches v2.190.15

### Bug description

I always enable "Hook Download Button", then I export all the settings to .json file.
Then, I clear ALL data of RVX.
Then, I open RVX and import settings from .json file.
All settings gets perfectly imported, except the Hook Download Button one.
So, please fix this in your free time.
![Screenshot_2023-09-30-08-55-57-26_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/inotia00/ReVanced_Extended/assets/91815107/be5d6f99-d1a7-4030-896e-a08e7e3caa83)

### Steps to reproduce

Described above.

### Relevant log output

```shell
No logs.
```

### Screenshots or videos

Given above.

### Solution

inotia00 will do, LOL.

### Additional context

Everything written above.

### Device Environment

Realme 7 Pro, Android 12.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
I know that this setting not exported, because in supported versions exist versions 18.22.37 and 18.23.36 that lower than 18.24.37 that reqired to make hook download button work. Inotia did this just to make compatible settings from 18.24.37+ to older versions and this is right decision until he will drop support for versions lower that 18.24.37
If i closed all your questions please close the issue

**Comment by inotia00** [comment]
This setting is an option that can only be used after going through the process of checking whether the app you are currently using is a version that can use the hook external downloader

For this reason this setting is not imported

**Comment by KobeW50** [comment]
> This setting is an option that can only be used after going through the process of checking whether the app you are currently using is a version that can use the hook external downloader
> 
> For this reason this setting is not imported

Do you intend on adding it in the future when all versions supported by your patches are newer than 18.24.37?

**Comment by inotia00** [comment]
yeah If the minimum supported version of the patch is v18.24.xx+, this setting will be imported without any issue
