### ISSUE TITLE
bug: Leaving `Edit spoof app version` empty gives error

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1441]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.32.39
ReVanced Patches v2.190.15

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/946e13ef-bd89-4a15-9e58-ff08f5c5e67a

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Solution

Prevent accepting empty field.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This setting is Experimental Flags

This means that this option is only available for those who know how to handle these settings

I assume that only people who know how to handle settings will input valid syntax, so I don't handle exceptions
