### ISSUE TITLE
Not Able to search for YouTube shorts

### ISSUE THREAD

**Issue by QuasarQuipper** [inotia00/ReVanced_Extended#1442]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

v18.32.39

### Bug description

I recently updated YouTube with revanced patches v2.190.15,
After which I am unable to sort for shorts of the topic I searched for (case 1 in the above video).

Earlier while using revanced patches v2.190.12
I was able to search for a topic and sort the shorts related to that topic (case 2 in the above video).

In both the cases hide_shorts_shelf toggle is enabled.
Disabling this toggle allows me to search for shorts but on the other hand I see shorts shelf on my homepage and subscription page.

What I want is that I'm able to search for shorts on the other hand there is no shorts shelf on my homepage and subscription page (as in case of revanced patches v2.190.12).

I need this feature (short searching) with good quality seekbar thumbnails, seekbar overlay (which is available in revanced patches V2.190.15) but is not available with revanced patches v2.190.12

Request u/inotia00 to resolve this issue.

### Steps to reproduce

I recently updated YouTube with revanced patches v2.190.15,
After which I am unable to sort for shorts of the topic I searched for (case 1 in the above video).

Earlier while using revanced patches v2.190.12
I was able to search for a topic and sort the shorts related to that topic (case 2 in the above video).

In both the cases hide_shorts_shelf toggle is enabled.
Disabling this toggle allows me to search for shorts but on the other hand I see shorts shelf on my homepage and subscription page.

Request u/inotia00 to resolve this issue.

### Relevant log output

```shell
Unknown
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/146509963/ded00769-a7d5-46f9-beeb-bbb12bbeeefd

### Device Environment

Android 13, one UI 5.1, S22 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Currently, `Hide shorts shelf` hides all shorts video from search results

Just turn off `Hide shorts shelf`

**Comment by QuasarQuipper** [comment]
Disabling Hide shorts shelf solves the problem but it also adds shorts shelf on homepage and subscription page, which I do not want.

It used to work fine with revanced patches V2.190.12

I think it is due to merging yt advanced/rex patches with rvx patches, earlier i.e. revanced patches v2.190.12 did not have this problem whereas yt
advanced did.

**Comment by QuasarQuipper** [comment]
> Currently, `Hide shorts shelf` hides all shorts video from search results
> 
> Just turn off `Hide shorts shelf`

Disabling Hide shorts shelf solves the problem but it also adds shorts shelf on homepage and subscription page, which I do not want.

It used to work fine with revanced patches V2.190.12

I think it is due to merging yt advanced/rex patches with rvx patches, earlier i.e. revanced patches v2.190.12 did not have this problem whereas yt
advanced did.
