### ISSUE TITLE
bug(YouTube/Overlay buttons): Default downloader list does not load when you first installed app

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1443]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

YouTube 18.22.37 ~ 18.32.39

### Bug description

When you first open "External downloader settings" it shows only "External downloader package name" option. All become normal only after first open "External downloader settings". This is not connected to first app start, you can not open "External downloader settings" after install and restart app 15 times but nothing changed. This is connected only to first open of "External downloader settings".
It reproducable with at least these three patches included:
`microg-support`
`settings`
`overlay-buttons`
I will pin screen recording for the best view

https://github.com/inotia00/ReVanced_Extended/assets/110785596/4b0c2c4c-ea73-4063-93ba-e13147df0ab7

### Steps to reproduce

1.Include `microg-support` patch
2.Include `settings` patch
3.Include `overlay-buttons` patch
4.Patch any of supported YT versions: 18.22.37 ~ 18.32.39
5.Open first time "External downloader settings" and see the bug described in bug description

### Relevant log output

```shell
:/
```
### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/1450

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.4)
