### ISSUE TITLE
bug: filmstrip quality low

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1444]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.32.39
Latest patches

### Bug description

RVX filmstrip quality is very low compared to ReVanced
Maybe they have applied the high quality thumbnails update also for filmstrip
![photo_5819200844200001021_y](https://github.com/inotia00/ReVanced_Extended/assets/130296934/d92d283d-505a-43b9-b2ff-1d583b340d49)
![photo_5819200844200001022_y](https://github.com/inotia00/ReVanced_Extended/assets/130296934/c4bc8e6d-23f2-4051-b5ac-a5ccc956e463)

### Steps to reproduce

n/a

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.18)
