### ISSUE TITLE
bug(YouTube/Import settings): sometimes when you try to import settings app just do nothing and redirect you to main YT settings

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1445]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube 18.22.37 ~ 18.32.39

### Bug description

Sometimes when you try to import settings app just do nothing and redirect you to main YT settings. This bug happens often, but in fact import wont do this second time. I mean if you tried to import settings and just fot redirected to YT settings on second time import will be done successfully. It can be reproduced with at least three patches applied:
`microg-support`
`settings`
`enable-old-quality-layout` (any patch that create setting that can be exported/imported, `enable-old-quality-layout` just as example)

### Steps to reproduce

1.Include `microg-support` patch
2.Include `settings` patch
3.Include `enable-old-quality-layout` patch (any patch that create setting that can be exported/imported, `enable-old-quality-layout` just as example)
4.Export settings and try to import them

### Relevant log output

```shell
:/
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
This bug appears more usual if you will patch with much patches, it easier to reproduce with reccomended included patches

**Comment by inotia00** [comment]
For some reason, the activity used on YouTube is not initialized properly.

This is also why import / export settings are classified as `Experimental Flags`

Similar issues have been registered before, so refer to the following issues https://github.com/inotia00/ReVanced_Extended/issues/1119#issuecomment-1635575206

**Comment by girshcatt** [comment]
Maybe this can be fixed just by import/export settings as a text instead of file? In ReVanced itnot cause any problem. I dont see reason to keep import/export settings through json file

**Comment by inotia00** [comment]
Yeah the issue occurs because RVX tries to export it as a json file

If RVX imports/exports as strings, no issues will occur

**Comment by girshcatt** [comment]
And why you keeping it as file method? Maybe some interesting reason.. If there is no reason i think you can do this option as text and get no bugs

**Comment by inotia00** [comment]
The reason is simple, I don't have time to implement it

**Comment by inotia00** [comment]
To restore `Press-to-swipe`, I rolled back the integration dependencies from a year ago and rebased the entire integrations code https://github.com/inotia00/ReVanced_Extended/issues/517#issuecomment-1829204755

This was quite an arduous task, and during this process I was also able to add the `Import / Export settings as text` that I promised in the past https://github.com/inotia00/ReVanced_Extended/issues/1119#issuecomment-1635579832
