### ISSUE TITLE
Currently, `Hide shorts shelf` hides all shorts video from search results

### ISSUE THREAD

**Issue by QuasarQuipper** [inotia00/ReVanced_Extended#1446]
Currently, `Hide shorts shelf` hides all shorts video from search results

Just turn off `Hide shorts shelf`

_Originally posted by @inotia00 in https://github.com/inotia00/ReVanced_Extended/issues/1442#issuecomment-1741686510_
            
Disabling Hide shorts shelf solves the problem but it also adds shorts shelf on homepage and subscription page, which I do not want.

It used to work fine with revanced patches V2.190.12

I think it is due to merging yt advanced/rex patches with rvx patches, earlier i.e. revanced patches v2.190.12 did not have this problem whereas yt
advanced did.

![Screenshot_20230930_174811_YouTube](https://user-images.githubusercontent.com/146509963/271772405-302ec8a0-0130-44e4-bed7-b5abd445826e.jpg)
![Screenshot_20230930_174720_YouTube](https://user-images.githubusercontent.com/146509963/271772408-b870c126-6ded-4ed5-ae94-9fa5b29a8bb9.jpg)

YouTube patched with revanced patches v2.190.12 did not have this issue, even with hide shorts shelf toggle turned on, I was able to search for shorts.

https://github.com/inotia00/ReVanced_Extended/assets/146509963/bf0235f8-2d14-4b48-8fe4-6823bcd3f42c

> Yes, but all works as expected, hide short shelve remove all shelves (from search too), this change came from ReX, check this ReX patches release changelog https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.187.2, [ReVanced/revanced-integrations#453](https://github.com/ReVanced/revanced-integrations/pull/453)

So can you publish a separate version of patches which excludes ReVanced/revanced-integrations#453 and has new patches from revanced patches v2.190.15 which support good quality seekbar thumbnails, seekbar overlay.
It would be very grateful of you to do so, since I need to search for shorts from time to time but do not want the shorts feed on my homepage and subscription page.
 or 
YOU CAN PUBLISH NEW PATCHES NOW ONWARDS WHICH EXCLUDES https://github.com/ReVanced/revanced-integrations/pull/453 AND FOR THOSE WHO WANT THAT FEATURE CREATE A CUSTOM FILTER FOR THEM.

**Comment by girshcatt** [comment]
Yes, but all works as expected, hide short shelve remove all shelves (from search too), this change came from ReX, check this ReX patches release changelog https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.187.2, https://github.com/ReVanced/revanced-integrations/pull/453

**Comment by QuasarQuipper** [comment]
> Yes, but all works as expected, hide short shelve remove all shelves (from search too), this change came from ReX, check this ReX patches release changelog https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.187.2, [ReVanced/revanced-integrations#453](https://github.com/ReVanced/revanced-integrations/pull/453)

So can you publish a separate version of patches which excludes ReVanced/revanced-integrations#453 and has new patches from revanced patches v2.190.15 which support good quality seekbar thumbnails, seekbar overlay.
It would be very grateful of you to do so, since I need to search for shorts from time to time but do not want the shorts feed on my homepage and subscription page.

**Comment by inotia00** [comment]
Open a PR if you want

**Comment by QuasarQuipper** [comment]
> Open a PR if you want

Sorry I'm quite new, what is a PR

**Comment by QuasarQuipper** [comment]
> ```
>           Currently, `Hide shorts shelf` hides all shorts video from search results
> ```
> 
> Just turn off `Hide shorts shelf`
> 
> _Originally posted by @inotia00 in [#1442 (comment)](https://github.com/inotia00/ReVanced_Extended/issues/1442#issuecomment-1741686510)_
> 
> Disabling Hide shorts shelf solves the problem but it also adds shorts shelf on homepage and subscription page, which I do not want.
> 
> It used to work fine with revanced patches V2.190.12
> 
> I think it is due to merging yt advanced/rex patches with rvx patches, earlier i.e. revanced patches v2.190.12 did not have this problem whereas yt advanced did.
> 
> ![Screenshot_20230930_174811_YouTube](https://user-images.githubusercontent.com/146509963/271772405-302ec8a0-0130-44e4-bed7-b5abd445826e.jpg) ![Screenshot_20230930_174720_YouTube](https://user-images.githubusercontent.com/146509963/271772408-b870c126-6ded-4ed5-ae94-9fa5b29a8bb9.jpg)
> 
> YouTube patched with revanced patches v2.190.12 did not have this issue, even with hide shorts shelf toggle turned on, I was able to search for shorts.
> 
>  Screen_Recording_20230930_175315_YouTube.mp4 
> > Yes, but all works as expected, hide short shelve remove all shelves (from search too), this change came from ReX, check this ReX patches release changelog https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.187.2, [ReVanced/revanced-integrations#453](https://github.com/ReVanced/revanced-integrations/pull/453)
> 
> So can you publish a separate version of patches which excludes [ReVanced/revanced-integrations#453](https://github.com/ReVanced/revanced-integrations/pull/453) and has new patches from revanced patches v2.190.15 which support good quality seekbar thumbnails, seekbar overlay. It would be very grateful of you to do so, since I need to search for shorts from time to time but do not want the shorts feed on my homepage and subscription page. or YOU CAN PUBLISH NEW PATCHES NOW ONWARDS WHICH EXCLUDES [ReVanced/revanced-integrations#453](https://github.com/ReVanced/revanced-integrations/pull/453) AND FOR THOSE WHO WANT THAT FEATURE CREATE A CUSTOM FILTER FOR THEM.

@girshcatt 
@Spacellary 
Can you please help me with this?
