### ISSUE TITLE
bug(rvx-builder): starting from 2.190.15 rvx builder not show the `microg-support` patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1447]
### Type

Other

### Tools used

rvx-builder

### Application

YouTube 18.22.37 ~ 18.32.39
YT Music 6.15.52 ~ 6.21.51

### Bug description

Starting from 2.190.15 rvx builder not show the `microg-support` patch for YT, YTM, but when you look to log microg patch applied automatically

https://github.com/inotia00/ReVanced_Extended/assets/110785596/3379f97a-85c5-4104-b80d-4d3b676f9767

https://github.com/inotia00/ReVanced_Extended/assets/110785596/4c6423d0-7c21-4c8c-bb9b-0140dd494f07

**Comment by inotia00** [comment]
When you run rvx-builder for the first time, check whether it can request root permission.

If root permission cannot be requested, the environment is set to non-root.

In this case, the `MicroG support` patch will not appear in the list.

This is intended behavior
