### ISSUE TITLE
bug: Thumbnails from previous video appear in autoplay videos in feeds

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1449]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.32.39
ReVanced Patches v2.190.15

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/3627de29-2586-4572-849c-b4174543906f

### Steps to reproduce

1. Enable `Playback in feeds`
2. Enable `Spoof player parameter` and restart
3. Follow the video above

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.18)
