### ISSUE TITLE
bug: hide fs button containter option still shown in tablet ui even tho it should not

### ISSUE THREAD

**Issue by HoriKyoukosimp** [inotia00/ReVanced_Extended#145]
### Type

Revanced settings error

### Application

Youtube

### Bug description

Title says it all

### Steps to reproduce

*enable tablet ui*

Settings -> revanced settings -> layout settings -> wolla

### Relevant log output

```shell
Unneeded
```

### Device Environment

Goofy ahh miui 13.0.7 android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a bug in stock YouTube, not ReVanced or ReVanced Extended bug

This can be reproduced by following the method:
1. Install stock YouTube v18.04.35 on your device
2. Clear app data
3. Launch YouTube and play the video without logging in to your Google account
4. Enter fullscreen
5. button container is not shown

**Comment by HoriKyoukosimp** [comment]
![Screenshot_2023-02-02-10-20-09-002_yuri.sh.png](https://user-images.githubusercontent.com/36318840/216223405-0b5194da-48cc-4679-a1e6-268b80118c9e.png)

I mean this thing

Even you're in tablet mode, hide full screen option still shown which shouldn't

**Comment by inotia00** [comment]
oh i misunderstood

it is not a bug
code linking those settings was too meshy so I just removed it.
