### ISSUE TITLE
bug: Hide Suggestion Shelf is not working properly

### ISSUE THREAD

**Issue by sams452m** [inotia00/ReVanced_Extended#1452]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.32.39

### Bug description

Hide suggestion shelf is not working properly in latest rvx patches there is some space remain there at the place of suggestion shelf

### Steps to reproduce

include hide-suggestions-shelf

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![IMG_20231001_064608_630](https://github.com/inotia00/ReVanced_Extended/assets/143210060/d6cfaa8a-5d9f-47bb-a0ce-9179d8c45730)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
I think that this is normal and expected thing that cant be removed. Like when you hide buttons in action label they remain space between. If i said incorrect inotia please correct me
