### ISSUE TITLE
> Open a PR if you want

### ISSUE THREAD

**Issue by QuasarQuipper** [inotia00/ReVanced_Extended#1453]
> Open a PR if you want

Sorry I'm quite new, what is a PR, if is a pull request that you mean, I may say I'm not much into coding therefore It is my humble request to you to resolve the this issue.

_Originally posted by @QuasarQuipper in https://github.com/inotia00/ReVanced_Extended/issues/1446#issuecomment-1741789531_

**Comment by inotia00** [comment]
revanced-patches is public, so anyone can change the source code and test it

after completing testing, when you think it is acceptable to reflect this, you leave a request for the source code you changed

This is an example of PR

https://github.com/inotia00/revanced-patches/pull/14
https://github.com/inotia00/revanced-patches/pull/15
https://github.com/inotia00/revanced-patches/pull/19
