### ISSUE TITLE
bug(YouTube/Hide button container): "like" and "dislike" button hide error

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/ReVanced_Extended#1454]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

all version

### Bug description

In 18.32.39 (the previous version was the same), patch 2.190.15 (the previous version was the same) hides only one "Like" button, or hides only one "Dislike" button, resulting in two "Like" and "Dislike" buttons. Everything is hidden.

### Steps to reproduce

like button hidden on
or 
disloke button hodden on

### Relevant log output

```shell
no
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
I don't know which patch you mean
Added more descriptions and screenshots

**Comment by root-kernelhacker** [comment]
youtube 18.32.30 (same  18.31.40)

patch 2.190.15 (same 2.190.12)
intg 0.117.15 (same 0.117.12)

setting - revamced extend - bottom player
- hidden disklike on  or hidden like on selecet one

---- like. disklike all hidden.

**Comment by inotia00** [comment]
ah, you mean the button container (action bar)

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.18)
