### ISSUE TITLE
suggestion: de-si YT sharing urls:

### ISSUE THREAD

**Issue by Cris--** [inotia00/ReVanced_Extended#1455]
### Application

YouTube

### Description

Hi,

this picture describes everything:

![threema-20230930-223917892](https://github.com/inotia00/ReVanced_Extended/assets/7994691/d1029de1-d846-4861-abd1-0c3e1affcadd)

Possible to add de-si YT urls with a future patch?

PS: Privacy first!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I do not accept new feature requests or new feature suggestions
