### ISSUE TITLE
bug: black text color on dark background

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#1456]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

YT Music 6.20.51

### Bug description

Black text color on dark background is very hard to read. Change black text to a light color.

### Steps to reproduce

Look at the screenshots.

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20231001_214332](https://github.com/inotia00/ReVanced_Extended/assets/130248949/448e931e-dff9-40dc-80a7-dca044d38b62)
![Screenshot_20231001_214042](https://github.com/inotia00/ReVanced_Extended/assets/130248949/4379f622-be6a-44f8-9162-b05492b695ef)
![Screenshot_20231001_214006](https://github.com/inotia00/ReVanced_Extended/assets/130248949/4e5f0eca-f3d9-4140-b294-7badf16fdfef)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is an unfixable issue
You will see it as you enter the content
