### ISSUE TITLE
bug: Delayed Implementation of Default Video Quality

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#1457]
### Type

Other

### Tools used

ReVanced Manager

### Application

This is the Youtube and Patch Version that I tried and encountered the bug. 

Youtube v18.19.36 Patch v2.190.12 Non-Root
Youtube v18.22.37 Patch v2.190.15 Non-Root

Patched via RVX Manager

### Bug description

I set the Default Video Quality (Wifi) to low resolution like 144p, 240p, 360p but the First few seconds of the video will be in higher resolution like 720p before it will switch to the set Default Video Quality for Wifi.

I've also encountered it with Default Video Quality on Mobile Data but after 1 video the next videos will start and play following the Default Video Quality. 

### Steps to reproduce

1) Set the Default Video Quality to a low resolution
2) Play a Video and it will start in a higher resolution before automatically switching to the Default Video Quality. 

### Relevant log output

```shell
.
```

### Device Environment

Model: KOB2-L09 (Huawei Matepad T8) 
EMUI Version 10.1.0
Android Version 10

Model: CPH1909 (Oppo a5s)
ColorOS Version 5.2.1
Android Version 8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [ ] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is also reproduced on unpatched YouTube
Looks like Google changed something on the server side

**Comment by Stale-1** [comment]
> This is also reproduced on unpatched YouTube Looks like Google changed something on the server side

The default Quality Preference of Youtube was set to auto that's why it starts at a higher quality. I set it to low and the video now starts at low quality.
