### ISSUE TITLE
bug: bug: ReVanced Extended setting page blank #143

### ISSUE THREAD

**Issue by KPVADALIYA** [inotia00/ReVanced_Extended#146]
### Type

Other

### Application

ReVanced Extended v18.01.35

### Bug description

When opening ReVanced Extended setting showing blank page

I install from below link 2 time

https://revanced.io/#download-apk

I just downloaded new apk after 5 minutes setting page gone blank

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

https://user-images.githubusercontent.com/103434326/212000622-273f627e-e8a1-4c52-b054-bd76181569c8.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/143
