### ISSUE TITLE
suggestion: <title>: Add option to not disable app when removing app from recent

### ISSUE THREAD

**Issue by phoenixnguyen1249** [inotia00/ReVanced_Extended#1462]
### Application

YouTube

### Description

Sometimes when I accidentally delete RVX or RVX music from a recent app (freeing up RAM), that app stops playing music. 
<b><i>I hope that in the next version there will be this option (in RVX and also in RVX Music) so users can want the app to continue playing music or stop when they remove it from recent apps.</b></i> 
Thank you very much for looking at my suggestion.  Love what you're doing ❤️

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Aspect250** [comment]
I don't think this can be done but what ui do you have (Miui, oneui, standard android etc)

**Comment by phoenixnguyen1249** [comment]
> I don't think this can be done but what ui do you have? (Miui, oneui, standard android etc)

I am using Evolution X on Redmi Note 8

**Comment by Aspect250** [comment]
As you can lock apps on the recents screen but I can only verify on oneui 5.1. you can tap on the app icon and select lock this app to lock it and it can't be cleared until you unlock it

But the way to lock and unlock an app can be different depending on your os/ui

**Comment by Aspect250** [comment]
> Redmi Note 8

I have put a search into Google bard and 8t said this


1.Open the Settings app.

2.Go to Security and privacy.

3.Tap Recent apps.

4.Tap the gear icon in the top right corner.

5.Tap Lock apps.

6.Toggle on the switch next to the apps that you want to lock.

Once you have locked an app, you will not be able to close it by swiping it away from the recent app space. To unlock the app, you will need to tap the lock icon next to it in the recent app space.




Hope this helps

**Comment by phoenixnguyen1249** [comment]
> As you can lock apps on the recents screen but I can only verify on oneui 5.1. you can tap on the app icon and select lock this app to lock it and it can't be cleared until you unlock it
> 
> But the way to lock and unlock an app can be different depending on your os/ui

I understand what you mean, but what I mean is, I want even if RVX (or RVX music) is removed from the recent apps section, it will still be able to continue running in the background until the user directly opens the app and turn off the music/videos. You can download an app called Musicolet on the Play Store, try playing a certain song and delete it from the recent apps section, it will continue to play music whether you lock the app or not. I know that this can only be done on the source code of this application so I suggest this feature

**Comment by inotia00** [comment]
Unfortunately, this is an OS-related policy, so it cannot be implemented on the client side
Change your system settings
