### ISSUE TITLE
bug: Clicking YouTube links within the app redirect to browser 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1464]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.33.40

### Bug description

When clicking on YouTube links within the YouTube app, normally you're taken to the video/channel depending on the type of link it is. But currently when clicking on such links redirects the user to open a browser window or if the user has open in external browser patch selected, opens in an external browser.

Repeated the above steps in stock YouTube app and it works fine.

### Steps to reproduce

1) Play any video which has an YouTube link in description.
2) Click on the link and notice how RVX YT redirects to a browser window.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

In RVX YT:

https://github.com/inotia00/ReVanced_Extended/assets/117499019/c6ee90c0-5292-4682-90e7-8507477b3121

In Stock YT:

https://github.com/inotia00/ReVanced_Extended/assets/117499019/b60cc5bb-f66f-4db9-8eab-014259401822

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is an issue that cannot be resolved in non-root builds.

When you open a YouTube link in RVX, it opens in stock YouTube (com.google.android.youtube).

Since this is a server-side response, fixing is not possible.

**Comment by ILoveOpenSourceApplications** [comment]
But this issue isn't present in ReVanced YouTube either.

**Comment by ILoveOpenSourceApplications** [comment]
And if I remember correctly it used to work fine in RVX also. Recently did it change to the issue reported form.

**Comment by inotia00** [comment]
Test it on YouTube v18.31.40 or v18.32.39

**Comment by ILoveOpenSourceApplications** [comment]
Stock or RVX?

**Comment by inotia00** [comment]
yep

**Comment by ILoveOpenSourceApplications** [comment]
Yeah, looks like setting RVX YT as the default to open links fixed it. Is there a way to automatically have this enabled because it's kinda annoying considering that RVX recommends it's users to do a clean install at times and that the user has a tendency to forget to apply this setting.

**Comment by inotia00** [comment]
Since Google changed the default app policy in Android 12+, it is nearly impossible to automatically apply it

The easiest solution is to simply use RVX in the root environment, since the link will receive a server-side response to open the `com.google.android.youtube` package as a priority

If you are using Android 12+ and a non-root environment, there is no valid easy way

**Comment by inotia00** [comment]
Not possible on Android 12+not possible in Android 12+ since Google changed Android's policy

**Comment by ILoveOpenSourceApplications** [comment]
Isn't it similar to what the manager does when asking permissions to storage? Can't something similar be done?

**Comment by inotia00** [comment]
Additionally, I no longer accept new feature requests or suggestions for YouTube

Exceptionally, if a PR is opened, it is merged

**Comment by inotia00** [comment]
Manager is open source
since all source code is open and customizable, it is also possible to build with legacy code

but YouTube doesn't
all code is close source, so customization is very limited
customization is only possible in a very small portion of the areas that can be accessed through reverse engineering

It would be possible to implement it in a client such as NewPipe or LibreTube

**Comment by ILoveOpenSourceApplications** [comment]
Thanks for the explanation as well as the good work. Keep up what you're doing and have a good day as well.
