### ISSUE TITLE
bug: `Hide audio track button` option present without selection 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1465]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.33.40

### Bug description

I haven't selected the patch `Hide Music Button` but still the setting shows up inside player within RVX settings.

### Steps to reproduce

1) Patch YT without selecting `Hide Music Button`.
2) Go into RVX settings and open Player.
3) Notice how `Hide audio track button` option is present.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

Patches selected:
![266063832-89dec45e-e021-4e9f-8d3c-2c256f54597b](https://github.com/inotia00/ReVanced_Extended/assets/117499019/ecd5937a-4860-4a7a-a756-bff631bc9952)

Option present within settings even though not selected:
![266063918-b1c5f678-e908-4613-bf92-f650761c34ad](https://github.com/inotia00/ReVanced_Extended/assets/117499019/572c9aa4-3108-46a0-b498-7cc9527c73b9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`Hide audio track button` is a patch included in `Hide-layout-components`

if you don't want the `Hide audio track button` added, you should exclude `Hide-layout-components` patch

The reason `Hide audio track button` is designated as `Player` category is simply because the audio track button is located inside the player

**Comment by ILoveOpenSourceApplications** [comment]
But isn't the patch `Hide Music Button` for the same purpose? Please correct me if I'm wrong.

**Comment by inotia00** [comment]
I didn't find any issue with the code for `Hide Music Button`

Please attach a screenshot to see if it is excluded in RVX Manager, but added to settings.

**Comment by ILoveOpenSourceApplications** [comment]
No, what I am asking is what does `Hide audio track button` do? Isn't its purpose similar to what `Hide music button` patch which hides the YT Music button on the top right of the player or is it hiding something different?

**Comment by inotia00** [comment]
hides it
![hide-audio-track-button](https://github.com/inotia00/ReVanced_Extended/assets/108592928/af57f89c-b2c8-462b-9665-c43e048e0b46)
