### ISSUE TITLE
bug: not sure if Hide seek message is working

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1466]
### Type

Other

### Tools used

Revancify

### Application

Youtube v18.33.40

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/130296934/72fa1914-e854-4e5a-88a1-c005909b25ff

(Also for some reason it keeps bringing back the pointer of the seekbar at its initial point when swiping forward or backward)

### Steps to reproduce

1. Enable Hide seek message
2. Follow the video

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`Hide seek message` patch only hides the `Slide left or right to seek` message

Hiding this message requires the `Hide seek undo message` patch, but is not currently implemented in rvx patches

**Comment by inotia00** [comment]
I checked and found that `seek undo message` is a feature added to YouTube v18.29.38+

This means that if you try to patch to YouTube v18.27.36 or earlier, you may not use `seek undo message`
