### ISSUE TITLE
bug: settings bug

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1468]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

If by mistake you rotate your screen in the settings, it takes you back at the very beginning which can be really annoying when you are trying to find a feature to enable/disable.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/cca5a9b7-fd21-49dc-a186-063a11b0194f

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Solution

When you rotate the screen, it should leave you exactly where you are.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
I am aware of the issue, but it is currently an issue that cannot be fixed due to limitations in the way RVX implements settings patch
