### ISSUE TITLE
suggestion: Small improvement in "Append video quality".

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1469]
### Application

YouTube

### Description

The maximum resolution of this video is 2160p. So, I'm requesting that it should show "2160p/2160p" or "2160p:2160p" instead of "2160p" only.

Basically, I'm requesting for "Current quality/Max available quality"

Reason: Sometimes, 2160p videos start playing at 1080p or 1440p randomly, even though video quality is set to 2160p. So, to avoid opening flyout menu again and again for confirmation, this can be implemented for user's convenience.

![Screenshot_2023-10-03-08-32-09-33_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/inotia00/ReVanced_Extended/assets/91815107/f414be5d-cb77-4616-baa6-c94a26752b27)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I'm not accepting any suggestions or feature requests for new patches for YouTube
