### ISSUE TITLE
feat(patch): add the disable-fullscreen-panels patch 

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#147]
### Application

YouTube

### Issue

The "disable-fullscreen-panels" patch, which is included and working in stock revanced is missing from revanced extended. 

### Patch

It's already exists, disable-fullscreen-panels in revanced 

### Motivation

Its really convenient, and I really like ReVanced extended, but I really miss this specific feature 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
This feature already exists in RVX. I just wish it would also not show when you tap video title in fullscreen.

**Comment by NBruderman** [comment]
> This feature already exists in RVX. I just wish it would also not show when you tap video title in fullscreen.

No, it's not on RVX, I even confirmed that in the patch list that this patch is missing.

**Comment by anyujinie** [comment]
> > This feature already exists in RVX. I just wish it would also not show when you tap video title in fullscreen.
> 
> No, it's not on RVX, I even confirmed that in the patch list that this patch is missing.
> 

![Screenshot_20230129-125611632 (1).jpg](https://user-images.githubusercontent.com/73917917/215324507-78da95bf-6ea6-488a-af84-576fe3135888.jpg)

I believe its this one you're reffering to? Check the app again and enable it

**Comment by anyujinie** [comment]
EDIT: Ok it seems that you're right. When comments are viewed and you switch into full screen the comments are showing there too.
Also when you tap video title in fullscreen it bring up the description.

Seems like this patch is not working in Rvx.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.159.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.1)
