### ISSUE TITLE
bug: Hook download button is not enabled after importing settings

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1470]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

If Hook download button is enabled and I export the settings, it is not enabled when I import settings after a fresh install.

### Steps to reproduce

Step 1. Enable 'Hook download button'
Step 2. Export settings
Step 3. Clear app data
Step 4. Import settings
Step 5. Check External downloader settings
 Hook download button will be disabled.

### Relevant log output

```shell
_
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1440
