### ISSUE TITLE
bug: Delay in locking Default Video Quality.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1471]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.33.40
RVX patches v2.190.18

### Bug description

My default video quality on WiFi is 2160p, but mostly all videos start playing at 480p, then exactly after the 10 second mark, it switches to 2160p.

In earlier patches, the videos used to start directly at 2160p.

### Steps to reproduce

Too simple.

### Relevant log output

```shell
No logs.
```

### Device Environment

Realme 7 Pro, Android 12.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1457
