### ISSUE TITLE
Loop: Start & End Time Playback

### ISSUE THREAD

**Issue by Loading617** [inotia00/ReVanced_Extended#1472]
### Application

YouTube

### Description

I would like to see a Start to End Time in ReVanced Extended 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
For YouTube I do not accept new patch feature requests or suggestions
