### ISSUE TITLE
feat(Reddit): add `Hide recently visited` patch

### ISSUE THREAD

**Issue by rywz** [inotia00/ReVanced_Extended#1473]
### Application

Reddit

### Issue

Reddit displays ALL of the communities you've recently visited.

### Patch

Hide this from sidebar

![Screenshot_2023-10-03-18-44-08-266_com reddit frontpage-edit](https://github.com/inotia00/ReVanced_Extended/assets/71558811/ff0a95a6-dcc8-40f6-b00a-c18e11047836)

### Motivation

It's irritating to see this, and there's no way to disable it; moreover, it can be _embarrassing_ if someone else sees it.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.4)
