### ISSUE TITLE
Bug: seekbar bugs out video/overlay when swiping up

### ISSUE THREAD

**Issue by Aspect250** [inotia00/ReVanced_Extended#1474]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.33.40
Patch version V2.190.18

### Bug description

Swiping up while seeking in the seekbar removes/glitches out the video overlays and removes most functions like swipe down to downsize the video, etc.

### Steps to reproduce

Step 1: have recommended patches
Step 2: tap and hold the seekbar to seek
Step 3: swipe up while still seeking 

### Relevant log output

```shell
Nil
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/102602600/a607e3bd-b327-4076-a4a3-d2154525ef9a

### Device Environment

Android 13, oneui 5.1, A34

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/1463
