### ISSUE TITLE
bug: like/dislike button in RTL layout (YouTube Music)

### ISSUE THREAD

**Issue by blacktornadog7** [inotia00/ReVanced_Extended#1475]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube Music 6.21.51

### Bug description

In RTL layout the like/dislike button container doesn't show up properly (screenshot below).

### Steps to reproduce

1. change display language of the app (or the phone) to a RTL layout
2. play a song 

### Relevant log output

```shell
No Relevant log output
```

### Screenshots or videos

![Screenshot_20231003_230039_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/74029985/175d66f1-fbb2-4d39-aea2-fdbdfe57ebb8)

### Device Environment

Android 13 (One UI 5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
ah, unlike YouTube, the like and dislike buttons do not change on YT Music even on RTL layout

I'll fix it in the next release

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.24)
