### ISSUE TITLE
suggestion:  Bring back 'save and restore brightness settings' for fullscreen landscape when force closing app and re-opening app

### ISSUE THREAD

**Issue by sliceanddice9** [inotia00/ReVanced_Extended#1476]
### Application

YouTube

### Description

I cannot for the life of me even begin to understand why 'save and restore brightness settings' was removed from ReVanced Extended.

The 'save and restore brightness settings' for fullscreen landscape could always be disabled for people who did not want to use it, so in the latest patches update why remove this feature by default for those of us who did want to use it? 

The 'save and restore brightness settings' for fullscreen landscape via the brightness gensture control which remained saved for ALL videos **even** after force closing the app and re-opening the app, was something that made ReVanced Extended feel like the true successor to the original Vanced because the original Vanced also had this functionality built-in as well. This functionality is something that regular ReVanced cannot do. 

With regular ReVanced if you force close the app and then re-open the app the brightness value you previously set is lost, so as a result the brightness defaults to 0 as soon as you enter fullscreen landscape on the video. This is what now happens with the latest patches update to ReVanced Extended too. 

Please bring this option back. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
The issue was that the option couldn't be disabled. It was also an experimental feature, so it was removed.

Refer to https://github.com/inotia00/ReVanced_Extended/issues/1349 for more details

**Comment by inotia00** [comment]
Just the switch has been removed so it is enabled by default
