### ISSUE TITLE
bug: Overlay buttons don't reappear after swiping seekbar

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1478]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/c8788ea8-bb91-445c-8820-6094b8b2094a

### Steps to reproduce

Have to swipe between the undo seek time frame.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
undo seek message is a fairly recent addition

So this is still an A/B test and has not yet been applied to my account

The undo seek message is a feature added in YouTube v18.29.38+, so you can bypass the issue by applying the patch to v18.27.36 or earlier

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/1450

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1)
