### ISSUE TITLE
bug: Overlay buttons reappear late after swiping seekbar

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1479]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/fcba21f4-4d2a-4de7-9e18-0c3142d1e350

https://github.com/inotia00/ReVanced_Extended/assets/127908708/f6a55965-cf57-40bd-8874-86010a7fa468

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/1450

**Comment by KobeW50** [comment]
@inotia00 

When seekbar tapping is disabled and you tap on the seekbar, the overlay buttons do not appear until the next time the player overlay appears.

https://github.com/inotia00/ReVanced_Extended/assets/84587632/344cbb5a-d40d-41f4-9c6b-f1ad5f53eea6

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1)
