### ISSUE TITLE
feat(patch): Exit by single pressing back (as in the default YouTube)

### ISSUE THREAD

**Issue by jezokshe** [inotia00/ReVanced_Extended#148]
### Type

Cosmetic

### Application

I would like to exit as in the default application, as a last resort, the choice in the settings, if many people need it through a double click. Unless of course it causes problems.

### Bug description

--

### Steps to reproduce

--

### Relevant log output

```shell
--
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by i6jm** [comment]
I agree with you
