### ISSUE TITLE
suggestion: Replace `Hide player overlay filter` with `Player overlay opacity`

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1480]
### Application

YouTube

### Description

Currently the patch only allows to completely disable the overlay, where with videos that have the colour white you can't see at all things like the time stamp or the overlay buttons or icons like captions and settings.
![Screenshot_20231004_063929_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/46170cf4-c884-417a-8db0-d84417b9d310)

On ReVanced instead of the `Hide player overlay filter` patch there is `Player overlay opacity`, which allows to decrease the opacity of the overlay and for example by decreasing it to 15...
![1000034688_3_50](https://github.com/inotia00/ReVanced_Extended/assets/127908708/f4feca46-684d-4124-bd7a-4f88cf450e9c)
...you can fairly see pretty much everything inside the player.
![Screenshot_20231004_063906_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/b9beb09f-7eb0-4657-81d8-9e6cf5d26035)

And if someone wants to completely disable the overlay, they can simply set it to 0 (and to turn it on to 100).

I think the `Player overlay opacity` patch would be much better because it would allow us to set the opacity to our choice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1363

**Comment by Kuddus73** [comment]
Oh duplicate, I wrote that essay for nothing 😆.
But I really do hope he opens a PR.

**Comment by inotia00** [comment]
I think someone will open a PR soon
