### ISSUE TITLE
bug(YouTube): share panel is hidden

### ISSUE THREAD

**Issue by kyoyacchi** [inotia00/ReVanced_Extended#1481]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube RVX (18.33.40)

### Bug description

I can't see share popup in RVX unlike stock YouTube

The video link: https://youtu.be/A9qPj-YJcN8

YT(stock)

### Steps to reproduce

Include all patches.
Try watching https://youtu.be/A9qPj-YJcN8 

### Relevant log output

```shell
N/A
```

### Screenshots or videos

RVX: 
![Screenshot_20231004-161802](https://github.com/inotia00/ReVanced_Extended/assets/63583961/3329fb20-227c-417b-9994-801c1467a171)

YT:
![Screenshot_20231004-161747](https://github.com/inotia00/ReVanced_Extended/assets/63583961/9372556f-14cb-40b5-a15d-d8c3ece1b2be)

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It does not reproduce on my side
Can you test with `Enable custom playback speed` turned off?

**Comment by kyoyacchi** [comment]
> It does not reproduce on my side Can you test with `Enable custom playback speed` turned off?

It's still same

**Comment by inotia00** [comment]
This issue should have been fixed in the latest patch as well
(a separate class is implemented to detect the shared panel)
