### ISSUE TITLE
bug: enable auto-brightness by swiping not working as expected

### ISSUE THREAD

**Issue by ANi1XO** [inotia00/ReVanced_Extended#1483]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v13.33.40

### Bug description

In swipe control menu when I enable brightness sliders and enable auto-brightness by swiping, during playback on full-screen mode when I swipe all the way down auto brightness should be enabled instead of brightness being set to 0 for current session, but with recent patch this function seems to have been broken. If I exit full-screen mode and enter full-screen mode again the brightness gets set to 0, same thing happens when I play another video and go full screen, the brightness automatically lowers to 0 instead of auto.

### Steps to reproduce

>Settings
> revanced extended
> swipe control
> enable auto-brightness by swiping
 >enable brightness gesture
> play a video
> enter full screen
> swipe brightness all the way down to enable auto brightness
> brightness sets to auto as expected
> exit full-screen
> enter full-screen again
> brightness is set to zero automatically while it should be on auto.
>Swipe down again so brightness is set to auto
>exit full-screen
>Enter full-screen again to see brightness go to zero.

### Relevant log output

```shell
N/a
```

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It can be reproduced on my side
In the process of removing legacy code, it seems that code that should not be removed was accidentally removed as well

I will reflect it in the next release

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.24)

**Comment by ANi1XO** [comment]
Awesome!! Thank you
