### ISSUE TITLE
I updated the RVX Manager instructions in the documentation repo wiki

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1485]
Just letting you know that I updated the documentation. The main change was to step 5, which didn't allow for root installs.

You can view all the changes by comparing versions of the page history with eachother.

https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-RVX-Manager-(Android)

Some of the small changes can also be made to some of the other patching tool docs, but its 5am for me.

Close this when you see this

**Comment by inotia00** [comment]
Thank you for your interest
I will edit it further when I have time

**Comment by KobeW50** [comment]
I just realized that the instructions say to install the apk that is downloaded from APKmirror.

This can be an issue for reddit, because the patched apk will have the same package name (and the manager [currently won't even display the error dialog from the Package Manager](https://github.com/ReVanced/revanced-manager/issues/1030) so the user may not even know there is a package conflict)

The user will need to:

1. Realize there is a package conflict
2. Export the patched Reddit apk
3. Uninstall the unpatched reddit apk
4. Install the patched apk.

**Comment by inotia00** [comment]
YouTube and YT Music only require APK installation on your device

Reddit should not be installed on your device because the package name does not change

I will update the documentation later
