### ISSUE TITLE
question(YouTube Music/Enable playback speed): can you hide playback speed everywhere except player flyout?

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1487]
### Application

YouTube Music

### Description

Can you hide playback speed everywhere except player flyout? Because in fact playback speed was only for player flyout menu, but it shown in not only in player, for example you can see it on main page in reccomended tracks flyout, i mean not in player. It causes crash like in screen recording

https://github.com/inotia00/ReVanced_Extended/assets/110785596/0d17734b-24f0-49b5-8fbd-4451675a78dc

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Also when you play a track and change playback speed for example at main page on random track it affects speed in playing track

https://github.com/inotia00/ReVanced_Extended/assets/110785596/fd465325-5c8c-4e8c-9cb4-d0d318a8e5a6

**Comment by inotia00** [comment]
It's theoretically possible, but it's not guaranteed to work perfectly

I can change the playback speed button to not shown in the player flyout panel, at least until the app is first launched and before music is playing

btw this is the same reason why I can't implement the following patch: https://github.com/inotia00/ReVanced_Extended/issues/1346

**Comment by inotia00** [comment]
I tried to implement it but there was no success
I don't think there is a way to implement this at now
