### ISSUE TITLE
bug: Black thumbnails playing recently finished live

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1489]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

With `Spoof player parameter` enabled, at the time of writing this, the affected live started streaming 1 hour ago and ended 9 minutes ago and as you can see its thumbnails appear black.
But old lives are fine.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/f0ab6842-1bc3-44ad-830a-6858ba7632c2

### Steps to reproduce

Explained in description.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
I checked some streamed video and cannot reproduce it. The only problem I met is the thumbnail need about 2-3 seconds for loading

**Comment by inotia00** [comment]
Thanks for the explanation, I understand now

cannot fix this issue due to limitations in the current method

If live stream just ended, just wait a moment and it will resolve itself
