### ISSUE TITLE
bug: some patches are not applyed

### ISSUE THREAD

**Issue by Azazil3203** [inotia00/ReVanced_Extended#149]
### Type

Error at runtime

### Application

17.49 and in later versions. 

### Bug description

17.45 Everything worked fine in the version, but the later versions didn't change while watching the video, even though I made the custom video speed settings. I asked on the Telegram channel. Other people didn't have such a problem or didn't notice it. 

### Steps to reproduce

Step 1) I have enabled custom video speed settings in Settings. I also actively marked the quality settings in the old style. 
Step 2) The application has been restarted. 
Step 3) If I want to change the speed while watching any video, the custom speeds do not appear. Also, if I want to change the video image quality, the quality settings do not appear in the old style. 

### Relevant log output

```shell
I don't know how to get any logs
```

### Device Environment

Android 13 Samsung galaxy s20 fe one ui 5 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Azazil3203** [comment]
I was able to explain so much because I didn't have English. I also wanted to send a screen recording but it didn't work. I'll do my best if you're interested.

**Comment by inotia00** [comment]
Please attach patch informations screenshot

**Comment by Azazil3203** [comment]
![Screenshot_20230115_093312_YouTube](https://user-images.githubusercontent.com/96293520/212526547-b94c66de-ea6a-4a0a-a576-8b6b82292492.jpg)

**Comment by Azazil3203** [comment]
Have you found a solution to my problem? Were you at least able to produce the problem? Because there's no one but me? I guess it's about Samsung phones.

**Comment by TheGoldenSun** [comment]
Azazil, relax, inotia00 is usually busy in reality just have patience.

**Comment by Azazil3203** [comment]
2.156.4 The patch doesn't fix the problems I mentioned. Stay informed.

**Comment by Variables2000** [comment]
2.158.4, does it work?

**Comment by Azazil3203** [comment]
> 2.158.4, does it work?
Yes, my problems have been fixed. Thank you. 
I don't know if it is necessary to open a new topic, so let me write here. When auto-brightness is on, the brightness is 0 when you leave full screen and switch back to full screen. A known issue?

**Comment by ILoveOpenSourceApplications** [comment]
@inotia00 this also is fixed.

**Comment by inotia00** [comment]
thanks
