### ISSUE TITLE
suggestion(YouTube/YT Music/Custom playback speed): correct custom playback speeds warning to do it look properly

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1490]
### Application

YouTube Music

### Description

Correct In YT and YTM custom playback speeds warning to do it look properly, now it looks like this: Custom speeds must be less than %sx, but in fact this is a little bit incorrect, because for exmaple speed can be 3x, but it cant be 3.01x, more properly to say: Custom speeds can't be more than %sx

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.193.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.4)
