### ISSUE TITLE
feat(YouTube Music): add `Disable comments overlay` patch 

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1492]
### Application

YouTube Music

### Issue

Add `Disable comments overlay` patch to remove dark laggy overlay when you open comments

https://github.com/inotia00/ReVanced_Extended/assets/110785596/1d1b4af8-ce56-4cb8-9194-68ebb5eacd9c

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.210.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.210.1)
