### ISSUE TITLE
suggestion: add two missing strings to translate on Crowdin

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1493]
### Application

YouTube

### Description

This issue explains it in detail:
https://github.com/YT-Advanced/YT-Advanced/issues/52

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/218
