### ISSUE TITLE
suggestion(YouTube Music/Replace cast button): add description string to crowdin

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1495]
### Application

YouTube Music

### Description

Add description string to crowdin
![Screenshot_20231006_204239_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/a66337dc-2280-400d-a3b2-33934b976b36)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Since this is a patch in the development stage, it has been designated as a translation exception
