### ISSUE TITLE
suggestion: <title>: Skip dummy segment for shorts

### ISSUE THREAD

**Issue by ANewDawn** [inotia00/ReVanced_Extended#1496]
### Application

YouTube

### Description

Recent skip dummy segment works well for videos. Be nice to have it work for shorts also as they play at low resolution at beginning.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I don't know what issues this might cause

So I designated it as `Experimental Flags`

After sufficient testing, I will introduce it as a general feature.
And I will consider it then.

I cannot accept this suggestion at this time as it is currently an experimental flag.
