### ISSUE TITLE
bug: Breaking News not hiding in v2.190.24

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1497]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.33.40 with v2.190.24 patches.

### Bug description

Only the "Breaking News" text is hiding, the whole component is not hiding.
This is happening after upgrading to v2.190.24. I had to use a custom filter to hide it (horizontal_video_shelf).
![Screenshot_2023-10-07-07-56-08-18_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/inotia00/ReVanced_Extended/assets/91815107/06652f11-3d16-4b43-a9df-667d083b03c1)

### Steps to reproduce

Step 1. Hide breaking news from Settings.

Step 2. Notice that it is not hiding fully.

### Relevant log output

```shell
No logs.
```

### Device Environment

Android 12, Realme UI 3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
Can confirm !

**Comment by Aryan-Chauhan** [comment]
> Can confirm !
> Update: After clean app data, all worked normally. But Suggestion Shelf not showed even if the Hide Suggestion Shelf options turned off

Did what you said. Still not working as it is supposed to do.

**Comment by inotia00** [comment]
Just wait for the next release

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.4)
