### ISSUE TITLE
feat(patch): Convert shorts to regular youtube videos

### ISSUE THREAD

**Issue by KyleBroflowski** [inotia00/ReVanced_Extended#15]
### Application

YouTube shorts

### Issue

The shorts history got completely removed from YouTube history. But when the short video links are replaced by regular youtu.be/watch links it gets added into the history

Also normal shorts layout doesn't have a seekbar or an option to change quality of video. This patch will resolve it tol

### Patch

A toggleable option within revanced settings called convert shorts To be able to convert the short links _youtube.com/shorts/_ 
to _youtube.com/watch?v= or youtu.be/_
and play them so that they may be available in the regular youtube history.

Additional Option to Add a button below the short videos to be able to view the regular shorts layout. 
This also resolves the issue mentioned in inotia00/ReVanced_Extended#1

### Motivation
Enhancer for YouTube extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
