### ISSUE TITLE
bug: material you patch not working

### ISSUE THREAD

**Issue by D3SOX** [inotia00/ReVanced_Extended#150]
### Type

Cosmetic

### Application

YouTube v18.01.36

### Bug description

material you patch not working

### Steps to reproduce

Step 1. include 'materialyou' and patch.
Step 2. start the app and see it not being applied

### Relevant log output

```shell
not relevant
```

### Screenshots or videos

![Screenshot_20230115-023522_ReVanced Manager](https://user-images.githubusercontent.com/24937357/212505095-d778474d-b7d3-4083-9471-c2e1fba0e12f.png)
![Screenshot_20230115-023527_ReVanced Extended](https://user-images.githubusercontent.com/24937357/212505112-12c75647-74d8-4d77-8830-2538002adb62.png)

### Additional context

Seems to work with the latest build from ReVanced_MMT channel

### Device Environment

Android 12, LineageOS 19.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![documentations](https://user-images.githubusercontent.com/108592928/212522763-dd6ccce8-7d71-4849-b69c-65a87577b8b1.png)
it's not a bug
You included both the `theme` patch and the `materialyou` patch

If you only want the `materialyou` theme, exclude the `theme` patch

**Comment by D3SOX** [comment]
Thanks, sorry I missed that
