### ISSUE TITLE
bug(YouTube): video doesn't exactly start from where it was closed

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1500]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

When you close the video in PiP, in normal mode it doesn't exactly start from the point you closed the video, the video starts from 5~7 seconds earlier

(Watch it with audio)

https://github.com/inotia00/ReVanced_Extended/assets/130296934/6a5b1136-0e67-4dc7-a784-539c6a45cdc6

### Steps to reproduce

Shown in video

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1482

**Comment by federicogith** [comment]
> #1482

That bug has just been fixed

But this bug still occurs with the latest release
@inotia00 can you open this as it's not a duplicate?

**Comment by inotia00** [comment]
sure
