### ISSUE TITLE
bug: headphones button missing in PiP

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1501]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.33.40
Patches latest

### Bug description

![Screenshot_20231008_165523_Nova7](https://github.com/inotia00/ReVanced_Extended/assets/130296934/9df4df91-5c99-4f82-b736-e18d1628f217)
![Screenshot_20231008_165528_Nova7](https://github.com/inotia00/ReVanced_Extended/assets/130296934/0b048fba-3642-4920-9f63-c60fa4d66090)

**Also without that button is not possible to play video in the background**

https://github.com/inotia00/ReVanced_Extended/assets/130296934/c87c5eee-9eb1-45d0-a112-d039b2052199

### Steps to reproduce

N/a

### Relevant log output

```shell
N/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.4)
