### ISSUE TITLE
bug: Notification miniplayer don't resume video just stop it.

### ISSUE THREAD

**Issue by staticpiratex** [inotia00/ReVanced_Extended#1502]
### Type

Other

### Tools used

ReVanced Manager

### Application

Youtube 18.33.40
Youtube 18.27.36
Patches latest

### Bug description

I open a video, then out of Youtube App with background playback video.
When I click to stop video in the notification player It works, but when I try resume the video don't works and sometimes crash app.
I tried on 18.33.40 and 18.27.36 app.

### Steps to reproduce

Step 1: Open a video on Youtube app;
Step 2: Go out from Youtube app with the video on playback background;
Step 3: Click to stop video on notification miniplayer;
Step 4: Click to resume video on notification miniplayer

### Relevant log output

```shell
???
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/102470605/79037b18-4b68-4664-b0a4-2ba2a36fa881

### Additional context

I tried with microg (teamvanced), microg (inotia00), mMicrog and microg (RE) and all reproduce the same bug.

### Device Environment

Android 13 One UI

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [x] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.4)
