### ISSUE TITLE
About seekbar thumbnail in Revanced and Revanced extended 

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#1503]
### Application

YouTube

### Description

There is difference between how the seekbar thumbnail appears between Revanced and RVX. The method of official Revanced is similar to the stock YouTube
There are 2 videos showing the difference
I think the method of Revanced is better as it show seekbar thumbnail as a small window rather than RVX method which show thumbnail in the whole video player
Is it possible to implement the method of Revanced in RVX?
First video (Revanced)
https://github.com/inotia00/ReVanced_Extended/assets/107951133/cc43c8ab-9d48-41fb-8608-b2b487d71302

Second one(RVX)

https://github.com/inotia00/ReVanced_Extended/assets/107951133/294c13d0-eca1-40f9-839c-57b92fc6ccbb

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This patch has already been implemented

You included the `Enable new thumbnail preview` patch and manually enable it in the settings

turn off:
Settings > ReVanced Extended > SeekBar > Enable new thumbnail preview
