### ISSUE TITLE
feat(YouTube): add separate option to spoof feed videos player paremeter from ReVanced 

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1505]
### Application

YouTube

### Issue

ReVanced added this as separate option, but in RVX we can do nothing with feed videos spoof parameter, this is not new feature, just match ReVanced change, and i think this thing is really needed
![Screenshot_20231009_213503_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/791deee1-495c-4141-944a-f694e97212e7)

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In other words, spoofing in the feed makes these bugs https://github.com/inotia00/ReVanced_Extended/issues/1313 https://github.com/inotia00/ReVanced_Extended/issues/1449
This is why I am not adding this to RVX Patches

**Comment by girshcatt** [comment]
Yes, i know, but spoof parameter is experimental flag, isnt it? And main option have side effects, just do feed spoof off by defalut and mark these side effects

**Comment by inotia00** [comment]
makes sense, I will reflect it in the next release

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.193.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.4)
