### ISSUE TITLE
Add warning to patch changelog that RVX Manager users must update manager manually 

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1506]
### Application

Other

### Description

Older RVX Manager versions are not able to fetch the current patches and will crash upon startup. (See this issue in the ReVanced Manager repo https://github.com/ReVanced/revanced-manager/issues/1330)

It will be good to add a warning in the changelog that users must manually update their RVX Manager by downloading it from your RVX Manager repo.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It was [added](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.4) a while ago 👍
