### ISSUE TITLE
bug(YouTube/Enable old quality layout): on tablets sometimes quality menu get bugged

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1507]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

YouTube 18.22.37 ~ 18.33.40

### Bug description

It can appear on all supported versions, i saw this bug much time ago, and now it came back, i think that it started to appear after you fixed https://github.com/inotia00/ReVanced_Extended/issues/1430, ah i forgot to describe bug. It appears sometimes and we have no any tutorial to reproduce it, just randomly when you open quality menu. You see new quality menu on all of the screen and other space is black, you cant leave this menu and get it off the screen, i have a screenshot
![Screenshot_20231010_031921_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/6d7630a2-0c98-4694-ad8a-cb14d6e99b84)
Just like this, i dont know much info about this bug, because it appears randomly

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
If i remember right it reproduced only one time on phone

**Comment by inotia00** [comment]
Since I don't have a tablet, I think a fix would take a very long time or be close to impossible

I'm leaving the issue open because I need to get some helpful information from others regarding this issue

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.12)

Since I don't have a tablet, I couldn't check if it was resolved.
In theory, it would definitely have been fixed.

If the issue persists, please re-open the issue then.

**Comment by girshcatt** [comment]
Issue apeared again, i used 18.29.38, dont know about other versions, but i think tnat it reproducable too, at least on all lower versions than 18.29 and 18.32, this is so rare bug that i cant just wait a month to reproduce it, i sure on 100% that it affect all versions from supported except 18.27.36 (because it has old quality menu)
![Screenshot_20231019_235319_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/36d86c72-70a0-4323-bec0-84e1f30b1f06)
I hope that you will finally buy a tablet as you said in rvx chat, i think that you can reopen issue

**Comment by inotia00** [comment]
Since this is a very rare issue, please export the settings you are using when the issue occurs and then upload it

**Comment by girshcatt** [comment]
[ReVanced Extended_v18.29.38_2023-10-19.json](https://github.com/inotia00/ReVanced_Extended/files/13052846/ReVanced.Extended_v18.29.38_2023-10-19.json)

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
