### ISSUE TITLE
bug: Pop-up message error, displayed at the bottom when turning movie lighting mode on and off

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/ReVanced_Extended#1508]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

YouTube 18.33.40

### Bug description

Pop-up message error, displayed at the bottom when turning movie lighting mode on and off.

Turns the movie lighting mode on and off, and the message at the bottom shows it as turning the standby mode on and off.

### Steps to reproduce

Turns the movie lighting mode on and off, and the message at the bottom shows it as turning the standby mode on and off.

### Relevant log output

```shell
display : standby mode on or off
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
RVX does not change pop-up messages

It's an issue that exists on stock YouTube

**Comment by root-kernelhacker** [comment]
Looking at stings.xml, the "cinematic_lighting_toggled_.." flag is set to "Ambient mode", and when I translate this into Korean, it becomes "Ambient mode".  It seems that YouTube set the translation and message incorrectly.
