### ISSUE TITLE
suggestion: use a more appropriate settings label

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1509]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

YouTube 18.33.40

### Bug description

I know it's a experimental patch as such, bugs are to be expected but I think Inotia00 can fix this little cosmetic bug without much effort or changing anything within the functions of the patch itself.
The patch ``Skip summy segment`` description is cut off mid way within the patch description inside ``ReVanced Extended/Video `` catagory.

### Steps to reproduce

1. Patch YouTube 18.33.40 normally
2. Go to ReVanced Settings/Video and see Skip dummy segments patch description at bottom under Experimental flags.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-10-10-18-13-59-147_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/d9aefedb-d9ad-42a9-92fd-bf4b6b882d3b)

### Solution

Add scroll bar within the patch descriptions if it's too long or fully show then when clicking on the description other then the toggle button.

### Additional context

N/A

### Device Environment

Android 13 MIUI 14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
I recommend just to do font smaller, it will be much more comfortable and not only in this situation

**Comment by inotia00** [comment]
If this is a bug, then the bug exists on all lower resolution devices

Change the label to something that seems more appropriate

**Comment by Rairof** [comment]
That makes sense, alright thanks.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.193.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.8)
