### ISSUE TITLE
feat(patch): Remove buttons in Shorts with extras

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#151]
### Application

YouTube

### Issue

1. Please add a patch to remove the Join button from Shorts too.
2.  Please add a section with options for shorts to disable buttons like camera, search, etc.
3. Please add a patch to remove this type of warnings in Shorts too.

If it is possible then please try to add a download button in shorts too. Because saving the shorts mixes in other Shorts. Please take a look at this.

### Patch

![Screenshot_20230115-130127](https://user-images.githubusercontent.com/93650504/212553644-ff570322-6233-4a0a-bd22-b485f717d71f.png)

### Motivation

It will improve productivity.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![shorts_player](https://user-images.githubusercontent.com/108592928/217692887-9da66ee5-b7b2-444e-a757-ec2e78d4a042.png)
① Hide shorts player join button
② Hide info panels

some are reflected in [revanced-patches-v2.159.6](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.6)

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
