### ISSUE TITLE
suggestion: <disable PIP trigger when using download patch>: 

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1511]
### Application

YouTube

### Description

When we use the download button on a video while it is playing, the download pop up actionsheet appears but YouTube itself triggers going to pip mode while having a loading screen on top of the playing video but pausing video and then clicking download doesn't trigger the pip trigger and the download actionsheet works over YouTube in background that stays on full-screen behind the download actionsheet while you play the video via media playback in your notification.
I suggest disabling the pip trigger on YouTube while clicking on download button so it works normally just like how it works while video is paused. I know it sounds confusing but these screenshots should make it easier to understand.

(Using download patch feature with video paused)
![Screenshot_2023-10-11-00-07-08-791_com deniscerri ytdl-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/c8eb6e40-7e3f-4d03-ad9f-36f9e4d246e0)

(Using download patch feature while video is playing)
![Screenshot_2023-10-11-00-09-01-432_com deniscerri ytdl-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/d59e412b-d8a9-4c25-88c9-a4efdf21ecd6)
Automatically triggers pip mode and shows a loading icon over the video while it's still playing in background.

I don't know if it's an issue, side-effect or supposed to behave like that but it would be ideal for YouTube not to trigger the pip mode like that as it's annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I'm not accepting any suggestions or feature requests for new patches for YouTube

**Comment by inotia00** [comment]
this can be solved by turning off pip mode. or open the PR

**Comment by Rairof** [comment]
> this can be solved by turning off pip mode. or open the PR

Turning off pip mode, going to the video and downloading it and then turning pip mode on is quite a lengthy workaround to this. Besides it works fine when video is paused, I was talking about behaving similarly but with video playing and not paused. I can open a new PR and description the issue in a more simplified way if needed. Thank you.
