### ISSUE TITLE
suggestion: <Improving video descriptions>: 

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1512]
### Application

YouTube

### Description

Video descriptions to dynamically show full description when there is free space available after hiding it's components.

![Screenshot_2023-10-11-00-21-44-877_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/3ac5ae55-305a-45fc-834d-f88bf327cba3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I'm not accepting any suggestions or feature requests for new patches for YouTube

**Comment by Rairof** [comment]
It was a suggestion revolving already existing patches under description category under ReVanced general settings.

**Comment by inotia00** [comment]
This is not a bug and the layout cannot be changed with RVX Patches.
Because litho components depend on the server side and cannot remove empty space or add new views.

**Comment by inotia00** [comment]
> I'm not accepting any suggestions or feature requests for new patches for YouTube

↑

**Comment by Rairof** [comment]
Alright then I understand. 👍
