### ISSUE TITLE
question: when will suggested youtube version be bumped?

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1517]
### Application

YouTube

### Description

Will you update YouTube to latest version ? If you update the latest version just type note what will happen after update bcus many wants latest version for new ui things

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Probably by 2024
