### ISSUE TITLE
bug(YouTube Music/Hook download button): when you open and close download menu immediately it looks a little laggy

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1518]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube Music 6.22.51

### Bug description

On old layout when you tap download button and exit it action buttons lag on half a second like this

https://github.com/inotia00/ReVanced_Extended/assets/110785596/b8ccdd3f-13ce-43b2-a75e-30aaeb10afee

### Steps to reproduce

Patch 6.15.52 ~ 6.22.51
Turn off enable new player layout
Turn on hook download button
Tap download button in any track and close popup menu until action buttons will dissapear

### Relevant log output

```shell
:/
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This bug can be resolved by not disabling `Enable new player layout`

Since new player layout is now officially rolled out, the `Enable new player layout` patch is no longer needed

Therefore, I will remove the `Enable new player layout` patch in the next release

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.8)

**Comment by D4niloMR** [comment]
> Therefore, I will remove the Enable new player layout patch in the next release

A new `enable-old-player-layout` patch can be added. Should I make an issue?

**Comment by girshcatt** [comment]
Interesting fact: 6.21.52 is the last version that has no this lag, now i am using it
