### ISSUE TITLE
bug(YouTube/Minimized playback): controlling notification control nothing

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1519]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.22.37 ~ 18.33.40

### Bug description

YouTube Shorts shows blank minimized playback notification. If it useless just remove it

https://github.com/inotia00/ReVanced_Extended/assets/110785596/c82483d0-8782-436a-9f09-986395f7f3ca

### Steps to reproduce

1.Include `minimized playback` patch
2.Watch Shorts video and check notifications

### Relevant log output

```shell
:/
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
It just do nothing

**Comment by YT-Advanced** [comment]
Lol I think Google should invite you to be an App Tester 😑

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.8)
