### ISSUE TITLE
External links of YouTube opening in YouTube app instead of YouTube revaced extended

### ISSUE THREAD

**Issue by rushabhT3** [inotia00/ReVanced_Extended#152]
That's it. It is for Android 12 and after YouTube 17. something. Mobile is realme 9 SE 5G. I can't disable YouTube app. Also option to choose opening YouTube links via revaced has disappeared now too.
Today itself I could to open external links via revaced but now it has altered somehow. And all I can do it open extra links in YouTube only I have also uninstall updates on YouTube but it still shows YouTube 17. Something. Earlier versions of YouTube I cannot download currently my device is not rooted.
Kindly consider working on this.

**Comment by inotia00** [comment]
Not an issue with ReVanced or ReVanced Extended
(Issue of Android 12+)

Also, when writing an issue, please write according to the form
