### ISSUE TITLE
bug(YouTube/Hide channel watermark): watermark is not hidden

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1521]
### Type

Error at runtime

### Tools used

Revancify

### Application

18.36.39

### Bug description

``Hide channel watermark`` no longer works after updating from last version to current latest version of RVX.

### Steps to reproduce

1. Patch YouTube with latest patches normally with confirming``Hide channel watermark`` patch selected 
2. Enable ``Hide channel watermark`` in RVX settings
3. Watch any video in fullscreen.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-10-13-07-12-50-559_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/24ddc92b-698c-4fb2-af75-215c662a6b3e)

But
![IMG_20231013_071642](https://github.com/inotia00/ReVanced_Extended/assets/107706560/52060110-9bba-4795-83fe-91828ebf8534)

### Solution

Fix ``Hide channel watermark`` patch to functional state.

### Additional context

N/A

### Device Environment

Android 13 MIUI 14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
it works for me
looks like A/B tests

**Comment by girshcatt** [comment]
@inotia00 he wrote issue a little bit incorrect, i know what he said about. I saw the same issue from person in RVX chat, he pinned video link and everyone who opened it saw watermark too, video link: https://youtu.be/cVzCxCk8klg?feature=shared, check it, i sure that you will se watermark. Also person from chat who found that bug said that it fixable by repatch to 18.35.36

**Comment by Rairof** [comment]
Oh so it's a YouTube version issue? I'd have no way of knowing what the cause is so thought it's just a minor plugin error. I didn't bothered to check on previous versions as that'll require multiple reinstallations and patching so thought it was a bug on all YouTube versions since I see video watermarks on almost all videos.

**Comment by inotia00** [comment]
nah these are just A/B tests

**Comment by girshcatt** [comment]
> nah these are just A/B tests

Did you tried video link?

**Comment by Rairof** [comment]
I tried it and it shows watarmark, however when watching another video from same channel, it doesn't shows watermark. Here is a pic.
![Screenshot_2023-10-13-14-59-51-439_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/107706560/b9c3cd15-c00c-48fd-8406-5500f60af12f)
So I guess it really are A/B tests probably.

**Comment by girshcatt** [comment]
As i see ReVanced fixed this problem in dev versions

**Comment by inotia00** [comment]
It was already merged into the private repo 16 hours ago.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.12)
