### ISSUE TITLE
Shorts Shelf not showing in home page

### ISSUE THREAD

**Issue by MayaBi7** [inotia00/ReVanced_Extended#1522]
Shorts Shelf not showing in homepage

**Comment by KobeW50** [comment]
You can unhide them by going to Settings > ReVanced Extended > Shorts.

**Comment by KobeW50** [comment]
> > You can unhide them by going to Settings > ReVanced Extended > Shorts.
> 
> Still not showing👍

You aren't refering to the shorts button are you?

Other possibilities i can think of are:

A) You have a custom filter hiding the shorts shelf

B) YouTube isn't showing the shorts shelf (maybe A/B testing)

C) There is a bug in which the ReVanced Extended option to hide the shorts shelf cannot be disabled. This would need a proper bug report if this is the case.

**Comment by MayaBi7** [comment]
> > > You can unhide them by going to Settings > ReVanced Extended > Shorts.
> > 
> > 
> > Still not showing👍
> 
> You aren't refering to the shorts button are you?
> 
> Other possibilities i can think of are:
> 
> A) You have a custom filter hiding the shorts shelf
> 
> B) YouTube isn't showing the shorts shelf (maybe A/B testing)
> 
> C) There is a bug in which the ReVanced Extended option to hide the shorts shelf cannot be disabled. This would need a proper bug report if this is the case.

![Screenshot_2023-10-13-09-51-20-207_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/96541364/0b4e58e4-236b-489c-b709-87b8aa2ed713)

**Comment by KobeW50** [comment]
Please give some context

**Comment by YT-Advanced** [comment]
@MayaBi7 can you turn off Hide Suggestion Shelf and check again too ?

**Comment by MayaBi7** [comment]
> @MayaBi7 can you turn off Hide Suggestion Shelf and check again too ?

Still not showing...👍

**Comment by MayaBi7** [comment]
@YT-Advanced @KobeW50 problems is in my account 🙃 changed to a different account and Short shelves showing in homepage again...I don't know what's going on with Google...😮‍💨
