### ISSUE TITLE
suggestion(YouTube/ SponsorBlock): make these settings exportable as RVX settings

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1526]
### Application

YouTube

### Description

SponsorBlock has some options related to RVX settings, not to SB settings. Can you make these settings exportable as RVX settings: Show voting button, Use compact skip button, Automatically hide skip button, Show create new segment button and Adjust new segment step value. Correct me if i mess some SB settings related to RVX. Also after this change won't be such issues as https://github.com/inotia00/ReVanced_Extended/issues/1435

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
I.e combine SB import/export patch with RVX import/export patch.

**Comment by girshcatt** [comment]
> i.e include SB import/export patch to RVX import/export patch.

No, no any new patch, i mean add SB settings related to RVX in RVX import/export option
