### ISSUE TITLE
suggestion(YouTube Music): correct revanced_external_downloader_package_name_summary string to match YouTube string

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1528]
### Application

YouTube Music

### Description

Correct revanced_external_downloader_package_name_summary string to match YouTube string. In YT it looks: Package name of your installed external downloader app, such as NewPipe or YTDLnis
And in YTM it looks: Package name of your installed external downloader app, such as NewPipe or Seal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.193.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.12)
