### ISSUE TITLE
suggestion(YouTube): add dots in strings where they needed

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1529]
### Application

YouTube

### Description

Strings in YTM grammatically looks right, they have dot at the end, but in YT you didn't do that, please add . where they needed

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Too many string changes required
Please leave a PR

**Comment by girshcatt** [comment]
Please not close issue now, when i will have enough time i will do all and open pr

**Comment by YT-Advanced** [comment]
Lol, you are OCD, I think

**Comment by girshcatt** [comment]
> Lol, you are OCD, I think

Phah, you guessed right, i have it
