### ISSUE TITLE
Can you make editing layouts in revaced extended like editing icons on Android or bookmarks in current safari browser in windows 

### ISSUE THREAD

**Issue by rushabhT3** [inotia00/ReVanced_Extended#153]
The names are hard to remember particularly. Many times I don't have clue like why a small minimized window of windows is not playing I still don't i must have toggled something. Or may be you can show what I'm editing with a quick snapshot of change pervious vs current etc. Kindly provide a more user friendly atmosphere for editing its a difficult one currently to understand

**Comment by inotia00** [comment]
no plan

Also, when writing an issue, please write it according to the form
