### ISSUE TITLE
question(YouTube Music): is this possible to implement playback speed the same way as it looks like in podcasts

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1530]
### Application

YouTube Music

### Description

Is this possible to implement playback speed the same way as it looks like in podcasts? I mean that podcasts has their own playback speed menu that looks like playback speed menu in YT, can this menu be implemented to tracks instead of already implemented method?
![Screenshot_20231013_183623_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/ebf56719-9642-4643-a995-7285c4de4f63)
![Screenshot_20231013_183627_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/8dac436d-7732-4822-b3f4-15ad4ecf7d2b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
That's impossible.

I've already tried this before, but if I force load the playback speed flyout panel when the podcast isn't playing, it returns an empty value and a alert dialog 'Playback speed not available' is shown.
