### ISSUE TITLE
Hide video recommended at the end of playback.

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1531]
### Application

YouTube

### Description

It would be nice to be able to hide the screen that opens at the end of playback....if possible.
![Screenshot_2023-10-13-18-00-26-182_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/50fc7d63-7888-4049-b9ef-0014eff1ac19)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Settings > Revanced Extended > Player > Hide suggested video overlay

**Comment by jhon1282** [comment]
> Settings > Revanced Extended > Player > Hide suggested video overlay

Thank you very much for your availability, I apologize but in the previous version this screen did not appear 👍
