### ISSUE TITLE
suggestion: <title>: gradiant loading screen improvement

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1533]
### Application

YouTube

### Description

When we first time open the app that time only gradient screen appers can you add gradient screen for those thumbnails which are not loaded while we scroll the videos.
![IMG_20231013_235642](https://github.com/inotia00/ReVanced_Extended/assets/131557644/9e132013-fc09-4437-a8b9-25ebb34716e5)

Well for thanks to add this feature in the extended after a long time i saw the new feature i like this one keep up.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I'm not accepting any suggestions or feature requests for new patches for YouTube

**Comment by Adity1243** [comment]
Ok np

**Comment by inotia00** [comment]
Thank you for understanding
