### ISSUE TITLE
Is there a list of all the logos that ReVanced Extended uses?

### ISSUE THREAD

**Issue by Clouud9** [inotia00/ReVanced_Extended#1534]
### Application

YouTube

### Description

I saw that the logo had changed for my version during an update and I preferred the old one. I've been unable to find the originals (and the AFN ones, for that matter), and I don't know where else to ask. Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by hlytus** [comment]
Afn icons were removed long time ago. [Here's](https://imgur.com/a/EFYrZRf) the list of icons that are currently being used.
