### ISSUE TITLE
bug: <title> Hide channel watermark Not working 

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1535]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube verson 18.36.39

### Bug description

Hide channel watermark no longer works after
updating from last version to current latest version
of RVX.

### Steps to reproduce

1. Patch YouTube with latest patches normally
with confirming Hide channel watermark
patch selected
2. Enable
settings
Hide channel watermark in RVX
3. Watch any video in fullscreen

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![IMG_20231014_113725](https://github.com/inotia00/ReVanced_Extended/assets/117540245/4c4322b4-ddad-4539-af82-358f4301da40)

### Solution

N/A

### Additional context

N/A

### Device Environment

Android 12, MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
It is a watermark added by channel owner, not Youtube itself
