### ISSUE TITLE
question: <title>: Remove PopUp in Video Player

### ISSUE THREAD

**Issue by itsmenewbie03** [inotia00/ReVanced_Extended#1536]
### Application

YouTube

### Description

How can make that pop up thing with an x button to not appear anymore?
![Screenshot_20231014_152609](https://github.com/inotia00/ReVanced_Extended/assets/89230263/1f761a95-bca0-4366-981c-4d032c4b7d71)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Settings > ReVanced Extended > Player > Hide info cards

**Comment by itsmenewbie03** [comment]
> Settings > ReVanced Extended > Player > Hide info cards

Info cards are hidden as the settings says, but it still appears.

**Comment by inotia00** [comment]
You may be using an outdated version
Patch again to the latest version
