### ISSUE TITLE
feat(patch): remember current brightness (swipe gesture)

### ISSUE THREAD

**Issue by sliceanddice9** [inotia00/ReVanced_Extended#154]
### Application

YouTube

### Issue

When changing the brightness number/level for a video, and then closing the app and opening the app back up again - the brightness number/level always resets to 0. 

### Patch

When setting the brightness for videos in fullscreen via the swipe control brightness gesture, have it stick to whatever brightness number/level you last set the brightness number/level to instead of the brightness number/level defaulting to 0 every time you close the app. 

### Motivation

The original YouTube Vanced via the swipe control brightness gesture locks the brightness level/number for all videos even when closing the app and then opening the app back up. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.156.4
