### ISSUE TITLE
bug: Hide NavBar when playing Shorts not worked correctly

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#1540]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Youtube v18.36.39

### Bug description

NavBar not hidden in Shorts

### Steps to reproduce

1. Open a shorts video
2. Click on comments section
3 Close comments section, navbar will immediately show up normally even if it's disabled

### Relevant log output

```shell
None
```

### Device Environment

Reproduced in both Android 11 and Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
Additational Information is that this hook code never be called in newer version
<img width="653" alt="image" src="https://github.com/inotia00/ReVanced_Extended/assets/70064328/dda256df-7a0f-4943-8b15-8980557a09f9">

**Comment by YT-Advanced** [comment]
The problem happened when you update your new fingerprint to support `v18.25.39`. Hope these information are enough useful for you

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1041
