### ISSUE TITLE
suggestion: YouTube Music: Hide refresh premium button

### ISSUE THREAD

**Issue by limonetas** [inotia00/ReVanced_Extended#1541]
### Application

YouTube Music

### Description

![Screenshot_2023-10-14-23-30-04-855_app rvx android apps youtube music-edit](https://github.com/inotia00/ReVanced_Extended/assets/47794002/7467ff1f-2a3a-4f3f-83f6-43273d8ba9d9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Include the 'Hide navigation bar component' patch. If it still isn't hidden, open YTM RVX > Settings > ReVanced Extended > Navigation > Hide Upgrade Button, On

**Comment by limonetas** [comment]
> Include the 'Hide navigation bar component' patch. If it still isn't hidden, open YTM RVX > Settings > ReVanced Extended > Navigation > Hide Upgrade Button, On

![Screenshot_2023-10-14-23-40-59-031_app rvx android apps youtube music](https://github.com/inotia00/ReVanced_Extended/assets/47794002/3491a7be-beb0-4b2b-b700-16357c9d67e2)
It is the latest update and they do not appear.
