### ISSUE TITLE
suggestion(YouTube Music): Package name has the word "app" repeated twice

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1542]
### Application

YouTube Music

### Description

The word "app" is repeated twice in the case of YT Music and it's not repeated for YouTube.

YouTube:
![Screenshot_20231015-190854~4](https://github.com/inotia00/ReVanced_Extended/assets/117499019/31b9026b-e086-46e4-8cd0-3c584701eb68)

YouTube Music:
![Screenshot_20231015-190844~3](https://github.com/inotia00/ReVanced_Extended/assets/117499019/d1ffea90-9958-4612-9d9c-0c44050b8f29)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
So my suggestion is that it would be better to remove "apps" from the package name of YouTube Music to `app.rvx.android.youtube.music` for consistency and better naming.

**Comment by hlytus** [comment]
I guess that's because official YT Music package name is com.google.android.apps.youtube.music and com.google is replaced with app.rvx. Same for YouTube.

**Comment by ILoveOpenSourceApplications** [comment]
Understood. But since we're modifying the package name anyways why not make it something a bit more proper while we're at it.

**Comment by ILoveOpenSourceApplications** [comment]
I understand that the `Custom package name` patch can be used to modify it. But, is the editing of the package name a huge task as you're required to modify it everywhere, if so I understand your disinterest. If not, don't you agree that it's weird to have the same word repeated twice in the package name by default?

**Comment by ILoveOpenSourceApplications** [comment]
Another issue is that when the user modifies the package name, it's recognised as a new app and installs separately. Whereas if it's done by default, yes the user will still have to install it as a new separate app, but afterwards won't be required to look into it. Would be similar to how YouTube at times is recommended as a clean install. Giving a small justification as to why it would be better if done by default. But, like I said in the previous comment, if it creates a lot of work in other areas, I understand your lack of interest.
