### ISSUE TITLE
bug (YouTube): videos in library disappear after entering fullscreen

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#1544]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

YouTube 18.36.39 patches 2.193.12

### Bug description

When on the history tab, entering full screen mode ends up in videos of library tab (so both in playlists and history) disappearing untill refreshed.

### Steps to reproduce

Step 1. Open library tab
Step 2. Open video in fullscreen mode
Step 3. Go back to library

### Relevant log output

```shell
None
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/78740080/aff79046-2665-41c0-9611-92654f71c785

### Device Environment

Android 14, pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Not reproduced on my side

Exclude patches until the issue does not reproduce and specify which patch is causing the issue

**Comment by KobeW50** [comment]
I haven't bothered narrowing down the patch, but I am able to reproduce this in 18.36.39 with patches version 2.193.12

In my case, the issue occurs even when just rotating my device (even when no video is played)

https://github.com/inotia00/ReVanced_Extended/assets/84587632/ae322a6d-52e4-44f1-8bed-0a2ec26d41d5

![logcat_10-16-2023_22-33-24.txt](https://github.com/inotia00/ReVanced_Extended/files/12923648/logcat_10-16-2023_22-33-24.txt)

**Comment by inotia00** [comment]
Interesting, this issue does not reproduce on Android 10, 11, and 12 devices
Reproduced only on Android 13 devices

Since I tested it on different devices, it may be related to the dpi settings of the device

I will do some more testing and record the results

**Comment by inotia00** [comment]
Surprisingly, this is a bug that exists in the unpatched `YouTube v18.36.39`
This issue does not reproduce in `YouTube v18.35.36` or `YouTube v18.37.36`, but only in `YouTube v18.36.39` lol

This is a Google bug, so I cannot fix it on my side

If you are using an Android 13+ device, just patch to `YouTube v18.35.36` or lower
