### ISSUE TITLE
bug: YouTube pip when comment

### ISSUE THREAD

**Issue by limonetas** [inotia00/ReVanced_Extended#1545]
### Type

Other

### Tools used

Revancify

### Application

Yt v.18.36.39, latest patches.

### Bug description

Look at the video

### Steps to reproduce

1. Pick any video 
1. Comment with playback
1. Swipe up o touch home button

### Relevant log output

```shell
?
```

### Screenshots or videos

[Video here](https://drive.google.com/file/d/1ck6dCINNY3caWunv167zu8pZtryNwGcp/view?usp=drivesdk)

### Device Environment

Android 13.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [ ] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It also reproduces on unpatched YouTube
This is an issue that Google needs to fix
