### ISSUE TITLE
bug(YouTube/RYD): on 18.34.xx+ in shorts dislikes count shows count of previous video and not update it automatically

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1547]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.34.38 ~ 18.37.36

### Bug description

On 18.34.xx+ in shorts dislikes count shows count of previous video and not update it automatically. This issue appear not on all devices, but much people yet facing it. As Alireza said ReVanced seem like they fixed it. I saw some people in chat reported the same, for example i will pin screen record

### Steps to reproduce

1.Patch 18.34.38 ~ 18.37.36 with included `Return YouTube Dislike` patch and turn on dislikes for shorts
2.Do some dislikes count tests

### Relevant log output

```shell
:/
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/110785596/26d8f43b-96f2-4f77-8de9-6fd811ea73a4

### Device Environment

Samsung Galaxy Tab S6
Android 12, One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
The process for reproducing the issue does not seem to be clear.
Is this issue only reproduced when the dislike button is clicked?

**Comment by 123jjck** [comment]
> The process for reproducing the issue does not seem to be clear. Is this issue only reproduced when the dislike button is clicked?

When watching shorts, dislikes from the previous Short are shown (if this is the first open Shorts, then it shows correctly). 
If you click dislike, the correct quantity for the current Short will be displayed. 
if not, then the incorrect dislikes count will continue to be displayed.

**Comment by girshcatt** [comment]
> The process for reproducing the issue does not seem to be clear. Is this issue only reproduced when the dislike button is clicked?

Yes

https://github.com/inotia00/ReVanced_Extended/assets/110785596/1cb0cf90-2bda-486f-820f-1b639007f5b9


https://github.com/inotia00/ReVanced_Extended/assets/110785596/729ddf92-330e-499c-8947-461f17c95228

**Comment by girshcatt** [comment]
Also some videos randomly can show that there is no dislikes at all, but when you click dislike count appear

**Comment by girshcatt** [comment]
After big tests i can say that best versions for Shorts RYD is 18.29.38, 18.30.37, 18.31.40 and 18.32.39. 18.33.40 seem working fine too, but on some devices it has issues too. All versions lower than 18.29.xx has problems like you swipe to previous video and it not shows dislike count before you will click the button

**Comment by inotia00** [comment]
Strangely, this issue does not reproduce on Android 10 devices
Maybe it will be fixed in the next release

**Comment by girshcatt** [comment]
> Strangely, this issue does not reproduce on Android 10 devices Maybe it will be fixed in the next release

I apologize that it can depends on device environment, most of people who facing this issue use device with One Ui, i one of them. But then i found that some people from other ROM facing the same

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.18)
