### ISSUE TITLE
suggestion(YouTube/Settings): place import and export options right way

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1548]
### Application

YouTube

### Description

Place import and export options right way, in my opinion they placed incorrectly, because all related to import export named in this sequence: 1.import 2.export
![IMG_20231017_144140_535](https://github.com/inotia00/ReVanced_Extended/assets/110785596/83eb74a0-51a3-4c68-bd59-a43943110bce)
If section named import/export why then first option is export?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is the intended order according to lexicographic sorting
