### ISSUE TITLE
bug(YouTube Music/SponsorBlock): when the app is in the background, segments are not fetched

### ISSUE THREAD

**Issue by JeFi2** [inotia00/ReVanced_Extended#1549]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube Music 6.20.51

### Bug description

If a new song starts while the app is not in the foreground, sponsorblock segments are not skipped. Only if I open the app, segments are skipped. If I open the app only briefly, it'll also work in the background until a new song starts.

### Steps to reproduce

-Start playing music while app is not in foreground
-Skip to a track that should have sponsorblock segments
-Sponsorblock segments are not skipped

### Relevant log output

```shell
none
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by rikinp93** [comment]
Same issue happening to me, same steps, have to unlock phone and open the app for sponsorblock to skip.

**Comment by KobeW50** [comment]
fixed in [2.196.0](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)

**Comment by KobeW50** [comment]
> fixed in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)

Wait nvm, the issue still occurs for me 😅

Also, if any1 needs an easy way to test, add [this song](https://music.youtube.com/watch?v=Zh9p-6JfrSo) to the queue

**Comment by inotia00** [comment]
The bug I fixed is an issue where the sponsorblock section is not fetched when the next music is played in the background

this issue has not been fixed yet

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.207.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.207.1)
