### ISSUE TITLE
bug: timecode navigation does not work in full screen mode

### ISSUE THREAD

**Issue by jezokshe** [inotia00/ReVanced_Extended#155]
### Application

YouTube

### Issue

Version 18.01.36 Non Root (NumberOne)
Only volume gesture enabled, player overlay disabled. Swipe on navigation in timecodes does not work.
  I wanted to let you know, just in case, sorry if it's been fixed.
Thank you for the patches and for the requests fulfilled.
![изображение](https://user-images.githubusercontent.com/77186394/212752376-8d5d537d-db87-4be1-b68a-c4be7b2815b3.png)

### Patch

j

### Motivation

j

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
No longer reproducible in latest release
