### ISSUE TITLE
feat(YouTube Music): add `Hide action buttons` patch

### ISSUE THREAD

**Issue by GasparGT11** [inotia00/ReVanced_Extended#1550]
### Application

YouTube Music

### Issue

Hope I'm not the only one, but I don't like the counter and comments in the player layout.

![Screenshot_20231017-154524](https://github.com/inotia00/ReVanced_Extended/assets/102194956/2c546bc3-15c6-43bd-a555-e70b0fcdddc8)

### Patch

I would love to hide the "Like" and "Comments" action buttons, just like in the video app.

![Screenshot_20231017-161405](https://github.com/inotia00/ReVanced_Extended/assets/102194956/359166e8-0f29-49a2-9443-21a0548024cd)

### Motivation

The are barely any options to customize the Action Bar. The only button that can be hidden is "Radio", wich I use a lot.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
I think that more correct will be to create an issue: feat(YouTube Music): add `Hide button containers` patch

**Comment by inotia00** [comment]
duplicate with https://github.com/inotia00/ReVanced_Extended/issues/1351, closing issue
