### ISSUE TITLE
suggestion(YouTube/Settings): remove reboot message when you import settings

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1552]
### Application

YouTube

### Description

Remove reboot message when you import settings, it useless because when you import settings app get rebooted automatically like this

https://github.com/inotia00/ReVanced_Extended/assets/110785596/bfc76b46-8dee-40f6-8e76-5aedbc3f1a46

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unfortunately, this cannot be reflected
Because the reboot dialog is shown automatically during the process in which dozens of settings are imported

**Comment by girshcatt** [comment]
> Unfortunately, this cannot be reflected Because the reboot dialog is shown automatically during the process in which dozens of settings are imported

Why you cant disable that app get autometically rebooted?

**Comment by inotia00** [comment]
Don't think it's strange, just accept it as is.
