### ISSUE TITLE
question(YouTube/Enable minimized playback): when you pause video in notification it can roll back on second

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1553]
### Application

YouTube

### Description

When you pause video in notification it can roll back on second, i did not give this issue a bug label because i cant test this in unpatched YouTube cause i have no premium. I need someone to test it.

https://github.com/inotia00/ReVanced_Extended/assets/110785596/f7cf3208-40a4-49a5-b13e-5a7eacf46b48

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It appears to be a duplicated issue with the following issue: https://github.com/inotia00/ReVanced_Extended/issues/1500
