### ISSUE TITLE
feat(YouTube/Hide layout components): add option to hide "Send feedback" in feed category bar

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1554]
### Application

YouTube

### Issue

Add option to hide "Send feedback" in feed category bar, it do nothing for MicroG users
![Screenshot_20231017_235621_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/d703ff7d-b4aa-4435-b95b-31d965b52e02)

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I do not accept new feature requests for YouTube.
