### ISSUE TITLE
suggestion(YouTube/Settings): all incorrect labels and issues in "Patches Information" section

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1555]
### Application

YouTube

### Description

All incorrect labels and issues in "Patches Information" section
1.`Custom speed overlay` info not shown
2.`Enable language switch` and `Force video codec` patches show old name that was before you renamed them: feat(YouTube): change patch name Language switch → Enable language switch; feat(YouTube): change patch name Force VP9 codec → Force video codec
3.All patch names shown with - like they were look before Cli v4
4.Change all lowercase patch names in the patch informations to uppercase

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is also necessary to change all lowercase patch names in the patch informations to uppercase
(e.g. `microg-support` → `MicroG support`)

Therefore, if additional changes are needed, please add them to contents.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.193.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.18)
