### ISSUE TITLE
Question about new flyout menu in player

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#1557]
### Application

YouTube

### Description

Fast question: today I received 'You' page instead library and new flyout design in player.
I have two questions:
1. Some hiding options don't work: report, loop, ambient mode, Premium steering. Rest I think it's working good. Will be fixed this in future?
2. Will be all related to library options renamed to 'You' page? (or Library/You)
![Screenshot_20231018_070631_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/69505731/0866f990-aba8-40a4-9573-8df73dba6da2)
![Screenshot_20231018_070634_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/69505731/aecfdea6-e466-49b4-b471-083da6570ff3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
nah neither layout is supported

related Issues https://github.com/inotia00/ReVanced_Extended/issues/630 https://github.com/inotia00/ReVanced_Extended/issues/1410

the only solution is to find a version that does not apply the new layout and apply the patch
