### ISSUE TITLE
bug(YouTube/Channel bar): join button hidden when it need to be shown

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1560]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.29.38

### Bug description

Join button hidden when it need to be shown, i checked that all channels i tested show join button in unpatched YouTube

https://github.com/inotia00/ReVanced_Extended/assets/110785596/a9cb535d-589a-4a6b-bfae-b2f80e4ee9c7

### Steps to reproduce

Turn off hide join button and check any channel that have it

### Relevant log output

```shell
:/
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Hide join button is located in the following path:
Settings > ReVanced Extended > Bottom player > Channel bar > Hide join button

In other words, it hides the join button in the channel bar at the bottom of the player
![IMG_20230108](https://github.com/inotia00/ReVanced_Extended/assets/108592928/e94dcff7-6e7d-4520-b7c6-f01674c83ff2)

It doesn't hide the join button on the channel information like the video you attached

None of the settings hide the join button in the channel information

Check out the custom filters you are using
That seems to be the likely cause
