### ISSUE TITLE
bug(youtube): `Hide account menu` can't hide items in new layout

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1561]
### Type

Error at runtime

### Tools used

Revancify

### Application

YT 18.39.41

### Bug description

The hide account menu does not hide the items in the "You" page in the new layout. I was unable to hide any of these.

![SmartSelect_20231019_001253_YT Extended](https://github.com/inotia00/ReVanced_Extended/assets/84587632/555a2402-1ad8-4786-8e78-887debb6559d)

### Steps to reproduce

1. Include the `Hide account menu` patch
2. Use an account that has the new layout (with the "You" page)
3. Try hiding the items using the account menu filter.

### Relevant log output

```shell
Can provide if needed
```

### Additional context

I wasn't sure if this is a bug or simply a feature depreciation since YouTube drastically changed app. It's not even an account menu anymore so I can't expect it to work.

### Device Environment

Android 13
OneUI 5.1
Non-root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
In the new layout, the components in the account menu have been moved to the `You tab`

Patch to hide the You tab component has not yet been implemented
