### ISSUE TITLE
suggestion(YouTube): Pluralize `Hide seek message` name and description

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1562]
### Application

YouTube

### Description

Now that the `Hide seek message` toggle hides multiple types of messages, the patch name, toggle label, and toggle description can be pluralized.

![SmartSelect_20231019_002530_YT Extended](https://github.com/inotia00/ReVanced_Extended/assets/84587632/ab5d17fc-bda2-43e0-81ce-5642e475dea7)

It would still be correct if it stays in singular form since only one message would be displayed, but I think the plural form is a slight improvement.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I will be applying this suggestion https://github.com/inotia00/ReVanced_Extended/issues/1566, so I will close this issue (To avoid duplication)
