### ISSUE TITLE
bug(youtube/spoof-player-parameter): Upcoming video with trailer don't have seekbar thumbnails

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#1564]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Youtube v18.39.41

### Bug description

Upcoming video with trailer don't have seekbar thumbnails

### Steps to reproduce

1. Open an upcoming video with Trailer
2. Seek the seekbar, no thumbnails showed

### Relevant log output

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
I will provide a fix for it soon

**Comment by inotia00** [comment]
Even if the issue is closed, please attach a link to a video that reproduces the issue

There is no need to open an issue in rare cases where the video is difficult to find

Spoof player parameter is `Experimental Flags`, and has already specified enough side effects
