### ISSUE TITLE
suggestion(YouTube): Split options

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1566]
### Application

YouTube

### Description

- Split `Disable undo haptic feedback` from `Disable seek haptic feedback`
- Split `Hide undo message` from `Hide seek message`

Because as you can see the `Undo` "feature" itself isn't disabled (it brings back the pointer of the seekbar at its initial point when swiping forward or backward), so those two options help to know where the "feature" finishes on the seekbar.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/c901c967-9dd0-4f11-964c-29af43fb120f

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This suggestion will be accepted, but there is one problem:

The problem with the `Hide seek undo message` patch is that it does not support all versions currently supported by RVX Patches

In the source code, `Seek undo message` was added in YouTube v18.29.38

Therefore, `Hide seek undo message`, `Disable undo haptic feedback` patches are not required in YouTube v18.24.37 ~ YouTube v18.27.36

There is a way to drop support for YouTube v18.27.36 and lower, but I'd like to avoid this if possible
(No A/B testing is applied to YouTube v18.27.36 or lower, so it is the most stable version)

So I will make sure not to add settings for `Hide seek undo message` and `Disable undo haptic feedback` in YouTube versions below v18.27.36

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
