### ISSUE TITLE
bug(YouTube/Hide shorts components): menu button is not hidden on tablets

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1567]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.24.37 ~ 18.39.41

### Bug description

On tablets menu toolbar button can't be hidden

### Steps to reproduce

1.Include `Hide shorts components` patch
2.Hide menu toolbar button
3(Optionally).Turn on tablet layout if you on phone

### Relevant log output

```shell
:/
```

### Screenshots or videos

![Screenshot_20231019_172815_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/267c801d-4f44-4dd9-9f77-483da9e57fbd)
![Screenshot_20231019_172824_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/fca18e0e-cee7-4e7b-835b-1e9f82f2124f)

### Solution

For this time i can only turn on phone layout(

### Device Environment

Galaxy Tab S6: Android 12, One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
