### ISSUE TITLE
bug(YouTube/Hide toolbar button): create button is not hidden on tablets

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1568]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.24.37 ~ 18.39.41

### Bug description

On tablets create toolbar button can't be hidden

### Steps to reproduce

1.Include `Hide toolbar button` patch
2.Switch navigation buttons
3.Hide toolbar button
4(Optionally).Turn on tablet layout if you on phone

### Relevant log output

```shell
:/
```

### Screenshots or videos

![Screenshot_20231019_173247_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/803c7f2a-f3c0-4c36-9f59-590b69a86597)
![Screenshot_20231019_173403_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/0df8e280-87b5-4e0f-ba99-524c1bfafb16)

### Solution

For this time i can only turn on phone layout(

### Additional context

Similarly as https://github.com/inotia00/ReVanced_Extended/issues/1567 bug can be reproduced on any phone just by turning on tablet layout

### Device Environment

Galaxy Tab S6: Android 12, One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Sam101011** [comment]
Having the same bug on my phone(Huawei P40 lite), so it's not tablet limited bug. Was gonna open an issue on my own(literally did the screen recording), but this one pretty much covers it.

From the testing I did, it looks like it's conflicting with the 'switch-create-notification' patch. If inotia decides my recording could be of any use, I'll open a seperate issue.

**Comment by inotia00** [comment]
Please upload screenshot

**Comment by Sam101011** [comment]
https://mega.nz/file/hWNF0AhI#fRWO4gS6ltbovrnfV3B2s9mFJfMN56dY7YHVb2ZTIIs

Providing mega link cuz GH doesn't allow uploads larger than 10mb

**Comment by inotia00** [comment]
> Providing mega link cuz GH doesn't allow uploads larger than 10mb

Create button is not hidden right?

**Comment by Sam101011** [comment]
>

> > Providing mega link cuz GH doesn't allow uploads larger than 10mb
> 
> Create button is not hidden right?

Yes, tho it looks like it gets hidden for a brief moment, before showing up again.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
