### ISSUE TITLE
bug (YouTube/Hide player flyout panel): If any component belonging to `Additional settings` is hidden, the entire `Additional settings` menu is hidden

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#1569]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

**`YT Version`**: **18.39.41**
**`Patches version`**: **2.193.18**

### Bug description

When I set anything in the player flyout menu, when I fire up the menu afterwards, the additional options tab disappears, which contains the video loop I need.
It is very interesting to note, as you will see in the two videos below in the steps to retroduce section, that the problem occurs in my native Polish language. In English, everything works fine. So the problem may not only relate to my language.

I have no idea if it's a fault on the part of YT or RVX, but the extra settings tab was missing at least the `Stats for nerds`, `Watch in VR`, and the new `Stable volume` option.

### Steps to reproduce

PART 1, where I'm changing settings in English: https://cdn.discordapp.com/attachments/1162123693644853402/1164586440282341497/RVX-Flyout-ENG.mp4?ex=6543c0a4&is=65314ba4&hm=185b6963429e3bbe1414bf76d33642ab6563de2116a3e4f20829882a674c17fb&

PART 2, where I'm changing setting in Polish:
https://cdn.discordapp.com/attachments/1162123693644853402/1164586441658093768/RVX-Flyout-POL.mp4?ex=6543c0a4&is=65314ba4&hm=6d5d1b9efbf7d4b37bdd7e89de381152a73d9a77ff779d096dc15609918fc9bd&
*I changed premium controls and stable volume settings*

Unfortunately via Discord due to GitHub's file size restrictions. And I don't want to lose video quality to be able to see anything.

### Relevant log output

```shell
My log are videos above
```

### Screenshots or videos

In steps to reproduce.

### Device Environment

**`Device`**: **HUAWEI JNY-LX1**
**`Android version`**: **10**
**`System version`**: **EMUI 12, 12.0.0.285**

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
I don't think it's a language related issue.
When an issue occurs, just open and close ReVanced Settings once.

Then restart the app and check the flyout panel again.

**Comment by Mhmodhaha** [comment]
For me ,Additional setting is at video flyout menu when opening video but after the video play it dispears. I was going to send this issue.

**Comment by GucekPL** [comment]
I'm sure that's the same case

**Comment by Mhmodhaha** [comment]
But this appears in the new layout which I think is not permanent cuz now on my pjone the old layout of returned and all settings work normally.

**Comment by inotia00** [comment]
nvm I checked the source code and it was my fault

**Comment by eldepor** [comment]
> But this appears in the new layout which I think is not permanent cuz now on my phone the old layout of returned and all settings work normally. Update: the new layout returned again and the same issue appears so I don't why the layout changes on its own?

I was using the app normally and experienced the issue with the Flyout menu, then suddenly a message announcing a new "You" tab and other stuff popped up and the layout changed, that's the first time I see it, but the problem remained in that layout too.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)

**Comment by eldepor** [comment]
I think I´m still having this issue. Cant see the additional options like lock screen, ambient mode, more info or stable volume despite having them enabled in the flyout menu settings. I also can´t get the new "You" new layout, if this is related to the issue.
Tested in 18.40.34 and 18.39.41

![image](https://github.com/inotia00/ReVanced_Extended/assets/19383172/6149e4e7-24ca-4970-af06-85a27ceaab76)
![image](https://github.com/inotia00/ReVanced_Extended/assets/19383172/f22440cd-2c6b-4e19-a3ca-dcc8b6be1d18)

**Comment by inotia00** [comment]
nah this is A/B tests

If the new layout has not been applied to your account, it is normal for Additional settings to not be added

**Comment by eldepor** [comment]
Hmm I do get it in RV tho.
