### ISSUE TITLE
bug: Screen Rotation freeze 

### ISSUE THREAD

**Issue by Eu69** [inotia00/ReVanced_Extended#157]
### Type

Error while patching

### Application

YOUTUBE 18.01.38

### Bug description

I'm using YouTube Advanced 17.03.38 so far. I have an app to control the screen rotation only for that YouTube so I don't have to turn on that setting all the time on my phone and affect all apps. So it affects only YouTube. It works very well and even when my phone is on portrait position i can swipe up on the video screen and it will turn on full screen Keeping the video on portrait mode. That said, I decided not to upgrade to YouTube 18.01.38 because by using the same functions, the screen freezes and does not reach the full screen. The thing is that when I install the last YouTube the whole rotation system works great at first. But if I go to the settings to change anything and make the app restart, it automatically actives the environment mode for example(it's never visible at the first time after installing the YouTube) and the full screen function always freezes. The problem is not the screen rotation app because it works great on the old version of YouTube. And I tried many others and the bug it's all the same. I would like to update to the last version but with that bug it's complicated. Do you know how to fix this? It's odd because the old YouTube Vanced works pretty well. Thanks 

### Steps to reproduce

1. After the installation the rotation screen works 100 % with the 3d party app.
2. When I change any settings and after the app restarts, i noticed that the environment mode appears and the rotation freezes.
3. Even when I shut down the environment mode the rotation bug will not disappear.
4. I have to reboot the app and I can't change any setting because it will make the app restart and the bug will appear again. 

### Relevant log output

```shell
Don't have any
```

### Screenshots or videos

Here is the video link:

https://mega.nz/file/cpsAEA4K#8KKq-XIcwWGg5m5Pa_3zXTFOvKD7jI3pBZ0ZxIlpZwI

### Solution

I only know that the version 17.03.38 works very well 

### Device Environment

Oneplus 7 pro Android 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Is this bug still present or is it resolved?

**Comment by Eu69** [comment]
Still present. Reminder: this is happening with the using of any Rotation Control app. Revanced is working very well in general.
