### ISSUE TITLE
Library page is not showing history

### ISSUE THREAD

**Issue by HauntedKnives** [inotia00/ReVanced_Extended#1571]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube 18.39.41

### Bug description

The library page doesn't show watch history. It shows the button to go to history but not showing history in the library page itself. Usually, the library page shows menu on the left side and watch history on the right side. Also, the YouTube or Premium logo is also disappeared.

### Steps to reproduce

Open library page

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20231020_003820_RVX Test](https://github.com/inotia00/ReVanced_Extended/assets/114818096/4a7fca35-a6ea-4e94-a2c0-e568f1549ae4)

### Device Environment

Android 13, OneUI 5.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
This is not related to rvx and not a bug, this is just youtube tablet layout, please close issue
