### ISSUE TITLE
bug(YouTube/Enable wide search bar): wide search bar does not apply to `You` tab

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1572]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube 18.29.38 ~ 18.39.41 (if i right these versions affected by new layout)

### Bug description

Wide search bar not work in "My Tab"

https://github.com/inotia00/ReVanced_Extended/assets/110785596/4adc8948-6989-4fb7-b3f6-fe55c5c7eed5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
