### ISSUE TITLE
bug(YouTube/Hide layout components): `Hide official header` doesn't work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1573]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.39.41
Patches v2.193.18

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/ab6fddc6-b27f-4f41-8ca1-c07108f085a3

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It does not reproduce on my side

**Comment by inotia00** [comment]
I was able to reproduce the issue while switching accounts.
This is A/B test

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
