### ISSUE TITLE
suggestion(YouTube/Disable speed overlay): change string revanced_edit_speed_overlay_value_summary to match google changes

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1575]
### Application

YouTube

### Description

Change string revanced_edit_speed_overlay_value_summary to match google changes, some time ago speed overlay was an ab test only for a little % of accounts, but today when google officially rollead out all new layout including speed overlay it nomore test.
Change string from this:
Edit speed that changes while holding down
Only available to some users who can use the speed overlay
To this:
Edit speed that changes while holding down

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Custom speed overlay` patch will be removed in the next release

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
