### ISSUE TITLE
bug (YouTube): `Hide account menus` doesn't work with new UI

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1576]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube v18.39.41
Patches v2.193.18

### Bug description

With the new UI it seems likes `Hide account menus` doesn't work anymore.

![ _20231019_222731](https://github.com/inotia00/ReVanced_Extended/assets/127908708/b3952601-d9ef-42b1-8aa6-8a4ea724234d)
![_Oct192023_222209](https://github.com/inotia00/ReVanced_Extended/assets/127908708/5a52b94e-d172-45d8-b7a2-b51e52c670fe)

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1561#issuecomment-1769873477
