### ISSUE TITLE
question(YouTube): google rolled out language switch option, what you will do with patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1577]
### Application

YouTube

### Description

Google rolled out language switch option, what you will do with patch. With new layout they added this feature. I think that after this new layout you will need to drop support for versions that not affected by new layout

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please refer to previous release notes

https://github.com/inotia00/revanced-patches/releases/tag/v2.193.12

![releases](https://github.com/inotia00/ReVanced_Extended/assets/108592928/55fe1e4d-5ee1-4c41-90c0-08fb86c563a1)
