### ISSUE TITLE
suggestion(YouTube): do some changes in `Enable new thumbnail`, `Enable new comment popup panels`, `Enable new splash animation`  patches

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1578]
### Application

YouTube

### Description

Do some changes in `Enable new thumbnail`, `Enable new comment popup panels`, `Enable new splash animation`  google rolled out officially these features, i think that you need to do changes like it was:
`Enable new thumbnail preview` Enables a new type of thumbnail preview.
`Enable new comment popup panels` Enables a new type of comment popup panel in the shorts player.
`Enable new splash animation` Enables a new type of splash animation.
Now it need to look like:
`Disable new thumbnail preview` Disables a new type of thumbnail preview.
`Disable new comment popup panels` Disables a new type of comment popup panel in the shorts player.
`Disable new splash animation` Disables a new type of splash animation.
And of coarse some changes in patches themselves

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is still the realm of A/B testing, and I don't think everyone will be able to access this feature without the patch, even on YouTube v18.24.37, which is the lowest version supported by the patch

**Comment by girshcatt** [comment]
Ok, if you want to continue support for old layout versions you have two ways: stay issue open before you will drop support for versions with old layout
Or you can close issue and just keep this in mind

**Comment by inotia00** [comment]
I will reopen when I drop support for YouTube v18.24.37 ~ YouTube v18.27.36
