### ISSUE TITLE
bug(YouTube): `Open library on app startup` doesn't work in new "You" tab

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1579]
### Type

Error at runtime

### Tools used

Revancify

### Application

YT 18.39.41

### Bug description

The `Open library on app startup` feature (in the Navigation settings) doesn't work for the new "You" tab.

### Steps to reproduce

1. Settings > Revanced Extended > Navigation > Open library on app startup, `On`
2. Restart the app and see that the "You" tab isn't opened.

### Relevant log output

```shell
NA
```

### Solution

I'm guessing this may need a new patch just like how the `Hide account menu` would need one. 

### Additional context

I'm guessing this may need a new patch just like how the `Hide account menu` would need one. I dont mean to request a new patch.

### Device Environment

Android 13
OneUI 5.1
Non root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Simple. `You` tab is not the `Library` tab
