### ISSUE TITLE
bug: default video speed is not working

### ISSUE THREAD

**Issue by chitranshnehra** [inotia00/ReVanced_Extended#158]
### Type

Error at runtime

### Application

YouTube v18.01.36

### Bug description

Default speed set to 1.5x but video play at 1x only

### Steps to reproduce

Include default video speed
Set it greater than 1
Not working

### Relevant log output

```shell
Sometimes works something don't
```

### Device Environment

Miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.156.1
