### ISSUE TITLE
bug (YouTube): Disabling `Hide feed flyout menu` also hides `Additional settings`

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1580]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube v18.39.41
Patches v2.193.18

### Bug description

![ _20231019_235412](https://github.com/inotia00/ReVanced_Extended/assets/127908708/698710fb-757a-40ac-b81e-9cf8efcd7c51)

**Which contains:**
![Screenshot_20231019_235114_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/0582f5b0-2fa3-452d-993f-e8c2c78e30c1)

**With the new UI, enabling `Hide feed flyout menu` also hides `Additional settings`**
![Screenshot_20231019_234941_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/1f2b7ecb-6f61-4b59-adff-b26e0c1bd76b)

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1569
