### ISSUE TITLE
suggestion(YouTube/Force video codec): separate the patch that spoofs device dimensions from the `Force video codec` patch

### ISSUE THREAD

**Issue by eldepor** [inotia00/ReVanced_Extended#1582]
### Application

YouTube

### Description

Any chance of including [this new patch](https://github.com/ReVanced/revanced-patches/commit/c8d409e1dbda6ac45fef01912ce7afad1022b4b
)? It solves the issue described in my comments [here](https://github.com/ReVanced/revanced-patches/issues/1721#issuecomment-1769498249), [here](https://github.com/ReVanced/revanced-patches/issues/1721#issuecomment-1770100593) and [here](https://github.com/ReVanced/revanced-patches/issues/1721#issuecomment-1770443402). Force codec patch does not solve it.

Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Already exists in RVX patch
The `Force video codec` patch does the same thing

**Comment by eldepor** [comment]
It doesn't, as I explained in detail above. Force video codec patch just "unlocks" higher resolutions not shown by default, but it doesn't prevent the quality drop issue I mentioned in the thread, please read it if you don't mind.

Check this video, look stats and quality menu marked with the red rectangle.

https://github.com/inotia00/ReVanced_Extended/assets/19383172/77b953a1-0cab-40e9-8d8d-48c72c9e848e

This doesnt happen with spoof device dimensions patch, stays in 1080p60

https://github.com/inotia00/ReVanced_Extended/assets/19383172/ee9ce379-3308-40ba-85f0-9a81f212392c

**Comment by inotia00** [comment]
The `Force video codec` patch also has the same function, but the `Force video codec` patch not only spoofs the dimensions, but also spoofs the model name and manufacturer.

This is probably the cause of the issue

It seems more appropriate to remove the part that spoofs dimensions from the `Force video codec` patch and separate it into the `Spoof device dimensions` patch.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)

**Comment by eldepor** [comment]
Thanks man for the separate patches, looks like issue is solved.
