### ISSUE TITLE
[Bug] Settings - General - Hide the latest video at the top of the feed does not work.

### ISSUE THREAD

**Issue by root-kernelhacker** [inotia00/ReVanced_Extended#1583]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

YouTube 18.39.41
Patches-2.193.18
Integrations-0.119.18

### Bug description

YouTube 18.39.41
Patches-2.193.18
Integrations-0.119.18

[Bug] Settings - General - Hide the latest video at the top of the feed does not work.

There is no change even if you set it as above or turn it off.

(The latest video button is exposed as is)

### Steps to reproduce

YouTube 18.39.41
Patches-2.193.18
Integrations-0.119.18

[Bug] Settings - General - Hide the latest video at the top of the feed does not work.

There is no change even if you set it as above or turn it off.

(The latest video button is exposed as is)

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
attach screenshot

**Comment by inotia00** [comment]
Please reopen the issue when a screenshot and the appropriate issue reproduction process have been added
