### ISSUE TITLE
How to change/turn off colors on right or left Video's when the video is in full screen mode 

### ISSUE THREAD

**Issue by TheKingTermux** [inotia00/ReVanced_Extended#1584]
### Application

YouTube

### Description

![IMG_20231020_170621](https://github.com/inotia00/ReVanced_Extended/assets/50316075/119b6084-aba3-41fa-9494-f7140f0e252a)

![IMG_20231020_171148](https://github.com/inotia00/ReVanced_Extended/assets/50316075/bd1735c7-4720-4d1b-9c78-5c5d381f2767)

In this image, when the video is in full screen mode there is a color on the right / left of the video (because the video may be too small on my cellphone) that is colored maybe towards gray. I want to change the color to black. Because sometimes it's annoying when the video uses a black background too, so it looks like it's cut off or something. Is it possible or a server side one?
Sorry if this question might be a little funny, because I just yesterday updated YouTube from V18.30.xx to V18.39.xx

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Looks like YouTube's new A/B tests

The only way to revert this is to re-patch to a sufficiently low version that RVX Patches currently supports (YouTube v18.24.37 ~ YouTube v18.39.41)

Personally, the version I recommend among the older versions is YouTube v18.33.40

**Comment by TheKingTermux** [comment]
> Looks like YouTube's new A/B tests

So it's a server side feature, now I understand

> Personally, the version I recommend among the older versions is YouTube v18.33.40

OK, thanks for the answer

**Comment by TheKingTermux** [comment]
> If you disable Ambient mode it will go away. To disable it, you may first need to unhide the Ambient mode option in Settings > Revanced Extended > Flyout menu
> 
> Then tap the gear button in the video player > Additional settings, Off.

Ohh thanks
I Will check it
