### ISSUE TITLE
bug: <Swipe-Controls> ``Enable auto-brightness by swiping`` not working properly

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1585]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube 18.39.41

### Bug description

Don't know how to explain/show this but when enabling auto-brightness by using swipe controls when full-screen on a video doesn't enables auto brightness or auto brightness doesn't work no matter how dark or bright environment I'm in.

### Steps to reproduce

1. Patch YouTube with swipe controls patch normally
2. Enable swipe controls and enable auto brightness by swiping option
3. Watch any video in full screen and swipe down till auto brightness pop up is triggered
4. Go to any dark or light environment and check if it works or not.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

N/A

### Solution

Fixing auto brightness while in full screen

### Additional context

Using Xiaomi 11T pro phone if that helps.

### Device Environment

Android 13, MIUI 14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`Auto brightness` in swipe controls is different from `Auto brightness` provided by System UI

It is an option to use the brightness used before entering fullscreen, not an option to change the brightness in real-time like `Auto brightness` provided by the System UI

**Comment by Rairof** [comment]
Oh I see, thought it adjusted brightness based on external environment. Thank you for clearing the confusion.
