### ISSUE TITLE
suggestion(YouTube/Hide suggestions shelf): "Listen again" section not marked in description

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1586]
### Application

YouTube

### Description

![Screenshot_20231020_135319_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/cb490293-a240-4010-aa68-529dfbc2ab4d)
"Listen again" section not marked in description, change revanced_hide_suggestions_shelf_summary string
From this:
Hides following shelves:
- Breaking news
- Continue watching
- Explore more channels
- Shopping
- Watch it Again
To this:
Hides following shelves:
- Breaking news
- Continue watching
- Explore more channels
- Shopping
- Watch it Again
- Listen again

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
