### ISSUE TITLE
bug: <Live's doesn't works>

### ISSUE THREAD

**Issue by nightznero** [inotia00/ReVanced_Extended#1587]
### Type

Error at using RVX

### Tools used

rvx-builder

### Application

18.39.41 (lower also)

### Bug description

Lives doesnt load up(case only about **LIVES!** movies works flawless),after 5-10s (look at screen) loads comments,channel,desc but player...never. I have enabled spoofs parameters,on RV(18.32.39) works normally,was resetted almost every single option but nothing changed at all,reinstalled with cleaned memeory before,didn't help.
I know 1 or 2 things about reverse engineering so advice about reinstall will not help,if there is any more info i can provide to help me fix that issue i m up to share anything if necessary

### Steps to reproduce

Just open a live

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20231020_164718](https://github.com/inotia00/ReVanced_Extended/assets/61750641/5febaafd-b424-4e65-a1b0-455f68c27676)
![Screenshot_20231020_165713](https://github.com/inotia00/ReVanced_Extended/assets/61750641/a462b59e-5c33-4d6e-8735-c5f1d1db8fd3)
![Screenshot_20231020_165724](https://github.com/inotia00/ReVanced_Extended/assets/61750641/75b99098-245c-4149-8813-cda9dc2d9108)
![Screenshot_20231020_165637](https://github.com/inotia00/ReVanced_Extended/assets/61750641/12547852-a6d9-4deb-8fa1-d00acc40af3b)

### Device Environment

A 13 OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It does not reproduce on my side

Please leave the results for each of the following cases:
1. When playing the same video on stock YouTube
2. When playing after disabling `Spoof player parameter` in RVX
3. When playing after disabling ‘Return YouTube Dislike’ in RVX

**Comment by nightznero** [comment]
> It does not reproduce on my side
> 
I have heard that its "only me" issue damn.

> Please leave the results for each of the following cases:
> 
> 1. When playing the same video on stock YouTube
> 2. When playing the same video after disabling `Spoof player parameter` in RVX
> 3. When playing the same video after disabling `Return YouTube Dislike` in RVX
> 4. When playing the same video in Incognito Mode in RVX
> 5. When playing the same video on RVX while using VPN

1. Works normally on old version as on the newest
2. Not working,tested with enabled and disabled: `Spoof player parameter` , `Spoof player parameter in feed` , `skip preloaded buffer` (just in case) - still nothing
3. Not working
4. Not working either
5. With and without VPN same results as above for every mentioned way,here also not working

**Comment by inotia00** [comment]
Exclude all patches and only include the `MicroG Support` patch and test for playback issues

**Comment by nightznero** [comment]
> Exclude all patches and only include the `MicroG Support` patch and test for playback issues

Damn xD
Must sorry You Inotia for bothering with pointless "issue". After Installing with `MicroG Support` i noticed everything works flawless and i solo made that issue with my polishing `.dex` files,RV and RVX is not perfect and after patching i clean apk from usuless pings to `adclick` and so on.
![Screenshot_20231020_201157_MT Manager](https://github.com/inotia00/ReVanced_Extended/assets/61750641/b8e3fb1d-fa13-4f10-88d2-315aad9187e5)
After looking i wrongly has made changes in dex files.
Feel free to close the issue and once again,sorry for bothering Ino!
