### ISSUE TITLE
Replace YouTube's Downloads page with external downloader's downloads page within YouTube

### ISSUE THREAD

**Issue by HauntedKnives** [inotia00/ReVanced_Extended#1588]
### Application

YouTube

### Description

Replace YouTube's existing Downloads page with a page that shows all downloads of external downloader. So that we can open the downloaded videos from YouTube itself.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I do not accept new feature requests for YouTube.
