### ISSUE TITLE
bug(YouTube/Default video quality): video quality toast shows wrong quality value

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1589]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.29.38

### Bug description

Defalut video quality shows wrong quality value, i just suddenly found this bug in one video, then it reproduces the same way on all my devices

### Steps to reproduce

Go to https://youtu.be/rwz2nWDrVv0?si=SuJX5Fc6ep21fhP_ video and change quality to 1080p, youtube toast will show that you changed quality on 1080, but defalut quality toast will show toast with 1440p

### Relevant log output

```shell
:/
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/110785596/39079225-cf69-45a3-b54c-82c9d1d66dfe

### Additional context

Maybe my settings file will help if you cant reproduce it
[ReVanced Extended_v18.29.38_2023-10-19.json](https://github.com/inotia00/ReVanced_Extended/files/13055850/ReVanced.Extended_v18.29.38_2023-10-19.json)

### Device Environment

Android 12 One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This issue can be fixed, but there will be a 0.3 second delay before the video quality toast message is shown.

I think it is better for the toast message to be shown 0.3 seconds later than not to fix the bug.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
