### ISSUE TITLE
bug: double tap to seek forward doesn't work if player controller is not visible

### ISSUE THREAD

**Issue by jackblk** [inotia00/ReVanced_Extended#159]
### Type

Other

### Application

* Youtube 17.49.37
* Revanced Extended patches: 2.153.6
* Integrations: 0.92.6

### Bug description

Unable to double tap to seek forward when the player is not visible & the volume swipe feature is disabled.

### Steps to reproduce

* Include all recommended patches
* Disable volume swipe gesture
* Exit & refresh the app
* Open any video in full screen, player not visible.
* Double tap the right portion of the screen

Expected: able to seek forward

Observed: nothing happens.

* If volume swipe gesture is enabled: can double tap
* Double tap the left portion for rewind will work when brightness swipe gesture is enabled or not (fixed before) in #133 

### Relevant log output

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Yamraaz** [comment]
Hi.. I am facing same issue.. Did you got any solution?

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.156.1

**Comment by jackblk** [comment]
Can confirm this is fixed. But it caused #176
