### ISSUE TITLE
suggestion: Play next video in channel

### ISSUE THREAD

**Issue by eng3** [inotia00/ReVanced_Extended#1590]
### Application

YouTube

### Description

Sometimes I want to watch all the videos in a channel.  However, it plays them in reverse order (newest to oldest).
Sometimes, for some reason the next video is often picked at random "or suggested".  Not sure why this happens.
In both cases, I must go back and manually click on the next video.
Is there a way to patch to have an option to play the next (newer) video in the same channel?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
There's no option for this. You can try finding mix playlists or regular playlists for the channel
