### ISSUE TITLE
question(YouTube): where i can find save to playlist and open playlist buttons?

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1591]
### Application

YouTube

### Description

Where i can find save to playlist and open playlist buttons? I just need this to translate all propely, sorry for question 😅

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![PLAYLIST_1](https://github.com/inotia00/ReVanced_Extended/assets/108592928/bbffb573-8a66-4bd8-b234-8d3595c66a85)
![PLAYLIST_2](https://github.com/inotia00/ReVanced_Extended/assets/108592928/58d67dcf-9644-478a-ad3e-22f83f0435dc)

Red: `Save to playlist`
Blue: `Open playlist`

In the case of the blue button, you can check it by entering fullscreen when playing a video in the Playlist (in stock YouTube)

**Comment by inotia00** [comment]
![MIX_PLAYLIST_1](https://github.com/inotia00/ReVanced_Extended/assets/108592928/8e51f3a1-e43c-4db1-9ed7-1a4e66161ee9)

Button that appears when playing a video in mix playlist will also be hidden

I think it might be `Hide open mix playlist button`
