### ISSUE TITLE
Tap to swipe Left/Right Not skipping video

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1592]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.39.41

### Bug description

Tap YouTube video player & swipe left/right.But video is now skipping.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Solution

N/A

### Additional context

N/A

### Device Environment

Android 12 MIUI 13 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1574
