### ISSUE TITLE
Slide Left or Right to seek Not working 

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1594]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v18.39.41

### Bug description

Holding and sliding right and left doesn't move the seekbar pointer anymore

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-10-21-01-21-00-289_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/117540245/42c21f90-7f05-4bec-b495-c0e5d3c0e8a1)

### Device Environment

Android 12 MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Why do you keep opening duplicate issues?

**Comment by Mehedi5585** [comment]
> Why do you keep opening duplicate issues?

What do you think this is a duplicate issue bro.

**Comment by inotia00** [comment]
You already opened the [same issue](https://github.com/inotia00/ReVanced_Extended/issues/1592) an hour ago, and the issue has already been closed because a [duplicate issue](https://github.com/inotia00/ReVanced_Extended/issues/1574) exists.

Why are you reopening a duplicate issue anyway?

**Comment by inotia00** [comment]
If you open a duplicate issue, you will be sending unnecessary email notifications to the original issue opener, commenters on the original issue, ReVanced Extended repo collaborators, and maintainers.

You didn't search enough for duplicate issues, and you opened a duplicate issue twice.

If you repeat this spamming behavior without a valid reason, I will have no choice but to block you from all my Githubs.

**Comment by Mehedi5585** [comment]
> If you open a duplicate issue, you will be sending unnecessary email notifications to the original issue opener, commenters on the original issue, ReVanced Extended repo collaborators, and maintainers.
> 
> You didn't search enough for duplicate issues, and you opened a duplicate issue twice.
> 
> If you repeat this spamming behavior without a valid reason, I will have no choice but to block you from all my Github repos.

I don't understand brother, actually I don't understand English very well, if I make a mistake, you will see it in the eyes of forgiveness.  I don't understand that it can't be done in seconds.  I am really very sorry.
