### ISSUE TITLE
bug(YouTube): Quality menu is missing from player flyout panel 

### ISSUE THREAD

**Issue by eqlivox** [inotia00/ReVanced_Extended#1595]
### Type

Other

### Tools used

ReVanced Manager

### Application

Patched YouTube v18.39.41

### Bug description

If spoof app version is enabled in settings, quality menu is missing from player flyout panel.

### Steps to reproduce

Step 1. Enable spoof app version (any version) in app settings 
Step 2. Go to any video and open player flyout panel 

### Relevant log output

```shell
No
```

### Solution

Disable spoof app version in settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
1. Spoof app version is `Experimental Flags`, so using Spoof app version may not be compatible with all patches.
2. This is a duplicate issue. https://github.com/inotia00/ReVanced_Extended/issues/1569
