### ISSUE TITLE
bug(YouTube/Hide latest videos button): latest videos not hidden on tablets

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1596]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.29.38

### Bug description

Latest videos not hidden on tablets, i think that this happens because of different look
1.Phones
![Screenshot_20231021_004237_Gallery](https://github.com/inotia00/ReVanced_Extended/assets/110785596/b2544ebd-e068-4a53-9811-370c5b21cc2c)
2.Tablets
![Screenshot_20231021_002244_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/110785596/c2b64039-bad2-445c-9536-966542d7319c)

### Steps to reproduce

1.Include `Hide latest videos`
2.Patch 18.29.38, maybe any other supported version idk
3.Turn on "Hide latest videos"

### Relevant log output

```shell
:/
```

### Additional context

Maybe it reproducable by activating of tablet ui on any phone 
My settings:
[ReVanced Extended_v18.29.38_2023-10-19.json](https://github.com/inotia00/ReVanced_Extended/files/13058818/ReVanced.Extended_v18.29.38_2023-10-19.json)

### Device Environment

Galaxy Tab S6: Android 12 One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Like the `Hide Mix Playlist` patch, it doesn't seem to be available on tablets

In the next release I will disable the `Hide latest videos` setting on tablets

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
