### ISSUE TITLE
bug: Back Button not hiding in Shorts.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1597]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

YouTube v18.40.34
inotia00 patches v2.195.1

### Bug description

I've enabled all hiding settings from Shorts folder.
But still the back button is remaining.
![Back Button](https://github.com/inotia00/ReVanced_Extended/assets/91815107/300c0e10-f7dd-4c0a-a124-0ef65cc641b3)
![Shorts Settings](https://github.com/inotia00/ReVanced_Extended/assets/91815107/3e75081c-2808-4321-94af-318a2d9d08c8)

### Steps to reproduce

Please check above screenshots.

### Relevant log output

```shell
No logs.
```

### Screenshots or videos

Given above.

### Solution

No response.

### Additional context

No response.

### Device Environment

Realme 7 Pro, Android 12 (RUI 3.0).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
What does it mean?
There is no `Hide back button` setting

**Comment by Aryan-Chauhan** [comment]
> What does it mean?
> There is no `Hide back button` setting

Any plans regarding adding it?

**Comment by Kuddus73** [comment]
> What does it mean? There is no `Hide back button` setting

Before you could only hide the entire top toolbar of Shorts player and by hiding that, it also hid the Back button.
It stopped hiding it from patches v2.193.18 when `Hide toolbar button patch` was added.
