### ISSUE TITLE
bug(Hide suggestions shelf): in old layout on tablets much black space appears

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1598]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.24.37 ~ 18.40.34

### Bug description

in old layout on tablets much black space appears

https://github.com/inotia00/ReVanced_Extended/assets/110785596/11db44dd-769a-4378-81cf-09a651956412

### Steps to reproduce

1.Include `Hide suggestions shelf` patch
2.Patch 18.24.37 ~ 18.40.34
3.Turn on hide suggestions shelf

### Relevant log output

```shell
:/
```

### Additional context

My settings:
[ReVanced Extended_v18.40.34_2023-10-21.json](https://github.com/inotia00/ReVanced_Extended/files/13060556/ReVanced.Extended_v18.40.34_2023-10-21.json)
To reproduce all on phone just turn on tablet layout

https://github.com/inotia00/ReVanced_Extended/assets/110785596/248bfcc3-a225-4618-b459-ab87f809e67f

### Device Environment

Galaxy Tab S6: Android 12 One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
Also i forgot to say that if u have new layout bug will be fixed

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.195.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.4)
