### ISSUE TITLE
bug: can't patch apps after latest RVX update

### ISSUE THREAD

**Issue by DiofyZz** [inotia00/ReVanced_Extended#1599]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YT 18.40.34, YTM 6.23.54, RVX manager 1.13.1, RVX patches 2.195.1

### Bug description

Select application menu in patcher shows nothing after latest update, when trying to patch downloaded apk patch selector menu is also blank.

### Steps to reproduce

1. Update RVX manager and patches to latest version
2. Open app selector in patcher tab

### Relevant log output

```shell
n/a
```

### Screenshots or videos

https://photos.app.goo.gl/XhJtemmVEimiYWWw5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Please update to [RVX Manager v1.14.2](https://github.com/inotia00/revanced-manager/releases/tag/v1.14.2) and try again using **mobile network**
