### ISSUE TITLE
feat(patch): Unlock 4k video quality

### ISSUE THREAD

**Issue by Pratyay360** [inotia00/ReVanced_Extended#16]
### Application

It's for 4k playback of youtube videos on all android phone.

### Issue

ie. snapdragon 680 don't have 4k video playback on youtube natively previously youtube vanced used to have this feature.

### Patch

any patch to tweak user agent for 4k playback 

### Motivation

this will be beneficial for playback of 4k videos on patched youtube app  

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please edit the title appropriately

**Comment by venkat2305** [comment]
Can snapdragon 680 handle 4k videos?

**Comment by Pratyay360** [comment]
@venkat2305  there was option of 4k in youtube vanced it's not available on revanced. one can  spoof device name in vanced but it's not the case in youtube app patched by revanced.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
