### ISSUE TITLE
question: <buffering>: 

### ISSUE THREAD

**Issue by zharxr** [inotia00/ReVanced_Extended#160]
### Application

YouTube

### Description

my internet is normal, but i can't play anything videos on my youtube revanced. It's just buffering. how to fix it? should i reset the micro G?
![Screenshot_2023-01-19-12-35-16-01_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/123052152/213364093-48764b75-5bf0-493d-a3fd-6df22e89872d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Melontune** [comment]
I've also been having this issue

**Comment by nikhilbadyal** [comment]
Microg issue

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/141
