### ISSUE TITLE
bug(YouTube): after "Hide toolbar button" patch can't hide short back button anymore

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1600]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube 18.37.36 and patches 2.193.15
YouTube 18.40.34 and patches 2.195.1

### Bug description

With the removal of the "**Hide toolbar**" patch and the addition of the "**Hide toolbar button**" patch it is no longer possible to hide the back button inside the short player

### On YouTube 18.37.36 and patches 2.193.15:
![ _20231021_145411](https://github.com/inotia00/ReVanced_Extended/assets/130296934/3de259c2-078a-4e80-8900-edd96037b915)
### On YouTube 18.40.34 and patches 2.195.1:
![ _20231021_145500](https://github.com/inotia00/ReVanced_Extended/assets/130296934/ea73deb3-70b4-4447-a135-691e94a9dcbe)

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
Duplicate of https://github.com/inotia00/ReVanced_Extended/issues/1597, close the issue

**Comment by federicogith** [comment]
But that one is closed too

It removed an implemented feature
Shouldn't this be considered a bug?

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.4)
