### ISSUE TITLE
bug(YouTube): "Hide official header" doesn't work anymore

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1603]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.41.39
Patches v2.195.6

### Bug description

The header doesn't get hidden anymore.
![Screenshot_20231028_073728_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/60bd95e1-0550-42a2-ab7f-60eb6ac604f0)

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`Hide official header` setting was removed in revanced-patches-v2.195.4

**Comment by Kuddus73** [comment]
I know that we can't ask for new features, but this one is not new.
Can you please add it back?

**Comment by inotia00** [comment]
It was removed because it no longer works in YouTube v18.41.39+

Even if you're using a version older than YouTube v18.41.39, it won't work for accounts with A/B testing applied

It wasn't removed for no reason

**Comment by federicogith** [comment]
> It was removed because it no longer works in YouTube v18.41.39+
> 
> Even if you're using a version older than YouTube v18.41.39, it won't work for accounts with A/B testing applied

Now hiding Shorts shelf also hides official header as a side effect

(I might be saying a nonsense but)
Wouldn't be possible to split that and makes it hide only official header?

**Comment by inotia00** [comment]
nah if i could do that i would have done it already

since I couldn't split these two settings in any method, I had no choice but to mention it as a side effect

**Comment by ILoveOpenSourceApplications** [comment]
@inotia00, now the header can be hidden with `compact_channel.eml` and the side effect of hide shorts shelf can be removed as well.

```kotlin
08-28 22:20:00.593 14729 14903 D Extended: LithoFilterPatch: Path: compact_channel.eml|6c4085e4a91446e6|CellType|
08-28 22:20:00.593 14729 14903 D Extended: LithoFilterPatch: BufferStrings: Key_SubscribeButtonWithControllerΓ¥Ösubscribe_button.eml|444c9d2c3a21db6Γ¥ÖKey_SubscribeButtonWithControllerΓ¥Ösubscribe_button.eml|444c9d2c3a21db6Γ¥Ö19.3M subscribers Γ¥Ö 1.6K videosΓ¥Ösans-serifΓ¥Ö@mkbhd Γ¥Ö American YouTuberΓ¥Ösans-serifΓ¥ÖMarques BrownleeΓ¥Ösans-serifΓ¥Öavatar.eml|ce2c7710a968513fΓ¥ÖGaO14Γ¥Ö1724863800110287648Γ¥Öcompact_channel.eml|6c4085e4a91446e6Γ¥Öeml.compact_channelΓ¥ÖUCBJycsmduvYEL83R_U4JriQ"Γ¥Ö/@mkbhd|Γ¥Ö
```

**Comment by inotia00** [comment]
> @inotia00, now the header can be hidden with `compact_channel.eml` and the side effect of hide shorts shelf can be removed as well.
> 
> ```kotlin
> 08-28 22:20:00.593 14729 14903 D Extended: LithoFilterPatch: Path: compact_channel.eml|6c4085e4a91446e6|CellType|
> 08-28 22:20:00.593 14729 14903 D Extended: LithoFilterPatch: BufferStrings: Key_Subscribe
> ```

It's most likely A/B tests

I can't hide the header of search results with the keyword `compact_channel.eml` in any of my Google accounts

**Comment by ILoveOpenSourceApplications** [comment]
This is how the header looks currently:
![Screenshot_20240828_233918_YouTube](https://github.com/user-attachments/assets/6e385223-ae5e-45dd-859a-e335422c834e)

**Comment by inotia00** [comment]
It still shows like this to me:

![278795989-60bd95e1-0550-42a2-ab7f-60eb6ac604f0](https://github.com/user-attachments/assets/f1a69ea2-1c7d-4907-bfce-e62c220b21ea)

**Comment by ILoveOpenSourceApplications** [comment]
Could be an A/B testing, but you can add it to the filters anyway as the previous one isn't even working.
