### ISSUE TITLE
About default video quality 

### ISSUE THREAD

**Issue by Mohammedibrahim15** [inotia00/ReVanced_Extended#1604]
### Application

YouTube

### Description

Sometimes default quality doesn't have a check mark on the selected quality so i have to check it manually
Is there a solution?
![Screenshot_20231027_125348_app rvx android youtube_edit_1756886577576705](https://github.com/inotia00/ReVanced_Extended/assets/130897201/855e161f-4691-4e14-8167-ffd78f2bee41)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an issue that is also reproduced on stock YouTube

To briefly explain the issue, the basic quality is applied only after the buffer section loaded when the video starts (server-side delay).

This seems to be a server-side issue, but RVX provides an option for this:

Settings > ReVanced Extended > Video > Skip preloaded buffer

![buffer](https://github.com/inotia00/ReVanced_Extended/assets/108592928/eff994af-ccd7-487a-8663-f5994782d4eb)
