### ISSUE TITLE
Import and export settings

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#1605]
### Application

YouTube

### Description

Hi sir 
When I try to import YouTube settings from internal storage. There are many files that i have deleted from storage but still being shown although it doesn't exist . As per this screenshot i have deleted Browser folder, fm themes folder  and both fast cromium folders . Is there a way to  prevent that issue 
![Screenshot_20231028_094805_com android documentsui](https://github.com/inotia00/ReVanced_Extended/assets/107951133/ea17a98f-9a8e-45ed-8c1d-d99931bea90e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
This is not RVX issue anyway, solution is easy, just do like on screen recording

https://github.com/inotia00/ReVanced_Extended/assets/110785596/e20614c9-5538-4f4f-9b05-972c7e28ab68

**Comment by Mohammed1520** [comment]
Ok thanks
I will close issue
