### ISSUE TITLE
add set of dark themes to chose from

### ISSUE THREAD

**Issue by gigachaand** [inotia00/ReVanced_Extended#1607]
### Application

YouTube

### Description

How I'm gonna access this dark themes can anyone explain.. where is the settings...I'm using Revancify👍

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
There is no such settings, all depends on `Theme` patch, it modifies the Dark theme to different color you can change in patch-options.json and anyway your question is a feature request, but inotia said that he wont add any new features, if you not believe me, just check https://github.com/inotia00/revanced-documentation/wiki/Announcement. If you want to get back original YouTube Dark theme just exclude `Theme` patch. If you have no questions please close the issue

**Comment by gigachaand** [comment]
![Screenshot_2023-10-28-17-16-17-329_com android chrome-edit](https://github.com/inotia00/ReVanced_Extended/assets/96541364/a49e502f-357a-4ed6-a137-b2bab88fc917)
I'm talking about these...👍

**Comment by girshcatt** [comment]
You understood the change wrong, it mean that more color options added that you can change in `Theme` patch patch-options.json file before you patch the YT

**Comment by Hennadz** [comment]
>it mean that more color options added that you can change in `Theme` patch patch-options.json

There, before, you could enter any color. If you want, it will be green, or blue, or yellow...
What has changed?

**Comment by gigachaand** [comment]
> > it mean that more color options added that you can change in `Theme` patch patch-options.json
> 
> There, before, you could enter any color. If you want, it will be green, or blue, or yellow... What has changed? This?
> 
> ![Screenshot_20231028-154937_YouTube](https://user-images.githubusercontent.com/130844239/278815573-d41ef557-848e-4358-9c0c-1431c6e7ef71.png)
> 
> ![Screenshot_20231028-160001_YouTube](https://user-images.githubusercontent.com/130844239/278815723-31bfacbc-6eba-445c-8897-8fa6731e28f4.png)
> 
> Instead of the previous one:
> 
> ![Screenshot_20231028-161930_MyTube](https://user-images.githubusercontent.com/130844239/278815876-26978469-9396-48d3-8f58-250a8c3b914b.png)

How I'm gonna change the colour??..I'm using Revancify for patching

**Comment by gigachaand** [comment]
![Uploading Screenshot_2023-10-28-20-13-14-087_com.termux-edit.jpg…]()

**Comment by gigachaand** [comment]
![Screenshot_2023-10-28-20-13-14-087_com termux-edit](https://github.com/inotia00/ReVanced_Extended/assets/96541364/53a4bc6a-b08c-43a5-b323-6f7d6ec5f472)

**Comment by Hennadz** [comment]
> How I'm gonna change the colour??..I'm using Revancify for patching

In order not to write the same thing again, I will give a link.
https://github.com/inotia00/ReVanced_Extended/issues/991

Examples of recording color codes can be found here:
https://www.w3schools.com/colors/colors_mixer.asp

**Comment by inotia00** [comment]
Changing color values through options.json is possible in Revancify, rvx-builder, and CLI.

As mentioned in the changelog, using color sets is only possible in RVX Manager.

![Manager](https://github.com/inotia00/ReVanced_Extended/assets/108592928/7170fd2d-3356-40c7-b3db-eb15cb26c236)

**Comment by Hennadz** [comment]
> As mentioned in the changelog, using color sets **is only possible in RVX Manager** .

Please circle in red where this is indicated.

![Screenshot_20231028-191807_Vivaldi Browser Snapshot](https://github.com/inotia00/ReVanced_Extended/assets/130844239/09dde159-8bcb-4129-ac9d-2cc3cfd1692c)

**Comment by inotia00** [comment]
> > As mentioned in the changelog, using color sets **is only possible in RVX Manager** .
> 
> Please circle in red where this is indicated.
> 

![278825277-09dde159-8bcb-4129-ac9d-2cc3cfd1692c](https://github.com/inotia00/ReVanced_Extended/assets/108592928/7082abdf-7b96-4003-b7f8-321ed7ae9c7a)

**Comment by gigachaand** [comment]
> > How I'm gonna change the colour??..I'm using Revancify for patching
> 
> In order not to write the same thing again, I will give a link. #991
> 
> Examples of recording color codes can be found here: https://www.w3schools.com/colors/colors_mixer.asp

Got it...thak u🥳

**Comment by Hennadz** [comment]
About RVX Manager where here?
