### ISSUE TITLE
suggestion(YouTube Music): add sb_about string

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1608]
### Application

YouTube Music

### Description

Add sb_about string, reason the same as in https://github.com/inotia00/ReVanced_Extended/issues/1392

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.8)
