### ISSUE TITLE
bug(YouTube/Custom playback speed): on tablets flyout panel change place to left

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1609]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.25.40 ~ 18.41.39

### Bug description

On tablets flyout panel change place to left after you open playback speed menu

https://github.com/inotia00/ReVanced_Extended/assets/110785596/83f2206b-62b7-4474-9f1f-cacf80eb7e59

### Steps to reproduce

1.Include `Custom playback speed` patch
2.Patch any supported version 18.25.40 ~ 18.41.39
3.Open player flyout panel
4.Tap on playback speed menu and leave it
5.Open player flyout menu again

### Relevant log output

```shell
:/
```

### Solution

[ReVanced Extended_v18.29.38_2023-10-28.json](https://github.com/inotia00/ReVanced_Extended/files/13195786/ReVanced.Extended_v18.29.38_2023-10-28.json)
Also i think that you can reproduce it on phone by dpi changing. You need to find dpi, on that player flyout panel will appear like popup window(i mean like you can see on screen recording)
Also i faced same behaviour with `Enable old quality menu`, but after some releases you changed smt and it not reproducable anymore, maybe you can compare change history of `Enable old quality menu` patch after 2.190.1

### Device Environment

Galaxy Tab S6: Android 12 One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
Can you check on unpatched Youtube ?

**Comment by girshcatt** [comment]
If you dont know without enabled custom playback custom playback looks like this

https://github.com/inotia00/ReVanced_Extended/assets/110785596/f16d713d-2f55-4026-b4aa-c7f79c14ebf0

**Comment by girshcatt** [comment]
If i right now custom playback speed patch returns playback speed menu from old flyout panel, but on versions with old flyout panel all work as normal, you can try unpatched 18.17.43, or just spoof to this or lower version your rvx

**Comment by inotia00** [comment]
Unfortunately, this issue can never be fixed.

The new player flyout panel is a litho component, and it is impossible to add a new view in a litho view (that's how the litho view is structured)

I tried so many different things, but I was never able to implement this issue.

To implement this I need the source code of the YouTube app

**Comment by girshcatt** [comment]
Is it possible to use playback speed menu from new player flyout panel to custom playback speed patch?

**Comment by inotia00** [comment]
impossible
