### ISSUE TITLE
feat(patch):  powertube

### ISSUE THREAD

**Issue by KPVADALIYA** [inotia00/ReVanced_Extended#161]
### Application

YouTube

### Issue

When clicking on download icon showing

Powertube not installed

I look in ReVanced manager but this powertube option is not available on letest version 

### Patch

![IMG_20230119_111631](https://user-images.githubusercontent.com/103434326/213365467-92c13ff3-99ea-4b11-89ab-fe41d8775c06.jpg)

### Motivation

Downloding easy

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Install PowerTube on your device
https://github.com/razar-dev/PowerTube/releases
