### ISSUE TITLE
feat(YouTube Music/Hide flyout panel): add `Hide help & feedback` settings

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1611]
### Application

YouTube Music

### Issue

Literally everything can be hidden from Flyout Menu, except this.

### Patch

![Screenshot_2023-10-28-19-01-15-60_0eaaacfb1e02f862bb18505a09b95933](https://github.com/inotia00/ReVanced_Extended/assets/91815107/cf9563c4-25b2-4160-a8bb-a61e441497c7)

### Motivation

Written under the "Issue" category.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.8)
