### ISSUE TITLE
suggestion: make feature less confusing

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1612]
### Application

YouTube

### Description

(Maybe this is more of a question)

First time seeing something like this, usually there would just be another option to hide the Back button
![Screenshot_20231028_170054_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/130296934/4a870b65-c9af-4bc2-8864-384083aaf57a)

So was it not possible to just have another toggle?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I couldn't implement a feature that only removes the back button from Shorts

So, it was implemented to simply hide the entire ToolBar
