### ISSUE TITLE
question: what's the purpose of patch option inside "premium heading"?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1613]
### Application

YouTube

### Description

![Screenshot_20231028_184824_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/130296934/41042b00-7b1a-44c0-83fe-8e16e0952f04)
![Screenshot_20231028_184827_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/130296934/e986172a-0ed8-452b-b544-a9b23d400aa2)
If I tick "premium heading" and also enable "use premium heading" then it shows the premium heading
But If I tick "premium heading" and disable "use premium heading" then it shows the default heading, making the inclusion of "premium heading" patch not necessary

So why does this patch contain an option inside?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In Patch Options, changing the toggle to OFF forces the default header to be used, and changing the toggle to ON forces the Premium header to be used
(intended action)

I also don't know why this patch exists, but since it was implemented in the official ReVanced Patches, it is also implemented in RVX Patches

**Comment by federicogith** [comment]
So its Patch Options is not necessary at all because if you want to have the premium header you could just tick the patch itself

Instead of ticking "premium heading" patch and then going inside its Patch Options and then changing the toggle to ON "use premium heading"
It can be just a normal a patch without Patch Options

**Comment by KobeW50** [comment]
> So its Patch Options is not necessary at all because if you want to have the premium header you could just tick the patch itself
> 
> Instead of ticking "premium heading" patch and then going inside its Patch Options and then changing the toggle of "use premium heading" to ON
> 
> What I'm saying is that its Patch Options makes it confusing and unnecessary because it can be just a normal a patch without Patch Options

The patch options are needed for YT Premium subscribers who want to have the default heading instead of the premium heading.
