### ISSUE TITLE
Separate the options for the custom package name for YT and YTM

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1615]
### Application

Other

### Description

# Issue

Currently, if you open the patch options menu in the RVX Manager for the YouTube `Custom Package Name` patch, you can set the package name for YT and YTM. But setting the package name for YTM will not affect the saved options for YTM and that can lead to confusion for the user. (The Manager saves the options separately for each app.)

Demonstration of the issue:

https://github.com/inotia00/ReVanced_Extended/assets/84587632/7a55825d-84a1-4714-86fe-c89631d17da7

# Solution

The solution for this would be to separate the custom package name in the options.json, which would require unique patch names.

(I wanted to suggest in the revanced-patches repo for the ability to specify package names for options in the options.json instead of only identifying by patch name, but oSumAtrix rejected this idea on discord because they will be replacing the options.json with CLI input and because the same option is supposed to be able to be applied to several apps.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YT Music's `MicroG support` patch uses YouTube's package name as well as YT Music's package name

So these two options cannot be separated..
