### ISSUE TITLE
bug(YouTube/Hide account menu): unintentional components are hidden

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1617]
### Application

YouTube

### Description

I'm not sure if it's intended or not.

If you add only the word "Your" in `Edit account menu filter` it hides both `Your videos` and `Your movies and TV` menus.
I know that you can just write the menu's full name to avoid this but it is to keep consistency with another same bug with `Edit feed flyout menus filter` that got fixed (https://github.com/inotia00/ReVanced_Extended/issues/1129).
The suggestion would be to apply the same fix of that bug (https://github.com/inotia00/ReVanced_Extended/issues/1129) and this way you would have more control over what to hide.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.8)
