### ISSUE TITLE
bug: Wide Search Bar hides Premium Header.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1618]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

YouTube: v18.41.39
Patches: v2.195.6

### Bug description

This is not a new patch request, please read on.

If "Wide Search Bar" is enabled, it hides the Premium Header. This can be considered unintended behaviour, since there is no warning or information text provided. So, can you consider making both of them visible at the same time?

Reasons:
1.) Lots of empty space is available to occupy both of them.
2.) Not requesting for new patch. I'm requesting for two existing patches to work together.
![A](https://github.com/inotia00/ReVanced_Extended/assets/91815107/941fad49-9e7e-4e21-8da0-574fdcc714f6)
![B](https://github.com/inotia00/ReVanced_Extended/assets/91815107/96683fb6-f69d-4cb3-ba73-8c07992f23ca)

### Steps to reproduce

No response.

### Relevant log output

```shell
No logs.
```

### Screenshots or videos

Given above.

### Solution

No response.

### Additional context

No response.

### Device Environment

Android 12, Realme 7 Pro.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Aryan-Chauhan** [comment]
> It is called "wide" search bar so it should be that wide and not kind of wide
> Also I enabled the wide search bar just to hide the header

I think, the "wideness" of it won't be affected by Premium Header.

Also, I think it should be optional, not mandatory.

**Comment by inotia00** [comment]
It's impossible

**Comment by shubamg1234567890** [comment]
I would like to suggest an idea regarding the same that in wide search if there is an option to hide premium logo or not for the users.. if selected not to hide logo then search bar is drawn below
