### ISSUE TITLE
bug: YouTube can't be patched

### ISSUE THREAD

**Issue by Pillow-Fan** [inotia00/ReVanced_Extended#162]
### Type

Error while patching

### Application

YouTube v18.01.36

### Bug description

After swapping the revamped repositories for the revamped extended ones, the Manager doesn't see YouTube (or any other app) as patchable and so it doesn't show any patches available.

### Steps to reproduce

1) install the latest revamped manager
2) go to settings -> sources and change "revanced" to "inotia00"
3) restart the app
4) go to patcher -> select application
There won't be any apps shown and even though the local apks can be selected, they won't be patchable as no patches are shown.

### Relevant log output

```shell
No log output as the app couldn't be patched.
```

### Screenshots or videos

![Screenshot_2023-01-20-12-41-30-623_app revanced manager flutter](https://user-images.githubusercontent.com/28104347/213687149-9cde64b8-ea9f-4b01-ae62-b86f0b797450.jpg)

### Device Environment

Android 12, MIUI 13, Poco F3 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I'm not a maintainer of ReVanced Manager, so I can't help with any issues with ReVanced Manager
