### ISSUE TITLE
bug: Shop button showing despite set to hide

### ISSUE THREAD

**Issue by MoTem** [inotia00/ReVanced_Extended#1620]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Youtube Version 18.41.39
Patches - v2.195.6 

### Bug description

The shop button appears below the video title despite being set to hide. Have tested this on a fresh install, cleared data, and enabled/disabled it. It still shows up on some videos. 

### Steps to reproduce

Step 1 - Go to Settings - Revanced Extended - Bottom Player - Enable Hide Shop Button 
Step 2 - Visit https://youtu.be/MbUvTbD9q4A?si=6GSiZtNl9fmxc4hC and notice the shop icon below the title. 

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![WhatsApp Image 2023-10-29 at 11 49 16 PM](https://github.com/inotia00/ReVanced_Extended/assets/49055655/7219e556-7d6d-4f54-ac31-804d088d72db)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`Hide shop button` is located in the following path:

Settings > ReVanced Extended > Bottom player > Button container > Hide shop button

In other words, `Hide shop button` hides only the shop button in the **button container**

![Button_Container](https://github.com/inotia00/ReVanced_Extended/assets/108592928/7e4ef7bf-d01e-4022-99b3-4443e0e02b61)

It doesn't hide the `Shop` tag in the video title like the screenshot you attached
