### ISSUE TITLE
bug(YouTube Music/Enable compact dialog): album art too small in the library page

### ISSUE THREAD

**Issue by skypeias** [inotia00/ReVanced_Extended#1621]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Youtube Music 6.23.55

### Bug description

The album art is too small on the Library page compared to stock YTM app

### Steps to reproduce

Just go to the Libary page and change from list to grid view. You can tell the album art thumbnails are way too small compared to Stock app

### Relevant log output

```shell
n/a
```

### Screenshots or videos

![Screenshot_20231030_012425_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/109490992/9656faa1-4b00-4dd8-8d99-441622008b8d)
![Screenshot_20231030_012413_YouTube Music](https://github.com/inotia00/ReVanced_Extended/assets/109490992/2bc36a3c-2caf-4984-81dd-bc0a041b432c)

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This issue is a side effect of the `Enable compact dialog` patch

You can turn it off in the following path:
Settings > ReVanced Extended > Flyout > Enable compact dialog

Since this issue cannot be fixed, I'll just add a side effect to the description of `Enable compact dialog`

**Comment by inotia00** [comment]
Since this issue cannot be fixed, so I added a known issue to the settings

This is reflected in [revanced-patches-v2.195.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.8), closing the issue
