### ISSUE TITLE
bug(YouTube/Hide Suggestion Shelf): Hide Suggestion Shelf also hides the podcasts

### ISSUE THREAD

**Issue by sams452m** [inotia00/ReVanced_Extended#1623]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.40.34

### Bug description

Hide suggestion shelf patch also hides the podcasts due to same LithoPatch.

### Steps to reproduce

include "Hide suggestions shelf"

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-10-30-15-09-59-884_app mod android youtube](https://github.com/inotia00/ReVanced_Extended/assets/143210060/e2eb6a9e-2c28-4526-b1a8-500479becddf)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
Any screenshot of your podcast ? Also because you can debug so pls send the log too

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)
