### ISSUE TITLE
bug: Grey screen after selecting the list of patches

### ISSUE THREAD

**Issue by Analonecrow** [inotia00/ReVanced_Extended#1624]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

RVX Manager v1.14.3
Youtube versions: 18.41.39 and 18.42.41

### Bug description

In the previous versions of the RVX Manager, after selecting the Youtube apk from the storage the app did not show the selected apk right away and I had to either wait a short while or switch tab to make it appear as a selected apk. And sometimes even after selecting the list of patches there woould be only a grey screen instead of the patch selection screen. And even after successfully applying the patches, the builder wouldn't neither install the built apk or save it to the storage.

In the new version of the manager, the problem with the selected Youtube apk not appearing in the same manner still persists but every attempt to open the list of patches results in the same grey screen showing up again.

P.S: after selecting any other apk than Youtube, the app won't allow any other apk to be selected and persists in showing the apk selected before that.

### Steps to reproduce

Step 1: Select the Youtube apk from the storage (resulting in it not showing up as selected)
Step 2: switch tabs so the selected apk to show up
Step 3: Selecting the list of patches (resulting in the grey screen)

### Relevant log output

```shell
No log due to not being able to patch the apk with the newest RVX Manager

Although I could test the previous version for the output log and post it if it's needed.
```

### Screenshots or videos

The grey screen:
![IMG_20231030_121416_084](https://github.com/inotia00/ReVanced_Extended/assets/107642397/27dc9cef-06eb-402d-8180-fa3f85bc2a2b)

Youtube apk not showing up after being selected:
![IMG_20231030_121440_511](https://github.com/inotia00/ReVanced_Extended/assets/107642397/02ffa951-34da-422a-ab84-5ab8a41a067d)

### Device Environment

Android version: 13
Device: Galaxy S22 Ultra

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
duplicated with the following issue https://github.com/inotia00/ReVanced_Extended/issues/1602

In summary, just delete RVX Manager's app data

**Comment by inotia00** [comment]
For some reason, fetching the Github API failed on the device you are using

Most people who have encountered this issue have solved it with one of these methods:
1. If you are using VPN/DNS, try turning it off
2. Try again with a different network - for example, if you are using Wi-Fi, try switching to mobile network
3. If the issue persists, try again after sufficient time has passed

**Comment by KobeW50** [comment]
> The app crashes after trying to save the built apk and produces an apk like this:

This occurs when the keystore isn't compatible with the Manager. Regenerating a new keystore should resolve the issue.

https://github.com/ReVanced/revanced-manager/issues/1253
