### ISSUE TITLE
CUSTOM speed to yt shorts

### ISSUE THREAD

**Issue by shubamg1234567890** [inotia00/ReVanced_Extended#1625]
### Application

YouTube

### Description

I know it sounds weird but shorts at custom speed sounds too good..tbh for many people.. can you please bring an overlay in YouTube shorts.. because they're also in video category.. so plz bring such an option there also. 

Suggestion 2 :
also if possible please bring channel whitelisting for ads.. when you feel ok.. You can add there an option.. so that people can enter their own YouTube data v3 api to access this feature..

Suggestion 1 & 2 .. 

Edit :- Thanks for your too much dedication inotia.. We love you brother deep heartedly ;) May God bless uh and ur family more.. ❤️

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Inotia00 isn't taking any feature requests for YouTube.
