### ISSUE TITLE
bug(YouTube/Return YouTube Dislike): RYD does not work in YouTube v18.41.39+

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1626]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.42.41
Patches v2.195.8

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/90a90310-0c31-4f28-a3a8-b7735aefaad0

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by CristianLN** [comment]
Spoofing the app version fixes the problem for me

**Comment by Kuddus73** [comment]
It used to work on YouTube v18.42.41 without any spoofing.

**Comment by inotia00** [comment]
This is A/B tests
There is no way to fix this, so in the next release, the support version will be rolled back to V18.40.34

**Comment by inotia00** [comment]
In [revanced-patches-v2.195.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.12), support for YouTube v18.41.39+has been dropped
Closing issue

**Comment by JUANHDA-CX** [comment]
I don't have that problem in 18.42.41

**Comment by jhon1282** [comment]
> I don't have that problem in 18.42.41

Same.
RYD work fine for me

**Comment by staticpiratex** [comment]
> > Non ho questo problema in 18.42.41
> 
> Same. RYD work fine for me. I believe the problem manifests itself when using rvx manager for patching. I tried with the manager and the problem is there. While using Revancify there is no this problem.

I'm using Revaced Manager on 18.42.41 and no problems!
