### ISSUE TITLE
bug: YouTube app crashes at short video upload process (videos below 1 min running time)

### ISSUE THREAD

**Issue by Retardium** [inotia00/ReVanced_Extended#1627]
### Type

Error at runtime

### Tools used

app.rvx.manager.flutter Version 1.14.3

### Application

YouTube Version 18.42.41 (default patches only)

### Bug description

App crash when I try to upload a video.

### Steps to reproduce

1. Click upload button.
2. Choose "Upload a video".
3. Select a video with running time <1 min. from your storage.
4. Click next in the editor.
5. Crash.

### Relevant log output

```shell
CrashLog from LogFox:

FATAL EXCEPTION: main
Process: app.rvx.android.youtube, PID: 5446
java.lang.IllegalStateException: MlKitContext has not been initialized
	at a.ag(PG:2)
	at alfg.a(PG:1)
	at alew.a(PG:1)
	at vmz.get(PG:13)
	at uxx.<init>(PG:28)
	at ybu.<init>(PG:22)
	at abvv.fv(PG:1)
	at fth.d(PG:4)
	at abvv.es(PG:1)
	at fth.c(PG:2)
	at xsd.y(PG:1)
	at xrd.x(PG:8)
	at ikf.M(PG:52)
	at bz.nR(PG:3)
	at opl.e(PG:24)
	at opl.g(PG:205)
	at cv.aA(PG:122)
	at cv.aC(PG:10)
	at cv.I(PG:3)
	at bb.d(PG:2)
	at ira.a(PG:7)
	at ira.c(PG:17)
	at ipm.v(PG:94)
	at ipm.u(PG:1)
	at ipm.k(PG:4)
	at qma.J(PG:75)
	at isn.onClick(PG:3)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Additional context

~~Maybe related to this old issue: https://github.com/inotia00/ReVanced_Extended/issues/4~~

### Device Environment

Android 13, CalyxOS
mMicroG Version 0.2.27.231613 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Retardium** [comment]
Example for a video file which crash the app.
I've attached the video aswell.
`General
Complete name             : VID_20231028_102432_962.mp4
Format                    : MPEG-4
Format profile            : Base Media
File size                 : 7.48 MiB
Duration                  : 20 s 967 ms
Overall bit rate mode     : Variable
Overall bit rate          : 2 993 kb/s
Frame rate                : 29.970 FPS
Encoded date              : 2023-10-26 21:19:58 UTC
Tagged date               : 2023-10-26 21:19:58 UTC

Video
ID                        : 1
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : High
Format level              : 3.1
Format settings, CABAC    : Yes
Format settings, Referenc : 4 frames
Format settings, GOP      : M=1, N=30
Codec ID                  : avc1
Duration                  : 20 s 958 ms
Bit rate                  : 2 723 kb/s
Width                     : 720 pixels
Height                    : 1 280 pixels
Display aspect ratio      : 0.562
Frame rate mode           : Variable
Frame rate                : 29.970 (29970/1000) FPS
Minimum frame rate        : 17.248 FPS
Maximum frame rate        : 30.010 FPS
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
Bits/(Pixel*Frame)        : 0.099
Stream size               : 6.80 MiB (91%)
Title                     : VideoHandle
Language                  : English
Encoded date              : 2023-10-26 21:19:58 UTC
Tagged date               : 2023-10-26 21:19:58 UTC
Codec configuration box   : avcC

Audio
ID                        : 2
Format                    : AAC LC
Format/Info               : Advanced Audio Codec
Codec ID                  : mp4a-40-2
Duration                  : 20 s 967 ms
Bit rate mode             : Variable
Bit rate                  : 265 kb/s
Nominal bit rate          : 44.1 kb/s
Channel(s)                : 2 channels
Channel layout            : L R
Sampling rate             : 44.1 kHz
Frame rate                : 43.066 FPS (1024 SPF)
Compression mode          : Lossy
Stream size               : 671 KiB (9%)
Title                     : SoundHandle
Language                  : English
Encoded date              : 2023-10-26 21:19:58 UTC
Tagged date               : 2023-10-26 21:19:58 UTC
`

https://github.com/inotia00/ReVanced_Extended/assets/32235655/05e04f76-bf9c-414f-b9c9-26d74b87dd03

**Comment by Retardium** [comment]
Example for a video which does not triggers a crash.

```
General
Complete name             : NA - Video_by_health.doityourself.mp4
Format                    : MPEG-4
Format profile            : Base Media
File size                 : 13.1 MiB
Duration                  : 1 min 17 s
Overall bit rate          : 1 410 kb/s
Frame rate                : 30.000 FPS

Video
ID                        : 1
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : High
Format level              : 3
Format settings, CABAC    : Yes
Format settings, Referenc : 4 frames
Codec ID                  : avc1
Duration                  : 1 min 17 s
Bit rate                  : 1 340 kb/s
Width                     : 576 pixels
Height                    : 1 024 pixels
Display aspect ratio      : 0.562
Frame rate mode           : Constant
Frame rate                : 30.000 FPS
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
Bits/(Pixel*Frame)        : 0.076
Stream size               : 12.4 MiB (95%)
Writing library           : x264 core 157
Encoding settings         : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=2 / psy=0 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=8 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=250 / keyint_min=126 / scenecut=0 / intra_refresh=0 / rc_lookahead=10 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=5825 / vbv_bufsize=11650 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=2:1.00
Color range               : Limited
Color primaries           : BT.709
Transfer characteristics  : BT.709
Matrix coefficients       : BT.709
Codec configuration box   : avcC

Audio
ID                        : 2
Format                    : AAC LC SBR
Format/Info               : Advanced Audio Codec
Commercial name           : HE-AAC
Codec ID                  : mp4a-40-5
Duration                  : 1 min 17 s
Bit rate mode             : Constant
Bit rate                  : 63.9 kb/s
Channel(s)                : 2 channels
Channel layout            : L R
Sampling rate             : 44.1 kHz
Frame rate                : 21.533 FPS (2048 SPF)
Compression mode          : Lossy
Stream size               : 606 KiB (5%)
Default                   : Yes
Alternate group           : 1
```

**Comment by Retardium** [comment]
I've tested a couple more videos, and it seems related to the video length. 
Videos below 1 minute runtime crash the app.

**Comment by inotia00** [comment]
It is not reproduced in my side
Try the patch with YouTube v18.40.34 and test if the issue is reproduced

**Comment by inotia00** [comment]
In [revanced-patches-v2.195.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.12), support for YouTube v18.41.39+has been dropped
Patch again with YouTube v18.40.34

If the issue persists, please open a new issue
