### ISSUE TITLE
RVX: Like Count Becomes Zero

### ISSUE THREAD

**Issue by Matty003** [inotia00/ReVanced_Extended#1629]
**Application:-** RVX `18.42.41`

**BUG** **DESCRIPTION:-**  When i open **_some_** videos, the Like count becomes **ZERO** after few seconds.

RELATED Video:-  

https://github.com/inotia00/ReVanced_Extended/assets/109008434/c35ab9ab-31c1-4655-9565-acbded0e239a

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1626

**Comment by inotia00** [comment]
You should downgrade YouTube v18.40.34
