### ISSUE TITLE
Youtube ReVanced Not Supporting Equalizer 

### ISSUE THREAD

**Issue by niravmachhi** [inotia00/ReVanced_Extended#163]
### Application

YouTube

### Issue

I Request to Team Please Resolve issue of Youtube ReVanced Not Supporting System Equalizer Without Equalizer YouTube Music and Youtube Not Giving Good Sound 

### Patch

I dont have screenshot 

### Motivation

This issue is facing all 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Google should support it on YouTube and YouTube Music
ReVanced / ReVanced Extended cannot support what YouTube and YouTube Music do not support
