### ISSUE TITLE
bug: <themes> light theme not working

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1631]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

YouTube v18.40.34

### Bug description

Light theme not working but dark theme patch works as intended.
Light theme just stays on defaut white theme and doesn't change to selected theme within light theme colours within the theme patch option.

### Steps to reproduce

1. Patch youtube with latest patches
2. Including themes option and both dark, light themes selected and saved within patch options
3. Install patched YouTube and open using dark and light mode to see if it works or not.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-10-31-18-24-48-579_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/dcec26a2-6a81-4f31-96b6-056c22fcdc59)
![Screenshot_2023-10-31-18-25-02-649_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/d8c0c56a-df20-41aa-abb6-a265563fd240)
![Screenshot_2023-10-31-18-25-25-772_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/2a53ed51-80f4-4118-996d-3215a86219b8)

### Solution

Fix light theme patch option.

### Additional context

Using Xiaomi 11t pro phone

### Device Environment

Android 13 MIUI14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Please upload the following screenshot

Settings > ReVanced Extended > Miscellaneous > Patch Information > (scroll down) > Theme

![Theme](https://github.com/inotia00/ReVanced_Extended/assets/108592928/3df7755f-4b76-40d3-9f97-76f0170f88e1)

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1631#issuecomment-1787195147
Here ya go.
![Screenshot_2023-10-31-19-03-29-618_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/37c29120-a969-43d5-a80c-8c1e9474c864)

**Comment by inotia00** [comment]
The priority of themes is as follows:

MaterialYou Light > Light Theme

Dark Theme > MaterialYou Dark

You included MaterialYou

Therefore, MaterialYou Light's theme was applied

If you want to use the Light Theme, you should exclude the `MaterialYou` patch

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1631#issuecomment-1787383565
I figured but I don't like those default Red notifs over custom themes so I use material you patch with it which used to work...
Can light theme be prioritised over material you theme like in dark theme?
