### ISSUE TITLE
bug(YouTube): The Video rewinds to the 0:00 after playing a Shorts Video

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#1634]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

Youtube v18.25.40
RVX Manager (Patch V2.195.12)

### Bug description

The Video rewinds to the very start (0:00) after playing shorts video instead of staying in the last played timestamp.

I have tried using the Original Youtube v18.25.40 and the bug doesn't appear, when I exit the shorts the video doesn't go back to 0:00 but rather stays where it stopped.

### Steps to reproduce

Step 1) Play a Video(Not Shorts)
Step 2) Under the Video Player, scroll down till you see a Shorts Shelf
Step 3) Click on a Shorts Video
Step 4) Exit Shorts/Go back to the Main Video
Step 5) The video goes back to (0:00) instead of going back to where it stopped. 

### Relevant log output

```shell
.
```

### Additional context

I have encountered this bug before in other patch version, got fixed but then reappeared in the latest patch v2.195.12

I just read the description and seems like it is a known issue but when I turn off "Spoof Player Parameter" and restart the app. The issue still persists despite spoof player parameter disabled. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
If I tested correctly, it seems that `Skip preloaded buffer` is causing the issue

Turn off `Skip preloaded buffer` and test if the issue reproduces

**Comment by Stale-1** [comment]
> If I tested correctly, it seems that `Skip preloaded buffer` is causing the issue
> 
> Turn off `Skip preloaded buffer` and test if the issue reproduces

Skip preloaded buffer already off when I tried but I turned it on still, then restart. It still didn't work then I turned it off and restart, issue still persist.

So I tried turning off the Spoof Player Parameter but still get the error. Not sure why it happens.

**Comment by inotia00** [comment]
In my side, the issue was reproduced only when I turned on `Skip preloaded buffer`

Other than that I have no idea 🫠

**Comment by inotia00** [comment]
Exclude patches one by one until the issue is not reproduced.
And please let me know which patch is the cause of the issue

**Comment by Stale-1** [comment]
> Exclude patches one by one until the issue is not reproduced. And please let me know which patch is the cause of the issue

I'm using YT version 18.39.41, with patch version 2.196.4
The bug doesn't exist occur anymore.

Forgot to mention, I also removed the "disable playing 2x speed" patch
