### ISSUE TITLE
question: <question regarding light theme>: 

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1639]
### Application

YouTube

### Description

While using light themes option in theme patch and material you patch, the light theme gets overriden by material you theme
I don't like those default Red notifs over custom themes so I use material you patch with it which used to work...
![Screenshot_2023-11-02-02-45-33-154_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/c5dc49ad-bc4a-480b-b3cb-6b6b01476034)
So my question is-
Can light theme option be prioritised over material you theme like in dark theme option?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's impossible
Exclude the `MaterialYou` patch to use a custom light theme
