### ISSUE TITLE
Conflict of installation with the latest update of the official YouTube app 

### ISSUE THREAD

**Issue by Shiroe93** [inotia00/ReVanced_Extended#164]
### Type

Other

### Application

YouTube Revanced extended 18.03.32

### Bug description

There's a conflict between the revanced extended package and the last YouTube official updated

### Steps to reproduce

1 install revanced extended 18.03.32
2 try to update YouTube official (through playstore or apk)
If you try to install revanced extended after the update of the official app it gives you the same kind of error

### Relevant log output

```shell
No code present
```

### Screenshots or videos

![Screenshot_20230122_223342_Google Play Store](https://user-images.githubusercontent.com/56954468/213941616-31fc6c29-01d1-4075-af66-d2c5d5a40637.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Shiroe93** [comment]
Also I noticed that when you click an info card of a suggested video it doesn't work work (it's doesn't open the video suggested)

**Comment by inotia00** [comment]
Recommended version of ReVanced Extended is v18.01.36
Try patching with the recommended version
