### ISSUE TITLE
bug: CLI, can't include patches

### ISSUE THREAD

**Issue by Zoey2936** [inotia00/ReVanced_Extended#1641]
### Type

Error while patching

### Tools used

CLI

### Application

CLI v4.04

### Bug description

When patching using https://github.com/inotia00/revanced-cli, I can't include patches

### Steps to reproduce

Run: `java -jar revanced-cli.jar patch --rip-lib=x86 --rip-lib=x86_64 --rip-lib=armeabi-v7a -p -m revanced-integrations.apk --keystore=revanced.keystore -b revanced-patches.jar -i replace-cast-button -o p-yt-m.apk yt-m.apk`
get log:
`INFO: Replace cast button excluded`
same with youtube

### Relevant log output

```shell
INFO: Replace cast button excluded
```

### Device Environment

Windows 11, WSL2, Debian testing, openjdk 17.0.9 2023-10-17

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
The cli doesn't use the `-`s anymore, and is capitalized according to the patch names found in the README of the patches repository.

So the new command would be `-i Replace cast button`
