### ISSUE TITLE
feat(YouTube/Translations): Add Simplified Chinese Please.

### ISSUE THREAD

**Issue by July2099** [inotia00/ReVanced_Extended#1643]
### Application

YouTube Music

### Issue

Because in the process of using it, when it is automatically translated to Traditional Chinese, it will often fail to display, or display incompletely.

### Patch

I hope Simplified Chinese can be added to the automatic translation.

### Motivation

It allows the majority of Chinese users to use YouTube more smoothly, facilitates cultural exchanges among people around the world, and promotes world harmony and progress.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube and YouTube Music already support language resources for Chinese Simplified
