### ISSUE TITLE
Unlimited buffering 

### ISSUE THREAD

**Issue by Mhmodhaha** [inotia00/ReVanced_Extended#1644]
### Type

Error while playing video

### Application

V18.40

### Bug description

When open a video for the first time it works normally but after closing it and opening it again the buffering issue come again it was working normally until today.

### Steps to reproduce

Open any video 
Colse it and open it again 

### Solution

Make default video quality auto 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Mhmodhaha** [comment]
My settings 
[YouTube_v18.40.34_2023-11-03.json](https://github.com/inotia00/ReVanced_Extended/files/13255351/YouTube_v18.40.34_2023-11-03.json)

**Comment by girshcatt** [comment]
Ab testing, much people started to report this a month ago, i will just paste inotias post:
If anyone has Minimized playback issues, try reinstalling all patch environments and re-patch with YouTube v18.27.36

I think YouTube v18.27.36 is the least affected by A/B testing

The meaning of resetting the patch environment is as follows:

Revancify
: Delete components > Tools

RVX Builder
: type rvxre or ./rvx-builder.sh reinstall && ./rvx-builder.sh run

RVX Manager
: reinstall Manager

I reset all my patch environments 10 minutes ago and rolled back to YouTube v18.27.36
finally I got my peace of mind back 🫠

EDIT: If you don't have any issues with v18.40.34, you can just patch to v18.40.34

**Comment by Mhmodhaha** [comment]
But after making default video quality in revanced extended setting it works normally 
And it is not minimized playback issue 
It just occurs when selecting a default quality

**Comment by Mhmodhaha** [comment]
> Ab testing, much people started to report this a month ago, i will just paste inotias post: If anyone has Minimized playback issues, try reinstalling all patch environments and re-patch with YouTube v18.27.36
> 
> I think YouTube v18.27.36 is the least affected by A/B testing
> 
> The meaning of resetting the patch environment is as follows:
> 
> Revancify : Delete components > Tools
> 
> RVX Builder : type rvxre or ./rvx-builder.sh reinstall && ./rvx-builder.sh run
> 
> RVX Manager : reinstall Manager
> 
> I reset all my patch environments 10 minutes ago and rolled back to YouTube v18.27.36 finally I got my peace of mind back 🫠
> 
> EDIT: If you don't have any issues with v18.40.34, you can just patch to v18.40.34
But after making default video quality in revanced extended setting it works normally 
And it is not minimized playback issue 
It just occurs when selecting a default quality

**Comment by Mhmodhaha** [comment]
> Ab testing, much people started to report this a month ago, i will just paste inotias post: If anyone has Minimized playback issues, try reinstalling all patch environments and re-patch with YouTube v18.27.36
> 
> I think YouTube v18.27.36 is the least affected by A/B testing
> 
> The meaning of resetting the patch environment is as follows:
> 
> Revancify : Delete components > Tools
> 
> RVX Builder : type rvxre or ./rvx-builder.sh reinstall && ./rvx-builder.sh run
> 
> RVX Manager : reinstall Manager
> 
> I reset all my patch environments 10 minutes ago and rolled back to YouTube v18.27.36 finally I got my peace of mind back 🫠
> 
> EDIT: If you don't have any issues with v18.40.34, you can just patch to v18.40.34

But after making default video quality in revanced extended setting it works normally 
And it is not minimized playback issue 
It just occurs when selecting a default quality
