### ISSUE TITLE
bug: Additional Setting option doesn't hide after hiding all elements

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1645]
### Type

Other

### Tools used

rvx-builder

### Application

YT 18.40

### Bug description

The "Additional Settings" option should be hidden after hiding it's all elements. It is always there. YT version is not an issue.

### Steps to reproduce

Hide all elements of that, and see.

### Relevant log output

```shell
...
```

### Screenshots or videos

![Screenshot_2023_1104_194531](https://github.com/inotia00/ReVanced_Extended/assets/93650504/55d0dd91-54ca-4ce1-9406-ffa38aafded7)

### Solution

Hiding elements should also hide that.

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
![IE](https://github.com/inotia00/ReVanced_Extended/assets/108592928/f02d8e01-267e-487f-8cd2-0fcba55d21bc)

This is a known issue with Import / Export Settings

If you have imported settings, you should open ReVanced Extended Settings at least once - to hide Additional setting
