### ISSUE TITLE
feat(patch): Making Dislike button also compact. (YT)

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1646]
### Application

YouTube Music

### Issue

Can you also make Dislike button also compact as you did with Like button. It will look nice if that dislike also not have a separator and making the bar more compact.
![Screenshot_2023_1104_213126](https://github.com/inotia00/ReVanced_Extended/assets/93650504/ec55eb52-400a-4ad0-8708-d964d878ad7d)

### Patch

...

### Motivation

Enhance look of Like and Dislike bar without having any separators b/w count and buttons.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Inotia not accept any feature request

**Comment by Vipin2003** [comment]
Ohkk...
