### ISSUE TITLE
Can't download long videos on SD card

### ISSUE THREAD

**Issue by rushabhT3** [inotia00/ReVanced_Extended#1647]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube Extended 18.42.41

### Bug description

Can't download in youtube on SD card it goes to 30-40% for many big videos and shows SD card error. 

### Steps to reproduce

Step 1. Youtube revanced download option set to SD card 
Step 2. Download YouTube video preferably a long video say 30 minutes: it would go up to 30-40% then shows error many times up to 70 % but still. 

### Relevant log output

```shell
... Idk what's this is
```

### Screenshots or videos

![IMG_20231105_185912](https://github.com/inotia00/ReVanced_Extended/assets/41021094/04e7d11c-2def-42d2-b69a-a72fbe1634af)

### Device Environment

![Screenshot_2023-11-05-19-01-51-34_9492aa3750dca76abb7c25b39a5f1e8e](https://github.com/inotia00/ReVanced_Extended/assets/41021094/a77df9c2-07f2-4e78-9314-386784512e49)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
Check if u use spoof player parameter in settings, on of his side effects is: downloading of videos can not work
