### ISSUE TITLE
suggestion: Whitelist Channel Speed

### ISSUE THREAD

**Issue by nochlab1** [inotia00/ReVanced_Extended#1648]
### Application

YouTube

### Description

Hi is it possible to add Whitelist Channel Speed for when the default speed is set to something other then normal
There was a pr opened for it before you shut down development so if possible to now add it in
Thanks so much

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Inotia saw ReX pr, he implemented almost things, but he cancelled whitelist feature and if you will check https://github.com/inotia00/revanced-documentation/wiki/Announcement and how you can see now he not accept any feature requests
