### ISSUE TITLE
How to hide this search 🔎 bar

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1649]
### Application

YouTube

### Description

![IMG_20231106_004806](https://github.com/inotia00/ReVanced_Extended/assets/117540245/d8479fc4-83ea-4fe8-9897-82852ec40b41)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
If i right only way is to clear app data 
and keep doing this until then on first app launch you won't see this search bar. YouTube server-side thing

**Comment by inotia00** [comment]
You can't

**Comment by Mehedi5585** [comment]
> If i right only way is to clear app data and keep doing this until then on first app launch you won't see this search bar. YouTube server-side thing

Thanks Dear

**Comment by Mehedi5585** [comment]
> You can't

No feature to hide it has been added yet.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)

**Comment by Mehedi5585** [comment]
> reflected in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)

Thanks Dear
