### ISSUE TITLE
question: Chapter thumbnail would not show even after the update

### ISSUE THREAD

**Issue by recogy** [inotia00/ReVanced_Extended#1650]
### Application

YouTube

### Description

Was using ver 18.31 perfectlly but run to this issue that the whole chapter thumbnail would bot show for every vids. Updated to 18.40 but it did not fix. Hide emoji is off and tried to reinstall and reboot but nothing helped. 
![Screenshot_20231106-175054](https://github.com/inotia00/ReVanced_Extended/assets/150017877/1688687e-fddd-45d9-b269-a813f774f56a)

What should I do?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It does not reproduce on my side

v18.31.37 is also still a supported version

If you didn't have the issue with v18.31.37, simply patch again to v18.31.37

**Comment by recogy** [comment]
> It does not reproduce on my side
> 
> v18.31.40 is also still a supported version
> 
> If you didn't have the issue with v18.31.40, simply patch again to v18.31.40

The problem was there on v18.31.40. I thought v18.40 would fix this issue so I updated but no. It happens on both version.

**Comment by inotia00** [comment]
Check if the issue reproduces when you watch the same video on unpatched YouTube

**Comment by recogy** [comment]
Yes, chapter thumbnails is showing on the unpatched youtube after a split second of loading.

**Comment by inotia00** [comment]
What method did you use to apply the patch?

Did you make any additional changes to the APK after the patch?

Check if the issue reproduces in the following situations:
1. When turning off the VPN
2. When turning off `Spoof player parameters`

**Comment by recogy** [comment]
I am currently located in China so I can not access youtube without a VPN but
Tried changing my ip from US to a private home server in Japan with the VPN.
Tried turning off Spoof player parameters.
Both did not fix the problem.

**Comment by recogy** [comment]
Found a solution. After turning on spoof app version, chapter thumbnails start to shown. Don't know what caused the issue but it works now.

**Comment by recogy** [comment]
Found out why. My unpatched youtube was version 18.12.34. After updating to the new version it starts to have the same issue. I guess google has done something towards it relating vpn? 
Anyway sorry for the disturbance and thank you for you replies.
