### ISSUE TITLE
bug(YouTube/Swipe controls): swipe gesture working even after after using `Lock screen` feature

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1653]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 18.40.34

### Bug description

Swipe gesture works even after using `Lock screen` feature in player settings.

### Steps to reproduce

1. Patch youtube with latest patches including swipe gesture patch
2. Watch a video in full screen and use 'Lock screen's feature
3. Try swiping up and down from left and right side to check if swipe gesture still works.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-11-06-18-29-47-303_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/5b493e50-d364-4474-943a-c902a584e433)
![Screenshot_2023-11-06-18-30-08-521_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/107706560/b92cf4c8-4b0e-4217-8696-f9e83a615784)

### Solution

Lock swipe gestures when `Lock screen` feature is used.

### Additional context

Using Xiaomi 11T pro

### Device Environment

Android 13 MIUI 14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)
