### ISSUE TITLE
question(YouTube Music): Why is there no option to download/share playlists?

### ISSUE THREAD

**Issue by maksam07** [inotia00/ReVanced_Extended#1654]
### Application

YouTube Music

### Description

Good afternoon. I know about the third party music download manager, but the problem is a bit different. In many sections of the app, the "download" and "share" buttons are not active. And if they are active, not all of them perform the action. 
This can be clearly observed with the playlists that are generated for me. These playlists can be downloaded with a direct link (from the browser) with the ytdlnis program, if cookies are used. This has already been tested. Why not make the integration with this program to the end? Is there any problem with that?

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by maksam07** [comment]
> Please attach a screenshot or screen record.


https://github.com/inotia00/ReVanced_Extended/assets/24889043/bd6b08d5-9fd0-4978-bb08-f79cbe89544f

I used the app from https://revanced.net/ to install this youtube music.

**Comment by inotia00** [comment]
You are using pre-built apk from an illegal website
I don't know which patches are included in the pre-built apk, and I don't know what additional modifications were made

For this reason I do not provide any support to pre-built apk users
Closing issue

**Comment by maksam07** [comment]
> You are using pre-built apk from an illegal website I don't know which patches are included in the pre-built apk, and I don't know what additional modifications were made
> 
> For this reason I do not provide any support to pre-built apk users Closing issue

Yes, I was wrong to provide a video based on the finished assembly. I added the patches through your application: https://github.com/inotia00/revanced-manager/releases/tag/v1.14.3

But it didn't change anything... Full patch application video:

https://github.com/inotia00/ReVanced_Extended/assets/24889043/24cfc88e-637d-46af-943a-13eb1911d3d3

**Comment by inotia00** [comment]
well.. nevertheless, since you performed the patch using the valid method, I will give you an answer

`Hook download button` setting is in the `ActionBar` category

In other words, the setting only hooks the download button in `ActionBar`
Download buttons other than `ActionBar` are not hooked, and there are no plans to implement it

**Comment by inotia00** [comment]
Also, in the case of an issue where an error message is shown when clicking the `Share` button...

Same issue in unpatched YouTube Music

There seems to be a problem with the YouTube Music server-side

**Comment by maksam07** [comment]
> Same issue in unpatched YouTube Music

Yes, you're right, I didn't notice it myself at first, but . Maybe there is a possibility to make this kind of interception: when clicking on the "share" button, the patch gets a link to the playlist (as if this playlist is open in the browser) and passes this link to ytdLnis? Or is there no way to know the id of the playlist to generate such a link?

> Download buttons other than `ActionBar` are not hooked, and there are no plans to implement it

Can you tell us why there are no plans for such an implementation? Unless it is not a secret, of course, and you can report such information.

**Comment by inotia00** [comment]
Like Chrome Extensions and ytdl, RVX is also the result of reverse engineering.

Therefore, features that cannot be reverse engineered cannot be implemented.

Implementing those features requires the full source code of YouTube Music.

**Comment by maksam07** [comment]
Thank you for your responses, I'm glad you took the time to do so
