### ISSUE TITLE
improvement of brightness gesture.

### ISSUE THREAD

**Issue by shubhamvermaa** [inotia00/ReVanced_Extended#1655]
### Application

YouTube

### Description

Brightness gesture increases the brightness really fast near the zero values,  slowly afterward, i assume this is because we perceive light in logarithmic scale, so I suggest to make the brightness guesture logarithmic too. This will create a smoother transition from higher to lower brightness.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicate with https://github.com/inotia00/ReVanced_Extended/issues/59
