### ISSUE TITLE
suggestion: <title>: Remove the translucent strip in the top status bar.

### ISSUE THREAD

**Issue by georgeharrison4** [inotia00/ReVanced_Extended#1656]
### Application

YouTube

### Description

Will it be possible to remove the top strip in the status bar (the first, also the top screenshot) to achieve a barless look, like on iOS (the second screenshot, also the bottom)?
<a href="https://ibb.co/z6HPzkM"><img src="https://i.ibb.co/1zJRkSg/Screenshot-2023-10-30-22-24-02-373-app-revanced-android-youtube.jpg" alt="Screenshot-2023-10-30-22-24-02-373-app-revanced-android-youtube" border="0"></a>
<a href="https://ibb.co/mC53n4F"><img src="https://i.ibb.co/8DgHy94/Screenshot-2023-10-30-22-23-17-943-org-videolan-vlc.jpg" alt="Screenshot-2023-10-30-22-23-17-943-org-videolan-vlc" border="0"></a>

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I do not accept new feature requests for YouTube.

**Comment by georgeharrison4** [comment]
While watching a video in full-screen mode, if you swipe down from the top to see the time, battery level, Wi-Fi and mobile network signal strength, and all of this is called the top bar or status bar. I want you to remove the semi-transparent strip in the status bar in your app versions, so the result looks like the second screenshot (bottom) of the first post.
