### ISSUE TITLE
question: Channel tab is hidden 

### ISSUE THREAD

**Issue by Yola-cola** [inotia00/ReVanced_Extended#1657]
### Application

YouTube

### Description

Usually there should be a channel tab showing a channels subscriptions and pinned channels 
But not it's completely gone.
Is there a way to get it back or is this a bug?
![Screenshot_20231107-142409_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/53379032/b4e3e426-1fba-49a4-84c9-5da6717bee40)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Check for unpatched YouTube first
If you don't have an issue on unpatched YouTube, but only on RVX
try removing app data
