### ISSUE TITLE
suggestion: <YouTube>: 3 dots from videos notifications having a download option.

### ISSUE THREAD

**Issue by NikunjKhangwal** [inotia00/ReVanced_Extended#1658]
### Application

YouTube

### Description

I don't know if it's possible to implement but i would love to have a direct download option from 3 dots menu of a video notification. (Offline save in-app, not talking about using 3rd party app to save to local storage) So i dont have to open every single video seperatly. Having this option behind 3 dots isn't necessary, if there's a seperate button in notification message that'll work too but i feel like that would be even harder to implement

![IMG_20231108_224157-min](https://github.com/inotia00/ReVanced_Extended/assets/99175083/d3193799-b15e-40a8-80ac-48619f935888)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Inotia00 isn't accepting new feature requests for YouTube
