### ISSUE TITLE
bug(YouTube Music/RYD): sometimes count not appears

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1659]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube Music 6.20.51

### Bug description

Sometimes count not appears, i have no clearly way to reproduce it, but today i faced it few times on half an hour

### Steps to reproduce

Step 1. Include `Settings` patch
Step 2. Include `Return YouTube Dislike` patch
Step 3. Open any song(For this time it reproduces only from single, album menu, idk how to name it, i mean this
![Screenshot_20231108_211928_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/2489d5ca-16aa-4177-9d01-779e7fd925c9)

### Relevant log output

```shell
:/
```

### Additional context

My settings:

"custom_filter": true,
"custom_filter_strings": "card_carousel_interstitial",
"custom_playback_speeds": "0.25\n0.5\n0.75\n1.0\n1.25\n1.5\n1.75\n2.0\n2.25\n2.5\n2.75\n3.0",
"disable_auto_captions": true,
"enable_compact_dialog": false,
"enable_flyout_panel_playback_speed": true,
"external_downloader_package_name": "com.junkfood.seal",
"hide_account_menu": true,
"hide_account_menu_empty_component": true,
"hide_account_menu_filter_strings": "Скачанные\nИстория\nВаш Recap\nСменить аккаунт\nСправка\/отзыв",
"hide_action_bar_label": true,
"hide_action_bar_radio": true,
"hide_button_shelf": true,
"hide_category_bar": true,
"hide_emoji_picker": true,
"hide_explore_button": true,
"hide_flyout_panel_download": true,
"hide_flyout_panel_help": true,
"hide_flyout_panel_like_dislike": true,
"hide_flyout_panel_save_to_playlist": true,
"hide_flyout_panel_share": true,
"hide_flyout_panel_start_radio": true,
"hide_navigation_label": true,
"hide_new_playlist_button": true,
"hide_playlist_card": true,
"hide_samples_button": true,
"hide_terms_container": true,
"hook_action_bar_download": true,
"replace_flyout_panel_dismiss_queue": true,
"replace_player_cast_button": true,
"ryd_compact_layout": true,
"sb_enabled": false

### Device Environment

Android 12, One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Rather than a patch issue, it is most likely a problem with the Return YouTube Dislike server.
Dislike numbers are sometimes not fetched from YouTube or the Chrome Extension due to an issue with the Return YouTube Dislike server.
