### ISSUE TITLE
SponsorBlock Weird Issues

### ISSUE THREAD

**Issue by Kaze2508** [inotia00/ReVanced_Extended#166]
### Type

Error at runtime

### Application

YouTube 18.02.33

### Bug description

In previous version, whenever I turn off the screen and play Music Video through Bluetooth Headphones, SponsorBlock worked flawlessly. Since I updated 18, SponsorBlock only works when I watch video directly. It was unable to skip Sponsor when I listen using Bluetooth Headphones anymore

### Steps to reproduce

Step 1. Uninstall version 17
Step 2. Play a video (specific Music Videos)
Step 3. Turn off the screen
Step 4. Sponsor are not skipped

### Relevant log output

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please use the recommended version
Current recommended versions are v17.49.37 and v18.01.36

I do not provide help for issues arising from non-recommended versions.
