### ISSUE TITLE
 Integration (Voice-over video translation)

### ISSUE THREAD

**Issue by byJE7** [inotia00/ReVanced_Extended#1660]
### Application

YouTube

### Description

Integration of voice-over video translation from Yandex (https://github.com/ilyhalight/voice-over-translation) if possible, a useful feature if you want to watch a video in another language, but you don't know it.

I apologize for possible mistakes, I used a translator

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
No longer accepting new patch requests or suggestions from YouTube
