### ISSUE TITLE
YouTube Dislike not working

### ISSUE THREAD

**Issue by SerialBus500** [inotia00/ReVanced_Extended#1661]
Recently installed the very latest version of Revanced Extended (18.42.41), and when I opened the app the dislike count wasn't displayed properly. Even after doing all the steps to disable and reenable it, the issue still persists. Is this a bug related to the update, or is there a technical issue that I'm not aware of?

**Comment by inotia00** [comment]
The current supported version is YouTube v18.40.34
Please try patching again with YouTube v18.40.34
