### ISSUE TITLE
can you please change the package name on constants.kt 

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [inotia00/ReVanced_Extended#1662]
### Application

YouTube

### Description

I mean the app package name, because when i try to install the app, on top of my actual youtube version (i patched it with a script which allow you to patch not officially supported revanced versions, so i didn't saw necesary to use my actual installed youtube version, also i can't patch my actual youtube version because is a split apk, and is a not supported version, so you know, and also all this script stuff), this is the script in matter: https://github.com/Zelooooo/AT-YT , so the point is what that way of naming the package don't allow me to install it alongside normal youtube, and the prebuilt versions don't have this issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
If you include the MicroG Support patch, the package name will be changed. You can also include the Custom Package Name patch and then specify a custom package name in the patch options (aka options.json).
