### ISSUE TITLE
suggestion: Ability to hide Views and Subscribers

### ISSUE THREAD

**Issue by Analonecrow** [inotia00/ReVanced_Extended#1663]
### Application

YouTube

### Description

Hello,
I've been using an extension on my PC to hide the subscriber count, views and the thumbnails for a long time. I think doing so only creates a better and a more natural experience while using Youtube. And now that Revanced has an awesome patch to alter the thumbnails, I think it would be great to also have a patch to hide the channels' subscribers and video views. 

Thanks to all the developers for putting effort and time to the project 🙏🏻 👍 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
No longer accepting new patch requests or suggestions from YouTube

**Comment by s7san007** [comment]
video_subtitle
compact_channel_bar
