### ISSUE TITLE
bug: YTM Play Next/Prev buttons missing over Rewind buttons

### ISSUE THREAD

**Issue by nightznero** [inotia00/ReVanced_Extended#1664]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

6.25.53

### Bug description

(sometimes) On long mixes buttons to Play Next/Previous are replaced by rewind buttons. On app as well as on miniplayer and other players

### Steps to reproduce

Any long mix 1h or 2

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20231109_201442](https://github.com/inotia00/ReVanced_Extended/assets/61750641/b4ccf797-8cf1-4a11-8d3b-68cca1a80558)

### Solution

Rewind buttons would be awesome to be close to play n/p butyons but if its not possible just normsl buttons to plsy next/prev as always it was

### Additional context

idk its intended to be just in YTM but if somebody want to skip period of time can do this in notification player with swipping finger on timeline but if want to close that music have to stop my tasks,open YTM and manually skip the song

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [ ] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is the same for unpatched YouTube Music
Closing issue
