### ISSUE TITLE
bug(YouTube/Hide general ads): `Hide general ads` hides upload time of video description

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#1666]
### Application

YouTube

### Description

![Screenshot_2023-11-11-14-45-47-075_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125992636/2a65a587-6cdd-4049-bacf-da1245261933)
![Screenshot_2023-11-11-14-50-35-303_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125992636/cc6c7920-61b3-4bc7-ab7c-def0ce67ff98)
Is YouTube removing the feature again?, or is this a bug?, why is the video upload date missing, whether it's in the description in normal video or short video

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I thought it was A/B tests
But I checked again and this is a bug in RVX

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)
