### ISSUE TITLE
suggestion(YouTube Music/Enable playback speed): add revanced_enable_flyout_panel_playback_speed_normal string

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1667]
### Application

YouTube Music

### Description

Add revanced_enable_flyout_panel_playback_speed_normal string, i mean
![Screenshot_20231111_105944_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/c0fccece-2986-4946-b242-8f0510e12dd5)
 in russian word "Стандартное" it is grammatically incorrect, also  word "Стандартное" not fit the screen on all phones except samsung and looks like:
![IMG_20231111_110759_792](https://github.com/inotia00/ReVanced_Extended/assets/110785596/7e6165f4-ae0e-419c-b90d-ddb99a177ef5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.196.1
