### ISSUE TITLE
bug(YouTube/Custom playback speed): width adjustment of the speed dialog is required

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1668]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 18.43.45
Patches 2.196.1

### Bug description

In other languages the translated word might get split:
![ _20231111_173327](https://github.com/inotia00/ReVanced_Extended/assets/127908708/55c577f8-3184-4b42-8824-8862f911eb6e)

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
The description of the issue is not sufficient

**Comment by Kuddus73** [comment]
In Italian the word "normal" is "normale".
As you can see from the screenshot the "e" of "normale" goes to new line.

**Comment by inotia00** [comment]
I thought it was a typo, but I didn't think it was an Italian translation
Okay I understand it now

**Comment by girshcatt** [comment]
Thats it, please do this for YTM too, because when i translate "Normal" string to fit the screen i need to cut a big part of a word

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.196.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.4)
