### ISSUE TITLE
bug: <title> youtube overlay button

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1669]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube v18.43.45

### Bug description

In early version the volume and brightness swipe overlay button works when we lock the screen can you add the option to if the overlay button should work in lock screen or  disable 

### Steps to reproduce

Open youtube
Play video in full screen
Use swipe overlay buttons

### Relevant log output

```shell
.
```

### Device Environment

Android 12,miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Unfortunately that is not possible

**Comment by Adity1243** [comment]
But that is working in previous patch
