### ISSUE TITLE
bug(YouTube/SponsorBlock): skip segments breaks autoplay

### ISSUE THREAD

**Issue by MarcoSupper** [inotia00/ReVanced_Extended#1670]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Youtube v18.42.41

### Bug description

When playing a video that has a sponsor block segment that will be skipped at the end of it the auto play will stop working and it just gets stuck at the end of the video. You will than have to manually go to the next video/replay the video. It seems this bug already happened once in May and was fixed afterwards (see issue: #547). Now it's back.

### Steps to reproduce

Playing a video that has a sponsor block segment at the end of it. It will get stuck and not auto play the next video.

### Relevant log output

```shell
none available
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.196.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.4)
