### ISSUE TITLE
suggestion: separate the `Shorts outline button` patch from `Overlay buttons` patch

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1671]
### Application

YouTube

### Description

Currently "Outline icons" of "Overlay buttons" also changes the icons of Shorts buttons
Some might want to change only just the icons of "Overlay buttons" and not also of the Shorts buttons

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.196.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.4)
