### ISSUE TITLE
bug: <Player button button background removal error>

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1672]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 18.43.45

### Bug description

After patching the app, I found it while turning on the video and confirmed that I installed the patch

### Steps to reproduce

1. Patch to the latest version
2. Open any video and watch it

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20231112_033740_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/98168192/52c42757-a338-40ff-9ca2-b58964a18eba)
![Screenshot_20231112_033916_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/98168192/d943cdf5-b397-45d5-8808-4627ec5d54b7)

### Device Environment

Android 13,one ui 5.1
Galaxy a33 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
You should turning on via settings
