### ISSUE TITLE
bug(YouTube): `Hide mix playlists` hides playlists from music section

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1674]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.25.40 ~ 18.43.45

### Bug description

`Hide mix playlists` hides playlists from music section, this is bug from chat https://t.me/revanced_extended_chat/274818
![IMG_20231111_221808_632](https://github.com/inotia00/ReVanced_Extended/assets/110785596/c290a01f-4ba0-4def-9d55-781e90dc0edc)

### Steps to reproduce

Step 1. Include `Settings` patch
Step 2. Include `Hide mix playlists` patch
Step 3. Hide mix playlists

### Relevant log output

```shell
:/
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
#1673
