### ISSUE TITLE
suggestion: Add info to 'Disable speed overlay' toggle that it restores 'Slide to seek'

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1676]
### Application

YouTube

### Description

Add to the description of this toggle that it restores the slide to seek function.

![SmartSelect_20231111_185920_YT Extended](https://github.com/inotia00/ReVanced_Extended/assets/84587632/369ae6a8-d119-444d-9ed5-22d236d0e823)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.196.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.4)
