### ISSUE TITLE
youtube - hide player button background makes the player overlay lag

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1679]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

youtube 18.43.45

### Bug description

when you include hide player overlay patch and enable it, the player overlay does not not appear smoothly, it gets a bit dark at first, then darker. if ypu dont enable it, then the issue doesnt occur.

im not sure if this issue existed earlier because i always used force hide background patch until now.

### Steps to reproduce

- include hide player overlay patch and enable it
- the player overlay does not not appear smoothly if you tap the player screen

### Relevant log output

```shell
.
```

### Screenshots or videos

HIDE PLAYER BUTTON BACKGROUND INCLUDED AND ENABLED

https://github.com/inotia00/ReVanced_Extended/assets/87489540/dcad3ff3-c79d-4a76-a3f3-312374237fb1

HIDE PLAYER BUTTON BACKGROUND INCLUDED BUT DISABLED

https://github.com/inotia00/ReVanced_Extended/assets/87489540/cca71a69-913c-452a-8b3f-45532626c9c0

### Device Environment

los20

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
This was why the force hide player button background patch was introduced, but it's been deprecated.

You can read more about it in https://github.com/inotia00/ReVanced_Extended/issues/1638#issuecomment-1789943531 and in https://github.com/inotia00/ReVanced_Extended/issues/569.

I'll wait for inotia00 to close this in case he wants to provide more information on the issue.

**Comment by inotia00** [comment]
sry I closed the issue by mistake

**Comment by inotia00** [comment]
I'll add the `Force hide player button background` patch again, and remove the `Hide player button background` patch

**Comment by Kuddus73** [comment]
Wasn't `Force hide player button background` patch deprecated?
If it isn't, why not keep both patches as before?

**Comment by inotia00** [comment]
I thought there was no need for duplicate patches to exist, so I `deperated` one of them and removed the patch.

The `Force hide player button background` patch is not buggy, and the `Hide player button background` patch is buggy.

Therefore, it is more appropriate to deperate the `Hide player button background`patch and restore the `Force hide player button background` patch.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.196.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.4)
