### ISSUE TITLE
bug: ads in shorts

### ISSUE THREAD

**Issue by kyoyacchi** [inotia00/ReVanced_Extended#1681]
### Type

Other

### Tools used

RVX Manager

### Application

18.43.45

### Bug description

Try scrolling down in shorts.

There are ads in shorts when i scroll down after some video.
I've enabled all options to hide ads. So..

### Steps to reproduce

1. Open Shorts
2. Scroll down till you see an ad video

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://kyoya.discowd.com/screen-20231112-154946.mp4

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`Hide video ads` patch only hides ads in general video

`Hide shorts ads` patch has not been implemented
