### ISSUE TITLE
feat(YouTub Meusic/Hide flyout panel): hide `Remove from playlist`

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1682]
### Application

YouTube Music

### Description

Nearly all options can be hidden from Flyout Menu, except "Remove from playlist". So, please add it.
![Screenshot_2023-11-12-18-38-24-08_0eaaacfb1e02f862bb18505a09b95933](https://github.com/inotia00/ReVanced_Extended/assets/91815107/837aa718-9c32-48c2-85f7-1a4c0ca334bb)
![Screenshot_2023-11-12-18-38-46-16_0eaaacfb1e02f862bb18505a09b95933](https://github.com/inotia00/ReVanced_Extended/assets/91815107/d59d768a-cf06-4996-a941-cb7440391bc9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.196.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.4)
