### ISSUE TITLE
feat(patch): DeArrow

### ISSUE THREAD

**Issue by aicynide** [inotia00/ReVanced_Extended#1683]
### Application

YouTube Music

### Issue

Ability to change youtube videos thumbnails and Titles

### Patch

All features of DeArrow
Currently rvx doesn't support changing Titles

### Motivation

Dearrow extension 

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
There are no video thumbnails or titles to change in YouTube Music

**Comment by inotia00** [comment]
Sorry but I don't accept new patch requests for YouTube
