### ISSUE TITLE
bug: Revanced Manager not showing YTM patch list nor option to patch after selecting APK

### ISSUE THREAD

**Issue by SleepDaemon** [inotia00/ReVanced_Extended#1684]
### Type

Other

### Tools used

RVX Manager

### Application

Latest

### Bug description

For YTM after selectin APK it should take me to screen where it shows lists of APK that are select along with a button called "patch". However, in the latest update v1.15.1, it doesn't take you there and shows the screen to pick which app to patch.

### Steps to reproduce

Just do the usual steps to patch with the manager

### Relevant log output

```shell
none
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/88533953/7ac9a414-684a-4155-998b-1537c8f0d540

### Device Environment

One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
Not sure how YT Music ended up being a split-APK, but nevertheless, download an [apk of YT Music](https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-27-53-release/#downloads) that is supported on your device (likely the arm64-v8a or armeabi-v7a architecture) and then select the apk from storage or install the apk and then select it from the app list.

**Comment by SleepDaemon** [comment]
> Not sure how YT Music ended up being a split-APK, but nevertheless, download an [apk of YT Music](https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-27-53-release/#downloads) that is supported on your device (likely the arm64-v8a or armeabi-v7a architecture) and then select the apk from storage or install the apk and then select it from the app list.
> 
> Edit: I see in the screen recording you tried selecting the ytm apk from storage but it didnt get selected. Try doing that again and then immediately switch to the settings tab and then back to the patcher tab.

I tried what you said in the Edit, didnt work or I am too slow cause you have to back out from that selection screen to show the navbar.

**Comment by KobeW50** [comment]
> I tried what you said in the Edit, didnt work or I am too slow cause you have to back out from that selection screen to show the navbar.

The navbar is supposed to be shown 🤷

![Screenshot_20231112_102832_RVX Manager.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/c54c2322-fe5a-4c1d-9e8f-579201ceae82)

Anyway, try downloading the ytm apk i linked, install it, and then select it from the app list.

**Comment by SleepDaemon** [comment]
> > I tried what you said in the Edit, didnt work or I am too slow cause you have to back out from that selection screen to show the navbar.
> 
> The navbar is supposed to be shown 🤷
> 
> ![Screenshot_20231112_102832_RVX Manager.jpg](https://user-images.githubusercontent.com/84587632/282308648-c54c2322-fe5a-4c1d-9e8f-579201ceae82.jpg)
> 
> Anyway, try downloading the ytm apk i linked, install it, and then select it from the app list.

No I meant this screen, no navbar. I have to tap back button to switch to settings tab.
![image](https://github.com/inotia00/ReVanced_Extended/assets/88533953/009117c1-d87e-497a-a0de-d6e1513e93ae)

**Comment by SleepDaemon** [comment]
I'll do what ya said, update YTM with the apk

**Comment by SleepDaemon** [comment]
do fix this tho
