### ISSUE TITLE
Channel profile photo not showing 

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1685]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v18.43.45

### Bug description

Channel profile photo is not showing, profile photo area is black.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![IMG_20231113_003414](https://github.com/inotia00/ReVanced_Extended/assets/117540245/93590e10-7013-4360-8d4e-00cdf6bd31ae)
![IMG_20231113_003342](https://github.com/inotia00/ReVanced_Extended/assets/117540245/b8bebecc-6616-4ab9-80b0-cb64b16a2558)
![IMG_20231113_003309](https://github.com/inotia00/ReVanced_Extended/assets/117540245/fba09072-428b-43e0-b5dc-a1e639ff943a)

### Solution

N/A

### Additional context

N/A

### Device Environment

Android 12 MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
check unpatched YouTube

**Comment by Mehedi5585** [comment]
> check unpatched YouTube

Unpatched YouTube working..  But patched YouTube some time profile photo showing & some time profile photo not showing.

**Comment by inotia00** [comment]
The issue is rarely reproduced even on unpatched YouTube
I don't know why either

It seems like an issue that Google needs to fix

**Comment by Mehedi5585** [comment]
> The issue is rarely reproduced even on unpatched YouTube I don't know why either
> 
> It seems like an issue that Google needs to fix

Okay dear, thanks for the information
