### ISSUE TITLE
bug(YouTube) : player flyout panels broken when using Samsung Dex

### ISSUE THREAD

**Issue by Lment** [inotia00/ReVanced_Extended#1687]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube v18.43.45

### Bug description

Hello.
Before any bug report I want to thank you deeply, for your codes and your codes alone have satisfied my needs.

I have found out that revanced - whether extended or not - have difficulties when it comes to keeping customized layout for video setting, particularly in Samsung S series tablets which supports the feature called Samsung Dex, some kind of dual booting system. And that Dex seems to be the reason of this bug.

In Revanced , touching video -> settings would result settings aligned in center, and it would have speed control, quality control, repeat control. When I turned Dex on and off, the settings _degrade_ to normal youtube - that is, clicking the settings button would result dropdown placed just below the button, and repeated playing is disabled.

Your codes added extra buttons to video layout, that acts as shortcut to repeated playing, and speed control. So even if settings dropdown malfunctions, there is still a workaround that mends this problem.

Could there be any way that layout is maintained even if I turn that Dex mode on and off?

### Steps to reproduce

Step 1. Prepare Samsung Tablets that supports Dex mode.
Step 2. Install Revanced Extended. Check whether video settings dropdown is aligned at center, and has feasible features.
Step 3. Turn Dex on and off
Step 4. Check video settings. It is now broken, setting dropdown degraded to non-Revanced youtube.

### Relevant log output

```shell
None available
```

### Screenshots or videos

![Screenshot_20231113_230454_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/26504920/817231f7-b599-4afa-9158-e31ea167818c)
![Screenshot_20231113_230635_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/26504920/769f0a85-3b1a-450b-9ea3-7817f5aae445)

The repeat slidebar does not work, since I am not subscribing Premium.

### Solution

Only Re-Installing fix issues until I turn on that Dex again.

### Additional context

No response

### Device Environment

Device : SM-X710
Android 13, One UI 5.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
change all the settings to off until the issue is no longer reproduced, and let me know which settings are the cause of the issue.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1705#issuecomment-1817675612
