### ISSUE TITLE
bug: Hide Suggested overlay video causes PIP buttons to change

### ISSUE THREAD

**Issue by Mhmodhaha** [inotia00/ReVanced_Extended#1688]
### Application

Youtube v18.43

### Bug description

Before all great thanks to inotia for his efforts 
My issue happenes when 
enabling hide Suggested video overlay and minimize the video (like in the attached screenshot)
The player button turned to other buttons not the usual ones 
This make it hard to play next video when it is minimized or playnig past video 

N.B:it not happens with all videos but it happens frequently mostly every 2 videos
![Screenshot_20231114_045434_One UI Home](https://github.com/inotia00/ReVanced_Extended/assets/141293135/3b38683c-91f6-4f09-a2c0-ffc99bc04e2a)

### Steps to reproduce

Already mentioned 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
I'm sorry, I'm having trouble understanding the bug you are encountering.

Can you please provide a screen recording of how it should be and a screen recording of how it is when the bug occurs?

**Comment by Mhmodhaha** [comment]
> I'm sorry, I'm having trouble understanding the bug you are encountering.
> 
> Can you please provide a screen recording of how it should be and a screen recording of how it is when the bug occurs?


https://github.com/inotia00/ReVanced_Extended/assets/141293135/283443e6-fa08-4e74-878b-a82daca800b5

**Comment by Mhmodhaha** [comment]
When the video ends the buttons have been changed

**Comment by KobeW50** [comment]
This also occurs on unpatched YouTube. Also, pressing the play button should make a new video play.
