### ISSUE TITLE
suggestion: <title>:  Use Lsposed

### ISSUE THREAD

**Issue by DGS7** [inotia00/ReVanced_Extended#1690]
### Application

YouTube

### Description

Hello inotia, Thank you for making this project possible. I would like you to make lsposed modules that can Batch YT and YT music for several reasons: 
1 - It will patch all current and future versions of YouTube or other applications.  
2 - lsposed modules can be used with those who do not have root via Lspatch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unfortunately, I'm not a ROOT user, and I've never used the LSPosed module.

If someone is ready to implement the project, just implement it.
At least I have no plans to support it

**Comment by DGS7** [comment]
You can use modules Lsposed For devices that do not have root, as I said,
or you can try rooting. It is a beautiful world .

في الأربعاء، 15 تشرين الثاني 2023, 12:40 م inotia00 <
***@***.***> كتب:
