### ISSUE TITLE
bug: <title>custom video resolution bug

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1691]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube v18.43.45

### Bug description

When we set custom video quality to 1440p or 2160p if any video we play that donsent has this video resolution will set to 360p or 480p.

### Steps to reproduce

Open youtube
Play video

### Relevant log output

```shell
.
```

### Solution

Make it set to 1080p or lower available resolution to video if  1440p or 2160p is not present.

### Additional context

Android 12, miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Adity1243** [comment]
Its strange bug some videos are working fine with this seetings but some videos 
set 360p or 480p at start. Some videos 
play 1080p correctly if 1440p is not present but after some time it sets to 360p or 480p  automatically.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1689

**Comment by Aryan-Chauhan** [comment]
Solution found for video quality not locking problem.

Clean-install v18.36.39

This version has no problem with quality locking + it has You tab (for people who want to solve their problem but also don't want to lose You tab).

**Comment by Adity1243** [comment]
> Solution found for video quality not locking problem.
> 
> Clean-install v18.36.39
> 
> This version has no problem with quality locking + it has You tab (for people who want to solve their problem but also don't want to lose You tab).

I solved this issue by spoofing version 18.33.40.
