### ISSUE TITLE
suggestion: <add `hide key concepts` patch within `YouTube/General/description` catagory>: 

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1694]
### Application

YouTube

### Description

Hides key concepts from video description that are auto generated by YouTube.

![Screenshot_2023-11-16-09-05-09-397_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/c535217e-9df0-42e5-adb8-3064c9515730)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
You can add `video_attribute` to the custom filter and it will hide the concept thumbnails in the description but won't hide it from the seekbar or the header in the description

![SmartSelect_20231115_205758_YT Extended.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/b2e8456c-c67a-4c9a-b03d-503afc17dcde)

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1694#issuecomment-1813652240
I'd still prefer a patch that would completely hide it from video descriptions!
