### ISSUE TITLE
bug(YouTube/Hide general ads): ads are still shown

### ISSUE THREAD

**Issue by AlpenMeister** [inotia00/ReVanced_Extended#1695]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 18.43.45
Patch v2.196.1

### Bug description

Normally it just leaves the area beneath the video black but now it display's ads. 

### Steps to reproduce

Enable related_video in general lay-out filter 

### Relevant log output

```shell
None
```

### Screenshots or videos

![Screenshot_20231116_090209_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/139682415/f2c830ae-7751-4c6d-9cc0-fd6fd24759d8)

### Device Environment

Android 13, Samsung S22 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Please patch again with [revanced-patches-v2.196.7](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.7) and let me know if the issue is still reproduced

**Comment by AlpenMeister** [comment]
> Please patch again with [revanced-patches-v2.196.7](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.7) and let me know if the issue is still reproduced

Reverting back to the legacy code fixed the issue, tested it with multiple video’s no adds being show anymore.

Thanks Inotia!
