### ISSUE TITLE
How to Hide this "Shop" option 

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1696]
### Application

YouTube

### Description

Revanced Extended/ Bottom player/ Hide shop button open the option but still don't hide shop button 
![Screenshot_2023-11-16-15-03-29-076-edit_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/117540245/8e5c7dde-cecb-4039-a9d2-c2dc256d7c7b)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
There is no such option, bottom player settings is about those buttons: like and dislike, save to library, shop and other. Inotia wont accept any feature request to add something like you said

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1620
