### ISSUE TITLE
feat(YouTube/Hide channel profile components): add `Hide 'For You' shelf` settings

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#1697]
### Application

YouTube

### Issue

This is not a patch request, but a description of the feature that will be introduce in the next release.

Translation contributors need to know exactly what this feature is, so I open an Issue to explain it.

### Patch

![For_You](https://github.com/inotia00/ReVanced_Extended/assets/108592928/1d441f30-180e-4f28-b1eb-6307a3dd6b80)

Google added new shelf called `For You` to the channel profile.

It is a shelf that recommends videos that users may be interesting on the channel, but some users may not need this.

Since `For You` shelf is A/B tests, it is not yet exposed to all users.

### Motivation

Some users may not need this.

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Please share screenshot how this looks in russian

**Comment by girshcatt** [comment]
Also you did a mistake and your string is: "Hide 'For You' shelf

**Comment by inotia00** [comment]
> Please share screenshot how this looks in russian

The string in Russian is:
```
Для вас
```
![Для вас](https://github.com/inotia00/ReVanced_Extended/assets/108592928/13180d82-5c7a-4e87-a179-7579c8f6c0c0)

> Also you did a mistake and your string is: "Hide 'For You' shelf

I don't remember exactly what string I uploaded to Crowdin, but it looks fine in settings

![Settings](https://github.com/inotia00/ReVanced_Extended/assets/108592928/710ba5f3-0817-49bc-9d1e-e65baca5f1ae)

**Comment by girshcatt** [comment]
revanced_hide_for_you_shelf_title string is: "Hide 'For You' shelf, for what here `"` in the begin
