### ISSUE TITLE
bug: RYD compact like button setting breaks dislike number

### ISSUE THREAD

**Issue by nintendork07** [inotia00/ReVanced_Extended#1698]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Youtube 18.45.38 (also present on 18.43.45)

### Bug description

Had the setting previously enabled before updating to the revanced extended patches v 2.196.1

### Steps to reproduce

Step 1. enable compact like button on Return Youtube Dislike setting
Step 2. play any video, dislike number is not shown

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20231116_123653_ReVanced](https://github.com/inotia00/ReVanced_Extended/assets/78343231/b7fa3a63-3191-4587-8d91-65d290b05100)

### Solution

None yet, just disabled the compact like button & it reverts to normal length but does show dislikes.

### Additional context

Did not occur before patches v 2.196.1

### Device Environment

Galaxy s23, oneui 6.0 (android 14)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1677
