### ISSUE TITLE
bug: Video gets on infinite loading right at the beginning or starts and a few seconds later goes into infinite loading.

### ISSUE THREAD

**Issue by italosouza09** [inotia00/ReVanced_Extended#170]
### Type

Error while patching

### Application

YouTube v17.49.37
YouTube v18.03.33

### Bug description

When you start a video, it does not run and is on an infinite load, the load never ends and or buffers.

In rare moments when starting a video, it runs for a few seconds and loads and the same happens reported above.

In early versions of vanced this bug occurred.

### Steps to reproduce

When you start a vídeo.

### Relevant log output

```shell
No logs
```

### Screenshots or videos

![Screenshot_20230125-093752_ReVanced Extended](https://user-images.githubusercontent.com/20961206/214565400-5fe93b44-ef18-4b7c-9490-fb0275563b2c.png)
![Screenshot_20230125-093800_ReVanced Extended](https://user-images.githubusercontent.com/20961206/214565411-868a6647-332e-429a-aec1-016ddb1db26d.png)

### Device Environment

One UI 4.1
Android 12
Patch 1/11/2022 Google play
Patch 1/10/2022 security

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
