### ISSUE TITLE
bug(YouTube/Hide suggestions shelf): does not working on latest patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1700]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

`Continue watching` and `Watch it again` sections shown on tablets, then after you go in apps menu and back you see much black space instead

### Steps to reproduce

Step 1. Include `Settings` patch
Step 2. Include `Hide suggestions shelf` patch
Step 3. Update home page before bug appears

### Relevant log output

```shell
:/
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/110785596/2fef967d-e881-4ae3-a89e-ce9efd904241

https://github.com/inotia00/ReVanced_Extended/assets/110785596/aae0b522-c24f-4513-9819-09a4230a38fb

### Additional context

My settings:
[ReVanced Extended_v18.29.38_2023-11-16.json](https://github.com/inotia00/ReVanced_Extended/files/13391809/ReVanced.Extended_v18.29.38_2023-11-16.json)

### Device Environment

Android 12, One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by 0frd** [comment]
Not only in table, alson on phone
![Screenshot_2023-11-28-16-49-50-468_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/72485140/6cd4dfa2-e066-439c-864f-9d37eb9fce87)

**Comment by girshcatt** [comment]
Bruh now i see `Watch it again` section too in 2.201.1 patches(

**Comment by girshcatt** [comment]
Also now i see only `Watch it again`... not `Continue watching`, i will test it 10 minutes more and edit issue

**Comment by girshcatt** [comment]
No, i saw `Continue watching` a minute ago, it means that problem became bigger

**Comment by inotia00** [comment]
I'd like to debug this issue, but for some reason my Google account no longer shows the suggestions shelf in my home feed

**Comment by girshcatt** [comment]
Bruh it seems that patch no longer work everywhere, i just opened yt on my phone and saw `Breaking news` shelf(((

**Comment by inotia00** [comment]
After using a vpn, I was able to make the breaking news shelf shown

But the patch works fine

**Comment by inotia00** [comment]
In [revanced-patches-v2.201.7](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.7), the `Hide suggestions shelf` patch has been moved to `Experimental Flags`

In other words, the `Hide suggestions shelf` patch has a very high possibility of bugs occurring, and is provided for users who are aware of this and will use it

Additionally, you can now choose how to identify `Hide suggestions shelf`

Until now, it has been identified through `browse id`, but in [revanced-patches-v2.201.7](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.7), it can be identified through `current tab`

Each known issue is different, so use your preferred method
