### ISSUE TITLE
bug: Category bar in feed Not working

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1701]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v18.45.38

### Bug description

![Screenshot_2023-11-17-20-03-12-828_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/117540245/763bf681-714d-4095-882a-794b6e1f62fe)
Disable Hide category bar in feed , but category bar not showing home feed

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-11-17-19-55-08-163_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/117540245/8e47ce07-0ed3-4d50-a8f7-c2184d00389c)

### Solution

N/A

### Additional context

N/A

### Device Environment

Android12 MIUI13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by girshcatt** [comment]
Try to do small swipe down, because unpatched youtube im most of situations wont let you see category bar before you will swipe down

**Comment by hphp22f** [comment]
> Try to do small swipe down, because unpatched youtube im most of situations wont let you see category bar before you will swipe down

thanks dear

**Comment by inotia00** [comment]
tbh this is the old bug of stock YouTube
Even if you report an issue here, the issue will continue unless Google fix it
