### ISSUE TITLE
Hide animated button background

### ISSUE THREAD

**Issue by hphp22f** [inotia00/ReVanced_Extended#1702]
### Application

YouTube

### Description

Hide animated button background. how to work this option..or how to enable \ disabe this

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
hide this

![231017471-4cc88681-2a25-4dcd-a850-b3aa937ba7a2](https://github.com/inotia00/ReVanced_Extended/assets/108592928/646fabcf-e039-4bd1-ab9a-7f6a561fd917)


Since settings do not exist, you can enable/disable them by including or excluding patches.
