### ISSUE TITLE
suggestion: add note to patch release changelog that `Shorts Outline Component` isn't supported on 18.45.41

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1703]
### Application

YouTube

### Description

Add a note to the recent patch release changelog that 18.45.41 isn't a supported version for all patches.

This will help avoid confusion for users who read the changelog and open the manager which still suggests 18.44.41

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed

**Comment by inotia00** [comment]
If you are using RVX Manager, just force close the app and relaunch it

If you are using Revancify, you should remove the tool and fetch it again
