### ISSUE TITLE
bug: <RVX Music Library Issue>

### ISSUE THREAD

**Issue by Stromansoor** [inotia00/ReVanced_Extended#1704]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Music v6.28.52

### Bug description

When spoofing the app version to 4.27.53 (I'm in Canada), the library tab starts to malfunction.

When I click on the library tab, the app doesn't "highlight" the library tab (when you switch between the tabs at the bottom, it changes the icon to white instead of an outline of the icon).

If I'm in my library and click, for example, playlists, I get stuck there until I reload the app. I can't return to the library to get to albums, songs, etc. Pressing the back button on the device exits the app. I can still access the home and explore tabs but the library remains stuck on whatever I selected earlier until I close the app.

### Steps to reproduce

Spoof app version to 4.27.53
Click Library
Select Playlists
From there, attempt to get back to the primary library screen (where you selected playlists originally above)

### Relevant log output

```shell
N/A. Sorry, I'm not technical enough to get the logs.
```

### Device Environment

Android 13, One UI version 5.1.1, Samsung Galaxy Z Fold4 unlocked.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1323
