### ISSUE TITLE
bug(YouTube): `Additional settings` toggles stays frozen after using them

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1705]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v18.45.41

### Bug description

On any YouTube video, when changing any of the additional setting toggles, it works and selected feature changes but the toggle stays frozen on its current state no matter if you are on full screen or not.

### Steps to reproduce

1. Patch YouTube with latest patches in RVX manager
2. Open any video and select settings and go to additional settings
3. Select any of the toggles and check if the toggle gets frozen or not.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/107706560/82eb98a9-dce4-4482-880c-f395ff5c0efc

### Solution

Fix said toggles to function properly

### Additional context

Using Xiaomi 11T pro phone

### Device Environment

Android 13 MIUI14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Exclude patches one by one until the issue is not reproduced.
And please let me know which patch is the cause of the issue

**Comment by Rairof** [comment]
Would also appreciate if you could try on your own end with my settings as you might be able to point of the issue better than me as I don't know what I'm actually looking for.

[YouTube_v18.44.41_2023-11-17.json](https://github.com/inotia00/ReVanced_Extended/files/13400295/YouTube_v18.44.41_2023-11-17.json)

**Comment by KobeW50** [comment]
This is a bug on unpatched YouTube.

https://github.com/inotia00/ReVanced_Extended/assets/84587632/64ce6845-2a1f-48ff-948b-be046198ee3c

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1705#issuecomment-1817675612

Oh, makes sense then. YouTube should really focus on fixing such small bugs more then going after adblockers. Thanks I'll be closing this as completed then. 👍
