### ISSUE TITLE
question: <YouTube>:  Hide podcast sections

### ISSUE THREAD

**Issue by hphp22f** [inotia00/ReVanced_Extended#1706]
### Application

YouTube

### Description

How to Work Hide podcast sections

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![deacriptions](https://github.com/inotia00/ReVanced_Extended/assets/108592928/1fef06eb-2f31-4c7e-a1d0-435a8f2b2ac4)

some videos have `Explore the podcast` in the description
(e.g. https://youtu.be/r4wLXNydzeY)

hide this

**Comment by hphp22f** [comment]
Thanks for the information
