### ISSUE TITLE
bug: Video Quality Downgrades

### ISSUE THREAD

**Issue by DevZer0ne** [inotia00/ReVanced_Extended#1709]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v18.45.41 Rooted. But it has been happening in previous versions as well.

### Bug description

The quality of videos automatically gets downgraded to 480p even if it is set to 4K for both WiFi and Data. Settings are all good, videos starts playing at 720p after about few seconds lets say under 10 seconds it changes to 480p instead of going up to 1080p or 4K.

It only happens in videos which has 1080p Premium Bitrate option available under video quality settings. Normal videos which doesn't have this option available plays at 4K quality by default.

### Steps to reproduce

Just play any video which has 1080p Premium Bitrate option available under video quality settings.

### Relevant log output

```shell
I don't have logs.
```

### Screenshots or videos

![Screenshot_2023-11-19-10-10-33-765_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/128327616/d9f024f9-7150-42d3-8cc4-5e8042713fa2)
![Screenshot_2023-11-19-10-10-54-283_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/128327616/74ab5c8f-6a58-4334-bb38-ef98abeba32a)
![Screenshot_2023-11-19-10-11-04-518_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/128327616/12f36881-4a39-47ae-ae5c-28f8fa8a2711)
![Screenshot_2023-11-19-10-11-21-642_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/128327616/9298648f-1a10-48fe-95af-743a4e6fbfb9)
![Screenshot_2023-11-19-10-11-56-751_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/128327616/d1ebae8f-0180-4ef0-bf46-df02768359f1)

### Device Environment

Android 13, Miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1689

**Comment by Aryan-Chauhan** [comment]
Solution found for video quality not locking problem.

Clean-install v18.36.39

This version has no problem with quality locking + it has You tab (for people who want to solve their problem but also don't want to lose You tab).
