### ISSUE TITLE
Update size

### ISSUE THREAD

**Issue by suryaraj086** [inotia00/ReVanced_Extended#171]
### Application

YouTube

### Issue

Can u add inapp update.And we had to download whole app to update.Instead make updates like playstore and make it inapp update

### Patch

Inapp low download size updates.

### Motivation

It would be more useful for everyone.Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I don't distribute apk
Read the documentations again
