### ISSUE TITLE
suggestion(YouTube Music): Add dependencies for two player settings

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#1710]
### Application

YouTube Music

### Description

Add dependencies between `new player background` and `old player layout`. This will prevent constant app crashes if the user accidentally tries to turn on these both toggles at once.

![Screenshot_20231119_204010_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/daba6521-bac0-45a2-8815-d70d49e493c8)
![Screenshot_20231119_203924_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/51eecfad-c6c7-414c-8b40-d4b324c114f3)
![Screenshot_20231119_204235_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/e676510b-3834-40aa-949f-f1604df1506d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unfortunately this is not possible

Due to limitations in the way patches are implemented in YT Music, it is impossible to add dependencies to the switch as desired like on YouTube.

Ideally, the `Enable old player layout` patch would be removed, but user backlash is expected in this case.
