### ISSUE TITLE
bug: "Hide suggested video overlay" doesn't work in minimised player

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1711]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 18.45.41
Patches latest

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/130296934/1561cab6-4b43-4cea-bc21-5ac877df7f96

![__20231119_230255](https://github.com/inotia00/ReVanced_Extended/assets/130296934/4b07ee1b-78f4-4c80-8355-14f192b14414)

### Steps to reproduce

Shown in the video

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
That's why the `Hide suggested video overlay` patch is designated as `Experimental Flags`

**Comment by federicogith** [comment]
> That's why the `Hide suggested video overlay` patch is designated as `Experimental Flags`

What does that mean?
(Is it not a bug?
Is it supposed to work like that?)

**Comment by inotia00** [comment]
![Experimental](https://github.com/inotia00/ReVanced_Extended/assets/108592928/79af8e4c-1fac-4e65-87f8-2a6a7513ead6)

As shown in the attached screenshot, `Hide suggested video overlay` belongs to the `Experimental Flags` category.

Patches belonging to `Experimental Flags` have a high probability of causing bugs and are likely to be removed at any time.

It is provided for users who are aware of this and will use it.
