### ISSUE TITLE
suggestion(YouTube/Player) : Add outline icons for upper section in player.

### ISSUE THREAD

**Issue by Shawonn19** [inotia00/ReVanced_Extended#1712]
### Application

YouTube

### Description

![Screenshot_20231120-121644~2](https://github.com/inotia00/ReVanced_Extended/assets/116424330/ab0fca1a-9f68-4d22-ba04-9a876be00d85)

The upper 2 icons are bold while the bottom 2 icons are minimal outline. Can't unsee the inconsistenty.
I know it's YouTube's fault, but any way of fixing it? Like making the upper icons minimal outline? It will look better and consistent.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I don't receive any new patch requests from YouTube
