### ISSUE TITLE
bug(Youtube/SponsorBlock): Skipped SponsorBlock segments at the end of a video does not advance to the next video in a playlist

### ISSUE THREAD

**Issue by bigyihsuan** [inotia00/ReVanced_Extended#1714]
### Type

Error at runtime

### Tools used

CLI

### Application

Youtube 18.45.38
Revanced Patches 2.196.4
Revanced Integrations 0.121.4

### Bug description

I was playing through videos on my Watch Later playlist and encountered videos that had endcard segments ending at the end of the video. Then, when the segment was skipped, it did not advance to the next video, and I had to manually 

### Steps to reproduce

1. Have SponsorBlock turned on.
2. Have segment skipping turned on.
3. Have automatically skipping end card turned on.
4. Find a video that has an end card segment.
5. Put it onto a playlist before another video.
6. Start playing the video with the end card segment in the playlist.
7. Let the video play and skip the end card.
8. The next video will not be played; the video player will be stuck on the end of the video with the end card until you manually change the video.

### Relevant log output

```shell
None
```

### Screenshots or videos

https://www.youtube.com/watch?v=3yKPa28Fojc

### Additional context

Revanced Extended settings: [ReVanced Extended_v18.45.38_2023-11-20 pretty.json](https://github.com/inotia00/ReVanced_Extended/files/13415896/ReVanced.Extended_v18.45.38_2023-11-20.pretty.json)

### Device Environment

- Oneplus 7
- Android 12, rooted

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.199.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.199.1)

**Comment by inotia00** [comment]
Duplicated issues have already been opened: https://github.com/inotia00/ReVanced_Extended/issues/1718
