### ISSUE TITLE
question: How to change like and dislikes buttons' appearance: 

### ISSUE THREAD

**Issue by aljustiet** [inotia00/ReVanced_Extended#1716]
### Application

YouTube

### Description

```To make look like this:``` 
![image](https://github.com/inotia00/ReVanced_Extended/assets/114720383/ac7f9bc2-2ff0-47b5-b94f-c10936b9177a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You can't
