### ISSUE TITLE
bug (Youtube/Sponsorblock): The video refused to end when autoplay isn't enabled and just skipped a segment at the end of the video

### ISSUE THREAD

**Issue by Raven-621** [inotia00/ReVanced_Extended#1718]
### Type

Other

### Tools used

rvx-builder

### Application

Youtube 18.45.41

### Bug description

The video refused to end (just rewinded 1 or 2 seconds) under the condition: 
1) Autoplay is off (confirmed it was off and i turned on remove suggested video overlay, which would kill autoplay anyway)
2) Sponsorblock is active and there's a skippable segment at the end of the video

### Steps to reproduce

1) Make sure autoplay is off
2) Sponsorblock is active
3) Watch a video where's there's a skippable sponsorblock segment at the end of the video (here's an example video: https://youtu.be/O5myIiXLqug?si=M2JmvUu05Z32L8iL)
4) After the segment is skipped, the video just refused to end, rewinded 1 or 2 seconds back, and repeat

### Relevant log output

```shell
None
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/141109979/641f24ef-4651-4d7b-b76a-132e9e7aefe9

### Device Environment

Android 10 (OneUI 2.0), Samsung Galaxy A6 Plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
![Patches Version](https://github.com/inotia00/ReVanced_Extended/assets/108592928/52265d87-7c41-4f09-b0be-11bcbf4c4373)

I am using revanced-patches-2.199.1, but the issue does not reproduce.

What version of revanced-patches are you using?

You can check it in the following path:
Settings > ReVanced Extended > Miscellaneous > Patches Information

**Comment by Raven-621** [comment]
![Screenshot_20231121-182429_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/141109979/b7a6add0-6ab0-46c5-b696-b0f63085baa0)

It is 2.199.1 i'm using rn. I don't have such problem in previous version of patches.
As for all of the rvx settings i used (that's different from default setting):
Fullscreen:
- Hide end screen overlay is on

General:
- Disable forced auto captions is on
- Hide mix playlist is on
- Hide suggestion shelf is on
- Hide community posts in home feed is off
- Hide movies shelf is on

Misc.:
- Bypass ambient mode restriction is on
- Enable opus codec is on

Navigation:
- Hide create button is off
- Switch create with notifications button is off

Overlay buttons:
- Show copy video URL button is off
- Hook download button is on (with Seal option chosen)

Player:
- Hide end screen cards is on
- Hide info cards is on
- Hide suggested videos overlay is on

Swipe controls:
- Enable brightness gesture is off
- Enable volume gesture is off

Video:
- Default video quality (mobile): 480p
- Default video quality (Wi-Fi): 1080p

**Comment by inotia00** [comment]
Could you please share at least 2 or 3 URLs of videos where this issue is reproduced?
I think a fix will be possible only if there are enough test samples.

**Comment by inotia00** [comment]
nvm this issue was reproducible in some videos in my playlist
It will be fixed in the next release

**Comment by Raven-621** [comment]
https://youtu.be/OkCX8d8WSOg?si=3xGM6SY0dHQogHvO

https://youtu.be/GXT46osICdY?si=CVnDO46l9pQQzjEv

Here's some. Yeah, it was inconsistent. Some videos ends just fine, others have this problem.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)
