### ISSUE TITLE
bug(YouTube/Spoof app version): Enabling spoofing hides playlists in the library section 

### ISSUE THREAD

**Issue by eqlivox** [inotia00/ReVanced_Extended#1719]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v18.39.41 with v2.199.1 patches

### Bug description

Enabling spoof app version and choosing 17.41.37 as target version leads to all playlists in the library section being completely hidden

### Steps to reproduce

1. Enable spoof app version
2. Choose 17.41.37 as target version
3. Go to the library section 

### Relevant log output

```shell
Don't have one
```

### Solution

Disable spoof app version or choose newer target version 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
`Spoof app version` belongs to the `Experimental Flags` category.

Patches belonging to `Experimental Flags` have a high probability of causing bugs and are likely to be removed at any time.

It is provided for users who are aware of this and will use it.
