### ISSUE TITLE
question(YouTube): does 18.38.45 version exist?

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1720]
### Application

YouTube

### Description

Does 18.38.45 version exist? You added 18.38.45 in spoof versions list, but i cant see such version in apkmirror
![Screenshot_20231121_174626_Chrome](https://github.com/inotia00/ReVanced_Extended/assets/110785596/7606b77c-0f79-4475-a9f2-2dd7ad15df46)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is a valid version but not uploaded to APKMirror
https://apkcombo.com/youtube/com.google.android.youtube/download/phone-18.38.45-apk
