### ISSUE TITLE
question: <YouTube>: How to hide this option 

### ISSUE THREAD

**Issue by hphp22f** [inotia00/ReVanced_Extended#1721]
### Application

YouTube

### Description

![IMG_20231122_012200](https://github.com/inotia00/ReVanced_Extended/assets/151181919/7cef6fc5-72d6-4e82-9e1c-65dbe2c45114)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
There is no such option, but by typing `account_header` in custom filter you can hide accout header entirely

**Comment by KobeW50** [comment]
Alternatively, you can add `ScrollableContainerType` to the custom filter. It will make it like this:

![Screenshot_20231121_150936_YT Extended.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/cad6ab72-f8d7-4920-9a10-063fe8ce8d97)

But it will also hide the soundtrack info at the bottom of shorts and the menu when you press the "Create" button (in the navigation bar or the camera icon near the search bar) will be completely broken. There may be other things that are unintentionally hidden that I'm not aware of.
