### ISSUE TITLE
New patches version not showing om rvx manager

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [inotia00/ReVanced_Extended#1722]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Rvx manager 1.15.1

### Bug description

When i opened the app and i saw in your github that you released a new version of revanced-patches and integrations, the dashboard section on both "patches" and "revanced manager" sections the loading caption get freezed and the app get unuseful

### Steps to reproduce

Open the app

### Relevant log output

Don't related

### Screenshots or videos

I didn't take screenshots i just tried to solve it my self and didn't worked

### Solution

I don't know

### Additional context

Idk if this is temporary error and it's already fixed, i'll check on the manager to see if now is all right

### Device Environment

Android 12

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by soyDESKTOP68A2MRFT** [comment]
I noticed that actually, the new patches version is showing, but the rvx supported version didn't changed

**Comment by KobeW50** [comment]
> I noticed that actually, the new patches version is showing, but the rvx supported version didn't changed

The supported versions didn't change in the most recent patch release.

The manager should suggest 18.45.41 for YT and 6.28.52 for YT Music
