### ISSUE TITLE
bug: <YouTube/ shorts player Play⏸️/Pause▶️ issue>

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1724]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v18.45.41

### Bug description

When I play the video the pause icon shows, and when I pause the video the play icon shows.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/117540245/fdecf9c6-bbfb-4886-b2a3-dc3ea999bec5

### Solution

N/A

### Additional context

N/A

### Device Environment

Android 12/ Miui13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [ ] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This issue often reproduces on unpatched YouTube, so Google needs to fix it.
