### ISSUE TITLE
suggestion: <adding universal patches and rest of YouTube patches in RVX with other apps support>: 

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1725]
### Application

Other

### Description

Are there any plans to add universal patches ReVanced has and other patches that normal ReVanced YouTube has but RVX YouTube doesn't have? I know and understand some of them aren't possible but still wanted to suggest it since some patches there are really useful.

Here are the patches that aren't available in RVX but available in ReVanced. I don't know why they aren't added but would be nice if they could be added to RVX too along with more apps support that ReVanced supports.
![IMG_20231123_101806](https://github.com/inotia00/ReVanced_Extended/assets/107706560/7e125b84-0041-414d-9584-ca75dadc70a8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Bypassing URL redirects already exist in YT RVX. The patch is called `Enable open links directly` and the settings for it is within the Miscellaneous settings within YT RVX.

Also the custom light and dark theme exists for YT RVX.

**Comment by inotia00** [comment]
Most of the new features added to ReVanced over the past year are features that already existed in RVX.

Most of the features of ReVanced that are not implemented in RVX were not implemented because they were unnecessary or had a very high risk of causing bugs.

If you need them just use the official ReVanced
