### ISSUE TITLE
bug(YouTube): Buttons bug in PiP when videos finish

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1726]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 18.45.41
Patches 2.199.1

### Bug description

When a video finishes in PiP mode it shows these buttons now:
![ _20231123_034112](https://github.com/inotia00/ReVanced_Extended/assets/127908708/58435982-cee2-4412-9605-2837a7151a2b)
But before it used to show these buttons:
![ _20231123_034149](https://github.com/inotia00/ReVanced_Extended/assets/127908708/6a77713c-7a3d-439e-a8a8-acff6e3c8b4e)

### Steps to reproduce

https://github.com/inotia00/ReVanced_Extended/assets/127908708/c1a04de0-9288-4469-a08c-113e4619ff18

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
This occurs on unpatched YT.

Related issue: https://github.com/inotia00/ReVanced_Extended/issues/1688
