### ISSUE TITLE
bug(YouTube): "MicroG does not run in the background" toast appears when MicroG isn't installed

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1727]
### Type

Error at runtime

### Tools used

Revancify

### Application

YT RVX v18.45.38

### Bug description

When MicroG is not installed, all toasts regarding MicroG will appear. 

* "MicroG is not found."
* "Please install MicroG. "
* "MicroG does not run in the background."

 The third one shouldn't appear if the first 2 appear.

### Steps to reproduce

Open YT RVX when MicroG is not installed

### Relevant log output

```shell
NA
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/84587632/db838181-65f3-4228-bc7e-2062025933bb

### Solution

In YT ReVanced the toasts seem to work fine (although I can't test for MicroG failing to run in the background). Perhaps adapt the [ReVanced implementation](https://github.com/ReVanced/revanced-integrations/blob/main/app/src/main/java/app/revanced/integrations/patches/MicroGSupport.java#L36-L49).

### Device Environment

Android 13
S22+
One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)

**Comment by ggafoor** [comment]
https://revanced.to/youtube/#download-apk

This the reall revanced website you installed another feke website application
![Screenshot_2023-11-29-23-41-20-43_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/inotia00/ReVanced_Extended/assets/82312786/1aa04db2-1490-4e2b-8524-57b3807ea363)
Icon is orginal revanced youtube application

**Comment by KobeW50** [comment]
> This the reall revanced website you installed another feke website application

No, you are incorrect. That website is absolutely non-official and potentially malicious. Please read the official patching methods in inotia00's documentation repository.

Revanced Extended apps are not distributed by any official site due to legal reasons. This is why you must patch them yourself.

**Comment by ggafoor** [comment]
> > This the reall revanced website you installed another feke website application
> 
> That website is absolutely non-official and potentially malicious. Please read the [official patching methods in inotia00's documentation repository](https://github.com/inotia00/revanced-documentation) and the [FaQ in the subreddit](https://www.reddit.com/r/revancedextended/wiki/faq/)
> 
> Revanced Extended apps are not distributed by any official site due to legal reasons. This is why you must patch them yourself.

How to update?

**Comment by KobeW50** [comment]
> How to update?

I'm assuming you are asking about updating YT ReVanced Extended. 

You won't be able to update the app that you got from that site unless you get the updated versions from that site (which we do not recommend) or if they provide the keystore file they use (which is unlikely).

I suggest patching your own YT ReVanced Extended with the RVX Manager using the guide in the documentation i linked above or one of the guides linked in the subreddit wiki. If you want to update YT ReVanced Extended that you patched yourself, you can find details about updating the Updating ReVanced Extended section in [this guide](https://github.com/ReVanced-Extended-Community/Community-Guides/blob/main/general-guides/community-wiki/yt-guide.md#updating-revanced-extended)

**Comment by ggafoor** [comment]
![Screenshot_2023-12-01-07-43-38-97_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/inotia00/ReVanced_Extended/assets/82312786/9d7d1e09-1148-412c-9bb7-b427d93f7829)
This is the current problem how to fix, ask access all Gmail ids

**Comment by KobeW50** [comment]
> This is the current problem how to fix, ask access all Gmail ids

Uninstall that MicroG and use [Vanced MicroG](https://github.com/inotia00/VancedMicroG/releases/tag/v0.2.27.230755)

If you need any more assistance, please ask in the [Subreddit](https://www.reddit.com/r/revancedextended) or [Telegram group](https://t.me/revanced_extended)
