### ISSUE TITLE
Sponsorblock Endcard Segment Ends Prematurely.

### ISSUE THREAD

**Issue by aleks01100001** [inotia00/ReVanced_Extended#1728]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.45.41

### Bug description

When attempting to add an Endcard/Credits segment to the end of a video, the finished segment does not align with the actual end of the video. Instead, it ends approximately 100 to 200 milliseconds sooner.

### Steps to reproduce

Step 1: Open a video
Step 2: Add the Endcard segment to the end of the video
Step 3:???

### Relevant log output

```shell
The sponsorblock patch patched successfully
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/49501241/b762a4bc-72ed-4532-8a4f-7569c202acd1

### Additional context

As you can see in the screen recording. I have added all the segments to the video, and they appear correctly. However, the Endcard segment ends slightly prematurely, approximately 100 to 200 ms before the actual end of the video.

### Device Environment

Android 14, OneUI 6

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1718
