### ISSUE TITLE
bug: The download button keeps loading endlessly

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1729]
### Type

Other

### Tools used

Revancify

### Application

Youtube 18.45.41 

### Bug description

While playing a video the download arrow button continues to load...and does not appear.

### Steps to reproduce

Just play a video in portrait mode

### Relevant log output

```shell
Na
```

### Screenshots or videos

![IMG_20231123_223545](https://github.com/inotia00/ReVanced_Extended/assets/125223735/3ee24696-5341-4dec-bf90-dbe76906efd7)

### Solution

Na

### Additional context

Na

### Device Environment

Android 13
Miui 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
YouTube issue

**Comment by jhon1282** [comment]
> YouTube issue

I apologize but on YouTube stock same version the problem is not present.
I tried before opening the report 🤔

**Comment by inotia00** [comment]
1. Switch to Incognito mode on stock YouTube
2. The same issue is reproduced
