### ISSUE TITLE
feat(patch): Changing the codec to VP9

### ISSUE THREAD

**Issue by sks2012** [inotia00/ReVanced_Extended#173]
### Application

YouTube

### Issue

Ability to change the codec to VP9 in the settings.

### Patch

VP9, saves a lot of mobile Internet traffic.
I think a lot of people would be happy to have this feature, which Vanced has.

### Motivation

VP9, saves a lot of mobile Internet traffic.
I think a lot of people would be happy with this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in revnaced-patches-v2.157.1

**Comment by Spacellary** [comment]
Awesome stuff!

**Comment by Xgangsa** [comment]
Good job
