### ISSUE TITLE
bug: <YouTube/Video>`Default video quality` not working

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1730]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v18.45.41

### Bug description

Setting default video quality on both wifi and mobile does nothing and videos keep playing at 480p.

### Steps to reproduce

1. Patch YouTube with latest patches.
2. Set default video quality to any specific quality.
3. Watch a video and check quality.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-11-24-09-17-52-781_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/5684eea2-e536-4dba-b8d3-a429e62c4498)

![Screenshot_2023-11-24-09-17-31-707_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/abed2b06-adb9-4176-beea-6236aea903ab)

### Solution

Fix default quality patch.

### Additional context

Using Xiaomi 11T pro

### Device Environment

Android 13 MIUI 14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1689

**Comment by Aryan-Chauhan** [comment]
Solution found for video quality not locking problem.

Clean-install v18.36.39

This version has no problem with quality locking + it has You tab (for people who want to solve their problem but also don't want to lose You tab).

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1730#issuecomment-1826178314
That's not solution, that's preventing the issue. I'd not like to downgrade from 18.45.41 to 18.36.39 for just one but really useful patch not working.
Would love if @inotia00 could find an actual fix for it hopefully soon. Thanks for your response either way.

**Comment by inotia00** [comment]
I already answered

it's not a bug
Because the same issue is reproduced on the latest unpatched YouTube as well.

This is just a change to the way Google handles default video quality on YouTube.
(Even on unpatched YouTube, if you change the video quality immediately after the video starts, it will take effect after 10 seconds, and can be checked through the `Stats for nerd` setting)

This is why I do not treat this issue as a bug

Whether you like it or not, you'll have to adapt to the way Google changes things.

If you prefer the old default video quality, just stick with YouTube v18.38.44 or earlier.

YouTube v18.38.44 or earlier is also a supported version.

**Comment by Rairof** [comment]
Oh didn't knew it was a Google change. That sucks. They're making everything worse. Thanks for the clarification and I'll stick with 18.38.44 then

**Comment by NMBlanco** [comment]
Sadly downgrading to 18.38.44 and following the instructions doesn't fix the issue anymore. It's now on every version and seems to be server sided. I tried any YouTube version until 18.35.36, but the issue remains.

**Comment by Aryan-Chauhan** [comment]
> Sadly downgrading to 18.38.44 and following the instructions doesn't fix the issue anymore. It's now on every version and seems to be server sided. I tried any YouTube version until 18.35.36, but the issue remains.

Fortunately, things are working fine for me as of yet, on v18.38.44 (latest patches, of course).

Will edit my comment if I start facing quality-latching issues on v18.38.44
