### ISSUE TITLE
question: Today I did a clean install and a new button appears. Does anyone know why?

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1731]
### Application

YouTube

### Description

![IMG_20231124_111928](https://github.com/inotia00/ReVanced_Extended/assets/125223735/70479450-c95d-46ff-b2d0-b4b4373192b4)

https://github.com/inotia00/ReVanced_Extended/assets/125223735/83e6d968-93e0-413d-b7e8-9cbbaa943567

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
It is [a/b testing](https://www.optimizely.com/optimization-glossary/ab-testing/#:~:text=A%2FB%20testing%20(also%20known,determine%20which%20one%20performs%20better.) from YouTube. You can try spoofing to an older version, use a different account, or patch a slightly older version. All the supported YT versions can be found in the README of inotia00's patches repository.
