### ISSUE TITLE
question(YouTube): what `Hide shopping links` option do?

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1732]
### Application

YouTube

### Description

What `Hide shopping links` option do? I need an example of shopping link

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I don't know either
Merged by ReVanced Team https://github.com/ReVanced/revanced-patches/commit/0c875a106308ae9747ae998d75b84db1c336762b

**Comment by girshcatt** [comment]
I found a video with shopping links, maybe it is right what we saying about? https://youtu.be/vaIgyRoUkQI?si=kqFswhJM94PYEXDd
