### ISSUE TITLE
bug(YouTube/Enable wide search bar): `Enable wide search bar` patch restores the old style search bar

### ISSUE THREAD

**Issue by kyoyacchi** [inotia00/ReVanced_Extended#1733]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 18.45.41

### Bug description

I discovered this bug when i enabled wide search bar option.

### Steps to reproduce

1. Go to Revanced Extended from Settings.
2. Go to General
3. Enable Wide Search Bar (turn it on)
4. Restart the app.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

This is without the wide search bar

[w/o wide sb](https://cdn.discordapp.com/attachments/871133764410019890/1178017047247065118/Screenshot_20231125-195839.jpg?ex=65749cde&is=656227de&hm=6f1ab7c4c959b1ec11db4697a85dd93498839ff9bfa7db5ae50129806a1baa5b&)

This is the search bar on the stock YouTube

[YouTube](https://i.redd.it/6dxlrf630i2c1.jpg)

And this is the RVX's when user enables wide search bar option.
[RVX](https://cdn.discordapp.com/attachments/871133764410019890/1178005717618262126/IMG-20231125-WA0002.jpg)

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
this is not a bug

**Comment by kyoyacchi** [comment]
> this is not a bug

Then what should i do to have that apperance?

**Comment by inotia00** [comment]
These are A/B tests
I have two RVXs installed on my device, one looks like the first and the other looks like the second.

**Comment by inotia00** [comment]
nvm I'm currently working on merging the official ReVanced source, and in the process I've realized that there was a mistake in my code

The reason I thought of this as an A/B test is that my primary RVX was using a sufficiently old patch that it seemed to be free from this issue
(It's common to think that developers will always use the latest build, but this isn't the case)

Anyway, I will reopen the issue as it is a valid issue

Thanks for reaching here

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)
