### ISSUE TITLE
End screen overlay bug

### ISSUE THREAD

**Issue by thedogismurdered** [inotia00/ReVanced_Extended#1734]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

18.43.45/ Latest

### Bug description

When in fullscreen, end screen overlay doesn't display the video cards. Tried including the patch and turning it off from the settings and also excluding the patch. 

### Steps to reproduce

Step 1: End screen overlay patch excluded/ included and turned off settings
Step 2: Enter fullscreen and stay in fullscreen until the end of the steps. 
Step 3: Wait for the video to complete
Step 4: 99.99% of the times, it would work as intended after the first video finishes. The cards will pop up from the bottom after the video ends. Select any video from those cards and let the video finish.
Step 5: The cards that popped from the bottom wouldn't pop up until you slide up.

### Relevant log output

```shell
NA
```

### Screenshots or videos

![Screenshot_20231126-001348__01](https://github.com/inotia00/ReVanced_Extended/assets/150788169/ce7bdc25-e2ff-44ba-b3c5-c8789196afb6)
![Screenshot_20231125-235812__01](https://github.com/inotia00/ReVanced_Extended/assets/150788169/e7de1f77-5b94-4e18-a53c-0e0ab74c02ef)

### Device Environment

Android 10/ OOS10 Non-root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by thedogismurdered** [comment]
Adding a video clip. 

https://github.com/inotia00/ReVanced_Extended/assets/150788169/8a234a45-5cbe-43f7-8108-6eee2e079ef9

**Comment by inotia00** [comment]
Exclude patches one by one until the issue is not reproduced.
And please let me know which patch is the cause of the issue

**Comment by thedogismurdered** [comment]
Ok. So it looks like it's a side effect of the 'Hide suggested video overlay' patch. With that disabled/ on vanilla YT, once the video ends, a suggested video pops up. When in fullscreen, if we either tap on x or close, the end screen overlay  cards from the bottom automatically pop up. But the question is, with the 'Hide suggested video overlay' patch enabled and 'End screen overlay' patch disabled, it works on the first video but does not later as in the video clip attached earlier.

**Comment by inotia00** [comment]
The `Hide suggested video overlay` patch is an experimental flag

So this is very likely a bug and I have no plans to fix it

Please refer my comment on this issue https://github.com/inotia00/ReVanced_Extended/issues/1711#issuecomment-1818434833
