### ISSUE TITLE
bug(YouTube/Hide shorts components): toolbar is hidden even when shorts is not being played

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1735]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

Toolbar dissappears after some steps described below

### Steps to reproduce

Step 1. go to any channel profile in search results
Step 2. go to `Videos` section and open any video from it
Step 3. exit channel profile

### Relevant log output

```shell
:/
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/110785596/5549ef49-c76c-41cf-8707-ef09d2942dfa

### Additional context

My settings:
[ReVanced Extended_v18.29.38_2023-11-18.json](https://github.com/inotia00/ReVanced_Extended/files/13465292/ReVanced.Extended_v18.29.38_2023-11-18.json)

I tried to disable settings related to toolbar, i mean: wide search bar, switch navigation buttons and hide toolbar buttons. But nothing changed

On unpatched YouTube 18.29.38 it not get reproduced

### Device Environment

Android 13 MiUi 14.0.3; Android 12 One Ui 4.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It does not reproduce on my side

Instead of turning these patches off in the settings, please exclude them and let me know the results of your tests

**Comment by girshcatt** [comment]
Did you tried right 18.29.38?

**Comment by inotia00** [comment]
I tested it after import settings json in v18.29.38 but it still doesn't reproduce

**Comment by MarcaDian** [comment]
https://github.com/inotia00/ReVanced_Extended/assets/152095496/bf417974-833b-47b1-a361-ff6f4f8ff8db
Same bug a month ago at 18.43.45 and patches 2.195.12

**Comment by MarcaDian** [comment]
And now 18.45.41 and patches 2.199.1

https://github.com/inotia00/ReVanced_Extended/assets/152095496/2255dd30-a7cb-47a6-b476-e603f8e9bdac

![Screenshot_2023-11-26-21-28-02-298_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/152095496/a45e60bf-81d4-455b-9274-84dc62b03107)

**Comment by inotia00** [comment]
It cannot be fixed until it is reproduced on my side.

Exclude patches until the issue does not reproduce

And deduce which patch is causing the bug

**Comment by inotia00** [comment]
ah, issue still does not completely reproducible, but I can guess what code needs to be changed

**Comment by inotia00** [comment]
In a specific environment, the issue was possible to reproduce.

As a result of checking a little more, this issue is fundamentally impossible to fix.
(Due to the limitations of the implementation of the code that hides the entire shorts toolbar.)

So, instead of fixing this bug, I will remove this patch.

The buttons of other shorts toolbars, except for the back button, still can be hidden. https://github.com/inotia00/ReVanced_Extended/issues/1597

**Comment by inotia00** [comment]
> So, instead of fixing this bug, I will remove this patch.

Don't ask questions like 'Can't you keep the patch without fixing the bug?'

I rewritten patches and Integrations dozens of times to solve this issue, and I made all my efforts to maintain the legacy code as much as possible.
Nevertheless, it was appropriate to drop patch.

**Comment by MondayNitro** [comment]
> > So, instead of fixing this bug, I will remove this patch.
> 
> Don't ask questions like 'Can't you keep the patch without fixing the bug?'
> 
> I rewritten patches and Integrations dozens of times to solve this issue, and I made all my efforts to maintain the legacy code as much as possible. Nevertheless, it was appropriate to drop patch.

alternatively, you can separate the hide back button patch and put a nice warning along with it

**Comment by federicogith** [comment]
I always had the entire Shorts toolbar including the back button of it hidden but never encountered this bug

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)
