### ISSUE TITLE
bug(YouTube/Overlay buttons): always repeat button does not work as intended

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#1736]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 18.29.38 - 18.45.41
RVX patches 2.199.1

### Bug description

The yellow autoplay button doesn't work. It just repeats the behavior of the blue one and doesn't stop playback when the video ends.

### Steps to reproduce

-

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20231126_170951_ReVanced](https://github.com/inotia00/ReVanced_Extended/assets/130248949/1b05621a-ed9f-455e-8545-de5a6a6f37e6)

### Device Environment

Samsung Note10Lite A13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is not a bug
It is a new feature added in `revanced-patches-v2.181.1`
https://github.com/inotia00/ReVanced_Extended/issues/707#issuecomment-1621835001

If the repeat button is long pressed, the button will change to yellow
In this state, after the video is end, the video will be paused

There is no way to stop auto playing in the playlist, so this feature is added.

You can just turn it off by long pressing the repeat button again

**Comment by s7san007** [comment]
> after the video is end, the video will be paused

It's nothing like that. After the video ends, it repeats over and over again. There is no difference between the yellow and blue buttons. Now they are two identical buttons for video replay. This is a bug, because on my 18.29.39 (2.181.6) the yellow button works correctly in playlists and home screen.

**Comment by inotia00** [comment]
It doesn't reproduce on my side, but I'll reopen the issue.

It seems that a fix may be possible by separating the patches.

**Comment by s7san007** [comment]
I added the device info. I don't have another smartphone to check this issue.

**Comment by inotia00** [comment]
I tried to fix it, but there was no success
I will remove it in the next release

**Comment by gms77** [comment]
This feature works perfectly for me using recommended version and latest patches. Please don't remove it as its one of the main reasons I'm using rvx over the regular rv.

**Comment by federicogith** [comment]
It works fine for me too with YouTube 18.45.41 and patches 2.199.1

https://github.com/inotia00/ReVanced_Extended/assets/130296934/391e4669-d49d-4cdb-bf91-213536690d80

**Comment by s7san007** [comment]
> I will remove it in the next release

Don't remove this patch. Leave it as is.
I got a Samsung Tab S8 tablet and on it the yellow button works correctly too.
You don't need to remove the patch just because of one me and one my device.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)

**Comment by federicogith** [comment]
In the end the feature was removed because only one person on only one device was having this bug?

Also couldn't it a/b? (Because you couldn't reproduce it and no one else had this bug)

**Comment by federicogith** [comment]
> In the end the feature was removed because only one person on only one device was having this bug?
> 
> Also couldn't it a/b? (Because you couldn't reproduce it and no one else had this bug)

@inotia00 would you mind commenting on this?
