### ISSUE TITLE
bug(YouTube/Return YouTube Dislike): RTL layout not applied in RollingNumber

### ISSUE THREAD

**Issue by blacktornadog7** [inotia00/ReVanced_Extended#1737]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube 18.45.41

### Bug description

In RTL layout the like/dislike button container doesn't show up properly (screenshot below).

### Steps to reproduce:
1. change display language of the app (or the phone) to a RTL layout
2. play a video

### Screenshot
![Screenshot_20231126_225450_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/74029985/97ef6b4a-1717-4d2b-a198-a5b58bf428ce)

### Error logs

```shell
No Relevant log output
```

### Device Environment

Android 13 (One UI 5.1)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a reproducible issue.
Please spoof the app version to v18.40.34 until the issue is resolved.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)
