### ISSUE TITLE
Youtube dislikes compatibilità with smash that like button

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#1738]
### Type

Cosmetic

### Tools used

Revancify

### Application

18.45.41

### Bug description

![Screenshot_2023-11-27-00-40-48-422_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/111771663/f7ae0f6d-0671-402a-8dfa-5d03033c0c81)

### Solution

stretch to fit dislikes If is possible

### Device Environment

Android 13 miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Google's changes are not bugs
