### ISSUE TITLE
youtube: multiple toast messages displayed when sponsorblock skips segments at the end of any video 

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1740]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Youtube 18.45.43

### Bug description

multiple toast messages are displayed when sponsorblock skips segments at the end of any video. ive also heard some light sounds when this happens.

https://github.com/inotia00/ReVanced_Extended/assets/87489540/294f7fe5-08e5-4c1e-bb1b-dd78ecb41632

 

### Device Environment

los20

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1718
