### ISSUE TITLE
question: How to work Hide notifications button

### ISSUE THREAD

**Issue by hphp22f** [inotia00/ReVanced_Extended#1746]
### Application

YouTube

### Question description

Hide notification button, how it works, and why it's not visible.
![Screenshot_2023-11-28-19-59-39-434-edit_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/151181919/c2a2c416-413f-4410-979e-fdf8f70838c5)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Hide create button must be disabled.
