### ISSUE TITLE
suggestion (YouTube): Move `Hide buttons in toolbar` toggle to Navigation settings

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1747]
### Application

YouTube

### Suggestion description

![SmartSelect_20231128_094321_YT Extended](https://github.com/inotia00/ReVanced_Extended/assets/84587632/d91570bb-5458-4c9c-a60a-2a27fe204f0d)

This toggle is closely to the `Switch create with notifications button` toggle and `Hide create/notification button` toggles. 

The `Hide buttons in toolbar` toggle should be moved to the Navigation settings to make it simpler for users.

(Sorry if this much is considered a feature request)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Sensible suggestion.

Should be implemented.
