### ISSUE TITLE
bug(YouTube): `Hide notifications button` doesn't work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1749]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 18.45.43

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/15e6132d-27ca-4950-934c-c39dd0a7f2a4

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![NOTIFICATIONS](https://github.com/inotia00/ReVanced_Extended/assets/108592928/e430f35e-7661-48b8-ad6d-6ff85d91f96d)

nah it's working as intended

There seems to be a need to make the patch description clearer https://github.com/inotia00/ReVanced_Extended/issues/1748
