### ISSUE TITLE
bug: my library just disappeared

### ISSUE THREAD

**Issue by Davi22227** [inotia00/ReVanced_Extended#175]
### Type

Error while patching

### Application

Youtube 18.02.34

### Bug description

I updated my revanced and my library just disappeared like nothing and now I can't get it back

### Steps to reproduce

1Updated 2 watched some videos 3 my library is gone

### Relevant log output

```shell
someone help me?
```

### Screenshots or videos

![Screenshot_20230127_003310_YouTube ReVanced](https://user-images.githubusercontent.com/123712289/215004367-bd92e5e6-9185-44e4-ab2f-4dc4bc8ba9ff.jpg)

### Solution

I don't know any solution

### Additional context

Isso aconteceu há 2 dias atrás 

### Device Environment

Android 13 one iu 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
v18.02.34 is an unsupported version

I do not provide any help for issues reported on unsupported versions
