### ISSUE TITLE
suggestion: an image server switch 

### ISSUE THREAD

**Issue by azamuku** [inotia00/ReVanced_Extended#1751]
### Application

YouTube

### Suggestion description

Can you please add an option to switch the image server from yt3.ggpht.com to yt4.ggpht.com? The first one is blocked in Russia so we literally don't have the profile pics, banners, community posts' pics. 
There are extension for that, maybe it would be helpful: [https://chrome.google.com/webstore/detail/resource-override/pkoacgokdfckfpndoffpifphamojphii](url)
Thanks
![Screenshot_20231128-225129](https://github.com/inotia00/ReVanced_Extended/assets/109271841/2d6e175e-26e6-428f-b289-af3c4120212f)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I no longer receive any new feature request for YouTube
