### ISSUE TITLE
question: `Top live games` hide patch exists?

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1753]
### Application

YouTube

### Question description

Is it possible to hide `Top live games` that's generated by YouTube?
I don't know if it's A/B tests or a patch to hide it already exists so I'm asking here.
![Screenshot_2023-11-29-07-08-25-095_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/ae9c0b9e-e82d-4698-ad97-cf5032abb68f)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
No patch for this exists. You can add `game_card` to the custom filter to reduce the amount of screen space it takes up, like this:

![SmartSelect_20231128_165812.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/9683d82e-c455-4505-b630-2634dff50ed9)

**Comment by Rairof** [comment]
Thanks for that..
