### ISSUE TITLE
suggestion: fix spacing issues between `Bottom player` buttons

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1754]
### Application

YouTube

### Suggestion description

The space between other buttons when you hide specific buttons in `Bottom player` space is random I guess which makes it sometimes annoying.

Pretty small issue but would be nice if it can be fixed.

Personally I think the space between the Like/Dislike button and share button is just perfect and should be that space between all other buttons on the bottom player buttons.

This suggestion is nothing app breaking or serious, just a nice good polish and would like to have consistent spaces between the buttons.

Referenced picture-
![Screenshot_2023-11-29-07-30-35-883_com miui gallery-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/f271a01c-2c87-4dc6-a949-186819468c52)

### Acknowledgements

- [ ] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/17

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1754#issuecomment-1830803727
I don't understand why this is an issue as official ReVanced doesn't has it.
![Screenshot_2023-11-29-12-25-18-297_app revanced android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/f9cfcf80-d5c5-49d7-b321-3cdda24cc957)
Would be great if @inotia00 just reflect on whatever ReVanced does to the bottom player...

**Comment by KobeW50** [comment]
The bug also exists in official ReVanced. In the image below, all 3 dots are the same size but the one between the Share and Download button does not overlap the buttons.

![Screenshot_20231128_214413.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/224b7f40-7b1c-4d60-a85c-d73d9c232259)

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1754#issuecomment-1831126943
Ah still that looks much better then rvx implementation

**Comment by KobeW50** [comment]
> Ah still that looks much better then rvx implementation 

The spacing changes slightly each time a video is opened

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1754#issuecomment-1831130616
Didn't knew that. Thanks

**Comment by Aryan-Chauhan** [comment]
I'm using my app like this.
![Screenshot_2024-01-04-21-49-25-42_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/d675cc47-a77c-41d6-85e9-c53274a42e47)
