### ISSUE TITLE
suggestion: fix clickable pads in `Like/Dislike` button

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1755]
### Application

YouTube

### Suggestion description

Since the removal of dislikes, the dislike button was already small enough to misclick but now that RYD exist, it adds back the dislike numbers but still the clicking pad is only limited to that small thumbs down button.

It would be nice to see the clickable pad cover the dislike counts too and not just thumbs down button. It not only will look better and balanced but also prevent accidental misclicks as users click on the dislike counts but it counts as a like.

Referenced picture-
![Screenshot_2023-11-29-07-58-43-912_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/5455d14f-23b8-4fdd-8992-5afdfd7bb25d)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Due to the limitations of the current method of implementation, it cannot handle it.

The most ideal method is to re-implement the code of the button container from the beginning, but to be possible, Google should release the entire YouTube source code.
