### ISSUE TITLE
question:(Youtube/ Spoof app version) Which version adds back the "about" and "channels" tabs?

### ISSUE THREAD

**Issue by Yola-cola** [inotia00/ReVanced_Extended#1756]
### Application

YouTube

### Question description

So recently youtube removed the "about" and "channels" tabs on channel pages. I want know which version should I spoof to re-enable them back? If it's possible of course.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This feature has been removed on the server side, so no matter which version you install, you cannot restore it.
