### ISSUE TITLE
Tapping on a channel icon after searching takes you to the yt homepage instead of the channel's

### ISSUE THREAD

**Issue by Sam101011** [inotia00/ReVanced_Extended#1758]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

RVX v18.45.43

### Bug description

When searching for a channel, tapping on the channel icon takes you to the yt homepage instead of the channel's.

https://github.com/inotia00/ReVanced_Extended/assets/90930406/dd583a52-07df-4375-aaa5-a674b1b59619

### Additional context

The issue started occuring in v18.45.41. I have cleared cache and force stopped the app a few times but the issue persists.
The issue isn't present in regular revanced.

### Device Environment

Device: Huawei p40 lite(JNY-LX1)
OS: Android 10
ROM: EMUI 12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You are spoofing a very old version via `Spoof app version`

Since the `Spoof app version` patch is an experimental flag, I do not receive any bug reports while using it.
