### ISSUE TITLE
bug: cannot swipe down at the middle of full screen to exit full screen when volume swipe is disabled

### ISSUE THREAD

**Issue by jackblk** [inotia00/ReVanced_Extended#176]
### Type

Other

### Application

Youtube 18.01.38

Revanced Extended patch v2.156.1

### Bug description

When in full screen, user can exit full screen by swiping down at the middle of the screen. It is not possible anymore if we disable volume swipe.

### Steps to reproduce

* Disable volume swipe in Revanced settings
* Go full screen
* Swipe down at the middle of the screen

Expected: exit full screen

Observed: nothing

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
If volume or brightness gestures are set to off, overall swipe sensitivity is reduced

Try swipe with a little long touch to exit full screen

Reduced swipe sensitivity, but still works well

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.156.4
