### ISSUE TITLE
bug(YouTube Music/Certificate spoof): YT Music does not work with Android Auto

### ISSUE THREAD

**Issue by radical4ever** [inotia00/ReVanced_Extended#1760]
### Type

Other

### Tools used

Revancify

### Application

Youtube Music 6.28.52

### Bug description

The bug is that i cant play online music on android auto, i try to open my library page on android auto and nothing appears, if i press settings on the android auto wi dlw the app crashes.
-connect phone to android auto supported tablet
-allow unknow sources
-start revanced music
-nothing related to online music appears only my local files

### Additional context

Probably is something related tko the patches idk, i'll try a patched  one only woth that patch and the disable ads one to see

### Device Environment

Android 13, OneUi 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Radical4ever** [comment]
I noticed too that the search button/bar is also missing on the patched version
