### ISSUE TITLE
bug(YouTube/Layout switch): cannot load the page

### ISSUE THREAD

**Issue by Medevi** [inotia00/ReVanced_Extended#1763]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube 18.45.43

### Bug description

First of all, this problem occurs on a tablet, not a smartphone.  I share an apk file from my smartphone and use it on my tablet. 
Here's what happens 
First, I play a video.
 Then I tap on the channel name of the video, the video becomes smaller and the channel should float, but the screen looks like the attached photo.
![Screenshot_20231201_102316_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/114724694/62f9647f-4092-4991-b6f0-6ae5760c751f)

### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Wait for the next release or exclude the `Layout Switch` patch.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.7](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.7)
