### ISSUE TITLE
bug:(YouTube): Live Chat Polls not displaying properly 

### ISSUE THREAD

**Issue by Jaydan101** [inotia00/ReVanced_Extended#1764]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 18.45.43

### Bug description

When you open the live comment on a live video, the poll section at the bottom is all white with none of the text showing. This is the same case will all live videos that features a poll. 

When you select a poll answer (even though you cannot see the options, if you click on it, it will select an option) it will move to the top and then display the poll results, which now becomes visible 

I waited for a few days to report.
![Screenshot_20231129_080344_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/152452522/b58590b1-9a68-4ec8-be54-702a687a341b)

### Error logs

```shell
None
```

### Solution

None found as yet. Restarting, repatching and clearing cache doesn't solve the issue 

### Device Environment

Samsung Galaxy 23U one ui 6 (android 14) latest November security patch

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please leave the video url

**Comment by Jaydan101** [comment]
After enabling unpatched youtube, the poll on a live video worked as intended. I noticed the unpatched youtube was on an older version since an update was available.

I updated it to the lastest available play store version (18.46.41). The poll showed all white as what's in the screen shot. 

I patched only with micro G support and the issue is still present. 

I rolled back my revanced extended to version 18.45.41 and the polls work as intended. 

It maybe an issue with the lastest updated youtube versions. Maybe Youtube broke something in their lastest updates. 

Sorry for wasting your time.

**Comment by inotia00** [comment]
This issue report will help save time for people who will visit this page due to the same issue as you
So you don't have to be sorry

Anyway, this issue is presumed to be a bug on stock YouTube, so I'll close the issue

**Comment by Jaydan101** [comment]
> This issue report will help save time for people who will visit this page due to the same issue as you So you don't have to be sorry
> 
> Anyway, this issue is presumed to be a bug on stock YouTube, so I'll close the issue

I can confirm that this bug has now been fixed in stock YouTube 18.49.36
