### ISSUE TITLE
suggestion(YouTube/YouTube Music): add `is` to revanced_ryd_toast_on_connection_error_title string

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1765]
### Application

YouTube/YouTube Music

### Suggestion description

Add `is` to revanced_ryd_toast_on_connection_error_title string

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
oh my

**Comment by inotia00** [comment]
I checked and it was a part taken from the official ReVanced source
This is the result of matching the official ReVanced source, and if there is a change in the official ReVanced source, this will be applied to RVX as well

**Comment by girshcatt** [comment]
It was fixed in revanced, also it fixed in rvx by miracle
![Screenshot_2023-12-05-10-48-11-951_com android chrome-edit](https://github.com/inotia00/ReVanced_Extended/assets/110785596/0d2b5608-b780-4c62-86fa-d6d451843ea1)
