### ISSUE TITLE
suggestion(YouTube): Centre the search bar or add some margin on the right

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1768]
### Application

YouTube

### Suggestion description

![ _20231202_063706](https://github.com/inotia00/ReVanced_Extended/assets/127908708/9e91621d-3cc9-4104-9cad-9ed30ae7a884)
(It's with `Hide voice search button` patch applied)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I tried to edit it but gave up, I think I need someone's contribution

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.202.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.202.1)

**Comment by ggafoor** [comment]
Please launcher settings option area serch option button  ![Screenshot_2023-12-04-00-06-38-09_c269bce7be08f98da9640039739b3cb0.jpg](https://github.com/inotia00/ReVanced_Extended/assets/82312786/7392d820-f304-4966-9f1b-82b9fcda9a88)
