### ISSUE TITLE
suggestion: (revanced-patches) patches.json didn't update ?

### ISSUE THREAD

**Issue by Sappurit** [inotia00/ReVanced_Extended#1769]
### Application

YouTube

### Suggestion description

 https://github.com/inotia00/revanced-patches/blob/revanced-extended/patches.json
did't updated.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Something seems to be twisted in a process that mergates repo
There is no issue in the [release](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.12), so you don't have to worry about it

`patches.json` file is automatically overrided in the build process even if it is not changed manually
