### ISSUE TITLE
Return YouTube dislikes on new layout 

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#177]
### Type

Other

### Application

YouTube version 18.03.33

### Bug description

Return YouTube dislikes suddenly stopped working in new layout while  i am logged in to my account.. if i log out it return to work normally

### Steps to reproduce

Please can you fix that problem and i wonder of anyone has faced such that problem 

### Relevant log output

```shell
.
```

### Solution

.

### Additional context

.

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
v18.03.33 is an unsupported version

I do not provide any help for issues reported on unsupported versions

**Comment by Mohammed1520** [comment]
Sir .. even in your supported version the problem have occured . I tried 3 versions and the same problem exists .. even i tried the official revanced and the problem remains .. RYD return to work only if i logged out my account
