### ISSUE TITLE
bug: swipe geasture bug

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#1770]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube v18.46.45

### Bug description

When enabling press to swipe feature  after locking the video the swipe geasture not working.

### Error logs

```shell
.
```

### Device Environment

Android 12,miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by hlytus** [comment]
That's not a bug. It's intended to work that way.

**Comment by Adity1243** [comment]
> That's not a bug. It's intended to work that way.

You didnt read carefully i said even after enabling press to swipe feature still swipe geasture not working when video is locked.

**Comment by hlytus** [comment]
"**swipe gesture working even after using `Lock screen` feature when `Press-to-swipe` is enabled**"- this was a bug that got fixed. That's what the changelog says. Any input is not supposed to work in Lock screen mode. That's what the lock screen mode is for.

**Comment by inotia00** [comment]
yeah this is not a bug

**Comment by Adity1243** [comment]
Lol it wasnt working before this patch released too whats the point.

**Comment by Adity1243** [comment]
I wanted to use in lock screen mode bcus when i touch the screen sometime it goes to portrait mode so mostly i use that feature while in lock screen so it wont go in portrait mode, and fter some patch updates it got removed.

**Comment by Adity1243** [comment]
> "**swipe gesture working even after using `Lock screen` feature when `Press-to-swipe` is enabled**"- this was a bug that got fixed. That's what the changelog says. Any input is not supposed to work in Lock screen mode. That's what the lock screen mode is for.

Lol it wasnt working before this patch released too, so whats the point. I was become happy after i think that it started working again and swipe geasture is not bother if screen got misclicked bcus its work only if we do  swipe not just by click.

**Comment by Adity1243** [comment]
I wanted to use in lock screen mode bcus when i touch the screen sometime it goes to portrait mode so mostly i use that feature while in lock screen so it wont go in portrait mode, and after some patch updates it got removed.
