### ISSUE TITLE
suggestion: Make "Hide voice search button" an ON/OFF toggle.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1771]
### Application

YouTube

### Suggestion description

In patches v2.201.12, you added "Hide voice search button" patch to both RVX & RVX Music.

Is it possible to make this a toggle?

Reason: Many people like me, include almost all patches while patching, so this results in unintentional hiding of that button.

That's why it would be convenient if this patch can have a simple ON/OFF toggle.

Thank you.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MondayNitro** [comment]
just exclude the patch, simple.
