### ISSUE TITLE
suggestion(YouTube/  YouTube Music): you didn't add new strings to crowdin

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1772]
### Application

YouTube

### Suggestion description

You didn't add new strings to crowdin:
strings related to Close interstitial ads

Also you forgot to add refresh and restart, refresh to load interface normally for YTM on crowdin

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is because, unlike other patches, it is a feature that has never been tested.

It is likely to be removed in the near future

**Comment by girshcatt** [comment]
I mean that i cant see translations of those strings in app now
i checked different languages
It translated in crowdin
![Screenshot_20231202_233058_Chrome](https://github.com/inotia00/ReVanced_Extended/assets/110785596/ec935d22-f9af-4bd9-b5d7-95f76ccf2eed)
But translation not shown in app
![20231202_232835](https://github.com/inotia00/ReVanced_Extended/assets/110785596/fcc1f9b0-d76c-4030-ac45-fe6db84be82f)
![Screenshot_20231202_232753_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/3cc44c63-a396-461e-a5b5-b1cb90abb1df)
