### ISSUE TITLE
suggestion: regarding hide mic patch

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1773]
### Application

YouTube

### Suggestion description

you should make this dimension in id/voice_search to 0dip instead of -8dip to prevent it from cutting into the edge of the screen.
![Screenshot_20231202-132038_Trebuchet](https://github.com/inotia00/ReVanced_Extended/assets/87489540/8f4e66ff-4c38-47db-b2ff-2fd063d07cce)
![Screenshot_20231202-132059_Trebuchet](https://github.com/inotia00/ReVanced_Extended/assets/87489540/1cec67e3-2259-46ce-acd3-aa5eaac659ef)
before
![Screenshot_20231202-132421_Trebuchet](https://github.com/inotia00/ReVanced_Extended/assets/87489540/a843a752-b91a-4337-9978-a25f59311d67)
after

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.202.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.202.1)
