### ISSUE TITLE
bug: default video quality.

### ISSUE THREAD

**Issue by Creativecze** [inotia00/ReVanced_Extended#1776]
Type

Other

### Tools used

RVX Manager

### Application

YouTube v18.46.43

Rvx patches 
v2.201.12 

### Bug description

When set default video quality to 1080p 1440p 2160p and play video then video quality changes to 480p or 360p on all videos

### Device Environment
Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [x] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1730#issuecomment-1826286065
