### ISSUE TITLE
bug(YouTube/SponsorBlock): Some videos refused to end where there's a skippable segment at the end

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#1777]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v18.46.43

### Bug description

This issue is derived from the issue https://github.com/inotia00/ReVanced_Extended/issues/1745

In some videos, if you skip the SponsorBlock section at the end of the video, the video does not end and falls into an infinite loop.

I have opened a new issue to add a more technical explanation.

To reproduce an issue, the following conditions must be met:

1. Autoplay is turned off.
2. All SponsorBlock segments are set to `Skip automatically`.
3. The end of the segment in SponsorBlock is longer than the length of the video.

ex1.
https://www.youtube.com/watch?v=chBrDqnimSo

![ex1](https://github.com/inotia00/ReVanced_Extended/assets/108592928/a156e7ec-b057-4940-bf8c-f70608d55fbb)

The end of the segment in SponsorBlock is `11:05.421`, which is longer than `11:05`, the length of video.

ex2.
https://www.youtube.com/watch?v=bvaLHbLTWuI

![ex2](https://github.com/inotia00/ReVanced_Extended/assets/108592928/87faa4c0-3176-4a37-89ff-4cdd28bdfce9)

The end of the segment in SponsorBlock is `11:52.401`, which is longer than `11:52`, the length of video.

There haven't been any issues so far, even if skipping to a point that's longer than the length of video.

At some point, the video would loop if you skipped to a section that was longer than the video.
(This doesn't always happen)

Maybe there have been some changes recently on the server side of YouTube

The last two commits tried to solve this issue by adding a process to the {@link VideoInformation#seekTo} method that compares the video length with the skip length.

https://github.com/inotia00/revanced-integrations/commit/3df066b44bc2f3a318de69197035b34c36b022ac

https://github.com/inotia00/revanced-integrations/commit/63f017055383e0df32313b0a489d139ca72d2c1c

But this didn't completely solve the issue

This is because it skips to a time before the end of the SponsorBlock segment, so it is treated as SponsorBlock segment was not skipped.

### Error logs

```shell
N/A
```

### Solution

After thinking about how to solve this, my conclusion is:
The idea was simply to make sure that when a SponsorBlock segment is fetched, the end of the segment is no longer than the length of the video.

I think this is a more ideal method than checking in the {@link VideoInformation#seekTo} method.

https://github.com/inotia00/revanced-integrations/commit/206b9baacaa7e49b0665e3b137aea1667098bb9b

But I'm still not sure if this is the most ideal solution.

### Additional context

N/A

### Device Environment

Android 13, MIUI 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] #1778
- [X] I have written the title and contents in English.

**Comment by Raven-621** [comment]
Looks like the bug is fixed on my end (tho some took a while before a video ends).

Kurzgesagt (this one took a while, assuming because there's multiple segments need to be skipped):

https://github.com/inotia00/ReVanced_Extended/assets/141109979/2120846a-a41e-41bc-9881-a24bf184a0a3

LTT:

https://github.com/inotia00/ReVanced_Extended/assets/141109979/6ee1d54f-08a7-4d02-9cc3-be7cbfb992d3

TerminalMontage:

https://github.com/inotia00/ReVanced_Extended/assets/141109979/718d4b71-480c-4c98-8528-82d3574e5968

**Comment by inotia00** [comment]
Thank you for testing. I will close the issue.

**Comment by davilex9** [comment]
playlist open speed , 18.16... moment , how fix ?  , or loading on olds
