### ISSUE TITLE
suggestion(YouTube): you made a mistake in revanced_swipe_gestures_lock_mode_summary_on string

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1780]
### Application

YouTube

### Suggestion description

You made a mistake in revanced_swipe_gestures_lock_mode_summary_on
Swipe gestures are `endabled` in 'Lock screen' mode.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed now
