### ISSUE TITLE
bug(RVX Manager): in-app update feature not working

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1781]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

RVX Manager v1.17.1 (fork)

### Bug description

Update button gets highlighted and when clicked, shows a loading pop up that keeps loading.

Reference pic-
![Screenshot_2023-12-03-21-36-50-332_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/6b026fb7-d993-4c89-b42e-18fcf63934a3)

### Error logs

```shell
N/A
```

### Solution

Fix in app update feature for RVX manager.
Official ReVanced manager works fine

### Additional context

Using Xiaomi 11T pro

### Device Environment

Android 13 MIUI 14.0.4

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by JRodster** [comment]
RvX Manager v1.17.1 for some reason is not appearing in the full "releases" page alongside the prior versions (latest that shows there is v1.16.0), but only in the "tags" page. Maybe related?

**Comment by ggafoor** [comment]
Good very good
