### ISSUE TITLE
bug: Shorts plays for 1-2secs & then replays again 

### ISSUE THREAD

**Issue by Sanathkumarcjois** [inotia00/ReVanced_Extended#1784]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube **v18.46.43**, latest patch. Installed via RVX manager v1.17.1.

![Screenshot_20231203-174154](https://github.com/inotia00/ReVanced_Extended/assets/90624092/06a85413-80fc-478a-9d2a-2fc336f14e8c)

![Screenshot_20231203-174222-698](https://github.com/inotia00/ReVanced_Extended/assets/90624092/80293de2-b43b-4c03-9c75-aae95fd98d77)
 

### Bug description

When storts is played, short starts but runs only for 1-2 seconds and then replays again then it continues as normal and as it should play.

https://github.com/inotia00/ReVanced_Extended/assets/90624092/6186b9b9-3f67-4517-a56b-9c8b7bb0b2d3

### Additional context

Happens for every single short and is very annoying as it is played for only some seconds and then replays

### Device Environment

Android 11, Motorola one fusion+

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.203.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.203.1)
