### ISSUE TITLE
bug(YouTube/Return YouTube Dislike): pressing like button sometimes hides dislike counts

### ISSUE THREAD

**Issue by NMBlanco** [inotia00/ReVanced_Extended#1786]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

18.46.43

### Bug description

With Return Dislikes enabled, the dislikes counter glitches when either liking or disliking a video.
It happens with compact-button mode as well as the best visibility mode.
It didn't happen in the patch-versions before, just started happening with the latest one.
Please refer to [this](https://drive.google.com/file/d/1cFKKFNTSz7p7mjv-FN5YFyJOSHKuOyru/view?usp=drivesdk) screenrecord

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.203.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.203.1)
