### ISSUE TITLE
Premium Video Play 

### ISSUE THREAD

**Issue by SM9947** [inotia00/ReVanced_Extended#1787]
### Application

YouTube

### Suggestion description

It will be good if you can add an option to play premium bitrate video in YouTube. Hint : you can find a option to download premium bitrate video in yt-dlp. Please try if you can do something 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
inotia00 only takes new feature requests for RVX Music.
