### ISSUE TITLE
feat(patch): backup & restore settings

### ISSUE THREAD

**Issue by Sappurit** [inotia00/ReVanced_Extended#179]
### Application

YouTube

### Description

There are a lot of settings in Youtube Revanced. It is good if we can backup & restore the settings. We can restore to many devices too. Many times we need to clean install too. eg. change package name or clear bug fix.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Eiskrem** [comment]
Would like to see this aswell. Would help restoring settings when installing on another phone.

**Comment by venkat2305** [comment]
This would be a killer feature. Please include sponsorblock settings, it's private Id as well.

**Comment by anyujinie** [comment]
> This would be a killer feature. Please include sponsorblock settings, it's private Id as well. 

Right! SB settings too!👌🏻

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)

**Comment by inotia00** [comment]
> @inotia00 Can you please include sponsorblock settings in this import/export settings please

1. Separate import/export settings already exist in SponsorBlock settings
2. Import/export settings in SponsorBlock must be compatible with other platforms
(e.g. chrome extension's SponsorBlock)

-> So I can't implement it my way

**Comment by inotia00** [comment]
> @inotia00 downloader package name isn't imported. Can you please check?

![export](https://user-images.githubusercontent.com/108592928/220585532-e85b5f1e-02ea-450a-8b24-adf11a213189.png)
yeah import/export works fine

**Comment by venkat2305** [comment]
It's not working for me I'm using seal
```
{"revanced_overlay_button_auto_repeat":false,"revanced_hide_button_download":false,"revanced_overlay_button_whitelist":false,"revanced_hide_fullscreen_button_container":false,"revanced_enable_phone_layout":false,"revanced_hide_shorts_player_subscriptions_button":false,"revanced_overlay_button_copy_url_with_timestamp":false,"revanced_enable_swipe_auto_brightness":true,"revanced_adremover_web_search_panel":true,"revanced_enable_tablet_miniplayer":false,"revanced_hide_shorts_player_thanks_button":true,"revanced_hide_menu_report":true,"revanced_hide_snackbar":true,"revanced_adremover_suggestions":true,"revanced_hide_player_button_background":false,"revanced_adremover_breaking_news_shelf":true,"revanced_swipe_overlay_background_alpha":"127","revanced_adremover_separator":true,"revanced_hide_menu_listening_controls":false,"revanced_hide_button_thanks":true,"revanced_swipe_overlay_timeout":"500","revanced_disable_haptic_feedback_zoom":false,"revanced_default_video_quality_mobile":"-2","revanced_enable_wide_searchbar":false,"revanced_enable_custom_seekbar_color":true,"revanced_adremover_browse_store_button":true,"revanced_adremover_timed_reactions":true,"revanced_hide_menu_more_info":false,"revanced_hide_email_address":true,"revanced_hide_time_and_seekbar":false,"revanced_adremover_emergency_box":true,"revanced_disable_haptic_feedback_scrubbing":false,"revanced_adremover_channel_member_shelf":true,"revanced_hide_cast_button":true,"revanced_hide_channel_watermark":true,"revanced_hide_button_create_short":true,"revanced_hide_menu_ambient_mode":false,"revanced_hide_prev_button":true,"revanced_hide_shorts_shelf":true,"revanced_adremover_view_products":true,"revanced_default_video_speed":"-2.0","revanced_hide_shorts_button":true,"revanced_hide_preview_comment":false,"revanced_hide_menu_stats_for_nerds":false,"revanced_initial_spoof":true,"revanced_hide_stories_shelf":true,"revanced_adremover_merchandise":true,"revanced_overlay_button_downloads":true,"revanced_enable_save_brightness":false,"revanced_enable_old_quality_layout":true,"revanced_hide_endscreen_overlay":true,"revanced_adremover_subscribers_community_guidelines":true,"revanced_hide_comments_section":false,"revanced_hide_auto_player_popup_panels":true,"revanced_adremover_community_guidelines":true,"revanced_default_video_quality_wifi":"1440","revanced_adremover_paid_content":true,"revanced_adremover_movie_shelf":true,"revanced_hide_button_report":true,"revanced_disable_haptic_feedback_chapters":false,"revanced_hide_autoplay_button":true,"revanced_hide_floating_microphone":true,"revanced_adremover_channel_guidelines":true,"revanced_hide_player_overlay_filter":false,"revanced_hide_menu_captions":false,"revanced_hide_button_create_clip":true,"revanced_hide_button_live_chat":false,"revanced_hide_menu_loop_video":false,"revanced_hide_menu_help":true,"revanced_adremover_custom_strings":"","revanced_enable_custom_video_speed":false,"revanced_video_ads_removal":true,"revanced_disable_haptic_feedback_seek":false,"revanced_hide_create_button":true,"revanced_hide_next_button":true,"revanced_hide_button_share":false,"revanced_swipe_magnitude_threshold":"0","revanced_adremover_medical_panel":true,"revanced_adremover_album_card_in_search":true,"revanced_custom_seekbar_color_value":"#ff0000","revanced_hide_shorts_player_join_button":true,"revanced_enable_always_auto_repeat":false,"revanced_hide_button_dislike":false,"revanced_adremover_general_ads":true,"revanced_hide_mix_playlists":true,"revanced_hide_button_like":false,"revanced_hide_menu_audio_track":false,"revanced_enable_minimized_playback":true,"revanced_hide_crowdfunding_box":true,"revanced_hide_menu_watch_in_vr":true,"revanced_enable_tablet_layout":false,"revanced_hide_startup_shorts_player":true,"revanced_enable_swipe_volume":true,"revanced_hide_shorts_player_remix_button":true,"revanced_adremover_official_card_in_search":true,"revanced_adremover_user_filter":false,"revanced_downloader_package_name":"com.junkfood.seal","revanced_adremover_self_sponsor":true,"revanced_adremover_community_posts":false,"revanced_enable_swipe_haptic_feedback":true,"revanced_hide_filmstrip_overlay":true,"revanced_adremover_channelbar_join_button":true,"revanced_hide_info_cards":true,"revanced_adremover_info_panel":true,"revanced_hide_auto_captions":true,"revanced_overlay_button_speed":false,"revanced_enable_press_to_swipe":false,"revanced_enable_external_browser":false,"revanced_enable_open_links_directly":true,"revanced_hide_suggested_actions":true,"revanced_adremover_chapter_teaser":true,"revanced_adremover_latest_posts":true,"revanced_override_premium_header":false,"revanced_enable_old_layout":false,"revanced_hide_button_playlist":false,"revanced_swipe_overlay_text_size":"27","revanced_adremover_feed_survey":true,"revanced_hide_endscreen_cards":true,"revanced_adremover_compact_banner":true,"revanced_enable_swipe_brightness_in_hdr":false,"revanced_adremover_image_shelf":true,"revanced_enable_save_video_quality":false,"revanced_hide_live_chat_button":false,"revanced_hide_shorts_player_comments_button":false,"revanced_adremover_button_ads":true,"revanced_overlay_button_copy_url":false,"revanced_hide_fullscreen_panels":false,"revanced_hide_captions_button":false,"revanced_enable_vp9_codec":false,"revanced_enable_save_video_speed":false,"revanced_enable_seekbar_tapping":true,"revanced_enable_swipe_brightness":true,"revanced_hide_menu_listen_with_youtube_music":true}


```

**Comment by venkat2305** [comment]
`{"revanced_overlay_button_auto_repeat":false,"revanced_hide_button_download":false,"revanced_overlay_button_whitelist":false,"revanced_hide_fullscreen_button_container":false,"revanced_enable_phone_layout":false,"revanced_hide_shorts_player_subscriptions_button":false,"revanced_overlay_button_copy_url_with_timestamp":false,"revanced_enable_swipe_auto_brightness":true,"revanced_adremover_web_search_panel":true,"revanced_enable_tablet_miniplayer":false,"revanced_hide_shorts_player_thanks_button":true,"revanced_hide_menu_report":true,"revanced_hide_snackbar":true,"revanced_adremover_suggestions":true,"revanced_hide_player_button_background":false,"revanced_adremover_breaking_news_shelf":true,"revanced_swipe_overlay_background_alpha":"127","revanced_adremover_separator":true,"revanced_hide_menu_listening_controls":false,"revanced_hide_button_thanks":true,"revanced_swipe_overlay_timeout":"500","revanced_disable_haptic_feedback_zoom":false,"revanced_default_video_quality_mobile":"-2","revanced_enable_wide_searchbar":false,"revanced_enable_custom_seekbar_color":true,"revanced_adremover_browse_store_button":true,"revanced_adremover_timed_reactions":true,"revanced_hide_menu_more_info":false,"revanced_hide_email_address":true,"revanced_hide_time_and_seekbar":false,"revanced_adremover_emergency_box":true,"revanced_disable_haptic_feedback_scrubbing":false,"revanced_adremover_channel_member_shelf":true,"revanced_hide_cast_button":true,"revanced_hide_channel_watermark":true,"revanced_hide_button_create_short":true,"revanced_hide_menu_ambient_mode":false,"revanced_hide_prev_button":true,"revanced_hide_shorts_shelf":true,"revanced_adremover_view_products":true,"revanced_default_video_speed":"-2.0","revanced_hide_shorts_button":true,"revanced_hide_preview_comment":false,"revanced_hide_menu_stats_for_nerds":false,"revanced_initial_spoof":true,"revanced_hide_stories_shelf":true,"revanced_adremover_merchandise":true,"revanced_overlay_button_downloads":true,"revanced_enable_save_brightness":false,"revanced_enable_old_quality_layout":true,"revanced_hide_endscreen_overlay":true,"revanced_adremover_subscribers_community_guidelines":true,"revanced_hide_comments_section":false,"revanced_hide_auto_player_popup_panels":true,"revanced_adremover_community_guidelines":true,"revanced_default_video_quality_wifi":"1440","revanced_adremover_paid_content":true,"revanced_adremover_movie_shelf":true,"revanced_hide_button_report":true,"revanced_disable_haptic_feedback_chapters":false,"revanced_hide_autoplay_button":true,"revanced_hide_floating_microphone":true,"revanced_adremover_channel_guidelines":true,"revanced_hide_player_overlay_filter":false,"revanced_hide_menu_captions":false,"revanced_hide_button_create_clip":true,"revanced_hide_button_live_chat":false,"revanced_hide_menu_loop_video":false,"revanced_hide_menu_help":true,"revanced_adremover_custom_strings":"","revanced_enable_custom_video_speed":false,"revanced_video_ads_removal":true,"revanced_disable_haptic_feedback_seek":false,"revanced_hide_create_button":true,"revanced_hide_next_button":true,"revanced_hide_button_share":false,"revanced_swipe_magnitude_threshold":"0","revanced_adremover_medical_panel":true,"revanced_adremover_album_card_in_search":true,"revanced_custom_seekbar_color_value":"#ff0000","revanced_hide_shorts_player_join_button":true,"revanced_enable_always_auto_repeat":false,"revanced_hide_button_dislike":false,"revanced_adremover_general_ads":true,"revanced_hide_mix_playlists":true,"revanced_hide_button_like":false,"revanced_hide_menu_audio_track":false,"revanced_enable_minimized_playback":true,"revanced_hide_crowdfunding_box":true,"revanced_hide_menu_watch_in_vr":true,"revanced_enable_tablet_layout":false,"revanced_hide_startup_shorts_player":true,"revanced_enable_swipe_volume":true,"revanced_hide_shorts_player_remix_button":true,"revanced_adremover_official_card_in_search":true,"revanced_adremover_user_filter":false,"revanced_downloader_package_name":"com.junkfood.seal","revanced_adremover_self_sponsor":true,"revanced_adremover_community_posts":false,"revanced_enable_swipe_haptic_feedback":true,"revanced_hide_filmstrip_overlay":true,"revanced_adremover_channelbar_join_button":true,"revanced_hide_info_cards":true,"revanced_adremover_info_panel":true,"revanced_hide_auto_captions":true,"revanced_overlay_button_speed":false,"revanced_enable_press_to_swipe":false,"revanced_enable_external_browser":false,"revanced_enable_open_links_directly":true,"revanced_hide_suggested_actions":true,"revanced_adremover_chapter_teaser":true,"revanced_adremover_latest_posts":true,"revanced_override_premium_header":false,"revanced_enable_old_layout":false,"revanced_hide_button_playlist":false,"revanced_swipe_overlay_text_size":"27","revanced_adremover_feed_survey":true,"revanced_hide_endscreen_cards":true,"revanced_adremover_compact_banner":true,"revanced_enable_swipe_brightness_in_hdr":false,"revanced_adremover_image_shelf":true,"revanced_enable_save_video_quality":false,"revanced_hide_live_chat_button":false,"revanced_hide_shorts_player_comments_button":false,"revanced_adremover_button_ads":true,"revanced_overlay_button_copy_url":false,"revanced_hide_fullscreen_panels":false,"revanced_hide_captions_button":false,"revanced_enable_vp9_codec":false,"revanced_enable_save_video_speed":false,"revanced_enable_seekbar_tapping":true,"revanced_enable_swipe_brightness":true,"revanced_hide_menu_listen_with_youtube_music":true}`

**Comment by inotia00** [comment]
![backuped2](https://user-images.githubusercontent.com/108592928/220590473-855fea9f-ed2f-4aca-a86d-d649923b8327.png)
It seems to have exported successfully

**Comment by inotia00** [comment]
> It's not importing it though

What does it mean that the import failed?
Doesn't the Seal run when you click the download button after importing?

**Comment by venkat2305** [comment]
No. Seal is not running

**Comment by venkat2305** [comment]
All the other settings were imported successfully except the downloder

**Comment by inotia00** [comment]
> All the other settings were imported successfully except the downloder

Maybe it's a Seal issue.

I tested it with various downloaders in various situations, but it works fine in all situations.

**Comment by venkat2305** [comment]
The package name is not imported to the settings.
![Screenshot_2023-02-22-17-24-57-264_app.rvx.android.youtube.jpg](https://user-images.githubusercontent.com/55329452/220613057-7ebdb24a-6a41-4696-a9ac-7736e9a08a8d.jpg)
