### ISSUE TITLE
question: How to turn off this

### ISSUE THREAD

**Issue by hphp22f** [inotia00/ReVanced_Extended#1790]
### Application

YouTube

### Question description

This notification sometimes shows when you open the YouTube app.  How to turn it off?**
![Screenshot_2023-12-04-18-30-26-406_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/151181919/dda4395a-9b06-4997-a0a9-3d6c03a2bbef)
**

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
you can't
