### ISSUE TITLE
bug: Import and export issues of the custom settings file

### ISSUE THREAD

**Issue by AByakugans** [inotia00/ReVanced_Extended#1791]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube  v18.46.43

### Bug description

When I import my custom settings - and restart the app - and I do the re-export of the settings a lot of settings is missing almost all my custom settings is not re-exported correctly.

It even seems it is not correctly comparing default and my changed settings after my file import.

### Device Environment

Android 13 + OneUI 5.1
[YouTube_v18.40.34_2023-10-21_111.txt](https://github.com/inotia00/ReVanced_Extended/files/13547601/YouTube_v18.40.34_2023-10-21_111.txt)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Also the export file you attached is a configuration file that is not compatible with the latest revanced-patches.

Settings exported from versions prior to revanced-patches-2.201.7 are not compatible with versions later than revanced-patches-2.201.7.

This is also stated in the release notes https://github.com/inotia00/ReVanced_Extended/issues/1743#issuecomment-1829304394

**Comment by inotia00** [comment]
1. I followed the procedure you mentioned, but it works as intended.
```
Import settings at `revanced-patches-2.202.1` (Settings exported from `revanced-patches-2.201.7`)
→ Restart and export again
→ Exported settings are the same
```
2. The files you attached were exported in old Patches, so I can't guarantee that they are compatible with the latest patches.
