### ISSUE TITLE
YouTube history doesn't update on ReVanced Extended root version

### ISSUE THREAD

**Issue by alexyo02** [inotia00/ReVanced_Extended#1792]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube Revanced 18.45.43

### Bug description

When I see videos using ReVanced Extended, history doesn't update, but it does update if I see videos from other devices.

I'm using a Redmi Note 9 Pro (miatoll) with LineageOS 20, rooted with Magisk latest version (26.4) and I update my repos from NoName.exe repos which use this CLI

### Device Environment

Android 13, Lineage OS 21
Build (TQ3A.230901.001)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Proper support and debugging can't be done with APKs obtained from unofficial sources.

Anyways, your issue may lie with an adblocker, dns-blocker, firewall etc. Whitelist `s.youtube.com`.

**Comment by alexyo02** [comment]
Thank you sir, the issue was the adblocker, sorry for my ignorance
