### ISSUE TITLE
Hook Download Button patch is not working

### ISSUE THREAD

**Issue by HauntedKnives** [inotia00/ReVanced_Extended#1794]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 18.46.43

### Bug description

Showing YouTube download menu instead of external downloader even if Hook Download Button patch is turned on

### Device Environment

Android 13, One UI 5.1.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
`Hook download button` is an experimental feature, it means that dev won't accept any bug report on it, you can close the issue

**Comment by inotia00** [comment]
Yeah, the `Hook download button` patch implemented on YouTube has the feature of relying on the server side

So it's likely to stop working at any time, which is why I flagged it as `Experimental Flags`
