### ISSUE TITLE
feat(patch): Allow subtitles on PIP

### ISSUE THREAD

**Issue by DanGLES3** [inotia00/ReVanced_Extended#18]
### Application

Youtube

### Issue

The lack of subtitles when on PIP mode

### Patch

A patch that would allow subtitles to be displayed while on PIP mode (currently they're disabled)

### Motivation

Allowing the consumption of subbed content without the need to have YouTube fully opened

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
