### ISSUE TITLE
custom braiding icon bug

### ISSUE THREAD

**Issue by Turhvjbufv** [inotia00/ReVanced_Extended#1800]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 18.45.43

### Bug description

Custom branding icon doesn't work, screenshot to show files, maybe my files aren't set correctly or something idk
![Screenshot](https://github.com/inotia00/ReVanced_Extended/assets/91851160/fc566294-b3f1-46ca-8f74-d6d15f6dad50)
![Screenshot_1](https://github.com/inotia00/ReVanced_Extended/assets/91851160/8a53a84f-bf51-4e5a-95cd-dce90e6da611)

### Error logs

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: SM-A725F
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v18.45.43
Patches version: v2.203.2
Patches added: Custom branding icon YouTube [App icon: content://com.android.externalstorage.documents/tree/primary%3ARevanced%20icon]
Patches removed: Custom package name [Package name of YouTube: app.rvx.android.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Hide general ads, Alternative thumbnails, Hide button container, Hide comment component, Hide feed flyout panel, Enable old quality layout, Hide player flyout panel, Hide autoplay preview, Enable compact controls overlay, Hide end screen overlay, Force fullscreen, Hide fullscreen panels, Quick actions components, Hide account menu, Disable auto captions, Hide auto player popup panels, Hide category bar, Hide channel avatar section, Hide crowdfunding box, Hide channel profile components, Hide description components, Hide floating microphone, Hide handle, Hide latest videos button, Hide layout components, Enable gradient loading screen, Hide load more button, Hide mix playlists, Hide search term thumbnail, Hide snack bar, Hide suggestions shelf, Enable tablet mini player, Hide toolbar button, Hide trending searches, Enable wide search bar, Custom branding icon YouTube [App icon: content://com.android.externalstorage.documents/tree/primary%3ARevanced%20icon], Custom branding name YouTube [App name: ReVanced Extended], Custom double tap length [Double-tap to seek Values: 3, 5, 10, 15, 20, 30, 60, 120, 180], Disable pip notification, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Hide tooltip content, Ambient mode switch, Force video codec, Enable external browser, Enable language switch, Layout switch, Enable minimized playback, Enable open links directly, Disable QUIC protocol, Enable new splash animation, Spoof device dimensions, Change homepage, Hide navigation label, Hide navigation buttons, Enable tablet navigation bar, Overlay buttons [Outline icons: false], Hide autoplay button, Hide captions button, Hide cast button, Hide collapse button, Hide end screen cards, Hide filmstrip overlay, Disable haptic feedback, Hide info cards, Hide music button, Custom player overlay opacity, Hide previous next button, Hide seek message, Disable speed overlay, Hide suggested actions, Hide suggested video overlay, Hide channel watermark, Append time stamps information, Custom seekbar color, Hide seekbar, Enable seekbar tapping, Enable new thumbnail preview, Hide time stamp, Hide shorts components, Disable shorts on startup, Swipe controls, Spoof player parameters, MicroG support, Return YouTube Dislike, SponsorBlock [Outline icons: false], Disable HDR video, Default video quality, Default playback speed, Hide video ads, Force OPUS codec, Spoof app version, Sanitize sharing links, Translations, Settings, Custom playback speed
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Custom branding icon YouTube failed: app.revanced.patcher.patch.PatchException: Invalid app icon path: content://com.android.externalstorage.documents/tree/primary%3ARevanced%20icon
	at app.revanced.patches.youtube.layout.branding.icon.CustomBrandingIconPatch.execute(CustomBrandingIconPatch.kt:133)
	at app.revanced.patches.youtube.layout.branding.icon.CustomBrandingIconPatch.execute(CustomBrandingIconPatch.kt:17)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Applied 1 patches
Compiling patched dex files
Compiled 9 dex files
Compiling modified resources
Signing APK
Patched
```

### Additional context

I have lineage os maybe that's a problem

### Device Environment

Seen in logs

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This error log tells you why the patch failed
(You entered an invalid path)

> Custom branding icon YouTube failed: app.revanced.patcher.patch.PatchException: Invalid app icon path: content://com.android.externalstorage.documents/tree/primary%3ARevanced%20icon 

This shows an example where I used the Custom branding icon patch

![1207074446452835](https://github.com/inotia00/ReVanced_Extended/assets/108592928/dba0fa1e-9902-447d-9c09-c557899cf8a5)


1. Using Apktool M, I moved to the path where the icon exists.
2. Click on the path, then use `Enter path` to copy the value of the current path.
3. I pasted this into the Patch Option of RVX Manager, saved it, and then performed the patch.

**Comment by Turhvjbufv** [comment]
I selected the path using "select folder" option, maybe there is a problem with that or I misunderstood what that's for

**Comment by Turhvjbufv** [comment]
I selected the path using "select folder" option, maybe there is a problem with that or I misunderstood what that's for

**Comment by jont4** [comment]
I'm unable to configure it using rvx-builder. In the description it mentions that it should be informed in options.json, but there is no key/value for the Custom Branding icon. I've tried several key/values, but none worked.
The last I tried:

```json
 "patchName" : "Change branding icon",
  "options" : [ {
    "key" : "AppIcon",
    "value" : "mmt"
    } ]
```

**Comment by inotia00** [comment]
> I'm unable to configure it using rvx-builder. In the description it mentions that it should be informed in options.json, but there is no key/value for the Custom Branding Icon. I've tried several key/values, but none worked.

Probably you are using the outdated `options.json` file

1. If you are using Windows, Linux, or Mac OS
: Just remove the `options.json` file manually

2. If you are using Android (Termux)
: Reinstall rvx-builder (enter command `rvxre`)

If you need the source of the latest `options.json` file, use this:
[options.json](https://github.com/inotia00/ReVanced_Extended/files/13762383/options.json)

**Comment by jont4** [comment]
> > I'm unable to configure it using rvx-builder. In the description it mentions that it should be informed in options.json, but there is no key/value for the Custom Branding Icon. I've tried several key/values, but none worked.
> 
> Probably you are using the outdated `options.json` file
> 
>     1. If you are using Windows, Linux, or Mac OS
>        : Just remove the `options.json` file manually
> 
>     2. If you are using Android (Termux)
>        : Reinstall rvx-builder (enter command `rvxre`)
> 
> 
> If you need the source of the latest `options.json` file, use this: [options.json](https://github.com/inotia00/ReVanced_Extended/files/13762383/options.json)

Now working. Thanks
