### ISSUE TITLE
bug(YouTube Music/Hide general ads): `Close interstitial ads` closes entire app

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1802]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube Music 6.29.58

### Bug description

`Close interstitial ads` closes entire app.
Sorry that i did not add screen recording, i need long time to caught interstitial ad

### Error logs

```shell
:/
```

### Additional context

[ReVanced Extended Music_v6.29.58_2023-12-22.txt](https://github.com/inotia00/ReVanced_Extended/files/13752084/ReVanced.Extended.Music_v6.29.58_2023-12-22.txt)

### Device Environment

Android 13, MiUi 14.0.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It does not reproduce on my side

There were additional changes related to this in revanced-patches-v2.204.1
Please patch again with revanced-patches-v2.204.1 and let me know how it goes

**Comment by girshcatt** [comment]
Is there a tutorial to make interstitial ad appear? Or i need just to restart app until ad will appear?

**Comment by inotia00** [comment]
In my case, I am using multiple Google accounts for A/B testing

It sometimes appears when I switch to a different Google account

**Comment by inotia00** [comment]
This issue also appears to have been resolved, so I'll close it.
If the issue reproduces again, please open a new issue.

**Comment by girshcatt** [comment]
Literally 5 minutes ago i saw interstitial ad and the issue reproduced, please reopen the issue

**Comment by girshcatt** [comment]
I remembered that i have all animations on 0.5x, can it cause this issue?
![Screenshot_2023-12-22-15-42-28-702_com android settings-edit](https://github.com/inotia00/ReVanced_Extended/assets/110785596/70dc8c0d-8a7e-417d-b131-229f6bf4830f)

**Comment by girshcatt** [comment]
Please test it with all animations on 0.5x, because of i will try to make interstitial ad aplear it will take a few weeks(

**Comment by inotia00** [comment]
nvm this feature will be removed in the next release

**Comment by YT-Advanced** [comment]
> nvm this feature will be removed in the next release

This feature on YouTube seem worked, I think you can change it from Exprimental Feature to Normal Feature

**Comment by inotia00** [comment]
`Hide interstitial ads` settings replaces `Close interstitial ads` settings

reflected in [revanced-patches-v2.207.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.207.1)

**Comment by girshcatt** [comment]
> `Hide interstitial ads` settings replaces `Close interstitial ads` settings
> 
> reflected in [revanced-patches-v2.207.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.207.1)

What is this new patch actually do? I thought that it closes interstitial ad by different method, but today i saw an interstitial ad when opened the app

**Comment by inotia00** [comment]
Well.. it appears that Google has changed the way it handles interstitial ads via server sides

Unfortunately I have no plans to fix this anymore

**Comment by girshcatt** [comment]
> Well.. it appears that Google has changed the way it handles interstitial ads via server sides
> 
> Unfortunately I have no plans to fix this anymore

Then is it necessary to keep this patch in rvx?

**Comment by inotia00** [comment]
`Hide interstitial ads` setting will be removed from the final build
