### ISSUE TITLE
bug(YouTube/Hide general ads): `Hide view products banner` setting hides the content of `Store` section in channel profile

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1803]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

Content of `Store` section in channel profile is not visible
Patched YouTube:
![IMG_20231208_123636_134](https://github.com/inotia00/ReVanced_Extended/assets/110785596/628c13aa-57db-4c0d-b08c-d96d4d6635f2)

Unpatched YouTube:
![IMG_20231208_124226_753](https://github.com/inotia00/ReVanced_Extended/assets/110785596/e3258c9a-082f-4ced-9dd9-1fc9ee94e3f3)

### Error logs

```shell
:/
```

### Additional context

My settings:
`"bypass_ambient_mode_restrictions": true,
"custom_filter": true,
"custom_filter_strings": "quality_sheet_header\nbottom_sheet_header",
"custom_playback_speeds": "0.25\n0.5\n0.75\n1.0\n1.25\n1.5\n1.75\n2.0\n2.25\n2.5\n2.75\n3.0",
"default_video_quality_wifi": 1080,
"disable_ambient_mode": true,
"disable_ambient_mode_in_fullscreen": true,
"disable_auto_captions": true,
"disable_haptic_feedback_chapters": true,
"disable_haptic_feedback_scrubbing": true,
"disable_haptic_feedback_seek": true,
"disable_haptic_feedback_seek_undo": true,
"disable_haptic_feedback_zoom": true,
"disable_hdr_video": true,
"enable_custom_playback_speed": true,
"enable_new_splash_animation": false,
"enable_save_playback_speed": true,
"enable_swipe_brightness": false,
"enable_swipe_volume": false,
"enable_wide_search_bar": true,
"external_downloader_package_name": "com.junkfood.seal",
"hide_account_menu": true,
"hide_account_menu_filter_strings": "Оформить YouTube Premium\nТворческая студия YouTube\nYouTube Music\nYouTube Детям\nПокупки и платные подписки\nВаши данные на YouTube\nСправка\/отзыв\nДобавить аккаунт\nВаши видео\nВаши фильмы\nВаши клипы",
"hide_button_remix": true,
"hide_button_report": true,
"hide_button_rewards": true,
"hide_button_shop": true,
"hide_button_thanks": true,
"hide_button_transcript": true,
"hide_captions_button": true,
"hide_category_bar_in_feed": true,
"hide_category_bar_in_related_video": true,
"hide_collapse_button": true,
"hide_comments_thanks_button": true,
"hide_create_shorts_button": true,
"hide_emoji_picker": true,
"hide_end_screen_cards": true,
"hide_feed_flyout_panel": true,
"hide_feed_flyout_panel_filter_strings": "Добавить в начало очереди\nОтправить отзыв",
"hide_game_section": true,
"hide_info_cards": true,
"hide_info_cards_section": true,
"hide_movie_shelf": true,
"hide_music_section": true,
"hide_navigation_label": true,
"hide_place_section": true,
"hide_player_flyout_panel_ambient_mode": true,
"hide_player_flyout_panel_captions_footer": true,
"hide_player_flyout_panel_more_info": true,
"hide_player_flyout_panel_quality_footer": true,
"hide_player_flyout_panel_report": false,
"hide_player_flyout_panel_stable_volume": true,
"hide_podcast_section": true,
"hide_quick_actions": true,
"hide_search_term_thumbnail": true,
"hide_seek_message": true,
"hide_seek_undo_message": true,
"hide_shorts_button": true,
"hide_shorts_toolbar_banner": true,
"hide_shorts_toolbar_camera_button": true,
"hide_shorts_toolbar_menu_button": true,
"hide_shorts_toolbar_search_button": true,
"hide_snack_bar": true,
"hide_suggestions_shelf_method": true,
"hide_transcript_section": true,
"hide_youtube_music_button": true,
"hook_download_button": true,
"overlay_button_always_repeat": false,
"overlay_button_copy_video_url": false,
"overlay_button_external_downloader": false,
"overlay_button_speed_dialog": false,
"spoof_player_parameter": true,
"spoof_player_parameter_in_feed": true,
"switching_create_notification": false,
"ryd_compact_layout": true,
"sb_auto_hide_skip_button": false,
"sb_track_skip_count": false,
"sb_sponsor": "manual-skip",
"sb_selfpromo": "manual-skip",
"sb_interaction": "manual-skip",
"sb_poi_highlight": "seekbar-only",
"sb_intro": "manual-skip",
"sb_outro": "manual-skip",
"sb_preview": "manual-skip",
"sb_filler": "ignore",
"sb_music_offtopic": "manual-skip"`

### Device Environment

Android 12 One Ui 4.1.1, Android 13 MiUi 14.0.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
The filter `expandable_product_grid` in hide product section settings caused this

**Comment by girshcatt** [comment]
> The filter `expandable_product_grid` in hide product section settings caused this

But only filters i use are:
`quality_sheet_header
bottom_sheet_header`

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.205.1](https://github.com/inotia00/revanced-patches/releases)
