### ISSUE TITLE
"Listen with YouTube Music"

### ISSUE THREAD

**Issue by nightznero** [inotia00/ReVanced_Extended#1804]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT v18.46.43
YTM v6.29.57

### Bug description

YT>Additional Settings>"Listen with YouTube Music"
On version 18.43.45 i didn't had that issue but now(idk since when preceed) YT directs me into GP to install YTM while before i normally could continue listening into YTM.

### Additional context

Also would be awesome to have reverse Patch. From YTM to continue watching in normal YT

### Device Environment

A13
OneUI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
That feature only works when used in ROOT environment
