### ISSUE TITLE
bug(YouTube/SponsorBlock): Playback does not advance to the next video of a playlist when skipping a segment at the end of a video

### ISSUE THREAD

**Issue by bigyihsuan** [inotia00/ReVanced_Extended#1805]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.45.43
ReVanced Patches 2.203.2
ReVanced Integrations 0.126.2

### Bug description

When a video is in a playlist, and has a skipped SponsorBlock segment at the very end of the video, playback does not advance to the next video in the playlist.

1. Find a video that has a skippable SponsorBlock segment at the end of it.
2. Place it before any video in a playlist.
3. Let playback skip the segment.
4. Playback will not advance to the next video.

Similar issues with SponsorBlock segments at the end of videos were reported in #1777 (dup #1714) and #1745. The patch notes say that this was fixed in [v2.202.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.202.1), but it is not.

Clip of this happening:
https://youtu.be/AM7zSSDYRw8

Settings:
[ReVanced Extended_v18.45.43_2023-12-08.txt](https://github.com/inotia00/ReVanced_Extended/files/13618974/ReVanced.Extended_v18.45.43_2023-12-08.txt)

### Device Environment

Oneplus 7
Android 12, rooted

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by piviee** [comment]
Hi guys, I'm facing the same issue using RVX Mananger, the video never ends and the timer continues to count with whatever settings is (autoplay/SponsorBlock is enabled or not), and I have to play then next video manually

https://github.com/inotia00/ReVanced_Extended/assets/156946486/e5f595a6-2c8e-4bd3-8076-a88fe9167b45

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1)
