### ISSUE TITLE
suggestion(YouTube): rename `Enable music search` to `Enable song search`

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1806]
### Application

YouTube

### Suggestion description

Rename `Enable music search` to `Enable song search`
![IMG_20231209_125242_849](https://github.com/inotia00/ReVanced_Extended/assets/110785596/07e4d683-788e-4035-bfe8-857ce1f64712)
`Music search` name not mentioned anywhere

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.205.1](https://github.com/inotia00/revanced-patches/releases)
