### ISSUE TITLE
suggestion(YouTube): make `Hide voice search button` patch incompatible with `Enable music search` patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1809]
### Application

YouTube

### Suggestion description

Make `Hide voice search button` patch incompatible with `Enable music search` patch.
`Hide voice search button` patch have no settings, then `Enable music search` patch patched together with it become completely useless

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The `Hide vocie search button` patch hides only the voice search button in the search bar (toolbar), as described in the patch

In other words, this does not disable the voice search activity itself, so you can still access the voice search activity with other methods

For example, the YouTube search bar widget still has a voice search button, and you can click it to open the voice search activity

![YouTube-for-Android-widgets-header](https://github.com/inotia00/ReVanced_Extended/assets/108592928/754b138f-634c-4975-ba90-422c12155ba7)
