### ISSUE TITLE
feat(patch): auto-repeat button on notification widget

### ISSUE THREAD

**Issue by EnzoD33** [inotia00/ReVanced_Extended#181]
### Application

YouTube

### Description

I would love to have a respite button when I listen to music as in the photo
![Picsart_23-01-27_12-03-32-067~2](https://user-images.githubusercontent.com/106279223/215071340-674d227b-8bab-4046-bf21-4d542283ea9b.jpg)
I think it would be useful for a lot of people because whenever I want to listen to music several times in particular I have to go on youtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
