### ISSUE TITLE
bug(YouTube Music/Hide general ads): `Hide premium renewal banner` is not hidden properly

### ISSUE THREAD

**Issue by Ox3rror** [inotia00/ReVanced_Extended#1811]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube music : 6.29.57

Patch : v2.204.1

### Bug description

Hello,

After patching, the app stuck at this get YouTube premium loading screen also when press back or any button, it flickers.  Here's the screenshot: 
![Screenshot_2023-12-10-22-41-52-43_0ee52a21b47f2484ca705d66bfb85bda](https://github.com/inotia00/ReVanced_Extended/assets/132026922/e956b1d4-1a79-4e52-9a8d-f99faed28533)

### Device Environment

Oxygen os 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Let me know the results of your testing without the `Hide general ads` patch

**Comment by Ox3rror** [comment]
After excluding the "Hide general ads" patch, it shows me this message. Strange, As far as I remember, never signed up for the trial, the trial will end dec 23. I think, this trial message triggers something.
![Screenshot_2023-12-11-00-16-48-71_0ee52a21b47f2484ca705d66bfb85bda](https://github.com/inotia00/ReVanced_Extended/assets/132026922/1ca21cf2-74b3-4e9b-9094-6005fca7ceb2)

**Comment by inotia00** [comment]
Thanks for testing
I can confirm that this is a bug caused by the `Hide general ads` patch

I will fix it in the next release

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.205.1](https://github.com/inotia00/revanced-patches/releases)
