### ISSUE TITLE
suggestion: (Custom branding icon YouTube/YouTube Music) add material you icon presets

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1812]
### Application

YouTube

### Suggestion description

Add presets of material you icons of default YouTube/YouTube music. Would be nice to have it if possible since no guides/instructions exist to create one ourselves using custom values.
![Screenshot_2023-12-11-20-58-05-961_com miui gallery-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/553b195d-8ab6-4a7f-bb4c-04081394306a)
 I don't understand why Google don't just support it in their own apps like YouTube and YouTube music as they themselves created material you theming :(

### Acknowledgements

- [x] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
YouTube and YT Music does have material you icons already now.

**Comment by Rairof** [comment]
It wasn't available at the time I posted this suggestion but it's available now. I will be closing this suggestion.
