### ISSUE TITLE
bug(YouTube/Swipe controls): press-to-swipe gesture working on overlays

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1813]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v18.45.43

### Bug description

Press to swipe gesture is working on player overlay and on end screen overlay as well. [vid](https://i.imgur.com/gy4grdw.mp4)

https://github.com/inotia00/ReVanced_Extended/assets/125728453/62214288-cac2-45f0-8d70-7030e8a35d84

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.205.1](https://github.com/inotia00/revanced-patches/releases)
