### ISSUE TITLE
suggestion: Action Bar logo

### ISSUE THREAD

**Issue by longwolfdude** [inotia00/ReVanced_Extended#1814]
### Application

YouTube Music

### Suggestion description

For months I have been adding an action bar logo in the icon patches and it has been working great, but after patch v2.203.1 which combined all icons in one patch among other things with the icon files the extra resource file I added won't register. I attached screenshots of what I mean. I loved that the action bar icon also changed with the icon.
![Screenshot_20231211_215047_Youtube_Music_Vanced](https://github.com/inotia00/ReVanced_Extended/assets/74474209/411adba3-3bf3-4a8d-a42a-f9b262467774)
![Screenshot_20231211_223328_YouTube_Music_Vanced](https://github.com/inotia00/ReVanced_Extended/assets/74474209/26dc5f33-66ca-4f66-9670-27affbca9bb0)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1797#issuecomment-1842176588
