### ISSUE TITLE
question: Will you add gmsCore support?

### ISSUE THREAD

**Issue by chowder908** [inotia00/ReVanced_Extended#1815]
### Application

YouTube

### Question description

the main repo of ReVanced has started working on gmsCore will there be support for it as well for extended repo?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I have no plans to support it
