### ISSUE TITLE
bug(YouTube - Search Results): YouTube showing different categories under results

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1816]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

When the user searches for something in YouTube and when they scroll a bit down, they're initially greeted with a `People also watched`, followed by `For you`, `Previously watched` and finally `From related searches`. And guess what, the cycle repeats as well.

Also it shows up in a grey background which is off-putting. 

Different categories:
![Screenshot_20231213_000208_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/f06ddcee-6d35-473d-b8f0-6f008ad63b57)
![Screenshot_20231213_000216_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/a9a693ed-cd31-48db-9d37-4927c6836641)
![Screenshot_20231213_000221_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/a92cb028-fac0-439e-b33f-db71d4713b44)
![Screenshot_20231213_000232_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/e2e2e3f9-6776-43bd-8c06-0c5ba346d4a9)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
I was unsure whether it should be feature request or bug report and ended up picking bug report. Feel free to change it if necessary.

**Comment by ILoveOpenSourceApplications** [comment]
Another category which I came across just now which is `Latest from (Whatever channel you searched)`:
![Screenshot_20231213_001723_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/01dc577e-3f10-4456-91e6-6a4d13d863b7)

**Comment by inotia00** [comment]
This is a feature YouTube is testing

**Comment by ILoveOpenSourceApplications** [comment]
So it's an A/B testing? Still that implies this is a valid issue right?

**Comment by inotia00** [comment]
The valid bug that dev thinks should meet the following conditions:

Condition 1. This is not reproduced in unpatched YouTube
Condition 2. This is not an intended behavior of the RVX patch

This is very likely that it is a new A/B test of YouTube, so it does not meet condition 1.

There is no patch to hide the 'search results category' in the current RVX patch, so it does not meet condition 2.

**Comment by ILoveOpenSourceApplications** [comment]
Ah, so it should be a feature request then, right?

**Comment by ILoveOpenSourceApplications** [comment]
> I was unsure whether it should be feature request or bug report and ended up picking bug report. Feel free to change it if necessary.

But I already considered that as well. Just wasn't sure which one to pick.

**Comment by inotia00** [comment]
> Ah, so it should be a feature request then, right?

yeah this is more properly a feature request than a bug report

Unfortunately, I no longer accept new feature requests for RVX patches

**Comment by ILoveOpenSourceApplications** [comment]
Understood. Thanks for letting me know and continue up with the good work.

**Comment by ILoveOpenSourceApplications** [comment]
Hi @inotia00, a commit [(55cc7f1)](https://github.com/ReVanced/revanced-patches/pull/1/commits/55cc7f1c7722f56af6d33ea2bd09a1b99d635209) for the same is already done and implemented in ReVanced. Can you add it to RVX as well now?

**Comment by inotia00** [comment]
That commit is from RVX (feature already exists in RVX) https://github.com/inotia00/revanced-integrations/commit/afd7ab663316adc39c491b2d270386ce91db78f3

**Comment by ILoveOpenSourceApplications** [comment]
I think you misunderstood,  as the commit you have shared are for hiding videos with gray description. The one I shared is to hide the categories, I believe.

**Comment by ILoveOpenSourceApplications** [comment]
Hi @inotia00, I don't know if you had time to check the commit (https://github.com/ReVanced/revanced-patches/pull/1/commits/55cc7f1c7722f56af6d33ea2bd09a1b99d635209) and confirm it's the same as your commit (https://github.com/inotia00/revanced-integrations/commit/afd7ab663316adc39c491b2d270386ce91db78f3), but if it's not then implementing it would also close #1820 as well. Just wanted to let you know.
