### ISSUE TITLE
bug(YouTube/Official Headers): Official headers showing up when searching for people

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1817]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

When searching for individuals with YouTube account such as artists and all, official headers are showing up in search results. 

![Screenshot_20231213_000154_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/5db11dee-277f-4dff-88b1-52ef1104736c)
![Screenshot_20231213_001742_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/e98419e1-dfec-4404-8cb6-6c6b3ac6c2e4)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1603#issuecomment-1783724282

**Comment by ILoveOpenSourceApplications** [comment]
Oh, thanks for pointing it out. I'll close this as a duplicate of #1603 .
