### ISSUE TITLE
bug(YouTube/Hide general ads): new type of ads

### ISSUE THREAD

**Issue by thedogismurdered** [inotia00/ReVanced_Extended#1818]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

18.45.43

### Bug description

Search result/ Product ads show up for certain search results.
![Screenshot_20231213-003528](https://github.com/inotia00/ReVanced_Extended/assets/150788169/6cc6f2ec-5e6e-4fe8-b2e7-016e50e74ccc)
![Screenshot_20231213-003449](https://github.com/inotia00/ReVanced_Extended/assets/150788169/92d68e6c-a994-40ad-b943-6e84c1c850d8)

### Device Environment

OOS10

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.205.1](https://github.com/inotia00/revanced-patches/releases)
