### ISSUE TITLE
suggestion: Enable tapping on the navigation buttons at the bottom in a mini window

### ISSUE THREAD

**Issue by Arkuarius** [inotia00/ReVanced_Extended#1819]
### Application

YouTube

### Suggestion description

Every single app on Android let's you click on any button in a mini window, be it close to the borders of the mini window or not.

EXCEPT *any* version of YouTube, be it official, Revanced (Revanced Manager patch), or your project, Revanced-Extended.

YouTube refuses to let you click on the bottom buttons that say "home", "subscriptions", "you" etc. Why? I don't get it.

I know it's just a minor inconvenience, but I'd appreciate it a lot if you fixed this stupid restriction in a future version of Revanced-Extended and finally let us click those buttons on the bottom in a mini window. 

https://github.com/inotia00/ReVanced_Extended/assets/102014881/f9e47669-50f4-477a-996b-e6922e723f7c

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This part depends on the system OS.
It is not an area that can be controlled by the YouTube client.
