### ISSUE TITLE
bug: ReVanced Manager still shows 18.01.38 as Recommended version and not the latest 18.02.37

### ISSUE THREAD

**Issue by giwrgosmant** [inotia00/ReVanced_Extended#182]
### Type

Error while patching

### Application

ReVanced Manger 0.53

### Bug description

ReVanced Manager still shows 18.01.38 as Recommended version and not the latest [18.02.37](https://github.com/inotia00/revanced-patches/releases/tag/v2.156.4)
![rvx manager](https://user-images.githubusercontent.com/51835189/215077978-2bf317bd-6e3c-4a6c-890c-163d0c44e46b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
My patches are 'compatible' with ReVanced Manager, not guaranteed to work in all situations.
Also, I am not a developer or maintainer of ReVanced Manager

So I can't provide any help for issues with ReVanced Manager.

Follow the other method provided by the [documentation](https://github.com/inotia00/revanced-documentation/wiki)

**Comment by giwrgosmant** [comment]
> My patches are 'compatible' with ReVanced Manager, not guaranteed to work in all situations. Also, I am not a developer or maintainer of ReVanced Manager
> 
> So I can't provide any help for issues with ReVanced Manager.
> 
> Follow the other method provided by the [documentation](https://github.com/inotia00/revanced-documentation/wiki)

Seems it take a while for Manager to get the recent stuff.
It's all good now, thanks.
