### ISSUE TITLE
suggestion: Listen with YouTube music.

### ISSUE THREAD

**Issue by QuasarQuipper** [inotia00/ReVanced_Extended#1822]
### Application

YouTube

### Suggestion description

Request to map the "listen with YouTube music button" to YouTube music rvx, Earlier this option was visible only to premium users, but now l'm getting this option for every music video (1 do not have yt premium). It will be very helpful if it can be integrated with YouTube music rvx.

https://github.com/inotia00/ReVanced_Extended/assets/146509963/751beabe-3c4b-49fe-b2e1-f2177adaa947

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1804
