### ISSUE TITLE
bug(YouTube/Change start page): `Podcasts` start page can't be used in some languages

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1823]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

`Podcasts` start page can't be used in some languages, all is easy, in `Russian`(I apologize that same would be with some other languages) `Podcasts` drawer just not exist in `Explore` tab.
When you open app it will just redirect you to `https://www.youtube.com/podcasts`, but this page gives you 404 error:(

Steps to reproduce:
Step 1. Change start page to `Podcasts`
Step 2. Change language to `Russian`
Step 3. Restart the app

https://github.com/inotia00/ReVanced_Extended/assets/110785596/eac44693-99b6-4a35-887f-340c7e0094f4

### Error logs

```shell
:/
```

### Device Environment

Android 12 One Ui 4.1.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Podcast page not available for all account, so I think it is better to add a side effect into the descriptions

**Comment by inotia00** [comment]
Not many people will use the podcast as a start page, so it is not important

I will remove podcasts from the start page list in the next release

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.206.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.206.1)
