### ISSUE TITLE
question: is there no fix for the default video quality issue for some users?

### ISSUE THREAD

**Issue by NMBlanco** [inotia00/ReVanced_Extended#1824]
### Application

YouTube

### Question description

I tried everything that's stated in the Telegram group for fixing the issue with the lag at the beginning of a video, when you enabled default video quality.
Neither does a downgrade to 18.38.44 work for me, nor the option "Skip preloaded buffer". The lag is still there and it's really annoying.
I've seen that most of the users in the telegram group don't have this issue (anymore). So is this some A/B testing and some users are just screwed?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
`Skip preloaded buffer` is an experimental flag, same with `Spoof app version`. 
If option marked as `Experimental flag` this means that it can cause unexpected behaviour and dev won't accept any bug report on it.
Best way is just to patch 18.38.44 or lower

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1730#issuecomment-1826286065
