### ISSUE TITLE
[BUG] Like button glow shape is wrong when using RYD

### ISSUE THREAD

**Issue by GeekCornerGH** [inotia00/ReVanced_Extended#1825]
### Type

Cosmetic issue

### Tools used

CLI

### Application

YouTube 18.45.43

### Bug description

1. Have RYD enabled
2. Go to any video where someone says to smash the like button like [this one](https://youtu.be/obX2WdINsZo)
3. Wait until the like button glows

### Solution

Resize the overlay? I'm not that deep in Android apps dev so I can't really help sorry

### Additional context

![Screenshot_20231214_164304_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/45696571/2e77d96c-2f3a-4ef0-839c-8119f9f7d509)

Take care of yourself also, this is definitly not an important bug, and I can live with it

### Device Environment

Android 13, Samsung One UI 5.1, but probably irrelevant

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1738
