### ISSUE TITLE
Various additions to the YouTube Interface if possible

### ISSUE THREAD

**Issue by SunSea88** [inotia00/ReVanced_Extended#1826]
### Application

YouTube

### Question description

Hello,

Do you think that it's possible to add these following new options for enhanced comfort on YouTube Android please ?

1  Expand automatically the broadcast date, the video description, the long comments under video and the long community posts like this script on YouTube PC
-> https://greasyfork.org/fr/scripts/446954-youtube-expand-description-and-long-comments-show-all-the-replies

2  Show again the Username in comments, community posts... instead of User ID Handle with @ like this script on YouTube PC
-> https://greasyfork.org/fr/scripts/468740-restore-youtube-username-from-handle-to-custom

3  Hide the Most Replayed section in the videos like with uBlockOrigin on YouTube PC
-> https://droidwin.com/how-to-disable-youtube-most-replayed-feature/

4  Hide the videos that are in our private or public playlists in the YouTube Homepage like this script on YouTube PC
-> https://greasyfork.org/fr/scripts/474300-hide-videos-that-are-in-playlist

5  Review all videos, lives, premieres, shorts from a Channel in one place like when everything was in the "Videos" tab only ; Very useful to know what has been posted online in order like this script on YouTube PC
-> https://greasyfork.org/fr/scripts/454215-bring-back-youtube-channel-playlists

6  Put the Timestamps back in the livechat like on YouTube PC

Thank you in advance

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The Android YouTube client is not open source, so implementing features requires quite a bit of reverse engineering.

I am tired of this reverse engineering, so I am no longer accepting any feature requests/suggestions.
