### ISSUE TITLE
bug(YouTube Music): Some lines in input elements are black color and unreadable

### ISSUE THREAD

**Issue by MarcaDian** [inotia00/ReVanced_Extended#1827]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube Music 6.31.55

### Bug description

AMOLED patch is applied. Revanced-patches v2.205.1
Some lines in input elements are black color and unreadable.
More details on the screenshots

![Зображення WhatsApp, дата_ 2023-12-15 о 16 37 39_99aa5ac0](https://github.com/inotia00/ReVanced_Extended/assets/152095496/c708ff4b-fa8d-4b25-b5d3-63261ca51c90)
![Зображення WhatsApp, дата_ 2023-12-15 о 16 37 39_243f0822](https://github.com/inotia00/ReVanced_Extended/assets/152095496/f62a9b02-51cc-4aee-9037-19a7c1803fae)
![Зображення WhatsApp, дата_ 2023-12-15 о 16 37 39_974eb1d5](https://github.com/inotia00/ReVanced_Extended/assets/152095496/509abeaf-bf73-4f65-8910-f54635bd11ab)

### Device Environment

Android 12, MIUI Global 13.0.2.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1456
