### ISSUE TITLE
bug: (YouTube/Sponsorblock) Export and Import Settings are not consistent

### ISSUE THREAD

**Issue by Francesco146** [inotia00/ReVanced_Extended#1829]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 18.45.43 - 2.205.1 patches

### Bug description

currently the settings that can be exported and imported from the RVX settings regarding Sponsorblock are only those of the toggles.

aka these ones:
![IMG_20231215_163422_419](https://github.com/inotia00/ReVanced_Extended/assets/49027005/3371395d-4df7-4369-9147-659d5571eacf)

the statistics settings, which can be imported and exported in the form of JSON from the Sponsorblock settings, are not saved. 

aka these one:

```json
{
  "isVip": false,
  "serverAddress": "https:\/\/sponsor.ajay.app",
  "dontShowNotice": true,
  "showTimeWithSkips": true,
  "minDuration": 0,
  "trackViewCount": false,
  "skipCount": 4,
  "minutesSaved": 90.6617202758789,
  "categorySelections": [
    {
      "name": "sponsor",
      "option": 2
    },
    {
      "name": "selfpromo",
      "option": 2
    },
    {
      "name": "interaction",
      "option": 2
    },
    {
      "name": "poi_highlight",
      "option": 0
    },
    {
      "name": "intro",
      "option": 2
    },
    {
      "name": "outro",
      "option": 2
    },
    {
      "name": "preview",
      "option": 2
    },
    {
      "name": "filler",
      "option": 2
    },
    {
      "name": "music_offtopic",
      "option": 2
    }
  ],
  "barTypes": {
    "sponsor": {
      "color": "#00D400"
    },
    "selfpromo": {
      "color": "#FFFF00"
    },
    "interaction": {
      "color": "#CC00FF"
    },
    "poi_highlight": {
      "color": "#FF1684"
    },
    "intro": {
      "color": "#00FFFF"
    },
    "outro": {
      "color": "#0202ED"
    },
    "preview": {
      "color": "#008FD6"
    },
    "filler": {
      "color": "#7300FF"
    },
    "music_offtopic": {
      "color": "#FF9900"
    }
  }
}
```

the best thing is that these settings are also imported from the RVX settings

### Solution

Add the json from sponsorblock to the txt exported, or even better, use the json format as universal format for the export / import settings, all done in the RVX import setting.

### Device Environment

Android 13 - Samsung Galaxy S10 Lite

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1798
