### ISSUE TITLE
bug: hide button container settings not working

### ISSUE THREAD

**Issue by Abhigaruji** [inotia00/ReVanced_Extended#183]
### Type

Other

### Application

YouTube 18.02.37

### Bug description

Clip,remix,thanks buttons keep showing even after disabling them

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_2023-01-27-17-04-50-41_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/94916875/215083545-18ed1be5-d220-44a2-ab90-25964a885694.jpg)
![Screenshot_2023-01-27-17-04-15-79_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/94916875/215083564-96aa1461-d10b-46fa-a6a1-96b844135689.jpg)
![Screenshot_2023-01-27-17-05-08-82_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/94916875/215083576-56d25c5c-55a6-4ad7-be17-62bf37fee2b0.jpg)
![Screenshot_2023-01-27-17-04-37-89_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/94916875/215083589-0a1917de-cb1a-4947-9bff-0eddc178a3b5.jpg)
![Screenshot_2023-01-27-17-04-25-93_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/94916875/215083601-2c85d53f-1429-4ca0-bfac-3bac75dc38f3.jpg)
![Screenshot_2023-01-27-17-04-32-94_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/94916875/215083620-f2f8475e-2296-41c7-8ab6-bc70b9528a44.jpg)

### Solution

.

### Device Environment

Android 13 oxygen OS 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Abhigaruji** [comment]
Attached to the github bug report


On Friday, 27 January 2023, inotia00 ***@***.***> wrote:
> please attach screenshot
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/Ma-T2D7rLXN2aZcdjh4vUfplZOgi26l8U-gvmU1Q3CE_9K8Ekpb5watD3vazijsnpMXXWpzuXEwNzlQEuDDmTOItzOuI9uGKsqAaFxD_MVN-T_TvJ5ytJ8SP7WawhyHSLQ1vsBG_0maZ-ONkKTn5KmLrcU0cMUfIkc4pfbxBV3k5xOolsa-ANPkK3_sPTrZedhD2CfZ5khWG-I0FezRh_OMrayzd9NfGTbU4dAl4G5uNof2ivQ=s0-d-e1-ft#https://github.com/notifications/beacon/AWUFCC6L7C5WJ4IQTZQJUFTWUO5SDA5CNFSM6AAAAAAUIT4XTOWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTST2R3HG.gif>Message
ID: ***@***.***>

**Comment by Eiskrem** [comment]
I tested the brad pitt video and the patches seem to work for me. I don't see the thanks or clip button.
But maybe it's worth mentioning that I still use the old layout and my account hasn't received the new layout.

**Comment by inotia00** [comment]
yeah.. Unfortunately, it doesn't reproduce on my device despite the same settings
Therefore, it is difficult to provide a fix right now

**Comment by Abhigaruji** [comment]
> yeah.. Unfortunately, it doesn't reproduce on my device despite the same settings Therefore, it is difficult to provide a fix right now

Inotia00  I tried watching video in incognito mode there no issues but when watching it with account logged in this issue is present.
I also tried removing account and readding but no luck.
I also checked it in revanced no issues there 
Any solution?

**Comment by inotia00** [comment]
fixed in revnaced-patches-v2.157.1

**Comment by kyan5221** [comment]
> fixed in revnaced-patches-v2.157.1

@inotia00 

you said this button container issue has been fixed in v2.157.1 but this bug is still being reproduced in the newest patch.
please check if the button container fixed code has been applied on v2.157.1 again.
