### ISSUE TITLE
question: microg_not_installed_warning

### ISSUE THREAD

**Issue by reazord** [inotia00/ReVanced_Extended#1831]
### Application

YouTube

### Question description

after install patch always force close (microg not installed warning) even though I already installed microG

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
MicroG does not run in the background on some manufacturers ROMs

This issue was reported by MIUI and Infinix

Please follow these steps:

Step 1. Uninstall MicroG and RVX if it is installed
Step 2. Download MicroG from the following repository and install it on your device:
https://github.com/inotia00/VancedMicroG/releases/tag/v0.2.27.230755
Step 3. Open VancedMicroG's app information, grant notification permissions, and disable battery optimization
Step 4. If you are using MIUI, grant autostart permission to VancedMicroG according to the following doc:
https://support.counterpath.com/hc/en-us/articles/9937538499479-Managing-Auto-Start-services-on-Xiaomi-Devices
Step 5. Install RVX

**Comment by reazord** [comment]
it's still not working😅

**Comment by inotia00** [comment]
Please leave your Android version, OS, and patch information

(e.g. Android 13, MIUI 14, recommended patches including `MicroG support`)

**Comment by reazord** [comment]
im using android 13 on costum miui 14 rom (miuisr v14)

- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: M2012K11AG
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v18.45.43
Patches version: v2.205.1
Patches added: Alternative thumbnails, Ambient mode switch, Append time
stamps information, Change start page, Custom branding icon YouTube [App
icon: Revancify Blue], Custom branding name YouTube [App name: ReVanced
Extended], Custom double tap length [Double-tap to seek Values: 3, 5, 10,
15, 20, 30, 60, 120, 180], Custom package name [Package name of YouTube:
app.rvx.android.youtube, Package name of YouTube Music:
app.rvx.android.apps.youtube.music], Custom playback speed, Custom player
overlay opacity, Custom seekbar color, Default playback speed, Default
video quality, Disable HDR video, Disable QUIC protocol, Disable auto
captions, Disable haptic feedback, Disable pip notification, Disable shorts
on startup, Disable speed overlay, Enable compact controls overlay, Enable
external browser, Enable gradient loading screen, Enable language switch,
Enable minimized playback, Enable new splash animation, Enable new
thumbnail preview, Enable old quality layout, Enable open links directly,
Enable seekbar tapping, Enable tablet mini player, Enable tablet navigation
bar, Enable wide search bar, Force OPUS codec, Force fullscreen, Force
video codec, Hide account menu, Hide auto player popup panels, Hide
autoplay button, Hide autoplay preview, Hide button container, Hide
captions button, Hide cast button, Hide category bar, Hide channel avatar
section, Hide channel profile components, Hide channel watermark, Hide
collapse button, Hide comment component, Hide crowdfunding box, Hide
description components, Hide end screen cards, Hide end screen overlay,
Hide feed flyout panel, Hide filmstrip overlay, Hide floating microphone,
Hide fullscreen panels, Hide general ads, Hide handle, Hide info cards,
Hide latest videos button, Hide layout components, Hide load more button,
Hide mix playlists, Hide music button, Hide navigation buttons, Hide
navigation label, Hide player flyout panel, Hide previous next button, Hide
search term thumbnail, Hide seek message, Hide seekbar, Hide shorts
components, Hide snack bar, Hide suggested actions, Hide suggested video
overlay, Hide suggestions shelf, Hide time stamp, Hide toolbar button, Hide
tooltip content, Hide trending searches, Hide video ads, Layout switch,
MicroG support, Overlay buttons [Outline icons: false], Quick actions
components, Return YouTube Dislike, Sanitize sharing links, Settings,
SponsorBlock [Outline icons: false], Spoof app version, Spoof device
dimensions, Spoof player parameters, Swipe controls, Theme [Dark theme
background color: @android:color/black, Light theme background color:
@android:color/white], Translations
Patches removed: Custom package name [Package name of YouTube:
app.rvx.android.youtube, Package name of YouTube Music:
app.rvx.android.apps.youtube.music], Hide general ads, Alternative
thumbnails, Hide button container, Hide comment component, Hide feed flyout
panel, Enable old quality layout, Hide player flyout panel, Hide autoplay
preview, Enable compact controls overlay, Hide end screen overlay, Force
fullscreen, Hide fullscreen panels, Quick actions components, Hide account
menu, Disable auto captions, Hide auto player popup panels, Hide category
bar, Hide channel avatar section, Hide channel profile components, Hide
crowdfunding box, Hide description components, Hide floating microphone,
Hide handle, Hide latest videos button, Hide layout components, Enable
gradient loading screen, Hide load more button, Hide mix playlists, Hide
search term thumbnail, Hide snack bar, Change start page, Hide suggestions
shelf, Enable tablet mini player, Hide toolbar button, Hide trending
searches, Enable wide search bar, Custom branding icon YouTube [App icon:
Revancify Blue], Custom branding name YouTube [App name: ReVanced
Extended], Custom double tap length [Double-tap to seek Values: 3, 5, 10,
15, 20, 30, 60, 120, 180], Disable pip notification, Theme [Dark theme
background color: @android:color/black, Light theme background color:
@android:color/white], Hide tooltip content, Ambient mode switch, Force
video codec, Enable external browser, Enable language switch, Layout
switch, Enable minimized playback, Enable open links directly, Disable QUIC
protocol, Enable new splash animation, Spoof device dimensions, Hide
navigation label, Hide navigation buttons, Enable tablet navigation bar,
Overlay buttons [Outline icons: false], Hide autoplay button, Hide captions
button, Hide cast button, Hide collapse button, Hide end screen cards, Hide
filmstrip overlay, Disable haptic feedback, Hide info cards, Hide music
button, Custom player overlay opacity, Hide previous next button, Hide seek
message, Disable speed overlay, Hide suggested actions, Hide suggested
video overlay, Hide channel watermark, Append time stamps information,
Custom seekbar color, Hide seekbar, Enable seekbar tapping, Enable new
thumbnail preview, Hide time stamp, Hide shorts components, Disable shorts
on startup, Swipe controls, Spoof player parameters, MicroG support, Return
YouTube Dislike, SponsorBlock [Outline icons: false], Disable HDR video,
Default video quality, Default playback speed, Hide video ads, Force OPUS
codec, Spoof app version, Sanitize sharing links, Translations, Settings,
Custom playback speed
Options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Compiling patched dex files
Compiled 8 dex files
Signing APK
Patched
