### ISSUE TITLE
bug: Revanced-extended Search suggestions doesn't appear

### ISSUE THREAD

**Issue by Viper241** [inotia00/ReVanced_Extended#1832]
### Type

Other

### Tools used

CLI

### Application

App version- 18.45.43

### Bug description

In the past, YouTube search suggestions would display as typed in the search bar, offering a convenient way to find content. However, I've now observed that the area for search suggestions stays black, rendering them invisible.
Despite exploring the revanced extended settings and experimenting with options like enabling search history and trending searches, the problem persists. It's worth noting that this function worked smoothly in the past.
![Screenshot_20231217-014751](https://github.com/inotia00/ReVanced_Extended/assets/154020179/bc6eec05-9bd9-429b-9d11-e8d3ffe903d9)

### Device Environment

Android 14, Pixel 6

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Check if the issue persists in the unpatched YouTube

**Comment by Viper241** [comment]
> Check if the issue persists in the unpatched YouTube

Checked it on the normal unpatched YouTube, it works fine there. 

![Screenshot_20231217-024530](https://github.com/inotia00/ReVanced_Extended/assets/154020179/c7a641d3-7713-4f83-9e45-bc92240e1f2d)

**Comment by inotia00** [comment]
If so, you need to manually exclude each patch one by one to find out which patch is causing the issue.

At least for me, search term suggestions are displayed normally.

**Comment by Viper241** [comment]
> If so, you need to manually exclude each patch one by one to find out which patch is causing the issue.
> 
> At least for me, search term suggestions are displayed normally.

I checked it on two other device (Samsung S21 and Samsung S20 ultra) it works fine on them. I exported their settings and imported it to my phone (pixel 6, android 14) yet it doesn't work. The search suggestions doesn't appear. 

Also I tried installing the v18.33.40 and v18.33.37. The problem remains the same on my phone, but works on the others.

**Comment by inotia00** [comment]
If so, it is more likely not an issue with RVX

If this is clearly an RVX issue, it should be reproducible following specific steps on all devices.

Otherwise, this is impossible to reproduce even on the dev side, and of course it is impossible to fix it.

Just my opinion, but it's most likely an issue on your side.

Please re-open the issue with more specific information about which patch is causing the issue and what steps can be taken to reproduce the bug.
