### ISSUE TITLE
bug:(YouTube/Hide Premium controls menu) not working

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1834]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

Premium controls menu options don't get hidden when option is toggled on.

### Error logs

```shell
N/A
```

### Solution

Resolve said option

### Additional context

Referenced issue pictures-
![Screenshot_2023-12-18-07-53-02-483_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/2b35229e-5510-41b3-a719-88dc918f4fa7)
![Screenshot_2023-12-18-07-56-35-078_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/771ce746-a05a-4799-8044-0aff404be70c)

### Device Environment

Android 13, miui 14.0.7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
This is premium controls.

![YouTube-Premium-Listening-Controls-Android.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/bf89e2d5-e698-460b-9bdf-eb9fea22c058)

If you'd like to hide "Play next in queue" from the feed flyout menu, open settings > ReVanced Extended > Flyout menu > Hide feed flyout menu, On.

Then enter `Play next in queue` into the feed flyout menu filter on a new line. (For non-english users, they will need to enter the text as it appears in their language.)

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1834#issuecomment-1859307536
I see, thank you
