### ISSUE TITLE
Remove save buttn in now playing screen

### ISSUE THREAD

**Issue by Shivamhobbyist** [inotia00/ReVanced_Extended#1835]
### Application

YouTube Music

### Feature description

Plz add option to remove save buton on player i never use it
![Screenshot_20231219_152225_@Shivam_hobbyist](https://github.com/inotia00/ReVanced_Extended/assets/78287172/8632f05a-6f07-46b0-86c4-4a9fb50a0a70)

### Motivation

What motivation can you get from this button??
Nothing

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1351
