### ISSUE TITLE
bug:(YouTube Music/Edit custom filter) preset text not properly visible and gets cut off

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1836]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube Music v6.31.55

### Bug description

The preset text is black and blends in with background colour making it harder to read also not entire sentence can be read in it as it gets cut off after space runs out.
![Screenshot_2023-12-19-20-52-36-540_app rvx android apps youtube music-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/47fd91cc-3b60-4779-bb63-a1fafc53b97e)

### Error logs

```shell
N/A
```

### Solution

Resolve relevant issues by adaptive text colour based on background and have horizontal scrolling.

### Additional context

N/A

### Device Environment

Android 13 miui 14.0.7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1456
