### ISSUE TITLE
bug(YouTube/Hide comment component): Thanks button isn't hidden

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1837]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

Even though the `hide thanks button` option is enabled,  thanks button is showing up when trying to comment.

![Screenshot_20231219_191717_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/ba3dae4e-f573-451c-8be8-48324cb2a17d)
![Screenshot_20231219_191854_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/333be5ea-9391-4292-bc8c-d1258aa8fd5a)

### Additional context

Link to the video in which I had the issue:
https://youtu.be/oQA_Z08zyHM

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Same.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.207.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.207.1)
