### ISSUE TITLE
bug(YouTube/Default Video Quality):  Video quality preview is hidden in settings 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1838]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

The default video quality settings hides the preview of what the value is unit the user selects the setting. 
![Screenshot_20231219_193046_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/d366a4e4-344e-4605-abf2-42a9bded5b35)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
Is the issue closed because it's an intended behavior or is there anything missing from my end?

**Comment by inotia00** [comment]
Just choose the quality you prefer
