### ISSUE TITLE
suggestion(YouTube): separate `Reset to default` part from toasts

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1839]
### Application

YouTube

### Suggestion description

Separate `Reset to default` part from toasts. Some roms like MiUi have terrible thing, toasts can accommodate only few words. For example on Samsung devices it will look like this:
Custom speeds can't be more than %sx. Reset to default values.
And how on MiUi:
Custom speeds can't be more than %sx...
Do this like main toast will appear at first, and `Reset to default values.` toast will appear right after it.

List of strings, that contain `Reset to default values.`
YT:
revanced_custom_playback_speeds_invalid
revanced_custom_playback_speeds_warning
revanced_custom_player_overlay_opacity_warning
revanced_quick_actions_margin_top_warning
YTM:
revanced_custom_filter_strings_warning
revanced_custom_playback_speeds_invalid

`revanced_change_start_page_warning`, `revanced_custom_filter_strings_warning` toasts will show all normally in English, but translations for other languages as Russian can have this problem, please separate `Resetting to default.` part for them

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Does separating toasts into two lines help with this? Or is the only workaround to have 2 separate toasts?

**Comment by girshcatt** [comment]
MiUi/HyperOS cuts the toast after a certain number of characters. So only workaround is to have 2 separate toasts

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
