### ISSUE TITLE
bug: Automatic switching to default resolutions is currently broken

### ISSUE THREAD

**Issue by GUImodder** [inotia00/ReVanced_Extended#184]
### Type

Error at runtime

### Application

Revanced Extended Youtube 18.01.36

### Bug description

If you start a video on Mobile/WIFI then you switch to/from mobile/WIFI i.e. leave the house or get in your car the switching to default resolutions only works for the next video. In classic vanced you used to set a default resolution for Wifi/Mobile. Once the video ran out the buffer and switched to mobile/wifi it set the new appropriate Resolution selected as a default.

### Steps to reproduce

1. Start any video on either Wifi/mobile 2. Switch to wifi if you started on mobile/switch to mobile if you started on Wifi 3. recognise that automatic Resolution defaults are not enforced upon switching the connection modes

### Relevant log output

```shell
No log for this because NOTHING happens when a switch is supposed to happen
```

### Screenshots or videos

no point in doing that

### Solution

Fix the Resolution switching at the first reload/buffering on the new connection type

### Additional context

None

### Device Environment

Android 12 Oxygen OS 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Since it is most likely a Stock YouTube issue, I can't fix it

**Comment by GUImodder** [comment]
> Since it is most likely a Stock YouTube issue, I can't fix it
