### ISSUE TITLE
couldn't compile apk due to error 

### ISSUE THREAD

**Issue by EnderNon** [inotia00/ReVanced_Extended#1840]
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: NTH-NX9
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.40.34
Patches version: v2.195.12
Patches added: Alternative thumbnails, Ambient mode switch, Append time stamps information, Change homepage, Custom branding icon Revancify Blue, Custom branding name YouTube [App name: Myrd's 2nd Pot], Custom double tap length [Double-tap to seek Values: 3, 5, 10, 15, 20, 30, 60, 120, 180], Custom package name [Package name of YouTube: com.endernon.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Custom playback speed, Custom player overlay opacity, Custom seekbar color, Default playback speed, Default video quality, Disable HDR video, Disable QUIC protocol, Disable auto captions, Disable haptic feedback, Disable pip notification, Disable shorts on startup, Disable speed overlay, Enable compact controls overlay, Enable debug logging, Enable external browser, Enable gradient loading screen, Enable language switch, Enable minimized playback, Enable new splash animation, Enable new thumbnail preview, Enable old quality layout, Enable open links directly, Enable seekbar tapping, Enable tablet mini player, Enable tablet navigation bar, Enable wide search bar, Force OPUS codec, Force video codec, Hide account menu, Hide auto player popup panels, Hide autoplay button, Hide autoplay preview, Hide button container, Hide captions button, Hide cast button, Hide category bar, Hide channel avatar section, Hide channel watermark, Hide collapse button, Hide comment component, Hide crowdfunding box, Hide description components, Hide end screen cards, Hide end screen overlay, Hide feed flyout panel, Hide filmstrip overlay, Hide floating microphone, Hide fullscreen panels, Hide general ads, Hide handle, Hide info cards, Hide latest videos button, Hide layout components, Hide load more button, Hide mix playlists, Hide music button, Hide navigation buttons, Hide navigation label, Hide player button background, Hide player flyout panel, Hide previous next button, Hide seek message, Hide seekbar, Hide shorts components, Hide snack bar, Hide suggested actions, Hide suggested video overlay, Hide suggestions shelf, Hide time stamp, Hide toolbar button, Hide tooltip content, Hide trending searches, Hide video ads, Layout switch, MicroG support, Overlay buttons [Outline icons: false], Premium heading [Use premium heading: true], Quick actions components, Return YouTube Dislike, Settings, SponsorBlock [Outline icons: false], Spoof app version, Spoof device dimensions, Spoof player parameters, Swipe controls, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Translations
Patches removed: Custom package name [Package name of YouTube: com.endernon.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Hide general ads, Alternative thumbnails, Hide button container, Hide comment component, Hide feed flyout panel, Enable old quality layout, Hide player flyout panel, Hide autoplay preview, Enable compact controls overlay, Hide end screen overlay, Hide fullscreen panels, Quick actions components, Hide account menu, Disable auto captions, Hide auto player popup panels, Hide category bar, Hide channel avatar section, Hide crowdfunding box, Hide description components, Hide floating microphone, Hide handle, Hide latest videos button, Hide layout components, Enable gradient loading screen, Hide load more button, Hide mix playlists, Hide snack bar, Hide suggestions shelf, Enable tablet mini player, Hide toolbar button, Hide trending searches, Enable wide search bar, Custom branding icon Revancify Blue, Custom branding name YouTube [App name: Myrd's 2nd Pot], Custom double tap length [Double-tap to seek Values: 3, 5, 10, 15, 20, 30, 60, 120, 180], Disable pip notification, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Hide tooltip content, Ambient mode switch, Force video codec, Enable external browser, Enable language switch, Layout switch, Enable minimized playback, Enable open links directly, Disable QUIC protocol, Enable new splash animation, Spoof device dimensions, Translations, Change homepage, Hide navigation label, Hide navigation buttons, Enable tablet navigation bar, Overlay buttons [Outline icons: false], Hide autoplay button, Hide captions button, Hide cast button, Hide collapse button, Hide end screen cards, Hide filmstrip overlay, Disable haptic feedback, Hide info cards, Hide music button, Hide player button background, Custom player overlay opacity, Hide previous next button, Hide seek message, Disable speed overlay, Hide suggested actions, Hide suggested video overlay, Hide channel watermark, Append time stamps information, Custom seekbar color, Hide seekbar, Enable seekbar tapping, Enable new thumbnail preview, Hide time stamp, Hide shorts components, Disable shorts on startup, Swipe controls, Spoof player parameters, MicroG support, Return YouTube Dislike, SponsorBlock [Outline icons: false], Disable HDR video, Default video quality, Default playback speed, Hide video ads, Force OPUS codec, Spoof app version, Settings, Custom playback speed
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 95 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~rd_EPCTrSSrbDycx12GPlA==/app.rvx.manager.flutter-zz1QIPj6nFXq7Fm7cAvFUA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-DHKHDI/cache/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-DHKHDI/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:354)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~rd_EPCTrSSrbDycx12GPlA==/app.rvx.manager.flutter-zz1QIPj6nFXq7Fm7cAvFUA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-DHKHDI/cache/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-DHKHDI/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
	... 7 more

**Comment by EnderNon** [comment]
found the issue according to numerous StackOverflow threads:

use aapt2 instead of aapt.

**Comment by inotia00** [comment]
![note](https://github.com/inotia00/ReVanced_Extended/assets/108592928/f7dfb68e-8ef8-4b3d-8b33-330f3cdbff13)
yep
