### ISSUE TITLE
suggestion: regarding overlay buttons patch

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1841]
### Application

YouTube

### Suggestion description

this issue of very little space between seekbar and overlay buttons has made me to skip overlay buttons patch because many a times i tap the seekbar when i want to tap the overlay button. without the overlay button patch, the default space between seekbar and fullscreen button is sufficient, but the overlay button patch if included, reduces that space.
i suggest not to decrease this space in overlay buttons patch, because onsmall screen phone it becomes difficult to tap seekbar or overlay buttons

these are the tested bottom paddings to restore original spacing like youtube app, please consider (i could open pr if i knew code)-
* dont decrease timesamps and chapters bottom padding
![Web capture_21-12-2023_72429_github com](https://github.com/inotia00/ReVanced_Extended/assets/87489540/1c89ae3d-776a-45f5-b627-30e5c7623e74)

* increase overlaybuttons and fullscreen buttons bottom padding to 31.0dip
![Web capture_21-12-2023_72213_github com](https://github.com/inotia00/ReVanced_Extended/assets/87489540/e4e21577-a7c5-4950-9373-7e45b18f5741)

screenshots attached below, can see that chapters, timestamp and overlay buttons all aligned perfectly

![2](https://github.com/inotia00/ReVanced_Extended/assets/87489540/bfa4ef41-4012-4e30-8079-fbb6b3e78b73)
![4](https://github.com/inotia00/ReVanced_Extended/assets/87489540/798b94ae-9e90-424f-a5bc-d3570d91df63)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a reasonable suggestion.

If you make the bottom padding more wider, there is an issue where the button's click effect is located in the wrong position.
(See the attached screenshot)

![Click_Effect](https://github.com/inotia00/ReVanced_Extended/assets/108592928/af77a0c8-9ad1-4d62-a42b-18f932471545)

This is why I haven't accepted this suggestion so far.

Despite these known issues, this suggestion can be useful for devices for some high resolutions.

Therefore, I will reflect this suggetion in `Patch Options`.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.210.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.210.1)

**Comment by MondayNitro** [comment]
thank you!

**Comment by MondayNitro** [comment]
> This is a reasonable suggestion.
> 
> If you make the bottom padding more wider, there is an issue where the button's click effect is located in the wrong position. (See the attached screenshot)
> 
> ![Click_Effect](https://private-user-images.githubusercontent.com/108592928/293914934-af77a0c8-9ad1-4d62-a42b-18f932471545.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMjUzMTQsIm5iZiI6MTcwNDMyNTAxNCwicGF0aCI6Ii8xMDg1OTI5MjgvMjkzOTE0OTM0LWFmNzdhMGM4LTlhZDEtNGQ2Mi1hNDJiLTE4ZjkzMjQ3MTU0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMzM2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQxNmUwOTA5ZDZhM2ZlYmJjYTFhMmYzMDYwZDM5YzUzZTg0MTIwYTMwYjU2OTkwNDg5OTBiNGJiYmFiOThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.McgO1VKJas1Ov5QADPwrQJa5nB3NqLNyeOsAHiWAdqg)
> 
> This is why I haven't accepted this suggestion so far.
> 
> Despite these known issues, this suggestion can be useful for devices for some high resolutions.
> 
> Therefore, I will reflect this suggetion in `Patch Options`.

maybe the touchbox is positioned wrongly because in stock youtube, id/fullscreen_button is 60x60 box, but in rvx on using overlay buttons patch, it(and other overlay buttons) become 48x48

![Screenshot 2024-01-04 051300](https://github.com/inotia00/ReVanced_Extended/assets/87489540/958adf66-a374-4782-8c7d-ae6a8df23e26)

**Comment by inotia00** [comment]
This is intentional behavior

There are a total of 6 buttons supported by Overlay Buttons, and if the default size is maintained, the overlay button invades other layouts.

Therefore, I had no choice but to reduce the size of each button to 48x48.

**Comment by MondayNitro** [comment]
how about disabling the button tap circle for users who enable WiderBottomPadding (like hide double tap overlay filter), if its possible to do so
