### ISSUE TITLE
bug(YouTube/Enable wide search bar): layout breaks on devices above 720 dpi

### ISSUE THREAD

**Issue by kitadai31** [inotia00/ReVanced_Extended#1843]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

YouTube v18.45.43

### Bug description

If `Enable wide search bar` patch is included, various problems occur on tablet devices.

- Cannot open channel pages with 400 error
- History is not displayed
- Shorts are disabled
- UI layout such as Home tab or Search result seems old

This is reproducible with minimal patches (only `MicroG support` and `Enable wide search bar`)

### Screenshots

<details>

<summary>Screenshots of wide search bar patch included</summary>

Channel page

![channel_page](https://github.com/inotia00/ReVanced_Extended/assets/90122968/5f4de95d-82ea-4b2b-bf4c-8c44dd226d65)

History

![history_not_shown](https://github.com/inotia00/ReVanced_Extended/assets/90122968/d81803ed-5c65-4144-b448-938e14639c13)

Layout

![home_ui](https://github.com/inotia00/ReVanced_Extended/assets/90122968/f49a544b-904b-46dd-b7cf-4c7be64bab62)

</details>

<details>

<summary>Screenshots of wide search bar patch excluded</summary>

Channel page

![channel_page](https://github.com/inotia00/ReVanced_Extended/assets/90122968/2aadde71-9923-4581-9dcf-b38795b43303)

History

![history_shown](https://github.com/inotia00/ReVanced_Extended/assets/90122968/17aedcf3-75e9-475b-b214-0400e3f66246)

Home layout

![home_ui](https://github.com/inotia00/ReVanced_Extended/assets/90122968/185a0f6a-9263-43ff-b8ad-19d8408c4c05)

</details>

### Solution

- Turning on "Enable wide search bar" setting partially fixes this issue (At least I can open channel pages)
- Turning on "Enable phone layout" setting partially fixes this issue
- Turning on "Enable tablet layout" setting almost fixes this issue (even the device is tablet)

### Device Environment

Android Emulator (x86_64, Pixel Tablet 10.95 inch Android 12L)

Also this user is Huawei MediaPad M5, Android 9
https://t.me/revanced_extended_chat/284659

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Thank you for reporting very specific information
After confirmation, I will reflect it in the next release

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.207.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.207.1)
