### ISSUE TITLE
bug(YouTube): `Hide comments by members banner` isn't working

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1845]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

`Hide comments by members banner` isn't working

![Screenshot_2023-12-23-20-01-57-636_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/4a50fbbc-d9e2-4ab7-a8fb-bcb0aabc500a)
![Screenshot_2023-12-23-20-02-21-922_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/993f001d-9271-49c3-bead-260ebecb7f30)

### Device Environment

Android 12 One Ui 4.1.1, Android 13 MiUi 14.0.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
attach screenshot

**Comment by girshcatt** [comment]
I checked, isn't working on phone too

**Comment by girshcatt** [comment]
> attach screenshot

Attached

**Comment by inotia00** [comment]
![Comments_by_members](https://github.com/inotia00/ReVanced_Extended/assets/108592928/0f47ce39-6060-4df0-800e-b01319ab9616)

`Hide comments by members banner` setting hides only this banner as the name suggests

It is not to hide the `Members` tab

**Comment by girshcatt** [comment]
Please, can you attach screenshot of this banner in Russian for translations?

**Comment by inotia00** [comment]
![Comments_by_members_RU](https://github.com/inotia00/ReVanced_Extended/assets/108592928/a22491e0-d2fe-4126-85e2-6b7b2ccb643f)

```
Комментарии спонсоров
```
