### ISSUE TITLE
bug(YouTube Music/Settings): Overlay when section opened don't showing in `ReVanced Extended`, `Return YouTube Dislike`, `SponsorBlock`, `About YouTube Music` sections

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1846]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube Music 6.29.58

### Bug description

Overlay when section opened don't showing in `ReVanced Extended`, `Return YouTube Dislike`, `SponsorBlock`, `About YouTube Music` sections

Unpatched YTM:

https://github.com/inotia00/ReVanced_Extended/assets/110785596/87310167-39b6-4a5b-a32a-717d2c1fa3fe

Patched YTM:

https://github.com/inotia00/ReVanced_Extended/assets/110785596/01627c2b-fcad-450e-bcf0-2a735424e75a

### Error logs

```shell
:/
```

### Device Environment

Android 12 One Ui 4.1.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an issue that cannot be solved due to the limitations of the current method of implementation of the patch.
