### ISSUE TITLE
bug(YouTube Music/Hide general ads): `Hide interstitial ads` breaks layout

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1847]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube Music 6.29.58

### Bug description

`Hide interstitial ads` hides second line of videos in `Listen again` section and second row of `Grid View` in library

![IMG_20231224_201459_825](https://github.com/inotia00/ReVanced_Extended/assets/110785596/84bac770-5075-4e0c-bbea-91315f6ed8ce)

![IMG_20231224_201459_271](https://github.com/inotia00/ReVanced_Extended/assets/110785596/1c82ea21-0776-47de-9fa7-11f13b591638)

### Error logs

```shell
:/
```

### Device Environment

Android 12 One Ui 4.1.1, Android 13 MiUi 14.0.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
exclude one patch one by one and tell me which patch causes issues.

**Comment by girshcatt** [comment]
I just tried to switch some settings and now we know that `Hide interstitial ads` causes this issue

**Comment by Aryan-Chauhan** [comment]
When "Hide Interstitial Ads" is enabled/disabled.
![ResizedImage_2023-12-25_08-40-17_1861.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/8d72df1e-9300-40fe-8def-caf8eb1d0a76)

![ResizedImage_2023-12-25_08-41-26_1463.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/7b4d8455-5fdb-4635-9914-ca67542a4fa3)

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.208.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.208.1)
