### ISSUE TITLE
bug(Reddit/Change package name): force close occurs when patch is applied from RVX Manager

### ISSUE THREAD

**Issue by TheWitch69** [inotia00/ReVanced_Extended#1848]
### Type

Other

### Tools used

RVX Manager

### Application

Reddit 2023.50.1

### Bug description

With included change package name patch (default or clone) for Reddit app dont want open just crash working perfect with original package name

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.208.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.208.1)
