### ISSUE TITLE
suggestion: Expanding Comment section when "Hide preview comment" Turned on

### ISSUE THREAD

**Issue by Baseduserrr** [inotia00/ReVanced_Extended#1849]
### Application

YouTube

### Suggestion description

Please can you extend the comment section a little bit when turning on "Hide preview comment" because Its size is exaggeratedly small
Here is a pic how it looks like :
![3ny2e0m5518c1](https://github.com/inotia00/ReVanced_Extended/assets/153088092/eeb38a8c-6389-4da2-afee-0ede1b1d4003)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MondayNitro** [comment]
i think it's font fault, ive seen similar issue on gboard buttons with some fonts
![photo_6071150540680707606_x](https://github.com/inotia00/ReVanced_Extended/assets/87489540/d152ac5c-7232-46a9-b9b9-7e6cc7a9ddbe)
gsp font is shown in correct position

**Comment by Baseduserrr** [comment]
any font recommended or the font that you using in the screenshot ???

**Comment by MondayNitro** [comment]
> any font recommended or the font that you using in the screenshot ???

google sans prime

**Comment by Baseduserrr** [comment]
give me the link please
