### ISSUE TITLE
feat(patch): Remove "New Playlist" button from library tab

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#185]
### Application

YouTube Music

### Issue

Please add an patch to remove the intrusive "create new playlist" button in library. Or optionally make it when scrolling down the button goes away/hides.

### Patch

![Screenshot_20230128-014639749 (1)](https://user-images.githubusercontent.com/73917917/215232097-47449864-0fb9-41d1-a39d-b9eb53ca6bc7.jpg)

### Motivation

Remove unneccesary element.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.18)
