### ISSUE TITLE
suggestion(YouTube Music/Hide navigation buttons): do description of `Hide explore button` shorter

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1850]
### Application

YouTube Music

### Suggestion description

Do description of `Hide explore button` shorter, from: Hides the explore button in navigation bar. to: Hides the explore button.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a result reflected in the following suggestions: https://github.com/inotia00/ReVanced_Extended/issues/1748

The descriptions of all settings have been unified to ensure consistency in hide navigation buttons settings.
