### ISSUE TITLE
question(YouTube/Hide button container): attach screenshots of `Transcript` and `Rewards button` in Russian for translations

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1851]
### Application

YouTube

### Question description

Please attach screenshots of `Transcript` and `Rewards button` in Russian for translations

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
1. The rewards button is not always visible.

So I couldn't take a screenshot

Instead, I will attach the URL of Google's official document.

https://support.google.com/googleplay/answer/10197218?hl=en

https://support.google.com/googleplay/answer/10197218?hl=ru

According to the official document, the Russian word for the reward button is `Бонусы`

2. In the case of the Transcript button, the features that existed in ReX in the past were merged.

https://github.com/YT-Advanced/RVX_BUG_CENTER/issues/1

After searching, it appears that this feature removed from button container relatively recently.

Reference https://youtu.be/7YkWTWRo8cc

It will also be removed in RVX patch in the near future.
