### ISSUE TITLE
question: is it impossible to add "search bar channels" on RVX ?

### ISSUE THREAD

**Issue by Baseduserrr** [inotia00/ReVanced_Extended#1852]
### Application

YouTube

### Question description

Is it impossible to add that "Search videos in specific channel" feature it's already on desktop and mobile web YT so I'm asking is it impossible to be added on RVX 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unfortunately it is not possible
If you need to search for channels, use the web.

**Comment by Baseduserrr** [comment]
Ok. Thanks for your clarification
