### ISSUE TITLE
bug: SponsorBlock (Non-Music)

### ISSUE THREAD

**Issue by nightznero** [inotia00/ReVanced_Extended#1854]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YTM v6.29.58

### Bug description

in YTM The Non-Music section from SB doesn't work properly after few songs(like 5or so) if played in the background. Have to open again and then works again,idk it's important but I think on songs where starts with that segment appears that issue

### Solution

Should skip immediately segments

### Device Environment

SM s20 Ultra OneUI 5.1 A13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue has already been fixed in revanced-patches-v2.207.1

If you have not patched within the last 12 hours, please patch again with the latest patch.
