### ISSUE TITLE
bug(YouTube Music): 'Hide interstitial ads' causes Grid View in library to a singular row

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1855]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube Music 6.31.55
patch v2.207.1

### Bug description

When 'Hide interstitial ads' setting is enabled, Grid view in library only displays a single row.

<img src="https://github.com/inotia00/ReVanced_Extended/assets/125728453/aebfb503-3a37-4366-bba9-02b9eef2b619" width="300">

Same thing happens in landscape mode.
<img src="https://github.com/inotia00/ReVanced_Extended/assets/125728453/c84f8ce1-e6e9-4047-8886-899f4c1a26b7" width="600">

Steps to reproduce-
1. Enable 'Hide interstitial ads'
2. Go to library and switch to [grid view](https://imgur.com/KI3bp6q)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
integrate to https://github.com/inotia00/ReVanced_Extended/issues/1847

**Comment by girshcatt** [comment]
> integrate to #1847

I am already integrated
