### ISSUE TITLE
bug(YouTube Music/Hide category bar): Hide category bar also hides the category bar in the library tab

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1856]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube Music 6.31.55
patch v2.207.1

### Bug description

When 'Hide category bar' is enabled, the Category bar is also hidden in the Library tab as well. 

Shown
<img src="https://i.imgur.com/HiHFrPT.jpg" width="600">

Hidden
<img src="https://i.imgur.com/3ujcTL4.jpg" width="600">

Steps-
1. Include `Hide category bar` patch.
2. Enable ReVanced Extended> General> Hide category bar
3. Look at the library tab.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is intended behavior

**Comment by hlytus** [comment]
Oh ok. If that's the case, then patch and setting description should be changed — "Hides the music category bar at the top of the homepage." to "Hides the music category bar."
