### ISSUE TITLE
bug(YouTube Music/Sponsorblock): changing segment behaviour in sponsorblock setting crashes the app

### ISSUE THREAD

**Issue by GitGitu79** [inotia00/ReVanced_Extended#1857]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube Music 6.31.55

### Bug description

When trying to change the segment behaviour' in sponsorblock setting, it goes to black screen and crash the app

1. Open YouTube Music
2. Open setting
3. Go to sponsorblock
4. Click on segment 
5. Crash

Here's the video to clarify:

https://github.com/inotia00/ReVanced_Extended/assets/152173286/093153bc-58bd-4b73-8f23-b60083baa2ec

List of patch used:
![Screenshot_20231224_184148_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/152173286/339131f3-7ed4-495c-83ee-dac7e3268d65)

### Device Environment

Version: 1.17.1
Model: SM-M127F (Samsung M12)
Android Version: 13
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.208.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.208.1)
