### ISSUE TITLE
feat(YouTube Music/Hide flyout panel): add settings to remove `Shuffle play`, `Edit playlist` and `Delete Playlist` from flyout menu

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1858]
### Application

YouTube Music

### Feature description

Option to remove Shuffle play, Edit playlist and Delete Playlist from flyout menu.

<img src="https://github.com/inotia00/ReVanced_Extended/assets/125728453/49de10f5-81e4-4f15-9658-374d299e2cc2" width="500">

### Motivation

To remove unnecessary items.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
I implemented this request to https://github.com/inotia00/ReVanced_Extended/issues/1404

**Comment by inotia00** [comment]
thanks
