### ISSUE TITLE
[YouTube Music] Remember Shuffle icon (Vanced Music)

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#186]
### Application

YouTube Music

### Issue

https://github.com/revanced/revanced-patches/issues/1295
👆🏻
Hey Inotia if you read this I'd like to inform you that your shuffle patch for Rvx Music and that of Vanced Music are **two completely different things**. Your patch **forces** shuffle while Vanced Music did not. It only remembered your last decision/tap on the shuffle icon and kept shuffle on/off depending on your last tap. You misunderstood when I made feature request for shuffle.

Perhaps I shouldn't have copied the wording from Vanced Music. To be exact it should be called "Remember Shuffle" and the other is "Remember Repeat".

See this is how it works in Vanced Music. I still have it installed in one of my phones:
https://streamable.com/x3epx6
(As you can see in the clip Vanced Music also has Remember Repeat feature. Meaning the repeat icon does not reset each time you play a new item, it remembers your last tap/decision. In this case don't repeat, tap once = repeat album/playlist, tap twice = repeat track (infinite loop)

### Patch

Remember last tap/decision on Shuffle icon and DON'T FORCE shuffle (<-wrong, made up feature)

### Motivation

Less time spend tapping the shuffle icon over and over. Because default YTM behavior doesn't remember last tap on the Icon and resets it every time you play a new item.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
already implemented

**Comment by anyujinie** [comment]
> There is already a patch that does something similar, so I won't implement it.

Again it does _not_ do something similiar. It forces shuffle throughout the entirety of using the app. Who wants to shuffle at all times? I don't see anyone using that patch. 

But I understand it's your app and your decision wether to add it or not. I wish we had 0xrxL he would know how to add it since he was the one who added it for Vanced Music.
