### ISSUE TITLE
I don't know this is a bug ornot

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#1860]
### Application

YouTube

### Question description

![Screenshot_2023-12-26-10-13-16-637_com miui securitycenter](https://github.com/inotia00/ReVanced_Extended/assets/125992636/30ce5352-63ef-43f4-85fa-e8724f36a38e)

![Screenrecorder-2023-12-26-10-09-21-649_exported_2216](https://github.com/inotia00/ReVanced_Extended/assets/125992636/961afbe4-98ac-4f00-b772-03ae62a29ef4)

https://github.com/inotia00/ReVanced_Extended/assets/125992636/1fcf2f62-f467-4731-9cb6-c7cdba2e65f6

I just want to ask why I can't swipe up or press the more video button, is this a bug or do I need to undo some toggles in the ReVanced Extended settings? I used the latest apk and latest patch with my previous settings

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
I think you need to disable Hide end screen overlay.

Settings > Revanced Extended > Fullscreen > Hide end screen overlay, Off.

**Comment by KimYo2** [comment]
Thanks it worked 👍
