### ISSUE TITLE
feat(YouTube Music/Settings): add `Open default app settings` setting

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1861]
### Application

YouTube Music

### Feature description

Adds ability to open default app settings to add opening links to it like on YouTube.
![Screenshot_2023-12-27-18-33-55-725_com android settings-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/6faeb171-c330-4562-877f-5ac7400292d6)

### Motivation

To set YouTube music as default app on opening supported links rather than phone opening them in browser.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by hlytus** [comment]
Setting already exits.

<img src="https://i.imgur.com/144pHfu.jpg" width="300">

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1861#issuecomment-1870417908
Not in app settings like on YouTube ReVanced extended

**Comment by Rairof** [comment]
YouTube-
![Screenshot_2023-12-28-01-45-18-303_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/bacb74f0-d3f9-46a4-a0be-f50de47f2701)

YouTube music-
![Screenshot_2023-12-28-01-45-38-736_app rvx android apps youtube music-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/87cff854-633b-436c-ac03-85b8a9b50bc7)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
