### ISSUE TITLE
bug(YouTube/Hide captions button): Hide Captions button not working properly

### ISSUE THREAD

**Issue by adrianis86** [inotia00/ReVanced_Extended#1864]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

The CC button is reapearing after some time with the settings turned on (Revanced Extended > Player > Hide captions button).

I've tried different configs and reverted to full defaults (only disabled custom icon and name).
Nothing helps.
After few videos or hours, the CC button reapears.

### Device Environment

Android 11, OnePlus 7T

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by adrianis86** [comment]
![Screenshot_20231227-214401](https://github.com/inotia00/ReVanced_Extended/assets/6066994/16520b72-e771-409f-919f-98b4c963ac60)

**Comment by KobeW50** [comment]
Possibly relevant issue from the ReVanced-patches repository 

https://github.com/ReVanced/revanced-patches/issues/23

**Comment by adrianis86** [comment]
> Possibly relevant issue from the ReVanced-patches repository
> 
> [ReVanced/revanced-patches#23](https://github.com/ReVanced/revanced-patches/issues/23)

I cleaned data and with CC hidden (not for long), the Autoplay button is not spaced as in those screenshots.
So, i couldn't reproduce that behaviour

![Screenshot_20231227-220941](https://github.com/inotia00/ReVanced_Extended/assets/6066994/d5690443-4b0d-4d8d-a871-9ee2de46db74)

**Comment by KobeW50** [comment]
> I cleaned data and with CC hidden (not for long), the Autoplay button is not spaced as in those screenshots.
> So, i couldn't reproduce that behaviour
> 
> ![Screenshot_20231227-220941](https://github.com/inotia00/ReVanced_Extended/assets/6066994/d5690443-4b0d-4d8d-a871-9ee2de46db74)

The screenshot that the author of that issue shared with the space where the caption button should be is when they hid the new type of captions button using the custom filter.

**Comment by adrianis86** [comment]
> The screenshot that the author of that issue shared with the space where the caption button should be is when they hid the new type of captions button using the custom filter.

Most likely
Was missleadef by his last comment:
"It shows up to the left of the other buttons, so it's as correct as it can be here."

So we have now new items to hide...

**Comment by inotia00** [comment]
It is not reproduced in my side, and this is likely to be an A/B test.

This issue is not reproduced in any of the Google accounts I am using.

When I analyzed the YouTube code, it is only likely that this A/B test was applied after the YouTube v18.31.40.

Apply the patch to `YouTube v18.30.37`.

And after using it for enough time (about a week later), please let me know if the issue still persists.

**Comment by adrianis86** [comment]
> It is not reproduced in my side, and this is likely to be an A/B test.
> 
> This issue is not reproduced in any of the Google accounts I am using.
> 
> When I analyzed the YouTube code, it is only likely that this A/B test was applied after the YouTube v18.31.40.
> 
> Apply the patch to `YouTube v18.30.37`.
> 
> And after using it for enough time (about a week later), please let me know if the issue still persists.

I can confirm now that on v18.30.37, the issue is not present.

**Comment by adrianis86** [comment]
> It is not reproduced in my side, and this is likely to be an A/B test.
> 
> This issue is not reproduced in any of the Google accounts I am using.
> 
> When I analyzed the YouTube code, it is only likely that this A/B test was applied after the YouTube v18.31.40.
> 
> Apply the patch to `YouTube v18.30.37`.
> 
> And after using it for enough time (about a week later), please let me know if the issue still persists.

I can already confirm, after few days on v18.30.37, the captions button is still hidden.

**Comment by adrianis86** [comment]
![Screenshot_20231230-223859](https://github.com/inotia00/ReVanced_Extended/assets/6066994/be77dddd-714f-4db1-be8c-d1cd9aa2fbe3)
![Screenshot_20231230-223816](https://github.com/inotia00/ReVanced_Extended/assets/6066994/39c6ec48-ce5d-4d3d-94d5-bd30ac97caa3)

**Comment by inotia00** [comment]
Thanks for testing
It will probably be fixed in the next release

**Comment by inotia00** [comment]
Perhaps this issue was fix in [revanced-patches-v2.209.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.209.1).

This issue is not reproduced in my side.
So.. patch again with revanced-patches-v2.209.1, and If the issue seems to have been resolved, please close this issue.

**Comment by adrianis86** [comment]
Thank you, inotia00!
The captions button is hidden for good now.

Happy New Year!
