### ISSUE TITLE
bug: Clear Downloads Does Not Work For YouTube Music

### ISSUE THREAD

**Issue by ColeSpringer** [inotia00/ReVanced_Extended#1865]
### Type

Other

### Tools used

RVX Manager

### Application

Patched YouTube Music 6.31.55, going to "Downloads & Storage" and selecting "Clear downloads" does not clear downloads.

### Bug description

When you first install the application the "Recently played songs" option is enabled and will begin to download songs. In the regular (non-patched) version you can use the "Clear downloads" option to remove these automatically downloaded songs. In the patched version, nothing gets cleared when you tell it to clear downloads. No errors are thrown or anything but the songs are still labeled as downloaded and no space is cleared.

I do have YouTube premium if that matters at all since I don't think you can usually download from the Revanced youtube music applications.

### Device Environment

Google Pixel 8.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![1](https://github.com/inotia00/ReVanced_Extended/assets/108592928/3ae0c960-800a-4702-8889-02403de3febf)
![2](https://github.com/inotia00/ReVanced_Extended/assets/108592928/9fff5ea1-5e1c-424d-a76d-6fee2cbeb86d)

It is not reproduced in my side.

If this is an issue that is reproduced only on your side, you should estimate which patch is exactly what causes the issue.

Exclude one by one and tell me which patch causes issues.
