### ISSUE TITLE
bug: Empty list when selecting app to patch

### ISSUE THREAD

**Issue by amazingakita** [inotia00/ReVanced_Extended#1866]
### Type

Error while patching

### Tools used

RVX Manager

### Application

RVX Manager 1.18.1

### Bug description

after updating the rvx manager app, youtube no longer appears in the list of apps to patch.

![Screenshot_20231228_083624_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/39305711/e0841233-008c-4687-a4bc-067248f2e2f7)

uninstalling and reinstalling did not help.

this is mildly annoying, because i can't check which version of youtube is the recommended one without already having an apk to hand

### Error logs

[rvx_logs.txt](https://github.com/inotia00/ReVanced_Extended/files/13784819/rvx_logs.txt)

### Solution

i had a similar issue recently with the base revanced manager, and to solve it i had to update the patches organisiation from `revanced` to `revanceD`. is there any capitals missing from the default `inotia00`?

![SmartSelect_20231228_084109_ReVanced Manager](https://github.com/inotia00/ReVanced_Extended/assets/39305711/f33ab176-077b-44a2-a361-0e85da097e53)

### Device Environment

android 13
samsung z flip 4
one ui 5.1.1
non-root

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1602
