### ISSUE TITLE
suggestion(YouTube/Append time stamps information): add `Auto` string to translate

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1867]
### Application

YouTube

### Suggestion description

Add `Auto` string to translate, this word appears when you append video quality and open video first time after reboot
![Screenshot_20231229_183404_Gallery](https://github.com/inotia00/ReVanced_Extended/assets/110785596/2141534c-76d2-40fa-be7b-97aea43fd8e8)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This follows the translation of YouTube
