### ISSUE TITLE
bug(YouTube/Shorts/Return YouTube Dislike): dislikes of previous short not shown until you tap the button

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1868]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.25.40, 18.27.36

### Bug description

Dislikes of previous short not shown until you tap the button. This is not about 18.34.38+ problem, current problem existed before these versions were released. I mean fix it if you can reproduce it on your device

https://github.com/inotia00/ReVanced_Extended/assets/110785596/3b2d14af-5472-4c89-8ba2-773c9e0c9e08

### Error logs

```shell
:/
```

### Device Environment

Android 12 One Ui 4.1.1, Android 13 MiUi 14.0.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Vipin2003** [comment]
But this issue is not there for me.

**Comment by inotia00** [comment]
This is one way of implementation of RYD.
You can also check the code.
https://github.com/inotia00/revanced-integrations/blob/1d70d1717e0e2e81e0db350f654525cf028f6ebd/app/src/main/java/app/revanced/integrations/patches/utils/ReturnYouTubeDislikePatch.java#L65

**Comment by girshcatt** [comment]
But why 18.29.38 ~ 18.33.40 has no this issue?

**Comment by inotia00** [comment]
Your question seems to be wrong
'Why do you have this issue in Youtube v18.34.38+?' Is a more appropriate question

→ In YouTube v18.34.38+, Google completely changed the structure of the action bar of Shorts.
Accordingly, the method of RYD patch applied in YouTube v18.34.38+ is completely different.
