### ISSUE TITLE
suggestion(YouTube Music/Hide action bar component): `Hide add to playlist button` does not match name of the button

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1869]
### Application

YouTube Music

### Suggestion description

`Hide add to playlist button` does not match name of the button
![Screenshot_20231230_153049_YouTube Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/5423fef2-61c5-4c75-98ce-8acea2c4ace8)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The name does not necessarily need to match
