### ISSUE TITLE
feat(patch): Add Tap to seek in YouTube Shorts

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#187]
### Application

YouTube

### Issue

Would be nice if YT shorts had a Tap to seek functionality for it's seekbar. Maybe even with previews when you hold and swipe.

### Patch

Tap to seek for YT shorts 

### Motivation

Would make it more enjoyable watching Shorts 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
@inotia00 Any news on this request?

**Comment by inotia00** [comment]
Implemented by Google
