### ISSUE TITLE
Bug: Alternative Thumbnail settings working badly if DeArrow doesn't have thumbnails for a particular video

### ISSUE THREAD

**Issue by mikkovedru** [inotia00/ReVanced_Extended#1870]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube ReVanced Extended v. 18.46.43.
- Screenshot from browser: https://www.youtube.com/@joelpollardjkd/videos
![image](https://github.com/inotia00/ReVanced_Extended/assets/2521942/09168780-4318-4e90-b820-9fc1b9ef5311)

- Screenshot from Android Youtube ReVanced Extended v. 18.46.43.:
![image](https://github.com/inotia00/ReVanced_Extended/assets/2521942/4a494035-5bef-4f1b-b964-c92af4683c55)

- Settings: Alternative thumbnails 
![image](https://github.com/inotia00/ReVanced_Extended/assets/2521942/67f1b685-c760-43ba-8106-69323cbd7582)

### Bug description

The core of the issue, as I understand it is that if:
1. the alternative thumbnails are being turned on 
2. as is the DeArrow service
3. but DeArrow doesn't have thumbnails for a particular video

this causes the thumbnails be takes as per the "Video time to take the still from", which in this case causes them to be clearly unusable.

### Solution

Would be nice to have the option of "use youtube's original thumbnail" in case DeArrow fails to produce (also a good error-handling strategy if DeArrow ever is down).

Perhaps the "Beginning of video" should also be changed from 0s to 1s-5s mark?

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You are using a version that is not currently supported.

**Comment by mikkovedru** [comment]
How is that possible? I am using Revanced Manager and this is the version it provided.
![image](https://github.com/inotia00/ReVanced_Extended/assets/2521942/987a250a-f987-4293-8ed6-872d318cb47b)

**Comment by inotia00** [comment]
You are using an illegal build

Please refer to the documentations

1. [Github](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-RVX-Manager-(Android))
2. [Reddit](https://www.reddit.com/r/revancedextended/s/7kq7iT7jKp)
