### ISSUE TITLE
Issue while using native downloader to download from ytdlnis

### ISSUE THREAD

**Issue by aransari1** [inotia00/ReVanced_Extended#1871]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.45.43

### Bug description

While using the native YouTube downloader to download the video from ytdlnis, the complete link is not showing in ytdlnis but working while sharing the link and then using the ytdlnis downloader. How to fix this issue. See above video in the attached link.

### Additional context

Link: https://www.reddit.com/r/revancedextended/comments/18lieib/issue_while_using_native_downloader_to_download/

### Device Environment

MIUI 14, Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![EX](https://github.com/inotia00/ReVanced_Extended/assets/108592928/c0eb89e2-df4b-4b1c-b58a-625c3d124749)

Perhaps you are reporting a bug in the `Hook download button`.

Unfortunately, this feature is very bug-prone and has therefore been classified as an `Experimental Flags`.

`Experimental Flags` is a feature provided for users who are aware of the high possibility of bugs occurring and will use it.

Therefore, I do not accept any bug reports related to this.
