### ISSUE TITLE
bug(YouTube/Settings): settings are not initialized properly

### ISSUE THREAD

**Issue by adrianis86** [inotia00/ReVanced_Extended#1872]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

If "Overlay buttons" patch is deselected/not applied when building YouTube, some RVX functions are broken:
- No restart function after activating some options
- Default playback speed is not working (force close)

### Solution

Apply "Overlay buttons" when building

### Device Environment

Android 11, OnePlus 7T

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by adrianis86** [comment]
![Screenshot_20240101-015056~2](https://github.com/inotia00/ReVanced_Extended/assets/6066994/0b4cfd4e-bd61-4076-bc78-f918923d8074)
![Screenshot_20240101-014409](https://github.com/inotia00/ReVanced_Extended/assets/6066994/0c647bbc-5afd-4fcc-861a-55808f53ebc0)
![Screenshot_20240101-014349](https://github.com/inotia00/ReVanced_Extended/assets/6066994/722d13c9-97eb-4a57-93eb-0aa5792e15e5)

**Comment by adrianis86** [comment]
![Screenshot_20240101-013959](https://github.com/inotia00/ReVanced_Extended/assets/6066994/668ed7f7-b687-42cd-ae42-a72cddf2919a)
No "Overlay buttons" patch = no restart popups, force close when touching "Default playback speed" option

**Comment by inotia00** [comment]
Maybe it's the same issue as this one https://github.com/inotia00/ReVanced_Extended/issues/1838

Unlike previously reported issues, this issue includes specific steps to reproduce the issue.

So this is a valid issue.
You have reported which patch is causing the issue, so I will make sure it is fixed in the next release.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.210.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.210.1)
