### ISSUE TITLE
bug: Download Button Loading Animation keeps loading in incognito mode while watching a video

### ISSUE THREAD

**Issue by LegendarySpinx** [inotia00/ReVanced_Extended#1874]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

The download button downloading animation keeps going on even I have not pressed it.

![Screenshot_20240101-190442](https://github.com/inotia00/ReVanced_Extended/assets/69076256/85c807a0-de98-4ccb-9474-99597af5ddb1)
![Screenshot_20240101-190426](https://github.com/inotia00/ReVanced_Extended/assets/69076256/9c2ecb99-4dfc-400e-8636-a999c16d9234)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's YouTube issue
