### ISSUE TITLE
question: RVX YT and YTM are not shown in small-window apps and visual enhancement settings

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1875]
### Application

Other

### Question description

IDK but both YT and YTM (RVX version) are not shown in small window apps. Other RVX apps like Reddit, etc are shown in that. Is there any bug or wot or it triggers anything in system which RVX won't able to trigger ?

Device : iQOO Z7 Pro

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Perhaps, the OS you are using allows only supported apps to open in small windows.

To resolve this, you must ask the device manufacturer to add RVX's package name (`app.rvx.android.youtube`, `app.rvx.android.apps.youtube.music`) to the list of supported apps.

Or you can simply root your device.

**Comment by Vipin2003** [comment]
If iqoo can be rooted, then I'll definitely rit] root but it is not possible to root iqoo devices...
