### ISSUE TITLE
bug(YouTube Music/Sanitize sharing links): patch doesn't work

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#1876]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Music - any version (2.209.1)

### Bug description

`Sanitize sharing links` doesn't work (YTDLnis, Seal, Telegram, etc.) It starts to work only the second time, and not always.

![Screenshot_20240103_011901](https://github.com/inotia00/ReVanced_Extended/assets/130248949/e22f570f-49ae-4564-b9e0-bf51d2240a25)
![Screenshot_20240103_011709_Seal](https://github.com/inotia00/ReVanced_Extended/assets/130248949/40dce5ee-c6b2-4b7d-b9d6-123856b6deca)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.210.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.210.1)
