### ISSUE TITLE
feat(YouTube Music/Hide action bar component): add `Hide Like and Dislike buttons` settings

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1878]
### Application

YouTube Music

### Feature description

Pls also add `Hide Like Button` and `Hide Dislike button` patches to Action Button page. It was only available for 3-dot menu only.
![Screenshot_2024_0103_204515](https://github.com/inotia00/ReVanced_Extended/assets/93650504/daae0ae1-e8b1-4b69-95d7-2d56a8fa47aa)

### Motivation

It allow user to hide all the action buttons and make the action bar clear. As he can access all necessary buttons from 3-dot menu.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Please rename issue to
feat(YouTube/Hide action bar component): add `Hide like and dislike buttons` settings

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
