### ISSUE TITLE
feat(YouTube Music): add `Hide double tap overlay filter` patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1879]
### Application

YouTube Music

### Feature description

Add `Hide double tap overlay filter` patch to hide the double tap dark filter layer. Similar patch already exists for YouTube

### Motivation

:/

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1341
