### ISSUE TITLE
Button Container feat(patch): 

### ISSUE THREAD

**Issue by umunais** [inotia00/ReVanced_Extended#188]
### Application

YouTube

### Issue

Hide button container component in shorts section for like and dislike buttons..

### Patch

Hide button container component in shorts section for like and dislike buttons..

### Motivation

Hide button container component in shorts section for like and dislike buttons..

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/151
