### ISSUE TITLE
feat(YouTube Music): add `Hide tap to update button` patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1880]
### Application

YouTube Music

### Feature description

Add `Hide tap to update button` patch to hide tap to update button in library tab.
This button is similar thing to latest videos button in YouTube
![Screenshot_20240103_202238_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/02804ccf-96ec-43b4-ba4b-8ece0235fa61)

![IMG_20240103_212552_688](https://github.com/inotia00/ReVanced_Extended/assets/110785596/a562389f-11a8-460f-bf1a-ea2a0c458bf7)

### Motivation

:/

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Already implemented

**Comment by inotia00** [comment]
Thanks
