### ISSUE TITLE
question: Splash screen of custom icon yt (any) have same stock Splash Screen

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1881]
### Application

YouTube

### Question description

Splash screen doesn't have the custom logo, instead of that, stock yt logo is there. But this issue is not there for YT music. YTM splash screen follows the custom logo, but not YT. Why? Is it a bug or what?

https://github.com/inotia00/ReVanced_Extended/assets/93650504/90b6d6ff-49a1-4375-8ca6-9ecd615ce69b

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
refer comments https://github.com/inotia00/ReVanced_Extended/issues/1797

**Comment by Vipin2003** [comment]
Ohkk...I see.

N, one more thing, RV is introducing "Change Header", when will RVX is going to introduce it. And will it also reflect in splash screen too?
