### ISSUE TITLE
suggestion: changing that "Hide preview comment" layout

### ISSUE THREAD

**Issue by Baseduserrr** [inotia00/ReVanced_Extended#1883]
### Application

YouTube

### Suggestion description

Can you change that by Making it looks Like this : ✅

![Screenshot_2024-01-04-15-40-11-014_app rvx android youtube_1](https://github.com/inotia00/ReVanced_Extended/assets/153088092/8ef9b71e-c072-4f66-92a4-7feab800e26d)

instead of this : ❌

![Screenshot_2024-01-04-15-40-33-678_app rvx android youtube_1](https://github.com/inotia00/ReVanced_Extended/assets/153088092/d86b22f8-ca7d-46b0-b8ed-1fa72610eb59)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Baseduserrr** [comment]
Thanks "inotia00 for giving me shit.

**Comment by KobeW50** [comment]
> Thanks "inotia00 for giving me shit.

It was closed because it is a feature request.
