### ISSUE TITLE
suggestion: 

### ISSUE THREAD

**Issue by Karell2013** [inotia00/ReVanced_Extended#1884]
### Application

YouTube

### Suggestion description

Add support to the latest versions of YouTube (18.46.43, 18.48.39 and 18.49.36)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I probably don't plan on that.

YouTube v18.45.43 will be the last version supported by RVX before it is discontinued.

**Comment by Aryan-Chauhan** [comment]
v18.45.43 is the best
😍😍😍😍😍😍😍

**Comment by MattSolo451** [comment]
> I probably don't plan on that.
> 
> YouTube v18.45.43 will be the last version supported by RVX before it is discontinued.

This is very sad news.... It is possible to know the reason for this sad decision ? 😞

**Comment by MondayNitro** [comment]
only sponsorblock and external browser fail on 18.49.37
