### ISSUE TITLE
bug(YouTube/Overlay buttons) : chapter fade out animation is not shown properly

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1885]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

YouTube v18.45.43 with patches v2.210.1

### Bug description

When we play any video that has chapters & the name of chapters is long, the name comes over the overlay buttons for some time.

If you notice closely, you'll realize that this happens when the player overlay is "about to" turn off.

So, please fix this in your free time if it's fixable.

https://github.com/inotia00/ReVanced_Extended/assets/91815107/4fb8d821-8a34-4098-9a7e-59c1e4eb5985

### Error logs

```shell
No logs, but video is provided.
```

### Solution

Two solutions are possible:

1. Fix it in your own way.
2. Fix it by removing chapters from player.

### Additional context

No response.

### Device Environment

Realme 7 Pro
Realme UI 3.0 (Android 12)
Default font

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/1450
