### ISSUE TITLE
bug(YouTube/Shorts outline button): outline icon not applied when like/dislike button is clicked

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1886]
### Application

YouTube

### Suggestion description

I know that new implementations are stopped in YT, but can you look at this for once. 
I've just made a little improvement to the outline buttons of shorts i.e. buttons on liking or disliking a video are still stock. So, here I just changed it so that it should match with Outline buttons.

### Old after liking/disliking :
![Screenshot_2024_0105_162155](https://github.com/inotia00/ReVanced_Extended/assets/93650504/1eae8a51-c918-4a54-bc95-c52d10173e87)

### New after liking and disliking :
![Screenshot_2024_0105_162020](https://github.com/inotia00/ReVanced_Extended/assets/93650504/d7192b04-2f26-4573-9090-8b9bdcc8282c)

It will definitely enhance the look of liking/disliking while using outline buttons. Please try to add this.

[outline icons(only liking and disliking).zip](https://github.com/inotia00/ReVanced_Extended/files/13841122/outline.icons.only.liking.and.disliking.zip)

### Acknowledgements

- [x] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
