### ISSUE TITLE
bug(YouTube/Custom branding name YouTube): Patching time is long on RVX Manager

### ISSUE THREAD

**Issue by kitadai31** [inotia00/ReVanced_Extended#1887]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

Patching speed of `Custom branding name YouTube` is slow on RVX Manager.
After https://github.com/inotia00/revanced-patches/commit/441a9ecd586ca0bf6f372e38d43d9c6ae57aa230, the speed is certainly improved significantly, but it still takes time.

I measured the patching time on a mid-range device (Snapdragon 662, 4GB RAM).

Result:
- `AbstractRemoveStringsElementsPatch` took 40366 ms
- `CustomBrandingNamePatch` took 63 ms

Therefore, it seems that `AbstractRemoveStringsElementsPatch` takes long time to remove "application_name" string from each language files. (40 seconds)

### Solution

Match to official ReVanced code.
Official ReVanced uses a strategy of writing the new app name directly in AndroidManifest.xml.
https://github.com/ReVanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/layout/branding/CustomBrandingPatch.kt#L101
It takes only 3ms on the same environment.

### Effect of matching official revanced code

In case you are concerned about the impact, I have done some research in advance.

`@string/application_name` is used in these files:

```
res/layout/action_bar_ringo.xml
res/layout/action_bar_ringo_background.xml
res/layout/action_bar_ringo_background.xml
res/layout/action_bar_ringo_background_static.xml
smali_classes4/gcm.smali
smali_classes4/jqb.smali
smali_classes4/ltt.smali (As of 18.45.43)
```

For general users, this will affect the title text that appears in the ActionBar of WatchWhileActivity before the YouTube logo image loads, but it probably isn't a big deal. (It only appears for a short time on first startup)

![action_bar](https://github.com/inotia00/ReVanced_Extended/assets/90122968/0162d2f8-43ae-4b69-a081-25d5aa456a0a)

### Device Environment

Android 11, Snapdragon 662, 4GB RAM, RVX Manager 1.18.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The reason the RVX patch changes strings.xml instead of changing the AndroidManifest is because this does not work in a ROOT environment

In the ROOT environment, installation is done by mounting on stock YouTube

When mounting, the signature and manifest of the original APK still remain in memory, and the changed manifest is not reflected

This is why changing AndroidManifest does not work in ROOT environment

https://github.com/ReVanced/revanced-patches-template/pull/2178#issuecomment-1552412139

Because I am aware of this issue, I change strings.xml directly in the RVX patch

**Comment by kitadai31** [comment]
I didn't know about that, sorry. Thank you for your explanation!

**Comment by kitadai31** [comment]
I found that this issue was caused by the regex in `AbstractRemoveStringsElementsPatch`
Changing the regex like this solves it
The patching time was reduced from 40000ms to 600ms

```kt
.replace(""".+"$replacement".+""".toRegex(), "")
↓
.replaceFirst(""" {4}<string name="$replacement".+""".toRegex(), "")
```

According to regex101.com, the current regex takes 10 million steps, but this new one takes only 6000 steps
(with `values/strings.xml` from YT v18.45.43, enable and disable `global` flag)

**Comment by inotia00** [comment]
Thanks I will check it later

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
