### ISSUE TITLE
question: rvx header with custom icon youtube

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1888]
### Application

YouTube

### Question description

you might know that revanced added revanced header with their logo to their patches: https://github.com/ReVanced/revanced-patches/issues/2512
will you be willing to add rvx header, i can make custom header for revancify blue, red and mmt icons in case you plan to add.
already made a sample header here

![photo_6109433108903344518_x](https://github.com/inotia00/ReVanced_Extended/assets/87489540/21035248-b430-42f6-b05d-059e0811007f)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Sorry, I have no plans to add any more new patches to RVX

If you need that patch, use ReVanced

RVX will be discontinued in the near future
