### ISSUE TITLE
bug: <YouTube Server>

### ISSUE THREAD

**Issue by TheGoldenSun** [inotia00/ReVanced_Extended#189]
### Type

Other

### Application

YouTube version: 18.03.33

### Bug description

Whenever I tap onto the history section it's says this:

![Screenshot_20230127_162100](https://user-images.githubusercontent.com/104534608/215242843-8f822451-0fc7-4e6c-94e1-fb66713dd096.png)

Somebody should fix this. 

### Steps to reproduce

Patch and optimize a fix for history section.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20230127_162100](https://user-images.githubusercontent.com/104534608/215242894-58c5b5d5-57e2-4fad-a469-3c6b5ceb55f0.png)

### Solution

Implement a fix for history.

### Additional context

N/A

### Device Environment

Android 12, Galaxy A21

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
v18.03.33 is an unsupported version

I do not provide any help for issues reported on unsupported versions

**Comment by TheGoldenSun** [comment]
That's great because I tried your supported version 18.02.34 and still have been damaged with the same server 404 error.

**Comment by inotia00** [comment]
v18.02.34 is also an unsupported version

Try again with YouTube v18.02.37, revanced-patches-v2.156.4 and update results

**Comment by TheGoldenSun** [comment]
That's marvelous as heck, goodness I wish didn't have SM-A215U device on my hands right now but it's alive and precious to me since it exists as an arm64 device for me to use but it can't use it for YouTube anymore it seems idk why which is strange.

**Comment by TheGoldenSun** [comment]
Version: 0.0.53
Model: SM-A215U
Android Version: 12
Arch: arm64-v8a

Goodness it seems I'm hit with bad luck because Revanced manager isn't
initializing the patch a bit faster just slow on my device. and the version
you suggested for me to use made revanced manager label it as "unsupported
version" since 17.49.37 is still the usual stable version some people uses.
