### ISSUE TITLE
feat(YouTube): add `Disable update screen` patch

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#1890]
### Application

YouTube

### Feature description

YouTube v18.45.43 will be the last version supported by RVX.

Therefore, this version should be available as long as possible.

Google shows you the following update screen if you're using an old enough version of the client. And that means you'll no longer be able to use the app unless you update it.

![Update](https://github.com/inotia00/ReVanced_Extended/assets/108592928/a2b5e341-7ac0-426c-8597-9e7bd6c4c281)

(This screenshot is an image that forcibly loads update screens, in YouTube v18.45.43.)

It's not an issue right now, but in about two or three years, you'll be forced to see these update screens.

Before the RVX is discontinued, a patch that disables these update screens should be added.

### Motivation

To make YouTube v18.25.40 to YouTube v18.45.43, the version currently supported by the patch, available for as long as possible.

I will add this patch before RVX discontinues.

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Can you say approximate date when you planning to discontinue rvx? This is sad, but this is your decision((

**Comment by Sam101011** [comment]
For a long time, I feared that yt will try to break rv and rvx exactly before v19 releases and unfortunately, it looks like my fear was justified.

This patch is shaping to be the last piece of a giant puzzle you started constructing alongside the revanced team almost 2 years ago.

Thank you, inotia, for all that you've done for us. You've given us something truly wonderful.
There won't be a yt mod with that many features for a long time.

**Comment by sliceanddice9** [comment]
Really hope you return again in the future like you did last time. We appreciate you.

**Comment by girshcatt** [comment]
@inotia00, please, load this screen forcibly in Russian and share the screenshot

**Comment by inotia00** [comment]
> @inotia00, please, load this screen forcibly in Russian and share the screenshot

![Update_RU](https://github.com/inotia00/ReVanced_Extended/assets/108592928/e5ad233e-2286-41f5-9ca0-c94e078065b7)

Only the title was localized in each language

Russian for the title is as follows:

```
Обновите приложение
```

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
