### ISSUE TITLE
feat(YouTube Music): add `Hide fullscreen share button` patch

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1891]
### Application

YouTube Music

### Feature description

Add `Hide share button` patch to Hide the share button in the fullscreen player
![Screenshot_20240108_182443_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/62f58452-3dde-4131-ae8f-4fdd498a8d00)

### Motivation

:/

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
