### ISSUE TITLE
bug: YouTube Revanced Extended miniplayer blocks phone

### ISSUE THREAD

**Issue by AlphaNMC1999** [inotia00/ReVanced_Extended#1893]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 18.46.43

### Bug description

Sometimes, When you minimize the application, the miniplayer goes black and does not respond. Opening the app again makes the miniplayer flash black and the entire app goes full screen

### Additional context

When it remains on full screen, the phone is useless, you cannot exit the app. You have to restart.

### Device Environment

Android 13 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by AlphaNMC1999** [comment]
My phone is a Samsung S20FE 5G

**Comment by girshcatt** [comment]
Latest supported YouTube version is 18.45.43, if you use pre built apk for example from rvx lite group you wont receive support here

**Comment by AlphaNMC1999** [comment]
Same problem on previous version 18.45.43
