### ISSUE TITLE
suggestion(YouTube Music): change `Hide double tap overlay filter` patch name and description to more appropriate

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1894]
### Application

YouTube Music

### Suggestion description

Change `Hide double tap overlay filter` patch name and description to more appropriate. Because you made the patch based on https://github.com/inotia00/ReVanced_Extended/issues/1341 it hides player overlay filter too. Second (best in my opinion) solution is to just separate this patch in two: `Hide double tap overlay filter` and `Hide player overlay filter`

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
