### ISSUE TITLE
bug (YT) : Items are not hidden on home screen feed player

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1895]
### Type

Other

### Tools used

rvx-builder

### Application

18.45.43

### Bug description

Some buttons are not hidden from feed player like captions, fast-forward even enabling it in settings. They are only hidden in main player. Till previous updates, they are hidden from both feed player and main player.

https://github.com/inotia00/ReVanced_Extended/assets/93650504/b1f04692-959f-49b5-8ed7-144bd3c212a8

### Error logs

```shell
...
```

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by hlytus** [comment]
Not a bug tho. These settings are not for the feed.

**Comment by Vipin2003** [comment]
But if we hide these items for player in old version, they are also hidden for the feed player too
