### ISSUE TITLE
suggestion: Restrict YTM and Reddit to specific versions before discontinuing RVX

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1897]
### Application

Other

### Suggestion description

**Problem**

Within a few weeks or months of RVX being discontinued the fingerprints for new YTM and Reddit versions will no longer be able to be found. Users in the future will need to ask the community for the last known working version once this happens.

**Solution**

Constrain the patches for YTM and Reddit to versions that are tested to be working at the time of discontinuation. This will avoid any ambiguity regarding which version a person should use. Advanced users can still use newer YTM and Reddit versions until they no longer work.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is expected that there are too many changelogs, so it is difficult to reflect it in one patch.

Instead of launching the last patch in the last week of January, I will launch a new patch this week.

And I will release the last patch with the discontinued notice in the last week of January.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
