### ISSUE TITLE
bug: bypass youtube link redirect does nothing

### ISSUE THREAD

**Issue by Latrolage** [inotia00/ReVanced_Extended#19]
### Type

Other

### Bug description

When i enable the "youtube link redirect" i expected it to not go to "youtube.com/redirect" and ask me to open the respective app if there is one which can handle the link which I clicked. However it just opens my browser and goes to "youtube.com/redirect...." as normal

### Steps to reproduce

1. Install revanced with extended patches
2. Enable youtube link redirect
3. Click on a link in a video description for example
4. It opens up the youtube.com/redirect page

### Relevant log output

I dont know where to find runtime logs

### Screenshots or videos
<details>
<summary>video</summary>

https://user-images.githubusercontent.com/67372293/206877305-e969df63-00cf-4c90-8b71-d3c4857311f6.mp4
</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)
