### ISSUE TITLE
feat(patch): Add support for Android 13 Pixel launcher search

### ISSUE THREAD

**Issue by YounesBouhouche** [inotia00/ReVanced_Extended#190]
### Application

YouTube

### Issue

As you know, on Android 13 the pixel launcher search got lot of new features, like searching on play store, settings, and youtube, but searching on youtube requires installing original youtube app which I (and lot of YouTube Revanced users) don't want to. So if you can support this feature in your YouTube Revanced
I think it's something related with package name
Wish you all the best

### Patch

![Screenshot_20230128-062646_Pixel Launcher](https://user-images.githubusercontent.com/48130376/215249955-41a1bae3-207a-4a78-a2fb-52aac35b3b1e.png)

### Motivation

This feature would be very helpful، especially for those who have android 13. It make searching on youtube even faster and easier.
Here is a screen recording
https://photos.app.goo.gl/gEBDyGojV5zoMJfc9

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Google Assistant doesn't detect YouTube Music on non-root builds
This is because the package name of YouTube Music is hardcoded in Google Assistant

The issue you registered is also the same
If it is hardcoded in the Google Pixel launcher, there is no way to make it support it unless you modify the Google Pixel launcher

**Comment by YounesBouhouche** [comment]
> Google Assistant doesn't detect YouTube Music on non-root builds
> This is because the package name of YouTube Music is hardcoded in Google Assistant
> 
> The issue you registered is also the same
> If it is hardcoded in the Google Pixel launcher, there is no way to make it support it unless you modify the Google Pixel launcher

I didn't mean Google assistant I said pixel launcher they're not the same
Anyway thanks a lot
