### ISSUE TITLE
bug: Loading Download Button Looks Wierd in incognito mode 

### ISSUE THREAD

**Issue by Paras6408** [inotia00/ReVanced_Extended#1901]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube RVX v18.45.43

I was watching some videos in incognito mode and noticed that download button progress bar keeps loading and loading,

![Screenshot_2024-01-11-14-23-16-777_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/94892430/712458e5-025e-4047-b5fb-71dd22403129)

### Bug description

I occurs only while using incognito mode, everything is fine in normal mode.

### Error logs

```shell
I don't have
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1729#issuecomment-1825234809
