### ISSUE TITLE
suggestion(YT Music/Replace cast button): add description and known issues

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1903]
### Application

YouTube Music

### Suggestion description

According to the toggle description of Replace cast button the patch is still under development.

![SmartSelect_20240111_202756_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/84587632/8780b696-a682-457f-b4d1-6d685f112532)

Remember to either finish implementing the patch or remove it entirely before RVX is discontinued so that the project is in a finished state. ❤️

Close this issue if it is not a necessary reminder.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
This will be sad for me. You cant explain how is this patch useful, @inotia00 please, do not remove patch, because patch still work, just like any experimental feature

**Comment by KobeW50** [comment]
> @KobeW50 is it true RVX would discontinued? Is there legit info that i can read? :(

https://github.com/inotia00/ReVanced_Extended/issues/1890

**Comment by s7san007** [comment]
That was normal description in revanced-patches 2.190.15.
![Screenshot_20240114_211256_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/6acf313a-df19-42fe-89de-b8e608b5cca0)
The latest patches should either return this description.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
