### ISSUE TITLE
bug(YouTube Music/Change start page): fix typo of `Subscriptions` and `Charts` settings

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1904]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube Music

### Bug description

Fix typo of `Subscriptions` and `Charts` settings, now them named `Subscription` and `Chart`
![IMG_20240112_135721_275](https://github.com/inotia00/ReVanced_Extended/assets/110785596/6bca084d-3c18-4e3c-9373-1e993303a6e9)
![Screenshot_20240112_140537_ReVanced Extended Music](https://github.com/inotia00/ReVanced_Extended/assets/110785596/68fabc75-5d7c-4fee-8b87-e088738d200a)
![IMG_20240112_141525_306](https://github.com/inotia00/ReVanced_Extended/assets/110785596/2fbc3efd-d0a2-4ae3-b847-f5bcbe0aebeb)

### Error logs

```shell
:/
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
@inotia00 I can do this in my open PR.
