### ISSUE TITLE
bug(YouTube/Hide shorts components): `Hide like button` reappears if the short is liked

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1908]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v18.45.43

### Bug description

If `Hide like button` is enabled in shorts, and the short video is liked(by double tapping), the like button reappears. To reproduce this bug you need to atleast have one other side button shown (e.g. Comment, share, dislike etc.)

https://github.com/inotia00/ReVanced_Extended/assets/125728453/550c5a35-48c3-4eb7-ac6e-71e3701a2e54

Weird part is if all the side buttons are removed it works fine.

https://github.com/inotia00/ReVanced_Extended/assets/125728453/fa038668-edbb-4233-8985-853877c1d6ff

Steps to reproduce-
1. Turn on Shorts> Hide like button 
2.  Like any short

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
