### ISSUE TITLE
feat(patch): Getting rid of the unnecessary "last & next video" arrow in the video player overlay

### ISSUE THREAD

**Issue by GUImodder** [inotia00/ReVanced_Extended#191]
### Application

YouTube

### Issue

Since the maintainer of this fork seems to listen to feedback i wanted to give some feedback a lot of friends told me about:

Getting rid of the right and left arrows on screen while watching a video. Since extended already allows the users to modify/declutter the player overlay it would only be logical and consistent to implement this option.

![signal-2023-01-28-095603](https://user-images.githubusercontent.com/15251611/215257212-e2e8c4f0-08db-4b18-af81-60241a580108.jpeg)

imho this arrows (marked in red in the screenshot) don't serve a purpose most of the time (I can see them being helpful in playlists but even then you probably hit them unintentionally more often then not while trying to fast forward).

### Patch

Add a toggle to the "overlay button settings" that allows for disabling the "last" vs "next" video buttons. 

### Motivation

This "feature" in stock youtube is broken imho. It interferes with fast forwarding. If I hit the button on accident it usually doesn't even give the option to go back to the video I just came from for some reason. All around a terrible UI decision from YT stock that needs to be remedied by the community

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
already been implemented

**Comment by GUImodder** [comment]
Could you tell me where i can find this setting, please?

**Comment by inotia00** [comment]
> Could you tell me where i can find this setting, please?
> 
> ![signal-2023-01-28-125127](https://user-images.githubusercontent.com/15251611/215265054-59d81ead-c039-4dc1-bc57-2ee180b2f952.jpeg)
> 
> Apparently not in this menu (where it would be reasonably expected?)...

revanced-patches-v2.156.4++

![layoutsettings](https://user-images.githubusercontent.com/108592928/215265165-fbf47d61-8935-4b63-be46-bf9defad5a04.png)

ReVanced settings > Layout settings > Player layout settings > Hide Next / Prev button

**Comment by inotia00** [comment]
Sorry I accidentally deleted your comment...
don't know how to recover..

**Comment by GUImodder** [comment]
No problem...You set everything straigh! Thanks.

Just 1 final question: At what version of revanced extended is that patch integrated? I downloaded 18.01.36 this week and the setting you described is not found it that version?!?

**Comment by inotia00** [comment]
you can check [here](https://github.com/inotia00/revanced-patches/tree/revanced-extended#-json-format)

![supportversions](https://user-images.githubusercontent.com/108592928/215265670-a1aa979a-9f5e-42d0-b09b-fc3aec017b1f.png)

These are the currently supported versions

**Comment by GUImodder** [comment]
Oh ok...so you don't recommend getting the latest versions all the time? I just downloaded the latest release from your github and apparently the patch has not been implemented in it?!? 

There isn't even a 18.02.37 version of extended (at least not via github)??
