### ISSUE TITLE
bug(Youtube/History): Missing History entries

### ISSUE THREAD

**Issue by razcore-rad** [inotia00/ReVanced_Extended#1910]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube Revanced Extended 18.46.43

### Bug description

I have OnePlus Nord 3 & OnePlus Pad devices. On the OnePlus Pad the History entries in the You page are missing. The difference between the two devices is that OnePlus Pad recently got an OS update.

OnPlus Nord 3 with History
![Screenshot_2024-01-14-08-01-55-27_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/inotia00/ReVanced_Extended/assets/1177508/df7e8e98-559f-4fdf-af9b-1088d90f70c1)

OnePlus Pad missing History
![Screenshot_2024-01-14-07-58-53-78_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/inotia00/ReVanced_Extended/assets/1177508/e8dd10a7-1d04-4cbb-9b83-ea3305bdae54)

### Device Environment

OnePlus Nord 3: OxygenOS 13.1 CPH2465_13.1.0.622(EX01) | Android 13
OnePlus Pad: OxygenOS 14.0 OPD2203_14.0.0.100(EX01) | Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube v18.46.43 is not a supported version

**Comment by razcore-rad** [comment]
@inotia00 sorry, I don't understand how it isn't a supported version. I installed Youtube ReVanced Extended with Revanced Manager. Can you please clarify? Should I install something else that isn't in Revanced Manager?!

![Screenshot_2024-01-14-12-40-32-83_324a581c388555e4636ab38cef1d7a7e](https://github.com/inotia00/ReVanced_Extended/assets/1177508/75dabd59-5d6e-4ca4-ba01-06a18d549785)

**Comment by inotia00** [comment]
You are using an illegal build.

The official website of RVX is only my github, and websites such as 'revanced.net ' or 'revancedextended.com ' are fake websites.

No one knows what modifications have been made to the prebuild apk downloaded from these websites, and I'm not guaranteeing you any issues you'll experience from the use of the apk downloaded through these websites.

**Comment by inotia00** [comment]
You can never download the pre-built apk through the RVX Manager, and you need to be aware of how to build RVX through the RVX Manager from [documentations](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-RVX-Manager-(Android)) I wrote.

**Comment by razcore-rad** [comment]
Ohhh gotcha, I had no idea that Revanced Manager is a separate project, thanks.
