### ISSUE TITLE
bug(YouTube/Quick actions components): description of the toggle and the value limit of the internal code do not match

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1911]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT 18.45.43

### Bug description

After setting the `Quick actions top margin` value, the app no longer checks whether the given value is between 0-64. It won't show the [`revanced_quick_actions_margin_top_warning`](https://github.com/inotia00/revanced-patches/blob/2985e25ad32f790da24761cd15f187cc6ea5891c/src/main/resources/youtube/settings/host/values/strings.xml#L730) toast, and the value won't be reset to the default value (12).

 **Steps to reproduce**
 
 1. Reset the `Quick actions top margin` value and restart the app.
 2. Set the `Quick actions top margin` value to a value greater than 64, and restart the app when prompted.
 
(Check if you get a warning toast and if the value was reset)

https://github.com/inotia00/ReVanced_Extended/assets/84587632/2f1892ea-ec6f-4acf-8b3d-067ef19443e2

### Device Environment

Android 13
non-root
OneUI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Seem like this is the incorrect code:
https://github.com/inotia00/revanced-integrations/blob/b461cf30c95086798d56c06f5f1b9fa7f47a6fb9/app/src/main/java/app/revanced/integrations/patches/layout/FullscreenPatch.java#L55

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
