### ISSUE TITLE
bug: "Download video" in feed flyout panel downloads the wrong video

### ISSUE THREAD

**Issue by Pikasatupu75** [inotia00/ReVanced_Extended#1913]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 18.45.43
Revanced Patches 2.205.1

### Bug description

If there is an open video, doesn't matter if it is playing or paused, the "Download video" option in feed flyout panels of other videos download the open video instead of their videos.

https://drive.google.com/file/d/1e1LdPMdozYtySYZ78_y-00ScWVFvcYUe/view?usp=drivesdk

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Pikasatupu75** [comment]
https://github.com/inotia00/ReVanced_Extended/assets/126986435/51a0ae6d-9bd8-45be-9aa3-96fc7b23a418

Second attempt at trying to upload the video to github.

**Comment by Pikasatupu75** [comment]
https://github.com/inotia00/ReVanced_Extended/assets/126986435/206c3951-0032-46f4-9937-785e2139f95b

Second attempt to upload the video to github. I sped it up by 1.5x so it is smaller.

**Comment by Pikasatupu75** [comment]
Please inform me if the video link doesn't work. I uploaded it to my Google drive because the github upload didn't work.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1871#issuecomment-1872618287
