### ISSUE TITLE
bug: 'Disable forced auto captions' does not work in shorts player sometimes.

### ISSUE THREAD

**Issue by kyan5221** [inotia00/ReVanced_Extended#1915]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube v18.45.43

### Bug description

* Even if I enabled 'Disable forced auto captions', the subtitles are sometimes automatically displayed when I play the shorts video.
* patch v2.210.1

### Error logs

```shell
.
```

### Solution

.

### Additional context

.

### Device Environment

Android 13, One UI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
There was a similar issue last year https://github.com/inotia00/ReVanced_Extended/issues/484#issuecomment-1469262293

Forced auto captions are no longer disabled from Shorts

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/484#issuecomment-1893630906
