### ISSUE TITLE
bug: Video refuses to end and autoplay isn't working

### ISSUE THREAD

**Issue by piviee** [inotia00/ReVanced_Extended#1917]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube v18.45.43

### Bug description

I have seen some similar bug reports but it has SponsorBlock enabled.

In my case, whether SponsorBlock is enabled or not, the video does not end and the timer continues running until I tap on next button or double tap on the screen to forward 10 seconds, even in playlist.

Steps to reproduce:
1. Patch Youtube with/without disable suggested video end screen patch
2. Suggested video end screen is turned on/off
3. SponsorBlock is turned on/off
4. Autoplay is turned on/off
5. All SponsorBlock segments are set to any settings

https://github.com/inotia00/ReVanced_Extended/assets/156946486/8a9686ef-fb93-4911-83e5-23892db27737

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You are using ReVanced, not RVX

Also, this is duplicated with https://github.com/inotia00/ReVanced_Extended/issues/1805

**Comment by piviee** [comment]
> You are using ReVanced, not RVX
> 
> Also, this is duplicated with #1805

I'm sorry if my description caused any inconvenience to you, but I'm using RVX Manager, and the video never ends with whatever settings is, even with autoplay or SponsorBlock enabled or not

![z5082758770031_e71b0cef23d2df2c61ca42fc0901acf3](https://github.com/inotia00/ReVanced_Extended/assets/156946486/d37179dc-036e-4c61-9498-d9b170ba753d)
