### ISSUE TITLE
Floating menu - Loop & Stable Volume

### ISSUE THREAD

**Issue by nightznero** [inotia00/ReVanced_Extended#1918]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT v18.45.43

### Bug description

i have problem with reapiting, on float menu(also for stable volume). Its buggy but _overlay_ works flawless
![Screenshot_20240117_022956_YouTube RVX](https://github.com/inotia00/ReVanced_Extended/assets/61750641/80a81ed7-96fe-4b25-8ea5-cc33879bb27c)

### Solution

If not possible to work Should be greyed out but as on screen its looks weird;

Loop lights like it could be enable - cannot be switched
Stable Volume is greyed-out - its enabled and cannot be disabled

### Device Environment

A13
OneUI 5.1

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1705#issuecomment-1817675612

**Comment by KobeW50** [comment]
Also, refer to this in-the-works feature which should help alleviate the issue

https://github.com/inotia00/ReVanced_Extended/issues/1916
