### ISSUE TITLE
Everytime i played a music and watch movie videos in youtube vanced it can play only a 30 seconds or a minute and then they trip to stop and logging  i dont know how to fix this kind of problem?  Can you help me to troubleshoot this problem? Thanks and i hope you can find a better solution.

### ISSUE THREAD

**Issue by Jamesabs88** [inotia00/ReVanced_Extended#1919]
### Application

YouTube

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by sams452m** [comment]
Vanced is discontinued and it has playback issue as it is not updated from a while and it's revanced extended not vanced.

Solution - Shift to Revanced or Revanced Extended.
