### ISSUE TITLE
feat(patch): Force show compact headers

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#192]
### Application

YouTube

### Issue

![Screenshot_20230129-004816291 (1)](https://user-images.githubusercontent.com/73917917/215296381-79e2dd01-f5f0-435c-bd86-54344eec3d02.jpg)

These compact headers come and go all the time and there is no YouTube setting to show them at all times.
I use them alot and think they're very useful. Please consider adding a patch to force show them, so that they're always displayed there.

### Patch

Described above

### Motivation

Useful tool.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.

**Comment by hi-im-karma** [comment]
I got it, you have no plans to add new YT features. Please stop posting this under every single of my feature requests. I'm getting lots of email notifications.
