### ISSUE TITLE
feat(YouTube): add `Keep landscape mode` patch

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#1920]
### Application

YouTube

### Feature description

**※ This is said to be written to explain the new patch that will be added to the next build, not `Feature request`.**

From 2022 onwards, Google has changed YouTube to exit fullscreen when the screen is turned off and on.

[Source](https://www.reddit.com/r/revancedextended/comments/151v7f1/anyone_else_having_problems_with_full_screen/)

It's been over a year since these changes were implemented on YouTube, but many users are still complaining about them.

Fortunately, while reverse engineering the YouTube client, I found an experimental config that disables this in `YouTube v18.42.41+`.

Since it is expected that there will still be some bugs due to limitations in the implementation method, I plan to designate this patch as `Experimental Flags`.

### Motivation

It looks like Google has no plans to roll back this change.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)

**Comment by nintendork07** [comment]
this is a really great patch that replicates the older YouTube app behavior. is there a way to keep it in landscape when switching back & forth from the RVX app? like having a video play in RVX, then go home, then open another app, then go back to RVX? mimicking the behavior of the older app. it does stay in landscape successfully when turning off and on the screen though, which is great

**Comment by inotia00** [comment]
> this is a really great patch that replicates the older YouTube app behavior. is there a way to keep it in landscape when switching back & forth from the RVX app? like having a video play in RVX landscape, then go home, then open another app, then go back to RVX? currently when I switch back to RVX it flips back to portrait mode. it does stay in landscape successfully when turning off and on the screen though, which is great

If I had enough time, I would have implemented all the patches that I had not yet implemented.

In the past, I would have released a new patch in three days, but now it took me two weeks to release a new patch.
Tbh, I think I've completely lost interest in this project.

I hope someone who is still passionate about development will continue the RVX project.

**Comment by nintendork07** [comment]
> > this is a really great patch that replicates the older YouTube app behavior. is there a way to keep it in landscape when switching back & forth from the RVX app? like having a video play in RVX landscape, then go home, then open another app, then go back to RVX? currently when I switch back to RVX it flips back to portrait mode. it does stay in landscape successfully when turning off and on the screen though, which is great
> 
> If I had enough time, I would have implemented all the patches that I had not yet implemented.
> 
> In the past, I would have released a new patch in three days, but now it took me two weeks to release a new patch. Tbh, I think I've completely lost interest in this project.
> 
> I hope someone who is still passionate about development will continue the RVX project.

no worries at all, it's already much better than the default implementation. you do incredible work inotia00 & i'm extremely grateful for how much this project has helped me during a difficult time. wish you all the best & thank you for your hard work. may RVX live on in the community

**Comment by Aryan-Chauhan** [comment]
Stock YT v20.03.45 has this feature now.
