### ISSUE TITLE
bug: youtube - hide suggested video overlay doesnt work

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#1921]
### Type

Error at runtime

### Tools used

CLI

### Application

youtube 18.45.43

### Bug description

hide suggested video overlay doesnt work if you repeatedly play the last 2-3 sec of the video.

https://github.com/inotia00/ReVanced_Extended/assets/87489540/53f29e8a-98ab-431f-8302-6f5609a90bc5

https://github.com/inotia00/ReVanced_Extended/assets/87489540/1d81b005-509b-4241-870f-56f77cc97191

either create a timestamp to 2-3 sec before video ending or slide from seekbar, suggested video overlay will appear after 3-4 attempts

### Device Environment

Los20 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![EX2](https://github.com/inotia00/ReVanced_Extended/assets/108592928/5f029cb2-6651-4ced-b5ff-8603bebb33af)

Unfortunately, this feature is very bug-prone and has therefore been classified as an `Experimental Flags`.

`Experimental Flags` is a feature provided for users who are aware of the high possibility of bugs occurring and will use it.

Therefore, I do not accept any bug reports related to this.
