### ISSUE TITLE
bug: (YouTube) force-fullscreen Orientation Error 

### ISSUE THREAD

**Issue by Francesco146** [inotia00/ReVanced_Extended#1922]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

When the patch is enabled, the videos indeed go to full screen, but on a fixed orientation. 

The intended way was to simulate the press the full-screen button, that set the orientation accordingly to the device.

### Solution

Check the device orientation to decice in which side the video will be set.

### Device Environment

OneUi 6.0, Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
`Force fullscreen` is an experimental feature, inotia does not accept any bug reports on experimental features
