### ISSUE TITLE
bug: NO AUDIO in Fullscreen mode when screen rotates to left on OnePlus Nord CE 5G

### ISSUE THREAD

**Issue by d5stroy5r** [inotia00/ReVanced_Extended#1923]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v18.45.43 [ARM7] [ARM8]

### Bug description

While playing the video in fullscreen mode when screen rotates from Potrait mode to right side (by default) in Landscape mode the video and audio is comimg properly. But when screen rotates from Potrait mode to left side in Landscape mode the video is playing but there is NO AUDIO.

Steps to reproduce:
Step 1. Play video in landscape mode by default screen rotates from Potrait to Landscape mode turning to right (Audio - Video playning normally)
Step 2. Now rotate the screen 180 degree (upside down) or when screen rotates from Potrait to Landscape mode turning to left (Video is playning normally but there is NO AUDIO)

### Additional context

YouTube v18.45.43 [ARM7] [ARM8]
YouTube v18.40.34 [ARM7] [ARM8]

These are the versions I tried.

### Device Environment

Device: OnePlus Nord CE 5G 
OS: OxygenOS 11

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by d5stroy5r** [comment]
Also Tool Used: rvx-builder-win

**Comment by inotia00** [comment]
Exclude patches one by one.
And please let me know which patch is causing the issue.

**Comment by inotia00** [comment]
If the issue is reproducible even in the latest patch, please open a new issue
