### ISSUE TITLE
suggestion(YouTube Music/Enable force minimized player): fix typo

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1924]
### Application

YouTube Music

### Suggestion description

Fix tautology in revanced_enable_force_minimized_player_summary string, change it from: `Keeps the miniplayer minimized even when another track is played.` to: `Keeps the player minimized even when another track is played.`

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Please check https://github.com/inotia00/revanced-patches/pull/43, it fixes this issue

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
