### ISSUE TITLE
suggestion(YouTube Music/Hide cast button): move settings to the `Player` section and change patch description

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1926]
### Application

YouTube Music

### Suggestion description

Move settings to the `Player` section and change patch description
`Adds an option to hide the cast button.` is not right description, because patch hides cast button in the player

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
It also hides the cast button from the Homepage and Library tab, so it is therefore considered a general patch.

![Screenshot_20240119_150334_ReVanced Extended Music.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/2036434a-709f-4d67-9466-ed255d27d148)

![Screenshot_20240119_150145_ReVanced Extended Music.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/8c5b4059-0c4b-45a5-b6ca-f4005ec64d4a)
