### ISSUE TITLE
bug: In the flyout panel With the latest patches the "report" function has disappeared.

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1927]
### Type

Other

### Tools used

Revancify

### Application

Youtube 18.45.43

### Bug description

In the flyout panel
With the latest patches the "report" function has disappeared.

![Screenshot_2024-01-20-04-17-06-926_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/0d82ffb8-4a3c-4014-9ff0-acd9486e8c1f)

![IMG_20240120_041938](https://github.com/inotia00/ReVanced_Extended/assets/125223735/d1929a3b-13c7-4341-bccd-26b1ef82a964)

### Error logs

```shell
No
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
It still appeared in my side. Please check your Settings to make sure that you have turned off the Hide Report Button

**Comment by jhon1282** [comment]
> It still appeared in my side. Please check your Settings to make sure that you have turned off the Hide Report Button

Hi, I had already checked that setting and it is off
