### ISSUE TITLE
default-video-quality bug in low-end internets

### ISSUE THREAD

**Issue by User-noob2036876** [inotia00/ReVanced_Extended#1928]
### Type

Other

### Tools used

Revancify

### Application

YouTube 18.45.43
default-video-quality bug
Im entering video.
(Default video quality is 1080p in RVX settings)
Video plays normally forced to 1080p
But when i watch shorts video/do anything in background then back to video, video's quality reduces. No matter how long we wait, it does not increase automatically. (Default video quality is 1080p in RVX settings again) I didn't see this issue in the official ReVanced app.

### Bug description

Video plays normally forced to 1080p
But when i watch shorts video/do anything in background then back to video, video's quality reduces. No matter how long we wait, it does not increase automatically. (Default video quality is 1080p in RVX settings)
Step 1- Force videos quality to 1080p/higher on RVX settings
Step 2- Watch a 1080p+ video.
Step 3- Do anything in background/simply watch shorts on RVX
Step 4- Go back to video. Then play video without changing any setting. Then check quality on players bottom buttons, its 480p/lower
Its on a low-end internets. I guess.
My device is Redmi 12 Pro. Not rooted.
So i cant drop images/videos to here.

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue also reproduces on stock YouTube.
Therefore, this is a bug that Google needs to fix.
