### ISSUE TITLE
feat(patch): Dislike Counter for YouTube Shorts

### ISSUE THREAD

**Issue by sliceanddice9** [inotia00/ReVanced_Extended#193]
### Application

YouTube

### Issue

The current dislike statistic isn't shown when watching shorts. 

### Patch

Enable the live number of dislikes to be shown when playing shorts using the dedicated shorts player. 

### Motivation

So that people can see the number of dislikes a 'shorts' video has when scrolling through shorts via the actual shorts player. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.159.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.4)
