### ISSUE TITLE
bug(YouTube/Hide comment component): `Hide emoji picker` setting also hides the timestamp button

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#1930]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v18.45.43
RVX Manager v1.18.1
Patches v2.215.1

### Bug description

When "hide emoji picker" is toggled on, it also hides timestamp button in comments.

With emoji picker
![20240116_152624](https://github.com/inotia00/ReVanced_Extended/assets/132079771/9a5fe626-85c2-4926-afd6-50e79a3c6c89)

With emoji picker hidden
![20240116_152346](https://github.com/inotia00/ReVanced_Extended/assets/132079771/0fd8a022-ea88-4d60-8651-be77d0a58d8b)

### Device Environment

Android 14, One UI 6.0 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by NoMorePizza** [comment]
Shame that it can't be fixed, but thanks anyway. It's not that big of a deal anyway.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)

**Comment by RamPawar7** [comment]
Sorry for bugging but can you check if these can be separated now in the current (supported) app version
