### ISSUE TITLE
bug:(YouTube) Background playback doesn't work on vertical Livestreams

### ISSUE THREAD

**Issue by Oleepre** [inotia00/ReVanced_Extended#1931]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

 Vertical LiveStreams on YouTube can't use background playback. Going outside the app will make the audio stop.
 When the stream is over, watching the VOD makes it behave as it should with minimized/background playback working correctly.
 It seems the patch treats the livestream the same way it does with regular Shorts.
 The Minimized Playback patch should apply to vertical videos if they're flagged as LIVE.

### Device Environment

Android 13, Samsung A32

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
That's the behavior of stock YouTube

I've been subscribing to YouTube Premium for 3 years, so I can use background play on stock YouTube without any patches

Even on stock YouTube, background play and PiP do not work with Shorts or vertical live streams
