### ISSUE TITLE
suggestion: return spoof app version to 16.08.35 - Restore explore tab

### ISSUE THREAD

**Issue by hongcha666** [inotia00/ReVanced_Extended#1935]
### Application

YouTube

### Suggestion description

![photo1706062056](https://github.com/inotia00/ReVanced_Extended/assets/113239053/d4aa1214-abf0-4a2a-bf6f-3050d771b4c6)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
You can spoof on any version by `Edit spoof app version` option

**Comment by hongcha666** [comment]
> You can spoof on any version by `Edit spoof app version` option

How?

**Comment by girshcatt** [comment]
> How?
![IMG_20240124_075744](https://github.com/inotia00/ReVanced_Extended/assets/110785596/8ec1bf5d-21be-4842-93cb-d01f8bb68c24)

**Comment by hongcha666** [comment]
> > How?
> > ![IMG_20240124_075744](https://private-user-images.githubusercontent.com/110785596/299199939-8ec1bf5d-21be-4842-93cb-d01f8bb68c24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzY3NzksIm5iZiI6MTcwNjA3NjQ3OSwicGF0aCI6Ii8xMTA3ODU1OTYvMjk5MTk5OTM5LThlYzFiZjVkLTIxYmUtNDg0Mi05M2NiLWQwMWY4YmI2OGMyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNjA3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2ZiMmNlZTkxY2ZmYTFmNDViMjUxOGRjMDc2Y2Q0YmEyMTAwNjJhZjQ4ZDRlM2UxOTQ4MjhjYTkxZWZiNDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hwAv9K0BzriQAduF2-7vxMjxi6LJKgtDdC1liQ4kKMI)

Let me check

**Comment by hongcha666** [comment]
It works,Thank sir!

> > How?
> > ![IMG_20240124_075744](https://private-user-images.githubusercontent.com/110785596/299199939-8ec1bf5d-21be-4842-93cb-d01f8bb68c24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzY3NzksIm5iZiI6MTcwNjA3NjQ3OSwicGF0aCI6Ii8xMTA3ODU1OTYvMjk5MTk5OTM5LThlYzFiZjVkLTIxYmUtNDg0Mi05M2NiLWQwMWY4YmI2OGMyNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNjA3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2ZiMmNlZTkxY2ZmYTFmNDViMjUxOGRjMDc2Y2Q0YmEyMTAwNjJhZjQ4ZDRlM2UxOTQ4MjhjYTkxZWZiNDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hwAv9K0BzriQAduF2-7vxMjxi6LJKgtDdC1liQ4kKMI)
