### ISSUE TITLE
bug(YouTube/Hide layout components): `Hide join button` setting does not work

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1936]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

`Hide join button` setting does not work
![Screenshot_2024-01-24-11-22-56-251_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/3b75e976-2b4a-4a25-8832-daad4e241106)
![Screenshot_2024-01-24-11-22-47-952_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/3cf9722b-0cc5-418d-8f58-35bce069578c)

### Error logs

```shell
:/
```

### Additional context

[ReVanced Extended_v18.29.38_2024-01-24.txt](https://github.com/inotia00/ReVanced_Extended/files/14036028/ReVanced.Extended_v18.29.38_2024-01-24.txt)
https://youtu.be/Kn6uu2dokys

### Device Environment

Android 13 MiUi 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue does not reproduce on the Google account I have

Maybe it's just another A/B test

**Comment by girshcatt** [comment]
I checked all my google accounts, it reproduces on 1/4 accounts as well

**Comment by inotia00** [comment]
Fortunately, I was able to reproduce this issue on one of my Google accounts.

It will be fixed in the next release.

**Comment by girshcatt** [comment]
> Fortunately, I was able to reproduce this issue on one of my Google accounts.
> 
> It will be fixed in the next release.

Please, check `Hide start trial button` setting, is it affected by these ab tests?

**Comment by inotia00** [comment]
nah

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
