### ISSUE TITLE
bug(YouTube/Hide layout components): `Hide store tab` setting does not seem to work fine

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1937]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

`Hide store tab` setting does not seem to work fine.
It can appear at random moment(no screenshot yet, but i experienced this today) and you still able to get to the store tab by swiping at tabs
![Screenshot_2024-01-24-11-31-39-503_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/51e1179b-4085-4a0b-ab32-f525355c9e73)

https://github.com/inotia00/ReVanced_Extended/assets/110785596/03945813-0d49-4870-94db-612c71440f91

### Error logs

```shell
:/
```

### Additional context

[ReVanced Extended_v18.29.38_2024-01-24.txt](https://github.com/inotia00/ReVanced_Extended/files/14036305/ReVanced.Extended_v18.29.38_2024-01-24.txt)

### Device Environment

Android 13 MiUi 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is similar to hiding navigation buttons

Enable `Hide home button` or `Hide library button` from navigation settings does not permanently disable the home tab or library tab

You can still access to the `Home` tab or `Library` tab

This issue is also the same

Enable `Hide store tab` setting only hides the store tab from channel profile settings, it does not permanently disable the store tab

**Comment by girshcatt** [comment]
> setting only hides the store tab from channel profile settings
> It can appear at random moment(no screenshot yet, but i experienced this today)
Maybe it will take a time, but the tab can appear randomly in the channel profile
