### ISSUE TITLE
suggestion(YouTube/Settings): match settings import reset toast message to YTM variant

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1938]
### Application

YouTube

### Suggestion description

Match revanced_extended_settings_import_reset string to YouTube Music variant, i mean do: `Settings reset to default.` instead of: `Reset`

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Please, change sb_reset string too

**Comment by inotia00** [comment]
> Please, change sb_reset string too

![sb_reset](https://github.com/inotia00/ReVanced_Extended/assets/108592928/1aa23a74-0382-4fd2-97e5-5920dfeb89de)

This is the strings of `sb_reset`

What should I change this to?

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
