### ISSUE TITLE
suggestion(YouTube/Hide button container): remove `Hide transcript button` setting

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1939]
### Application

YouTube

### Suggestion description

Remove `Hide transcript button` setting.

`Transcript` button is removed from button container
> this feature removed from button container relatively recently.

In general this issue is just reminder to remove this setting in final release as you said earlier
>It will also be removed in RVX patch in the near future.

https://github.com/inotia00/ReVanced_Extended/issues/1851#issuecomment-1868366210

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
