### ISSUE TITLE
bug: Brightness reduces to 0% when Fullscreen mode, and also when going into Zoom mode.

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#194]
### Type

Other

### Application

Version 18.02.37

### Bug description

There is this weird Bug when i watch vertical videos (Kpop) and enter fullscreen the brightness changes on its own, and also changes again when i go from fullscreen into Zoom mode (fills entire screen)
Its a weird behavior and difficult to describe, but its very annoying. I have Auto-brightness disabled.

### Steps to reproduce

Step 1. Open vertical video
https://youtu.be/zs7VgEMbpUg

Step 2. Go into fullscreen mode

Step 3. Go into Zoom mode

Watch how the brightness goes down to 0% and changes on its own

### Relevant log output

```shell
I dont understand
```

### Screenshots or videos
https://streamable.com/q8w258
https://streamable.com/7dv6of

### Device Environment

Android 12
ROG Phone 5s Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
After updating to the latest version of revanced-patches, check if the issue reproduces in the new layout.

The bug is not reproduced in the latest version of revanced-patches, new layout

**Comment by anyujinie** [comment]
The new layout _still_ hasn't hit my Premium account 🤷🏻‍♂️

**Comment by anyujinie** [comment]
@inotia00 Please read comments here. People reporting the issue with Rvx:

https://www.reddit.com/r/revancedapp/comments/10p6uav/brightness_goes_back_to_0/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by Ankit2502** [comment]
I too having this issue on miui 13 pad

https://user-images.githubusercontent.com/89592455/216354349-f3016ead-f5ba-48fe-ac41-d2cca180f820.mp4

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.159.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.1)
