### ISSUE TITLE
suggestion(YouTube Music/Hide general ads): remove `Hide interstitial ads` setting

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1940]
### Application

YouTube Music

### Suggestion description

Remove `Hide interstitial ads` setting.
> Google has changed the way it handles interstitial ads via server sides

https://github.com/inotia00/ReVanced_Extended/issues/1802#issuecomment-1905553798

In general this issue is just reminder to remove this setting in final release as you said earlier
> `Hide interstitial ads` setting will be removed from the final build

https://github.com/inotia00/ReVanced_Extended/issues/1802#issuecomment-1905721442

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
