### ISSUE TITLE
bug(YT): Profile icons are not shown in subscription page

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1943]
### Type

Other

### Tools used

rvx-builder

### Application

Latest Supported

### Bug description

In subscription tab, there is a row of subscribed channels at the top of it. But it was not showing currently. Check this :

https://file.io/6pKPBCQpmdej

### Error logs

```shell
```

### Device Environment

Android 14

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is stock YouTube issue

**Comment by Aryan-Chauhan** [comment]
Did you turn off `Settings / Feed / Hide Subscriptions Section` ?

**Comment by Vipin2003** [comment]
> Did you turn off `Settings / Feed / Hide Subscriptions Section` ?

I already resolved it.
