### ISSUE TITLE
bug: App not installing to my device

### ISSUE THREAD

**Issue by wazeeahmed** [inotia00/ReVanced_Extended#1944]
### Type

Other

### Tools used

RVX Manager

### Application

RVX manager 1.17.1 > 1.18.1

### Bug description

I can't upgrade to the latest 1.18.1 rvx manager from my Android 11 device. Perhaps you forgot to add compatibility for it?

### Solution

Just add the a11 compatibility back 😮‍💨

### Device Environment

Android 11

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Installation was possible on Android 9.0 devices without any issues

Try uninstalling RVX Manager 1.17.1 first and then installing RVX Manager 1.18.1
