### ISSUE TITLE
bug(YouTube/Hide layout components): in Russian `Hide browse store button` setting hides last button

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1946]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

in Russian `Hide browse store button` setting hides last button(except subscribe button)
On channels where browse store button is not exist it should not do anything, but in Russian it hides last button on such channels as https://youtube.com/@HESUSDED where last button is join button
![Screenshot_2024-01-26-08-39-57-027_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/a04880ee-aaf0-4b8e-80a8-9a59d625b5f7)
![Screenshot_2024-01-26-08-42-06-553_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/f4f70afa-d5f8-44c6-8131-1a12b71317e8)

### Error logs

```shell
:/
```

### Additional context

[ReVanced Extended_v18.29.38_2024-01-24.txt](https://github.com/inotia00/ReVanced_Extended/files/14061247/ReVanced.Extended_v18.29.38_2024-01-24.txt)

### Device Environment

Android 13 MiUi 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Issue https://github.com/inotia00/ReVanced_Extended/issues/1945 is valid, but this issue is not valid

**Comment by girshcatt** [comment]
But it is reproduced on all my devices

https://github.com/inotia00/ReVanced_Extended/assets/110785596/a27447e2-99ee-471e-b2fb-c5723421077c

**Comment by girshcatt** [comment]
If you cant reproduce the bug you can try my settings file that i pinned in `Additional context` shelf

**Comment by girshcatt** [comment]
Wow, on my tablet it behaves different way, i will open another issue and then come back to this

**Comment by girshcatt** [comment]
https://github.com/inotia00/ReVanced_Extended/assets/110785596/0216c357-5886-480a-9ce0-b098d2ad48a2

Is issue still not valid?

**Comment by inotia00** [comment]
Yeah the cause of this bug is the `Hide store tab` setting, not the `Hide browse store button` setting

**Comment by inotia00** [comment]
Turn off the `Hide store tab and turn on only the `Hide browse store button` setting and test again

**Comment by girshcatt** [comment]
I turned it off and issue is still valid

**Comment by girshcatt** [comment]
https://github.com/inotia00/ReVanced_Extended/assets/110785596/024c34d8-bece-4fce-9fd5-4a8dca6a832a

**Comment by inotia00** [comment]
If so, does it no longer occur after turning off `Hide browse store button` settings?

**Comment by inotia00** [comment]
Because.. even if I look at the code of the integrations, the `Hide browse store button` setting does not hide the channel tab.

This is most likely a stock YouTube issue

check stock YouTube

**Comment by girshcatt** [comment]
Yes, as i understand YouTube changes button location depends on language you use. And I think that you can fix this bug since we know how YouTube behaves
![Screenshot_2024-01-26-12-18-50-621_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/1ed0cead-fd4f-4e28-9c85-9ebde532d030)
![Screenshot_2024-01-26-12-18-22-121_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/ca15ce36-009a-4d01-b1c7-29f2fa92f0af)

**Comment by girshcatt** [comment]
All is simple, hide browse store button hides bottom button, in Russian join button can be located at bottom if there is no browse store button

**Comment by inotia00** [comment]
Well.. I don't have any plans for that.
Contact to Google, or ReVanced Team.
