### ISSUE TITLE
suggestion(YouTube): move `Hide cast button` setting to `General` settings

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1947]
### Application

YouTube

### Suggestion description

Move `Hide cast button` setting to `General` settings
It also hides cast button in channel profile and homepage as in YTM

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
