### ISSUE TITLE
bug(YouTube/Hide layout components): on tablets `Hide browse store button` setting hides join button too

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1948]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 18.29.38

### Bug description

On tablets `Hide browse store button` setting hides join button too

https://github.com/inotia00/ReVanced_Extended/assets/110785596/de8d493d-178f-4365-a3f9-51178741912c

### Error logs

```shell
:/
```

### Additional context

[ReVanced Extended_v18.29.38_2024-01-26.txt](https://github.com/inotia00/ReVanced_Extended/files/14062109/ReVanced.Extended_v18.29.38_2024-01-26.txt)

### Device Environment

Android 12 One Ui 4.1.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.220.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.220.1)
