### ISSUE TITLE
question(YouTube/Hide layout components): what is `Hide latest posts` setting doing?

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1949]
### Application

YouTube

### Question description

What is `Hide latest posts` setting doing?
It hides this?
![Screenshot_20231129_171744_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/110785596/194b3104-79e8-4ea9-9c8f-179adfaff0de)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I think so too, but I'm not sure.
This was added by the ReVanced Team around 2022
