### ISSUE TITLE
feat(patch): Hide overlay filter when settings icon is tapped

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#195]
### Application

YouTube

### Issue

When you tap the settings icon to lets say check/change video quality, this dark filter fills up the entire phone screen. There is already a similiar patch "hide-player-overlay-filter". Can you please add another patch which removes the overlay filter from the entire app when tapping the settings icon? (Also in fullscreen)

### Patch

![Screenshot_20230129-143603656 (1)](https://user-images.githubusercontent.com/73917917/215329960-82bae3fd-8ee1-4500-b1fd-8f4341fbcdb6.jpg)
👇🏻
![Screenshot_20230129-143621202](https://user-images.githubusercontent.com/73917917/215329963-2aa4ecd2-786d-4a64-b23d-658db196dc37.jpg)

Fullscreen same issue:
![Screenshot_20230129-164501112.jpg](https://user-images.githubusercontent.com/73917917/215337865-11a4e960-b909-454a-b9bc-5fcd028e9d2d.jpg)

### Motivation

Remove overlay filter to see app contents better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
Edited my post with additional screenshot of same issue in fullscreen.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
