### ISSUE TITLE
Trying to go into mini player stucks YouTube Revanced Extended? 

### ISSUE THREAD

**Issue by lightningHoneypot** [inotia00/ReVanced_Extended#1951]
[https://github.com/inotia00/ReVanced_Extended/assets/88814097/d3833153-aab4-4c13-b804-dcbd390279ad

This video shows that when a user (me) is trying to go into mini player mode, it just gets stuck there, what is happening?

YouTube Version: using latest version
Device: Samsung Galaxy S7
OS: Android 9

**Comment by inotia00** [comment]
Additional information is needed
Please reopen the issue according to the issue template
