### ISSUE TITLE
bug: Going into mini player (PiP) will make YouTube Revanced Extended stuck in "full screen"?

### ISSUE THREAD

**Issue by lightningHoneypot** [inotia00/ReVanced_Extended#1952]
### Type

Other

### Tools used

RVX Manager

### Application

ReVanced Extended 19.02.39

### Bug description

When trying to go to a mini player, YouTube will not shrink.
Steps shown in this video
https://github.com/inotia00/ReVanced_Extended/assets/88814097/1f508849-b90b-4816-a3dc-f83e36bbe062

Note: the times where there seems to be a "pause" is me trying to move the video player.

P.S. This bug also affects regular YouTube Revanced

### Additional context

Note: Because I live outside the US and don't have YouTube Premium, I cannot be able to test out whether if unpatched YouTube is affected with this bug.
Thus, "This issue does not reproduce on unpatched YouTube or YT Music" is misleading and is incorrect.

But I can vouch that every video is affected

### Device Environment

Android 8, Samsung Galaxy 7, Samsung Experience 9.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1923
