### ISSUE TITLE
bug: translate comments 

### ISSUE THREAD

**Issue by Cyxcix** [inotia00/ReVanced_Extended#1953]
### Type

Error while patching

### Tools used

RVX Manager

### Application

v.18.45.43

### Bug description

the reason i am reporting this error is because i cannot translate comments from english to spanish. however, i tried it on another Galaxy A22 phone and the option to translate comments appeared.

i forgot to say that if you let me translate comments from other countries but not from english to spanish, i'm from mx.

### Additional context

this error happened months ago but I didn't give it any importance until now. I do understand English but it is easier for me to have that option activated without having to translate it in my little head *laugh*

i have tried other versions but the option to translate Google comments still did not appear. It is a very small error and I think it should not be given importance, but anyone who can provide the solution I will be grateful 

holy mother, I just filled out the text, don't read the bottom part, just the top part. 

### Device Environment

Oppo Reno6 Lite CPH2365 Android 13

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube issue
