### ISSUE TITLE
 buffer issue

### ISSUE THREAD

**Issue by Turhvjbufv** [inotia00/ReVanced_Extended#1954]
### Application

YouTube

### Question description

Do the latest patches solve the playabck and buffer issues in revanced for some user(would test it but currently can't)?
Oh and tnx very much for the release of the patches 
### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As mentioned in the changelog, playback issue has not been resolved.
https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1

**Comment by inotia00** [comment]
There will be many people who will report playback issues here, so no problem

**Comment by EnderMaster77** [comment]
Can confirm that this issue happens to me. Playback stops at 10 seconds.

**Comment by odkate** [comment]
patches-v4.8.0-dev.5
only 360p play ok👌🏻

**Comment by inotia00** [comment]
> patches-v4.8.0-dev.5
> only 360p play ok👌🏻

There is no need to be pessimistic about this.
At least, this means hooking video stream data via NewPipeExtractor works fine.

The reason the video is played in 360p means that the video stream data hook was successful, but the appropriate video quality tag was not found.

If additional reversing engineering is carried out, it may be possible to restore the original video quality in the future.

**Comment by odkate** [comment]
> fell back to 360p quality

If  turn on the 'Skip preloaded buffer', makes 720p playback available

In two cases, the quality menu disappears

**Comment by Vertuhai** [comment]
I was able to avoid long buffering times by patching YouTube version 18.48.39, which means there are fewer problems with this version.
But it seems to me that we need to return the old VancedMicroG-v0.3.0.234914, maybe it will work much better with it as before.
At least as a temporary solution to this problem.

**Comment by Cast0r-999** [comment]
> > patches-v4.8.0-dev.5
> > only 360p play ok👌🏻
> 
> There is no need to be pessimistic about this. At least, this means hooking video stream data via NewPipeExtractor works fine.
> 
> The video stream data hook was still successful, but fell back to 360p quality as the appropriate video quality tag could not be found.
> 
> By performing additional reversing engineering, it may be possible to restore the original video quality in the future.

Dev.5. "spoof stream data" does nothing on my device, still buffer infinitely.

**Comment by lkareeml** [comment]
On phone Android 13 MIUI14.0, YouTube v19.09.37 Patched by Rev Manager 1.19.3 Works fine without updating and currently working with no problem

switching to Tablet Android 14 HyperOS v1.0.6.0, having same buffering issue as everyone, tried multiple versions with no luck, even v19.09.37 transferred from phone doesn't work which is very weird.

Hope I can help

**Comment by enesinan** [comment]
Same issue. not loading videos, yesterday was working execually, after 1 seconds its stopping ( shorts already doesnt work but now videos not playing)

**Comment by Vertuhai** [comment]
> Same issue. not loading videos, yesterday was working execually, after 1 seconds its stopping ( shorts already doesnt work but now videos not playing)
Yes, most have already been blocked.
Nothing in Revanced YouTobe works for more than 30 seconds.
After which there is a long loading of the buffer.
But as an alternative, the usual YouTobe is installed.

**Comment by Vertuhai** [comment]
> Same issue. not loading videos, yesterday was working execually, after 1 seconds its stopping ( shorts already doesnt work but now videos not playing)

Yes, most have already been blocked.
Nothing in Revanced YouTobe works for more than 30 seconds.
After which there is a long loading of the buffer.
But as an alternative, the usual YouTobe is installed.

**Comment by enesinan** [comment]
> Use gray jay for now

What is that

**Comment by enesinan** [comment]
I couldnt find, like newpipe?

**Comment by Vertuhai** [comment]
> I couldnt find, like newpipe?

https://newpipe.net/

**Comment by Vertuhai** [comment]
> > I couldnt find, like newpipe?
> 
> https://grayjay.app/ Similar to new pipe but more creator focused and more plugins

What's the point of using this plugin))?
If it works just as well as the original YouTobe.
It’s better to use the original YouTobe than to create a crap program for yourself and then import the plugin.
But the most interesting thing is that it opens a full-length WEB page.
Honestly, in extreme cases, New Pipe is a hundred times better).

**Comment by enesinan** [comment]
copy url paste to new pipe:) 
I also install grayjay I will try it, but importing json (subscription) is too much slow

**Comment by inotia00** [comment]
As we all know, ReVanced Team solved the issue by spoofing the client with `ANDROID_TESTSUITE` and `IOS` when playing the video.

I'm implementing this in RVX.

I'm considering whether I should set `Spoof client` to its default value of OFF.

The reasons for this are as follows:
1. Not all users are experiencing playback issues.
2. There are too many side effects of the `Spoof client` patch.
3. Therefore, I think it would be better to make the user to manually turn on the `Spoof client` setting after reading all the side effects indicated in the `Spoof client` setting description.

**Comment by inotia00** [comment]
This issue was fixed by the `Spoof client` patch added in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3).

If you are experiencing playback buffer issues, patch with revanced-patches-4.8.3 and then turn on the settings in the following path:
`Settings > ReVanced Extended > Miscellaneous > Spoof client`

There are a lot of side effects, so I recommend reading the explanation before proceeding.

**Comment by enesinan** [comment]
When I switch spoof client, account specific video suggestion not work at Home, and subscriptions, notications not loading also but videos open now without buffer issues

![Screenshot_20240527_100110_RVX.jpg](https://github.com/inotia00/ReVanced_Extended/assets/72499839/dc5f64d7-b319-4247-b899-268496af86bf)

**Comment by GKid94** [comment]
Still a issue 
![Screenshot_2024-07-13-21-22-34-177_app rvx android youtube](https://github.com/user-attachments/assets/cdce31f1-4ea4-4e2e-8b62-2649a47943bd)

**Comment by GKid94** [comment]
![Screenshot_2024-07-20-15-13-57-526_app rvx android youtube](https://github.com/user-attachments/assets/23ccc59d-b986-49bf-94b2-70777ab0bef8)

**Comment by GKid94** [comment]
Why is this pinned then?

**Comment by kyoyacchi** [comment]
Does this count as buffer issue or should i create new issue for it?
![Screenshot_20240826-164335](https://github.com/user-attachments/assets/ea8a6eb1-9261-463b-8972-dc62be17c150)
![Screenshot_20240826-164317_1](https://github.com/user-attachments/assets/9d55dd4f-4857-4030-be2a-7e0e8b1d6b92)
