### ISSUE TITLE
Cant Open the app

### ISSUE THREAD

**Issue by briantgosling** [inotia00/ReVanced_Extended#1955]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

After patching and installing, the patched app cannot be opened, it keeps on closing

### Error logs

```shell
N/A
```

### Solution

N/A

### Additional context

N/A

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in https://github.com/inotia00/revanced-integrations/releases/tag/v1.8.2

integrations may not be updated immediately, so please wait some time and try again.
