### ISSUE TITLE
"Updates" section in RVX Manager loads indefinitely 

### ISSUE THREAD

**Issue by rywz** [inotia00/ReVanced_Extended#1956]
### Type

Other

### Tools used

RVX Manager

### Application

RVX Manager 1.20.1

### Bug description

It just indefinitely loads whilst trying to check for Manager and patches updates. Also, I can't use patches because of that, I guess.

![IMG_20240509_011734](https://github.com/inotia00/ReVanced_Extended/assets/71558811/82d36ee0-edf5-4f57-9595-49474ae6ce4c)
![Screenshot_2024-05-09-01-23-49-868_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/71558811/9f9e5016-df8e-4313-9ad1-c9e4b7853710)
![Screenshot_2024-05-09-01-23-59-786_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/71558811/8e178068-d6a7-4473-9bed-2f0aab3c3d1f)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an old issue with the official ReVanced Manager.
Please try the following steps:
1. Force close RVX Manager.
2. Switch mobile networks. (If you are currently connected to Wi-Fi, switch to Mobile network. If you are currently connected to Mobile network, switch to Wi-Fi.)
3. Re-open RVX Manager.

**Comment by inotia00** [comment]
Well.. try again later
This issue occurs quite often and will resolve itself if you wait

**Comment by 54m4d** [comment]
@inotia00 I changed my IP address and this issue did not happen, it seems like GH is restricting the IP from accessing the GitHub API, it's kind of a rate limit, but I have no idea why it happens, it's strange.

https://api.github.com/rate_limit

**Comment by inotia00** [comment]
Maybe there's something wrong with the way ReVanced Manager accesses the Github API.

rvx-builder also had a similar issue, but I was able to resolve this issue in rvx-builder by refactoring the source code.
In the case of RVX Manager, I will also explore it a little more deeply when my time allows.

**Comment by 54m4d** [comment]
Thanks for the info.

**Comment by shreyjain1998** [comment]
It is working for me while using [1.1.1.1](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone) application.

**Comment by inotia00** [comment]
fixed in [rvx manager v1.20.2](https://github.com/inotia00/revanced-manager/releases/tag/v1.20.2)

**Comment by ILoveOpenSourceApplications** [comment]
This issue is reported in https://github.com/ReVanced/revanced-manager/issues/1776. And yes, it's caused by GitHub ratelimit not being handled.

**Comment by inotia00** [comment]
> Still having the issue where it keeps "loading" with the new version 1.20.2.

There are a variety of reasons why Manager may not display information from Github.

One of the most well-known reasons was that it took too long to wait for the Github API response. - This bug has been fixed in RVX Manager 1.20.2.

There may be a variety of reasons why Manager still fails to display information from Github.

**Comment by Sickhead01** [comment]
> One of the most well-known reasons was that it took too long to wait for the Github API response. - This bug has been fixed in RVX Manager 1.20.2.

I'm still having this issue on 1.23.4 and 1.22.2

**Comment by hamid48707** [comment]
I want  rvx manager for updating

**Comment by XID404** [comment]
Please base update on ReVanced Manager 1.23.3, because RVX 1.23.5 (base 1.23.2) sometimes bug when finish patch "Installation Cancelled"... 😌
