### ISSUE TITLE
bug(youtube/shorts/hide navigation bar): navigation bar stays hidden after exiting shorts player

### ISSUE THREAD

**Issue by n1cKz1** [inotia00/ReVanced_Extended#1957]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

Navigation bar stays hidden even if you exit the Shorts player. It only comes back if you scroll for an extended period of time or press the back button to switch tabs (which only works if you had switched tabs beforehand)

Video:
https://streamable.com/t1l9t1 (link will expire in 2 days)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
1. Perhaps the Litho component was not loaded correctly on your device.
: If you are installing the app for the first time, you will need to force close it at least once.

2. `Hide navigation bar` setting in `Shorts components` is an `Experimental Flags`.
: Features that are likely to cause bugs or are still in the development stage belong to the `Experimental Flags`, and I do not receive bug reports for settings that fall under the `Experimental Flags`.
