### ISSUE TITLE
question(YouTube/`Hide suggested video end screen`): Tapping `Autoplay next video` does nothing

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1958]
### Application

YouTube

### Question description

As the title says, tapping the autoplay next video settings option isn't doing anything. 

![Screenshot_20240509_105547_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/14767733-2c20-46ca-bf9d-f89ee291bf3b)

https://github.com/inotia00/ReVanced_Extended/assets/117499019/dab498f8-a3e0-4e71-b713-d188c0a06cd3

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
It's the toggle below, 'Mobile phone/tablet'. If turned off there'll be no suggested video end screen and if turned on it'll be there.

**Comment by inotia00** [comment]
On YouTube, which is old enough, `Suggested video end screen` was only visible when autoplay was turned on.
(You can also check it out in unpatched YouTube v18.29.38.)

For some reason, on the latest YouTube, `Suggested video end screen` is visible regardless of whether autoplay is turned on or not, so I'm labeling this a 'bug'.

The patch changes the `Suggested video end screen` to only be visible when autoplay is turned on. (i.e. it restores the old YouTube behavior.)

Official ReVanced always closes the `Suggested video end screen`, but this breaks the autoplay behavior.
It also doesn't work when the video is minimized or playing in the background.

**Comment by ILoveOpenSourceApplications** [comment]
> Official ReVanced always closes the `Suggested video end screen`, but this breaks the autoplay behavior. It also doesn't work when the video is minimized or playing in the background.

Ah, I see. So you've modified the patch to follow the pattern of the older version by which turning off autoplay hides the video end screen as a result.

**Comment by inotia00** [comment]
FYI - commit that reflects this change is as follows: https://github.com/inotia00/revanced-patches/commit/f51739a4fe8231406a4a04b04e3ae0cb15bdd7e7
