### ISSUE TITLE
bug: Bug with Voice Access Button in YT

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#196]
### Type

Other

### Application

Youtube

### Bug description

Bug with Mic Button is that the color of button is not proper due to which it is difficult to find. It is completely black with icon. Please fix this in next update. Working fine in light mode.

### Steps to reproduce

Switch to amoled dark mode.
1. Search for any video.
2. You will find this.

### Relevant log output

```shell
..
```

### Screenshots or videos

https://user-images.githubusercontent.com/93650504/215336205-4502ba62-69c2-4e7c-92af-77908bc909ee.mp4

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It is a bug in the official YouTube, not a revanced bug

Reported in the official YouTube [#1](https://www.reddit.com/r/youtube/comments/10o4ei6/is_there_a_way_to_put_this_obtrusive_white) [#2](https://www.reddit.com/r/youtube/comments/10nl1cu/how_to_remove_this_thing) 

Google should fix it
