### ISSUE TITLE
bug: Video Quality when use seekbar thumbnail

### ISSUE THREAD

**Issue by Papye** [inotia00/ReVanced_Extended#1960]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.16.39

### Bug description

If have set default video quality. When watching a video and setting the quality to another else. quality will alway back to default when used seekbar thumbnail.

### Device Environment

Samsung , Android 11 , one ui 3.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Thank you for reaching here.
Since a duplicate issue has been reported, you can continue the discussion by going to the following link: https://github.com/inotia00/ReVanced_Extended/issues/1959
