### ISSUE TITLE
feat: switch to new gmscore

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [inotia00/ReVanced_Extended#1963]
### Application

YouTube Music

### Feature description

This feature applies for both YT music and Youtube, and consists on changing the old microg for this one https://github.com/ReVanced/GmsCore 

And this is the original one

https://github.com/microg/GmsCore

The official microg project released a version which fix all buffering issues, and all the forks (YT-Advanced, anddea, rufusin, etc...) switched to that instead of the old versions, you can see their code in order to do the respective changes to yours, to be more up to date respecting this novelty

### Motivation

I decided to write this because of the recent buffering issues in some builds

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I have already switched my source to ReVanced GmsCore, and you can check it in the release notes. https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1
