### ISSUE TITLE
bug: Manager almost always stuck at loading

### ISSUE THREAD

**Issue by 54m4d** [inotia00/ReVanced_Extended#1965]
### Type

Other

### Tools used

RVX Manager

### Application

Revanced Manager v1.20.1

### Bug description

Hi!

When I open the Manager and navigate to the update section at the top, it often gets stuck on "Loading." However, after returning several hours later, it resolves itself. This issue has persisted consistently, and the only solution is to try again after a while.

I'm using Revanced Manager v1.20.1 by inotia.

<details>
<summary>Screenshot</summary>
<img src=https://github.com/inotia00/ReVanced_Extended/assets/52612348/113eb9fe-9709-49d3-a18f-4793745a8cb9>
</details>

### Error logs

```shell
N/A
```

### Additional context

N/A

### Device Environment

Not device related.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Thank you for reaching here.
Since a duplicate issue has been reported, you can continue the discussion by going to the following link: https://github.com/inotia00/ReVanced_Extended/issues/1956
