### ISSUE TITLE
bug (YouTube/ `Hide suggested video end screen`): Toggling `Autoplay next video` requires an app restart to take effect 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1968]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

The button only works after an app restart and currently it doesn't do that by default. 

### Solution

Either add a pop-up to restart the app when changing the toggle or add a description saying that option requires an app restart when changing.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You mean, `Skip autoplay countdown` setting?

**Comment by inotia00** [comment]
For the `Autoplay next video` toggle in YouTube settings, an app restart is not required.
The settings will only be applied from the next video playing.

If you change `Settings > ReVanced Extended > Player > Player buttons > Hide autoplay button` to off, the `Autoplay button` will be visible in the player.

You can also change the `Autoplay next video` status through the `Autoplay button` in the player, so check it out.

**Comment by ILoveOpenSourceApplications** [comment]
If the user starts playing a video with the toggle on, and then turned it off right as the autoplay timer is going on, the end screen card stays on top of every video and can't be closed though that's a weird situation to happen. I guess this issue isn't that big as hopefully nobody will decide to change the setting at the very last moment. You can close it if you want.

An app restart or toggling the setting on/off does fix the issue.

https://github.com/inotia00/ReVanced_Extended/assets/117499019/cb44f5e4-683c-45df-a1c8-7f12d99c243a

**Comment by inotia00** [comment]
Makes sense.
An app restart dialog cannot be added to the toggle in YouTube settings.
Therefore, it seems more appropriate to add an explanation to the summary of the `Hide suggested video end screen` setting.

**Comment by ILoveOpenSourceApplications** [comment]
> If the user starts playing a video with the toggle on, and then turned it off right as the autoplay timer is going on

The toggle I meant here is `Settings>Autoplay>Mobile phone/tablet` one and not the autoplay button on the video player. So now, I'm in doubt whether a description is needed or not. Let's see if anyone else reports this issue in the future and if so we can add the description. Till then I say leave it as it is, as like I mentioned earlier it's a strange replication situation for a normal user. Either they want autoplay or they don't. I was just playing around with the setting when I came across this one, which implies a normal user shouldn't.

**Comment by ILoveOpenSourceApplications** [comment]
So, shall I just close this as not planned for the time being?

**Comment by inotia00** [comment]
I just added one line to the description as follows:

```
This setting has been deprecated.

Instead, use the 'Settings → Autoplay → Autoplay next video' setting.

Note:
• If you have any issues with 'Suggested video end screen', try restarting the app.
```

**Comment by ILoveOpenSourceApplications** [comment]
Looks good, though some may argue it's a bit lengthy.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.8.0-dev.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.4)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)

**Comment by inotia00** [comment]
> Could you have an option to show the suggested end card without the auto play next video.
> 
> Before I used the play now if I wanted to watch the suggested video or not. Now it's autoplays automatically with no option to choose.

I think it's a little different from the topic of this issue.
Could you please open a new issue?
