### ISSUE TITLE
bug(YouTube Music): RYD & Action Bar settings don't work 

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#1969]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

App: YouTube Music
Version: 6.50.51
Patches version: 4.7.1

### Bug description

Since last month, the action bar and RYD settings don't working despeite being set properly. Problem exists also on different patches by other devs (ReX, Anddea's RVX). Re-installing (along with GMSCore) did nothing, and the problem seems to only occur with me - on my parents and friends YTM all is working properly, settings are working, so I suspect it's A/B testing or similar thing.
![1](https://github.com/inotia00/ReVanced_Extended/assets/69505731/643fca36-5fee-4381-880e-bea7c64a64af)
![2](https://github.com/inotia00/ReVanced_Extended/assets/69505731/24de2de1-d068-4d0c-8e7f-e92867aa4cb3)
![3](https://github.com/inotia00/ReVanced_Extended/assets/69505731/51eefd05-a76d-45f8-b982-0c3241b3b07e)

### Additional context

Translated options from Polish to English:

**Action bar**: Hide: comments button, download button, button labels, radio button, hook download button
**RYD**: option to enable & API connection notifications inside app

### Device Environment

Device: HUAWEI JNY-LX1
Operating system: EMUI 12, Android 10
Version of operating system: 12.0.0.295

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I haven't experienced it yet.
It is likely to be A/B tests.

**Comment by GucekPL** [comment]
Just as I thought... is there nothing that can be done about it?

**Comment by inotia00** [comment]
Fix is only possible if this A/B test is applied to all users
Until then, there is no other way than to stay at the lowest version supported by the patch (YT Music v6.29.58)

**Comment by YT-Advanced** [comment]
> I haven't experienced it yet.
> It is likely to be A/B tests.

Yea right, it is. With new A/B Testing, the action bar will use Litho Component for their button. However, right now they reverted their changes in my account :(

**Comment by GucekPL** [comment]
Today, Google reverted their changes to my account related to `LithoComponent` on Action Bar. RYD & Action Bar settings works again properly 🥳

**Comment by inotia00** [comment]
Finally, I too started to experience this issue on one of my accounts

The version affected by the A/B test is **YouTube Music 7.17.51+**

Users can avoid these A/B tests by rolling back to the previous supported version, **YouTube Music 7.16.53**

**Comment by GucekPL** [comment]
Oh, I see Google didn't forget about `LithoComponent` on Action Bar. I hope I don't have to relive the destroyed customisation of the Action Bar 😅

**Comment by inotia00** [comment]
In [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1), the supported version has been rolled back to YouTube Music 7.16.53.
This bug is only reproducible on YouTube Music 7.17.xx+, so the issue is closed.
