### ISSUE TITLE
feat: settings for `remove-player-button-background` patch

### ISSUE THREAD

**Issue by kazimmt** [inotia00/ReVanced_Extended#197]
### Application

YouTube

### Issue

Currently there is no settings available for this patch

### Patch

An option to turn on/off player button background from ReVanced Extended Settings

### Motivation

So we can use whatever we like without repatching the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)

**Comment by kazimmt** [comment]
> reflected in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)

Thank you So Much

**Comment by briantgosling** [comment]
hey can i ask what this patch do
