### ISSUE TITLE
suggestion(YouTube): Hide 'Thanks' button in Live Chat

### ISSUE THREAD

**Issue by Oleepre** [inotia00/ReVanced_Extended#1972]
### Application

YouTube

### Suggestion description

 Hide the dollar sign button near the comment box on live chats, used to send Super Stickers, Super Chats, join membership, and Membership gifting.

![Screenshot_20240430_203601](https://github.com/inotia00/ReVanced_Extended/assets/137729871/7ced7103-5140-4967-b593-cb9c300a2586)
 
 We can hide a similar button in the comment section (RVX Settings->Comments->Hide thanks button), so it would make sense to do the same with this one. I believe we were able to do it on previous versions.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Since this is not a `comment`, it is normal for it to not be hidden.
(`Hide thanks button` setting is in `Comments` settings)
