### ISSUE TITLE
suggestion (YT) : Make "Keep Landscape Mode" stronger / more aggressive.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1973]
### Application

YouTube

### Suggestion description

Currently, this is what "Keep Landscape Mode" toggle does: 

When a video is playing in fullscreen and the user locks their phone, then unlocks it, the video will still be in fullscreen. But this feature does not work when you switch back & forth between RVX and other apps. You can try this by playing some video in fullscreen, then tap Home button, then open RVX, and notice how the player automatically comes out of fullscreen.

This is what I'm suggesting:

Make a video remain fullscreen, when user comes back to RVX, after using some other apps.

Interestingly, the above problem does not happen on "portrait fullscreen" videos ( https://youtu.be/2uoau4UwQsY ). You can play them in fullscreen, and switch between apps all you want, it will still be in fullscreen.

So, is there any way to replicate this "good behaviour" for all types of videos?

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Well.. this is the intended behavior of stock YouTube

If you use another app in landscape mode and return to YouTube, fullscreen will remain

**Comment by Aryan-Chauhan** [comment]
> Well.. this is the intended behavior of stock YouTube
> 
> If you use another app in landscape mode and return to YouTube, landscape mode(fullscreen) will remain

Actually, I just tried it and fullscreen didn't remain.

I played a video in landscape fullscreen in VLC, then I played a video in landscape fullscreen in RVX.

Then I switched back and forth between these two "fullscreen apps" (as you said), but still RVX came automatically out of fullscreen.

If you get time, can you look into this suggestion? It is one of the most demanded feature.

**Comment by Aryan-Chauhan** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1920

Me & @nintendork07 are talking about the same thing.

**Comment by inotia00** [comment]
I don't accept new patch requests for YouTube, and `Keep landscape mode` is an experimental flag.

Thanks for the suggestion, but it would be better to ask to ReVanced Team.

**Comment by Aryan-Chauhan** [comment]
Hmm.

https://github.com/ReVanced/revanced-patches/issues/465

**Comment by Aryan-Chauhan** [comment]
Stock YT v20.03.45 has this feature now.
