### ISSUE TITLE
suggestion (YT) : Slash, Total Duration & Quality should be white in colour for uniform look.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1974]
### Application

YouTube

### Suggestion description

In the player UI, please make these 3 elements white in colour.

Reason: Overlay Buttons, Elapsed Time, Play Button, Settings Button, Collapse Button, all of them are in white. So, compared to them, they look out of place and have no benefit in being grey colour.

So, if it's not a highly time-consuming process, please make them white.
![Screenshot_2024-05-10-09-42-15-73_a9acfd2263b6b7a65bf2540b0d9449ca](https://github.com/inotia00/ReVanced_Extended/assets/91815107/a10c34dd-8079-433a-b756-857bcdf9fc0b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Closing the issue, as it is a patch request.
