### ISSUE TITLE
suggestion (YT) : Allow the user to keep same type of Swipe Control on both side of the screen.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1975]
### Application

YouTube

### Suggestion description

Currently, we can use "Brightness Gesture" on the left side of the screen & "Volume Gesture" on the right side of the screen.

So, I'm requesting for implementation of two possibilities (1st can't be used when 2nd is enabled and vice-versa):

1. An option to use Volume Gesture on both left side and right side.

2. An option to use Brightness Gesture on both left side and right side.

Thank you.

**Motivation:**

There are people who only use one type of Swipe Control (either Volume or Brightness), so it's a logical move to provide them the ability to use 100% of the screen to change values of either Volume or Brightness.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Any particular reason for closing?

**Comment by inotia00** [comment]
I don't accept `Feature requests` for YouTube.
Most YouTube layouts rely on the server side, making the feature difficult to implement.

If you want to submit `Feature request` for YouTube, please contact the ReVanced Team.
If you want the feature you implemented to be merged into the repo, please open a Pull request.

**Comment by Aryan-Chauhan** [comment]
Hmm.

https://github.com/ReVanced/revanced-patches/issues/3174
