### ISSUE TITLE
suggestion (YT) :  Ability to hide "Quality" from Player Flyout Panel.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1976]
### Application

YouTube

### Suggestion description

Kindly add the ability to hide "Quality" from Player Flyout Panel.

![313443118-5c083d0c-eb61-4a66-8286-25ae9c7ec881](https://github.com/inotia00/ReVanced_Extended/assets/91815107/283178fc-c4ca-496b-b111-b94174c0cdf0)

**Motivation:**

• It is the only option in Player Flyout Panel that cannot be hidden. All others have an option to hide them.

• There are many people who use WiFi & always want their videos to play at maximum available quality, so they have no need for "Quality" in Player Flyout Panel. I, too, fall in this category.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Closing the issue, as it is a patch request.

**Comment by Aryan-Chauhan** [comment]
> Closing the issue, as it is a patch request.

But inotia00, "Hide Player Flyout Menu" is a patch, which is already available.

Inside it, a small option called as "Hide Quality" is lacking.

Can you consider this a "patch improvement" instead of a  full-fleged YT patch request?

**Comment by inotia00** [comment]
I have no plans to add `Hide quality menu` setting in the future for the following reasons:

1. In some versions of YouTube, hiding the `Quality` menu will also hide the `Additional settings` and `Premium controls` menus. (yeah, it's buggy)
2. I haven't found any proper motivation to hide all player flyout menus.

**Comment by Aryan-Chauhan** [comment]
> I have no plans to add `Hide quality menu` setting in the future for the following reasons:
> 
> 1. In some versions of YouTube, hiding the `Quality` menu will also hide the `Additional settings` and `Premium controls` menus. (yeah, it's buggy)
> 2. I haven't found any proper motivation to hide all player flyout menus.

If the user is ready to bear the side-effects, then is it okay?

You can add an `INFORM` that warns the user about any unintended hiding.

You can treat this as motivation: It will be good for people who use `Replace Time Stamp Action`.

Waiting for your opinion.

**Comment by YT-Advanced** [comment]
> 1. If the user is ready to bear the side-effects, then is it okay? You can add an `INFORM` that warns the user about any unintended hiding.
> 
Some usets have never read any side effect, they just asking. You can see it in RVX Chat.

**Comment by Aryan-Chauhan** [comment]
> > 1. If the user is ready to bear the side-effects, then is it okay? You can add an `INFORM` that warns the user about any unintended hiding.
> > 
> Some usets have never read any side effect, they just asking. You can see it in RVX Chat.

Do you mean, "Some users have never had any side effect" ?

**Comment by YT-Advanced** [comment]
> > > 1. If the user is ready to bear the side-effects, then is it okay? You can add an `INFORM` that warns the user about any unintended hiding.
> > > 
> > Some usets have never read any side effect, they just asking. You can see it in RVX Chat.
> 
> Do you mean, "Some users have never had any side effect" ?

Nah no. For example, in the past, Spoof Player Parameter will not have seekbar thumbnails, you know. However, users just spamming everyday with "Where is my seekbar thumbnails" instead reading the side effect
