### ISSUE TITLE
bug: "Show universal patches" does not show universal patches

### ISSUE THREAD

**Issue by max-brod** [inotia00/ReVanced_Extended#1979]
### Type

Other

### Tools used

RVX Manager

### Application

RVX Manager v1.20.1

### Bug description

When enabling "Show universal patches" in Settings, universal patches do not get listed for any supported application, such as YouTube or YouTube Music. 

### Solution

Universal patches should still be supported in addition to RVX patches as some are still likely be used by Revanced users. If there are no plans for universal patches to be included, please remove the setting.

Expected behavior:
When enabling "Show universal patches", universal patches should be shown.

### Additional context

I personally like the "Spoof video player resolution" patch for my 1440p-supported phone running 1080p natively.

### Device Environment

Android 13, OneUI 5.1, Galaxy Note 20 Ultra 5G

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unlike the official ReVanced, my patch does not support Universal patches.

Therefore, it is not a bug that universal patches are not visible even if the `Show universal patches` setting is turned on.

List of all patches supported by RVX patches can be found in README.md:
https://github.com/inotia00/revanced-patches?tab=readme-ov-file#-list-of-patches-in-this-repository
