### ISSUE TITLE
bug: Video buffer settings are not applied

### ISSUE THREAD

**Issue by LTVA1** [inotia00/ReVanced_Extended#198]
### Type

Error at runtime

### Application

Youtube 17.28.35

### Bug description

No matter what numbers I put in video buffer settings the actual size of buffered video piece stays at default value. 

### Steps to reproduce

1. Pick up an hour long video
2. Scroll to random place, pause, wait until it stops downloading stuff, play the video until it stops
3. Change video buffer settings
4. Repeat `2.` and see that nothing changes 

### Relevant log output

```shell
Emmm
```

### Device Environment

Android 11, MIUI Glibal 12.5.7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
At some point the custom video buffer patch is no longer valid
So I will completely remove the custom video buffer patch in the next version

**Comment by inotia00** [comment]
removed `custom-video-buffer` patch in revanced-patches-v2.158.1

**Comment by Evengard** [comment]
Erhm, the patch was pretty useful. Will it be brought back?

**Comment by inotia00** [comment]
> Erhm, the patch was pretty useful. Will it be brought back?

I know that patch is useful, but it doesn't work properly with latest YouTube anymore

If I find a method that works on the latest YouTube, I'll add it back.
