### ISSUE TITLE
bug(YouTube/SponsorBlock): pressing the fine adjustment buttons skips to the end of the video while creating a new SponsorBlock segment

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#1980]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.7.1

### Bug description

When I click the fine adjustment buttons, it skips to the end of the video. I have tried to use different amounts of milliseconds, but nothing changed.

https://github.com/inotia00/ReVanced_Extended/assets/132079771/a609019d-f3b8-401a-8d16-bf9a8ea47045

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.0-dev.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.4)

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)
