### ISSUE TITLE
feat (YT Music) : add Wide Search Bar & Wide Search Bar With Header.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1981]
### Application

YouTube Music

### Feature description

Please add "Wide Search Bar" on the encircled area. That way, RVX YT Music heading & Wide Search Bar will appear simultaneously side-by-side.
![320844907-dea52ef1-eee2-479b-9942-913d0c5b149d](https://github.com/inotia00/ReVanced_Extended/assets/91815107/3ac14339-441d-497c-aadf-8cf44151fd8f)

### Motivation

Search is a basic feature, so it should have a bigger bar for user's convenience.

Also, RVX YT has this feature.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Duplicated with the following issue: https://github.com/inotia00/ReVanced_Extended/issues/36

**Comment by Aryan-Chauhan** [comment]
> Duplicated with the following issue: https://github.com/inotia00/ReVanced_Extended/issues/36

Will it be a good idea to close #36 and open #1981 because of the following reason?

• #36 only requests for Wide Search Bar and #1981 requests for Wide Search Bar + Wide Search Bar With Header.
