### ISSUE TITLE
feat (YT Music) : Hook `Share Button` to open up Android's Native Share Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1983]
### Application

YouTube Music

### Feature description

Kindly add a patch that opens up Android's Native Share Menu when you tap on `Share Button`.

Currently, when you tap on Share, YT Music's in-app share menu opens up, then you have to click on `Share With Other Apps`, and then finally Native Share Menu opens up.
![1](https://github.com/inotia00/ReVanced_Extended/assets/91815107/306b0be6-3603-4038-b074-e2567500f671)
![2](https://github.com/inotia00/ReVanced_Extended/assets/91815107/db3ecd81-fb11-4772-a40e-9ec78d49c3dd)
![3](https://github.com/inotia00/ReVanced_Extended/assets/91815107/b8c9b058-f23a-4bcf-8fe6-4dcebb974795)

### Motivation

YT Music's in-app share menu is useless, since Android's Native Share Menu has more sharing options.

It just increases steps.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1)

**Comment by nightznero** [comment]
What `si` stands for in sharing links?
@inotia00 bcs if sharing direct from yt menu link looks like this:
`https://music.youtube.com/watch?v=yZlEj8XRLAw`
but from Android looks like:
`https://music.youtube.com/watch?v=yZlEj8XRLAw**&si=kfqAerzTpV8xpK0F**`
Its not not timestamp,its any tracker/metric?
