### ISSUE TITLE
bug(youtube): hide chapters in seekbar doesn't work

### ISSUE THREAD

**Issue by n1cKz1** [inotia00/ReVanced_Extended#1984]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

Chapters still show up in seekbar when the option is enabled, as do their effects while seeking (auto dragging etc.)

https://github.com/inotia00/ReVanced_Extended/assets/107653639/93bf3df2-6c0c-4b10-8545-5726aaf474d5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![Chapter](https://github.com/inotia00/ReVanced_Extended/assets/108592928/dc2a7559-1f1b-4582-b70f-fb41d3aa83ec)
`Hide seekbar chapter` setting, as the name suggests, hides only the chapter labels in the seekbar.

**Comment by n1cKz1** [comment]
The title made it sound like that's what it was, perhaps it could be renamed as `Hide chapter labels`?

**Comment by inotia00** [comment]
Chapters in the thumbnail preview are also called ‘chapter labels’ by some people.
I'll just stick with the current setting title for a while.
