### ISSUE TITLE
suggestion(YT) : Re-adding `Rounded (curved) Overlay icons` from Anddea patches

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1985]
### Application

YouTube

### Suggestion description

Can you please try to re-add them. You have removed them in your commit [bb331e5](https://github.com/inotia00/revanced-patches/commit/bb331e5c3a4ad0a9e9156f9487759b6fc8aa30a8). But @anddea added them back in his commit [73ab950](https://github.com/anddea/revanced-patches/commit/73ab950ce251e673860826cf32239c451de64122).

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Same. Open pull request if necessary https://github.com/inotia00/revanced-patches/pull/30

**Comment by Vipin2003** [comment]
> Open pull requests if necessary [inotia00/revanced-patches#30](https://github.com/inotia00/revanced-patches/pull/30)

Should I open it for player overlay icons? As it is for player.
