### ISSUE TITLE
suggestion (YT): Merging necessary patches from Anddea RVX Patches.

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1986]
### Application

YouTube

### Suggestion description

As Anddea introduced too many patches and keep old patches. Can't to merge some of the patches from there to here. Here are the patches which people like:
1. Custom Icon Splash Screen
2. Snackbar Theme
3. Hide live chat messages and header for Shorts.
4. Visual Preference Icons
5. Rounded Overlay Icons

There are more many features which can be merged. So that, Anddea can close his repo carefreely.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Open pull request if necessary https://github.com/inotia00/revanced-patches/pull/30

**Comment by Vipin2003** [comment]
> Open pull requests if necessary [inotia00/revanced-patches#30](https://github.com/inotia00/revanced-patches/pull/30)

Can't you add them without PR as there too much code changes in your repo and Anddea repo. Isn't it is worth if I just create issues with the patch request (or suggestions) with a refer to the anddea's commit. Som you don't have to find rhem manually,
