### ISSUE TITLE
bug(YouTube/Return YouTube Dislike): wrong video id is used in shorts

### ISSUE THREAD

**Issue by 1fia** [inotia00/ReVanced_Extended#1987]
### Type

Cosmetic

### Tools used

Revancify

### Application

YT 19.16.39

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/163759302/550a01fa-22da-4c60-8ded-0707b85675cb

the correct value isnt shown unless the dislike button is pressed
4.8.0-dev.2 patches
1.9.0-dev.1 integrations

### Device Environment

Android 12 OneUI 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.0-dev.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.4)

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)
