### ISSUE TITLE
bug: can't create new playlists

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [inotia00/ReVanced_Extended#1988]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube Music 6.51.52

### Bug description

When i try to create a playlist from queue or from library, the dialog disappears on first case and in second case it simply doesn't work

### Error logs

```shell
Idk
```

### Solution

There is not

### Additional context

Could you amswer more recent issues instead of the older ones

### Device Environment

Android 12 one ui 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You have already opened the issue: https://github.com/inotia00/ReVanced_Extended/issues/1971
