### ISSUE TITLE
bug(YouTube/Hide layout components): Hide settings menu whitelist method doesn't work properly

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1989]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 19.16.39

### Bug description

1. When only one keyword is used e.g. `General` opening that setting just shows a black screen.
![a](https://github.com/inotia00/ReVanced_Extended/assets/125728453/7e3bb56b-cfa7-4a11-9335-08b8b32d565b)

2. When multiple keywords are entered e.g. `General`, `Notifications`, none of them appear. Only ReVanced Extended is shown.
![c](https://github.com/inotia00/ReVanced_Extended/assets/125728453/4aab78d3-e461-42aa-91d1-e4a0c140c4a2)
![b](https://github.com/inotia00/ReVanced_Extended/assets/125728453/4ff65d1a-39b5-4975-855c-486987dd57ce)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Since this is a bug in the dev branch, you can trace it from https://github.com/inotia00/ReVanced_Extended/issues/1964
