### ISSUE TITLE
feat: new yellow icon for revanced 

### ISSUE THREAD

**Issue by Pravir46** [inotia00/ReVanced_Extended#1990]
### Application

YouTube Music

### Feature description

![RDT_20240510_1527576841156707860770116](https://github.com/inotia00/ReVanced_Extended/assets/99163211/23adcf51-37e5-47f4-8d59-5c71ec1dd530)
Add this as icon for revanced extended for both YouTube music and YouTube 

### Motivation

I guess it looks much better than red and blue and these icons have been used for more than year something new should be done for icon 

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You can change the icon to whatever you want using the patch options in the `Custom branding icon YouTube Music` patch:
https://github.com/inotia00/ReVanced_Extended/issues/1800#issuecomment-1843814955

If you want the new icon to be reflected in the source code, please open the PR.
(e.g. https://github.com/inotia00/revanced-patches/pull/8)

**Comment by Pravir46** [comment]
Can i get a tutorial or something about how to use a different icon by
custom branding icon patch I don't know how to use my icons using this
patch

**Comment by Pravir46** [comment]
Ok thank you I got it how to do that but may I know how to do this in revancify ?

**Comment by inotia00** [comment]
If you are using Revancify, you can enter the patch options in the following path:

```
5. Edit Patch Options > Custom branding icon YouTube
```

Simply replace the previously entered value with the path where the icon is located in local storage.

**Comment by Pravir46** [comment]
Ok thank you and bro one more issue I am having my friend hai realme gt master (Indian version) he is facing buffer issue I have several time uninstalled GMS core and  revanced then to it is having the same problem any solution ?

**Comment by inotia00** [comment]
The playback issue has not yet been fully resolved.
You can keep tracking it at https://github.com/inotia00/ReVanced_Extended/issues/1954
