### ISSUE TITLE
Issue: YouTube shorts trending section blank screen 

### ISSUE THREAD

**Issue by Pravir46** [inotia00/ReVanced_Extended#1991]
### Type

Other

### Tools used

Revancify

### Application

YouTube version 19.16.39
![Screenshot_2024-05-11-02-34-39-256_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/99163211/80b28015-60bb-4dc2-ae31-ce14e39f3a2d)
Fix this issue with next patches 

### Bug description

Can't see the YouTube shorts trending section 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Just turn off the following settings:

Settings > ReVanced Extended > Shorts > Hide in home feed and related videos

'Trending' belongs to the home feed, so it is not a bug that it is hidden.
