### ISSUE TITLE
suggestion: Override `download` button state to always-available when `Override download action button` is used

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1992]
### Application

YouTube

### Suggestion description

Suggestion to forcibly enable always-available (not greyed out) state for download button on videos where downloads aren't available for non-premium users as downloads work just fine when using `Override download action button` feature.

### Download not available for non-premium users (greyed out)-
![Screenshot_20240511-073016](https://github.com/inotia00/ReVanced_Extended/assets/107706560/5e281a3b-afd6-4302-8331-dd5378b71e92)
### Being able to download the video regardless of it not being available to non-premium users due to `Override download action button` patch-
![Screenshot_20240511-073333](https://github.com/inotia00/ReVanced_Extended/assets/107706560/c2fbdf20-1355-4b26-b92c-d86730cd7010)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
I'm not sure what "Override the greyed download buttons" means, can you explain more clearly?

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1992#issuecomment-2105542734
So usually normal YouTube shows download button as light greyed for when the related video is available to download-

![Screenshot_20240511-144451](https://github.com/inotia00/ReVanced_Extended/assets/107706560/128f97e6-2159-43bb-9c3e-b3742ce46144)

This indicates that we can download it. But on other videos where downloads free options for non-premium users aren't available, they're greyed out like this-

![Screenshot_20240511-144744](https://github.com/inotia00/ReVanced_Extended/assets/107706560/8b36d117-6cc8-409e-977b-1d8432e55fb4)

What I suggested is that when `Override download action button` is enabled, that distinction dosen't matters as we are using a 3rd party app to download that said video anyways. So it makes more sense logically for all download icons to be normally grey colour like the first pic in this comment. Hope this makes sense.

**Comment by Rairof** [comment]
Perhaps I should have used a more appropriate title for this

**Comment by Cast0r-999** [comment]
I support this!!!

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2285#issue-2442621238
It would be great if this suggestion is also implemented alongside https://github.com/inotia00/ReVanced_Extended/issues/2285#issue-2442621238 just to make "Hook download" feature nearly a complete feature.

**Comment by Rairof** [comment]
@YT-Advanced I have edited this issue post to better explain the suggestion. Hopefully its clear to understand now. Let me know if there are any questions or if more clarification is required! <3
