### ISSUE TITLE
YTM Author "Includes Paid"

### ISSUE THREAD

**Issue by nightznero** [inotia00/ReVanced_Extended#1994]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YTM 6.50.51, Patches v4.7.1

### Bug description

On minimalized player some musics shows `Includes Paid` over orginal author. Just Cosmetic issue,nothing serious.
![Screenshot_20240511_060826_YouTube Music RVX](https://github.com/inotia00/ReVanced_Extended/assets/61750641/9aea0267-9512-4b5a-88f1-d8b0bf9b888c)

### Solution

shows as should be: name author

### Device Environment

A13 OneUI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Patch to hide this label has not been implemented in YT Music.
Therefore, the `Bug report` label is not appropriate, closing issue.

You can open a new issue using the `Feature request` label if you want.
