### ISSUE TITLE
question: What values can the WiderBottomPadding option have?

### ISSUE THREAD

**Issue by odkate** [inotia00/ReVanced_Extended#1995]
### Application

YouTube

### Question description

![Screenshot_20240511-170002](https://github.com/inotia00/ReVanced_Extended/assets/90364108/0eea1869-71ae-42dc-9ef4-94f77c3ca3b1)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`true` or `false` (default is `false`)
