### ISSUE TITLE
question (RVX YT Music) : What does `Hide Empty Component` do?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1997]
Just a small question.

Thanks!

**Comment by inotia00** [comment]
![YT_Music_v6 29 59](https://github.com/inotia00/ReVanced_Extended/assets/108592928/e03fdb2f-ce0d-446d-be30-507858fff60d)

In certain versions of YT Music, the account switching menu has an empty but clickable dummy menu.
(I don't know why Google added this menu)

`Hide account menu filter` has a limitation of not being able to hide empty values, so this menu cannot be hidden with a filter.

So I added a setting to hide this empty menu.
