### ISSUE TITLE
bug(YouTube/Return Youtube Dislike): shorts dislike count not always shown

### ISSUE THREAD

**Issue by 1fia** [inotia00/ReVanced_Extended#1999]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

the first short will display the number but after that, the dislike counter only shows "-"

https://github.com/inotia00/ReVanced_Extended/assets/163759302/49507c80-7c43-4517-a5dd-b991f436cf09

it seems that scrolling back and forth between shorts makes the number reappear or disappear 

Patches 4.8.0-dev.5
Integrations 1.9.0-dev.4

### Additional context

the bug occurs only when patch or spoof v18.33.40 and lower

### Device Environment

Android 12 OneUI 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Integrates with the following issues: https://github.com/inotia00/ReVanced_Extended/issues/1565

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.0-dev.6](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.0-dev.6)
