### ISSUE TITLE
bug: Aborts process in A13

### ISSUE THREAD

**Issue by SpyderThingy** [inotia00/ReVanced_Extended#20]
### Type

Error while patching

### Application

When I try to patch the app on A13 it bugs out and aborts the process.

### Bug description

Shown

### Steps to reproduce

Have A13
Do all regular steps
Patch app

### Relevant log output

```shell
Cant
```

### Device Environment

One UI 5
Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
What app did you try to patch (e.g. YouTube v17.45.36),
which method was used (e.g. rvx-builder),
What errors occur (screenshot/log)
please add these

**Comment by SpyderThingy** [comment]
It was the latest manager
That's why

**Comment by SpyderThingy** [comment]
It's fine now

**Comment by inotia00** [comment]
umm ok
