### ISSUE TITLE
seekbar

### ISSUE THREAD

**Issue by Lilliput1212** [inotia00/ReVanced_Extended#200]
### Application

YouTube

### Description

could you please make a tweak to change the colour of the duration while playing a video. sometimes it is not possible to see the duration of the video clearly while playing it .

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This request is already added patch-request https://github.com/inotia00/ReVanced_Extended/issues/67
Since this is a duplicate issue, I'll close this issue
