### ISSUE TITLE
suggestion(YT) - Hide extra buttons from shorts while paused

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#2000]
### Application

YouTube

### Suggestion description

This patch should remove buttons like Trending, Live, Subscription from Shorts while paused.

![Screenshot_20240512_170414](https://github.com/inotia00/ReVanced_Extended/assets/93650504/3b7bc4dc-ec4b-4636-ab88-2b7fc75afda4)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by shreyjain1998** [comment]
It's already available in latest patches.
Shorts > Shorts player > `Hide paused overlay buttons`
