### ISSUE TITLE
bug: (YT Music/Settings): The old player background/layout aren't available in the RVX settings.

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#2002]
### Type

Other

### Tools used

RVX Manager

### Application

YT Music 6.50.51, 6.51.52.
v4.7.1—4.8.0-dev5.

### Bug description

The old player background and the old player layout are missing in RVX Settings → Player.

![Screenshot_20240512_144318_ReVanced Music](https://github.com/inotia00/ReVanced_Extended/assets/130248949/a1c22a81-2e2d-429d-beb0-12af70be05b1)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Those settings are only available in YT Music 6.29.58

Settings are added only in compatible versions

**Comment by s7san007** [comment]
Ок. Then you should write it here. Because I don't see any mention that it's only for 6.29.58.

> feat(YouTube Music): Enable color match player, Enable force minimized player, Enable old player background, Enable old player layout, Remember repeat state, Hide fullscreen share button, Remember shuffle state, Enable zen mode patches have been integrated into Player components patch.
