### ISSUE TITLE
bug(YouTube): Expand video description opens channel page for no description videos

### ISSUE THREAD

**Issue by shreyjain1998** [inotia00/ReVanced_Extended#2003]
### Type

Other

### Tools used

Revancify

### Application

YouTube v19.16.39

### Bug description

For the videos with no description, Enabling the `Expand video description` opens up the channel page of the creator. [ example video](https://youtu.be/aPPZJ1DmZxg)

I know it's an experimental feature, but it would be great if it could be fixed.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
That's why the `Expand video description` setting is marked as `Experimental Flags`.
