### ISSUE TITLE
suggestion: Adding Option to Blur Video Thumbnail

### ISSUE THREAD

**Issue by vishal273007** [inotia00/ReVanced_Extended#2005]
### Application

YouTube

### Suggestion description

I want to give a suggestion for adding an option to add "blur effect" on the video thumbnail. I use YouTube in Chrome browser with extension and enabled blur option in extension. This option is very beneficial as it helps to minimize the urge to click on the video without reading the video title.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I don't accept feature requests for YouTube.
