### ISSUE TITLE
suggestion: split "Hide suggestions sections" option

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2006]
### Application

YouTube

### Suggestion description

Talking about this option:
![Screenshot_20240513_161854_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/130296934/25d4fce1-9ddc-4cd7-8902-f56680ff9e8c)

In the past "Hide suggestions sections" option was 3 different options and thus I was able to only hide the "place section"
How was in the past:
![Screenshot_20240513_162545_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/130296934/616a1a14-7022-4d8b-b30f-208b3180c9f1)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Google has unified the identifiers for these suggestion sections in the latest version of YouTube.

Therefore, it is not possible to split the settings to hide the suggestion section as before.
