### ISSUE TITLE
suggestion: Change `Default` package name of `Custom package name`

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2007]
### Application

Other

### Suggestion description

For default, it shows "anddea" for both YouTube and YouTube Music.
![Screenshot_20240513_160353_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/127908708/4985d485-8398-4f66-bda4-103a8828cf12)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![0514004631927489](https://github.com/inotia00/ReVanced_Extended/assets/108592928/deb98831-68fc-456e-8625-579d632b5b8b)

Make sure the alternative source is entered correctly

**Comment by Kuddus73** [comment]
> Make sure the alternative source is entered correctly

https://github.com/inotia00/ReVanced_Extended/assets/127908708/71eafd2e-abee-4471-a2f1-f88311990c91

**Comment by inotia00** [comment]
![Options2](https://github.com/inotia00/ReVanced_Extended/assets/108592928/d13d6103-648f-44cc-a68c-891c6e81509c)

Or, you can click the `Reset to defaults` button in the patch options and restart the app
