### ISSUE TITLE
feat(patch): Remove the tooltip content pop ups that appear after reinstalling YouTube.

### ISSUE THREAD

**Issue by bw003** [inotia00/ReVanced_Extended#201]
### Application

YouTube

### Issue

A patch which is important to remove all the irritating quick guide popups blue in colour which appear every time I fresh install YouTube ReVanced.

### Patch

A patch which is important to remove all the irritating quick guide popups blue in colour which appear every time I fresh install YouTube ReVanced.

### Motivation

A patch which is important to remove all the irritating quick guide popups blue in colour which appear every time I fresh install YouTube ReVanced.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by bw003** [comment]
There are a lot of popups and it's true that each one of them shows only one time but it's irritating.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.159.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.1)
