### ISSUE TITLE
feat (YT) : Ability to hide text that are inside three-dot menus.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2010]
### Application

YouTube

### Feature description

There are various three-dot menus located on the top bar throughout the UI. This feature request is to add the ability to hide some/all text from inside them. Screenshots are attached.
![294395454-355c1372-8f27-4d37-a53f-735b2941477b](https://github.com/anddea/revanced-patches/assets/91815107/82b8621c-6edd-4659-bdb4-26239cf6f266)
![294395465-42a865de-86e1-4740-b5d5-7b48a4dcab18](https://github.com/anddea/revanced-patches/assets/91815107/cf3a44c4-979a-4d77-ae75-0769f7dbd86d)
![294395467-85d14f7e-dac6-4216-b268-d3d7b4216a7d](https://github.com/anddea/revanced-patches/assets/91815107/e4cdf8b1-dd05-4c2a-b1aa-3dc048ca54c8)
![294395475-914d0915-08af-4703-bed8-5a4c9aa747ab](https://github.com/anddea/revanced-patches/assets/91815107/716abd7d-82b5-4631-a1b6-25c1eb757a05)
![294395481-0f719659-d0c6-4946-a3d3-66acd649ba94](https://github.com/anddea/revanced-patches/assets/91815107/0b706ef6-e3e6-4c69-b08b-4238e734fb90)

### Motivation

This feature should be implemented because it is a personalization feature & "Customize your app" is written as one of the features of ReVanced patches.

Another reason is:

ReVanced has already removed/hid/improved various annoying stuff of stock YT app. So, why not make it even better by adding this feature?

### Acknowledgements

- [ ] This is not a YouTube feature request.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
It would be better to basically add all Premium promotion UI elements and "Help and support" & "Terms & conditions" elements to be listed in a single post to be requested to be hidden for clean UI. Can you do that?

**Comment by Aryan-Chauhan** [comment]
> It would be better to basically add all Premium promotion UI elements and "Help and support" & "Terms & conditions" elements to be listed in a single post to be requested to be hidden for clean UI. Can you do that?

Everything you said in your comment, can be hidden. But if you provide name and screenshots of UI elements that you don't like on Telegram (@EustaceGideon or RVX Chat), then I can make a single post.
![Screenshot_2024-05-14-14-59-28-80_fe557b5c831afa8eecca413bd340ebe7.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/6f5baa9b-0dae-422c-b368-314e019179d1)
![Screenshot_2024-05-14-15-00-14-70_270755430a2a239778e0eeec997274a1.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/64aa3a2e-1008-41e7-82f3-8e5c1426a0f0)

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2010#issuecomment-2109733648
Dosen't seem like it...
![Screenshot_20240514-193630](https://github.com/inotia00/ReVanced_Extended/assets/107706560/8f09ed70-3772-4ab1-8a5e-6fa66c570354)

**Comment by Aryan-Chauhan** [comment]
Don't know about your first screenshot, because "Discover button" is not accessible for me (because I hid category bar in feed, search results and related videos). Also, Home Tab is hidden for me.

Elements in your second screenshot can be hidden like this:
![Screenshot_2024-05-14-15-10-44-47_fe557b5c831afa8eecca413bd340ebe7.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/211765d6-6431-473c-9fe8-315e3a9128a1)

**Comment by inotia00** [comment]
I don't accept `Feature requests` for YouTube.
Most YouTube layouts rely on the server side, making the feature difficult to implement.

If you want to submit `Feature request` for YouTube, please contact the ReVanced Team.
If you want the feature you implemented to be merged into the repo, please open a Pull request.
