### ISSUE TITLE
feat (YT) : Overlay Button that opens up Captions Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2011]
### Application

YouTube

### Feature description

Please add an overlay button that, when clicked, opens up Captions Menu.
![Screenshot_2024-03-15-08-11-30-72_f22faf49515899f9781ec174a4d85388](https://github.com/anddea/revanced-patches/assets/91815107/5f3640af-1f08-4135-b609-aa7b3a97405a)

### Motivation

• Captions Menu has equal importance to that of Playback Speed Menu, but only the latter has a dedicated overlay button (as of yet).

• It will save steps/taps for opening Captions Menu. Saving steps/taps was also the motivation behind Playback Speed Overlay Button, so Captions Menu should also get equal treatment.

• If implemented, large number of people will use it, just like they use Playback Speed Overlay Button.

• I've personally seen multiple positive comments on how convenient Playback Speed Overlay Button is, and the proposed button is also a convenient & practical one. So, that's why it should be implemented. 

### Acknowledgements

- [ ] This is not a YouTube feature request.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Every video I watch on YouTube, I watch with subtitles enabled (provided they are official subtitles).

So, I open the captions menu a lot.

Because I use it daily multiple times, that's why I requested for it.

**Comment by Rairof** [comment]
Alright. 👍

**Comment by inotia00** [comment]
I don't accept `Feature requests` for YouTube.
Most YouTube layouts rely on the server side, making the feature difficult to implement.

If you want to submit `Feature request` for YouTube, please contact the ReVanced Team.
If you want the feature you implemented to be merged into the repo, please open a Pull request.
