### ISSUE TITLE
feat (YT) : Overlay Button that opens up Quality Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2012]
### Application

YouTube

### Feature description

Please add an overlay button that, when clicked, opens up Quality Menu.
![Screenshot_2024-03-15-08-27-14-60_f22faf49515899f9781ec174a4d85388](https://github.com/anddea/revanced-patches/assets/91815107/e51232e1-3afe-49c4-98c3-d69a8f5298d8)

### Motivation

• Quality Menu has equal importance to that of Playback Speed Menu, but only the latter has a dedicated overlay button (as of yet).

• It will save steps/taps for opening Quality Menu. Saving steps/taps was also the motivation behind Playback Speed Overlay Button, so Quality Menu should also get equal treatment.

• If implemented, large number of people will use it, just like they use Playback Speed Overlay Button.

• I've personally seen multiple positive comments on how convenient Playback Speed Overlay Button is, and the proposed button is also a convenient & practical one. So, that's why it should be implemented.

### Acknowledgements

- [ ] This is not a YouTube feature request.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
Why? Quality option already exists under settings icon..
![Uploading Screenshot_20240514-183222.png…]()

**Comment by Aryan-Chauhan** [comment]
Playback Speed, Copy Link, Download are also accessible from somewhere else, but still they have overlay button.

Because they save time & provides convenience to the user.

Also, 2160p@60fps videos have crazy frame drops on my phone, but 2160p@50fps & below videos play smoothly. So personally, having an overlay button that opens up quality menu is a major convenience for someone in my shoes.

**Comment by Rairof** [comment]
Playback Speed, Copy Link, Download are also accessible from somewhere else, but still they have an overlay button.
- Yea because they're used frequently unlike quality option, save to playlist.
- 
 Because they save time & provides convenience to the user.
- It's just +2 clicks.

Also, 2160p@60fps videos have crazy frame drops on my phone, but 2160p@50fps & below videos play smoothly. So personally, having an overlay button that opens up quality menu is a major convenience for someone in my shoes.
-  ![Screenshot_20240514-183634](https://github.com/inotia00/ReVanced_Extended/assets/107706560/0a2b4a51-e474-4aed-8c62-ea1b88474fcc)

**Comment by Aryan-Chauhan** [comment]
This is a response for your screenshot:

I already know about default video quality.

As I said, 2160p@30fps and 2160p@50fps videos play fine, so I keep default WiFi quality on 2160p.

For 2160p@60fps videos, I manually switch down to 1440p@60fps when they are opened, so they can play smoothly.

This is why I requested for a quality menu overlay button.

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2012#issuecomment-2109698279
Sounds like either your device can't handle 2160p@60fps or it's a device issue

**Comment by Aryan-Chauhan** [comment]
Yes, I'm aware that my phone's processor (SD 720G) can't handle 2160p@60fps on YT app.

**Comment by shreyjain1998** [comment]
@Aryan-Chauhan alternatively, you can goto Player > Seekbar and enable these settings.

![Screenshot_2024-05-14-20-35-09-767_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107779107/c174ab23-7d0c-40a9-b2bd-25e894cdb812)

Then you'll be able to click on timestamp and open quality menu.

**Comment by Aryan-Chauhan** [comment]
> @Aryan-Chauhan alternatively, you can goto Player > Seekbar and enable these settings.
> 
> ![Screenshot_2024-05-14-20-35-09-767_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/107779107/c174ab23-7d0c-40a9-b2bd-25e894cdb812)
> 
> Then you'll be able to click on timestamp and open quality menu.

Thank you for your comment.

I'm aware about these setting, and currently using it too.

But I thought a full-fleged overlay button would be better.

**Comment by inotia00** [comment]
I don't accept `Feature requests` for YouTube.
Most YouTube layouts rely on the server side, making the feature difficult to implement.

If you want to submit `Feature request` for YouTube, please contact the ReVanced Team.
If you want the feature you implemented to be merged into the repo, please open a Pull request.
