### ISSUE TITLE
feat (YT) : Overlay Button that opens up Android's Native Share Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2013]
### Application

YouTube

### Feature description

Please add an overlay button that, when clicked, opens up Android's Native Share Menu.
![Screenshot_2024-03-15-07-46-07-16_c31b32364ce19ca8fcd150a417ecce58](https://github.com/anddea/revanced-patches/assets/91815107/bb38eca3-26fa-494c-852f-cdb6315e7bf3)

### Motivation

• Android's Native Share Menu has equal importance to that of Playback Speed Menu, but only the latter has a dedicated overlay button (as of yet).

• It will save steps/taps for opening Android's Native Share Menu. Saving steps/taps was also the motivation behind Playback Speed Overlay Button, so Android's Native Share Menu should also get equal treatment.
![1710472210920](https://github.com/anddea/revanced-patches/assets/91815107/38a687ab-dd10-41da-9774-89cb188cb13f)

• If implemented, large number of people will use it, just like they use Playback Speed Overlay Button.

• I've personally seen multiple positive comments on how convenient Playback Speed Overlay Button is, and the proposed button is also a convenient & practical one. So, that's why it should be implemented.

### Acknowledgements

- [ ] This is not a YouTube feature request.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
It's a share button... I'm pretty sure it's provides no content viewing improvements on using YouTube (unlike playback speed overlay button) other than just sharing links. Which you can just do fine with the current method. It doesn't need to be efficient.

**Comment by Aryan-Chauhan** [comment]
> It's a share button... I'm pretty sure it's provides no improvements in content viewing or improving user experience when using YouTube (unlike playback speed overlay button) other than just sharing links. Which you can just do fine with the current method. It doesn't need to be efficient.

You just said "unlike playback speed overlay button" and still failed to provide any reason why playback speed should be considered a higher level feature than sharing links.

**Comment by Rairof** [comment]
Didn't knew sharing is as important to be efficient  as watching content. Whatever.👍

**Comment by inotia00** [comment]
I don't accept `Feature requests` for YouTube.
Most YouTube layouts rely on the server side, making the feature difficult to implement.

If you want to submit `Feature request` for YouTube, please contact the ReVanced Team.
If you want the feature you implemented to be merged into the repo, please open a Pull request.
