### ISSUE TITLE
feat (YT) : Swipe Controls that can change Playback Speed.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2015]
### Application

YouTube

### Feature description

Please add the swipe controls feature for playback speed, where swipe-up increases the speed & swipe-down decreases the speed.

### Motivation

• Playback Speed is an equally important parameter when compared to Volume & Brightness, so it should get equal treatment.

• It will save steps/taps for opening Playback Menu. Saving steps/taps was also the motivation behind Brightness & Volume Gesture, so Playback Speed should also get equal treatment.

• If implemented, large number of people will use it.

### Acknowledgements

- [ ] This is not a YouTube feature request.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
• It will save steps/taps for opening Playback Menu. Saving steps/taps was also the motivation behind Brightness & Volume Gesture, so Playback Speed should also get equal treatment.

Same features deserve equal treatment. Different features deserve different treatments. Personally, I think having swipe gestures for quality or playback speed is too niche and really impractical to have and I'd imagine pretty hard to implement.

**Comment by Aryan-Chauhan** [comment]
> • It will save steps/taps for opening Playback Menu. Saving steps/taps was also the motivation behind Brightness & Volume Gesture, so Playback Speed should also get equal treatment.
> 
> Same features deserve equal treatment. Different features deserve different treatments. Personally, I think having swipe gestures for quality or playback speed is too niche and really impractical to have and I'd imagine pretty hard to implement.

I agree that it's kind of niche.

**Comment by inotia00** [comment]
I don't accept `Feature requests` for YouTube.
Most YouTube layouts rely on the server side, making the feature difficult to implement.

If you want to submit `Feature request` for YouTube, please contact the ReVanced Team.
If you want the feature you implemented to be merged into the repo, please open a Pull request.
