### ISSUE TITLE
feat (YT) : Swipe Controls that can change Video Quality.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2016]
### Application

YouTube

### Feature description

Please add the swipe controls feature for video quality, where swipe-up increases the quality & swipe-down decreases the quality.

### Motivation

• Video Quality is an equally important parameter when compared to Volume & Brightness, so it should get equal treatment.

• It will save steps/taps for opening Video Quality Menu. Saving steps/taps was also the motivation behind Brightness & Volume Gesture, so Video Quality should also get equal treatment.

• If implemented, large number of people will use it.

### Acknowledgements

- [ ] This is not a YouTube feature request.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
Very niche feature request. Not sure if your average users would like to frequently quick swap video quality with swipe gestures.

**Comment by Aryan-Chauhan** [comment]
> Very niche feature request. Not sure if your average users would like to frequently quick swap video quality with swipe gestures.

I agree that it's very niche.

**Comment by Aryan-Chauhan** [comment]
Yes, I'm aware about this feature.

Just waiting for inotia00's opinion on this request.

**Comment by inotia00** [comment]
I don't accept `Feature requests` for YouTube.
Most YouTube layouts rely on the server side, making the feature difficult to implement.

If you want to submit `Feature request` for YouTube, please contact the ReVanced Team.
If you want the feature you implemented to be merged into the repo, please open a Pull request.
