### ISSUE TITLE
make volume steps as default (15 steps instead of 150) even if volume gesture enabled

### ISSUE THREAD

**Issue by irishFaraon** [inotia00/ReVanced_Extended#2018]
### Application

YouTube Music

### Feature description

Is there a way to force volume buttons to work the same amount as they do by default in android : from 0-15 (not from 0 to 150), even in yt Fullscreen and volume gesture is enabled .

    when i'm not in Fullscreen mode, volume button has 15 steps from empty to full (like for other apps sound)

My request is to keep button volume like for other apps (from 0 to 15) even in yt fullsceen and gesture enabled or add a specific setting to detach volume steps of buttons from steps of the gesture

A full topic with screen record to explain in the link : https://github.com/anddea/revanced-patches/issues/390

### Motivation

when I enter fullscreen in yt, i have 150 steps from empty to full (like volume gesture) by button clicks (if volume is high while it's night, i'll wake up all the family before I get to decrease volume! Count 150 clicks)

**Comment by inotia00** [comment]
I don't accept `Feature requests` for YouTube.
Most YouTube layouts rely on the server side, making the feature difficult to implement.

If you want to submit `Feature request` for YouTube, please contact the ReVanced Team.
If you want the feature you implemented to be merged into the repo, please open a Pull request.
