### ISSUE TITLE
Add support for Reddit 2024.20.1 for CLI users

### ISSUE THREAD

**Issue by Xisrr1** [inotia00/ReVanced_Extended#2019]
Promoted ads are visible in comments. And there is no RVX settings.

**Comment by inotia00** [comment]
https://github.com/inotia00/revanced-documentation/wiki/Supplement.-Patch-for-latest-Reddit

**Comment by Xisrr1** [comment]
Thanks. It is weird I can patch it with Termux but it fails in Revancify, which also runs in Termux.
