### ISSUE TITLE
Pause button sometimes doesn't work video continues to play

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#202]
### Type

Error at runtime

### Application

Version 18.02.37

### Bug description

I noticed that occasionally a video that I put on pause suddenly continues playback after a few seconds. Please kindly look into it if it's possible. Quite the annoying bug.

### Steps to reproduce

Hard to describe how to reproduce it. It happens sometimes.

### Relevant log output

```shell
.
```

### Device Environment

Android 12, Non-root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
YouTube's bug, not ReVanced Extended's bug

**Comment by anyujinie** [comment]
> YouTube's bug, not ReVanced Extended's bug

But do you know what I mean? Did you experience it too? I never had it happen with stock YT the few times I use it.
