### ISSUE TITLE
Cannot patch with CLI

### ISSUE THREAD

**Issue by Xisrr1** [inotia00/ReVanced_Extended#2020]
![Screenshot_20240515_005000_Termux.jpg](https://github.com/inotia00/ReVanced_Extended/assets/133952156/8daf125f-4901-4908-ba3f-acad8b8649d7)

So I re-tried with the versions you provided but now it doesn't work.

**Comment by inotia00** [comment]
Please provide additional information.

You should provide information about the Cli version, Patches version, Integrations version, and the commands you tried.

**Comment by Xisrr1** [comment]
Integrations- https://github.com/inotia00/revanced-integrations/releases/latest

Patches- https://github.com/inotia00/revanced-patches/releases/tag/v2.174.0-arsclib

CLI- https://github.com/inotia00/revanced-cli/releases/tag/v2.21.2-arsclib

I followed this guide: https://www.reddit.com/r/revancedextended/s/yb85Rj72vc

**Comment by inotia00** [comment]
In the case of arsclib, since it is based on the old version, the cli command is slightly different.

Use the commands included in the [documentation](https://github.com/inotia00/revanced-documentation/wiki/Supplement.-Patch-for-latest-Reddit#using-revanced-cli-pc).

**Comment by Xisrr1** [comment]
Can you please give me the command? Its a bit complicated

**Comment by inotia00** [comment]
```
java -jar cli.jar -a reddit.apk -o revanced -m integrations.apk -b patches.jar
```

Once patched, you will need to move to the `revanced` directory and install `base.apk` manually.

**Comment by Xisrr1** [comment]
Wow, thanks.
What was the point of the `chmod +x aapt2 ; java -jar cli.jar patch -b patches.jar -m integrations.apk --custom-aapt2-binary=./aapt2 -o rvx.apk reddit.apk` in the tutorial on Reddit? It has this aapt2 thing and more code, while the command you sent was much shorter.

**Comment by inotia00** [comment]
aapt2 is not used in arsclib

**Comment by Xisrr1** [comment]
Thank you
