### ISSUE TITLE
bug(YouTube/Shorts components): `Hide shorts shelf` setting does not work

### ISSUE THREAD

**Issue by Sam101011** [inotia00/ReVanced_Extended#2021]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Youtube 19.16.39

### Bug description

Shorts are appearing on the home feed, even when the switch to disable them is toggled on. 
They appear only on the home feed but not on the subscription feed.

Tried with force stop and clear cache but the issue persists.

![Screenshot_20240515_014211_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/90930406/cddd0c9f-f5cb-46b9-851c-6c81b9cbffb9)
![Screenshot_20240515_014225_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/90930406/8337d29c-f5b3-40b9-b522-a5868d62e3a2)

### Device Environment

Android 10
EMUI 12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Are you using `Spoof app version`?

**Comment by Sam101011** [comment]
Yes, I am. I have spoofed to v17.33.42

**Comment by inotia00** [comment]
I can't reproduce it on my side

Try changing `Hide in home feed and related video`, `Hide in subscriptions feed`, `Hide in search results`, and `Hide in watch history` to all on, and let me know the results if the Shorts shelf is still not hidden

**Comment by Sam101011** [comment]
Ok, so I tried with switching "hide in watch history" on and off(it's the only shorts switch that I had off) and that seems to hide shorts in the home feed.

**Comment by inotia00** [comment]
While migrating old RVX settings, it appears that some settings were not maintained properly. (yeah.. there were so many changes in RVX setting)
Please open an issue later if you encounter the same issue again.

**Comment by Sam101011** [comment]
Ok, thank you.
