### ISSUE TITLE
bug (YouTube): mix playlists still present in fullscreen

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#2022]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39 patches 4.8.0-dev 5

### Bug description

With mix playlists turned off in rvx settings, mix playlists are still showing up in fullscreen 

https://github.com/inotia00/ReVanced_Extended/assets/78740080/3ce418e9-60ee-4bb6-86b1-a785307ebc90

### Device Environment

Android 14, pixel 7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Hide mix playlists` setting belongs to the `Feed components` patch.

The intention of the patch is to only hide mix playlists that appear in the feed, so this is not a bug.
