### ISSUE TITLE
bug: Action buttons are not hidden

### ISSUE THREAD

**Issue by akir45** [inotia00/ReVanced_Extended#2023]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patch v dev.5

### Bug description

Even if I hide the action button, it doesn't disappear.
![Screenshot_2024-05-15-23-01-06-105_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/91464996/d0b48c1e-e43a-41c5-b8b2-a2f18f287374)
![Screenshot_2024-05-15-23-00-41-937_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/91464996/7fd96a22-ac8d-4a2e-bf90-ce69724599cf)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by akir45** [comment]
Thank you

**Comment by inotia00** [comment]
To avoid opening duplicate issues,
Keep this issue open until it is merged into the main branch

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)
