### ISSUE TITLE
question: is there any reason to release dev releases?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2025]
### Application

YouTube

### Question description

After your return, you started to release also dev releases

Just out of curiosity, is there any reason?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
So far, my private repository has been taking over the role of the dev branch.
Since I no longer use private repositories, I use the dev branch. That's it
