### ISSUE TITLE
bug: (Player/Action buttons) `Hide Thanks button` patch not working

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2027]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

`Hide Thanks button` patch dosen't hide Thanks button in action button in player section.

### Error logs

```shell
N/A
```

### Solution

Fix relevant patch.

### Additional context

Relevant screenshots-
![Screenshot_20240516-075715](https://github.com/inotia00/ReVanced_Extended/assets/107706560/92c2ef33-ec92-4bdc-91e5-b796deab4e99)
![Screenshot_20240516-075613](https://github.com/inotia00/ReVanced_Extended/assets/107706560/a96e7b3f-01ec-491a-84ac-78408aba5873)

### Device Environment

Android 14, Project Elixir 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2023
