### ISSUE TITLE
suggestion: Change default value of "Hide stats for nerds menu" to disabled

### ISSUE THREAD

**Issue by kitadai31** [inotia00/ReVanced_Extended#2028]
### Application

YouTube

### Suggestion description

The stats for nerds menu is already disabled by default in YouTube settings.
However, "Hide stats for nerds menu" settings in ReVanced Extended settings (Player > Flyout menu) is enabled by default.
Therefore, users who want to see "stats for nerds" have to change not only YouTube settings but also ReVanced Extended settings.

Since the stats for nerds will not be displayed unless the user change YouTube settings, I think it is better to change the default value to didabled.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)
