### ISSUE TITLE
bug: Video quality on shorts video always changed automatically.

### ISSUE THREAD

**Issue by xgangsa** [inotia00/ReVanced_Extended#203]
### Type
#
Error at runtime

### Application

Youtube 18.04.35

### Bug description
latest patches version 2.158.1

My setting was set always on 480p in revanced setting and both mobile and wifi network, higher videos in youtube default setting.

When i playing shorts video, quality always change to higher immediately in fews second after play it.

Also i screenshot before and after quality changed.

### Steps to reproduce

1. Change video setting quality in default app setting.
2. Change video setting in revanced app ans tick keep remembered quality.
3. Play some random shorts videos.
4. Open stats for nerd menu for more info.

### Relevant log output

```shell
-
```

### Screenshots or videos

Default app setting.
![Screenshot_20230131-033749_Trebuchet](https://user-images.githubusercontent.com/17465947/215591390-7784334c-8a8e-4601-a466-b54306f20d54.png)

Revanced video setting.
![Screenshot_20230131-035109_Trebuchet](https://user-images.githubusercontent.com/17465947/215594124-25fb42e0-379c-45ed-aa0b-bdf8e1da536c.png)

Before changed
![Screenshot_20230131-034000_Trebuchet](https://user-images.githubusercontent.com/17465947/215591443-58f7b227-50f8-44ee-9f66-96bf6458425f.png)

And after changed automatically.
![Screenshot_20230131-034014_Trebuchet](https://user-images.githubusercontent.com/17465947/215591565-09370153-31c8-4cb6-baac-1814706a14ac.png)

### Device Environment

Android 11 LineageOS 18.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
shorts players do not support default video quality and default video speed
it is normal
