### ISSUE TITLE
bug: scroll stuck

### ISSUE THREAD

**Issue by Nalmor1** [inotia00/ReVanced_Extended#2030]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39  Patches-v.2.225.0 dev.10 by anddea
  

https://github.com/inotia00/ReVanced_Extended/assets/169981296/480faa47-1bfb-49b3-a322-3a9ac75297ef

### Bug description

appeared precisely on version 19.16.38-39.  Previously, on version 19.11.43 there was no such problem, the scroll seemed to stick and did not allow you to scroll the tape, I show it in the video. Thank you.

### Device Environment

Asus ZenFone 9 android 13 device 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Already fixed on inotia releases. And we don't accept any report related to @anddea fork

**Comment by Nalmor1** [comment]
Thanks
