### ISSUE TITLE
question: 

### ISSUE THREAD

**Issue by Nalmor1** [inotia00/ReVanced_Extended#2031]
### Application

YouTube

### Question 

Hello
 is it possible to add hide some text on the main page?
![Screenshot_20240516-110809_YouTube (1)](https://github.com/inotia00/ReVanced_Extended/assets/169981296/38dd5835-3153-4ad1-947e-9b869874a2b9)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
no, that's not possible
