### ISSUE TITLE
question: loading buffer

### ISSUE THREAD

**Issue by Nalmor1** [inotia00/ReVanced_Extended#2032]
### Application

YouTube

### Question description

Is it possible to add a loading buffer that changes the size so that the video is not interrupted where the Internet signal is weak?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It was possible in the past, but now it is not possible due to server-side changes.
