### ISSUE TITLE
question:  status bar

### ISSUE THREAD

**Issue by Nalmor1** [inotia00/ReVanced_Extended#2033]
### Application

YouTube

### Question description

 hi, is it possible to add a full screen hiding status bar when launching YouTube?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
no it's not possible
