### ISSUE TITLE
suggestion (YT) : Make `Double-tap to seek preferences` an importable & exportable setting.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2034]
### Application

YouTube

### Suggestion description

Hi. Please make "Double-tap to seek preferences" an importable & exportable setting, so that user doesn't have to set it up again when they do a clean installation.

![Screenshot_2024-04-19-21-17-05-64_f22faf49515899f9781ec174a4d85388](https://github.com/anddea/revanced-patches/assets/91815107/b3fb7c11-fcd6-4b54-ba82-c9e847a835ef)

### Motivation

It is an RVX-specific setting, so ideally, it should also be a part of exported `.txt file`.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Like RVX settings, YouTube settings are not saved through SharedPreferences.
So this is impossible.
