### ISSUE TITLE
feat (YT Music) : `Launcher Icon`, `Splash Icon` & `Header Icon` should be same.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2036]
### Application

YouTube Music

### Feature description

In your older patches, all of them used to be same. If user selects MMT icon, then it gets applied automatically to `Launcher Icon`, `Splash Icon` & `Header Icon`.

Kindly bring this behaviour back.

### Motivation

• It was cool & wasn't hurting anybody.

• Currently, when we tap on MMT `Launcher Icon` to open the app, the stock YT Music icon comes up as the `Splash Icon`, which looks very ugly & inconsistent. 

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
