### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Ahmey1400** [inotia00/ReVanced_Extended#2037]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

Yt 19.16.39 v4.8.0-dev.6

### Bug description

(Yt 19.16.34) hide remix button doesnt work
its show up every time

![Screenshot_20240516_172349_RVX Youtube](https://github.com/inotia00/ReVanced_Extended/assets/143447608/2642b819-14b1-4e0f-a2dc-a2fd8d7ee276)
![Screenshot_20240516_172325_RVX Youtube](https://github.com/inotia00/ReVanced_Extended/assets/143447608/5c4d3ba3-f670-4a99-8a5c-1f2842704669)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2023
