### ISSUE TITLE
feat(patch): Remove Join btn from Shorts

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#204]
### Application

YouTube

### Issue

Add a patch or option to remove the Join button from Shorts on Subscribed Channels.

### Patch

Dev can merge this option with "Hide subscription" option. (Or can add it separately).

### Motivation

Improve productivity.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/151
