### ISSUE TITLE
bug(YouTube): ReVanced Extended settings is hidden

### ISSUE THREAD

**Issue by Alxon4789** [inotia00/ReVanced_Extended#2040]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube 19.16.39
Patches version: 4.7.1
Integrations version: 1.8.2

### Bug description
(By way of warning, no, I did not remove them)
Individual settings suddenly disappear. On the screenshots, I was able to show the disappearance of the "Information" section (the settings are in Polish) but just as suddenly the Revanced Extended option disappeared. Repatching does not change anything.
<img src="https://github.com/inotia00/ReVanced_Extended/assets/143010511/84b96316-5c05-4f33-9921-fda19738e1a2" width=50% height=50%><img src="https://github.com/inotia00/ReVanced_Extended/assets/143010511/dfd31b01-93b6-4cb6-b20d-9330ee4f35d5" width=50% height=50%>

### Device Environment

Android 14, AOSPA 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is not reproduced on my side.
Please attach Revancify's patch log.

**Comment by Alxon4789** [comment]
> It is not reproduced on my side. Please attach Revancify's patch log.

[patch_log (2).txt](https://github.com/inotia00/ReVanced_Extended/files/15353965/patch_log.2.txt)

**Comment by inotia00** [comment]
Patch has been applied in the root environment.
Patch was applied normally, but there may be a problem with the mount.
Has the app icon changed properly?

**Comment by Alxon4789** [comment]
> Patch has been applied in the root environment. Patch was applied normally, but there may be a problem with the mount. Has the app icon changed normally?

Everything ok with the icon
<img src="https://github.com/inotia00/ReVanced_Extended/assets/143010511/9d5d45b4-3e9f-444c-a796-843cc61a35fb" width=50% height=50%>

**Comment by inotia00** [comment]
Only 'ReVanced Extended Settings' is missing?
I mean, do patches like hiding ads or hiding navigation buttons still work?

**Comment by inotia00** [comment]
I was unable to reproduce the issue despite testing under the same conditions (same YouTube version, same included patch).
Would you like to try a different patch method?

**Comment by Alxon4789** [comment]
> Only 'ReVanced Extended Settings' is missing? I mean, do patches like hiding ads or hiding navigation buttons still work?

"Revanced Extended" and "Information" are missing (as seen in the video)
At the moment (I think) all patches work correctly



https://github.com/inotia00/ReVanced_Extended/assets/143010511/c92ed8e4-fa76-4693-9f1b-092e03cdaafd

**Comment by Alxon4789** [comment]
> I was unable to reproduce the issue despite testing under the same conditions (same YouTube version, same included patch). Would you like to try a different patch method?

Sure, no problem. RVX Manager can it be?

**Comment by inotia00** [comment]
Yeah try with RVX Manager

**Comment by Alxon4789** [comment]
> Yeah try RVX Manager
Still the same

<img src="https://github.com/inotia00/ReVanced_Extended/assets/143010511/5c28b496-86e1-49d5-a8e6-fb6b989da269" width=40% height=40%>

https://github.com/inotia00/ReVanced_Extended/assets/143010511/068a2979-81fe-437f-b612-4cffe036d750

**Comment by ILoveOpenSourceApplications** [comment]
The settings aren't actually disappearing. The scroll bar glitches out when scrolling. The scroll bar shrinks for some reason as per the video, which somehow makes the app think it's scrolling all the way down and top.

**Comment by Alxon4789** [comment]
> Maybe it's another A/B test from Google I'll leave the issue open in case someone else reports the same issue. Anyway this is really weird..

By some miracle, after x repatch in a row, the button returned and the problems disappeared. As a precaution (thanks to your patches) I added a shortcut to it on the main screen.

Thank you for your work

**Comment by inotia00** [comment]
It's really weird, but I'm glad it's resolved
