### ISSUE TITLE
bug: (Return YouTube Dislikes) count showing in view count

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2041]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

RYD counts sometimes show up in video views as well.
![Screenshot_20240518-004917](https://github.com/inotia00/ReVanced_Extended/assets/107706560/00a7cd99-8898-4ba5-8b2f-61aa9cef5c14)

### Error logs

```shell
N/A
```

### Solution

RYD counts not show up in views counts

### Additional context

It's random so I can't tell how to reproduce this.

### Device Environment

Android 14, Project Elixir 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
If I remember correctly, this bug was already fixed in the latest RVX patch.

Please add the version of revanced-patches you are using.

**Comment by Rairof** [comment]
Okay.
![Screenshot_20240518-011650](https://github.com/inotia00/ReVanced_Extended/assets/107706560/6266e8eb-4233-4dd5-8c55-04a4a88ed456)

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)
