### ISSUE TITLE
bug: (Player/Video description) Video description interactions not working

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2042]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

Video description interactions like Tap & hold to select or tap to scroll dosen't work even when relevant `Disable video description interaction` patch is toggled off.

https://github.com/inotia00/ReVanced_Extended/assets/107706560/9d66be56-91f2-4388-8de8-c3b376f1982a

### Error logs

```shell
N/A
```

### Solution

Fix relevant video description interactions to work.

### Additional context

As seen in the video, holding on links automatically copies them and that works fine. I don't know about the rest of the interactions not working.

### Device Environment

Android 14, Project Elixir 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Since that setting only works for those eligible for A/B tests, it has been classified as an experimental flag.

Experimental flags may not work for everyone or are buggy.
Please do not report bugs where settings specified in the experimental flag do not work

**Comment by inotia00** [comment]
That setting is not a patch to "force enable" it

This patch is only valid for users subject to A/B tests.

This means that your Google account must be subject to A/B tests for this setting to work correctly.

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2042#issuecomment-2117833272
Yes but the relevant experimental patch was still enforced when it's disabled. That's what I was reporting on. It's likely not due to any A/B tests related to my account as it persists when I switch between multiple accounts as well.
