### ISSUE TITLE
bug(Hide layout components): glitch related to `Hide setting menu` setting

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2043]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39 or YouTube Music v7.10.52

### Bug description

> The settings aren't actually disappearing. The scroll bar glitches out when scrolling. The scroll bar shrinks for some reason as per the video, which somehow makes the app think it's scrolling all the way down and top.
(@ILoveOpenSourceApplications in https://github.com/inotia00/ReVanced_Extended/issues/2040#issuecomment-2118031686)

That's what happening to me when certain YouTube settings are hidden.
The scroll bar glitches, making you stop scrolling early without reaching the bottom.
The glitch goes away by exiting and re-entering RVX though, so it's a minor inconvenience, but the glitch can reappear at random times.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I don't think I fully understand
Could you please upload a screenshot or video to supplement the explanation?

**Comment by Kuddus73** [comment]
> I don't think I fully understand
> Could you please upload a screenshot or video to supplement the explanation?



First, the scrolling glitches, making you unable to scroll up and down.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/30bafb3d-db5f-47bd-a23c-00b5e3b0d4de

Second, RVX settings gets hidden, but going to the phone home and re-entering the app makes it reappear.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/c3eebf56-4d8e-428c-b4e5-fcf82143e5ef

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.14.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.2)
