### ISSUE TITLE
suggestion: Theme `seekbar` within `Material You` patch

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2044]
### Application

YouTube

### Suggestion description

Not sure why it's not done yet but since we already have `Custom seekbar colour` patch so I thought it would be great to have it since it seems to be the only part of YouTube that isn't themed by `Material You` patch when using that patch.
![Screenshot_20240518-133202](https://github.com/inotia00/ReVanced_Extended/assets/107706560/74cd022a-e2a3-400f-99fe-49db9c0d9b30)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
1. In the case of YouTube, much of it depends on the server side.
2. I have no plans to customize the theme anymore. If you've implemented it, feel free to open a PR.
