### ISSUE TITLE
bug: (Player/Seekbar) Seekbar in video player remains hidden even when `Hide Seekbar in video player` is toggled off

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2045]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

As said in the title, the Seekbar dosen't remain when the player UI overlay fades away and during playing videos even when `Hide Seekbar in video player` is toggled off.

![Screenshot_20240518-133546](https://github.com/inotia00/ReVanced_Extended/assets/107706560/3beb3d87-bad4-4cc2-a496-d085d7ad362b)

![Screenshot_20240518-133718](https://github.com/inotia00/ReVanced_Extended/assets/107706560/dfa051f6-c101-4370-87dc-4f2f38a22790)

### Error logs

```shell
N/A
```

### Solution

Keep Seekbar in player at all times.

### Additional context

Hopefully this is not some A/B tests. If it is then I don't think I'm that lucky enough to get it on all 3 of my google accounts.

### Device Environment

Android 14, Project Elixir 4.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is stock YouTube behavior, not a bug
