### ISSUE TITLE
suggestion: Enhancement of ReVanced Extended with Test Client Playback Integration

### ISSUE THREAD

**Issue by Abhishek-MTC** [inotia00/ReVanced_Extended#2046]
### Application

YouTube

### Suggestion description

Dear Development Team,

I hope this message finds you well. I wanted to bring to your attention an issue I've encountered with ReVanced Extended related to playback functionality, which appears to be impacted by recent enforcement measures from Google.

Despite exploring various troubleshooting methods, I found a temporary solution by switching to the Test Client, where playback worked flawlessly.
However, the Test Client lacks the comprehensive features and polished GUI of the standard client, particularly for YouTube.

Of particular note, I've observed that when using the same Google account, playback issues were absent on Redmi Note 4 running Android 7 while utilizing kitadai3's YouTube ReVanced. Conversely, on my Samsung M14 running Android 14 and utilizing inotia00's ReVanced, the playback issue persisted until resolved with the Test Client.

I humbly suggest that the development team consider integrating the Test Client's playback functionality into the standard client to ensure a seamless user experience across all platforms.

Thank you for your time and consideration of this matter. Your efforts are greatly appreciated, and I look forward to the continued improvement of ReVanced Extended.

Warm regards,
Abhishek MTC

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
There is already a duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/1954

**Comment by Abhishek-MTC** [comment]
Yeah, fine but could you please give me the Test Client version? That would be helpful for me...

Can we use Newpipe's video extractor?
