### ISSUE TITLE
Custom header change patch

### ISSUE THREAD

**Issue by es419** [inotia00/ReVanced_Extended#2047]
### Application

YouTube 

### Feature description

Would like you to add custom change header patch. This patch change the header of youtube app to whatever we want.
This patch was integrated in rex and original revanced long ago and would like you to add it so i can use your amazing stable patches.

### Motivation

Better look and asthetic for youtube app that differ it from revanced.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2029
