### ISSUE TITLE
bug(YouTube/Return YouTube Dislike): subscribe icon is hidden

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#2048]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.16.39 patches 4.8.0 dev 6

### Bug description

Personalized notification bell not visible anywhere

![Screenshot_20240517-204408](https://github.com/inotia00/ReVanced_Extended/assets/78740080/b4252e63-e37d-4b74-aa03-54f357e3b2c5)
![Screenshot_20240518-213753](https://github.com/inotia00/ReVanced_Extended/assets/78740080/572516d2-5087-4dca-a0d3-eae5cf7fa0de)

And in some cases subscribe button background not visible below player
![Screenshot_20240517-204550](https://github.com/inotia00/ReVanced_Extended/assets/78740080/8c14bcfd-0bbd-4ece-8d92-666908650334)

### Device Environment

Android 14, pixel 7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please disable the settings one by one, and report back which settings are causing the issue.

**Comment by ayushTNM** [comment]
Both flitches disappear when disabling return youtube dislike setting

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)
