### ISSUE TITLE
feat(patch): Add option to subscribe without google account.

### ISSUE THREAD

**Issue by W1zardK1ng** [inotia00/ReVanced_Extended#205]
### Application

YouTube

### Issue

For now to subscribe to any channel we need to use a google account. This is an issue and forces to have a google account to get this feature. This patch should help to subscribe to channels without a google account. 

### Patch

Please add a patch which can allow users to subscribe channels without a google account, this should be something like a rss feed method which is being used by newpipe, libretube etc.

The notifications are sent by the server in the traditional way, but what we are trying to achieve here is a option to have a list of subscriptions (its not the actual subscription)but just a list of channels which the users added in their list and search the server for new videos at a particular interval. it doesn't get instant notifications but it can push us the notification about new videos at the pre set interval or by doing it manually. This is how apps like Newpipe, libretube, freetube are doing the channel subscription without a google account.

### Motivation

Providing subscription without google account will completely eliminate the use of a google id unless someone want to comment and react on videos but still able to track the subscriptions and watch contents easily.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
At least this feature is not supported by YouTube clients, and there is no way to make it support unless Google discloses YouTube's source code
