### ISSUE TITLE
suggestion: hook download button on playlist to external downloader

### ISSUE THREAD

**Issue by NichirinSword** [inotia00/ReVanced_Extended#2050]
### Application

YouTube

### Suggestion description

Hook download button option not working in playlist as download button opens internal download option. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
![IMG_20240607_154824_189](https://github.com/inotia00/ReVanced_Extended/assets/49027005/75cf8524-ac57-4c5b-95fb-31ee2f8927e0)

not sure if this is what you're referring to, I don't have any download button there, must be A/B testing? even removing all the custom filters i have i don't have that

**Comment by Aryan-Chauhan** [comment]
It may be a region-specific thing.

I get download button on almost all playlists.

**Comment by vippium** [comment]
> not sure if this is what you're referring to, I don't have any download button there, must be A/B testing? even removing all the custom filters i have i don't have that
> ps: not spoof client and version has been used.

It is there for me too. Try switching to different account.

**Comment by YT-Advanced** [comment]
In the past I already have a commit for this feature, but idk why it isn't merged into rvx.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1)
