### ISSUE TITLE
suggestion (YouTube/`Hide Shorts shelves`): Rename `Hide shorts shelves` to `Hide Shorts shelves`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2051]
### Application

YouTube

### Suggestion description

Shorts being a category, would be more fit with a capital 'S' in the patch setting and renaming it so would be more appropriate. 

![Screenshot_20240525_202458_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/bdd4bb41-7064-4288-b0bb-781be8c33a5e)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
Welp, I guess it is how it is. Playables are quoted so by YouTube everywhere and hence makes sense to leave it as is. But on a similar note the `Hide shorts shelves` should be changed to `Hide Shorts shelves`.

**Comment by ILoveOpenSourceApplications** [comment]
And this change would make it more consistent with other Shorts patches as well as its own description.

**Comment by inotia00** [comment]
In RVX, all proper nouns, such as `Shorts` and `Clips`, are written in lowercase
In the future, when time permits, I will change this to be written in all capital letters

**Comment by KobeW50** [comment]
I can PR for this

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.8.6-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.6-dev.1)
