### ISSUE TITLE
bug(YouTube/SponsorBlock): pressing Now while manually editing a segment results in an error

### ISSUE THREAD

**Issue by Oleepre** [inotia00/ReVanced_Extended#2053]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches 4.8.0-dev6

### Bug description

 While creating a new SponsorBlock segment, hitting the **"Now"** button when using the manual edit results in "Invalid time given". Using the circular button works fine tho.

 1_ Click the "Create new segment" logo.
 2_ Click the manual edit "Pencil" logo.
 3_ Choose "Start" or "End".
 4_ Hit the "Now" option.
 5_ Error occurs.

 
![Screenshot_20240520_182218_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/137729871/32eed871-7793-40d2-9928-fe7cdd51057a)

 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)
