### ISSUE TITLE
bug: Can't create a new playlist on latest version of Revanced Extended Manager, Patcher, and Music

### ISSUE THREAD

**Issue by destroyer22719** [inotia00/ReVanced_Extended#2054]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

On the latest version, Youtube Music 6.50.1, everything works perfectly but I can't create a new playlist

### Bug description

Create a new playlist, when you click the create a new playlist button, either nothing happens or you get the message "navigation not available"

### Solution

Go to the older version

### Device Environment

Galaxy S23 OneUI 6.1, Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1971
