### ISSUE TITLE
bug(RVX Manager/`Remove unused library`): May remove necessary files from already arm64-v8a arch apks

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2055]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YT Music v6.50.53

### Bug description

Though the recommended version is v6.50.51, I used v6.50.53 as the downloaded apk size was lesser, with .51 having 58MB and the later being 46MB. When using RVX Manager with the `Remove unused library` setting toggled on, it does nothing to .51 version as it should as the apk is already for arm64, but it's removing something from v.53 which causes the app to crash without even opening.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
| RVX Manager | ReVanced Manager|
|--------|--------|
| ![Screenshot_20240522_142031_Settings](https://github.com/inotia00/ReVanced_Extended/assets/117499019/b06050ad-a1e9-48cd-ab9e-6a63d942f527) | ![Screenshot_20240522_142152_Settings](https://github.com/inotia00/ReVanced_Extended/assets/117499019/1230f9a0-8206-434b-bf8e-6250e3d57b3e) |

**Comment by inotia00** [comment]
What is the architecture of the YouTube Music APK you are trying to patch?

![f](https://github.com/inotia00/ReVanced_Extended/assets/108592928/d4038c50-a3c1-4fe8-ad37-b7352b910eb2)

Is it arm64-v8a or armeabi-v7a?

**Comment by ILoveOpenSourceApplications** [comment]
arm64-v8a only.

**Comment by ILoveOpenSourceApplications** [comment]
I think apkmirror listed it wrongly during the release and I downloaded it at the time. Similar to how currently v7.02.51 is having a single file makred as arm64-v8a but I highly doubt it's actually arm64 because of the file size difference.

**Comment by inotia00** [comment]
> Similar to how currently v7.02.51 is having a single file makred as arm64-v8a but I highly doubt it's actually arm64 because of the file size difference.

nvm.. it seems like an issue with APKMirror

**Comment by ILoveOpenSourceApplications** [comment]
> nvm.. it seems like an issue with APKMirror

Yeah. They're listing is wrong. Currently armeabi-v7a is listed as arm64-v8a. So early downloaders will end up with the wrong architecture apks.
