### ISSUE TITLE
suggestion: Please add a patch for Daywise App

### ISSUE THREAD

**Issue by EbinDominic** [inotia00/ReVanced_Extended#2057]
### Application

Other

### Suggestion description

Please add a patch for [Daywise](https://play.google.com/store/apps/details?id=com.synapse.alarm.daywise) Premium 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The RVX Patches only supports three apps: YouTube, YT Music, and Reddit.

If you need added support for other apps, please contact the ReVanced Team:
https://github.com/ReVanced/revanced-patches/issues
