### ISSUE TITLE
suggestion: spoof patches from RV

### ISSUE THREAD

**Issue by Ahmey1400** [inotia00/ReVanced_Extended#2059]
### Application

YouTube

### Suggestion description

Can you add spoof patches from RV such as; spoof sim country, spoof wifi

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The RVX Patches only supports three apps: YouTube, YT Music, and Reddit.
Universal patches such as spoof sim country and spoof wifi are not needed for these three apps.
If you need those patches, just use the original ReVanced Patches.
