### ISSUE TITLE
question: root patching

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#2060]
### Application

YouTube

### Question description

Can i change the youtube custom package name or custom app name in root medhod  ?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
no it is not possible

**Comment by s7san007** [comment]
> custom package name
 
No.

> custom app name

Yes.

My root versions.
![Screenshot_20240525_003101_One UI Home](https://github.com/inotia00/ReVanced_Extended/assets/130248949/e7c513bc-110e-4d3e-80ff-e4fd3e136403)

**Comment by Adity1243** [comment]
Bcus my launcher has dosent changing the icon maybe changing package name will fix the issue but with only change name will works too ?
