### ISSUE TITLE
Why I can't change notifications settings inside my phone settings question: 

### ISSUE THREAD

**Issue by kpro10** [inotia00/ReVanced_Extended#2061]
### Application

YouTube

### Question description

Hi,
Before your comeback and while using other patches except yours, for example rex, anddea, rufusin I was able to change notifications settings inside my phone settings app. But now I am not able to do so. I would like to turn on sound for notifications for videos that come out from subscribed channels. But I can't there isn't an option for notifications categories while as I mentioned before there was such option.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
tbh I don't fully understand this question
Isn't there a notification setting in YouTube settings?

**Comment by kpro10** [comment]
There are but there is also a setting for notifications categories on samsung phones where you can decide for each categories if they are enabled with sound or not or disabled. If you use a rex patched yt apk for example when you go in settings this option is available.

**Comment by inotia00** [comment]
On my side, notification settings like `Mobile search for TV`, `Livestreams`, `Comments and replies` including `Subscriptions` are shown normally.
Can’t you see only the `Subscriptions` category?

**Comment by kpro10** [comment]
My bad one ui 6.1 was the problem. Anyway I found the solution: https://www.reddit.com/r/samsunggalaxy/comments/1abim5s/notifications_categories_is_missing_in_oneui_61/
