### ISSUE TITLE
Pls bring the spoof player parameters patch back suggestion: 

### ISSUE THREAD

**Issue by kpro10** [inotia00/ReVanced_Extended#2062]
### Application

YouTube

### Suggestion description

Hi,

Can you bring spoof player parameters patch back? For an unknown reason on rex and other patches that have it yt works better for me.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please refer to the comment I wrote
https://github.com/inotia00/ReVanced_Extended/issues/1966#issuecomment-2102625739

Google changed the response on the server side, so any invalid playback request that does not contain Droidguard results will receive a response with `the following content is not available on this app`.

Accordingly, most other clients that had solved playback issues in the `ANDROID` client via `Player parameters`, including ReVanced, have also removed this.

**Comment by kpro10** [comment]
I know but for my country they haven't take any steps. So it works better for me.

**Comment by kpro10** [comment]
Ok thanks anyway. Rex patches seem to work for me the best. The only reason I switched to yours is because the first second of shorts in rex played 2-3 times. With that setting on rex I didn't have any issues. While to yours at random times it buffers and I need to wait for 3-10 secs for the video to load.
