### ISSUE TITLE
Hide carousel shelf not hiding continue watching sometimes

### ISSUE THREAD

**Issue by NichirinSword** [inotia00/ReVanced_Extended#2063]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patch v4.8.0-dev6
Integrations v1.9.0-dev5

### Bug description

Continue watching shelf in feed not hiding properly. 

### Device Environment

Galaxy J7 Pro (arm7)
Android 9
One UI 1.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by NichirinSword** [comment]
![Screenshot_20240524-161610_RVX](https://github.com/inotia00/ReVanced_Extended/assets/98078687/653edeb6-456c-4a2a-8b20-21c1746241a4)

**Comment by inotia00** [comment]
The `Hide carousel shelf` setting, as the name of the setting suggests, hides the `horizontally scrollable` shelves.

In the screenshot you attached, it is a 'vertically scrollable' shelf so it will not be hidden.

**Comment by NichirinSword** [comment]
Consider adding a fix for this vertically scrollable issue in your next patch update.

**Comment by inotia00** [comment]
This is a new layout for YouTube, not a bug in RVX.
(This is server-side dependent, so you can't force enable or disable it in an RVX patch)

If you don't want the new layout to apply, just patch the older version.
(e.g. YouTube v18.48.39 or YouTube v19.05.36)
