### ISSUE TITLE
bug: Action buttons are not hidden

### ISSUE THREAD

**Issue by sliceanddice9** [inotia00/ReVanced_Extended#2064]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube APK Version: 19.16.39

### Bug description

The Player Actions buttons like 'download', 'remix', 'thanks' etc, are still showing under videos despite being individually set to "hidden". 

### Device Environment

Android 10: Color OS V7.1/Nova7 Launcher 7.0.57

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2023
