### ISSUE TITLE
suggestion: add setting toggle for `Hide suggested video end screen`

### ISSUE THREAD

**Issue by ANewDawn** [inotia00/ReVanced_Extended#2066]
### Application

YouTube

### Suggestion description

Currently the suggested video at end screen is used with the autoplay option which autoplays the video whereas previous had it hit play button if wanted to play it.

Having it show without auto play be helpful.

Thanks

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
ref: I requested that a new issue be opened as this setting cannot be turned on or off, nor can it be included or excluded.

I aim to reflect this in the next release.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.8.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.4)
