### ISSUE TITLE
bug(YT) : Old seekbar thumbnail doesn't work after 19.16.39

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#2067]
### Type

Error while patching

### Tools used

rvx-builder

### Application

YT 19.20.34

### Bug description

Old seekbar thumbnail no more working in latest supported version.
![Screenshot_2024_0526_171434](https://github.com/inotia00/ReVanced_Extended/assets/93650504/5aa8e8fc-834b-4fa0-af06-939c90bff4f7)

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Read the `Announcement` in the [release note](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.3)

**Comment by Vipin2003** [comment]
Well OK...Just waiting for fixture in coming future.

**Comment by inotia00** [comment]
Google has removed all code related to the `Restore old seekbar thumbnails` setting from YouTube, so it will not be added in the future - unless Google provides the source code.
As mentioned in the Announcement, it has literally been `deprecated`.
