### ISSUE TITLE
feat(patch): Toggle for Remember brightness in fullscreen

### ISSUE THREAD

**Issue by rks2000** [inotia00/ReVanced_Extended#207]
### Application

YouTube

### Issue

Currently there is no toggle for remembering the brightness on/off. I like the orginal revanced like brightness where the brightness is same as potrait mode when going in fullscreen mode

### Patch

Add a toggle enable/ disable for remembering brightness in fullscreen 

### Motivation

Whenever at night i go in fullscreen mode the brightness remembered is always high so i had to turn it down when going from portrait mode to fullscreen mode. So if you can add a toggle for this then it will be easier for both the people who wants this feature and for those who don't.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.159.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.1)
