### ISSUE TITLE
bug: crash when playing normal videos

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [inotia00/ReVanced_Extended#2071]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.20.34

### Bug description

When you play normal videos the app just crash, i've seen the manager logs and it's all fine, looks like is a samsung only problem, because im on samsung with one ui 5.1

### Additional context

It doesn't happen with shorts

### Device Environment

Android 12 One ui 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Since a duplicate issue has already been opened, you can track the issue there: https://github.com/inotia00/ReVanced_Extended/issues/2068, https://github.com/inotia00/ReVanced_Extended/issues/2069

**Comment by soyDESKTOP68A2MRFT** [comment]
I just found that the problematic patch is the video playback patch, just
excluded it and youtube started working again

**Comment by inotia00** [comment]
Thank you for finding the cause of the issue

This issue is not reproduced on my side
If possible, please attach the crash log

**Comment by soyDESKTOP68A2MRFT** [comment]
How?

**Comment by inotia00** [comment]
If you know how to use ADB you can try the following command:
```
adb logcat | findstr AndoridRuntime > logcat.txt
```

**Comment by soyDESKTOP68A2MRFT** [comment]
Thanks for the tip!
