### ISSUE TITLE
bug(YouTube - Spoof Client): Wrong listed spoofing side effects

### ISSUE THREAD

**Issue by n1cKz1** [inotia00/ReVanced_Extended#2072]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube (general)

### Bug description

The following changes should be made on spoof client strings:

Watch history on brand accounts doesn't work only on iOS spoof, works fine on VR spoof. It should be removed from "revanced_spoof_client_summary_on" and instead added to "revanced_spoof_client_use_ios_summary_on".

"Higher video qualities may be missing." on iOS spoof has already been fixed. Only HDR quality isn't available, and that's already listed on general spoof summary.

Video background playback works on live streams, only audio-only background playback doesn't (when you tap headphone icon on pip mode). Also, live streams don't work at all on Android 8.0 and probably below, so something like "Live streams may not play on older devices" should probably be added. (iOS spoof)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
> Watch history on brand accounts doesn't work only on iOS spoof, works fine on VR spoof. It should be removed from "revanced_spoof_client_summary_on" and instead added to "revanced_spoof_client_use_ios_summary_on".

Even if you spoof it with Android VR, Shorts and Clips use the iOS client.
(i.e. Watch history does not work in Shorts and Clips for both Android VR and iOS clients)

> "Higher video qualities may be missing." on iOS spoof has already been fixed.

This depends on your Android version.
Spoofing with the iOS client causes it to use the Android device's media player rather than ExoPlayer.
Certain Android versions support all resolutions, while certain Android versions do not.

**Comment by n1cKz1** [comment]
> Shorts and Clips use the iOS client.

I forgot about that, though it can still be made a little clearer

> This depends on your Android version.

Might wanna add "on older devices" to avoid confusion

**Comment by inotia00** [comment]
> Might wanna add "depending on Android version" to avoid confusion, as for most people higher qualities will most likely be available

Well, I think the sentence 'Higher quality **may** be missing' is enough.

> Video background playback works on live streams, only audio-only background playback doesn't

This part needs to be changed.

> live streams don't work at all on Android 8.0 and probably below, so something like "Live streams may not play on older devices" should probably be added.

This is an issue only for Android 8.0 (API 26)
(The minimum Android version supported by YouTube is Android 8.0)

![exoplayer](https://github.com/inotia00/ReVanced_Extended/assets/108592928/b5b6dde3-63f7-4850-82bb-6341c135408f)

https://developer.android.com/media/media3/exoplayer/supported-formats#progressive-container
