### ISSUE TITLE
bug(YouTube/Disable splash animation): does not work on YouTube v19.17.41+

### ISSUE THREAD

**Issue by kpro10** [inotia00/ReVanced_Extended#2073]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube v.19.20.34

### Bug description

Hi on your latest patches disable splash animation doesn't work, it's broken and it doesn't do anything.

### Error logs

```shell
-
```

### Solution

-

### Additional context

-

### Device Environment

S22u, a14, one ui 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It will be fixed in the next release
Until then, use YouTube v19.16.39

**Comment by kpro10** [comment]
Ok thanks I can leave without it. Also I don't know what you changed but your latest pre release versions didn't work for me, unlike rex and rufusin which work amazingly for me. Now without any spoofing or changing settings or that stuff they started to work.

**Comment by Cast0r-999** [comment]
Mine option to "disable splash animation" are working on the latest version of Youtube and pacthes...

**Comment by kpro10** [comment]
Maybe it's for some people. But the dev confirmed it is an issue anyway.

**Comment by selfmusing** [comment]
> It will be fixed in the next release Until then, use YouTube v19.16.39

It works but in a different way :  https://t.me/revanced_extended_chat/333790

**Comment by inotia00** [comment]
Google added one more instruction to load splash animation in YouTube v19.20.34
This is what causes the patch to behave strangely on YouTube v19.20.34
This will also be fixed in the next release

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.4)

**Comment by kpro10** [comment]
Yes it's fixed thank you really much
