### ISSUE TITLE
bug(YouTube/Hide feed components): community posts are not hidden

### ISSUE THREAD

**Issue by Cast0r-999** [inotia00/ReVanced_Extended#2074]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.20.34
Patches 4.8.3
Integration 1.9.2

### Bug description

Some community post (without image) are not hidden in Subscription feed, even when all options are turned on. 

### Device Environment

Android 10, MIUI 12.0.1 official, non-root. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is not reproduced on my side.
Most likely A/B tests.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.9.2-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2-dev.1)
