### ISSUE TITLE
bug(YouTube/SponsorBlock): "submit a new segment" button doesn't work

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#2075]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.8.3

### Bug description

When I try to submit a new SponsorBlock segment by pressing the "submit new segment" button, nothing happens.

https://github.com/inotia00/ReVanced_Extended/assets/132079771/73af5e36-75cc-4407-9fc9-bef203ec7c89

### Device Environment

Android 14, One UI 6.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by NoMorePizza** [comment]
This happens with YouTube v19.20.34 as well.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.4)
