### ISSUE TITLE
suggestion: disable bottom player gesture

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#2078]
### Application

YouTube

### Suggestion description

the older releases of rvx had a "disable bottom player gestures patch" which prevented portrait fullscreen when swiping down below the video player accidentally. this was a very useful feature for many users but has been removed for some reason now. i request that it be brought back, if possible.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by kpro10** [comment]
This is already in rvx settings in gestures

**Comment by MondayNitro** [comment]
> This is already in rvx settings in swipe controls

is it? ill check
