### ISSUE TITLE
suggestion: compile time patches

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#2081]
### Application

YouTube

### Suggestion description

i suggest grouping together all such patches that work by editing layout xmls under a common patch and allowing the user to pick the individual patches from options,json
this will also make it easier for the user to know that these patches are permanent and dont have a toggle

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Yeah, my goal is to be able to exclude all RVX settings through options.json in the future, even if it's not right now.
