### ISSUE TITLE
After spoof client app broken

### ISSUE THREAD

**Issue by enesinan** [inotia00/ReVanced_Extended#2082]
When I switch spoof client, account specific video suggestion not work at Home, and subscriptions, notications not loading also but videos open now without buffer issues![Screenshot_20240527_100110_RVX.jpg](https://github.com/inotia00/ReVanced_Extended/assets/72499839/8601d0f7-29ba-41d4-9d68-7d5b8099a8ed)

Which version of YouTube are you using?
original youtube 19.16.38
Which version of revanced-patches did you patch with?
4.8.3
Which client did you spoof with?
android 13

**Comment by inotia00** [comment]
You did not write according to the issue template

1. Which version of YouTube are you using?
2. Which version of revanced-patches did you patch with?
3. Which client did you spoof with?

**Comment by enesinan** [comment]
Sorry, I add the versions to comment

**Comment by inotia00** [comment]
> Which client did you spoof with?
> android 13

nah, what I mean is, you would have used `Spoof client`

Please check whether you spoofed with an Android VR client or an iOS client.

**Comment by inotia00** [comment]
I haven't received a reply from you, but I think updating to [revanced-patches-4.8.4](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.4) resolves this issue.

If this issue still occurs in revanced-patches-4.8.4, please open the issue again according to the template.
