### ISSUE TITLE
bug: There is no way to use the automatic subtitle translation feature

### ISSUE THREAD

**Issue by StarsShine11904** [inotia00/ReVanced_Extended#2085]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.20.34
Revanced Patch version: 4.8.3

### Bug description

Can't find option for automatic subtitle translation

### Additional context

![Screenshot_20240527_235725_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/89504980/ada44de8-9721-44c1-87d0-122bcb14e158)

### Device Environment

Device:Samsung A33 5G
Use the system:One UI 6.0
Android version:Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Automatic subtitle translation is not provided even on unpatched YouTube.
I don't think it's a bug in RVX.

**Comment by inotia00** [comment]
![Unpatched_YT png](https://github.com/inotia00/ReVanced_Extended/assets/108592928/852cda88-173d-41fc-945d-c809ad501d09)

On my side, the Automatic subtitle translation does not exist in unpatched YouTube v19.20.34

Tested videoId:
https://youtu.be/12Xh5pK_zQ0
