### ISSUE TITLE
Bug:Video progress bar displays incorrectly

### ISSUE THREAD

**Issue by StarsShine11904** [inotia00/ReVanced_Extended#2088]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.20.34

### Bug description

Just after opening the app, I played a video randomly, and the progress bar did not display correctly. It returned to normal until I picked up the progress bar to watch the clip and then put it down. I think this is a bug.

If this is not a bug, please help me resolve this issue

### Additional context

https://github.com/inotia00/ReVanced_Extended/assets/89504980/ed5370da-b331-4cc1-89ee-0557cda3c318

### Device Environment

One UI 6.0
Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is YouTube's A/B tests, not a bug in RVX.

The only way to bypass YouTube's A/B tests is to use a lower version of YouTube.

Try YouTube v19.05.36.
