### ISSUE TITLE
bug(YouTube/Miniplayer): when the video is minimized, the wrong player ratio is applied

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2089]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39 ~

### Bug description

Step 1 - Include `Miniplayer` patch.
Step 2 - Change `Miniplayer` type to `Modern 1`.
Step 3 - Minimize the video.

Video gets cropped off a bit by the right side when it's minimized.

Referenced issue video-

https://github.com/inotia00/ReVanced_Extended/assets/107706560/8e1bf2ef-8d75-4aff-a431-ca3e5fe59d3b

### Error logs

```shell
N/A
```

### Solution

Set relevant video player ratio to show the full video without any cropping when minimised

### Additional context

This has been happening since I updated from 4.8.0 dev-6 release to 4.8.3 and this issue persists even on latest 4.8.5

### Device Environment

Android 14, Derpfest 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Does this issue still persist?

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/2160

**Comment by Rairof** [comment]
@inotia00 can you also add a bug in there that I encountered while using the new modern player types or should I open a new issue for it?

**Comment by inotia00** [comment]
refer issue https://github.com/inotia00/ReVanced_Extended/issues/2142

**Comment by Rairof** [comment]
Seems like this issue has been fixed in v4.10.1 as the minimised Miniplayer now displays the full video content it it's intended ratio now.
