### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Sarreos** [inotia00/ReVanced_Extended#209]
### Type

Error at runtime

### Application

Tried 18.03.42, 18.03.36 and 18.04.35

### Bug description

Just crashes on startup

### Steps to reproduce

Patch the app with any patch

### Relevant log output

```shell
Will post later when I have access to my PC.
```

### Device Environment

Android 12, Motorola g50

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please add the following description
1. Is it a root build or a non-root build?
2. Which patches were included or excluded

**Comment by Sarreos** [comment]
I got it working through the cli so not really a big deal.

**Comment by Sarreos** [comment]
1. Non root build
2. Pretty much including any patch.

**Comment by Thai2706** [comment]
My case:
[Bug description](https://paste.crdroid.net/dXKqqO)

**Comment by inotia00** [comment]
> My case: [Bug description](https://paste.crdroid.net/dXKqqO)

This is a cli issue
Occurs occasionally for unknown reasons
repatch help fix this issue

**Comment by IsaacHub** [comment]
18.04.35 is keep crashing upon launching, older versions are working fine. 
Samsung A52s OneUI 5.0
Android 13

**Comment by inotia00** [comment]
> 18.04.35 is keep crashing upon launching, older versions are working fine. Samsung A52s OneUI 5.0 Android 13

please upload logcat
