### ISSUE TITLE
bug: After playing a video and pressing pause to return to the home page, the video suddenly resumes playing.

### ISSUE THREAD

**Issue by StarsShine11904** [inotia00/ReVanced_Extended#2090]
### Type

Other

### Tools used

RVX Manager

### Application

Patches for pre-release versions
### Bug description

How to reproduce the problem

1.Click on a random video
2.Press to pause the video and return directly to the homepage
3.The video suddenly continued playing

This seems to be a mistake. If not, please tell me how I should adjust it to avoid this problem.

### Device Environment

Samsung A33 5G
OneUI 6.0
Android 14
No root

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![VR](https://github.com/inotia00/ReVanced_Extended/assets/108592928/bdd0a84b-f72b-4b50-9144-ee026f96c089)

This is a known side effect of the `Client spoof` setting
