### ISSUE TITLE
suggestion:Hope this patch can restore the suggested video ending screen, I need this Function

### ISSUE THREAD

**Issue by StarsShine11904** [inotia00/ReVanced_Extended#2091]
### Application

YouTube

### Suggestion description

I hope that the suggested video end screen can be restored, because I am used to turning off the auto-play switch, but once I turn off the suggested video end screen, it cannot be used. This has caused me trouble. I hope you can add this function back to the patch.
![Screenshot_20240528_092916_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/89504980/8b5075e7-51ec-4cee-8a8a-fae9b70ee73d)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![4-8-5](https://github.com/inotia00/ReVanced_Extended/assets/108592928/a70effaa-b30d-49e0-992f-ed3c96580f5a)

Already restored in [revanced-patches-4.8.5](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.5)

If this setting is not shown, just re-patch
