### ISSUE TITLE
Youtube video goes back one seconds earlier when locking/unlocking the screen

### ISSUE THREAD

**Issue by kdpkke** [inotia00/ReVanced_Extended#2094]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube v19.20.34

### Bug description

I just installed rvx for the first time and everything works fine with the spoof option. The only problem I have with youtube is when i lock the screen, the video stops for 1 second and it resumes from 1 second earlier (the last words of a video are repeated). Same thing happens when i unlock the screen again. Is there a way to solve this?

### Device Environment

Motorola edge 40 pro with android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2090
