### ISSUE TITLE
Automatic video resuming when device is turned off whit spoof client on

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#2095]
### Type

Other

### Tools used

Revancify

### Application

YouTube 19.20.34

### Bug description

https://github.com/anddea/revanced-patches/issues/538#issue-2320214331

### Device Environment

Android 13 miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2090
