### ISSUE TITLE
Bug: (YouTube): Errors with the player

### ISSUE THREAD

**Issue by Kevinr99089** [inotia00/ReVanced_Extended#2096]
### Type

Other

### Tools used

rvx-builder

### Application

YouTube V19.20.34, YouTube V19.16.39

### Bug description

2 bugs found

1. When the video is paused, playback can resume automatically, randomly (When you return to the home menu (device) or when the device is in standby mode)
2. Sliding gestures doesn't work/not correctly (to bring video to full screen or for exit full screen)  (When the first video is played (since the application was launched) or when playing the following video from end card screen, suggested video or countdown to auto-play) [Here is a Mega link to the video](https://mega.nz/file/GWwQFAzb#gpmrycVJvZJrG2Ep_DxH8HUjq2OXKHoiutepN34Nc0g)

### Error logs

```shell
No crashing
```

### Solution

1. Re-Pause/close application
2. Closing the player and restarting a video (from home page, subscription or a channel)

### Additional context

- I've tried deleting the data, uninstalling the application and repatching it, but the bug is still there.
- I even tried the patches on a slightly older version, same problem.
- However, I won't be able to tell which patch is causing this bug.

- Here are the patches applied 
[YouTube (Extended) v19.20.34.txt](https://github.com/inotia00/ReVanced_Extended/files/15468009/YouTube.Extended.v19.20.34.txt)

### Device Environment

Tested on 2 devices: 
- Samsung Galaxy S23 SM-S911B/DS, OneUI 6.1, Android 14, no-root
- Samsung Galaxy Tab S9 SM-X710, OneUI 6.1, Android 14, no-root

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2090

**Comment by Kevinr99089** [comment]
> duplicated with #2090

This isn't the only bug, and spoof client to IOS isn't enabled for me.

**Comment by inotia00** [comment]
This is a side effect that is only reproduced when the `Spoof to iOS` setting is **disabled**

Enable the `Spoof to iOS` setting

**Comment by Kevinr99089** [comment]
> This is a side effect when the `Spoof to iOS` setting is **disabled**
> 
> Enable the `Spoof to iOS` setting

Ahh, okay, I didn't get that. Thanks
