### ISSUE TITLE
Feature: Add a 'disable swipe to next/previous song' in the player and miniplayer

### ISSUE THREAD

**Issue by Xisrr1** [inotia00/ReVanced_Extended#2097]
### Application

YouTube Music

### Feature description

A patch that will add 2 options, one to disable the swipe left/right on the music player, and the second to disable the swipe option fir the mini player. 
![Screenshot_20240529_033040_YouTube Music](https://github.com/inotia00/ReVanced_Extended/assets/133952156/08e3978b-2074-4f27-8160-07c6f845622b)

### Motivation

It is very annoying and common to accidentally swipe, as it is very sensitive. 

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1)
