### ISSUE TITLE
question: inotia00, do you have any interest in making the `Spoof client` patch compatible with Relay v11.0.19 ?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2098]
### Application

Other

### Question description

Just wanted to ask this.

Relevant issue on ReVanced repository:

https://github.com/ReVanced/revanced-patches/issues/2532

Thanks!

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
No I don't use 'Relay For Reddit'
I don't want to reverse engineer an app I'm not using
Just wait for the team to find a workaround
