### ISSUE TITLE
bug(YouTube/Settings): `CairoSettings` causes RVX settings to be hidden

### ISSUE THREAD

**Issue by TidalMist** [inotia00/ReVanced_Extended#2099]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube 19.20.34

### Bug description

![IMG_20240530_083425](https://github.com/inotia00/ReVanced_Extended/assets/91356643/e51c3cd6-ab79-4c47-9583-f895ace179d2)

### Additional context

New YouTube settings UI with outline icons. A/B test? Patches 4.8.5
Developer preferences not pressed and not scroll down
### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`CairoSettings` was released on the server side sooner than I expected (A/B tests)
I will force disabling `CairoSettings` in the next release (just like uYouPlus did)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.8.6-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.6-dev.1)

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.6](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.6)
