### ISSUE TITLE
feat(patch): Skip silences during playback

### ISSUE THREAD

**Issue by suddenlydoomy** [inotia00/ReVanced_Extended#210]
### Application

YouTube

### Issue

Many YouTube videos, especially podcast episodes, include silences and other dead time that make the video unnecessarily long.  NewPipe has functionality to skip these silences while playing YouTube videos.

### Patch

A patch to algorithmically detect and skip silences in a video. NewPipe does this, as does Google Podcasts for Android.

### Motivation

Think of the impact if this patch is successfully implemented -- thousands of users getting hours of their lives back while still viewing the content they want to view and rewarding creators.

To be clear, this is not SponsorBlock.  SponsorBlock crowdsources recommendations of video segments to skip.  The proposed patch would monitor actual audio levels(?) and compare them against some kind of threshold(?) and then skip ahead through silences.  (I honestly don't know how this works.  I'm hoping you can just copy whatever NewPipe does.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.

**Comment by Registrar7317** [comment]
Can you please open the issue as maybe someone someday might see the issue and work on it?
