### ISSUE TITLE
bug(YouTube/Settings): some settings cannot be changed

### ISSUE THREAD

**Issue by fredrik1102** [inotia00/ReVanced_Extended#2100]
### Type

Error at runtime

### Tools used

CLI

### Application

integrations-1.9.4-dev.1.apk
patches-4.8.6-dev.1
YouTube 19.16.39 / YouTube 19.20.34

### Bug description

Settings > ReVanced Extended > Player > **Opacity value between 0-100, where 0 is transperant.**

**and**

Settings > ReVanced Extended > Player > **Speed overlay valuebetween 0-8.0**

Does not save its values and therefore does not work.

![rvx](https://github.com/inotia00/ReVanced_Extended/assets/74833943/52c958dc-c6aa-4224-8703-72ae8db04ac6)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Thank you for your inquiry.
In the process of refactoring RVX settings, some setting keys were missing.
This appears to be a fairly serious issue, so I will prepare a patch asap.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.8.6](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.6)
