### ISSUE TITLE
suggestion(YouTube/Description components): separate the `Hide Key concepts section` setting from the `Hide Chapters section` setting

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2102]
### Application

YouTube

### Suggestion description

`Hide Chapters Sections` can hide both Chapters Section as well as Key Concepts.

So, it is requested to either do 1 or 2:

1. Make a new setting called as `Hide Key Concepts`.

2. Rename `Hide Chapters Sections` to `Hide Chapters Sections & Key Concepts`.

Example videos:

https://youtu.be/zgdMhNnNuY0

https://youtu.be/86VUqcXo8Sc

Thank you!

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Key Concepts` are not visible in my side. Are these A/B tests?

**Comment by Aryan-Chauhan** [comment]
I've been seeing them for over an year.
![Screenshot_2024-05-31-16-25-00-23_fe557b5c831afa8eecca413bd340ebe7.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/fdec2cdd-649f-4020-bc56-06fc2564f77a)
![Screenshot_2024-05-31-16-25-38-55_fe557b5c831afa8eecca413bd340ebe7.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/d8a91fc7-326d-4b36-adc2-fa6d7ab1cef1)

**Comment by Aryan-Chauhan** [comment]
`macro_markers_carousel$learning_concept`

This custom filter can hide Key Concepts.

Credits: https://github.com/anddea/revanced-patches/issues/552#issuecomment-2143382489

**Comment by ILoveOpenSourceApplications** [comment]
> `^macro_markers_carousel$learning_concept`

The problem is `hide chapters section` uses `macro_makers_carousel` and hence toggling it on will still hide both sections. The above quoted component can only be useful if the user requires one but not the other.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
