### ISSUE TITLE
suggestion: "Hide mix playlists" option should hide mix playlists in related videos overlay too.

### ISSUE THREAD

**Issue by Pikasatupu75** [inotia00/ReVanced_Extended#2105]
### Application

YouTube

### Suggestion description

I am suggesting that when the "Hide mix playlists" option is activated in the feed options, that the mix playlists in related videos overlay are hidden too. Since I think feed and related videos overlay are supposed to show the same list of videos, hiding mix playlists in related videos overlay as well would add consistency to the app.

Related videos overlay
![Screenshot_20240531-011422_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/126986435/70caf58b-e11e-4cd3-91e8-2165551c4943)

Feed
![20240531_011927](https://github.com/inotia00/ReVanced_Extended/assets/126986435/fba65e1b-ea51-4b8e-9578-9820365a44f0)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Hide mix playlists` setting belongs to the `Feed components` patch
As intended by the patch, the `Hide mix playlists` setting properly hides the mix playlists shown in the feed https://github.com/inotia00/ReVanced_Extended/issues/2022

The screenshot you attached is `Related video overlay`
And settings such as `Hide mix playlists in related video overlay` are not implemented
