### ISSUE TITLE
feat (YT Music) : `Settings Menu Filter` for RVX YT Music.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2107]
### Application

YouTube Music

### Feature description

Ability to hide the following.
![Screenshot_2024-06-01-00-07-35-73_270755430a2a239778e0eeec997274a1](https://github.com/inotia00/ReVanced_Extended/assets/91815107/8116ac23-f590-4f20-a9b9-de8b7acf4336)

### Motivation

They do not contain anything useful or worth-changing, so ability to hide them would be appreciated.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/1899
