### ISSUE TITLE
suggestion: separate `Hide videos with low views` setting

### ISSUE THREAD

**Issue by Cast0r-999** [inotia00/ReVanced_Extended#2108]
### Application

YouTube

### Suggestion description

That would be awesome, if you separate filtering "People also watched this in search results" from other filtering variants.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Want to hide videos with the label `People also watched this video` from search results only?
Or you want videos with the label `People also watched this video` hidden from your home feed, related videos, and search results?

I think the explanation of the suggestion is a bit lacking

**Comment by Cast0r-999** [comment]
Only from search results. I never encountered "People also watched this video" in home or related feeds on my [account/country/region]. If this is too complicated, then simply add option to hide it from every feed.

**Comment by inotia00** [comment]
Already added `Hide recommended videos` in revanced-patches-4.7.1

You can turn it off or on in the following path:
```
Settings - ReVanced Extended - Feed - Video filter - Hide recommended videos
```
Is it different from this?

**Comment by Cast0r-999** [comment]
I know all of this, that's what i talking about. This option filter 3 type of videos: "Videos with less than 1000 views" + "Only for Membership" + "People also watched". I want to hide only "People also watched" from search results.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1-dev.1)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
