### ISSUE TITLE
suggestion: Thanks Button

### ISSUE THREAD

**Issue by zerozero0022** [inotia00/ReVanced_Extended#2109]
### Application

YouTube

### Suggestion description

https://github.com/ReVanced/revanced-patches/commit/89c154861c8b3afa665542e97ff201c3e84410b2

Can you divide 'Hide Thanks button' into 'Hide Thanks Button (Action Button , Existed Setting), 'Hide Thanks Button (Comment Section, Existed Setting)', and 'Hide 'Buy Super Thanks' Button' (Shorts Player, No Existed Setting, The button above the information (location, tagged product...))'?

It seems like I can hide 'buy super thanks' button by with one of the two existing settings.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I thought I merged all commits, but missed this one
Thanks anyway

**Comment by zerozero0022** [comment]
++ https://github.com/ReVanced/revanced-integrations/commit/303754c46f6d3471405d67b7911065fc3a87f721

thanks

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1-dev.1)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
