### ISSUE TITLE
bug: shorts player in tablet mode

### ISSUE THREAD

**Issue by Pendragon55555** [inotia00/ReVanced_Extended#211]
### Type

Cosmetic

### Application

Youtube 18.04.35, Patches 2.158.1

### Bug description

Tablet mode on phone no longer works with the shorts player (tablet mode used to zoom out shorts/add black bars), like in older versions of Revanced Extended

### Steps to reproduce

Step 1. Turn on tablet mode in the extended settings on a phone.

### Relevant log output

```shell
NA
```

### Device Environment

Androiid 13, OneUI 5.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Do not report issues from experimental flags
