### ISSUE TITLE
bug: Navigation buttons disappear after coming back from a short

### ISSUE THREAD

**Issue by Lanzheim** [inotia00/ReVanced_Extended#2110]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.20.34
Patches 4.8.6

### Bug description

If the option to hide navigation buttons in the short section is enabled it makes the nav bittons to disappear when returning from the short to the main feed. They can be brought back either by pressing the search icon or entering a regular video and going back. But the navigation buttons should show up after returning from any video, short or not.

Just found out that the nav buttons also come back if "playback on feed" is enabled and the preview of a video starts playing and you scroll down, there the buttons come back. 
![Screenshot_20240531_233557_RVX](https://github.com/inotia00/ReVanced_Extended/assets/33710966/b944db69-755d-43e2-9166-d4e6a2877715)

### Device Environment

Galaxy S24 ultra, Android 14, OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/1957
