### ISSUE TITLE
bug: (YouTube/Feed): `Hide carousel shelf` not hiding relevant feeds properly

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2111]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.20.34

### Bug description

`Hide carousel shelf` patch hiding the relevant `Watch it again` or `Continue watching` (not sure which one it is) isn't working anymore and shows them in feed.

![Screenshot_20240601-230719_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/107706560/4ff4b3bb-8570-406a-91c3-df5e5f426fb7)

### Error logs

```shell
N/A
```

### Solution

Fix relevant patch

### Additional context

Maybe it's a new type of feed container that just recently released. I don't know but I can reload the page and it goes away but at random times it comes back

### Device Environment

Android 14, Lineage OS 21

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2063#issuecomment-2129536467

**Comment by inotia00** [comment]
btw I tried hiding this shelf but it doesn't seem easy

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2111#issuecomment-2143451118
Its alright, thank you for trying, its not a big issue and can be resolved with a refresh so thanks for trying!
