### ISSUE TITLE
bug(YT & YTM) - "Open GMSCore" button doesn't support forked GMSCore(s)

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#2112]
### Type

Other

### Tools used

rvx-builder

### Application

GMSCore forks

### Bug description

"Open GMSCore" doesn't support or open any of the forked GMSCore. It only support official from revanced. As we know that revanced GMSCore doesn't support hiding from launcher. Due to which many people like me use the rufusin GMSCore as he only added support for hide from launcher.

So, the option should open forked GMSCore(s) from ReX and rufusin too.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Vipin2003** [comment]
The same feature (previously) for Microg works well with all the types of Microg. GMSCore option should also be compatible with every GMSCore.

**Comment by YT-Advanced** [comment]
Uhm I can still open my own GMSCore via RVX Settings ._.

**Comment by inotia00** [comment]
I tested it a while ago, and it doesn't seem to be an issue with RVX

While implementing the feature to remove icons from the launcher, it appears that a certain class `org.microg.gms.ui.SettingsActivity` has been removed
(It appears that the fork does not reflect the latest GmsCore changes)

I built the GmsCore fork locally, which does not have the feature to remove the icon from the launcher, and it worked normally

Just ask them to fix this in GmsCore fork

**Comment by Vipin2003** [comment]
Umm... That's the reason. Well OK, I'll ask him to update it.
