### ISSUE TITLE
bug: (YT) Autoplay Preview Container isn't hidden

### ISSUE THREAD

**Issue by Francesco146** [inotia00/ReVanced_Extended#2113]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v19.20.34

### Bug description

Fullscreen > autoplay preview container is enabled

this is surely A/B testing because it appeared minutes ago. it has always been hidden until now.

![IMG_20240601_230726_165](https://github.com/inotia00/ReVanced_Extended/assets/49027005/45e81bea-762b-4ee1-8dc3-6b16fe717275)

I've used recommended patches.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
I'll provide protobuff logs in a few days

**Comment by inotia00** [comment]
`Hide autoplay preview container` setting hides this:

![hide-autoplay-preview](https://github.com/inotia00/ReVanced_Extended/assets/108592928/d8a9b9f7-4628-4ad3-ad9e-9a84f7c44c4d)

The setting to hide `More videos` was `Hide related videos in quick actions`, and in the latest patch it has been integrated into the `Hide related video overlay` setting
