### ISSUE TITLE
feat(Reddit): add `Hide Related communities` patch

### ISSUE THREAD

**Issue by sliceanddice9** [inotia00/ReVanced_Extended#2114]
### Application

Reddit

### Feature description

Remove the annoying 'Related Communities' on the 2024.17.0 version of the Reddit APK that appears when scrolling within subreddits.

### Motivation

The 'Related Communities' section is an ad in itself. It appears in the 2024.17.0 version of the Reddit APK.. It would be great to see a toggle under **Settings > ReVanced Extended** that disables 'Related Communities' from showing in the feed. 
![Screenshot_2024-06-02-08-46-36-47_b72a20be883aec8a014bd2b7c7038e87~2](https://github.com/inotia00/ReVanced_Extended/assets/59092472/25166753-15f8-4142-a8ac-f7d64f2be24d)

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by sliceanddice9** [comment]
I believe the 2024.17.0 version is the last Reddit APK that can be patched with ReVanced/RVX Manager. If **'Remove 'Related Communities'** can be patch updated in ReVanced/RVX Manager using the 2024.17.0 version then that'd be just fine.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)

**Comment by sliceanddice9** [comment]
> reflected in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)

Thanks man. You are the best.
