### ISSUE TITLE
bug(YouTube/Spoof client): selective spoofing always uses "Shorts, Clips" client (except when moving to another video)

### ISSUE THREAD

**Issue by kitadai31** [inotia00/ReVanced_Extended#2116]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.20.34

### Bug description

If I open a video or live stream when no video is playing, the "Shorts, Clips" client will always be used.
The correct client will only be used if I open another video while a video is playing.

~~However, it seems that if the Shorts shelves has never been displayed on the screen since launching YouTube, the correct client will be used once.~~ EDITED: This doesn't matter

https://github.com/inotia00/ReVanced_Extended/assets/90122968/e0225022-ccb3-48b3-bb15-f4ff6605c6f4

### Additional context

When the wrong client is applied, the LiveStreamRendererRequester logs like this are not shown.

```
D/Extended: LiveStreamRendererRequester: Request took: 104ms
D/Extended: LiveStreamRendererRequester: Parsing liveStreamRenderer from response: {"playabilityStatus":{"status":"OK"},"videoDetails":{}}
D/Extended: LiveStreamRendererRequester: Failed to get videoDetails for response: {"playabilityStatus":{"status":"OK"},"videoDetails":{}}
D/Extended: LiveStreamRendererRequester: Fetched: LiveStreamRenderer{videoId=KSsMG1uzEYA, client=ANDROID_VR, playabilityOk=true, isLive=false}
```

### Device Environment

Android 11 Google Pixel 3
Android 7.1.1 Fujitsu arrows M04

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I think it has something to do with the Shorts shelf in the feed
Could you please turn off 'Autoplay in feed' and test again and let me know?
I can't use my phone right now

**Comment by kitadai31** [comment]
Autoplay in feed is already turned off

But if I turned on it, this issue was mitigated
The correct client is used more often

**Comment by kitadai31** [comment]
It is caused by these lines.

https://github.com/inotia00/revanced-integrations/blob/3ff66969568e7afc22bcdbdabe2ae7a3af106b38/app/src/main/java/app/revanced/integrations/youtube/patches/misc/SpoofClientPatch.java#L223-L225

I added a logging code in there and found that the PlayerType checking code was being called before the PlayerType changed.

```
06-04 17:05:23.973 D/Extended: SpoofClientPatch( 7911): [playerParameterIsClipsOrShorts] isNoneOrHidden() is true.
06-04 17:05:23.974 D/Extended: SpoofClientPatch( 7911): [playerParameterIsClipsOrShorts] isNoneOrHidden() is true.
06-04 17:05:23.985 D/Extended: PlayerType( 7911): PlayerType changed to: WATCH_WHILE_SLIDING_MINIMIZED_MAXIMIZED
```

Therefore, `playerParameterIsClipsOrShorts()` always returns true when cold start the videos.

Removing the PlayerType checking code solves this issue.
(Just checking player parameters is enough, right?)

P.S. It did not matter whether the short shelf was displayed on the screen or not.
When playing a video for the first time after launching YouTube, the PlayerType seems to change a little early.

```
06-04 17:26:57.119 D/Extended: SpoofClientPatch(15396): [playerParameterIsClipsOrShorts] isNoneOrHidden() is true.
06-04 17:26:57.125 D/Extended: PlayerType(15396): PlayerType changed to: WATCH_WHILE_MAXIMIZED
06-04 17:26:57.135 D/Extended: SpoofClientPatch(15396): [playerParameterIsClipsOrShorts] isNoneOrHidden() is false.
```

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1-dev.1)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
