### ISSUE TITLE
feat:  patch to change the YouTube log when app is opened

### ISSUE THREAD

**Issue by Pravir46** [inotia00/ReVanced_Extended#2117]
### Application

YouTube Music

### Feature description

Is it possible for you to make a patch for changing the YouTube logo which appears when the app is opened 

### Motivation

It might look much better 

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in https://github.com/inotia00/revanced-patches/pull/55
