### ISSUE TITLE
suggestion: Pin important repositories in your GitHub profile

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2118]
### Application

Other

### Suggestion description

**Issue**

Currently, the following 6 repositories are on the homepage of your GitHub profile:

![image](https://github.com/inotia00/ReVanced_Extended/assets/84587632/c2cc571c-3d90-43a1-a881-6c9af935e6e5)

These are not ideal, since Vanced MicroG and mmicrog are not in use.

**Solution**

Curate the shown repositories by pinning the ones you want to show.

![Screenshot 2024-06-04 002857](https://github.com/inotia00/ReVanced_Extended/assets/84587632/6d589c47-31f5-45c6-a980-427ed9ad204d)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It was really useful information for me
