### ISSUE TITLE
bug(YouTube/`Hide Visit store button`): The 'Visit store' button on channel profile isn't hidden

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2121]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.19.39

### Bug description

`Hide 'Visit store' button` isn't working. 
![Screenshot_20240605_192319_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/676a2ca7-f3b6-4d83-b830-a49240490739)

### Solution

Adding the litho component: `^channel_profile.eml$header_store_button` in custom filter seems to work.
```kotlin
04-21 18:08:29.982 11186 11186 D revanced: LithoFilterPatch: Searching ID: null Path: channel_profile.eml|fe7264abae464c88|channel_profile_phone.eml|4a5e3ed8b99b52ed|ContainerType|channel_action_buttons_phone.eml|93f701b73481db51|ContainerType|button.eml|e4d01425197b9e68|ContainerType| BufferStrings: Visit storeΓ¥Ösans-serifΓ¥Öeml.header_store_buttonΓ¥ÖUCV6mNrW8CrmWtcxWfQXy11gΓ¥Ö8gYEEgIqAA%3D%3D"Γ¥Ö/@DarkViperAUΓ¥Ö
04-21 18:08:29.982 11186 11186 D revanced: LithoFilterPatch: Searching ID: null Path: channel_profile.eml|fe7264abae464c88|channel_profile_phone.eml|4a5e3ed8b99b52ed|ContainerType|channel_action_buttons_phone.eml|93f701b73481db51|ContainerType|button.eml|e4d01425197b9e68|ContainerType|TextType| BufferStrings: Visit storeΓ¥Ösans-serifΓ¥Öeml.header_store_buttonΓ¥ÖUCV6mNrW8CrmWtcxWfQXy11gΓ¥Ö8gYEEgIqAA%3D%3D"Γ¥Ö/@DarkViperAUΓ¥Ö
``` 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
Commits:
https://github.com/ReVanced/revanced-patches/pull/3077/commits/04ea9c39dd91a2be0ca90a09a85b22be28a5ff4e
https://github.com/ReVanced/revanced-integrations/pull/622/commits/801ec76cd2751412f636a32314bcaed4074dcb62

**Comment by KobeW50** [comment]
This was fixed in patches 4.8.6

![Screenshot_20240605_103414_YT Extended.png](https://github.com/inotia00/ReVanced_Extended/assets/84587632/91a5b6c4-50f2-4c7b-a2d1-288878f964b1)

**Comment by ILoveOpenSourceApplications** [comment]
I hadn't updated to 4.8.6 since the changelogs didn't have that many changes that interested me and this wasn't mentioned either. Looks like it was fixed. Closing this then.

**Comment by ILoveOpenSourceApplications** [comment]
On an unrelated note, the method which is used to hide the individual tabs on the channel profile, is it a complex method or is it something simple?

**Comment by KobeW50** [comment]
I it helps, I think this is the relavent code.

Patch: https://github.com/inotia00/revanced-patches/blob/revanced-extended/src%2Fmain%2Fkotlin%2Fapp%2Frevanced%2Fpatches%2Fyoutube%2Ffeed%2Fcomponents%2FFeedComponentsPatch.kt#L244-L284

Integrations: https://github.com/inotia00/revanced-integrations/blob/revanced-extended/app%2Fsrc%2Fmain%2Fjava%2Fapp%2Frevanced%2Fintegrations%2Fyoutube%2Fpatches%2Ffeed%2FFeedPatch.java#L36-L61

**Comment by ILoveOpenSourceApplications** [comment]
Also @KobeW50, shouldn't it be `'Visit store'`?

**Comment by ILoveOpenSourceApplications** [comment]
The patch was renamed, but the button isn't hidden for me.

**Comment by KobeW50** [comment]
> Also @KobeW50, shouldn't it be `'Visit store'`?

I'm not sure. Based off of [this comment](https://github.com/inotia00/revanced-patches/pull/53#discussion_r1616706602) and the third commit in [this PR](https://github.com/inotia00/revanced-integrations/pull/42) I would assume that it shouldn't have single quotes. This is why I made [this commit](https://github.com/inotia00/revanced-patches/commit/198eabfa378e5ac636c01d6b3b531d6d3be4d158) to revert many of the single-quotes that added earlier in the PR.

I'm not sure if the stuff that has single-quotes in Revanced is meant to have them in RVX (eg: `Hide 'For you' shelf`)

**Comment by ILoveOpenSourceApplications** [comment]
Single word components are so far the ones which use a first letter capitalize method. If it's a two word component, I think the quotation is used to indicate that both the word is part of the component.

**Comment by ILoveOpenSourceApplications** [comment]
Examples: `'For you', 'Notify me'`, and now `'Visit store'`.

**Comment by KobeW50** [comment]
> Single word components are so far the ones which use a first letter capitalize method. If it's a two word component, I think the quotation is used to indicate that both the word is part of the component. 

> Examples: `'For you', 'Notify me'`, and now `'Visit store'`.

It makes sense, but I understand why it isn't desirable to have quotes. It makes the settings look cluttered, and the sentences aren't truly ambiguous without them.

For example, in the title `Hide Playback speed menu`, it is obvious that "speed" must be connected to "Playback", and that "menu" is separate and not part of the proper noun.

Regardless of the convention, it should always be consistent. So either every multi-word proper noun has quotes, or none should have quotes.

**Comment by ILoveOpenSourceApplications** [comment]
> Regardless of the convention, it should always be consistent. So either every multi-word proper noun has quotes, or none should have quotes.

Yes. This is a decision that needs to be made by @inotia00.

**Comment by rocholojavinar** [comment]
![](https://img.youtube.com/vi/T866AS3mB9M/maxresdefault.jpg)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1-dev.1)

**Comment by ILoveOpenSourceApplications** [comment]
It's still not hidden.

**Comment by inotia00** [comment]
It works for me

**Comment by ILoveOpenSourceApplications** [comment]
<details><summary>Video</summary>
<p>


https://github.com/inotia00/ReVanced_Extended/assets/117499019/bcdd4fd7-a91d-4416-ba82-2b46c513c5c5



</p>
</details>

**Comment by ILoveOpenSourceApplications** [comment]
I'll do a litho check again. Even when adding `^channel_profile.eml$header_store_button` to custom filters, the button isn't hidden for me.

**Comment by inotia00** [comment]
If so, the path would have changed

Attach an Extended debug logging, not the debug logging of the revanced

**Comment by ILoveOpenSourceApplications** [comment]
The path did change. It's now `^page_header.eml$header_store_button` and leaves behind a black space where the button was unlike the previous one.

![Screenshot_20240611_114736_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/6d85c104-6dc5-48bc-8f6f-b010ba86a3f4)

```kotlin
06-11 11:16:42.181 16748 16748 D Extended: LithoFilterPatch: Path: page_header.eml|29bf20f8b14236d4|ContainerType|ContainerType|ContainerType|flexible_actions.eml|daf1064fca739913|ContainerType|ContainerType|ContainerType|button.eml|ebc698722222cbfe|ContainerType|
06-11 11:16:42.181 16748 16748 D Extended: LithoFilterPatch: BufferStrings: Visit storeΓ¥Ösans-serifΓ¥Öeml.header_store_buttonΓ¥ÖVisit storeΓ¥ÖUCeeFfhMcJa1kjtfZAGskOCAΓ¥ÖEgVzdG9yZfIGBBICKgA%3D"Γ¥Ö/@techlinkedΓ¥Ö
```

**Comment by inotia00** [comment]
Thanks, I'm sure that this is an A/B tests

**Comment by ILoveOpenSourceApplications** [comment]
Should be. I will try and see if it returns to the old one and if so, all is well. But if not, their will be a blank space of nothing when the button is hidden, thanks YouTube.

**Comment by ILoveOpenSourceApplications** [comment]
> It makes sense, but I understand why it isn't desirable to have quotes. It makes the settings look cluttered, and the sentences aren't truly ambiguous without them.
> 
> For example, in the title `Hide Playback speed menu`, it is obvious that "speed" must be connected to "Playback", and that "menu" is separate and not part of the proper noun.
> 
> Regardless of the convention, it should always be consistent. So either every multi-word proper noun has quotes, or none should have quotes.

Also, @inotia00 any comments on this?

**Comment by inotia00** [comment]
It's off-topic
If you need a discussion to improve the patch description or string, a new issue should be opened

**Comment by ILoveOpenSourceApplications** [comment]
Okay. Opened a new issue.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)

FYI: Hidden, but still left empty space
