### ISSUE TITLE
Missing side effect of using client spoof "Android Vr" / missing download button

### ISSUE THREAD

**Issue by AlexDeFoc** [inotia00/ReVanced_Extended#2122]
### Type

Other

### Tools used

rvx-builder

### Application

v19.20.34
Using latest patches from rvx builder.

### Bug description

If the client is spoofed to the option called "Android VR", the download button is missing. Thus is propose the description of the side-effects of the option should be updated to include is missing feature. Honestly this option was almost perfect, i would get the speed option and other ones but the little touch for downloading would've been golden.
![Screenshot_20240606_023038_Revanced](https://github.com/inotia00/ReVanced_Extended/assets/86987255/fd4b9c29-ffc8-408a-8168-d4b20178d19f)
![Screenshot_20240606_023102_Revanced](https://github.com/inotia00/ReVanced_Extended/assets/86987255/e9e5413b-8d82-4617-9a41-f7473fcbb1e5)

### Solution

- Update the description of the sideefects 
- Or update the....idk what changes the ui btn, but to add the download btn back on vr. Although logically you may not use the download btn on a real vr, but this is client spoofing.

### Additional context

Also to refresh the client change of setting you gotta exit the app and open it again.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1-dev.1)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
