### ISSUE TITLE
bug: hook download button on playlists opens internal downloader instead of external

### ISSUE THREAD

**Issue by neel9-9** [inotia00/ReVanced_Extended#2123]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.20.34

### Bug description

The hook download button opens internal downloader when clicked on Playlists.

![WhatsApp Image 2024-06-06 at 20 10 38_0eb8f211](https://github.com/inotia00/ReVanced_Extended/assets/171947316/7402f88c-8e71-40a9-b38b-1b2870bb469d)

The button works fine for individual videos. 
This is not an issue in ReX patches on YouTube v19.05.36
![WhatsApp Image 2024-06-06 at 20 10 37_522a35a8](https://github.com/inotia00/ReVanced_Extended/assets/171947316/9b9b7ef5-709e-4432-8214-2aa2bfaad12d)

### Solution

Merge the patch from YT-Advanced

### Device Environment

Android 14
OneUI 6.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2050
