### ISSUE TITLE
bug: YouTube Movies (free with ads) doesn't work on IOS client spoof, but it does work with Android VR client spoof. 

### ISSUE THREAD

**Issue by youngkong10** [inotia00/ReVanced_Extended#2124]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 19.20.34

### Bug description

Title says it. Using IOS client spoof I get a "tap to retry" video playback error on movies that are marked free with ads, but if I change the Shorts, Clips spoof (using dev release) to Android VR it will work. 

### Solution

Swapping to Android VR for Shorts, Clips client. 

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2116
