### ISSUE TITLE
bug (YT) : `quality_sheet_header` custom filter is not working in the flyout menu opened by `Replace Time Stamp Action`.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2126]
### Type

Cosmetic

### Tools used

Revancify

### Application

YT 19.16.39

Patches: 4.8.6

Integrations: 1.9.4

### Bug description

As mentioned in the title, the custom filter `quality_sheet_header` is not working when I open the quality flyout menu by tapping on the time stamp. But the same custom filter is working fine when I open quality flyout menu menu using the traditional method (clicking Gear icon, then Quality). So, kindly fix this.

https://github.com/inotia00/ReVanced_Extended/assets/91815107/b0f7cf4e-2096-4d4a-92b6-aa4671bbc3da

### Error logs

```shell
No logs.
```

### Solution

No matter what method the user employs to open the quality flyout menu, the custom filter `quality_sheet_header` should work.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro

Android 12 (skin name is Realme UI 3.0)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is not a litho component
Therefore, it cannot be hidden with custom filter (Litho Filter)

Similar example) if you spoof the app version with 18.21.35 or previous version, some player flyouts are still not a litho component, so you can't hide them with a custom filter

**Comment by Aryan-Chauhan** [comment]
Then how is that custom filter working when I open Quality Menu from Settings Gear icon?

**Comment by inotia00** [comment]
If it's not a litho component, it should be hidden in the layout, not the custom filter (should be implemented in the patch)

**Comment by inotia00** [comment]
[Similar PR has already been opened before](https://github.com/inotia00/revanced-patches/pull/19), and it's not very difficult to hide the non-litho components
I'll add the `Hide quality menu header` setting in the next release

**Comment by Aryan-Chauhan** [comment]
Thank you!

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1-dev.1)
