### ISSUE TITLE
feat(YouTube/Shorts components): If the `Hide disabled comments button` setting is turned on, the comment button is always hidden

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2127]
### Type

Other

### Tools used

RVX Manager

### Application

Latets patches using version 19.20.35

### Bug description

In youtube shorts there is no comment button i goto settings and turn it on/off still not there

### Device Environment

Hyper os 1.0.9 device name is poco x6 pro

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a reproducible issue in my side

When I checked the code, the patch uses regular expressions in the byte buffer, so it makes it difficult to find a solution in my side

I will temporarily remove the `Hide disabled comments button` setting from the next release

**Comment by Aryan-Chauhan** [comment]
For some reason, this setting is working fine for me on anddea patches.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
