### ISSUE TITLE
feat(YouTube Music/Settings): add patch option `RVX settings menu name`

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2128]
### Application

YouTube Music

### Feature description

You added feature to change rvx settings name in youtube but there is no patch for youtube music can you add it as well?

### Motivation

Just patch for changing settings name

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
