### ISSUE TITLE
bug: (YouTube): Various `Visual preference icons` icons are missing

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2129]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.20.35
ReVanced Patches: 4.9.1-dev.1
ReVanced Integrations: 1.10.1-dev.1

### Bug description

The newly added `Visual preference icons` patch seems to be missing quite a lot of icons on various other sections such as (YouTube/Shorts/Short player), (YouTube/Miscellaneous), specifically in (YouTube/Videos) section.

(YouTube/Videos) Various patch preference icons are missing-
![Screenshot_20240611-055254](https://github.com/inotia00/ReVanced_Extended/assets/107706560/2d8aad32-52c2-4ec5-8991-0ac7f44c5e98)
(YouTube/Shorts/Shorts player) `Hide disabled comments button` patch preference icon is missing-
![Screenshot_20240611-055331](https://github.com/inotia00/ReVanced_Extended/assets/107706560/273fe943-fe0e-4115-b7df-58d99a92e08f)
(YouTube/Miscellaneous) `Enable debug buffer logging` patch preference icon is missing-
![Screenshot_20240611-055353](https://github.com/inotia00/ReVanced_Extended/assets/107706560/4c3cb35b-616a-49ec-9dc5-b38187b0c5f8)

### Error logs

```shell
N/A
```

### Solution

Add relevant preference icons

### Additional context

Maybe it's just an error with implementing the patch as there are the spaces for icons to be added in the said sections but no icons are set, or as it is a completely new patch and the visuals of Revanced extended settings seems to be overhauled (which I like btw thx inotia ♥️) these might be some sort of bug?

### Device Environment

Android 14, pixelOS

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by vippium** [comment]
They are not missing. They are not even created by anddea. So this is not an bug. Icons which are already there in anddea's repo are here

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2129#issuecomment-2159587649
I see, then maybe they might open a PR to this issue when then decide on adding those icons.

**Comment by Aryan-Chauhan** [comment]
Did you check if they exist in anddea's RVX or not?

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2129#issuecomment-2159589717
I didn't used anddea patches so I haven't checked them.

**Comment by vippium** [comment]
> Did you check if they exist in anddea's RVX or not?

I'm 

> [#2129 (comment)](https://github.com/inotia00/ReVanced_Extended/issues/2129#issuecomment-2159589717) I didn't used anddea patches so I haven't checked them.

I use both rvx bro..so it is known to me. He is adding more in upcoming releases. Just wait for these icons.
