### ISSUE TITLE
question(YouTube): Regarding certain option naming

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2131]
### Application

YouTube

### Question description

Currently, single word components are so far the ones which use a first letter capitalize method. If it's a two word component, the quotation is used to indicate that both the word is part of the component. But this method is not followed consistently throughout the settings UI.

As said by @KobeW50:
>It makes sense, but I understand why it isn't desirable to have quotes. It makes the settings look cluttered, and the sentences aren't truly ambiguous without them.
>
>For example, in the title Hide Playback speed menu, it is obvious that "speed" must be connected to "Playback", and that "menu" is separate and not part of the proper noun.
>
>Regardless of the convention, it should always be consistent. So either every multi-word proper noun has quotes, or none should have quotes.

So either we'll have to make every option with more than two words inside a quote, or make everything without one and follow the first word capitalize method.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
@inotia00, your opinion?

**Comment by inotia00** [comment]
It is ideal to use the quotation, but it is not appropriate to apply it to the patch name

It seems better to unify by removing the quote

**Comment by ILoveOpenSourceApplications** [comment]
Looks like we have a conclusion then.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
