### ISSUE TITLE
bug(YouTube/Custom branding icon YouTube): `Custom header` is not applied when both the patch options `App icon` and `Custom header` are set custom values

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#2132]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

patches 4.9.1-dev.1, YT lastest supported

### Bug description

I declared in Manager folder with all files needed for this option, and when I installed app, nothing changed - there's still default and Premium

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by GucekPL** [comment]
![Screenshot_20240611_144453_app.rvx.manager.flutter.jpg](https://github.com/inotia00/ReVanced_Extended/assets/69505731/4bb8d3b2-79fb-401b-b527-8fff056f0fcd)

![Screenshot_20240611_144514_com.huawei.filemanager.jpg](https://github.com/inotia00/ReVanced_Extended/assets/69505731/5de012db-26c2-4731-b3be-527abf493b4c)

**Comment by inotia00** [comment]
![Option](https://github.com/inotia00/ReVanced_Extended/assets/108592928/4db65fc4-f6ab-4076-8f52-47d243d657fd)

You have to turn on `Change header` option first to use a custom header
(yeah, `Custom branding icon YouTube` patch is a bit complicated)

Turn on the `Change header` option and test if the issue is reproduced

**Comment by GucekPL** [comment]
Still no changes in the header, still custom heading don't work

**Comment by inotia00** [comment]
All four images must be located in all directory
Like this:

```
drawable-hdpi
  L yt_premium_wordmark_header_dark.png
  L yt_premium_wordmark_header_light.png
  L yt_wordmark_header_dark.png
  L yt_wordmark_header_light.png
drawable-mdpi
  L yt_premium_wordmark_header_dark.png
  L yt_premium_wordmark_header_light.png
  L yt_wordmark_header_dark.png
  L yt_wordmark_header_light.png
drawable-xhdpi
  L yt_premium_wordmark_header_dark.png
  L yt_premium_wordmark_header_light.png
  L yt_wordmark_header_dark.png
  L yt_wordmark_header_light.png
drawable-xxhdpi
  L yt_premium_wordmark_header_dark.png
  L yt_premium_wordmark_header_light.png
  L yt_wordmark_header_dark.png
  L yt_wordmark_header_light.png
drawable-xxxhdpi
  L yt_premium_wordmark_header_dark.png
  L yt_premium_wordmark_header_light.png
  L yt_wordmark_header_dark.png
  L yt_wordmark_header_light.png
```

![FileManager](https://github.com/inotia00/ReVanced_Extended/assets/108592928/b8eed0c4-24ba-4b07-a32f-d3c6cb89f414)

According to the [screenshot](https://github.com/inotia00/ReVanced_Extended/issues/2132#issuecomment-2160673332) you attached, there are only 4 images in the directory `drawable-xxhdpi`, and only 2 images in the rest of the directory

**Comment by GucekPL** [comment]
Facticially, I am already setting about correcting this. I'll let you know when I've got it all figured out

**Comment by GucekPL** [comment]
`Custom header` changes graphic separately to default and Premium logos, or for all?

**Comment by inotia00** [comment]
for all

**Comment by GucekPL** [comment]
Still don't work, I checked files names, I have 4 files (2 to default, 2 to Premium) in all 5 folders

**Comment by GucekPL** [comment]
Yes, icon was changed (I'm using default, but in black version), but header didn't

**Comment by inotia00** [comment]
> Yes, icon was changed

Ah, that seems to be the cause

**Comment by GucekPL** [comment]
4.9.1-dev.2 - all works properly, custom header works perfectly in YT ;) - I will check later YTM
![image](https://github.com/inotia00/ReVanced_Extended/assets/69505731/d1124975-e39e-452c-86b2-110173ba21c2)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
