### ISSUE TITLE
bug (YouTube/YouTube Music - Hide ads): Toast messages are shown multiple times

### ISSUE THREAD

**Issue by MarcaDian** [inotia00/ReVanced_Extended#2133]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Music 7.04.51, patches v.4.9.1-dev.1

### Bug description

`Fullscreen ads closed` toast shown about 5 times.
By the way Fullscreen ads was closed 😉

### Error logs

```shell
Nan
```

### Additional context

<details>

![Screenshot_2024-06-11-18-12-43-992-edit_app revanced android apps youtube music](https://github.com/inotia00/ReVanced_Extended/assets/152095496/64447ec5-94b2-45d4-b24d-f326ae12a5ba)

</details>

### Device Environment

MIUI 13, A12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
