### ISSUE TITLE
suggestion: split "Custom header" from "Custom branding icon YouTube"

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2135]
### Application

YouTube

### Suggestion description

I don't think it really makes sense to have them together as they do two different things and so it would be more user friendly to separate them as two different patches

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
