### ISSUE TITLE
bug(YouTube/Settings): `Search bar in settings` can't find certain settings

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2136]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.20.35
Patches v4.9.1-dev.1

### Bug description

**As you can see, it can't find `Close fullscreen ads`:**
![Screenshot_20240611_173827_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/3da5d0d2-6a8c-4c3e-9f22-e5edc0ac8633)

**But here it can:**
![Screenshot_20240611_173843_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/25c6bb8c-e5c0-4341-82f9-8a7db390a004)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
