### ISSUE TITLE
bug (YT) : `Hide Disabled Comments Button` is hiding comments button of Shorts that have 1 or more comments.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2138]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39 on latest dev patches.

### Bug description

I think the title explains it sufficiently.

That setting is supposed to hide the comments button of Shorts when there are 0 comments or when comments section is disabled.

But in actuality, it is hiding comments button of Shorts that have 1 or more than 1 comments.

So, kindly look into it.

### Error logs

```shell
No logs.
```

### Solution

It should work ideally.

### Additional context

Nothing.

### Device Environment

Realme 7 Pro.

Android 12.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2127
