### ISSUE TITLE
bug(YouTube): `Hide disabled comments button` doesn't work properly

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2139]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.20.35
Patches v4.9.1-dev.1

### Bug description

As you can see, neither the comments of the Short are disabled nor the Short has 0 comments, but when `Hide disabled comments button` is enabled the comments button of Shorts gets hidden anyway.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/91138a1e-cd07-44d6-8037-369ed8e3c488

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2127
