### ISSUE TITLE
feat(patch): hide filter bar 

### ISSUE THREAD

**Issue by briantgosling** [inotia00/ReVanced_Extended#214]
### Application

YouTube

### Issue

not a problem really more of a suggestion 

### Patch

![IMG_20230131_164718](https://user-images.githubusercontent.com/116717037/216811675-aaa55a8f-458c-4349-bf3e-f362268d4f9d.jpg)
this little circle recommendation for content or idk their name is they kind of annoying or rather unpleasant to the display in YouTube so could you please add a patch to remove these?

### Motivation

I think it's simple and isn't really much of a trouble but just for YouTube revanced x to be clean looking

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
I don't understand why you would want to hide them. Those are one of the very few useful features added by YouTube.

**Comment by briantgosling** [comment]
> I don't understand why you would want to hide them. Those are one of the very few useful features added by YouTube.

well i kinda find it annoying it's just for people like me who don't like it if ever it's added others can just ignore it or not patch it :)

**Comment by s23ultra512** [comment]
I would love to have an option to hide these also, I find them rather annoying.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.166.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.18)
