### ISSUE TITLE
question: Will you add miniplayer?

### ISSUE THREAD

**Issue by akir45** [inotia00/ReVanced_Extended#2140]
### Application

YouTube

### Question description

RVX crowdin has miniplayer related strings but they are not present in RVX patch. Will you add them from official revanced in the future?
![Screenshot_2024-06-12-18-14-25-176_app revanced android youtube](https://github.com/inotia00/ReVanced_Extended/assets/91464996/3de81831-1ccb-4c0f-8b82-bca09d26fdbe)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Patch was implemented local at the time of adding strings to crowdin, but a small problem was found so I did not reflect in the repository

All problems have been solved now, and soon will be reflected to the repository
