### ISSUE TITLE
Bug (YouTube): unselected custom branding name applied

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#2141]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 19.20.35 patches 4.9.1 dev 2

### Bug description

Custom branding name applies even if patch is not selected. It seems default value for youtube name is RVX

Have tried clearing patch options

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The `Custom branding name YouTube` patch has been renamed to the `Custom branding name for YouTube`

Try to reinstall the RVX Manager after backing up the keystore

**Comment by ayushTNM** [comment]
That seems to have fixed it. Will keep in mind for future releases.

Also, before i open issue, is it impossible for the custom header patch to work with either just the wordmark header png or just the wordmark premium header png and if it does not, should this give an error during patching?

**Comment by inotia00** [comment]
> That seems to have fixed it. Will keep in mind for future releases.

In general, you do not have to reinstall the RVX Manager
Exceptionally, there were too many changes in revanced-patches-4.9.1, so I just recommended reinstallation



> Also, before i open issue, is it impossible for the custom header patch to work with either just the wordmark header png or just the wordmark premium header png and if it does not, should this give an error during patching?

Sorry, but I haven't tested it
(Tested only if all files are located)
