### ISSUE TITLE
bug(YouTube/Miniplayer): `Swipe miniplayer to expand or close` does not work

### ISSUE THREAD

**Issue by akir45** [inotia00/ReVanced_Extended#2142]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.20.35
patch v4.9.1 dev-2

### Bug description

`Swipe miniplayer to expand or close` does not work when miniplayer `Hide expand and close buttons` are enabled.

### Device Environment

android 14

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by akir45** [comment]
It can be closed, but not expanded. The official revamp works fine.

https://github.com/inotia00/ReVanced_Extended/assets/91464996/55c97873-2d9a-47b8-a671-57fcbf499d9d

**Comment by inotia00** [comment]
Ah this is not a bug

Google has changed Miniplayer behavior in YouTube 19.20.35+ so that videos can only be expanded using the expand button
(also reproduced on unpatched YouTube)

If you want the old behavior, roll back to YouTube 19.16.39

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2142#issuecomment-2163518135
But with newer tablet miniplayer types, the expand button doesn't exist so the only way to expand the payer is to tap on the player which goes against muscle memory of many users I'd assume.
Hence, it's would be preferably good to have previous swipe to expand miniplayer gesture restored on new tablet miniplayers we have now.

**Comment by inotia00** [comment]
The 'bug' on YouTube's side appears to have been fixed in YouTube 19.25.xx+

> Ah this is not a bug
> 
> Google has changed Miniplayer behavior in YouTube 19.20.35+ so that videos can only be expanded using the expand button (also reproduced on unpatched YouTube)

This behavior has been rolled back in YouTube 19.25.xx+
(Modern 1 only)

Therefore, in the next release, support for YouTube 19.23.40 will be removed and support for YouTube 19.25.39 will be added

**Comment by Diesel1987** [comment]
On version 19.25.39 seekbar adjust on wrong position when shuffle. 

https://github.com/inotia00/ReVanced_Extended/assets/174826982/4cc62dda-0390-431b-bbb8-22e3a52b9ce8

On old version 19.23.40 everything i ok

https://github.com/inotia00/ReVanced_Extended/assets/174826982/d3c665f8-13d1-4565-bfed-b79e0fd1af40

**Comment by inotia00** [comment]
Same goes for unpatched YouTube.
In other words, this is YouTube's new layout.

**Comment by joseph-starks** [comment]
![Screenshot_20240714_133058_RVX](https://github.com/user-attachments/assets/6679d2ba-1bf9-4e4c-a1d0-049e4a84dcae)
![Screenshot_20240714_133202_RVX](https://github.com/user-attachments/assets/1aa83541-70d1-4017-9c99-5660780aa517)

What's going one with RVX? I'm connected to the internet, I've tried re-downloading RVX or older ones like RVX and yet same issue keeps popping up? What happened to it?

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2142#issuecomment-2227446020
Please open a new issue for any new issues.
Unrelated comment please mark as off-topic, @inotia00
