### ISSUE TITLE
suggestion: Translations: Titles on 2 lines

### ISSUE THREAD

**Issue by Kevinr99089** [inotia00/ReVanced_Extended#2144]
### Application

YouTube

### Suggestion description

Some languages (French in my case) can contain long words, so we have to shorten the titles in the Extended settings, which can lower the quality of the translation (or even make it incomprehensible, and French contains a lot of long words).
I've seen that on YT Music, the title can be on 2 lines (see image), would it be possible to add it on YouTube too?
(This problem hasn't arisen since the icons were added, it was already the case before. I've just noticed today that the titles on Music can be on several lines.)

YouTube: 
![Screenshot_20240612_230521_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/93716347/7bac1d12-8836-412f-8346-fbd22cbdccda)

Same Title, but on YT Music :
![Screenshot_20240612_230454_YouTube Music](https://github.com/inotia00/ReVanced_Extended/assets/93716347/38153c3b-14a3-488f-9593-a77ebcb1b6c8)

Here are some examples of settings that are cut:
![Screenshot_20240612_232345_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/93716347/88ba9228-5ece-408b-86b1-5aca0655b48a)
![Screenshot_20240612_232451_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/93716347/2b24281d-8d87-4fc0-a734-3240a1a0b83b)
![Screenshot_20240612_232459_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/93716347/8a9cc0cf-2f62-4bc5-9afb-ee1b3702acc4)
(and we do our best to keep titles as short as possible.) 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Due to the structural limitations of the patch:
`Android Library` is used on YouTube, 
`AndroidX Library` is used in YouTube Music

This is the result of this difference..
So.. this is not possible

**Comment by Kevinr99089** [comment]
Right, and that explains why the left bar stays open on Music unlike YouTube on Extended settings? (on tablet)

Youtube: 
![Picsart_24-06-13_14-10-52-252](https://github.com/inotia00/ReVanced_Extended/assets/93716347/1e2fed08-c965-482b-837c-57d4e1f7b6b8)

Music: 
![Picsart_24-06-13_14-08-22-365](https://github.com/inotia00/ReVanced_Extended/assets/93716347/fe4ab3e6-1c5e-45c0-8359-0375044cc0d5)
