### ISSUE TITLE
bug: short stop playing

### ISSUE THREAD

**Issue by KPVADALIYA** [inotia00/ReVanced_Extended#2145]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.20.35

https://github.com/inotia00/ReVanced_Extended/assets/103434326/fa45c547-5f1a-4042-8a04-55205a5fd506

### Bug description

Shorts start buffering after playing 2 sec

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1954
