### ISSUE TITLE
bug(Hide ads): app crashes at old client

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#2146]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 18.29.38

RVP 4.9.1

### Bug description

Steps to reproduce the bug:
1. Patch 18.29.38 including "Hide ads".
2. Install and open the app.
3. The app crashes. :(

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.9.2-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2-dev.1)

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
