### ISSUE TITLE
suggestion: GmsCore Option battery optimization dialog

### ISSUE THREAD

**Issue by CobalTitan** [inotia00/ReVanced_Extended#2147]
### Application

YouTube

### Suggestion description

Could the patch from anddea GmsCore support: added Don't show again option for battery optimization dialog (3069354) be imported too.

https://github.com/anddea/revanced-patches/commit/3069354e5e736dbbebc1a85cdde2762a436f1338

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2120
