### ISSUE TITLE
suggestion: force snackbar theme

### ISSUE THREAD

**Issue by hezz79** [inotia00/ReVanced_Extended#2148]
### Application

YouTube

### Suggestion description

![Screenshot_20240608-072353~2](https://github.com/inotia00/ReVanced_Extended/assets/159753968/f3ac8c64-e62e-4cde-a2e5-229b571a263d)
please add force snackbar theme so snackbar can adapt to be dark/light mode like in the picture attached 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The reason why the patch was not implemented can be found in the following comments:
https://github.com/inotia00/revanced-patches/pull/55#discussion_r1623865222
