### ISSUE TITLE
feat(patch): hide-shorts-component

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#215]
### Application

YouTube

### Issue

removal of unnecesary shorts component

### Patch

please remove channel info and "audio used" on shorts player
![photo_6266822112450820214_w](https://user-images.githubusercontent.com/87489540/216813318-398bc807-86e3-43bd-8ece-f43d961f8a4b.jpg)

### Motivation

these components are unnecessary

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/151
