### ISSUE TITLE
Button to disable swipe-to-switch video absent with anddea patches

### ISSUE THREAD

**Issue by Gubbbka** [inotia00/ReVanced_Extended#2150]
### Application

YouTube

### Question description

4 days ago i met in anddeas version that by swiping op or down i can swith video. I wanted to disable this but not found any buttom related to that.  In anddeas releases changelog also isnt info about it, so i thought its bug. 

But in your changelog i read its your new feature, and in your settings this buttom was present.
So why without anddeas work your new feature auto merged to his version, but buttom in settings not appeared in his settings?
Ps. After i posted this on anddea issues page he suggested me to report you

### Acknowledgements

- [ ] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You have already opened the same issue, and I answered https://github.com/inotia00/ReVanced_Extended/issues/2149
