### ISSUE TITLE
suggestion: Add "Restore Old Seekbar" in Spoof App target version 

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2153]
### Application

YouTube

### Suggestion description

It will be good if you can add 19.16.39 in Spoof App target version for enabling old seekbar.
![Screenshot_2024_0614_235346](https://github.com/inotia00/ReVanced_Extended/assets/93650504/8a9ef774-89ed-4055-a72a-cb172b9197a0)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
No, it's not a server-side change, it's a client-side change

Old seekbar thumbnails are not available even if you spoof the app version

The only solution is to patch to YouTube 19.16.39
