### ISSUE TITLE
feat: YTM - Add patch option for "Hiding buttons from samples" with background circle

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2154]
### Application

YouTube Music

### Feature description

Like we have buttons hiding feature for Shorts in YT, can we have same feature for "Samples" too. I know that it is not that much used. But it will be good if we have it, for cleaner "Samples" xperience.
Already created [issue](https://github.com/anddea/revanced-patches/issues/600#issue-2353609519) in anddea repo

### Motivation

Enhance "Samples" by making it buttons free. Or having less buttons.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/1365
