### ISSUE TITLE
bug(YouTube/Miniplayer): when the video is minimized, video title is hidden

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2155]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39 ~

### Bug description

Step 1 - Include `Miniplayer` patch.
Step 2 - Change `Miniplayer` type to `Modern 2`.
Step 3 - Play the vertical video and minimize the video.

https://github.com/inotia00/ReVanced_Extended/assets/93650504/20204d3a-5e7a-4419-b886-3d02af8dde06

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/2160
