### ISSUE TITLE
bug: RVX root medhod bug

### ISSUE THREAD

**Issue by Graywizard888** [inotia00/ReVanced_Extended#2156]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube v19.21.40

### Bug description

![Screenshot_2024-06-15-12-17-00-161_com miui securitycenter](https://github.com/inotia00/ReVanced_Extended/assets/172885338/07642bce-3c67-48a8-932c-47f6070b10c7)

I patched youtube with root medhod using revancify and it works well that time and many days but when i reboot my device the youtube keep crashing and its name is changed to random anything like dark theme,Artist you like, etc. The app version get downgraded too like if i patch youtube v19.21.40 then it will be v19.20.34 old version. Can you suggest me how to fix this.

My root medhod is kernal su

### Device Environment

Android 12, miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an issue where detach does not work, it has nothing to do with the patch
