### ISSUE TITLE
bug: YT - `Hide Disabled Comment Button` hiding the button unnecessarily.

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2158]
### Type

Other

### Tools used

rvx-builder

### Application

16.39
YT

### Bug description

A/c to the patch, it should only hides the comment button only when the comment button is disabled or comment count is 0. But, after latest patches, it hides the whole comment button even comments are not 0 or disabled.

### Device Environment

Funtouch 14
A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by akir45** [comment]
https://github.com/anddea/revanced-patches/discussions/446
This patch has not yet been added to the inotia repository.
