### ISSUE TITLE
suggestion (Youtube): Improve hiding irrelevant search results.

### ISSUE THREAD

**Issue by Cast0r-999** [inotia00/ReVanced_Extended#2159]
### Application

YouTube

### Suggestion description

Could you improve "RVX - Feed - Video filter - Hide recommend videos" to clean search results from irrelevant already watched videos? Or better, add separate option. They don't have labels or some sort of indication, except "Show more" at the bottom. They appear, if you scroll results further down.
P.S. I'm not talking about relevant watched videos.
Example: https://youtu.be/JfpoKJvYVIU 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
To implement it, you need a new client like NewPipe
In ReVanced, it cannot be implemented
