### ISSUE TITLE
feat(patch): hide endscreen overlay components

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#216]
### Application

YouTube

### Issue

remove shopping/ channel store links from endscreen overlay

### Patch

![photo_6266822112450820220_w](https://user-images.githubusercontent.com/87489540/216813708-7efa1f17-9822-4bcc-a036-d0b6c7770775.jpg)

### Motivation

i think everyone would love it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
