### ISSUE TITLE
suggestion(YouTube): add support versions 19.19.39

### ISSUE THREAD

**Issue by zerozero0022** [inotia00/ReVanced_Extended#2161]
### Application

YouTube

### Suggestion description

for users who want these features...

• swipe miniplayer to expand 
• Swipe up / down to play the next / previous video

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
That's an already supported version.

**Comment by zerozero0022** [comment]
@ILoveOpenSourceApplications 

A warning popup will appear when you patch with the manager. I know I can ignore it, but I wanted to see the popup.

![Screenshot_20240617-053123_RVX Manager~01](https://github.com/inotia00/ReVanced_Extended/assets/163995091/2324e81f-3a95-4f47-86c4-59fa6f33e881)

**Comment by inotia00** [comment]
Reopening as this is a valid issue

**Comment by zerozero0022** [comment]
This feature is not possible in v19.19.39.
• Swipe up / down to play the next / previous video

**Comment by inotia00** [comment]
If so, it's probably a server-side limitation
(On the client side, the code is already implemented in YouTube 19.19.39, but the server side may have limited the available versions)

I will check again later and close the issue

**Comment by inotia00** [comment]
After testing, it seems to be available only on YouTube 19.20.35+
Closing issue
