### ISSUE TITLE
feat (YT Music) : (1) Add round background to the YTM MMT splash icon. (2) Size of YTM's MMT splash icon should be equal to YT's MMT splash icon.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2162]
### Application

YouTube Music

### Feature description

For point (1) : As you can see in the below screenshot, MMT splash icon doesn't have any round background in RVX YTM. But in RVX YT, MMT splash icon does have a round background. So, it is requested to add a round background to YTM's MMT splash icon.

For point (2) : Kindly make adjustments such that `size of YTM's MMT splash icon = size of YT's MMT splash icon`.

Screenshots, so that above 2 points make sense:
![Screenshot_2024-05-18-17-58-54-39_270755430a2a239778e0eeec997274a1](https://github.com/inotia00/ReVanced_Extended/assets/91815107/b5ec658d-d8a4-4297-9d16-d12d210b48ac)
![Screenshot_2024-05-18-17-58-37-17_fe557b5c831afa8eecca413bd340ebe7](https://github.com/inotia00/ReVanced_Extended/assets/91815107/054b3198-4f65-43f7-a2f5-b897487069e1)

### Motivation

Launcher icon, splash icon, header icon should be same. But currently, only launcher icon & header icon are same to each other.

Splash icon ≠ Launcher icon.

Splash icon ≠ Header icon.

If round background is added to MMT splash icon, all 3 icons will become same.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
@kazimmt

**Comment by vippium** [comment]
> ### Application
> YouTube Music
> 
> ### Feature description
> For point (1) : As you can see in the below screenshot, MMT splash icon doesn't have any round background in RVX YTM. But in RVX YT, MMT splash icon does have a round background. So, it is requested to add a round background to YTM's MMT splash icon.
> 
> For point (2) : Kindly make adjustments such that `size of YTM's MMT splash icon = size of YT's MMT splash icon`.
> 
> Screenshots, so that above 2 points make sense: ![Screenshot_2024-05-18-17-58-54-39_270755430a2a239778e0eeec997274a1](https://private-user-images.githubusercontent.com/91815107/340150746-b5ec658d-d8a4-4297-9d16-d12d210b48ac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTI0MTYsIm5iZiI6MTcxODU5MjExNiwicGF0aCI6Ii85MTgxNTEwNy8zNDAxNTA3NDYtYjVlYzY1OGQtZDhhNC00Mjk3LTlkMTYtZDEyZDIxMGI0OGFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAyNDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYjQ1MGI4ZWJiZTAxODIwN2Q5MjNkY2YxNmJjOGJmNDE3ZWY1OGI1ZmFlODQ4ODc5NmI5ZDhhMTMzYjNhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1avShy3fjMuynpMQxTMDmvr_fKKn5RS29nRNR7kn29s) ![Screenshot_2024-05-18-17-58-37-17_fe557b5c831afa8eecca413bd340ebe7](https://private-user-images.githubusercontent.com/91815107/340150785-054b3198-4f65-43f7-a2f5-b897487069e1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTI0MTYsIm5iZiI6MTcxODU5MjExNiwicGF0aCI6Ii85MTgxNTEwNy8zNDAxNTA3ODUtMDU0YjMxOTgtNGY2NS00M2Y3LWEyZjUtYjg5NzQ4NzA2OWUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAyNDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOTY5YmM4MTUyMTBiOTk1NDEwZWZjNTg5OGQ5MDI5ZjdlYzBjYzE0YmU3ZWU2ZTA0NmJmNGQxNzBjZTM4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._0NoK7aOVsnMl5nq_nNN1kysikbHg6t3LUx1nmjb6x0)
> 
> ### Motivation
> Launcher icon, splash icon, header icon should be same. But currently, only launcher icon & header icon are same to each other.
> 
> Splash icon ≠ Launcher icon.
> 
> Splash icon ≠ Header icon.
> 
> If round background is added to MMT splash icon, all 3 icons will become same.
> 
> ### Acknowledgements
> * [x]  This is not a feature request for YouTube.
> * [x]  This issue is not a duplicate of an existing feature request.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.
> * [x]  I have written the title and contents in English.

Instead of adding rounded circle, why not mmt remove the rounded circle of YT. It will look more fantastic. @kazimmt can you remove the rounded circle from the YT splash logo?

**Comment by inotia00** [comment]
Icon was added through PR:

https://github.com/inotia00/revanced-patches/pull/8
https://github.com/inotia00/revanced-patches/pull/10

The current icon includes the contributor's intention

If you want to change the icon, you can open a new PR
