### ISSUE TITLE
suggestion: Bring back Shorts outline buttons

### ISSUE THREAD

**Issue by blacktornadog7** [inotia00/ReVanced_Extended#2164]
### Application

YouTube

### Suggestion description

please bring back [Shorts outline buttons](https://imgur.com/a/VXJvZoM) as an option alongside [Custom Shorts action buttons](https://i.redd.it/cl4p93di8uqc1.jpeg) and not instead of it.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
The option wasn't removed. You can select "Outline" in the `Shorts icon style` patch option of the `Custom Shorts action buttons` patch.

![SmartSelect_20240617_152916_RVX Manager.png](https://github.com/inotia00/ReVanced_Extended/assets/84587632/88c82617-6d12-4c86-943f-8e12801b0e43)

**Comment by inotia00** [comment]
![manager](https://github.com/inotia00/ReVanced_Extended/assets/108592928/3de29149-6e2b-4003-9ae4-c3c43aabc9ee)
