### ISSUE TITLE
suggestion: Enhancement in mmt header icons or logos. 

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2165]
### Application

YouTube Music

### Suggestion description

@kazimmt Can you make a enhancement in the header icon. Like instead of putting the app icon logo directly, can you enhance it by replacing the black part in the logo with transparent. So that, the header logo looks great and follows other icons too. And will also have more space to increase the logo size like other too. While using other icons like afn, rvf, they have transparent background in header which gives them a + point in header icon.
Can you pls add this suggestion for enhancing the header logo. Here is the example:
**MMT Red or MMT Default**
![Screenshot_2024_0618_112922](https://github.com/inotia00/ReVanced_Extended/assets/93650504/b26e493a-d7b6-498a-b8fd-3ed7d547eeaa)
**Revancify Blue**
![Screenshot_2024_0618_113108](https://github.com/inotia00/ReVanced_Extended/assets/93650504/c01b047b-8828-4102-950d-cd2398e2a9d1)

And also, this suggestion is for both YT & YTM. Try to do it when you find it useful. And also try to add a comment whether you liked my suggestion.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by kazimmt** [comment]
Stock YTM header isn't transparent i guess.
I'm following the same!

**Comment by vippium** [comment]
> Stock YTM header isn't transparent i guess. I'm following the same!

I know that. As it have red as background, so it looks filled. But after using all the custom icons, I feel the same for MMT too.

**Comment by vippium** [comment]
> > Stock YTM header isn't transparent i guess. I'm following the same!
> 
> I know that. As it have red as background, so it looks filled. But after using all the custom icons, I feel the same for MMT too. Like all have black background, and they removed it in header

Splash screen is inconsistent after enabling `Cairo splash animation` option. Here, after enabling, it feels too laggy. Need to add support for `Cairo splash animation`

![Screenshot_2024_0623_230753](https://github.com/inotia00/ReVanced_Extended/assets/93650504/2ffd48e7-b538-4f3a-8b5b-4060a3860ae7)
