### ISSUE TITLE
suggestion: Updated side effects of spoof client

### ISSUE THREAD

**Issue by raman452mth** [inotia00/ReVanced_Extended#2166]
### Application

YouTube

### Suggestion description

Update the side effects of spoof client patch

Android Testsuite  
~~• Seekbar thumbnail is missing.~~
• Low quality seekbar thumbnail.
• Download button is missing.
• End screen cards are missing.

Android TV  
• Low quality seekbar thumbnail.
• Download button is missing.
 
### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
If anyone finds a side effect that isn't listed here, please leave a comment

**Comment by AlexDeFoc** [comment]
on Android Testsuite : watch history is NOT doesn't work

also inotia00, quick question, which would be easier to fix and faster: 
watch history to work for brand accounts (i use one and it would realllly help cuz the ios spoof client it's almost perfect) 

OR 

the captions to work on other client spoofs, other than ios and vr

Thx for reading ❤️

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
