### ISSUE TITLE
suggestion(YouTube - Hide fullscreen ads): Remove toast being shown when hiding fullscreen ad

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2167]
### Application

YouTube

### Suggestion description

Currently, the `Hide fullscreen ads` toast shows up when it hides ads as well as when it hides some other UI elements, like opening community posts images. It feels unwanted to have a toast show up when ads are hidden, whereas if it's when it's hiding a UI element, it'll help the user identify what's causing the issue.

Also, there are users who hide community posts and for them having a toast pop-up simply when hiding an ad just feels unnecessary. 

So, if possible, the toast can be avoided when hiding ads and only pop-up when hiding UI elements would be perfect. 

![Screenshot_20240618_213256_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/0a0a4f34-d8c8-4972-bd8b-16d0b2e092c8)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This toast is needed to resolve the issue https://github.com/inotia00/ReVanced_Extended/issues/2017

This is because it is not yet known what type of dialog is used in community posts image

**Comment by inotia00** [comment]
If the dialog type used in community post images becomes known,
`Close fullscreen ads` setting will not be necessary and the toast will also be removed
