### ISSUE TITLE
bug:(YouTube Music) app crashes at old client

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#2168]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Music 6.29.58

RVP 4.9.1—4.9.2-dev1

### Bug description

Steps to reproduce the bug:

1. Enable `Hide like and dislike buttons`
2. Enable `Restore old player layout`
3. The app crashes.

Also, when enabling `Old player layout`:
1. `Previous button` in the miniplayer is missing.
2. `Enable black player background` doesn't apply.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
