### ISSUE TITLE
bug (YouTube): `Navigation bar` elements is not hiding, when they have new icons 

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#2169]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

**YT app version**: `19.25.39`

### Bug description

Today, YouTube decided to endow my Google account with new navigation bar icons. Along with this, hiding the notification button no longer works.

**Steps to reproduce**:
1. Make sure you have the icons as in the screenshot below
![image](https://github.com/inotia00/ReVanced_Extended/assets/69505731/d9d74db3-e5d0-4f58-a6ed-cdf744da99fb)
2. Enable `Swap Create and Notifications buttons` and `Hide notifications button` in the `Navigation buttons` options
![image](https://github.com/inotia00/ReVanced_Extended/assets/69505731/9ec60cca-f2e2-4960-bde5-db6d330238ad)
3. As shown, notifications button is still showing
![image](https://github.com/inotia00/ReVanced_Extended/assets/69505731/4bd42a24-7784-4bcf-8be5-bb97818e6a7f)

### Solution

Rollback to YouTube 19.16.39

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by GucekPL** [comment]
I would also add that I checked the option to hide the notification button in the toolbar, and it doesn't work too

**Comment by inotia00** [comment]
It looks like A/B tests
Not only the Notification button, but also other buttons are not hidden? (Home, Shorts, Scubscriptions, etc..)

**Comment by inotia00** [comment]
These are clearly A/B tests

If this issue still occurs on your account, could you please provide the debug log?

**Comment by GucekPL** [comment]
How to do that? I have never done this

**Comment by inotia00** [comment]
1. Turn on the following settings:
```
Settings - ReVanced Extended - Miscellaneous - Enable debug logging
```

2. Launch [termux](https://github.com/KitsunedFox/termux-monet/releases/latest)

3. In termux, enter the following command:
```
logcat | grep Extended > /storage/emulated/0/logcat.txt
```

4. Force close and launch the RVX again

5. After about 10 seconds, return to termux and click the `CTRL` button, and then click the `C` on the keyboard

6. The `logcat.txt` file generated in the internal storage (/sdcard/logcat.txt)

7. Upload `logcat.txt`

**Comment by inotia00** [comment]
1. Download and install the `Locat Reader` app:

[F-Droid (summary)](https://f-droid.org/packages/com.dp.logcatapp/)
[F-Droid (direct download)](https://f-droid.org/repo/com.dp.logcatapp_33.apk)

2. Enable USB debugging and grant permission by entering the following command from the CMD on your PC:

```
adb shell "pm grant com.dp.logcatapp android.permission.READ_LOGS && am force-stop com.dp.logcatapp"
```

3. Launch the Locat Reader app

4. Move to `3dot menu - Filters`

5. Click the `+` button and type it like a screenshot:

![LogCatReader](https://github.com/inotia00/ReVanced_Extended/assets/108592928/a97f0d6f-23dc-4e22-a6e4-4d8c35f044f8)

and then, click `OK`

6. In RVX, turn on the following settings:
```
Settings - ReVanced Extended - Miscellaneous - Enable debug logging
```

7. Force close and launch the RVX again

8. After about 10 seconds, back to the `Locat Reader` app and screen capture

![LogCatReader](https://github.com/inotia00/ReVanced_Extended/assets/108592928/8da67bd6-03a0-4927-997b-bc686752fd38)

**Comment by GucekPL** [comment]
Okay, tysm, I will do this later

**Comment by GucekPL** [comment]
@inotia00 
![image](https://github.com/inotia00/ReVanced_Extended/assets/69505731/d50dadea-9f6c-491e-b341-92e6886ba506)
I have only 2 logs after opening RVX

**Comment by inotia00** [comment]
Thanks.. I think the Cairo icon cannot be identified by the Enum value
(requires deeper debugging)

It seems that a fix is ​​only possible when this A/B test is applied to my account

btw Cairo icon for navigation bar was added in YouTube 19.20.35, so using YouTube 19.16.39 may solve the issue

**Comment by inotia00** [comment]
One last thing, please test that the `Hide navigation labels` setting works

**Comment by GucekPL** [comment]
Works

**Comment by GucekPL** [comment]
@inotia00 1 hour ago, Google reverted for my account new Cairo-icons, so all works perfectly again. LMAO 😅

**Comment by inotia00** [comment]
In [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2), the supported version has been rolled back to YouTube 19.16.39.
This bug is only reproducible on YouTube 19.20.xx+, so the issue is closed.

**Comment by GucekPL** [comment]
@inotia00 so from now, hiding works on new icons?

**Comment by inotia00** [comment]
Yes the patch supports it now, but I haven't been able to test it because the A/B tests were reverted on my account the day after I checked the debug logs

**Comment by GucekPL** [comment]
> Yes the patch supports it now, but I haven't been able to test it because the A/B tests were reverted on my account the day after I checked the debug logs

In my case these icons are appearing and dissappearing randomly 😅

**Comment by AbakNacchan** [comment]
Up to which version that doable using this source?
