### ISSUE TITLE
feat(patch): remove remix button under video player

### ISSUE THREAD

**Issue by kazimmt** [inotia00/ReVanced_Extended#217]
### Application

YouTube

### Issue

YT added a remix button under video
![Screenshot_2023-02-05-19-36-23-437_app revanced android youtube-edit](https://user-images.githubusercontent.com/82371061/216822711-8b019f3b-ce13-4361-8175-84fed0bb4b0e.jpg)

### Patch

Option to remove remix button inside `hide button container component`

### Motivation

To hide the button like others

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![rvx](https://user-images.githubusercontent.com/108592928/216823322-57e4796d-349b-4b2f-8cf5-2b3fa67cb609.png)
Already implemented

**Comment by kazimmt** [comment]
Different name.
I see
Thanks tho
