### ISSUE TITLE
bug: (Youtube) Chapters menu doesn't work in Landscape mode.

### ISSUE THREAD

**Issue by fedonr** [inotia00/ReVanced_Extended#2170]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v19.21.40

### Bug description

Ideally when in landscape(full screen mode) when you tap on chapters in seekbar it should pop-up a chapters menu on the right side keeping the orientation landscape, while here it takes me back to Portrait mode when I tap on chapters in Full screen.

https://github.com/inotia00/ReVanced_Extended/assets/120009841/c1fe434c-97db-4262-84d9-a4c71b1712d5

### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Exclude patches one by one and report back which patch is the cause of the issue

**Comment by fedonr** [comment]
Ah! I'm sorry, I'm closing this, I gave 3 hours to it removing each patch from top to bottom one by one and kept updating app with each apk, the issue randomly came up in certain patching and went away. 

Then I realised the issue was with my cache memory clearing storage data fixed it.

**Comment by inotia00** [comment]
It's weird but it's okay
