### ISSUE TITLE
bug: (YouTube - Spoof Client): playback error occurs

### ISSUE THREAD

**Issue by akir45** [inotia00/ReVanced_Extended#2171]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.20.35
patch v4.9.2-dev.1

### Bug description

When I spoof to the iOS, Android VR client and play the live stream and open YouTube with audio only, an error may occur. The error does not occur in Android VR.

https://github.com/inotia00/ReVanced_Extended/assets/91464996/704300cd-1d58-45a9-97d3-6873f8bdc36a

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is known side effects

**Comment by akir45** [comment]
Sorry, I misspelled the letters. is the error that occurs in Android VR also a known issue?
