### ISSUE TITLE
bug(YouTube - Hide carousel shelf): new types of shelves does not hidden

### ISSUE THREAD

**Issue by n1cKz1** [inotia00/ReVanced_Extended#2172]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube

### Bug description

New types of carousel/horizontal shelves have started showing up. Here's an example of the breaking news one

![Screenshot_2024-06-20-04-13-10-678-edit_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/107653639/ed7da95a-5e8c-4333-bcb1-f0b11258bb9c)

### Solution

Component name is `horizontal_shelf_inline.eml`

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
