### ISSUE TITLE
bug(YouTube - Hide quick actions components): `Hide Open mix playlist button` and `Hide Open playlist button` aren't working 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2174]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.21.40

### Bug description

`Hide Open mix playlist button` and `Hide Open Playlist button` doesn't hide their respective buttons.

![Screenshot_20240621_004000_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/698d7539-7d73-4390-8eb3-157f406869c9)
![Screenshot_20240621_004239_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/740b9ce2-dbd1-4737-82e9-68b866841946)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
