### ISSUE TITLE
Account menu filter issue

### ISSUE THREAD

**Issue by Gubbbka** [inotia00/ReVanced_Extended#2176]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

19.20.40

### Bug description

Unable to turn off "get youtube premium" via filters whith russian language. Other buttons i can disable I think it caze YT prem wrote on english
P.S: how put away that 3 lines which placed after every 2 buttons
![Screenshot_20240621_212921_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/169579036/b4dc9c51-c8fa-4025-bd08-42c61e5ec7ba)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I don't know why either, but the Russian strings applied to the YouTube layout are coded a little strangely
(bugs in YouTube)

You can hide it normally by referring to this comment:
https://github.com/inotia00/ReVanced_Extended/issues/1423#issuecomment-1736007858
