### ISSUE TITLE
bug(YouTube): `Hide animated button background` patch doesnt work

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#2179]
### Type

Other

### Tools used

Revancify

### Application

yt 19.19.39

### Bug description

"hide animated button background" patch doesnt hide the dark circular background surrounding play/pause buttons in shorts

### Error logs

```shell
none
```

### Solution

.

### Additional context

![Screenshot_20240622-215634_Trebuchet](https://github.com/inotia00/ReVanced_Extended/assets/87489540/96deb90b-f36f-483d-a413-25b573c1f5a2)

![Screenshot_20240622-215555_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/87489540/564cf4a5-3d90-4375-a0ed-c2bc62d5b17b)

![Screenshot_20240622-215553_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/87489540/bc0acba4-2cac-40b6-974e-42fa59299cb8)

### Device Environment

los18 a11

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
