### ISSUE TITLE
feat(patch): Add string "Included" to the Crowdin translation

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#218]
### Application

YouTube

### Issue

The string "Included" in Patches Information still shows English in all languages.

### Patch

![IMG_20230205_233246](https://user-images.githubusercontent.com/54460494/216832304-21708576-1da3-468e-9696-e0d2090035f8.png)

### Motivation

I think you should add this string to the Crowdin translation so that it is translated and consistent with the current RVX languages.
Everyone loves 100% localized languages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I don't provide a translation to this screen, because I need to refer this screen to a bug report

**Comment by KobeW50** [comment]
> I don't provide a translation to this screen, because I need to refer this screen to a bug report

Is it possible to write both in English and the translated language?

Something like:

* Hide Create Button

Included / Включено

**Comment by inotia00** [comment]
It's theoretically possible, but it takes 2-3 times longer to open the settings
