### ISSUE TITLE
bug(YouTube/Hide action buttons) : empty space is left after hiding all action buttons under videos

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2180]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v19.16.39

Patches v4.9.2-dev.1

### Bug description

Earlier, when I used to hide all action buttons in video player, there was no empty space.

But now it is something like this, so kindly fix this.

![Screenshot_2024-06-23-07-18-19-62_fe557b5c831afa8eecca413bd340ebe7](https://github.com/inotia00/ReVanced_Extended/assets/91815107/c2ebcfbb-8ce0-41b7-b238-84c26f1b90aa)

Settings:

![Screenshot_2024-06-23-07-18-44-39](https://github.com/inotia00/ReVanced_Extended/assets/91815107/913e94d0-c7d5-4c56-8e83-ff4d307e7a4c)

### Error logs

```shell
No logs.
```

### Solution

When all action buttons are hidden, no empty space should be left.

It was fine earlier, but now suddenly I'm getting that empty space.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro on Realme UI 3.0 (Android 12).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.9.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.2)
