### ISSUE TITLE
bug: Translucent navigation bar is not translucent

### ISSUE THREAD

**Issue by akir45** [inotia00/ReVanced_Extended#2182]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.23.40
patch v4.9.2-dev.2

### Bug description

translucent navigation bar is not translucent only when scrolling down. I don't know if this is a bug or a YouTube spec...

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is why the patch is flagged as `Experimental flags`.
