### ISSUE TITLE
bug: translucent navigation bar not always visible

### ISSUE THREAD

**Issue by Kevinr99089** [inotia00/ReVanced_Extended#2183]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.23.40

### Bug description

The translucent navigation bar only works when scrolling up, and only in the "Subscription" section.
As for the translucent navigation bar that becomes opaque when you scroll down, I have the impression that this happens when the top bar disappears.

https://github.com/inotia00/ReVanced_Extended/assets/93716347/28a3a328-1d79-4351-9b74-ee89df0350b6

### Solution

Scroll up

### Device Environment

Samsung Galaxy S23, Android 14, OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2182
