### ISSUE TITLE
bug: YT - Slide up gesture not working on any `Modern Miniplayer`

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2185]
### Type

Other

### Tools used

rvx-builder

### Application

Latest supported

### Bug description

Sliding up the miniplayer to go to expand the video player not working. Previously it is working fine with every type of Miniplayer. But, after updating with latest patches, it is not working. Currently it is only working for phone and tablet version.

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2142
