### ISSUE TITLE
bug(YouTube): `Skip` button doesn't work after playing Shorts

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2186]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.23.40
Patches v4.9.2

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/406ba207-ba13-4ed5-9e82-4866da0c1203

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/1538
