### ISSUE TITLE
feat(patch): hide collapse button in fullscreen 

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#219]
### Application

YouTube

### Issue

When fullscreen is entered there is this annoying button at the top left. When you tap it (accidentally) it exits fullscreen and makes the entire app go into landscape mode (very annoying)
Please add a patch to remove that button. Entirely useless. 
(We can already exit fullscreen by swiping down and this way it doesn't turn the app into landscape...)
### Patch

https://user-images.githubusercontent.com/73917917/216839021-04f45779-515d-4ca1-8c75-ac08b51c648b.mp4

### Motivation

Annoying button should be removed. It makes app go into landscape mode...

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.163.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.163.1)

**Comment by anyujinie** [comment]
Thx for adding this 🙏🏻❤️
