### ISSUE TITLE
suggestion (YT) : Try to eliminate these side effects of `Android VR client` & `iOS client`.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2190]
### Application

YouTube

### Suggestion description

If these side-effects are eliminated, then these spoof clients will become near-perfect:

1. Android VR : `Paused videos can randomly resume.`
2. iOS : `Higher video qualities may not be available.`

Even if either of the above 2 are solved, it will be great.

Thanks!

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Regardless of this suggestion, I always try to fix the side effect, but there is no success

Even if the suggestion is not opened, if a valid fix is ​​found, it will be reflected in the patch

Closing issue
