### ISSUE TITLE
bug(YouTube/Shorts components): `Hide sound button` doesn't work 

### ISSUE THREAD

**Issue by imvoldemort** [inotia00/ReVanced_Extended#2193]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.23.40

### Bug description

Hide sound button in shorts player settings doesn't work.
![IMG_20240624_155255](https://github.com/inotia00/ReVanced_Extended/assets/159900453/aeaeec26-02e1-4836-85e3-e7a2618dd2ca)
![IMG_20240624_155157](https://github.com/inotia00/ReVanced_Extended/assets/159900453/6affe747-b937-41bd-acda-cbbec86d151e)

### Device Environment

Android 10, MIUI 12.5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.1)
