### ISSUE TITLE
[Bug] shorts title doesn't exist 

### ISSUE THREAD

**Issue by TheTrueShadow** [inotia00/ReVanced_Extended#2194]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.25.33

### Bug description

![Screenshot_20240625_112954](https://github.com/inotia00/ReVanced_Extended/assets/80232013/ac6a771b-f5c8-47f2-941b-1e49872ceab6)
![Screenshot_20240625_112950](https://github.com/inotia00/ReVanced_Extended/assets/80232013/e1ddc3d4-48dc-4e02-a80d-9d9a5f190763)
![Screenshot_20240625_112946](https://github.com/inotia00/ReVanced_Extended/assets/80232013/cf21c44a-5864-4252-95fc-cbc6470ef3f8)
![Screenshot_20240625_112942](https://github.com/inotia00/ReVanced_Extended/assets/80232013/45252e18-e552-4361-8c42-3ed8beaa622c)
![Screenshot_20240625_112932](https://github.com/inotia00/ReVanced_Extended/assets/80232013/688ac62d-71ec-4061-ad2d-9bce51445fae)

The bug is that the shorts title and anything on the bottom left doesn't appear 

All patches applied are below

"alt_thumbnail_dearrow_connection_toast": true,
"custom_seekbar_color_value": "#ff0000",
"default_video_quality_mobile": 720,
"default_video_quality_wifi": 1080,
"disable_ambient_mode": true,
"enable_custom_playback_speed": true,
"enable_custom_seekbar_color": true,
"hide_info_cards_section": true,
"hide_podcast_section": true,
"hide_shorts_full_video_link_label": false,
"hide_shorts_info_panel": false,
"hide_shorts_subscribe_button": false,
"overlay_button_external_downloader": true,
"overlay_button_speed_dialog": false,
"remove_viewer_discretion_dialog": true,
"spoof_app_version": true,
"spoof_client_stats_for_nerds": false,
"spoof_player_parameter": true,
"swipe_overlay_text_size": 27,

"sb_compact_skip_button": true,
"sb_filler": "manual-skip",
"sb_interaction": "skip",
"sb_intro": "skip",
"sb_local_time_saved_milliseconds": 7398386,
"sb_local_time_saved_number_segments": 287,
"sb_music_offtopic": "skip",
"sb_outro": "skip",
"sb_preview": "skip",

"sb_toast_on_connection_error": true,
"sb_voting_button": true

### Error logs

```shell
N/A
```

### Solution

N/A

### Additional context

I don't remember when it started it has been at least 2 months 

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.25.33 is not a supported version
