### ISSUE TITLE
bug(YouTube/Hide feed components): View count filter doesn't hide videos with zero views

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2195]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.23.40
Patches version 4.9.2

### Bug description

The `Hide recommended videos by views` setting does not hide videos with zero views. 

![Screenshot_20240625_184621_YT Extended](https://github.com/inotia00/ReVanced_Extended/assets/84587632/c308d1eb-e593-43d3-934f-d840d94f3e7d)

### Additional context

The `Hide recommended videos by view count` setting is enabled, and it is set to hide videos with less than 1000 views.

Note: It is an assumption I made that this is specific to videos with zero views. This is the only time I've ever seen the view count filter fail. Also, I only saw this issue in the related videos feed. I can't confirm whether this issue occurs in other feeds, since it is very difficult to replicate.

I understand that there is basically no point in fixing this bug since it is so minor and rare.

### Device Environment

Android 14.
OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.1)
