### ISSUE TITLE
bug: Manager successfully patches, can't install due to package conflicts with the pre-installed youtube client.

### ISSUE THREAD

**Issue by WAS-D** [inotia00/ReVanced_Extended#2196]
### Type

Other

### Tools used

RVX Manager

### Application

 Any version of RVX Manager, any version of youtube using the current patches

### Bug description

everything executes correctly, but the package built by RVX Manager isn't differentiated from com.google.youtube, as it tries to overwrite the pre-installed version without root. 

Steps to reproduce: 
Install RVX manager. 
Grab the latest default patches
Grab youtube 19.23.40 to patch without root
patch
package attempts to override the pre-installed youtube version. 

Something interesting here, is that the reddit and YTM patches cannot simply grab from an installed app without root, and must grab an apk from storage, yet Youtube proper doesn't have said restriction. 

it is, like 12:30 am, i am tired. i woulf provide screenshots, but it's just a loop of the manager saying that there is a conflict, to uninstall, and then doing that, and then it being unable to go past the first version of Youtube that came with my device. 

My way of bypassing it is just to download a pre-built binary. This only happens after patching youtube proper. 

### Solution

i suspect it has something to do with the patches not changing the package name properly, as old forks such as anddea's patches do not have this conflict.

### Additional context

the base youtube app comes pre installed on many phones, so without root it is impossible to patch using the manager this way. 

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
For non-root YT installations you must include the GmsCore support patch.

**Comment by inotia00** [comment]
I do not distribute pre-installed APKs due to DMCA takedown risk

Try again including the `GmsCore Support` patch

**Comment by WAS-D** [comment]
issue still persists with purely the GmsCore Support patch added, but not after adding the "Change branding name" Patch. 

I am stupid though. A lot of patches that were included by default aren't anymore. Huh.

**Comment by inotia00** [comment]
In recent releases, many patches have been merged or renamed through PRs

If your RVX Manager has not been reinstalled in a while, you may need to manually include some patches

**Comment by WAS-D** [comment]
This happened on a fresh install for me though. Then again, the alternative patch sources i was using persisted after a reinstall using the github apk. Idk. It's weird. Thanks again.
