### ISSUE TITLE
bug(YouTube/Theme): Down arrow in live chat is white in amoled theme

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2197]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.21.40

### Bug description

The down arrow to scroll to the bottom in live chat is white all the time and only when tapping the button will it show the arrow itself. 
<details><summary>Details</summary>
<p>

In RVX:

https://github.com/inotia00/ReVanced_Extended/assets/117499019/3358ea5c-c33a-4fbc-8be5-540a3fb45aa6

In stock (same version):
![Screenshot_20240626_165145_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/0a28df93-06f8-4b86-b886-c9e38e1fd8ae)

</p>
</details> 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
> In stock (same version):
> ![Screenshot_20240626_165145_YouTube](https://private-user-images.githubusercontent.com/117499019/343136574-0a28df93-06f8-4b86-b886-c9e38e1fd8ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDYxNTMsIm5iZiI6MTcxOTQwNTg1MywicGF0aCI6Ii8xMTc0OTkwMTkvMzQzMTM2NTc0LTBhMjhkZjkzLTA2ZjgtNGI4Ni1iODg2LWM5ZTM4ZTFmZDhhZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMjQ0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGY3MjUyNTRmZmRlMWRhMzVlNDk1NDllN2YzMmZjZmY5MDcwNDk2MzhiMDVjYjExMmI1MWRjMGI1ZjQ3NzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YKp_NrMZ3z7N6Iw089OnM7rk-mNgQ_RRl1AuDVWQ7dU)

The background color of the button on the latest YouTube doesn't look good (visibility is too bad)

It would be better to roll back the YouTube button background color to the previous version

**Comment by ILoveOpenSourceApplications** [comment]
> The background color of the button on the latest YouTube doesn't look good (visibility is too bad)

Agreed. It should've been a white circle with a black arrow. But hey, it's YouTube. 

> It would be better to roll back the YouTube button background color to the previous version.

In 19.16.39, it's a blue circle with white arrow for light and dark theme. Now in light theme, it's a black circle with white arrow, but the opposite isn't implemented properly in dark theme.

**Comment by inotia00** [comment]
yeah in recent months, Google has been making some big and small mistakes in Android YouTube

It would be better to use the the old button background until the issue with YouTube is resolved

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.1)

**Comment by inotia00** [comment]
Looks like Google fixed this bug on the server side

This bug is no longer reproducible on unpatched YouTube 19.21.40

I will revert https://github.com/inotia00/revanced-patches/commit/bb916a7dcdcac94138bdbb0a879768adc819a16b
