### ISSUE TITLE
Translation language not removed from setting 

### ISSUE THREAD

**Issue by NichirinSword** [inotia00/ReVanced_Extended#2199]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.23.40

### Bug description

I removed all the string languages and RVX languages from Translation patch but Languages not removed from YouTube. Still shows in YouTube General Setting menu.

### Additional context

Patches from anddea solves this problem. Patching with his patch removes all the languages which are not included in the list.

### Device Environment

Android 14, RealmeUI 5.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As intended by the `Translations` patch, it only removes the language list on the resource at compile time.
`Translations` patch does not remove languages ​​from bytecode.
