### ISSUE TITLE
feat(patch): Display video quality when player is tapped

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#22]
### Application

YouTube

### Issue

Please consider adding a feature that would display the video quality when tapping the video. I don't like the fact that current video quality is hidden in that settings wheel. It should show somewhere in the player ui when the player is tapped.

### Patch

![Screenshot_20221222-182634469 (1)](https://user-images.githubusercontent.com/73917917/209192938-49e67bb2-904a-4a92-9563-cebec72d011a.png)

![Download](https://user-images.githubusercontent.com/73917917/209192956-baa7a505-777d-40df-8906-5f745f0617fd.png)

### Motivation

Displaying the video quality when player is tapped seems convenient. It shouldn't be hidden in the settings wheel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
@inotia00 Any chance for this feature request to get added?

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
