### ISSUE TITLE
question: <title>: Video playback not working 

### ISSUE THREAD

**Issue by Love2316** [inotia00/ReVanced_Extended#220]
### Application

YouTube

### Description

I’m sorry, may I ask why I’ve been stuck in the buffer when I log in to my account to watch the video after downloading, but I can watch the video normally after turning on the incognito mode, thank you very much
![FB_IMG_1675628668815](https://user-images.githubusercontent.com/124529770/216842964-e7c7ab0d-e432-49e1-9d94-956b64211532.jpg)
``

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/141
