### ISSUE TITLE
bug(Reddit) : Some patches are not working on Reddit `2024.26.1`+

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2200]
### Type

Error at runtime

### Tools used

Revancify

### Application

Reddit v2024.26.1, but wasn't working in v2024.25.3 either.

Patches: https://github.com/inotia00/revanced-patches-arsclib/releases/tag/v2.177.1

Integrations: https://github.com/inotia00/revanced-integrations/releases/tag/v1.11.1-dev.1

### Bug description

`Remove Notification Suggestion Dialog` is enabled in the settings, but it is not working. To reproduce it:

1. Go to any subscribed subreddit that you've never visited before.
2. Open any post & scroll a bit for 2-3 seconds. Then press back button.
3. Now `Notification Suggestion Dialog` will be shown.

![Screenshot_2024-06-26-07-22-02-77_b72a20be883aec8a014bd2b7c7038e87](https://github.com/inotia00/ReVanced_Extended/assets/91815107/838d9720-1501-4a62-b6d8-b88cc9c589f5)

![Screenshot_2024-06-26-07-21-39-29_b72a20be883aec8a014bd2b7c7038e87](https://github.com/inotia00/ReVanced_Extended/assets/91815107/89da0139-8601-44dc-bf4f-16ca9e6edacc)

### Error logs

```shell
No logs.
```

### Solution

Rollback to Reddit 2024.25.3

### Additional context

No additional context.

### Device Environment

Realme 7 Pro.

Android 12 (Realme UI 3.0).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In Reddit 2024.26.1+, obfuscation is applied to most classes, so there are cases where the patch is not applied even if the patch is successful.

The workaround is to roll back to Reddit 2024.25.3, a version that does not have obfuscation applied to the class.

**Comment by Aryan-Chauhan** [comment]
New information: Till yesterday I was using v2024.25.3 and that feature wasn't working in it, either.

I added this info in application description.

**Comment by inotia00** [comment]
It may have been fixed by https://github.com/inotia00/revanced-integrations/commit/eebd225262d4fb141d6202bebc6d2e6f9f1f7987

**Comment by sir-harlekin** [comment]
2024.25.3+ still not patching for me, are there any tipps?

**Comment by inotia00** [comment]
read docs:
https://github.com/inotia00/revanced-documentation/blob/main/docs/latest-reddit-patch-info.md

**Comment by sir-harlekin** [comment]
I did patching via CLI in the past but somehow I cant get it to work. Is it necessary to specify options.json? Or is the Version I am trying to use not supported (v28.2024)? I always get option.json incorrect or missing error.

**Comment by inotia00** [comment]
Please open a new issue including the error log (screenshot)
