### ISSUE TITLE
bug(YouTube/Disable forced auto captions): Subtitles don't work after playing Shorts

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2202]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.23.40
Patches v4.10.1-dev.2

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/47c26fc9-6de8-4667-b471-47787dea7d13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This appears to be a side effect of the Spoof client

**Comment by inotia00** [comment]
To provide additional information from other users experiencing the same issue, please add the `Spoof client` setting value you are using

e.g.
Spoof client:
ON

Spoof client options
General:
iOS

Live streams:
Android VR

Shorts, Clips:
iOS

Unplayable video:
Android Testsuite

**Comment by Kuddus73** [comment]
@inotia00 I don't even have the spoofing enabled:
![Screenshot_20240629_045544_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/127908708/2188d757-760c-4c59-b89f-faa138f1a974)

**Comment by inotia00** [comment]
Then, I have no idea

please exclude patch one by one and report back

**Comment by Kuddus73** [comment]
> please exclude patch one by one and report back

From my testings it's caused by `Disable forced auto captions`.

**Comment by inotia00** [comment]
issue does not reproduce on my side

**Comment by Kuddus73** [comment]
> issue does not reproduce on my side

@inotia00

https://github.com/inotia00/ReVanced_Extended/assets/127908708/f78673b2-9b65-47dd-8e27-e64e59541858

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2)
