### ISSUE TITLE
question: Is there a way to change default rvx settings for apks

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2203]
### Application

YouTube

### Question description

When i install apk the cast button is hidden by default there are some people i know that want rvx but they don't know how to turn some settings on so is there way to change default settings?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
You can export your settings configuration to a `.txt` file and then import it.

Settings > ReVanced Extended > Miscellaneous > Import / Export settings

**Comment by inotia00** [comment]
Unlike KobeW50's answer, I will explain how to change it in the source code:

It follows the default values ​​specified in Settings.java

For example, to change the default value of `Hide cast button` (in player) to OFF, you would change it like this:

https://github.com/inotia00/revanced-integrations/blob/fef430618ca30b9cbf12fc70cb5420b4506fe291/app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java#L307

Change
```
public static final BooleanSetting HIDE_PLAYER_CAST_BUTTON = new BooleanSetting("revanced_hide_player_cast_button", TRUE, true);
```
To
```
public static final BooleanSetting HIDE_PLAYER_CAST_BUTTON = new BooleanSetting("revanced_hide_player_cast_button", FALSE, true);
```

**Comment by AykhanUV** [comment]
How can i acces the source code? Plus after modifying the source code how can i build the apk again

**Comment by AykhanUV** [comment]
hey i just did it and built the apk but the result is same
![Screenshot_2024-07-05-20-20-36-301_ru zdevs zarchiver](https://github.com/inotia00/ReVanced_Extended/assets/172329144/401865c2-9b03-4267-bb5e-8d8d2a434ae7)

**Comment by AykhanUV** [comment]
maybe i have to change something else?
