### ISSUE TITLE
bug: Unable to delete some setting in YouTube menu

### ISSUE THREAD

**Issue by Alxon4789** [inotia00/ReVanced_Extended#2204]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube: v19.16.39
CLI: inotia00-cli-v4.6.1.jar
Patches: inotia00-patches-v4.10.1-dev.2.jar
Integrations: inotia00-integrations-1.11.1-dev.2.apk

### Bug description

Using the filter for deleting YouTube settings, it is not possible to delete "Your data in Youtube" (in Polish is "Twoje dane w Youtube"), even though I clearly typed it next to the others. I tried different combinations of words (in my language, of course). I encountered that this error occurs only in the Polish language version. As evidence, I send screenshots and patchlog.
[patch_log.txt](https://github.com/user-attachments/files/16037461/patch_log.txt)

<img src="https://github.com/inotia00/ReVanced_Extended/assets/143010511/43d2abca-e372-4a45-be77-f9b076de6acb" width=50% height=50%><img src="https://github.com/inotia00/ReVanced_Extended/assets/143010511/d46f552e-6561-477e-ada4-af63294c42ac" width=50% height=50%>

### Device Environment

Poco F4
Android 14
Paranoid Android Uvite Beta 4

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/1964
