### ISSUE TITLE
question: Hiding playlist recommendations below player

### ISSUE THREAD

**Issue by RoonMoonlight** [inotia00/ReVanced_Extended#2206]
### Application

YouTube

### Question description

Hello, is there any ways to hide playlist that sometimes appears below player?

It seems to be happening for some videos and streams and wondering if there is a actual way to remove it completely below playlist.

Below is an screenshot of playlist appearing from some streams:
![Screenshot_20240629_221244_YouTube RVX](https://github.com/inotia00/ReVanced_Extended/assets/25527589/9a8b3eae-4d83-4da0-b5ac-588f8f36320e)

P.S. No, this is not an mix playlist.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is already implemented as a patch

turn on:
`Settings > ReVanced Extended > Feed > Hide carousel shelf`
