### ISSUE TITLE
bug(YouTube/Spoof client): some videos cannot be played

### ISSUE THREAD

**Issue by JakobHunterek** [inotia00/ReVanced_Extended#2207]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube 19.23.40

### Bug description

Livestreams stops playing in the background when minimizing for a second time without interrupting the stream. Returns with a different error code. 
1. Visit any livestream 
2. Fully Minimize YouTube to background
3. Open YouTube fully again
4. Repeat step 2
You get an error code
![Screenshot_20240629_233648_RVX](https://github.com/inotia00/ReVanced_Extended/assets/139505017/d0bd4fca-64bc-4147-a5a0-5d76953ed62a)

### Solution

Close the stream and reopen again for the background play to work in the first try

### Additional context

All patches selected from revancify as recommended (plus materialyou, minus swipe controls)
This issue does not appear when playing normal YouTube videos (VODs) in background.

### Device Environment

Android 14 OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Try changing all spoofing options to iOS in `Settings > ReVanced Extended > Miscellaneous > Spoof client`
And report back the results

**Comment by JakobHunterek** [comment]
Here are the results after I changed my spoofing options for livestreaming
iOS: Doesn't play in background as expected
Android VR: Stops playing in background after minimizing it for a second time with an error code

My default settings:
General: iOS
Livestreams: Android VR
Shorts, clips: iOS
Substitute: Test client

**Comment by inotia00** [comment]
Thank you for reporting back
It looks like the side effects of the Android VR client need to be updated

**Comment by Dimedro11** [comment]
Please note that this error has not been fixed. The problem disappears when rolling back to patch version 4.10.1 Android 14 Operating system OneUI 6.1 shell
![Screenshot_20240717_213740_Settings](https://github.com/user-attachments/assets/5e9cdd56-b767-472d-9706-e556a1fc0c79)

https://github.com/user-attachments/assets/930bc49e-7fb2-4a61-8ecb-72bae13d11b3

![Screenshot_20240717_213433_YouTube](https://github.com/user-attachments/assets/933756c1-997c-432c-9d3f-2a3b630e224e)

**Comment by GKid94** [comment]
![Screenshot_2024-07-20-15-13-57-526_app rvx android youtube](https://github.com/user-attachments/assets/9529b067-5f4c-4150-bfe7-58e538c6ca98)

**Comment by GKid94** [comment]
![Screenshot_2024-07-28-20-18-12-772_app rvx android youtube](https://github.com/user-attachments/assets/3cbc754d-a7fd-464a-8528-69dfe5ee9610)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
