### ISSUE TITLE
question: Title less clickbait DeArrow

### ISSUE THREAD

**Issue by Kevinr99089** [inotia00/ReVanced_Extended#2208]
### Application

YouTube

### Question description

Hello, there's a patch for DeArrow that replaces the thumbnails, but the other DeArrow function that also makes titles less clickbait isn't present.
Do you plan to add it one day, or are the titles on the application more complicated (if not impossible) to modify unlike the browser extension?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Well... ReVanced Team has implemented the `Alternative thumbnails` patch
I don't think I will implement it
