### ISSUE TITLE
bug(YouTube/Spoof client): `Spoof client` not working

### ISSUE THREAD

**Issue by GKid94** [inotia00/ReVanced_Extended#2209]
### Type

Error at runtime

### Tools used

CLI

### Application

![Screenshot_2024-06-30-10-30-12-775_com miui securitycenter](https://github.com/inotia00/ReVanced_Extended/assets/18757054/be1b3767-6b6d-4b63-bb8e-22c39d708270)

### Bug description

Videos often keep buffering and won't respond 
![Screenshot_2024-06-30-10-27-42-922_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/18757054/43ffc23f-e0a8-4e1a-8f75-ec143696815a)

### Device Environment

![Screenshot_2024-06-30-10-30-23-395_com android settings](https://github.com/inotia00/ReVanced_Extended/assets/18757054/388bd814-983b-46b8-9f29-2663f7ea58da)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by GucekPL** [comment]
Enable client spoof

**Comment by GKid94** [comment]
It's enabled
![Screenshot_2024-06-30-15-11-17-042_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/18757054/e79b47ca-b865-49d5-896a-54a04f5e8988)

**Comment by inotia00** [comment]
Try changing all spoofing options to iOS in `Settings > ReVanced Extended > Miscellaneous > Spoof client`
And report back the results

**Comment by GKid94** [comment]
![Screenshot_2024-07-02-12-54-37-780_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/18757054/4b0b73eb-75f0-4fa6-ac3b-3a3c04ed83ee)
![Screenshot_2024-07-02-13-00-33-553_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/18757054/e7000062-e009-436d-a3ab-83b2e04e63ba)

**Comment by inotia00** [comment]
You can keep track of issue at https://github.com/inotia00/ReVanced_Extended/issues/2207

**Comment by GKid94** [comment]
👍
