### ISSUE TITLE
bug: grey separator in youtube

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#221]
### Type

Other

### Application

18.04.41

### Bug description

enable web search panels, find grey separator between video and web search results which is visually appalling especially in amoled black theme.

### Steps to reproduce

enable web search panels, find grey separator between video and web search results which is visually appalling especially in amoled black theme.

### Relevant log output

```shell
none
```

### Screenshots or videos

![Screenshot_20230206-000005_YouTube](https://user-images.githubusercontent.com/87489540/216843075-2f077b52-6bef-43de-a427-b4c7928e0c6e.png)

### Solution

modify the already existing hide grey separator patch.

### Device Environment

LOS 18.1 A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The gray separator in the screenshot is included in the web search panel
(part of the web search panel)

So it is not a bug that it is shown
