### ISSUE TITLE
bug(YouTube/Hide ads): new ads are not blocked

### ISSUE THREAD

**Issue by GKid94** [inotia00/ReVanced_Extended#2210]
### Type

Error at runtime

### Tools used

CLI

### Application

![Screenshot_2024-06-30-13-24-42-958_com miui securitycenter](https://github.com/inotia00/ReVanced_Extended/assets/18757054/be6072bd-a5ae-4a84-9891-f6cdb033a824)

### Bug description

Ads showing
![Screenshot_2024-06-30-13-24-01-662_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/18757054/0718eef2-2f21-42bf-8332-0a264f57cc8a)
![Screenshot_2024-06-30-13-24-07-123_com miui home](https://github.com/inotia00/ReVanced_Extended/assets/18757054/17ed3c9a-6d62-41d6-af3c-b847592e3544)

### Device Environment

![Screenshot_2024-06-30-13-24-34-874_com android settings](https://github.com/inotia00/ReVanced_Extended/assets/18757054/259bc435-afd8-446e-af40-c3c793ee6286)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.1)

**Comment by GKid94** [comment]
👍
