### ISSUE TITLE
suggestion(RVX Manager): Remove `Show universal patches`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2211]
### Application

Other

### Suggestion description

As RVX doesn't support any universal patches, it's an obsolete option and removing it would make sense. 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
People can change the sources in the Manager to one with universal patches

**Comment by Kuddus73** [comment]
> it's an obsolete option and removing it would make sense.

Why would it make sense to remove a useful feature?

> People can change the source in the Manager to one with universal patches

Exactly.

**Comment by ILoveOpenSourceApplications** [comment]
Quoting inotia00
"RVX Manager is provided simply for compatibility with my patch, if you run into issues follow the other patch method."

Also, If you're someone using universal patches you can install ReVanced Manager as well.

**Comment by KobeW50** [comment]
> Quoting inotia00
> "RVX Manager is provided simply for compatibility with my patch, if you run into issues follow the other patch method."
> 
> Also, If you're someone using universal patches you can install ReVanced Manager as well.

At that point, you can even remove all of the Alternative sources options and have it always set to inotia00.

Forks of RVX recommend patching on the RVX Manager instead of the ReVanced Manager (likely for the same reason the RVX Manager was created for)

And it doesn't make sense for inotia00 to put in work to remove a feature that doesn't cause any issues.

**Comment by Kuddus73** [comment]
> Quoting inotia00
> "RVX Manager is provided simply for compatibility with my patch, if you run into issues follow the other patch method."
> 
> Also, If you're someone using universal patches you can install ReVanced Manager as well.

Why would I install **another** app if the same app can do it without any issues?
You are seeing problems where there aren't any.

> At that point, you can even remove all of the Alternative sources options and have it always set to inotia00.

> And it doesn't make sense for inotia00 to put in work to remove a feature that doesn't cause any issues.

 Again, exactly.

**Comment by ILoveOpenSourceApplications** [comment]
It's a suggestion after all, and if inotia00 agrees it'll get removed and if not, it'll stay.
