### ISSUE TITLE
bug: (YouTube/miniplayer)It cannot be swiped to expand or close.

### ISSUE THREAD

**Issue by akir45** [inotia00/ReVanced_Extended#2212]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.25.39
patch 4.10.1

### Bug description

When double-tap action is enabled on modern 1, I cannot swipe to expand and close.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
it's not a bug

It only works when `Enable double-tap action` and `Enable drag and drop` are both off
