### ISSUE TITLE
suggestion(Youtube/Shorts): Including "Shorts" in hide paused overlay buttons patch

### ISSUE THREAD

**Issue by 0frd** [inotia00/ReVanced_Extended#2213]
### Application

YouTube

### Suggestion description

Hide "Shorts" when the shorts paused would be nice
![Screenshot_2024-07-05-14-25-50-714_com google android youtube-edit~2](https://github.com/inotia00/ReVanced_Extended/assets/72485140/41390a11-e117-44b7-8850-e513c7488707)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Normally I don't accept feature requests from YouTube

This setting was implemented in an old RVX patch, so it will be reflected in the next release

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2)
