### ISSUE TITLE
bug: Links keep opening regular YouTube 

### ISSUE THREAD

**Issue by GKid94** [inotia00/ReVanced_Extended#2214]
### Type

Error at runtime

### Tools used

CLI

### Application

![Screenshot_2024-07-05-11-40-37-682_com miui securitycenter](https://github.com/inotia00/ReVanced_Extended/assets/18757054/ad993308-eb78-4e31-be5a-412163da745e)

### Bug description

YouTube links open regular YouTube instead of Revanced
![Screenshot_2024-07-05-11-39-48-661_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/18757054/8a96f6b1-a7d0-4325-a65e-950de6b86054)
![Screenshot_2024-07-05-11-43-21-606_com android settings](https://github.com/inotia00/ReVanced_Extended/assets/18757054/637bcd63-c0df-4711-9f12-4d8360494e90)

### Device Environment

![Screenshot_2024-07-05-11-40-45-711_com android settings](https://github.com/inotia00/ReVanced_Extended/assets/18757054/58a08ee5-adb2-41f2-bf98-e22f940ba42a)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's a policy in Android 12+, not a bug in RVX

**Comment by GKid94** [comment]
Can you maybe add a force option?
