### ISSUE TITLE
question(YouTube/Description): Why tap & hold to copy text in description not work?

### ISSUE THREAD

**Issue by sr-shishir** [inotia00/ReVanced_Extended#2215]
### Application

YouTube

### Question description

Today I got a screenshot from a user whose YouTube v19.23.40 (Patched with RVX manager) **_Tap and Hold to Copy text_** from description working fine. BUT mine and almost all users don't work this feature. So, what's the drawback here? Is it an internal bug or there is something that I missed? It was a very useful feature. 😓

If it's not fixable then how this dude's YouTube working?
![Copy text](https://github.com/inotia00/ReVanced_Extended/assets/139035194/bf471648-c03b-4b5a-a644-62ac84de2b63)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Above screenshot is from my phone, I'm that user.

It is working fine for me.

**Comment by inotia00** [comment]
This feature is only available with Google accounts registered for A/B tests
(server-side)
