### ISSUE TITLE
feat(YouTube Music): add `Visual preferences icons` patch

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2216]
### Application

YouTube Music

### Feature description

Can you add visual prefrences icons to yt music? I saw this feature in anddea patches so can you bring it to rvx?

### Motivation

This makes the app look very good still youtube music does not have it

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The current way of copying all drawable vectors increases the file size of the entire Patches, but not significantly

(It's only about 300KB or less)

It also doesn't affect the resulting file size of the patched app at all

It's definitely better than the current way, but it's not the best solution either

It seems the best way is to create an Enum class that contains a set of icon paths and keys, and handle them in that

**Comment by anddea** [comment]
> It also doesn't affect the resulting file size of the patched app at all

True, the patches' size is slightly smaller; the app size remains the same.

> It seems the best way is to create an Enum class that contains a set of icon paths and keys, and handle them in that

It might be a good idea for better organization, but the implementation may be a bit more complex. I’m fine with either option.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
