### ISSUE TITLE
suggestion (YT) : `Bold, Rounded & Thin Icons` for the Gear Icon / Settings Icon in player.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2217]
### Application

YouTube

### Suggestion description

This Gear Icon / Settings Icon should also have `Bold, Rounded & Thin Icons` similar to the corresponding designs of Overlay Buttons.

Can the designer who designed `Bold, Rounded & Thin Icons` design this also?

![Screenshot_2024-07-05-20-47-52-62_a9acfd2263b6b7a65bf2540b0d9449ca](https://github.com/inotia00/ReVanced_Extended/assets/91815107/c6da26c4-b932-4420-868d-d94392aa0629)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
New patches can only be contributed through PR

**Comment by vippium** [comment]
If we want this, then, we also have to redesign them for captions, autoplay, cast button to match it. This was in my mind but I dropped it because of this.
