### ISSUE TITLE
feat: AV1 software decoding option

### ISSUE THREAD

**Issue by alcatraz-zz** [inotia00/ReVanced_Extended#2218]
### Application

YouTube Music

### Feature description

Allow youtube AV1 codec streams on phones that don't support hardware decoding.

### Motivation

Thr data saving or quality increase is significant. Many phone cpus are powerful enough to decode AV1 in software. 

I'm fully aware that software decoding is inefficient but consider having the option at least. Some of us have bad internet connections and perhaps use external displays to watch video.

I know that my snapdragon 865 can decode AV1 in software at 1440p because I just tried it with the Chrome browser.

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by alcatraz-zz** [comment]
I'm confused. Is this feature impossible to implement and therefore closed? 

Or is it going to appear in the next version of revanced-patches? RvX or Rv?

I recently switched to inotia's revanced over the vanilla revanced. This is clearly the better version today. Keep up the great work.

**Comment by inotia00** [comment]
Issue is closed as this is a feature request

**Comment by alcatraz-zz** [comment]
Excuse me, please. Are there any plans for offering AV1 software decoding in RvX?
