### ISSUE TITLE
bug(YouTube - Shorts components): `Hide sound metadata label` toggled on can glitch timestamp of Shorts

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2219]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.25.39

### Bug description

Hide sound metadata label when toggled on, can show timestamp on Shorts player tags on home page.

Buggy timestamp:
![Screenshot_20240705_230240_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/30b0918b-7b1f-4479-b82f-9a2882fb64e1)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Bruh, it is still an experimental options

**Comment by ILoveOpenSourceApplications** [comment]
I'm not sure if this is also a side effect, but when I enabled Shorts timestamp, it stopped showing Shorts in home page.

**Comment by ILoveOpenSourceApplications** [comment]
> Bruh, it is still an experimental options

Yes, but it shouldn't affect the user when it's not enabled.

**Comment by ILoveOpenSourceApplications** [comment]
Sorry for editing the issue so much, but I had to confirm the cause of the issue. Looks like the feature is already introduced but isn't consistent across all Shorts pages and currently is only present on the home page. Hence if the user has `Hide sound metadata label` on and has video title off, then it'll glitch onto the title. (This won't happen if the user have both hidden)

But if they enable the newly added `Enable timestamps` it'll add a padding thus fixing this issue. But in which case, if they have sound metadata label turned off will cause two separate layer on top of each other.
Like this:
![Screenshot_20240706_000054_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/a651cf5f-25a1-49ce-b344-e19536db9d51)

**Comment by ILoveOpenSourceApplications** [comment]
I'm not even sure what to title the issue anymore. I'm having mixed emotions. This UI sucks, to pause a short, now the user has to tap on the timestamp. Like who at YouTube thought that this was a good idea.

**Comment by inotia00** [comment]
Experimental Flags

**Comment by ILoveOpenSourceApplications** [comment]
Is this Srtting only present in v19.25 and above?

**Comment by inotia00** [comment]
yeah it's a feature added in YouTube 19.25.39

**Comment by ILoveOpenSourceApplications** [comment]
I downgraded to 19.24.45 at which point the experimental setting itself disappears. And when updating to 19.25.37, timestamp no longer appears in Shorts on home page for me. 

YouTube has introduced this UI for Shorts in 19.25.39 for sure in home page.
