### ISSUE TITLE
feat: hide microphone button above keyboard

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#222]
### Application

YouTube

### Issue

a patch that hides microphone button on search screen, introduced in recent youtube versions. unnecessary because we already have mic option on search bar as well as keyboard, also its blue colour on pitch black background is repelling.

### Patch

remove this please
![Screenshot_20230205-220626_YouTube](https://user-images.githubusercontent.com/87489540/216843591-e9028ef3-420b-492b-abe5-00f09f90da5d.png)

### Motivation

mic button unnecessary because we already have mic option on search bar as well as keyboard, also its blue colour on pitch black background is repelling.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)
