### ISSUE TITLE
bug(YouTube/Feed components): `Hide recommended videos` setting does not working in home feed

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#2220]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.24.39
RVX patches v4.10.1

### Bug description

"From your Watch later playlist" text is not hidden under the feed thumbnails.
![20240705_213859](https://github.com/inotia00/ReVanced_Extended/assets/132079771/b1479da1-3eac-4cb6-945e-dac640a60b7a)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Did you enable the setting?

**Comment by NoMorePizza** [comment]
Yes, I have it enabled.

**Comment by NoMorePizza** [comment]
The same issue is also present in search results.

![20240708_193212](https://github.com/inotia00/ReVanced_Extended/assets/132079771/7b933d5b-acc5-4b71-b4bc-c566e0a621aa)

**Comment by inotia00** [comment]
In [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2), the supported version has been rolled back to YouTube 19.16.39.
This bug is only reproducible on YouTube 19.20.xx+, so the issue is closed.

**Comment by NoMorePizza** [comment]
This bug still exists in YouTube v19.16.39 and pathces v4.10.2. Home feed and search results both have it, at least on my end.

**Comment by inotia00** [comment]
I think I can remove the A/B tests label
(now can be reproduced in YouTube 19.16.19)

reopen the issue

**Comment by Cast0r-999** [comment]
I have this bug too, long ago started. On 19.16 right now and on 19.25
"Watch later" is visible in home feed.
"People also watch" is visible in search feed.
Please fix.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.3)
