### ISSUE TITLE
bug(YouTube - Hide Shorts components): not working on home page

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2221]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.25.39

### Bug description

The subscribe button is no longer hidden in Shorts when the toggle is turned on. 

![Screenshot_20240705_230240_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/30b0918b-7b1f-4479-b82f-9a2882fb64e1)

### Solution

Rollback to YouTube 19.16.39

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
A/B testing probably. It's once again only present on Shorts played from home page.

**Comment by inotia00** [comment]
Please attach debugging logs

**Comment by inotia00** [comment]
In [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2), the supported version has been rolled back to YouTube 19.16.39.
This bug is only reproducible on YouTube 19.20.xx+, so the issue is closed.
