### ISSUE TITLE
bug(YouTube/Translations): patch does not work in some languages

### ISSUE THREAD

**Issue by Yumipk** [inotia00/ReVanced_Extended#2222]
### Application

YouTube  

Patch configuration does not have Chinese simplified language

### Question description

![Screenshot_2024-07-06-14-08-35-04_a87fd7db6caa850b517aa6fa9d2fcd0e](https://github.com/inotia00/ReVanced_Extended/assets/146193668/508f7465-eb96-431f-a6f6-6e0beed4306f)

Translating ReVanced_Extended to Chinese Simplified language - Crowdin
https://crowdin.com/project/revancedextended/zh-CN

Simplified Chinese 100%

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Thanks for reaching here
I tested it a while ago and it appears that the translation is not applied in some languages ​​due to a bug
It will be fixed in the next release

**Comment by inotia00** [comment]
![Simplified_Chinese](https://github.com/inotia00/ReVanced_Extended/assets/108592928/e7d515b8-ab5e-45d1-818b-90b199ba52ad)

Update: I removed the `Patch options` and tried patching again and it seems to work fine

Follow steps:
1. Remove Patch options
2. Include `Translations for YouTube` patch
3. Try the patch again

And report back the results
