### ISSUE TITLE
bug(YouTube - Hide Play & Pause button background): does not work if the timestamp is turned on

### ISSUE THREAD

**Issue by odkate** [inotia00/ReVanced_Extended#2223]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube 19.25.39

### Bug description

![2024_07_06_14 59 3](https://github.com/inotia00/ReVanced_Extended/assets/90364108/05a46812-b7fd-4d3e-bf0a-20f16c54807f)
![2024_07_06_14 58 0](https://github.com/inotia00/ReVanced_Extended/assets/90364108/8d447266-55ec-4305-9ee1-a0a7729c60bf)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Enable timestamps` setting is `Experimental Flags`.
I do not provide support for bugs caused by activating `Experimental Flags`.
