### ISSUE TITLE
bug(YouTube/Enable gradient loading screen): patch not working properly

### ISSUE THREAD

**Issue by UNIVERSA7VLAD** [inotia00/ReVanced_Extended#2224]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.25.39

### Bug description

When loading the videos, the gradient theme isn't showing. When refreshing the page, the gradient color only works on the upper bar where you can you can chose what type of videos do you want to watch like games and music. It only shows the default dark grey color.

### Solution

Rollback to YouTube 19.16.39

### Additional context

It randomly happened a few days ago. I tried: clearing cache, deleting the app and repatching the app. Nothing worked.

### Device Environment

Ulefone Armor 21, android 13, Mediatek Helio G99, Mali-G57 MC2

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.23.40 is not currently a supported version
Please update to the currently supported version - YouTube 19.25.39 - and reopen the issue if the bug persists

**Comment by UNIVERSA7VLAD** [comment]
> YouTube 19.23.40 is not currently a supported version
> Please update to the currently supported version - YouTube 19.25.39 - and reopen the issue if the bug persists

Did that, still doesn't work. By the way, I'm using the anddea patches and when I posted this issue on their GitHub report page, a guy told me to post it on here.

**Comment by inotia00** [comment]
![Gradient](https://github.com/inotia00/ReVanced_Extended/assets/108592928/7308030c-9f51-4cb6-adbd-21aafd0e7af9)

`Enable gradient loading screen` seems to work well (YouTube 19.25.39)

Can you upload your screenshot?
(screenshot of `Enable gradient loading screen` status in RVX setting & screenshot of the video loading screen)

**Comment by UNIVERSA7VLAD** [comment]
![Screenshot_20240707-201043.png](https://github.com/inotia00/ReVanced_Extended/assets/170043255/5469cc4e-f57b-4c43-a1a0-94a51bf8d13d)

![Screenshot_20240707-200942.png](https://github.com/inotia00/ReVanced_Extended/assets/170043255/966d7761-f2de-4e56-9123-0e2e1696ec66)

It's not really much to see. It just doesn't work

**Comment by inotia00** [comment]
Yes, it's a valid bug
Reopen the issue

**Comment by inotia00** [comment]
Perhaps rolling back to YouTube 19.16.39 will solve the issue

Could you please try patching again to YouTube 19.16.39?

**Comment by UNIVERSA7VLAD** [comment]
It works now. Patched every single thing the same, except that I changed the package name. Should I reopen/open a new issue on the anddea bug report GitHub page and tell them that the 25 version doesn't work with this patch?

**Comment by UNIVERSA7VLAD** [comment]
It works now. Patched every single thing the same, except that I changed the package name. Should I reopen/open a new issue on the anddea bug report GitHub page and tell them that the 25 version doesn't work with this patch?

**Comment by inotia00** [comment]
Nah all patches work for most people even on YouTube 19.25.39

The patch will not work for some people registered in A/B tests
(Issues with the label `A/B tests` are issues that are reproduced only by some users)

**Comment by inotia00** [comment]
In [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2), the supported version has been rolled back to YouTube 19.16.39.
This bug is only reproducible on YouTube 19.20.xx+, so the issue is closed.
