### ISSUE TITLE
question: where is "outlined version of actual YouTube shorts action buttons"?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2225]
### Application

YouTube

### Question description

v4.10.1 added [outlined version of actual youtube shorts action buttons](https://github.com/inotia00/revanced-patches/pull/59) but it doesn't seem to be listed:
![Screenshot_20240706_165741_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/130296934/e280e2a8-9071-4f1f-bca7-c387308717f4)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
You'll have clear data and check again in manager for it to appear. Do a backup of patches and keystore.
