### ISSUE TITLE
bug: Seekbar bug

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2226]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 19.25.39 with latest patches

### Bug description

When you try to use the seekbar bottom buttons just disappear and seekbar goes down it wasn't like this it last patch (19.23.40) 
![Screenshot_2024-07-06-20-56-37-380_app uvteam afnify](https://github.com/inotia00/ReVanced_Extended/assets/172329144/ea165245-1b81-4f21-a180-7b087d8111af)
![Screenshot_2024-07-06-20-56-42-227_app uvteam afnify](https://github.com/inotia00/ReVanced_Extended/assets/172329144/9cdf29d8-d5db-4318-8e1e-448820875868)

### Device Environment

Android 13, HyperOS 1.0.9, Poco x6 pro

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unpatched YouTube 19.25.39 also has the same layout

So this is a new layout in YouTube 19.25.39, not a bug in RVX
