### ISSUE TITLE
suggestion: Ability to auto-hide Mordern Miniplayer always-on overlay buttons

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2228]
### Application

YouTube

### Suggestion description

The ability to auto-hide the 2 overlay buttons similar to how pause & seek buttons authorise after some time for a seamless streaming experience.
Overlay buttons-
![IMG_20240707_200938](https://github.com/inotia00/ReVanced_Extended/assets/107706560/21c228f7-e65d-4e13-8153-0029796ddd75)
pause & seeking buttons-
![Screenshot_20240707-201047](https://github.com/inotia00/ReVanced_Extended/assets/107706560/028897dc-fd1d-40e5-8667-9cb94c21a35f)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Sorry, I don't accept feature requests from YouTube
(You can contribute to the project through PR)
