### ISSUE TITLE
bug(YouTube/Shorts components): the next short plays on replaying a short when the repeat state is set to `pause`

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#2231]
### Type

Error at runtime

### Tools used

Revancify

### Application

youtube 19.25.39

### Bug description

as mentioned in title, when a short ends and you try replay the short, the next short starts playing. you need to swipe down to the next shorts video and swipe back up to rewatch the current shorts video.

https://github.com/inotia00/ReVanced_Extended/assets/87489540/01db7b83-8b5e-4716-8db7-e44d63f2f25d

### Device Environment

los18.1 a11

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MondayNitro** [comment]
if this is fixable, can you also try to change replay behaviour of shorts player? assuming the above reported bug gets fixed, the user has to tap twice on the screen to replay the short after it ends. on the first tap, the pause button pops up, on the next tap short replays.
it would be better if it follows the normal video player, where after the video ends, just one tap on the replay button replays the video,

**Comment by inotia00** [comment]
Since [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1), the `Change Shorts repeat state` setting has been changed to an `Experimental Flags`

Closing issue
