### ISSUE TITLE
question(YouTube - Swipe Controls): Can't restore 'Save and Restore Brightness'?

### ISSUE THREAD

**Issue by zerozero0022** [inotia00/ReVanced_Extended#2232]
### Application

YouTube

### Question description

Can't restore 'Save and Restore Brightness'?

(It's a feature that RVX had before and ReVanced now has.

But I don't know where source code is for that feature in ReVanced.)

I want to use a brightness swipe controls, but I don't want to save the brightness value.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2)
