### ISSUE TITLE
bug(YouTube): No Shorts action buttons are hidden on home page

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2233]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.25.39
Patcher v4.10.1

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/787b1e93-862c-4423-b19b-5d32af89888f

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Integrate with issue https://github.com/inotia00/ReVanced_Extended/issues/2221
