### ISSUE TITLE
bug(YouTube/Theme): theme is broken in home feed

### ISSUE THREAD

**Issue by Graywizard888** [inotia00/ReVanced_Extended#2234]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube v19.25.39

### Bug description

When my youtube gets the new ui the home screen gets bugged with black theme but i set blue. And it happen everytime i open the youtube, when i play any video the theme backs to normal to set theme. Theme patch working normally on old youtube ui

![Screenshot_2024-07-10-12-08-00-705_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/172885338/25661356-b721-43f8-abe8-09259532e74a)

### Device Environment

Android 12 ,miui 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Exclude patches one by one and report back which patches are causing the issue

**Comment by Graywizard888** [comment]
Only theme patch issue

**Comment by Graywizard888** [comment]
Other patches working normally

**Comment by inotia00** [comment]
Please try again with YouTube 19.16.39

**Comment by Graywizard888** [comment]
****

> Please try again with YouTube 19.16.39

The problem seem to be fixed in your mentioned version i will update you if the bug appear again

**Comment by Graywizard888** [comment]
![Screenshot_2024-07-11-18-59-19-302_com google android youtube](https://github.com/inotia00/ReVanced_Extended/assets/172885338/ec1c6857-d0f0-4322-93fe-e5cb74b82ae8)

**Comment by Graywizard888** [comment]
Ok that bug is fixed permanently in v19.16.39

**Comment by Graywizard888** [comment]
The theme patch working when i patched v19.26.39 when i patched with pre-release, but the cairo seekbar turn default red seekbar, custom seekbar colour working properly

**Comment by inotia00** [comment]
In [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2), the supported version has been rolled back to YouTube 19.16.39.
This bug is only reproducible on YouTube 19.20.xx+, so the issue is closed.
