### ISSUE TITLE
Phone significantly slows down when using Miniplayer or PiP

### ISSUE THREAD

**Issue by NichirinSword** [inotia00/ReVanced_Extended#2235]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.25.39

### Bug description

Scrolling in YouTube feed or in phone significantly sluggish, lagging everywhere when using Miniplayer or PiP.
I didn’t have this kind of issue in previous build. 

https://github.com/inotia00/ReVanced_Extended/assets/98078687/db5923f0-311d-4630-b7ba-0d2b8a1e4a55

### Device Environment

Realme 9 Pro (Supports 120Hz refresh rate)
Android 14
RealmeUI 5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Because this is a difficult issue to reproduce, it cannot be fixed
