### ISSUE TITLE
suggestion(YouTube - Player): Include products panel in 'Hide player popup panels'

### ISSUE THREAD

**Issue by zerozero0022** [inotia00/ReVanced_Extended#2236]
### Application

YouTube

### Suggestion description

suggestion(YouTube - Player): Include products (tagged products) panel in 'Hide player popup panels'

![Screenshot_20240711-023533_YouTube ReVanced](https://github.com/anddea/revanced-patches/assets/163995091/a31b9362-23b3-4c4b-824c-51cb6f10dee0)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
This products player popup panel is coming up for me too on few videos.

Can you provide 2-3 links of videos where this panel pops up?

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2)
