### ISSUE TITLE
bug (Youtube-Navbar) : `translucent` navbar turns black / Fully Opaque on feed scroll

### ISSUE THREAD

**Issue by NeeRaj-2401** [inotia00/ReVanced_Extended#2237]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

19.25.39

### Bug description

the experimental translucent option for navigation gets turned into black as soon as we start scrolling feed

### Device Environment

android 14, nothing os 2.6

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2182
