### ISSUE TITLE
feat(patch): Add download Button in YT music

### ISSUE THREAD

**Issue by rks2000** [inotia00/ReVanced_Extended#224]
### Application

YouTube Music Revanced Extended 

### Issue

It will add ability to use download button from the app. Just like youtube Revanced Extended we can set any downloader of our choice from the settings.

### Patch

![IMG_20230206_093621](https://user-images.githubusercontent.com/62375786/216881900-2b8605df-b995-44da-8067-9ea6fcffff16.jpg)

### Motivation

It definitely reduces some steps to download a song from YT music app. Otherwise we need to to share the link everytime to open it in particular downloader then start the downloading. But With this download button added we don't need to leave the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by GeorgeAbboud** [comment]
Why not hook the external download to the built in download button instead of the share button
