### ISSUE TITLE
bug: Shorts `Captions` option not hiding in feed flyout

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2240]
### Type

Other

### Tools used

rvx-builder

### Application

16.39

### Bug description

Every option can be hidden instead of Captions options in shorts.

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Patch to hide the flyout menu for Shorts has not been implemented

**Comment by vippium** [comment]
> Patch to hide the flyout menu for Shorts has not been implemented

It doesn't need another patch...we can hide it through Feed Flyout Filters.
