### ISSUE TITLE
suggestion: drop support for YouTube 19.25.39+

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2241]
### Application

YouTube

### Suggestion description

Currently, the RVX patch supports all versions up to YouTube 19.28.xx. (dev branch)

Most users will not encounter any bugs associated with the YouTube version.

Google is conducting [A/B testing](https://en.wikipedia.org/wiki/A/B_testing) on a subset of users, and the patch will not work for users in [A/B testing](https://en.wikipedia.org/wiki/A/B_testing).

Here are some cases where patches don't work due to A/B testing:
1. https://github.com/inotia00/ReVanced_Extended/issues/2169
2. https://github.com/inotia00/ReVanced_Extended/issues/2173
3. https://github.com/inotia00/ReVanced_Extended/issues/2221
4. https://github.com/inotia00/ReVanced_Extended/issues/2224
5. https://github.com/inotia00/ReVanced_Extended/issues/2234

This is not a bug that is reproduced by all users, only by some users in A/B testing.
(ofc these are bugs that cannot be reproduced on my side)

If there were only a few bugs caused by A/B testing, it wouldn't be a big issue, but in reality, too many patches are broken due to A/B testing.

For this reason, I will bump the YouTube version when A/B testing is fully completed and new features have been rolled out widely (to most users).

In the next release, supported YouTube versions will be rolled back to 19.16.39.

Users can still patch to the latest YouTube versions, including YouTube 19.28.xx, but no support, including bug reports, will be provided in this case.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Will you be implementing the `Change version code` patch as a universal patch when dropping support for these YT versions?

https://github.com/inotia00/ReVanced_Extended/issues/2229

**Comment by inotia00** [comment]
Oh, I've been so busy lately that I forgot to merge it
It will be applied in the next release

**Comment by Kuddus73** [comment]
> It will be applied in the next release

Was it applied on v4.10.2-dev.2?

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2)

**Comment by alcatraz-zz** [comment]
I'm on 4.10.2 and 19.16.xx now and I lost 4k resolutions on my phone. They were working fine. Is that normal?

**Comment by Tiebe** [comment]
This has caused it to stop working on the Android 15 beta, as the system installed version is higher than 19.16.39 (19.17.42). I'll be changing my version manually for now, but just something you should be aware of!

**Comment by alcatraz-zz** [comment]
> This has caused it to stop working on the Android 15 beta, as the system installed version is higher than 19.16.39 (19.17.42). I'll be changing my version manually for now, but just something you should be aware of!

Although I haven't tried it, there's a developer called Anddea that also provides RvX patches. Currently his RvX is based off of 19.23.xx

**Comment by akash07k** [comment]
Can you please provide the link to his builds? I can't find.

> > This has caused it to stop working on the Android 15 beta, as the system installed version is higher than 19.16.39 (19.17.42). I'll be changing my version manually for now, but just something you should be aware of!
> 
> Although I haven't tried it, there's a developer called Anddea that also provides RvX patches. Currently his RvX is based off of 19.23.xx. That might work for you in the meantime.

**Comment by KobeW50** [comment]
@akash07k https://github.com/anddea/revanced-patches/

anddea has also rolled back to v19.16.39. 

Inotia00s patches should still (for the most part) on newer unsupported versions, so you can use them if you need (just dont submit bug reports).

The good news is that inotia00 has said that (on Discord) that the supported version will likely be bumped before the end of the year.

**Comment by akash07k** [comment]
Oh, ok. sadly 2 months are still remaining before the end of the year :-)

> @akash07k https://github.com/anddea/revanced-patches/
> 
> anddea has also rolled back to v19.16.39.
> 
> Inotia00s patches should still work (for the most part) on newer unsupported versions, so you can use them if you need (just dont submit bug reports).
> 
> The good news is that inotia00 has said that (on Discord) that the supported version will likely be bumped before the end of the year.

**Comment by SM-03** [comment]
@inotia00 
There's a new RV v19.45.38 released today on 26th Nov 24
is it possible to update this RVE version (from v19.16.39) to that or even newer v19.46.40 / 19.47.36?
