### ISSUE TITLE
bug: Youtube: video would pause during background play

### ISSUE THREAD

**Issue by Yola-cola** [inotia00/ReVanced_Extended#2243]
### Type

Other

### Tools used

Revancify

### Application

Youtube 

### Bug description

My problem is when I play a video in the background after a while It stops playing it and keeps buffering forever. I don't know how to make it stop, so I hope you.Please fix it.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Additional information is needed

1. Which version of YouTube are you using?
2. Are you using the Spoof client?
3. If you are using the Spoof client, which client did you spoof with? (iOS, Android VR Android TV, Android Testsuite)

**Comment by inotia00** [comment]
Since I haven't received any response from OP in 3 days, I'm closing the issue.
Please reopen the issue including what I mentioned in my previous comment.
