### ISSUE TITLE
bug(YouTube/Settings): Text shuffles when picking certain settings

### ISSUE THREAD

**Issue by Oleepre** [inotia00/ReVanced_Extended#2245]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.10.2-dev.1

### Bug description

 In Revanced Extended settings, when clicking either "**Return YouTube Dislike**" or "**Sponsorblock**", the menu's text moves up giving the impression that it glitches.
 After looking closely it seems the Setting's Search Bar dissapears when clicking on those two settings.
 Slowed down recording:
 

https://github.com/user-attachments/assets/f63c5c08-1fad-4562-9dbd-9e94cc141ecb

### Device Environment

Android 14, Galaxy A32

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an issue that cannot be fixed due to structural limitations of RVX settings
