### ISSUE TITLE
On version 19.25.39 seekbar adjust on wrong position when shuffle.

### ISSUE THREAD

**Issue by Diesel1987** [inotia00/ReVanced_Extended#2248]
On version 19.25.39 seekbar adjust on wrong position when shuffle. 

https://github.com/inotia00/ReVanced_Extended/assets/174826982/4cc62dda-0390-431b-bbb8-22e3a52b9ce8

On old version 19.23.40 everything i ok

https://github.com/inotia00/ReVanced_Extended/assets/174826982/d3c665f8-13d1-4565-bfed-b79e0fd1af40

_Originally posted by @Diesel1987 in https://github.com/inotia00/ReVanced_Extended/issues/2142#issuecomment-2211250124_

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2142#issuecomment-2211532373
