### ISSUE TITLE
bug: Seekbar thumbnail missing 

### ISSUE THREAD

**Issue by GKid94** [inotia00/ReVanced_Extended#2249]
### Type

Error at runtime

### Tools used

CLI

### Application

![Screenshot_2024-07-15-20-41-34-484_com miui securitycenter](https://github.com/user-attachments/assets/3d805f27-8a4e-42b5-9626-94037d73e082)

### Bug description

Seekbar thumbnails are missing when skipping video parts and there is no option for it 
![Screenshot_2024-07-15-20-42-35-227_app rvx android youtube](https://github.com/user-attachments/assets/1123f490-c00d-40a8-a3b6-5c5caadfdd9d)
![Screenshot_2024-07-15-20-42-20-547_app rvx android youtube](https://github.com/user-attachments/assets/ad9e80ef-7624-495e-abd8-26bfae3a5c52)

### Device Environment

![Screenshot_2024-07-15-20-41-42-601_com android settings](https://github.com/user-attachments/assets/9d7cb2ea-5037-42f5-b619-f12b8ba9de92)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.25.39 does not support the `Restore old seekbar thumbnails` setting

**Comment by GKid94** [comment]
Can you add it?

**Comment by inotia00** [comment]
No in YouTube 19.17.41+ the code associated with Restore old seekbar thumbnails has been completely removed (by Google)

Additionally, in the latest dev branch, the supported version has been reverted to YouTube 19.16.39.

So just use YouTube 19.16.39

**Comment by GKid94** [comment]
Ok thanks
