### ISSUE TITLE
bug: Hide Live Chat button doesn't work properly

### ISSUE THREAD

**Issue by kazimmt** [inotia00/ReVanced_Extended#225]
### Type

Error at runtime

### Application

YouTube 18.04.41

### Bug description

There are two options in Layout Settings
1. Hide Live Chat on Player
2. Hide live chat button under video button container

But if we hide live chat button under player button container
It doesn't work
But if we hide live chat button from player, it hides live chat button under the player.

### Steps to reproduce

Step 1:
- Open ReVanced
- Go to ReVanced Settings
- Layout Settings
- Hide Button Container Components
- Hide Live Chat Button

Step 2:
- Open ReVanced
- Go to ReVanced Settings
- Layout Settings
- Hide live chat button from Player Layout Settings

### Relevant log output

```shell
...
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.159.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.4)
