### ISSUE TITLE
 Offline songs (YT-M)

### ISSUE THREAD

**Issue by Roxo7777** [inotia00/ReVanced_Extended#2250]
### Application

YouTube Music

### Feature description

Just like the Spotify X/Plus and Dezeer mods, it is possible to create an internal download for offline music;

The usual formats for these applications are .opus, .aac, .mp3, .flac, .ogg (the main and best for YT-M are Opus and AAC). Many amateur modifications I have seen put them in fragments in Android\.data\application, but this causes loss of sound quality, and it should not be that difficult to get around the scanning problem;

The download method is not "intimidating", since it will only be necessary to use yt-dlp and other mirrors, but it would require a method to avoid having to fragment the files, .opus and .acc, with Bitmovin Player or the traditional ExoPlayer being a great solution;

 If possible, use Mutagen to add the lyrics to the songs...

If there is anything incongruent, it may be due to the translation made (Portuguese to English)

### Motivation

1️⃣ It would be the best feature to be implemented, since there is more search for offline content on YT-M;
2️⃣ There are uncertainties about this, but the risks are very low;
3️⃣ YouTube Music, although not as famous as Spotify, is better in many ways, and it is very useful to have it offline;
4️⃣ It is probably one of the most flashy services on YT-M, giving completeness to the modifications

There may be some incongruity in the translation, pardon me for that

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by sr-shishir** [comment]
Use external player like snaptube or videoder or YMusic

**Comment by Roxo7777** [comment]
> Use external player like snaptube or videoder or YMusic

I already use Seal, but I would like something more effective.

**Comment by inotia00** [comment]
RVX Music already supports external downloader hooks
