### ISSUE TITLE
bug (YouTube - Navigation Bar) : Transculent Navigation Bar Properly not Working

### ISSUE THREAD

**Issue by sr-shishir** [inotia00/ReVanced_Extended#2251]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube

### Bug description

When my feed scrolling up the nav bar transculent mode not working but when scrolling down then it’s working. 

https://github.com/user-attachments/assets/ec219680-0140-456e-8456-b821d2511650

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
The patches is marked as experimental, so it have a high chance to have bug.

**Comment by sr-shishir** [comment]
> The patches is marked as experimental, so it have a high chance to have bug.

Hmm that I've seen. Just reported here to fix asap.

**Comment by YT-Advanced** [comment]
> Hmm that I've seen. Just reported here to fix asap.

Duplicate with https://github.com/inotia00/ReVanced_Extended/issues/2182 https://github.com/inotia00/ReVanced_Extended/issues/2237
