### ISSUE TITLE
bug: YouTube fails to patch (root)

### ISSUE THREAD

**Issue by Brubhubedits** [inotia00/ReVanced_Extended#2252]
### Type

Error while patching

### Tools used

RVX Manager

### Application

RVX Manager v1.20.4 for YouTube v19.25.39
Error occurs at "Aligning APK" stage in the patching process

### Bug description

There's an error when in the patching process and I reach "Aligning APK" in the steps.
Here's all I really did:
Download the latest YouTube 19.25.39 APK
Choose the following patches:

Disable resuming Shorts on startup
Enable gradient loading screen
Enable open links directly
Layout switch
MaterialYou
Remove background playback restrictions
Remove viewer discretion dialog
Return YouTube Dislike
Sanitize sharing links
Settings for YouTube
SponsorBlock

Then I patched and got the error :(

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.4
Model: 21121210C
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.25.39 (Suggested: 19.25.39)
Patches version: v4.10.1
Patches added: MaterialYou
Patches removed: Custom package name, Hide ads, Alternative thumbnails, Hide feed components, Hide feed flyout menu, Disable auto audio tracks, Disable auto captions, Hide layout components, Miniplayer, Navigation bar components, Disable splash animation, Spoof app version, Change start page, Toolbar components, Custom Shorts action buttons, Custom branding icon for YouTube, Custom branding name for YouTube, Custom double tap length, Theme, Translations for YouTube, Enable OPUS codec, Enable debug logging, Enable external browser, Disable QUIC protocol, Hide action buttons, Ambient mode control, Hide player buttons, Hide comments components, Player components, Description components, Hide player flyout menu, Change player flyout menu toggles, Fullscreen components, Disable haptic feedback, Overlay buttons, Seekbar components, Shorts components, Swipe controls, Spoof client, GmsCore support, Video playback
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: false
Use pre-release: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 11 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
An error occurred:
java.io.FileNotFoundException: /storage/emulated/0/Android/data/app.rvx.manager.flutter/files/revanced-manager.keystore: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at app.revanced.library.ApkUtils.readPrivateKeyCertificatePairFromKeyStore(Unknown Source:13)
	at app.revanced.library.ApkUtils.readOrNewPrivateKeyCertificatePair(Unknown Source:51)
	at app.revanced.library.ApkUtils.sign(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:575)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$0x5RQW3TgU-norbj4KLWHG0V2oA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(Unknown Source:15)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 8 more
```

### Device Environment

Eliterom Gaming - Based on HyperOS 1.0.24.6.24 DEV Beta
POCO F4 GT

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
For some reason, your device cannot access RVX Manager's keystore file.
Maybe you are missing permissions that should be granted.

RVX Manager is provided simply for compatibility with my patches, so not much support is provided for issues that occur in RVX Manager.

I provide other patch methods as well as RVX Manager, so please select one of the following patch methods to proceed with the patch:

- [rvx-builder (PC)](https://github.com/inotia00/revanced-documentation/wiki/Method-2.-Using-RVX-Builder-(Windows---MacOS---Linux---Android)#using-rvx-builder-windows--macos--linux)
- [rvx-builder (Android, termux)](https://github.com/inotia00/rvx-builder/wiki/How-to-use-rvx-builder-on-Android)
- [Revancify (Android, termux)](https://github.com/inotia00/revanced-documentation/wiki/Method-4.-Using-Revancify-(Android---termux))
