### ISSUE TITLE
Bug(Youtube/Spoof client): Occasional error when playing video

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#2253]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.26.42 patches 4.10.2-dev.2

### Bug description

Upon patching with spoof client patch and default spoofing settings, in some cases an error occurs when launching a video. This gets fixed when tapping to retry. This error most likely has to do with the "delay when video starts" adjustment in patches 4.10.2-dev.1.

https://github.com/user-attachments/assets/ab703c60-badb-441f-a59e-42f31c0d183a

### Solution

Tapping to retry solves this, but it is not ideal

### Device Environment

Android 14 pixel 7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
unsupported version

**Comment by ayushTNM** [comment]
Still happening on 19.16.39

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2207

**Comment by inotia00** [comment]
Update: This issue appears to be a bug caused by the `Skip preloaded buffer` setting, not `Spoof client`
(The `Skip preloaded buffer` setting is an experimental flag, so do not use this setting)

**Comment by GKid94** [comment]
![Screenshot_2024-07-20-15-13-57-526_app rvx android youtube](https://github.com/user-attachments/assets/ab02410f-7b49-43b8-97b7-083478f98898)
