### ISSUE TITLE
question: why were they merged in one?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2254]
### Application

YouTube

### Question description

"Disable player popup panels" patch (its current name) is related with just aesthetic choice and has nothing to do with advertisements and "Hide products panel" is related with hiding a type of ads.

Aren't the two patches too different to be merged in one patch?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Because it is a type of automatic pop-up
Also, due to structural limitations, the patches could not be separated, so they were inevitably integrated into one patch.
