### ISSUE TITLE
bug: An error occurred when playing videos in new patches.

### ISSUE THREAD

**Issue by Dimedro11** [inotia00/ReVanced_Extended#2257]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

When switching to patches 4.10.2 or 4.10.2dev, errors of this kind occur, regardless of whether various player substitution options are enabled (or it is disabled).I am attaching a video /photo fixing the error along with the operating system version here.
![Screenshot_20240717_213740_Settings](https://github.com/user-attachments/assets/a9760522-4f23-44e1-9aa4-0843a2dc0542)

https://github.com/user-attachments/assets/d7d4ebbd-903e-42e3-9cc5-d59b4482a213

![Screenshot_20240717_213433_YouTube](https://github.com/user-attachments/assets/83b6e7be-e323-44f4-bea6-3ac4be74e59d)

### Solution

Rolling back to patch versions 4.10.1 helps<

### Device Environment

Android 14
OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an issue that does not appear on my side.

Exclude patches one by one.
And please report back which patch is causing the bug.

**Comment by Dimedro11** [comment]
> Эта проблема не воспроизводится на моей стороне.
> 
> Исключайте патчи по одному. И сообщите, какой патч вызывает проблему.

Skipping the preloaded buffer does not crash without it, but again in version 4.10.1 it did not work adequately in version 4.10.2.

**Comment by Dimedro11** [comment]
> This is an issue that does not reproduce on my side.
> 
> Exclude patches one by one. And please report back which patch is causing the issue.

Skipping the preloaded buffer has not always worked up to this point, and starting from 4.10.2dev, an error started coming out with it.Again, I repeat, everything worked FINE in version 4.10.1

**Comment by inotia00** [comment]
Skip preloaded buffer setting is an experimental flag
