### ISSUE TITLE
question: The modified package name on YouTube has disappeared

### ISSUE THREAD

**Issue by Yumipk** [inotia00/ReVanced_Extended#2258]
### Application

YouTube

### Question description

I can't find it. Change the package name to YouTube

![Screenshot_2024-07-18-11-35-58-36_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/143e12de-6dc7-4726-9c40-e6694a3f9bb2)
![Screenshot_2024-07-18-11-38-54-89_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/63c1f83f-3a6a-4870-ac45-be4c51cfdd6f)
![Screenshot_2024-07-18-11-38-47-73_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/fbd7e985-d309-4c67-9fe3-f706333cac8c)
![Screenshot_2024-07-18-11-28-20-39_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/e376a406-fd6b-4321-9b5b-3a2f7b8f389a)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
[read release note](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2)

```
feat: merge the Custom package name patch into the GmsCore support patch
```
