### ISSUE TITLE
bug: hide-fullscreen-panels

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#226]
### Type

Other

### Application

YouTube 18.04.41

### Bug description

the new hide-fullscreen-panels patch, when used, makes the live chat button in fullscreen player useless. you cant show/hide live chat by tapping the live chat button. The previous hide-fullscreen-buttoncontainer patch was more useful, as it gave you the freedom to keep livechat on/off while this new patch makes the live chat overlay button broken.

### Steps to reproduce

step 1 include hide-fullscreen-panels patch
step 2 open any livestream in fullscreen
step 3 try tapping the live chat button as many times as you want, it wont do anything

### Relevant log output

```shell
none
```

### Screenshots or videos

![photo_6271780342956406160_y](https://user-images.githubusercontent.com/87489540/216983969-f2b739f3-71e5-47eb-9454-573a3452a531.jpg)

### Solution

i suggest to either remove the new patch and bring back  the old, or better still, make available  both the patches o that users have choice which of the two patches they want to keep. even if the panels patch duplicates some features of buttoncontainer patch, users can simply choose not to include buttoncontainer patch if they include panels patch

### Device Environment

LOS 18.1 A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a bug that also exists in the official ReVanced, and there are no plans to fix it.

**Comment by MondayNitro** [comment]
Don't fix it, just please add back the hide-fullscreen-buttoncontainer patch. Like i mentioned, users can choose which patch they want.

**Comment by inotia00** [comment]
then.. write new `patch-request`
I will reflect when I have time later

**Comment by MondayNitro** [comment]
thanks! suggestion: you can simply include a warning for users in patch description that dont include buttoncontainer patch if youre including hide-panels patch.
