### ISSUE TITLE
suggestion: Adding color options (HEX) to change `Cairo Seekbar` color

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2260]
### Application

YouTube

### Suggestion description

You can add options to change the colours of starting and ending points of Cairo Seekbar. So that, people using custom Seekbar colour can also adjust the colour according to their custom Seekbar colour. 
![IMG_20240719_084734_803](https://github.com/user-attachments/assets/b404548f-a29d-4e3e-9567-700cd03ec2d4)

Steps to do that:
1. Download and install apktool M
https://maximoff.su/apktool

2. Decompile your already patched apk. It should end up in a folder called apktool_m then you can edit it. 

3. Navigate to res/values/colors.xml

4. Change the hex values of the bottom items yt_youtube_red_cairo for the main line and yt_youtube_magenta for the ending color.

5. Save then compile the file. It should then update your patched apk!
### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The current supported version, YouTube 19.16.39, does not support the Cairo seekbar
