### ISSUE TITLE
feat(YouTube/Spoof client): change hardcoded device information in iOS clients 

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2261]
### Application

YouTube

### Feature description

![hdr](https://github.com/user-attachments/assets/a1e24f5f-c1af-481d-ade2-4f0fa3e76627)

According to @0xrxL, spoofing from the latest YouTube client to the iOS client enabled HDR playback.

**Additional context**

1. The device must support hardware AV1 decoding.
 
The following chipsets support hardware AV1 decoding:

Broadcom bcm72180+
Google Tensor G1+
MediaTek Dimensions 1000+
Realtek’s RTD1311+
Samsung Exynos 2100+
Snapdragon 8 Gen 2+

2. The iOS device model in Spoof client must be iPhone16,1 (iPhone 15 Pro) or iPhone16,2 (iPhone 15 Pro Max).
RVX is currently using the iPhone 15,3 (iPhone 14 Pro) when spoofing with the iOS client.

Among released iOS devices, the only ones that support hardware AV1 decoding are the iPhone16,1 (iPhone 15 Pro) or iPhone16,2 (iPhone 15 Pro Max).

3. `Spoof client` patch should spoof user-agents.
Currently `Spoof client` patch does not spoofing user-agents.

Also RVX currently uses iOS YouTube 19.01.1.

### Motivation

Although there are many prerequisites, it is possible to get HDR playback on some devices when spoofing with an iOS client.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The attached screenshot uses SM-S916B, and the chipset used in SM-S916B, Snapdragon 8 Gen 2, supports hardware AV1 decoding.

The patch will not work on Android Emulators that are not expected to support hardware AV1 decoding.

**Comment by 0xrxL** [comment]
> The attached screenshot uses SM-S916B, and the chipset used in SM-S916B, Snapdragon 8 Gen 2, supports hardware AV1 decoding.
> 
> The patch will not work on Android Emulators that are not expected to support hardware AV1 decoding.

Yeah...but it's however weird that, with iPhone 16,1 and the same user agent patch, I wasn't able to enable HDR with previous versions.

For this reason I wondered what exactly fixed this lack.

**Comment by AlexDon228** [comment]
Spoofing from the latest YouTube client to the Android Testsuite client enabled HDR playback.

Hardware AV01 decoding.

Chipsets MediaTek Dimensity 8100.

![IMG_20240719_223536_559](https://github.com/user-attachments/assets/6f91c42a-1496-44e6-bc13-2a5b6ef2933a)

**Comment by Aryan-Chauhan** [comment]
Does this mean this will unlock 1440p & 2160p even if user is using iOS client?

**Comment by 0xrxL** [comment]
> Does this mean this will unlock 1440p & 2160p even if user is using iOS client?

Yes, I currently have only iOS spoof on my client, up to 2160p available...with HDR too.

**Comment by 0xrxL** [comment]
> Spoofing from the latest YouTube client to the Android Testsuite client enabled HDR playback.
> 
> Hardware AV01 decoding.
> 
> Chipsets MediaTek Dimensity 8100.
> 
> ![IMG_20240719_230334_390](https://private-user-images.githubusercontent.com/175939764/350540157-6c0e2232-b46a-4399-92d7-74667d358437.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MDQwOTgsIm5iZiI6MTcyMTUwMzc5OCwicGF0aCI6Ii8xNzU5Mzk3NjQvMzUwNTQwMTU3LTZjMGUyMjMyLWI0NmEtNDM5OS05MmQ3LTc0NjY3ZDM1ODQzNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxOTI5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTJmYmIyM2ExMjAwN2MwNmNkMDgyYzdjMzNiMTNlNTE1ZWUyZWY2ZTdiZWFhYTM2NTFlMmRiM2I2MjVmMjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i1CWK7AGxhLr-FjkQY1mmcGE2qBUhysGIXi3G_Bt6xY)

You must try with iOS spoof, not Testsuit. This thread is related to iOS spoof.

**Comment by AlexDon228** [comment]
> You must try with iOS spoof, not Testsuit. This thread is related to iOS spoof.

In my case, HDR only plays when Android Testsuite spoof is enabled.
iOS, Android TV, Android VR spoof - disabled HDR playback.

Hardware AV01 decoding HDR - enabled HDR playback.
Hardware VP9.2 decoding HDR - disabled HDR playback.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.3)
