### ISSUE TITLE
bug: RestoreOldSplashAnimation

### ISSUE THREAD

**Issue by STEK1337** [inotia00/ReVanced_Extended#2264]
### Type

Other

### Tools used

CLI

### Application

YouTube v19.16.39

### Bug description

`RestoreOldSplashAnimation = true`

Not working as intended, after 3-4 opening of the app it starts showing the new splash animation

### Error logs

https://github.com/user-attachments/assets/40ba3da1-b550-4867-88e7-5dbbee2b2c3b

### Device Environment

Samsung Galaxy A53
Android 14
One UI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Do this.

![Screenshot_2024-07-20-20-26-20-08_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/user-attachments/assets/a5d316af-1f8c-40ea-ba96-22da8ef6c90c)

**Comment by inotia00** [comment]
'RestoreOldSplashAnimation' restores the splash animation that Google deprecated in YouTube 18.19.36

The old splash animation is only used when the app is cold started, not when the app is warm started.

In other words... this is intended behavior

You can reproduce it even on unpatched YouTube 18.18.39
