### ISSUE TITLE
bug: Picture in picture not displayed correctly

### ISSUE THREAD

**Issue by Kevinr99089** [inotia00/ReVanced_Extended#2265]
### Type

Cosmetic

### Tools used

rvx-builder

### Application

Youtube v19.16.39

### Bug description

It's been a long time that Picture in Picture doesn't display correctly, sometimes it displays correctly, sometimes it displays as in the example, except on this version where every time, PIP doesn't display correctly (unless you put the video in full screen).

I haven't seen this kind of issue, maybe it's related to my device.

https://github.com/user-attachments/assets/9134a1e0-81bd-4b73-a6f9-770f5d260647

### Solution

- Go to full screen
- Go to another app (launcher in my example).

### Device Environment

Samsung Galaxy S23 (One UI 6.1, No root, since the rollback: the App has been uninstalled, repatched and installed at the latest patch version)
Samsung Galaxy Tab S9 (One UI 6.1) Tablet mode, PiP seems to work.

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue is reproduced even on unpatched YouTube
