### ISSUE TITLE
bug: Captions Overlap

### ISSUE THREAD

**Issue by orez-x** [inotia00/ReVanced_Extended#2266]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patch v4.10.2

### Bug description

There is a bug caused by iOS spoof that affects videos with multiple captions displayed simultaneously. The top caption gets moved to the bottom, overwriting the bottom caption. Note that this bug does not occur with Android VR.

(Android VR)
![Screenshot_20240721-063343](https://github.com/user-attachments/assets/1081e813-1953-4194-98d9-8973b98a9b83)

(iOS spoof)
![Screenshot_20240721-064021](https://github.com/user-attachments/assets/2f2716fe-6ecf-4e65-800a-2e32bda3d70f)

### Solution

Switching to Android VR seems to fix the issue; however, you will then have to deal with paused videos resuming automatically.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Known side effect
