### ISSUE TITLE
feat: Hide rewards on reddit app

### ISSUE THREAD

**Issue by fynks** [inotia00/ReVanced_Extended#2269]
### Application

Reddit

### Feature description

First of all thanks for your awesome work.
Now on feature request, can we please develop a patch for removing/hiding awards button on posts on reddit android app?

image of rewards button is highlighted:
![Imagepipe_0](https://github.com/user-attachments/assets/e44a574d-0c20-4ad9-beb1-da654871345f)

### Motivation

This removes unnecessary clutter from reddit UI
(clutter can be for someone but can be useful to others, so as patches are optional it would be optional to have it removed or not)

> I'm not a developer but can help in testing the patch on device

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2056
