### ISSUE TITLE
feat(patch):hide-fullscreen-buttoncontainer 

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#227]
### Application

YouTube

### Issue

please bring back hide-fullscreen-buttoncontainer patch that you axed in favour of hide-fullscreen-panels patch, this will enable users to choose which of the two patches they want to include in their rvx builds. the hide panels patch is bugged, so some eople might have issues with that patch.

### Patch

https://github.com/inotia00/ReVanced_Extended/issues/226

### Motivation

The previous hide-fullscreen-buttoncontainer patch was more useful, as it gave you the freedom to keep livechat on/off while this new patch makes the live chat overlay button broken.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)
