### ISSUE TITLE
bug(YouTube/Toolbar components): turning on the `Hide voice search button` setting makes the margin of the searchbar 0

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#2270]
### Type

Error at runtime

### Tools used

Revancify

### Application

youtube 19.16.39

### Bug description

there is no space between the edges of the screen and the voice search button, this wasnt the case in earlier patches.

![photo_6118316698999308246_y](https://github.com/user-attachments/assets/21939d33-f77b-40b5-8272-5ac1638a7ceb)

### Device Environment

android 13 hyperos

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.3)
