### ISSUE TITLE
bug: YouTube history isn't working 

### ISSUE THREAD

**Issue by ginno13** [inotia00/ReVanced_Extended#2271]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.16.39

### Bug description

I updated the YouTube app to the latest patch and since then history has stop updating. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
It is a known side effect of Spoof Client patch

**Comment by ginno13** [comment]
So if I change the spoofing I can fix it?

**Comment by Aspyryan** [comment]
Is the spoof client patch necessary? What client should I choose to get my history back? Can I just disable the spoofing and get it working again?

**Comment by Aspyryan** [comment]
I do see `s.youtube.com` was blocked in my network firewall. Testing it out now

**Comment by inotia00** [comment]
Here are the solutions:

Solution 1. Turn off `Spoof client` setting
: Go to `Settings > ReVanced Extended > Miscellaneous > Spoof client`.

Change `Spoof client` setting to off.

If you are a root user or are lucky enough [not to experience playback issues](https://github.com/inotia00/ReVanced_Extended/issues/2238#issuecomment-2227186178), you do not need to turn on `Spoof client` setting.

Simply turning off `Spoof client` setting should solve the issue.

Solution 2. Change `Spoof client` options
: If you have turned off `Spoof client` and are experiencing playback issues when playing videos, you must turn on `Spoof client` setting.

In this case, turn on `Spoof client` and change `General`, `Live streams`, `Shorts, Clips`, `Unplayable video` to a client other than `iOS` in `Spoof client options`.

The issue of watch history not being saved on brand accounts is a side effect of the `iOS` client.

Other clients also have side effects, so please read the explanation below carefully and choose your client.

Solution 3. Disable VPN or DNS
: Some VPNs or DNS block the `s.youtube.com` domain.
In this case, watch history is not saved.

Disable VPN or DNS, or add the `s.youtube.com` domain to the whitelist.
