### ISSUE TITLE
bug(YouTube/Video playback): Skip pre-load buffer is not working on random videos

### ISSUE THREAD

**Issue by pumaspoilagetrustable** [inotia00/ReVanced_Extended#2274]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v19.16.39
Patches v4.10.2

### Bug description

Sometimes skip pre-load buffer does not work on random videos. This usually applies to videos that have quality options that are above 1080p (4k60 fps and 1440p60 fps). I have already tried enabling and disabling spoofing to IOS client, spoofing and not spoofing the app version to v18.17.43 (Restore old player flyout panel), and enabling spoof device dimensions (to ensure highest quality video is available).

### Additional context

Skip pre-load buffer is reliably  working with all videos on youtube patched with [YT-Advanced ](https://github.com/YT-Advanced) patches (fork of ReVanced_Extended patches) using revancify. The parameters for the youtube app patched with YT-Advanced patches are Youtube v19.07.40 (last version officially compatible with YT-Advanced patches), [v2.220.10](https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.220.10) YT-Advanced patches, spoofing the app version to v18.17.43 (Restore old player flyout panel), spoof device dimensions enabled, Spoof player parameter (option may be different in ReVanced_Extended patches since YT-Advanced does not spoof to IOS client).

### Device Environment

Android 14 Stable, Google Pixel 7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
That's why the `Skip preloaded buffer` setting is marked as `Experimental Flags`.

No support will be provided for any issues that arise while using `Experimental Flags`.
