### ISSUE TITLE
Change package name is missing for YouTube 

### ISSUE THREAD

**Issue by Raihan-Shovo** [inotia00/ReVanced_Extended#2276]
### Type

Other

### Tools used

Revancify

### Application

YouTube v19.05.36

### Bug description

Well as the title says when I tried to patch YouTube and in the patch selection option there is no patch option for change package name. Well didn't notice it in first but after patching the YouTube and after installation guess what, I had 2 patched YouTube. Then I checked the patch options and found out about it.

### Error logs

```shell
None
```

### Solution

Maybe a simple fix would be good.🙂

### Additional context

Sorry I couldn't provide screenshots, I cleared the tools data and I forgot that the internet is slow for the time being. (Cause of Bangladesh data center was burned down.)

### Device Environment

Android 8.1

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2258
