### ISSUE TITLE
bug(YouTube/Spoof app version): In youtube version 19.16.39 while spoofing the app to any version older than 18.33.40 will hide the shorts title

### ISSUE THREAD

**Issue by FishAndFire** [inotia00/ReVanced_Extended#2277]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

As the title describes if you patch the latest recommended version of Youtube which is 19.16.39 and then try to spoof the app version to a version older than 18.33.40, then the shorts title disappears. And you can reproduce this if you do what I said above.
![Screenshot_20240727_203322_ReVanced Extended](https://github.com/user-attachments/assets/5949b5dc-ee0b-42f8-ac22-6383f611d11e)

### Solution

As for now the only solution I could find was to patch to YouTube v19.05.36 which is the second suggested/recommended version as it doesn't appear to have this issue.

### Additional context

I should also mention that the version I was selecting was the ones given in "Spoof app version target" settings and I didn't use "Edit spoof version target". I should also mention that this happend with patches v4.10.2 & v4.10.3 (latest at the time of writing this)but then again I patched v19.16.39 only with patches v4.10.2 & v4.10.3 so I don't know if this issue happend with previous patches. 

### Device Environment

Android 14, One-UI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Spoof app version patch is an `Experimental Flags`

This patch is very likely to break YouTube's layout, and is an unstable patch, so it is marked as experimental

Unfortunately, I am not accepting any bug reports for `Experimental Flags`, nor am I providing support

Since YouTube 18.33.40 is also included in the supported version, I recommend using the patched YouTube 18.33.40 instead of using the Spoof app version
