### ISSUE TITLE
question (YT) : Why turning on `Skip Preloaded Buffer` can cause video playback issues?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2279]
When you turn on `Skip Preloaded Buffer`, the below dialog is shown.

Just wanted to ask the reason behind it.

![Screenshot_2024-07-29-09-21-13-05_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/user-attachments/assets/d88e331f-ecb8-41c3-8009-8306cb9e9332)

Thanks!

**Comment by inotia00** [comment]
Because it actually causes playback issues https://github.com/inotia00/ReVanced_Extended/issues/2257
