### ISSUE TITLE
feat(patch): hide `Browse store` button

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#228]
### Application

YouTube

### Issue

In some countries, the `Browse store` button is shown on certain channels

The `Hide merchandise banners` setting already exists, but it does not remove the `Browse store` button

We need a new adblock filter to get rid of this

### Patch

![Browse_store](https://user-images.githubusercontent.com/108592928/217060542-5db0fc8d-116e-4b3c-81f9-d782a80f5690.png)
hide this `Browse store` button

(attached screenshot is only shown to users residing in the United States)

### Motivation

The `Hide merchandise banners` setting already exists, but it does not remove the `Browse store` button

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.159.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.4)

**Comment by S23u512** [comment]
@inotia00 

Was this patch removed or was it combined with other patches? If it was combined with other patches its not working anymorw. I just wanted to ask this befors creating a new bug report.

**Comment by inotia00** [comment]
There is a bug in the latest YouTube version that hiding the browsing store button hides all buttons in the channel info
So this has been changed to be very tricky to block, so it has been removed in the latest build
