### ISSUE TITLE
bug(RVX Manager): the bug in Github API calls and the number of patch options first loaded

### ISSUE THREAD

**Issue by stainlf** [inotia00/ReVanced_Extended#2281]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

RVX Manager v1.20.4, v1.21.1

### Bug description

1. The issues below still persist. I am using AdGuard and have not set any exceptions on purpose, and this symptom does not occur at all in ReVanced Manager.
https://github.com/inotia00/ReVanced_Extended/issues/1956
![Screenshot_20240730_225849_RVX Manager](https://github.com/user-attachments/assets/2f628d66-2764-4d33-a1da-affd77e623f5)

2. When RVX Manager first loads the latest version, newly updated patch from a registered source, the patch itself is loaded properly, but the number of patch options is 0. There is no problem if the patching is proceeded, and if i go back and come back, the number of patch options returns to normal.
![Screenshot_20240623_210005](https://github.com/user-attachments/assets/35619975-11e8-4121-a05e-00c111090ef2)

### Solution

1. Please merge the relevant patch of ReVanced Manager.
https://github.com/ReVanced/revanced-manager/pull/1911
I've been waiting for this patch to be merged, but it hasn't worked, so I'm requesting it. This method is better than the way you fixed it.

2. Well, IDK. At least in ReVanced Manager, this symptom does not appear and the patch loading speed itself is much faster.

### Additional context

Thanks

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
RVX Manager is provided simply for my patch compatibility

There are no plans to fix bugs in RVX Manager

(This is also mentioned in the RVX Manager release notes)

Please use a different patching method than RVX Manager

**Comment by inotia00** [comment]
Maybe it's because I changed the Header to include PAT when sending a request to Github API

https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

(PAT is a unique value, so I didn't uploaded it in the source code)

**Comment by inotia00** [comment]
Yes, I have included my PAT in the latest manager build

**Comment by inotia00** [comment]
Even if I include PAT in my RVX manager build, the Github API rate limit is only increased from 60 requests per hour to 5000 requests per hour

The frequency of the rate limit toast is noticeably reduced compared to before, but the issue is still valid

The issue has been closed with no plans, so please do not mention me on this issue anymore
