### ISSUE TITLE
question: When will you guys add support version 19.17.33

### ISSUE THREAD

**Issue by rimehrab** [inotia00/ReVanced_Extended#2282]
### Application

YouTube

### Question description

Hello, Thank you guys for giving us another great or i would rather say one of the best folk.
My question is when you will add support fkr YouTube version 19.17.34
I use latest update of my phone software in that default yt version is 19.17.34 so i cannot uninstall my current version i need new patch
Thanks once again

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Here are three ways for you

Workaround 1. Patching RVX in a non-root environment
: This is the simplest way

Patching RVX in a non-root environment only requires the YouTube apk, so no downgrade is required

For detailed installation instructions, please refer to the [documentation](https://github.com/inotia00/revanced-documentation/blob/main/docs/rvx-manager.md)

Workaround 2. Downgrading YouTube using [Shizuku](https://github.com/RikkaApps/Shizuku) module [InstallWithOptions](https://github.com/zacharee/InstallWithOptions)
: If you know how to use Shizuku, this is not too difficult either

In InstallWithOptions, select the `Allow Downgrade` option and install YouTube 19.16.39

Then proceed with the patch

Workaround 3. Using YouTube 19.25.39
: [Unofficially, my patch works on YouTube 19.25.39 without any error messages](https://github.com/inotia00/ReVanced_Extended/issues/2241)

There is no support for bugs that occur in this case
