### ISSUE TITLE
suggestion (YT - Watch history): Use toggles instead of radio buttons for the `Watch history type` setting 

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2283]
### Application

YouTube

### Suggestion description

**Problem**

"Watch history type" doesn't imply that the options would be between `Original`, `Replace domain`, and `Block watch history`.  This can make it difficult for someone trying to block watch history or change the domain.

For example, if someone's watch history doesn't work and they see in the Watch history settings menu that "Watch history may not work due to DNS or VPN", they still will not know that they can fix this in YT RVX.

**Solution/Suggestion**

Separate the `Watch history type` setting into two toggles.

Toggle 1: `Block watch history`

Toggle 2: `Replace watch history domain` (Only toggleable when toggle 1 is disabled)

This will make it much easier to find these options.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Using toggle may make some confusion for user, since they're not sure if they're turning on the correct settings. In the past, this also happened with the `Spoof player parameter type` settings.

**Comment by inotia00** [comment]
I've been thinking about it for a long time, but it seems better to keep it as is rather than splitting it into two switches
