### ISSUE TITLE
bug (YT) : In portrait/vertical videos, the `Fullscreen Button` is not hiding itself when the player overlay is timed-out. It is working fine on normal/landscape videos.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2284]
### Type

Cosmetic

### Tools used

Revancify

### Application

YT v19.16.39

Latest patches & integrations.

### Bug description

In portrait/vertical videos, the `Fullscreen Button` is not hiding itself when the player overlay is timed-out. In normal/landscape videos, there is no issue.

I will show you the screenshots to better explain it.

Normal/landscape video with active player overlay: 
![Screenshot_2024-07-31-11-40-38-43_f22faf49515899f9781ec174a4d85388](https://github.com/user-attachments/assets/4a0a2e69-f69b-4b72-803a-08bb132b2276)

Normal/landscape video with timed-out player overlay: 
![Screenshot_2024-07-31-11-40-27-51_f22faf49515899f9781ec174a4d85388](https://github.com/user-attachments/assets/00d357d1-f94a-48e2-80e7-4ced6549e098)

Portrait/vertical video with active player overlay: 
![Screenshot_2024-07-31-11-30-22-35_f22faf49515899f9781ec174a4d85388](https://github.com/user-attachments/assets/f3b4d8a0-8c35-49a2-b5ad-5e42c537fbe6)

Portrait/vertical video with timed-out player overlay: 
![Screenshot_2024-07-31-11-30-30-64_f22faf49515899f9781ec174a4d85388](https://github.com/user-attachments/assets/e1a422b2-46ac-4620-8b7b-c68d79c3eb92)
As you can see in this screenshot, the player overlay has timed-out and the other overlay buttons are gone, but the Fullscreen button is still there.

### Error logs

```shell
No logs.
```

### Solution

All overlay buttons should get hidden when the player overlay is timed-out, irrespective of the orientation of the video.

### Additional context

My player button settings:

![Screenshot_2024-07-31-11-21-29-83](https://github.com/user-attachments/assets/b9b70a4a-4e5c-4e39-acc2-155013eca8d1)

### Device Environment

Realme 7 Pro

Android 12 (skin name: Realme UI 3.0)

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It also reproduces on unpatched YouTube
