### ISSUE TITLE
feat(YouTube): add `Hook Download Actions` patch

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#2285]
## Application
YouTube

## Feature description
**This is not a patch request, but a description of the feature that will be introduced in the next release.**

#### Basically, this setting is transferred from `Override download action buttons` located in Settings -> Player -> Player Buttons.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/5d262be1-6ff5-4f76-8973-4106ed7b2afe">

#### When enabled, the following sections will be overridden:
- `Download` button in Player Actions Bar:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/70c77ee0-bc7b-4590-8528-39cdec0c8f34">

- `Download video` section in Flyout Menu:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/e5bdbf75-cd81-4d89-8c12-64c762352f7a">

### 2. `Override playlist download action` setting:
**This setting will hook into the playlist download button, allowing users to use an external downloader.**

Before | After |
--- | --- |
<img width="263" alt="image" src="https://github.com/user-attachments/assets/4d0b9bc8-9660-4525-bc40-09cc4f7c803b">  | <img width="263" alt="image" src="https://github.com/user-attachments/assets/e1bcea36-c692-457b-83f6-2dfae290987b"> | 

#### In restricted countries:
Playlist download button is geo-restricted in numerous countries, for example, in Europe. This means that this setting will be completely useless. To resolve the issue, the playlist download button will be **forcibly enabled**.

Before | After |
--- | --- |
<img width="263" alt="image" src="https://github.com/user-attachments/assets/43658d52-753e-4cda-811b-9f000958e989">  | <img width="263" alt="image" src="https://github.com/user-attachments/assets/c28de188-3f1c-4fa4-ac76-2c03f53eb087"> | 

### Limitations:
Right now, due to the limitation of external downloader app (see below), only YTDLnis supports playlist download. Therefore, to use this feature you need to have YTDLnis installed in your phone.
- Seal: https://github.com/JunkFood02/Seal/issues/736
- NewPipe and Tublar: https://github.com/TeamNewPipe/NewPipe/pull/2018#pullrequestreview-311195954

## Motivation
- This patch will simplify the process of downloading videos and playlists for users.
- With YouTube's built-in downloader, Freemium users are limited to 360p resolution, and some videos may not be downloadable.
- The playlist download feature is restricted in most countries, so it's necessary to override the visibility of playlist download button.

## Acknowledgements
* [x]  This is not a feature request for YouTube.
* [x]  This issue is an explain for an existing feature request.
* [x]  I have chosen an appropriate title.
* [x]  All requested information has been provided properly.
* [x]  I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
@KobeW50 @inotia00 Can #2050 be transfered into this issues for better track ?

**Comment by Francesco146** [comment]
https://github.com/inotia00/revanced-patches/pull/70

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1)

**Comment by Rairof** [comment]
Seems like `Override download button` patch doesn't work anymore after 4.12.1 update in YouTube

**Comment by Francesco146** [comment]
the fix is coming (https://github.com/inotia00/revanced-patches/pull/71)
