### ISSUE TITLE
question: How to use CLI

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2286]
### Application

Other

### Question description

I looked at documentation and nothing there to how to open it i double click nothing opens. Can you tell me how to open it

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
See [documentation](https://github.com/inotia00/revanced-documentation/blob/main/docs/revanced-cli.md)

If you are on Windows, use [rvx-builder](https://github.com/inotia00/revanced-documentation/blob/main/docs/rvx-builder.md#using-rvx-builder-windows--macos--linux)

It is easier to use and supports ARSCLib for the latest Reddit patches
(You have to enable it in settings)

**Comment by KobeW50** [comment]
> It is easier to use and supports ARSCLib for the latest Reddit patches (You have to enable it in rvx-builder settings)

This isn't mentioned in the doc for patching reddit 2024.18.0+. (If i have time i can add it next week)
