### ISSUE TITLE
question: Hide related videos below player

### ISSUE THREAD

**Issue by RoonMoonlight** [inotia00/ReVanced_Extended#2287]
### Application

YouTube

### Question description

Hello, I have been using `related_video` General filter for YouTube to hide related videos for while. However seems YouTube changed its way to display the related videos section and now it displays again even I have set the `related_video` filter to hide it. Is there any workaround for this?

![Screenshot_20240802_184830_YouTube RVX](https://github.com/user-attachments/assets/87d46d18-b6ed-407b-be5b-bdc4ba09f0c9)
![Screenshot_20240802_184902_YouTube RVX](https://github.com/user-attachments/assets/00210d61-0b25-46de-a710-643380d52d50)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Google changed the identifiers of components on the server side

This resulted in many custom filters breaking

The identifier of components in related videos is now `video_lockup_with_attachment`

The problem is that videos in the home feed and videos in the subscriptions feed both use the same identifier

If you add the keyword `video_lockup_with_attachment` to your custom filter, all videos in the home feed, subscriptions feed, and related videos will be blocked

If you combine it with a buffer string filter, it's a little better

If you add the keyword `video_lockup$relatedH` to your custom filter, you can filter only related videos

This also doesn't filter live streams that appear in related videos

Since this is a server-side change, it's unlikely to be reverted

**Comment by ARYAN-gif-creator** [comment]
Can anyone plz mention what buffer string filter to combine to make that identifier better

**Comment by KobeW50** [comment]
> If you add the keyword video_lockup_with_attachment to your custom filter, all videos in the home feed, subscriptions feed, and related videos will be blocked

Is there any risk to one's YT account or the like by using this filter? 

oSumAtrix said that using the related_video filter is ["highly dangerous as it strains the API"](https://github.com/ReVanced/revanced-patches/issues/981#issuecomment-1854975333) yet i havent ever heard of anyone facing consequences. What are your thoughts on this?

**Comment by inotia00** [comment]
It is true that it uses a lot of unnecessary resources, but it is not likely to put a huge burden on YouTube servers

**Comment by vaibhav423** [comment]
> Can anyone plz mention what buffer string filter to combine to make that identifier better
> 

+1

**Comment by KobeW50** [comment]
@vaibhav423 update with the latest patches. RVX now has a setting to hide related videos in settings > Revanced Extended > Feed > Video filter > Hide related videos. Note that it is an experimental feature

**Comment by vaibhav423** [comment]
video_lockup$relatedH was very helpful
But i am also looking to remove the videos in the home feed also.


video_lockup_with_attachment did do the work 

but it also removed the content when searching for video from search bar.


Is there any other buffer string literal as inotia mentioned to remove the home feed (all video from home tab).

**Comment by droemmelbert** [comment]
> @vaibhav423 update with the latest patches. RVX now has a setting to hide related videos in settings > Revanced Extended > Feed > Video filter > Hide related videos. Note that it is an experimental feature

Just patched and do not have this option in my settings :/

**Comment by KobeW50** [comment]
@droemmelbert You need to include the `Hide feed components` patch. If you still have trouble, please move to one of the revanced extended support platforms (discord, reddit, telegram) for assistance.

**Comment by Lyqed** [comment]
> @droemmelbert You need to include the `Hide feed components` patch. If you still have trouble, please move to one of the revanced extended support platforms (discord, reddit, telegram) for assistance.

Hi, I have this option but it doesn't seem to do anything. Is there anything else I need to do after turning the toggle on?

**Comment by rrnm444** [comment]
> Google changed the identifiers of components on the server side
> 
> This resulted in many custom filters breaking
> 
> The identifier of components in related videos is now `video_lockup_with_attachment`
> 
> The problem is that videos in the home feed and videos in the subscriptions feed both use the same identifier
> 
> If you add the keyword `video_lockup_with_attachment` to your custom filter, all videos in the home feed, subscriptions feed, and related videos will be blocked
> 
> If you combine it with a buffer string filter, it's a little better
> 
> If you add the keyword `video_lockup$relatedH` to your custom filter, you can filter only related videos
> 
> This also doesn't filter live streams that appear in related videos
> 
> Since this is a server-side change, it's unlikely to be reverted

Hello, can I modify it to only 12 recommendations? 
Not the normally loads of recommended videos.

**Comment by muffafa** [comment]
> video_lockup$relatedH was very helpful But i am also looking to remove the videos in the home feed also.
> 
> video_lockup_with_attachment did do the work
> 
> but it also removed the content when searching for video from search bar.
> 
> Is there any other buffer string literal as inotia mentioned to remove the home feed (all video from home tab).
> 
> Edit : found a way around it, to get rid of all distraction
> 
> Use this : 1.)video_lockup_with_attachment And 2.)Enable table layout (in general)
> 
> If u don't do 2.) no video would be available other, than those in you tab.

Thank you so much. you saved my day. I also recommend to remove homepage under general > navıgatıon buttons. Also turn on always change start page and choose start page as library. Turn offs shorts. And lastly set setings under player such as hide and screeen cards etc.
