### ISSUE TITLE
No videos plays with spoof client and device dimension patch enabled. 

### ISSUE THREAD

**Issue by NichirinSword** [inotia00/ReVanced_Extended#2288]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

While spoof client enabled, enabling device dimension patch makes all the videos unplayable. There's some kind of errors. But if spoof client is turned off, all videos plays and also unlocks higher resolution. But there’s another issue arise with spoof client off, like buffering issue though it is not the infinite buffering issue. Videos plays like 35-40 sec and take some time to buffer and plays, then again in some more seconds another buffering then video plays but quality drops down to like 360p or 480p.

### Device Environment

Android 14
Realme UI 5.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Spoof device dimension is an `Experimental Flags`

**Comment by Aryan-Chauhan** [comment]
Are you sure you are using latest patches?

Both `Spoof Client` & `Spoof Dimensions` are enabled for me, and the app works fine.
