### ISSUE TITLE
feat(patch): 30 Fps on 60 fps videos

### ISSUE THREAD

**Issue by nochlab1** [inotia00/ReVanced_Extended#229]
### Application

YouTube

### Issue

Videos that are 60fps can't be played in 30fps and sometimes the internet isn't good enough to play higher quality at 60fps when it would be able to if it was playing at 30fps

### Patch

Add a option for 30fps which is available as if the device doesn't support 60fps it plays at 30fps

### Motivation

Watch higher quality on bad service

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
