### ISSUE TITLE
feat(YouTube/Spoof client): fix background playback issue with livestream on iOS clients

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2290]
### Application

YouTube

### Feature description

**This is not a patch request, but a description of the feature that will be introduce in the next release.**

Background playback does not work on livestreams when spoofing with iOS clients.

This is a known issue, and a [commit (selectively spoof client for general video/livestreams/Shorts/fallback)](https://github.com/inotia00/revanced-patches/commit/aabf1ecb97baf5c2020f311fbc9940f31ee54926) was added as a temporary workaround for this.

Luckily I found a method to force-enable background playback, which may be a valid workaround for the background playback issue with livestream on iOS clients.

One problem is that this fix only works if the `Remove background playback restrictions` patch is included.

Accordingly, the `Remove background playback restrictions` patch will be added as a dependency of the `Spoof client` patch.

### Motivation

The iOS client has the least side effects.

To use the iOS client as the default, I need to fix the remaining side effects as much as possible.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
> ReVanced/revanced-patches#3480

That PR doesn't resolve the watch history issue on the brand account

> However, I know that iOS clients do not support the OPUS codec. Is there nevertheless a way to apply the OPUS codec?

The response of the audio codec depends on the response of the video codec https://github.com/yt-dlp/yt-dlp/issues/8377
(i.e. it is not possible)

**Comment by inotia00** [comment]
> I thought it was because it appeared to have been resolved [here](https://github.com/ReVanced/revanced-patches/issues/3208). Am I wrong?

Yes, watch history issue for brand accounts is still not resolved
It is also mentioned in the [PR's comments](https://github.com/ReVanced/revanced-patches/pull/3480#issuecomment-2261203861)

**Comment by 0xrxL** [comment]
https://github.com/ReVanced/revanced-patches/issues/3503

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1)
