### ISSUE TITLE
bug: Hide Navigation Bar patch is not working (YouTube)

### ISSUE THREAD

**Issue by VioletS24Ultra** [inotia00/ReVanced_Extended#2291]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39
RVX Manager v1.21.1

### Bug description

Enable Hide Navigation Bar patch, and restart YouTube app. Notice how navigation bar at the bottom does not hide.

PS: Is this patch suppose to hide bottom navigation bar or something else?

### Device Environment

Android v6.1 OneUI

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by VioletS24Ultra** [comment]
I found this patch by using the search feature, not sure where this patch is located.

**Comment by inotia00** [comment]
First, the `Hide navigation bar` patch does not exist.

The `Shorts components` patch includes a `Hide navigation bar` setting, but this only works in the Shorts player.

Additionally, the `Hide navigation bar` setting is defined as `Experimental Flags`.

Settings defined as `Experimental Flags` have a very high risk of causing bugs, so they are recommended for experimental purposes only.

For this reason, I do not receive bug reports for settings specified as `Experimental Flags`.
