### ISSUE TITLE
suggestion(RVX Builder): add support for anti-split

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2292]
### Application

Other

### Suggestion description

About two weeks ago, some apps began to no longer provide universal apk in the Google Play API

As a result, the latest versions of Reddit and Twitter (X) can no longer use the universal apk
(Other apps, such as YouTube, may also stop providing universal apk in the future)

I plan to add support for anti-split in rvx-builder temporarily, until ReVanced Patcher adds support for split-apk

If this suggestion is reflected, rvx-builder will be able to patch apps for which a universal apk is not provide
(e.g. Reddit 2024.30.0+)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [rvx-builder-3.15.1](https://github.com/inotia00/rvx-builder/releases/tag/v3.15.1)

**Comment by federicogith** [comment]
@inotia00 you might be interested in [revanced-antisplit](https://github.com/AbdurazaaqMohammed/revanced-antisplit).
