### ISSUE TITLE
bug(YouTube/Overlay buttons): `Always repeat` button doesn't work when the video is minimized

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2293]
### Type

Error at runtime

### Tools used

Revancify

### Application

YT v19.16.39

Latest patches, integrations & ReVancify.

### Bug description

If we use the yellow mode of `Always Repeat Button`, below 2 things happen:

1. When the video ends, the video goes to 0:00 and stays at paused condition [Intended behaviour].
2. If we play any video from some playlist or Watch Later, and it ends, the video goes to 0:00 and stays at paused condition [Intented behaviour].

But there is a bug, it is described below:

If the video ends while it is playing in the Miniplayer, then it just starts playing the video from the beginning.

In other words, if a video ends while it is playing in the Miniplayer, the yellow mode of `Always Repeat Button` won't be obeyed.

![Screenshot_2024-08-03-20-52-23-79_f22faf49515899f9781ec174a4d85388](https://github.com/user-attachments/assets/b9b08aea-c0e7-4467-b414-f5689c07a49d)

### Error logs

```shell
No logs.
```

### Solution

The yellow mode of `Always Repeat Button` should work even if the video ends while being in the Miniplayer View.

It works fine when videos end while being in Half Player View, Fullscreen View & Background Playback.

### Additional context

To reproduce the bug, do this:
1. Open any video and make the `Always Repeat Button` yellow.
2. Go to the last 15 seconds of the video.
3. Now swipe the video down, so that it keeps playing, but in the Miniplayer.
4. Now let the video end.
5. You will notice that the video restarts from the beginning, which shouldn't happen when the `Always Repeat Button` is yellow.

### Device Environment

Realme 7 Pro

Android 12 (skin name: Realme UI 3.0)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1)

**Comment by hugobasith** [comment]
J̌~~jppplP
L~~
