### ISSUE TITLE
question: Would you accept paid feature requests? (Foldable phone fullscreen rotate)

### ISSUE THREAD

**Issue by assist726** [inotia00/ReVanced_Extended#2294]
### Application

YouTube

### Question description

https://github.com/ReVanced/revanced-patches/issues/1840

I currently use a foldable phone and on the internal screen, fullscreen doesn't rotate the video correctly to landscape.

Would happy pay a reasonable amount to get this feature implemented

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Sorry, I'm not good enough to receive sponsorship

For feature requests on YouTube, please contact the ReVanced Team
