### ISSUE TITLE
bug (YT) : Setting `Shorts repeat state` to `Pause` doesn't work. Shorts still starts playing from the beginning after ending.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2295]
### Type

Error at runtime

### Tools used

Revancify

### Application

YT v19.16.39

### Bug description

Described in title.

### Error logs

```shell
No logs.
```

### Solution

It should work as intended.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
> This bug happens when you are using iOS spoof client for Shorts.
> 
> I turned off whole spoof client and now it's working fine, now the Shorts do get paused when they end.

Thanks for the reply

I think the issue https://github.com/inotia00/ReVanced_Extended/issues/2231 is also due to this

Since the `Spoof client` patch is included by default, it seems better to make the `Shorts repeat state` setting an `Experimental Flags`

**Comment by MondayNitro** [comment]
> I think the issue #2231 is also due to this


its not, it occurs on both root and non-root. also i dont use spoof client on non-root as no playback issue there for me.
i tried different kinds of shorts, it seems that if you play related shorts under currently playing video, issue #2231 doesnt occur.
![download](https://github.com/user-attachments/assets/3d2f51e9-1314-420d-807d-1b967cc0173d)
for all other types of shorts, #2231 occurs

**Comment by MondayNitro** [comment]
it shouldnt be account specific too, as i tried on 3 different devices, all having different accounts and the issue was there

**Comment by inotia00** [comment]
Since [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1), the `Change Shorts repeat state` setting has been changed to an `Experimental Flags`

Closing issue

**Comment by soykot500** [comment]
No logs.
