### ISSUE TITLE
bug: Can't scroll through more than 30 videos under Oldest/Popular filters due to A/B tests

### ISSUE THREAD

**Issue by imvoldemort** [inotia00/ReVanced_Extended#2296]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.16.39 +

### Bug description

Can't scroll through more than 30 videos if I sort them by oldest or popular filter under Videos section. Shorts section seems to work fine though. It seems like an A/B test issue because it works fine on the other account.

### Device Environment

Android 10, MIUI 12.5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
You said you are using v19.16.39+.

Have you tried using v19.16.39?

You don't get to report bugs if you are using unsupported versions.

**Comment by inotia00** [comment]
This is an issue with unpatched YouTube
