### ISSUE TITLE
feat(YouTube/Spoof client): partial fix for watch history issue of brand accounts on iOS clients

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2297]
### Application

YouTube

### Feature description

**This is not a patch request, but a description of the feature that will be introduce in the next release.**

Watch history does not work on brand accounts when spoofing with iOS clients.

I've been tracking this known issue for a long time and found out that [SmartTubeNext](https://github.com/yuliskov/SmartTube) can force the generation of Watch history.

(This is invoked by the [TrackingService](https://github.com/yuliskov/MediaServiceCore/blob/master/youtubeapi/src/main/java/com/liskovsoft/youtubeapi/track/TrackingService.java) class in the [MediaServiceCore](https://github.com/yuliskov/MediaServiceCore) library.)

Of course, it is impossible to directly apply the method of SmartTubeNext, which is a completely different client, to ReVanced, but it seems possible to apply it to ReVanced with restrictions.

If this is implemented in ReVanced, there are the following limitations:
1. Watch history for brand accounts only works on **YouTube 18.38.45 or earlier**.
2. The last watched time is not saved. (I haven't implemented this in the patch yet.)

### Motivation

Although there are many prerequisites, it may be useful for someone.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
> Watch history for brand accounts only works on YouTube 18.38.45 or earlier.

Will this work when spoofed to this version or earlier (via the spoof app version patch)?

**Comment by inotia00** [comment]
> Will this work when spoofed to this version or earlier (via the spoof app version patch)?

This fix doesn't work with `Spoof app version`

It seems to be related to the YouTube API response changing in YouTube versions after 18.38.45

**Comment by 0xrxL** [comment]
What is the goal of this issue tracking? Improve the already existing patch by ReVanced?

**Comment by inotia00** [comment]
> What is the goal of this issue tracking? Improve the already existing patch by ReVanced?

ReVanced doesn't fix brand account's watch history issues

See https://github.com/inotia00/ReVanced_Extended/issues/2290#issuecomment-2266636076 and https://github.com/inotia00/ReVanced_Extended/issues/2290#issuecomment-2266646179

**Comment by 0xrxL** [comment]
Then the title of ReVanced's PR is wrong. 🤔

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.12.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.1)
