### ISSUE TITLE
rvx music add not blocked 

### ISSUE THREAD

**Issue by Shiroe93** [inotia00/ReVanced_Extended#2298]
### Type

Other

### Tools used

RVX Manager

### Application

RVX music 7.10.52

### Bug description

Adds are not blocked 
![Screenshot_20240804_143011_One UI Home](https://github.com/user-attachments/assets/33f375e8-5080-447e-a4da-e57026b0b880)

### Additional context

I don't know why but i have this problem only with your version and not with the "official" revanced

### Device Environment

Android 14 one UI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Shiroe93** [comment]
• Amoled 
• Bitrate default value 
• Bypass image region restrictions
 • Certificate spoof 
• Change start page 
• Custom branding icon for YouTube Music 
• Custom branding name for YouTube Music 
• Disable auto captions 
• Disable dislike redirection 
• Enable OPUS codec 
• Enable debug logging 
• Enable landscape mode 
• Flyout menu components 
• GmsCore support 
• Hide account components 
• Hide action bar components 
• Hide layout components 
• Navigation bar components 
• Player components 
• Remove background playback restrictions 
• Remove viewer discretion dialog 
• Restore old style library shelf 
• Return YouTube Dislike 
• Sanitize sharing links 
• Settings for YouTube Music 
• SponsorBlock 
• Spoof app version 
• Translations for YouTube Music 
• Video playback

**Comment by inotia00** [comment]
You did not include the `Hide ads` patch

Please include the `Hide ads` patch and re-patch

**Comment by Shiroe93** [comment]
My bad in the previous versions that i used was included in the default selection so i didn't notice

**Comment by inotia00** [comment]
You responded as quickly as possible so I could respond to you quickly too
So no problem
