### ISSUE TITLE
question: will this be helpful to RVX Manager?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2299]
### Application

YouTube

### Question description

[revanced-antisplit](https://github.com/AbdurazaaqMohammed/revanced-antisplit)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
According to GPL v3.0, all derivative software must disclose the source code.

This repository does not disclose the source code.
