### ISSUE TITLE
feat(patch): request to remove next and previous button in player

### ISSUE THREAD

**Issue by rks2000** [inotia00/ReVanced_Extended#23]
### Application

YouTube

### Issue

Accidentally switching videos

### Patch

Patch request to remove next and previous video change button in player.

### Motivation

Almost everytime when double tapping screen for forwarding video i accidentally tap on the next and previous button and videos gets changed which is very annoying. 
![IMG_20221223_135735](https://user-images.githubusercontent.com/62375786/209300828-32b3c93a-bca7-4d87-9ea4-d9fc46184549.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cavidmammadov** [comment]
yes, it annoys me too.  I have asked this question.  but it seems that this is not possible yet

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.156.4
