### ISSUE TITLE
"Disable Shorts PIP mode" not working

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#230]
### Type

Other

### Application

Youtube

### Bug description

The "disable shorts pip" is not working after latest patches.

### Steps to reproduce

No steps. The option is not working. If we on the option, then it will not work.

### Relevant log output

```shell
...
```

### Screenshots or videos

Uploading az_recorder_20230207_101936.mp4…

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Vipin2003** [comment]
https://user-images.githubusercontent.com/93650504/217171849-17919310-46ab-45f7-a942-93e2f0383c47.mp4

**Comment by inotia00** [comment]
Settings in the Experimental Flags are not always guaranteed to work.

That's why it's in the experimental flag

So please don't report bugs related to experimental flags.

**Comment by Vipin2003** [comment]
But it was working fine till previous patches...but not with new one.
