### ISSUE TITLE
bug: rvx manager 1.21.1 doesn't support korean input in settings

### ISSUE THREAD

**Issue by kyan5221** [inotia00/ReVanced_Extended#2302]
### Type

Other

### Tools used

RVX Manager

### Application

rvx manager v1.21.1

### Bug description

I can't type korean characters in settings.
previous rvx manager had no multi-lang input ssue.

![Screenshot_20240805_200140_RVX Manager](https://github.com/user-attachments/assets/d0304658-f754-4d5d-9402-434177b67972)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I noticed the issue was opened late

If the issue is reproducible on ReVanced Manager, please open an issue there

If the issue is resolved on ReVanced Manager side, these changes will also be reflected on RVX Manager
