### ISSUE TITLE
bug: (YouTube) Im getting end screen cards despite the hide end screen cards setting being enabled

### ISSUE THREAD

**Issue by VioletS24Ultra** [inotia00/ReVanced_Extended#2303]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.16.39

Patches:

[selected_patches_2024-08-06_23_00_55.json](https://github.com/user-attachments/files/16515185/selected_patches_2024-08-06_23_00_55.json)

Settings:

[RVX_v19.16.39_2024-08-06.txt](https://github.com/user-attachments/files/16515653/RVX_v19.16.39_2024-08-06.txt)

### Bug description

Im getting end screen cards despite the hide end screen cards setting being enabled.

Screenshot:

![Screenshot_20240806_225009_RVX](https://github.com/user-attachments/assets/245b3d6f-e5aa-4cc1-b60c-fd699e73eb51)

### Error logs

```shell
I dont have a computer.
```

### Solution

Not really sure.

### Device Environment

Android 6.1 OneUI

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
End cards are the video suggestions embeded into the video player.

To disable these, go to Settings > Revanced Extended > Player > Fullscreen > Hide related video overlay

**Comment by VioletS24Ultra** [comment]
> End cards are the video suggestions embeded into the video player.
> 
> To disable these, go to Settings > Revanced Extended > Player > Fullscreen > Hide related video overlay

I cant change those settings, they are grayed out.

**Comment by KobeW50** [comment]
When `Disable engagement panel` or `Enable tablet mode` is enabled the option is greyed out. I see you currently have `Disable engagement panel` enabled

**Comment by VioletS24Ultra** [comment]
> When `Disable engagement panel` or `Enable tablet mode` is enabled the option is greyed out. I see you currently have `Disable engagement panel` enabled

I got it, what disable engagement panel setting actually does?

**Comment by KobeW50** [comment]
It hides the Video title and channel name at the top left of the video player. It may hide other things as well, but im not sure.
