### ISSUE TITLE
question (YT) : Is there any benefit of keeping `Enable OPUS Codec` enabled?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2306]
What difference would it make? Should I keep it on or off?

![Screenshot_2024-08-07-20-36-01-67_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/user-attachments/assets/0e2fae92-3ba8-4ce6-8da5-85c0a066b773)

Thanks!

**Comment by inotia00** [comment]
This is not related to the patch, so I'm closing the issue

Please refer to the community, such as the [subreddit](https://www.reddit.com/r/youtubedl/comments/11v8xkk/opus_vs_m4a/)
