### ISSUE TITLE
bug (YT) : Shorts become long when they end & pause.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2308]
### Type

Error at runtime

### Tools used

Revancify

### Application

v19.16.39

Latest patches.

### Bug description

I know that fixing bugs in experimental patches is low-priority for you, but I thought of reporting this bug to know your opinion and if it's fixable or not.

Here's the bug:

When you set `Change Shorts Repeat State` to `Pause`, it works fine, the Shorts do pause when they end. But they become `LONG` when they end & pause. It is shown in the below screen recording:

https://github.com/user-attachments/assets/9175b115-4e6b-4ee9-912e-456151282b3c

Thanks!

### Error logs

```shell
No logs.
```

### Solution

Shorts shouldn't become long when they end & pause.

### Additional context

Hide NavBar in Shorts is off.

### Device Environment

Realme 7 Pro.

Android 12 (skin name: Realme UI 3.0).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [ ] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Change Shorts repeat state` setting is an `Experimental Flags`
