### ISSUE TITLE
Video bug in Latest Patches

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#231]
### Type

Other

### Application

YT

### Bug description

The video (which is played lastly) is always opened in recents in Youtube. This is happening from today's patch. Clean Installed.

### Steps to reproduce

Play any video...close YT from recents...Reopen YT again. The video is there.

### Relevant log output

```shell
...
```

### Screenshots or videos

https://user-images.githubusercontent.com/93650504/217170637-74b0b297-64ce-4fba-a37c-d5d8f5be536c.mp4

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Not an issue with ReVanced
Check your system settings

**Comment by Vipin2003** [comment]
Ohh...It was the feature probided by YT for Premium subscribers. I checked this on main YT
