### ISSUE TITLE
suggestion: bump Reddit patches

### ISSUE THREAD

**Issue by rywz** [inotia00/ReVanced_Extended#2310]
### Application

Other

### Suggestion description

As said on https://github.com/ReVanced/revanced-patches/issues/3099#issuecomment-2252351360 & https://github.com/ReVanced/revanced-patches/issues/3099#issuecomment-2252504457, AAPT related issues seems to be fixed but trying to patch Reddit via the manager will fail due to out-of-date patches.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
If the ReVanced Team does it, it will apply to my patch too

**Comment by kitadai31** [comment]
revanced-patches-arsclib appears to support Reddit 2024.28.0+
but as stated in this issue, Reddit 2024.28.0+ can also be compiled on the nornal ReVanced CLI & Manager (not arsclib)

Do you plan to go back to regular patches?

**Comment by inotia00** [comment]
The latest Reddit does not have a universal apk

ReVanced Patcher does not officially support split-apk

The docs tell users to download the universal apk and patch it

(So adding support for the latest Reddit without any preparation would confuse many users)

If ReVanced Patcher or Composed Manager officially adds support for split-apk, I'm willing to do it

**Comment by kitadai31** [comment]
It makes sense. Thank you for answering!
