### ISSUE TITLE
bug: Hold to seek overlay bug

### ISSUE THREAD

**Issue by GKid94** [inotia00/ReVanced_Extended#2312]
### Type

Other

### Tools used

CLI

### Application

![Screenshot_2024-08-10-12-23-08-744_com miui securitycenter](https://github.com/user-attachments/assets/1fa55ecc-5bd7-4254-baf1-bc27881ccba6)

### Bug description

The video image blurs and the seekbar drops down when holding it
![Screenshot_2024-08-10-08-50-47-541_app rvx android youtube](https://github.com/user-attachments/assets/e18ceb64-cd3b-4ecc-bb63-90e2f8ec48a3)

### Device Environment

![Screenshot_2024-08-10-12-23-15-071_com android settings](https://github.com/user-attachments/assets/d8b7f964-82b9-48ef-9c5c-2297e808b984)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.25.39 is not a supported version

**Comment by GKid94** [comment]
Which one is?

**Comment by Aryan-Chauhan** [comment]
> Which one is?

Insread of using CLI, start using ReVancify or RVX Manager.

Recommended versions are shown there.

**Comment by GKid94** [comment]
![Screenshot_2024-08-12-08-47-47-439_com revanced net revancedmanager](https://github.com/user-attachments/assets/d5623777-2622-4ff0-affb-a1fe93045851)

**Comment by inotia00** [comment]
It is an illegal build

Build it yourself according to the [documentation](https://github.com/inotia00/revanced-documentation/blob/main/docs/rvx-manager.md)

**Comment by Aryan-Chauhan** [comment]
> ![Screenshot_2024-08-12-08-47-47-439_com revanced net revancedmanager](https://github.com/user-attachments/assets/d5623777-2622-4ff0-affb-a1fe93045851)
> 

LMFAO, fake app.

**Comment by GKid94** [comment]
> It is an illegal build
> 
> Build it yourself according to the [documentation](https://github.com/inotia00/revanced-documentation/blob/main/docs/rvx-manager.md)

It get's files from the official website
