### ISSUE TITLE
bug (RVX Manager): Mount install method doesn't work if the "Save patched app" option is disabled

### ISSUE THREAD

**Issue by FixItKit** [inotia00/ReVanced_Extended#2314]
### Type

Other

### Tools used

RVX Manager

### Application

RVX Manager 1.21.1

### Bug description

RVX Manager doesn't mount anything when trying to install any app with the mount install method if the "Save patched app" option is turned off. This bug does not happen in ReVanced Manager.

1. Turn off "Save patched app"
2. Patch any app
3. Try to install it with the mount install method

### Device Environment

Android 13, One UI 5.1.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
RVX Manager is provided simply for my patch compatibility

There are no plans to fix bugs in RVX Manager

(This is also mentioned in the RVX Manager release notes)

Please use a different patching method than RVX Manager
