### ISSUE TITLE
bug: Forced auto captions are disabled won't work in YouTube shorts

### ISSUE THREAD

**Issue by Bakchxd** [inotia00/ReVanced_Extended#2316]
### Type

Other

### Tools used

RVX Manager

### Application

youtube-rvx_v19.16.39-patches_v4.12.1

### Bug description

Disable forced auto captions doesn't work in YouTube shorts. 
![Screenshot_20240812-080248](https://github.com/user-attachments/assets/c5b7bcb6-13c6-4f25-8a57-261ebd3c690b)

### Device Environment

Android 11 Realme ui

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This patch now follows [ReVanced's source](https://github.com/inotia00/ReVanced_Extended/issues/2267#issuecomment-2249329547)
Perhaps the same bug can be reproduced in ReVanced

Please open an issue in ReVanced's repository
If an issue is fixed in ReVanced, it will be applied to RVX as well

**Comment by Bakchxd** [comment]
issue opened in ReVanced's repository 😶
