### ISSUE TITLE
feat: Center video in fullscreen 

### ISSUE THREAD

**Issue by GKid94** [inotia00/ReVanced_Extended#2317]
### Application

YouTube Music

### Feature description

Add an option to center the video in YouTube fullscreen because it's a little on the side 

### Motivation

The would be properly centered and easier to watch

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue is closed because it is a patch request for YouTube

**Comment by GKid94** [comment]
Can you add it?
