### ISSUE TITLE
bug: RVX Manager - Installation conflict when when trying to update YouTube after patching

### ISSUE THREAD

**Issue by VioletS24Ultra** [inotia00/ReVanced_Extended#2318]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39
RVX Manager 1.21.1

### Bug description

Updating YouTube app after patching fails, I uninstalled RVX Manager and cleared data and cache and tried patching again. But updating the app fails.

![Screenshot_20240812_132342_RVX Manager](https://github.com/user-attachments/assets/d3ebe04e-50cf-4963-9ae1-068cf5bf85b6)

### Error logs

```shell
No log.
```

### Solution

Not really sure.

### Device Environment

Android 14 OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The reason why this message is displayed is because the patched app is signed with a different signing key

(If you reinstall RVX Manager, the signing key will change)

Uninstall the previously installed RVX and then reinstall the patched app

**Comment by VioletS24Ultra** [comment]
> The reason why this message is displayed is because the patched app is signed with a different signing key
> 
> (If you reinstall RVX Manager, the signing key will change)
> 
> Uninstall the previously installed RVX and then reinstall the patched app

Actually no, I only uninstalled RVX Manager afterwards, after I got this error message. I wiped my phone today earlier, then used RVX Manager to install YouTube. Then I saw your new patch release, patched YouTube app and when I tried to install it I got this error. I had to uninstall older  patched YouTube, then installing the new one worked correctly.
