### ISSUE TITLE
question: "Change share sheet" where is this patch in the settings?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2319]
### Application

YouTube

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Settings > ReVanced Extended > Miscellaneous > Experimental Flags > Change share sheet

If this setting is not present, check if the patch is included
