### ISSUE TITLE
bug: subscribe button + new like/dislike pill doesnt show anymore

### ISSUE THREAD

**Issue by NMBlanco** [inotia00/ReVanced_Extended#232]
### Type

Cosmetic

### Application

v 18.05.34 (patched with revanced manager .54)
v 18.04.35 (RVX Magisk Module)

### Bug description

Since the latest versions, the design of the like/dislike and subscription pill has changed / been removed.
In versions before 18.04.35 there was also that gradient style of the first comment. Now its just plain black.
I don't have the old layout enabled. Tried clean reinstalling several times, but its still the same.
Saw other people having the same issue in RVX Telegram Chat.

### Steps to reproduce

See above

### Relevant log output

```shell
/
```

### Screenshots or videos

![Screenshot_20230207-195406~2](https://user-images.githubusercontent.com/12681440/217339818-9e2ed830-27ce-4ab0-9d0c-8974c040a95b.png)

### Device Environment

Android 12, latest Magisk, latest LSposed
Motorola Edge 30 Ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by xgangsa** [comment]
Mine too, when reinstall yt app set with old layout. But i copied youtube.xml in sharedpref folder on backup yt app can apply new layout.

**Comment by inotia00** [comment]
The new layout follows your google account status (server side)

This is not an issue in ReVanced and cannot be fixed in the frontend.
