### ISSUE TITLE
bug(RVX Manager): In `Installed App Info` pakage name appears as `Stock` app and `Open` button does open `Stock` app on the patch success screen

### ISSUE THREAD

**Issue by ghost** [inotia00/ReVanced_Extended#2320]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

RVX Manager 1.21.1

### Bug description

1. In the bellow environment, pakage name appears as `Stock` one maybe by #1388 fix (or in v1.21.1)
`Dashboard > Installed Apps > Info`

![Screenshot_20240812_221027](https://github.com/user-attachments/assets/8832ab5e-2638-4702-b5c3-38ed9a47ff0a)

They are both the same package name but it appears divided into two.

Order Version
![Screenshot_20240812_220956](https://github.com/user-attachments/assets/9eb242c1-dbb7-441c-8b4c-d78c7b3ac6d8)

Updated Version (package name bug occured)
![Screenshot_20240812_222612](https://github.com/user-attachments/assets/62aabdd3-c3ff-4ccd-b818-499c543bbd71)

2. `Install` button works but `Open` button does open `Stock` app on the patch success screen. If `Stock` app don't be installed, `Open` button does not work.

### Additional context

Thanks.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by VioletS24Ultra** [comment]
Related? #2318

**Comment by inotia00** [comment]
RVX Manager is provided simply for my patch compatibility

There are no plans to fix bugs in RVX Manager

(This is also mentioned in the RVX Manager release notes)

Please use a different patching method than RVX Manager

**Comment by inotia00** [comment]
I have no plans to fix bugs in RVX Manager

Therefore I will no longer accept any reports of bugs in RVX Manager
