### ISSUE TITLE
suggestion: YouTube - Merge anddea's 'Default Quality & Speed): Add an option to disable toasts when changing the default values' patch

### ISSUE THREAD

**Issue by ghost** [inotia00/ReVanced_Extended#2323]
### Application

YouTube

### Suggestion description

This patch would be super cool to have, I know you dont take any patch requests anymore for YouTube but could you please consider adding this? You only need to merge this.

https://github.com/anddea/revanced-patches/commit/cc95f316485fe1759621b37471980c0ffe14d7cd

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by VioletS24Ultra** [comment]
https://github.com/inotia00/revanced-patches/pull/76

**Comment by VioletS24Ultra** [comment]
https://github.com/inotia00/revanced-patches/pull/76

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
