### ISSUE TITLE
suggestion: RVX Manager   "Custom package │ name"

### ISSUE THREAD

**Issue by Yumipk** [inotia00/ReVanced_Extended#2324]
### Application

Other

### Suggestion description

![Screenshot_2024-08-14-23-21-30-78_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/8919ce0e-4533-4fa7-9509-d324f7d7816c)

Can this feature be added ?
"Custom package  name" YouTube .
😄

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2258#issuecomment-2235275165
