### ISSUE TITLE
Chapter thumbnails are White

### ISSUE THREAD

**Issue by mysticmac3** [inotia00/ReVanced_Extended#2325]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube RVX v19.16.39 Patch v4.12.3

### Bug description

1. Chapters thumbnails are white in all videos
2. Open any video with chapters and select chapters
3. Tried with both Bypass image restrictions on and off
![20240815_082539](https://github.com/user-attachments/assets/6608878c-14f6-4a76-8d19-a51c797688d5)

### Device Environment

Samsung Galaxy Note 9, and Samsung galaxy S24 Ultra

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please check if the issue is reproduced on unpatched YouTube

If not, exclude the patches one by one and report back which patch is causing the issue

**Comment by mysticmac3** [comment]
Sorry my bad this problem persists in the official app as well, before posting the issue that wasn't the case but now even official app has the same problem, seems like YouTube is the problem, thanks
