### ISSUE TITLE
question: Custom Filters: Hide home feed?

### ISSUE THREAD

**Issue by shivammishra2004** [inotia00/ReVanced_Extended#2326]
### Application

YouTube

### Question description

I used to use home custom filter to hide home feed. But now youtube has changed the component to video_lockup.
I saw how you added the buffer string $relatedH to make it hide only the related video. 

Is there some similar buffer string for hiding home feed?
Also can you please include live streams as well as normal videos. I just want both related videos and home feed be completely blank.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
If it helps, you can hide the Home button and make the app automatically start in the subscriptions feed so that it's impossible to view the home feed.

**Comment by shivammishra2004** [comment]
Thanks, I actually knew about this feature, I used it to hide the home button and my start page was you tab. The problem was when I clicked back, the youtab changes to home feed. I thought that would be same for other pages also.That's why I posted this. But setting it to subscription doesnt show home feed at all. Still I would like to keep this open as it might help others.

**Comment by inotia00** [comment]
If you add the keyword `video_lockup$FEwatch_to_watch` to your custom filter, you can filter out regular videos that appear in your home feed.

**Comment by NilsLeo** [comment]
First of all, thank you so much for maintaining this Project 🙏. 

I've already removed the home button on the navbar and set my default start page to the library and added the filter as suggested, but still end up here sometimes
![Screenshot_20241120-225651](https://github.com/user-attachments/assets/bd4921b3-85be-4fac-8e0b-9e52557a400a)



I want to get rid of all feeds, to stay distraction free. This is the last piece of that puzzle, so if anyone knows how to get rid of this feed in particular, pls lmk 

My settings
```
"alt_thumbnail_home": "dearrow",
"change_start_page": "library",
"custom_filter": true,
"custom_filter_strings": "related_video\nchannel_action_button\nchannel_header_links\nexpandable_list_inner\nexpandable_product_grid\ngrid_channel_shelf\nhero_carousel\nlibrary_recent_shelf\noffer_box\nproduct_offers\nshorts_shelf\nstyled_product_carousel\nvideo_lockup$FEwatch_to_watch",
"hide_category_bar_in_feed": true,
"hide_category_bar_in_related_videos": true,
"hide_category_bar_in_search": true,
"hide_comments_section_in_home_feed": true,
"hide_community_posts_channel": true,
"hide_community_posts_subscriptions": true,
"hide_feed_survey": false,
"hide_low_views_video": false,
"hide_mix_playlists": true,
"hide_movie_shelf": true,
"hide_navigation_home_button": true,
"hide_navigation_notifications_button": true,
"hide_navigation_shorts_button": true,
"hide_navigation_subscriptions_button": true,
"hide_notify_me_button": true,
"hide_preview_comment": true,
"hide_recommended_video": true,
"hide_related_videos": true,
"hide_shorts_channel_bar": true,
"hide_shorts_comments_button": true,
"hide_shorts_dislike_button": true,
"hide_shorts_like_button": true,
"hide_shorts_share_button": true,
"hide_shorts_video_title": true,
"hide_subscriptions_carousel": true,
"hide_video_by_view_counts_home": true,
"sb_local_time_saved_milliseconds": 39127214,
"sb_local_time_saved_number_segments": 854
```
