### ISSUE TITLE
bug: YouTube - Fullscreen bugged when opened a video in RVX from Galaxy Store

### ISSUE THREAD

**Issue by VioletS24Ultra** [inotia00/ReVanced_Extended#2328]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 19.16.39

### Bug description

When a YouTube link is opened in RVX from Galaxy Store, it will bug fullscreen. Default YouTube app will not bug and shows fullscreen correctly 

Screenshot of RVX:

![Screenshot_20240816_230200_RVX](https://github.com/user-attachments/assets/0afccb87-6bf1-4765-9012-79cf91f80b16)

Bug:

Fullscreen bugs out, it shows part of the recommended video under the fullscreen video, that makes the fullscreen video tiny.

Link to Galaxy Store app that I used in this example:

https://apps.samsung.com/appquery/appDetail.as?appId=com.samsung.android.app.galaxyraw&cId=000007163045

Settings:

[RVX_v19.16.39_2024-08-16.txt](https://github.com/user-attachments/files/16641452/RVX_v19.16.39_2024-08-16.txt)

Patches:

Everything else except Translate and Debug Logging

### Solution

No idea.

### Device Environment

Android 14 OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unfortunately, there is no way to reproduce this issue on my side

Apps like Galaxy Store or Huawei AppGallery cannot be tested in environments including Android Emulator

So if you want the issue to be fixed, you must attach a crash log

**Comment by VioletS24Ultra** [comment]
> Unfortunately, there is no way to reproduce this issue on my side
> 
> Apps like Galaxy Store or Huawei AppGallery cannot be tested in environments including Android Emulator
> 
> So if you want the issue to be fixed, you must attach a crash log

Getting that log is impossible because I dont have a computer, and cant afford one.
