### ISSUE TITLE
Downloader doesn't show 2160p for MP4 (Is limited to 1080p)

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#233]
https://youtu.be/N_Maw56tLCI?t=245

I don't understand this video is 2160p, but MP4 is limited to 1080p? 

![Screenshot_20230207-214433864 (1)](https://user-images.githubusercontent.com/73917917/217362461-b0637b89-bd5f-4179-b72b-54274d57e101.jpg)

I have encountered this issue with quite alot videos. Videos are 4K but downloader shows only up to 1080p mp4 🤔 
This issue forces me to download WEBM instead which I want to avoid. Prefer MP4.

Is there a fix to it?

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
bruh wrong place to report issue
https://github.com/razar-dev/PowerTube/issues
