### ISSUE TITLE
question: how to hide "Featured channels" in Subscriptions tab?

### ISSUE THREAD

**Issue by spftware** [inotia00/ReVanced_Extended#2330]
### Application

YouTube

### Question description

Just want to hide the "Featured channels" list below subscriptions.

![Screenshot_20240817_160106_RVX](https://github.com/user-attachments/assets/a75022db-9299-4fb3-8e8d-9842b559c220)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
They cannot be hidden with custom filters
