### ISSUE TITLE
Shorts Player Enable Timestamps Flag on v19.16.39

### ISSUE THREAD

**Issue by goooglefc** [inotia00/ReVanced_Extended#2331]
### Application

YouTube

### Question description

The two experimental flags shown in the image only appear if I patch v 19.25.39. ( i know it's not supported).
Is there any way to make them appear on the supported version 19.16.39?
![Screenshot_20240818](https://github.com/user-attachments/assets/4d8d2d98-20f5-4c04-b0ba-c0edc6df48e5)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is a feature that Google added in YouTube 19.24.xx+
(i.e. it is not possible)
