### ISSUE TITLE
bug: (YouTube Music/Player components) : 'Preview Version Issue'

### ISSUE THREAD

**Issue by ImpenetrableNoble** [inotia00/ReVanced_Extended#2332]
### Type

Other

### Tools used

RVX Manager

### Application

RVX version of YouTube music: 7.13.52

### Bug description
I've been facing limited ad free music playback experience by YouTube music telling me that my “preview subscription service will end” on the RVX version.

Despite successfully listening to music without advertisements, the app consistently displays a “preview” label, suggesting that ad-free playback for all RVX and Revanced users is limited.

This discrepancy between the perceived and actual ad-free experience is causing confusion and frustration for me since it's telling me that the preview version of YouTube music will end soon.

To reproduce the issue:

1. Install the modified RVX version of YouTube music.

2. Observe the absence of Advertisements.

3. Note the persistent “preview” label displayed within the app.

Expected behavior:
The “preview” label should not appear when ad-free music was already patched.

Actual behavior:
The “preview” label persists despite ad-free playback on the RVX version.

![Screenshot_20240819_232624](https://github.com/user-attachments/assets/7d6d530f-f82b-4cea-a69b-06f3918d88d7)

![Screenshot_20240820_014603](https://github.com/user-attachments/assets/0754fe6e-a373-4bb7-9ff4-87c575e4b4e7)

### Error logs

```shell
N/A
```

### Solution

The Problem:
The core issue seems to be that the YouTube Music app is incorrectly identifying modified RVX versions as preview versions, leading to an inconsistent ad-free experience.

Proposed Solution:
 * Implement User-Agent Detection:
   * Analyze the user-agent string sent by the modified RVX version of the YouTube Music app.
   * Create a whitelist of specific user-agent strings associated with verified and authorized modified RVX versions.
   * Upon detecting a whitelisted user-agent, override the "preview" label and grant full ad-free feature privileges.
   * Set up an AI bot to regularly update the whitelist to accommodate new modified RVX versions while maintaining security.

Benefits of this Solution:
 * Accurate Ad-Free Experience: Users with RVX versions YouTube music will enjoy the expected ad-free experience without having their RVX version of YouTube music being labeled as a preview version.
 * Improved User Satisfaction: Eliminates confusion and frustration caused by the inconsistent "preview" label.
 * Scalability: Can be easily adapted to accommodate future changes in modified RVX versions.

By implementing user-agent detection and following the outlined considerations, RVX version of YouTube Music can effectively address the ad-free issue for RVX users while maintaining system integrity.

### Additional context

I don't understand why is this happening to me. 

### Device Environment

Samsung Galaxy a21
&
Studio Mini 2023

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
RVX only has a patch implemented to remove ads, it doesn't unlock YouTube Premium
(it relies on server side)

Bug reports are only valid if the currently implemented patch doesn't work as intended

There is currently no patch implemented to remove the banner in the screenshot you attached

You can open a new issue with the feature request label
