### ISSUE TITLE
bug(YouTube/Hide feed components) : Community posts aren't hiding

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2334]
### Type

Error at runtime

### Tools used

Revancify

### Application

YT v19.16.39

Latest patches & integrations

### Bug description

From 2-3 days, I'm noticing that community posts aren't hiding in related videos below the player. If this could be fixed, it will be great.

Thanks!

![Screenshot_2024-08-21-11-49-54-02_f22faf49515899f9781ec174a4d85388](https://github.com/user-attachments/assets/d7d15d43-66d9-41ce-b180-36419b2d2d67)

### Error logs

```shell
No logs.
```

### Solution

.

### Additional context

.

### Device Environment

Realme 7 Pro, Android 12.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Cast0r-999** [comment]
Please fix this in turbo mode. Very annoying bullshit.

**Comment by Aryan-Chauhan** [comment]
> Please fix this in turbo mode. Very annoying bullshit. 

What is turbo mode?

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
