### ISSUE TITLE
bug(YouTube/Spoof client): IP/Wlan throtteling

### ISSUE THREAD

**Issue by MarcoSupper** [inotia00/ReVanced_Extended#2338]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.16.39

### Bug description

Error still persists after downgrading to 19.16.39. Where is the debug log output located btw.

Since about 2 weeks RVX keeps buffering since it's not preloading fast enough. Most of the time it's at the start of playing a video. I have to keep closing/reopening the video to be able to play it. Then in the first quarter of the video it sometimes loads so slow that it just keeps buffering than going for like 2 seconds than buffering again. It seems this problem doesn't happen when I use mobile data. And no my internet works perfectly well. I can use it for anything else besides RVX. I have all my spoof clients set to IOS.
Haven't been able to test it with a different wlan yet.
There seems to have been a similar bug recently but that was said to have been patched ~2-3 months ago.

### Device Environment

Android 13.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
