### ISSUE TITLE
question (YT - Check GmsCore): Is this only used to remove the battery optimization popup?

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2339]
### Application

YouTube

### Question description

The `GmsCore support` patch has a `Check GmsCore` patch option. The description does not mention anything about battery optimizations or the battery optimization popup, but I don't understand the purpose of the patch option except to remove the battery optimization popup warning that appears when GmsCore has battery optimizations enabled.

What is the purpose of not checking if GmsCore is installed, and should the patch option description be changed to inform users that it removes the battery optimization popup warning?

![SmartSelect_20240825_004212_RVX Manager](https://github.com/user-attachments/assets/62bb92ea-1a1f-4600-b113-f252181ae0ad)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
> ### Application
> YouTube
> 
> ### Question description
> The `GmsCore support` patch has a `Check GmsCore` patch option. The description does not mention anything about battery optimizations or the battery optimization popup, but I don't understand the purpose of the patch option except to remove the battery optimization popup warning that appears when GmsCore has battery optimizations enabled.
> 
> What is the purpose of not checking if GmsCore is installed, and should the patch option description be changed to inform users that it removes the battery optimization popup warning?
> 
> ![SmartSelect_20240825_004212_RVX Manager](https://private-user-images.githubusercontent.com/84587632/361294267-62bb92ea-1a1f-4600-b113-f252181ae0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDM4ODIsIm5iZiI6MTcyNDcwMzU4MiwicGF0aCI6Ii84NDU4NzYzMi8zNjEyOTQyNjctNjJiYjkyZWEtMWExZi00NjAwLWIxMTMtZjI1MjE4MWFlMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDIwMTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0Nzc2ZjcxOWFkZGEwZDQzZDcxNzIxYTg1Mjg3OGZmMDc1YzdiNTRiZGI3ZjFiMzVhZDdiMWQyZTYxMDI5ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.46Clf8v9K4QS5ymEgckXJmhqaxx6R2FsDK2eJlQRcsI)
> 
> ### Acknowledgements
> * [x]  This issue is not a duplicate of an existing question.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.
> * [x]  I have written the title and contents in English.

Things which will happen after disabling this toggle:
1. Youtube app will crash , if there's gms core installed on your device.
2. It will not redirect to gms core download link.
3. You won't get that annoying popup anymore which ask us to disable battery optimisations .

**Comment by inotia00** [comment]
Closes the issue as sufficient answers exist
