### ISSUE TITLE
feat(patch): remove `Continue Watching` banner

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#234]
### Application

YouTube

### Issue

There is a "Continue Watching" feature for Premium subscribers. This feature plays the last video at every restart of YT.

### Patch

Need a patch to remove it completely as some users don't want this feature. There is no perfect option in Original YT to disable this.

### Motivation

Please add this feature as some users don't want this feature. 
![Screenshot_20230208-133613](https://user-images.githubusercontent.com/93650504/217471467-9d7f8ccd-2fcf-4e44-aa1e-c655241976e3.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, I do not support unlocking premium features
That's because there's a DMCA takedown risk.
(The official ReVanced repo also experienced a DMCA takedown due to the premium unlock feature)

**Comment by Vipin2003** [comment]
I'm not saying to unlock premium feature.Thia is already unlocked feature in premium....I'm requesting for removing this feature as there is no way to remove or disable it.

**Comment by Vipin2003** [comment]
And thanks for refactoring "Disable Shorts PIP" as in latest patch, it again start working. Last time, it was not working.

**Comment by inotia00** [comment]
Ah, it seems I misunderstood

Please attach the url of that video

**Comment by Vipin2003** [comment]
It is not work specific video. It happens with every video. The last video we play before closing the YT, that video played with every restart of YT.

Currently not able to upload that video... Will upload soon

**Comment by Vipin2003** [comment]
https://user-images.githubusercontent.com/93650504/217807325-2c691e51-c208-482b-a104-bdee97b9acec.mp4

**Comment by Vipin2003** [comment]
I found the reason for it....it only appears when we have connected our account to TV stick and the YT is running on stick.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
