### ISSUE TITLE
suggestion: 

### ISSUE THREAD

**Issue by Aleksandrt6** [inotia00/ReVanced_Extended#2340]
### Application

YouTube

### Suggestion description

![Screenshot_20240817_114727_IntentResolver](https://github.com/user-attachments/assets/0ff870aa-3666-442c-9c53-7e8472bd6ef8)
 Video pause ,the machine do this .

Coppa ftc signal. 

Remove graphics inappropriate language 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
Totally understandable 😳🤯

**Comment by Aryan-Chauhan** [comment]
LMAO
