### ISSUE TITLE
bug: Hook download action doesn't show `Download Playlist` in the flyout menu

### ISSUE THREAD

**Issue by Francesco146** [inotia00/ReVanced_Extended#2342]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.38

### Bug description

(https://github.com/inotia00/revanced-patches/pull/70#issuecomment-2273104609) as the title says, the hook download actions patch works only for the few countries that have that buttons. we currently made the button visible to all in the playlist page, but in the flyout is still missing

### Solution

I'm planning to work on this in my free time. I don't have much of it, and I work at a much slower pace than inotia, so I'll leave the name of the class where the object is rendered.

class name: `aist`
method name: `b`

I'll leave also a stacktrace of this method.

```
DownloadActionsPatch test
dalvik.system.VMStack.getThreadStackTrace(Native Method)
java.lang.Thread.getStackTrace(Thread.java:1841)
app.revanced.integrations.youtube.patches.general.DownloadActionsPatch.test(DownloadActionsPatch.java:77)
aist.b(PG:49)
aist.setContentView(PG:2)
tv.a(PG:318)
bnf.b(PG:28)
bnf.d(PG:41)
bni.j(PG:15)
ca.pn(PG:90)
bq.pn(PG:1)
opx.e(PG:244)
opx.g(PG:1027)
cx.aB(PG:131)
cx.aD(PG:92)
cx.J(PG:29)
bc.d(PG:7)
bq.u(PG:15)
ahpz.af(PG:235)
ahpz.ae(PG:46)
ahpz.ad(PG:36)
mnk.onClick(PG:879)
android.view.View.performClick(View.java:7506)
android.view.View.performClickInternal(View.java:7483)
android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
android.view.View$PerformClick.run(View.java:29334)
android.os.Handler.handleCallback(Handler.java:942)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loopOnce(Looper.java:201)
android.os.Looper.loop(Looper.java:288)
android.app.ActivityThread.main(ActivityThread.java:7872)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
iirc, whether the flyout menu `Download playlist` is exposed or not is not a region-specific restriction, but depends on your YouTube Premium subscription status

Just as the flyout menu `Play next in queue` is only available to YouTube Premium subscribers, the flyout menu `Download Playlist` is also server-side dependent

**Comment by vippium** [comment]
Ya..I can download whole playlist with that button. And for your confirmation, it is not a premium feature. You can mark it as a region specific feature.
And for premium, I don't have that much money to give it to Google.

**Comment by Francesco146** [comment]
right, I'll still work on this feature, if i can make it work, then I'll open a PR. I'll let inotia decide whether to leave this issue open or not

**Comment by inotia00** [comment]
Even if it doesn't depend on YouTube Premium, I don't know of a way to force the flyout menu to be enabled
(it's possible to hide the video action button and the flyout menu, but there's no known way to force it to be enabled)

This issue has been closed as it is a bug report related to a setting that is flagged as experimental flags

**Comment by Francesco146** [comment]
ah, understood. I'll take a deeper look, maybe there's some flag to be inverted, like for the button in the Playlist page. idk
