### ISSUE TITLE
bug: 1080p video playback x1.5 and more lagging

### ISSUE THREAD

**Issue by Vladitslav** [inotia00/ReVanced_Extended#2345]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Revanced Extended Anddea v19.25.39

### Bug description

When I watch videos on 1080p with speed multiplier x1.5 and higher it gets all laggy, like a frameskip. It's unwatchble. It works fine on 720p quality and lower. I tried using both experimental skip buffer at the start of videos and codec change, but it doesn't help

### Device Environment

Android 14, realme UI 5.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.25.39 is not a supported version
