### ISSUE TITLE
bug(YouTube/Disable force auto captions): patch doesn't work with Shorts

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2346]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches latest dev release

### Bug description

Explained in the title.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please attach an example of a shorts video with forced auto captions applied

**Comment by federicogith** [comment]
> Please attach an example of a shorts video with forced auto captions applied

The bug seems to arise only with Shorts in the subscriptions feed AND with certain system languages, I only tried Italian

Please watch the video until the end:

https://github.com/user-attachments/assets/5efeb84b-7275-4c4c-9a84-4ff821f07884

**Comment by inotia00** [comment]
There is an issue when applying patches in Shorts: https://github.com/inotia00/ReVanced_Extended/issues/484

To prevent this, Shorts has been changed to not apply patches

Since this old bug cannot be fixed, the following description will be added to the settings:
```
Limitation: This setting does not apply to Shorts
```

**Comment by inotia00** [comment]
nvm I refactored the patch so it now works properly in Shorts too

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
