### ISSUE TITLE
suggestion: 17.33.42 Change of function contents  

### ISSUE THREAD

**Issue by AsphaltKoreaWiki** [inotia00/ReVanced_Extended#2347]
### Application

YouTube

### Suggestion description

17.33.42 is almost similar to 17.41.37 except for the current video rounded thumbnail  corners deactivation. Change the content to "Disable video thumbnail rounded corners"

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Not only the thumbnail corner style, but also the comment box and action button style are different
17.33.42 also does not support ambient mode
(unless the old data remains)

The current description is more accurate
