### ISSUE TITLE
feat: bring titles together with `thumbnail` filter on

### ISSUE THREAD

**Issue by selirof** [inotia00/ReVanced_Extended#2348]
### Application

youtube

### Feature description

I think it would be great if it was possible to make the feed look like this:
 
![Screenshot_20240829-133431](https://github.com/user-attachments/assets/43d70aea-a529-4964-9d60-c2b68c5b463d)

now this is only possible in the  "related videos" feed but in the homepage/subscription feed it looks like this with empy spaces between titles:

![Screenshot_20240829-133715](https://github.com/user-attachments/assets/8aa68e13-9b19-4083-84f8-dcafec1cb59b)

### Motivation

it would make the filter "thumbnail" worth using by conferring a more minimalistic look to the app

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue has been closed because it is a feature request
