### ISSUE TITLE
A sharing bug

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#235]
### Type

Error while patching

### Application

Newest

### Bug description

when I share something it doesn't preview anymore 

### Steps to reproduce

Share something (i have used whatsapp) 

### Relevant log output

```shell
No
```

### Additional context

I dont know if is my phone xiaomi or a bug of the application. 
Give me a answer thanks

### Device Environment

Android 12 miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Not an issue with ReVanced
(If you check stock YouTube, it will be the same)

**Comment by speedlorenzo12** [comment]
In youtube the sharing works

**Comment by inotia00** [comment]
If so, please refer to the documentations and patch it again from the beginning
https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android)

**Comment by speedlorenzo12** [comment]
In YouTube the sharing works, and i dont never do that and i dont have the desire to do this.
