### ISSUE TITLE
bug: Sponsor Block patch is broken in v4.13.1-dev.1

### ISSUE THREAD

**Issue by DarkSanctuary** [inotia00/ReVanced_Extended#2350]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39
Patches v4.13.1-dev.1

### Bug description

Sponsor Block is not blocking anything after v4.13.1-dev.1 patch

### Solution

Downgrade to previous stable v4.12.3 patch

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's not a problem on the ReVanced side, it's a problem on the SponsorBlock server side

https://www.reddit.com/r/SponsorBlock/s/NHgRvZQYN7

**Comment by KobeW50** [comment]
Just adding: You can see the SponsorBlock server status here: https://status.sponsor.ajay.app/
