### ISSUE TITLE
question (YT Music): Why is the `Open GmsCore` setting part of the `Enable debug logging` patch?

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2351]
### Application

YouTube Music

### Question description

In YT Music (with patches v4.13.1-dev.1), if you only include the `GmsCore support` (and the `Settings for YouTube Music`) patch, the only setting within the Miscellaneous menu is the Import/Export settings option. The option to open GmsCore is not there.

Only if you include the `Enable debug logging` patch does the `Open GmsCore` option appear. Why is this the case?

(For YouTube, the `Open GmsCore` option is added with the `GmsCore support` patch)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
