### ISSUE TITLE
bug(YouTube Music/Return YouTube Dislike): likes and dislikes are switched in RTL layout

### ISSUE THREAD

**Issue by blacktornadog7** [inotia00/ReVanced_Extended#2353]
### Type

Cosmetic

### Tools used

CLI

### Application

YouTube Music 7.13.52

### Bug description

likes and dislikes are switched in right to left layout while its normal in left to right layout

| Left to Right Layout    | Right to Left Layout |
| ---------------------------------- | ----------------------------------- |
| ![Screenshot_20240830_061528_RVX Music](https://github.com/user-attachments/assets/40684d19-cb3c-432f-8d1f-cb3d77eb4167) | ![Screenshot_20240830_061254_RVX Music](https://github.com/user-attachments/assets/39112398-ecfb-4f27-96fc-fd5a51c98ae0) |

### Steps to reproduce

1. close the app if open
2. change YouTube Music's display language to a right to left one
3. close miniplayer if open
4. pull down to refresh
5. open a song

### Device Environment

Android 13 (One UI 5.1)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
