### ISSUE TITLE
bug (YT Music) : There is no splash screen in RVX YT Music.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2354]
### Type

Cosmetic

### Tools used

Revancify

### Application

YT Music v7.16.52

Patches v4.13.1-dev.1

App settings are stock/out-of-the-box.

### Bug description

No splash screen is showing when opening the app. 

You click on the app to start it, an empty screen comes before you, then the homepage of RVX YT Music app comes up.

https://github.com/user-attachments/assets/d77110ec-2e00-4500-8a7d-afd24e2c0fcd

### Error logs

```shell
No logs.
```

### Solution

Appropriate splash screen should be shown like before.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro

Android 12 (skin name: Realme UI 3.0)

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unpatched YouTube Music also has the same issue

**Comment by Aryan-Chauhan** [comment]
> Unpatched YouTube Music also has the same issue

My unpatched YT Music (v7.16.52) has splash screen.

https://github.com/user-attachments/assets/5a8fd872-19ed-432f-9f89-93d37518a0ce

**Comment by inotia00** [comment]
On my side, the splash animation is gone even on unpatched YouTube Music

It seems Google is doing A/B tests to widely roll out Cairo splash animations

You can avoid these A/B tests by patching YouTube versions prior to 7.08.xx
