### ISSUE TITLE
question: can I have screenshots of "Trends" button and "Use template" button?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2358]
### Application

YouTube

### Question description

I would like to see what exactly "Hide Trends" button and "Hide Use template" button hide

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Use Template` button is no longer visible in my Google account
(A/B tests maybe?)

So I reproduced the screenshot as I remembered:

![Use_templates](https://github.com/user-attachments/assets/707b25bf-e863-4fc9-868b-c5e56af21a82)

As for the `Trends` button, you can see it if you pause Shorts:

![Trends](https://github.com/user-attachments/assets/24225492-3c81-4920-8d94-582b51665c30)
