### ISSUE TITLE
suggestion: Update Overlay Buttons's default margins

### ISSUE THREAD

**Issue by ghost** [inotia00/ReVanced_Extended#2359]
### Application

YouTube

### Suggestion description

This would ensure that people who are using overlay buttons are not accidentally hitting the seekbar. I did thorough testing with various different dip settings and 5.0dip hits the sweet spot. It doesnt make the overlay buttons to go too high so that it will cover the video, or too low that will make users to hit the seekbar.

When users have seekbar hidden and dip set to 0.0, it makes users to hit the seekbar instead of overlay buttons.

![Screenshot_20240902_191217_Termux](https://github.com/user-attachments/assets/dc57e995-4621-4f38-a3c1-700dfeeb4cc7)

With 5 0dip:

![Screenshot_20240902_191326_RVX](https://github.com/user-attachments/assets/50fe8349-489b-4496-a4d9-88f254531dee)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
On my device, it seems like there is too much margin when bottom margin is set to 5.0dip
(Yeah this setting varies depending on the device the user is using and the settings the user has changed)

So instead of changing the default bottom margin to 5.0dip, I'll add the following options:
```
Default (2.5dip)
None (0.0dip)
Wider (5.0dip)
```

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
