### ISSUE TITLE
bug: `Hide Gray Seperator` Hides `From Your Watch Later Playlist`

### ISSUE THREAD

**Issue by kazimmt** [inotia00/ReVanced_Extended#236]
### Type

Error at runtime

### Application

YouTube v18.04.41 & v18.05.34

### Bug description

When I disable ` HideGray Seperator` from Settings, it shows `From your watch later playlist` under video thumbnail.

When I enable ` HideGray Seperator` from Settings, it doen't shows `From your watch later playlist` under video thumbnail.

### Steps to reproduce

- Open YouTube ReVanced Extended
- Turn off `Hide Gray Seperator` from ad settings
- Add some videos to Watch Later Playlist

It'll Show `From your watch later playlist` under video

- Open YouTube ReVanced Extended
- Turn on `Hide Gray Seperator` from ad settings
- Add some videos to Watch Later Playlist

It'll not Show `From your watch later playlist` under video

### Relevant log output

```shell
­
```

### Screenshots or videos

`Hide Gray Seperator` Disable
![Screenshot_2023-02-08-19-33-29-126_com miui gallery](https://user-images.githubusercontent.com/82371061/217546205-f26bf5b5-a24a-4d07-86ac-37ff7ca47fac.jpg)

`Hide Gray Seperator` Enable
![Screenshot_2023-02-08-19-33-44-375_com miui gallery](https://user-images.githubusercontent.com/82371061/217546407-13369d7c-3fc8-466f-970f-ba976d091831.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.160.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.160.1)

**Comment by kazimmt** [comment]
@inotia00 Thank You
but, I don't see any commit regarding this!
