### ISSUE TITLE
bug(YouTube Music/SponsorBlock): SponsorBlock segments at the end of a song cause the player to get stuck

### ISSUE THREAD

**Issue by Lassie111** [inotia00/ReVanced_Extended#2360]
### Type

Error at runtime

### Tools used

CLI

### Application

Youtube Music 7.13.52

### Bug description

Steps to reproduce:
1. Find a song with a SponsorBlock segment at the end of the video
2. Let that segment be automatically skipped
3. Observe the player get stuck at the end of the song, failing to play the next song automatically

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please provide a url that can reproduce this issue

**Comment by Lassie111** [comment]
https://music.youtube.com/watch?v=yYchF3OLkm4

It stays like this after skipping the segment:
![Screenshot_20240902_233043_RVX Music](https://github.com/user-attachments/assets/3f2fc494-9882-4dcd-9d2b-d0e8afc40737)

**Comment by lpcurcio** [comment]
The same thing is happening with my device. In both versions (root and non-root).

**Comment by Lassie111** [comment]
Seems fixed in the `dev` branch.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
