### ISSUE TITLE
question: How do I filter components after I capture the debug logs?

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2362]
### Application

YouTube

### Question description

I am able to capture debug logs in YouTube and YT Music, but I struggle with interpreting them and using them to create custom filters.

For example, someone asked me if they can hide video Premieres, such as [this one](https://youtu.be/n0aMaAjrd24). (I know that you can add "Premieres" to the keyword filter, but for the sake of this example I want to see how to do it through the custom filter). 

I started capturing debug logs and searched for the video title.

This is what I captured: 
[search_of_premiere.txt](https://github.com/user-attachments/files/16842322/search_of_premiere.txt)

I then filtered it for "Premieres", since this seems to be a BufferString associated with the Premier: 
[filtered_for_premieres.txt](https://github.com/user-attachments/files/16842331/filtered_for_premieres.txt)

I thought I would be able to filter `video_lockup_with_attachment$Premieres` or `video_lockup$Premieres` or `thumbnail$Premieres` but none of these have the desired effect.

![Screenshot_20240902_212841_Logcat Reader](https://github.com/user-attachments/assets/4fc5805f-8aad-4280-9768-fbd0856ea45c)

![SmartSelect_20240902_211408_YT Extended](https://github.com/user-attachments/assets/191a5281-b6c0-4504-ae92-04c20fc18097)

What am I doing wrong, and how would you approach such a task?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As far as I know, some strings contained in byte buffers need special decoding to be filtered

Customfilter can also filter some strings contained in byte buffers, but it cannot filter all strings contained in byte buffers
(This is why keyword filters were released)
