### ISSUE TITLE
bug(YouTube/Hide feed components) : Community posts aren't hiding in subscription feed.

### ISSUE THREAD

**Issue by Soler3737** [inotia00/ReVanced_Extended#2364]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 19.16.39

### Bug description

From 2-3 days, I'm noticing that community posts aren't hiding in subscription feed even though the option to hide them is selected. 

Thanks!

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The title is different, but it is the same issue as https://github.com/inotia00/ReVanced_Extended/issues/2334 (treated as a duplicate issue)
