### ISSUE TITLE
suggestion: Remove Revancify Shortcut information from the revancify.md

### ISSUE THREAD

**Issue by PolishBastard** [inotia00/ReVanced_Extended#2367]
### Application

Other

### Suggestion description

That command doesnt work anymore, or I dont know how to correctly use it. After running that command in Termux nothing happens.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Revancify Shortcut still works on my device

Did you follow this [guide](https://github.com/inotia00/revancifyshortcut?tab=readme-ov-file#how-to-use
)?

What is your device and OS?

**Comment by PolishBastard** [comment]
> Revancify Shortcut still works on my device
> 
> Did you follow this [guide](https://github.com/inotia00/revancifyshortcut?tab=readme-ov-file#how-to-use)?
> 
> What is your device and OS?

I followed the guide yes, after I ran that command in termux nothing happened.

My termux version is 0.119.0-beta 1 and my phone OS is android 14 with one ui 6.1.
