### ISSUE TITLE
suggestion (YT): Translated name of patches in `Patches information`

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#2369]
### Application

YouTube

### Suggestion description

Since in the tab mentioned in the topic, the categories of patches are translated, as well as the signature ‘included/excluded’, why not also enrich this by translating the names of patches (as well as ReVanced Patches and Integrations)? For people not necessarily good at English, this would be quite an improvement. Additionally, this would make everything translated in this category. It depends if it is important to you inotia that necessarily the patch names are only-English, or if it is not a problem to implement this.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
The screen is for debugging purposes.
See https://github.com/inotia00/ReVanced_Extended/issues/218#issuecomment-1418232811
