### ISSUE TITLE
bug(YouTube - Comments): `Hide channel guidelines` is not working when the video is just uploaded

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2371]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

I'm assuming this, but I came across an LTT video which was just uploaded (for me it was showing uploaded 22 seconds ago) and when I tapped the comments, I was shown the channel guidelines. 
![Screenshot_20240907_214231_YouTube](https://github.com/user-attachments/assets/55a619ae-81e6-4d7f-af2f-12e0c1084aa5)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/329
