### ISSUE TITLE
bug(YouTube/Settings): `Swap Create and Notifications button` description cuts off

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2373]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

Patch description of `Swap Create and Notifications button` gets cut off before finishing in the patch description in app settings.
![Screenshot_20240908-220116_YouTube](https://github.com/user-attachments/assets/32371627-e1d0-4fa6-8b00-3ba9c1f29739)

### Error logs

```shell
N/A
```

### Solution

Scrollable descriptions or a "show more" option within the bigger descriptions to hide long descriptions. 

### Additional context

N/A

### Device Environment

Android 14, Rising OS 5.0
Xiaomi 11T Pro 
2107113SG (vili)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
