### ISSUE TITLE
bug: (YouTube/Spoof streaming data) iOS spoof livestream starts at the start of the stream not instead of live

### ISSUE THREAD

**Issue by WsNyc00** [inotia00/ReVanced_Extended#2374]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39
RVX patches: v4.13.1

### Bug description

When client is spoofed to iOS livestream launched at the start of livestream (like a regular video) instead it should be at the "LIVE"
Clicking on the "LIVE" where the video timer is goes to live, but starting another livestream start stream from the start.

### Error logs

N/A

### Solution

Solution would be spoof to Android VR, or press "LIVE" where the video timer is everytime you watch another livestream.

### Device Environment

Android 8.1.0
Android 14

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [x] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Closes the issue as it is flagged as a known issue in Spoof streaming data
