### ISSUE TITLE
bug(YouTube/Hide feed components): `Hide expandable chip under videos` setting does not work

### ISSUE THREAD

**Issue by 30b0** [inotia00/ReVanced_Extended#2376]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

In the Feed the Merchandise Shelves as well as the Expandable Chips still show up, even when the Settings to hide them are enabled.
![Screenshot_20240908-215834_YouTube](https://github.com/user-attachments/assets/97c22423-8d85-4e9b-91fc-7656a8c9a970)
![Screenshot_20240908-221346_YouTube](https://github.com/user-attachments/assets/30b03821-0e02-4af4-a3e8-68ef71ac2a97)
![Screenshot_20240909-014834_YouTube](https://github.com/user-attachments/assets/d9f3c19b-2ac5-4ce6-9f01-1f5f10689946)
![Screenshot_20240909-014914_YouTube](https://github.com/user-attachments/assets/ede72036-b1aa-4c5b-9580-4d03681b0a3a)

This Problem appeared with the latest Patches v.4.13.1.
A/B-Testing should not be the Problem here, since the same is present with another unused Account.

The same Problem with an unsupported YT-Version was closed: https://github.com/inotia00/ReVanced_Extended/issues/2173

### Device Environment

OnePlus 9 Pro, crDroid 10.7, Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
