### ISSUE TITLE
bug: Delete download didn't work

### ISSUE THREAD

**Issue by xondamirahmadov** [inotia00/ReVanced_Extended#238]
### Type

Other

### Application

Extended 18.04.35

### Bug description

Delete download didn't work. Delete video in history didn't work properly, results seeing only after update page

### Steps to reproduce

Aaa

### Relevant log output

```shell
Aaa
```

### Screenshots or videos

#

https://user-images.githubusercontent.com/94036691/217582506-4d73918e-c80b-4db8-935e-40cf69d6eb0d.mp4

### Device Environment

Miui 13.0.5 stable

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Gungrave223** [comment]
This was marked as closed but the issue is still happened on the latest patch.
