### ISSUE TITLE
suggestion: rollback supported version to YouTube Music 7.16.52

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2382]
### Application

YouTube Music

### Suggestion description

Google is conducting [A/B testing](https://en.wikipedia.org/wiki/A/B_testing) the new action bar for YouTube Music with some users. https://github.com/inotia00/ReVanced_Extended/issues/1969

The new action bar looks exactly the same as the old action bar, and there is no functional difference, but switching to the new action bar means losing support for the following patches:
- `Hide action bar components`
- `Return YouTube Dislike`

The LithoViews implemented in YouTube Music do not have a granular ComponentTree, unlike YouTube.

This means that the buttons in the new action bar in YouTube Music cannot be modded anymore.

This A/B test only applies to YouTube Music 7.17.51+.

If you are using YouTube Music 7.17.51+, the patches will work for users who haven't gotten the new action bar, but not for users who have gotten the new action bar.

If you're on YouTube Music 7.16.52, the patches will work for all users.

For this reason, the supported YouTube Music version will be rolled back to 7.16.52 in the next release.

Users can still patch to the latest YouTube Music version, including YouTube Music 7.18.xx+, but support, including bug reports, will not be provided in this case.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by NBruderman** [comment]
I see no issues with this. Unlike reverting the regular YouTube version, that causes some issues with android 15 (only if you install it as a system app), no such issue occur if you revert youtube music to the version suggested. So I'm up for it.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)

**Comment by PureBloodOldBigGuy** [comment]
> ![Screenshot_20241114-163811.png](https://private-user-images.githubusercontent.com/26320625/386260546-b4af1a32-54fb-4a52-a703-81e8e3f8ed7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTk2ODgsIm5iZiI6MTczMTU5OTM4OCwicGF0aCI6Ii8yNjMyMDYyNS8zODYyNjA1NDYtYjRhZjFhMzItNTRmYi00YTUyLWE3MDMtODFlOGUzZjhlZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE1NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MjdmNjVhODJjMWVhODNiZDQyYjI3YjFmM2I0YTdhZDRiNjQyNDhkNGRjOGEzMTJiNTU5NmJkYTJjMjBjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xeyJgQP57ngofCdy8IMejtWNlY6lo8GhDhhtVIKCDJI)
> 
> There may not be a choice, but to update soon.

Did you try what I mentioned?

**Comment by cromefire** [comment]
> Did you try what I mentioned? 

The only version still works for me, so I didn't upgrade yet. Was just informing that rolling back the recommended version might not work much longer. I try not to upgrade if I don't have to.

**Comment by fuengfah** [comment]
I haven't ipgrade to new version yet but with today new release I might try it out.

**Comment by Karthik-Subbu** [comment]
@inotia00  I'm seeing a flash notice to update yt music. Can the app version info be spoofed to a higher version to bypass update nag when  older versions like 7.16 are used to preserve integrity of patches like hide action buttons and RYD?

**Comment by fuengfah** [comment]
> @inotia00  I'm seeing a flash notice to update yt music. Can the app version info be spoofed to a higher version to bypass update nag when  older versions like 7.16 are used to preserve integrity of patches like hide action buttons and RYD?

Are you using root module  zip? or apk?
You can either use zygisk detach or uncheck auto update in the playstore.

**Comment by Karthik-Subbu** [comment]
> > @inotia00  I'm seeing a flash notice to update yt music. Can the app version info be spoofed to a higher version to bypass update nag when  older versions like 7.16 are used to preserve integrity of patches like hide action buttons and RYD?
> 
> Are you using root module  zip? or apk?
> You can either use zygisk detach or uncheck auto update in the playstore.

I am a non root user. I was referring to in-app update notice whenever yt music is launched.

**Comment by ILoveOpenSourceApplications** [comment]
A side note, `Hide ads` fails on YT Music v7.29.51. I'm a user who doesn't use both the patches holding back the suggested version.

**Comment by roy1205** [comment]
Alguien me puede ayudar mi YT miusic se detiene al minuto de reproducir y me pide actualización
