### ISSUE TITLE
bug: Audio track menu doesn’t work properly ( can't change audio track )

### ISSUE THREAD

**Issue by Bakchxd** [inotia00/ReVanced_Extended#2385]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube Extended_v19.16.39
patches_v4.13.1
Uploading InShot_20240913_195312809.mp4…

### Bug description

audio track not showing 

### Device Environment

Android 11,realme ui

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![side_effect](https://github.com/user-attachments/assets/117ed81f-1a91-46bb-8e75-d45d8ecd1d50)

This is a known side effect of Spoof streaming data
