### ISSUE TITLE
bug(YouTube/Hide feed components): Duration filter only hides thumbnail for videos shorter than allowed length

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2389]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39
Patches v4.13.1

### Bug description

When a duration filter is set to hide videos from the feed that are shorter than a specified duration, videos shorter than the duration will only have their thumbnails hidden.

In the screenshot of the home feed below, I have it set that all videos shorter than 25 minutes should be hidden.

![Screenshot_20240915_014602_YT Extended](https://github.com/user-attachments/assets/9193dc5d-7713-49df-8a9c-57730b42c649)

### Additional context

On the bright side, this behavior can be utilized by users who want to hide video thumbnails (although it doesn't work in related videos ofc)

### Device Environment

Android 14
OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As Google has recently made a lot of changes to the server-side components, the filter is now pretty broken

Before the server-side changes, we could get information about the duration of the video anywhere in the layout, which corresponds to the red rectangle (thumbnail + video info panel)

After the server-side changes, we can only get information about the duration of the video from the blue rectangle, the thumbnail

That is, after the server-side changes, we can no longer get information about the duration of the video from the video info panel

I don't think it's possible to fix this

Until a better way is found, the `Duration filter` will be removed from the settings

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
