### ISSUE TITLE
feat(patch):  startup on library tab screen first as replacing home and remove other tabs like subscriptions 

### ISSUE THREAD

**Issue by Zedroid** [inotia00/ReVanced_Extended#239]
### Application

YouTube

### Issue

get rid of non-library feeds and buttons

### Patch

could you remove home screen or subscription feed in the bottom bar
i want to see the library first

removing those other videos would be nice as well like an adblock

### Motivation

I do not want other recommended videos to distract me and I need to get off my youtube addiction 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/14
