### ISSUE TITLE
question: can I have a screen shot of expandable shelf?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2390]
### Application

YouTube

### Question description

"Hide expandable shelves" setting has been added
Can I see an example of expandable shelf?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This layout was added so recently that I don't have any screenshots
(it only appeared to me once)

I'll add screenshots later if I get them
