### ISSUE TITLE
suggestion(YouTube/Visual preferences icons): add patch options that do not apply to sub-settings

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2392]
### Application

YouTube

### Suggestion description

![parent_preferencescreen](https://github.com/user-attachments/assets/054593e7-04aa-4d45-b63f-73473a761cf6)

For the sake of simplicity, I will define `First screen that appears when you enter YouTube settings or RVX settings` as `Parent PreferenceScreen` (The screen without switches)

The `Visual preferences icons` patch applies to the `Parent PreferenceScreen` of YouTube settings, the `Parent PreferenceScreen` of RVX settings, and all RVX sub-settings

The problems with the `Visual preference icons` patch are as follows:

1. `Visual preference Icons` patch is not easy to maintain

RVX sub-settings are added or removed quite frequently

When new settings are added or removed in RVX, icon support is not provided quickly

Honestly, the `Visual preference icons` patch has not changed at all since the PR https://github.com/inotia00/revanced-patches/pull/55

2. `Visual preference icons` patch does not change the icons of all RVX sub-settings

As mentioned in https://github.com/inotia00/ReVanced_Extended/issues/2129, the `Visual preference icons` patch still does not change the icons for many RVX sub-settings

![rvx_sub](https://github.com/user-attachments/assets/98a10930-863b-4084-aabc-4ece68e74be1)

There are settings with icons, settings with empty icons, and settings without icons

Because of the inconsistency, the `Visual preference icons` patch was excluded by default

![cairo](https://github.com/user-attachments/assets/c2779055-fc3c-4e81-b479-e007c7985788)

This is a screenshot of the `Cairo setting` that Google is preparing

The `Cairo icon` is only applied to the `Parent PreferenceScreen` of YouTube settings

Similar to the `Cairo setting` that Google suggested, it seems better for the `Visual preference icons` patch to only change the icons of the `Parent PreferenceScreen` of RVX settings

Considering this, the patch option `ApplyToAll` will be added in the next release

The default value of the patch option `ApplyToAll` is FALSE

```
If TRUE - icons are applied to the parent PreferenceScreen of YouTube settings, the parent PreferenceScreen of RVX settings and the RVX sub-settings

If FALSE - icons are applied to the parent PreferenceScreen of YouTube settings and the parent PreferenceScreen of RVX settings
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
> Because of the inconsistency, the Visual preference icons patch was excluded by default

Now it will be included by default?

**Comment by inotia00** [comment]
Patch: included by default
Patch option (ApplyToAll): FALSE by default

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
