### ISSUE TITLE
suggestion: Update Disable VP9 codec description

### ISSUE THREAD

**Issue by ghost** [inotia00/ReVanced_Extended#2393]
### Application

YouTube

### Suggestion description

My suggestion:

• Maximum resolution is 1080p.
• Video playback will use more data when VP9 codec is disabled.
• To get HDR video playback, enable VP9 codec or use AV1 codec.
• When VP9 codec is disabled, AV1 codec might be used instead.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
> • Video playback will use more data when VP9 codec is disabled.

This description only shows when VP9 is already disabled. Similar bullet point lists found in RVX settings explain the effects of the current configuration. So `...when VP9 codec is disabled.` would be inconsistent phrasing.

Here is my suggestion:
`• Video playback will use more data than with the VP9 codec.`

> • To get HDR video playback, enable VP9 codec or use AV1 codec.

The current description implies that it will automatically use the VP9 codec when playing HDR video. @inotia00 is it automatic or needs to be done manually?

**Comment by inotia00** [comment]
> Here is my suggestion:
`• Video playback will use more data than with the VP9 codec.`

This suggestion is more clear

> The current description implies that it will automatically use the VP9 codec when playing HDR video. @inotia00 is it automatic or needs to be done manually?

Only VP9 and AV1 codecs support HDR video

`Disable VP9 codec` setting does not work with HDR video
(VP9 codec is disabled for other videos, but not for HDR video)

The current description:

```
• Maximum resolution is 1080p.
• Video playback will use more internet data than VP9.
• To get HDR playback, HDR video still uses the VP9 codec.
```

If the description needs to be clearer, a sentence like `VP9 codec is not disabled for HDR video` would be more appropriate

**Comment by KobeW50** [comment]
Maybe, `For HDR video the VP9 codec is still used.`

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
