### ISSUE TITLE
feat(YouTube/Change start page): change the actual start page instead of redirecting the Url

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2395]
### Application

YouTube

### Feature description

**This is not a patch request, but a description of the feature that will be introduce in the next release.**

The `Change start page` patch implemented in YouTube does not change the actual start page

It opens the start page Url as soon as the home feed is opened

Therefore, the following issues have been raised:

1. The user sets the start page to `Library` and opens YouTube
2. The Library tab is opened (root tab is the home feed)
3. When the back button is clicked on the Library tab, the home feed appears instead of exiting the app

The `Change start page` patch implemented in YouTube Music overrides the [browseId](https://ytmusicapi.readthedocs.io/en/latest/faq.html#what-is-a-browseid)

Since the patch changes the root tab, clicking the back button exits the app instead of returning to the home feed

Just like in YouTube Music, we need to override the browseId in YouTube as well

### Motivation

1. This suggestion is more consistent with the patch description
2. If this suggestion is applied, the patch will no longer depend on `Shell_HomeActivity`, so it can be used regardless of YouTube version

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by 1node0001** [comment]
Hmm, my start page is set to Search, if I use previous key it goes to homepage instead of exiting the app.

**Comment by 1node0001** [comment]
> For some special pages like Search, Liked video, Watch later, due to limitations of YouTube API, parent browseId cannot be overridden (Forcing override causes bug)
> 
> For these special pages, fall back to the default home feed to avoid bugs

Can you add a small disclaimer under the Start Page setting stating this?

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
