### ISSUE TITLE
bug(YouTube Music/SponsorBlock): SponsorBlock does not skip segment at the beginning when in background

### ISSUE THREAD

**Issue by Lassie111** [inotia00/ReVanced_Extended#2396]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube Music 7.16.52

### Bug description

Steps to reproduce:
1. Find a song that has SponsorBlock segment at the beginning (e.g. https://music.youtube.com/watch?v=ExF2jwBXAiw).
2. Go to the next song.
3. Minimize YouTube Music to the background.
5. From the Media panel, go to the previous song.
6. The segment at the beginning is not skipped.

Note that step 3 is important. If YouTube Music is still on the foreground, it works fine even if the Media panel is used.

https://github.com/user-attachments/assets/a35dacb4-73d8-42ce-a322-296fa1a98c1c

In the video, the segment is skipped immediately on returning YouTube Music to foreground.

### Device Environment

Android 14, One UI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
