### ISSUE TITLE
bug(YouTube/Shorts components): `Hide save sound to playlist button` setting does not work

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2397]
### Application

YouTube

### Suggestion description

This patch will hide the `Save music` button in the Shorts component.
![Screenshot_20240920_122228](https://github.com/user-attachments/assets/6e6a8df1-000e-4a83-b531-f122a20a9926)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is already implemented with the following setting:
`Hide save sound to playlist button`

So it is a bug that it is not hidden

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
