### ISSUE TITLE
question: How to convert to .jar?

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2399]
### Application

Other

### Question description

So i have downloaded pathces source and did some modifications to change default settings for YTM but i don't have any idea how i can convert it into .jar file

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
U can build patches via Android Studio or command line

**Comment by AykhanUV** [comment]
i figured it out thanks
