### ISSUE TITLE
question: Chromecast not showing. 

### ISSUE THREAD

**Issue by DMD786** [inotia00/ReVanced_Extended#240]
### Application

YouTube

### Issue

When choosing to cast. Chromecast not showing.

### Patch

Chomecast support

### Motivation

Would be nice if able to cast to Chromecast 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I think the explanation is a bit lacking.

1. Are you asking that the cast button is not visible?
2. Or does it mean that you can see the cast button, but cannot cast to the TV?

**Comment by DMD786** [comment]
The cast button is visible. Cannot cast to the TV via Chromecast.

**Comment by inotia00** [comment]
It's normal that it doesn't work on non-root builds.
Because MicroG doesn't support Chrome cast v2

If it doesn't work on root builds, this is a bug

**Comment by Vipin2003** [comment]
But it is working in my case with non-root build.

**Comment by inotia00** [comment]
> But it is working in my case with non-root build.

Most likely, your TV is not using Chrome cast v2 or using some other API so there is no issue

**Comment by DMD786** [comment]
Stock YouTube app finds and works with Chromecast but Revanced does not.

**Comment by DMD786** [comment]
Had this problem with Vanced YouTube. Downgraded to YouTube Vanced v16.14.34 that worked.

**Comment by inotia00** [comment]
This is a MicroG issue, not a ReVanced issue
