### ISSUE TITLE
bug: `Hide YouTube Music button` doesn't work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2400]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.13.2-dev.1

### Bug description

https://github.com/user-attachments/assets/744dd66d-d46a-4dc6-82e8-570c426fbb09

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
This settings hide Music button in Player Overlay, not Search Result
