### ISSUE TITLE
bug(YouTube/Hide feed components): `Hide recommended videos` setting does not work in home feed

### ISSUE THREAD

**Issue by 30b0** [inotia00/ReVanced_Extended#2402]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39 | Patches v1.14.1-dev.1

### Bug description

Videos that are saved in the "Watch Later"-Playlist randomly apper without Informations in the Home-Feed.
![Screenshot_20240923-235355_YouTube](https://github.com/user-attachments/assets/1d315820-a3ee-4792-b549-8ddf33921d23)
![Screenshot_20240923-235717_YouTube](https://github.com/user-attachments/assets/b92b9520-ef0a-4a0f-9de4-003ac772927d)

### Device Environment

Android 14, OnePlus 9 Pro, CrDroid 10.8

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an issue that is not reproducible on my side

Exclude patches one by one until the issue can no longer be reproduced

Report back which patch is causing the issue

**Comment by inotia00** [comment]
nvm issue is reproducible on my side

**Comment by 30b0** [comment]
Found the Setting that causes that Problem, it's "Hide recommended Videos".
When this Settings is active it causes the Problem seen above.

If it's not active it looks like this in the Feed:
![Screenshot_20240924-004025_YouTube](https://github.com/user-attachments/assets/8323277e-4bb1-41ca-8a45-18ec3ef1326e)

And when active it looks like above:
![Screenshot_20240924-004111_YouTube](https://github.com/user-attachments/assets/303988ae-cdf8-4be1-9d32-915089b131e9)
![Screenshot_20240924-004133_YouTube](https://github.com/user-attachments/assets/a2e2c5fc-9e58-44ba-a4c2-8435da02e941)

**Comment by inotia00** [comment]
yeah Google changed the path of the litho component in the home feed on the server side

We can no longer hide recommended videos that appear in the home feed without bugs

Instead of completely removing the `Hide recommended videos` setting, I will change it to only apply to search results and related videos

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
