### ISSUE TITLE
bug(YouTube): Keyboard keeps opening when going back

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2403]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.14.1-dev2

### Bug description

https://github.com/user-attachments/assets/c8c30a00-c010-460c-ac7b-9009023fd54e

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is not a bug, this is intended behavior
