### ISSUE TITLE
bug: AV1 decoding and streams are available but VP9 used

### ISSUE THREAD

**Issue by alcatraz-zz** [inotia00/ReVanced_Extended#2405]
### Type

Other

### Tools used

RVX Manager

### Application

 19.16.39 latest stable patches no 13.

### Bug description

AV1 is available but not used by RvX on 4.13 patches. (and previous patches)

Check screenshots comparing RvX with SmartTube. Please read below the pictures. There's an odd exception.
![20240926_092348](https://github.com/user-attachments/assets/ae5c7ac7-8f16-4bb0-8612-c66aeddee294)
![20240926_092408](https://github.com/user-attachments/assets/6bd26022-81e9-4608-977d-0bbf741f2ebf)

On RARE occasions I do get AV1 with RvX like here:
![20240926_092727](https://github.com/user-attachments/assets/461ca445-3536-4adf-b4e2-dd52f7262766)

Is it possible that the AndroidTV spoofing has AV1 disabled? Then my question is, why do two different videos use different spoofing? 

Thanks for the help. Love your work. 😍🙏

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You are using `Spoof streaming data`

The supported formats for the video vary from client to client, and this depends on the response from the YouTube API

For this reason, you cannot force-enable a codec on a specific client, and this is not a bug

(It is possible to force-disable a codec that exists in the response from the YouTube API, but it is not possible to force-enable a codec that does not exist in the response from the YouTube API)

To get the response from the `Android` client, simply turn off the `Spoof streaming data` setting
