### ISSUE TITLE
suggestion(YouTube/Shorts Component): always hide suggested actions when all settings in the suggested action category are enabled

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2407]
### Application

YouTube

### Suggestion description

New button added `Green Screen`, as like `Use Music`
![Screenshot_20240927_231331](https://github.com/user-attachments/assets/5eb70659-d329-472c-8a83-347d6e7564d7)
Shorts link : https://youtube.com/shorts/TKNR610yAZg

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The suggested action buttons in Shorts seem to be too many, including the ones that haven't been revealed yet

If I were to manually add all the suggested action buttons, there would be too many settings

If all the settings in all the suggested action categories are enabled, it would be better to always hide the suggested action

**Comment by inotia00** [comment]
Opening a new issue to show a short video would send unnecessary notifications to other collaborators, so I'll leave it here as a comment

If someone asks something like 'What is the `Disable Like button animation` setting?', just show them this comment

`Disable Like button animation` (Fountain animation):

https://github.com/user-attachments/assets/d8a61b68-6696-4583-81e4-ae442fbce5bb

As you can see in the attached video, it disables the animation above the Like button in Shorts

Google seems to call this `Fountain animation`

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
