### ISSUE TITLE
bug: YouTube Music doesn't follow playlists

### ISSUE THREAD

**Issue by nightznero** [inotia00/ReVanced_Extended#2409]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YTM v7.17.51 RVX v4.13.1

### Bug description

Yesterday noticed after playing my playlist that after few songs YTM changes music from playlist into random(from Recommendation i guess) songs. Yesterday it was after 15songs +-,today after 4 and after change to follow playlist when song end again YTM changed songs.

### Device Environment

A13 OneUi 5.1

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's a bug in unpatched YouTube Music
