### ISSUE TITLE
feat: Change widgets

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2410]
### Application

YouTube Music

### Feature description

There are widgets for both ytm and yt and when i use them app name would be default YouTube. Is there a way to change them to match with custom name?

### Motivation

-

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I don't understand what type of widget you are talking about
Please upload the screenshot

**Comment by AykhanUV** [comment]
![Screenshot_2024-09-28-20-25-46-609_com mi android globallauncher](https://github.com/user-attachments/assets/6e89311c-89c2-4bec-891e-286741592ba1)
This type of home screen widget as you see there is YouTube instead of name i have used

**Comment by inotia00** [comment]
I think this is only for YouTube, not YouTube Music

Because YouTube Music doesn't have a label like `Search YouTube`

Sorry, I don't take feature requests that are specific to YouTube

**Comment by AykhanUV** [comment]
There is at least "Now playing"  widget that you can change for ytm

**Comment by YT-Advanced** [comment]
https://github.com/ReVanced/revanced-patches/pull/3707
