### ISSUE TITLE
suggestion: YouTube/Custom Branding Icon) Widen the empty space in between the search bar and the YouTube (Minimal) icon

### ISSUE THREAD

**Issue by 1node0001** [inotia00/ReVanced_Extended#2412]
### Application

YouTube

### Suggestion description

I wrote about this here but didnt get any response:

https://github.com/inotia00/revanced-patches/pull/83#issuecomment-2379314553

There should be similar empty space in between the search bar and the icon, otherwise it will look ugly.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by MondayNitro** [comment]
instead i will make the space equal to the space bw search bar and screen end
![Screenshot_30-9-2024_112148_github com](https://github.com/user-attachments/assets/7b808754-c80c-479d-b81e-441ccb21fb80)
unnecessarily adding too much space will ruin it

**Comment by 1node0001** [comment]
https://github.com/inotia00/revanced-patches/pull/83#issuecomment-2382527932
