### ISSUE TITLE
RVX Manager  "Unable to use selected application"

### ISSUE THREAD

**Issue by nightznero** [inotia00/ReVanced_Extended#2413]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

RVX Manager v1.22.2

### Bug description

Any app that try to add on Managers shows up that error,even with choosen suggested version of app.
Its first time that i met this,any advice what can cause that issue?
![Screenshot_20240930_044358_RVX Manager](https://github.com/user-attachments/assets/4ea55ca8-06de-41d5-a665-4a31d2886251)

Best Regards, NIGHTZNERO.

### Device Environment

A13 OneUI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
I can't replicate this. From where did you get the APK that you are selecting?

**Comment by nightznero** [comment]
> From where did you get the APK that you are selecting?

[Apkmirror.com](ApkMirror)
It's normal `.apk` file,nor any abb,apkx or so. But not only from there,apps from Mobilism and 4PDA forums also doesnt work,apps from GitHub works normally

**Comment by inotia00** [comment]
RVX Manager is provided simply for my patch compatibility

There are no plans to fix bugs in RVX Manager

This is also mentioned in the RVX Manager release notes:

```
▶ RVX Manager is provided simply for compatibility with my patch, if you run into issues follow the other patch method.
```

Please use a different patching method than RVX Manager
