### ISSUE TITLE
question: experimental flag doesn't work

### ISSUE THREAD

**Issue by AliBASE** [inotia00/ReVanced_Extended#2418]
### Application

YouTube

### Question description

I'm trying to use the --experimental flag on windows cli to patch incompatible version of youtube, but the cli doesn't recognize the experimental flag at all.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Option `--experimental` is deprecated since ReVanced CLI 4.0

This option has been replaced by `-f` or `--force` since ReVanced CLI 4.0

**Comment by AliBASE** [comment]
Cli version = 4.6.0
Unknown option: '--force'
Usage: revanced-cli [-hV] [COMMAND]
Command line application to use ReVanced.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  patch          Patch an APK file.
  options        Generate options file from patches.
  list-patches   List patches from supplied patch bundles.
  list-versions  List the most common compatible versions of apps that are
                   compatible with the patches in the supplied patch bundles.
  utility        Commands for utility purposes.

**Comment by inotia00** [comment]
please type full command

**Comment by AliBASE** [comment]
java -jar cli.jar --force patch youtube_19.36.44.apk -b patches.jar -m integrations.apk -o "Revanced.apk" -i "GmsCore support"

**Comment by inotia00** [comment]
The `--force` option must be declared after the patch

Likes:

```
java -jar cli.jar patch youtube_19.36.44.apk -b patches.jar -m integrations.apk -o "Revanced.apk" --force -i "GmsCore support"
```

**Comment by AliBASE** [comment]
Thank you legend, I'll try that later & let you know if it works.

**Comment by AliBASE** [comment]
Problem solved, thx!
