### ISSUE TITLE
feat(patch): Sort the ReVanced Extended Settings 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#242]
### Application

YouTube

### Description

Can we sort the settings in alphabetical order so that it'll be easier to find an option rather than having to go through each patch options individually.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Chirronupu** [comment]
I think a setting search option would be preferable

**Comment by ILoveOpenSourceApplications** [comment]
> I think a setting search option would be preferable

I don't know which one would be easier to be implemented. Depending on the number of patches one includes I would say both would be nice.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
