### ISSUE TITLE
bug: deletion of downloaded videos

### ISSUE THREAD

**Issue by VEAJ** [inotia00/ReVanced_Extended#2424]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Revanced extended 4.10.1

### Bug description

I downloaded some videos to watch offline using YouTube built in download system on the app, but when i proceed to delete it, it just doesn't delete it and keeps it there without doing anything, even after restarting the device its still there and works as downloaded

### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You are using an outdated patch

The latest patch is revanced-patches-4.14.1, and the recommended version is YouTube 19.16.39

just update (re-patch)
