### ISSUE TITLE
question: is there a custom filter?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2425]
### Application

YouTube

### Question description

Is there any any custom filter to hide that button?
![ _20241007_035931](https://github.com/user-attachments/assets/ef0b0e0a-f012-4721-9a7c-f62701ec9e82)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Not sure but:

```
CellType|ContainerType|ContainerType|button.eml$YouTube Music
```

- Only hides the `YouTube Music` button
- Might not work on Tablet or Tablet layout
