### ISSUE TITLE
bug: this app runs like shit 

### ISSUE THREAD

**Issue by No-Clever-Username** [inotia00/ReVanced_Extended#2428]
### Type

Other

### Tools used

rvx-builder

### Application

v19.16.39

### Bug description

I don't think I've ever used a app as buggy as this. crashing, lagging, refusing to load videos. I have a (presumably) decent phone as well. (A13 5G) Fix your shitty ass code. This is unacceptable.

### Error logs

```shell
fix
```

### Solution

your

### Additional context

shitty

### Device Environment

code

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Dont use if u dont want

**Comment by inotia00** [comment]
Please re-open an issue by attaching the logcat and filling in the appropriate format to show which patch is causing the crash
