### ISSUE TITLE
question: why does custom filter not works?

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#2429]
### Application

YouTube

### Question description

In your latest patch, custom filter 'library_recent_shelf' does not work at tablet. However in phone, it works well. Any reason why this happens?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It is not a unique value for the component id

Since YouTube is a kind of web app, the component id can change at any time due to server-side changes

As of now, the following are valid custom filter keywords to hide the library shelf:

```
horizontal_$FElibrary
```
