### ISSUE TITLE
bug: autoplay not working

### ISSUE THREAD

**Issue by turbozik** [inotia00/ReVanced_Extended#243]
### Type

Error at runtime

### Application

YouTube 18.5.35

### Bug description

when you turn on the constant auto-rotation, the video at the end is repeated instead of switching to the next one

### Steps to reproduce

go to the "button display" and enable the "constant auto-rotation" function

### Relevant log output

```shell
I do not know where to get it
```

### Device Environment

Android 11 realm yo 2.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
can't reproduce
Check if enable always auto repeat is off
