### ISSUE TITLE
question: Spoof Streaming data patch auto including although I don't include in patch

### ISSUE THREAD

**Issue by dib12** [inotia00/ReVanced_Extended#2430]
### Application

YouTube

### Question description

I included only this three patch. And I don't want to add Spoof Streaming data.but its auto patching.Is there any reason?
 "Remove background playback restrictions" 
 "GmsCore support"
"Hide ads" 

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The cause of the playback issue is GmsCore

That's why when you include `GmsCore support` patch, you also include the `Spoof streaming data` patch
(The two patches are dependent)

This is the intended behavior
