### ISSUE TITLE
RVX Managerl not showing latest patch/not matching with latest GitHub release 

### ISSUE THREAD

**Issue by mysticmac3** [inotia00/ReVanced_Extended#2433]
### Application

YouTube

### Question description

Hi first of all thanks for your hard work, I am not sure if it's a  bug on githhub/manager or a mistake in version numbering. there was a release of patches by you around 17h ago but RVX manager is not showing latest release, please see the screenshot below
![20241013_162000](https://github.com/user-attachments/assets/38665f99-8632-48a2-8d0e-40d33d263ddc)

Screenshot of github below 

![20241013_161308](https://github.com/user-attachments/assets/ae951706-9d13-44cf-a7c4-90c653bb8231)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It seems that only the version shown on the RVX Manager home feed is wrong
If you actually apply the patch, v4.14.2 will be applied

This will be resolved when v4.15.1 is released

**Comment by mysticmac3** [comment]
Thanks for your response,my manager is set with pre release toggled on, should i just go ahead and patch?

**Comment by inotia00** [comment]
You can do that if you want

I always use the dev branch btw

**Comment by mysticmac3** [comment]
I use dev branch always as well but its not letting me patch because of this bug, also as you mentioned it will patch 4.14.2 if i just go ahead and patch i am assuming it will patch the stable version 4.14.2 if i go ahead and patch

**Comment by mysticmac3** [comment]
Edit:- now it is showing me the latest dev branch you just posted 17 minutes ago, thanks the problem is solved now,i will go ahead and patch with the latest dev branch
