### ISSUE TITLE
bug: "Unavailable Videos Are Hidden" shows up despite no videos being removed.

### ISSUE THREAD

**Issue by 03bgood** [inotia00/ReVanced_Extended#2434]
### Type

Glitch

### Tools used

N/A

### Application

ReVanced, ReVanced Extended

### Bug description

When going a playlist I created (always the same one); it says "Unavailable Videos are Hidden". It happens more on RV than RVX. This is a bug as all videos are available and none of them seem to have been removed. The initial solution is to "clear cache" and "force stop" RV/RVX, under "Settings > Apps". However, the issue returns about 5-10 minutes later.

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please add more details including YouTube version, revanced-patches version, and screenshot where the issue occurs

**Comment by 03bgood** [comment]
V19.05.36

**Comment by inotia00** [comment]
What is the version of revanced-patches?

**Comment by 03bgood** [comment]
I'm not sure but it happens only on one playlist. It's called "80s Music". It shows all 88 videos, eventhough it says "Unavailable Videos are Hidden". It's a weird bug that's been happening since last Friday. It happens way more on RV than RVX.

**Comment by inotia00** [comment]
Please re-patch with the latest patch and report back if the issue is reproduced

**Comment by 03bgood** [comment]
> Please re-patch with the latest patch and report back if the issue is reproduced

That's not the issue. This didn't happen until a few days ago.

**Comment by inotia00** [comment]
This issue does not reproduce on YouTube 19.05.36

I am using the latest patch (revanced-patches-4.14.2)

Re-patch according to the [documentation](https://github.com/ReVanced-Extended-Community/Community-Guides/blob/main/community-wiki/guide-for-beginners.md)

**Comment by 03bgood** [comment]
Its still happening, please fix!

**Comment by inotia00** [comment]
Issues that suddenly appear at some point are usually server-side issues

If you are using an unpatched YouTube 17.33.42 or 19.05.36, it will be the same

If this is a bug caused by a patch, you should exclude the patches one by one and report back which patch caused the issue

(You still do not provide enough information)

Please reopen the issue after including enough information and specifying exactly which patch caused the issue

**Comment by 03bgood** [comment]
> Issues that suddenly appear at some point are usually server-side issues
> 
> If you are using an unpatched YouTube 17.33.42 or 19.05.36, it will be the same
> 
> If this is a bug caused by a patch, you should exclude the patches one by one and report back which patch caused the issue
> 
> (You still do not provide enough information)
> 
> Please reopen the issue after including enough information and specifying exactly which patch caused the issue

Again, it's not a patch issue. This has been happening since last Friday and it's only affecting one playlist.

**Comment by inotia00** [comment]
> Again, it's not a patch issue.

If it's not a patch issue, why are you contacting this repository?

This repository only handles bug reports due to patches

Please report issues with the YouTube app to Google

**Comment by 03bgood** [comment]
I'm not sure where to put this, but it is a ReVanced issue.
