### ISSUE TITLE
bug: youtube history doesn't work 

### ISSUE THREAD

**Issue by auron98x23** [inotia00/ReVanced_Extended#2436]
### Type

Other

### Tools used

CLI

### Application

19.25.39

### Bug description

The history of YouTube watched videos doesn't update anymore.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.25.39 is not a supported version
