### ISSUE TITLE
bug(YouTube/Hide ads): `Hide view products banner` setting not working

### ISSUE THREAD

**Issue by smed79** [inotia00/ReVanced_Extended#2437]
### Type

- Other (ads)

### Tools used

- RVX Manager v1.22.2
- RVX Patchs v4.14.2

### Application

- YouTube v19.16.39

### Bug description

**View products** banner that overly the video player is not hidden.

![hvpd](https://github.com/user-attachments/assets/79b8ac31-b7ce-461c-9267-cb63d6516cc0)

![bnr](https://github.com/user-attachments/assets/547aee1c-9703-4299-a9a6-a906ebebb4ec)

### Additional context

Example video when you can reproduce 

- `https://youtu.be/tsdpdtmigXM`
- `https://youtu.be/sM_lWr6iRds`

### Device Environment

- Android 14.0 (_OxygenOS_)

### RVX Logs

```
- Device Info
RVX Manager: 1.22.2
Model: CPH2581
Android version: 14 (OxygenOS)
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: rvx.android.youtube v19.16.39 (Suggested: Any)
Patches version: v4.14.2
Patches added: Custom header for YouTube, Force hide player buttons background, Hide Shorts dimming, Hide shortcuts, MaterialYou
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: true
Use pre-release: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 61 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Ripping selected native libs
Aligning APK
Signing APK
Patched APK
Installing patched app
Installed
```
### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
please add the version of revanced-patches you used

**Comment by smed79** [comment]
More details add above ☝️

I get more big annoying banner on the below 👇 video 

- `https://youtu.be/pijEZbZemUM`

**Screenshots**

![001](https://github.com/user-attachments/assets/0a8d8a34-3d7b-44e2-ae5b-637985cb2eb8)

![002](https://github.com/user-attachments/assets/5b4bb038-db36-481b-aa0f-2800d185bc16)

Thank you in advance 🙏

**Comment by smed79** [comment]
Applying the last patches v4.15.1-dev.3 unfortunately did not fixed the issue.

- [revanced-manager_logcat.log](https://github.com/user-attachments/files/17444537/revanced-manager_logcat.log)
- [rv_patches_mgr.log](https://github.com/user-attachments/files/17444540/rv_patches_mgr.log)

What i can provide to help you investigate?

---
PS: I also noticed that "[Up next](https://github.com/user-attachments/assets/2e5d016e-2552-4910-aa8a-bfaa54d031ed)" suggested video banner is not hidden with "[Hide end screen card and suggested video](https://github.com/user-attachments/assets/88f10ce2-a0f2-4a33-afd5-4af318912948)" switched on (autoplay is off). 

Should i open new issue for this bug or just follow tracking it here?

**Comment by inotia00** [comment]
> PS: I also noticed that "[Up next](https://github.com/user-attachments/assets/2e5d016e-2552-4910-aa8a-bfaa54d031ed)" suggested video banner is not hidden with "[Hide end screen card and suggested video](https://github.com/user-attachments/assets/88f10ce2-a0f2-4a33-afd5-4af318912948)" switched on (autoplay is off).

This is `autoplay preview container`, not `end screen card and suggested video`

▼ autoplay preview container ▼

![hide-autoplay-preview](https://github.com/inotia00/ReVanced_Extended/assets/108592928/d8a9b9f7-4628-4ad3-ad9e-9a84f7c44c4d)

**Comment by inotia00** [comment]
> What i can provide to help you investigate?

If it's not hidden even in the latest dev branch, then this is a new ad that is not being reproduced on my side.

You can extract the debug log by following the steps below:

1. Install ADB on your PC according to the [docs](https://www.xda-developers.com/install-adb-windows-macos-linux/).
2. Turn on `Enable debug logging` and `Enable dubug buffer logging` in RVX settings.
3. Enable USB debugging in Developer options in System settings.
4. Connect your phone and PC, and open CMD in the directory where `adb.exe` is.
5. Type the following in CMD:

```
adb logcat | findstr "LithoFilterPatch" > log.txt
```

6. Open a video with the View products banner.
7. Type `Ctrl + C` in CMD.
8. Attach the `log.txt`.

**Comment by smed79** [comment]
> You can extract the debug log by following the steps below

I'm on Linux, so I used `grep` instead of `findstr` but unfortunately i get an empty file.

![logcat](https://github.com/user-attachments/assets/0b5c17de-962c-4e0c-ab92-7371d8422669)


Filtering the logcat by the package name
```
adb logcat | grep rvx.android.youtube > log.txt
```

give me the output > [64f628f5af0dd2e64339d34d0d99d580](https://gist.github.com/smed79/64f628f5af0dd2e64339d34d0d99d580)

---

> This is `autoplay preview container`, not `end screen card and suggested video`

Thank you very much :pray:

**Comment by inotia00** [comment]
No debug logging included

Are these turned on?

> 2\. Turn on `Enable debug logging` and `Enable dubug buffer logging` in RVX settings.

Command in Linux:

```
adb logcat | grep --line-buffered "LithoFilterPatch" > log.txt
```

**Comment by smed79** [comment]
Of course yes, `Enable debug logging` and `Enable dubug buffer logging` in RVX settings are turned on and also `USB debugging` in `Developer Options` but i still get an empty `log.txt` file with the command you have provided for linux.

I also tried via `Wireless debugging` using [Shizuku](https://github.com/RikkaApps/Shizuku) + [aShell You](https://github.com/DP-Hridayan/aShellYou) > Same thing, i get an empty file.

I don't know, maybe something goes wrong with my rom/device.
I will try to find another device for testing and see if i can reproduce the ads, then providing a log.

Thank you so much for your assistance.

**Comment by inotia00** [comment]
You can also extract logs via the `Locat Reader` app

Try this:

1. Download and install the `Locat Reader` app:

[F-Droid (summary)](https://f-droid.org/packages/com.dp.logcatapp/)
[F-Droid (direct download)](https://f-droid.org/repo/com.dp.logcatapp_33.apk)

2. Enable USB debugging and grant permission by entering the following command from the CMD on your PC:

```
adb shell "pm grant com.dp.logcatapp android.permission.READ_LOGS && am force-stop com.dp.logcatapp"
```

3. Launch the Locat Reader app

4. Move to `3dot menu - Filters`

5. Click the `+` button and type it like a screenshot:

![LogCatReader](https://github.com/user-attachments/assets/bc6cdd12-e2b2-4a6b-9480-8895f4e05c63)

and then, click `OK`

6. In RVX, turn on the following settings:
```
Settings - ReVanced Extended - Miscellaneous - Enable debug logging / Enable dubug buffer logging
```

7. Force close and launch the RVX again

8. Open a video with the view products banner

9. After about 10 seconds, back to the `Locat Reader` app and click `3dot menu - Save`

![3Dots](https://github.com/user-attachments/assets/27d50448-caa3-4367-852d-3565baacf850)

10. Attach the log.txt

**Comment by smed79** [comment]
Hope this help > [logcat_10-20-2024_08-28-01.txt.zip](https://github.com/user-attachments/files/17449424/logcat_10-20-2024_08-28-01.txt.zip)

... & Thanks for the useful tutorial :+1:

**Comment by inotia00** [comment]
> Hope this help > [logcat_10-20-2024_08-28-01.txt.zip](https://github.com/user-attachments/files/17449424/logcat_10-20-2024_08-28-01.txt.zip)
> 
> ... & Thanks for the useful tutorial 👍

The debug log contains the keyword `shopping_overlay.eml-js-b`, which is missing from both ReVanced and RVX

Can you please add the keyword `shopping_overlay` to `Settings - ReVanced Extended - General - Custom filter - Custom filter` and report back if it gets hidden?

**Comment by smed79** [comment]
I confirm... The added filter: `shopping_overlay`, successfully hide the **_shopping products banner_** :tada:

**Comment by smed79** [comment]
The patches `v4.15.1-dev.4` successfully `Hide products banner`.

Closing...

**Comment by smed79** [comment]
@inotia00 FYI, I figured out that what was causing to get the empty log file is that `Logger buffer sizes` was turned `off` by mistake.
