### ISSUE TITLE
bug: (YouTube/Hide Action Button) "Save" button is not appeared 

### ISSUE THREAD

**Issue by A-of-Wonder** [inotia00/ReVanced_Extended#2439]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube: 19.16.39
Patches: 4.15.1-dev2
RVX Manager: 1.22.2

### Bug description

![Screenshot_20241017-210034](https://github.com/user-attachments/assets/2fd58011-92d9-4391-98a2-769430ec838b)
![Screenshot_20241017-210208](https://github.com/user-attachments/assets/0273f60e-2c64-4ab4-b20c-9b49f7add1f4)

Whether the toggle is on or off, it is not appeared.
Other items work fine.

### Device Environment

Android 12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [ ] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue is a known side effect of the `Hide related videos` setting

The `Hide related videos` setting is an `Experimental Flags` so I do not accept bug reports related to it

(Just turn off `Hide related videos` setting)
