### ISSUE TITLE
feat(patch): hide shorts component in pip mode

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#244]
### Application

YouTube

### Issue

When you go in pip mode whit a short the buttons in the video remains, I wish that when you look at a short you don't see the buttons that are in pip mode

### Patch

Patch named remove short buttons in pip mode and the description is removes the button of the short in pip mode

### Motivation

I would like the short to be seen better and then those buttons in that mode are useless and do nothing

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by speedlorenzo12** [comment]
This is a example 
![Screenshot_2023-02-10-11-05-27-013-edit_com.miui.home.jpg](https://user-images.githubusercontent.com/111771663/218063685-69577793-25f1-4865-9808-ce76c3e223a2.jpg)

**Comment by inotia00** [comment]
PIP mode for shorts videos will be forcibly disabled in the next release (just like the official ReVanced)
So this patch request is not needed
