### ISSUE TITLE
feat(YouTube Music/Navigation bar components): do not use hardcoded color values ​​when `Enable black navigation bar` setting is turned off

### ISSUE THREAD

**Issue by innuendofloyd** [inotia00/ReVanced_Extended#2440]
### Application

YouTube Music

### Feature description

Hello, my eyes really hurt when I read white fonts on a amoled/black background, so I usually theme color.xml. The recent Navbar patch overwrite my (kinda) theme. Even if I disable black Navbar it stays greysh.
I kindly request to allow the choice of Navbar color, in options file maybe?
![NEW](https://github.com/user-attachments/assets/394c2d76-20cc-4181-a9a9-6d115e884f14)
![OLD](https://github.com/user-attachments/assets/dd792f4c-7a0f-402b-bdd5-c18ab6b31e70)

Thank you.

### Motivation

I know it could be "ad personam" request, I just like the UI to be neat with the color I chose.
My eyes are thankful with #FF5b513f , so I don't see white fonts in the sky for an half hour after I used the app.
Thank you anyway

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
please add the color name of the colors.xml you modified

(e.g. "yt_black0", "yt_black1", ...)

**Comment by innuendofloyd** [comment]
Since I'm a butcher and not a developer I basically changed every black or dark color in colors.xml 
[colors.zip](https://github.com/user-attachments/files/17435537/colors.zip)

**Comment by inotia00** [comment]
In this case, it would be difficult to implement with a uniform patch

**Comment by innuendofloyd** [comment]
I don't demand a total theme for the entire app. Maybe could it be possible to separate the black navbar code from the navbar patch? 
My point is I need it just to hide "sample" and "upgrade to premium" 
Moreover, could I exclude navbar patch totally, and hide "sample" and "premium" in another way?

**Comment by inotia00** [comment]
It's hard to separate only the `Enable black navigation bar` patch from the `Navigation bar components` patch

Instead, I can make it use the color defined in colors.xml (@color/ytm_color_grey_12) instead of the hardcoded color when the `Enable black navigation bar` setting is off

**Comment by innuendofloyd** [comment]
Yes!! Thank you!!
