### ISSUE TITLE
suggestion (YT) : Little change in `Replace Timestamp Action` for user convenience & cosmetic reasons.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2441]
### Application

YouTube

### Suggestion description

When user taps on the timestamp, below flyout panel opens. I'm suggesting that this flyout panel doesn't look good.
![j](https://github.com/user-attachments/assets/73901c3a-b6a0-4a5e-9dfd-eccaef186d0b)

Instead of the above flyout panel, the below flyout panel should open when user taps on the timestamp.
![h](https://github.com/user-attachments/assets/3f5a645b-ceea-4d13-a88c-a10e53f81165)

Reason: While in full-screen mode, the current flyout panel isn't centred and covers the full screen. The suggested flyout panel is centered and doesn't cover the full screen. Also, because of it's rounded corners, it looks better.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Loading a litho component requires a command inherited from the parent litho view, and timestamp is not a litho view

So this is structurally impossible, regardless of my will

**Comment by Aryan-Chauhan** [comment]
> Loading a litho component requires a command inherited from the parent litho view, and timestamp is not a litho view
> 
> So this is structurally impossible, regardless of my will

Oh, I did not know that.

**Comment by Aryan-Chauhan** [comment]
Out of curiosity, one question came to my mind. I hope you will answer it.

Is the flyout panel shown in below screenshot "made by you" or it already exists in the YouTube APK and you inserted a hook in the timestamp to invoke it when touched?

![378086166-73901c3a-b6a0-4a5e-9dfd-eccaef186d0b.jpg](https://github.com/user-attachments/assets/4d4f6b86-f2ec-416a-8283-54ce6463d0fb)
