### ISSUE TITLE
bug(YouTube): Quality dips automatically and quality menu gets greyed out

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2442]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

While running on the latest dev release, YouTube starts playing without an issue, but in between will buffer and the quality will dip and the quality menu gets greyed out, locking the user to watch in low quality instead.

https://github.com/user-attachments/assets/a8563b47-b0bd-4ce0-bcae-6e5ee0576e8a

The issue isn't present in the last stable patches version. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
I forgot to mention but, using v4.15.1-dev.2 also didn't have this issue. So changes made in v4.15.1-dev.3 is causing something. 
P.S: I don't use spoof streaming data.

**Comment by inotia00** [comment]
This may be related to https://github.com/inotia00/ReVanced_Extended/issues/2419#issuecomment-2424322396

1. Exclude the `Spoof app version` patch and patch again
2. Reinstall RVX (The app version when you first installed it is saved in YouTube settings, so you need to reinstall)
3. Report back if the issue is reproduced

**Comment by ILoveOpenSourceApplications** [comment]
> This may be related to [#2419 (comment)](https://github.com/inotia00/ReVanced_Extended/issues/2419#issuecomment-2424322396)
> 
> 1. Exclude the `Spoof app version` patch (and re-patch)

I don't use spoof app version.

> 2. Reinstall RVX (Or delete app data)

I did uninstall  RVX. Then patched and installed using the stable release, and updated later to the dev release but the issue still persisted.
 
> 3. Report back if the issue is reproduced

Yes, I can reproduce the issue.

**Comment by ILoveOpenSourceApplications** [comment]
Here's the list of patches that I use:
![1000073244](https://github.com/user-attachments/assets/e9d93bfc-eefd-486d-9717-1ff56d840291)

**Comment by inotia00** [comment]
Does the issue reproduce even if you only include the `GmsCore support` patch?

**Comment by inotia00** [comment]
Ah, I can reproduce this on my side
If you turn on Stats for nerds, you will see that this is just a playback issue

This can be solved by using `Spoof streaming data`

**Comment by ILoveOpenSourceApplications** [comment]
> Does the issue reproduce even if you only include the `GmsCore support` patch?

Yes.

**Comment by ILoveOpenSourceApplications** [comment]
> Ah, I can reproduce this on my side If you turn on Stats for nerds, you will see that this is just a playback issue
> 
> This can be resolved by using `Spoof streaming data`

But I don't have this issue on 4.14.2 or on v4.15.1-dev.2.

**Comment by inotia00** [comment]
This issue is probably being reproduced after https://github.com/inotia00/revanced-patches/commit/f999aead6bdfd8040a5fdbd9f380c0dc6f79a5bc

Reverting the commit will fix the issue, but it may cause memory leaks or battery drain due to services not implemented in GmsCore

This is not a big problem, as the `Spoof streaming data` patch was added to fix the playback issue

**Comment by ILoveOpenSourceApplications** [comment]
From the changelogs, I'm only seeing two things that can cause this issue for me. This is my speculation. 

> 1) chore(YouTube/PlayerType): supplement PlayerType limits under certain conditions
> 2) fix(YouTube/YT Music - GmsCore support): unimplemented service in GmsCore causes memory leak ReVanced/revanced-patches#3768

**Comment by ILoveOpenSourceApplications** [comment]
> This issue is probably being reproduced after [inotia00/revanced-patches@f999aea](https://github.com/inotia00/revanced-patches/commit/f999aead6bdfd8040a5fdbd9f380c0dc6f79a5bc)
> 
> Reverting the commit will fix the issue, but it may cause memory leaks or battery drain due to services not implemented in GmsCore
> 
> This is not a big problem, as the `Spoof streaming data` patch was added to fix the playback issue

Is there a way to better implement this so that a user who didn't have any playback issue can continue without 'spoof streaming data'.

**Comment by inotia00** [comment]
> From the changelogs, I'm only seeing two things that can cause this issue for me. This is my speculation.
> 
> > 1. chore(YouTube/PlayerType): supplement PlayerType limits under certain conditions
> > 2. fix(YouTube/YT Music - GmsCore support): unimplemented service in GmsCore causes memory leak [bug: (YouTube)Too many Binders sent to SYSTEM ReVanced/revanced-patches#3768](https://github.com/ReVanced/revanced-patches/issues/3768)

If you only include the GmsCore support patch, then the `PlayerTypeHook` patch or the `LithoFilter` patch will not be applied

So 1 is not the cause of the issue

**Comment by inotia00** [comment]
The `Spoof streamind data` patch was added for the playback issue, and since the warning - `Turning off this setting may cause video playback issues.` - is already shown to the user, I don't think it is an issue

**Comment by inotia00** [comment]
> Is there a way to better implement this so that a user who didn't have any playback issue can continue without 'spoof streaming data'.

Although not ideal, there is a way to add the patch option `EnableGmsServiceBroker` to the `GmsCore support` patch

> Reverting the commit will fix the issue, but it may cause memory leaks or battery drain due to services not implemented in GmsCore

It may have side effects like the above, but it uses the old hooking method

**Comment by ILoveOpenSourceApplications** [comment]
> > Is there a way to better implement this so that a user who didn't have any playback issue can continue without 'spoof streaming data'.
> 
> Although not ideal, there is a way to add the patch option `EnableGmsServiceBroker` to the `GmsCore support` patch
> 
> > Reverting the commit will fix the issue, but it may cause memory leaks or battery drain due to services not implemented in GmsCore
> 
> It may have side effects like the above, but it uses the old hooking method

I would appreciate if this possible as I wouldn't be forced to use 'Spoof streaming data'.

**Comment by ILoveOpenSourceApplications** [comment]
What about these changes? https://github.com/ReVanced/revanced-patches/compare/v4.17.0-dev.12...v4.17.0-dev.13

**Comment by inotia00** [comment]
> What about these changes? [ReVanced/revanced-patches@v4.17.0-dev.12...v4.17.0-dev.13](https://github.com/ReVanced/revanced-patches/compare/v4.17.0-dev.12...v4.17.0-dev.13)

For the GmsCore support patch in revanced-patches-4.15.1-dev.3, the changes in ReVanced 4.17.0-dev.13 and the changes in 0xrxL/uDrop are already included

**Comment by inotia00** [comment]
Patch options are as follows:

title:

`Disable GmsService Broker`

description:

```
Disabling GmsServiceBroker will somewhat improve crashes caused by unimplemented GmsCore services.
For YouTube, the 'Spoof streaming data' setting is required.
```

The default is OFF, and only when the user manually changes it to ON will the same result as revanced-patches-4.15.1-dev.3 be achieved.

**Comment by ILoveOpenSourceApplications** [comment]
Thank you, @inotia00!

**Comment by Aryan-Chauhan** [comment]
Guys, I don't understand if I should keep the value of `DisableGmsServiceBroker` as true or false.

@inotia00 , can you explain which user should enable it and which should keep it disabled?

**Comment by inotia00** [comment]
The default value of the patch option `Disable GmsService Broker` is OFF

If you change this value to ON:

It will have better battery life and memory usage, since it will not invoke classes that are not implemented in ReVanced GmsCore

![Screenshot_20241019_233431_Device care](https://github.com/user-attachments/assets/ccd8ba5b-5d58-4386-b3e9-a3cc95ad72a3)

Of course, this only works for [ReVanced GmsCore](https://github.com/ReVanced/GmsCore/releases/latest)

It will have no effect if you use WSTxda/MicroG

[Since WSTxda/MicroG removes many services that are necessary for ReVanced to run](https://github.com/WSTxda/MicroG-RE/issues/20), it will cause more frequent crashes on ReVanced or RVX, regardless of whether you change the patch option

The downside of changing the patch option `Disable GmsService Broker` to ON is that it requires the `Spoof streaming data` setting
