### ISSUE TITLE
bug: Alternative thumbnails patch is applied even if not selected

### ISSUE THREAD

**Issue by ArcherLegend** [inotia00/ReVanced_Extended#2443]
### Type

Other

### Tools used

rvx-builder

### Application

19.16.39

### Bug description

The alternative thumbnails patch for RVX is applied even if it is not selected.
I have this issue with both RVX-builder 1.15.1 and 1.16.1 and it affects both forks of RVX I patch (inotia00 and anddea) no matter what the patched version is (latest release or dev build).

Patch RVX and unselect alternative thumbnails
Install RVX
Alternative thumbnails patch is in the settings and can be used
RVX-builder version 1.15.1 and 1.16.1

OS: Windows
Version: 10

### Acknowledgements

[settings.json](https://github.com/user-attachments/files/17450531/settings.json)
[options.json](https://github.com/user-attachments/files/17450532/options.json)

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It doesn't reproduce on my side

The issue is probably in RVX-builder

If you were using a sufficiently old RVX-builder and then updated it, you may need to manually delete the `settings.json` file

Please report back if the issue is reproduced after moving RVX-builder to another directory

**Comment by ArcherLegend** [comment]
I always use a freshly donwloaded RVX-builder an I run it in an empty folder.
I'll try to do this again with your latest dev build for RVX and reach back.

**Comment by ArcherLegend** [comment]
I have repatched with a cleanly donwloaded RVX builder in a new folder and I have cleanly installed RVX on my device however the alternative thumbnails patch is still available in the settings despite me not including it.
I have attached the .options and .settings jsons in the initial post in case they are useful.

**Comment by inotia00** [comment]
You excluded the `Alternative thumbnails` patch and included the `Bypass image region restrictions` patch

So setting should look like the attached screenshot

![Alternative_thumbnails](https://github.com/user-attachments/assets/2f1f510d-2e49-4ce6-ab84-4502dcc664e4)

![Patch_information](https://github.com/user-attachments/assets/fe83ee12-8b20-4bf5-945e-870aba92d6f1)

What does your setting look like?

**Comment by ArcherLegend** [comment]
This is embarassing, I missed the fact that the bypass image restriction was part of the alternative thumbnails API and if fact by excluding it and after a clean RVX installation the "alternative thumbnails" patch is gone from the settings... I am so sorry for wasting your time for a misundarstanding on my side in regards to the bypass image restricion patch.. I am marking this bug report as closed. Sorry again.

**Comment by inotia00** [comment]
It might be helpful for people who come to the repo with similar issues Discussing the issue is meaningful to these people
