### ISSUE TITLE
bug: hide explore more topics in feed

### ISSUE THREAD

**Issue by NichirinSword** [inotia00/ReVanced_Extended#2445]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

Option to hide explore more topics in feed.

![Screenshot_2024-10-21-13-37-50-58_f9ee0578fe1cc94de7482bd41accb329](https://github.com/user-attachments/assets/f6c07088-94d6-48f4-b686-917b9b7e132b)

### Device Environment

Android 14, realmeUI 5.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by smed79** [comment]
This is not included in : 
**Feed** > `Hide carousel shelf`
?

**Comment by NichirinSword** [comment]
> This is not included in : **Feed** > `Hide carousel shelf` ?

No

**Comment by smed79** [comment]
@inotia00 Can you provide a `custom filter` ?

Thanks in advance.

**Comment by inotia00** [comment]
Please provide debug log according to https://github.com/inotia00/ReVanced_Extended/issues/2437#issuecomment-2424625151

**Comment by NichirinSword** [comment]
@inotia00 adding the following custom filter solve this issue.

topic_with_thumbnail_view_model
