### ISSUE TITLE
bug: (YouTube) Subscriptions page auto scroll to top if `"hide_related_videos": true`

### ISSUE THREAD

**Issue by smed79** [inotia00/ReVanced_Extended#2446]
### Type

Other

### Tools used

RVX Manager

### Application

- YouTube 19.16.39

### Bug description

In **Experimental Flags** enable `Hide related videos`

`"hide_related_videos": true`

Scroll down the **subscriptions** page.
Click any video.
Close the video player.

You will notice the page auto jumped to top.

The page should stay where we have scroll it down.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [ ] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Do not report bugs that occur while using experimental flags

**Comment by smed79** [comment]
Ok, sorry for noise.
