### ISSUE TITLE
bug: (YouTube/Hide ads) Store ads below the video is not hidden

### ISSUE THREAD

**Issue by smed79** [inotia00/ReVanced_Extended#2447]
### Type

Other (ads)

### Tools used

- RVX Manager v1.22.2
- RVX Patches v4.15.1

### Application

- YouTube 19.16.39

### Bug description

I see store ads below the video player.

![horizontal_shelf_content](https://github.com/user-attachments/assets/806554d4-954a-43bc-909e-f8c92c44e212)

### Error logs

- [logcat_10-21-2024_18-43-55.zip](https://github.com/user-attachments/files/17466121/logcat_10-21-2024_18-43-55.zip)

### Solution

<s>Adding the below custom filter hide the ads.

-  `horizontal_shelf_content.eml`</s>

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by UnknownErrorNotFound** [comment]
Did you try clean install? Uninstall, repatch, reinstall.

**Comment by nick-77** [comment]
I can confirm this, having the same issue with 4.15.1 patches version

**Comment by smed79** [comment]
> Did you try clean install? Uninstall, repatch, reinstall.

For sure Yes.

At first I thought the problem was from restored `rvx settings` and for that reason i did a clean install.

**Comment by nick-77** [comment]
> Did you try the custom filter that i provided?

Didn't realise i could use it that way sorry, but yes just tried the custom filter method and it works 👍

**Comment by inotia00** [comment]
It's not reproduced on my side, but maybe `Hide movies shelves` is what hides this

**Comment by inotia00** [comment]
Nevertheless, if it is not hidden, please provide debug log according to https://github.com/inotia00/ReVanced_Extended/issues/2437#issuecomment-2424625151

**Comment by smed79** [comment]
> but maybe Hide movies shelves is what hides this

`Hide movies shelves` is already **enabled** in my settings.

> provide debug log

Already **provided** in my first messages (_Error logs_) !

**Comment by nick-77** [comment]
> @nick-77 
> 
> The filter i have provided `horizontal_shelf_content.eml` have the side effects to hide the horizontal **Playlists** in your profile tab 😞

Oh yes, I didn't notice till you mentioned it
Still, thankyou for trying to help 👍

> It's not reproduced on my side, but maybe `Hide movies shelves` is what hides this

Just tried enabling 'hide movie shelves', store ads are still visible

**Comment by ILoveOpenSourceApplications** [comment]
```kotlin
10-22 17:37:22.952 18976 19579 D Extended: LithoFilterPatch: Path: horizontal_shelf.eml|54b86fe45af5d3c1|CellType|horizontal_shelf_content.eml|d6c99df52af65671|ContainerType|ContainerType|CollectionType|shopping_item_card_list.eml|f8346fb6d9d34ace|CellType|shopping_item_card.eml|18462e928a7ba534|ContainerType|ContainerType|ContainerType|shopping_content_line.eml|3f1d5a2f482c2c38|ContainerType|shopping_content_line_item.eml|fa962b9552a7fe74|ContainerType|TextType|
10-22 17:37:22.952 18976 19579 D Extended: LithoFilterPatch: BufferStrings: shopping_content_line_item_key_0Γ¥Ö2,101.93Γ¥Ösans-serifΓ¥Ösans-serifΓ¥Ö
```

**Comment by smed79** [comment]
Both filters hide the ads but leave the title "... store".

![store_ads](https://github.com/user-attachments/assets/5503b040-00d9-4eec-97fd-eb6cfbe65850)

**Comment by KobeW50** [comment]
ReVanced just fixed this: https://github.com/ReVanced/revanced-patches/pull/3804

**Comment by federicogith** [comment]
And with this: https://github.com/ReVanced/revanced-patches/pull/3806
