### ISSUE TITLE
question: Is "feat add download button on shorts in `Hook buttons` patch" considered a feature request?

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#2448]
### Application

YouTube

### Question description

I wanted to request for a new button in the shorts UI that adds a download button that opens whatever is selected in `Hook buttons` patch. Right now I just copy the shorts link and go to YTDLnis app and search for it and download it in there but it would be convenient to have a button in the shorts itself. I am not sure if this is a entirely new feature request or just an addition to the `Hook buttons` patch so I am asking this question instead of just making a feature request.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Google has not implemented the download feature in Shorts
