### ISSUE TITLE
bug: dislike count wasn't shown when a dislike was pressed in the Shorts player

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#245]
### Type

Other

### Application

YT

### Bug description

The Dislike count is not shown after making a dislike on a Shorts video. The Dislike count is replaced by "Dislike" text after that.
And if we dislike a short and move to next one and come back to previous short, then, the dislike count also won't shown even liking or disliking. Check video to understand.

### Steps to reproduce

Play any shorts.

Dislike any video and see.

### Relevant log output

```shell
...
```

### Screenshots or videos

https://user-images.githubusercontent.com/93650504/218129762-19fa15c1-5a34-4759-97ec-ba3920a9f7ec.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)
