### ISSUE TITLE
bug(YouTube): `Return YouTube Username` doesn't work with preview comment

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2450]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.15.1

### Bug description

https://github.com/user-attachments/assets/ed06a36f-d4af-4629-b6a1-ebf34e1ceeac

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
We can't change all the handles that are accessible from the comments

It's a bit long to explain technically, but in short, some handles are not in text format but in animation format, so it's impossible to replace them

In addition, for handles that have text format but are not replaced, the code is too complex and memory-intensive to implement, so they are not implemented

This is the same for `Return YouTube Username` implemented in the RVX patch, as well as for `Return YouTube Comment Username` in Chrome Extensions

For this reason, the `Return YouTube Username` patch is excluded by default
