### ISSUE TITLE
feat(YouTube/Hide Store Components): add `Hide products and commissions section links` setting 

### ISSUE THREAD

**Issue by hphp22f** [inotia00/ReVanced_Extended#2451]
### Application

YouTube

### Feature description

Hopefully an option to `hide products and commissions` it will be added in the next patch.

### Motivation

![Screenshot_2024-10-23-00-38-36-490-edit_com google android youtube](https://github.com/user-attachments/assets/e0386850-c3c2-4c01-8d0b-faa31e1e4529)

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [ ] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2447
