### ISSUE TITLE
Add feature to enable/disable "Video Download Suggestion" in RVX settings

### ISSUE THREAD

**Issue by Hulklove** [inotia00/ReVanced_Extended#2455]
### Application

YouTube Music

### Feature description

• If this feature is turned off, the app will no longer suggest downloading videos when the network connection is lost (Google's purpose of this is to Download videos with network connection and watch videos when there is no network connection offline)
• The application in question is "YouTube RVX"

### Motivation

• Essential for non-tech savvy seniors (Their kids will set it up).
• When the network connection is lost, YTB Rvx will not suggest videos to download and the elderly will not accidentally press the download button, causing the memory to be full when the network connection is restored.
• Their children only need to set it up for the elderly once, no need to worry about the elderly accidentally downloading videos when accidentally clicking the recommended video download button when there is no network, causing the memory to be full.
• Your app is very popular with young and old people... Old people use Youtube Rvx a lot, but some smart features they can't develop and use properly in thinking
![Screenshot_20241022-215219_Google~2](https://github.com/user-attachments/assets/84a7eee5-7224-446a-af6b-9a4358a136ea)
.

https://img.upanh.tv/2024/10/25/Screenshot_20241022-215219_Google2.png

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Thank you for your inquiry, but I do not accept feature requests for YouTube

**Comment by Hulklove** [comment]
Thanks for the feedback, I still love you and your products no matter what.
Thanks

Vào 06:07, T.6, 25 Th10, 2024 inotia00 ***@***.***> đã viết:
