### ISSUE TITLE
bug: store ……

### ISSUE THREAD

**Issue by Bakchxd** [inotia00/ReVanced_Extended#2456]
### Type

Other

### Tools used

RVX Manager

### Application

youtube-rvx_v19.16.39-patches_v4.15.1
![Messenger_creation_5F0BD109-2313-45BC-B680-553920F07D00](https://github.com/user-attachments/assets/51795392-3e09-41bf-9dc0-1cef7a58aa05)

### Bug description

hide store option doesn’t work 

### Device Environment

Android 11 realme ui

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by smed79** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2447

**Comment by Bakchxd** [comment]
It doesn’t solve the problem
