### ISSUE TITLE
bug(YouTube): Not all SponsorBlock settings get exported

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2457]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.16.1-dev.1

### Bug description

As you can see, only a minimal part of SponsorBlock settings get exported.
For example, SB has 9 segment types (Sponsor, Unpaid, Highlight and so on) in total, but only 4 (Filler, Highlight, Interaction and Introduction) of their behaviours are exported. Also, none of segments's colour hex values, the buttons' or unavailable API toast messages' visibility preferences are getting exported, and so on.
![1000052076](https://github.com/user-attachments/assets/a8541ee0-a8c1-49cf-8c9e-c0046834360c)

### Solution

Export every single setting of SponsorBlock.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2404
