### ISSUE TITLE
feat(patch): want true black not grey please 

### ISSUE THREAD

**Issue by afisyazriq** [inotia00/ReVanced_Extended#246]
### Application

YouTube

### Issue

background color

### Patch

-

### Motivation

similiar to original youtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
include `theme` patch
