### ISSUE TITLE
bug(YouTube/Seekbar compontents): `Enable high quality thumbnails` don't work

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#2460]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

**Patches**: 4.16.1-dev.1
**App version**: 19.16.39 (recommended) 19.17 and above (new thumbnail previews in seekbar are default)

### Bug description

When the option given in the issue title is enabled, the quality of the thumbnails does not change and still is "medium". Naturally, users using combo Premium+RVX are not affected, because they have "high quality".

### Device Environment

**Device**: Xiaomi POCO X6 Pro 5G
**OS**: HyperOS 1.0.12.UNLEUXM (Europe)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
I'm using v19.16.39 and this patch is not working for me, previews are still of same quality as before.

**Comment by GucekPL** [comment]
Good to know, I will edit issue

**Comment by ILoveOpenSourceApplications** [comment]
Shouldn't this issue also be opened in the ReVanced repo, given that this feature was introduced there first.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v4.16.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.16.1)

**Comment by keekek69** [comment]
@inotia00 

Would you consider re-adding this patch at some point? Now that "Restore old seekbar thumbnails" is gone, it would make sense to test this patch again to see how it works with newer YouTube version.
