### ISSUE TITLE
bug(YTM/Player components): Song uses background color if it contains Video, even after enabling `Player uses Black Background`

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2463]
### Type

Other

### Tools used

RVX Manager

### Application

YTM Latest Supported

### Bug description

After enabling, songs without videos uses black background. But, if the video contains video, then, it will use the background color. It should always remain black even the video contains the video. There should not be any effect of having video in the song.

https://github.com/user-attachments/assets/66945842-4ff4-45fa-8837-5a4ce8c17926

### Device Environment

A14 (FT OS 14)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by vippium** [comment]
> This seems to be a duplicate of #2119
> 
> If it is, please comment on that issue that it only occurs on songs with videos.

It can be duplicate. In that issue, I also got songs without videos which doesn't follow it. But still, it is unsolved.

**Comment by vippium** [comment]
Why closed?

**Comment by KobeW50** [comment]
inotia00 marked it as a duplicate
