### ISSUE TITLE
question: How can I set a larger preload buffer? 

### ISSUE THREAD

**Issue by alcatraz-zz** [inotia00/ReVanced_Extended#2464]
### Application

YouTube

### Question description

Hey fellas. Love your work.

My internet speed goes a bit up and down sometimes and having a longer preload buffer would help with that A LOT. Right now it's 5 seconds (default), but I'd like to set something like 30s.

I can't see an option for it. 

Thanks for the help!

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Unfortunately there is no such option for this. It did exist in the past, but it broke close to 2 years ago and the patch was removed. See https://github.com/inotia00/ReVanced_Extended/issues/198 for more information.
