### ISSUE TITLE
suggestion (YouTube/Seekbar components): Change default seekbar color to match new branding 

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#2466]
### Application

YouTube

### Suggestion description

A minor suggestion that does not require much work. With YT's new branding coming into effect from 15.10, it would be nice to change the default seekbar colour from the current **`#FF0000`** to **`#FF0033`**.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.1)
