### ISSUE TITLE
bug(YouTube/SponsorBlock): wrong segment behavior selected

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2468]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.16.1-dev.1

### Bug description

Only showed the first 3 segments types but it's the same with all.

https://github.com/user-attachments/assets/e858e324-914f-4bd7-8041-76a804d25cc9

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
It shows at 0:30 that the exported settings configuration file is 0 bytes.

**Comment by Kuddus73** [comment]
> It shows at 0:30 that the exported settings configuration file is 0 bytes.

https://github.com/user-attachments/assets/2bb53f81-9393-4733-881c-d87d2e2c5599

**Comment by inotia00** [comment]
When you open a video with a SponsorBlock segment, the imported settings will work as they were

That is, these settings were imported successfully, but the wrong values ​​are selected in the SponsorBlock segment dialog

**Comment by inotia00** [comment]
reflected in [revanced-patches-v4.16.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.16.1)
