### ISSUE TITLE
bug(YouTube): "Upload time", number of "Views", "Likes" and "Dislikes" are not shown

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2469]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.16.1-dev.1

### Bug description

![Screenshot_20241102_155750_YouTube](https://github.com/user-attachments/assets/efb1eb23-7c4d-4336-b6d3-a574568dcd1e)
![Screenshot_20241102_155753_YouTube](https://github.com/user-attachments/assets/26c99efb-064d-48d1-9d42-d1d89e58db55)

**After some time, while you watching the video, even the upload time under the video title disappears:**
![Screenshot_20241102_162955_YouTube](https://github.com/user-attachments/assets/0cb63e09-52fc-41fa-9272-29beee99f8ba)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by GucekPL** [comment]
Use spoof app version to 19.13.37. That's YT-related issue.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2419
