### ISSUE TITLE
question: Playback quality

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#247]
### Application

YouTube

### Description

When I play a video on youtube in browser, it supports 2k and 4k playback, and working fine, but in app maximum is 1080p. Is it possible to patch youtube to enable 2K/4k playback in revanced?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
YouTube resolution depends on device hardware
ReVanced and ReVanced Extended have no bearing on it
(If your device does not support 4k resolution on the stock YouTube, ReVanced and ReVanced Extended also do not support 4k resolution.)
