### ISSUE TITLE
bug: likes and view count disappeared from the videos

### ISSUE THREAD

**Issue by JakobHunterek** [inotia00/ReVanced_Extended#2471]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 19.16.39

### Bug description

Like count and view count disappeared from countless YouTube videos
![Screenshot_20241104_221800_RVX](https://github.com/user-attachments/assets/e3025f7c-a87d-40c9-a893-c272a3e2984e)
![Screenshot_20241104_221818_RVX](https://github.com/user-attachments/assets/f3ab50e7-2ef1-4aa9-8d6f-299b72cde199)

### Solution

None

### Additional context

Using recommended patches plus materialyou minus swipe controls 
Patch version 4.15.1

### Device Environment

Android 14 oneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2469
