### ISSUE TITLE
suggestion(YouTube): change option option

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2472]
### Application

YouTube

### Suggestion description

The option "Hide Notify me button" hides this button:
![01](https://github.com/user-attachments/assets/46d87476-b649-42d6-bf12-044ab756b9d5)
But there is another button with the same name inside the player:
![02](https://github.com/user-attachments/assets/ae9b3e53-7751-42e0-8e1a-81a6864283f4)

To differentiate the buttons, change the option's name to "Hide Notify me button in feed" or something similar

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The `Hide Notify me button` setting is in the `Feed` category, not the `General` or `Player` category, so it seems okay to leave the description unchanged

**Comment by federicogith** [comment]
> The `Hide Notify me button` setting is in the `Feed` category, not the `General` or `Player` category, so it seems okay to leave the description unchanged

Following that logic also from "Hide feed captions button" or "Hide feed search bar" should be removed the word "feed" from them since they are also in the "Feed" category

**Comment by inotia00** [comment]
Please open a new issue
