### ISSUE TITLE
question: why was "Hide in watch history" removed?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2475]
### Application

YouTube

### Question description

The patch release doesn't say anything about its removal
It was useful to hide Shorts really everywhere

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
stopped working on my device

**Comment by inotia00** [comment]
1. That setting sometimes doesn't work, and also causes the Shorts shelf to sometimes not hide (e.g. https://github.com/inotia00/ReVanced_Extended/issues/2467)

2. If you hide all the Shorts shelves, the Shorts shelf will also be hidden in the Watch history
