### ISSUE TITLE
suggestion:(YouTube) Remove the spoof app version dialog when the app is first launched - no longer needed

### ISSUE THREAD

**Issue by RVXuser** [inotia00/ReVanced_Extended#2477]
### Application

YouTube

### Suggestion description

Since Google has fixed the issue #2419 we no longer need the spoof app version dialog to show up when the app is launched for the first time.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v4.16.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.16.1)
