### ISSUE TITLE
question: Why YouTube Music Revanced Extended Closes Itself?

### ISSUE THREAD

**Issue by SMOKESCREE** [inotia00/ReVanced_Extended#2479]
### Application

YouTube Music

### Question description

Why does YouTube Music Revvanced Extended crash so much?
I have the Xiaomi Redmi A2 with Android 13 Go Edition MIUI 14 and when the music pauses the app closes by itself.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please add YouTube Music version and revanced-patches version

**Comment by SMOKESCREE** [comment]
Version: 7.16.53
Revanced Patches: 4.17.0

**Comment by inotia00** [comment]
> Version: 7.16.53 Revanced Patches: 4.17.0

It looks like you are not using RVX

The latest RVX patch is [revanced-patches-4.15.1](https://github.com/inotia00/revanced-patches/releases/latest)

Re-patch according to the [documentation](https://github.com/ReVanced-Extended-Community/Community-Guides?tab=readme-ov-file#community-guides)

**Comment by SMOKESCREE** [comment]
> Adicione a versão do YouTube Music e a versão revanced-patches

Version: 7.16.53
Revanced Patches: 4.15.1

**Comment by SMOKESCREE** [comment]
YouTube Music Revanced Extended continues to crash a lot in the background.
I installed GMSCore Huawei on my Xiaomi and it still doesn't solve the problem.
I've already used YouTube Music Revanced and YouTube Music Revanced Extended Anddea and it's the same situation.

**Comment by inotia00** [comment]
If you exclude all patches and only include the GmsCore support patch, does RVX Music still crash?

If possible, please attach a crash log
