### ISSUE TITLE
bug: endscreen cards/ fullscreen panels

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#248]
### Type

Other

### Application

Youtube 18.05.35

### Bug description

The swipe up to show endscreen cards gesture does not work if you enable 'hide-fullscreen-panels' and enter fullscreen mode while leaving comments/ live chat open

### Steps to reproduce

1. include hide-fullscreen-panels patch but dont include hide-endscreen-cards patch
2. play a video, goto fullscreen mode and endscreen cards will show up if you swipe up
3. now exit fullscreen mode, open comments box or live chat, now go to fullscreen mode again
4. swipe up as much as you want, endscreen cards wont show up

### Relevant log output

```shell
none
```

### Screenshots or videos

https://user-images.githubusercontent.com/87489540/218274967-3ab85e4f-72af-41dc-8f6c-5c07df601787.mp4

### Solution

bring back hide-fullscreen-buttoncontainer patch.  it does the work for most users as the only irritating thing on fullscreen is the button container.  as for the fullscreen panels patch, you can remove it or keep it as well.  users can choose buttoncontainer patch or panels patch, whichever they like

### Additional context

.

### Device Environment

LOS 18.1 A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
it's not a bug
`hide-fullscreen-panels` patch was added by the official ReVanced Team, and if you enable the patch, the tablet layout will only be applied in fullscreen

In the tablet layout, the related video (end screen overlay) is not shown when swiping up.
For the same reason, the tablet layout does not support comment panels in fullscreen
it is Google's intent so it's normal

**Comment by MondayNitro** [comment]
even so, can you please bring back the hide-fullscreen-buttoncontainer patch? a lot of people are used to using comments and endscreen cards on fullscreen. i will be grateful if you bring this patch back. i also requested it here https://github.com/inotia00/ReVanced_Extended/issues/227

**Comment by MondayNitro** [comment]
on a different note, patching 18.04.43 gives error
