### ISSUE TITLE
feat(YouTube/Spoof streaming data): update the hardcoded iOS client version

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2480]
### Application

YouTube

### Feature description

**This is not a feature request, but a description of the feature that will be introduce in the next release.**

While testing the `Spoof Streaming Data` patch, I found that it is possible to use the opus codec on iOS clients if the iOS app client version is close enough to the latest version.

[The same issue was already opened in the ReVanced repository](https://github.com/ReVanced/revanced-patches/issues/3756), but it was not reproducible on my side at the time.

It is possible that an A/B test was applied to my account, but it is more likely that it was rolled out widely.

The reasons for this are:
1. The opus codec was available on all Google accounts and in Inognito mode.
2. The opus codec was available on iOS app client version 19.30.2, while it was not available on 19.16.3.

The following environments are still untested:
1. Whether the opus codec is available on hardware AV1 decoding.
2. Whether the opus codec is available even when the app version is spoofed.

Nevertheless, since the opus codec can be partially available, it is necessary to update the iOS app client version.

### Motivation

It's not hard to make the opus codec partially available thanks to server-side changes.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v4.16.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.16.1)

**Comment by dib12** [comment]
Then why not add a setting to change ios app version in setting.

It will more better if there will a feature to import custom configuration for spoof .(Like device,model,app version in xml)
Thank you
