### ISSUE TITLE
bug: (YouTube) App crashes after patching v4.16.1-dev.3

### ISSUE THREAD

**Issue by RVXuser** [inotia00/ReVanced_Extended#2481]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

After installing v4.16.1-dev.3 the app crashes when launched, cleared cache and data, uninstalled, patched again and reinstalled, still crashes.

![Screenshot_20241108_154301_Device care](https://github.com/user-attachments/assets/55b96367-630e-4b2d-b0ce-774c56532cac)

### Error logs

```shell
I got this error popup, attached above.
```

### Device Environment

Android 14 - OneUI 6.1.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by RVXuser** [comment]
Why closed?

**Comment by inotia00** [comment]
update to revanced-patches-v4.16.1
