### ISSUE TITLE
bug: YTM crashes when casting

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2482]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube music 7.16.53

### Bug description

App crashes after trying to cast to tv, after i relaunch it crashes again till tv us disconnected or turned off

### Device Environment

Tried on 3 devices, android 12,14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Casting can be partially supported, but it causes severe battery and memory drain

(GmsCore does not fully support casting, so it cannot be fixed on the patch side)

That is why the services related to casting have been disabled since the latest patch

If you want to use casting, use the root build

**Comment by AykhanUV** [comment]
Hey i wanted to update i tried older patches from july, august it worked now with latest ones it does not

**Comment by AykhanUV** [comment]
Now i tried revanced it seems to work fine too?
