### ISSUE TITLE
bug: YouTube Music playback stops after reaching 1 minute and gets loading infinitely

### ISSUE THREAD

**Issue by geilsonf15** [inotia00/ReVanced_Extended#2484]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube Music 7.16.53

### Bug description

Whenever i play a song on YouTube Music the player gets stuck after 1 minute of playing and endlessly loads the media. And if I move the seek bar to 1 minute or more, the problem persists and the play/pause button stops responding.
![Screenshot_2024-11-08-16-30-49-546_app.rvx.android.apps.youtube.music](https://github.com/user-attachments/assets/e4a0ca92-fdc2-4214-9453-2ac7f21b6aa7)

### Additional context

Playback was working a few days ago, but recently started having the issue.

### Device Environment

Xiaomi POCO X5 5G, Android 14, HyperOS 1.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Maybe Google is testing the playback issue on YouTube Music too

Can you please check if the issue is reproduced on the official ReVanced?

**Comment by geilsonf15** [comment]
I checked, the problem also happens in official ReVanced.

**Comment by inotia00** [comment]
Could you try patching with YouTube Music 6.20.51, which is the lowest version supported by the patch, and report back the results?

**Comment by geilsonf15** [comment]
I patched version 6.51.53 (the last one before v7.x.x, without any buffer issues, as well as in 6.20.51

**Comment by inotia00** [comment]
The next release will also add a Spoof streaming data patch to YouTube Music

Until then, anyone with playback issues can patch YouTube Music 6.20.51 - 6.51.53

**Comment by rm4xn** [comment]
Tested those versions but I'm still having the problem. Songs stop playing at the minute.

**Comment by KARTIKEYNEGI** [comment]
Same here

**Comment by MrPPatra** [comment]
7.24.51, non root, suddenly stop playing in 1 minutes range. What happened.

**Comment by MrPPatra** [comment]
Installed 6.20.51, and it's solved.

**Comment by MrPPatra** [comment]
Still the same issue with 6.20.51 from today.
I just restart my device and this happened.

**Comment by PoeticMichael** [comment]
JFYI, same problem started happening to me two days ago on my "Google built-in" embedded car system (Polestar, Android 12).

After clearing cache and storage, trying to reinstall it, Youtube Music stopped playing songs completely :(

**Comment by MrPPatra** [comment]
I turn off the spoof player from settings and now working again.

**Comment by SMOKESCREE** [comment]
I installed version 7.13.52 and it is working correctly.
Versions 7.17.51 ​​and 7.16.53 have the buffering problem.

**Comment by SMOKESCREE** [comment]
Versions 6.20.51 and 6.51.53 also have a buffering problem.

**Comment by inotia00** [comment]
There are two workarounds

Workaround 1. Re-patch with [revanced-patches-5.0.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.0.1), including the `Spoof client` patch, and enable Spoof client (Settings > ReVanced Extended > Miscellaneous > Spoof client)
Workaround 2. Enable Spoof app version

The `Spoof streaming data` patch will be added in the next release

**Comment by Zeyrisk** [comment]
have same issue, but for now i can play music with another account, temporary way while waiting for fix :)

**Comment by KobeW50** [comment]
> have same issue, but for now i can play music with another account, temporary way while waiting for fix :)

The fix is already out

**Comment by roy1205** [comment]
Alguien que me pueda ayudar mi YT miusic se detiene después de 1 minuto de reproducir y pide actualización

**Comment by ananalby** [comment]
The problem solved using 6.51.53 build

**Comment by roy1205** [comment]
Alguien me pudiera pasar el link de YouTube miusic con la actualización mas reciente y con su parche

**Comment by TheFoxsGuide** [comment]
Can anyone explain me how do I change the version of the patch in RVX Manager to the one that Inotia shared (5.0.1)?

I tried patching YT Music by myself using the RVX Manager that the patch version needs (Universal fork 1.23.4), but I don't know how to change the patch version from the latest one to the 5.0.1 on the app.

**Comment by jgoedde** [comment]
> Thanks! Going into the miscellaneous settings and turning on spoof video streams worked.

Not working for me, running latest ReVanced patches (5.41.0) with recommended yt music APK and ReVanced microg services

Version 0.3.1.4.240913

app.revanced.android.gms
versionCode 240913008

Playback still stops after 1 m, showing banner "could not fetch any client streams" no matter spoof video streams being on or off.
