### ISSUE TITLE
bug(Reddit): `Change version code` patch doesn't work as it's set to false

### ISSUE THREAD

**Issue by rywz** [inotia00/ReVanced_Extended#2486]
### Type

Error while patching

### Tools used

rvx-builder

### Application

Reddit 2024.46.0.2012189

### Bug description

Self explanatory. It sets  `ChangeVersionCode` to false and the patch doesn't work as intended.

![1](https://github.com/user-attachments/assets/75dc71e5-a105-4301-969e-bd5e2a88057b)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The arsclib branch is based on a fairly old revanced patcher, so sometimes patches are not excluded

Therefore, the `Change version code` patch only changes the version code if the value of options.json is true

You left the value of options.json false or did not change it, so the patch was not applied

This is the intended behavior

**Comment by inotia00** [comment]
If you are using termux, type `opon`

options.json editor will open
