### ISSUE TITLE
YouTube app can not videos cast to TV by cast button click

### ISSUE THREAD

**Issue by Komar2000** [inotia00/ReVanced_Extended#2487]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 19.16.39 and newer

### Bug description

There is a problem in the Youtube videos cast to TV . you can connect (link) the TV using the cast button but the video does not work on the TV !!! it is as if the app never connected to the TV at all !!!

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2482
