### ISSUE TITLE
New rvp format

### ISSUE THREAD

**Issue by paradowskidm** [inotia00/ReVanced_Extended#2489]
### Application

YouTube

### Question description

Will you be switching to the new rvp format like the revanced team did?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's on the roadmap and will be implemented by February 2025 at the latest
