### ISSUE TITLE
suggestion: Refining ReVanced Extended Settings 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#249]
### Application

YouTube

### Issue

Add back button on the top left for every sub category pages under ReVanced Extended Settings along with their own titles just like the initial settings page after clicking the same.
Main RVX Settings page:
![Screenshot_20230212-144729~2](https://user-images.githubusercontent.com/117499019/218302758-c97a72c2-014a-4b4f-8f08-cc71cf19e7be.png)
Why the seperation in between, where one is titled ReVanced settings and the other ReVanced Extended Settings? Some of those patches are unique to extended and not present in ReVanced and hence I don't understand this seperation.

One of the sub settings page:
![Screenshot_20230212-145121~2](https://user-images.githubusercontent.com/117499019/218302802-bba3ac06-ee40-490d-a195-3dfd2064366d.png)
Also rename the main settings title to ReVanced Extended settings rather than ReVanced settings and remove the title under it.
![Screenshot_20230212-145331~2](https://user-images.githubusercontent.com/117499019/218302964-15cc244b-6bf5-4fd2-9ba2-0151da63ca49.png)

### Patch

As mentioned above in issues.

### Motivation

Revanced Extended, though a fork of ReVanced, is still progressing and considering the request of its users and progressing steadily. Hence it should have its own unique identity throughout the UI.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.162.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.1)

**Comment by ILoveOpenSourceApplications** [comment]
![Screenshot_20230218-141906~2](https://user-images.githubusercontent.com/117499019/219851248-ccc29e1b-9a79-4c1b-86d7-4f4334249850.png)
Is this really necessary, to have a title below the ReVanced Extended settings title in the settings bar. 

Also I believe out of my suggestions only some got implemented and hence I believe this can't be closed now right?

**Comment by inotia00** [comment]
Only acceptable suggestions were partially reflected

The reason this issue is closed is because there are no plans to reflect the rest of the suggestions.

If there are any changes to the official ReVanced, they will be reflected.

**Comment by ILoveOpenSourceApplications** [comment]
> ![Screenshot_20230218-141906~2](https://user-images.githubusercontent.com/117499019/219851248-ccc29e1b-9a79-4c1b-86d7-4f4334249850.png) Is this really necessary, to have a title below the ReVanced Extended settings title in the settings bar.

Can't atleast this be implemented then? As ReVanced Extended settings is the only option having a subtitle to the original title, yes it sticks out but aesthetically it's not nice.

**Comment by inotia00** [comment]
> > ![Screenshot_20230218-141906~2](https://user-images.githubusercontent.com/117499019/219851248-ccc29e1b-9a79-4c1b-86d7-4f4334249850.png) Is this really necessary, to have a title below the ReVanced Extended settings title in the settings bar.
> 
> Can't atleast this be implemented then? As ReVanced Extended settings is the only option having a subtitle to the original title, yes it sticks out but aesthetically it's not nice.

reflected in [revanced-patches-v2.162.6](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.6)

**Comment by ILoveOpenSourceApplications** [comment]
Thanks!
