### ISSUE TITLE
question: Why did I switch to the old version for recommended downloads

### ISSUE THREAD

**Issue by wwjj999** [inotia00/ReVanced_Extended#2490]
### Application

YouTube

### Question description

Has the recommended download version become an old version? Why?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
If you are referring to the recommended version for YouTube, the reasons are outline in https://github.com/inotia00/ReVanced_Extended/issues/2241

Important announcements and common information can be found in the release notes (https://github.com/inotia00/revanced-patches/releases)

Also, if you are downloading a pre-patched APK from any website or social media, they are unofficial. See the [documentation](https://github.com/inotia00/revanced-documentation) for official methods to install ReVanced Extended apps.

**Comment by KobeW50** [comment]
Unofficial and possibly malicious. Please see the documentation.
