### ISSUE TITLE
feat: YouTube revenced extended for Android tv 

### ISSUE THREAD

**Issue by MD-ISMAIL-1** [inotia00/ReVanced_Extended#2492]
### Application

YouTube Music

### Feature description

Hello revenced team, thank you for your great app you developed. 
I have a request to you to develop the YouTube app for Android tv. The smart tube app is great but not familiar like original YouTube app. 🥺Please kindly make a mod version for YouTube tv app with same UI but with premium features like add blocking like you developed the mobile version.
I Hobe you would be kind enough to to review my request of the YouTube revenced app for Android tv.
Respectfully-
Ismail
From Bamgaldesh.

### Motivation

In the YouTube tv app there are many annoying adds in almost every video. And the premium version is very expensive for people like us.
It would be very helpful for us if you fulfill your request. 

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by RVXuser** [comment]
Use SmartTube on androidtv, you can sideload it. Just google the instructions how to do it, then you can use RVX as a remote for it.
