### ISSUE TITLE
question: Someone is uploading your RVX Manager to APKMirror

### ISSUE THREAD

**Issue by RVXuser** [inotia00/ReVanced_Extended#2493]
### Application

Other

### Question description

I found these today by accident:

https://www.apkmirror.com/apk/inotia00/

I think these should not be there.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is the response I received from APKMirror when I asked about it:

![APKMirror](https://github.com/user-attachments/assets/0909e311-e7a1-4863-af95-bc794fe969be)
