### ISSUE TITLE
bug:(YouTube) The embed segment keeps playing after its end

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#2494]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Any version

### Bug description

Video doesn't stop at the end of its embed segment, but keeps playing.
Link with embed segment for example:
https://youtube.com/embed/[video ID]?start=35&end=55
In RVX, the video doesn't stop at 55s.

In all mobile and desktop browsers, this link works fine and stops the video at the end of the segment.

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an issue with unpatched YouTube.
