### ISSUE TITLE
Bug: Watched shorts aren't visible in watch history

### ISSUE THREAD

**Issue by nick-77** [inotia00/ReVanced_Extended#2495]
### Type

Cosmetic

### Tools used

Revancify

### Application

YouTube v 19.16.39
Rvx patches version 4.16.1

### Bug description

• Shorts are not visible in watch history section in the YouTube app, even when it's visible in history in "YouTube history" section in Google 

### Additional context

• only shorts are affected, regular videos showup in watch history
• tried with clean install of YouTube app aswell
• using two experimental settings, however the result is same even when disabled experimental settings

### Device Environment

Android 14, Realme UI 5.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by nick-77** [comment]
Not sure if it's related, but I have this issue aswell where history section is like this ![1000026485.jpg](https://github.com/user-attachments/assets/342a7476-76d9-4934-85f0-8c2d17df9821)

**Comment by inotia00** [comment]
If the all settings to hide all Shorts shelves are enabled, the Shorts shelf will always be hidden https://github.com/inotia00/ReVanced_Extended/issues/2475#issuecomment-2460063644

This is intended behavior, and the official ReVanced has the same behavior
