### ISSUE TITLE
question: how would it be possible to fully hide the button?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2498]
### Application

YouTube

### Question description

I use a filter to hide the subscribe button under the player, but the filter sometimes doesn't hide the button completely.
![ _20241121_141901](https://github.com/user-attachments/assets/ccfe941b-704a-4d92-9360-f393d6c3f3dd)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
```
^compact_channel_bar.eml$subscribe-button-key
```

**Comment by federicogith** [comment]
@inotia00 tried both ways but didn't work

![Screenshot_20241126_114304_YouTube](https://github.com/user-attachments/assets/d6e4f4c6-04e4-4c97-a19d-a7c9ba7e1e5b)
![Screenshot_20241126_114404_YouTube](https://github.com/user-attachments/assets/95d3bbdf-4d48-4551-ba43-07c83ce1552f)
![ _20241126_114705](https://github.com/user-attachments/assets/ac1ce673-0f01-432e-a9ca-c2c2d11e9270)

**Comment by inotia00** [comment]
Well then I don't know either

**Comment by ScorpionFy** [comment]
Actually inotia00 the bug occurs only from 18.29.38 to 19.16.39, but the bug isn't present in the 19.44.39 aka recommend version.
