### ISSUE TITLE
Error 400 while playing a video

### ISSUE THREAD

**Issue by E-Radjas** [inotia00/ReVanced_Extended#2499]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.23.40

### Bug description

When playing any video you get the message "There was a problem with the server [400] (Playback ID: XXXXXXXXXXXX)" in the player.

### Solution

 I found a fix by disabling client spoof but I don't know if it's a good idea and if it will have side effects.

### Additional context

It doesn't happen on another account in the same build for some reason.

### Device Environment

Android 14, One UI 6.1.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You are using an outdated patch

Re-patch to the latest resources according to the [docs](https://github.com/ReVanced-Extended-Community/Community-Guides/blob/main/community-wiki/guide-for-beginners.md)

**Comment by RVXuser** [comment]
> You are using an outdated patch
> 
> Re-patch to the latest resources according to the [docs](https://github.com/ReVanced-Extended-Community/Community-Guides/blob/main/community-wiki/guide-for-beginners.md)

Hes also using unsupported version, this version is not yet supported.
