### ISSUE TITLE
bug: Tapping like/dislike button doesn't update their states unless the video is reloaded.

### ISSUE THREAD

**Issue by christantoan** [inotia00/ReVanced_Extended#25]
### Type

Cosmetic

### Application

YouTube v17.49.37
Patches v2.147.0

### Bug description

Tapping like/dislike button doesn't update their appearance and counter unless the video is reloaded.

### Steps to reproduce

1. Patch normally
2. Open a video
3. Tap like or dislike button
4. The button and its counter don't update their states

### Relevant log output

```shell
None
```

### Screenshots or videos

https://user-images.githubusercontent.com/7300310/209329090-78520907-fa9b-449c-8f78-70490f7e3b7b.mp4

### Solution

Reload the video to update button's state

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
A clean install is essential

After the first run, open ReVanced Settings, force close the app, then try running again.

Check if issue reproduce

**Comment by christantoan** [comment]
Sorry. I thought it was a clean install because it has a new package name.

After doing your tips woth proper clean reinstall, it now all works.

Sorry for the false bug reports.

**Comment by inotia00** [comment]
Don't worry, I created this repo to receive reports on even minor issues.
