### ISSUE TITLE
bug: Image Very Pixelated on 1440p and 2160p (not 1080p)

### ISSUE THREAD

**Issue by tomhollandy** [inotia00/ReVanced_Extended#2502]
### Type

Error while patching

### Tools used

RVX Manager

### Application

On the last youtube RVX (6 November 2024)

### Bug description

When you switch on 1440p and 2160p (not 1080p), you have an image very very pixelated, impossible to watch a video.

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's an issue with YouTube
