### ISSUE TITLE
Will the duration filter ever come back?

### ISSUE THREAD

**Issue by goooglefc** [inotia00/ReVanced_Extended#2503]
### Application

YouTube

### Question description

Will the duration filter return to RvX or is it gone forever?

I just want to hide videos longer than 30 mins from my subs feed.

Is there another way to do this?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
If I could filter it out, it would be added back in, but I think it's probably pretty unlikely
