### ISSUE TITLE
question: Playlist thumbnail customization

### ISSUE THREAD

**Issue by SamratVikramaditya108** [inotia00/ReVanced_Extended#2505]
### Application

YouTube Music

### Question description

Like spotify allows us to edit and customize the thumbnail for playlist, can we have the same for YT Music? The library looks very cluttered with the default thumbnail of 4 songs in a grid format

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As far as I know, it's impossible
