### ISSUE TITLE
suggestion: iOS Client Deletion Request

### ISSUE THREAD

**Issue by AsphaltKoreaWiki** [inotia00/ReVanced_Extended#2509]
### Application

YouTube

### Suggestion description

The IOS client no longer works, Android VR does

### Acknowledgements

- [ ] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2508

**Comment by kitadai31** [comment]
For your information, iOS client still works if Google account is logged out (including incognito mode)
