### ISSUE TITLE
bug: Server Error

### ISSUE THREAD

**Issue by AFSkyzoo** [inotia00/ReVanced_Extended#2510]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

![IMG_20241128_173149](https://github.com/user-attachments/assets/7e0a2a97-c869-4e4d-aa26-722e75dbba57)
ReVanced Extended Version 19.25.39

### Bug description

![IMG_20241128_173605](https://github.com/user-attachments/assets/53369bbc-23a4-42ad-822d-1bef4675bbd3)
When i try to play some video with a google account,it gets a message about server error.
But,when i Install again with no account,it's working like usually.

### Device Environment

Realme 8 Pro
Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by RVXuser** [comment]
Youre using unsupported version, patch 19.16.39.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2499
