### ISSUE TITLE
bug(YouTube): Subtitles aren't centered and go outside the screen

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2513]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.16.1

### Bug description

https://github.com/user-attachments/assets/3b39e0ef-21e5-46a0-8017-c1957be8fbd2

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Irfan2700** [comment]
I checked myself on both yt revance 19.16.39 and latest yt (original app), both having this issue thats clearly indicate that its maybe from the creator uploaded caption problem. Below is the recording from yt 19.46.40 (original stock app)

https://github.com/user-attachments/assets/12fb7b7f-c8fd-40f7-b2a2-3fc62e2ee512
