### ISSUE TITLE
bug: Report of buffering issues in YouTube Music ReVanced Extended

### ISSUE THREAD

**Issue by SMOKESCREE** [inotia00/ReVanced_Extended#2516]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube Music Revanced Extended 7.17.51, 7.16.53

### Bug description

Hello ReVanced Extended Team,

First of all, I would like to thank you for the excellent work on the development and maintenance of YouTube Music ReVanced Extended. The app has been an amazing and extremely useful alternative for many users.

However, I have recently been experiencing issues related to music playback on the app. I’d like to provide the details to assist in identifying and resolving the problem:

Issue Description
When playing music, it frequently freezes, and playback is interrupted with a loading wheel displayed on the screen.
Sometimes, the music takes a long time to start, while in other instances it starts normally but freezes during playback. After a few seconds, it resumes playing, but I notice that the audio quality slightly worsens after that.
The issue occurs on both Wi-Fi and mobile data, and my internet connection is stable for other streaming apps.
Device and Configuration
Device Model: Xiaomi Redmi A2
Operating System: Android 13 Go Edition (MIUI 14)
App Version: I tested versions 7.16.53 and 7.17.51, and the issue persists on both.
MicroG: Updated to the latest version available on GitHub.
Actions Attempted Without Success
Reinstalled YouTube Music ReVanced Extended and MicroG.
Cleared app data and cache, as well as MicroG data.
Tested different audio quality settings.
Switched between Wi-Fi and mobile data, but the issue persists on both.
Verified available storage and memory, and my device has enough resources to run the app.
Considerations
I believe the issue might be related to the app’s buffering, especially during music streaming. Despite testing various app versions, I couldn’t resolve the issue. It’s worth mentioning that other ReVanced apps (such as YouTube ReVanced Extended) work perfectly on the same device.

I would like to know if there are plans to address this issue or if there’s anything else I can try to fix it. I’m available to provide additional information or perform tests if needed.

Thank you in advance for your hard work and for considering my feedback!

Best regards,

### Device Environment

Xiaomi Redmi A2, Android 13 Go Edition, MIUI 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Possibly related to https://github.com/inotia00/ReVanced_Extended/issues/2484

Try patching  6.20.51 - 6.51.53 (see [this comment](https://github.com/inotia00/ReVanced_Extended/issues/2484#issuecomment-2481616226))

**Comment by SMOKESCREE** [comment]
I installed version 7.13.52 and it is working correctly.
Versions 7.17.51 ​​and 7.16.53 have the buffering problem.

**Comment by SMOKESCREE** [comment]
Versions 6.20.51 and 6.51.53 also have a buffering problem.
