### ISSUE TITLE
bug(YouTube - Hide layout components): Hiding items in the Settings menu is not working

### ISSUE THREAD

**Issue by BugreporterXX** [inotia00/ReVanced_Extended#2518]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.16.39
RVX Manager 1.23.4
Patches 5.0.1

### Bug description

After patching 5.0.1 I noticed how hiding items in the Settings menu is not working, I uninstalled YouTube, then reinstalled. Didnt import settings, but toggled them one by one just to make sure that the imported file doesnt cause any corruptions.

Screenshot (I hid all the items except ReVanced Extended, but items are not hiding)

![Screenshot_20241208_140407_RVX YouTube](https://github.com/user-attachments/assets/c35dc44e-2a72-4635-8837-094beb21f9c8)

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by andylee516** [comment]
me too

**Comment by inotia00** [comment]
fixed in [revanced-patches-5.0.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.0.2)
