### ISSUE TITLE
feat(patch): Remove cast to TV banner on album art

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#252]
### Application

YouTube Music

### Issue

If we're playing a song in the premises of a TV that supports cast, the YT Music latest version shows a banner to do so on top of the album art.
![Screenshot_20230212-184039~2](https://user-images.githubusercontent.com/117499019/218313180-fe633662-7a0d-4563-ab99-f0e432302a6a.png)

### Patch

A patch to remove said banner from YT Music.

### Motivation

It's quite unnecessary as if we really want to cast we already have an option present in the same screen. Why the forceful casting from YouTube's side.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.190.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.8)
