### ISSUE TITLE
question: This version (patch-5.0.1.rvp) does not patch with the CLI.

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#2520]
### Application

YouTube

### Question description

How to patch this (patch-5.0.1.rvp)
[patch_log.txt](https://github.com/user-attachments/files/18052286/patch_log.txt)
 version with CLI?
Please share patch guide..

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Revancify doesn't support my source yet

Use RVX Manager or rvx builder

**Comment by hphp22f** [comment]
> Revancify doesn't support my source yet
> 
> Use RVX Manager or rvx builder

okay Dear, thanks

**Comment by Adity1243** [comment]
> Revancify doesn't support my source yet
> 
> Use RVX Manager or rvx builder

Lol, and decipher saying its rvx developr issue and fixed by rvx developer isnt a revancify issue🤷

**Comment by nick-77** [comment]
> > Revancify doesn't support my source yet
> > 
> > Use RVX Manager or rvx builder
> 
> Lol, and decipher saying its rvx developr issue and should fixed by rvx developer, this isnt a revancify issue🤷

It's fixed now, if you're still facing issue check revancify developer's suggestion in official revancify telegram group
