### ISSUE TITLE
bug: Youtube music black screen problem 

### ISSUE THREAD

**Issue by ahmetyasinakturk** [inotia00/ReVanced_Extended#2522]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube-Music-ReVanced-Advanced-v7.24.51-arm64-v8a-Patches-v2.230.0_signed

### Bug description

On Samsung phones, youtube music remains on a black screen. I've figured out why this is happening. If the "hide promotion alert" part in the ads section is active in the application, it remains on the black screen regardless of the version. If we refuse to restart when turning on and enter the settings and turn off this setting, the problem disappears. 

### Solution

The problem is solved when you come to the settings section and enter the revanced settings from there, select the ads option and turn off the hide promotion alert option from there. 

### Device Environment

Android 12 and up
OneUI4 and above. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [ ] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2515
