### ISSUE TITLE
bug(Reddit): Reddit 2024.50.0+ successfully patched but nothing is applied to the app.

### ISSUE THREAD

**Issue by 54m4d** [inotia00/ReVanced_Extended#2523]
### Type

Other

### Tools used

rvx-builder

### Application

Reddit 2024.50.0

### Bug description

Reddit 2024.50.0 is successfully patched using RVX Builder but nothing seems to be applied to the app, I checked the settings of Reddit and there is no `ReVanced Settings` even though it was included as a patch.

Reddit 2024.49.1 is tested and is not affected by this issue.

### Error logs

```shell
No errors
```

### Solution

Patch Reddit 2024.49.1

### Additional context

Excluded patches:
```
Change version code
Custom branding name for Reddit
Hide navigation buttons
```

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
Same here.

**Comment by inotia00** [comment]
ARSCLib branch will be discontinued soon

Revanced Patches branch will support the latest Reddit later this year

**Comment by 54m4d** [comment]
Good, Thanks!

**Comment by Aryan-Chauhan** [comment]
Hope you mean "ReVanced Extended patches" branch 🥺

**Comment by inotia00** [comment]
Starting with [revanced-patches-5.1.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.1), you can now patch Reddit 2024.52.0+

Closing issue
