### ISSUE TITLE
bug: can't sign in

### ISSUE THREAD

**Issue by Spaceshiprace** [inotia00/ReVanced_Extended#2524]
### Type

Error while patching

### Tools used

RVX Manager

### Application

19.16.39

### Bug description

Can't sign in, I also tried to remove microg account and then sign in again and it didn't work
![Screenshot_2024-12-08-17-41-36-763_app rvx android youtube_1_1](https://github.com/user-attachments/assets/c2285751-ce40-43b0-8481-96837172471a)

### Error logs

```shell
idk
```

### Solution

tbh idk

### Additional context

HELP

### Device Environment

android 12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by tarqallwdhy** [comment]
me too.....
i patch the same version and newer version like 19.40.42 and it's the same problem....
i can't sign in using GSMCore like I was able to.....
i think the problem is from GSMCore app because Google had changed somethings from their side.....

**Comment by tarqallwdhy** [comment]
even when I try to rull back to the version yhat I have been using 2 hours ago that I was using it for while it didn't work either. I downloaded it from the website and it has version number 19.25.39 in the website.....
shiiiiit I didn't know that will happen....

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2519
