### ISSUE TITLE
bug: (YouTube/Overlay buttons) The main feature of Time-ordered playlist doesn't work.

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#2527]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT 19.16.39

5.0.1/5.0.2

### Bug description

The main feature of the "Channel playlist button" which was incorrectly called "Time-ordered playlist" has been removed. "&list=UL" no longer works and has been replaced by 12 types of sorting.
Now it's impossible to create a channel playlist in chronological order starting with the current video to the newest one.

### Solution

Bring **&list=UL** back!

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's not a bug, it's just that the options don't include `Sort by oldest`

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.1)
