### ISSUE TITLE
feat(patch): add exception for `hide-snackbar`

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#253]
### Application

YouTube

### Issue

When I enable the Hide Snackbar it removes the annoying toast when I dislike a video, _but it also_ removes the toast "added to this playlist" which is important to me:

![Screenshot_20230212-200710106 (1)](https://user-images.githubusercontent.com/73917917/218331784-c123ba5e-9867-4e4f-9690-8f78bd000812.jpg)

Can you please add seperate Hide snackbar patch which ONLY hides the annoying snackbar for when Video is disliked, but doesn't hide other toast messages such as the added to playlist toast.
The fact that the current implementation also hides the added to playlist toast makes me not want to use it.

Really need a patch which ONLY hides this annoying toast:
![Screenshot_20230212-201519821 (1)](https://user-images.githubusercontent.com/73917917/218332101-29eb9013-8c87-40b6-bda0-76c8ce08ef2d.jpg)

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
When you add a video to a playlist, just long press the "Save to Playlist" button

**Comment by anyujinie** [comment]
Thx for letting me know about this, but I would prefer to keep the added to playlist toast and only remove the dislike toast:')

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
