### ISSUE TITLE
question: Unable to View Comments

### ISSUE THREAD

**Issue by esperanzality** [inotia00/ReVanced_Extended#2530]
### Application

YouTube

### Question description

Sometimes, I can't see the hierarchy of the comment section. Could this be a bug?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This bug is also reproduced on unpatched YouTube

**Comment by esperanzality** [comment]
ok. thank you so much.
