### ISSUE TITLE
bug: Issue with Moving the Seek Bar Up and Down

### ISSUE THREAD

**Issue by esperanzality** [inotia00/ReVanced_Extended#2532]
### Type

Error while patching

### Tools used

RVX Manager

### Application

ReVanced-YouTube-v19.34.42-arm64-v8a-cli_v5.0.1-patches_v5.1.1-dev.1

### Bug description

This happens when watching a video in full-screen mode. Instead of moving the seek bar horizontally, moving it vertically causes strange behavior.
![Screenshot_20241210_175439_YouTube](https://github.com/user-attachments/assets/6bbdaa07-3db5-4f6a-907e-f6ca9dcb782f)
In the official app, moving the seek bar upwards allows for more precise chapter selection. Could this issue be caused by having that feature turned off?

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.34.42 is still WIP
(I'm not accepting bug reports for this version at this time)

**Comment by esperanzality** [comment]
sorry ok.
