### ISSUE TITLE
bug: It's continuing to load indefinitely

### ISSUE THREAD

**Issue by gayeon59** [inotia00/ReVanced_Extended#2533]
### Type

Error while patching

### Tools used

rvx-builder

### Application

YouTube 19.20.34

### Bug description

After the video is played for about 50 seconds, it continues to load indefinitely

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [ ] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by rainman74** [comment]
YouTube 19.20.34 is not a supported version! Therefore any further comment here is unnecessary.
