### ISSUE TITLE
bug(YouTube): `Hide seek message` doesn't work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2534]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.34.42
Patches v5.1.1-dev.1

### Bug description

https://github.com/user-attachments/assets/61d6d837-8eac-4428-bdc9-1c39e30b0f61

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.34.42 is still WIP
(I'm not accepting bug reports for this version at this time)
