### ISSUE TITLE
bug: cant hide navigation bar items/ can't find navigation bar settings 

### ISSUE THREAD

**Issue by superjet1268** [inotia00/ReVanced_Extended#2535]
### Type

Other

### Tools used

RVX Manager

### Application

bug: can't find navigation bar settings on v5.0.3 patch 

### Bug description

![Screenshot_2024-12-11-00-31-10-74_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/user-attachments/assets/396664df-5fcb-4010-9f9f-d459b0c12020)

### Device Environment

Android 13 realme ui

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
include `Navigation bar components` patch

**Comment by superjet1268** [comment]
Yes i have added navigation component while i was patching the app. The YouTube version i used was 19.34.42 and i also tried to patch 19.16.39 version, in this version navigation component was available on settings

**Comment by BugreporterXX** [comment]
> Yes i have added navigation bar components while i was patching the app. The YouTube version i used was 19.34.42 and i also tried to patch 19.16.39 version, in this version navigation component was available on settings

Clear rvx manager data/cache and then update rvx manager to the latest version (1.23.5).

**Comment by superjet1268** [comment]
> > Yes i have added navigation bar components while i was patching the app. The YouTube version i used was 19.34.42 and i also tried to patch 19.16.39 version, in this version navigation component was available on settings
> 
> Clear rvx manager data/cache and then update rvx manager to the latest version (1.23.5).

I cleared data/cache it Solved the issue thanks
