### ISSUE TITLE
suggestion: The feature that allows a video title to expand to full screen by swiping down.

### ISSUE THREAD

**Issue by esperanzality** [inotia00/ReVanced_Extended#2537]
### Application

YouTube

### Suggestion description

I would like an option to disable this feature."

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
This is a feature request.
Anyway, this feature already exists. Settings > ReVanced Extended > Swipe controls > Enable watch panel gestures, OFF. 
Note that it is an experimental feature. Also if you don't see this option, repatch and include the Swipe Controls patch,

**Comment by esperanzality** [comment]
I’m sorry. Thank you for your assistance.  

I turned off "Enable watch panel gestures," but it didn’t work.  
Perhaps I didn’t explain it well, so I’ll attach some photos.

![Uploading Screenshot_20241211_135918_YouTube.jpg…]()

**Comment by esperanzality** [comment]
![Uploading Screenshot_20241211_135918_YouTube.jpg…]()

**Comment by esperanzality** [comment]
![Uploading Screenshot_20241211_140206_Gallery.jpg…]()

**Comment by esperanzality** [comment]
For some reason, I couldn’t attach the images.  
I’m referring to the feature where swiping down on the title of the screen (before switching to full screen) allows it to go full screen in portrait mode.

**Comment by KobeW50** [comment]
> For some reason, I couldn’t attach the images. 

You need to wait until the image is uploaded before sending the message on GitHub. Its a bit janky.

> I’m referring to the feature where swiping down on the title of the screen (before switching to full screen) allows it to go full screen in portrait mode.

Actually, it doesn't either work for me. But it's an experimental flag so there is nothing that can be done (unless you want to fix it yourself in a PR)

**Comment by esperanzality** [comment]
![Uploading Screenshot_20241211_135918_YouTube.jpg…]()

**Comment by esperanzality** [comment]
![Uploading Screenshot_20241211_163516_Chrome.jpg…]()
