### ISSUE TITLE
bug(YouTube): Patching fails under certain conditions

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#2538]
### Application

YouTube

### Question description

cli - latest 5.0.1
patches - latest stable/dev
jdk - zulu 17

i use the following cli command to build
`java -jar "revanced-cli-5.0.1.jar" patch -p "patches.rvp" --exclusive -e "Change share sheet" -e "Change start page" -e "Custom branding icon for YouTube" -e "Custom Shorts action buttons" -e "Description components" -e "Disable auto captions" -e "Disable haptic feedback" -e "Disable resuming Shorts on startup" -e "Disable splash animation" -e "Enable external browser" -e "Enable open links directly" -e "Force hide player buttons background" -e "Fullscreen components" -e "GmsCore support" -e "Hide Shorts dimming" -e "Hide action buttons" -e "Hide ads" -e "Hide comments components" -e "Hide feed components" -e "Hide feed flyout menu" -e "Hide layout components" -e "Hide player buttons" -e "Hide player flyout menu" -e "Hook download actions" -e "Navigation bar components" -e "Overlay buttons" -e "Player components" -e "Remove background playback restrictions" -e "Sanitize sharing links" -e "Seekbar components" -e "Shorts components" -e "SponsorBlock" -e "Swipe controls" -e "Theme" -e "Toolbar components" -e "Video playback" -e "Visual preferences icons for YouTube" --legacy-options="options.json" "youtube-v19.16.39.apk" -o "RVX.apk"`

but most patches keep failing
[patchlog.txt](https://github.com/user-attachments/files/18089710/patchlog.txt)

also the options.json file isnt read (since custom icon patch succeeded but output apk has revancify icon instead of stock icon which i specified)

am  i missing some requirement here? or my cli usage command is wrong? i cant find any solution in documentation.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is probably a bug on the patch side

If a patch is missing a dependency, this issue can occur

**Comment by sleepingiv** [comment]
> This is probably a bug on the patch side
> 
> If a patch is missing a dependency, this issue can occur

Mostly BytecodePatch is causing everything to fail.

Here's my patchlog using revancify - 
[patch_log.txt](https://github.com/user-attachments/files/18107118/patch_log.txt)

**Comment by mddanish00** [comment]
I also have the same error.

My cli command.

```
java -jar temp/inotia00-rv/revanced-cli-5.0.1-all.jar patch temp/com.google.android.youtube-19.16.39-all.apk --purge -o temp/youtube-revanced-extended-19.16.39-all-apk.apk -p temp/inotia00-rv/patches-5.0.3.rvp --keystore=ks.keystore --keystore-entry-password=XXXXXX --keystore-password=XXXXXX --signer=jhc --keystore-entry-alias=jhc -e "Theme" -e "MaterialYou" -e "Custom branding name for YouTube" -e "Custom branding icon for YouTube" -e "Custom header for YouTube" -OappIcon=MMT -OappName=RVX -e "GmsCore support" --rip-lib x86_64 --rip-lib x86
```

If I include 'Custom header for YouTube' for YouTube and  'Custom header for YouTube Music' for YouTube Music, it will set icon and also header with default value even I specify appIcon to another icon. If I don't include that patches, the icon patch will work as intended.

**Comment by MondayNitro** [comment]
the app still crashes with my patch selection on 19.16.39 (although all selected patches show succeeded and options.json is now being read)
`Change share sheet, Change start page, Custom branding icon for YouTube, Custom Shorts action buttons, Description components, Disable auto captions, Disable haptic feedback, Disable resuming Shorts on startup, Disable splash animation, Enable external browser, Enable open links directly, Force hide player buttons background, Fullscreen components, Hide Shorts dimming, Hide action buttons, Hide ads, Hide comments components, Hide feed components, Hide feed flyout menu, Hide layout components, Hide player buttons, Hide player flyout menu, Hook download actions, Navigation bar components, Overlay buttons, Player components, Remove background playback restrictions, Sanitize sharing links, Seekbar components, Shorts components, SponsorBlock, Swipe controls, Theme, Toolbar components, Video playback, Visual preferences icons for YouTube`

i tried with half of the patches and then the other half, but it was still crashing
heres the log    [rvx_logcat_12-18-2024_11-24-43.txt](https://github.com/user-attachments/files/18175840/rvx_logcat_12-18-2024_11-24-43.txt)

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.1)
