### ISSUE TITLE
bug: `hide shorts player subscribe button` does not work

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#254]
### Type

Error at runtime

### Application

Version 18.05.35

### Bug description

When I tap to pause a Short a popup "Abos" shows up on the top left for some reason. Abos(German) means subscriptions.
Can you please look into it and remove it? Shouldn't show when Short is paused.
Here you can see the issue:
https://streamable.com/mqc1cr

### Steps to reproduce

Play a Short
Pause Short
Abos / Subscriptions shows on top left

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Is this issue still present or has it been resolved?

**Comment by anyujinie** [comment]
> Is this issue still present or has it been resolved?

![Screenshot_20230225-165150831 (1).png](https://user-images.githubusercontent.com/73917917/221366505-74cda291-1bd6-47ac-a765-792869735092.png)

If you disable this patch it persists

**Comment by ILoveOpenSourceApplications** [comment]
That's the patch that's supposed to do what you had an issue with right. So that means the bug is solved?

**Comment by anyujinie** [comment]
> That's the patch that's supposed to do what you had an issue with right. So that means the bug is solved?

Why are you commenting on all my bug reports? What's your issue?

**Comment by inotia00** [comment]
Does the issue still persist in the latest release?
