### ISSUE TITLE
Support for versions of YT music higher than 7.16.53

### ISSUE THREAD

**Issue by Karthik-Subbu** [inotia00/ReVanced_Extended#2540]
### Application

YouTube Music

### Suggestion description

In light of recent update nags on yt music versions which were released only a couple of months ago, this request is made for supporting for higher versions of yt music.  Critical patches like hide ads, sponsor blocks are failing in latest versions. Hence as described by you in https://github.com/inotia00/ReVanced_Extended/issues/2382 , hide action bar components, return YouTube dislike and few other layout related patches alone shall be version constrained and version support shall be expanded for others.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Superseded by https://github.com/inotia00/ReVanced_Extended/issues/2554
