### ISSUE TITLE
bug: (Shorts Component) - Showing Jumbled Characters in Channel name

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2541]
### Type

Other

### Tools used

RVX Manager

### Application

Latest Pre Support.

### Bug description

https://github.com/anddea/revanced-patches/issues/880

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The `Return YouTube Channel Name` setting is an Experimental Flags
