### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2542]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube 19.34.42

### Bug description

Options are not included in the app

### Error logs

```shell
-
```

### Solution

-

### Additional context

java -jar revanced-cli.jar patch YTM7.16.53.apk -o y.apk -O options.json -p patches.rvp --rip-lib=x86 --rip-lib=x86_64 --rip-lib=armeabi-v7a -e "Hide overlay filter" -e "Custom branding icon for YouTube Music" -e "Custom branding name for YouTube Music" -e "Hide overlay filter" -e "Custom header for YouTube Music" -f

### Device Environment

-

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by BugreporterXX** [comment]
#2538

**Comment by inotia00** [comment]
The command to input the options.json file has changed in CLI 5.0+

The options.json file used in ReVanced Patches 4.x or earlier is no longer compatible with ReVanced Patches 5.0+

You can generate an options.json compatible with ReVanced Patches 5.0+ with the following command:

```
java -jar revanced-cli.jar options patches.rvp
```

You can specify options.json when patching with the following command:

```
java -jar revanced-cli-all.jar patch \
 -p patches.rvp \
 --legacy-options=options.json \
 -o revanced-extended.apk \
 youtube.apk
```

for more info, refer the [docs](https://github.com/inotia00/revanced-documentation/blob/main/docs/revanced-cli.md#non-root-installations)
