### ISSUE TITLE
Exporting the keystore from rvx manager and using it in rvx builder not working

### ISSUE THREAD

**Issue by shifoc** [inotia00/ReVanced_Extended#2543]
### Type

Error while patching

### Tools used

rvx-builder

### Application

All of them

### Bug description

When I replaced revanced.keystore with the one exported from rvx manager the patching stays loading forever

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unlike RVX Manager, rvx builder does not yet implement features like keystore import / export keystore, set keystore aliagn (and password
