### ISSUE TITLE
bug(YouTube): 1080 premium video quality no longer working for YT premium user

### ISSUE THREAD

**Issue by Kantotero** [inotia00/ReVanced_Extended#2544]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

RVX 19.16.39

### Bug description

I updated to the latest version and tried watching like usual. While I have a premium the 1080 premium option would work after watching videos if I have installed RVX. Now ofc it works in vanilla app but in RVX it no longer works. I disabled spoof streaming when I'm on premium because it usually works just fine but now it changed, the 1080p premium no longer pops out.

![Screenshot_2024-12-12-12-04-34-608](https://github.com/user-attachments/assets/74aed5bb-e5e3-4d46-a85c-0c1b3d7a3ee9)
![Screenshot_2024-12-12-12-05-11-086](https://github.com/user-attachments/assets/608c6ac3-86a9-4fb5-afb2-31beb07b65b3)
_the vanilla app where 1080p premium is present & the video bitrate's (356 vp9) difference is significant_

![Screenshot_2024-12-12-12-04-55-448](https://github.com/user-attachments/assets/f2b2ec0c-13ef-4099-9b43-149b8a5e6ebf)
![Screenshot_2024-12-12-12-05-20-541](https://github.com/user-attachments/assets/06feff5e-d241-4032-bbd0-7d0e5e7f5882)
_in RVX there's no 1080p premium option for the quality menu & video bitrate is lowered & reset to default (248 vp9)_

[_**Sample link for 1080p premium:**_ ](https://youtu.be/e1gs0G_7ZTc)

### Solution

I tried removing the spoof streaming data before patching and/or disabling it in the settings but the 1080p premium option doesn't return.

Android 11

_No response_

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![Flyout](https://github.com/user-attachments/assets/6e6a034e-abcf-4487-9272-41ac5677ae0c)

Are you sure the `Hide 1080p Premium menu` is turned off?

**Comment by Kantotero** [comment]
> 
> ![Flyout](https://github.com/user-attachments/assets/6e6a034e-abcf-4487-9272-41ac5677ae0c)
> 
> Are you sure the `Hide 1080p Premium menu` is turned off?

Thanks, my bad it was my fault I hid it. But there's a new problem now. [When trying to use 1080p premium I get playback issues and the quality turns to 360p](https://www.dropbox.com/scl/fi/59jeymetc7peaq765pngh/playback-issue-Yt-1080p-premium.mp4?rlkey=6187szzagvwebvu0o4h54j5i8&st=dsvdmxdq&dl=0) and it becomes unwatchable. That's where `spoof stream data` comes into play but now the 1080p premium will be gone if I turn it on.

**Comment by YT-Advanced** [comment]
> Thanks, my bad it was my fault I hid it. But there's a new problem now. [When trying to use 1080p premium I get playback issues and the quality turns to 360p](https://www.dropbox.com/scl/fi/59jeymetc7peaq765pngh/playback-issue-Yt-1080p-premium.mp4?rlkey=6187szzagvwebvu0o4h54j5i8&st=dsvdmxdq&dl=0) and it becomes unwatchable. That's where spoof stream data comes into play but now the 1080p premium will be gone if I turn it on.

Can u change spoof client to `ANDROID_VR`

**Comment by Kantotero** [comment]
> Can u change spoof client to `ANDROID_VR`

The clients doesn't show the 1080p premium, I tried all 3 ios, android Tv & vr

**Comment by inotia00** [comment]
This is not an issue with RVX

I have opened an issue related to this, please read it

https://github.com/inotia00/ReVanced_Extended/issues/2384
