### ISSUE TITLE
suggestion(YouTube): Hide AI live chat summary

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2545]
### Application

YouTube

### Suggestion description

YouTube has introduced chat summary using AI to live streams. Using `live_chat_summary_banner.eml` in custom filter does hide it.

![Screenshot_20241212_110133_YouTube](https://github.com/user-attachments/assets/7cad1897-f708-4709-9b06-65af2c8dd3e0)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
https://github.com/ReVanced/revanced-patches/pull/4110

**Comment by federicogith** [comment]
> [ReVanced/revanced-patches#4110](https://github.com/ReVanced/revanced-patches/pull/4110)

Instead of suggesting, I think it would be better and quicker for inotia00 if you open a PR as you did in ReVanced

**Comment by federicogith** [comment]
> [ReVanced/revanced-patches#4110](https://github.com/ReVanced/revanced-patches/pull/4110)

Instead of suggesting, I think it would be better and quicker for inotia00 if you open a PR as you did in ReVanced, as this kind of looks like a feature request

**Comment by ILoveOpenSourceApplications** [comment]
inotia00 can merge that PR here as well as RVX is a fork of ReVanced. I need not necessarily require to open a PR for that. But if inotia00 insists I don't mind doing so.

**Comment by federicogith** [comment]
> I don't mind doing so.

All the current PRs (except the conflicting one) have been already added to the dev branch a few hours ago
Just saying that by opening a PR it's a sure thing that a feature will be added for sure and soon

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.1)
