### ISSUE TITLE
bug: Gradient loading screen doesn't work

### ISSUE THREAD

**Issue by Wojtaz0w** [inotia00/ReVanced_Extended#2547]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.34.42

### Bug description

The gradient loading screen doesn't work in the main feed. (Nor in the subscriptions tab, etc)
It works under the video player.
It used to work perfectly fine on 19.16.39
![Screenshot_20241213-080045](https://github.com/user-attachments/assets/79ba99b6-7d46-4c39-8a12-e186dd6dede9)
![Screenshot_20241213-080039](https://github.com/user-attachments/assets/6292c384-1034-4eda-a8d6-1cd31925faeb)

### Device Environment

Android 15 QPR2 Beta 1
Google Pixel 9

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by BugreporterXX** [comment]
It works correctly on my end, try to uninstall/reinstall.

**Comment by inotia00** [comment]
YouTube 19.34.42 is still WIP

Bug reports for YouTube 19.34.42 will not be accepted until it is merged into the main branch

Just use YouTube 19.16.39
