### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Sajid1500** [inotia00/ReVanced_Extended#2549]
### Type

Error while patching

### Tools used

Revancify

### Application

All version 

### Bug description

Downloads not working
`
![Screenshot_2024-12-13-16-09-32-743_com termux](https://github.com/user-attachments/assets/91d2c54a-e145-4c5c-a1c7-3040b5cec591)
`

### Device Environment

Hyperos eu 1.0.7.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I am not a maintainer of Revancify

Open an issue here

https://github.com/decipher3114/Revancify/issues
