### ISSUE TITLE
bug: (YouTube/Player) Info cards don't work properly.

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#2550]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39

4.16.1–5.1.1-dev1

### Bug description

1. Tap on info card in the upper right corner of the screen.
2. The description of the current video opens instead of the info card.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please report back if the issue is reproducible even when the `Description components` patch is excluded

**Comment by s7san007** [comment]
This issue is reproducible on stock YouTube.
YouTube has changed the behaviour of info cards.
Now tapping on the info card will open the description of the current video and at the bottom will be a preview of the video from the info card.
