### ISSUE TITLE
feat(YouTube Music): Support version `7.25.52`

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#2554]
### Application 

YouTube Music 

### Feature description 

**This is not a feature request, but a description of the feature that will be introduce in the next release.** 

I previously rolled back the support version of YouTube Music to `7.16.53` for [this reason](https://github.com/inotia00/ReVanced_Extended/issues/2382). 

![outdated](https://github.com/user-attachments/assets/71fccbbe-4bf2-4ede-8bf3-1c6aec864bd2) 

About a month ago, Google started showing a banner to users of YouTube Music `7.24.51 or earlier` urging them to update. 

(This banner is hidden within about 1 second after the banner is shown due to the `Hide ads` patch.) 

So I have been preparing support for YouTube Music `7.25.52` for a month. 

I have confirmed that in YouTube Music `7.25.52`, the action bar has been converted to a full litho component, and fortunately, it has a ComponentTree that is almost identical to YouTube. 

So I was able to still implement most of my patches in YouTube Music `7.25.52`. 

### The following patches are no longer available or have changed behavior due to the changes in YouTube Music `7.25.52`: 

**Patch: `Hide action bar components`, Setting: `Hide action button labels`**
: The action bar in YouTube Music `7.25.52` is now structured almost identically to YouTube’s action bar. 

You can no longer hide the action bar label the way you did in YouTube Music `7.16.53`. 

**Patch: `Hide action bar components`, Setting: `Hide action buttons`**
: The action bar in YouTube Music `7.25.52` now has a nearly identical structure to YouTube's action bar, so https://github.com/inotia00/ReVanced_Extended/issues/17 is reproduced in YouTube Music `7.25.52`+. 

**Patch: `Hide action bar components`, Setting: `Override Download action button`**
: Starting with YouTube Music `7.25.52`, this feature is available only to Premium users.

This feature is available only on YouTube Music `7.16.53`.

**Patch: `Player components`, Setting: `Remember shuffle state`**
: Starting with YouTube Music `7.25.52`, the server rejects shuffle requests sent before the track starts. 

(Now, `Always shuffle` can be applied 1 second after the track starts.) 

While `Always shuffle` is still applied immediately in YouTube Music `7.16.53`,
YouTube Music `7.25.52` applies `Always shuffle` 1 second after the track starts. 

**Patch: `Spoof app version`, Setting: `Spoof app version`**
: Google has removed code related to the old-style action bar in YouTube Music `7.25.52`. 

So if you spoof the app version from YouTube Music `7.25.52` to `7.24.51 or earlier`, you will lose the action bar. 

For this reason, the recommended version of the `Spoof app version` patch is restricted to `7.16.53`. 

### Motivation 

![outdated](https://github.com/user-attachments/assets/71fccbbe-4bf2-4ede-8bf3-1c6aec864bd2) 

Since the banner asking for an update is still visible, it seems likely that the YouTube Music API will change 'soon', so I added support for YouTube Music `7.25.52`. 

**Personally, if you don't have any major issues with it, I would still recommend staying on YouTube Music `7.16.53`.** 

### Acknowledgements 

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.1)

**Comment by aayushrautela** [comment]
Does it implies that no support for hooking the download button to an external app?

**Comment by ILoveOpenSourceApplications** [comment]
Will there be an unofficial bump to all the other patches to the last version of 2024?

**Comment by Idmbc** [comment]
It's okay dude Thank you for your hard work

**Comment by sliceanddice9** [comment]
[inotia00](https://github.com/inotia00) do you know any Custom Filters to individually remove **Playlists**, **Songs**, **Albums** and **Artists** from the category bar within library? I know that I can simply enable the 'Hide Category Bar' in YouTube Music ReVanced Extended settings but I want to keep the **Podcasts** button on-screen within library.
