### ISSUE TITLE
bug(YouTube Music): Crashes immediately on start

### ISSUE THREAD

**Issue by Lassie111** [inotia00/ReVanced_Extended#2555]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube Music v7.16.53
Patches v5.0.3

### Bug description

Yesterday worked normally, today crashes every time on start. Root install. Reboot did not fix it. 

### Error logs

[ytm-logs.txt](https://github.com/user-attachments/files/18157007/ytm-logs.txt)

### Device Environment

Android 14 magisk patched

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The debug log just says that the exception occurred because the settings could not be initialized

Please exclude the patches one by one and report back which patch is causing the issue

**Comment by Lassie111** [comment]
> The debug log just says that the exception occurred because the settings could not be initialized
> 
> Please exclude the patches one by one and report back which patch is causing the issue

Tried without "Spoof client" but still crashes. Patched with older patches since I don't have to binary search now. Will probably do it when I have some free time.

**Comment by Lassie111** [comment]
It was not caused by the patches.
It was a problem with the RVMM builder: https://github.com/j-hc/revanced-magisk-module/issues/545
I didn't see it earlier cause it is already fixed and closed. Had to merge it in my clone though. I'm sorry for the inconvenience!
