### ISSUE TITLE
bug: Subscriptions button is not clickable through subs carousel

### ISSUE THREAD

**Issue by smed79** [inotia00/ReVanced_Extended#2557]
### Type

Other

### Tools used

RVX Manager v1.23.5

### Application

ReVanced Patchs v5.5.1-dev.1
YouTube v19.34.42

### Bug description

Click a channel icon in subscriptions carousel.
Click the Subscriptions button in navigation bar.

➞  The subscriptions button is not clickable.

Ss 
- https://i.ibb.co/T44w8pZ/subscriptions-button.jpg

### Error logs

[logcat_12-17-2024_01-51-20.zip](https://github.com/user-attachments/files/18159039/logcat_12-17-2024_01-51-20.zip)

### Device Environment

Android 14.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.34.42 is still WIP

Bug reports for YouTube 19.34.42 will not be accepted until it is merged into the main branch

Just use YouTube 19.16.39

**Comment by smed79** [comment]
Same issue with 
YouTube v19.16.39
Patches v5.0.3

([2558#issuecomment-2552640712](https://github.com/inotia00/ReVanced_Extended/issues/2558#issuecomment-2552640712))

**Comment by inotia00** [comment]
This issue is reproducible even on unpatched YouTube 19.16.39
So this is an issue that Google needs to fix
