### ISSUE TITLE
bug(YouTube - Hide feed components): Community post are not hidden through subs carousel

### ISSUE THREAD

**Issue by smed79** [inotia00/ReVanced_Extended#2558]
### Type

Other

### Tools used

RVX Manager v1.23.5

### Application

ReVanced Patchs v5.0.3
YouTube v19.16.39

### Bug description

Hide all community posts.
Go to subscriptions page.
Click a channel icon in subscriptions carousel.

 ➞  Community posts are not hidden.

Ss 
- https://i.ibb.co/Kqn3wdw/community-posts-settings.jpg
- https://i.ibb.co/K5rXHym/community-post.jpg

### Error logs

_Removed_

### Device Environment

Android 14.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.34.42 is still WIP

Bug reports for YouTube 19.34.42 will not be accepted until it is merged into the main branch

Just use YouTube 19.16.39

**Comment by smed79** [comment]
I have used what was suggested by rvx manager.

![yt requested version](https://github.com/user-attachments/assets/41a56832-0425-4233-b5d2-3fc2349ca94e)

**Comment by inotia00** [comment]
turn off `Use pre-release` toggle

**Comment by smed79** [comment]
I patched  YouTube v19.16.39 with rvx Patches v5.0.3 using Manager v1.23.5 and i get the same results.

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.1)

**Comment by smed79** [comment]
Thank you.

**Comment by smed79** [comment]
Subscriptions carousel are hidden with tablet layout (experimental flags).

This is :point_up: not a bug report, but just to inform you.

Thank you.
