### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Juanpaxt** [inotia00/ReVanced_Extended#256]
### Type

Other

### Application

YouTube 18.04.35v

### Bug description

when playing a video it gets stuck between 8 and 10 seconds

### Steps to reproduce

Only one video should be played so that in my case, it gets stuck at 8 seconds 

### Relevant log output

```shell
I don't know how to find and fill in this box
```

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
