### ISSUE TITLE
bug: (YouTube) Enable Wide Search Bar with header patch is broken

### ISSUE THREAD

**Issue by BugreporterXX** [inotia00/ReVanced_Extended#2560]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.38.41
RVX Manager 1.23.5
Patches 5.1.1 dev 2

### Bug description

After patching 5.1.1 dev 2 I noticed how the Premium logo gets hidden while Wide Search Bar is active, 5.1.1 dev 1 didnt have this issue. I uninstalled and reinstalled, didnt help.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Bug reports for dev will not be accepted until it is merged into the main branch

**Comment by smed79** [comment]
I patched  YouTube v19.16.39 with rvx Patches v5.0.3 using Manager v1.23.5 and i get the same results.
