### ISSUE TITLE
bug: Buffering and Audio Quality Issues in YouTube Music ReVanced Extended

### ISSUE THREAD

**Issue by SMOKESCREEN2** [inotia00/ReVanced_Extended#2561]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube Music Revanced Extended:
Version  7.16.53
Services Microg:
Version 0.3.1.4.240913-hw

### Bug description

Description:
YouTube Music ReVanced Extended currently has serious buffering and audio quality issues when playing music. When starting a song, two problematic scenarios can occur:

The music freezes at first, loading for a long time, and only then starts playing with degraded audio quality.
The music starts normally, but then it starts loading slowly and, when it returns, the audio quality is lower than expected.

Tests performed:

I realized that this problem is not related to my internet connection, as on stable and fast networks the problem persists.
I tested it on the official YouTube Music app, where there was no buffering or audio quality issue.
Reinstalling YouTube Music ReVanced Extended and MicroG Service does not resolve the issue, indicating that the source is in the modified application itself.
Expected behavior:
Songs should start playing instantly, with the correct audio quality and without interruptions throughout playback, similar to the behavior of the official app.

Current behavior:
User experience is impaired due to long loading times and degraded audio quality, even under normal network and device conditions.

Additional notes:

Device: Xiaomi Redmi A2 (Android 13 Go Edition MIUI 14)

### Solution

I hope this issue can be fixed in a future update as it is compromising the user experience.

### Device Environment

Xiaomi Redmi A2 Android 13 Go Edition MIUI 14 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
duplicated with https://github.com/inotia00/ReVanced_Extended/issues/2484
