### ISSUE TITLE
bug: Audio track button.

### ISSUE THREAD

**Issue by jalisonsousa** [inotia00/ReVanced_Extended#2562]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v.16.30.39

### Bug description

Audio track button It doesn't appear in the video player. Some videos I watch are in English and I can't change the language. This is only happening in revanced.
Even with the audio track option to be displayed active. The button does not appear 

### Solution

Fix the error to display the audio track in videos 

### Device Environment

Android 14, hyperOS, poco f3

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [ ] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
You are using an unsupported version
