### ISSUE TITLE
bug: (YouTube Revanced) Player full screen ambient mode is not working

### ISSUE THREAD

**Issue by sandy5544** [inotia00/ReVanced_Extended#2563]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube revanced 19.38.41

### Bug description

Player full screen ambient mode is not working even though bypass ambient mode restrictions enabled.

attached the screenshot. 
![Screenshot_20241217-203913](https://github.com/user-attachments/assets/68b0276a-f49f-407f-8b83-cb51dbade425)
![Screenshot_20241217-203855](https://github.com/user-attachments/assets/44c213c5-5e76-4789-a1e6-c38cd96fc385)

### Device Environment

Android 15, Pixel android 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Bug reports for dev will not be accepted until it is merged into the main branch
