### ISSUE TITLE
question: overheating

### ISSUE THREAD

**Issue by esperanzality** [inotia00/ReVanced_Extended#2564]
### Application

YouTube

### Question description

Are there any overheating issues? It feels like it gets warmer compared to using the official app.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
No, there is no such issue

Make sure if you have patched it correctly according to the [docs](https://github.com/ReVanced-Extended-Community/Community-Guides/blob/main/community-wiki/guide-for-beginners.md)
