### ISSUE TITLE
bug(YT/Shorts Component): Showing string name instead of Actual name in custom toolbar

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2565]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Latest Dev Supported

### Bug description

Custom toolbar with dabbe useful actions showing string name instead of the actual name. Check this: 
![Screenshot_20241217_214017](https://github.com/user-attachments/assets/b1ada806-dc98-4f6c-b2c3-7f10e93a8633)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
@inotia00 maybe there can be an Acknowledgements before making bug reports so people dont open them for the dev branch
