### ISSUE TITLE
bug: Wide Search Bar with YouTube Header

### ISSUE THREAD

**Issue by sr-shishir** [inotia00/ReVanced_Extended#2566]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.38.41

### Bug description

Basically couple of bugs I faced.

1. **Wide search bar with YouTube header** not working.
2. **The splash animation** also not working with icons. 
3. **Hide next & previous buttons** not hiding them.

![IMG_20241218_000705](https://github.com/user-attachments/assets/ea16e43d-e6b0-4341-ae86-5e1e8626e30a)

### Device Environment

Android 14 on HYPEROS

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by BugreporterXX** [comment]
I reported issue 1 earlier.

Also, hiding floating mic is not working.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2560
