### ISSUE TITLE
bug: rvx music doesnt load songs

### ISSUE THREAD

**Issue by zrx3** [inotia00/ReVanced_Extended#2569]
### Type

Other

### Tools used

RVX Manager

### Application

RVX Music v7.17.51

### Bug description

Songs don't load, they rarely do after like 20 seconds

### Error logs

```shell
Doesn't show any errors in logcat...
```

### Solution

Well... the only solution i found is enabling the "Spoof app version", spoofing to "4.27.53" (works for a bit but then does it again)

### Device Environment

Android 14 / MagicOS 8.0.0.232 (C430E5R2P2) / HONOR Magic6 Lite

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [ ] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2484
