### ISSUE TITLE
bug: "Take a break" malfunction

### ISSUE THREAD

**Issue by x33st0rm** [inotia00/ReVanced_Extended#257]
### Type

Other

### Application

18.05.35

### Bug description

"Remind me to take a break" after X time, does not work as intended. Nor in earlier versions.

It should halt video, prompt for you to continue watching, and then make the app and fullscreen video go to sleep.

It halts the video, waits until screen timeout and then turns video black while audio continues.

### Steps to reproduce

Turn it on from Settings > General. Should be top entry.

It was also broken in all earlier versions i've tried.

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Is it working just as intended in stock YouTube like you mentioned?

**Comment by ILoveOpenSourceApplications** [comment]
I have to disagree as I tried it out and it's functioning properly just like you mentioned.

**Comment by ILoveOpenSourceApplications** [comment]
Can you list all the patches that you've applied?

**Comment by inotia00** [comment]
No support for prebuilt apk
