### ISSUE TITLE
bug(YouTube Music - SponsorBlock): `Change segment behavior` and `About` sections are hidden in the settings

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2575]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT Music 7.16.53
Patches v5.0.3

### Bug description

In the SponsorBlock settings, all of the settings for changing segment behaviors, as well as the About section, are hidden. The segment behavior is therefore impossible to configure.

<img src="https://github.com/user-attachments/assets/d498db76-20de-402f-82db-cf20f9ee46c7" width=400>

### Patch logs

```shell
- Device Info
RVX Manager: 1.23.4
Model: SM-S906U1
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v7.16.53 (Suggested: 7.16.53)
Patches version: v5.0.3
Patches added: Default
Patches removed: None
Default patch options changed: Custom branding icon for YouTube Music [App icon: mmt], GmsCore support [Package name of YouTube Music: com.rvx.android.apps.youtube.music]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Remove unused library: true
Use pre-release: false
Patches source: inotia00/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 34 patches
Compiling modified resources
Aligning APK
Signing APK
Patched APK
```

### Device Environment

Android 14. 
OneUI 6.1
Samsung S22+

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.1)
