### ISSUE TITLE
Playing stops after one song

### ISSUE THREAD

**Issue by oleglucic** [inotia00/ReVanced_Extended#2576]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Music 7.16.53

### Bug description

After the song stops playing, the next one doesn't autoplay, but repeat button appears.

### Device Environment

OneUI 6.1 (Android 14)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Have you tried using a `Spoof client`?
