### ISSUE TITLE
question: was "Restore old seekbar thumbnails" removed?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2578]
### Application

YouTube

### Question description

I can't find the option "Restore old seekbar thumbnails" in the settings anymore
Was it removed in patches v5.1.1?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Restore old seekbar thumbnails` setting is deprecated in YouTube 19.17.41+

(Google removed the source code)

If you want it, you'll need to patch YouTube 19.16.39
