### ISSUE TITLE
feat(patch): remove double tap overlay

### ISSUE THREAD

**Issue by tb115** [inotia00/ReVanced_Extended#258]
### Application

YouTube

### Issue

When double tapping to skip 10 seconds the video briefly darkens. Enabling 'remove player button background' does not remove the player background when double tapping to skip. Another patch can add in this feature. Thanks for considering.

### Patch

![Removedarkeningproposal](https://user-images.githubusercontent.com/108863839/218640931-3566a93d-1601-4a92-9726-384839af52bc.jpg)

### Motivation

This patch will nicely compliment the 'remove player button background' patch. This will make the player experience more consistent.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
The patch you mentioned serves a different functionality. "Remove player button background" removed the dark circles behind the prev-pause/play-next buttons. The patch you're talking about is "hide player overlay filter".

**Comment by tb115** [comment]
Yes, my mistake. I have both the hide player overlay filter as well as the remove player background button enabled. Just to reitterate double tapping to skip still darkens entire video.

**Comment by ILoveOpenSourceApplications** [comment]
Yeah looks like so. I'm pretty sure inotia00 will look into it and fix it eventually.

**Comment by s7san007** [comment]
@inotia00 
Removing dark and foggy overlay filters on tap to seek (FF & RW)
File - res/layout/quick_seek_overlay.xml
Code:
```<com.google.android.libraries.youtube.player.features.quickseek.overlay.CircularClipTapBloomView
>         android:id="@id/tap_bloom_view"
>         android:focusable="false"
>         android:visibility="gone"
>         android:layout_width="0.0dip"
>         android:layout_height="0.0dip"
>         android:contentDescription="@null"
>         app:endColor="@color/quick_seek_bloom_end"
>         app:startColor="@color/quick_seek_bloom_start" />
>     <ImageView
>         android:id="@id/dark_background"
>         android:visibility="gone"
>         android:layout_width="0.0dip"
>         android:layout_height="0.0dip"
>         android:src="@color/dark_transparent" />
```
Before:
![Screenshot_20230409_162641_YouTube](https://user-images.githubusercontent.com/130248949/230777069-5a4d277e-7d4e-4a61-bed2-9321f0304994.png)
After:
![Screenshot_20230408_232621](https://user-images.githubusercontent.com/130248949/230777138-1c593e5b-89f6-4478-b80f-2d4658bcf138.png)

Please, add a toggle (patch) for removing that filter.

**Comment by inotia00** [comment]
thank you
but this method seems impossible to control through settings

**Comment by tb115** [comment]
> thank you
> but this method seems impossible to control through settings

Can you elaborate on it "being impossible to control". As a long time youtube mobile user it is muscle memory to double tap to skip. If i am watching a video with lots of writing (math tutorial) i dont want to miss out on anything die to the darkening.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)

**Comment by anyujinie** [comment]
Wow this is great. Now the overlay filter is even removed when tapping on the screen. Thx to OP for bringing this up and Inotia for implementation 👌🏻

**Comment by Spacellary** [comment]
Thanks for the quick work, Inotia!

**Comment by inotia00** [comment]
> Wow this is great. Now the overlay filter is even removed when tapping on the screen. Thx to OP for bringing this up and Inotia for implementation 👌🏻
> 
> EDIT: @inotia00 Do I need to enable this patch? Just patched to new version and can't find it in settings. Is it enabled by default?

Due to the limitations of the patch method, it cannot be implemented as a setting UI
You have to include in the patching process

**Comment by s7san007** [comment]
@inotia00, thanks for removing dark filter, but another foggy (light blooming) filter is still visible. :(
![Screenshot_20230411_023342_ReVanced Extended](https://user-images.githubusercontent.com/130248949/231020175-70474257-3736-4ab3-b5d4-c8dc9f5a45bf.png)
Can you remove it in next patches?

**Comment by inotia00** [comment]
The double tap overlay has two filters

one is a dark overlay
The other is a white circle overlay (image you attached)

Only the patch to remove the dark overlay when double-tapping was implemented, and the patch to remove the white circular overlay was not implemented.

**Comment by Spacellary** [comment]
> The other is a white circle overlay (image you attached)

Oh I see, so that's how it works. Hopefully eventually this can be improved but I'm already thankful for this much xD
