### ISSUE TITLE
bug(YouTube - Toolbar components): `Hide voice search button` setting does not work

### ISSUE THREAD

**Issue by ghost** [inotia00/ReVanced_Extended#2580]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.44.39
RVX Manager 1.23.5
Patches 5.1.1 stable

### Bug description

Hiding voice search button is not working.

![Screenshot_20241221_121640_RVX YouTube](https://github.com/user-attachments/assets/f0dc5b2a-b0d4-411a-a438-09968e628fed)

I uninstalled and reinstalled, did not help.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
There are two different settings related to floating button and voice search button.

Floating button located at the bottom right corner & this button is voice search button you can disable it from
RVX Settings > Toolbar > Hide voice search button

**Comment by worthlesspieceofshit** [comment]
> There are two different settings : 'Hide floating button' and 'Hide voice search button' .
> 
> Floating button is located at the bottom right corner. This is voice search button in toolbar which you can disable from `RVX Settings > Toolbar > Hide voice search button`

I have it enabled:

![Screenshot_20241221_123122_RVX YouTube](https://github.com/user-attachments/assets/c9057b64-60f5-42d9-9f8b-7cd86a2a5dc1)

**Comment by selfmusing** [comment]
> > There are two different settings : 'Hide floating button' and 'Hide voice search button' .
> > Floating button is located at the bottom right corner. This is voice search button in toolbar which you can disable from `RVX Settings > Toolbar > Hide voice search button`
> 
> I have it enabled:
> 
> ![Screenshot_20241221_123122_RVX YouTube](https://private-user-images.githubusercontent.com/192420319/397921198-c9057b64-60f5-42d9-9f8b-7cd86a2a5dc1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODA4NzYsIm5iZiI6MTczNDc4MDU3NiwicGF0aCI6Ii8xOTI0MjAzMTkvMzk3OTIxMTk4LWM5MDU3YjY0LTYwZjUtNDJkOS05ZjhiLTdjZDg2YTJhNWRjMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMTI5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWFiMGVmYjYzMWVmMmQzNTFjZWE4ZjNlNGUxZDhhOGE4NDlhNDYzMDBmOTVkZDQ3NjY3MWVjMmU5NDQ2YTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SByDhWS1Tzy5dUyKLiYnZiV6ltmPaATHD_CWOxcHh10)

![Screenshot_20241221-170013_YT-RVX](https://github.com/user-attachments/assets/77358164-2497-4484-b60a-dd709c63ec1a)
![Screenshot_20241221-170027_YT-RVX](https://github.com/user-attachments/assets/12fe228e-6fa7-4041-a3de-8d194699171c)

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.2)
