### ISSUE TITLE
bug(YouTube Music): App crashes when including `Hide action bar components` patch

### ISSUE THREAD

**Issue by kljjh** [inotia00/ReVanced_Extended#2584]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Music v7.16.53

### Bug description

App crashes immediately when I start to play a music. 

https://github.com/user-attachments/assets/7209f21d-b9e9-4d76-bba3-5272ffbdb53b

### Error logs

```shell
12-21 21:38:52.856 32049 32049 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No static method inAppDownloadButtonOnClick(Landroid/view/View;)V in class Lapp/revanced/extension/music/patches/actionbar/ActionBarPatch; or its super classes (declaration of 'app.revanced.extension.music.patches.actionbar.ActionBarPatch' appears in /data/app/~~qQPLzzxt90WXXyARYTrLVQ==/app.rvx.android.apps.youtube.music-zZWuKqJyto2DSGnEH1qZSg==/base.apk!classes4.dex)
12-21 21:39:01.987 32366 32366 E AndroidRuntime: bndw: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoSuchMethodError: No static method inAppDownloadButtonOnClick(Landroid/view/View;)V in class Lapp/revanced/extension/music/patches/actionbar/ActionBarPatch; or its super classes (declaration of 'app.revanced.extension.music.patches.actionbar.ActionBarPatch' appears in /data/app/~~qQPLzzxt90WXXyARYTrLVQ==/app.rvx.android.apps.youtube.music-zZWuKqJyto2DSGnEH1qZSg==/base.apk!classes4.dex)
```

### Solution

Exclude `Hide action bar components` patch

### Additional context

It seems not happened in former version of revanced patches because I just repatched ytm today, then the error occured. Before that I use the patched ytm normally. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.2)
