### ISSUE TITLE
bug: App merges with top status bar

### ISSUE THREAD

**Issue by WsNyc00** [inotia00/ReVanced_Extended#2586]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

RVX: 19.44.39
Patches: v5.1.1

### Bug description

Top bar, where all the info, notifications icons (i think its called status bar), battery procentage, clock merges with the patched app after going into the settings from anywhere, (doesn't matter if its from "You" page or Home or any other page)
Also this happens with default RVX or Youtube settings.

1. Open patched app
2. Go to Settings page
3. Leave the settings page with back button

**Before:**

![i7dwcSk (1)](https://github.com/user-attachments/assets/abcb833f-8612-4d8d-8d21-800d04452ee5)

**After:**

![05qzs76 (1)](https://github.com/user-attachments/assets/b6f1ca0b-1777-4210-9959-d8beea83efb1)

### Solution

Changing pages for example from Home page to You, or any page restores position.

### Additional context

Only on Android 8.1.0
This doesn't happen on Android 14 and problably other versions.

### Device Environment

Android 8.1.0

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a 'new feature' that Google added to the latest YouTube

You can disable this by turning on setting:
```
Settings - ReVanced Extended - General - Disable translucent status bar
```

**Comment by WsNyc00** [comment]
> This is a 'new feature' that Google added to the latest YouTube
> 
> You can disable this by turning on setting:
> 
> ```
> Settings - ReVanced Extended - General - Disable translucent status bar
> ```
> 
> (This issue has been closed as it is reproducible even on unpatched YouTube)


Thank you, disabling translucent bar fixed the problem.
I tried replicate same issue on unpatched app but couldn't replicate on it.

**Comment by WsNyc00** [comment]
Option "Disable translucent status bar" was removed in v5.2.1-dev.1 Or its was renamed? How do i disable that translucent status bar thing now?
