### ISSUE TITLE
bug(YT/Shorts): No Seekbar and Thumbnails in Shorts

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2587]
### Type

Error while patching

### Tools used

RVX Manager

### Application

44.39

### Bug description

There is no Seekbar and Thumbnails in Shorts in latest version

https://github.com/user-attachments/assets/de863417-d746-40f5-a70c-3f6a1a2336c5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Exclude patches one by one and report back which patch causes the issue.

**Comment by vippium** [comment]
> Exclude patches one by one and report back which patch causes the issue.

Now it is working fine. It happens randomly. If happens again, will open it again.
