### ISSUE TITLE
bug: (YouTube - Player/Fullscreen) Quick Actions Top Margin setting works only if Miniplayer Type is Tablet

### ISSUE THREAD

**Issue by keekek69** [inotia00/ReVanced_Extended#2589]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.44.39
RVX Manager v1.23.5
RVX Patch v1.5.1

### Bug description

This issue is really weird, I went into the settings and changed Quick Actions Top Margin to 15 and restarted RVX, everything was fine.

Then I changed the Miniplayer Type to Modern 1 and restarted RVX. Then I noticed how Quick Actions Top Margin setting stopped working.

I then tried Modern 2 and Modern 3, the same issue occured. I then changed it back to Tablet which I had enabled when everything was fine. And Quick Actions Top Margin started working again when Miniplayer Type is set to Tablet.

So, in conclusion. When Quick Actions Top Margin setting is tampered with, it does not work with Modern 1, 2 and 3 Miniplayer Types, but it does work with Tablet mode.

### Additional context

My settings file:

[RVX YouTube_v19.44.39_2024-12-21.txt](https://github.com/user-attachments/files/18219901/RVX.YouTube_v19.44.39_2024-12-21.txt)

My patch selection:

[selected_patches_2024-12-21_22_45_07.json](https://github.com/user-attachments/files/18219910/selected_patches_2024-12-21_22_45_07.json)

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I've tested a few things after importing your settings

![Margin_32_Modern1](https://github.com/user-attachments/assets/30b543f5-5696-4be4-aac1-500030c094d1)

▲ Margin 32, Modern1 ▲

![Margin_32_Modern2](https://github.com/user-attachments/assets/bc8a12b6-1129-4153-add0-526d9a4028e0)

▲ Margin 32, Modern2 ▲

![No_Margin](https://github.com/user-attachments/assets/ecad577d-00e2-4d60-ab6a-16d4532c1515)

▲ No Margin, Phone ▲

At least for me it seems to work as intended

Please test it on YouTube 19.16.39 and report back with your results.

**Comment by keekek69** [comment]
Hmm, when I look at your screenshots it looks like the margin was not changed to 32, the margin looks exactly the same in all 3 screenshots. (Your margin looks like default margin which is 0, looks like nothing has changed)

This is how it looks on my end with 15 margin: (tablet mode)

![Screenshot_20241222_041327_RVX YouTube](https://github.com/user-attachments/assets/e8cd79ef-7a5c-4e3d-9c3b-47e799ec56f9)

Notice how it's located a lot lower than in your screenshots, that kinda confirms my theory how margin only works when miniplayer is set to tablet.

I will report you later how it goes with v19.16 39, now I need some sleep.

**Comment by inotia00** [comment]
Quick action top margins are different

I marked the lines on the image:

![Margin_32_Modern1](https://github.com/user-attachments/assets/4c3667a7-2665-47df-9a14-7598e631a45a)

▲ Margin 32, Modern1 ▲

![No_Margin](https://github.com/user-attachments/assets/0111098e-206a-4e10-9aa3-c1315fb94815)

▲ No Margin, Phone ▲

**Comment by keekek69** [comment]
The setting that you are changing is bottom margin, which you can only change in RVX Manager while patching:

![Screenshot_20241222_130023_RVX Manager](https://github.com/user-attachments/assets/6dfa2c6e-37b2-4af7-a689-541c2a75beda)

The setting what I am changing is Top Margin, which you can change in the RVX settings Player > Fullscreen > Quick Actions Top Margin:

![Screenshot_20241222_130246_RVX YouTube](https://github.com/user-attachments/assets/d4887423-5bf6-441f-8518-aebc6ffa444d)

![Screenshot_20241222_041327_RVX YouTube](https://github.com/user-attachments/assets/8efee12f-318b-49cc-a1f1-de73c9bb805f)

**Comment by inotia00** [comment]
The screenshot you attached is the patch option for `Overlay buttons`, not `Quick actions top margin`

`Quick actions top margin` can be changed in the following path:

```
Settings > ReVanced Extended > Player > Fullscreen > Quick actions top margin
```

**Comment by inotia00** [comment]
Nah.. I also changed the settings in the following path

```
Settings > ReVanced Extended > Player > Fullscreen > Quick actions top margin
```

**Comment by inotia00** [comment]
> ![Screenshot_20241222_041327_RVX YouTube](https://private-user-images.githubusercontent.com/192462465/397980670-8efee12f-318b-49cc-a1f1-de73c9bb805f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjU4MTEsIm5iZiI6MTczNDg2NTUxMSwicGF0aCI6Ii8xOTI0NjI0NjUvMzk3OTgwNjcwLThlZmVlMTJmLTMxOGItNDljYy1hMWYxLWRlNzNjOWJiODA1Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQxMTA1MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjg2NjBhNTA1MTA5NmNiYjFmZGI2YjBiMGIwN2QxN2IyZjk5MjAyMGM1MmI4MWE5YmQ4ZTNhOGQxMzQwMDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O4MejiF1HE6E7R2SKlcXhbBhmgxs6WKsg-fOTE9Im8s)

This is not a quick actions top margin, and no patches have been implemented to change this

This margin only occurs on `Tablet`, which is a known bug:

https://github.com/inotia00/ReVanced_Extended/issues/271

**Comment by keekek69** [comment]
But why it looks like in your screenshots that your top margin was not actually changed to 32? When comparing those to mine, it looks like mine was actually changed to 15 and it sits lower than yours, even though yours was set to 32.

There is somekind of a bug for sure, but finding it will be very difficult.

**Comment by inotia00** [comment]
Because the calculation of dip depends on the resolution of the device (not an absolute value)

This issue is closed because it is a duplicate or invalid issue

**Comment by keekek69** [comment]
Fair, also when I took a look of issue #271, I actually do not have the issue where title shifts down when tablet miniplayer is activated. I manually changed the setting so that I could get it a bit lower.
