### ISSUE TITLE
bug(RVX Manager): `WARNING` and `INFO` are not printed

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2590]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Reddit 2024.29.0

### Bug description

According to [this line of code](https://github.com/inotia00/revanced-patches/blob/03849073241cdee3dfa50a35fc35c3db5c9364aa/patches/src/main/kotlin/app/revanced/patches/reddit/layout/navigation/NavigationButtonsPatch.kt#L37), it seems that a warning is meant to be printed to the patch log when the `Hide navigation buttons` patch is included when patching a version newer than 2024.17.0.

This warning is not present when patching 2024.29.0.

### Error logs

```shell
- Device Info
RVX Manager: 1.23.5
Model: SM-S906U1
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.29.0 (Suggested: Any)
Patches version: v5.1.1
Patches added: Custom branding name for Reddit, Hide navigation buttons
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Remove unused library: true
Use pre-release: false
Patches source: inotia00/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 12 patches
Compiling modified resources
Ripping selected native libs
Aligning APK
Signing APK
Patched APK
Installing patched app
Installed
```

<img src="https://github.com/user-attachments/assets/f6ee72a5-704a-4f5c-99f4-724af8911bce" width=400>

### Additional context

I have not tested with a CLI-based patching tool. Let me know if I should test using revancify, rvx-builder, or the CLI.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
When patching other apps, not just Reddit, RVX Manager does not print any type of warnings

Printing warnings is a feature implemented only in RVX patches, so it is a valid issue related to RVX Manager

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.2)
