### ISSUE TITLE
Bug(Youtube): default quality getting overridden 

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#2591]
### Type

Error at runtime

### Tools used

CLI

### Application

Youtube 19.44.39

### Bug description

This is an old back that has returned. When setting an video quality (like 2160p) as a default, after watching few videos with different qualities, the quality get set to 480p and stays there.

### Additional context

This bug was already present in the past, but was fixed. And now it has returned. 

### Device Environment

Android 15

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue has been reported too many times already and is reproducible on unpatched YouTube, so I'm closing this issue

See https://github.com/inotia00/ReVanced_Extended/issues/1730#issuecomment-1826286065 for more information
