### ISSUE TITLE
bug(Youtube - spoof streaming data) : videos stop loading after 1 minute on the runtime if set to ios

### ISSUE THREAD

**Issue by Arin-hana** [inotia00/ReVanced_Extended#2593]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube v19.44.39

### Bug description

Videos wouldn't load after 1 minute of runtime if spoof streaming data set to ios
But when using a vpn it works, i dont know if its my internet provider or google is testing something

Steps to reduce
Settings -> ReVanced extended -> miscellaneous -> spoof streaming data -> set default client to ios

Applied patches
- Custom Shorts action buttons
- Disable QUIC protocol
- Disable resuming Shorts on startup
- Enable external browser
- Enable open links directly
- Hide ads
- Hook YouTube Music actions
- Hook download actions
- Layout switch
- MaterialYou
- Miniplayer
- Navigation bar components
- Player components
- Remove background playback restrictions
- Return YouTube Dislike
- Return YouTube Username
- Sanitize sharing links
- Seekbar components
- Settings for YouTube
- SponsorBlock
- Spoof app version
- Spoof streaming data
- Swipe controls
- Toolbar components
- Video playback
- Visual preferences icons for YouTube

### Solution

Set spoof streaming data to other than ios

### Additional context

Using patches v5.1.1, though its been happening since 2 days ago

### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The same issue was opened in the ReVanced repository yesterday

I haven't been able to reproduce the issue yet, so this is probably still A/B tests

![ReVanced](https://github.com/user-attachments/assets/5d27cea8-cdb1-4d2f-bf05-774cbb335330)

▲ ReVanced ▲

The ReVanced Team has done the following:
1. Default client type has been changed to `Android VR`
2. `iOS` has been removed from the selectable client types
3. `Default client` setting has been removed

RVX will eventually follow the ReVanced Team's changes, but not right now

![Android_Clients_Only](https://github.com/user-attachments/assets/38d18caa-b4fc-4496-8bea-7d2e95817629)

▲ RVX (Next Release) ▲

In the next release of RVX..
1. Default client type will change to `Android VR`
2. `iOS TV` will be added to the selectable client types (cannot play movies or paid videos)
3. `Use Android clients only` setting will be added (enabled by default)

**Comment by Arin-hana** [comment]
Alright 
Should i close this or keep it open?

**Comment by inotia00** [comment]
Since there may be users who come here with similar issues, the issue will not be closed until the next release

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.2)

**Comment by inotia00** [comment]
Can you check if the playback issue is reproducible on iOS TV?

**Comment by Arin-hana** [comment]
It appears to be working

**Comment by inotia00** [comment]
Looks good

If you have any playback issues in iOS TV client, please leave a comment here again

**Comment by Karthik-Subbu** [comment]
> Looks good
> 
> If you have any playback issues in iOS TV client, please leave a comment here again

Hi.. It appears the IOS TV client cannot play some news related videos. 

https://youtu.be/OEgNAI_Gd88

I am not sure of the reason why an empty response is received for the video. But the streaming request falls back to the IOS logged out client.

**Comment by WsNyc00** [comment]
iOS TV buffers on shorter videos (maybe) i was listening some music today and video stoped played after about 1 minutes, but again launching longer video, video plays fine.

**Comment by marieSt3wartizzle** [comment]
I have this same issue too... this only frequently happens on short-form videos.

**Comment by meateatingrex** [comment]
I haven't had a single issue with iOS Spoofing, since day one when iOS Spoofing was implemented till this day, zero issues with playback.

**Comment by YT-Advanced** [comment]
`MWEB` can be used by setting the User Agent to [bypass potoken](https://github.com/yt-dlp/yt-dlp/blob/0b6b7742c2e7f2a1fcb0b54ef3dd484bab404b3f/yt_dlp/extractor/youtube.py#L259)

I have implemented in https://github.com/YT-Advanced/ReX-patches/commit/ab0c645a394adef2e760d72eee82ea9af8bd7ce8 but it is not worked 🫠
