### ISSUE TITLE
bug: playlists thumbnails on accout menu page keep disappearing and appearing when refresh 

### ISSUE THREAD

**Issue by Finblade** [inotia00/ReVanced_Extended#2594]
### Type

Other

### Tools used

RVX Manager

### Application

19.44.39

### Bug description

In previous versions this was not happened but after updating the app into 19.44.39, playlist thumbnails doesn't even render when app starts and it keeps appearing and disappearing like in the video that i attatched. You can compare the differences

19.44.39

https://github.com/user-attachments/assets/f4700e2c-09ec-41f5-b40f-e39b4751497f

19.34.32

https://github.com/user-attachments/assets/e8b0122a-45c4-475f-a137-31bb3faf957a

These are selected patches in 19.44.39

{"com.google.android.youtube":["Alternative thumbnails","Ambient mode control","Bypass image region restrictions","Change player flyout menu toggles","Change share sheet","Change start page","Custom Shorts action buttons","Custom double tap length","Description components","Disable QUIC protocol","Disable auto audio tracks","Disable auto captions","Disable haptic feedback","Disable resuming Shorts on startup","Disable splash animation","Enable OPUS codec","Enable debug logging","Enable external browser","Enable gradient loading screen","Enable open links directly","Force hide player buttons background","Fullscreen components","GmsCore support","Hide Shorts dimming","Hide action buttons","Hide ads","Hide comments components","Hide feed components","Hide feed flyout menu","Hide layout components","Hide player buttons","Hide player flyout menu","Hide shortcuts","Hook YouTube Music actions","Hook download actions","Layout switch","MaterialYou","Miniplayer","Navigation bar components","Overlay buttons","Player components","Remove background playback restrictions","Remove viewer discretion dialog","Return YouTube Dislike","Return YouTube Username","Sanitize sharing links","Seekbar components","Settings for YouTube","Shorts components","SponsorBlock","Spoof app version","Spoof streaming data","Swipe controls","Theme","Toolbar components","Translations for YouTube","Video playback","Visual preferences icons for YouTube","Watch history"]}

### Device Environment

Android 14

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
I don't see anything wrong in the video

**Comment by Finblade** [comment]
> I don't see anything wrong in the video

Compare the two videos then you will see the wrong thing

**Comment by KobeW50** [comment]
Oh, the first vid didnt render before. I see now

**Comment by inotia00** [comment]
This is a reproducible bug even on unpatched YouTube, so Google needs to fix it

FYI: This is a server-side issue, so you can work around it by spoofing the app version to 19.33.37 or earlier

**Comment by Finblade** [comment]
Oh i got it. Thanks!
