### ISSUE TITLE
bug: (RVX manager) keeps crashing at building stage

### ISSUE THREAD

**Issue by Noth1ngLol** [inotia00/ReVanced_Extended#2596]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

1.23.5

### Bug description

https://drive.google.com/file/d/1-rGCZQNnjItiXqpFPsPEjc2w5F4G8NTb/view?usp=drivesdk

### Device Environment

Android 14, funtouch 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This appears to be an old bug in ReVanced Manager, Out Of Memory issue

Close all running apps and try patching again with Manager

**Comment by inotia00** [comment]
4GB of memory is not enough to run the Manager without any problems

Follow other patching methods provided in the [docs](https://github.com/inotia00/revanced-documentation?tab=readme-ov-file#docs)

**Comment by ILoveOpenSourceApplications** [comment]
Try ReVanced Manager and see if the issue persists or not.
