### ISSUE TITLE
bug(YouTube): string bugs

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2597]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.44.39
Patches v5.1.2

### Bug description

1.![Screenshot_20241222_085954_YouTube](https://github.com/user-attachments/assets/7098a0bf-713a-4f92-99e6-b246bd659fa4)

2.![Screenshot_20241222_090003_YouTube](https://github.com/user-attachments/assets/4636a364-ee73-426b-be05-d6ce37cc5343)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in revanced-patches-5.1.3

**Comment by thamniyomroots** [comment]
> fixed in revanced-patches-5.1.3
