### ISSUE TITLE
bug: YT Music not showing on Android auto

### ISSUE THREAD

**Issue by Berlinkk** [inotia00/ReVanced_Extended#2599]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT Music v 7.25.52

### Bug description

YT music now showing on Android auto. I'm facing this issue from past many releases even after including certificate spoof patch

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It's not a bug in RVX

For the patched RVX Music (GmsCore support) the package name has changed, so AA doesn't recognize it

Follow the instructions in this link:

https://www.reddit.com/r/AndroidAuto/s/2WIDy2XMwK
