### ISSUE TITLE
bug: Disabling remove-player-button-background patch doesn't remove its effect

### ISSUE THREAD

**Issue by christantoan** [inotia00/ReVanced_Extended#26]
### Type

Cosmetic

### Application

YouTube v17.49.37
Patches v2.147.0

### Bug description

Disabling remove-player-button-background patch doesn't work. Its effect is still applied whether the patch is applied or not.

### Steps to reproduce

1. Patch YouTube without remove-player-button-background patch
2. Open a video and tap the video player to show its controls
3. The buttons don't have background that normally should be there

### Relevant log output

```shell
None
```

### Screenshots or videos

![Screenshot_20221223-184511](https://user-images.githubusercontent.com/7300310/209331375-afe80e06-c27a-475e-abda-2b169a3f79b8.png)
![Screenshot_20221223-184539](https://user-images.githubusercontent.com/7300310/209331390-e3cd8dc6-8d1c-4190-9fb5-2249debd5e4c.png)

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![Screenshot_20221224-003801_ReVanced Extended](https://user-images.githubusercontent.com/108592928/209361514-0dd23415-f0e7-444a-9db5-48ae1d127fe2.png)
![Screenshot_20221224-003739_ReVanced Extended](https://user-images.githubusercontent.com/108592928/209361521-dc09e37b-6d13-4bc1-8461-4e9eaf5d793d.png)

it works as intended
