### ISSUE TITLE
feat(patch): channel blacklist

### ISSUE THREAD

**Issue by Spacellary** [inotia00/ReVanced_Extended#260]
### Application

YouTube

### Issue

YouTube still recommends you horrible channels that you don't like sometimes.

A feature similar to [this extension](https://chrome.google.com/webstore/detail/blocktube/bbeaicapbccfllodepmimpkgecanonai) -- **BlockTube** -- would allow the user to block certain channels for good, from recommendations and possibly content search results.

Alternatively just a simple channel name blacklist could be implemented.

### Patch

A feature similar to [this extension](https://chrome.google.com/webstore/detail/blocktube/bbeaicapbccfllodepmimpkgecanonai) -- **BlockTube** -- would allow the user to block certain channels for good, from recommendations and possibly content search results.

Alternatively just a simple channel name blacklist could be implemented.

### Motivation

YouTube still recommends you horrible channels that you don't like sometimes.

### Acknowledgements

- [x] I filled out all of the requested information in this issue properly.
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
