### ISSUE TITLE
bug(YT/Navigation): `Translucent Navigation` doesn't work

### ISSUE THREAD

**Issue by vippium** [inotia00/ReVanced_Extended#2600]
### Type

Other

### Tools used

RVX Manager

### Application

Latest Supported 44

### Bug description

After removing the `Enable Translucent Navigation Bar` and splitting it into light and dark, it doesn't work anymore. I tried every option, but it won't.

I know that it is `Experimental` but it was working previously and not anymore are splitting.

### Solution

Returning that option bach and adding light and dark Translucent Navigation under `Enable Translucent Navigation` can be done.

### Device Environment

A14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [ ] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is normal because the `Enable transluent navigation bar` setting has been removed

`Enable transluent navigation bar` (setting removed)
: force enable transluent navigation bar

`Disable transluent navigation bar` (setting added)
: force disable transluent navigation bar

**Comment by vippium** [comment]
> This is normal because the `Enable transluent navigation bar` setting has been removed

It doesn't. I tried patching v40 too. But Translucent bar is not working. There is only `Disable Translucent status bar`, not `Disable Translucent Navigation bar`. It is splitted into light and dark. 

Why don't you change it to `Enable light Translucent` and `Enable Dark Translucent`, as it will force it to get Enable.

**Comment by inotia00** [comment]
The `Enable transluent navigation bar` setting has been removed

Why do you think this is a bug?

**Comment by s7san007** [comment]
> The `Enable transluent navigation bar` setting has been removed

Starting with which version is it removed?
On versions 19.23.40-19.41.41 the translucent navbar works fine. But now I can't enable it coz of removing the toggle in the RVX settings. :(

**Comment by vippium** [comment]
> Starting with which version is it removed?

For every version I think
