### ISSUE TITLE
bug: Start page Trending not always working

### ISSUE THREAD

**Issue by flower434** [inotia00/ReVanced_Extended#2603]
### Type

Other

### Tools used

rvx-builder

### Application

YouTube v19.44.39
Patches v5.1.3

### Bug description

When using the “Change start page “ setting to change it to “Trending” it only works when the app is completely closed.
![Screenshot_20241222-155541](https://github.com/user-attachments/assets/834700a3-a1c5-40c9-b8b2-6e1fb214c2e3)
When the app is closed with the back key and then reopened again (without task closing it) it will open the Home page and not the Trending page.

### Solution

After closing the app with the back key it is required to task close the app and then it will again open with Trending page.

### Additional context

"patches": [
        "Ambient mode control",
        "Change start page",
        "Custom branding icon for YouTube",
        "Custom branding name for YouTube",
        "Description components",
        "Disable auto audio tracks",
        "Disable auto captions",
        "Disable haptic feedback",
        "Disable resuming Shorts on startup",
        "Disable splash animation",
        "Enable external browser",
        "Enable open links directly",
        "Force hide player buttons background",
        "Fullscreen components",
        "GmsCore support",
        "Hide Shorts dimming",
        "Hide action buttons",
        "Hide ads",
        "Hide comments components",
        "Hide feed components",
        "Hide feed flyout menu",
        "Hide layout components",
        "Hide player buttons",
        "Hide player flyout menu",
        "MaterialYou",
        "Navigation bar components",
        "Player components",
        "Remove background playback restrictions",
        "Remove viewer discretion dialog",
        "Return YouTube Dislike",
        "Sanitize sharing links",
        "Seekbar components",
        "Settings for YouTube",
        "Shorts components",
        "SponsorBlock",
        "Spoof streaming data",
        "Theme",
        "Toolbar components",
        "Video playback",
        "Visual preferences icons for YouTube"
      ]

### Device Environment

Android 15

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Starting with YouTube 19.34.42, the Start page will only change when the app is cold started

You can change the Start page on warm starts as well by changing the following settings:

```
Settings - General - Change start page type
```
