### ISSUE TITLE
bug: yt app crashes on opening videos tab under channel profile

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#2609]
### Type

Cosmetic

### Tools used

CLI

### Application

yt 19.16.39 root version

### Bug description

open a channel homepage then move to videos tab, the app will crash within seconds.

### Device Environment

android 14 moto stock

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It doesn't reproduce on my side

Please attach crash log

**Comment by MondayNitro** [comment]
sorry its was a random crash that happened twice, i should have checked more
