### ISSUE TITLE
feat(patch): make buffered part visible in dark mode

### ISSUE THREAD

**Issue by yazanx9** [inotia00/ReVanced_Extended#261]
### Application

YouTube

### Issue

can you pls make the buffered/downloaded part of the seekbar (look at the attached pictures) visible all the time, cause it is only visible when i tap on the video but after that it became invisible...thank you.

### Patch

![iMarkup_20230213_220612~01](https://user-images.githubusercontent.com/125409294/218868573-9e7f83e0-c9a2-481c-b0cd-bb454b2e7da2.jpg)
![iMarkup_20230213_220800~02](https://user-images.githubusercontent.com/125409294/218868727-d3ac1e68-8400-4a88-bdf2-2c8f91b814a2.jpg)

### Motivation

english is not my native launguage so i cant really describe my thought flawlessly..thanks for understanding.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Duplicate with following issue https://github.com/inotia00/ReVanced_Extended/issues/67
