### ISSUE TITLE
bug: Reddit - Account icon vanishes, post/inbox page crashes app

### ISSUE THREAD

**Issue by bagarwa** [inotia00/ReVanced_Extended#2610]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Reddit 2924.52.0

### Bug description

There are two issues I'm having with Reddit after patching with RVX Manager. 

# Account Switcher vanishes from top right. 
In an unpatched state of the Reddit app, I have 2 accounts logged in. The account icon shows-up at the top right of the app. Tapping it shows the profile pane and I can switch to other accounts form there. 
![Reddit 1A](https://github.com/user-attachments/assets/9b470248-3f5a-4ec8-a57b-373784ac2e30)  ![Reddit 1B](https://github.com/user-attachments/assets/3848ffcf-b982-4b65-a537-b06e9010fa6d)

But after patching the app using RVX Manager, this account icon vanishes from that place and I can no longer switch accounts. 
![Reddit 2](https://github.com/user-attachments/assets/ea790b7e-1f15-43e0-a9d4-6ef1a0df6162)

# Tapping any post / comment bubble / inbox icon in navbar crashes Reddit 

After patching, if I tap on my post or the comment bubble or the inbox icon in the navbar, instead of opening that page, Reddit app crashes. 

## Used patches: 
All reddit patches except - 
1. Change package name
2. Custom branding name for reddit
3. Change navbar icons

### Additional context

I did try to do it fresh. Uninstalled the reddit app completely, downloaded apk from apkmirror, installed that. Then without login into the reddit app, patched it with RVX Manager first. Launched the patched app. Login into reddit account. Both reported issues still exist. 

### Device Environment

Pixel 9 Pro XL, running Android 15 QPR 2 Beta 2, Magisk 28.1. 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It doesn't reproduce on my side

Please exclude patches one by one and report back which patch is causing the issue

**Comment by bagarwa** [comment]
Sadly seems to be happening for any and all patches. I repeated the following cycle for one patch at a time - 

1. Unmount in RVX Manager, cleared app data, uninstalled Reddit, reinstalled from apk, 
2. Patch Reddit in RVX Manager. Only one patch at a time. 
3. Launch Reddit. Login. See both issues are reproduced. 

These are the three patches I tried right now - only one at a time - 
1. Disable screenshot popup
2. Hide ads
3. sanitize sharing links

**Comment by inotia00** [comment]
Does the issue reproduce on Reddit 2024.17.0, where the resources were not obfuscated?

If so, it may be an issue with APKTOOL

**Comment by bagarwa** [comment]
It seems to be working on Reddit 2024.17.0. I applied all patches I had originally applied to latest version to this version and the patched app doesn't have the issues I mentioned originally. (Though the whole device crashed and rebooted once after the patch. Working fine afterwards.)

**Comment by inotia00** [comment]
Did you `Mount` instead of `Install` after patching Reddit?

**Comment by bagarwa** [comment]
Yes. Since I'm rooted, I use Mount option for all 3 RVX app patches. YT and YTM are working fine with the latest supported version mentioned in the RVX Manager.

**Comment by inotia00** [comment]
Maybe that's the cause of the issue

The `Mount` option should only be used for apps that support `GmsCore support`

(e.g. YouTube, YouTube Music, Google News, etc)

Also, universal apk is not provided from Reddit 2024.29.0+

So, the latest Reddit must be patched by following the procedure below

1. Download the BUNDLE (apkm) from APKMirror
2. Upload the BUNDLE (apkm) from Antisplit tool (e.g. [this one](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases)) and convert it to apk
3. Do not install the converted apk on your device, but upload it in RVX Manager
(Click the disk icon in the bottom right)
4. Run the patch and click `Install` to install it

**Comment by inotia00** [comment]
@KobeW50 I had to tag you because the provider of the document also needs to be aware of this

**Comment by KobeW50** [comment]
Okay ill note that Reddit shouldn't be mounted.

Should I also add the anti-split instructions to the docs?

**Comment by inotia00** [comment]
If a user wants to patch the latest Reddit with RVX Manager, they must do anti-splits

RVX Builder or Revancify do anti-splits automatically, but RVX Manager doesn't

Yeah.. I think we should add something to the docs

**Comment by bagarwa** [comment]
> So, the latest Reddit must be patched by following the procedure below
> 
> 1. Download the BUNDLE (apkm) from APKMirror
> 2. Upload the BUNDLE (apkm) from Antisplit tool (e.g. [this one](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases)) and convert it to apk
> 3. Do not install the converted apk on your device, but upload it in RVX Manager
>    (Click the disk icon in the bottom right)
> 4. Run the patch and click `Install` to install it

Followed this and it worked with the latest Reddit version. 👍
