### ISSUE TITLE
bug: YTM casting

### ISSUE THREAD

**Issue by Jeromi-e** [inotia00/ReVanced_Extended#2613]
### Type

Error at runtime

### Tools used

CLI

### Application

YTM 7.25.x

### Bug description

When i try to cast to tv and the moment it connects, it crashes and never opens again till data is cleaned or reinstalled.

ReVanced casting works fine

### Device Environment

Poco x6 pro, Android 14
Samsung A51, Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2482
