### ISSUE TITLE
bug: Fullscreen Video Resets to Start After Notification Panel Interaction

### ISSUE THREAD

**Issue by ShredRum** [inotia00/ReVanced_Extended#2616]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.44.39, RVX 5.1.3 (Release)

### Bug description

When watching a YouTube video in fullscreen mode on a mobile device, interacting with the notification panel causes unexpected behavior. After opening and closing the notification panel, tapping on the left or right side of the screen results in the video jumping to the very beginning. Additionally, in some cases, 2x playback may be triggered.

Steps to Reproduce:

Open YouTube on a mobile device.
Play any video in fullscreen mode.
Swipe down to open the notification panel.
Close the notification panel to return to the video.
Tap on the left or right side of the screen.

### Solution

Use old version of RVX based on 19.16.39

### Additional context

Demonstration of the bug on video
https://github.com/user-attachments/assets/1c25a243-0714-4629-8260-ed0a84145785

### Device Environment

Android 14, OneUI 6.1 (December patch)
Samsung Galaxy A55 SM-A556B/DS

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ShredRum** [comment]
Sometimes the behavior is completely random: from rewinding the video (without going to the beginning), to shifting the entire video window up by a few pixels. The shift looks like this:
![Screenshot_20241223_222352_YouTube RVX](https://github.com/user-attachments/assets/04b35f66-0225-4787-a869-39c161669aad)
![Screenshot_20241223_222403_YouTube RVX](https://github.com/user-attachments/assets/511a599a-171a-4cee-8f9a-e38cabe1b319)

**Comment by ShredRum** [comment]
I conducted additional research and found that fully opening the notification panel is not necessary to trigger the bug. A slight downward swipe, which causes the video player to shift slightly (a micro-movement that naturally occurs when initiating the notification panel gesture but doesn’t exit fullscreen), is enough to reproduce the issue.

Video:
https://github.com/user-attachments/assets/d64b4079-42aa-46f2-b59d-e6c576f90ee8

**Comment by inotia00** [comment]
It also appears to be reproducible on unpatched YouTube 19.44.39

**Comment by ShredRum** [comment]
> It also appears to be reproducible on unpatched YouTube 19.44.39

Thank you. I checked the reproducibility on vanilla YouTube, though a newer version, my mistake. In the end, I returned to version 19.16.39, but with new patches (in RVX Manager I allowed the patch of non-recommended versions) - everything works fine.
