### ISSUE TITLE
bug(YouTube Music): Weird Spacing on Comments then Replies

### ISSUE THREAD

**Issue by Mathew-88** [inotia00/ReVanced_Extended#2618]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Music v.7.16.53

### Bug description

Happens when on comments > replies.
![Screenshot_20241224-151517_YouTube Music](https://github.com/user-attachments/assets/406023e2-e438-4ed4-b699-1d981e322dbe)

### Device Environment

Android 11, One UI Core 3.1

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Looks like a bug in unpatched YouTube Music 7.25.53
