### ISSUE TITLE
bug: I can't log in with my Google account.

### ISSUE THREAD

**Issue by skl551** [inotia00/ReVanced_Extended#2619]
### Type

Other

### Tools used

RVX Manager

### Application

Rvx app version 19.44.39

### Bug description

I can't log in with my Google account. Everything worked fine until I updated the app. It tells me I don't have an internet connection but my internet is working fine.
![Screenshot_2024-12-24-21-27-52-11_680d03679600f7af0b4c700c6b270fe7](https://github.com/user-attachments/assets/d339c86f-36df-4f58-ae69-119e59bcd2dc)

### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by skl551** [comment]
![Screenshot_2024-12-24-21-31-50-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/133bf9d9-2b1a-4940-9d41-2cd37a390006)

**Comment by KobeW50** [comment]
Remove the google account signed in to MicroG (ReVanced Gmscore) from your device's Account settings. Then sign back in.

Or uninstall and reinstall microG (ReVanced GmsCore)
