### ISSUE TITLE
Traductor 

### ISSUE THREAD

**Issue by Cyxcix** [inotia00/ReVanced_Extended#262]
### Application

YouTube

### Issue

There is no option to translate comments from English to Spanish.

But in other languages, if the option appears.

I'm from Mexico.

### Patch

https://user-images.githubusercontent.com/123632625/218937018-53d06251-0fd3-4e22-8c3f-3dd8e9a6b901.mp4

### Motivation

Is YouTube premium 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It depends on the server side
It is not a feature that can be added by the client
