### ISSUE TITLE
suggestion: please add video buffering size setting!

### ISSUE THREAD

**Issue by Golukumar00** [inotia00/ReVanced_Extended#2623]
### Application

YouTube

### Suggestion description

Video buffering size is by default 120 to 130 seconds and the problem is just click on video it downloaded 2 minutes even I don't want to watch it and it consumes a lots of data. as living in India here 5g phone can use unlimited data but 4g can't use, it is limited. If possible please add buffering size option because previous I was using "libretube" app and in this app there is an option related to this for setting custom buffer size 

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2032#issuecomment-2116314424

Also, feature requests for YouTube are not accepted.
