### ISSUE TITLE
bug: Video restarts

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2624]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube 19.44.39

### Bug description

Whenever I'm watching a video in fullscreen and i swipe down to un-fullscreen video restarts and video goes black for 2-3 seconds and starts playing again

### Device Environment

Android 14

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by mysticmac3** [comment]
Turn off disable swipe to change video option,it worked for me

**Comment by AykhanUV** [comment]
Also there is still a bug when i double tap to seek all player components show for a second

**Comment by AykhanUV** [comment]
@inotia00 Hey remember i opened issue about double tap to seek bug, that issue still persists
