### ISSUE TITLE
suggestion: Infinite loading at Movies Browse page

### ISSUE THREAD

**Issue by selfmusing** [inotia00/ReVanced_Extended#2626]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube ( v19.44.39 , v19.30.39 , v19.16.39 ) 
Tried these three versions 

### Bug description

![Screenshot_20241228-003554_YT-RVX](https://github.com/user-attachments/assets/2bf98f91-350f-4228-9f93-61e4ede1fc52)
Activating this setting results in an infinite loading state for the Movies Browse page.

### Solution

My suggestion: I think there's no way to fix this issue , so it's better to add a side effect string for this setting ( some users reported this issue at rvx chat )

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by selfmusing** [comment]
Fixed with this PR :
https://github.com/inotia00/revanced-patches/pull/116

**Comment by KobeW50** [comment]
It's best to keep issues open until the PR is at least merged to the dev branch, or preferably to even to wait until its reflected in the main branch. So people can find this issue easier.
