### ISSUE TITLE
bug: The link is copied

### ISSUE THREAD

**Issue by esperanzality** [inotia00/ReVanced_Extended#2627]
### Type

Other

### Tools used

RVX Manager

### Application

v19.44.39
5.1.3

### Bug description

When you tap the link in the description, it gets copied to your clipboard instead of opening.

### Acknowledgements

- [ ] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by esperanzality** [comment]
why completed？

**Comment by inotia00** [comment]
This issue is reproduced on unpatched YouTube.

**Comment by esperanzality** [comment]
oh...sorry thank you
