### ISSUE TITLE
feat(patch): Vertical fullscreen

### ISSUE THREAD

**Issue by Evergard** [inotia00/ReVanced_Extended#263]
### Application

YouTube

### Issue

Lack of vertical support.

### Patch

Clicking fullscreen button while in portrait will open vertical fullscreen but won't if we swipe up the video. Will also enter vertical fullscreen according to device auto rotation but only when already in fullscreen mode.

### Motivation

It makes it emit less light compared to landscape mode and even during portrait mode with all the suggested videos, comment, and title below the video player.

Perfect for sleeping.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
