### ISSUE TITLE
bug: podcast playlist showing

### ISSUE THREAD

**Issue by iznawh** [inotia00/ReVanced_Extended#2632]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.44.39 (nodpi) 
Manager:
Version: 1.23.5
Model: SM-S911U
Android Version: 14
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

### Bug description

![Screenshot_20241230_210613_RVX](https://github.com/user-attachments/assets/c463d58b-1565-489f-ae62-41cbcf0bd911)
![Screenshot_20241230_211444_RVX](https://github.com/user-attachments/assets/862ecb78-032f-4e55-8319-7c2782f62189)
These podcast playlist keep allowing up in my recommended even though I have all the ad options enabled. It's been happening for awhile as well. [Reddit post](https://www.reddit.com/r/revancedextended/comments/1gq8tz3/_/) I have tried reinstalling, fully uninstalling and then installing

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Settings like `Hide playlist in feed` are not implemented
