### ISSUE TITLE
bug: (YouTube/Swipe Controls) Swiping up on a video makes it fullscreen despite Disable Watch Panel Gestures being enabled

### ISSUE THREAD

**Issue by meateatingrex** [inotia00/ReVanced_Extended#2633]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39
RVX Manager 1.23.5
Patch 5.2.1 dev 1

### Bug description

I'm not entirely sure if 5.1.3 patch has this issue as well, I just happened to notice this on patch 5.2.1 dev 1 by accident.

- open up any video
- swipe up on a video
- video goes fullscreen

I have swipe controls disabled, I did try to turn on the setting Disable Watch Panel Gestures but that didn't help.

Video:

https://streamable.com/anmyij

### Additional context

Settings:

[RVX YouTube_v19.16.39_2024-12-31.txt](https://github.com/user-attachments/files/18281819/RVX.YouTube_v19.16.39_2024-12-31.txt)

Patches:

[selected_patches_2024-12-31_15_38_47.json](https://github.com/user-attachments/files/18281821/selected_patches_2024-12-31_15_38_47.json)

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is not a setting to disable the action to switch to fullscreen in the general player

This is a setting to disable the gesture to switch to the previous/next video when swiping from top to bottom or bottom to top in the center of the fullscreen

Please read the description of the setting again

**Comment by inotia00** [comment]
My bad, the issue is dealing with YouTube 19.16.39

I'll re-test on YouTube 19.16.39 and get back to you

**Comment by inotia00** [comment]
The patch also works as intended on YouTube 19.16.39

**Comment by meateatingrex** [comment]
But in some reason I can swipe up on a video to make it fullscreen, as if Swipe Controls were enabled. And I don't mean the gesture that switches video to another, I.mean the gesture that makes the video to go fullscreen.

**Comment by inotia00** [comment]
Such patches are not implemented in RVX
