### ISSUE TITLE
feat(patch): Backup settings

### ISSUE THREAD

**Issue by no7hanky0u** [inotia00/ReVanced_Extended#264]
### Application

YouTube

### Issue

Sometime I need to reinstall an app or OS and after that I need to configure the app. There is no button to Backup settings.

### Patch

I'm asking you to add a settings backup and restore feature because reconfiguration is so annoying.

### Motivation

I think this will be very helpful for people who like to use many of the features and settings provided but are tired of having to reconfigure after reinstalling etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/179
