### ISSUE TITLE
feat(patch): Save 'Shorts' Videos to Playlist

### ISSUE THREAD

**Issue by sliceanddice9** [inotia00/ReVanced_Extended#265]
### Application

YouTube

### Issue

When scrolling through YouTube Shorts via the dedicated shorts player, there is no way to instantly save a 'shorts' video from within the player directly to any one of your playlists. 

### Patch

When scrolling through shorts via the dedicated shorts player, have a 'Save' button somewhere along the top or side so that a 'shorts' video can instantly be saved to any one of your selected playlists. 

### Motivation

There are plenty of valuable 'shorts' videos being produced by content creators, and sometimes these videos get disposed of or lost or forgotten when mindlessly scrolling through shorts; so it would be nice to have a way to quickly and easily save these 'shorts' videos inside the UI of the actual 'shorts' player itself.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Implemented by Google
