### ISSUE TITLE
feat(patch): Disable forced playback speed for music.

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#267]
### Application

YouTube

### Issue

When you select the default video speed from _Video settings_ it obviously applies to every video. This patch will disable that default speed for music videos so everytime we will not have to change the speed to normal while watching music videos.

### Patch

This patch will disable that default speed for music videos so every time we will not have to change the speed to normal while watching music videos. It could be something like this-
![Screenshot 13 36 (Saturday 18 02) brave 219](https://user-images.githubusercontent.com/125728453/219850434-cf048651-be47-4a8a-b451-e1c7268158a8.png)

### Motivation

I think it will save time clicking everytime to change playback speed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
unfortunately, it's impossible

This is because there is no method to determine whether the playing video is music or not.

If you long press the speed button (overlay button), the playback speed of the currently playing video is changed to 1.0x. use it

**Comment by manishloshali** [comment]
Thanks for taking a look. This is available in a chrome extension that is called [ImprovedTube](https://chrome.google.com/webstore/detail/improvedtube/bnomihfieiccainjcjblhegjgglakjdd). Click on player > Force playback speed for music. This is their github page https://github.com/code-for-charity/ImprovedTube-for-YouTube
