### ISSUE TITLE
bug: ′hide next button′ and ′hide prev button′ patches are borken in the latest patches

### ISSUE THREAD

**Issue by kapchapka** [inotia00/ReVanced_Extended#268]
### Type

Other

### Application

Youtube 18.06.35

### Bug description

′hide next button′ and ′hide prev button′ patches are not working as intended.
 If only ′hide next button′ patch is on, both the next and the previous buttons are hidden. On the other hand, if only ′hide prev button′ patch is on, both the next and the previous buttons are shown. 

Enabling both of the patches works as intended- that is, both the next and the previous buttons are hidden.

### Steps to reproduce

Step 1: Enabling one of the two patches.
Step 2: Disabling the other one.

### Relevant log output

```shell
...
```

### Device Environment

Android 13, OneUI 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.162.6](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.6)
