### ISSUE TITLE
bug: Old Layout is Enabled Whether The Toggle is Active or Not.

### ISSUE THREAD

**Issue by christantoan** [inotia00/ReVanced_Extended#27]
### Type

Cosmetic

### Application

YouTube v17.49.37
Patches v2.147.0

### Bug description

I still get old layout whether I enabled old layout toggle or not.

### Steps to reproduce

1. Patch normally
2. Disable "Enable old layout" toggle
3. Restart YouTube
4. Open a video and notice that the old layout is still enabled 

### Relevant log output

```shell
None
```

### Screenshots or videos

https://user-images.githubusercontent.com/7300310/209331963-0ca098cd-0982-4252-bf33-53ec1d204b56.mp4

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![Screenshot_20221223-182524_ReVanced Extended](https://user-images.githubusercontent.com/108592928/209360654-e9b5c991-5ee7-40ff-ade7-183328f4bee5.png)
If you set the old layout to on, the YouTube version changes to v17.28.35

If you check your app settings and it doesn't show the version as v17.28.35, it's a server side issue.

Not an RVX issue
