### ISSUE TITLE
feat(patch): Move "Hide community guidelines", "Hide subscribers community guidelines" and "Hide channel guidelines"

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#270]
### Application

YouTube

### Issue

I think you should move "Hide community guidelines", "Hide subscribers community guidelines" and "Hide channel guidelines" patches to "Hide comments component" section. Because they are just labels that shown in the comments box and not in the general layout

### Patch

![IMG_20230218_181429_211](https://user-images.githubusercontent.com/54460494/219857405-e6b893d8-07e9-42d3-be84-b6735caac70e.jpg)
![IMG_20230218_181432_521](https://user-images.githubusercontent.com/54460494/219857411-0ab61058-abaf-4be2-ae9c-d8017be88b31.jpg)

### Motivation

I think it's right to move them to reduce clutter in the general layout.
Sorry for my English not good.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.163.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.163.1)

**Comment by buiducanh142qn** [comment]
"Hide community guidelines" patch has not been moved in [revanced-patches-v2.163.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.163.1)

**Comment by inotia00** [comment]
checked, If necessary, please open a new issue related to this

**Comment by inotia00** [comment]
fixd in [revanced-patches-v2.163.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.163.4)

**Comment by devilboy1122** [comment]
![Screenshot_2023-02-25-10-21-43-1473227033](https://user-images.githubusercontent.com/79780868/221337284-5e2fce7f-4251-4a4c-a305-27914141df94.png)
When i like any video dislike count didn't show please fix this problem
