### ISSUE TITLE
bug(YouTube/Miniplayer): title shifts down in fullscreen

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#271]
### Type

Cosmetic

### Application

All YouTube versions supported by the RVX patch

### Bug description

I enabled tablet miniplayer patch and title of the video has shifted down.

### Steps to reproduce

Step 1 - Include `Miniplayer` patch.
Step 2 - Change `Miniplayer` type to `Tablet`.
Step 3 - Look at the top of the player in fullscreen.

### Relevant log output

```shell
_
```

### Screenshots or videos

![Screenshot_2023-02-18-16-45-46-58_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125728453/219857947-c4ec0d89-dbbd-4ee1-81c1-f3530ece025f.jpg)
Space above the title.
![Screenshot_2023-02-18-16-46-16-23_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125728453/219857977-16d644ab-00b2-4bb1-80c1-cd8accbe0fb5.jpg)

### Additional context

I think it has something to do with status bar but I'm not sure.

### Device Environment

Android 12, Realme UI. Tested on other devices but same result.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Spacellary** [comment]
👀

**Comment by manishloshali** [comment]
Any fix yet?

**Comment by S23u512** [comment]
Im not sure if this is related or not but on my end the video title goes a bit too much to the right, and doesnt stay at the edge on the left side of the screen.

![Screenshot_20230706_135229_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/138691006/7d85f536-d8d1-4333-846b-99c210847030)

I tested with phone view / tablet view and the same issue persist.

**Comment by S23u512** [comment]
I believe that in my case when this down pointing arrow is hidden it leaves an empty space behind, so if inotia00 could make the title to move into that empty space when this arrow is hidden it would solve this issue.

**Comment by inotia00** [comment]
As the way the `Enable tablet mini player` patch is applied has changed in [revanced-patches-4.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1), this bug has been fixed for YouTube v19.12.41+.

This is still a valid bug in YouTube versions lower than v19.12.41.

**Comment by inotia00** [comment]
For better tracking of the issue this has been migrated to https://github.com/inotia00/ReVanced_Extended/issues/2160
