### ISSUE TITLE
bug: No Speed.java in Integrations

### ISSUE THREAD

**Issue by nestyo** [inotia00/ReVanced_Extended#272]
### Type

Error while patching

### Application

-

### Bug description

Error while patching from source. There's no Speed.java file in [revanced-integrations](https://github.com/inotia00/revanced-integrations/tree/revanced-extended)/[app](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app)/[src](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app/src)/[main](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app/src/main)/[java](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app/src/main/java)/[app](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app/src/main/java/app)/[revanced](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app/src/main/java/app/revanced)/[integrations](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app/src/main/java/app/revanced/integrations)/[patches](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app/src/main/java/app/revanced/integrations/patches)/[button](https://github.com/inotia00/revanced-integrations/tree/revanced-extended/app/src/main/java/app/revanced/integrations/patches/button)/

### Steps to reproduce

-

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
nah.. I haven't fully added the commits to github yet.

About 12 hours ago, I couldn't use some github features because the github server was in bad condition, and when github was partially restored, I hurriedly uploaded only releases first and went to the appointment.

Now, github seems to be completely restored, so I'm going to merge them into the repo one by one.

**Comment by inotia00** [comment]
All commits are merged now :)

**Comment by nestyo** [comment]
Can't build, no BuildConfig file?

<details><summary>Logs</summary>revanced-integrations/app/src/main/java/app/revanced/integrations/utils/ReVancedHelper.java:56: error: cannot find symbol<br>&emsp;var currentVersion = BuildConfig.VERSION_NAME;<br>&ensp;symbol:   variable VERSION_NAME<br>&ensp;location: class BuildConfig</details>

**Comment by inotia00** [comment]
Don't build in debug environment, build in release environment

I didn't remove the debug type config from the build type in build gradle, even though it no longer supports building in a debug environment.
