### ISSUE TITLE
bug: Video quality does'nt take effect in shorts and reels

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#273]
### Type

Error at runtime

### Application

YouTube v18.06.35

### Bug description

Shorts and Reels don't follow video quality settings, they always play at 480p resolution, if video codec is vp9(I didn't include 'force-vp9-codec'). If video codec is avc, video follows video quality settings.

### Steps to reproduce

Step 1:  java -jar revanced-cli-2.20.0-all.jar -a YouTube_v18.06.35.apk -c -o YouTubeRevanced.apk -b revanced-patches-2.162.1-xtended.jar -m revanced-integrations-0.97.1-xtended.apk -e custom-branding-icon-afn-red -i custom-branding-icon-afn-blue -e custom-branding-name -i force-premium-heading -i materialyou -e force-vp9-codec -e optimize-resource -e translations
Srep 2: Install the app
Step 3: Go to revanced settings, default video quality, and set it to 720p or 1080p
Step 4: Play a short and open stats for nerds, you'll see video quality is 480x854

### Relevant log output

```shell
Null
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
YouTube's shorts player doesn't support video speed and video quality

Google should support it
