### ISSUE TITLE
bug: hide-cast-button included without selection 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#274]
### Type

Error while patching

### Application

YouTube v18.06.35

### Bug description

Just like the title, hide cast button gets included even if we don't select the patch when patching.

### Steps to reproduce

Step 1. Patch without selecting hide cast button.
Step 2. Go into other layout settings and the option is there.

### Relevant log output

```shell
Nil
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
it's not a bug
microg patch contains a `hide-cast-button` patch
So if you include the microg patch, it is forced to be included
(this is implemented by the official ReVanced Team)

**Comment by ILoveOpenSourceApplications** [comment]
Okay.
