### ISSUE TITLE
Materialyou seekbar colour

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#275]
### Application

YouTube

### Description

Feature request for an option to grab the seekbar colour from the materialyou colours.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Choose the appropriate label and re-register the issue according to the prescribed format
