### ISSUE TITLE
bug: Various settings missing from Youtube settings

### ISSUE THREAD

**Issue by achyutde13** [inotia00/ReVanced_Extended#276]
### Type

Cosmetic

### Application

YouTube 18.06.35

### Bug description

During the first launch when the old layout is used, all the youtube settings are present but after closing the app and when the new layout activates most of the default youtube settings go missing. Specially the playback in feeds which cannot be changed later unless wipe app data. 

### Steps to reproduce

Start app for the first time then check settings during the old layout to confirm they're there, then close the app and start it again and check settings during new layout. 

### Relevant log output

```shell
-
```

### Screenshots or videos

Settings during first launch
![Screenshot_20230219-090828_ReVanced Extended](https://user-images.githubusercontent.com/38592400/219917050-9db71e7a-7ef4-4de1-aa2e-3e65e2e55dfd.png)
![Screenshot_20230219-090835_ReVanced Extended](https://user-images.githubusercontent.com/38592400/219917059-fd7be856-cae0-4de1-bbf6-6a2445aa584f.png)

Settings during second launch with new layout
![Screenshot_20230219-090922_ReVanced Extended](https://user-images.githubusercontent.com/38592400/219917194-2cb1ecad-cdd0-4298-a644-9bbcabff11f7.png)
![Screenshot_20230219-090928_ReVanced Extended](https://user-images.githubusercontent.com/38592400/219917204-4678c94e-0687-4187-a703-f98916c97e74.png)

### Additional context

I applied the recommended selection in revanced manager then ticked off swipe controls and theme. 

### Device Environment

Android 12L, Custom ROM Crdroid 8.12 Poco F1. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It's a YouTube bug, not a ReVanced bug
