### ISSUE TITLE
It doesn't show version information and you can't change the country

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#277]
### Type

Other

### Application

YouTube v18.06.35

### Bug description

It doesn't show version information and you can't change the country

### Steps to reproduce

Select general settings > Select information > a black page appears which does not show the current version (for example 18.06.35).

The change location setting appears grayed out

### Relevant log output

```shell
No
```

### Device Environment

Android 11 miui 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/276
