### ISSUE TITLE
feat(patch): (sponsorblock) better skipped time format

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#279]
### Type

Cosmetic

### Application

ReVanced Extended v18.06.35

### Bug description

In sponsor block, the time you saved have missing spaces in the time shown between the numbers and the text (example in the screenshot below)

### Steps to reproduce

Enter into the sponsorblock tab, go to the bottom, and you'll see it

### Relevant log output

```shell
not relevant
```

### Screenshots or videos

![Inkedתמונה של WhatsApp‏ 2023-02-19 בשעה 10 30 14](https://user-images.githubusercontent.com/6445601/219937543-d162a76d-fef7-4052-a306-f6a0e37df1e5.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
'47 minutes 11 seconds' instead of '47minutes 11seconds'?

**Comment by NBruderman** [comment]
yep, exactly. although personally I liked the old format (47 min, 11 sec) better.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.162.6](https://github.com/inotia00/revanced-patches/releases/tag/v2.162.6)
