### ISSUE TITLE
How do I figure out what an option does?

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#28]
### Application

YouTube

### Description

when I put an option I can't really know what changes me in the application. could you put like a ? that makes it possible to see with an image and description what the aforementioned description does? and would it be possible to put the translations in other languages ​​like spanish and italian for example?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by vadgama-nikz** [comment]
https://telegra.ph/RV--RVX-Features-List-10-31
