### ISSUE TITLE
bug: <I found advertisement in home screen>

### ISSUE THREAD

**Issue by Golukumar00** [inotia00/ReVanced_Extended#280]
### Type

Other

### Application

V18.06.35

### Bug description

When scrolling home screen in specific video.

### Steps to reproduce

![Screenshot_20230219-175640](https://user-images.githubusercontent.com/119071430/219948587-25fc1c6c-01f4-4a7f-8a69-05bd54765474.png)
When scrolling home screen in specific video.

### Relevant log output

```shell
No log
```

### Screenshots or videos

![Screenshot_20230219-175640](https://user-images.githubusercontent.com/119071430/219948333-8f0a8bca-b785-4342-8189-4e9093346590.png)

### Device Environment

Android12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It is not ads
(Also visible to YouTube Premium users)
