### ISSUE TITLE
bug: `Material You` broken

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#282]
### Type

Error while patching

### Application

Youtube Latest Build

### Bug description

Material You patch not work on the new build !

### Steps to reproduce

Just include Material You patch and open the app

### Relevant log output

```shell
None
```

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/266
