### ISSUE TITLE
 bug: no option to turn off download recommendations

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#283]
### Type

Error at runtime

### Application

YouTube 18.06.35

### Bug description

There is no option turn off download recommendations.

### Steps to reproduce

N.A.

### Relevant log output

```shell
N.A.
```

### Screenshots or videos

![Screenshot_2023-02-19-19-43-01-68_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/219953767-2c066ea6-6472-41a6-9228-c1be4fac26b7.jpg)
![Screenshot_2023-02-19-19-43-08-00_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/219953773-9bc19d03-8eb7-44d6-8e54-9ef10375b6f3.jpg)

### Device Environment

Android 13, Realme UI 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/276
