### ISSUE TITLE
Hide overlay filter for when Shorts is paused

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#284]
### Application

YouTube

### Issue

Theres this dark overlay when I pause a Short. Please add a patch to remove it. 

https://user-images.githubusercontent.com/73917917/219973593-e4b51ba2-df84-49bf-a803-232af4f39403.mp4

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
