### ISSUE TITLE
I installed latest release and it reset all my settings!!

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#285]
### Type

Error at runtime

### Application

I just installed the latest release which includes the import/export Settings Feature and i noticed that it RESET all my settings! Why did this happen? Now i gotta spend lots of time again try setting everything up as it was before and with restarting the app all the time... Trying to Remember and Figure out my settings from before 

### Bug description

.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![notice](https://user-images.githubusercontent.com/108592928/219987251-47ca6f6f-31f1-4012-9714-b95d9941ee9f.png)
read notice

**Comment by anyujinie** [comment]
I read it very carefully and oversaw it. Why put such important information at the bottom not even highlighted?
