### ISSUE TITLE
YouTube removed "Playback in feed" setting. Add it back as patch please.

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#286]
I just updated to the latest release which includes import/export settings patch and I already regret it. In the latest release it seems like YouTube removed a feature that would prevent random shit(normal videos AND Shorts) being added to my history.

When you use the feed and stop scrolling video or Short will automatically start playing. I had this disabled with the previous version but now this feature is removed altogether so videos will start automatically playing regardless.
Please add a patch to readd this YouTube feature to the next Rvx release. I cannot stand the fact that now the feed is autoplaying videos. I cannot stop on feed and must always scroll or use another tab to prevent this behavior. It's ridiculously annoying that it adds random videos to my history.

https://user-images.githubusercontent.com/73917917/219981191-b9a5c463-179c-4623-8599-87c74822c956.mp4

![Screenshot_20230220-000859154 (1)](https://user-images.githubusercontent.com/73917917/219981250-d04c5328-f898-47e3-a139-6d58b9544d77.png)

![Screenshot_20230220-001002777 (1)](https://user-images.githubusercontent.com/73917917/219981251-4e145a65-3e4a-42cd-be5e-efe243aed06c.png)

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/276

**Comment by anyujinie** [comment]
I don't even have the new layout and still affected by this. So is it a bug ? Because these settings are gone from stock YouTube aswell
