### ISSUE TITLE
feat(patch): hide options from library menu

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#287]
### Application

YouTube

### Issue

There are a lot of unwanted options in 'Library', like my clips, my videos, history that were not there in a bit older versions. It would be great if you could add a patch to remove these options from view.

### Patch

These options should be removable using the requested patch.
![photo_6311796875375784790_w](https://user-images.githubusercontent.com/87489540/219983024-95f3488d-9615-4c34-bcc0-f3fb675edc8f.jpg)

### Motivation

There are a lot of unwanted options in 'Library', like my clips, my videos, history that were not there in a bit older versions. It would be great if you could add a patch to remove these options from view.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/35
https://github.com/inotia00/ReVanced_Extended/issues/79
