### ISSUE TITLE
bug: YT Tap to Seek no longer works

### ISSUE THREAD

**Issue by SoumyBhow** [inotia00/ReVanced_Extended#288]
### Type

Error at runtime

### Application

YouTube 18.06.35 (ROOT)

### Bug description

This issue started yesterday out of no where. Initially it was with a magisk module but then I tried building with Revanced manager and the issue persists

### Steps to reproduce

Include recommended patches (please see picture) and patch.
Open patched YouTube once, test a video (this first instance, tap to seek does work)
Close out YT, clear it from recents
Open YT again, open a video
Tap to seek no longer works even when closing and opening YT again

### Relevant log output

```shell
.
```

### Screenshots or videos

https://user-images.githubusercontent.com/42043870/219983328-fdca8ae6-1d2d-4c59-851e-de23660e5bb2.mp4

![Screenshot_20230219-185337_ReVanced Manager](https://user-images.githubusercontent.com/42043870/219983333-793f50c4-16ae-431e-b33c-bec53d2208fc.png)
![Screenshot_20230219-185342_ReVanced Manager](https://user-images.githubusercontent.com/42043870/219983337-3a38c2ef-3bdc-4661-93cf-2f059aa076a9.png)

### Additional context

This is with the rooted version of YouTube Revanced Extended. I've tried with different magisk modules (the ones that forks of https://github.com/j-hc/revanced-magisk-module) and building myself with Revanced Manager. I've also tried to take a log cat of the issue. 
[ytrvx.txt](https://github.com/inotia00/ReVanced_Extended/files/10778335/ytrvx.txt)

### Device Environment

OnePlus 7 Pro
Android 13 (CrDroid)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
i can't reproduce it
Maybe it's Google's A/B testing.

**Comment by inotia00** [comment]
Please test if the issue reproduces when you include only the `enable-seekbar-tapping` patch and exclude the rest of the patches.

**Comment by SoumyBhow** [comment]
I tried patching just ```enable-seekbar-tapping``` and the issue persists. This was done on YT 18.06.41.

**Comment by SoumyBhow** [comment]
By the way. I've found that seekbar tapping does work on regular Revanced. Perhaps that could be of use?

**Comment by inotia00** [comment]
yeah.. presumably this is another A/B test that Google is testing.

Does the issue persist even when Old Layout is enabled?

**Comment by SoumyBhow** [comment]
Yes. Patching only ```enable-seekbar-tapping``` and ```enable-old-layout``` and enabling the old layout in the newly patched YTRVX didn't solve the issue.

**Comment by SoumyBhow** [comment]
Very strange. I've patched YT with all of my regular preferred patches some time ago and tapping works now and I have no idea why. Also disabling the old layout mode still keeps me on the old layout. I'm not sure how long this will last though..

**Comment by inotia00** [comment]
yeah.. then, this is definitely an A/B test

Enabling the old layout is a way to forcefully disable A/B testing.

Unfortunately, there is currently no clear way

**Comment by SoumyBhow** [comment]
What a shame. Still thank you for your time.

**Comment by ILoveOpenSourceApplications** [comment]
Then shouldn't this be closed?

**Comment by inotia00** [comment]
> Then shouldn't this be closed?

nah.. there may be people who come across this issue later, so we need to archive it. (it's valid)

**Comment by ILoveOpenSourceApplications** [comment]
> > Then shouldn't this be closed?
> 
> nah.. there may be people who come across this issue later, so we need to archive it. (it's valid)

Seems reasonable. So be it.

**Comment by inotia00** [comment]
No longer reproducible in latest release
