### ISSUE TITLE
remove playback speed from player flyout panel

### ISSUE THREAD

**Issue by xenophorm12** [inotia00/ReVanced_Extended#289]
### Application

YouTube

### Issue

Now that we can finally put playback speed in the overlay panel, there should be an option to hide it from the player flyout panel.

### Patch

Let us hide "playback speed" from the player flyout panel.

![IMG_20230220_140617](https://user-images.githubusercontent.com/58360189/220089198-cce0992b-c351-459a-88de-7f9529df3aaa.jpg)
![IMG_20230220_140710](https://user-images.githubusercontent.com/58360189/220089209-44f6e35d-c07f-4369-97b7-3a37f6243f91.jpg)
![IMG_20230220_140813](https://user-images.githubusercontent.com/58360189/220089214-8871898b-c965-44c5-b23c-77572a9f53af.jpg)

### Motivation

Same motivation as the other removable components.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/33
