### ISSUE TITLE
question: <title>: "ussr.razar.youtube_dl" not installed 

### ISSUE THREAD

**Issue by Toshiro05** [inotia00/ReVanced_Extended#290]
### Application

YouTube

### Description

Whenever i try to download the video..it keep showing ussr.razar.youtube_dl not installed..

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
Install PowerTube

**Comment by inotia00** [comment]
install [PowerTube](https://github.com/razar-dev/PowerTube/releases)
