### ISSUE TITLE
Return YouTube dislikes 

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#291]
### Application

YouTube

### Description

Return YouTube dislikes no longer works for my account only .. this problem exists since last month.. when i logged out my account or signed in with another account it works properly .
I wonder if there is any solution? Or if anyone has faced this problem!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Still not reproducible. I guess it's a side issue
