### ISSUE TITLE
feat(patch): choosing a method to close the app

### ISSUE THREAD

**Issue by Troj80** [inotia00/ReVanced_Extended#292]
### Application

YouTube 18.xx.xx

### Issue

Implement the ability to choose between patches

• One back(OneBackToClose) to exit the app

• Double back(DoubleBackToClose) to exit the app

### Patch

• One back(OneBackToClose) to exit the app
https://github.com/revanced/revanced-patches/tree/main/src/main/kotlin/app/revanced/patches/youtube/misc/fix/backtoexitgesture
******************************************************
• Double back(DoubleBackToClose) to exit the app
https://github.com/inotia00/revanced-patches/tree/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/ads/doublebacktoclose

### Motivation

All people are different, someone is comfortable with two swipes, someone closes the application with one swipe. It would be really cool if you could implement a choice, given that these patches have already been written, and work great individually, it would certainly give a noticeable advantage when using your patches. Many would be grateful to you, I'm sure. You are the best ;)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue  https://github.com/inotia00/ReVanced_Extended/issues/148
