### ISSUE TITLE
bug: 'Pull down to refresh' channel doesn't work anymore.

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#293]
### Type

Error at runtime

### Application

Version 18.06.35

### Bug description

Just realized pull down to refresh channel doesn't work anymore. Guess this might be related to the recent YouTube bug with missing settings...

https://user-images.githubusercontent.com/73917917/220323497-8108838a-ca64-4b37-a3dc-a51e2a49a3e2.mp4

### Steps to reproduce

Visit any YT channel
Try pull down to refresh
Does not work

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cuynu** [comment]
Google disabled this feature from stock YouTube app. Please check in stock

**Comment by anyujinie** [comment]
> Google disabled this feature from stock YouTube app. Please check in stock

I checked already. Yes it's disabled in stock aswell. But I don't think/hope they did this willingly. Probably bug that it doesn't work anymore? Why would they remove it?

**Comment by anyujinie** [comment]
> This is a change in stock YouTube, not a bug in ReVanced

Change or bug?🤔 I don't see the point of removing it by YouTube

**Comment by cuynu** [comment]
> > This is a change in stock YouTube, not a bug in ReVanced
> 
> Change or bug?🤔 I don't see the point of removing it by YouTube

Change

**Comment by anyujinie** [comment]
@inotia00 Can it be added back as patch?

**Comment by inotia00** [comment]
It is part of the new layout, and the new layout depends on the server side.
Therefore, it is impossible to add or remove it with a patch.

**Comment by anyujinie** [comment]
> It is part of the new layout, and the new layout depends on the server side.
> Therefore, it is impossible to add or remove it with a patch.

Ok gotchu. Thx for clarifying that. I just don't understand these YouTube decision makers at this point. Why remove things for no reason? Who was possibly bothered by pull down to refresh in channels? It's just so frustrating with these YouTube brainlots...
