### ISSUE TITLE
bug: Some menus are not displayed.

### ISSUE THREAD

**Issue by gjgok** [inotia00/ReVanced_Extended#294]
### Type

Error while patching

### Application

YouTube ver.18.07.34

### Bug description

When opening YouTube settings, there is a bug that prevents some menus, such as autoplay, history and feed playback, from appearing.

### Steps to reproduce

1.Start the revanced extended.
2.Open the settings.
3The menu is not displayed.

### Relevant log output

```shell
I don't know how to save logs as this is the Android version.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/276
