### ISSUE TITLE
why are some of the settings missing?

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#295]
### Application

YouTube version 18.07.34

### Description

![Screenshot_2023-02-21-21-42-20-758_app rvx android youtube](https://user-images.githubusercontent.com/125992636/220376104-2129cff3-fa96-4631-baed-b9481ebf7c6e.jpg)
![Screenshot_2023-02-21-21-42-24-079_app rvx android youtube](https://user-images.githubusercontent.com/125992636/220376125-a9043e6d-16e7-4449-a3ed-46f4096832f2.jpg)
![Screenshot_2023-02-21-21-42-34-528_app rvx android youtube](https://user-images.githubusercontent.com/125992636/220376135-49b4501d-8227-400b-97d8-f2b4d3915e91.jpg)
![Screenshot_2023-02-21-21-42-38-640_app rvx android youtube](https://user-images.githubusercontent.com/125992636/220376145-e11b23ba-6b85-4775-91ac-6e7b05c3980c.jpg)

why are some of the settings in ReVanced (Extended) missing, even though there are some useful settings such as video buffer settings, these settings are very useful when the signal is bad

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/276

**Comment by KimYo2** [comment]
> #276

What about video buffer Settings from ReVanced Extended patch?

**Comment by inotia00** [comment]
> > #276
> 
> What about video buffer Settings from ReVanced Extended patch?

It's no longer valid on latest YouTube, so it was removed (a few weeks ago)
