### ISSUE TITLE
bug: Hide-view-products-banner seems to not work

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#296]
### Type

Error at runtime

### Application

YouTube v18.06.39

### Bug description

The view products banner has started to show up again even before the latest patch release, i.e., 2.162.7, as I noticed the banner and thought somehow I have removed the patch by accident but that wasn't the case.

### Steps to reproduce

Try to somehow pull the JerryRigEverything video in your homepage.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

![Screenshot_20230221-215219~2](https://user-images.githubusercontent.com/117499019/220405169-38ed7f0f-04b0-49a0-b153-50c0b92d80ba.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![iaj6qddw08s91](https://user-images.githubusercontent.com/108592928/220420904-fbd14f28-74ba-4768-af40-8ea63ccd5f27.jpg)
`Hide-view-products` setting removes this banner inside the player

It has nothing to do with the attached screenshot.

**Comment by ILoveOpenSourceApplications** [comment]
So I should be opening a new patch request to resolve this issue?

**Comment by inotia00** [comment]
> So I should be opening a new patch request to resolve this issue?

nah.. already registered issue exists https://github.com/inotia00/ReVanced_Extended/issues/303

**Comment by ILoveOpenSourceApplications** [comment]
Okay, but I think the title isn't accurate to the issue as it should be something like hide-view-products-in-video or just combine it with the hide-view-products-banner
