### ISSUE TITLE
bug: The spoofing version to fix the settings disappearing bug doesn't carry over updates 

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#298]
### Type

Error at runtime

### Application

YouTube 18.06.39 (root variant)

### Bug description

After installing an update through magisk on a clean installed app with the spoofing for fixing settings fix applied, the fix does not carry over, and the settings begin to disappear again. the only fix for that is to clean install again, and to not apply any updates. I don't know if this bug exists in the unrooted variant also.

I found the bug when applying the small update between patch v2.162.6 to v2.162.7.

### Steps to reproduce

1. Make a clean install and apply the fix when prompted.
2. Flash an update through magisk
3. Open the app again and go to settings.
4. Sometimes the app will still work fine when opening it right after the update, but when you close and re-open again, the bug will return.

### Relevant log output

```shell
---
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
yeah.. i plan to provide force spoof option in next version

In the dialog that appears when you first install the app

When you click OK -> do not spoof (v18.06.39)
When you click CANCEL -> force spoof (v18.04.43)

**Comment by NBruderman** [comment]
> yeah.. i plan to provide force spoof option in next update
> 
> current plan is... In the dialog that appears when you first install the app When you click OK -> do not spoof anymore (v18.06.39) When you click CANCEL -> force spoof (v18.04.43)

Unfortunatley, now even after a clean install the bug returns. It took about an hour, but it returned.

**Comment by NBruderman** [comment]
@inotia00 update: I think google fixed the issue. I opened the app this morning, and everything went back to normal. Did it get fixed on your end too?

**Comment by inotia00** [comment]
Yep, it looks like Google has fixed this issue.
It seems to have been resolved sooner than expected
