### ISSUE TITLE
question: <title>: skipping parts Problem

### ISSUE THREAD

**Issue by racecar69420** [inotia00/ReVanced_Extended#299]
### Application

YouTube

### Description

i dont know how to disable the introduction/ending/non-musical part/sponsor thing, can you help me?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![SponsorBlock](https://user-images.githubusercontent.com/108592928/220461522-2da8053e-97e2-4d28-b0c6-6e91dd2656c6.png)

Settings > SponsorBlock > segment
