### ISSUE TITLE
Background Playback Freeze

### ISSUE THREAD

**Issue by MehrojOfficial** [inotia00/ReVanced_Extended#3]
### Type

Error at runtime

### Bug description

When background playback is enabled, if you turn off the screen and listen to the music in the background after some time background music stops randomly. Happening with longer videos especially (30min+)

### Steps to reproduce

Step 1: Play longer YouTube video
Step 2. Turn on background playback and turn off the screen
Step 3: Wait for the music stops randomly 

### Relevant log output

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is also an outdated issue
It is not reproduced in the latest version
