### ISSUE TITLE
question: <title>:feature suggestions

### ISSUE THREAD

**Issue by Sjhd2332** [inotia00/ReVanced_Extended#300]
### Application

YouTube

### Description

I would like to suggest a feature.  You can change the version as you like with the version function.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
A lot of information is missing

Please fill out with the following conditions and write again

1. Change to an appropriate title
2. Change to the appropriate label (patch-request)
3. Add an appropriate description
