### ISSUE TITLE
feat(patch): Add upload date to Shorts

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#301]
### Application

YouTube

### Issue

Would be nice if there was a upload date on Shorts. Not knowing when they were uploaded is quite annoying and frustrating.
Like 1h. 2w. 1d. 3m. 3y.

Something like this:

![Screenshot_20230222-024459898 (1)](https://user-images.githubusercontent.com/73917917/220499785-9c4ac400-34e8-4feb-be54-3d139b3b5bf2.png)

![Screenshot_20230222-023908107 (1)](https://user-images.githubusercontent.com/73917917/220499061-92f842d0-27b7-4892-a3dd-bb625f998771.png)

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by venkat2305** [comment]
It's ugly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
