### ISSUE TITLE
bug: custom-seekbar-color patch doesn't stay consitent with the color

### ISSUE THREAD

**Issue by FawaSan92** [inotia00/ReVanced_Extended#302]
### Type

Cosmetic

### Application

Youtube v18.01.33-v18.06.39

### Bug description

Ever since this patch was added in v2.153.0, whenever I change the seekbar color, it changes to that color, but the issue is that it reverts back to the red color when you tap on the video player. No matter what color I change it to, it will always turn back into the default color whenever the video player is tapped on. The miniplayer also shows the default color.

### Steps to reproduce

Step 1. Include 'custom-seekbar-color' and 'settings' patch
Step 2. Turn on dark mode inside Youtube app
Step 3. Change the color inside the Revanced Extended settings to any hex color and restart the app.
Step 4. Open a video and see the custom color used.
Step 5. Tap on the video player or minimize it to see the default red color get used instead.

### Relevant log output

```shell
Don't have.
```

### Screenshots or videos

![Screenshot_20230221_212146_ReVanced Extended](https://user-images.githubusercontent.com/118403967/220506183-ed5749a0-cb35-4dc8-9cf0-42e0ac2309b1.jpg)
![Screenshot_20230221_212150_ReVanced Extended](https://user-images.githubusercontent.com/118403967/220506185-0b131b15-beb1-4cfb-984f-514d301e3bea.jpg)
![Screenshot_20230221_212201_ReVanced Extended](https://user-images.githubusercontent.com/118403967/220506187-a64a8788-65eb-4ca4-9f89-cd13d87bdf1d.jpg)
![Screenshot_20230221_212208_ReVanced Extended](https://user-images.githubusercontent.com/118403967/220506190-f70a127f-a4e3-4424-b93a-25177363940f.jpg)
![Screenshot_20230221_213240_ReVanced Extended](https://user-images.githubusercontent.com/118403967/220506191-60b592ed-df60-4f3d-bb01-aa4cfd7ce30e.jpg)

### Additional context

I included all patches except for 'custom-branding-icon-afn-blue' and 'custom-branding-afn-red'.
This bug started when this patch was released and is still present in the newest patches in v2.162.7

### Device Environment

Android 13, One UI 5.0, Samsung Galaxy S21 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It only changes seekbar color 'in dark mode', 'before touching'
(like the first screenshot)

this is not a bug
This is also indicated in the patch description.

The second screenshot probably depends on the server side as far as I know, so you can't change it in the app.
(If you know of a possible way, please leave a PR)
