### ISSUE TITLE
feat(patch): change the icon for YouTube music

### ISSUE THREAD

**Issue by KIL011** [inotia00/ReVanced_Extended#305]
### Application

YouTube Music

### Issue

Request about recovering old version icon.

### Patch

I would like to ask you to change icon to old version as original one instead of black and red version.

### Motivation

To maintain overall consistency and coordination.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
what do you mean?

Currently, YouTube Music supports three icons: red, blue, and revancify.

You can include or exclude any icon you want.

the same as in the past

**Comment by inotia00** [comment]
Also, this is the part where you should leave a pull request, it is far from a patch-request

because i don't have any icon source

Leave a Pull Request

**Comment by KIL011** [comment]
Ok, allow me to explain here: I'm using version 5.40.51. The icon is exactly same as the original (official) version [red style]. But when I update to 5.44.53, the icon automatically changed to [revancify style].

May I ask if I could manually change the icon?

Besides, it's the first time I submit on GitHub. I'll do as you said next time.

**Comment by inotia00** [comment]
Perhaps, you included the `custom-branding-music-revancify` patch and excluded the `custom-branding-music-afn-red` patch

Just exclude the `custom-branding-music-revancify` patch and include the `custom-branding-music-afn-red` patch

**Comment by KIL011** [comment]
Thanks for your reply. Does this function [patch] need root of android devices?

**Comment by inotia00** [comment]
> Thanks for your reply. Does this function [patch] need root of android devices?

nah.. refer [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android))

**Comment by KIL011** [comment]
Sure, thanks
