### ISSUE TITLE
bug: `Hide mix playlist` not working in home feed

### ISSUE THREAD

**Issue by Issam28** [inotia00/ReVanced_Extended#307]
### Type

Error at runtime

### Application

Youtube 18.06.39

### Bug description

The setting 'Hide mix playlist' doesn't work. I have tested it both on and off and it doesn't work.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
bruh.. It seems that Google moved the layout of Mix playlists to litho in the latest build (server side)

It will take some time to respond to this

**Comment by Issam28** [comment]
I have no idea what that means, but hope this can be fixed soon.

**Comment by inotia00** [comment]
fixd in [revanced-patches-v2.163.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.163.4)
