### ISSUE TITLE
Feat(patch): Materialyou seekbar

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#308]
### Application

YouTube

### Issue

There is only the possibility to adjust the seekbar color manually

### Patch

A toggle to grab the seekbar colour from materialyou theme.

### Motivation

Make the YouTube theme even more personalized using the materialyou colours

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
