### ISSUE TITLE
feat(patch): Third party Casting Service to cast videos to TV

### ISSUE THREAD

**Issue by pbbecksen** [inotia00/ReVanced_Extended#309]
### Application

YouTube

### Issue

Since YouTube uses its own casting thing, which only opens that specific video on the youtube app on your tv, which makes it have adds and not skip sponsors.

### Patch

How about an integration with a third party Casting Service that, instead of opening the video on the TV app, actually casts the video as is to the screen. That way it wouldn't have any ad interruptions, and if sponsoblock skipps ahead it would happen on the TV too.

This could be added to YouTube and YouTube music too

### Motivation

We have been compromising by disabling casing either because it was broken or because it just made videos have ads for a while now. The only workaround for this was to just screenshare my entire phone, but that kind of defeats the purpose of casting it to the TV in the first place, since now you cannot use your phone.

With a patch like this, it would give us an option to cast out youtube videos to the TV and still enjoy ReVanced commodity on it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by sliceanddice9** [comment]
Would be amazing if the third party Casting Service - 'Web Video Caster' could be supported. That would make multi platform casting from an Android device to an Apple TV 4K possible, thus enabling an ad-free experience of YouTube on a ATV4K

**Comment by pbbecksen** [comment]
That's an awesome Idea. I hope they make it happen. 
Both YouTube and YouTube Music would benefit from this

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
