### ISSUE TITLE
bug: 'Hide mix playlist' not working

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#310]
### Type

Error at runtime

### Application

Version 18.06.41 non-root

### Bug description

Today I updated to the latest release and upon scrolling down my home feed I realized that those annoying Mix playlists have appeared despite me having them disabled with the patch.

![Screenshot_20230222-202305189 (1)](https://user-images.githubusercontent.com/73917917/220737447-c2bfb318-c628-485c-a63c-71c3182251e7.png)

![Screenshot_20230222-202249137 (1)](https://user-images.githubusercontent.com/73917917/220737474-61b5867f-6df7-4e93-8370-25545b84c9fe.png)

![Screenshot_20230222-202448929 (1)](https://user-images.githubusercontent.com/73917917/220737499-cf882db5-8190-4c39-b131-c0952168f930.png)

### Steps to reproduce

Open home feed
Scroll down
You will see 'mix playlists'

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/307
