### ISSUE TITLE
Like button whit dislike

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#312]
### Type

Cosmetic

### Application

Newest

### Bug description

The like button contains the dislike number, when the imp reduced dislike button is unchecked somethimes the first stick becomes white for a unknown reason and when you press the like button the dislike numbers disappear

### Steps to reproduce

1.Watch a video
2.watch the dislike button
3.if the color works close the app and return in the First step or choose a another video and return to the first step

### Relevant log output

```shell
...
```

### Screenshots or videos

First bug
![Screenshot_2023-02-22-21-07-06-706-edit_app rvx android youtube](https://user-images.githubusercontent.com/111771663/220747501-e73afbaa-e7d0-4795-a3fb-70f7558329ca.jpg)
Second bug
![Screenshot_2023-02-22-21-08-20-073-edit_app rvx android youtube](https://user-images.githubusercontent.com/111771663/220747499-cc9c06eb-fa18-42ff-88e8-fe066d6d700e.jpg)

### Solution

The first is resolve the random change of color, the second is a bug of the dislike 

### Device Environment

Android 12 miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
ReVanced doesn't change color when like button is pressed

Maybe, it's a side issue
(For example, MIUI's force dark theme)

**Comment by speedlorenzo12** [comment]
But happens
