### ISSUE TITLE
What about chapters and chat in landscape mode?

### ISSUE THREAD

**Issue by jezokshe** [inotia00/ReVanced_Extended#313]
In my latest versions, the chat (on streams) and the chapters open only under the video, that is, you need to transfer the smartphone to vertical mode.  After all, everything was different, it opened to the right of the full-screen video.  Is this a bug or feature on Google's part?  I didn't find how to get it back.

**Comment by inotia00** [comment]
Create a new issue with the prescribed form and the prescribed label.
