### ISSUE TITLE
백그라운드 전원버튼 끈후, 동영상 미디어 재생 끊김 현상.After turning off the background power button, video media playback is interrupted.

### ISSUE THREAD

**Issue by sangmo0145** [inotia00/ReVanced_Extended#314]
revanced 동영상 시청시 백그라운드 상태에서... pip>power off!>미디어 청취시에 끊김현상이 있습니다.
이 점을 개발에 신경을 써주시기를 부탁드립니다.
Revanced 동영상 애호자 입니다.
잘 보고 있습니다. 감사드립니다.👍❤️When watching a revanced video, in the background... pip>power off!> There is a disconnection when listening to media.
 Please pay attention to this in development.
 I am a fan of Revanced videos.
 Looking good.  Thank you.👍❤️

**Comment by inotia00** [comment]
Open a new issue with the prescribed form and the prescribed label.
