### ISSUE TITLE
bug: <hide mix playlist>

### ISSUE THREAD

**Issue by MustafaErdqn** [inotia00/ReVanced_Extended#315]
### Type

Error at runtime

### Application

Although the mix playlist is turned off in the settings, the lists appear on the main page.

### Bug description

Although the mix playlist is turned off in the settings, the lists appear on the main page.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![photo_2023-02-23_09-06-00](https://user-images.githubusercontent.com/126149028/220853042-e75be70f-fd56-49cf-acd9-fa15facc24bc.jpg)

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/307
