### ISSUE TITLE
feat(patch): make text selectable in info box

### ISSUE THREAD

**Issue by NMBlanco** [inotia00/ReVanced_Extended#316]
### Application

YouTube

### Issue

Text can not be selected and copied within the youtube app (for example inside the infobox). I think it would be a neat feature if you could make this a patch.

### Patch

Option to enable selectable text 

### Motivation

It would be an useful addition to the already incredibly great revanced extended.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by tikkamasalla** [comment]
Not possible.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
