### ISSUE TITLE
question: <title>:I want to erase the bottom part of the short 

### ISSUE THREAD

**Issue by yuu4649** [inotia00/ReVanced_Extended#317]
### Application

YouTube

### Description

When watching a short on YouTube, a button appears at the bottom.
Is there any way to turn it off?
(I am using Deepl translation, so the text may be a little strange)
![無題459_20230223212509](https://user-images.githubusercontent.com/52097238/220905091-8a21cb08-7768-4d5f-9eab-2ecdbe17d0cc.png)

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Perhaps, what you mean is this
https://github.com/inotia00/ReVanced_Extended/issues/110

Same issue has already been registered
