### ISSUE TITLE
bug: "save search history" does not work

### ISSUE THREAD

**Issue by lethinhrider** [inotia00/ReVanced_Extended#318]
### Type

Other

### Application

ReVanced Extended 18.06.41

### Bug description

After searching in the search bar, everything is not saved in Revanced Extended. I don't use any DNS service so it won't be blocked.
Bug still there even when I logged in google account. Search history is still saved in stock youtube and Vanced. 

### Steps to reproduce

.

### Relevant log output

```shell
I don't know where to find the log file.
```

### Screenshots or videos

https://user-images.githubusercontent.com/43519453/220975038-710a0554-82e9-4615-9a20-4b8dcde3e9cb.mp4

### Solution

If the bug cannot be fixed, I suggest adding the "Import search history" patch, which will import the search history from the text file. This patch will help a lot of people who need search history like me.
My habit is to search for something then pause the search history to keep it unchanged in the future, but this feature is currently not working so I don't know how to do it. 

### Additional context

Does different android version, device or language setting lead to this?

### Device Environment

Nokia 3.1 Plus
Android 10
Location content setting: Vietnam

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![rvx](https://user-images.githubusercontent.com/108592928/220985462-81ca1d07-023e-43cb-87f4-42fff9e4a418.png)
can't reproduce

Search history is saved normally for both unpatched YouTube and RVX

**Comment by lethinhrider** [comment]
> 

After reinstalling Vanced MicroG latest version from your repo, non-login is still not fixed but after login can save search history now. If possible, I suggest adding a new patch "local-search-history" so that users who are not logged in can still use the "search history" feature.

**Comment by lethinhrider** [comment]
> > 
> 
> After reinstalling Vanced MicroG latest version from your repo, non-login is still not fixed but after login can save search history now. If possible, I suggest adding a new patch "local-search-history" so that users who are not logged in can still use the "search history" feature.

I just checked stock youtube(unpatched) which still allows saving search history even though not logged in. So this is still a bug that can only be fixed 1/2

**Comment by inotia00** [comment]
This is a MicroG issue, not a ReVanced issue.
