### ISSUE TITLE
question: where to find pause search/watch history option?

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#319]
### Application

YouTube

### Description

If I click on "Manage all history" it shows the following two options: "Vanced microG" and "Google Account", instead of showing the settings options for pause search history, pause watch history, etc. (as it used to show earlier).
![Screenshot_2023-02-23-22-59-24-92_c31b32364ce19ca8fcd150a417ecce58](https://user-images.githubusercontent.com/125809686/220984922-4a533c90-ccf9-48d2-bec7-6307a4e405ea.jpg)

If I click on Vanced microG, it shows this:
![Screenshot_2023-02-23-22-59-28-51_8ba307c69b33dad378e924b4feaa6203](https://user-images.githubusercontent.com/125809686/220985075-2ffa7410-8674-4e93-b6c6-82db941509a2.jpg)

While clicking on Google Account option does nothing.

Where and how can I find those settings options?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Google has moved the history option inside Google Play Services
(server side)

If you want to enable/disable it, you have to use unpatched YouTube, or set it on your PC or browser

**Comment by madhurvarshney** [comment]
> Google has moved the history option inside Google Play Services (server side)
> 
> If you want to switch enable/disable it, you have to use unpatched YouTube, or set it on your PC or browser

Then how about just removing that "Manage all history" option (or maybe "Privacy" as well) from settings page, since they provide no useful purpose?
Or, if possible, provide this information (that to change the history settings use unpatched YouTube or using PC or browser) somewhere, like as a note or something like that.

**Comment by inotia00** [comment]
Unfortunately, currently there is no way

It is possible to remove the parent container (the entire Settings container), but it is impossible to enable or disable the child elements because they are received from the server side.

**Comment by madhurvarshney** [comment]
Okay. Thanks.
