### ISSUE TITLE
bug: downloader package name dialog is not shown

### ISSUE THREAD

**Issue by K4Z3R0** [inotia00/ReVanced_Extended#32]
### Type

Other

### Application

YouTube v17.49.37

### Bug description

Clicking the downloaders doesn't do anything, it should automatically put the package name

### Steps to reproduce

Probably happens to everyone else also

### Relevant log output

```shell
None
```

### Solution

Just needs to be fixed

### Device Environment

Android 10, HiOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Duplicate with this issue https://github.com/inotia00/ReVanced_Extended/issues/24

**Comment by venkat2305** [comment]
https://user-images.githubusercontent.com/55329452/209444881-5947ef50-53bf-4ea9-b1df-5d6e8a18fa77.mp4

Is this relevant for this issue?

**Comment by inotia00** [comment]
fixed in latest releases
