### ISSUE TITLE
feat(patch): remember videos only selection in subscription feed

### ISSUE THREAD

**Issue by SamuelAdmand** [inotia00/ReVanced_Extended#323]
### Application

YouTube

### Issue

It will not solve any issue but it will give a better look to subscription feed. 

### Patch

![Screenshot_20230224-081713_YouTube](https://user-images.githubusercontent.com/89719145/221080003-4508cd1a-da42-4e9e-b071-b6089583570f.png)
This patch will give clean look to the subscription feed in the current scenario if we want to remove posts from subscription feed we will need to turn off community post. 
But if you add this patch we will get a clean look without turning off the community post. 

### Motivation

If you provide this patch we will not have to disable community post to get a cleaner look of subscription feed. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
