### ISSUE TITLE
question: playback stopped at a certain point

### ISSUE THREAD

**Issue by sangmo0145** [inotia00/ReVanced_Extended#324]
### Application

YouTube

### Description

Revanced 동영상 시청 미디어 재생이 끊김! 현상이 계속 반복 됩니다.
이 점을 개선,개발을 바라겠습니다.
개개발자님의발자님의 무료 유튜브시청에 깊은 감사를 드립니다!
Watch Revanced Videos Interrupted Media Playback!  The symptom repeats over and over again.
 We hope to improve and develop this point.
 Thank you very much for watching the developer's free YouTube!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/141
