### ISSUE TITLE
Patch Suggestion

### ISSUE THREAD

**Issue by briantgosling** [inotia00/ReVanced_Extended#325]
### Application

YouTube

### Issue

Not really an issue but it can basically help a little bit i guess

### Patch

I would like to request a patch that can lock or a lock option when watching a video since I always have to wipe my screen evrytime im watching videos and I always have to turn off the screen to do it so I thought maybe having a lock option would be great when watching 

### Motivation

It kinda help to focus more on watching videos and I think it is lowkey great

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/10
