### ISSUE TITLE
bug: Some `hide-button-container` settings hide the entire button container

### ISSUE THREAD

**Issue by briantgosling** [inotia00/ReVanced_Extended#326]
### Type

Other

### Application

YouTube 18.06.41

### Bug description

found it while watching videos, it's a bug that hides the like button and others

### Steps to reproduce

no i do not know the reason why this occurred 

edit: it's when you hide a particular button and everything just disappear 

### Relevant log output

```shell
no log output
```

### Screenshots or videos

![Screenshot_2023-02-25-06-42-46-856_app rvx android youtube](https://user-images.githubusercontent.com/116717037/221311401-62fe4c34-75b7-4125-a42f-22d8e1aa7804.jpg)

### Solution

nope i dont got any solution 

### Device Environment

Android 12 Miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/320#issue-1597386894

Guess this is not fixed then

**Comment by inotia00** [comment]
please add revanced-patches version and hide button container screenshot

**Comment by inotia00** [comment]
fixed in [revanced-integrations-0.99.2](https://github.com/inotia00/revanced-integrations/releases/tag/v0.99.2)

**Comment by briantgosling** [comment]
> fixed in [revanced-integrations-0.99.2](https://github.com/inotia00/revanced-integrations/releases/tag/v0.99.2)

thank you, you're so fast!
