### ISSUE TITLE
bug: Several patches disappeared and now seeing COVID panels and community guidelines

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#327]
### Type

Error at runtime 

### Application

Version 18.06.41 non-root

### Bug description

I just updated to latest release and noticed that several patches are missing from RVX settings. Thus I'm now seeing these COVID panels and community guidelines...

+ hide mix playlists patch enabled and it's not working. Still seeing mix's. Buttons below video sometimes still missing or just a black space being added.

• All of Community guidelines patches are missing
(Hide channel guidelines)
• Some of the emergency/medical patches are missing
• 'Hide compact banners' is missing

![Screenshot_20230225-014420828](https://user-images.githubusercontent.com/73917917/221326597-29e9c692-660f-40cd-8a9e-bc9835cbf1ae.png)

![Screenshot_20230225-014641984 (1)](https://user-images.githubusercontent.com/73917917/221326599-e00845ab-49c9-46d8-b85f-9cdb57073e60.png)

![Screenshot_20230225-020435757 (1)](https://user-images.githubusercontent.com/73917917/221327391-7ab206a6-0e75-4725-aa7d-b13f9c35e354.png)

![Screenshot_20230225-012811075 (1)](https://user-images.githubusercontent.com/73917917/221326830-ac414b7b-8cb7-43ad-9935-0e5a33ac9f0d.png)

Confirm dialogue for when viewing suicide related topics? (Just testing wether patch is working. These dialogues are quite annoying)
Is this the emergency box patch supposed to remove this dialogue?

![Screenshot_20230225-015759468 (1)](https://user-images.githubusercontent.com/73917917/221327046-afdee307-e940-4caf-a29f-03ed03e26e90.png)

**Comment by anyujinie** [comment]
And issue with buttons missing still persists:

![Screenshot_20230225-032027928 (1).png](https://user-images.githubusercontent.com/73917917/221331190-8527dc6d-fca5-4311-a378-e80210f09c41.png)

**Comment by inotia00** [comment]
it's not a bug. read changelog

**Comment by anyujinie** [comment]
> it's not a bug. read changelog

Huh? I just read it again. I'm still seeing Mix Playlists, Covid19 banner in search result and below video, and where is the hide compact banners patch? It's missing aswell.

See screenshots above. I don't understand...

**Comment by inotia00** [comment]
for covid panels, refer https://github.com/inotia00/ReVanced_Extended/issues/125

and glitch is still unreproducible

**Comment by anyujinie** [comment]
> for covid panels, refer https://github.com/inotia00/ReVanced_Extended/issues/125#issuecomment-1374940916
> 
> and glitch is still unreproducible

Ok enabled hide info panels. Does this patch hide anything else besides COVID-19 panels? Just asking cause it might hide some things that I want to see.

So is hide mix playlists still showing them mix's for you aswell? And action buttons below video missing?

You only can't reproduce the glitch in feed?

**Comment by inotia00** [comment]
> Ok enabled hide info panels. Does this patch hide anything else besides COVID-19 panels? Just asking cause it might hide some things that I want to see.
> 
> So is hide mix playlists still showing them mix's for you aswell? And action buttons below video missing?
> 
> You only can't reproduce the glitch in feed?

yeah.. it hides all info panels at the bottom of the video

For example, include a panel like this
![bbc](https://user-images.githubusercontent.com/108592928/221356823-d53f3ab8-3ea7-470f-a8a1-b0cdba5cacca.png)

Since 2023 Google no longer displays Covid-19 information in the medical panel, and has incorporated it into the info panel

**Comment by anyujinie** [comment]
>

So is hide mix playlists still showing them mix's for you aswell? And action buttons below video missing?

You only can't reproduce the glitch in feed?>

**Comment by inotia00** [comment]
both cannot be reproduced

Hide Mixplaylists setting works as intended (remove it from the home feed, related videos feed), the glitch doesn't reproduce

**Comment by anyujinie** [comment]
> both cannot be reproduced
> 
> Hide Mixplaylists setting works as intended (remove it from the home feed, related videos feed), the glitch doesn't reproduce

Gotchu. That's weird. Guess I have to deal with these glitches and mix's showing...

**Comment by inotia00** [comment]
Patches can break in the old layout
As mentioned before, my patch was written based on the new layout.

**Comment by anyujinie** [comment]
My fucking account just won't receive the new layout for some reason...

**Comment by ILoveOpenSourceApplications** [comment]
@anyujinie you haven't received the new UI even in the stock YouTube app?

**Comment by anyujinie** [comment]
> @anyujinie you haven't received the new UI even in the stock YouTube app?

No obviously not even in stock YouTube

**Comment by ILoveOpenSourceApplications** [comment]
Try signing out of the account or even uninstall microg and maybe reinstall the YouTube app but not login initially.
