### ISSUE TITLE
feat(patch): Disable automatic captions[CC] when playing video in YouTube Music 

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#328]
### Application

YouTube Music

### Issue

When I watch music videos in YouTube Music the same issue with YouTube of automatic subtitles happens there. A patch to disable this behavior would be great 👍🏻

### Patch

![Screenshot_20230225-032007155](https://user-images.githubusercontent.com/73917917/221331335-4966de52-61f5-4811-a503-75654f31c7b6.png)

### Motivation

Subtitles being automatically enabled is annoying. We know it from YouTube and a patch to disable it for YouTube exists. Asking for the same thing in YouTube Music.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please attach the url of the video in the screenshot

**Comment by anyujinie** [comment]
> Please attach the url of the video in the screenshot

https://music.youtube.com/watch?v=cKlEE_EYuNM&feature=share

**Comment by anyujinie** [comment]
@inotia00 Did you have time to look into this? This continues to be a major annoyance when playing videos in YTM...

It's showing subtitles not only in English but also in German. I don't want to see them automatically displayed. This is the annoying YT behavior.


![Screenshot_20230311-005149769 (1).png](https://user-images.githubusercontent.com/73917917/224450619-8c286bbc-632c-45ce-8dd5-86fafd8f6e4f.png)

![Screenshot_20230311-005217142 (1).png](https://user-images.githubusercontent.com/73917917/224450620-38248185-ab1a-4f03-aeb4-23d40583130f.png)

Video Link: https://music.youtube.com/watch?v=iLXyoC2HRgY&feature=share

**Comment by inotia00** [comment]
Maybe it will be reflected in the next update

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.24)

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.164.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.24)

**Comment by anyujinie** [comment]
Thanks you for adding it :)
