### ISSUE TITLE
feat(patch): Hide channel guidelines popup

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#329]
### Type

Error at runtime

### Application

RVX v18.06.41
revanced-patches v2.164.1
revanced-integrations v0.99.2

### Bug description

I noticed that hide channel guidelines patch just hides its "label" from the comment box, not actually completely hiding the channel guidelines.
Although I have enabled the option to hide channel guidelines, when I click to comment on a video with channel guidelines, a message dialog box will appear asking I to click agree to the guidelines.
Once I clicked OK, the message dialog never appeared on that channel's video again.

### Screenshots or videos

![Screenshot_2023-02-25-09-53-38-728_app rvx android youtube](https://user-images.githubusercontent.com/54460494/221332654-e15ac25f-64a4-4f71-8273-692ed141cc00.jpg)
https://user-images.githubusercontent.com/54460494/221332788-a966f28f-7829-4a3a-99f3-4765171c3433.mp4

### Solution

I want this patch to actually hide channel guidelines completely, which means hiding both of the cases I mentioned above.
Sorry for my English not good.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The Hide Channel Guideline setting removes the banner at the top of the comment, not the pop-up.
(hence the intended functionality)

Getting rid of popups requires a whole new patch

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
