### ISSUE TITLE
feat(patch): Hide Playback speed component in the player flyout

### ISSUE THREAD

**Issue by K4Z3R0** [inotia00/ReVanced_Extended#33]
### Application

YouTube

### Issue

Hides the playback speed component in the player flyout

### Patch

Hides the playback speed component in the player flyout

### Motivation

I never or rarely use the playback speed option, it just doesn't make sense to me

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.163.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.163.1)
