### ISSUE TITLE
How do I change the color's app? For yt and yt music

### ISSUE THREAD

**Issue by Blueaulo** [inotia00/ReVanced_Extended#331]
### Application

Other

### Description

I couldn't find it in the options

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please add some more explanation to supplement the question

**Comment by Blueaulo** [comment]
Oh, sorry, 
I know that you can change the icon color from red to blu and in the patch information I see the patch blu, but I don't see a setting for  use it.
I forgot to add icon i the first request

**Comment by inotia00** [comment]
ah, yeah.. As stated in the documentation, you can choose between red, blue, or revancify before starting the patch.

Unfortunately, this cannot be changed in the settings.

You can only change it to what you choose before starting the patch.

**Comment by Blueaulo** [comment]
Oh I see, so only with revanced manager or other, but you can't with just install the apk
