### ISSUE TITLE
bug: still seeing community posts

### ISSUE THREAD

**Issue by Issam28** [inotia00/ReVanced_Extended#332]
### Type

Error while patching

### Application

Youtube V18.06.41

### Bug description

With the latest release, I am still seeing community posts (is this how they are called?).  See screenshot for an example.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230225-094106](https://user-images.githubusercontent.com/22579217/221347886-6b3ad91b-1536-4eea-860b-c28c3f614fbe.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.5](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.5)
