### ISSUE TITLE
Return YouTube dislikes 

### ISSUE THREAD

**Issue by Moibrahim2074** [inotia00/ReVanced_Extended#333]
### Type

Other

### Application

YouTube 18.06.41

### Bug description

When i likes a video whose its likes count is under 1k the dislikes disappear .. when likes is 1k or more the problem disappears

### Steps to reproduce

Please can you fix that problem 

### Relevant log output

```shell
..
```

### Screenshots or videos

![Screenshot_20230225_134433_app rvx android youtube_edit_33681671385485](https://user-images.githubusercontent.com/126328267/221355129-f310417b-6dad-4208-8d9e-4cc7e13e15ce.jpg)
![Screenshot_20230225_134437_app rvx android youtube_edit_33667486997466](https://user-images.githubusercontent.com/126328267/221355130-dd6ed44a-f8c8-4ac1-9b3c-8b0be46ac09f.jpg)

### Solution

..

### Additional context

..

### Device Environment

Android 12 .. Arm 64

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/281
