### ISSUE TITLE
bug: hide-floating-microphone-button requires an app restart 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#335]
### Type

Error at runtime

### Application

YouTube v18.06.41

### Bug description

This patch doesn't apply itself unless the app is restarted. So either give it the restart app option or change it so that it takes effect when the toggle is turned on/off.

### Steps to reproduce

Step 1: Turn the patch on and it'll be there.
Step 2: Restart the app and it's gone.
Step 3: Turn it off and it won't come back.
Step 4: Restart the app and it's back.

### Relevant log output

```shell
Nil
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.5](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.5)

**Comment by ILoveOpenSourceApplications** [comment]
@inotia00, I hope me leaving a comment in issues haven't been annoying you. I'm only trying to help you close issues which seemed resolved.

**Comment by inotia00** [comment]
yeah your intentions weren't wrong

**Comment by ILoveOpenSourceApplications** [comment]
But it looks like anyujinie thought I was somehow nose diving into all his issues and blocked me for it hence preventing me from further responding to all his issues. Even in the ReVanced repositories, given that I'm a triage over there. Just saying so you would know.
