### ISSUE TITLE
bug: cannot pause downloading video

### ISSUE THREAD

**Issue by wasiwah30** [inotia00/ReVanced_Extended#336]
### Type

Error at runtime

### Application

18.07.34 and previous versions as well

### Bug description

Cannot pause the downloading while downloading video within app

### Steps to reproduce

Start download

### Relevant log output

```shell
No
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
ReVanced does not offer a built-in downloader option
It's a YouTube issue
