### ISSUE TITLE
question: Why is the recommended version not the latest stable version of the play store?

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#337]
### Application

YouTube

### Description

Thank's for your job.
But, I have a question.
Why is the recommended version not the latest stable version of the Play Store?
Not so sure about Apkmirror info.
Latest stable version on Apkmirror is listed as 18.06.41, while on Play Store it is 18.07.34.
I'm confused.I apologize if this seems like a stupid question

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The recommended version doesn't always mean the latest stable

Among the versions where all patches work normally, the version I tested becomes the recommended version.

**Comment by jhon1282** [comment]
I'm sorry but if I asked the question it's because I tried the latest patches on version 18.07.34 and they work perfectly, otherwise I wouldn't have asked the question, anyway thanks for your availability :-)
