### ISSUE TITLE
bug: Swipe controls (Volume/Brightness) don't work with active player buttons

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#338]
### Type

Error at runtime

### Application

Version 18.06.41 non-root 

### Bug description

This has been an issue since forever and a very annoying one. Essentialy the swipe controls won't engage when the player buttons are active showing (Stop/Play, Prev, Next buttons)

See here: https://streamable.com/bgjeas

Would like to see this behavior fixed. The swipe controls should work at all times. Otherwise it beats their purpose..

### Steps to reproduce

1. Open any video in fullscreen
2. Try using swipe controls while player buttons are showing...

**Comment by inotia00** [comment]
this is not a bug

When the ReVanced Team rewrote the swipe gesture code from scratch, it was designed to recognize the gesture only when the player controller is not visible.

https://github.com/revanced/revanced-integrations/pull/123

**Comment by anyujinie** [comment]
> this is not a bug
> 
> When the ReVanced Team rewrote the swipe gesture code from scratch, it was designed to recognize the gesture only when the player controller is not visible.
> 
> https://github.com/revanced/revanced-integrations/pull/123

I didn't know this. Can you add an option so the swipe gestures work at all times?

**Comment by inotia00** [comment]
nah.. I already tried adding that option before, but it broke the swipe gesture patch so I rolled back

**Comment by anyujinie** [comment]
> nah.. I already tried adding that option before, but it broke the swipe gesture patch so I rolled back

😞 It's literally so annoying since it acts weird all the time. What was the Revanced team thinking...

**Comment by inotia00** [comment]
No.. at least I don't have a plan
If you can, please rewrite your code and leave a PR

**Comment by anyujinie** [comment]
I wish I had the ability to write code and a proper computer setup.. Nothing I can do..
