### ISSUE TITLE
Hide Mix playlist keeps disabling (shown).

### ISSUE THREAD

**Issue by K4Z3R0** [inotia00/ReVanced_Extended#34]
### Type

Other

### Application

YouTube v17.49.37

### Bug description

The `Hide mix playlist` setting keeps **disabling** `(shown)`.
I already tried force stopping the and restart youtube but it keeps switch off even if I **enabled** `(hidden)` it.

### Steps to reproduce

Open youtube
 **Enable** `(hidden)` `Hide mix playlist`
Restart or Force stop youtube
Go to layout settings where `Hide mix playlist` are
It's **disabled** `(shown)`

### Relevant log output

```shell
None
```

### Solution

Fix

### Device Environment

Android 10, HiOs

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
hide-mixplaylists doesn't fully support the tablet layout, rather it causes a bug that breaks the layout

So, if you are using tablet or tablet layout, it will be forcefully disabled, and it will change to OFF
