### ISSUE TITLE
feat(patch): remove tap a comment te reply

### ISSUE THREAD

**Issue by Issam28** [inotia00/ReVanced_Extended#342]
### Application

YouTube

### Issue

I rarely comment or reply on Youtube. The issue that happens, is quite often I accidentally tap a comment, and that prompts me to reply which I did not intend to do, and that's a bit annoying.

### Patch

Add the ability to turn off/on the tap to comment or reply.

### Motivation

I think it could be valuable for people who don't comment on Youtube 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
