### ISSUE TITLE
bug: hide products patch doesn't work properly

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#344]
### Type

Other

### Application

18.07.35

### Bug description

even though i enable hide products patch as well as hide chapter teaser under videos patch, they still appear for a video on homepage. it does not appear on search page, i.e. a certain video 'x' will show products below it if it shows up in my hompage videos list, but if i search for that same video, it does not show products below it in the search results. more simply, the hide products patch and hide chapter teaser under videos patch affects videos in search results and not those on home page(it should hide both)

### Steps to reproduce

step 1  enable hide products patch and chapter teaser patch.
step 2 scroll down your homepage feed. there will be some video that shows products below it
step 3 now search that same video, in the search results it will not show products below it

### Relevant log output

```shell
.
```

### Screenshots or videos

![1](https://user-images.githubusercontent.com/87489540/221422366-900629a4-e667-4282-b641-a56a5f33599b.jpg)
![2](https://user-images.githubusercontent.com/87489540/221422377-9c931403-16c6-439c-a8f5-64b13ea4fd1e.jpg)

### Solution

modify both patches to hide products and chapter teasers in homepage videos as well 

### Device Environment

a11 los 18.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
It's related to hide-chapter-teaser-under-videos which was fixed recently but it's showing up again in the latest version.
![Screenshot_20230226-225001~2](https://user-images.githubusercontent.com/117499019/221426133-decddac9-cdd3-4292-9b0c-0cb91473b7a8.png)

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/296
