### ISSUE TITLE
bug: Disabling this patch shows a weird glitch in Shorts

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#345]
### Type

Error at runtime

### Application

Version 18.07.35 non-root 

### Bug description

![Screenshot_20230226-180912435 (1)](https://user-images.githubusercontent.com/73917917/221425472-49bdc99e-5bd2-4a1a-941b-875394d34c90.png)

![Screenshot_20230226-180845493 (1)](https://user-images.githubusercontent.com/73917917/221425473-5f52536f-3462-4071-bb43-bf194191abe4.png)

I don't know what the name of this patch is in English, but disabling it shows "Abos" (Subscriptions) button when a Short is paused. I don't want to enable it as this removes the red subscribe button below. But just pointing out this weird button that appears at top left when it's disabled and Shorts is paused. 
Is this fixable?

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/254
