### ISSUE TITLE
bug: components under video player lags behind in loading and makes the the app unresponsive

### ISSUE THREAD

**Issue by Tasin5541** [inotia00/ReVanced_Extended#347]
### Type

Error at runtime

### Application

Youtube: 18.07.35
Patch: 2.164.5

### Bug description

Everything under the video player takes a moment to load (1-3s). This makes the app unresponsive while it's loading.
Does not happen everytime but happens frequently enough to be a problem.

This started with patch V2.162.1 and YouTube v18.06.35 after the reinstall. 

### Steps to reproduce

Access any video directly from a link (most prominent) or,
Choose a video from home of the app

### Relevant log output

```shell
No relevant logs to share from YouTube
```

### Screenshots or videos

![Screenshot_2023-02-27-09-44-05-845_app rvx android youtube](https://user-images.githubusercontent.com/42533823/221468641-754789b3-d2bb-4985-91f9-75eb324de5b6.jpg)

### Additional context

Selected patches
![Screenshot_2023-02-27-09-55-25-327-edit_app revanced manager flutter](https://user-images.githubusercontent.com/42533823/221470796-f145d6b7-5438-4f76-9508-177ace6edf2b.jpg)

Applied settings
`{"revanced_video_ads_removal":true,"revanced_overlay_button_auto_repeat":false,"revanced_overlay_button_whitelist":false,"revanced_swipe_magnitude_threshold":"0","revanced_adremover_medical_panel":true,"revanced_overlay_button_copy_url_with_timestamp":true,"revanced_enable_swipe_auto_brightness":false,"revanced_adremover_album_card_in_search":false,"revanced_adremover_web_search_panel":true,"revanced_enable_tablet_miniplayer":true,"revanced_enable_always_auto_repeat":false,"revanced_adremover_general_ads":true,"revanced_adremover_suggestions":false,"revanced_adremover_breaking_news_shelf":false,"revanced_swipe_overlay_background_alpha":"127","revanced_adremover_separator":false,"revanced_enable_minimized_playback":true,"revanced_swipe_overlay_timeout":"500","revanced_default_video_quality_mobile":"1080","revanced_adremover_browse_store_button":true,"revanced_adremover_timed_reactions":true,"revanced_enable_swipe_volume":false,"revanced_adremover_official_card_in_search":false,"revanced_adremover_user_filter":false,"revanced_adremover_emergency_box":true,"revanced_adremover_channel_member_shelf":false,"revanced_hide_cast_button":false,"revanced_adremover_self_sponsor":true,"revanced_adremover_community_posts":false,"revanced_hide_channel_watermark":true,"revanced_adremover_community_posts_home":false,"revanced_enable_swipe_haptic_feedback":true,"revanced_hide_filmstrip_overlay":false,"revanced_adremover_channelbar_join_button":false,"revanced_adremover_view_products":true,"revanced_hide_info_cards":true,"revanced_adremover_info_panel":true,"revanced_default_video_speed":"-2.0","revanced_overlay_button_speed":false,"revanced_initial_spoof":true,"revanced_enable_press_to_swipe":true,"revanced_enable_external_browser":true,"revanced_enable_open_links_directly":true,"revanced_adremover_merchandise":true,"revanced_overlay_button_downloads":false,"revanced_enable_save_brightness":false,"revanced_enable_old_quality_layout":true,"revanced_adremover_chapter_teaser":false,"revanced_adremover_latest_posts":false,"revanced_hide_endscreen_overlay":false,"revanced_enable_old_layout":false,"revanced_adremover_subscribers_community_guidelines":true,"revanced_swipe_overlay_text_size":"27","revanced_adremover_feed_survey":true,"revanced_adremover_community_guidelines":true,"revanced_default_video_quality_wifi":"1440","revanced_adremover_paid_content":false,"revanced_adremover_movie_shelf":false,"revanced_hide_endscreen_cards":true,"revanced_adremover_compact_banner":true,"revanced_enable_swipe_brightness_in_hdr":false,"revanced_adremover_image_shelf":false,"revanced_enable_save_video_quality":false,"revanced_hide_floating_microphone":true,"revanced_adremover_channel_guidelines":false,"revanced_adremover_button_ads":true,"revanced_overlay_button_copy_url":false,"revanced_adremover_community_posts_subscriptions":false,"revanced_enable_seekbar_tapping":true,"revanced_double_back_timeout":"0","revanced_adremover_custom_strings":"","revanced_enable_swipe_brightness":true}`

### Device Environment

Android 12, miui 13, sd 870, ram 6gb

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anil-al** [comment]
I can confirm it happens to me, mostly after watching a video in PiP outside of the app and then return to the video page or when changing the width app has in multi window or pop-up window in tablet (Tab S8+) while video is playing minimised in the app.

**Comment by inotia00** [comment]
This is an issue related to return youtube dislike

For some reason, you cannot access the ryd api on your device.

Temporarily, disable return youtube dislike

**Comment by inotia00** [comment]
No longer reproducible in latest release

**Comment by Tasin5541** [comment]
![Screenshot_2023-03-22-23-13-40-350_app rvx android youtube](https://user-images.githubusercontent.com/42533823/226990844-621b2c99-4698-46bd-b9c7-390853317243.jpg)

Still facing this issue.

**Comment by inotia00** [comment]
No matter what environment I test it, it is not reproducible

Anyway, if this issue still persists for you, I will reopen the issue.

**Comment by Tasin5541** [comment]
> No matter what environment I test it, it is not reproducible
> 
> Anyway, if this issue still persists for you, I will reopen the issue.

Here's my settings. Hope this helps. 

`{"revanced_video_ads_removal":true,"revanced_overlay_button_auto_repeat":false,"revanced_overlay_button_whitelist":false,"revanced_swipe_magnitude_threshold":"0","revanced_adremover_medical_panel":true,"revanced_overlay_button_copy_url_with_timestamp":true,"revanced_enable_swipe_auto_brightness":false,"revanced_adremover_album_card_in_search":false,"revanced_adremover_web_search_panel":true,"revanced_enable_tablet_miniplayer":true,"revanced_enable_always_auto_repeat":false,"revanced_adremover_general_ads":true,"revanced_adremover_suggestions":false,"revanced_adremover_breaking_news_shelf":false,"revanced_swipe_overlay_background_alpha":"127","revanced_adremover_teaser":true,"revanced_adremover_separator":false,"revanced_enable_minimized_playback":true,"revanced_swipe_overlay_timeout":"500","revanced_default_video_quality_mobile":"1080","revanced_adremover_browse_store_button":true,"revanced_adremover_timed_reactions":true,"revanced_enable_swipe_volume":false,"revanced_adremover_official_card_in_search":false,"revanced_adremover_user_filter":false,"revanced_adremover_emergency_box":true,"revanced_adremover_channel_member_shelf":false,"revanced_hide_cast_button":false,"revanced_enable_protobuf_spoof":false,"revanced_adremover_self_sponsor":true,"revanced_adremover_community_posts":false,"revanced_hide_channel_watermark":true,"revanced_adremover_community_posts_home":false,"revanced_enable_swipe_haptic_feedback":true,"revanced_hide_filmstrip_overlay":false,"revanced_adremover_channelbar_join_button":false,"revanced_adremover_view_products":true,"revanced_hide_info_cards":true,"revanced_adremover_info_panel":true,"revanced_default_video_speed":"-2.0","revanced_overlay_button_speed":false,"revanced_initial_spoof":true,"revanced_enable_press_to_swipe":true,"revanced_enable_external_browser":true,"revanced_enable_open_links_directly":true,"revanced_adremover_merchandise":true,"revanced_overlay_button_downloads":false,"revanced_enable_save_brightness":false,"revanced_enable_old_quality_layout":true,"revanced_adremover_chapter_teaser":false,"revanced_adremover_latest_posts":false,"revanced_hide_endscreen_overlay":false,"revanced_enable_old_layout":false,"revanced_adremover_subscribers_community_guidelines":true,"revanced_swipe_overlay_text_size":"27","revanced_adremover_feed_survey":true,"revanced_adremover_community_guidelines":true,"revanced_spoofing_type":false,"revanced_default_video_quality_wifi":"1440","revanced_adremover_paid_content":false,"revanced_adremover_movie_shelf":false,"revanced_hide_endscreen_cards":true,"revanced_adremover_compact_banner":true,"revanced_enable_swipe_brightness_in_hdr":false,"revanced_adremover_image_shelf":false,"revanced_enable_save_video_quality":false,"revanced_hide_floating_microphone":true,"revanced_adremover_channel_guidelines":false,"revanced_adremover_button_ads":true,"revanced_overlay_button_copy_url":false,"revanced_adremover_community_posts_subscriptions":false,"revanced_enable_seekbar_tapping":true,"revanced_double_back_timeout":"0","revanced_adremover_custom_strings":"","revanced_enable_swipe_brightness":true}`
