### ISSUE TITLE
feat(patch): Seek control buttons on Picture-In-Picture/PiP Mode

### ISSUE THREAD

**Issue by sliceanddice9** [inotia00/ReVanced_Extended#348]
### Application

YouTube

### Issue

There are no rewind back and skip forward seek buttons within PiP when playing videos. If there were seek buttons when Picture-In-Picture is enabled than we wouldn't have to maximize the app itself to access the fullscreen player in order to use the touch input rewind back and skip forward seek controls. 

### Patch

An updated version of Picture-In-Picture/PiP that includes seek buttons. 

A PiP player like this would be what I'd like to see:

![image](https://user-images.githubusercontent.com/59092472/221494304-391cbe60-086b-4d9d-aef9-bb5fc95c6da5.png)
 

### Motivation

When watching YouTube videos and multi-tasking - PiP is critical to allows the user to continue watching the YouTube video while also opening other apps and doing other things on their device. 

Being able to re-watch certain segments in a video or skipping ahead through certain segments in a video with the touch of a button. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by tikkamasalla** [comment]
That's literally not possible. It's an android limitation.

**Comment by sliceanddice9** [comment]
> That's literally not possible. It's an android limitation.

How so? NewPipe's version of PiP has built-in seek controls, why can't ReVanced's version of PiP be updated to include these buttons too?

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
