### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by Russogoxx** [inotia00/ReVanced_Extended#349]
Hola era para saber si me podían ayudar con algo que me pasa con revanced, cuando estoy mirando un video de la nada se pone la pantalla negra y cargar, no se si es algo mío o de la app si ke 
![Screenshot_20230227-100256_ReVanced Extended](https://user-images.githubusercontent.com/126479354/221570857-34ae3dfc-f9ba-4f9a-a66a-e1d082ee27ef.jpg)

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
