### ISSUE TITLE
bug: control overlay does not disappear

### ISSUE THREAD

**Issue by Rage-X** [inotia00/ReVanced_Extended#350]
### Type

Cosmetic

### Application

YouTube 18.07.35

### Bug description

Regression, control overlay sometimes does not disappear - known Revanced bug but never saw it in Revanced Extended. No such bug in previous extended version (18.06.XX).

### Steps to reproduce

Using recommended patches. After watching a number of videos the control overlay on the video is stuck. Fixed by restarting app.

### Relevant log output

```shell
NA
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is an old YouTube bug, not a bug in ReVanced / ReVanced Extended.

**Comment by Rage-X** [comment]
> This is an old YouTube bug, not a bug in ReVanced / ReVanced Extended.

That's very strange, I only experienced it in Revanced and never in Extended. I thought you did something to fix it.

Ah well time to downgrade.
