### ISSUE TITLE
feat(patch): hide-products-list-under-videos

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#351]
### Application

YouTube

### Issue

During the patch version 2.163.1 hide-chapter-teaser-under-videos was fixed as the products list under videos started showing up but given that it's linked to this patch makes no sense.

Chapter teaser are these under the videos:
![Screenshot_20230227-191740~2](https://user-images.githubusercontent.com/117499019/221582146-243f14ec-5246-42d5-b2f5-e9d2db39ec23.png)

But the ones that needs to be hidden are these:
![Screenshot_20230226-225001~2](https://user-images.githubusercontent.com/117499019/221582265-a5b41f33-9bb1-4756-802b-6f209954374b.png)

YouTube calls them "Product(s) listed here" when tapping the info icon:
![Screenshot_20230227-191621~2](https://user-images.githubusercontent.com/117499019/221582623-800e2611-7389-49fc-a6fe-5fa354987ac8.png)

### Patch

Introduce a new patch or edit the current one (hide-chapter-teaser-under-videos) into hide-products-list-under-videos or something more meaningful to the issue.

### Motivation

ReVanced team is introducing hide-chapter-teaser-under-videos to hide the actual chapter teasers under the videos, like it should be. So this should be renamed to something more meaningful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
I don't know if it's a patch request or a bug but I went with patch request as it's a new patch title.

**Comment by ILoveOpenSourceApplications** [comment]
Okay with the latest patch version 2.164.8, once again the products list has stopped showing up in the home feed, did you fix it again and forgot to mention or was it related to the YouTube app version.

**Comment by ILoveOpenSourceApplications** [comment]
It can even be named hide-products-list-under-videos instead of the new hide-teaser-under-videos, which still doesn't make much sense as a title for this issue.

**Comment by ILoveOpenSourceApplications** [comment]
I noticed that if we search for a channel, then in the search results we'll get the same products-list like banner but instead it's having chapter teaser. So I guess my current title suggestion wouldn't make sense anymore. But still is "teaser" the accurate title description for the patch is the question.

Another One:
![Screenshot_20230306-143832~2](https://user-images.githubusercontent.com/117499019/223066935-a2e72d42-4024-4cee-82f4-fdd22f4ae600.png)

And Another One:
![Screenshot_20230306-143849~2](https://user-images.githubusercontent.com/117499019/223067390-012a9dd1-3794-4de8-bb14-7276a0bfc2cb.png)

The patch works fine so you can change the label of this request into suggestion as it cannot be classified as a patch request.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)

**Comment by ILoveOpenSourceApplications** [comment]
Is there any changes in how the custom filter works currently?

**Comment by inotia00** [comment]
where are you running into issues?

**Comment by ILoveOpenSourceApplications** [comment]
![Screenshot_20230713-232852~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/8c430315-48ff-4207-9b17-af28299322dc)

Even after adding `inline_expander` & `expandable_metadata` to custom filter & having the patch hide expandable chip under videos on, I'm still seeing the chip under the videos.
![Screenshot_20230713-233222~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/fbb43ad0-c933-48cd-b9d3-9579c709014b)

**Comment by inotia00** [comment]
ah, unlike official ReVanced, custom filters in ReVanced Extended (YouTube) are separated by line (enter)

**Comment by ILoveOpenSourceApplications** [comment]
Can you show an example? Like inline_expander expandable_list_inner or is it inline expander, expandable list inner?

**Comment by inotia00** [comment]
like this
![e g](https://github.com/inotia00/ReVanced_Extended/assets/108592928/f27f0f16-a16b-423f-883b-0b436839bcdd)

separated by lines rather than commas (,)

**Comment by inotia00** [comment]
Separating with commas is less readable, so I changed it to input in line units.
(other adblock extensions already separate custom filters by line)

This is also mentioned in the description

![des](https://github.com/inotia00/ReVanced_Extended/assets/108592928/374bbb1b-db68-498e-ae72-46d21323ed74)

**Comment by ILoveOpenSourceApplications** [comment]
Okay, got it to work. But like I said, isn't hide expandable chip under video supposed to hide this component?

**Comment by inotia00** [comment]
Since the official ReVanced commits have been applied, they are probably hidden

**Comment by ILoveOpenSourceApplications** [comment]
But they are not. Not here not over ReVanced as well. It's really strange why it isn't getting filtered.
