### ISSUE TITLE
bug: hide-playlist-card patch's description 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#353]
### Type

Cosmetic

### Application

YT Music 

### Bug description

The description for hide-playlist-card currently has a spelling and grammatical mistake. Instead of recommended it says "recommand" and between the manager and the app itself, the description has "home feed" and "homepage" respectively.

### Steps to reproduce

Step 1: While patching YT Music including hide-playlist-card patch.
Step 2: Inside YT Music ReVanced Extended Settings and checking hide-playlist-card patch toggle.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

The Patch's Manager Description:
![Screenshot_20230227-232127~2](https://user-images.githubusercontent.com/117499019/221647840-0cefcb19-4bdb-48e2-87ee-0315f0300423.png)

The Patch's In-app Settings Description:
![Screenshot_20230227-233124~2](https://user-images.githubusercontent.com/117499019/221647926-2625bcb6-d2c1-4a2c-a2f4-8891c8141bac.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.164.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.10)

**Comment by ILoveOpenSourceApplications** [comment]
The manager description remains the same though, also the "homepage" and "home feed" in them as well. Please match the description across the Manager and YT Music app if possible.

**Comment by ILoveOpenSourceApplications** [comment]
Or just remove the recommend part. I don't see why it needs to be called recommend playlist as it's just a playlist card.

**Comment by inotia00** [comment]
ah.. I forgot again
I'll reflect it in the next release

**Comment by ILoveOpenSourceApplications** [comment]
No hurry, just here to help you.
