### ISSUE TITLE
feat(patch): pip doesn't work on youtube shorts

### ISSUE THREAD

**Issue by karasevych** [inotia00/ReVanced_Extended#356]
### Application

YouTube

### Issue

Disabling pip on youtube shorts

### Patch

Disabling pip on youtube shorts

### Motivation

 This interferes with how shorts does not work, then let it not be better at all

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
PIP mode is already disabled in Shorts player
