### ISSUE TITLE
feat(patch): remove YouTube clickbates

### ISSUE THREAD

**Issue by briantgosling** [inotia00/ReVanced_Extended#357]
### Application

YouTube

### Issue

About the clickbaits I hate clickbates in youtube so I thought about the extension in chrome that removes the clickbates just like sponsorblock and return dislike button maybe you can add this too

### Patch

See most YouTube videos have these clickbates which I find kind of annoying so maybe addding an extension or whatever you call it That removes the clickbate thumbnails might help

### Motivation

I think it is very unique and it can help to avoid getting clickbaited 

i just think it is cool

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
