### ISSUE TITLE
bug:  video quality not saved 

### ISSUE THREAD

**Issue by KPVADALIYA** [inotia00/ReVanced_Extended#358]
### Type

Error while patching

### Application

Revanced extended v18.08.34

### Bug description

Video quality not saved.

Everytime i have to change manually 

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KPVADALIYA** [comment]
[view this screen recording ](https://drive.google.com/file/d/1-mm9CakHFzVrhlm2KJHAC9C5bF0fiZ2a/view?usp=drivesdk)

**Comment by KPVADALIYA** [comment]
[view this ](https://drive.google.com/file/d/1-mm9CakHFzVrhlm2KJHAC9C5bF0fiZ2a/view?usp=drivesdk) 

.

**Comment by ILoveOpenSourceApplications** [comment]
For some reason when you're changing the video quality it's not getting registered by the save video quality setting.

**Comment by KPVADALIYA** [comment]
Yes

**Comment by ILoveOpenSourceApplications** [comment]
Have you tried repatching or reinstalling?

**Comment by KPVADALIYA** [comment]
Yes tried 3 times but same issue

**Comment by ILoveOpenSourceApplications** [comment]
> Yes tried 3 times but same issue

Well, I tried replicating the issue but it isn't occuring for me. Let's see if inotia00 can replicate it or not. Or if it's due to some other A/B testing from YouTube side.

**Comment by KPVADALIYA** [comment]
@inotia00 this is working only for old layout, if you change it to new layout then it bot saving video quality

**Comment by KPVADALIYA** [comment]
Also found other glitch that if you change back to old layout and save video quality than change it to new layout video quality is saved as old layout so you don't have to change manually everytime

**Comment by inotia00** [comment]
No longer reproducible in latest release
