### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by DawDrg** [inotia00/ReVanced_Extended#359]
### Application

YouTube

### Issue

The problem is that it does not have compatibility with Android TV I recently tried to install it directly from the app package on a Chromecast but it threw me that it is not compatible with the TV Something that had not happened with any other modified version of YouTube since I was recently using the latest version released by vanced

### Patch

It would be innovative if it had the compatibility to be able to install on Chromecast 4 (google tv) devices as well as on Android TV

### Motivation

I think this will favor the audience that follows this project

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
ReVanced YouTube or RVX doesn't support Android/Google TV (as of now anyways). But you can install and use [SmartTubeNext](https://github.com/yuliskov/SmartTubeNext) instead.
