### ISSUE TITLE
Why? & How ti fix please 🥺

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#361]
### Application

YouTube

### Description

This is how to fix it, how come the video settings in the latest version can't be changed

![Screenshot_2023-03-01-12-06-35-396_app rvx android youtube](https://user-images.githubusercontent.com/125992636/222050702-eb0a4d14-52f4-45a7-8aa4-1ef75d1f6474.jpg)

even though I pressed the toggle

![IMG_20230301_121113](https://user-images.githubusercontent.com/125992636/222051073-69b8c7a9-93ef-481d-9435-e627f6f43160.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KimYo2** [comment]
Oh yeah this is the new version 

![Screenshot_2023-03-01-12-16-12-503_app rvx android youtube](https://user-images.githubusercontent.com/125992636/222051493-2c6f3d2f-b854-4983-afa2-b85a16dcce62.jpg)

![Screenshot_2023-03-01-12-16-23-333_app rvx android youtube](https://user-images.githubusercontent.com/125992636/222051499-201e34e1-14e6-4385-ad90-f5f5e2c714a1.jpg)

**Comment by inotia00** [comment]
Duplicate issue already exists https://github.com/inotia00/ReVanced_Extended/issues/358

Most likely, it's an A/B test

**Comment by KimYo2** [comment]
A/B test?

**Comment by ILoveOpenSourceApplications** [comment]
> A/B test?

YouTube trying some changes from the server side which affects the patches and may result in some patches not functioning optimally.

**Comment by Dhrubaof2002** [comment]
Hey @KimYo2 which font are you using ?
