### ISSUE TITLE
question: 18.08.37 not available anywhere

### ISSUE THREAD

**Issue by NMBlanco** [inotia00/ReVanced_Extended#362]
### Application

YouTube

### Description

Just tried to download 18.08.37 from apkmirror but it's not uploaded anywhere.
Where did u get the version from? @in

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
It's the latest version and will take some time to be uploaded in apkmirror. Just be patient and you'll be able to download it from there itself.

**Comment by cyberboh** [comment]
[YouTube 18.08.36](https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-08-36-release/) , maybe 18.08.37 is typo

**Comment by tttsetsy** [comment]
No, it's on telegram

**Comment by cyberboh** [comment]
> No, it's on telegram

we need original apk

**Comment by Sappurit** [comment]
Can we extract from our root phone and combine into SAI nodpi apk by ourself ?

**Comment by NMBlanco** [comment]
> No, it's on telegram

Which telegram? @tttsetsy

**Comment by inotia00** [comment]
I temporarily added v18.08.36 to support list

**Comment by ILoveOpenSourceApplications** [comment]
YouTube v18.08.37 is now available.
