### ISSUE TITLE
bug: Remove 'Mixes' banner button

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#365]
### Type

Error at runtime

### Application

Version 18.07.35

### Bug description

![Screenshot_20230301-123306257 (1)](https://user-images.githubusercontent.com/73917917/222129752-04f43976-5dee-4558-8ace-ce613e85e246.png)

Tapping this button only opens an entire black screen...
While I like to see the top banner and would like a force show patch for it, i don't like this mixes button.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is not a bug
