### ISSUE TITLE
bug : Dislike Count won't change after Dislike

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#366]
### Type

Other

### Application

YT

### Bug description

The dislike Count won't increase or change after clicking Dislike. Like count os working properly. Dislike count only change if we Dislike the Video and then replay the video.

### Steps to reproduce

1. Start any Video.
2. Press dislike button.
3. The Dislike count won't change.

### Relevant log output

```shell
...
```

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
Having the same issue....
