### ISSUE TITLE
feat(patch): long press save button to open playlists dialog box

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#368]
### Application

YouTube

### Issue

this feature used to be present in youtube some time ago, i dont get why they removed such a useful feature. long pressing the save button opened a playlists box where you could choose the desired playlist to save to. but now you can only tap on the save button and it saves to the recently selected playlist. a patch to bring back this feature would be really useful for everyone.

### Patch

long press save button to open playlists dialog box so that one can choose which playlist to save to

### Motivation

i believe it was a useful feature for everybody

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Are you on the latest patch version? Cause I'm still getting this option.

**Comment by inotia00** [comment]
This is a feature already implemented on stock YouTube.

**Comment by ILoveOpenSourceApplications** [comment]
> can you check it once? because i havent been seeing this feature on my 2 accounts for some weeks now. when i long press save button, no dialog box opens.

Which version are you on currently?

**Comment by MondayNitro** [comment]
> > can you check it once? because i havent been seeing this feature on my 2 accounts for some weeks now. when i long press save button, no dialog box opens.
> 
> Which version are you on currently?

18.08.37, i even tried 18.02.xx and 18.03.xx and it doesnt work, can you check if if its still working for you?

**Comment by ILoveOpenSourceApplications** [comment]
Can you try if the same works in ReVanced?

**Comment by MondayNitro** [comment]
> Can you try if the same works in ReVanced?

its not even working on stock youtube downloaded from playstore, which version are you using?

**Comment by MondayNitro** [comment]
> ![Screenshot_20230302-213728~2](https://user-images.githubusercontent.com/117499019/222484353-87ad45ee-72e7-4f49-864f-ec1e50cbabc3.png) Yes, I'm still having the option as I mentioned earlier.

so you open a video, long press the save button, nothing more?

**Comment by ILoveOpenSourceApplications** [comment]
> so you open a video, long press the save button, nothing more?

Nothing more, nothing less.
