### ISSUE TITLE
ReVaced Extended

### ISSUE THREAD

**Issue by DrimTim2020** [inotia00/ReVanced_Extended#369]
There is some kind of bug with the new patches.
When you enter ReVaced Extended, it either throws you on the main page of YouTube or ends with a critical error.

**Comment by inotia00** [comment]
Please re-add the issue after meeting the prescribed form and label.

**Comment by DrimTim2020** [comment]
I reflashed the new file twice on 18.08.36 and the error was in both cases.

**Comment by DrimTim2020** [comment]
> Пожалуйста, повторно добавьте выпуск после соблюдения установленной формы и ярлыка.
I checked again but already on an older version of YouTube 08/18/34 and now it is not included in ReVaced Extended on it either.
Either throws on the main YouTube, or ends with a critical error.
You answer me why you are such a blockhead, when you write that there is a specific error, you fucking close the topic !!!!!
