### ISSUE TITLE
bug: ReVanced Extended turns into ReVanced after restarting the phone 

### ISSUE THREAD

**Issue by NearCram** [inotia00/ReVanced_Extended#37]
### Type

Error while patching

### Application

YouTube v 17.49.37 (Rooted Install)

### Bug description

Revanced Extended basically turns into ReVanced, even after typing the root command from the Telegram Group.

### Steps to reproduce

Step 1: Install Revanced throught builder with root

Step 2: Open the patched YT apk and restart your phone

Step 3 : Open the patched YT apk after restart

### Relevant log output

```shell
How do I get this?
```

### Device Environment

Android 13 (Evolution X Rom) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
read documentations and follow method
https://github.com/inotia00/revanced-documentation/wiki/Method-2.-Using-RVX-Builder-(Windows---MacOS---Linux---Android)

**Comment by NearCram** [comment]
Following "0." In that guide solved the issue. Thanks
