### ISSUE TITLE
Why is there no hdr-auto-brightness and copy-video-url patch?

### ISSUE THREAD

**Issue by lethinhrider** [inotia00/ReVanced_Extended#371]
### Application

YouTube

### Description

The original Revanced patch had 2 patches named copy-video-url and hdr-auto-brightness, were they removed in Revanced Extended or included in another patch?
copy-video-url will be useful for those who copy the link with the timestamp.
hdr-auto-brightness will make some HDR videos easier to look when they are too dark.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Kobewaxman** [comment]
The copy video URL feature is within the Overlay Buttons patch.

**Comment by inotia00** [comment]
The `copy-video-url` patch has been integrated into the `overlay-buttons` patch.

Removed `hdr-auto-brightness` patch from patch list as it no longer works properly in official ReVanced
