### ISSUE TITLE
Feature: disable thumbnails and profile icons

### ISSUE THREAD

**Issue by lukinhagf** [inotia00/ReVanced_Extended#373]
### Application

YouTube

### Issue

Feature: disable thumbnails and profile icons on comments, channel icon, channel banner

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
