### ISSUE TITLE
bug: clip button visibility issue 

### ISSUE THREAD

**Issue by ran-some** [inotia00/ReVanced_Extended#374]
### Type

Error while patching

### Application

YouTube v18.08.34

### Bug description

Clip button visible even if i enable hide button in flyout panel..

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_2023-03-02-07-37-36-104_app rvx android youtube](https://user-images.githubusercontent.com/126348889/222312881-d04fdd76-36ff-435a-bc4c-190fdce2e1b6.jpg)
![Screenshot_2023-03-02-07-37-43-315_app rvx android youtube](https://user-images.githubusercontent.com/126348889/222312895-0e8004ea-cf6d-4219-9551-43fa92197a34.jpg)
![Screenshot_2023-03-02-07-38-35-924_app rvx android youtube](https://user-images.githubusercontent.com/126348889/222312915-dcb40075-a41a-4e15-988f-d3fce03f1399.png)

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
`Hide the clip button`setting is hides the clip button in the button container, not the flyout panel.

Patch that hides the clip button in the flyout panel does not exist

**Comment by ran-some** [comment]
Sorry to say but i correct my mistake not flyout panel its not hide the clip button in button container see the images above as i attached.

**Comment by inotia00** [comment]
![Screenshot_2023-03-02-07-37-36-104_app rvx android youtube](https://user-images.githubusercontent.com/126348889/222312881-d04fdd76-36ff-435a-bc4c-190fdce2e1b6.jpg)
This is the flyout panel

![Screenshot_2023-03-02-07-38-35-924_app rvx android youtube](https://user-images.githubusercontent.com/126348889/222312915-dcb40075-a41a-4e15-988f-d3fce03f1399.png)
This is the setting to hide the button container

it hides the clip button in the button container, not the clip button in the flyout panel.
