### ISSUE TITLE
bug: Default playback speed controls not working 

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#375]
### Type

Error at runtime

### Application

Youtube 18.08.36

### Bug description

Only revanced overlay speed button is working, the default playback speed option in flyout menu is not working.

### Steps to reproduce

Used patches - "custom-branding-icon-afn-blue","custom-branding-name","custom-seekbar-color","custom-video-speed","default-video-quality","default-video-speed","enable-minimized-playback","enable-open-links-directly","enable-seekbar-tapping","force-premium-heading","hide-auto-captions","hide-autoplay-button","hide-button-container","hide-cast-button","hide-channel-watermark","hide-create-button","hide-crowdfunding-box","hide-endscreen-cards","hide-floating-microphone","hide-flyout-panel","hide-fullscreen-buttoncontainer","hide-general-ads","hide-info-cards","hide-mix-playlists","hide-pip-notification","hide-shorts-button","hide-shorts-component","hide-startup-shorts-player","hide-stories","hide-tooltip-content","hide-video-ads","materialyou","microg-support","optimize-resource","overlay-buttons","patch-options","return-youtube-dislike","sponsorblock","swipe-controls","theme"

### Relevant log output

```shell
.
```

### Device Environment

Android 12 , MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Dhrubaof2002** [comment]
![Screenshot_2023-03-02-14-32-32-550-edit_app.rvx.android.youtube.jpg](https://user-images.githubusercontent.com/64865031/222381591-286f60b2-f6af-41d9-b3ae-37ca22f2455d.jpg)

**Comment by inotia00** [comment]
Does that mean that if you change the speed in the attached screenshot it won't be reflected in the current video?

**Comment by Dhrubaof2002** [comment]
![Screenshot_2023-03-02-14-32-32-550-edit_app.rvx.android.youtube.jpg](https://user-images.githubusercontent.com/64865031/222381591-286f60b2-f6af-41d9-b3ae-37ca22f2455d.jpg)

    Yes, exactly that

**Comment by Dhrubaof2002** [comment]
> Does that mean that if you change the speed in the attached screenshot it won't be reflected in the current video?

Yes, exactly that

**Comment by harshal8** [comment]
> > Does that mean that if you change the speed in the attached screenshot it won't be reflected in the current video?
> 
> Yes, exactly that. But the overlay speed button is working perfectly fine

Set default video speed to auto  
Video settings<default video speed<auto

**Comment by Dhrubaof2002** [comment]
> > > Does that mean that if you change the speed in the attached screenshot it won't be reflected in the current video?
> > 
> > Yes, exactly that. But the overlay speed button is working perfectly fine
> 
> Set default video speed to auto  
> Video settings<default video speed<auto

I have save video speed enabled , so your suggestion wouldn't do anything.

**Comment by sleepingiv** [comment]
This patch fixes this issue - https://github.com/inotia00/revanced-patches/releases/tag/v2.164.24

**Comment by sleepingiv** [comment]
Hey @inotia00 this issue is back after 2.168.1

**Comment by sleepingiv** [comment]
Hey inotia, this is an old issue and is back after the mentioned patch.

**Comment by inotia00** [comment]
At least for me this issue has never occurred.

I can't fix issues that don't reproduce on my device.

**Comment by sleepingiv** [comment]
Should I close this as completed and open a new issue with proper explanation, screen recording and patchlog ?

**Comment by inotia00** [comment]
nah.. there is no debug patch for RVX, so extracting the logcat is meaningless unless it is the crash log

Someone reproducing this issue should fix it
(requires someone's contribution)

**Comment by sleepingiv** [comment]
Hey inotia , I am providing options.toml , patchlog , settings.json . See if you can reproduce the issue.

Options.toml - https://drive.google.com/file/d/18O4Cz29DY8L9ydVBje1q_nUiyXtDyU55/view?usp=drivesdk

Patchlog.txt - https://drive.google.com/file/d/18NeMYDWTvvvxBI1oI0jZXXs_QUD8Rr5I/view?usp=drivesdk

Settings.json - https://drive.google.com/file/d/18IF6sYtpG2IiKKr8vWF-p9cADlpFtqQF/view?usp=drivesdk
