### ISSUE TITLE
bug: custom playback speed not working after account switch

### ISSUE THREAD

**Issue by harshal8** [inotia00/ReVanced_Extended#376]
### Type

Other

### Application

YouTube 18.08.37

### Bug description

I have noticed the issue of custom playback speed in the latest patches of rvx, when I switch to another Google account, the original playback speed comes instead of the custom playback speed

### Steps to reproduce

NA

### Relevant log output

```shell
NA
```

### Screenshots or videos

![Screenshot_2023-03-02-09-10-54-27](https://user-images.githubusercontent.com/84259098/222335750-7ff0d272-0a2a-4e1e-a0f2-01f8219c5089.jpg)
![Screenshot_2023-03-02-09-11-32-66](https://user-images.githubusercontent.com/84259098/222335764-d618062a-2311-4efc-ac6b-2ecbe3915f78.jpg)

### Solution

NA

### Additional context

[patchlog.txt](https://github.com/inotia00/ReVanced_Extended/files/10867779/patchlog.txt)

### Device Environment

Android 10, Realme UI 1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Just force close and relaunch the app when switching accounts
it solves issue

**Comment by harshal8** [comment]
Still same

**Comment by inotia00** [comment]
hmm it's weird I can't reproduce it at all

Very occasionally when this issue reproduced, force close and relaunch resolved the issue.

Anyway, this issue will be reopened for archival purposes.

**Comment by harshal8** [comment]
I can change the default(original) playback speed when the default playback speed is set to auto but when it is set to normal I cannot change the default(original) playback speed which appears on screen, When I set custom playback speed (like 2.2)
![Screenshot_2023-03-03-09-38-48-06](https://user-images.githubusercontent.com/84259098/222631166-df4ba4bb-b904-4937-9283-36fe5bfe0151.jpg)
![Screenshot_2023-03-03-09-46-20-15](https://user-images.githubusercontent.com/84259098/222631195-171e7f6e-d604-40bc-9edb-a099e06b4884.jpg)
![Screenshot_2023-03-03-09-46-23-69](https://user-images.githubusercontent.com/84259098/222631229-682b5470-722d-405b-82c2-37375e275ba7.jpg)
 there it works but it doesn't show on flyout panel

**Comment by harshal8** [comment]
I checked the old version of RVX and from that I know that this issue started from v2.162.1 patches.

**Comment by inotia00** [comment]
ah, this is impossible to fix due to the limitations of the currently implemented method

If a value that exists in the custom speed list does not exist in the default speed list, it is normal to shown it as such.

This is an unfixable issue
(because all patches work independently)

Also, there are no plans to fix it in the future.
