### ISSUE TITLE
bug: Enable-old-style-quality-layout not working 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#377]
### Type

Error at runtime

### Application

YouTube v18.08.37

### Bug description

Even after patching with enable-old-style-quality-layout and having it turned on, the new quality layout is the one showing up. 

### Steps to reproduce

Step 1: Patch with enable-old-style-quality-layout.
Step 2: Assure that it's turned on.
Step 3: Go into quality settings of any video and the new quality layout shows up.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

Enable-old-style-quality-layout is enabled:
![Screenshot_20230302-130905~2](https://user-images.githubusercontent.com/117499019/222362983-4b801d61-94bc-4d95-8e75-60be2c036025.png)

But it's not working when playing a video:
![Screenshot_20230302-130931~2](https://user-images.githubusercontent.com/117499019/222363073-08e20949-c3ec-4441-98c9-39130d570b7a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
it's really weird
Maybe Google is testing A/B testing on YouTube

Please test to see if the issue reproduces on RVX v18.06.41, and also on the official ReVanced (v18.03.36) and leave results in the comments.

**Comment by ILoveOpenSourceApplications** [comment]
Let me check and I'll update.

**Comment by ILoveOpenSourceApplications** [comment]
Okay, in RVX only I seem to have this issue. Even in version 18.06.41 I'm still getting the new quality layout. But in ReVanced, I'm getting the old quality layout, though initially after my installation I was welcomed with the old UI layout after which I force stopped the app and was welcomed with the new UI.

**Comment by ILoveOpenSourceApplications** [comment]
The issue seems to exist with Extended only atm anyway.

**Comment by ILoveOpenSourceApplications** [comment]
> okay. In the next release I'll roll back to follow the official ReVanced's method for patching the old quality layout

Okay, let's see if that can fix the issue or not.

**Comment by inotia00** [comment]
Can you test with revanced-patches-v2.164.12?

**Comment by ILoveOpenSourceApplications** [comment]
I just did

**Comment by ILoveOpenSourceApplications** [comment]
And yeah, no luck. I saw the old quality layout for a sec before it reverted back to the new one.

**Comment by ILoveOpenSourceApplications** [comment]
Okay, definitely something to do with the latest YouTube app version. I tried RVX patches on ReVanced supported YouTube, which is 18.03.36. From the patches that I applied only default video speed and default video quality patches failed to apply. But yeah, the old quality layout is there.

**Comment by ILoveOpenSourceApplications** [comment]
In incognito it's working fine, and if you're really quick while playing a video and going into the quality settings you'll get the old style but after that it'll be the new one.

**Comment by eks28** [comment]
Same here just tested with new patches and not working but everything else working

**Comment by ILoveOpenSourceApplications** [comment]
And now when using enable-old-layout, the enable-old-quality-layout is working fine. So those are the conditions under which it works.

**Comment by eks28** [comment]
Thanks but still doesn't work (at least for me) unless turn on old version/layout setting

**Comment by ILoveOpenSourceApplications** [comment]
Yeah, it's still like how it was.

**Comment by inotia00** [comment]
Can you test with revanced-patches-v2.164.18?

**Comment by ILoveOpenSourceApplications** [comment]
Nope, still it's like how it was early.

**Comment by ILoveOpenSourceApplications** [comment]
I think my account is undergoing some A/B testing from YouTube, which is why the old quality layout isn't working. And hence why I go into incognito/use the old layout, I get out of the A/B testing and hence the function working properly.

**Comment by ILoveOpenSourceApplications** [comment]
So I believe your patch is actually working fine for those who all aren't going through this A/B testing. But for those who are going through this testing phase, the patch is broken and the fixes aren't doing anything.

**Comment by ILoveOpenSourceApplications** [comment]
Then again, when I tried RVX patches on an older version (18.03.36) of YouTube, I seemingly got the patch to work fine. Which when considered all together is a weird environment in which the patch fails.

**Comment by ILoveOpenSourceApplications** [comment]
Currently the old quality layout patch is functioning as it should and hence I'll close this issue.

**Comment by inotia00** [comment]
It was really weird.. Why was this patch broken? Anyway, I'm glad the issue is resolved

**Comment by b1ackfa1c0n** [comment]
I still got this bug, I turned on incognito mode and the patch seems to work fine, how can I get out of this youtube a/b testing thing to use my account normaly?

**Comment by b1ackfa1c0n** [comment]
For any one having this issue in the future, I fixed it by enabling "enable old layout" in the experimental tab inside the miscellaneous section.

**Comment by ILoveOpenSourceApplications** [comment]
Yeah, something from the server side is affecting the patch to not work. Unless this change comes to everyone this can't be fixed is what I believe.

**Comment by inotia00** [comment]
Fixed in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
