### ISSUE TITLE
Loading /Buffering Forever Problem

### ISSUE THREAD

**Issue by Tronak007** [inotia00/ReVanced_Extended#378]
Since Yesterday I'm Facing Problem Any Video I'll Play It Plays For A While Then It Buffers And Never Play Again, This Is Happening With All The Videos, It Happens Even If I Close The Video And Play It Again It Plays A Little Bit And Then Goes Buffering And It Keeps On Like That Forever Even On Wifi And Mobile Data, 

I Tried Reinstall Rebuild And Almost Everything I Thought Any Other Fix Or Trick To Solve The Problem, Please Help, 

As I Found Out With Me This Happens When I Login To Google Account Through MicroG Without Logging In It Works Fine, Any Fix Or Any Help Anyone Can Provide Please, 

Tried To Re Install MicroG Also Doesn't Helps

Nothing Phone Android 13
Youtube Version Is 18.08.37

![Screenshot_20230302-154414](https://user-images.githubusercontent.com/106589892/222399675-3b8fbd86-bf49-4d05-9d99-a047bbaee9de.png)
![Screenshot_20230302-154546](https://user-images.githubusercontent.com/106589892/222399784-f060ef74-ef79-44fd-bb6d-2bd30e82bfbf.png)

**Comment by ILoveOpenSourceApplications** [comment]
This is a known issue. It's not the fault of RVX YouTube, rather it's an issue regarding micro-g. There's no solution rather other than to use a VPN service atm.

**Comment by ILoveOpenSourceApplications** [comment]
#141
