### ISSUE TITLE
bug: Playback Stops When Logged In

### ISSUE THREAD

**Issue by r0br0y7** [inotia00/ReVanced_Extended#379]
### Type

Other

### Application

ReVanced Extended v18.08.37

### Bug description

When you're logged in with your Google Account in ReVanced Extended, the video playback stops at some point and will never finish. No issues when you are logged out but you won't see your subscriptions.

### Steps to reproduce

Log-in to your Google Account and play any video.

### Relevant log output

```shell
N.A.
```

### Solution

Logout your Google Account

### Additional context

N.A.

### Device Environment

OneUI 4.1 Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
Yes, same. Idk, maybe its from server side? I experienced the same v18.06.41 (patch v2.163.1), so I updated to the latest v18.08.37 (patch v2.164.11), but the issue is still there.

**Comment by ILoveOpenSourceApplications** [comment]
#141

**Comment by ILoveOpenSourceApplications** [comment]
This is a known issue. It's not the fault of RVX YouTube, rather it's an issue regarding micro-g. There's no solution other than to use a VPN service atm.

**Comment by ILoveOpenSourceApplications** [comment]
But can you guys also try installing ReVanced and see if this issue exists there also? Just to confirm that it's an issue related to micro-g or not.

**Comment by r0br0y7** [comment]
> This is a known issue. It's not the fault of RVX YouTube, rather it's an issue regarding micro-g. There's no solution other than to use a VPN service atm.

Tried using VPN but playback still stops.

**Comment by ILoveOpenSourceApplications** [comment]
> Tried using VPN but playback still stops.

That is one of the few workarounds to get around this issue. I say either to keep trying or go back to using the ad world called stock YouTube. Or be a rooted user, that's an option too.

**Comment by inotia00** [comment]
Method #1. Use ROOT build
Method #2. Use a different Google Account

Currently, there is no clear solution other than this.
