### ISSUE TITLE
question: Custom Branding Name patch not taking name from Options file

### ISSUE THREAD

**Issue by shreyjain1998** [inotia00/ReVanced_Extended#38]
### Application

YouTube

### Description

I want my app name to be Revanced X so I have updated options.toml file as below

['custom-branding-name']
appName = "ReVanced X"

I've tried by including/excluding Custom Branding Name & Patch Options patches but app name doesn't change according to what I put in file.

I'm using rvx-builder-win with the latest version.
Please let me know if I'm doing anything wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Are you using it in root environment?

**Comment by shreyjain1998** [comment]
No. I'm just doing it from rvx-builder-win app in windows laptop.

**Comment by inotia00** [comment]
nah I mean, did you include `microg-support` patch?

**Comment by shreyjain1998** [comment]
No, I'm not patching for root device and yes, I had included microg-support patch as well.

The thing is I was updating the appName in options file and trying to patch but I'm not very sure how exactly this process works.

Anyways thanks for your responses and I'll try to build by removing the options file again.

**Comment by inotia00** [comment]
Did you include `patch-options`?

**Comment by shreyjain1998** [comment]
Hi, yes I was including patch-options as well. But, now I'm able to rename the youtube app successfully. Can we do it same with yt music app too?

**Comment by inotia00** [comment]
ability to change the app name has not yet been implemented in YouTube Music
but will support later

**Comment by shreyjain1998** [comment]
Ok thanks
