### ISSUE TITLE
bug: ambient mod

### ISSUE THREAD

**Issue by Fouad0418** [inotia00/ReVanced_Extended#380]
### Type

Error while patching

### Application

18.08.35

### Bug description

When I install youtube revanced at firs 3 app openings ambient mode works than it returns to the old ui

### Steps to reproduce

When I install youtube revanced at firs 3 app openings ambient mode works than it returns to the old ui

### Relevant log output

```shell
Don't know what you mean
```

### Solution

Reset the app but only temporary fix as i said at the third opening it returns to old ui 

### Device Environment

S21 Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Can you share a screenshot showing the same?

**Comment by inotia00** [comment]
ambient mode is included in the new layout, the new layout follows your google account status

ReVanced / ReVanced Extended has nothing to do with it

**Comment by Fouad0418** [comment]
> ambient mode is included in the new layout, the new layout follows your google account status
> 
> ReVanced / ReVanced Extended has nothing to do with it

So we cant use ambient mode

**Comment by inotia00** [comment]
Simply create a new Google account
A new layout will be applied

**Comment by Fouad0418** [comment]
> 

But works only on the new account ?

**Comment by ILoveOpenSourceApplications** [comment]
Can you share a screenshot of the issue you're facing?

**Comment by inotia00** [comment]
How to force the new layout is unknown to anyone other than Google

I'm just giving one example where you can use the new layout.
(make a new account)

As I said before, the new layout follows the state of your Google account, not ReVanced or ReVanced Extended.

Contact to Google

**Comment by Fouad0418** [comment]
> How to force the new layout is unknown to anyone other than Google
> 
> I'm just giving one example where you can use the new layout. (make a new account)
> 
> As I said before, the new layout follows the state of your Google account, not ReVanced or ReVanced Extended.
> 
> Contact to Google

After using one day the new account ambient mode appeared to my old account thank you so muchh!!
