### ISSUE TITLE
bug: hide community post in home and subscription page not working properly

### ISSUE THREAD

**Issue by ran-some** [inotia00/ReVanced_Extended#382]
### Type

Error while patching

### Application

YouTube v18.08.37

### Bug description

Community post shows in home and subscription page both in i enable anyone of them

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Device Environment

Android 11, miui 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
I can't seem to replicate this issue. Can you share a video with the issue?

**Comment by inotia00** [comment]
Perhaps, this is guessed as an A/B test.

Because it was possible to reproduce from another Google account.

It will be fix in the next release

**Comment by ILoveOpenSourceApplications** [comment]
Google's doing something, which is why so many patches which worked fine previously started breaking now. Especially with the loading issues that popped up.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.12)

**Comment by devilboy1122** [comment]
![Screenshot_2023-03-03-14-23-35-1283108335](https://user-images.githubusercontent.com/79780868/222670751-254eb353-802c-4ea4-b204-6c1a236b9116.png)
The new patch didn't show YouTube dislike count
