### ISSUE TITLE
bug: clip button showing in button container

### ISSUE THREAD

**Issue by ran-some** [inotia00/ReVanced_Extended#383]
### Type

Error while patching

### Application

YouTube v18.08.37

### Bug description

Hide clip button in button container not working properly its still visible in player. See video i am talking about this.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

https://user-images.githubusercontent.com/126348889/222452029-3b0ab8cc-9aa2-47c1-a9ab-7ca8b51b86ac.mp4

### Device Environment

Android 11, MIUI 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The patch in the attached screenshot has not been implemented
So this is not a bug
