### ISSUE TITLE
bug: After a while it cuts out

### ISSUE THREAD

**Issue by IeFHC233** [inotia00/ReVanced_Extended#384]
### Type

Error at runtime

### Application

V18.07.35

### Bug description

After about 40 seconds, each video freezes (loading view) and can no longer be played 

### Steps to reproduce

Nothing

### Relevant log output

```shell
I don't know how
```

### Screenshots or videos

Link to the movie https://www.mediafire.com/file/e811dt8ckg3291h/Record_2023-03-02-15-45-47.mp4/file

### Device Environment

Android 13 Realme ui 4 Realme GT master edition f.01 update

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#141

**Comment by ILoveOpenSourceApplications** [comment]
This is a known issue. It's not the fault of RVX YouTube, rather it's an issue regarding micro-g. The workarounds are:
1. Use a VPN and is if it works.
2.  Be a rooted user.
3. Start a new Google account
4. Use in incognito.

**Comment by IeFHC233** [comment]
Using YT vanced before, I didn't have a problem with micro g And I wouldn't change this version if it wasn't for the YT blockade in the form of too old version of the application, and as you know, vanced is no longer supported

**Comment by ILoveOpenSourceApplications** [comment]
> Using YT vanced is no longer supported.

I don't think that's the case. There are still some people who continues using Vanced and currently the ReVanced team is producing a patch to remove the ads in the UI, so that it can be used by users having older Android versions.

**Comment by IeFHC233** [comment]
When more or less will there be a version for older phones, because maybe it's a problem?
Works well in incognito and without an account but I won't watch yt without an account

**Comment by ILoveOpenSourceApplications** [comment]
> When more or less will there be a version for older phones, because maybe it's a problem? 

What's a problem?

> Works well in incognito and without an account but I won't watch yt without an account

Yes, because micro-g isn't required in these scenarios.

**Comment by IeFHC233** [comment]
I've installed loads of different versions of microg and it doesn't work. Don't you have some alternative version of microg?

**Comment by ILoveOpenSourceApplications** [comment]
> I've installed loads of different versions of microg and it doesn't work. Don't you have some alternative version of microg?

No version of micro-g fixes this issue. They're looking into it, but so far nothing.
