### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Andres1001YT** [inotia00/ReVanced_Extended#385]
### Type

Error at runtime

### Application

YouTube ReVanced Extended v18.08.37

### Bug description

Cuando reproduzco un vídeo se detiene y no pasa de 1 minuto y la calidad del video cambia y se limita a HD cuando realmente era un vídeo Full HD 

### Steps to reproduce

Al iniciar cualquier vídeo solo hay que esperar entre 49 a 59 segundos y dejara de cargar

### Relevant log output

```shell
No tengo idea de que significa esto pero si me explican no tengo problema con dar la información necesaria
```

### Screenshots or videos

![Screenshot_2023-03-02-10-21-41-213_app rvx android youtube](https://user-images.githubusercontent.com/126798063/222471729-cc8fca3d-3b13-40ed-b664-d7c460aeef97.jpg)
![Screenshot_2023-03-02-10-21-31-391_app rvx android youtube](https://user-images.githubusercontent.com/126798063/222471742-0e1651fc-2d14-4c74-92f6-756b82eb49db.jpg)

### Solution

Creo que el vídeo se corrompe pero no soy experto así que no tengo ni idea de cómo ayudar con eso 

### Additional context

Vine de Youtube Vanced por que dejó de funcionar les deseo lo mejor con este proyecto 

### Device Environment

Android 12 MIUI Global 13.0.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#141

**Comment by ILoveOpenSourceApplications** [comment]
This is a known issue. It's not the fault of RVX YouTube, rather it's an issue regarding micro-g. The workarounds are:
1. Use a VPN and is if it works.
2.  Be a rooted user.
3. Start a new Google account
4. Use in incognito.

**Comment by ILoveOpenSourceApplications** [comment]
> Hello, I set up a new account as you said and if the videos load, luckily I had 2 accounts and the main one fails but the secondary one does not have that error the videos play without any problem but well in any case thanks :)

You're welcome. Hopefully a fix would come soon enough. You can close this issue for now.
