### ISSUE TITLE
bug: Keeps buffering, cannot play full video.

### ISSUE THREAD

**Issue by dion1319** [inotia00/ReVanced_Extended#387]
### Type

Error while patching

### Application

YouTube Revanced 18.06.39

### Bug description

Videos will play at the start but buffers and stops loading when about 1/4.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#141

**Comment by ILoveOpenSourceApplications** [comment]
This is a known issue. It's not the fault of RVX YouTube, rather it's an issue regarding micro-g. The workarounds are:

Use a VPN and is if it works.
Be a rooted user.
Start a new Google account
Use in incognito.
