### ISSUE TITLE
feat(patch): Proposal to add a feature to notify YouTube Revanced  Extended users of available updates

### ISSUE THREAD

**Issue by RednGreen777** [inotia00/ReVanced_Extended#388]
### Application

YouTube

### Issue

_The YouTube Revanced Extended application does not have a feature that notifies users when updates or patches are available, this could lead to several problems._ 

● _Users could miss out on important features or improvements that have been added to the app._ 

● _In addition (in the event that a possible security patch is added), without the appropriate security patches, users could be exposed to potential security flaws that could compromise the security of their device or personal data._ 

● _Finally, users could encounter compatibility issues with other applications or their device in general, if the application is not regularly updated. Having a feature to notify users when updates are available would mitigate these risks and ensure an optimal and secure user experience._

### Patch

_Add a notification feature for updates and patches
When opening the application, Allowing us to download the latest patch or application updates from this text notification._

**_Here are some illustrated examples:_** 

_- What users should expect to see when an update has been announced and they open the YouTube Revanced Extended for the first time in their session_
![banner](https://user-images.githubusercontent.com/124512514/222509415-295cf085-cd5f-4bbb-a708-be0f02c50063.png)

![R jpeg-1](https://user-images.githubusercontent.com/124512514/222509418-56555e4e-6574-4aa3-b9da-c9be44e6ba60.jpg)
 _- What users should expect to see as Notification in the status bar if an update has been announced but they are/not in the YouTube Revanced Extended application_ 

P.-S.: I would also like to add that an update checker could possibly be an option to add too.

### Motivation

_I humbly suggest adding a very useful feature for the users of the application. This feature would alert them when updates or patches are available. It would be wise to consider displaying a clear and visible message when opening the application so that users can update their application quickly from this message and take advantage of the latest improvements available so it would make the process of updating the application much easier for users, thus avoiding longer and more tedious procedures._

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by hoang-himself** [comment]
Such feature is dependent on the Revanced Manager, which is not in the scope of RVX.

**Comment by inotia00** [comment]
Perhaps, you are referring to the built-in update notifications, but I have never considered this.

Because I don't distribute the apk anymore

instead, use [github notification channel](https://t.me/revanced_extended_repo)
