### ISSUE TITLE
bug: video freezes while watching

### ISSUE THREAD

**Issue by guisz1** [inotia00/ReVanced_Extended#390]
### Type

Error while patching

### Application

V18.08.37

### Bug description

the video simply freezes and does not load beyond the point where it is, this occurs between 50 seconds and 2 minutes of video

### Steps to reproduce

Start watching a vídeo With ad and that ocurrea

### Relevant log output

```shell
I dont receive a log
```

### Device Environment

Android 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
