### ISSUE TITLE
Unending buffer after ~1 minute of watchtime

### ISSUE THREAD

**Issue by EthanParlsey** [inotia00/ReVanced_Extended#391]
### Application

YouTube

### Description

After 1 minute of watching any video, a loading circle appears and I can't continue watching that video. It only affects one of my accounts, is this on my end? Some sore of account restriction?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
