### ISSUE TITLE
bug: videos not loading

### ISSUE THREAD

**Issue by L1nkBest** [inotia00/ReVanced_Extended#392]
### Type

Other

### Application

Revanced extended
Version 18.08.37

### Bug description

When I was watching video in this app
After 40 or less seconds it starts load the rest of the video but it never stop even on background it will not stop loading

### Steps to reproduce

Step 1:download microG
Step 2:download revanced extended or revanced
Step 3:watch any video

### Relevant log output

```shell
None
```

### Screenshots or videos

![Screenshot_20230302_233549](https://user-images.githubusercontent.com/126828706/222575497-4b1b02b2-c0f4-4294-b53b-597afa74310c.jpg)

### Solution

None

### Device Environment

Android 11 honor 50 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
