### ISSUE TITLE
ReVanced buffering

### ISSUE THREAD

**Issue by anggieayana** [inotia00/ReVanced_Extended#393]
### Type

Error at runtime

### Application

Revanced

### Bug description

video buffering every 1 minute and must be refreshed from the beginning again. always over and over.signal good. 
![Screenshot_2023-03-03-07-55-45-959_app revanced android youtube](https://user-images.githubusercontent.com/17428047/222593246-226862ba-2bd4-48c7-a17d-20a8c86c10ab.jpg)

### Steps to reproduce

A

### Relevant log output

```shell
A
```

### Screenshots or videos

![Screenshot_2023-03-03-07-55-45-959_app revanced android youtube](https://user-images.githubusercontent.com/17428047/222593457-b3a78397-e385-4c26-947c-90b8ff36ae63.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
