### ISSUE TITLE
bug: <title>unable to patch with magisk module if youtube app isn't a system app

### ISSUE THREAD

**Issue by YuzurihaS** [inotia00/ReVanced_Extended#394]
### Type

Error while patching

### Application

tested on
YouTube v17.49.37
YouTube v18.03.36
YouTube v18.08.37

### Bug description

If YouTube is not a system app, patching will fail.

### Steps to reproduce

When YouTube isn't a system app
Step 1: patch the magisk module

Package com.google.android.youtube installed for user: 0
! Please uninstall updates for YouTube app and try again
! Installation failed

### Relevant log output

```shell
- Extracing module files
- System architecture: arm64-v8a
Package com.google.android.youtube installed for user: 0
! Please uninstall updates for YouTube app and try again
! Installation failed
```

### Screenshots or videos

![a](https://user-images.githubusercontent.com/93084167/222631558-4f39e114-8bd9-4377-a926-60a867e6f9cb.jpg)

### Device Environment

Android 13, ColorOS for OnePlus

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
There is no patching method using the magisk module.
Use the patching method outlined in the documentation.
https://github.com/inotia00/revanced-documentation/wiki

**Comment by YuzurihaS** [comment]
Sorry I mean installing.

I just used termux and systemizer module and made YouTube a system app. And now the installation of revanced extended is successful.

But still, thought this is worth mentioning, as revanced extended seems to not recognize that YouTube was already installed when the YouTube app isn't a system app.

Like in this case on ColorOS from OnePlus, or on some other phones people might be using.
