### ISSUE TITLE
Selective buffering

### ISSUE THREAD

**Issue by MrBeyblade** [inotia00/ReVanced_Extended#395]
### Type

Error at runtime

### Application

Youtube revanced 

### Bug description

Everytime i want to watch a video after a period of time it buffers but if i go into incognito mode everything works maybe its because of my google account? I dont know but my wifi is good so thats not it

### Steps to reproduce

Watch a youtube video and wait

### Relevant log output

```shell
None
```

### Screenshots or videos

![Screenshot_20230303_095756_ReVanced Extended](https://user-images.githubusercontent.com/106775188/222677069-cb68ad03-0f0e-40bf-87ea-19cefb67b7d0.jpg)

### Solution

It works in incognito but then my data is not accesable 

### Additional context

Its with almost every video

### Device Environment

Samsung galaxy A 51 

Android 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#141
