### ISSUE TITLE
bug: A "gap" where the notification bar would be that isn't present in regular ReVanced 

### ISSUE THREAD

**Issue by Spacellary** [inotia00/ReVanced_Extended#396]
### Type

Cosmetic Bug inside YouTube

### Application

YouTube 18.08.38
Patches 2.164.15
Integrations 0.99.15

### Bug description

There's an additional "gap" at the top where the notification bar would be in Extended that doesn't happen in regular ReVanced.

_Sorry if it is a duplicate but I wasn't able to find the same issue reported here._

### Steps to reproduce

Open any video and tap the screen show the player controls.

### ReVanced:
![Screenshot_2023-03-03-22-47-10-503_app revanced android youtube](https://user-images.githubusercontent.com/39604793/222869519-25692f2b-0c3a-4bdf-bb5e-e6389a59068c.jpg)

### ReVanced Extended:
![Screenshot_2023-03-03-22-46-04-439_app rvx android youtube](https://user-images.githubusercontent.com/39604793/222869552-aef2da73-60fe-4de9-86a2-dcc04855ca20.jpg)

### Device Environment

REDMI NOTE 11 (4G GLOBAL)
Android 12, MIUI 13.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/271
