### ISSUE TITLE
feat(patch): built in audio equalizer

### ISSUE THREAD

**Issue by Aditya646754** [inotia00/ReVanced_Extended#397]
### Application

YouTube

### Issue

Audio eqalizer

### Patch

I want audio equalizer in revanced youtube.

### Motivation

since some videos plays in low sound volume or listning music in youtube without revanced music.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Aditya646754** [comment]
![Screenshot_2023-03-09-14-02-01-001_com android musicfx](https://user-images.githubusercontent.com/126933641/223965140-5559d852-53a2-43f1-b606-0f92249004ef.jpg)
Please add this function in youtube revanced, and can you tell me when it will add. Thanks.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
