### ISSUE TITLE
feat(patch): to hide sponserblock settings overlapping & clip flyout button

### ISSUE THREAD

**Issue by ran-some** [inotia00/ReVanced_Extended#398]
### Application

YouTube

### Issue

1- sponser block setting overlaps cross(x) icon when i open endscreen overlay
2- clip button shows in (...) button container
See in pictures

### Patch

![Screenshot_2023-03-04-08-42-44-419_app revanced android youtube](https://user-images.githubusercontent.com/126348889/222873285-da90d701-e4dc-4bea-9743-2bfdc774dba6.jpg)
![Screenshot_2023-03-04-08-42-38-133_app revanced android youtube](https://user-images.githubusercontent.com/126348889/222873289-3f781e21-3158-4d2c-8959-46ec122e6e61.jpg)

### Motivation

these icons irritating me & others also..

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
