### ISSUE TITLE
bug: breaking news self shows only one result

### ISSUE THREAD

**Issue by ran-some** [inotia00/ReVanced_Extended#399]
### Type

Error while patching

### Application

YouTube v18.08.38

### Bug description

Breaking news self shows only one result
See the pictures.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_2023-03-04-08-54-18-756_app revanced android youtube](https://user-images.githubusercontent.com/126348889/222873540-8afd00b3-caea-4403-b663-461a9c4ddccd.jpg)

### Device Environment

Android 11, Miui 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a YouTube bug, not a ReVanced bug.
