### ISSUE TITLE
"Create a Short" and "Upload a video" dosen't work.

### ISSUE THREAD

**Issue by gimmee94** [inotia00/ReVanced_Extended#4]
### Type

Other

### Bug description

So whenever I am trying to upload a video using the Create Button, the app just crashes. Same thing happens if I click on the "Create a Short" option. "Go live" and "Create a post" options are working but "Create a Short" and "Upload a video" both result in crash.

### Steps to reproduce

Step 1: Turn on the '+' Create button from the revanced extended settings.
Step 2: Let the app restart.
Step 3: Click the '+' button at the bottom middle and choose "Upload a video".
Step 4: App will crash.

### Relevant log output

```shell
No Logs.
```

### Screenshots or videos

https://dai.ly/kfOpKGQIqddtWZyrK6D

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by KevinNitroG** [comment]
I think you should try to build RVX by using another tool. I used to build RVX with a repo which I don't remember ((: and it had that problem like you are facing. I'm using Revanced Manager now and it works fine.

**Comment by inotia00** [comment]
This is an outdated issue
It works normally in the latest version.
