### ISSUE TITLE
selected patch warning display

### ISSUE THREAD

**Issue by bbknql** [inotia00/ReVanced_Extended#40]
### Type

Error while patching

### Application

os ; crdroid10 --rooted magisk
youtube 17.45.36 (nodpi)
mnager 0.0.42
microG ; not installed

### Bug description

try to use extendded version following xda thread here ;

https://forum.xda-developers.com/t/revanced-revanced-extended-guides-useful-links.4523967/
but showing like an attachment below

note : 
i dont know about correlations about DCMA takedown mentioned by revanced telegram channel with my error.
yesterday im following xda thread and works. but not today. 

### Steps to reproduce

following xda thread 

### Relevant log output

```shell
none
```

### Screenshots or videos

![Screenshot_20221225-013445634](https://user-images.githubusercontent.com/103966351/209448034-c07cc93b-e0f7-433a-88f9-50207f38e407.jpg)
![Screenshot_20221225-013452049](https://user-images.githubusercontent.com/103966351/209448035-89e9cf87-b83b-459d-a252-90586b27ffb0.jpg)
![Screenshot_20221225-013457963](https://user-images.githubusercontent.com/103966351/209448036-3ed05a95-7fd5-4e9d-a89d-ef77b3493274.jpg)
![Screenshot_20221225-013509197](https://user-images.githubusercontent.com/103966351/209448037-98ea2102-1529-4374-813c-22842aa0cddf.jpg)
![Screenshot_20221225-014629646](https://user-images.githubusercontent.com/103966351/209448038-7b1093ea-d941-4d81-84e8-1ff1125b185c.jpg)
![Screenshot_20221225-015032031](https://user-images.githubusercontent.com/103966351/209448105-6448da46-f769-404b-a4d1-c156cb92e076.jpg)

### Device Environment

android 10 
crdroid 6.13 --magisk v25.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
1. You are using the wrong version of ReVanced Manager
The current version of ReVanced Manager recommended by the latest patch is v0.0.51/0.0.52
2. The YouTube version you use for the patch is incorrect
Currently the latest patch recommends YouTube version is v17.49.37
3. That url is not a guide written by me. Read the documentations [wiki](https://github.com/inotia00/revanced-documentation)

**Comment by bbknql** [comment]
thankyou dev
working now with your guide
