### ISSUE TITLE
bug: `hide-cast-button` gets included without acknowledgement

### ISSUE THREAD

**Issue by hoang-himself** [inotia00/ReVanced_Extended#400]
### Type

Error while patching

### Application

YouTube v18.08.38

### Bug description

I did not select `hide-cast-button` but it is somehow included in the patches

### Steps to reproduce

Patch selection:

```json
["client-spoof","enable-minimized-playback","enable-open-links-directly","enable-seekbar-tapping","force-premium-heading","force-vp9-codec","hide-create-button","hide-crowdfunding-box","hide-floating-microphone","hide-general-ads","hide-video-ads","microg-support","optimize-resource","overlay-buttons","return-youtube-dislike","sponsorblock"]
```

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20230304_122606_YouTube](https://user-images.githubusercontent.com/10150902/222877966-5b60931a-9bba-4606-bf4d-f8505b5aeff5.png)

### Device Environment

Android 13, OneUI 5.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#274
