### ISSUE TITLE
feat(patch): hide YouTube Music icon (in player)

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#401]
### Type

Error at runtime

### Application

Version 18.07.35 non-root 

### Bug description

![Screenshot_20230304-064534744 (1)](https://user-images.githubusercontent.com/73917917/222878394-5fba1778-b471-41be-9670-7b0eed531af7.png)
 
I have already disabled all YTM stuff in player flyout menu, but still seeing this button when playing music videos. Is it because I have installed stock YTM aswell? 
https://youtu.be/qGWZUtfV3IU

**Comment by inotia00** [comment]
There is no patch for this

If necessary, I will change the label of this issue to the patch-request

**Comment by anyujinie** [comment]
Ok gotchu.

Thx for changing it to patch request 🙂

**Comment by hoang-himself** [comment]
> Also tapping that icon doesn't even open RVX Music, no it opens stock YTM.... I'm non-root.

Sounds like you haven't set supported web addresses. Just go to the RVX Music app info in Android's settings and enable all web addresses in Defaults.

**Comment by anyujinie** [comment]
> Sounds like you haven't set supported web addresses. Just go to the RVX Music app info in Android's settings and enable all web addresses in Defaults.

I have that already enabled. Please don't make useless assumptions. 

![Screenshot_20230305-145809950 (1).png](https://user-images.githubusercontent.com/73917917/222964942-4397ff7a-0eb2-4023-b343-6a288ef66a48.png)

And yes i use the stock logo and YouTube Music name for RVX Music

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.164.21](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.21)
