### ISSUE TITLE
feat(patch): change the position of overlay buttons

### ISSUE THREAD

**Issue by xenophorm12** [inotia00/ReVanced_Extended#402]
### Application

YouTube

### Issue

We can't see which chapter we're in when the overlay buttons are enabled in portrait mode. Placing them next to SponsorBlock button would solve this issue.

![IMG_20230304_092431](https://user-images.githubusercontent.com/58360189/222879988-631aa7e6-ea6d-4f2f-a029-a634382a3b0a.jpg)
![IMG_20230304_092541](https://user-images.githubusercontent.com/58360189/222879990-47fcd641-5e9d-4f44-8b57-9771985daa33.jpg)

### Patch

Place the overlay buttons next to SponsorBlock button.

### Motivation

This would make it easier to see the current chapter in portrait mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MondayNitro** [comment]
but the video title leaves very little to no space at the top!!

**Comment by Spacellary** [comment]
Seeing the video title isn't as important though imo.
You can just go to Portrait mode to see the title and you know it anyways before clicking the videos so...
This would be amazing if possible ofc

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
