### ISSUE TITLE
Show full title of videos in playlist 

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#403]
### Application

YouTube

### Issue

The titles of playlist video is always short .i mean it doesn't show the full title of video as shown in picture 
![Screenshot_20230304_110624_app rvx android youtube_edit_218931979072322](https://user-images.githubusercontent.com/107951133/222888538-44688322-728c-4015-8586-a62162fb8e04.jpg)

### Patch

I inquire if there is a patch to show full videos titles when browsing them from playlist so we won't have to enter the video to know its complete title 

### Motivation

It will benefit users so much

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#86
