### ISSUE TITLE
feat(patch): Add OPTION to sort videos of a channel by (date) oldest.

### ISSUE THREAD

**Issue by AdishSagarawat** [inotia00/ReVanced_Extended#404]
### Application

YouTube

### Issue

I donkow why google removed it?

### Patch

Just like in older version of YT.

### Motivation

Because I am eager to see the first video uploaded by a creator.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cuynu** [comment]
Add a patch that spoof version to 17.03.xx/17.04.xx can enable sort by oldest option

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/123
