### ISSUE TITLE
YouTube revanced video buffering problem 

### ISSUE THREAD

**Issue by Aiwazfazil** [inotia00/ReVanced_Extended#405]
### Type

Other

### Application

YouTube 18.01.38

### Bug description

Video buffering issue, whenever i Play video it work properly for 1, 2 minutes after that video started buffering.

### Steps to reproduce

Please help me

### Relevant log output

```shell
Be fast
```

### Device Environment

Android 13 realme ui 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by hoang-himself** [comment]
#141
