### ISSUE TITLE
bug: Video thumbnail hidden in feed?🙃

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#406]
### Type

Error at runtime

### Application

Version 18.07.35 non-root 

### Bug description

Today it seems like my acc finally received the new layout after waiting for an eternity (hoping it doesn't go away...)
Anyway I just noticed a video in feed which didn't show the thumbnail. This was a very weird thing to witness, as I've never seen or heard of such bug.
It only shows video title. 
Please see here: https://streamable.com/47yq7p

What could possibly be causing this? Can it be fixed?

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.18)
