### ISSUE TITLE
Bug: imoticon bars are showing only when we write comments

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#408]
### Type

Error while patching

### Application

18.08.38

### Bug description

The imoticon bars are showing below comment section when we try to write comments on yt. It doesnt happen when we search in home feed. I tried to refresh data of my keyboard and rvx, but it still shows tjis bug.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
has nothing to do with rvx
