### ISSUE TITLE
suggestion : Add Vanced icons in patch.

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#410]
### Application

YouTube

### Issue

Please add Vanced icon for both yt and music for Vanced lovers. As it is gonna very difficult for rooted users in modules.

### Patch
![IMG_20230305_161520_460](https://user-images.githubusercontent.com/93650504/222955755-fc3729ea-72f5-44b9-a6fe-a85c5f61286a.jpg)

...

### Motivation

Will help Vanced lovers to choose  vaned icon from there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by manishloshali** [comment]
![227816741-5c03ba7d-917d-4748-a269-47a7ed5efa23](https://user-images.githubusercontent.com/125728453/227844436-bdd37059-70b3-426a-827d-fa4c14788191.png)

![IMG_20230324_171406-removebg-preview (1)](https://user-images.githubusercontent.com/125728453/227844466-734e4652-e982-4d42-bda0-9fec2d020015.png)

![product_logo_youtube_color_144](https://user-images.githubusercontent.com/125728453/227844485-edf1e6da-ba53-49b6-a02c-1e8a33dee3db.png)

**Comment by inotia00** [comment]
It seems difficult to add due to DMCA issues
