### ISSUE TITLE
bug: The autoplay and sponsorblock icons are misaligned 

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#411]
### Type

Cosmetic

### Application

Youtube 18.08.38 (latest patches)

### Bug description

Like the title says (and shows in the screenshot below).
Probably happens with other icons, but I haven't tested those.

### Steps to reproduce

Enter a video with sponsorblock icons active

### Relevant log output

```shell
---
```

### Screenshots or videos

![Inkedתמונה של WhatsApp‏ 2023-03-05 בשעה 15 15 01](https://user-images.githubusercontent.com/6445601/222962871-3ed6d46e-aead-4f71-b363-78de9494031a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is not a bug
In Extended, the sponsor block icons have been fixed to align to the left of the autoplay button as shown in the attached screenshot (this is intended)

**Comment by inotia00** [comment]
![RV](https://user-images.githubusercontent.com/108592928/222988536-2e9bace0-edb1-4c33-a483-90cb3ebacb9b.png)
This screenshot is from the official ReVanced

There is a bug where the SponsorBlock buttons disappear in videos with live chat if you align the SponsorBlock buttons to the right of the Autoplay button.

To prevent this bug, in Extended, the SponsorBlock buttons are aligned to the left of the autoplay button.
