### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Marcus719** [inotia00/ReVanced_Extended#413]
### Type

Error at runtime

### Application

V18.06.41

### Bug description

the video plays for a certain time, then loads infinitely. I already installed a bunch of versions and I don't know what else to 

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230305_192658_ReVanced Extended](https://user-images.githubusercontent.com/126763938/222989451-c0e356ae-1673-48e1-ab46-d78c5da49215.jpg)

### Solution

a version without this annoying bug 

### Additional context

the white bar that is below the red line of video playback does not appear either 

![Screenshot_20230305_192625_ReVanced Extended](https://user-images.githubusercontent.com/126763938/222989530-e5d9674c-d8f3-4f5a-8513-3f027f06c9cd.jpg)

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
