### ISSUE TITLE
Playback bug

### ISSUE THREAD

**Issue by TrevorAntony** [inotia00/ReVanced_Extended#415]
### Type

Error while patching

### Application

Youtube revanced extended and mirco g latest versions

### Bug description

I don't know what has changed recently the app has been working perfectly for months since I first used it. 
Now it will only play around 30 seconds of a video and then gey stuck infinitely buffering unless I sign out and use the app without being signed in.

### Steps to reproduce

Sign in 
Play video

### Relevant log output

```shell
None
```

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141

**Comment by TrevorAntony** [comment]
Thanks for the response🤝🏾let me try the solutions in the thread
