### ISSUE TITLE
imoticon bars

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#416]
### Type

Error at runtime

### Application

youtube 18.08.39

### Bug description

at sudden time, when i try to write comment on rvx, this imoticon bars show up. But strange thing is that in homefeed search it doesnt appear. Sorry for asking one more time of this and you told me it doesnt matter with rvx. However this thing only show up in rvx when try to comment something. I tried clear all data of my keyboard and checked the og youtube. og yt doesnt have this prob. i sincerly ask for you and i hope you will give answer.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230307_010033_YouTube](https://user-images.githubusercontent.com/113352087/223164673-22a0c922-3d22-4a16-a72a-f9f3e2d9e71c.jpg)

### Device Environment

android 13 samsung

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by andylee516** [comment]
> ### Type
> Error at runtime
> 
> ### Application
> youtube 18.08.39
> 
> ### Bug description
> at sudden time, when i try to write comment on rvx, this imoticon bars show up. But strange thing is that in homefeed search it doesnt appear. Sorry for asking one more time of this and you told me it doesnt matter with rvx. However this thing only show up in rvx when try to comment something. I tried clear all data of my keyboard and checked the og youtube. og yt doesnt have this prob. i sincerly ask for you and i hope you will give answer.
> 
> ### Steps to reproduce
> .
> 
> ### Relevant log output
> ```shell
> .
> ```
> 
> ### Screenshots or videos
> ![Screenshot_20230307_010033_YouTube](https://user-images.githubusercontent.com/113352087/223164673-22a0c922-3d22-4a16-a72a-f9f3e2d9e71c.jpg)
![Screenshot_20230307_011538_YouTube](https://user-images.githubusercontent.com/113352087/223168967-d3903a52-8db6-44f5-b3b9-e6eae6fdfd05.jpg)

> 
> ### Solution
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Device Environment
> android 13 samsung
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new and no duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is not a bug
This is a feature 'timed reaction[timed reaction](https://support.google.com/youtube/thread/157635086/timed-reactions-experiment-a-new-way-to-engage-with-videos?hl=en) ' provided by YouTube (A/B test)

**Comment by andylee516** [comment]
Thanks for reply. By the way is this feature different by real emoji reactions? Also does ab test means that only some people have this feature??
