### ISSUE TITLE
feat(patch): Move dislike counts to right dislike button

### ISSUE THREAD

**Issue by cuynu** [inotia00/ReVanced_Extended#417]
### Application

YouTube

### Issue

no issue

### Patch

I hope you can put the dislike counts to the right of the dislike button instead of putting it inside the like button. It will be more balanced and reasonable.

### Motivation

It will be more balanced, look more comfortable

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
Add the screenshot also
Which you've posted on the chat group

**Comment by kazimmt** [comment]
![photo_6066770545917146483_w](https://user-images.githubusercontent.com/82371061/223325428-f2d1a035-5088-4fbf-95bf-dbe817a9f8e4.jpg)

**Comment by kazimmt** [comment]
No it's not
I mean he want it like this.

**Comment by sliceanddice9** [comment]
I agree, the dislike counter layout looks easier on the eyes like this.

**Comment by DokterKaj** [comment]
@inotia00 @KobeW50 can this issue be reopened? Not sure why the author closed this but I think it'd be nice to have this as an option

**Comment by KobeW50** [comment]
can this issue be reopened? Not sure why the author closed this but I think it'd be nice to have this as an option

Inotia00 no longer accepts feature requests for YouTube
