### ISSUE TITLE
Add a control lock button!

### ISSUE THREAD

**Issue by MiCRONZ2** [inotia00/ReVanced_Extended#418]
### Application

YouTube

### Issue

This is a small suggestion

### Patch

Add a control lock button just like local video players (ie. Mx player). 

### Motivation

This would help most on mistouch. Also a great feature too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/10
