### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by MomentP** [inotia00/ReVanced_Extended#419]
### Type

Other

### Application

YouTube 18.08.39

### Bug description

I'm facing the issue when watching reels the app just closes 

### Steps to reproduce

In the reels tab

### Relevant log output

```shell
I don't have any
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please attach at least a screenshot or video

Also, please attach the method or logcat where the error is reproduced.
