### ISSUE TITLE
feat(patch): full screen button container

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#420]
### Application

YouTube

### Issue

In latest rvx, in full screen button container there is clip button which looks like (...) So can you add a patch that can hide full screen button container respectively? In current patch when we hide fullnscreen buttoncontainer it just hides all.

### Patch

https://www.mediafire.com/view/o2tdccz9c6d2bq5/IMG_20230307_104354_190.jpg/file

### Motivation

I think it will look more simple.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/398
