### ISSUE TITLE
Revanced bug 

### ISSUE THREAD

**Issue by KrishanMohanDev** [inotia00/ReVanced_Extended#422]
### Application

YouTube

### Issue

Video stuck problem 

### Patch

I am using revanced YouTube in this moded version of YouTube the video will start buffering after some minutes and the video will never play it will continually loading. It's not internet Issue cause i check from many different network. Please try to solve them. 

### Motivation

Idk

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
#141
