### ISSUE TITLE
feat(patch): remove super thanks button from comments section

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#423]
### Application

YouTube

### Issue

a "buy super thanks" button appears to the right of type comment box in the comments section for certain channels.
check this short's comment section to see it https://youtube.com/shorts/QJ9zfgHmA90?feature=share
im not sure if it appears only in shorts comment section or also in videos comments section, currently ive seen it only in shorts comments of certain channels.

### Patch

the patch shouls hide/disable this

![photo_6068747089866765776_y](https://user-images.githubusercontent.com/87489540/223376947-3ccc1b77-372b-44f4-9ab8-0b0e8ba22422.jpg)

### Motivation

it is unnecessary so it would be better if removed

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.164.21](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.21)

**Comment by madhurvarshney** [comment]
I noticed it today. It is still shown to me.
YouTube v18.11.36
Patch v2.166.15
![IMG_20230326_122814](https://user-images.githubusercontent.com/125809686/227760488-987112eb-191e-41ae-9e60-1c1ab4db3ef4.jpg)

**Comment by inotia00** [comment]
turn on:
Settings > ReVanced Extended > buttom player layout > comments > hide thanks button

default value is off
