### ISSUE TITLE
Video Buffering

### ISSUE THREAD

**Issue by manishbaldawa** [inotia00/ReVanced_Extended#424]
![Screenshot_20230307-144317](https://user-images.githubusercontent.com/127190806/223377090-0a8da654-b05a-4fa2-a7b6-ae7d87ba9304.png)
Video stops playing in middle and starts buffering

**Comment by madhurvarshney** [comment]
#141

**Comment by masterb8t** [comment]
Same that happened with me. Around the 1:39 mark. Any way to solve this?

**Comment by manishbaldawa** [comment]
> Same that happened with me. Around the 1:39 mark. Any way to solve this?

You login with another google account it solves problem

**Comment by manishbaldawa** [comment]
Login with another google account it solved the problem
