### ISSUE TITLE
feat(patch) : add `old style fullscreen button container` patch

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#425]
### Application

YouTube

### Issue

Ad an option to revert back to the previous style for the full screen button layout 

### Patch

Refer to this screenshot for the new change from youtube today - 
![Screenshot_2023-03-07-14-42-41-965-edit_app rvx android youtube](https://user-images.githubusercontent.com/64865031/223380999-5c4a9940-08c1-46c4-a3ea-110729d85b88.jpg)

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
