### ISSUE TITLE
bug: `hide-get-premium` patch breaks account popup layout in tablet UI

### ISSUE THREAD

**Issue by hoang-himself** [inotia00/ReVanced_Extended#426]
### Type

Cosmetic

### Application

YouTube Music v5.46.52

### Bug description

Tapping the account image at the top right corner to show the bugged account popup

### Steps to reproduce

Patches: `["background-play","client-spoof-music","enable-opus-codec","exclusive-audio-playback","hide-music-ads","hide-upgrade-button","minimized-playback-music","music-microg-support","optimize-resource-music","hide-get-premium"]`

Selecting `enable-tablet-mode` makes no difference

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20230307_210232_YouTube Music](https://user-images.githubusercontent.com/10150902/223445300-62b74ef1-79e7-475b-89d9-ded9a52e2de8.jpg)

![Screenshot_20230307_210242_YouTube Music](https://user-images.githubusercontent.com/10150902/223445230-0d4808be-4e0b-4577-96aa-ddb5f10504e5.jpg)

### Device Environment

Samsung Galaxy Tab S6 Lite, One UI 5.0, Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
How is it shown on unpatched YouTube Music on your device?

**Comment by hoang-himself** [comment]
This is with unpatched v5.46.52

![Screenshot_20230308_000626_YouTube Music](https://user-images.githubusercontent.com/10150902/223497414-b7b70973-9715-4884-bd7c-1a361792c92c.jpg)

**Comment by A72010** [comment]
For me also this bug

**Comment by inotia00** [comment]
Unfortunately, I don't have a tablet, so a fix is not possible right now.

**Comment by MrAdityaAlok** [comment]
This does not happen if `hide-get-premium` is excluded. So, some problem might be in that patch.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.24)
