### ISSUE TITLE
feat(patch): make rotation stay like the sensor dictates when returning from horizontal video

### ISSUE THREAD

**Issue by mindforger** [inotia00/ReVanced_Extended#429]
### Application

YouTube

### Issue

YT switches back to vertical when hitting back on horizontal playback and keeps the mainmenu horizontal when returning again until you flip the phone once vertical and back horizontal 

### Patch

Either return to the horizontal menu with the video in pip mode when using back button (old vanced did this) or when entering the menu, make a forced orientation check to align propely

### Motivation

this is a weird bug that has been in the native app ever since i discovered vanced and made vanced my most loved App feature after the obvious feature

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
well.. It is the latest YouTube change

The latest YouTube is forced to rotate the screen, and RVX is not forced to rotate the screen.

Also, in the past, similar patch-requests have already been registered, so I will close this issue. https://github.com/inotia00/ReVanced_Extended/issues/50

**Comment by mindforger** [comment]
Sorry i did not search for potrait mode, not native english here, can you help me understand the other issue, is it still valid or considered unfixable?

**Comment by inotia00** [comment]
Briefly, this feature relies on the server side

If the YouTube server recognizes the current client as v17.10.xx or later, the feature is forcibly enabled.

This is a server dependent feature and cannot be disabled
