### ISSUE TITLE
Configuration:

### ISSUE THREAD

**Issue by rsr123123** [inotia00/ReVanced_Extended#431]
### Application

YouTube

### Description

You could add the option to hide stories; also put the download button under the video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rsr123123** [comment]
You could add the option to hide stories; also put the download button under the video.

**Comment by inotia00** [comment]
What are you curious about?
