### ISSUE TITLE
question: <title>: 

### ISSUE THREAD

**Issue by rahulpalshepherd** [inotia00/ReVanced_Extended#433]
### Application

YouTube

### Description

Why YouTube video link doesn't open in Vanced directly instead it opens in browsers.
I have cleared default settings of my browser and set vanced as default but still doesn't work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
YouTube links not opening in ReVanced instead of opening in Google Chrome (or any other browser)?

Here is the Solution (screenshot included)

- Solution for all OS
https://telegra.ph/YT-Link-Solution-for-ReVanced-12-26

- Solution for MIUI
https://telegra.ph/YT-Link-Solution-for-MIUI-10-13
