### ISSUE TITLE
bug: 'Resource has been exhausted' toast message = Cannot subscribe to channels 

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#434]
### Type

Error at runtime

### Application

Version 18.08.39 non-root 

### Bug description

This bug only happens with RVX. I tested stock YouTube and it lets me subscribe.

Basically in rvx I cannot subscribe to channels due to this bug:

![Screenshot_20230308-150854076 (1)](https://user-images.githubusercontent.com/73917917/223735710-ef1a844a-e8b9-4585-8f1b-9c3e87321027.png)

**Comment by inotia00** [comment]
This is a bug in the official Youtube
This bug does not occur in all situations, and it occurs only when certain conditions are met.
This is an issue Google needs to fix
https://www.reddit.com/r/youtube/comments/ofbegf/error_resource_has_been_exhausted_eg_check_quota

**Comment by anyujinie** [comment]
@inotia00 But I had no issue subscribing with stock YT 🤔 Seems to happen more frequently with RVX

**Comment by inotia00** [comment]
nah.. this bug is obviously a bug in stock youtube

https://www.reddit.com/r/youtube/comments/znjc6v/resource_has_been_exhausted_eg_check_quota/
https://www.reddit.com/r/youtube/comments/10eeg06/anyone_know_why_resource_has_been_exhausted_eg/

To reproduce or fix this bug, I need the full source code from YouTube

**Comment by anyujinie** [comment]
But then why every time I try it with stock YT it just works immediately without that bug? Every time Rvx doesn't let me subscribe I have to open stock YT where it just works...

**Comment by inotia00** [comment]
If so, exclude all patches until it works fine and add the patch you suspect as causing the issue.
