### ISSUE TITLE
Sudden Black Screen

### ISSUE THREAD

**Issue by mchoy45** [inotia00/ReVanced_Extended#435]
### Type

Error while patching

### Application

When playong a video for a certain time it usually loads endlessly even though having an excellent internet connection and afterwards it suddenly goes blackscreen. Same thing happens when i try seeking/skipping when watching.

### Bug description

By using the revanced app

### Steps to reproduce

Idk

### Relevant log output

```shell
Idk
```

### Screenshots or videos

![Screenshot_2023-03-09-02-14-15-28_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/127339424/223796054-f45e3e34-63a2-435d-8ace-8248b1fdc74f.jpg)

### Solution

Idk

### Additional context

Hope to solve this bug/problem by the developers. Anyways thankyou in advance.

### Device Environment

Realme 8i
Android 12
Realme UI 3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
