### ISSUE TITLE
feat(patch): comments/live chat overlay button

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#436]
### Application

YouTube

### Issue

since youtube moved live chat button to fullscreen buttoncontainer, and people wouldnt want to exclude the fullscreen button container patch just for the live chat button, it would be really great if you could add a **dynamic overlay button that opens comments for regular videos and live chat for livestreams**

### Patch

dynamic overlay button that opens comments for regular videos and live chat for livestreams

### Motivation

user convenience that youtube wants to take away for some reason

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This feature has already been implemented by Google.
