### ISSUE TITLE
feat(patch): add additional "share -> incognito" button 

### ISSUE THREAD

**Issue by mindforger** [inotia00/ReVanced_Extended#437]
### Application

YouTube

### Issue

https://github.com/inotia00/ReVanced_Extended/issues/141

currently a viable workaround for me is to share and copy the link to clipboard and enter incognito mode to watch the video by searching for the link

but it is a little bit unconveniant

### Patch

could this 5 steps: share -> copy clipboard -> swipe up to change to incognito -> select search -> paste link -> select from search

be made into only two with an intelligent button: share -> "watch incognito" -> select from search

(suppose it would be too much to ask the video to play directly :P)

### Motivation

more conveniance!? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Shiroe93** [comment]
I use a similar method sharing the video to newpipe it would be a nice to have a direct button to do this

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
