### ISSUE TITLE
feat(patch): Fix for UI positioning when using forced immersive mode (such as via SystemUI tuner or ADB)

### ISSUE THREAD

**Issue by pressRtowin** [inotia00/ReVanced_Extended#438]
### Application

YouTube

### Issue

If you use forced immersive mode within youtube to watch a video, due to the difference in positioning without the expected status bar, the player positions itself too low when entering full screen. This can be fixed by rotating the device 90° and rotating it back, however this is annoying. I'm not sure if this part is DPI dependent, but for me, the screen is shifted far down enough that the top of the dot that indicates the current position is visible, but the entire progress bar is below the edge of the screen. This also affects how the Zoom to Fit feature works, as it zooms until the top edge of the video (which is now much lower) in aligned with the top edge of the display (which is now much further away), resulting in quite a bit of the bottom of the video being cut off.

### Patch

If possible, detect the useable screen area correctly, and enter full screen with the UI aligned properly, regardless of immersive mode settings.

### Motivation

Static elements are bad for OLED displays. There are quite a few of us who avoid them at all costs, by using settings such as gesture navigation and immersive mode whenever possible. This is a good QOL change for us.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
