### ISSUE TITLE
feat(patch): replace YouTube share menu with system share menu

### ISSUE THREAD

**Issue by pressRtowin** [inotia00/ReVanced_Extended#439]
### Application

YouTube

### Issue

The giant grid of applications is annoying and doesn't support features like direct share. Can this be replaced with the standard system share menu?

### Patch

See above

### Motivation

System share > youtube share

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
What do you mean by custom share menu and system share menu?

Could you attach a screenshot for better understanding?

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
