### ISSUE TITLE
bug: lag in UI 

### ISSUE THREAD

**Issue by Dhrubaof2002** [inotia00/ReVanced_Extended#440]
### Type

Error at runtime

### Application

Youtube v18.09.37

### Bug description

https://user-images.githubusercontent.com/64865031/223978269-9bdf22f5-83a0-45d1-afd4-49b10458d05b.mp4

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Device Environment

Android 13 , MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please add a sufficient description and process to reproduce the issue.

**Comment by Dhrubaof2002** [comment]
> Please add a sufficient description and process to reproduce the issue.

The screen record is the problem that is happening and its just happening, don't know how to reproduce.

**Comment by inotia00** [comment]
At least in screenrecord there is no lag.

**Comment by inotia00** [comment]
unpatched YouTube client is stuck at 60fps when playing video

This is forced by stock YouTube, not forced by rvx
