### ISSUE TITLE
bug: Some options are not possible to change

### ISSUE THREAD

**Issue by Pupvert** [inotia00/ReVanced_Extended#441]
### Type

Other

### Application

Youtube v18.09.37
Revanved extended patches v2.164.21
ReVanced Manager v0.0.56

### Bug description

Going through the revanced extended settings. I noticed that some settings were not possible to change. 

### Steps to reproduce

1. Going into the different settings. 
2. Not being able to change some of them because they are greyed out.

### Relevant log output

```shell
No relevant logs exists. All patches were successfully patched.
```

### Screenshots or videos

![Screenshot_20230309-113343_ReVanced_Extended](https://user-images.githubusercontent.com/102103233/223999996-e1f42b92-47e8-4e69-814a-16f33cdb78af.png)
![Screenshot_20230309-113419_ReVanced_Extended](https://user-images.githubusercontent.com/102103233/224000060-8f7306e9-6d57-47d8-bb50-8016adc73dba.png)

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Settings that are not available on your device are disabled

Disabled settings in the attached screenshot are options that are not available in the tablet UI.

To force use of disabled settings, turn on `Enable phone layout`
