### ISSUE TITLE
bug: Excluded Premium Header patch but it still shows in latest version 

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#443]
### Type

Error at runtime

### Application

Version 18.09.37 non-root

### Bug description

![Screenshot_20230309-141242679 (1)](https://user-images.githubusercontent.com/73917917/224033859-f241b0f2-f844-4c97-a37e-b624ba446882.png)

I always exclude this patch and in the previous version it was accordingly not showing, but when I now just updated to latest version it's now showing in RVX settings. This is a patch I'm not interested in and don't want it in RVX settings. Seems like excluding the patch didn't work this time.

**Comment by inotia00** [comment]
read [documentation](https://github.com/inotia00/revanced-documentation/wiki/Options-Information-about-the-patch#if-you-want-force-premium-header)
