### ISSUE TITLE
question: <title>: uploading video problems

### ISSUE THREAD

**Issue by ssanina1488** [inotia00/ReVanced_Extended#444]
### Application

YouTube

### Description

https://user-images.githubusercontent.com/127409686/224032776-6a5db046-6277-49af-a777-aae41e64c875.mp4

Greetings, I ran into an unpleasant problem. After YouTube vanced stopped working, I installed YouTube revanced but there is one significant drawback. The fact is that the video is loaded only at a certain point, and after the video freezes and a black screen appears. I ask you to tell me what I need to do and if it can be fixed. Version MIUI 13.0.5. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
