### ISSUE TITLE
feat(patch): Hide official header

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#445]
### Application

YouTube

### Issue

Whenever searching for a movie trailer, at the top there's a result saying whatever movie we searched trailer and I feel this banner is not significantly worth to be present there.

Here it's the brown box right below the search bar:
![Screenshot_20230309-230123](https://user-images.githubusercontent.com/117499019/224109780-ba3e427e-d0a7-4f7f-a2f4-77ab0aad40c3.png)

### Patch

A patch to simply hide it away from the search results.

### Motivation

It doesn't play any significant role by being present where it is in the search results.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
Good suggestion. What's the point of that useless banner.

**Comment by ILoveOpenSourceApplications** [comment]
@anyujinie I have a feeling that you've blocked me in GitHub which made it impossible for me to leave a comment in your issues. I understand that you felt that I was spamming comments in your issues but I was just trying to help you out.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.18)

**Comment by inotia00** [comment]
> ![Screenshot_20230406_233844_YouTube](https://user-images.githubusercontent.com/113352087/230413895-f88963d6-407f-4c44-b610-7b8da5719a4b.jpg) i think it didnt solved... even more keywords are on the searchbar. This time its something sports related.

it's off topic
