### ISSUE TITLE
bug: Can I not cast with non-root Rvx Music? 

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#446]
### Type

Error at run time

### Application

I have a non-root phone and was wondering if by now casting with Rvx Music/MicroG is possible or not? I just ordered a Nest Mini and would like to be able to cast with my Rvx Music app to it.
Is this possible or not? I don't want to root my phone.

### Bug description

![Screenshot_20230309-224208763 (1)](https://user-images.githubusercontent.com/73917917/224167115-c3c5c9dc-10b8-42ab-8140-d47f5ec8a65d.png)

**Comment by inotia00** [comment]
MicroG doesn't support chrome cast v2
use root build

**Comment by anyujinie** [comment]
Ok got it. Again I don't want to root my phone. Guess I'll have to install stock YTM only for casting aswell....

I thought OxrxL mentioned he wanted to develop a microg that works with casting
