### ISSUE TITLE
bug: Default resolution for WIFI vs. Mobile not working properly in 18.08.39

### ISSUE THREAD

**Issue by GUImodder** [inotia00/ReVanced_Extended#447]
### Type

Error at runtime

### Application

18.08.39 Revanced extended

### Bug description

Hi!

So default resolution for WIFI /Mobile does not work. I sent the default resolution for WIFI to 1440 and 144 for mobile (just in case I forget to turn of a podcast or a longer video to save data). 

### Steps to reproduce

![signal-2023-03-09-210148_003](https://user-images.githubusercontent.com/15251611/224185479-b2b9ec20-641e-4566-97c3-1efd4a788700.jpeg)

Screenshot 1: my settings

![signal-2023-03-09-210148_002](https://user-images.githubusercontent.com/15251611/224185558-0b97fc12-4994-440e-8cba-04d167e28900.jpeg)

Screenshot 2: Example: This video offers up to 4k60...and defaults to 480p in WIFI...WTF?

I don't really know whats the problem but it used to work up to this version.

### Relevant log output

```shell
I got none
```

### Screenshots or videos

see screenshots above

### Solution

So i hope this can be fixed to work as intended: Every Video on WIFI defaults to 1440p (if available, if not the next highest resolution). Every video started on Mobiles defaults to 144p and nothing higher than that.

Please contact me if further assistance is required

### Device Environment

Android 13 One UI 5.1 Samsung S23+

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/321
