### ISSUE TITLE
feat(patch) : add auto option in old style video quality flyout menu

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#449]
### Application

YouTube

### Issue

.

### Patch

Add auto option here - 
![Screenshot_2023-03-10-10-07-04-892_app rvx android youtube-edit](https://user-images.githubusercontent.com/64865031/224224693-292b7bea-56c4-4c50-9938-d922943731f0.jpg)

### Motivation

It'll be really helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
