### ISSUE TITLE
Proper Alignment of buttons under Video

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#451]
### Application

YouTube

### Issue

After Disabling unused buttons from container, the buttons are not properly aligned. Sometimes on some videos, they are aligned properly and sometimes not. After every clean install, the alignment changes. Sometimes there is no gap remaining b/w buttons.

![Screenshot_20230310-213051~2](https://user-images.githubusercontent.com/93650504/224364195-9ed54927-fd92-478b-be13-2a41c04c9685.jpg)

### Patch

If it is possible, then pls do something with it. On old layout, there is no such problem.

### Motivation

It will definitely enhance the look of button container. Centering the buttons will be great. (i.e. 1 or 2 btns will be start placing from center)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/17
