### ISSUE TITLE
question: Grouped Notifications: 

### ISSUE THREAD

**Issue by badhabit7** [inotia00/ReVanced_Extended#452]
### Application

YouTube

### Description

Notifications are not grouping like in Gmail or WhatsApp and they disappear after 5 notifications.. I have a Huawei y7p, I'm using the last update of MicroG and Rvx, battery optimization is disabled for them both, there no change in the notification settings, i tried several times to solve the issue but no luck, i tried a mod on Rvx with "app cloner" by forcing grouping Notifications, but results were not what i expected.
Is there a way to solve this? Is this a global issue or just for my phone? 
I really need my notifications not disappearing ! 

![Screenshot_20230310_201004_com microsoft emmx](https://user-images.githubusercontent.com/110391269/224410413-70a6129a-2734-43d1-a0da-91e5ae0d893c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, current YouTube clients do not offer group notifications.
Google should support this
