### ISSUE TITLE
Downloads page not appearing when offline

### ISSUE THREAD

**Issue by YounesBouhouche** [inotia00/ReVanced_Extended#453]
### Type

Error at runtime

### Application

YouTube 18.08.39 (non-root)

### Bug description

When I updated to this version, I found that u can't access my downloads library without being offline. But before, that was possible.
Please fix it as soon as possible.

### Steps to reproduce

1. Turn off wifi or mobile data
2. Open YouTube Revanced extended (non-root)
3. Open "Library" tab and you'll see a circular progress bar turning forever

### Relevant log output

```shell
No need to this
```

### Screenshots or videos

![Screenshot_20230310-222138_YouTube](https://user-images.githubusercontent.com/48130376/224466904-99cafcb9-8329-4cc0-820c-2b24b2bce3c6.png)

### Device Environment

Android 13 AOSP. February update

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The same issue is reproduced on unPatched YouTube.

Probably, a change from official YouTube

Since YouTube Premium accounts can access the offline download feature without any problems when there is no internet connection, it appears that Google has changed their policy to only provide access to offline downloads to YouTube Premium users when there is no internet connection.

**Comment by YounesBouhouche** [comment]
Is there any possibility to get it back?
Like what you did about red seekbar

**Comment by inotia00** [comment]
Unfortunately, this is not possible as it relies on the server side.

**Comment by YounesBouhouche** [comment]
Suddenly it was automatically fixed!
It automatically opens this page
![Screenshot_20230312-203009_YouTube.png](https://user-images.githubusercontent.com/48130376/224570312-3792438f-e2d2-4532-a477-bed2c5f07950.png)

Anyway, thank you very much for listening to me. I really appreciate it. Keep going 🔥🔥🔥
