### ISSUE TITLE
bug: `hide-mix-playlists` patch hiding video description under some videos

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#454]
### Type

Cosmetic

### Application

YouTube_v18.09.37

### Bug description

Can't see links & other info in description of some videos. If `hide mix playlists` is turned on.

### Steps to reproduce

Step 1: Patch YouTube_v18.09.37 with `hide-my-mix` patch
Step 2: Open this video:
- https://youtu.be/vvHTi7ZWrh4

### Relevant log output

```shell
Null
```

### Solution

I used previous implementation for hiding mix playlists, it solved the problem. I used following implementation:

      private static boolean hideMixPlaylist(String value, ByteBuffer buffer) {
        List<byte[]> byteBufferList = new ArrayList<>();

        byteBufferList.add("for you".getBytes());
        byteBufferList.add("mix-watch".getBytes());
        byteBufferList.add("list=".getBytes());
        byteBufferList.add("rellist".getBytes());

        // home feed & search result
        if (value.contains("home_video_with_context.") ||
                value.contains("search_video_with_context.")) {

            for (byte[] b : byteBufferList) {
                int bufferIndex = indexOf(buffer.array(), b);
                LogHelper.printDebug(() -> "Hiding mix playlists in feed & search result");
                if (bufferIndex > 0 && bufferIndex < 1500) return true;
            }
        }

        // related video
        if (value.contains("related_video_with_context.")) {
            for (byte[] b : byteBufferList) {
                int bufferIndex = indexOf(buffer.array(), b);
                LogHelper.printDebug(() -> "Hiding mix playlists in related videos");
                if (bufferIndex > 0 && bufferIndex < 1500) return true;
            }
        }

        return false;
    }

In filter(String, ByteBuffer) method:

    if (SettingsEnum.HIDE_MIX_PLAYLISTS.getBoolean())
            return hideMixPlaylist(value, buffer);

### Device Environment

Redmi Note 11, MIUI 13, Android 12S

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.24)
