### ISSUE TITLE
feat(patch): hide grey description under video

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#455]
### Application

YouTube

### Issue

in some videos it shows up grey wording that say 'Viewer also watched this video'.
can you disable this inotia??

### Patch

![Screenshot_20230312_012139_YouTube](https://user-images.githubusercontent.com/113352087/224496053-ea1e645d-4a40-4bba-9515-318f77a743c2.jpg)

### Motivation

it will look more nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
If not right now, I'll add it sometime later

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
