### ISSUE TITLE
′Hide more information menu′ patch is broken

### ISSUE THREAD

**Issue by kapchapka** [inotia00/ReVanced_Extended#456]
### Type

Other

### Application

Youtube 18.09.39

### Bug description

Hide more information menu still shows up in the flyout panel despite it being hidden.

### Steps to reproduce

Step 1. Include ′Hide more information menu′ patch 
Step 2. Go to flyout menu settings and enable ′Hide more information menu′ patch

### Relevant log output

```shell
...
```

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
can be reproduced
it will be fixed in next release

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.30)
