### ISSUE TITLE
feat(patch): into patch "Applies a custom theme (default: amoled)" add black splashScreen

### ISSUE THREAD

**Issue by odkate** [inotia00/ReVanced_Extended#458]
### Application

YouTube

### Issue

Incomplete amoled theme

### Patch

in the styles.xml file, replace `    <style name="Base.Theme.YouTube.Launcher.Light" parent="@style/Base.Theme.YouTube.Launcher">
        <item name="colorPrimaryDark">@color/yt_grey1</item>
        <item name="splashScreenColor">@color/yt_white1</item>
    </style>` on `    <style name="Base.Theme.YouTube.Launcher.Light" parent="@style/Base.Theme.YouTube.Launcher">
        <item name="colorPrimaryDark">@color/yt_grey1</item>
        <item name="splashScreenColor">@color/yt_black1</item>
    </style>`

### Motivation

There will be a full-fledged amoled theme for users with Android less than 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This feature has already been implemented

**Comment by odkate** [comment]
> This feature has already been implemented

What versions of the patch? I have a white flash screen on my 9 android after termux

**Comment by odkate** [comment]
> This feature has already been implemented
here is the patched file
https://github.com/odkate/yellow_mod/releases/download/latest/ReVanced.root.18.09.37_armeabi-v7a-cli_v2.21.0-patches_v2.164.21.apk

**Comment by inotia00** [comment]
The patch appears to have been applied normally.

The reason the splash screen on your device is not shown as dark is because Android 9.0 devices do not support system dark mode.

On Android 10+ devices, it is normally shown in black.

**Comment by odkate** [comment]
> The patch appears to have been applied normally.
> 
> The reason the splash screen on your device is not shown as dark is because Android 9.0 devices do not support system dark mode.
> 
> On Android 10+ devices, it is normally shown in black.

My suggestion for the patch update is for 8 and 9 android

**Comment by inotia00** [comment]
ah, unfortunately that's impossible

The part that loads the splash screen uses the device's system theme, not the YouTube app's theme.

Since the theme of the YouTube app is imported only after the splash screen has finished loading, it is practically impossible to force a theme on the splash screen.

**Comment by odkate** [comment]
> ah, unfortunately that's impossible
> 
> The part that loads the splash screen uses the device's system theme, not the YouTube app's theme.
> 
> Since the theme of the YouTube app is imported only after the splash screen has finished loading, it is practically impossible to force a theme on the splash screen.

But I manually changed the values in the styles.xml as indicated above and I have a black splash screen on android 9

**Comment by inotia00** [comment]
yes it is possible if you manually modify it

However, if you change it like that, the background color of the splash screen does not change according to the system dark mode on Android 10+ devices.
