### ISSUE TITLE
feat(patch): caption customise

### ISSUE THREAD

**Issue by Golukumar00** [inotia00/ReVanced_Extended#461]
### Application

YouTube

### Issue

I just request developer that if possible can you add "caption customise" like showing subtitles upper instead of down. 

### Patch

![Screenshot_20230312-193554~2](https://user-images.githubusercontent.com/119071430/224550038-0d47d575-10fb-45d3-8687-c93882580988.png)

### Motivation

I think many users including me struggles, when watches like English content we have to focus on subtitles, upper subtitles would help at least more better and we would enjoy content more.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
