### ISSUE TITLE
Click on Seek Bar to Forward ⏩ Video not working. bug: <title>

### ISSUE THREAD

**Issue by BrijeshMock** [inotia00/ReVanced_Extended#462]
### Type

Error at runtime

### Application

Rooted version

18.08.39  ( Arm64) 

### Bug description

When i click on Video Seek bar to farward video at specific point , video not forwarded ;  it's clickable but not working.
In the rvx setting default enabled - seekbar tapping enabled

### Steps to reproduce

I don't do anything modification in setting. Just install app & flash module & open RYt. & This bug found.

### Relevant log output

```shell
I don't know how to create log for this 🥺
```

### Screenshots or videos

https://user-images.githubusercontent.com/114675763/224564244-15ae6fc3-541f-48ba-b3c4-20be10db868b.mp4

### Additional context

I tried Non rooted version also same bug there. So i shifted to rooted version Same here.

### Device Environment

Android 13. 

Oos 13 F.14
Magisk - 25.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is an outdated issue
Please proceed with the patch again through the latest patch
