### ISSUE TITLE
bug: Hide mix Playlist 

### ISSUE THREAD

**Issue by ItzPritz** [inotia00/ReVanced_Extended#463]
### Type

Other

### Application

Youtube v18.09.39

### Bug description

If you go to the Settings> revanced extended> General layout and turn on the 'hide mix playlist', It'll not let you to upload the videos on your channel. (Create button will become buggy and it'll not show any options to upload the video). After turning off the 'hide mix playlist' it'll work fine.

### Steps to reproduce

Go to Settings> Revanced extended> General layout and turn on 'hide mix playlist'. Then go and tap the create button to upload the videos. It'll not show any options to upload the video.

### Relevant log output

```shell
I don't have any log output.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ItzPritz** [comment]
I've a video of this issue but i can't upload it here for some reasons.

**Comment by inotia00** [comment]
well.. not reproducible

**Comment by inotia00** [comment]
Perhaps this issue has been fixed in revanced-patches-v2.164.30. Try repatch.
If resolved, please close the issue

**Comment by ItzPritz** [comment]
Hello, I've repatched it and issue is now resolved. I'm closing the issue. Thank you so much💓
