### ISSUE TITLE
feat(patch): full screen custom seekbar colour

### ISSUE THREAD

**Issue by Aditya646754** [inotia00/ReVanced_Extended#465]
### Application

YouTube

### Issue

Make the custom seekbar colour apply to full screen videos 

### Patch

Full screen custom seekbar colour

### Motivation

Its will more personalized
![IMG_20230313_144024](https://user-images.githubusercontent.com/126933641/224656863-518a236c-dac9-4174-b6b2-b1294250352c.jpg)
![IMG_20230313_144100](https://user-images.githubusercontent.com/126933641/224656872-7e117725-0f8c-4bf8-a33f-8308dc9f4196.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.21](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.21)
