### ISSUE TITLE
bug: Share button doesn't work if hide mix playlist is enabled

### ISSUE THREAD

**Issue by Faszom11** [inotia00/ReVanced_Extended#466]
### Type

Other

### Application

YouTube 18.09.39

### Bug description

If you turn on hide mix playlist in revanced extended>general layout, the share button won't display anything. If you turn it off, it will show normally

### Steps to reproduce

Go to revanced extended>general layout, turn it on. Open a video, tap the share button.

### Relevant log output

```shell
No logs
```

### Screenshots or videos

https://user-images.githubusercontent.com/127752289/224705737-c4fdb056-d9e1-4fea-a9ef-521ef5d5bb5d.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Perhaps this issue has been fixed in revanced-patches-v2.164.30. Try repatch.
If resolved, please close the issue

**Comment by Faszom11** [comment]
The issue has been fixed, thank you!
