### ISSUE TITLE
How to fix network error when trying to sign into Google account question: <title>: 

### ISSUE THREAD

**Issue by Jordanpll3** [inotia00/ReVanced_Extended#467]
### Application

YouTube

### Description

I downloaded the YouTube app today. It shows my username when I hit sign on, but I am unable to load it as it says there is a network error – connection error

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
it's MicroG issue

follow steps below
https://github.com/inotia00/VancedMicroG/issues/1#issuecomment-1295962488
