### ISSUE TITLE
bug: like/dislike button container in "Right to Left Languages"

### ISSUE THREAD

**Issue by blacktornadog7** [inotia00/ReVanced_Extended#468]
### Type

Cosmetic

### Application

YouTube 18.08.39

### Bug description

In "Right to Left Languages" (like Arabic and Hebrew) the like/dislike counter doesn't show up properly (screenshot below).
And sometimes when liking a video the dislike counter disappears (this mostly happens when the dislikes are 1-2 digit numbers).

### Steps to reproduce

1. change Youtube's display language from the phone settings (requires android 13) or change the whole phone display language to a right to left language.
2. like a video

### Relevant log output

```shell
no logs
```

### Screenshots or videos

![Screenshot_20230313_163937_ReVanced Extended](https://user-images.githubusercontent.com/74029985/224747130-9edeb130-bc3f-4e9f-9662-7deb68fad48a.jpg)

https://user-images.githubusercontent.com/74029985/224753974-ec6f2de7-46fb-416a-878a-f07836b09138.mp4

### Solution

🤷🤷🤷

### Device Environment

Android 13 (One UI 5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed by ReVanced Team

**Comment by inotia00** [comment]
nah.. this issue is still valid, so I'll reopen it.

**Comment by inotia00** [comment]
![ReVanced](https://user-images.githubusercontent.com/108592928/226789892-6fe6f1fc-b7f8-4a37-a73b-adc2c7f6fb68.png)
fixed in [revanced-patches-v2.166.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.10)

**Comment by blacktornadog7** [comment]
when likes are below 1000, dislikes still disappear as in the clip I posted before.

**Comment by inotia00** [comment]
This is an issue that has been registered before.

After about 3 seconds, the dislike count will be displayed again

This issue cannot be fixed due to limitations in the implementation of return-youtube-dislike.
