### ISSUE TITLE
bug: app reboot dialogue not showing

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#47]
### Type

Error at runtime

### Application

YouTube v17.49.37

### Bug description

App should show reboot dialogue, when toggling preference's switches. But it doesn't show!

### Steps to reproduce

Patch YouTube with default patches, try to turn off `video ads` patch, and it doesn't show alert dialogue

### Relevant log output

```shell
null
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Duplicate with this issue https://github.com/inotia00/ReVanced_Extended/issues/24
