### ISSUE TITLE
bug: YouTube - Auto video play on home screen plays sound even if it's muted

### ISSUE THREAD

**Issue by Tasin5541** [inotia00/ReVanced_Extended#471]
### Type

Error at runtime

### Application

Youtube v. 18.09.39

### Bug description

After updating to the latest patch with the protobuf spoof, videos on the home screen are playing sound even though they are muted. I can unmute and mute again to solve this problem for one video but it plays sound again for the next video. 

### Steps to reproduce

1. Have autoplay on home screen turned on
2. The autoplay should be muted from home screen if this is the first time turning this feature on
3. Scroll to a video on home screen and let it autoplay
4. The video plays with sound even though you can see that the unmute option is being shown the top right corner of the video

### Relevant log output

```shell
No relevant logs
```

### Screenshots or videos

![IMG_20230314_113648](https://user-images.githubusercontent.com/42533823/224906135-6ffd651e-4612-4346-81d4-573f19fc0467.jpg)

### Device Environment

MIUI 14, Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by odkrys** [comment]
I have a problem too. I used xda's version.
https://forum.xda-developers.com/t/revanced-revanced-extended-guides-useful-links.4523967/

Also, can you make the "Playback in feeds" option visible on the tablet layout?
I turned that option off on my smartphone, but it doesn't appear on the tablet layout.

**Comment by fedonr** [comment]
Same with me, latest update broke the Playback in Feeds. I create the Apk using Builder each time and this issue only with the latest update. If you toggle and mute the video again it'll muted, but as soon as you scroll now the next video will be loud even when it shows muted.

**Comment by jhon1282** [comment]
In addition to reproducing the audio in the main screen, I also point out subtitles are deactivated for default

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.32](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.32)

**Comment by odkrys** [comment]
In v2.164.32, only the phone layout has been fixed.
The tablet layout still makes sound.
