### ISSUE TITLE
feat(patch): Watch History Fix

### ISSUE THREAD

**Issue by KROCKcorp** [inotia00/ReVanced_Extended#473]
### Application

YouTube

### Issue

YouTube watch history stopped working a week ago from this date : 14-March-2023, but the watch history is still working on the regular YouTube app and YouTube's website.

version 18.08.39
com.google.android.youtube
versionCode 1536294336
targetSdk 33
minSdk 26
Installed: Mar 14, 2023; 8:07 AM

### Patch

I think google is blocking watch history from third party apps and clientsike vanced and revanced, I don't know really how to spoof it or fix it, i don't know how watch history requests are made or how the watch data is synchronized between different apps and devices.

### Motivation

It's a core feature in YouTube, you get recommended videos you already watched again and again, you can't find videos you watched before, and it just makes using revanced a bad experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Google saves watch history of Vanced or ReVanced

Check your Google account settings and whether you are using a VPN

※ Some adblock VPN prevent saving YouTube watching history

**Comment by Spacellary** [comment]
For the record, this solved https://www.reddit.com/r/revancedextended/comments/12ust0a/watching_a_video_doesnt_add_it_to_watched_videos/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button
