### ISSUE TITLE
bug: <Impossible to add comment under the video>

### ISSUE THREAD

**Issue by Blazko381** [inotia00/ReVanced_Extended#474]
### Type

Other

### Application

YouTube all versions

### Bug description

Bug is on latest revanced-patches newer than 2.164.21(2.164.21 is ok)

### Steps to reproduce

Try comment under video. Circle is loading in infinite loop. Comment is not under video

### Relevant log output

```shell
I don't have logs
```

### Device Environment

Android 12, Samsung Galaxy S10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
please add screenshot or additional description

**Comment by Blazko381** [comment]
I don't know why but also on 2.164.21 patches is the same problem. I write comment, press send, the circle on right is spinning and doesn't nothing.

![Screenshot_20230315_074446_ReVanced Extended](https://user-images.githubusercontent.com/15677240/225228458-83fdcfec-20ac-49e2-acad-24576660dbde.png)

**Comment by inotia00** [comment]
It was a YT server side issue, and it seems to have been resolved in the latest YouTube
