### ISSUE TITLE
bug: All videos are saved as Shorts in the watch history

### ISSUE THREAD

**Issue by emylf** [inotia00/ReVanced_Extended#475]
### Type

Other

### Application

ReVanced Extended 18.10.33

### Bug description

All videos are saved as Shorts in the watch history after update to 18.10.33 version.

### Steps to reproduce

-

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_2023-03-14-14-21-54-252_app rvx android youtube](https://user-images.githubusercontent.com/94843551/224954883-7eff9a59-4839-4b35-aab0-2fb22253a85e.jpg)

### Device Environment

Android 12, MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.32](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.32)
