### ISSUE TITLE
Channel watermark is no longer displayed even if enabled in settings

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#478]
### Type

Cosmetic

### Application

18.09.39

### Bug description

Channel watermark is no longer displayed even if enabled in settings

### Steps to reproduce

Uncheck hide watermarks
Watermark don't is visible 

### Relevant log output

```shell
Don't have
```

### Screenshots or videos

![IMG_20230314_120809](https://user-images.githubusercontent.com/125223735/224985569-b4bdfd33-8d36-44f8-8b8a-daecf3d56179.jpg)

![IMG_20230314_121007](https://user-images.githubusercontent.com/125223735/224985636-9b935836-d0f0-4a81-af36-1abc9b792f47.jpg)
Default version

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jhon1282** [comment]
Sorry, I reversed the screens

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.32](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.32)
