### ISSUE TITLE
bug: Automatic playback in feed always unmuted

### ISSUE THREAD

**Issue by anmolvirk1997** [inotia00/ReVanced_Extended#479]
### Type

Cosmetic

### Application

Youtube Revanced 18.10.33

### Bug description

Automatic Playback in feeds always play with sound even when the mute button in top right corner is on(shows muted)......

### Steps to reproduce

step: Set the automatic playback in feeds option in YouTube general settings to on
step2: swipe on any video in youtube feed
step3: video/preview plays with sound, try changing to mute or unmute and mute again, it stays the same.....

### Relevant log output

```shell
I don't know how to generate log in youtube revanced
```

### Device Environment

Android 13, Oppo Reno 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anmolvirk1997** [comment]
Unmuting and muting against mutes the playback but next video preview always plays unmuted

**Comment by Tasin5541** [comment]
This has been fixed with the latest release.
