### ISSUE TITLE
bug: Splash screen is black even when dark theme is disabled in youtube settings

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#48]
### Type

Error while patching

### Application

YouTube v17.49.37

### Bug description

Patch YouTube with theme patch included, when you start app, it should be light splash screen but it's not!

### Steps to reproduce

Step 1: include theme patch
Step 2: open the app
Step 3: turn off dark theme if already turned on

### Relevant log output

```shell
null
```

### Device Environment

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
@inotia00 I believe this bug doesn't exist anymore.

**Comment by inotia00** [comment]
yeah outdated issue
