### ISSUE TITLE
bug: <title> seekbar tapping not work

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#482]
### Type

Error while patching

### Application

youtube 18.09.39

### Bug description

in the patch 2.162.32 seekbar tapping wont work for me despite that i had checked seekbar tapping while patching at rvx. in the home feed it works but when we encounter a video it doesnt work. i tried to upload screen video about this but in my phone i cant upload videos so giving you screen shot. sorry for that.

### Steps to reproduce

1. include seekbar tapping patch
2. go to yt
3. home feed work but it doesnt work at main video

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230315_000315_Gallery](https://user-images.githubusercontent.com/113352087/225044241-cb4632a5-46c9-4931-95c2-283fb9e88595.jpg)
![Screenshot_20230315_000339_Gallery](https://user-images.githubusercontent.com/113352087/225044291-c8151b31-6faf-444c-9899-6ceed89336c5.jpg)

### Device Environment

android 13 samsung

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/481
