### ISSUE TITLE
Video plays unmuted from search

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#485]
### Type

Other

### Application

Youtube

### Bug description

Unmute bug is only fixed in home feed, but if we search something then the video is played unmuted there. This Bug is not fixed completely.
And also there is no more mute/unmute button in video box (or frame, whatever).

### Steps to reproduce

1. Search for anything.

https://tempclip.com/en/6y278cEBeDVJsIP/watch

(Try to ignore BG noise)

### Relevant log output

```shell
...
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by AnjayVJ** [comment]
Facing same issue even after updating it to latest patch. Also when you search any videos the results also will be played on unmute and there is no icons of mute as well on searched results auto play feeds.

The home feed sound workaround as of now is to click on unmute and mute to actually mute it, but on the next video it'll again be unmute so not a effective workaround

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/480
