### ISSUE TITLE
bug: full screen doesn't auto rotate when tilted

### ISSUE THREAD

**Issue by RyanRiz** [inotia00/ReVanced_Extended#487]
### Type

Error at runtime

### Application

YouTube 18.09.39

### Bug description

When turn on full screen, it doesn't auto rotate when tilted to the right side.

### Steps to reproduce

On full screen mode

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Applied custom-branding-icon-revancify
Applied default-video-quality
Applied enable-external-browser
Applied enable-minimized-playback
Applied enable-open-links-directly
Applied enable-seekbar-tapping
Applied hide-channel-watermark
Applied hide-email-address
Applied hide-endscreen-cards
Applied hide-general-ads
Applied hide-pip-notification
Applied hide-snackbar
Applied hide-suggested-actions
Applied hide-video-ads
Applied microg-support
Applied optimize-resource
Applied overlay-buttons
Applied patch-options
Applied protobuf-spoof
Applied return-youtube-dislike
Applied settings
Applied sponsorblock
Applied swipe-controls
Applied translations
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
Installing patched file using nonroot method
Installed!
```

### Device Environment

Android 12, MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please check that it is reproduced even in the unpatched YouTube

**Comment by RyanRiz** [comment]
> Please check that it is reproduced even in the unpatched YouTube

You we're right. Turns out, it was bug from original unpatched file. I tried to download other 18.09.39 from apkmirror, apkcombo and apkpure, all has the same result (I tried several times). But it's strange, If I download 18.09.39 from PS somehow works well. So I try downgrade to 18.08.39, is all good now. Thanks.
