### ISSUE TITLE
bug: lift-vertical-video-restriction Patch does not work properly

### ISSUE THREAD

**Issue by odkate** [inotia00/ReVanced_Extended#488]
### Application

YouTube

### Description

Why does the lift-vertical-video-restriction patch hide the pivotbar in short videos? Judging by its description, it is intended for something else. Where did the hide-shorts-pivot-bar patch disappeared?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by odkate** [comment]
I checked again, the hide-shorts-pivot-bar patch is present in termux. But for some reason, it is replaced by the lift-vertical-video-restriction patch in the settings.
![Screenshot_YouTube_20230315-030845](https://user-images.githubusercontent.com/90364108/225178838-8b383dc2-b747-48c6-a82b-d77beb87e623.png)

**Comment by inotia00** [comment]
Please do not report issues related with `Experimental Flags`
