### ISSUE TITLE
Shorts doesnt work in background 

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#489]
### Type

Cosmetic

### Application

Newest

### Bug description

When i go in pip or background mode and of the short continue It blocks if the short Is paused if you start the short you cant see nothing but only black

### Steps to reproduce

Watch a short
Exit from the app

### Relevant log output

```shell
...
```

### Device Environment

Android 12 MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is not a bug
Shorts player won't play in the background even on unpatched YouTube

**Comment by speedlorenzo12** [comment]
But in a older version works
