### ISSUE TITLE
bug: Full screen button container is missing 

### ISSUE THREAD

**Issue by venkat2305** [inotia00/ReVanced_Extended#49]
### Type

Cosmetic

### Application

YouTube 17.49.37

### Bug description

![Screenshot_2022-12-25-14-10-05-164_app revanced android youtube](https://user-images.githubusercontent.com/55329452/209461929-bbca1680-8bb2-4fa8-9140-5013972748b3.jpg)

![Uploading Screenshot_2022-12-25-14-11-19-189_app.revanced.android.youtube.jpg…]()

### Steps to reproduce

Open any video

### Relevant log output

```shell
Iam using the apk from rvx lite channel
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Fullscreen button container is not supported on tablet layout

**Comment by venkat2305** [comment]
It's turned off
![Screenshot_2022-12-25-17-34-23-260_app.revanced.android.youtube.jpg](https://user-images.githubusercontent.com/55329452/209467224-c551fa09-f53a-411d-90e0-a250ee347669.jpg)

**Comment by inotia00** [comment]
and also check `Hide Fullscreen button container` settings

**Comment by venkat2305** [comment]
Please check this image
![Screenshot_2022-12-25-19-55-52-792-edit_app.revanced.android.youtube.jpg](https://user-images.githubusercontent.com/55329452/209471785-d8892231-75d3-430d-8fa5-6e0b97bc5883.jpg)

**Comment by inotia00** [comment]
If so, this is a bug
