### ISSUE TITLE
bug: ambient mode doesn't work after enabling protobuf spoof

### ISSUE THREAD

**Issue by ronin08** [inotia00/ReVanced_Extended#490]
### Type

Error while patching

### Application

YouTube Extended v18.09.39

### Bug description

Disabling the protobuf make ambient mode work properly. 

### Steps to reproduce

1. Enable protobuf spoof
2. Turn on ambient mode (It will not work!)

### Relevant log output

```shell
N/A
```

### Device Environment

Non-Root
Android 11
MIUI 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
Change 'Select protobuf to spoof' to ON

**Comment by inotia00** [comment]
There is no valid fix for this

If you don't want to face this issue, just turn off the protobuf-spoof

**Comment by ILoveOpenSourceApplications** [comment]
@inotia00, does it get included even if one patches without the protobuf-spoof. So it's recommended to patch with protobuf-spoof patch?

**Comment by johnconner122** [comment]
Just restart the app after toggling ambient mode, it works
