### ISSUE TITLE
protobuff's setting exist even excluded from patching process

### ISSUE THREAD

**Issue by abganteng** [inotia00/ReVanced_Extended#493]
### Type

Error while patching

### Application

Youtube v.18.09.39

### Bug description

i exclude protobuff patch from the process, but the setting on youtube exist

### Steps to reproduce

none

### Relevant log output

```shell
none
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Same as the client-spoof patch, if the MicroG patch is included, the protobuf-spoof patch is also included.

it's perfectly normal

**Comment by MondayNitro** [comment]
cant you separate the two patches like it was when protobuf patch didnt exist? makes sense, since protobuf is an experimental patch currently and many users dont have vuffering issue. i hope you separate protobuf from microg patch in next release sir!

**Comment by inotia00** [comment]
Of course I just wanted to say that this is not a bug.

However, in the next release this dependency will be removed.
