### ISSUE TITLE
bug: Ambient mode not working properly 

### ISSUE THREAD

**Issue by datlmhg** [inotia00/ReVanced_Extended#494]
### Type

Other

### Application

v18.08.39

### Bug description

"Ambient mode" not working

### Steps to reproduce

Turn on "Ambient mode" in video

### Relevant log output

```shell
Don't have
```

### Screenshots or videos

![Screenshot_20230315-194534_ReVanced Extended](https://user-images.githubusercontent.com/86174857/225314199-7d5069a8-ab60-4227-acac-8e99516b9652.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/490

**Comment by datlmhg** [comment]
> #490

How to disable it? I can't find it in settings

**Comment by inotia00** [comment]
just patch again with revanced-patches-v2.165.1

**Comment by datlmhg** [comment]
> just patch again with revanced-patches-v2.165.1

Can you give detailed instructions? I really don't know these things very well

**Comment by inotia00** [comment]
Umm... I don't know where you downloaded the ReVanced Extended you're using, but I'm not distributing the apk.

follow this [documentations](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android)) 

You can apply the latest patches using ReVanced Manager
