### ISSUE TITLE
feat(patch): aspect ratio in fullscreen

### ISSUE THREAD

**Issue by Sumedhvats** [inotia00/ReVanced_Extended#495]
### Application

YouTube

### Issue

Please add aspect ratio instead of cropping, I don't want black bars but cropping leaves details 

### Patch

Just like MX player,

### Motivation

No black bars, everyone happy 🤝

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
