### ISSUE TITLE
Patch to hide ad under video thumbnail 

### ISSUE THREAD

**Issue by Kobewaxman** [inotia00/ReVanced_Extended#496]
### Application

YouTube

### Issue

There is a type of ad that I've seen on the home screen that shows under a video. It is very similar to the teaser that alpears underneath videos. As you can see from the screenshots, when the bar is opened the contents are hidden already.

Btw I have the `hide teaser under video` set to Shown. Setting it to Hidden will effectively hide this type of ad.

![Screenshot_20230315_165841_ReVanced Extended](https://user-images.githubusercontent.com/84587632/225447122-ec656c22-1118-4b21-80e6-576bbdfeb177.jpg)
![Screenshot_20230315_165846_ReVanced Extended](https://user-images.githubusercontent.com/84587632/225447133-48e2d380-d2e1-43e4-8044-13725d515ce0.jpg)

### Patch

I was wondering if you want to add a patch that completely removes the ad bar from underneath the video without having to disable the standard teasers that are underneath videos.

### Motivation

To make Revanced Extended ad-free.

I know that this type of ad isn't very noticeable or intrusive.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/351
