### ISSUE TITLE
feat(patch): change playback speed by swiping up or down with two fingers 

### ISSUE THREAD

**Issue by hwasiti** [inotia00/ReVanced_Extended#497]
### Application

YouTube

### Issue

I noticed that this gesture to change speed is quite useful in MX player:
[change playback speed by swiping up or down with two fingers](https://www.reddit.com/r/androidapps/comments/668v4t/til_in_mxplayer_you_can_change_playback_speed_by/)

There are lots of use cases where one needs to modify the speed and keep changing between let's say 5x to skim the slides of a conference talk and slow down to 2x when there is something interesting then go back 5x. 

### Patch

change playback speed by swiping up or down with two fingers 

### Motivation

Rapid change in playback speeds is useful when one wants to skim a video without skipping anything just in case something important happens. Double tap to fast-forward is not ideal in those scenarios. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by hwasiti** [comment]
maybe implementing both and letting the user choose in the settings?
* Long press on the video (or long-press on the playback speed icon since the long press is interfering with a current function of video seek) -> toggle between preferred1, preferred2 speeds
* two fingers swipe up and down -> fine-tuned choice of the playback speed. Also, this is faster and more responsive than a long press

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
