### ISSUE TITLE
bug: <title> Buffering issu in revanced extended

### ISSUE THREAD

**Issue by Imon24** [inotia00/ReVanced_Extended#498]
### Type

Error while patching

### Application

Video buffers when playing large files.
Revanced extended version 18.10.33

### Bug description

Suddenly videos don't load and buffering issues starts. But my internet connection in very good

### Steps to reproduce

Suddenly videos don't load and buffering issues starts.

### Relevant log output

```shell
Suddenly videos don't load and buffering issues starts.
```

### Device Environment

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Imon24** [comment]
> 

Enable protobuf spoof cannot be found

**Comment by hoang-himself** [comment]
Its name is `Protobuf Spoof`

**Comment by hoang-himself** [comment]
Settings -> ReVanced Extended -> Miscellaneous -> Enable Protobuf Spoof

**Comment by Imon24** [comment]
![Screenshot_20230317-205446](https://user-images.githubusercontent.com/128045849/225940571-43085a86-3462-4e59-8839-438a8ad65e28.png)
But sir, there are no such settings💔

**Comment by hoang-himself** [comment]
Either you did not select the Protobuf Spoof patch or something is conflicting. Check your patch selection again or show what patches you selected.

**Comment by Imon24** [comment]
> Either you did not select the Protobuf Spoof patch or something is conflicting. Check your patch selection again or show what patches you selected.

I didn’t select any patch.. I just downloaded revanced extended from revansed.io directly

**Comment by hoang-himself** [comment]
Since you're using pre-built APK, make an issue on [their repo](https://github.com/j-hc/revanced-magisk-module) to include the patch. Otherwise make your own APK.

@inotia00 please lock
