### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by Daosik322** [inotia00/ReVanced_Extended#499]
### Application

YouTube

### Issue

18.10.33

### Patch

Hi, I have a problem with (Recommendation) it's totally pointless and doesn't reflect what I watch and like, I wish the next updates could change it and of course further improvements because sometimes bugs appear. Thanks in advance, the app is great :) 

### Motivation

A friend of mine I recommended Revanced has the same thing, with broken recommendations

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
repatch with latest patches
