### ISSUE TITLE
bug: <Unnecessary options in settings page>

### ISSUE THREAD

**Issue by NeeRaj-2401** [inotia00/ReVanced_Extended#5]
### Type

Error at runtime

### Bug description

I m having those options in settings page for which i didn't even select patches

### Steps to reproduce

Step 1. Build using revanced builder & Select patches
Step 2.  install and open patched .apk
Step 3. go to setting>revanced settings

### Relevant log output

```shell
NA
```

### Screenshots or videos

Selected Patches :

<img src="https://user-images.githubusercontent.com/88180887/198883559-b39b067d-0140-4057-a169-20a761aae03c.png" width="40%"/>

Revanced extended settings options:

<img src="https://user-images.githubusercontent.com/88180887/198883630-5c678564-fd92-49c9-971c-4b17574726ad.png" width="20%"/>

<img src="https://user-images.githubusercontent.com/88180887/198883772-5202b808-43fa-44e9-8d16-d3c882eb9905.png" width="20%"/>

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Supported by latest patch

**Comment by NeeRaj-2401** [comment]
@inotia00 will work with ytm too?

**Comment by inotia00** [comment]
YT Music's settings UI does not follow the settings UI of the existing Revanced Settings

Therefore, YT Music still does not support `settings-framework`
