### ISSUE TITLE
feat(patch): disable forced portrait mode

### ISSUE THREAD

**Issue by vadgama-nikz** [inotia00/ReVanced_Extended#50]
### Application

YouTube

### Issue

In the previous version whenever i watched a video in full screen mode with rotation locked in my phone, and i switched to another app (video pauses because of my config) and returned back, the video would be in full screen mode (paused), but in the latest version whenever i switch back to the YT app from another app, it returns back to portrait mode, having me to make the video in full screen mode again 

### Patch

The patch would lock the video being played in landscape mode with a toggle to keep it in landscape or 'default'.

### Motivation

It just saves a few seconds of time and makes it easier for the user to return back to the video and resume it quickly, without first the app turning the video to portrait and then making the user to go full screen again 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
tbh, this is the issue of Original Youtube, not rvx

**Comment by vadgama-nikz** [comment]
Is this issue patchable ? 

I guess it is a feature of youtube premium maybe, because uo until yesterday i had YT premium and it was not automatically being rotated to portrait when returning from another app.

**Comment by vadgama-nikz** [comment]
> tbh, this is the issue of Original Youtube, not rvx

Is this issue patchable ? 

I guess it is a feature of youtube premium maybe, because uo until yesterday i had YT premium and it was not automatically being rotated to portrait when returning from another app.

**Comment by inotia00** [comment]
Please edit the title appropriately

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
