### ISSUE TITLE
Muted playback option not working

### ISSUE THREAD

**Issue by hitesh-hkg** [inotia00/ReVanced_Extended#500]
### Type

Other

### Application

Extended v18.10.33

### Bug description

Muted playback plays with sound on homepage.

### Steps to reproduce

1. Launch the app
2. Enable muted playback in data saver settings if not enabled
3. Restart the app (optional)
4. On the homepage the video playback works but isn't muted even though the icon shows as muted.

### Relevant log output

```shell
-
```

### Device Environment

Realme ui 2.0
Realme X2 Pro
Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
outdated issue
just repatch
