### ISSUE TITLE
Strange behavior if one or two of the Protobuf buttons are selected.

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#501]
### Application

YouTube

### Description

If I activate the first Protobuf button the subtitles are displayed at the bottom and the thumbnail on the progress bar does not work.
If I also select the other Protobuf button the subtitles are shown at the top but the thumbnails on the progress bar work fine.
![Screenshot_2023-03-17-02-40-58-944_app rvx android youtube](https://user-images.githubusercontent.com/125223735/225791035-784a1deb-e830-47cb-9edc-477c7f79b84d.jpg)
![Screenshot_2023-03-17-02-38-49-072_app rvx android youtube](https://user-images.githubusercontent.com/125223735/225791063-8a89b8d4-4c1a-4bbc-b4a6-0c130d973682.jpg)
![Screenshot_2023-03-17-02-47-16-093_app rvx android youtube](https://user-images.githubusercontent.com/125223735/225791373-b061f55c-fe33-454e-bec9-7fad69cc63b6.jpg)
![Screenshot_2023-03-17-02-47-26-696_app rvx android youtube](https://user-images.githubusercontent.com/125223735/225791389-ae274c8f-52b6-4372-b96b-0876f5ffde78.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a known issue
