### ISSUE TITLE
feat(patch): hide emoji picker

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#502]
### Application

YouTube

### Issue

when we write comment on youtube, the time reaction imoticon bars are up on the keyboard. However in home feed search this doesnt happens. can you disable this feature please inotia??

### Patch

![223164673-22a0c922-3d22-4a16-a72a-f9f3e2d9e71c](https://user-images.githubusercontent.com/113352087/225933031-a48f7767-f076-41cf-9164-56eb4c0b7f61.jpg)
![223168967-d3903a52-8db6-44f5-b3b9-e6eae6fdfd05](https://user-images.githubusercontent.com/113352087/225933066-6ae9da13-0744-449d-bb1c-22b33c07b05b.jpg)

### Motivation

it will look more simple.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It's a terrible new layout that Google recently added.

I reverse engineered this all day yesterday to hide it, but no success.

It is obviously assumed to be a litho element, but after debugging, it was not a litho element.

**Comment by andylee516** [comment]
hmm...so in current situation we dont have any way to fix it?

**Comment by cuynu** [comment]
this new layout is quite similar to tiktok (junk platform) comments

**Comment by cuynu** [comment]
It also happen on older version 18.01.38, seem like a new server-side feature 
![Screenshot_20230317-220532_YouTube Vanced](https://user-images.githubusercontent.com/90895715/225943506-fbb48230-19cc-49a4-a3e9-77f86a8a48ca.png)

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.166.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.4)
