### ISSUE TITLE
bug: protobuf settings present in app even when i dont select the protobuf patch while patching

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#503]
### Type

Other

### Application

18.09.39

### Bug description

i use rvx builder to build, i dont include protobuf patch because i dont have buffer issue yet, but in latest release 2.166.1, the protobuf settings are present in app even when i dont select the protobuf patch while patching.

### Steps to reproduce

1. exclude protobuf patch and patch the youtube app
2. open patched app, goto experimental settings and you find protobuf settings there

### Relevant log output

```shell
.
```

### Screenshots or videos

![Web capture_17-3-2023_205714_localhost](https://user-images.githubusercontent.com/87489540/225950176-8870f98d-9331-4a51-8b24-0be445726584.jpeg)
![photo_6098250908145138147_y](https://user-images.githubusercontent.com/87489540/225950192-53a14a9c-416f-49c3-a165-bb81dee99f86.jpg)

### Device Environment

los18.1 a11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/493
