### ISSUE TITLE
bug: Overlay buttons are not hidden when swiping the seekbar

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#504]
### Type

Other

### Application

YouTube v18.10.36
Revanced Patches v2.166.1

### Bug description

When swiping the seek bar none of the overlay buttons are hidden like regular buttons.

![Screenshot_20230315_163848_YouTube](https://user-images.githubusercontent.com/127908708/225980898-32cc7455-668d-4b9e-993e-aca806cbe804.jpg)

### Steps to reproduce

Swipe the seek bar of any video.

### Relevant log output

```shell
N/A
```

### Solution

Hide the overlay buttons automatically when swiping the seek bar.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.1)
