### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by Maddy0104** [inotia00/ReVanced_Extended#508]
### Application

YouTube

### Description

The application keeps crashing while using the shorts tab every 2 mins

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Follow the method in the [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android)#root-environment)
