### ISSUE TITLE
bug: `protobuf-spoof` patch not working in YouTube notifications section

### ISSUE THREAD

**Issue by Shiroe93** [inotia00/ReVanced_Extended#509]
### Type

Error while patching

### Application

YouTube 18.10.37
Patch 2.166.5 (from this repo) 

### Bug description

When I select a video from the notification bell tab the black screen issue discussed in issue [#141](https://github.com/inotia00/ReVanced_Extended/issues/141) comes back
(the relevant spoof setting is enabled) 

### Steps to reproduce

1) open the app
2) click on the bell icon on the top right of the screen
3) click on a video from this screen
4) wait 90 - 120 seconds 

### Relevant log output

```shell
No relevant log
```

### Solution

Start the video in another way (for example from your history) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
did you enabled `Enable protobuf spoof`?

**Comment by Shiroe93** [comment]
Thanks
Keep up the good work

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.166.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.8)
