### ISSUE TITLE
question: <title>: app crash

### ISSUE THREAD

**Issue by Aditya646754** [inotia00/ReVanced_Extended#510]
### Application

YouTube

### Description

App is crashing when opened after install the revanced extended v18.11.34 how to fix?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
non recommand version no support
