### ISSUE TITLE
bug: PiP window does not work properly under certain circumstances

### ISSUE THREAD

**Issue by Shiroe93** [inotia00/ReVanced_Extended#512]
### Type

Other

### Application

YouTube 18.10.37
Patch 2.166.8

### Bug description

When a full video is open from a shots comment PiP bugs out like if you have done this with a short (in wich I know Pip doesn't work even in the official app but I'm mentioning it because it exhibits the same behavior) 

### Steps to reproduce

1 open a YouTube shorts
2 go in the comment section of that short
3 click on the link with the full video
4 activate PiP by returning to the homescreen 

### Relevant log output

```shell
No relevant log output
```

### Solution

Reopen the video from your history 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I didn't understand 'click on the link with the full video'

How do I open another video in shorts player?
Could you provide a link or screenshot or screenrecord for better understanding?

**Comment by Shiroe93** [comment]
https://user-images.githubusercontent.com/56954468/226166044-17295a4d-0361-4902-ba17-695f228695e8.mp4
sorry for not uploading a video in the frist place but i open this issue on my phone 
[here](https://youtube.com/shorts/Jy_B1DxfSVQ?feature=share) the shots if you want to try reproduce the problem

**Comment by inotia00** [comment]
yeah.. it's reproducible

**Comment by inotia00** [comment]
Google no longer allows external links to be used in YouTube Shorts comments

The issue can only be reproduced by clicking on the external link in the YouTube Shorts comment, so it is an issue that cannot be reproduced anymore
