### ISSUE TITLE
Request: Can you please add an option to hide these?

### ISSUE THREAD

**Issue by s23ultra512** [inotia00/ReVanced_Extended#513]
![Screenshot_20230319_140729_ReVanced Extended](https://user-images.githubusercontent.com/128295857/226174210-750431ee-6b7e-4dc7-ba7e-3da3b16b3463.jpg)

This suggestions list pops up in certain channels and its really annoying because when youre trying to hit the channel logo Youtube makes the page to jump because its loading that list in which quite often makes me to hit the wrong thing.

Thank you for your hard work.

**Comment by inotia00** [comment]
Duplicate issue already exists https://github.com/inotia00/ReVanced_Extended/issues/214
