### ISSUE TITLE
feat(patch): Add patch for enabling Explore(Trending) tab

### ISSUE THREAD

**Issue by Dr-Sauce** [inotia00/ReVanced_Extended#516]
### Application

YouTube

### Issue

The Shorts tab has replaced the Explore(Trending) tab and people like me hate it.

uYouPlus on iOS allows you to bring back the Explore tab. So I'm sure it's possible.

### Patch

![image](https://user-images.githubusercontent.com/82555878/226235655-ddb287d0-6919-47b0-8da3-76013f8a8a14.png)

### Motivation

This is a big feature that was requested but the ReVanced Team hasn't added this patch. It would be great if ReVanced Extended could add it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Spacellary** [comment]
Explore has been moved to this place now, but down there was definitely a much better place for it.

![Screenshot_2023-03-20-06-14-23-908_app rvx android youtube](https://user-images.githubusercontent.com/39604793/226296790-624dd929-e6e0-48e8-b65d-cea7d4894cf7.jpg)

**Comment by KyuhaSuk** [comment]
Yes, and currently it requires two steps to open that tab 🥲

**Comment by harshal8** [comment]
Give the switch option so that the trading button is on the right side of the home button

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.171.4+

**Comment by Dr-Sauce** [comment]
![Uploading Screenshot_20230504_141010_YouTube.png…]()

**Comment by Dr-Sauce** [comment]
@inotia00 Okay, thanks!
