### ISSUE TITLE
ModeAmbient mode doesn't appear on root on non root it appears thanks

### ISSUE THREAD

**Issue by Mozzaru** [inotia00/ReVanced_Extended#52]
### Type

Error while patching

### Application

Ambient mode doesn't appear on root on non root it appears thanks
Yt  17.49.37

### Bug description

Ambient mode doesn't appear on root on non root it appears thanks

### Steps to reproduce

Ambient mode doesn't appear on root on non root it appears thanks

### Relevant log output

```shell
Ambient mode doesn't appear on root on non root it appears thanks
```

### Screenshots or videos

![Screenshot_20221225-005450_YouTube](https://user-images.githubusercontent.com/100791931/209467001-aa458197-8fc4-4f69-90ab-c666f1e4d078.png)

### Device Environment

Custom ROM Android 10  and Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is not a bug
Ambient mode works only in dark mode
