### ISSUE TITLE
bug: Explore tab is missing from home page

### ISSUE THREAD

**Issue by ronin08** [inotia00/ReVanced_Extended#520]
### Type

Error at runtime

### Application

YouTube Extended v18.10.37

### Bug description

The trending/explore tab row is missing even after multiple refresh.

### Steps to reproduce

Open YouTube and check on home page.

### Relevant log output

```shell
NA
```

### Additional Context
After going incognito, the explore tab row is present.

_No response_

### Device Environment

Android 11, MIUI 12
Non-Root 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This bug also reproduces on unpatched YouTube

This is an issue Google needs to fix

**Comment by ronin08** [comment]
you're right. it's working fine now 👍
