### ISSUE TITLE
feat(patch): Option to remove hashtags from title 

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#521]
### Application

YouTube

### Issue

![Screenshot_2023-03-14-14-40-31-98_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125728453/226361995-de788b4f-e2d6-4459-bb38-8cd8a0a7f42d.jpg)
https://www.youtube.com/watch?v=Cfyc1M-MtUE
![Screenshot_2023-03-14-14-40-35-55_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125728453/226362027-0d490d62-f86c-4f41-b2c3-a53bac2610fe.jpg)

![Screenshot_2023-03-14-08-15-50-75_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125728453/226361243-90fd211a-1462-4869-a955-aecde72ee8b0.jpg)
https://www.youtube.com/watch?v=Wq-QuyF8b4k&t=5s
![Screenshot_2023-03-14-08-15-53-97_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125728453/226361276-f47718a9-9a85-4898-8a66-0413a6bbbcd8.jpg)

### Patch

A patch that will remove hashtags and playlist links(i guess) from title.

### Motivation

It would look more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
