### ISSUE TITLE
feat(patch): 2X Playback Speed By Long Press

### ISSUE THREAD

**Issue by insvishal507** [inotia00/ReVanced_Extended#527]
### Application

YouTube

### Issue

This Gesture To Speed Up 2X Playback speed when long press  Is Useful in PLAYit, Vanced Tuber.
This is a very useful feature when watching a movie, you can skip without missing any scene.
Just long press and playback speed upto 2X & when release long press Normal to 1X.

### Patch

Playback Speed increase to 2X By Long pressing in player , After release Long press comes to Normal playback speed 1x.
![Screenshot_20230321-150502_1_1](https://user-images.githubusercontent.com/128448282/226573645-35d7792d-a8fc-4efa-b98b-983f3a838db2.jpg)

### Motivation

Very Easy to use Geature Just Long press , It's useful when skip video without missing anything,
Double tap to is not ideal. 
Thanks you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
