### ISSUE TITLE
feat(patch): hide-product-you-might-like in search 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#528]
### Application

YouTube

### Issue

When you search for a specific product, in the search results there's a "products you might like" section which shows all the site and prices related to the product. 

![Screenshot_20230321-202445](https://user-images.githubusercontent.com/117499019/226647846-1de8bb95-3187-4fda-9c39-e7886732259f.png)

Upon pressing the drop down arrow:
![Screenshot_20230321-202457~2](https://user-images.githubusercontent.com/117499019/226647941-fc7aa832-25cd-4d1c-bd30-3606a8f02e28.png)

### Patch

A patch to hide this from the search, similar to hiding web results from the search.

### Motivation

I believe a similar patch is already present and also this is an ad promotion so it's better hidden.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Hi, @inotia00 were you able to replicate this on your side. If so can you please let me know the environment you tested it in. Since ReVanced is also having this issue and I'm not able to do a logcat atm, it would be really helpful to have that information.

**Comment by inotia00** [comment]
this banner is not exposed on my side

It is assumed to be geo-based advertising

Please tell me which countries this banner appears in

**Comment by ILoveOpenSourceApplications** [comment]
I am currently residing in India.

**Comment by inotia00** [comment]
Even if I try to change the country in settings or use a VPN, the banner does not appear..

**Comment by ILoveOpenSourceApplications** [comment]
Yeah, the same happened when I reported in ReVanced too. I tried giving access to the account but it wasn't happening either which I don't know why.

**Comment by ILoveOpenSourceApplications** [comment]
[logcat 1.txt](https://github.com/inotia00/ReVanced_Extended/files/11186002/logcat.1.txt)
I have captured the logcat regarding this and have attached it her. Hope it helps.
