### ISSUE TITLE
Crowdin "new strings" issue

### ISSUE THREAD

**Issue by User-noob2036876** [inotia00/ReVanced_Extended#53]
Normally, crowdin send "new strings to translate on xxxx project" to my mail, but revanced extended project not sends mail. This issue was also present in the previous crowdin. all other projects send notifications. 
![Screenshot_20221224-142026_Gmail.jpg](https://user-images.githubusercontent.com/117031829/209471422-c0dadbe9-65a1-4a34-b0df-606d32093846.jpg)

**Comment by User-noob2036876** [comment]
Like in picture

**Comment by inotia00** [comment]
place to report the issue is wrong
