### ISSUE TITLE
bug: full screen mode 

### ISSUE THREAD

**Issue by tikkamasalla** [inotia00/ReVanced_Extended#530]
### Type

Other

### Application

revanced extended ver:18.10.37

### Bug description

Full screen mode only tilts one side, doesn't tilt to the other when phone is flipped. 

### Steps to reproduce

Full screen mode and tilt phone 

### Relevant log output

```shell
.
```

### Device Environment

Android 13, one ui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a YouTube bug, not a ReVanced bug.
