### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by SpeederSpeederSpeder** [inotia00/ReVanced_Extended#532]
### Application

YouTube

### Issue

This patch should help to better control the volume and brightness of the video we are watching.

### Patch

This gestural volume control would be like this :
![1679431598906](https://user-images.githubusercontent.com/100723886/226737120-f099d19c-b9a4-4bf5-bbca-06ba2bb8ad06.jpg)

The gestural brightness control will be like this :
![1679431598909](https://user-images.githubusercontent.com/100723886/226737298-b1d555b9-f9ad-4249-b1e3-81410230edc6.jpg)

### Motivation

This patch should help people in the community to better control the volume and brightness of the videos they watch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/259
