### ISSUE TITLE
bug: Sponsorblock user private ID (and segment step) resets after flashing an update

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#535]
### Type

Error at runtime
### Application

Latest youtube with the latest patches

### Bug description

After flashing an update through magisk, the user id and segment step values reset. the User id is set to a random new account (same behavior as a fresh install) and the segment step value sets back to the default one (150ms).
All other sponsorblock settings (toggles and segments preferences) do not reset, and work as expected. 

### Steps to reproduce

1. check the current user ID
2. flash an update to the app or the patches (I think flashing the same version won't work)
3. open the app (It might take several times for this to happen)
4. check sponsorblock settings, and see a different user ID

### Relevant log output

```shell
---
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Does not provide an installation method via Magisk
Try installing using the method recommended in the [documentation](https://github.com/inotia00/revanced-documentation/wiki)

**Comment by NBruderman** [comment]
I build it through this tool, which uses the official CLI, and then package it to be flashable through magisk with root, and also create non-root apks.
https://github.com/j-hc/revanced-magisk-module

**Comment by inotia00** [comment]
Same. The documentations don't include the Magisk method.

Also, I do not guarantee that the Magisk method will work properly (the method you are using is an unofficial method).

Please proceed with the patch according to the method recommended in the documentations and open a new issue if the issue reproduces.
