### ISSUE TITLE
bug: v18.11.xx crashes or never opens

### ISSUE THREAD

**Issue by chris122380** [inotia00/ReVanced_Extended#537]
### Type

Error at runtime

### Application

ReVanced-Extended-18.11.35.apk

### Bug description

I installed the March 21st and March 22nd build from https://revanced.io the latest build I can launch is ReVanced-Extended-18.10.33.apk (I can play shorts for about 5 minutes and then the app crashes on this build.)

### Steps to reproduce

App won't launch on OnePlus 9 Pro running Oxygen OS 13. 

### Relevant log output

```shell
Unsure how to get this log
```

### Device Environment

Oxygen OS 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MondayNitro** [comment]
the version you mentioned isnt supported for patching yet, patch any of these versions only - "18.06.41","18.07.35","18.08.39","18.09.39","18.10.37"

**Comment by chris122380** [comment]
Recommend building using Termux (I found the directions to do that for ReVanced but not for ReVanced_Extended)?
