### ISSUE TITLE
bug: Autoplay automatically turns ON in incognito mode even if it is turned OFF

### ISSUE THREAD

**Issue by FlamySan** [inotia00/ReVanced_Extended#538]
### Type

Other

### Application

YouTube v18.10.37

### Bug description

Autoplay turned off works fine when you're logged in with an account. In incognito mode the status of Autoplay still shows as OFF but once you start playing any video it turns ON automatically. On turning it to OFF and restarting the application it again turns itself ON on playing any video. Works fine again once you switch back from incognito mode.

### Steps to reproduce

Step 1. Turn off Autoplay from settings in a logged in application 
Step 2. Play any video. The next video doesn't play automatically
Step 3. Get into incognito mode & play any video
Step 4. The next video autoplays after a countdown 

### Relevant log output

```shell
-
```

### Device Environment

Android 12, MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It also reproduces on unpatched YouTube

This is an issue on YouTube
Google should fix it
