### ISSUE TITLE
feat(patch): add tasker plugin

### ISSUE THREAD

**Issue by FineFindus** [inotia00/ReVanced_Extended#539]
### Application

YouTube

### Issue

Currently, it is not possible to run Tasker automations following an action in the YouTube app. For example, it is not possible to run an automation to enable auto-rotate when playing a video in the app.

### Patch

The path should hook into commonly done actions such as watching a video, adding a video to a playlist, etc. and provide them to a tasker plugin.

### Motivation

This further improves the usability by allowing users to customize how their app works in combination with other apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
