### ISSUE TITLE
bug: Seekbar not displaying properly when playback controls are hidden.

### ISSUE THREAD

**Issue by DanyaalMajid** [inotia00/ReVanced_Extended#54]
### Type

Cosmetic

### Application

YouTube v17.49.37

### Bug description

The bug is visible on all videos, where the normally red seekbar changes to a white bar when playback controls are not in focus, the buffering indicator is also hidden, this issue is most noticable in non landscape mode, it does also happen in Fullscreen mode, but only for a split second.

### Steps to reproduce

All recommended patches included, only custom name patch skipped.

### Relevant log output

```shell
No log provided.
```

### Screenshots or videos

![Screenshot_20221225-204223_YouTube](https://user-images.githubusercontent.com/71455068/209474202-eeda12c7-4d6f-4711-a36d-1ad2efa16369.png)
![Screenshot_20221225-204234_YouTube](https://user-images.githubusercontent.com/71455068/209474206-48353b77-5391-47db-bd08-ab93ceb161d5.png)

### Device Environment

Android 12.1, CrDroid 9, Poco F3

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is not a bug with rvx

Google changed YouTube's seekbar color to white in the dark mode of the new layout.

If you've used Stock YouTube, you'll understand.

**Comment by DanyaalMajid** [comment]
> This is not a bug with rvx
> 
> Google changed YouTube's seekbar color to white in the dark mode of the new layout.
> 
> If you've used Stock YouTube, you'll understand.

Yes, I understand, I haven't used stock YouTube in a long time, but why is it not showing the buffering bar, it used to be light gray, but now it is only visible sometimes, is that also a stock feature?

**Comment by inotia00** [comment]
yeah.. same in stock YT

**Comment by inotia00** [comment]
Added releated settings in `revanced-patches-v2.147.2`
https://github.com/inotia00/revanced-patches/releases/tag/v2.147.2

**Comment by DanyaalMajid** [comment]
Thanks for the positive response, I hope that you continue your work as long as you are enjoying it.
I know that this isn't the place to say these kinds of things, so feel free to remove it.

All open source devs are doing amazing work, and the things that you guys do make our lives better, even if it is something as small a color on some bar. Peace.
