### ISSUE TITLE
bug: theme not applied to left separator of compact like button in return-youtube-dislike

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#540]
### Type

Other

### Application

YouTube v18.10.37
Revanced Patches v2.166.10

### Bug description

![20230323_004947](https://user-images.githubusercontent.com/127908708/227070833-55c60412-f7fa-4507-b809-7fccc8432d80.jpg)

**When the option "Compact like button" is disabled, it makes the first stick and dot appear bold.**
![20230323_001951](https://user-images.githubusercontent.com/127908708/227069367-ba377d26-4e21-4d0f-8c30-4d9a551d94ed.jpg)

**Strangely if you just go to settings it gets fixed.**

https://user-images.githubusercontent.com/127908708/227071362-cad09ac4-3520-46e0-9f6a-a57833b81736.mp4

**However, if you close and re-open YouTube, the issue comes back.**

### Steps to reproduce

1. Disable "Compact like button" option
2. Close YouTube app
3. Open YouTube app and play any video

### Relevant log output

```shell
N/A
```

### Solution

It should always appear like this:
![20230323_002132](https://user-images.githubusercontent.com/127908708/227070157-36471d03-a093-448b-9d7a-cb6c6984ca1e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
With a high probability, it is assumed to be a theme related issue of the OS you are using.

For example, MIUI users reproduced this issue when they enabled system forced dark mode or RVX did not whitelist forced dark mode.

Check the theme-related settings of your OS

**Comment by Kuddus73** [comment]
> With a high probability, it is assumed to be a theme related issue of the OS you are using.
> 
> For example, MIUI users reproduced this issue when they enabled system forced dark mode or RVX did not whitelist forced dark mode.
> 
> Check the theme-related settings of your OS

I'm using One UI and I have indeed dark mode activated.

Now, what should I do?

**Comment by inotia00** [comment]
just turn off force dark mode

**Comment by Kuddus73** [comment]
@inotia00 The issue wasn't caused by force dark mode cuz I never had it on.

The actual reason is that my phone was in light mode but I wanted the RVX app in dark mode, so I changed it to dark theme from Setting/General/Appearance.

This bug also occurs if the phone theme is dark and you also choose dark theme from the app settings, but in that case you can simply choose to use the device theme option to fix it.

However, if someone has their phone in light theme but they want the app to be dark, this bug will keep occuring, so that's why I'm re-opening the issue.

**Comment by inotia00** [comment]
Please proceed with the patch again with the latest resource and tell me the result

**Comment by Kuddus73** [comment]
I just unistalled and cleaned installed YouTube v18.13.38 with patches v2.168.27, and it keeps crashing just by opening it.

**Comment by inotia00** [comment]
bruh any crash log?

**Comment by Kuddus73** [comment]
Actual bruh moment.
My phone was definitely acting up cuz the app isn't crashing anymore, no clues what happened.

Anyway, with YouTube v18.13.38 and Revanced Patches v2.168.27, and can confirm the bug still occurs.

(Including proof this time for credibility lol)

https://user-images.githubusercontent.com/127908708/230750347-035f34f2-fb2e-405c-a7b8-f08954f630da.mp4

**Comment by Kuddus73** [comment]
> Strangely if you just go to settings it gets fixed.

**NOTE: After you visit settings, you must restart the app to reproduce the bug.**

**Comment by inotia00** [comment]
Same issue as [this issue](https://github.com/inotia00/ReVanced_Extended/issues/690), should have been fixed in revanced-patches-v2.168.30
