### ISSUE TITLE
bug: button containers still visible when turned off

### ISSUE THREAD

**Issue by manishloshali** [inotia00/ReVanced_Extended#541]
### Type

Cosmetic

### Application

youtube 18.10.37 patch 2.166.10

### Bug description

Even if the button container setting is off some buttons are still visible.
[Sometimes ](https://imgur.com/a/f9s18jF)the buttons are just weird.

opening new case because [#339](https://github.com/inotia00/ReVanced_Extended/issues/339) was closed.

### Steps to reproduce

1. Go to bottom player layout settings 
2. Hide Create, clip and thanks buttons
doesn't work

### Relevant log output

```shell
_
```

### Screenshots or videos

![b0a212f4-6d99-495d-b788-d02e84608b17](https://user-images.githubusercontent.com/125728453/227096256-a108b722-faf0-40df-8bb8-3e013038c9a2.jpg)
![39c5e155-b301-40c5-b6d6-b1a9e60c3071](https://user-images.githubusercontent.com/125728453/227096310-27123973-cef3-406c-b04b-c84f03ec543f.jpg)
![a886930d-1d74-4d8b-95df-122304402b2b](https://user-images.githubusercontent.com/125728453/227096358-e93a7843-dd6c-4f0d-ad79-f3a196737878.jpg)
![98936a67-1bc6-4c12-adfb-aa462b086920](https://user-images.githubusercontent.com/125728453/227096394-ff14bfdd-39bd-48db-ab60-2f3281049006.jpg)

### Solution

Everything worked fine in patch v2.166.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, this issue is not fixable

`hide-button-container` patch has too many bugs,
I will remove the `hide-button-container` patch in the next release

**Comment by manishloshali** [comment]
Please don't remove it. It works sometimes. 
Also while using old YouTube layout, it works without any bugs. It has something to do with new layout.
Suggestion: If you can reorder bottom buttons (or include an option to), we can just reorder create, clip and thanks button to last so even if they appear we won't see them.

**Comment by Vipin2003** [comment]
No man...I always use the Share button.
After integrating, I have to enable the useless clip thanks buttons also..😭😭😭 Please revert it back

**Comment by manishloshali** [comment]
Me too. Now i have enabled copy link overlay

**Comment by buiducanh142qn** [comment]
I think the hide-button-container patch should be removed to avoid affecting the layout.
Even when you turn on the hide action buttons option, the YouTube layout (new layout) looks weird.

**Comment by inotia00** [comment]
Separating it like before reproduces the bug for some people
(This is also the same for official ReVanced)

The only way to fix the bug completely is to integrate the hide action buttons into one.

**Comment by NearCram** [comment]
@inotia00 Would it be possible to keep both as seperate patches so people can apply them depending upon which layout they use?

**Comment by devilboy1122** [comment]
Hide action button are hidden share option not showing

**Comment by venkat2305** [comment]
Need share option. Please give options to hide the individual buttons.
