### ISSUE TITLE
Cannot share videos to other platforms bug:

### ISSUE THREAD

**Issue by Octoberrust75** [inotia00/ReVanced_Extended#542]
### Type

Other

### Application

YouTube Revanced 18.10.37

### Bug description

Tried to share several videos to Facebook chat, an error pops up 

### Steps to reproduce

Tried to share a Music video to Facebook chat. Error 

### Relevant log output

```shell
Error says: Failed to load. Try again later
```

### Screenshots or videos

![Screenshot_20230323-074847-751](https://user-images.githubusercontent.com/85897520/227194745-dce3e5ed-c4eb-4445-aea4-20a1725a60da.png)

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please check if it reproduces on unpatched YouTube
