### ISSUE TITLE
feat(patch): allow higher custom playback speed than 5x

### ISSUE THREAD

**Issue by hwasiti** [inotia00/ReVanced_Extended#544]
### Application

YouTube

### Issue

Current devices are very capable of higher playback speeds, especially with lower resolutions like 720p. On iOS ['It's playing' video player app](https://apps.apple.com/us/app/its-playing/id442839861) support much higher speeds than 5x. 

Please consider letting the user add his own highest speed and let her/him decide what number he would like to enter in a textbox in the settings.

### Patch

adding truly custom playback speed in a textbox in settings

### Motivation

skimming videos of talks with slides would be fantastic at high speeds. My geeky instinct loves to get all the juice from the GPU/CPU of my new Samsung Gnote phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
You can add it via `options.toml`
(Already provided by rvx-builder and Revancify)

Since it must be added in the patching process, it is absolutely impossible to control via settings.

**Comment by hwasiti** [comment]
Thanks for the genius solution that you have made in the recent update. Now we can add speeds up to 9.9x. 

But why the limit to 10x? A warning may suffice for low-end devices and let us experiment with higher speeds :)
