### ISSUE TITLE
bug: <App crashes while opening in miui>

### ISSUE THREAD

**Issue by slurrednblurred** [inotia00/ReVanced_Extended#546]
### Type

Error while patching

### Application

Latest version of Revanced Extended

### Bug description

App automatically crashes to moment I try to open it, I've tried all techniques available on the internet but nothing worked. 

### Steps to reproduce

. 

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_2023-03-23-13-23-38-570-edit_com miui screenshot](https://user-images.githubusercontent.com/90458001/227274367-6650c2f5-9963-48ce-82cd-b90bd933cc8e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
repatch with latest patches
