### ISSUE TITLE
bug: autoplay stops when sponsorblock skips at the end of the video

### ISSUE THREAD

**Issue by Faszom11** [inotia00/ReVanced_Extended#547]
### Type

Error at runtime

### Application

Latest supported youtube app, latest patches / integrations

### Bug description

When you're watching playlists or just random videos with autoplay on, it stops if sponsorblock skips the end of the video and you have to flip the phone to either portrait or landscape mode to start the playing the next video.

### Steps to reproduce

Just watch a video with sponsor at the end of it.

### Relevant log output

```shell
No logs
```

### Screenshots or videos

https://user-images.githubusercontent.com/127752289/227276990-85e80fc2-2f4b-4bb3-876e-30baeab9601a.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by manieKMP** [comment]
I don't think this bug is related strictly to autoplay. It's an issue with most videos that have sponsorblock section at the end. Player just stays in a loop and plays last bit of the video, not showing controls (like replay button) and it seems, not being able to start next video.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.12)

**Comment by ayushTNM** [comment]
I am experiencing this in latest 2.193.18 YouTube 18.39.41

**Comment by KobeW50** [comment]
> I am experiencing this in latest 2.193.18 YouTube 18.39.41

Please open a new bug report
