### ISSUE TITLE
bug: Splashscreen not visible in MIUI

### ISSUE THREAD

**Issue by shreyjain1998** [inotia00/ReVanced_Extended#548]
### Type

Error at runtime

### Application

YouTube v18.10.37+

### Bug description

Blank splash screen is coming in Android 13 since v2.166.8 release. I have tried clean install and the issue still persist. 

### Steps to reproduce

YouTube v18.10.37+
Patch v2.166.8+
Android 13 
Miui 14

### Relevant log output

```shell
Na
```

### Screenshots or videos

https://photos.app.goo.gl/D3jwMwDE5kHXgPs39

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It is no longer reproduced in latest patches.
closing the issue
