### ISSUE TITLE
bug: video buffering 

### ISSUE THREAD

**Issue by Daniel-San-13** [inotia00/ReVanced_Extended#550]
### Type

Error at runtime

### Application

YouTube revanced 18.08.39

### Bug description

When playing any video, it will start buffering after around 15 seconds of playback.

### Steps to reproduce

Start YouTube revanced
Play any video
Wait

### Relevant log output

```shell
.
```

### Device Environment

Android 10, MIUI 12.5.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
update to latest patches and turn on protobuf-spoof
