### ISSUE TITLE
feat(patch): Option to also hide the gray seperators on the account menu

### ISSUE THREAD

**Issue by dumbdeniz** [inotia00/ReVanced_Extended#551]
### Application

YouTube

### Issue

The gray seperators & padding of each "category"? remain even if the options are hidden using the custom filter.

Screenshot:

![Screenshot_20230323-235323_YouTube](https://user-images.githubusercontent.com/77262340/227374066-ccca3d5a-8b19-4fce-8f59-e0d17cc1fe96.jpg)

### Patch

A seperate option in layout settings to hide all seperators on the account menu, or updating the hide-account-menu patch method to also hide the seperator if all the category content is hidden.

What hide all seperators option for the account menu would look like:

![1](https://user-images.githubusercontent.com/77262340/227375627-7ee16460-d848-4dd6-8763-c857181f7103.jpg)

What the account menu would look like if the patch only hid the seperators of the empty categories:

![2](https://user-images.githubusercontent.com/77262340/227376635-50939217-db7b-4fe9-a39a-b2d505f586d4.jpg)

### Motivation

the hide-account-menu patch was something i was really looking for and i was about to open a feature request for it soon before it got implemented. The account menu was the only place left untouched and thus filled with completely unnecessary stuff like premium, help, feedback etc. Now that the patch got implemented we can finally hide the unnecessary stuff which is really great.

It's mostly a cosmetic thing, still better than before obv but it could be better i think if implemented, as it would make the account menu look better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
