### ISSUE TITLE
question: gestures on fullscreen comments

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#552]
### Application

YouTube

### Description

From today I find myself a new form of gesture that I've never had before

https://user-images.githubusercontent.com/125223735/227384718-2119f5ff-1e31-4131-85d9-4588ebce74fd.mp4

Android 11, Miui 12.5.
On YouTube stock same version 18.11.35 I don't have these gestures, what can it be?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jsinfate** [comment]
I noticed today too that I have this same issue. Gestures are not working for brightness and volume. When I use either swipe gesture the video "zooms" in and out, in normal size or full screen. 
I tried updating ReVanced Extended and ReVanced Manager, disabling each swipe gesture setting one at a time then enabling them one at a time, but nothing changed.

I am on Android 13 using a OnePlus 11 phone.

**Comment by inotia00** [comment]
Interesting

This doesn't look like ReVanced's swipe gesture, it appears to be a new swipe gesture on YouTube

I'm guessing it's probably an A/B test, but thanks to you, I found out that this feature was added to YouTube.

**Comment by madhurvarshney** [comment]
Yeah, I have this feature too.

**Comment by jhon1282** [comment]
Now also on youtube stock 18.12.34 stable I have this gesture.
I really think it's a new layout
