### ISSUE TITLE
bug: hide account menu doesn't hide "Your videos" and "Downloads" sections

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#553]
### Type

Other

### Application

YouTube v18.11.35
Revanced Patches v2.166.12

### Bug description

**The title pretty much explains it.**

https://user-images.githubusercontent.com/127908708/227390949-dc5b57db-9346-44ca-9e94-b7a11cfdb5ae.mp4

### Steps to reproduce

1. Enable "hide account menu" option.
2. Add custom filters "Your videos,Downloads".
3. Restart the app.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is not a bug

Hiding those two hasn't been implemented yet
