### ISSUE TITLE
bug: Custom filter hides all account options when empty

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#554]
### Type

Other

### Application

YouTube v18.11.35
Revanced Patches v2.166.12

### Bug description

**When adding some filters, if you by mistake erase everything and press OK, it hides all your account options, including the Settings and so you can't go back to fix the issue.**

![Screenshot_20230324_002321_YouTube](https://user-images.githubusercontent.com/127908708/227413965-74818541-919e-4e4a-94b7-92bcbe55f862.jpg)

### Steps to reproduce

1. Enable "hide account menu" option.
2. Delete everything inside "Custom filter" and press OK.
3. Restart the app.

### Relevant log output

```shell
N/A
```

### Solution

**Prevent accepting empty filter.**

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.166.15
