### ISSUE TITLE
bug: shorts player's glitch

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#556]
### Type

Other

### Application

YT

### Bug description

1.There is a problem with Shorts that the Videos go in PIP mode in Shorts. Like every video is overlapping each other.
2. Some part of Shorts Video get hides.
3. This Shorts PIP issue also affects the home videos also. I doon't have the clip of that but happened yesterday.
(Will upload if happens again)

### Steps to reproduce

Happens on when opens YT 4-5 times. (Check if this also happens for you too)

### Relevant log output

```shell
...
```

### Screenshots or videos

https://photos.app.goo.gl/w65nKhv4Zq8aXxvW9

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Vipin2003** [comment]
https://photos.app.goo.gl/naARmYD6DP6GWgm96

After visiting comments, the pivot bar get visible.

**Comment by inotia00** [comment]
As you know, hiding pivotbar on shorts players is an Experimental Flags

**Comment by Vipin2003** [comment]
But pls check for the pip bug...it is very annoying

**Comment by inotia00** [comment]
It is not reproduced in my side

I'll fix it when this issue can be reproduced on my side.

**Comment by Vipin2003** [comment]
Now check this which pip issue I am talking about : 
https://photos.app.goo.gl/fqauRBBn32PZ174p6
