### ISSUE TITLE
bug: app crashing instantly on opening 

### ISSUE THREAD

**Issue by kanishk-upadhyay** [inotia00/ReVanced_Extended#559]
### Type

Error at runtime

### Application

ReVanced-Extended-v18.11.35

### Bug description

The app just crashes on opening when I updated it to version 18.11.34 and things haven't changed in version 18.11.35 also

### Steps to reproduce

Just opening the app causes it to close

### Relevant log output

```shell
revanced extended keeps stopping
```

### Screenshots or videos

https://user-images.githubusercontent.com/66172350/227592687-0b359032-25d1-423b-9033-f42a58b46be5.mp4 

### Solution

The app version 18.10.33 was working just fine

### Device Environment

Android 13,  realme UI 4.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Repatch to the latest releases following the guide in the [documentations](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android))
