### ISSUE TITLE
question: custom-branding-icon description naming

### ISSUE THREAD

**Issue by xafn** [inotia00/ReVanced_Extended#56]
### Application

Other

### Description

Hi inotia! First I got to say, RVX is pretty nice. 

I was just wondering if you can rename the custom branding red and blue patches description to not say ReVanced, but instead afn. This is not because I really care about the credit, but more so to remove confusion. People think that my icon is ReVanced Extended's icon or ReVanced official icon, when in reality it's just my icon submission for now. Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Hi, I'm also glad to be in touch with you after a long time.

Since you are the original author of those two icons, I would like to accommodate your request.

I also want to prevent confusion from users.

Is there any explanation you would like in particular?

**Comment by xafn** [comment]
Ah sorry I didn't respond, I haven't been caught up with my emails for a while. Thank you for resolving this, appreciate it!

**Comment by Spacellary** [comment]
@xafn People are clamoring for your icons, if you are able of course, we'd be happy to have the SVG files for further updates.
