### ISSUE TITLE
Application closing by itself 

### ISSUE THREAD

**Issue by Christophecs2** [inotia00/ReVanced_Extended#560]
### Type

Error at runtime

### Application

The application closes itself when watching 4shorts or more.

### Bug description

When the app closes

### Steps to reproduce

Only watch 4 shorts in a row 

### Relevant log output

```shell
Doesn't throw any log error when the app closes by itself
```

### Additional context

I believe it could be an application error, I'm not very good at programming, but is it possible to understand that there is a possibility of a timeout perhaps?

### Device Environment

Miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Christophecs2** [comment]
Just correcting the title

**Comment by inotia00** [comment]
repatch with latest sources

**Comment by Christophecs2** [comment]
True, I updated and now it works
Thank you very much!
