### ISSUE TITLE
question: <title>: some features aren't working.

### ISSUE THREAD

**Issue by LoneFaizaan** [inotia00/ReVanced_Extended#561]
### Application

YouTube

### Description

I have installed both YouTube revanced extended & Yt music but in the revanced extended YouTube i don't get the feature of open in yt music in YouTube revanced extended,even i have enabled the feature & restarted yt revanced extended many times.. could you please fix this it would help a lot as many users are musicphile & it let us add that music to our playlist easily. 
& Special thanks to your whole team for creating such an interesting & helpful mod ❤️❤️❤️

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It is normal that ReVanced (NON-ROOT) cannot open ReVanced Music (NON-ROOT)

Because there is no patch for this
