### ISSUE TITLE
bug: `hide-mixplaylists` patch blocks search results for certain keywords

### ISSUE THREAD

**Issue by Aspect250** [inotia00/ReVanced_Extended#562]
### Type

Error at runtime

### Application

Youtube 18.11.35
Revanced Extended 2.166.12
Extended integrations 0.100.12

### Bug description

Searching for "for you" comes up with no loading videos
Has to be "for you" in that order. 
This only happens in extended and not in normal revanced or normal youtube.

### Steps to reproduce

Step1. Patch with recommended patch's and recommended version
Step 2. Search for "for you"
Step 3. No video is loaded

### Relevant log output

```shell
...
```

### Screenshots or videos

![Screenshot_20230325_210032_ReVanced Extended](https://user-images.githubusercontent.com/102602600/227711039-09e8db28-9e9d-48bf-996a-0bbbd30bf283.jpg)
![Screenshot_20230325_210504_ReVanced Extended](https://user-images.githubusercontent.com/102602600/227711044-8788f668-a2ed-4b0e-9f9f-23923a75e76f.jpg)

https://user-images.githubusercontent.com/102602600/227711963-97139c24-0c0d-4592-a79a-b821f1c20c7c.mp4

### Additional context

I also live in Australia if that's relevant at all

I encountered this after I wanted to see the borzoi meme with kermit singing

### Device Environment

Android 12, one ui 4.1, sm-970f / S10e, March update 2023

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
One of the adblock keywords of `hide-mixplaylists` is [for you](https://github.com/inotia00/revanced-integrations/blob/056f05360bafe46d49aa199b84f1db6108ec2473/app/src/main/java/app/revanced/integrations/patches/ads/ByteBufferFilterPatch.java#L26) 

Blocking mix playlists requires a fairly aggressive blocking filter rule, so it seems that everything is blocked even when the keyword is included in the search results.

Temporarily, turn off the `hide-mixplaylists` setting

**Comment by inotia00** [comment]
This issue will be fixed in the next release

Anyway, thanks for reporting an issue that no one has reported for months (probably because it's hard to find)

**Comment by Aspect250** [comment]
Found it couple weeks back and thought it was because of it being a new release as I always patch to the newer version on release. Glad I helped, have s great day.

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.166.15
