### ISSUE TITLE
question: <title>: 

### ISSUE THREAD

**Issue by Aditya646754** [inotia00/ReVanced_Extended#563]
### Application

YouTube

### Description

How to download older version of youtube extended v18.10.37, bcus i dont want to download from other pirated sites.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by manishloshali** [comment]
Download YouTube 18.10.37 apk from Apkmirror
