### ISSUE TITLE
question: <title>: Settings search bar inside ReVanced Extended

### ISSUE THREAD

**Issue by shreyjain1998** [inotia00/ReVanced_Extended#564]
### Application

YouTube

### Description

So I generally patch the app with all the available/recommended patches but it is really hard sometimes to find a particular setting toggle on a random day. So would that be possible to have a search bar for settings inside the ReVanced Extended settings which will show results similar to our phone OS settings search feature?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/83
