### ISSUE TITLE
feat(patch): Bypass Ambiant Mode off if battery saver is On

### ISSUE THREAD

**Issue by kevinr99089** [inotia00/ReVanced_Extended#566]
### Application

YouTube

### Issue

The Ambient mode which is disable when battery saver is enable

### Patch

This patch would allow to bypass Ambiant Mode restriction when Battery Saver is On.

### Motivation

For those who like the ambient mode, but can't enjoy it because of the battery saver (e.g., when the battery can't hold a charge).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.3](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.3)
