### ISSUE TITLE
suggestion: fix typo

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#567]
### Type

Cosmetic

### Application

YouTube

### Bug description

It's not actually a bug but more like a cosmetic inconsistency.

Here all the options in the flyout menu layout settings looks good except for Hide-Watch-in-VR-menu. My request would be to use a lowercase 'w' instead of the uppercase 'W' so that it's more consistent with the other options.
![Screenshot_20230326-095823~2](https://user-images.githubusercontent.com/117499019/227755430-3308508f-055e-4d8e-b6fb-e97afcfb3028.png)

### Steps to reproduce

Just go into flyout menu settings after including the respective patch.

### Relevant log output

```shell
Nil
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.166.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.18)
