### ISSUE TITLE
bug: `hide-player-button-background` patch makes animations hidden

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#569]
### Type

Error at runtime

### Application

verizon 18.11.36

### Bug description

when i hide player button background, tapping on the video player makes the animation of the shadow filter a little bit laggy compared to the hide player button background patch by ReVanced Team

### Steps to reproduce

turn on Hide player button background feature

### Relevant log output

```shell
.
```

### Screenshots or videos

ReVanced

https://user-images.githubusercontent.com/36302515/227757818-c273286a-1e52-4cee-974d-614f0f57559c.mp4

ReVanced Extended

https://user-images.githubusercontent.com/36302515/227757830-80d857cb-f239-46c4-9e97-4a88fa40f4b6.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This issue can be completely fixed, but in that case you won't be able to control ON/OFF via settings

**Comment by BrilliantlyEducated** [comment]
fine

**Comment by BrilliantlyEducated** [comment]
please unblock me on Telegram
