### ISSUE TITLE
bug: 'Hide shorts shelf' also hides shorts in search results

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#570]
### Type

Error at runtime

### Application

YouTube v18.11.36

### Bug description

When 'Hide shorts shelf' option is ON and you search a keyword and select 'Shorts' from the filter bar at the top, no search results are shown.
It does not happen when 'Hide shorts shelf' is OFF.
I don't know if this is intended/expected.

### Steps to reproduce

1. Enable 'Hide shorts shelf' option.
2. Search a keyword.
3. Select 'Shorts' from the filter bar.

### Relevant log output

```shell
N.A.
```

### Screenshots or videos

https://user-images.githubusercontent.com/125809686/227762504-4eff7b9f-b45d-4f9e-b9d8-8d3996969808.mp4

### Device Environment

Android 13, Realme UI 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is not a bug
