### ISSUE TITLE
bug: disabling press-to-swipe option doesn't work

### ISSUE THREAD

**Issue by MF-Debug** [inotia00/ReVanced_Extended#571]
### Type

Error at runtime

### Application

Youtube v18.11.36

### Bug description

While watching any videos, it triggers the press-to-swipe feature if I long press on the player screen even if it is disabled under the option swipe controls.

### Steps to reproduce

1. Watch any videos with press-to-swipe option disabled under swipe controls.
2. Long press on the player screen.

### Relevant log output

```shell
nothing
```

### Screenshots or videos

https://user-images.githubusercontent.com/6173607/227767298-c1a2b06f-44f2-4b3a-8d7a-18adc7acfc8b.mp4

### Additional context

Here is my exported settings for RVX: https://tempfile.io/en/sGsLDijYQ6wdbku/file

revanced-patches: 2.166.12
revnaced-integrations: 0.100.12

### Device Environment

Samsung Galaxy Note 3 SM-N9005, LOS 18.1, arm-v7a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a gesture from YouTube, not a gesture from ReVanced
