### ISSUE TITLE
feat(patch): screen lock icon to prevent accidental touch

### ISSUE THREAD

**Issue by farz-bhullar** [inotia00/ReVanced_Extended#572]
### Application

YouTube

### Issue

Sometimes, while watching videos, an accidental touch can cause the next or previous video to play, which is a pity.

### Patch

It would be helpful to have an overlay button with a lock icon that can lock/unlock the screen, similar to the one found in MX Player.

### Motivation

This feature could be useful for others as well, especially since I've seen many people complain about accidentally touching the seek bar.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/10
