### ISSUE TITLE
feat(patch): Sorting "from old to new" videos in the "Like", "History" and regular playlists, as it used to be in Vanced.

### ISSUE THREAD

**Issue by sks2012** [inotia00/ReVanced_Extended#573]
### Application

YouTube

### Issue

Add the ability to sort records by date, from old to new, as it used to be in Vanced.
Sometimes I'd like to see the very first video in the "liked" playlist... But, 10,000 likes to swipe... Hell!

### Patch

Sorting "from old to new" videos in the "Like", "History" and regular playlists, as it used to be in Vanced.

### Motivation

It's very convenient to start watching tutorials starting with the FIRST video and going from old to new... 
Not manually flipping down through 300 videos...
Or "History", start watching from the very first videos... Not by painfully leafing through all 14,000 entries!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by donthaveaneme** [comment]
I also have the same request, YouTube has started taking down the old version by disabling the player and directing users to download or use the newest version of YouTube. But the functionality of sort by, like and dislike, etc. Still working without problems

**Comment by Sasukegay** [comment]
I have a similar problem, but not just for playlists alone, all channels too. I would like to see the very first video on some channels, but scrolling down the entirety of a channel just for one video is annoying, especially for channels with a lot of uploads. Would be nice to have this
