### ISSUE TITLE
suggestion: modify button container under videos 

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#574]
### Application

YouTube

### Description

Can you make the button container settings same as official revanced, where share button is kept as separate from remix,clip and thanks buttons? because the share button is necessary for users, also having only 3 buttons(like, download and save) means we have weirdly huge spaces between buttons.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Since hiding the Share button is buggy, I simply unified it as 'Hide action buttons'.

It will be separated again when the bug is fixed
