### ISSUE TITLE
bug: breaking news shelf is shown although the settings to hide it is turned ON

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#575]
### Type

Error at runtime

### Application

YouTube v18.11.36

### Bug description

Starting from today onwards, the breaking news shelf started getting shown to me although I have enabled the 'Hide breaking news shelf' option.
It was hidden until yesterday. It just started showing up today (from about 12 am IST) all of the sudden.

### Steps to reproduce

N.A.

### Relevant log output

```shell
N.A.
```

### Screenshots or videos

https://user-images.githubusercontent.com/125809686/227799753-9beccd21-5886-4620-b8ca-14d60ac2c01e.mp4

### Device Environment

Android 13, Realme UI 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
As with the [previously reported issue](https://github.com/inotia00/ReVanced_Extended/issues/549), it is assumed to be an issue related to the new layout (A/B test).

Fixing is possible only when the new layout is applied to me.
