### ISSUE TITLE
feat(patch): custom-branding-icon-old_vanced

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#576]
### Application

YouTube

### Issue

can you add a patch to replace stock youtube icon with old vanced icon(the one that was present in vanced 14.xx and 15.xx). the icon looked really good and i think you might agree with that. i also have res zip for the old vanced icon and i can add links here in case you agree to add the patch

### Patch

![ic_launcher](https://user-images.githubusercontent.com/87489540/227816741-5c03ba7d-917d-4748-a269-47a7ed5efa23.png)

### Motivation

the icon looks better than stock youtube icon in my opinion

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by manishloshali** [comment]
[#410](https://github.com/inotia00/ReVanced_Extended/issues/410)
