### ISSUE TITLE
Landscape (full screen) is bright and no way to adjust

### ISSUE THREAD

**Issue by ballo** [inotia00/ReVanced_Extended#577]
### Type

Error at runtime

### Application

Version 18:10:33
Android 9

Problem: in landscape (full screen) the brightness goes way up and there is no way to adjust it back to normal. I can swipe down to access the brightness bar but can't adjust it at all. There is no work-around except to never use landscape/fullscreen mode.

### Bug description

Landscape/Fullscreen mode is bright and no way to adjust

### Steps to reproduce

1: flip phone to landscape while playing video
2: no step 2

### Relevant log output

```shell
?
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
You are using an unsupported version. After patching to a supported version, please open an issue.

**Comment by ballo** [comment]
I literally just downloaded the APK from https://revanced.io/#download-apk

If that version isn't good enough well I don't know what to tell you

**Comment by ballo** [comment]
> You are using an unsupported version. After patching to a supported version, please open an issue.

I literally just downloaded the APK from https://revanced.io/#download-apk

If that version isn't good enough well I don't know what to tell you

**Comment by inotia00** [comment]
revanced.io is an illegal site.

If you downloaded the prebuilt APK from there, I can't help you any more.

Contact the administrator of the site.
