### ISSUE TITLE
Bug: "Enable swipe commands" in French version 

### ISSUE THREAD

**Issue by Poney01234** [inotia00/ReVanced_Extended#579]
### Type

Error at runtime

### Application

YouTube 18.02.34

### Bug description

Running the French version on March 27, 2023. 
The toggle "Enable swipe commands" ("Activer les commandes de balayage") is turned off by default, with the caption "The swipe commands are off" ("Les commandes de balayages sont désactivées"), BUT the the commands are on! 

To disable the commands, I have to turn on the setting ("The swipe commands are off"). 

Maybe it's not just in the French version 

### Steps to reproduce

Default app 

### Relevant log output

```shell
No log
```

### Screenshots or videos

![Screenshot_20230327-080923_ReVanced Extended](https://user-images.githubusercontent.com/95702666/227857062-aadd94d4-9cb2-4cf6-bd57-f9bf1da6f2b3.jpg)

### Solution

The labels are in line with the toggle state
The toggle state should be reversed to match the setting. 

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
unsupported version

**Comment by Poney01234** [comment]
Hello, what do you mean, "unsupported version"? Unsupported by what?

**Comment by inotia00** [comment]
You are using an unsupported version

The currently supported versions are listed below.

YouTube
v18.11.36
v18.10.37
v18.09.39
v18.08.39
v18.07.35
v18.06.41

Versions other than this version are not supported.

Patch the latest build according to the [documentations](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android)) .

**Comment by Poney01234** [comment]
OK thanks
