### ISSUE TITLE
feat(patch): Remove "?feature=share" while sharing videos.

### ISSUE THREAD

**Issue by AdishSagarawat** [inotia00/ReVanced_Extended#58]
### Application

YouTube

### Issue

This extra unwanted content should be removed man !

### Patch

![6149741544480027534_121](https://user-images.githubusercontent.com/69076256/209645871-2c8b74a4-68db-4c6a-aa63-fb0d83351fd9.jpg)

### Motivation

Make the URL tidy, Neat and Clean :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It seems that Google no longer provides these features on the server side.
