### ISSUE TITLE
feat(patch): Hide category bar in searches

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#583]
### Application

YouTube

### Issue

![Screenshot_20230327_153252_YouTube](https://user-images.githubusercontent.com/127908708/227979448-603ba365-cfb1-4cd1-baf2-dbbc8dcbe614.jpg)

### Patch

A toggle to turn it on or off.

### Motivation

To make YT more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Kuddus73** [comment]
> Including unpatched YouTube, I don't see this category bar.

I found out that it was requested previously (https://github.com/inotia00/ReVanced_Extended/issues/513), but for some reason that request was closed as a duplicate, even though it wasn't.

**Comment by inotia00** [comment]
If so, it looks like this isn't an A/B test, it's a country-specific layout.
Which country do you belong to?

**Comment by inotia00** [comment]
ahh never mind
I was able to reproduce it using a VPN from my neighboring country.

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.166.21
