### ISSUE TITLE
feat(patch): search button at bottom

### ISSUE THREAD

**Issue by zahiduuzz** [inotia00/ReVanced_Extended#585]
### Application

YouTube

### Issue

It would be nice to have the search button at bottom

### Patch

Just like the create button and notification button swap, It would be easy to reach the search from the bottom.

### Motivation

Accessibility, Reachability

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by s23ultra512** [comment]
+1.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
