### ISSUE TITLE
feat(patch): hide fullscreen button

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#586]
### Application

YouTube

### Issue

.

### Patch

hides the fullscreen button in portrait type videos or square type videos

### Motivation

to watch videos without seeing the fullscreen button
![IMG_20230328](https://user-images.githubusercontent.com/36302515/228099852-f22e4ffa-dce0-41ee-ace9-173dbf5fcde3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.

**Comment by StradivariusKane** [comment]
@inotia00

Is it possible to hide it with custom filter?

**Comment by inotia00** [comment]
No
