### ISSUE TITLE
feat(patch): split `Hide movie shelf` settings

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#587]
### Application

YouTube

### Issue

make hide movies shelf patch to hide movies shelf only under video and search results

### Patch

.

### Motivation

so we can access Movies and TV section
![Screenshot_2023-03-28](https://user-images.githubusercontent.com/36302515/228100786-c8482907-72a1-4997-bf33-3efa7cc056ef.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, there is no valid block filter to identify whether a movie shelf is showing in the home feed, search results, or library..

**Comment by inotia00** [comment]
I will change it to an appropriate title and reopen

Next time you write an issue, please name the title appropriately.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
