### ISSUE TITLE
bug: Why am I seeing Clip and Remix buttons now?

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#588]
### Type

Error while patching

### Application

Version 18.11.36 non-root 

### Bug description

I just noticed that the two annoying Clip & Remix buttons are showing and the patches to remove them are removed from Rvx settings? What is going on? I don't want these two buttons that I never use taking up space...

![Screenshot_20230328-074822984 (1)](https://user-images.githubusercontent.com/73917917/228142126-c3a24d12-132a-4fe1-9398-95cd18534e75.png)

![Screenshot_20230328-075355617 (1)](https://user-images.githubusercontent.com/73917917/228142131-f93d28c6-4b3d-459a-a204-3324aae787f8.png)

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/574#issuecomment-1484114690

**Comment by anyujinie** [comment]
Got it. Hope this can be fixed so it's easier to notice and distinguish.

**Comment by anyujinie** [comment]
> https://github.com/inotia00/ReVanced_Extended/issues/574#issuecomment-1484114690

Inotia I noticed when enabling the hide action buttons patch this removes remix and clip button **but also removed the share button** 
Why? Can I not keep the share button and only remove the other two...

**Comment by inotia00** [comment]
`Hide action buttons` hides all buttons except for the following buttons:
- Like button
- Dislike button
- Download button
- Save to playlist

**Comment by anyujinie** [comment]
> `Hide action buttons` hides all buttons except for the following buttons:
> - Like button
> - Dislike button
> - Download button
> - Save to playlist

So there's currently no way of hiding the clip and remix buttons without it hiding the share button aswell? Seems very broken 😭

I want to keep the share button at all costs since I use it all the time. So this means I cannot use the 'hide action buttons ' because it removes the share button aswell.

Also none of these experimental patches are working 😭 I'm still seeing clips, remix, and even the thanks button. None of the patches are working 😭
![Screenshot_20230328-170514695 (1).png](https://user-images.githubusercontent.com/73917917/228282952-850dfe5b-27de-4ac5-8562-e78819f39880.png)

![Screenshot_20230328-170535148 (1).png](https://user-images.githubusercontent.com/73917917/228282953-245a1d46-302e-437a-a7c0-9bcb247274b6.png)

**Comment by inotia00** [comment]
yeah that's a feature I gave up on implementing

If you really need that feature, use the official ReVanced

**Comment by inotia00** [comment]
I've been refactoring the code for a whole month to accommodate people's comments that this is a bug.

Nevertheless, I couldn't completely fix the issue, so I just gave up on implementing it any further.

All source code and refactoring history is in the git repository, so if you can fix it, please fix it and make a PR.

I don't intend to touch this patch anymore. I'm so tired.

**Comment by anyujinie** [comment]
> I've been refactoring the code for a whole month to accommodate people's comments that this is too buggy.
> 

I have never experienced a single bug with this feature. Can you reinstate the previous working versions?

> so if you can fix it, please fix it and make a PR.
> 
As I mentioned earlier I have unfortunately no coding experience, otherwise I would surely try fix it 😭
