### ISSUE TITLE
Rebuld 3.90 not workbug: <title>

### ISSUE THREAD

**Issue by kazuma85** [inotia00/ReVanced_Extended#590]
### Type

Error at runtime

### Application

YouTube 18.11.36 the rebuld versión 3.90 not work and cant buld my revanced extended to 18.11.36 put 8 hr to convert and not make the apk 

### Bug description

Me try to Convert 18.11.36 original arm 7 youtube and the bulder not work 

### Steps to reproduce

![Screenshot_20230328-064817](https://user-images.githubusercontent.com/62585930/228251362-bbec5f80-97b3-4c7d-9498-482fbb210d55.png)

### Relevant log output

```shell
YouTube 18.11.36 the rebuld versión 3.90 not work
```

### Screenshots or videos

![Screenshot_20230328-064817](https://user-images.githubusercontent.com/62585930/228252529-321f9dbe-e6b7-4743-9103-e00a486436d0.png)

### Solution

Maybe the owner need to put more compability to the bulder to more updates of original youtube or update the bulder or patches

### Additional context

Bug bulder 3.90

### Device Environment

Shock Android 11 arm 7 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The termux methods also do not support the armebai-v7a architecture

Try patching through PC

**Comment by kazuma85** [comment]
> Los métodos termux tampoco soportan la arquitectura armebai-v7a
> 
> Pruebe a parchear a través de la PC

Sorry for the Drawback suddently the bulder works and convert the new versión 18.11.36 maybe the new pack of patches resolve the issue bug on my arm 7 Android 11 thanks for your answer and for all the great work you make to revanced extended 🙌 🍀
