### ISSUE TITLE
bug: Custom filter hides both "Your videos" and "Downloads" when entered only "Your videos"

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#591]
### Type

Other

### Application

YouTube v18.11.36
Revanced Patches v2.166.21

### Bug description

When you write only "Your videos" inside Custom filter, it hides both "Your videos" and "Downloads" sections.

### Steps to reproduce

1. Enable "hide account menu" option.
2. Add custom filter "Your videos".
3. Restart the app.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reproducible, but impossible to fix

Looking at the internal structure of the app, the two menus are dependent on each other.

Therefore, it is impossible to remove only one
