### ISSUE TITLE
feat(patch): hide history shelf in library menu

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#592]
### Application

YouTube

### Issue

can you please extend the functionality of 'hide ccount menu' patch by adding an option to hide history menu. history option is useless for those who have turned their history off.

### Patch

![photo_6132172147532084971_w](https://user-images.githubusercontent.com/87489540/228281607-431fa3d1-d756-4f7b-bb1e-f6feb2382cd9.jpg)

### Motivation

history option is useless for those who have turned their history off.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
