### ISSUE TITLE
feat(patch): split `Hide category bar in feed`

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#594]
### Application

YouTube

### Issue

![Screenshot_20230327_161232_YouTube](https://user-images.githubusercontent.com/127908708/228298858-6550286c-e52a-48d6-8176-73c99ecb4997.jpg)

### Patch

A toggle to turn that on or off.

### Motivation

To make YT more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
`Hide category bar in feed` will hide it too

It may differ by country and by account, but at least in the account I use, I can hide the category bar in the subscription feed by turning on `Hide category bar in the feed`

**Comment by Kuddus73** [comment]
> I can hide the category bar in the subscription feed by turning on `Hide category bar in the feed`

You are right.
However, I don't hide it in the home feed because it contains also the **Trends button**.

My suggestion would be to have two different options to toggle:
1. Hide category bar in home feed
2. Hide category bar in subscriptions feed

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
