### ISSUE TITLE
bug: 'Your videos' and 'Downloads' are not hiding

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#595]
### Type

Other

### Application

YT

### Bug description

'Your Videos' and 'Downloads' options are not hiding after adding them in the filter.

### Steps to reproduce

Just add with urself and see....Using latest YT

### Relevant log output

```shell
...
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
what version of patches did you use?

**Comment by inotia00** [comment]
just repatch with latest patches

**Comment by Vipin2003** [comment]
I have patched recommended with latest patches....after that I'm posting

**Comment by inotia00** [comment]
It's strange.. I confirmed that it was patched using the latest patches.

But for some reason it doesn't work
Anyway, this issue is valid, so I'll reopen it

**Comment by Vipin2003** [comment]
Recently, I got new layout there...check this
![Screenshot_20230329-101008](https://user-images.githubusercontent.com/93650504/228428645-6afac4ba-c5a9-4dde-9fe9-da14528b7f18.png)

In this layout, it is working. But in old layout, it is not.

And, pls remove the separator line too after hiding the "Your videos" and "downloads" buttons

**Comment by inotia00** [comment]
Please refer this issue https://github.com/inotia00/ReVanced_Extended/issues/591

I know these settings don't work with the old layout, so I plan to roll them back in the next release

**Comment by inotia00** [comment]
This feature has been removed from revanced-patches-v2.166.24
