### ISSUE TITLE
bug: YouTube Music version spoof breaks Library

### ISSUE THREAD

**Issue by 98xe** [inotia00/ReVanced_Extended#596]
### Type

Other

### Application

Tested on:

YouTube Music v5.48.53 + v5.49.54.
ReVanced Manager v0.0.57
Patches v2.166.21

### Bug description

While the new version spoof patch finally enables functionality for Canadian users on the latest versions of YT Music, it completely breaks the Library interface.

### Steps to reproduce

 Include the following patches in ReVanced Manager:

- Background Play
- Exclusive Audio Playback
- Hide Get Premium
- Hide Music Ads
- Hide Music Cast Button
- Hide Upgrade Button
- Minimized Playback Music
- Music MicroG Support
- Optimize Resource Music
- Spoof Version (Spoof the YouTube Music client version.)

Patch and Install.

Open app, enable spoof version setting within the app settings.

Refresh Library page.

Close and reopen app, head over to Library tab.

Library interface should be broken.

### Relevant log output

```shell
.
```

### Screenshots or videos

How it's suppose to look like

![Screenshot_20230328-143537_YouTube Music](https://user-images.githubusercontent.com/129218138/228341817-07942c28-55f6-49fc-9448-6991fef22790.jpg)

How it looks like after applying the spoof

![Screenshot_20230328-143612_YouTube Music](https://user-images.githubusercontent.com/129218138/228341838-d92d46c2-5338-48e4-8237-32c96a782d92.jpg)

### Additional context

Turning off the spoof version patch and restarting the app fixes the issue.

### Device Environment

S10+, Android 12.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Same as the old layout.
Since it's spoofing the app version on the server side, some layouts are loaded with outdated layouts. (cannot fix)
