### ISSUE TITLE
suggestion: supplement description of `hide-email-address` patch

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#597]
### Type

Other

### Application

YouTube v18.11.36
Revanced Patches v2.166.21

### Bug description

The "Hide email address" option now actually hides the account's handle, so I suggest to update the name of the option.

### Steps to reproduce

Go to ReVanced Extended settings

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
what do you mean 'account's handle'?

**Comment by Kuddus73** [comment]
The option **works completely fine**, you just have to change the name of the option from _hide email address_ to _hide handle_.

> what do you mean 'account's handle'?

Under the account's name, YT used to show the account's email, but now it shows the handle instead.
The handle is basically the nickname of the account, it begins with **@** for everyone.
![iMarkup_20230329_005051](https://user-images.githubusercontent.com/127908708/228391814-e14420c9-d6ac-47ea-a542-ca28ec70e462.jpg)

**Comment by inotia00** [comment]
oh, i understand

I just found out now that it's called account's handle

Anyway, this is not a bug

The account handle is not treated as an email address even in the code inside the app.
(This is another identifier)

So it is normal that it is not hidden

hide-account-handle patch not implemented yet

**Comment by Kuddus73** [comment]
> still exposes your email address to some people

Oh I didn't know that it was still showing to some people.

In that case you could change it to "Hide email address/**handle**", or something like that.
I'm asking this cuz it took me a while to figure out what `Hide email address` was hiding cuz to me it was showing the handle instead of the email, so rightfully it was hiding the handle.

I know it is a minor thing but it would be easier to understand.

**Comment by inotia00** [comment]
umm okay I'll change the title of this issue appropriately and reopen it

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.1)
