### ISSUE TITLE
qustion: Is there a new section? (recommended videos)

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#598]
### Application

YouTube

### Description

Today I use revancify and patches v2.166.21.
Now a new section has appeared on the home screen.
Recommended
I don't think it's Google ad. 
Maybe another A/B test?

![IMG_20230328_214123](https://user-images.githubusercontent.com/125223735/228370497-21296db2-365a-4890-9bdf-d42fa0355baa.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
If you have time, try patching with YouTube v18.06.41

If it doesn't reproduce in this version, it will most likely be a new layout

**Comment by jhon1282** [comment]
I tried on Revanced Classic 18.05.40.
The same thing has been reproduced.
So it must be server side I think, perhaps it depends on the region, i'm in Italy

![Screenshot_2023-03-28-23-56-37-289_app revanced android youtubf](https://user-images.githubusercontent.com/125223735/228392127-63bbc1bc-48ad-4846-bb8e-cab7e288d6ad.jpg)

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
