### ISSUE TITLE
feat(YouTube Music): add `Enable previous song` patch

### ISSUE THREAD

**Issue by KarmaBeast** [inotia00/ReVanced_Extended#60]
### Application

YouTube Music

### Issue

I saw this idea in the Revanced subreddit and want to share it here. Please consider adding this button to Rvx Music.

Original post with many upvotes: [Reddit](https://www.reddit.com/r/revancedapp/comments/zw23al/add_button_to_previous_song_here/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)

### Patch

List view:
![RDT_20221227_2239047670112041966400262](https://user-images.githubusercontent.com/73917917/209724850-d9e2a3fd-107a-439c-88d8-e8e85ef40fb9.jpg)

Mini-Player:
![Screenshot_20230416-192455799 (1).png](https://user-images.githubusercontent.com/73917917/232329907-00639a17-90f3-42a4-b130-91b0cee5172a.png)

### Motivation

Go back to previous song when in Mini-Player and List view.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
@inotia00 I wrote this patch request long time ago. Is it please possible to implement? I'd gladly donate money too for the time you invest  in it :)

**Comment by inotia00** [comment]
nop

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.7.1)
