### ISSUE TITLE
Buffering issue bug

### ISSUE THREAD

**Issue by L3y0nha5** [inotia00/ReVanced_Extended#600]
### Type

Error at runtime

### Application

Youtube revanced premium last 6 updates

### Bug description

Although i installed lateset version of micro g
Uninstall and re install again
Cleared catch
I did every thing but still buffering.
The funny thing when i use my second account its working so fine although iam using the same mobile

### Steps to reproduce

Although i installed lateset version of micro g
Uninstall and re install again
Cleared catch
I did every thing but still buffering.
The funny thing when i use my second account its working so fine although iam using the same mobile

### Relevant log output

```shell
I am not that expert to fo this.
Iam here to report a bug
```

### Solution

Although i installed lateset version of micro g
Uninstall and re install again
Cleared catch
I did every thing but still buffering.
The funny thing when i use my second account its working so fine although iam using the same mobile

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
turn on `Enable protobuf spoof`

**Comment by L3y0nha5** [comment]
Thanks bro, i will test it for couple of days and feed back.

So far it's working well 👍🏻🌹🌹🌹🌹

**Comment by L3y0nha5** [comment]
You're the best my friend, thanks so so much👍🏻👍🏻👍🏻

**Comment by inotia00** [comment]
yeah I'm glad the issue was resolved
