### ISSUE TITLE
bug: Play Store apps update notification crashes YT

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#601]
### Type

Other

### Application

YouTube v18.11.36
Revanced Patches v2.166.21

### Bug description

Whenever Google Play Store sends a notification of app updates, it closes YT and goes to phone's home.
![Screenshot_20230329_022757_Nova7](https://user-images.githubusercontent.com/127908708/228405478-87abb750-cfde-4778-8efb-8cb34d61f3ad.jpg)

### Steps to reproduce

The only way I know of is to not update any apps and wait for Play Store to send the notification to update them.

Play Store sends apps update notification at random times, so I don't know if there are specific steps to manually reproduce the issue.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Do a clean install according to the [documentations](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android)#common)
