### ISSUE TITLE
feat(patch): Hide YouTube settings menu

### ISSUE THREAD

**Issue by 0Walker0** [inotia00/ReVanced_Extended#603]
### Application

YouTube

### Issue

Unnecessary menus in YouTube actual settings.

Some examples: Try new features, Billing and payments, Purchases and memberships, etc.

### Patch

Add a custom filter field like the ones for ads or the account menus but for the YouTube settings menu.
![Screenshot_20230329_041841_ReVanced Extended](https://user-images.githubusercontent.com/86571480/228480432-8c4edca2-ba1e-46e5-a54e-d925d7a74bdc.jpg)

### Motivation

More customization and freedom of choice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
