### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by AVVVVB** [inotia00/ReVanced_Extended#605]
### Application

YouTube

### Issue

Speed function working in live streaming

### Patch

i want speed function didn t working in live streaming

### Motivation

후야!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
bruh
