### ISSUE TITLE
bug: `Hide channelbar join button` doesn't work with old layout

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#606]
### Type

Other

### Application

YouTube v18.11.36
Revanced Patches v2.166.24

### Bug description

`Hide channelbar join button` option doesn't hide the join button when the old layout is enabled.

![iMarkup_20230329_154052](https://user-images.githubusercontent.com/127908708/228575748-fc5639f6-c160-4624-bd13-4857548338a3.jpg)

### Steps to reproduce

1. Enable `Hide channelbar join button`.
2. Enable old layout.
3. Restart the app.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Kuddus73** [comment]
> Since the old layout is forcibly overriding a layout that has been deprecated by Google, some patches may break.
> 
> That's why I defined the old layout as an `Experimental Flags`, and I don't provide any help for issues that arise when using flags classified as experimental flags.

Oh, right. That's fair and makes sense.

I thought I should report this cuz you removed a recent feature that wasn't working with the old layout (https://github.com/inotia00/ReVanced_Extended/issues/595#issuecomment-1487942267), that's why I thought you might provide a fix.

**Comment by inotia00** [comment]
The reason for rolling [it](https://github.com/inotia00/ReVanced_Extended/issues/595#issuecomment-1487942267) back wasn't simply because the patch was broken in the old layout
patch was broken in a lot of situations, including the tablet UI and A/B test layout
