### ISSUE TITLE
feat(patch): Remove Minus time/Remaining time

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#607]
### Application

YouTube

### Issue

I sometimes accidentally tap this
![Screenshot_20230329-021927812 (1)](https://user-images.githubusercontent.com/73917917/228600977-17326f13-b35b-48c0-b15a-70308d850eda.png)
and force it to show remaining time, which I don't want. Please remove this as I prefer the default time display, and never use the remaining time.

**Comment by manishloshali** [comment]
just click it again

**Comment by anil-al** [comment]
And I use it all the time, so?..

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
