### ISSUE TITLE
feat(patch): Hide subscribed channels section in subscriptions feed

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#608]
### Application

YouTube

### Issue

**Add an option to hide the subscribed channels section at the top:**
![20230328_173530](https://user-images.githubusercontent.com/127908708/228612563-5d8472c9-b6c6-4683-a2b1-3aeb1d02d5de.jpg)

### Patch

A toggle to turn it on or off.

### Motivation

To make YT more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.1)
