### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by Avalach2004** [inotia00/ReVanced_Extended#609]
### Application

YouTube

### Issue

Please add a dark and black theme together

### Patch

![362514411](https://user-images.githubusercontent.com/129339201/228684576-622a07b5-963a-4b36-9f9e-628fb39ffcc5.jpg)

### Motivation

You no longer have to release 2 types of modifications, with different designs
p.s Google translation

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The ability to specify the theme you want is already implemented through options.toml
