### ISSUE TITLE
request: cast button can not be activated

### ISSUE THREAD

**Issue by Maggus2k** [inotia00/ReVanced_Extended#610]
### Type

Cosmetic

### Application

YT ReVanced (Extended) 18.12.34

### Bug description

cast button cannot be re enabled. In general version, there is an option for this.

### Steps to reproduce

No settings there

### Relevant log output

```shell
not needed.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
non recommand version no support

**Comment by Maggus2k** [comment]
OK, but there is no recommand version on https://revanced.io/
Download button linked to this apk
