### ISSUE TITLE
bug: Playback buffering issue is back

### ISSUE THREAD

**Issue by Menelwenn** [inotia00/ReVanced_Extended#611]
### Type

Other

### Application

Youtube 18.10.36
Youtube 18.11.36

### Bug description

The previous buffering issue is back.

I tried updating my RVE app from 18.10.36 to 18.11.36 and the issue started from there. No, I didn't had the bug before updating, I updated for convenience.

I double checked if indeed the Client Spoofing v.0.0.1 was checked and installed and saw no errors in the logs.

I am using the Revanced Manager method.

### Steps to reproduce

Step 1. Patch YouTube with Revanced Extended Patches
Step 2. Include Client Spoofing v0.0.1 and proceed the installation successfully
Step 3. Play any video and it will buffer automatically and indefinitely about 40 seconds in

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Applied custom-branding-icon-revancify
Applied default-video-quality
Applied enable-external-browser
Applied enable-minimized-playback
Applied enable-old-quality-layout
Applied enable-tablet-miniplayer
Applied enable-wide-searchbar
Applied hide-channel-watermark
Applied hide-create-button
Applied hide-flyout-panel
Applied hide-general-ads
Applied hide-mix-playlists
Applied hide-pip-notification
Applied hide-shorts-button
Applied hide-startup-shorts-player
Applied hide-video-ads
Applied layout-switch
Applied materialyou
Applied microg-support
Applied overlay-buttons
Applied patch-options
Applied return-youtube-dislike
Applied settings
Applied sponsorblock
Applied theme
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Screenshots or videos

![Screenshot_2023-03-30-10-50-41-90_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/50523111/228798029-e4f43603-0e8d-4381-9318-30e6ea4e67cf.jpg)

### Additional context

I tried multiple different videos and all were affected, the Timestamps feels random, with buffering that starts at 0.40, 0:46, 0:50, 1:19 (intro sponsorblock skip) and a final one at 1:21.

I tried Downgrading my RVE app, by Downgrading the OG YouTube App, uninstalling RVE, updating the OG YouTube ver at 18.10.36, patching RVE with YT ver 18.10.36 and had the issue still even though it was the version I've been using since the first Buffering Fix release. I tried updating that new app to 18.11.36 and still has buffer issues.

To be clear, I was using ver 18.10.36 since the first Playback Buffering issue was fixed and it worked nice and no issues (expect some very low quality short videos that was frozen), I tried updating to 18.11.36 (current recommend version) to fix it and have other conveniences but it made the buffering issue real back again.

### Device Environment

Oxygen OS 13.0 (Android 13) - KB2003_11_F62

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Did you turn on Enable protobuf spoof?

**Comment by inotia00** [comment]
If you turn `Enable protobuf spoof` to on, what type of spoof was it?

Did you spoof to general video? Or did you spoof to shorts video?

**Comment by inotia00** [comment]
try to spoof to shorts

**Comment by Menelwenn** [comment]
Switched the setting to spoofing to Shorts,
The 60s Short played again without issues and buffering.
The general video actually works now..? 2:00 in and no buffering.

Did the setting ghosted somehow?

**Comment by Menelwenn** [comment]
I did all these tests in the latest recommended ver (so 18.11.36), I cannot update further.

Before updating to .11, when using .10, I did not require Protobuf in my patch at all somehow? But I did had no Thumbmails on the seekbar like it was patched in (was it included to Client Spoof?)

Anyways, I have no issues now (expect the seekbar thumbmails but thats to be expected with Protobuf), maybe it was a rare issue somehow that made my setting to not apply but still on, Im sure I rebooted my app tho.. I have no idea about what happened..
