### ISSUE TITLE
bug: failed to install Youtube Music

### ISSUE THREAD

**Issue by abganteng** [inotia00/ReVanced_Extended#612]
### Type

Other

### Application

 Youtube Music v5.50.52

### Bug description

i cant install youtube music, i use latest patches revanced-patches-2.166.24  and  revanced-integrations-0.100.24, before that works fine 

### Steps to reproduce

none

### Relevant log output

```shell
none
```

### Screenshots or videos

![Screenshot_2023-03-30-17-44-58-266_com miui packageinstaller](https://user-images.githubusercontent.com/72485140/228813731-ff4bcc92-f435-4f42-963a-7cb065653f1b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It seems to be an issue that does not match the signature of the previously installed version.

Uninstall the installed YouTube Music and try again

**Comment by abganteng** [comment]
> It seems to be an issue that does not match the signature of the previously installed version.
> 
> Uninstall the installed YouTube Music and try again

i dont have any youtube music installed, i repatch to the latest patch because i clean install my phone, is it something to do with my template ? im using this patch template 

`java -jar revanced-cli-2.21.0-all.jar -a music_5.50.52.apk -o com.google.android.apps.youtube.music.apk -b revanced-patches-2.166.24.jar -m revanced-integrations-0.100.24.apk -e client-spoof-music -e custom-branding-music-afn-red -e music-settings -e translations-music --experimental`

**Comment by inotia00** [comment]
Why did you use the original YT Music package name even though you included the microg patch?

Original YT Music's package name could not pass the package manager's signature verification

Change to another package name and try again.
