### ISSUE TITLE
bug: Hide breaking news shelf toggle also hides history

### ISSUE THREAD

**Issue by Faszom11** [inotia00/ReVanced_Extended#613]
### Type

Error at runtime

### Application

Youtube version 18.08.39, latest patches and integrations
.json file:
[Settings.json.zip](https://github.com/inotia00/ReVanced_Extended/files/11110796/Settings.json.zip)

### Bug description

If you toggle on hide breaking news shelf, it also hides watch history

### Steps to reproduce

Go to settings > revanced extended > general layout and toggle on "hide breaking news shelf"

### Relevant log output

```shell
No logs
```

### Screenshots or videos

https://user-images.githubusercontent.com/127752289/228818901-768751e7-1c02-444c-b099-3eb68afa1473.mp4

### Additional context

Selected patches:

Variant: nonRoot
Arch: arm64-v8a
App: YouTube-18-08-39.apk
CLI: inotia00-cli-v2.21.0.jar
Patches: inotia00-patches-v2.166.24.jar
Integrations: inotia00-integrations-v0.100.24.apk
Patches argument: -i custom-branding-icon-afn-red
-i custom-branding-name
-i custom-seekbar-color
-i custom-video-speed
-i default-video-quality
-i enable-external-browser
-i enable-minimized-playback
-i enable-old-layout
-i enable-old-quality-layout
-i enable-seekbar-tapping
-i force-premium-heading
-i hide-account-menu
-i hide-auto-captions
-i hide-auto-player-popup-panels
-i hide-category-bar
-i hide-channel-watermark
-i hide-email-address
-i hide-endscreen-cards
-i hide-general-ads
-i hide-info-cards
-i hide-mix-playlists
-i hide-player-button-background
-i hide-video-ads
-i microg-support
-i optimize-resource
-i overlay-buttons
-i patch-options
-i return-youtube-dislike
-i settings
-i sponsorblock
-i swipe-controls
-i theme

### Device Environment

Android 13, OneUi 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Fixed in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
