### ISSUE TITLE
feat(patch): add player controller buttons(gesture) in shorts

### ISSUE THREAD

**Issue by sliceanddice9** [inotia00/ReVanced_Extended#614]
### Application

YouTube

### Issue

There is currently no way to rewind or fast forward shorts using the shorts player. Double tap input seek buttons would solve this. 

### Patch

Double tapping the screen to the left to rewind by 5 seconds, and double tapping the screen to the right to fast forward by 5 seconds. 

### Motivation

So that people can go back or go forward with ease when watching a shorts video using the shorts player itself. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
Good suggestion. Would like to see this as well and a progress bar.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
