### ISSUE TITLE
feat(patch): rvx music spoof in korea

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#615]
### Application

YouTube

### Issue

in my country seoul Korea, we can use rvx music only by vpn. so it offers low speed by using vpn. In recent rvx music patchlog i guess you enabled spoofing for Canada. Likewise can you add this spoofing for korea plz??

### Patch

![Screenshot_20230331_000239_YouTube Music](https://user-images.githubusercontent.com/113352087/228879577-07eae25e-a063-413d-9c72-eeb149e6f2d7.jpg)

### Motivation

it will be more nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by hoang-himself** [comment]
There was indeed a `spoof-version` patch to fix a problem where [radio mode is always enforced](https://www.reddit.com/r/Vanced/comments/qve609). It has nothing to do with the availability of free YT Music in selected regions.

@inotia00 this is out of scope
