### ISSUE TITLE
feat(patch): Show time remaining with reference to playback speed

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#616]
### Application

YouTube

### Issue

Remaining time shown taking playback speed into consideration.
for ex. if video length is 5:00 and playback speed is 2x so remaining time should show 2:50.

inspired from [this](https://chrome.google.com/webstore/detail/improve-youtube%F0%9F%8E%A7for-yout/bnomihfieiccainjcjblhegjgglakjdd) chrome extension
https://github.com/code-charity/youtube

### Patch

![Screenshot 20 58 (Thursday 30 03) msedge 316](https://user-images.githubusercontent.com/125728453/228889493-22b4dbbc-a27b-473c-86a3-f10b3a6749ce.png)
![Screenshot 21 22 (Monday 27 03) msedge 313](https://user-images.githubusercontent.com/125728453/228889656-95d94080-a1d9-493f-9e5d-bfef68701ee5.png)
![Screenshot 21 23 (Monday 27 03) msedge 315](https://user-images.githubusercontent.com/125728453/228889682-cd1145c8-345f-45f0-9179-c7f27ac06209.png)
![Screenshot 21 22 (Monday 27 03) msedge 314](https://user-images.githubusercontent.com/125728453/228889692-08906783-b614-4b83-9822-35face6265b3.png)

### Motivation

would be very useful

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
Just click it again.

**Comment by manishloshali** [comment]
> Just click it again.

What

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
