### ISSUE TITLE
feat(patch): remove mic from search 

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#617]
### Application

YouTube

### Issue

Patch to remove mic button next to search bar and in search results.

### Patch

![IMG_20230330_214837](https://user-images.githubusercontent.com/125728453/229144468-4e7b5193-5018-4f86-8125-77912048c217.jpg)
![IMG_20230330_214901](https://user-images.githubusercontent.com/125728453/229144678-703fef88-7eb5-48a8-827c-e562d4473694.jpg)

### Motivation

Would look cleaner for people who don't use voice search.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
