### ISSUE TITLE
feat(patch): Allow `Hide account menu` to hide Account section

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#618]
### Application

YouTube

### Issue

Allow `Hide account menu` option to hide the highlighted section:
![20230328_221916](https://user-images.githubusercontent.com/127908708/229147827-ec3be61e-5c78-4268-8a3e-3b0410cd807c.jpg)

### Patch

Allow us to hide the section via `Custom filter` by entering its name.

### Motivation

To make YT more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
