### ISSUE TITLE
Use old video quality player menu does not show auto quality

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#619]
### Type

Cosmetic

### Application

Youtube 18.11.36 

### Bug description

Use old video quality player menu does not show auto quality

### Steps to reproduce

![IMG_20230331_221242](https://user-images.githubusercontent.com/125223735/229225369-0bbd4b3f-650e-49c6-abbe-753f690583a6.jpg)

![IMG_20230331_221430](https://user-images.githubusercontent.com/125223735/229225410-7b84a634-5698-4af0-a155-12eea4c0d16a.jpg)

### Relevant log output

```shell
N
```

### Device Environment

Android 11 miui 12.5 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
There are no plans to fix this issue

**Comment by jhon1282** [comment]
With patch 2.168.33 this problem disappeared, you can put it in the fixed issues i think. Many thanks
