### ISSUE TITLE
feat(patch): Hide Shop button

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#620]
### Application

YouTube

### Issue

**Add an option to hide the Shop button from the bottom of the player.**
![20230401_003836](https://user-images.githubusercontent.com/127908708/229250714-d5ef6713-1397-495a-9647-3ade8690953b.jpg)

### Patch

A toggle to show it or hide it.

### Motivation

To make YT more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.1)
