### ISSUE TITLE
feat(patch): Revert new YouTube layout

### ISSUE THREAD

**Issue by 98xe** [inotia00/ReVanced_Extended#621]
### Application

YouTube

### Issue

It seems like YouTube is testing new UI on some accounts.

It's pretty awful.

Not only did the comments section become more concealed, but the subscribe button has completely disappeared, as well. You have to manually go to a channel's page in order to subscribe, or to see if you're already subscribed.

For me, this layout only appears only on relatively new (brand) accounts created within the last few months. This layout appears on the stock YouTube app, too. 

### Patch

It would be great if there could be a patch to force the original layout for accounts that are affected by the change.

Here's how the new layout looks like:

![Screenshot_20230331-233401_YouTube](https://user-images.githubusercontent.com/129218138/229264201-504344e2-ab7b-4856-9d12-080ad2cc579e.jpg)

Here's how it was before:

![Screenshot_20230331-233432_YouTube](https://user-images.githubusercontent.com/129218138/229264225-f6b60d52-4bcd-4c8a-b845-70d7a6799f12.jpg)

### Motivation

The original layout is much more practical and functional.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
