### ISSUE TITLE
bug: Hide movies shelf toggle also hides album cards from search results

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#622]
### Type

Error at runtime

### Application

v18.06.41
revanced-patches v2.166.24

### Bug description

.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.1)
