### ISSUE TITLE
question: <title>: 

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#623]
### Application

YouTube

### Description

YouTube version 18.12.35 came out Don't you update it?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Don't ask about ETA

**Comment by sssh7710** [comment]
> ETA에 대해 묻지 마세요

What does that mean?
