### ISSUE TITLE
feat(patch): 擋直播的廣告

### ISSUE THREAD

**Issue by 4197amt** [inotia00/ReVanced_Extended#624]
### Application

YouTube

### Issue

會跳出連兩則無法跳過的廣告

### Patch

擋直播的廣告

### Motivation

觀看線上直播比較不會被打擾，能造福大家

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 4197amt** [comment]
![Uploading Screenshot_2023-04-02-15-19-43-46_d11ae654701a5fadb313ea6fa9a6836f.jpg…]()

**Comment by inotia00** [comment]
1. Please edit the content in English
2. Screenshot not uploaded
3. Please list the YouTube version you tried to patch and the revanced-patches version

**Comment by inotia00** [comment]
Please reopen the issue by meeting the conditions above
