### ISSUE TITLE
bug: "old style quality layout" isn't working 

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#627]
### Type

Error at runtime

### Application

YouTube 18.12.35

### Bug description

.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

https://user-images.githubusercontent.com/64865031/229351544-bfd672b2-2845-471d-a4b0-3070207016e3.mp4

### Device Environment

Android 13 , MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Test if the issue persists when you exclude the `hide-button-container` patch, and let me know the results

**Comment by sleepingiv** [comment]
Yes , the issue persists

**Comment by inotia00** [comment]
Could you try patching with revanced-patches-v2.168.3 and let me know the results?

**Comment by sleepingiv** [comment]
There is a thing that I noticed , the old style works until the whole ui is loaded . Refer to the attached video for better understanding.https://user-images.githubusercontent.com/64865031/229568677-18c71f7d-15c0-4f6a-ad3b-b49342bea66b.mp4

**Comment by sleepingiv** [comment]
Hey inotia, please fix this soon if possible.

**Comment by inotia00** [comment]
At least for me this issue has never occurred.

I can't fix issues that don't reproduce on my device.

**Comment by sleepingiv** [comment]
Should I close this as completed and open a new issue with proper explanation, screen recording and patchlog ?

**Comment by sleepingiv** [comment]
Hey inotia , I am providing options.toml , patchlog , settings.json . See if you can reproduce the issue.

Options.toml - https://drive.google.com/file/d/18O4Cz29DY8L9ydVBje1q_nUiyXtDyU55/view?usp=drivesdk

Patchlog.txt - https://drive.google.com/file/d/18NeMYDWTvvvxBI1oI0jZXXs_QUD8Rr5I/view?usp=drivesdk

Settings.json - https://drive.google.com/file/d/18IF6sYtpG2IiKKr8vWF-p9cADlpFtqQF/view?usp=drivesdk

**Comment by inotia00** [comment]
Fixed in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
