### ISSUE TITLE
feat(patch): hide chapters section from video description panels

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#628]
### Application

YouTube

### Issue

Patch Request to hide these stuffs from Video's Discription box :-

![Screenshot_20230402-195019~2](https://user-images.githubusercontent.com/93650504/229359064-ec140b44-623a-4711-83f6-cd5534b9bd4c.png)

2. Hide **Subscription** button from Navigation Bar as like **Shorts** button.

### Patch

Already explained in Issue.

### Motivation

Enhance YT Experience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)

**Comment by Vipin2003** [comment]
Welcome Back... @inotia00
