### ISSUE TITLE
feat(patch): Hide short Search, Camera and 3 Dots buttons

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#629]
### Application

YouTube

### Issue

**Three individual options to hide the Search, Camera and 3 Dots buttons when watching shorts.**

![20230329_064349](https://user-images.githubusercontent.com/127908708/229359285-481bfbad-8dfd-4d10-8900-bcdd110f2852.jpg)

### Patch

Three different toggles to show or hide.

### Motivation

To make YT more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/151
