### ISSUE TITLE
Revanced-patches changelog issue

### ISSUE THREAD

**Issue by User-noob2036876** [inotia00/ReVanced_Extended#63]
In revanced-patches 2.147.2 as in the picture below There were no notification settings in the subscriptions section. Please add it to 2.147.3 changelog.
![Screenshot_20221228-090437_ReVanced Extended](https://user-images.githubusercontent.com/117031829/209766518-80b2d361-a6e0-47b6-9451-fc69834bde57.jpg)

**Comment by inotia00** [comment]
Please write a new issue according to the specified form

![209766800-0503a5b1-4b24-4d48-a310-f91ff5dede1f](https://user-images.githubusercontent.com/108592928/209775524-9f6db681-9b33-4ca8-b781-9577c7731531.png)

Also, please attach patches information Screenshot
