### ISSUE TITLE
bug(YouTube/Hide handle): handle is not hidden in new layout

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#630]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.36.39

### Bug description

The email address/handle does not hide even after turning 'Hide email address (handle)' ON.

### Steps to reproduce

Turn on 'Hide email address (handle)' option.

### Relevant log output

```shell
N.A.
```

### Screenshots or videos

https://user-images.githubusercontent.com/125809686/229370317-6ea3c0fd-d03b-464a-8e22-a0a7d589d58e.mp4

### Solution

**Patch to YouTube v18.30.37 or v18.33.40, which does not apply A/B tests**

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
![em](https://user-images.githubusercontent.com/108592928/229387620-d5d014d2-92e1-4346-97c1-7f41874729d4.png)
The patch removes email from my account settings
Emails elsewhere are not hidden

**Comment by madhurvarshney** [comment]
But my handle is still shown in the account settings. See the video I attached at the timestamp 0:06. I could not find any difference between when 'Hide email address (handle)' option is ON/OFF.

**Comment by inotia00** [comment]
ahh.. this is the part related to A/B testing

Anyway, it's valid, so I'll reopen

**Comment by madhurvarshney** [comment]
Another thing with the new layout I wanted to bring to your notice is that now there is no 'Time watched' option in the new layout, as it used to be earlier.
In the new layout, there is an icon that is exactly same as the one for 'Time watched' but it shows analytics of the channel instead.
See the images below:

1. Account with NEW LAYOUT
![IMG_20230403_173110](https://user-images.githubusercontent.com/125809686/229505508-d701eb0e-1048-418d-b73c-a7b82be382ef.jpg)

2. Account with OLD LAYOUT
![IMG_20230403_172915](https://user-images.githubusercontent.com/125809686/229505588-18ae9619-bb75-4ec0-b89a-6b136463cb33.jpg)

**Comment by inotia00** [comment]
It seems that these A/B tests are not applied within the currently supported version (YouTube v18.19.36 ~ v18.31.40)

After testing on 12 different Google accounts, this new layout does not load on YouTube v18.19.36 - v18.31.40

There will be no more version bumps, so this issue is no longer valid

Close the issue

**Comment by inotia00** [comment]
These A/B tests were recently re-added, so I'm reopening the issue

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.18)
