### ISSUE TITLE
feat(patch): YouTube Vanced style shorts with the refresh type 

### ISSUE THREAD

**Issue by TheTrueShadow** [inotia00/ReVanced_Extended#632]
### Application

YouTube

### Issue

This patch should make it so it is similar to YouTube Vanced when you leave the shorts tab on vanced it refreshes the shorts tab and on ReVanced it does not automatically do that you have to scroll up all they way to the first video

### Patch

Either when YouTube is refreshed or shorts tab is closed have the shorts tab refresh and have new videos popup 

### Motivation

The reason I think its valuable to the community is because some people like to watch shorts and when they leave the shorts tab and go back they do not have fresh shorts instead they have the same ones this would stop people from having to close and reopen the app all the time to refresh shorts or scroll all the way to the top to refresh which works sometimes 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It's not the style of YouTube Vanced, it's the style of old YouTube

It is possible to apply what you want by specifying the old layout version via options.toml
