### ISSUE TITLE
feat(protobuf-spoof): support spoofing in feeds too

### ISSUE THREAD

**Issue by WanderBoi** [inotia00/ReVanced_Extended#633]
### Type

Error at runtime

### Application

18.13.33

### Bug description

Pretty explanatory, videos load for exactly 40 seconds in autoplay then it turns black and endlessly buffer. I tried several methods, protobuf, codec, protocol, each individually, together, paired.

### Steps to reproduce

autoplay videos in feed

### Relevant log output

```shell
sorry not sure how to do this in the extended app
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/29160030/229357522-231bc782-9a3a-4432-a72f-2d1e5e2b24e9.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by WanderBoi** [comment]
I have now tried several other versions reaching the same conclusion.

**Comment by inotia00** [comment]
In the feed, there is an issue where sound is always output when protobuf spoof is applied

That's why protobuf spoof doesn't apply in feeds.

**Comment by WanderBoi** [comment]
any way of having that functionality instead? I'd rather have audio in feed than no autoplay.

**Comment by inotia00** [comment]
If so, I will change the label of this patch to patch-request
