### ISSUE TITLE
bug: Protobuf spoof makes auto-generated subtitles appear weirdly

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#634]
### Type

Other

### Application

YouTube v18.12.35
Revanced Patches v2.168.1

### Bug description

**With protobuf spoof disabled:**
![Screenshot_20230403_032403_YouTube](https://user-images.githubusercontent.com/127908708/229398140-e94e6a9c-586a-436c-80a7-38f1fa5ed0ee.jpg)

**With protobuf spoof enabled:**
![Screenshot_20230403_032113_YouTube](https://user-images.githubusercontent.com/127908708/229398031-993d5871-86e2-4cb6-8c85-9d357dad9157.jpg)

### Steps to reproduce

1. Enable protobuf spoof
2. Restart app
3. Play a video with auto-generated subtitles

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
Yes

**Comment by inotia00** [comment]
It will be fixed in the next release
