### ISSUE TITLE
bug(protobuf-spoof): subtitles are still on top in some videos

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#636]
### Type

Other

### Application

YouTube v18.12.35
Revanced Patches v2.168.6

### Bug description

**The latest update fixed the auto-generated subtitles, but it also put at top the normal subtitles.**

![Screenshot_20230403_153522_YouTube](https://user-images.githubusercontent.com/127908708/229543151-222c12d4-2cc1-4511-988e-2787199f3297.jpg)

### Steps to reproduce

1. Enable protobuf spoof
2. Restart app
3. Play a video with subtitles

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The commit fixing this issue has been merged into the repo
just wait for the next release

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.12)
