### ISSUE TITLE
question: `certificate-spoof` patch for YT Music

### ISSUE THREAD

**Issue by hoang-himself** [inotia00/ReVanced_Extended#637]
### Application

YouTube Music

### Description

If I include `certificate-spoof` patch for YT Music and install it on non Android Auto devices, will the app have any unexpected behavior? If the patch includes a device type check, please ref the lines of code as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The `certificate-spoof` patch bypasses signature verification when connecting to Android Auto.

Even if you do not use Android Auto, there is no problem even if you include it.
(As you may be aware, the MicroG patch also includes a patch to bypass Google Play Services' signature verification)

**Comment by inotia00** [comment]
Yep You can't run your app in a MicroG environment without bypassing Google Play Services signature verification

So, to use it in MicroG environment, you must include it.

However, even if Android Auto's signature verification bypass is not included, it is still possible to run the app in the MicroG environment.

However, you must include it to use Android Auto.
