### ISSUE TITLE
bug: `Hide shorts player join button` doesn't always hide the button

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#639]
### Type

Other

### Application

YouTube v18.12.35
Revanced Patches v2.168.6

### Bug description

https://user-images.githubusercontent.com/127908708/229675443-8318ee4f-180c-490c-a11d-3da932d6e734.mp4

### Steps to reproduce

1. Enable `Hide shorts player join button`
2. Play a video
3. Play a short **without closing the video**

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
Yes, it's reproducible.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.12)
