### ISSUE TITLE
bug(protobuf-spoof): end screen cards are still hidden

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#640]
### Type

Other

### Application

YouTube v18.12.35
ReVanced Patches v2.168.12

### Bug description

With protobuf spoof enabled, the end screen cards are not shown at all.

### Steps to reproduce

1. Enable protobuf spoof
2. Restart app
3. Play a video with end screen cards

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is the only side effect of the `protobuf-spoof` patch
(most side issues were fixed by many contributions)

I think this issue will be hard to fix for a long time

**Comment by jhon1282** [comment]
I don't have this problem
![Screenshot_2023-04-04-15-45-05-447_app rvx android youtubf](https://user-images.githubusercontent.com/125223735/229813058-0bae4040-7e63-4479-80c7-3130524dec81.jpg)
If that's what you say

**Comment by Kuddus73** [comment]
> I think this issue will be hard to fix for a long time

So in the meantime, can you disable the automatic spoofing protobuf?

For me videos still work if I use a VPN and I find the end screen cards pretty useful, but `protobuf-spoof` keeps enabling itself even if I manually disabled the option several times.

**Comment by inotia00** [comment]
There is no way to turn off automatic protobuf spoofing
just exclude `protobuf-spoof` patch when proceeding patch

**Comment by Kuddus73** [comment]
> There is no way to turn off automatic protobuf spoofing just exclude `protobuf-spoof` patch when proceeding patch

I probably explained myself badly with _the automatic spoofing protobuf thing_.

Once you disable any option, it shouldn't be able to enable itself, but since version 2.168.1 strangely the `Enable protobuf spoof` option keeps suddenly and automatically enabling itself.

But if there actually isn't a fix, I will exclude `protobuf-spoof` as you suggested.

**Comment by inotia00** [comment]
> > I think this issue will be hard to fix for a long time
> 
> So in the meantime, can you disable the automatic spoofing protobuf?
> 
> For me videos still work if I use a VPN and I find the end screen cards pretty useful, but `protobuf-spoof` keeps enabling itself even if I manually disabled the option several times.

In the next release, I'll change to activating it only once
(Even if you include the 'protobuf-spoof' patch, the switch won't be activated automatically several time)

**Comment by inotia00** [comment]
since it is no longer spoofing with shorts player parameters in latest patches, closing the issue
