### ISSUE TITLE
feat(patch): Disable live button on channel icons

### ISSUE THREAD

**Issue by A-of-Wonder** [inotia00/ReVanced_Extended#641]
### Application

YouTube

### Issue

On the Home tab mainly, tapping the icon of a channel that is live-streaming will take you directly to that live-streaming screen, not to the channel page. This is very useless and tedious.

### Patch

![sketch-1680615807772](https://user-images.githubusercontent.com/128334768/229812145-a9fc4866-986b-42b8-b9c8-10a4ef173483.png)

### Motivation

If this could be disabled, it would be better experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
