### ISSUE TITLE
feat(patch): full screen comment layout

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#642]
### Application

YouTube

### Issue

in the previous rvx, full screen comment layout was little different. Below the image that i posted, number1 arrow slidedown/up doesnt work.(it worked in previous version but i cant remember;;) Instead number 2 arrow direction activates on recent rvx. However the problem is this. when we scroll up and down with full screen comment, number2 and number3 direction movements is collapsing. Specifically when we scroll down comment by number3 sometimes comment section blow up by number2. I hope you understand what i mean.(sorry for not video just text)

### Patch

![Screenshot_20230404_230650_YouTube](https://user-images.githubusercontent.com/113352087/229821491-24c10c1f-2e53-4749-a072-31651cc62c2c.jpg)

### Motivation

it will be more nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reproducible even on unpatched YouTube
It looks like Google changed YouTube's layout server-side
