### ISSUE TITLE
After the last few patches I have the old bottom layout. Is it something server side?

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#643]
### Application

YouTube

### Description

After the last few patches I have the old bottom layout.

![IMG_20230404_161424](https://user-images.githubusercontent.com/125223735/229824108-c0fb9e3c-0969-4581-b1e5-1f4bea13c6bf.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It also reproducible even on unpatched YouTube
It looks like Google changed YouTube's layout server-side
