### ISSUE TITLE
feat(patch): Option to add button background on individual button when player overlay filter is hidden

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#645]
### Application

YouTube

### Issue

When player overlay filter is hidden it hard to see the buttons when there is a white background. Would it be possible for other buttons to have the player background buttons just like pause, previous and next?

### Patch

![Screenshot 20 51 (Tuesday 04 04) msedge 322](https://user-images.githubusercontent.com/125728453/229840354-4b06ce6b-ed00-4ebc-9b86-caa05b3650e6.png)
![Screenshot 20 51 (Tuesday 04 04) msedge 323](https://user-images.githubusercontent.com/125728453/229840387-1f14c11c-135c-4a26-a5dc-aebb2314ba96.png)

### Motivation

Easier to see especially on white screens

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
