### ISSUE TITLE
feat(patch): `disable-landscape-mode` patch

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#646]
### Application

YouTube

### Description

https://user-images.githubusercontent.com/125223735/229881827-89b48ad4-670f-4fa0-8a5f-b98f32746e2e.mp4

In ReVanced Extended I don't see them

https://user-images.githubusercontent.com/125223735/229882538-bc697ea3-8114-4983-9b16-41b22a37c152.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.15)

**Comment by Evergard** [comment]
> reflected in [revanced-patches-v2.168.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.15)

This was the exact patch request that I did .-.

**Comment by odkrys** [comment]
It would be nice if this patch could be reversed, as on tablets I have to turn on auto-rotation to view the video in landscape.
It would be nice to have "enable-landscape-mode" for tablets.

**Comment by odkrys** [comment]
You will know what I'm talking about.
I surf the web in portrait mode with auto-rotation off on my tablet. Because I don't want the screen to rotate depending on the angle.
Then open YouTube and make the video full screen. Then, on the tablet, it becomes a portrait mode full screen, so I have to turn the tablet after turning on the auto-rotation feature.

This is not the case with smartphones. Because when I press the full screen button, the video automatically becomes landscape full screen.

I'd love to make this an option. I don't know why revanced #923 doesn't understand this. On a tablet this is pretty annoying.

**Comment by odkrys** [comment]
I modified the smali code a bit. Even on a tablet, like a smartphone, when I press the full screen button, it works as landscape full screen.
```
root@instance-20220814-1527:~/test# grep -r "disableLandScapeMode" ./youtube-revanced_v18.09.39
./youtube-revanced_v18.09.39/smali_classes5/taz.smali:    invoke-static {p1}, Lapp/revanced/integrations/patches/layout/FullscreenPatch;->disableLandScapeMode(Z)Z
./youtube-revanced_v18.09.39/smali_classes5/taz.smali:    invoke-static {p1}, Lapp/revanced/integrations/patches/layout/FullscreenPatch;->disableLandScapeMode(Z)Z
./youtube-revanced_v18.09.39/smali_classes5/app/revanced/integrations/patches/layout/FullscreenPatch.smali:.method public static disableLandScapeMode(Z)Z
```

./youtube-revanced_v18.09.39/smali_classes5/taz.smali
original
```
.method public constructor <init>(Landroid/app/Activity;)V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    iput-object p1, p0, Ltaz;->b:Ljava/lang/Object;

    invoke-static {p1}, Lrla;->Z(Landroid/content/Context;)Z

    move-result p1

    invoke-static {p1}, Lapp/revanced/integrations/patches/layout/FullscreenPatch;->disableLandScapeMode(Z)Z

    move-result p1

    iput-boolean p1, p0, Ltaz;->a:Z

    return-void
```
```
.method public final f(Landroid/content/res/Configuration;)V
    .locals 1

    if-eqz p1, :cond_0

    iget-object v0, p0, Ltaz;->b:Ljava/lang/Object;

    check-cast v0, Landroid/app/Activity;

    .line 1
    invoke-virtual {v0, p1}, Landroid/app/Activity;->createConfigurationContext(Landroid/content/res/Configuration;)Landroid/content/Context;

    move-result-object p1

    invoke-static {p1}, Lrla;->Z(Landroid/content/Context;)Z

    move-result p1

    invoke-static {p1}, Lapp/revanced/integrations/patches/layout/FullscreenPatch;->disableLandScapeMode(Z)Z

    move-result p1

    iput-boolean p1, p0, Ltaz;->a:Z

    :cond_0
    return-void
.end method
```

modified
```
.method public constructor <init>(Landroid/app/Activity;)V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    iput-object p1, p0, Ltaz;->b:Ljava/lang/Object;

    const/4 p1, 0x0

    iput-boolean p1, p0, Ltaz;->a:Z

    return-void
```
```
.method public final f(Landroid/content/res/Configuration;)V
    .locals 1

    if-eqz p1, :cond_0

    iget-object v0, p0, Ltaz;->b:Ljava/lang/Object;

    check-cast v0, Landroid/app/Activity;

    const/4 p1, 0x0
    
    iput-boolean p1, p0, Ltaz;->a:Z

    :cond_0
    return-void
.end method
```
