### ISSUE TITLE
feat(patch): SponsorBlock import/export settings system same as RVX

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#648]
### Application

YouTube

### Issue

Currently there's a copy/paste system to import/export settings for SponsorBlock.

### Patch

When exporting the settings for SponsorBlock, save it into a json file and when importing, allow to choose the exported file, exactly like the ReVanced eXtended system present in Miscellaneous.

### Motivation

To improve the system of importing/exporting settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
refer comments https://github.com/inotia00/ReVanced_Extended/issues/179#issuecomment-1439275792
