### ISSUE TITLE
bug: Short PiP breaks when recents button or phone home button is pressed while you're watching it

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#649]
### Type

Other

### Application

YouTube v18.12.35
ReVanced Patches v2.168.12

### Bug description

https://user-images.githubusercontent.com/127908708/229969694-bdb34dc3-ac47-44d9-bca2-e810d8a0e6d5.mp4

### Steps to reproduce

1. Play a short
2. Press the _recents button_ or _phone home button_ **while you're watching the short**

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reproducible even on unpatched YouTube

**Comment by jhon1282** [comment]
On my device, the application closes directly. No PIP in shorts


https://user-images.githubusercontent.com/125223735/229978964-68b7fa6d-f89c-46a5-a3eb-bbc1b093c33f.mp4

**Comment by Kuddus73** [comment]
> This is a YouTube issue

Then would it be possible, as @jhon1282 showed, to add an option that when either of the two buttons mentioned is pressed prevents going into PiP mode?
Or like an option to disable PiP for all shorts?
