### ISSUE TITLE
feat(patch): select only specified languages in cli.

### ISSUE THREAD

**Issue by bw003** [inotia00/ReVanced_Extended#65]
### Application

YouTube

### Issue

Just like rip-lib, there should be a feature to select only required languages like english and any regional languages. This will help in reducing the apk size a lot.

### Patch

Just like rip-lib, there should be a feature to select only required languages like english and any regional languages. This will help in reducing the apk size a lot.

### Motivation

Just like rip-lib, there should be a feature to select only required languages like english and any regional languages. This will help in reducing the apk size a lot.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This request cannot be implemented in CLI due to limitations in the patch method
