### ISSUE TITLE
bug: cannot interact 

### ISSUE THREAD

**Issue by nobl55** [inotia00/ReVanced_Extended#650]
### Type

Error at runtime

### Application

YouTube 18.12.35
Patch 2.168.12

### Bug description

Patching in updated Termux without problem. Once I start the patched app it starts no problem normal brightness.
Then immediately after start some kind of overlay grays the screen and prevent any interaction 

### Steps to reproduce

Standard install

### Relevant log output

```shell
Don't know where to get that
```

### Additional context

Already tried to reinstall from scratch. Including other youtube versions. Same problem.

### Device Environment

Oneui 5.1 fold 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It is missing information about which patches were included or excluded, what the specific symptoms were (screenshots to support the description), and what process could reproduce the issue.

**Comment by nobl55** [comment]
Protobuf spoofing seems to be the culprit.
Disabling it makes the app work normally it seems.

**Comment by inotia00** [comment]
bruh closed by mistake

**Comment by inotia00** [comment]
`protobuf-spoof` patch does not interact with the layout in any way.

**Comment by nobl55** [comment]
Then i don't know. I tried so many things. Then i turned protobuf patch off and reinstalled (each time from scratch) and it works🤷🏻‍♂️

**Comment by inotia00** [comment]
I didn't understand what you said
(Also, simply turning on `protobuf-spoof` does not reproduce the issue)

Once the issue can be accurately reproduced, please reopen the issue with additional information
