### ISSUE TITLE
bug: Video ads whitelist not working 

### ISSUE THREAD

**Issue by rsaurav12** [inotia00/ReVanced_Extended#652]
### Type

Other

### Application

YouTube 18.12.35
Patch 2.168.15

### Bug description

After Whitelisted any channel for video ads, the ads still won't show up on any video of that channel

### Steps to reproduce

1) include "overlay-button" patch and  patch it  and then install
2) go to "overlay button " section in Revanced settings
3) enable "show whitelist button"
4) go to your desire channel that you wanna watchlist it
5) click any video of than channel
6) tap on Whitelist button on video overlay
7) tap on ADS
8) try to watch the same video again or another video of that same channel you watchlisted
9) you will see ads are still not showing up

### Relevant log output

```shell
No log
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
it's weird
Even though I have checked all the code, It can't turn off at all by `Hide video ads` setting

Once the `hide-video-ads` patch is included, you can't turn off any way.
(Currently, Google is testing a lot on the server side, so this may be the reason for the bug. At least when I tested it last month, it worked normally)

Would you like to patch with YouTube v18.06.41, the minimum version of RVX and test it?

**Comment by rsaurav12** [comment]
I tested it bit still ads won't show up

**Comment by inotia00** [comment]
Only added in commit, not released yet
Perhaps the video ad whitelist feature will be removed

**Comment by inotia00** [comment]
removed in [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)

**Comment by igarca** [comment]
> removed in [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)

I am sad you removed it. It was the reason why I installed RV Extended:( because I could use RV but support useful channels, which I consider very important!
I hope you reconsider it:( Thanks for your work anyways!!
