### ISSUE TITLE
bug: playlist popup is floating upward 

### ISSUE THREAD

**Issue by rsaurav12** [inotia00/ReVanced_Extended#653]
### Type

Other

### Application

YouTube: 18.12.35

### Bug description

When i tap on playlist it floats upward 

### Steps to reproduce

1) tap on playlist below any video 

### Relevant log output

```shell
No log
```

### Screenshots or videos

![Screenshot_2023-04-05-17-13-03-445_app rvx android youtube](https://user-images.githubusercontent.com/53332518/230071819-474ac6e4-3347-41c6-8868-b35243e692eb.jpg)

### Device Environment

Miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This issue also occurs occasionally on unpatched YouTube

Looks like an issue on YouTube

**Comment by rsaurav12** [comment]
Oh okay thanks
