### ISSUE TITLE
question: how to get revanced ext. notification working on miui 14? 

### ISSUE THREAD

**Issue by rsaurav12** [inotia00/ReVanced_Extended#655]
### Application

YouTube

### Description

Seen i deleted youtube app from my device and started using vanced, then revanced classic, then revanced extended i never ever got any notification. 

1.) I have disabled battery optimisation of revanced ext. And vanced Microg.
2.) Microg cloud messanging status is connected 

But still problem didn't solved

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
First of all, to fix this issue, I need to know which build of Vanced MicroG you are using.

If you are using the Vanced MicroG build in my fork repo, there is an issue where notifications are sometimes missing from the last build v0.2.27.230755

If you are using this build, please roll back to the [previous build](https://github.com/inotia00/VancedMicroG/releases/tag/v0.2.26.225014)

If you're using the official Vanced MicroG (v0.2.24.220220) build, I can't help you with this.

On MIUI devices, you need to grant Autostart permission for Vanced MicroG to run smoothly in the background.

Please refer [this document](https://nine-faq.9folders.com/articles/8772-how-to-manage-autostart-service-on-the-xiaomi-devices)
