### ISSUE TITLE
feat(patch): Hide Likes, Dislikes and Share buttons in shorts player

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#656]
### Application

YouTube

### Issue

![20230405_172830](https://user-images.githubusercontent.com/127908708/230144818-b626fbab-8518-4c8f-bb28-af2516cf99dd.jpg)

### Patch

Three toggles to show or hide the three mentioned buttons.

### Motivation

To make YT more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
