### ISSUE TITLE
feat(patch): Hide trending searches

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#657]
### Application

YouTube

### Issue

In the search page keyword that i didnt searched is keep showing below the searchtab despite of disabled youtube history. Can you  remove this unwanted keyword plz?

### Patch

![Screenshot_20230406-091847_YouTube](https://user-images.githubusercontent.com/113352087/230245322-3afa8442-e15e-4463-a31a-ce9d9edc349b.jpg)

### Motivation

It would be nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)
