### ISSUE TITLE
feat(patch): Remove translate button under comments

### ISSUE THREAD

**Issue by SoundBoomer** [inotia00/ReVanced_Extended#658]
### Application

YouTube

### Issue

I don't like when I watch a video in a foreign language I know and every single comment has the "Translate into *language name*" button which just takes space.

### Patch

An option in settings to disable translation button under comments. And an option to not translate comments from a certain language would be great.

### Motivation

It would improve readability and save space

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
