### ISSUE TITLE
feat(patch): add sound button to videos in subscription feed

### ISSUE THREAD

**Issue by WanderBoi** [inotia00/ReVanced_Extended#659]
### Application

YouTube

### Issue

No autoplay buttons in the subscription feed 

### Patch

The ability of turning sounds on or off for ambient mode in youtube subscription feed, or having it always on if the patch is chosen whichever is easier

### Motivation

Honestly, just inconsistencies, never understood why the option isn't there, and I'd love to start enjoying my subscription feed again, it seems like it was forgotten by youtube

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I didn't understand the content
Please add a bit more explanation

**Comment by WanderBoi** [comment]
![SmartSelect_20230406_181854_ReVanced Extended.jpg](https://user-images.githubusercontent.com/29160030/230424138-c599e0c8-4a17-4138-98fc-f5a2feeb1fa8.jpg)
This, but for the subscription feed, so you can listen to the videos in ambient mode

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
