### ISSUE TITLE
feat(patch): shorts player lagging

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#660]
### Application

YouTube

### Issue

when we see a short video which is under of the normal video (not from the shorrts tab) the first shorts video have a loading lag. Im not sure that this is because if protocal spioofing patch but this lag appears even we turn off protocal spoof. Also  can you see the search tab issue that i wrote before? it even get more worse. i had 2 more unwanted search tab.

### Patch

![Screenshot_20230406_233844_YouTube](https://user-images.githubusercontent.com/113352087/230423398-3e7a2569-a272-4750-99a4-cd5566317e27.jpg)

### Motivation

it will be more nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/556
https://github.com/inotia00/ReVanced_Extended/issues/543
