### ISSUE TITLE
feat(patch): Change app language

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#661]
### Application

YouTube

### Issue

Currently, it isn't possible to have the language of the app different from that of the phone.

### Patch

Add a setting to change the app language.

### Motivation

Many other apps already provide a built-in language setting just for the app, but YouTube still lacks it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DRYN07** [comment]
This is the most frustrating thing if an app lacks this option. I live in a small country with an uncommon language. That means every app with this auto-translate crap provides a pathetic useless translation. If I stumble upon an app like this that I want to use, I always write to the devs that put at least a freakin English in it. It drives me crazy. And the craziest is that Google, one of the biggest company in the universe can't make a language switch button in their products... 

So I absolutely support this request. I think most of us don't need translations, just a "force english" option or something.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
