### ISSUE TITLE
bug: <title>revanced extended se cierra pasados los 2 minutos de minimizar o incluso menos 

### ISSUE THREAD

**Issue by Quiceno96** [inotia00/ReVanced_Extended#662]
### Type

Error while patching

### Application

Error en APK revanced extended 18.13.36 luego de poner a reproducir un video o lista de reproducción en segundo plano a los 2 minutos o menos la aplicación se cierra totalmente pero una vez que se cierra y se vuelve a abrir no vuelve a ocurrir hasta que lo cierres de nuevo tu mismo

### Bug description

Solo me ha ocurrido este error lo descubrí al minimizar la aplicación y usar la ventana flotante 

### Steps to reproduce

No hay algo en específico 

### Relevant log output

```shell
No me salen códigos
```

### Screenshots or videos

No poseo algúno en especial 

### Device Environment

Lenovo legión duel 2 android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
1. When opening an issue, please write in English
2. YouTube v18.13.36 is not the recommended version.
non-recommended version no support
