### ISSUE TITLE
bug: some elements in the video player screen are blank black

### ISSUE THREAD

**Issue by OmarKlhaled** [inotia00/ReVanced_Extended#663]
### Type

Other

### Application

YouTube v18.12.35
ReVanced Patches v2.168.18

### Bug description

It's sometimes the first video suggestion (mostly) or the whole video suggestions or the comment preview panel.
They will look blank black until scrolling down.

### Steps to reproduce

1. Play a video.
2. Minimize it.
3. Exit YouTube and let the video playing in background.
4. Re-open YouTube and maximize the video player.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![1](https://user-images.githubusercontent.com/49593839/230559767-f086fc40-a148-4c9c-8228-1de499514430.gif)
![2](https://user-images.githubusercontent.com/49593839/230559848-b36372e3-dc3a-4af6-9b4b-8de308b98227.gif)
![3](https://user-images.githubusercontent.com/49593839/230559391-4ef1b330-529f-47b6-89b5-0ad84415907b.gif)

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is an outdated issue
