### ISSUE TITLE
feat(patch) : Restore the YTM library to the old style

### ISSUE THREAD

**Issue by harutoku** [inotia00/ReVanced_Extended#664]
### Application

YouTube Music

### Issue

・

### Patch

As the title says.

### Motivation

・

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please add a description or attach a screenshot

**Comment by harutoku** [comment]
![Screenshot_20230408-085926859 (1).jpg](https://user-images.githubusercontent.com/123850345/230694528-39023879-fdd8-49ed-b08e-7464a89c63f6.jpg)

![Screenshot_20230408-090823758 (1).jpg](https://user-images.githubusercontent.com/123850345/230694529-c8a3f1e2-01e7-4a76-990a-5ce4dd81caff.jpg)

Sorry, I didn't explain too well.

**Comment by harutoku** [comment]
We want them to go from the state pictured above to the state pictured below.

I am Japanese, so sorry if my English is wrong.

**Comment by inotia00** [comment]
ahh got it
It doesn't seem easy to implement this because the new layout is forced to be overridden on the server side

If you try patching with YouTube Music v5.34.52 or earlier, you will get a UI like the attached screenshot

**Comment by harutoku** [comment]
Oh, I see. I'm sorry, but it can't be helped.
Thank you very much, I will actually use it.
