### ISSUE TITLE
bug: 'Double back timeout' not working properly

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#665]
### Type

Other

### Application

YouTube v18.12.35
Patch v2.168.18

### Bug description

The app exits on single back press/swipe irrespective of the timeout set in the 'Double back timeout' settings.

### Steps to reproduce

1. Set 'Double back timeout' to 1 or 2 or 3 sec.
2. Press/swipe back single time.
The app exits on the single back press/swipe (which should happen only when the timeout is set to 0 sec).

### Relevant log output

```shell
N.A.
```

### Screenshots or videos

https://user-images.githubusercontent.com/125809686/230612223-537ee6a1-5ec8-41b6-8c2c-76536e8aaf7f.mp4

### Device Environment

Android 13, Realme UI 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The patch is only effective when ads appear on the first view of the home feed due to structural limitations.

Therefore, ads are not shown on the first view of the home feed, or are not valid for YouTube Premium subscribers.

There is no plan to fix

**Comment by madhurvarshney** [comment]
But I am not a YouTube Premium subscriber. I am just using the "Premium" header.

**Comment by inotia00** [comment]
In addition to YouTube Premium subscribers, the doubleback timeout does not work even if no ads are shown on the first view.
(whether ad is shown on first view depends on server side)

From the beginning, the patch is a feature added to solve the issue of 'Can't exit the app with the back button in the home feed'
(Patch to fix a bug inherited from Vanced)

**Comment by madhurvarshney** [comment]
Got it 👍
