### ISSUE TITLE
bug: Faded black screen preventing interaction with app

### ISSUE THREAD

**Issue by ShinyGil** [inotia00/ReVanced_Extended#666]
### Type

Error at runtime

### Application

ReVanced Extended v18.13.37

### Bug description

On launch, my screen went dark and I can't interact with anything, almost as if there was a pop up menu I couldn't see. Nothing makes the screen usable, even uninstalling and reinstalling ReVanced Extended.

### Steps to reproduce

Launch the app.

### Relevant log output

```shell
No log output I am aware of
```

### Screenshots or videos

![Screenshots_2023-04-07-09-12-40](https://user-images.githubusercontent.com/130161554/230623588-841ec585-21af-4019-9cb9-42f25d4209ad.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
non recommended versions are not supported

**Comment by ShinyGil** [comment]
> non recommended versions are not supported

Not sure I understand, I downloaded the latest version from the ReVanced site (listed as today, April 7). Would the latest version be unrecommended? For what it's worth, this issue did also happen before updating.

**Comment by inotia00** [comment]
I do not provide prebuilt APKs

Contact the administrator of the site providing that APK.

The current recommended version is v18.12.35
