### ISSUE TITLE
feat(patch): Amoled Theme Switch

### ISSUE THREAD

**Issue by sequekento108** [inotia00/ReVanced_Extended#667]
### Application

YouTube

### Issue

add an option to enable or disable amoled theme

### Patch

there would be an "amoled mode" switch in the settings which would allow the user to turn the amoled theme on or off

### Motivation

it would allow people who dont want to use the amoled theme to just turn in off in the app instead of having to build a whole different apk/magisk module just to change the theme and it would also be better for security because people who cant/dont know how to build the app themselves and want to use the app with a different theme wouldnt have to download it from random repos with the theme patch removed 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
