### ISSUE TITLE
bug(YouTube/Return YouTube Dislike): dislike count not showing after playing Shorts

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#668]
### Type

Other

### Application

YouTube v18.12.35
ReVanced Patches v2.168.21

### Bug description

https://user-images.githubusercontent.com/127908708/230697820-5774f240-62d8-415c-b423-c3cf5c4cae56.mp4

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jhon1282** [comment]
Is it possible that the bug is related to RYD support for Shorts?
Exiting the current video probably RYD connects to the server again to show the Dislikes of the Short.
Going back to the current video, being already running it won't connect anymore.
It's just a guess

**Comment by jhon1282** [comment]
Start video
Watch the Dislikes
Now launch Short
Watch the Dislikes
Close app
Re-open and go back to the initial video
Both have the same number of Dislikes
![IMG_20230408_063602](https://user-images.githubusercontent.com/125223735/230703583-a7de6c7f-8b2e-411f-a605-0a4b58f314e8.jpg)

![IMG_20230408_063313](https://user-images.githubusercontent.com/125223735/230703622-fc67c3cb-9b31-4de7-a2ba-a2c69c40743a.jpg)

**Comment by inotia00** [comment]
> Start video Watch the Dislikes Now launch Short Watch the Dislikes Close app Re-open and go back to the initial video Both have the same number of Dislikes ![IMG_20230408_065344](https://user-images.githubusercontent.com/125223735/230703856-6e862034-77a9-4d17-9db6-d27452c99cf4.jpg)
> 
> ![IMG_20230408_063602](https://user-images.githubusercontent.com/125223735/230703583-a7de6c7f-8b2e-411f-a605-0a4b58f314e8.jpg)
> 
> ![IMG_20230408_063313](https://user-images.githubusercontent.com/125223735/230703622-fc67c3cb-9b31-4de7-a2ba-a2c69c40743a.jpg)

this is a separate issue

Please open a separate issue page

**Comment by jhon1282** [comment]
Sorry I think is related to same issue.
As soon as I can I open a new one.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)
