### ISSUE TITLE
feat(patch): Add an patch option to disable "Playback in feeds" by default

### ISSUE THREAD

**Issue by gotham8x** [inotia00/ReVanced_Extended#669]
### Application

YouTube

### Issue

Whenever users install a new ReVanced_Extended version, we have to manually go to the settings to turn off the "Playback in feeds" setting. It would be beneficial if ReVanced_Extended had a patch that disabled it by default.

### Patch

Add a new patch option to disable "Playback in feeds" by default.

### Motivation

It would save a lot of time during installation, and users would be more willing to try/test new patch versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
