### ISSUE TITLE
feat(patch): loaded video seekbar

### ISSUE THREAD

**Issue by User-noob2036876** [inotia00/ReVanced_Extended#67]
### Application

YouTube

### Issue

On youtube's old version (new layout update), the video seekbar was as follows;
![Screenshot_20221228-162428](https://user-images.githubusercontent.com/117031829/209819674-9fa1e508-c5d6-4694-8105-701e60d6a0ad.jpg)
but rvx's `old-seekbar-color` patch does not show loaded  the times like in photo;
![Screenshot_20221228-161643_ReVanced Extended](https://user-images.githubusercontent.com/117031829/209820168-840e49c5-1ea8-406d-a1eb-1fb7e0f868b1.jpg)

### Patch

Video-seekbar-color patch show loaded times.
It even shows the loaded times when the player interface is open in the new overlay;
![Screenshot_20221228-161516_ReVanced Extended](https://user-images.githubusercontent.com/117031829/209820641-19c0150f-0d46-4fe8-9f49-371d1da63616.jpg)

### Motivation

without clicking the screen, we can see loaded times

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by User-noob2036876** [comment]
@inotia00 add it until its too late, please

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
