### ISSUE TITLE
feat(patch) : turn off trending/recommended search suggestions

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#671]
### Application

YouTube

### Issue

Refer to this screenshot - 
![IMG_20230408_110128](https://user-images.githubusercontent.com/64865031/230705138-de248e52-84ad-4d72-8e76-fff0be4c4b74.jpg)

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/657
