### ISSUE TITLE
bug: bag in player

### ISSUE THREAD

**Issue by FrontEnd07** [inotia00/ReVanced_Extended#672]
### Type

Error at runtime

### Application

18.10.37

### Bug description

While playing a video, the video is interrupted and continues, something is wrong with the buffering of the video player, I don't know how to catch the bug in an understandable way, but I'll attach a screenshot of the player

### Steps to reproduce

Я не нашел этой вкладки на приложения

### Relevant log output

```shell
Я не нашел этой вкладки на приложения
```

### Screenshots or videos

![photo1680956108](https://user-images.githubusercontent.com/91734166/230720558-dd6a2a79-4c1a-4d0c-b1ec-c930bdbcbbf2.jpeg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Just re-patch with latest sources
