### ISSUE TITLE
bug: Inconsistent spacing between action buttons.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#674]
### Type

Cosmetic

### Application

YouTube 18.12.35
Patches: 2.168.18
Integrations: 0.101.18

### Bug description

I just use Like, Dislike, Share, Download and Save.

And there is inconsistent spacing between these buttons (kindly see attached screenshot).

### Steps to reproduce

Step 1: Just keep these 5 buttons enabled and see (Like, Dislike, Share, Download, Save)

### Relevant log output

```shell
Kindly see screenshot.
```

### Screenshots or videos

![IMG_20230408_195045](https://user-images.githubusercontent.com/91815107/230726997-ca601221-6941-42ee-a752-e135759892b9.jpg)

### Device Environment

Realme 7 Pro, running on Android 12 (skin name is Realme UI 3.0).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/17
