### ISSUE TITLE
feat(patch): disable auto scrolling in Shorts

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#675]
### Application

YouTube

### Issue

Auto-Scrolling feature in Shorts in YT

### Patch

Can you add a patch for this auto-scrolling feature in shorts.

### Motivation

Will enhance use of shorts

https://a.uguu.se/xPKSgEmo.mp4

I got this at random open of YT (don't know how)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I didn't understand
You mean, autoplay in shorts?

**Comment by Vipin2003** [comment]
I mean that shorts should automatically scrolled to next short without scrolling it manually. Check the video I have provided

**Comment by inotia00** [comment]
oh I got it

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
