### ISSUE TITLE
bug: shorts ads are blocked

### ISSUE THREAD

**Issue by inotia00** [inotia00/ReVanced_Extended#676]
### Type

Error at runtime

### Application

YouTube v18.13.38

### Bug description

Until now, no YouTube client has been able to block shorts ads.

But on YouTube v18.13.38, shorts ads are blocked
Since the patch to remove ads in shorts has not been implemented, this is an obvious bug

### Steps to reproduce

1. Patch YouTube v18.13.38 with the latest resources
2. Open shorts
3. No ads are shown on shorts

### Relevant log output

```shell
N/A
```

### Screenshots or videos

N/A

### Solution

If I find a solution, I'll reflect it into the repository.

### Additional context

N/A

### Device Environment

Android 13, Android Virtual Device

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
I noticed the same on v18.12.35 and now also in v18.13.38 I am noticing the same thing:
Sometimes such ads are shown as shown below:
![Screenshot_2023-04-09-14-21-16-57_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/230763461-c12307f6-e395-466d-808e-37d25efe091f.jpg)
![Screenshot_2023-04-09-14-21-33-62_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/230763470-bbd914f5-b5a6-48ab-b2b9-213b596d0087.jpg)
And other times, it just shows black screen (see below)
![Screenshot_2023-04-09-14-21-47-72_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/230763509-c5202c27-8cb1-4e45-97b2-cfcd9d685e8f.jpg)
Showing of ads/black screen is like 50-50%
Location - India

**Comment by selfmusing** [comment]
👁️👄👁️

**Comment by Adity1243** [comment]
Just skip the black screen when is short ad is going to pop.it will be fine

**Comment by inotia00** [comment]
fixed by Google
