### ISSUE TITLE
bug: like/dislike text color changing after clicking 

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#677]
### Type

Error at runtime

### Application

YouTube 18.13.38
Patch 2.168.24

### Bug description

https://user-images.githubusercontent.com/64865031/230732444-44c22fb3-03ea-4e2c-ac84-8955bd04e676.mp4

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Device Environment

Android 13, MIUI 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
If you are using MIUI, try turning off the force dark mode

**Comment by sleepingiv** [comment]
Force dark mode for individual apps are turned off for revanced extended

**Comment by inotia00** [comment]
It can be reproduced on videos with like counts exceeding 1k
A rollback will be made in the next release to prevent this issue.

**Comment by sleepingiv** [comment]
Thanks 🙏

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.168.27
