### ISSUE TITLE
About the Material YOU + Amoled theme.

### ISSUE THREAD

**Issue by holyvicks** [inotia00/ReVanced_Extended#678]
### Application

YouTube

### Description

How can I disable it? Or changing it? Because I wanted to have the colors like in the standard version of YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
Just exclude `Materialyou` patch.

**Comment by holyvicks** [comment]
Ok, but how do I do this?

**Comment by madhurvarshney** [comment]
Do you patch using ReVanced Manager or some other way like using Revancify?

**Comment by holyvicks** [comment]
I'm using ReVanced Manager

**Comment by madhurvarshney** [comment]
So just scroll down and find the `Materialyou` patch and uncheck it.
Btw I suggest you to use recommended patches (that will exclude this `Materialyou` patch by default). You can do so by just clicking on the "Recommended" option available at the top of the "Select patches" page.

**Comment by inotia00** [comment]
If you want to use the stock YouTube theme, exclude the `theme` patch and the `materialyou` patch.

Please refer the patch information [wiki](https://github.com/inotia00/revanced-documentation/wiki/Options-Information-about-the-patch#if-you-want-only-black-theme) for details

**Comment by holyvicks** [comment]
Thanks for the help!
