### ISSUE TITLE
bug: "invalid hex code" toast appears while playing videos in playstore

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#679]
### Type

Error at runtime

### Application

18.13.38, latest patches

### Bug description

After update, the play store doesn't crash anymore, but an "invalid hex code" message appears while playing a video from the play store 

### Steps to reproduce

Make sure play store and youtube are closed
Open play store, and find an youtube video to play (you can just search for the youtube app, there is a video there)
Play the video, and see the toast

### Relevant log output

```shell
---
```

### Screenshots or videos

![Screenshot_20230409-021112](https://user-images.githubusercontent.com/6445601/230746340-381ea68d-0e58-4fc2-95f6-81a060d1082e.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
I am currently using YouTube v18.12.35 and patch v2.168.21 and it works fine on that.

**Comment by psrocksstill** [comment]
same here i just recently notice the toast "invalid hex code" after updating the app in the magisk

**Comment by madhurvarshney** [comment]
I have updated to the latest patches and this issue doesn't occur for me.

**Comment by psrocksstill** [comment]
> I have updated to the latest patches and this issue doesn't occur for me.

done updating on latest version via magisk still the toast  invalid hex code persist specially videos playing in youtube site via google discover or other platform

**Comment by psrocksstill** [comment]
i followed inotia00 fix..and it works just disable "custom seekbar color"  in Settings>Revanced Extended>Custom Seekbar  Color

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)

**Comment by psrocksstill** [comment]
> fixed in [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)

thank you so much for the fix ❤️❤️
