### ISSUE TITLE
bug(YouTube/Hide videos ads): video ads are always hidden

### ISSUE THREAD

**Issue by rsaurav12** [inotia00/ReVanced_Extended#680]
### Type

Other

### Application

YOUTUBE 

### Bug description

disabling "Hide videos ads" doesn't show ads

### Steps to reproduce

-

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by madhurvarshney** [comment]
Maybe close this issue as it's kinda duplicate and @inotia00 clarified it [here](https://github.com/inotia00/ReVanced_Extended/issues/652#issuecomment-1497773102) ?

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.201.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.201.1)
