### ISSUE TITLE
feat(patch): split hide previous and next button option

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#681]
### Application

YouTube

### Issue

Hide previous and next button option was previously two different options

### Patch

Make hide previous and next button option two options again

### Motivation

I only hid the next button because when I double-tapped to skip forward I always pressed it by mistake
I never hid the previous button because it's the only way for going back to the first video when you are watching a related video

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
