### ISSUE TITLE
bug: YouTube/Premium Header is not visible on the "You" (Library) page in the new layout

### ISSUE THREAD

**Issue by madhurvarshney** [inotia00/ReVanced_Extended#683]
### Type

Cosmetic

### Application

YouTube v18.13.38
Patch v2.168.27

### Bug description

In the Youtube v18.13.38 with patch v2.168.27, YouTube/Premium header is not visible on the page called "You", as in the new layout. (See Image 1)
It was visible until the Youtube v18.12.35 with patch v2.168.21. (See Image 2)

### Steps to reproduce

N.A.

### Relevant log output

```shell
N.A.
```

### Screenshots or videos

Image 1
![Screenshot_2023-04-09-23-35-23-29_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/230790360-be25401d-cf62-4a52-8b84-d6830f140023.jpg)

Image 2
![Screenshot_2023-04-09-23-36-14-67_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/230790370-b545ea51-4b74-4b24-bf5b-e988c8d17fcb.jpg)

### Additional context

Even including the `force premium heading` patch  doesn't show Premium header on the "You" page on YouTube v18.13.38/Patch v2.168.27

### Device Environment

Android 13, Realme UI 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
As confirmed in 9to5Google, this is not a bug, but part of new layout
