### ISSUE TITLE
bug: YouTube Music crashes

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#685]
### Type

Error at runtime

### Application

Version 5.51.50 non-root
Android 11, ROG Phone II Ultimate 

Recently I updated RVX Music to the latest patches(features) and when I start it, it crashes only after a few seconds of usage. So after around 20 seconds of using it crashes. Also it feels laggy and heavy ever since this started happening. Essentially cannot use it anymore 😔
Kindly asking for assistance. I really love the new compact dialog feature and wanna be able to use RVX Music. I tried adding/removing certain patches but it still crashes😭

### Bug description

Just crashes after around 20secs and playing around w the app 

### Steps to reproduce

Difficult to describe as it happens on my end.

### Relevant log output

```shell
How can I do this?
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
https://streamable.com/a7svd4

I tried again for the 7th time including these patches and it still crashes after around 30secs. App still feels heavy and laggy. It was so fast before...

**Comment by inotia00** [comment]
Please attach crash log

**Comment by anyujinie** [comment]
> Please attach crash log
> 
> If you don't know how to extract the logcat, try excluding the `hide-new-playlist` patch
> (Patch with high possibility of crash)


You mean disable the "Hide new playlist button in library" patch? I'm already testing the app with that patch disabled.

Yes i don't know how to extract logcat 😕

**Comment by anyujinie** [comment]
@inotia00 
Also please look at how heavy and laggy the app has become. It was superfast before these crashes issue started happening 2 days ago:
https://streamable.com/z1lt86

**Comment by inotia00** [comment]
not reproduced
Fix is impossible unless logcat is attached

**Comment by anyujinie** [comment]
> not reproduced
> Fix is impossible unless logcat is attached

I asked previously **how can I get logcat? **


I suspect it's the "hide playlist button in libary" patch when enabled causing crashes. I'm not 100% sure just a suspicion. 
But the app has also been very heavy and laggy recently for some reason. Was superfast before.

**Comment by inotia00** [comment]
This is how to extract logcat

- Enable USB debugging on your phone
- [Install adb on your PC](https://www.xda-developers.com/install-adb-windows-macos-linux/)
- Connect Phone to PC
- Open cmd from the path where adb.exe is installed
- Enter the following
```
adb logcat *:E > logcat.txt
```

attach logcat.txt here
