### ISSUE TITLE
feat(patch): Dim everything but the video when playing YouTube video.

### ISSUE THREAD

**Issue by devanteweary** [inotia00/ReVanced_Extended#686]
### Application

YouTube

### Issue

No real issue, just make videos easier to see without distraction. Also creates a visually better experience. 

### Patch

I'd love to see the same functionality of the "[Turn Off the Lights](https://play.google.com/store/apps/details?id=com.stefanvd.turnoffthelights)" browser extension in the YouTube app.

When you watch a video, the rest of the app/screen dims by 75%. (maybe by placing a dark layer on top?).

Options requested

- Option to dim everything but video on play. (main function of patch)
- Option to temporarily brighten everything back up when scrolling. Stop scrolling for 5 seconds and resume dimming.
- Option to turn off dimming when video is paused.
- Option to customize dim level.

### Motivation

I've been using this function on desktop YouTube for so long, it's one of those functions that seems like it should be native.
It makes watching videos more immersive, visually makes more sense, and helps eye strain.

Thank you for the consideration and I can't say thanks enough for keeping Revanced/Extended alive.
Can't live without it!

Here's an example: [https://imgur.com/a/mDMoA9y](https://imgur.com/a/mDMoA9y)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
