### ISSUE TITLE
feat(patch): Hide ticket shelf

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#687]
### Application

YouTube

### Issue

![20230410_054225](https://user-images.githubusercontent.com/127908708/230827745-e34bec79-a26f-44d7-84c1-37a474ed7809.jpg)

### Patch

A toggle to hide it.

### Motivation

They kinda look like ads and to make YT more clean.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
bruh Google added another weird shelf
