### ISSUE TITLE
feat(patch): press the back button to minimize in landscape mode

### ISSUE THREAD

**Issue by midnightrebellion86** [inotia00/ReVanced_Extended#688]
### Application

YouTube

### Issue

Older versions of Youtube allowed for people to hit the back button and full screen videos in landscape would collapse the video to miniplayer. In newer versions of the app, I hit the back button and the screen rotates to portrait mode instead of collapsing the full screen to miniplayer.

### Patch

I'd like to see a patch that enables the back button to vollapse the video in landscape mode.

### Motivation

This patch should be considered because I'm sure there are plenty of users who only use Youtube in landscape, and users other than me who stayed on older Youtube versions until recently.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
