### ISSUE TITLE
feat(patch): View community posts on the home page in landscape mode

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#689]
### Application

YouTube

### Issue

Community posts are currently only visible in portrait mode
![Screenshot_2023-04-10-12-35-10-238_app rvx android youtube](https://user-images.githubusercontent.com/125223735/230888028-ca14f5d1-009d-4ee1-bc37-ddfa056f369e.jpg)

### Patch

Add a patch for this feature :Show community posts in landscape if possible

### Motivation

I think it's convenient to be able to view posts in landscape mode, without having to rotate the screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
