### ISSUE TITLE
feat(patch): Shorts can't be added to a playlist when in channel

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#69]
### Application

YouTube

### Issue

This is same behavior with stock YT. When you visit a channel and go to its Shorts list, tap the 3 dots there is no "add to playlist" option that would appear with normal videos. Instead the menu shows only 'Send feedback' option.
Please add this missing option to Shorts in channels.

### Patch

https://user-images.githubusercontent.com/73917917/209890579-307dca2b-6cb8-4e43-ba69-e6edd8ae83f0.mp4

### Motivation

Having the ability to add Shorts to a playlist while being in the channel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Server side issue, not supported by stock YouTube as well
(Features that cannot be implemented in the front end)
