### ISSUE TITLE
bug: <title> video orientation bug

### ISSUE THREAD

**Issue by Aditya646754** [inotia00/ReVanced_Extended#691]
### Type

Error at runtime

### Application

Youtube revanced v18.13.38

### Bug description

While playing video in landscape mode for some time when we touch anywhere on screen the video automatically swiches portrait mode.
make the video orientation change only when we swiches to portrait mode not by automatically.

### Steps to reproduce

Step 1 :- play video in landscape mode for 5 to 10 mins.
Step 2 :- touch anywhere on screen while video in landscape mode. Then sometime The screen automatically switches to portrait mode.

### Relevant log output

```shell
I dont have.
```

### Solution

![Screenshot_2023-04-10-22-50-08-964-edit_app rvx android youtube](https://user-images.githubusercontent.com/126933641/230955535-7e95e13e-e1ae-4c68-90b3-20d6055dcaa7.jpg)
make the patch that video orientation can only change by showed button in screenshot while in landscape mode.

### Device Environment

MIUI 13 , Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reproducible even on unpatched YouTube

**Comment by Aditya646754** [comment]
Cant you patch it like i show in screenshot

**Comment by cuynu** [comment]
> Cant you patch it like i show in screenshot

It's reproducible on original youtube as inotia00 say
