### ISSUE TITLE
bug: `Hide player overlay filter` doesn't work with end screen cards

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#692]
### Type

Other

### Application

YouTube v18.13.38
ReVanced Patches v2.168.27

### Bug description

The player overlay filter is not hidden when end screen cards are shown.

https://user-images.githubusercontent.com/127908708/230992283-fc156df1-6bc1-4774-b9c4-8db7ab565179.mp4

### Steps to reproduce

1. Enable `Hide player overlay filter`
2. Restart the app
3. Watch a video with end screen cards

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
`Hide player overlay filter` removes the dark overlay on the player, not the dark overlay on the end screen

A patch to remove the dark overlay on endscreens has not yet been implemented
