### ISSUE TITLE
feat(patch): Remove player button background and Overlay filter on Shorts 

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#693]
### Application

YouTube

### Issue

https://github.com/inotia00/ReVanced_Extended/issues/258#issue-1583478381
⬆️
Similiar to above patches, I'd like to suggest adding patches to remove the dark background on Shorts Play/Pause button, aswell as the overlay filter when Shorts is paused (it's darkening the Shorts screen...)
Please see here:
https://streamable.com/fy3o24

![Screenshot_20230411-012115716 (1)](https://user-images.githubusercontent.com/73917917/231017471-4cc88681-2a25-4dcd-a850-b3aa937ba7a2.png)

1) There's the player button dark background
2) You can clearly see when Shorts is paused, Overlay filter appears

Please add patches to fix these two issues with Shorts. Thanks in advance 🙏🏻

### Motivation

Better experience when watching Shorts.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
