### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Dosedonor** [inotia00/ReVanced_Extended#694]
### Type

Error while patching

### Application

Youtube v18.06.35

### Bug description

Video won't continue playing after couple of minutes/ infinite loading in fullscreen mode

### Steps to reproduce

-

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20230411_024250_YouTube](https://user-images.githubusercontent.com/130413831/231019659-0b02627f-fd35-4584-9743-fe5d295fcde1.jpg)

### Additional context

Might be android 12 issue or else

### Device Environment

Samsung S10  android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is an outdated issue
Proceed to patch again with the latest resource
