### ISSUE TITLE
feat(patch): default homepage to "Library" page

### ISSUE THREAD

**Issue by FawaSan92** [inotia00/ReVanced_Extended#695]
### Application

YouTube

### Issue

Change the default homepage.

### Patch

Have Youtube default its homepage to the "Library" page when you open the app instead of the default "Home" page.

### Motivation

A patch already exists for changing homepage to the "Subscriptions" page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rks2000** [comment]
Since hide home button and subscription button is added then it will make sense to add this feature also.

**Comment by inotia00** [comment]
Unfortunately, the YouTube internal code is missing the code to designate the library as the home page

**Comment by inotia00** [comment]
yep
