### ISSUE TITLE
Suggestion: The "default video speed in live stream" option description is confusing 

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#697]
![Screenshot_2023-04-11-08-07-34-426_app rvx android youtube-edit](https://user-images.githubusercontent.com/64865031/231041662-1522efc7-aad1-4b05-aa63-e89d4a547b72.jpg)

**Comment by inotia00** [comment]
If the title is too long, it will be truncated with a ... mark.

Therefore, a detailed explanation was added to the summary, and the title can only be expressed as briefly as possible.

**Comment by sleepingiv** [comment]
I mean , the settings toggle is enabled but the description says that it's disabled that's why

**Comment by inotia00** [comment]
ah ok
I will try to fix the title within a range that does not exceed one line.

**Comment by madhurvarshney** [comment]
Moreover, I think the 'V' in "Video" should be lowercase.
