### ISSUE TITLE
feat(patch): Ease of use feature

### ISSUE THREAD

**Issue by assassin2388** [inotia00/ReVanced_Extended#699]
### Application

YouTube

### Issue

Add video quality selection in the interface button
 and 
enable video acceleration forward by simply clicking on the right of the video and promising the speed as it was when decompressing

### Patch

![IMG_٢٠٢٣٠٤١١_٠٨٤٥١١](https://user-images.githubusercontent.com/130437896/231079222-78f0eb4e-39ec-4cc7-a59a-a0d58979ba73.jpg)
![IMG_٢٠٢٣٠٤١١_٠٨٤٤٣٩](https://user-images.githubusercontent.com/130437896/231079235-352a8347-56da-430e-acfa-346a883aee32.jpg)

### Motivation

The demand for the application will increase, 
as putting a shortcut to adjust the quality is very useful, and 
the touch acceleration feature makes the use faster, easier, and more.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
