### ISSUE TITLE
feat(patch): Using the real download button

### ISSUE THREAD

**Issue by Hokyps** [inotia00/ReVanced_Extended#7]
### Application

YouTube

### Issue

We have two download buttons. The one implemented in the player (functional) and the one that asks you to become a premium user.

### Patch

An implementation that let us choose what download button to use. Either the one embedded in the player or the one below in the action buttons.

![194949574-b1f0d3a5-cb12-4e86-baac-fd687cf2a1a0](https://user-images.githubusercontent.com/111386632/199116988-abde0e4a-25be-4659-8de3-e66228cfb24b.jpg)

### Motivation

It's a bit redundant to have two download buttons. I think we can get a like premium experience if we enable the second download button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
