### ISSUE TITLE
feat(patch): Focus Mode

### ISSUE THREAD

**Issue by NeeRaj-2401** [inotia00/ReVanced_Extended#70]
### Application

YouTube

### Issue

As We know, YT algorithm is strongly designed to track & recommended best of the video suitable to user
resulting in user spending more time on YT.
and more time user spends on YT their algorithms learns more about the user
Thats a loop which basically traps user.

### Patch

I was thinking about a solution:
as u guys can hide the general ads components
how about hiding the video components too
in home tab as well as below video playe

### Motivation

that solution might help user to have control over what he is going to watch and on what he should spent time watching, not youtube's suggestions

inspired from [Unhook - Remove YouTube Recommended Videos](https://chrome.google.com/webstore/detail/unhook-remove-youtube-rec/khncfooichmfjbepaaaebmommgaepoid) browser extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by NeeRaj-2401** [comment]
Please give your thoughts in this

 PS: i have already opened the same issue on official patches repo too but dont know how they would react, but as extended provide much more features, so i thought to suggest it here too.

**Comment by inotia00** [comment]
Umm... I don't plan to add this feature

However, you can remove the related video by following the method
1. Go to:
Settings > ReVanced settings > Ads settings > Custom filter
2. Turn on Enabled user filter
3. Add the following keywords to the custom filter:
`related_video`
4. Save, force close and relaunch the app

![related_video](https://user-images.githubusercontent.com/108592928/209927063-88115236-be03-4f57-b288-d10cceb969d9.png)

**Comment by NeeRaj-2401** [comment]
Will this  hide the recommended videos in home tab too?
Or for that there is different filter?

**Comment by inotia00** [comment]
ah, it removes only the related video at the bottom of the video being played

**Comment by NeeRaj-2401** [comment]
Can u please help me with the home tab videos too..

**Comment by inotia00** [comment]
It is impossible

In the official Android YouTube app, there is no way to distinguish whether the video from the home tab is a general video or a related video.

If the feature is necessary, use the browser + extension, or use a completely independent client
(e.g. NewPipe, Libetube, etc)

**Comment by NeeRaj-2401** [comment]
> there is no way to distinguish whether the video from the home tab is a general video or a related video.

Oops...  Hiding all the video in home tab would help too
No need to distinguish

**Comment by NeeRaj-2401** [comment]
Also no alternative client matches the UX of official YT hence applying the custom filter will be good idea.
Also from that its up to me whenever i want to roll back i can just remove the filter

**Comment by elvinup** [comment]
@inotia00 This method `related_video` works` great for 90% of video recommendations, now i just see free youtube movies being recommended on some videos. Do you by chance know what the tag is for those free youtube movies so we could hide those too?

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
