### ISSUE TITLE
bug: Sponsorblock segments won't show milliseconds

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#702]
### Type

Cosmetic

### Application

Youtube 18.13.38 with latest patches

### Bug description

In every video with sponsorblock segments enabled, you can see the list of segments with thier full timings. But since tbe latest update, the segments timings don't show the milliseconds (last 3 digits after the dot).
As segments can be shorter than 1 sec, and segments need to be precise, the millisecond are still valuable. 

### Steps to reproduce

Enable sponsorblock (including voting for segments) 
Enter to a video
Open the segments list

### Relevant log output

```shell
---
```

### Screenshots or videos

![Screenshot_20230411-201401](https://user-images.githubusercontent.com/6445601/231240390-b6d21304-222a-427e-a272-e1303612092b.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a change reflected in the official ReVanced

Since ReVanced Team completely rebases SponsorBlock, it is different from SponsorBlock implemented by Vanced Team.

this is also one of them

So this is not a bug
