### ISSUE TITLE
Fix spacebar play/pause video

### ISSUE THREAD

**Issue by pressRtowin** [inotia00/ReVanced_Extended#704]
This is a longstanding issue in the android youtube app. If you hold <kbd>Ctrl</kbd> in the app (while playing a video), you can even see that this is supported, but in reality, pressing space just toggles whatever element is selected (such as the title/description bar to expand/collapse the video description) unless you're in fullscreen. Absolutely ridiculous that Google has left this unresolved for years now, but maybe it can be fixed via revanced?

![Screenshot_20230411_161318_ReVanced Extended](https://user-images.githubusercontent.com/25999169/231289672-8e40f312-06ab-4477-b489-b515f4478efb.png)

**Comment by inotia00** [comment]
1. Next time you open an issue, please format it with an appropriate label (patch-request).
2. It is impossible unless Google discloses YouTube's source code.
At least to fix an old issue with YouTube, I need YouTube's full source code.
