### ISSUE TITLE
feat(patch): search settings

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#705]
### Application

YouTube

### Issue

Revanced extended now has numerous features and sometimes you need to enable/disable a setting quickly but you have to go through all the settings to find the single one

### Patch

An example from another app
![Screenshot_20230408_150727](https://user-images.githubusercontent.com/130296934/231303198-0d5b3681-e814-48c3-a810-b29f735a1afd.jpg)
![Screenshot_20230408_151708](https://user-images.githubusercontent.com/130296934/231303208-eef30e30-257c-4a0d-ba2c-6ecb681d092a.jpg)

### Motivation

It will make it easier and faster to find the desired setting

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/83
