### ISSUE TITLE
bug: app crash on using force hide player button background patch

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#706]
### Type

Error while patching

### Application

18.13.38 youtube

### Bug description

youtube app crashes on using the force hide player button background patch, i never used this patch before so i cant say if it was the same on earlier releases as well

### Steps to reproduce

1. include the force hide player button background patch
2. install and open rvx, it will crash

### Relevant log output

```shell
.
```

### Screenshots or videos

.

### Solution

.

### Additional context

.

### Device Environment

los18 a11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Exclude the `force-hide-player-button-background` patch and try patching again.

And let me know if crash happens

**Comment by MondayNitro** [comment]
it doesnt, ive patched without those patches. it crashes if i include **force hide/hide player button background patch, and disable dark overlay filter**, but doesnt crash if i include the disable dark background on double tap patch.

**Comment by MondayNitro** [comment]
ok, the two times that i included hide player button background patch and disable dark overlay filter patch, i had also included disable dark background on double tap patch. maybe patches conflicting due to similar nature? otherwise its bad luck here ig. used rvx builder btw

**Comment by inotia00** [comment]
no plans to fix
