### ISSUE TITLE
feat(patch): Disable autoplay for videos in playlists

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#707]
### Application

YouTube

### Issue

For some weird reason YouTube itself doesn't allow disabling the autoplay for videos that are in playlists.

### Patch

Add an option to disable autoplay for videos that are inside a playlist.

### Motivation

The autoplay can be really annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)

- feat(youtube/overlay-buttons): disable autoplay by tapping and holding the `always repeat button`
