### ISSUE TITLE
bug: End Screen Card Isn't Working, Even Thought It's Already Turned Off.

### ISSUE THREAD

**Issue by AryanGoAnimateCool** [inotia00/ReVanced_Extended#709]
### Type

Other

### Application

YouTube 18.14.37 Beta

### Bug description

When I watched any video, end screen card is not working even thought it's already turned off.

### Steps to reproduce

Step 1. Watch Any Video.
Step 2. go into at end video.
Step 3. no end screen card.

### Relevant log output

```shell
I don't know
```

### Screenshots or videos

![Screenshot_20230412_081010_YouTube](https://user-images.githubusercontent.com/101686823/231321532-3d05c4ad-fbfd-45f5-ac62-5b30659cc598.jpg)

### Solution

I don't know

### Additional context

I don't know

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by aryanmaulana7636** [comment]
oh.
