### ISSUE TITLE
feat(patch): Disable Slide left or right to seek gesture

### ISSUE THREAD

**Issue by MF-Debug** [inotia00/ReVanced_Extended#711]
### Application

YouTube

### Issue

I often accidentally trigger this annoying gesture by youtube by touching the screen while playing videos. I've attached a screenshot of this for reference.
![Screenshot_20230411-144410_YouTube](https://user-images.githubusercontent.com/6173607/231402969-9f9d59a4-75de-4732-8bc4-dfe45e27ac69.png)

### Patch

An option to turn off/on this gesture would be fantastic.

### Motivation

I'm sure that many would agree with me that this gesture often gets triggered accidentally, specially if it's a sensitive touchscreen. Moreover, there's already an option to seek directly by tapping on the seekbar itself. I think it's more convenient and safe to use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by australianpokies** [comment]
Was fixed [#1063](https://github.com/inotia00/ReVanced_Extended/issues/1063)
