### ISSUE TITLE
feat(patch): back ground play upgrade

### ISSUE THREAD

**Issue by andylee516** [inotia00/ReVanced_Extended#713]
### Application

YouTube

### Issue

in some shorts video there is a link that can see the full length of video(at comment section). However when we get into that link, we can notice that background play stops. This thing doesnt happen only at shorts btw. In normal videos that link another video at the comment section same thing happens.

### Patch

https://www.mediafire.com/file/frzdr2q1yc1mxzp/Screen_Recording_20230413_000453_YouTube.mp4/file

### Motivation

it would be nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
