### ISSUE TITLE
bug: <title>short bug

### ISSUE THREAD

**Issue by Aditya646754** [inotia00/ReVanced_Extended#714]
### Type

Error while patching

### Application

Youtube revanced extended v18.13.38

### Bug description

Navigation bar is visible after we open comment section even after hiding it.

### Steps to reproduce

Step 1 :- play shorts
Step 2 :- open comments

### Relevant log output

```shell
I dont have
```

### Screenshots or videos

https://user-images.githubusercontent.com/126933641/231599807-b47e0167-3cb0-4839-95a0-05572a61bd44.mp4

### Device Environment

Miui 13, android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Experimental Flags
