### ISSUE TITLE
question: How to update to the latest patch using RVX Builder?

### ISSUE THREAD

**Issue by s23ultra512** [inotia00/ReVanced_Extended#717]
### Application

YouTube

### Description

I know how to build an apk using RVX Builder, but how do I make sure it will update to the latest patches?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Just run rvx-builder and proceed with patching in the same way
rvx-builder automatically fetches for latest patches on github
