### ISSUE TITLE
bug: black screen when trying loading video, but doesn't working.

### ISSUE THREAD

**Issue by AryanGoAnimateCool** [inotia00/ReVanced_Extended#719]
### Type

Error at runtime

### Application

YouTube 18.14.39

### Bug description

When I watched any video, black screen appear when trying loading video.

### Steps to reproduce

N

### Relevant log output

```shell
N
```

### Screenshots or videos

![Screenshot_20230413_165719_ReVanced Extended](https://user-images.githubusercontent.com/101686823/231725402-ea4f170e-6609-4e06-b7c6-5eb0d43588ea.jpg)

### Solution

N

### Additional context

N

### Device Environment

One UI 5.1 Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
turn on `Enable protobuf spoof`

**Comment by aryanmaulana7636** [comment]
But, it will disable end screen card, if I enable that.

**Comment by inotia00** [comment]
it's a known issue, side effect of the `protobuf-spoof` patch

This is why the `protobuf-spoof` patch is designated as `Experimental Flags`
