### ISSUE TITLE
feat(patch): hide player overlay filter in endscreen

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#720]
### Application

YouTube

### Issue

is it possible for you to modify the hide player overlay filter such that it has 2 options for hiding the dark overlay, one for the screen that apperas on single tap, and the other for the dark filter on endscreen overlay. the endscreen overlay has a lot of items on screen which look better with the dark overlay in my opinion. so i would want to keep dark filter for endscreen overlay and remove it for single tap screen.

### Patch

https://user-images.githubusercontent.com/87489540/231734151-7e251607-10ee-4e9f-8b39-1381ce7287f6.mp4

https://user-images.githubusercontent.com/87489540/231734176-03073bd9-f278-41c9-b2a3-e523029cf0f2.mp4

the patch should allow separate options for hiding dark filter on single tap screen and endscreen overlay

### Motivation

the endscreen overlay has a lot of items on screen which look better with the dark overlay in my opinion. so i would want to keep dark filter for endscreen overlay and remove it for single tap screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
@inotia00 dark overlay while screen controls are visible is a imageview, it's id is `scrim_overlay` hope it helps.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
