### ISSUE TITLE
bug: compatibility between hide create button and switch create and notification buttons

### ISSUE THREAD

**Issue by ayushTNM** [inotia00/ReVanced_Extended#721]
### Type

Cosmetic

### Application

YouTube 18.13.38

### Bug description

Turning on switch create and notification buttons while hide create button is turned on still showed create button in top right.

### Steps to reproduce

Turn on hide create button
Turn on switch create and notification button

### Relevant log output

```shell
None
```

### Screenshots or videos

![Screenshot_20230413-132601](https://user-images.githubusercontent.com/78740080/231744621-c6c239a7-8ca7-470c-87b9-1ee84f14f282.png)

![Screenshot_20230413-132641](https://user-images.githubusercontent.com/78740080/231744789-9b361b95-6d58-4b03-8815-c17ee6a32a97.png)

### Device Environment

Android 13, pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This setting is under `Navigation`

And in the attached screenshot, the create button is no longer located on the navigation bar.

Since that setting is a setting to 'remove the Create button in the navigation bar', even if it is enabled, the create button is not located on the navigation bar anymore, so it is normal that it is not removed.
(I think it works as intended)

**Comment by ayushTNM** [comment]
But doesn't it make more sense if it wasn't a navigation only feature? That we can hide the create button regardless of if it is in the navigation bar or not.

**Comment by inotia00** [comment]
nah.. currently implemented patch can only hide the buttons in the navigation bar.

Other patches not implemented
