### ISSUE TITLE
bug: <title> Video keeps buffering at random even on a good internet connection.

### ISSUE THREAD

**Issue by Ktgt15** [inotia00/ReVanced_Extended#722]
### Type

Error at runtime

### Application

Latest one. 

### Bug description

While playing any video on the app, the video starts buffering every 5-30 seconds. This is not a network issue, every other thing in the app works fine (even while the video is buffering, the comments, the searches, my subscriptions, everything loads instantly). Sometimes it buffers and resumes the video automatically, while many a times, it just buffers endlessly and I'm forced to exit the video and reselect that video and play it again from that time stamp but it starts buffering again. I've tried clearing cache, data but to no avail.
I do have MicroG, Hide Ads, Return Dislike Button, Video Downloader enabled along with some other settings but they all worked perfectly until today. 

### Steps to reproduce

Not a programmer.

### Relevant log output

```shell
Again, not a programmer.
```

### Device Environment

Android 8.0 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by s23ultra512** [comment]
Try to clear your phones cache by connecting it to a tv or a computer, depending on what phone youre using this next method may vary.

1. Connect your phone
2. Power it off
3. Power it on by holding power and volume up
4. Keep holding those buttons down until you see a new window
5. Use volume down button to browse down until you see clear cache partition
6. Select it with power button
7. Use power button again to accept cache clearing
8. Use power button agai  to accept phone restart
9. Once on the homescreen reset your network settings
10. If thats not working then try to swap your simcard to a 2nd slot

**Comment by inotia00** [comment]
You need to include the `protobuf-spoof` patch.
