### ISSUE TITLE
question: <title>: 

### ISSUE THREAD

**Issue by Trufel-l** [inotia00/ReVanced_Extended#724]
### Application

YouTube

### Description

Is it possible to set the theme like in Vanced?
The Vanced theme is more gray.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Exclude `theme` patches and `materialyou` patches
