### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by Lucifepyc** [inotia00/ReVanced_Extended#725]
### Application

YouTube

### Issue

Буфферизация работает первые 2 минуты +-, после видео не грузится. Если в фоне воспроизводить как аудио, всё работает. 18.05.40. Но и другие пользователи 4пда пишут об этой проблеме, со вчерашнего дня у некоторых.

### Patch

Решить проблему буфферизации.

### Motivation

4пда

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by s23ultra512** [comment]
Can you please write in English, if written in a different language they are automatically ignored, and closed.

**Comment by inotia00** [comment]
1. Please use the correct title
2. Please use English

**Comment by Lucifepyc** [comment]
Learn Russian or use google translator

чт, 13 апр. 2023 г., 21:02 inotia00 ***@***.***>:
