### ISSUE TITLE
Alternate video quality

### ISSUE THREAD

**Issue by Adiraj18** [inotia00/ReVanced_Extended#726]
### Application

YouTube

### Issue

Nothing to solve. It just adds another functionality if possible!

### Patch

Let me first explain it.
Suppose my default video quality is 240p. But quality options in a video available are only 144p and 360p. So the algorithm selects the lower quality than the default. The patch will allow users to select the upper quality or the lower quality
![Screenshot_20230413-210109_YouTube](https://user-images.githubusercontent.com/100271014/231812167-04f7f3ef-39d2-4864-b674-bccc125fdef8.png)
This is my default quality.
![Screenshot_20230413-210053_YouTube](https://user-images.githubusercontent.com/100271014/231812513-827d7f70-6338-4304-ad7c-43787199e6b8.png)
And this is the video where only 144p and 360p are available and the patch will make the algorithm select immediate upper quality that is 360p.

### Motivation

This will just help not to select the lower quality than the default.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Adiraj18** [comment]
Other qualities are also available but the patch will only select the IMMEDIATE upper or lower quality

**Comment by inotia00** [comment]
The current method uses a method that selects a lower quality if 240p is not available.

Why not simply select 360p?

I didn't understand the meaning
