### ISSUE TITLE
bug: minimum width like/dislike button looks weird

### ISSUE THREAD

**Issue by RedWhiteNavy** [inotia00/ReVanced_Extended#727]
### Type

Cosmetic

### Application

Youtube v18.14.40

### Bug description

The button layout isn't symmetrical and just looks weird (see the first image)

### Steps to reproduce

Step 1. include 'return-youtube-dislike' and patch
Step 2. go to 'settings' and then 'return youtube dislikes'
Step 3. enable 'Enable Return Youtube Dislike' and make sure 'Compact like button' is enabled
Step 4. watch any video

### Relevant log output

```shell
none needed
```

### Screenshots or videos

First image:
![first image](https://user-images.githubusercontent.com/101016008/231824018-93bb9e58-3ded-4ea6-819a-8a6c74653995.png)
Second image:
![second image](https://user-images.githubusercontent.com/101016008/231824743-ccf0eadd-b7d3-4022-a3a5-a1ed60f52e98.png)

### Solution

I made an improved version by taking a screenshot and editing it (see the second image).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
A bug means that an unintended issue has occurred.

However, this is the intended layout

If you want something like the second screenshot, use the patch-request or suggestion label.
