### ISSUE TITLE
bug: get's stuck after 1 minute 

### ISSUE THREAD

**Issue by Yanonne** [inotia00/ReVanced_Extended#729]
### Type

Other

### Application

18.01.38

### Bug description

After i watch for a minute it get's stuck, i did reinstall, installed the newest version for both the APK and micro manager, tested on both Motorola edge 20 lite and poco X3 oro

### Steps to reproduce

Just watch a video 

### Relevant log output

```shell
Idk how to
```

### Screenshots or videos

![Screenshot_20230413-233452](https://user-images.githubusercontent.com/60784245/231877429-200118d4-24b6-4627-851a-284888b625ab.png)

### Solution

Exit the video and start again, you have to select the seconds again each minute 

### Device Environment

Android 12, and MIUI 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
repatch

**Comment by Yanonne** [comment]
I did it and now it works unless I connect to my Google account, any fix for this? I got your extended version btw if it matters, hope it s gonna get fix soon
