### ISSUE TITLE
feat(patch): Hide Breaking News shelf

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#73]
### Application

YouTube

### Issue

When I surf the new feeds, I found Breaking News but I hate it. Can u make an option to hide it :D

### Patch

![image](https://user-images.githubusercontent.com/70064328/210030699-0c515afe-ce07-421e-adae-d88409aaeeb0.png)

### Motivation

Because it has been added on Revanced

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
already exists
