### ISSUE TITLE
bug: video starts awhile later the video goes black and loads forever 

### ISSUE THREAD

**Issue by marioisgud** [inotia00/ReVanced_Extended#730]
### Type

Error

### Application

YouTube.Vanced.v18.01.38

### Bug description

happens to all the videos I watch 

### Steps to reproduce

I don't know 

### Relevant log output

```shell
idk
```

### Screenshots or videos

![Screenshot_20230413_201644_YouTube Vanced](https://user-images.githubusercontent.com/130717659/231916372-a840bac8-2ca3-412c-abe9-49748b3d1256.jpg)

### Solution

I don't know 

### Device Environment

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
v18.01.38 is an unsupported version

**Comment by marioisgud** [comment]
where do I get that
