### ISSUE TITLE
feat(patch): better PIP options

### ISSUE THREAD

**Issue by XeiDaMoKa** [inotia00/ReVanced_Extended#731]
### Type

Functionality

### Issue

the normal popup doesn't allow us to do almost anything , the newpipe pop-up is ages head.

### Feature

since newpipe i believe is open source , couldn't revanced extended have an option to pick between the normal PIP and newpipes PIP , is much much better , 
allow us to pick any location on the screen , allow us to go back and foward on the video , allow us to change speed , and pick any size , the normal youtube PIP is very limited 

### Motivation

i would like to use one app alone for youtube , i'm using revanced extended for normal usage and newpipe when i need pop up , it takes awhile and its frustrating when i just leave without remember to share to NP 

### Additional context

well i'm just asking because i believe newpipe is open source and their PIP is magnitudes better than youtube's one so it would improve the quality at least for people who like newpipe PIP better but prefer your app to use as youtube

**Comment by sliceanddice9** [comment]
Yes I agree. Better PiP options and even lockscreen/background play options would be fantastic.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
