### ISSUE TITLE
feat(patch): show actual date instead of X days/months/years ago

### ISSUE THREAD

**Issue by nexsych** [inotia00/ReVanced_Extended#732]
### Application

YouTube

### Issue

I literally watched videos that said it was from "1 year ago" and the actual publication date was 1 year and 11 months ago. It had rounded down to the full year. Absolutely ridiculous

### Patch

It'd be great to have an option (a toggle) to see actual publication date or any similar feature to improve this rounding.

### Motivation

I think it's really important to have it and it can save time for checking the date without opening the video

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
