### ISSUE TITLE
feat(patch): disable HDR videos.

### ISSUE THREAD

**Issue by odkrys** [inotia00/ReVanced_Extended#734]
### Application

YouTube

### Issue

Color distortion in HDR on some Android devices.

### Patch

```
root@instance-20220814-1527:~/test# grep -r "getHdrCapabilities" ./youtube-revanced_v18.07.35_2
./youtube-revanced_v18.07.35_2/smali_classes3/aaki.smali:    invoke-virtual {p1}, Landroid/view/Display;->getHdrCapabilities()Landroid/view/Display$HdrCapabilities;
./youtube-revanced_v18.07.35_2/smali/ccu.smali:    invoke-virtual {p0}, Landroid/view/Display;->getHdrCapabilities()Landroid/view/Display$HdrCapabilities;
./youtube-revanced_v18.07.35_2/smali_classes8/yyt.smali:    invoke-virtual {p2}, Landroid/view/Display;->getHdrCapabilities()Landroid/view/Display$HdrCapabilities;
```

 ./youtube-revanced_v18.07.35_2/smali_classes8/yyt.smali

original
```
.method public final bf(ILandroid/view/Display;)Z
    .locals 4

    .line 1
    invoke-virtual {p2}, Landroid/view/Display;->getHdrCapabilities()Landroid/view/Display$HdrCapabilities;

    move-result-object p2

    const/4 v0, 0x0

    if-eqz p2, :cond_1

    .line 2
    invoke-virtual {p2}, Landroid/view/Display$HdrCapabilities;->getSupportedHdrTypes()[I

    move-result-object p2

    .line 3
    array-length v1, p2

    const/4 v2, 0x0

    :goto_0
    if-ge v2, v1, :cond_1

    aget v3, p2, v2

    if-ne v3, p1, :cond_0

    const/4 p1, 0x1

    return p1

    :cond_0
    add-int/lit8 v2, v2, 0x1

    goto :goto_0

    :cond_1
    return v0
.end method
```

patched
```
.method public final bf(ILandroid/view/Display;)Z
    .locals 4

    const/4 v0, 0x0

    return v0
.end method
```

### Motivation

My Galaxy tablet handles HDR just fine, but other Lenovo tablet has issue with HDR being distorted when using the full landscape screen.
It would be better if app provided an option to turn HDR video playback off and on. I've often seen issues with HDR playback from other users as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by odkrys** [comment]
https://github.com/revanced/revanced-patches/issues/570

**Comment by inotia00** [comment]
Is the attached smali the code when it was implemented?

And can you elaborate more on what this patch does?

**Comment by odkrys** [comment]
Removed the part that checks the device's hdr playback capability. Below is the patched code.
It loads as sdr video instead of hdr video.

**Comment by odkrys** [comment]
Lenovo tablet has completely broken hdr playback on Android 12. It is a feast of red color when the screen is horizontal.

https://imgur.com/a/A5eYs9L

**Comment by odkrys** [comment]
I looked into this a bit more. Deleting the entire code felt like it would make it difficult to add feature.
Changing one line is enough.
Just replace the value "const/4 p1, 0x1" with "const/4 p1, 0x0" in the original code.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.173.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.2)
