### ISSUE TITLE
Revanced App Not Opening after new update to v18.14.40

### ISSUE THREAD

**Issue by psrocksstill** [inotia00/ReVanced_Extended#735]
### Type

Other

### Application

![Screenshot_20230414-182747_Nova7](https://user-images.githubusercontent.com/130269737/232020570-747db0f6-f984-4400-83b7-b87f7e23c59e.png)

Revanced latest update not opening/keep on crashing

### Bug description

Apps keep not opening/crashing after updating to latest update in Magisk v18.14.40

### Steps to reproduce

Just Open the App

### Relevant log output

```shell
https://paste.crdroid.net/LsqfPi
```

### Screenshots or videos

![Screenshot_20230414-182747_Nova7](https://user-images.githubusercontent.com/130269737/232020927-3b5e3003-866c-472e-bd43-74c0cdfb35cf.png)

### Additional context

Its working before but after the update its not opening anymore

### Device Environment

Poco X3 Pro running on crdroid 9.3 android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
There is no Magisk method in the [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android)) 
Proceed with the patch according to the method recommended in the documentation.
