### ISSUE TITLE
question: why hdr video colors are washed off? 

### ISSUE THREAD

**Issue by rsaurav12** [inotia00/ReVanced_Extended#736]
### Application

YouTube

### Description

https://user-images.githubusercontent.com/53332518/232075985-8c184e2c-1420-4c55-8e59-046773bbf55e.mp4

In miui i can fixed it by enabling "Disable HW overlays" in developer settings

 but is there any  other way to fix it? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
To make it easier to understand..
HDR video filters follow the device manufacturer's policy.

Certain manufacturers' ROMs force an HDR filter when playing HDR videos.

This cannot be disabled in the YouTube client

You need to disable restrictions in the manufacturer rom you are using

If your manufacturer's ROM doesn't provide the ability to disable the HDR video filter, the only way is to use a custom ROM.
