### ISSUE TITLE
Revancify Termux?

### ISSUE THREAD

**Issue by mysticmac3** [inotia00/ReVanced_Extended#737]
### Application

YouTube

### Description

Hi what is revancify Termux?  Currently i am using official revanced manager and using Inotia00 patches and downloading YouTube apk from apk mirror and patching manually to be updated,i see a guide for revancify termux,is this better than the current process? I am looking for a way to keep my revanced extended YouTube updated automatically without manually patching it every time, please guide is revancify is the right way or does it make things better?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Revancify is similar to ReVanced Manager

Every time there is an update, you have to go through the patch manually.

Revancify differs from ReVanced Manager in the following ways:

1. Faster patching speed

2. Remove unnecessary libraries
- When patched through ReVanced Manager: About 140MB
- When patched via Revancify: about 80MB

3. You can customize `options.toml`
- Through this, you can change the custom branding name, custom video speed value, theme color value in dark mode, old layout version, etc.

4. Signing key is not changed even after reinstallation

5. You do not need to manually download the apk file from APKMirror
: Revancify automatically downloads the recommended version when starting a patch.
