### ISSUE TITLE
No Download Button in video player

### ISSUE THREAD

**Issue by TarikSalkovicHTL** [inotia00/ReVanced_Extended#738]
### Application

YouTube

### Description

So I reinstalled ReVanced Extended and updated it to Youtube Version 18.14.40. After installing the Patch all the options in the Video Player were gone, including the Download Button for the custom downloader.

![Player ReVanced Extended](https://user-images.githubusercontent.com/98904283/232146176-841f8b7a-6627-46e4-aa24-f0aa6a51d558.jpg)

Is this some kind of bug or are some of my Patches a problem?

![Patches ReVanced Extended](https://user-images.githubusercontent.com/98904283/232146521-790b54e8-7d82-478f-9271-d213f1b54b03.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Include `Overlay Button` patch
