### ISSUE TITLE
question: No End Screen Cards

### ISSUE THREAD

**Issue by kevinr99089** [inotia00/ReVanced_Extended#739]
### Application

YouTube

### Description

After each update of Extended, the End screen Card is not displayed anymore, even though the options are activated.
Sometimes, the option works only once, and when I restart the application, it does not work anymore.
Sorry, I use the application in French.
![Picsart_23-04-15_01-40-30-525](https://user-images.githubusercontent.com/93716347/232171548-7c4e0853-bc05-4cde-8ae8-0bbbf8f04423.jpg)
![Picsart_23-04-15_01-41-29-469](https://user-images.githubusercontent.com/93716347/232171551-6f80fe71-ba51-4776-b32d-b328f7a7af2f.jpg)
![Picsart_23-04-15_01-42-41-841](https://user-images.githubusercontent.com/93716347/232171553-8bcca985-44bc-42f1-b38a-a5abbb1b550e.jpg)
Ps: I'm the one who added the question marks to the End-screen location.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a side effect of the `protobuf-spoof` patch https://github.com/inotia00/ReVanced_Extended/issues/640
