### ISSUE TITLE
How about if u move all your patches to the orginal Revanced

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#74]
### Application

YouTube

### Description

Dear sir, I love all of your patches but how about if u move all your patches to the orginal Revanced then focus on the original
version because some patches in the orginal you don't have and your patches don't have in the original

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
After about 4 months of improvement, rvx's code has been completely rebased from the code used in the official revanced-patches.

Therefore migration to official revanced-patches is not possible.
