### ISSUE TITLE
question: YouTube for Android TV: 

### ISSUE THREAD

**Issue by r0br0y7** [inotia00/ReVanced_Extended#742]
### Application

YouTube

### Description

Will the ReVanced Manager work if I try to patch YouTube for Android TV apk file or do we have a separate ReVanced Manager for it or none at this time?

Thank you ReVanced Community for allowing us to enjoy ad-free YouTube streaming!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
ReVanced and ReVanced Extended do not support Android TV

Similarly, advertisements that are exposed when casting are not blocked.

Use other YouTube clients for Android TV

**Comment by r0br0y7** [comment]
Thank you Sir inotia00. I am currently using SmartTube Next but free movies in YouTube Movies & TV doesn't play unlike in ReVanced Youtube but I can live with it. Thank you by the way on resolving the issue with videos stopping after a minute by enabling the protobuf-spoof patch in ReVanced Manager and disabling cloud messaging in vanced micro g settings.
