### ISSUE TITLE
question: no root install on familylink device

### ISSUE THREAD

**Issue by MikeKOD** [inotia00/ReVanced_Extended#743]
### Application

YouTube

### Description

Good morning, I installed the app on my son's device, controlled by family link (parental control), I can install microg and install it, but when opening YouTube it crashes.  how can i solve?  Has this ever happened to you?  realme 7i device no root android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Current Vanced MicroG does not support Family Link

Presumably, that is the reason

**Comment by MikeKOD** [comment]
until yesterday it went with vanced...

**Comment by inotia00** [comment]
no plans to fix
