### ISSUE TITLE
feat(patch): Remove "White circle overlay" when tapping (rewind/ffw)

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#745]
### Application

YouTube

### Issue

https://github.com/inotia00/ReVanced_Extended/issues/258#issuecomment-1502481262

![231020175-70474257-3736-4ab3-b5d4-c8dc9f5a45bf](https://user-images.githubusercontent.com/73917917/232227140-a3e03932-93be-4e29-8021-6b9573d235b3.png)

Referring to above issue I would very much like to see this white overlay/Fog removed.

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.168.38

**Comment by anyujinie** [comment]
Thank you very much!
