### ISSUE TITLE
Video keeps on buffering. 

### ISSUE THREAD

**Issue by Abhists** [inotia00/ReVanced_Extended#746]
While any video on vanced (18.01.38), in between video starts to buffer even on good internet connection, immediately when I play another video it goes fine.

**Comment by inotia00** [comment]
v18.01.38 is an unsupported version

**Comment by Abhists** [comment]
> v18.01.38 is an unsupported version
Which is the most stable and supported version, I can use?

**Comment by inotia00** [comment]
The currently supported versions of ReVanced Extended are listed below:
v18.06.41
v18.07.35
v18.08.39
v18.09.39
v18.10.37
v18.11.36
v18.12.35
v18.13.38
v18.14.40

And this is the repo of ReVanced Extended, not the repo of Vanced
