### ISSUE TITLE
question: <title>: tap no have live chat?

### ISSUE THREAD

**Issue by Lemoma1272** [inotia00/ReVanced_Extended#747]
### Application

YouTube

### Description

Galaxy tap s8+ used
Fullscreen mode no have live chat button.
I did all setting off but i cant find it
Its bug?

Same ver. Note20ultra work
Only tap not work
![Screenshot_20230416_025912_YouTube](https://user-images.githubusercontent.com/130861945/232246992-82eb6b1e-45df-4424-ad1f-fc6f07e8f4bc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![NEW_LAYOUT](https://user-images.githubusercontent.com/108592928/232250799-f398316d-1e85-42fc-8f83-2a90f878099d.png)
Google has moved the live chat button to the button container in the new layout. (A/B testing)

However, the button container is not shown in the tablet layout, so the live chat button is not visible.

It is part of the new layout, so this is normal

You can forcibly disable these A/B tests via `Enable old layout`

**Comment by odkrys** [comment]
The live chat button does not appear on tablets even when "Enable old layout" is enabled. Currently there seems to be no way. That's a bit inconvenient.

**Comment by odkrys** [comment]
You probably get different results with A/B testing. I don't see the live chat button on the youtube app either.

title / autoplay / chromecast / closed caption / settings
