### ISSUE TITLE
feat(patch): Color edit for more than the video progress bar

### ISSUE THREAD

**Issue by woful25** [inotia00/ReVanced_Extended#748]
### Application

YouTube

### Issue

not an issue just a suggestion for color changing settings

### Patch

Can you please make the color editing go to all the originally red colored entities instead of just the video progress bar?
Like the bar that shows on already watched video thumbnail & subscribe butten and such things....

### Motivation

Only Beauty value

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.173.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.2)
