### ISSUE TITLE
Remove these 2 features

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#749]
### Application

YouTube

### Description

![Screenshot_20230416_000729_app rvx android youtube_edit_276750145378601](https://user-images.githubusercontent.com/107951133/232255241-fa85db58-f452-43ea-a539-842547c1f80a.jpg)
In the latest release ( refactor(default-video-quality): apply the official ReVanced commit)
This mean that 2 settings is useless now as there have been replaced by Revanced commit (change default video speed and quality inside the settings menu)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![revanced](https://user-images.githubusercontent.com/108592928/232260333-e63e1ef6-cd29-4f1a-82db-e6904f7330b2.png)
'Enable save video speed'(Remember video speed changes) and 'Enable save video quality'(Remember video quality changes) settings still exist in official ReVanced
