### ISSUE TITLE
bug: YT Music - amoled patch changes other areas to black color besides the flyout panel

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#750]
![photo_2023-04-16_11-10-37](https://user-images.githubusercontent.com/54460494/232266484-e9108961-327f-4bf1-be84-193dee605eb4.jpg)
![photo_2023-04-16_11-10-43](https://user-images.githubusercontent.com/54460494/232266486-8fd80f03-648e-4d14-bbf5-7e199317cbe8.jpg)
Looks like amoled patch of YT Music hid the overlays of some buttons in the Explore tab. I think it's better to keep this gray overlay to highlight the buttons.

**Comment by inotia00** [comment]
The description of the current `amoled` patch is as follows:
Applies pure black theme in flyout panels.

Currently, the amoled patch is applied only to flyout panels.

**Comment by buiducanh142qn** [comment]
Sorry idk. But after I apply revanced-patches v2.168.38, my YT Music Explore tab shows like this.

**Comment by inotia00** [comment]
bruh it's bug

**Comment by inotia00** [comment]
Sorry I didn't read the content properly as I was preparing for a new release (v2.168.40)

This is an unintended part, so it's a bug

I'll either edit the description of the patch or make sure the theme isn't applied to that area.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.42](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.42)
