### ISSUE TITLE
suggestuon: Editing labels of this 2 settings 

### ISSUE THREAD

**Issue by Mohammedibrahim15** [inotia00/ReVanced_Extended#751]
### Application

YouTube

### Description

![Screenshot_20230416_105430_app rvx android youtube_edit_281960223250202](https://user-images.githubusercontent.com/130897201/232287936-760498b9-cbca-44ff-8347-c2d30c4e7fcd.jpg)
![231263202-5e4d8e43-5883-409c-b5be-6a2a106c824f_edit_282029790473629](https://user-images.githubusercontent.com/130897201/232288002-fe1d812f-c6b1-45c9-bba2-fe55e06d2910.png)
Please can you replace "default video quality wifi" and "default video quality cellular " in revanced extended to be matched with labels in official revanced

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.42](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.42)
