### ISSUE TITLE
Tap to seek bar in shorts isn't showing or working

### ISSUE THREAD

**Issue by ForBackup2** [inotia00/ReVanced_Extended#752]
### Type

Error at runtime

### Application

YouTube Revanced Extended version 18.13.37 non-root

### Bug description

I think after the update of 18.13.37, the tap to seek bar is not working anymore. Now I cannot seek through any video in shorts anymore.

### Steps to reproduce

Step 1. Open YouTube Ravanced Extended app
Step 2. Play a video in Shorts

### Relevant log output

```shell
I don't have any
```

### Screenshots or videos

![IMG_20230416_161110](https://user-images.githubusercontent.com/97826495/232294654-1bfc1582-841f-4fd1-9209-12055f1aee23.jpg)

### Device Environment

VIVO Y11.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anyujinie** [comment]
I don't even have a seekbar. It only shows with YT iOS app...
