### ISSUE TITLE
Remove killerGuru from admin role

### ISSUE THREAD

**Issue by Evoprism** [inotia00/ReVanced_Extended#753]
He does not deserve admin role and is literally the worst. Got a terrible ego and posts revanced extended as rbmods exclusives to his own channels

**Comment by selfmusing** [comment]
+1

**Comment by Evoprism** [comment]
![Screenshot_20230416-161639_Nekogram](https://user-images.githubusercontent.com/16971902/232319251-003094bf-36c3-4ae8-9fa9-d3989b1ab2c6.png)
Posts apps to his own devuploads without changing anything thereby earning money from other peoples work

**Comment by gm1827** [comment]
+1

**Comment by umair786155** [comment]
+1

**Comment by selfmusing** [comment]
![Screenshot_20230416-224725_Nekogram_X](https://user-images.githubusercontent.com/109387456/232329454-a24f0524-12dc-457f-b32e-65f6dd937bbd.png)


WTF HE'S EVEN DOING : https://t.me/ReVancedGuru/331

**Comment by MondayNitro** [comment]
> He does not deserve admin role and is literally the worst. Got a terrible ego and posts revanced extended as rbmods exclusives to his own channels

this issue does not exist in revanced extended app, but seeing that its still open after 4 hrs, i think inotia is giving it a serious thought

**Comment by inotia00** [comment]
wrong place to report

**Comment by HoriKyoukosimp** [comment]
Why is there an github issue about this 😭
@shion_yorigami on tg
