### ISSUE TITLE
bug: Hide general ad and Hide video ads not working

### ISSUE THREAD

**Issue by ykitt** [inotia00/ReVanced_Extended#754]
### Type

Error while patching

### Application

Youtube v.18.05.40

### Bug description

I followed everything in the guide to do the patch but when I install it and go to patches information it says both of Hide ads where excluded and I'm 100% sure I have both of them turned on when doing the patch 

### Steps to reproduce

Include hide-video-ad and hide-general-ad and it just ignores it

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Applied custom-video-speed
Applied enable-wide-searchbar
Applied hide-autoplay-button
Applied hide-cast-button
Applied hide-create-button
Applied hide-crowdfunding-box
Applied hide-email-address
Applied hide-endscreen-cards
Applied hide-info-cards
Applied hide-seekbar
Applied hide-shorts-button
Applied microg-support
Failed to apply return-youtube-dislike: Failed to resolve TextComponentSpecObjectFingerprint
Failed to apply sponsorblock: 'sponsorblock' depends on 'sponsorblock-bytecode-patch' but the following error was raised: 'sponsorblock-bytecode-patch' depends on 'override-speed-hook' but the following error was raised: Failed to resolve VideoSpeedParentFingerprint
Applied swipe-controls
Applied theme
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
Installing patched file using nonroot method
Installed!
```

### Screenshots or videos

![Screenshot_20230416_122411_YouTube](https://user-images.githubusercontent.com/130921350/232326477-cf9906e1-8bfe-4f84-bd8b-73ad86cefe4c.jpg)

### Additional context

I've donde the whole process of installing everything again, downloading everything again and selecting Hide ad

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MondayNitro** [comment]
bro this version is not supported, why are you using it? some patches fail in ths version while patching.

**Comment by inotia00** [comment]
v18.05.40 is non support version
