### ISSUE TITLE
bug: manage all history no work

### ISSUE THREAD

**Issue by kevinr99089** [inotia00/ReVanced_Extended#755]
### Type

Other

### Application

Youtube: 18.14.41

### Bug description

When I click on Manage all History, YouTube asks me if I should open it with Google Play Service, or if I should open it with Vanced MicroG, in both cases, it does not open the tab

### Steps to reproduce

Open the app, go to settings, click on manage all history, the app doesn't crash, but it doesn't open Manage All History, and when I click on that button, Android asks me if I should open it with Google Play Service or if I should open it with Vanced MicroG (which is not the case with YT Music).

### Screenshots or videos

https://user-images.githubusercontent.com/93716347/232332135-cd11401d-530a-48b0-84ef-b71a35328594.mp4

### Additional context

I don't know if it's a patch that fixes this, but here are the patches I didn't apply:
-Swipe Control
-Hide Channel Watermark
-Disable Landscape Mode
-Disable haptic Feedback
-Custom SeekBar Color
-Protobuf Spoof
-Hide Double Tap Overlay Filter

### Device Environment

Samsung Galaxy S23, Android 13, One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/319
