### ISSUE TITLE
feat(patch): disable auto loop in shorts player

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#756]
### Application

YouTube

### Issue

add a patch that allows a shorts video to be played only once, so if the user wants to play it again, he can tap the screen to do so

### Patch

add a patch that allows a shorts video to be played only once, so if the user wants to play it again, he can tap the screen to do so.

### Motivation

if you leave the screen as is, the shorts player keeps playing the current video infinitely. if its just once, it will be great

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
As a result, it is almost identical to this patch-request https://github.com/inotia00/ReVanced_Extended/issues/675
