### ISSUE TITLE
change dark theme color feat(patch): 

### ISSUE THREAD

**Issue by Mefisst** [inotia00/ReVanced_Extended#757]
### Application

YouTube

### Issue

YouTube Vanced has a dark theme with a dark gray color, while reVanced has a black one.  can i change it to dark grey?

### Patch

change the dark theme color to dark gray, as it was in Vanced

### Motivation

dark gray color is more pleasing to the human eye.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
You can do this by following
- exclude `theme` patch
- include `enable old layout` patch
- turn on `Enable old layout`

**Comment by Mefisst** [comment]
can't find it, it's still black.

**Comment by inotia00** [comment]
did you exclude `theme` patch?

**Comment by Mefisst** [comment]
> You can do this by following
> 
> * exclude `theme` patch
> * include `enable old layout` patch
> * turn on `Enable old layout`

can't find it, it's still black.

**Comment by inotia00** [comment]
doesn't exist in settings
You should only exclude `theme` patches from the patching process.

Read the [documentation](https://github.com/inotia00/revanced-documentation/wiki/Options-Information-about-the-patch#if-you-want-only-black-theme)  for details

**Comment by Mefisst** [comment]
> 

How?  I included the old interface, maybe that's not it

**Comment by inotia00** [comment]
![builder](https://user-images.githubusercontent.com/108592928/232348798-6d7ebfeb-d604-4fed-8190-e5ea93b30695.png)

exclude `theme` patch

**Comment by Mefisst** [comment]
> ![builder](https://user-images.githubusercontent.com/108592928/232348798-6d7ebfeb-d604-4fed-8190-e5ea93b30695.png)
> 
> exclude `theme` patch

I don't have this section in the application

**Comment by Mefisst** [comment]
> > ![builder](https://user-images.githubusercontent.com/108592928/232348798-6d7ebfeb-d604-4fed-8190-e5ea93b30695.png)
> > exclude `theme` patch
> 
> I don't have this section in the application

Setting -> ReVanced Extended?
