### ISSUE TITLE
How to fix audio keep breaking randomly during playtime?

### ISSUE THREAD

**Issue by BrokeAsian101** [inotia00/ReVanced_Extended#758]
### Application

YouTube

### Description

Audio keep silencing at random when playing video 

reVanced Youtube Extended v18.14.41

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please attach a patch list or your settings
