### ISSUE TITLE
bug: Overlay filter sometimes doesn't work anymore

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#759]
### Type

Error while patching

### Application

Version 18.14.41 non-root

Yesterday I patched to latest version and noticed today that the overlay filter (dark filter) occasionally doesn't appear to be working. 
You can clearly see it here:
https://streamable.com/bypgch

When I pause/tap the video the dark filter appears...

**Comment by inotia00** [comment]
![k](https://user-images.githubusercontent.com/108592928/232346854-99598c87-0946-4283-8499-e30639e558dd.png)

**Comment by anyujinie** [comment]
![Screenshot_20230417-004107938 (1).png](https://user-images.githubusercontent.com/73917917/232346942-a681a475-12e4-4483-b2e5-e5dd4c725439.png)


Yes I have that already enabled. That's why I stated that it _sometimes/occasionally_ breaks and the dark filter shows.

**Comment by inotia00** [comment]
then no idea

**Comment by anyujinie** [comment]
😔

I have removed the previous and next buttons, and since a long while this play/pause button is also acting up and vanishes from the player. Only minimizing/maximizing the player and tapping around a few times makes it appear again.
![Screenshot_20230417-011342363 (1).png](https://user-images.githubusercontent.com/73917917/232348713-d6bd0e8b-2cb9-4ac0-a849-82efe46d97b8.png)

**Comment by inotia00** [comment]
If a fix is possible, please open a PR

**Comment by anyujinie** [comment]
Ok now the dark filter appears on every video once I tap at end of seekbar. Seems like this patch for some reason is completely broken now. I tried closing the app etc but still the same.

I didn't even change any settings before updating yesterday

**Comment by anyujinie** [comment]
Tapping near the end of the seekbar seems to trigger the patch breaking. 
Not sure:
https://streamable.com/15n8fo

**Comment by inotia00** [comment]
There is no plan to fix
(It is not reproducible, and it is not a feature that developers mainly use)
