### ISSUE TITLE
bug: <Dislike Button>

### ISSUE THREAD

**Issue by TheGoldenSun** [inotia00/ReVanced_Extended#76]
### Type

Other

### Application

YouTube version: 17.49.37

### Bug description

![Screenshot_20221229_223102](https://user-images.githubusercontent.com/104534608/210067932-85456e2b-b95f-4130-ac1e-84edb963d076.png)

In this screenshot here I couldn't see the full result of dislikes due to those numbers only showing me three dots for that particular video, when I watch another video it shows me -1 like and 1- dislike which is odd because I never seen something like that before.

### Steps to reproduce

Step 1 improve dislike-button-patch from how RYD did through his extension.

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20221229_223102](https://user-images.githubusercontent.com/104534608/210067964-be9f4384-e5bf-41b3-9969-158a6de3a0b0.png)

![Screenshot_20221230_070259](https://user-images.githubusercontent.com/104534608/210068392-729f3504-cc0c-44a2-af43-381f01fbaa1d.png)
![Screenshot_20221230_070318](https://user-images.githubusercontent.com/104534608/210068397-de721e76-d87d-410c-835e-7da8256359ec.png)

### Solution

Enhance dislike button's API current version 3.0.0.6 from @anarios for revanced extended.

### Additional context

I've been wondering about why am I the only one seeing -1 like and -1 dislike whilst three dots on another video that's different only has three dots according to the first screenshot I sent? 

### Device Environment

Android 12

Samsung Galaxy a12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 0xrxL** [comment]
This is a bug of stock YouTube, which cause a stuck of the layout on the same button size and preventing the view of the new (and more long as in this case) buttons name.

You can reproduce this bug by clicking on Save button.

**Comment by inotia00** [comment]
The first issue is the stock YouTube issue
1. Play a video from stock YouTube
2. Add video to playlist
3. The first issue is reproduced

first issue is one that Google needs to fix

second issue has been fixed in recent releases
