### ISSUE TITLE
скорость видео по-умолчанию

### ISSUE THREAD

**Issue by evd316** [inotia00/ReVanced_Extended#760]
### Application

YouTube

### Description

Привет. Можно добавить в настройки пункт про скорость видео по-умолчанию как было в Vanced чтобы все видео открывались сразу на скорости, например, ×1.25?
И куда делись настройки Ad sponsor block?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
read the [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android))

**Comment by evd316** [comment]
я не понимаю по англ.
