### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by viveksharma55** [inotia00/ReVanced_Extended#761]
### Application

YouTube

### Issue

Dark mode is not working it's showing light dark like grey 

### Patch

Dark patch 

### Motivation

It's feel good on eye and look better than grey

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Hennadz** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/757
