### ISSUE TITLE
bug: The "borderless" mode stops working

### ISSUE THREAD

**Issue by Ilya-Ezhik** [inotia00/ReVanced_Extended#763]
### Type

Error at runtime

### Application

YouTube ReVanced 18.14.41 (patches-2.168.38)

### Bug description

The “borderless video" mode stops working - it is impossible to melt to the full screen without margins. For a shirt time can help only a complete cleaning of the cache and application data.

### Steps to reproduce

Open the video in full screen and try to stretch the video with fingers

### Relevant log output

```shell
No logs
```

### Screenshots or videos

https://user-images.githubusercontent.com/130345901/232499825-57e479cd-1e3f-4f63-889e-279d46de5b3d.mp4

https://user-images.githubusercontent.com/130345901/232500159-7ac48b20-1e50-4335-8d53-2e4971bca206.mp4

### Device Environment

Samsung Galaxy A22 5G, Android 13, One UI Core 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
what is `borderless video`?
please attach screenshot

**Comment by inotia00** [comment]
YouTube issue, not Extended issue

**Comment by Ilya-Ezhik** [comment]
> YouTube issue, not Extended issue

And what to do about it? Constantly clean the cache and data?

**Comment by jhon1282** [comment]
It happens to me sometimes, but just zooming out to PiP and back to full screen and the problem is solved

**Comment by jhon1282** [comment]
Sorry, looks like a bug with this version of YouTube, try a clean reinstall, maybe it works

**Comment by Ilya-Ezhik** [comment]
> clean reinstall, maybe it works

No, none of that helped. Let's wait, maybe someone will fix the problem
