### ISSUE TITLE
bug: Potential bug in Hide Like/Dislike button appearance

### ISSUE THREAD

**Issue by s23ultra512** [inotia00/ReVanced_Extended#765]
### Type

Cosmetic

### Application

YouTube: v18.14.41
Patches: v2.168.40

### Bug description

Potential bug:

Hide Like button: (Keep Dislike button enabled)
![Screenshot_20230417_213747_ReVanced Extended](https://user-images.githubusercontent.com/128295857/232581740-5e592a41-4bbc-4cf1-a1c0-a5146c9c264f.jpg)

Hide Dislike button: (Keep Like button enabled)
![Screenshot_20230417_213626_ReVanced Extended](https://user-images.githubusercontent.com/128295857/232581950-53ff45cb-c1df-4e15-a800-c57a27468128.jpg)

### Steps to reproduce

Explanation:

While enabling Hide Dislike button and keeping Hide Like button disabled it will hide both buttons, Im not sure if this is intended or not, or if this is how YouTube works, or if this is an issue on their end.

### Relevant log output

```shell
I dont have a computer to gather a log.
```

### Device Environment

Galaxy S23 Ultra, OneUI 5.1, Android 13.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In the new layout, the like button and dislike button are integrated into one.

Therefore, it is impossible to remove only one of the two.
