### ISSUE TITLE
feat(patch): add shortcut to share to a specific app (work around the unclear share menu)

### ISSUE THREAD

**Issue by Retardium** [inotia00/ReVanced_Extended#767]
### Application

YouTube

### Issue

The problem is the terribly bad share menu that is always unsorted and especially sorted differently every time you open it again.

I use the YT app mainly to search for videos and share them to my Kodi box (via Yatse or Kore app).
It's very inconvenient at the moment, having to constantly search for the right app in the share menu.

Video of the problem: https://youtu.be/GCrP77M7Z8k
I know - it's an extreme example -  I have too many apps installed. 😅

### Patch

I imagine that the patch would add another entry in the hamburger menu of a particular video that will send the video directly to an app specified in the settings of the Revanced Extended settings (e.g. I would set the Yatse app).

There could also be a patch which would add an alternative share button with the same function below the video close to the default share button.

How it could look like:
![custom_burger_menu_and_share_button](https://user-images.githubusercontent.com/32235655/232631946-9c02cea2-ef60-48a7-8a34-838253e209f5.png)

### Motivation

It could be a workaround for people which share videos often to the same app and are annoyed by the ridiculous share menu (see issue #439).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
