### ISSUE TITLE
question: <title>: videos stop playing

### ISSUE THREAD

**Issue by Eddyzo** [inotia00/ReVanced_Extended#768]
### Application

YouTube

### Description

Videos stop playing from playlist is it normal ?
Internet connection is stable 
Happens in all videos 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by T1nG3R** [comment]
Seems like it happens on ReVanced General too

**Comment by inotia00** [comment]
This is an outdated issue (already fixed)
Please re-patch with latest resources

**Comment by mattdd50** [comment]
I uninstalled old version, re-patched to latest version (v2.168.40) and reinstalled and I am still having this issue. It started this morning.

**Comment by inotia00** [comment]
check `Enable protobuf spoof` status

![protobuf](https://user-images.githubusercontent.com/108592928/232783539-40ae677d-525b-47fb-a9d3-14acbdecf237.png)

Settungs > ReVanced Extended > Miscellaneous > Enable protobuf spoof

**Comment by mattdd50** [comment]
> check `Enable protobuf spoof` status
> 
> ![protobuf](https://user-images.githubusercontent.com/108592928/232783539-40ae677d-525b-47fb-a9d3-14acbdecf237.png)
> 
> Settungs > ReVanced Extended > Miscellaneous > Enable protobuf spoof

That was already enabled when I checked but it now seems to be working. Thanks
