### ISSUE TITLE
Plantare charge after max 60s

### ISSUE THREAD

**Issue by G4M37R0N** [inotia00/ReVanced_Extended#769]
### Type

Other

### Application

YouTube Revanced 18.13.36

### Bug description

Tried to view videos but suddenly they go to loading and keep there. Tried to restart phone, deleted cache and repach but bug still there

### Steps to reproduce

Step 1 open include block of ads, swipe controls, hide storied & create, and player menu staff.
Step 2 reopen app
Step 3 play video

### Relevant log output

```shell
No output
```

### Screenshots or videos

![Screenshot_2023-04-18-15-34-58-892_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779146-40d6ce6a-60f5-426c-ad85-907ee19127c4.jpg)
![Screenshot_2023-04-18-15-34-56-148_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779154-e3cdab74-02d0-42e7-b6dc-c6f8cb13d8c1.jpg)
![Screenshot_2023-04-18-15-34-52-017_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779159-77f3b856-5b06-4c2c-8b67-80b5da5478e6.jpg)
![Screenshot_2023-04-18-15-34-46-707_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779163-f6cebee1-ada4-4eb3-8dcb-c271b38e7622.jpg)
![Screenshot_2023-04-18-15-34-22-594_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779165-859f10b5-e776-47b3-961c-434949ca52b6.jpg)
![Screenshot_2023-04-18-15-34-06-192_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779168-89f2ce90-4481-4f42-b7eb-ab57060eff77.jpg)
![Screenshot_2023-04-18-15-33-45-953_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779173-ee355a64-53c7-4c38-9ae9-7b207f0c613e.jpg)
![Screenshot_2023-04-18-15-33-49-054_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779177-6c700fbc-bb74-45d5-9063-665083314734.jpg)
![Screenshot_2023-04-18-15-33-51-582_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779181-c3734463-23b1-4ec4-95cb-39b4dad3db5f.jpg)
![Screenshot_2023-04-18-15-33-53-713_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779183-8337406d-0e3c-49aa-910c-a92248f56436.jpg)
![Screenshot_2023-04-18-15-34-18-833_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779188-9d743c69-29b8-464f-8685-798aa5014b46.jpg)
![Screenshot_2023-04-18-15-34-17-215_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779191-1421fdac-bdd2-4729-a9da-ecdc5aa8b1cf.jpg)
![Screenshot_2023-04-18-15-34-09-557_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779197-3d5ae951-95e3-496c-b9e6-d8f09e97a8c3.jpg)
![Screenshot_2023-04-18-15-34-24-950_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779200-7e925590-ee88-467d-a11d-b3c39680c21e.jpg)
![Screenshot_2023-04-18-15-34-34-423_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779209-a88f9d71-6860-44bf-a427-52f58041e4a3.jpg)
![Screenshot_2023-04-18-15-34-41-982_app rvx android youtube](https://user-images.githubusercontent.com/76266405/232779214-1ac82155-cf80-4630-9f04-36bb4594b403.jpg)

### Device Environment

Android 10 miui 12.0.14.p

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
repatch with latest resources
