### ISSUE TITLE
feat(patch): hide shorts ads

### ISSUE THREAD

**Issue by barraIhsan** [inotia00/ReVanced_Extended#77]
### Application

YouTube

### Issue

So when you scroll through shorts, sometimes you got a video ad (a whole video). And it's kinda annoying

### Patch

Remove the shorts ads

### Motivation

So that people can scroll through the shorts without any ads

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
