### ISSUE TITLE
question: inquiry about patches 

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#770]
### Application

YouTube

### Description

Do you happen to have patches for Android 6 & 7 i.e; `YouTube v17.34.36`

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
nah.. I drop support Android 6 & 7 (YT v17.34.36)
