### ISSUE TITLE
Share Button Who Disappeared 

### ISSUE THREAD

**Issue by JuJust123** [inotia00/ReVanced_Extended#773]
### Type

Error while patching

### Application

Last Version of YouTube ReVanced Extended in French

### Bug description

No matter whether or not I enable the appearance of the share button below the video in the settings, the button does not appear. 

### Steps to reproduce

Nothing special sorry

### Relevant log output

```shell
I don't know how to do that
```

### Device Environment

Android 13 One Plus Nord CE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I'm really sorry, but I don't plan to fix the issue with the button container

It's not reproducible, and I'm tired from too much refactoring.

**Comment by JuJust123** [comment]
Ok, that's not very important afterall because we have the copy link button
🤷
So don't worry, I'm really happy about this version despite this !
Thank you for all ^^
