### ISSUE TITLE
Automatic activation of subtitles does not work 

### ISSUE THREAD

**Issue by JuJust123** [inotia00/ReVanced_Extended#774]
### Type

Error while patching

### Application

YouTube ReVanced Extended last version

### Bug description

No matter if the option is enabled or disabled, the subtitles do not play automatically when I play a video after restarting the application. 

### Steps to reproduce

Nothing Special 

### Relevant log output

```shell
I don't know how to do that
```

### Device Environment

Android 13 OnePlus Notd CE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
`Hide auto caption` disables the automatically appearing subtitles, but does not forcibly activate them.

A patch to force automatic subtitles to be enabled has not been implemented

**Comment by JuJust123** [comment]
Oh ok ... So that's an error of traduction (i have the french version)
