### ISSUE TITLE
bug: Playing video in split screen bug 

### ISSUE THREAD

**Issue by rsaurav12** [inotia00/ReVanced_Extended#775]
### Type

Error while patching

### Application

YouTube 18.14.41

### Bug description

Videos hide when playing in split screen 

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

https://user-images.githubusercontent.com/53332518/232858591-95a5cdca-e68d-479e-974f-cc96306e181f.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
YouTube's issue, not ReVanced Extended's issue

**Comment by rsaurav12** [comment]
Ok thanks
