### ISSUE TITLE
question: hide video speed in timestamp: 

### ISSUE THREAD

**Issue by itsmenewbie03** [inotia00/ReVanced_Extended#776]
### Application

YouTube

### Description

Is there a way I could hide this speed indicator here?
![Screenshot_20230419_065210](https://user-images.githubusercontent.com/89230263/232922008-ca5f9fc4-010a-4e8d-ad6e-53fa4d35d32a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Settings > ReVanced Extended > Seekbar > Enable timestamp speed

**Comment by itsmenewbie03** [comment]
> Settings > ReVanced Extended > Seekbar > Enable timestamp speed

Thank You ❤️
