### ISSUE TITLE
bug: Sponsorblock does not skip segments in background play with playlists on videos played during background play

### ISSUE THREAD

**Issue by sezonis** [inotia00/ReVanced_Extended#777]
### Type

Error at runtime

### Application

Youtube Revanced Extended-all V18.14.41 (latest)

But tried it on previous versions (18.0.7.35 and above) before that too, same problem. 

Using tablet mode spoof but tried without and same problem. Apparently this was "resolved" 2 weeks ago but it's still persisting on my end. 

### Bug description

I like to listen to videos while sleeping, I noticed I kept hearing sponsors and intros. I just thought the sponsorblock servers were done. Turns out it wasn't. Worked good on the original revanced. 

### Steps to reproduce

Create a playlist
Add 2-3 videos in it, make the 2nd video have a segment at least within the first 15 seconds just so you don't have to wait too long. 
Play video 1, skip to the end of the video. Turn your screen off at least 10-15 seconds before the video ends. Once it goes to the 2nd video, you will notice sponsorblock wont skip any segments until the screen is turned back on and phone unlocked. 

Happens for all videos in the playlist except for the vide you played to begin with. Once the screen is on and you turn the screen off, the segments will skip just fine for that current video.

100% reproducible 

### Relevant log output

```shell
N/A
```

### Device Environment

Android v8.0.1 (but tested on android 10 and 12, still the same issue)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
RVX's SponsorBlock code now completely follows the official ReVanced's code

Therefore, even if you report a SponsorBlock related issue here, there is nothing I can fix.

SponsorBlock-related issues that occur in RVX also occur in official ReVanced (dev branch)

Since SponsorBlock is completely rebased by ReVanced Team, you will need to report the issue to the ReVanced repo to be able to fix it.

**Comment by sezonis** [comment]
> RVX's SponsorBlock code now completely follows the official ReVanced's code
> 
> Therefore, even if you report a SponsorBlock related issue here, there is nothing I can fix.
> 
> SponsorBlock-related issues that occur in RVX also occur in official ReVanced (dev branch)
> 
> Since SponsorBlock is completely rebased by ReVanced Team, you will need to report the issue to the ReVanced repo to be able to fix it.

Hello, I Just patched using the latest version of revanced and it does not happen with revanced. Works as intended. But with RVExtended, it happens. So clearly there is something bugging out. I don't know if it's to do with the sponsorblock code or something else to do with the player itselfs seek functions? perhaps the seek hook might not be functioning during bg play as intended but with revanced itself it functions correctly. Would appreciate if you could look into it

**Comment by inotia00** [comment]
As a result of checking, this issue was not in the sponsorblock patch, but in the `video-id-hook` patch
(`video-id-hook` patch is an independent patch implemented in rvx)

So, since this issue is valid, I will reopen it

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.42](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.42)
