### ISSUE TITLE
Speed button menu showing in PiP

### ISSUE THREAD

**Issue by Kobewaxman** [inotia00/ReVanced_Extended#778]
### Type

Error at runtime

### Application

YT v.18.14.41

Patches 2.168.38

Integrations 0.102.0 (if that matters)

### Bug description

When exiting the app to PiP mode while the speed button menu is open, the PiP will fill with the speed menu instead of the video player.

This happens while in landscape mode as well (not shown in the video).

### Steps to reproduce

Open a video 

Open the speed button menu 

Press the home button to exit the app and enter pip mode

### Relevant log output

```shell
Debug logs? I don't know how to do that.
```

### Screenshots or videos

https://user-images.githubusercontent.com/84587632/232960158-24248aaa-8d6b-4bb0-a70c-1b6f6be5473d.mp4

### Additional context

This is not important to fix, but it's worth reporting it so that you are aware of it.

### Device Environment

Android 13. One UI 5.1. S22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, I do not plan to fix this issue

This is a very minor issue, and it is impossible to fix due to the limitations of the patch implementation method.
