### ISSUE TITLE
Is there any way to change the colour of the background to white?

### ISSUE THREAD

**Issue by DoomDoog** [inotia00/ReVanced_Extended#779]
### Application

YouTube

### Description

In light theme it always confuses me whether my phone is using a comfort mode. Is there a way to change the background colour to white? Thanks in advance. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DoomDoog** [comment]
> Yes, the light theme is white. You can set any hex color to dark theme in options.toml file.

Idk why but I have it that colour #FEEFD8 
Although same app on my tablet is white 
![Screenshot_20230419_140605_YouTube](https://user-images.githubusercontent.com/117683163/233056208-a8aa4a20-d7d6-4cfd-bd23-236117dc79b7.jpg)

**Comment by inotia00** [comment]
That's the color when the `materialyou` patch is applied (Android 12+)
Unfortunately, there is no other way to change the white theme other than using the `materialyou` patch.
