### ISSUE TITLE
feat(patch): add autoplay delay option

### ISSUE THREAD

**Issue by kapchapka** [inotia00/ReVanced_Extended#78]
### Application

YouTube

### Issue

Every time a video ends you get a pop up lasting 3 seconds, which afterwards leads you to a different video. However, 3 seconda might be a little too short for someone to react in time.

### Patch

It would be great if we could change the length of time, chaing it, for example, from 3 seconds to 10. 

### Motivation

It would prevent one from accidentally opening a video he/she wasn't intending to watch. I guess there is a patch to completly remove this pop-up, but it would be great to have it and be able to cuztomize the time since sometimes it can be useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
