### ISSUE TITLE
 Is the owner of this website yours?

### ISSUE THREAD

**Issue by ccxty9** [inotia00/ReVanced_Extended#780]
### Application

Other

### Description

https://revancedextended.com/

Is it a fake site?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Mohammed1520** [comment]
https://t.me/revanced_extended/219

**Comment by inotia00** [comment]
nah.. fake website
