### ISSUE TITLE
bug: Playback speed drops to 2x when video changes during background playback

### ISSUE THREAD

**Issue by possessed-client** [inotia00/ReVanced_Extended#782]
### Type

Other

### Application

YouTube 18.14.41
(Didn't work on 17 either)

### Bug description

If default playback speed is set or remembering playback speed is toggled (or both simultaneously), and is above 2x, then after changing of video, while the app is in the background, playback speed is always dropped to 2x. It immediately increases to the chosen speed when the app is opened to foreground from background, or if it just remains foreground.

### Steps to reproduce

1. Set default playback speed above 2x (for example 3x).
2. Start video playback.
3. Lock phone, open notifications - note how many seconds get played each second.
4. Tap next video from notifications.
5. By the seconds rate it can be seen that speed is 2x now, for some reason.

### Relevant log output

```shell
I don't think log is necessary, it's not a crash (but do tell if it's necessary after all).
```

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is intentional behavior, no fix planned

**Comment by possessed-client** [comment]
> This is intentional behavior, no fix planned
Could you point to the code responsible for this, this is exceedingly annoying behaviour (I think it used to work how I prefer in Vanced in some versions), at this point I might make my own builds.

**Comment by inotia00** [comment]
if so, please open PR
