### ISSUE TITLE
feat(patch): Change of playback speed in notifications.

### ISSUE THREAD

**Issue by possessed-client** [inotia00/ReVanced_Extended#783]
### Application

YouTube

### Issue

People talk in different speeds (and with varying diction, audio quality), keeping the screen on uses battery, unlocking the phone is cumbersome, so it would be helpful if it were possible to change the playback speed quicker.

### Patch

Extra two buttons in the YouTube notification for playback speed increase/decrease. (Or any other way, provided it's as quick or quicker)

### Motivation

Playback speed fine tuning is important for efficient time management.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
