### ISSUE TITLE
bug: playlist bug

### ISSUE THREAD

**Issue by Parachute2004** [inotia00/ReVanced_Extended#784]
### Type

Other

### Application

YouTube v18.13.36

### Bug description

whenever I try to save a video to a playlist it crashes.

### Steps to reproduce

Step 1. Find a video you like.
Step 2. Tap the 3 dots.
Step 4. Tap "Save to Playlist".
Step 5. It opens up the playlist menu.
Step 6. Then it crashes.

### Relevant log output

```shell
Idk how to do this step.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
v18.13.36 is unsupported version
