### ISSUE TITLE
bug: Video played

### ISSUE THREAD

**Issue by Skindetafenbolle** [inotia00/ReVanced_Extended#789]
### Type

Error at runtime

### Application

MicroG v - 0.2.27
Revanced v - 18.11.36

### Bug description

When i start a video, then playing above 3 minut amd later starting infinity loading video, but my Inet very good 

### Steps to reproduce

Idc 

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
patch with latest resources and turn on `Enable protobuf spoof`
