### ISSUE TITLE
question: <title>:  can we add more customisation?

### ISSUE THREAD

**Issue by idontveapc** [inotia00/ReVanced_Extended#790]
### Application

YouTube

### Description

i want the theming and custom fonts options really. what we can change is the colors for sponsor block, but material you option lets you customise colors of the app right?

can that be two fonts types: the font style and emoji font? i've system emoji font that's old but i can change that to updated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Nah.. unfortunately, to implement all of those features, Google would have to open source all of YouTube's source code.

**Comment by idontveapc** [comment]
:(
