### ISSUE TITLE
bug: RYD missing strings

### ISSUE THREAD

**Issue by HundedFifteeTee** [inotia00/ReVanced_Extended#791]
### Type

Cosmetic

### Application

YouTube ReturnYouTubeDislike

### Bug description

The following string appear to be missing:

revanced_ryd_failure_ryd_enabled_while_playing_video_then_user_voted

### Steps to reproduce

enable RYD, and then:

1. open a video
2. open a short (without closing the regular video)
3. close the short
4. vote for the regular video

It tries to load `revanced_ryd_failure_ryd_enabled_while_playing_video_then_user_voted`, but it appears the string is not found in patches strings.xml

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.45](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.45)
