### ISSUE TITLE
default-video-speed: <default-video-speed>: 

### ISSUE THREAD

**Issue by Advaldolc** [inotia00/ReVanced_Extended#793]
### Application

YouTube

### Description

default-video-speed why removed?
Can you enable again?

Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I did not removed `default video speed` patch

**Comment by Advaldolc** [comment]
Thanks by the answer,

In ReVanced, I can't find the option to fix speed for all videos in Settings/Video.

Sincerely, Advaldo

________________________________

**Comment by inotia00** [comment]
read [documentation](https://github.com/inotia00/revanced-documentation/wiki) 
I think you are using unsupport version

**Comment by Advaldolc** [comment]
v-18.14.41

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Advaldolc** [comment]
I don't know how to make it, sorry.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
