### ISSUE TITLE
question: <title>:  shorts

### ISSUE THREAD

**Issue by De1ta68** [inotia00/ReVanced_Extended#796]
### Application

YouTube

### Description

The problem is that when playing shorts on demand ("blogger shorts"), it plays 5 shorts and then plays shorts according to recommendations. Is it possible to make it so that all shorts are played on request?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
nah.. to implement it, Google must open up all YouTube's source code and x-protobuf API.
