### ISSUE TITLE
Swipe gestures step size and response

### ISSUE THREAD

**Issue by Jinkxt** [inotia00/ReVanced_Extended#797]
Compared to the old versions of vanced, the swipe gestures (specifically brightness slider) 's stepping speed is too high, as a consequence screen brightness response lags behind which introduces over corrections by the user.

Suggestions : introduce a stepping speed variable for the brightness slider.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/59
https://github.com/inotia00/ReVanced_Extended/issues/259
