### ISSUE TITLE
feat(patch):  remove "important" category from notification list

### ISSUE THREAD

**Issue by NBruderman** [inotia00/ReVanced_Extended#798]
### Application

YouTube

### Issue

The notifications list was always ordered by the time the videos came out. However, recently, youtube made a separate category, which is called "important", which appears above the recent notifications, and have 2 older random videos in it from the list.

### Patch

The patch should remove the important category, and restore the old list, which only sorted the notifications by time. Need to make sure the 2 "important" videos will be re-added to the original list

### Motivation

Its really inconvenient, as most of the times, the videos are not important, and just being chosen randomly. Also, there is no option to disable the feature and go back. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Flowwer-ye** [comment]
I would like to have an option to remove it as well, it can be pretty annoying when trying to see what new videos you were notficated about

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
