### ISSUE TITLE
feat(patch): Allow Lower Video Playback Speeds

### ISSUE THREAD

**Issue by Yola-cola** [inotia00/ReVanced_Extended#799]
### Application

YouTube

### Issue

I find it confusing that they allow a variety of speed options but yet the slower speeds are still capped at 0.25

### Patch

Basically just add slower playback speed or at least so they are even with the faster speeds.

### Motivation

So the custom playback speed can actually be custom.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Already implemented
The `custom-video-speed` patch is that

If you edit the `options.toml` file, you can add the speed you want.
