### ISSUE TITLE
feat(patch): vanced hide comment section 

### ISSUE THREAD

**Issue by DanTcyb** [inotia00/ReVanced_Extended#800]
### Application

YouTube

### Issue

this function disappeared since last update. would really like to get it back if possible

### Patch

I guess you could just write a code for that but I might be wrong. but considering that it was working and now you can hide almost anything, I hope comments wouldn't be a problem 

### Motivation

can't stand seeing typical YouTube jokes etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
What do you mean?

Please attach a screenshot with a more detailed description of what patch you are referring to.

**Comment by DanTcyb** [comment]
you used to be able to hide comment section in old versions. now that I have updated it, I can't hide comment section under the video.

**Comment by inotia00** [comment]
Settings > ReVanced Extended > Bottom player > Hide comment
