### ISSUE TITLE
bug: video is black after exiting and reopening app

### ISSUE THREAD

**Issue by Kiwikip** [inotia00/ReVanced_Extended#801]
### Type

Error at runtime

### Application

Youtube revanced extended 18.14.41

### Bug description

The whole video page turns black and the video keeps loading after reopening, if I exit again and reopening, the video isn't opend anymore

### Steps to reproduce

1:Play a video, pause the vid

2:exit (keep it in recent), do something else on another app for some time (don't know if the duration (for me somthimes instant and somthimes more than 5 min.) or apps opend matters, my phone keeps the rest of the youtube in RAM)

3:open the app. it should be with video loading forever and black videopage (doesn't work every time..)

(4: if bug recreated, exit and reopening again (black screen and loading vid dissappear as if it wasn't opend)) 

### Relevant log output

```shell
Don't have any
```

### Screenshots or videos

Pic is patches installed
![Screenshot_20230420_200502](https://user-images.githubusercontent.com/130678837/233453798-dc406d97-496b-4396-b237-a878dc0f6f6b.jpg)

Vid is bug (didn't capture opening the app, but this was the first moment it was opend and what happens when I close and open again)

### Device Environment

Android 13
ONE UI 5.1
S23 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
please check in unpatched video

**Comment by jhon1282** [comment]
Yep it happens to me too.
Closing the application from PiP, in recent it looks like this.
![Screenshot_2023-04-20-23-42-12-795_com miui home](https://user-images.githubusercontent.com/125223735/233494860-e4a70a23-41cf-4b73-8364-ad4555df5a12.jpg)

Reopen and double buffered black screen

![Screenshot_2023-04-20-23-38-48-399_app rvx android youtube](https://user-images.githubusercontent.com/125223735/233495562-fdbc6529-ecec-4c68-ade7-6bb72b9f2823.jpg)

**Comment by jhon1282** [comment]
![Screenshot_2023-04-21-00-02-42-847_com miui home](https://user-images.githubusercontent.com/125223735/233497872-a5eced13-6f0a-4aac-b461-9373692da14c.jpg)

Original youtube not closing from PiP. And it looks like this.
In the screenshot you can see original youtube on the left, ReVanced on the right

**Comment by Kiwikip** [comment]
> and.. black video mean, buffer?

Yes, I mean buffer of the video and the video page.

>please check in unpatched YouTube

I couldn't recreate it in stock youtube

**Comment by Kiwikip** [comment]
Wrong button 😅

**Comment by inotia00** [comment]
try to turning on `Enable protobuf spoof`

**Comment by Kiwikip** [comment]
It happens with and without protobuf spoof enabled

**Comment by Kiwikip** [comment]
I don't know if it's related, but if i exit the app in rvx settings, do something for a couple of min. And reopening it, dark theme is gone and it's white. The moment I tap on something it goes back to normal. Only happens to me in rvx settings. Protobuf spoof doesn't change it.
Do I have to make a different bug report for this or not?

https://drive.google.com/file/d/1WIbLYSJG6TAxJp8cIBxhWuW_ttRtaXKM/view?usp=drivesdk

**Comment by s23ultra512** [comment]
I have the same exact device as OP has, and Im unable to repro this issue. On my end its working flawlessly.

Try to clear your youtube cache, and reset your network settings and try again.

Also wiping your phones cache might help.

**Comment by jhon1282** [comment]
> I don't know if it's related, but if i exit the app in rvx settings, do something for a couple of min. And reopening it, dark theme is gone and it's white. The moment I tap on something it goes back to normal. Only happens to me in rvx settings. Protobuf spoof doesn't change it. Do I have to make a different bug report for this or not?
> 
> https://drive.google.com/file/d/1WIbLYSJG6TAxJp8cIBxhWuW_ttRtaXKM/view?usp=drivesdk

Same issue

https://user-images.githubusercontent.com/125223735/233603860-231dacc6-a371-417d-97e7-7d2ac98f3534.mp4

**Comment by Kiwikip** [comment]
I've tried updating, reinstalling, restarting phone, with and without protobuf spoof, on wifi and mobile, with and without vpn.

Solution? I re patched the apk with the same patches from the same yt akp, now it works for me but the file name is different from the other patched version. The file name is 
youtube-revanced-revanced_v18.14.41.apk

Why 2 times revanced?

If this works for other people I will close the bug report with repaching as solution
