### ISSUE TITLE
question: Disable default video speed in live stream patch. How should it work? 

### ISSUE THREAD

**Issue by Hennadz** [inotia00/ReVanced_Extended#802]
### Application

YouTube

### Description

Tell me, please, what needs to be switched here so that the speed drop occurs not only in the background?
When the application interface is open, switching to normal speed does not occur.
Android 10
Updated Revancify
18.14.41, v2.168.42

![233321976-663c13d9-9fdf-4132-a34f-8dcf27692beb](https://user-images.githubusercontent.com/130844239/233466788-9e1bcfed-4f73-444d-8afe-a77c645173f8.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is an unimplemented feature
