### ISSUE TITLE
Infinite loading screen on  mobile device 

### ISSUE THREAD

**Issue by Karius7370** [inotia00/ReVanced_Extended#803]
### Type

Error at runtime

### Application

YouTube v18.05.40-all.apk

### Bug description

Basically the app fails to load videos longer than one minute(not sure if that would be correct but the tests ive run show that short videos lack the issue), and gets into an infinite loading screen. What happens vissualy is that one moment youre watching a video normally and the next thing is that the video cuts to a black background infinite loading screen that can only be exited by closing said video and re opening it again, im not a coder, but it could be related to late patches. If you are just listening to the video, it just cuts for a split second and continues. Although it may seem like an internet issue, it is not at least in my case as my internet speed is very high and other devices and apps can run perfectly without any issues. 

### Steps to reproduce

Step 1: Run the app normally
Step 2: Seek for a video longer than one minute
Step 3:Play the video and wait a few seconds for the bug to happen
Step 4: Boom, you are now in the infinite loading screen

### Relevant log output

```shell
[undefined]
```

### Screenshots or videos

https://user-images.githubusercontent.com/131401694/233471321-a716e666-17f3-4988-b983-2a2f266b3afc.mp4

### Solution

As i am not a pro coder, my sollution is to run through the code and maybe delete some lines that may interact with each other and create a loop of actions, since that could cause the bug and the infinite loading screen.

### Additional context

If anyone reads this and can contact me for more info, my discord is Karius#9012

### Device Environment

Realme 6i

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by thragna** [comment]
yt is blocking revanced client, try out root version revanced

**Comment by inotia00** [comment]
Enable protobuf spoof
