### ISSUE TITLE
bug: <screen orientation not changing>

### ISSUE THREAD

**Issue by Haseebshah805** [inotia00/ReVanced_Extended#804]
### Type

Cosmetic

### Application

18.14.41

### Bug description

videos in full screen won't flip direction on changing phone orientation by 180 degrees.

### Steps to reproduce

Play any video in full screen mode and then rotate the phone by 180 degrees. 
The video will remain in the same upside-down direction. 

### Relevant log output

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
YouTube issue, not ReVanced Extended issue
