### ISSUE TITLE
bug: <buffer won't show>

### ISSUE THREAD

**Issue by Haseebshah805** [inotia00/ReVanced_Extended#805]
### Type

Cosmetic

### Application

18.14.41

### Bug description

While watching videos, the buffer amount (gray bar on the seekbar) won't show unless you touch the screen to show the controls. 

### Steps to reproduce

Play any video and notice the seekbar.

No buffer amount will show unless you touch the video to make the buttons visible.

### Relevant log output

```shell
None
```

### Screenshots or videos

![Uploading Polish_20230421_010534999.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
That's YouTube's new layout
