### ISSUE TITLE
bug: Bottom Button Player hiding doesn't work

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#806]
### Type

Other

### Application

YT

### Bug description

Hiding Bottom Buttons doesn't work in latest...not the main nor experimental flags...if we hide action buttons, thy don't hide. Only some buttons are working like download button etc. Please check this at your end, as I have reinstalled YT around 2-3 times from my end.

### Steps to reproduce

I will post the video here soon.

### Relevant log output

```shell
...
```

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Vipin2003** [comment]
https://a.uguu.se/QCmxezAl.mp4

**Comment by inotia00** [comment]
no plans to fix

**Comment by Vipin2003** [comment]
So, this means that we can't hide the action buttons rn.
