### ISSUE TITLE
bug: <title> Bottom Player button still visible

### ISSUE THREAD

**Issue by manishloshali** [inotia00/ReVanced_Extended#807]
### Type

Cosmetic

### Application

18.14.41

### Bug description

bug #541 is back
Hide action buttons setting is off but buttons are still visible.
Even enabling experimental patches doesn't work

### Steps to reproduce

1. Go to bottom player layout settings
2. Hide action buttons
3. check

### Relevant log output

```shell
_
```

### Screenshots or videos

![WhatsApp Image 2023-04-21 at 12 09 03 PM](https://user-images.githubusercontent.com/125728453/233562066-e5a3199f-ee9b-4cf5-9f8d-14c69ba05683.jpeg)
![WhatsApp Image 2023-04-21 at 12 09 04 PM (1)](https://user-images.githubusercontent.com/125728453/233562082-b839baa7-f4eb-4efc-813e-2040c47deda9.jpeg)
![WhatsApp Image 2023-04-21 at 12 09 04 PM](https://user-images.githubusercontent.com/125728453/233562085-3a17d349-d5aa-4faf-9830-6613feb3be3f.jpeg)

### Device Environment

Realme UI A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Hennadz** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/806

**Comment by inotia00** [comment]
The `hide-button-container` patch is buggy and no longer suitable for maintenance, so it will be removed in the next release

**Comment by Kuddus73** [comment]
> The `hide-button-container` patch is buggy and no longer suitable for maintenance, so it will be removed in the next release

Don't remove it, leave it as Experimental.
It still works perfectly for me as I believe for many others as well.

**Comment by s23ultra512** [comment]
I agree, dont remove it. This feature has been working flawlessly on my phone. If it gets removed then Im afraid that v2.168.45 will be my last build that I installed, not gonna update to newer builds if it gets removed.
