### ISSUE TITLE
question: <title>: List of Custom filter?

### ISSUE THREAD

**Issue by manishloshali** [inotia00/ReVanced_Extended#808]
### Application

YouTube

### Description

Can you share a list of custom user filters. I only know _related_video_
![4dd1e4e7-a721-41fd-808e-46aedbc3b236](https://user-images.githubusercontent.com/125728453/233563633-8e472909-06e2-4b40-b26c-d60bed2c4dc0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Features implemented by the ReVanced Team
so i don't know either
