### ISSUE TITLE
feat(patch): auto-hide portrait mode seekbar 

### ISSUE THREAD

**Issue by innuendofloyd** [inotia00/ReVanced_Extended#810]
### Application

YouTube

### Issue

not an issue, just cosmetic

### Patch

temporized hide-seekbar:

Hide seekbar when video is in portrait mode, but only after a certain amount of time, same amount of time of buttons. Tap on video to view seekbar again.
Similar to what happen when video is viewed in landscape mode.

### Motivation

Less distracting and makes more sense in UI

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
