### ISSUE TITLE
Suggestion: When `Press-to-swipe` is disabled, `Press-to-swipe haptic feedback` is also disabled

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#811]
`Press-to-swipe haptic feedback` feature only works when `Press-to-swipe` is enabled. Therefore, when `Press-to-swipe` is disabled, `Press-to-swipe haptic feedback` is also disabled to make RVX intuitive and avoid user confusion.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.169.5](https://github.com/inotia00/revanced-patches/releases/tag/v2.169.5)

**Comment by buiducanh142qn** [comment]
This issue is back in the lasted patch.

**Comment by inotia00** [comment]
I'll reflect on the next release

**Comment by buiducanh142qn** [comment]
Looks like you forgot to fix this issue again 🥲

**Comment by inotia00** [comment]
lol I forgot it
