### ISSUE TITLE
is it possible to increase or change the location of the button that is responsible for the function of reversing the video to full screen?

### ISSUE THREAD

**Issue by Dickcher** [inotia00/ReVanced_Extended#812]
### Application

YouTube

### Description

is it possible to increase or change the location of the button that is responsible for the function of reversing the video to full screen? If not, please add it in the update

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
also, attaching an image will help me understand

**Comment by Dickcher** [comment]
![IMG_20230421_191042](https://user-images.githubusercontent.com/65553064/233685302-6fcada87-ea27-435f-a4f4-a172fdb21b69.jpg)
I'm talking about this circled button at number 1, but I would like it to have a higher click position, as shown in circle 2, because sometimes I move to the end of the video by pressing the screen rotation button. Turn off the rewind bar, which I  indicated with an arrow, I don’t want it because it’s convenient. Also, one more request to make sure that when I swipe from top to bottom in horizontal mode when I watch a video, the video does not go into vertical mode. I will be grateful to you if you ever  you will do it. But so your program is very good, thanks!
