### ISSUE TITLE
question: `Hide Product Ads` in endscreen overlay 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#813]
### Application

YouTube

### Description

I remember there being an issue reported here regarding this issue. Was it resolved then? If so then which patch or setting is it? If not then please change this to a patch request and introduce a patch to fix this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
The issue in question:
![Screenshot_20230421-172444](https://user-images.githubusercontent.com/117499019/233633460-f084cf53-9a60-4abe-bf60-e48b5be6824a.png)

**Comment by inotia00** [comment]
duplicate with https://github.com/inotia00/ReVanced_Extended/issues/216
