### ISSUE TITLE
Revanced extended recommends nonexistent youtube v18.15.38

### ISSUE THREAD

**Issue by Jai-JAP** [inotia00/ReVanced_Extended#814]
Latest RVX release v2.168.45 recommends nonexistent youtube v18.15.38 which should be v18.15.35 (latest in 18.15.x series)

Running `java -jar revanced-cli.jar -a revanced-integrations.apk -b revanced-patches.jar -l --with-versions 2>/dev/null | grep -m1 hide-create-button`
gives 
```
INFO:        hide-create-button	Hides the create button in the navigation bar.	18.06.41, 18.07.35, 18.08.39, 18.09.39, 18.10.37, 18.11.36, 18.12.35, 18.13.38, 18.14.41, 18.15.38 4466

# It should be 18.15.35 which is the latest yt release for 18.15.x 
```

**Comment by Spacellary** [comment]
Same. Bump!

https://github.com/Spacellary/ReVanced-Extended-Builds-With-Automatic-Updates/actions/runs/4765882518/jobs/8472176905#step:5:124

**Comment by jhon1282** [comment]
https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-15-38-release/
