### ISSUE TITLE
Cant find version 18.15.38?

### ISSUE THREAD

**Issue by Aspect250** [inotia00/ReVanced_Extended#815]
### Application

YouTube

### Description

In the notes in v2.168.45 it's is said "add support YouTube v18.15.38" but from what I have found browsing apk websites YouTube v18.15.38 doesn't currently exist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Aspect250** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/814

**Comment by jhon1282** [comment]
https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-15-38-release/
