### ISSUE TITLE
bug: whitelist overlay button does not hidden

### ISSUE THREAD

**Issue by b-aaron** [inotia00/ReVanced_Extended#818]
### Type

Cosmetic

### Application

Youtube v18.14.41
revanced-patches 2.168.40

### Bug description

The whitelist overlay button sometimes shows up, when the option is disabled. This seems to be happening when a video is opened upon the start of the app.

A second problem that goes hand in hand with this is the whitelist overlay button showing up when the player controls aren't on screen. In the same situation that the button shows up, when it shouldn't, the button stays on screen after double-tapping to fast-forward/rewind.

### Steps to reproduce

1. Show whitelist button.
2. Hide whitelist button.
3. Restart Revanced Extended app while currently having a video open.
4. Open Revanced Extended.
5. See that whitelist overlay button is showing in video.
6. Double-tap to fast-forward/rewind.
7. See that whitelist overlay button shows up, when player controls are not showing.
8. Restart Revanced Extended app while no video is open.
9. Open Revanced Extended.
10. Start video and see that overlay button is not showing.

### Relevant log output

```shell
None
```

### Solution

Temporary: 
Always closing the Revanced Extended app while no video is opened will cause this bug to not happen.

Permanent: 
It seems that the implementation of the whitelist overlay button is different to those of the other overlay buttons. Implementing the whitelist overlay button in the same way the other ones are implemented should fix this.

### Additional context

This seems like it's related to issue #599. However, that one seems to have been closed without a change. Since I have found another problem with additional information on how to recreate it, I decided to open this new issue.

### Device Environment

Android 13
One UI 5.1
Samsung Galaxy S20 FE 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by b-aaron** [comment]
Just to be a bit more specific on one point:

By restarting the app I mean closing it from Recents and reopening it, so that any opened videos stay open.

For example restarting it through the app (by changing a setting that requires a restart) will cause any opened videos to close and therefore the bug to not occur.

**Comment by inotia00** [comment]
removed in [revanced-patches-v2.173.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.1)
