### ISSUE TITLE
bug: <Dislikes are not shown while watching videos via cast button>

### ISSUE THREAD

**Issue by rightsaid** [inotia00/ReVanced_Extended#819]
### Type

Error while patching

### Application

v18.15.38

### Bug description

Dislikes are not shown in Youtube Revanced while watching videos via cast button on Android TV. Return Youtube Dislike is activated

### Steps to reproduce

Step 1: Activate Cast mode
Step 2: open a Youtube video

### Relevant log output

```shell
do not have
```

### Screenshots or videos

https://user-images.githubusercontent.com/16355687/233714619-86ff9db3-53b0-4616-ac25-11bb7801f22c.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, official ReVanced and ReVanced Extended do not provide support for casts.

Therefore, I do not provide support for issues arising from casting (e.g. ryd does not work when casting, video ads are not blocked when casting)

When you need to cast, use another YouTube client
