### ISSUE TITLE
Skip segment for whitelisted channels

### ISSUE THREAD

**Issue by venkat2305** [inotia00/ReVanced_Extended#82]
### Application

YouTube

### Issue

Skip segment for whitelisted channels

### Patch

For whitelisted channels, instead of 

### Motivation

Skip segment for whitelisted channels

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
too little explanation

**Comment by venkat2305** [comment]
Right now, if a channel is whitelisted sb segments won't be downloaded. But it would be great if the segments were downloaded and we were given an option at each segment to skip the segment with a skip button. Does this make sense?
