### ISSUE TITLE
bug: <title> tela preta na hora do vídeo 

### ISSUE THREAD

**Issue by saviogomes77** [inotia00/ReVanced_Extended#821]
### Type

Error at runtime

### Application

YouTube vanced

### Bug description

A tela fica preta na hora que está assistindo o vídeo e isso é chato 

### Steps to reproduce

Você entra e assiste só um pouco 

### Relevant log output

```shell
E depois o vídeo para e não consigo assistir
```

### Screenshots or videos

![Screenshot_2023-04-21-20-35-58-189_com vanced android youtube](https://user-images.githubusercontent.com/131498117/233749111-80e57f40-46c0-493a-97b4-22a85326a3c1.jpg)

### Solution

Qual a solução?

### Additional context

Eu quero que esse bug seja consertado 

### Device Environment

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by saviogomes77** [comment]
Alguém corrige isso por favor

**Comment by inotia00** [comment]
Enable protobuf spoof
