### ISSUE TITLE
question: <title>: can't see recommand videos and subs button

### ISSUE THREAD

**Issue by WSRCK** [inotia00/ReVanced_Extended#822]
### Application

YouTube

### Description

I turned off options about hide recommand videos and subs button. But I can't see buttons when videos end. 
How can I see that things?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
hide recommand videos patch not implemented
What do you mean?

**Comment by inotia00** [comment]
Please reopen with screenshots and a suitable description
