### ISSUE TITLE
Huawei devices sign-in in new microg

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#823]
### Application

YouTube

### Description

In vanced microg and other related microg there is a button designed for Huawei devices to sign in . But it doesn't exist in the Mmicrog. Please can you bring back this function?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Contact the official microg team
