### ISSUE TITLE
Can not open the app

### ISSUE THREAD

**Issue by mishu-uu-ulala** [inotia00/ReVanced_Extended#824]
### Type

Error at runtime

### Application

Every version after `youtube-revanced-extended-magisk-v18.13.38-all`

### Bug description

First I updated to "youtube-revanced-extended-magisk-v18.14.40-all" through the magisk official update channel. After that I rebooted, just like instructed. 
That was the first time I encountered the issue. After reboot, I tried to open YouTube app. Everytime I launch the app, It just force closes. No ReVanced logo, no nothing.
This issue is persistent on every update after "youtube-revanced-extended-magisk-v18.13.38-all".
I had to downgrade to "v18.13.38-all"

Foot Note, Non root apk works fine.

### Steps to reproduce

> Step 1. Install "youtube-revanced-extended-magisk-v18.14.40-all" or later. Latest update will do.

> Step 2. Reboot.

> Step 3. Try to open YouTube app.

### Relevant log output

```shell
N/A
```

### Device Environment

Device Name          : Redmi Note 7 Pro
Manufacturer         : Xiaomi Inc.
Device Codename : Violet

Android version      : Android 10.0
MIUI version            : MIUI Global 12.5.1-Stable
ROM status             : Stock ROM
OEM status             : Unlocked
Root status             : Rooted
Recovery                  : twrp-3.7.0_9-0-violet
Magisk                     : Installed v26.1 (26100)
Zygisk                      : Yes
Ramdisk                  : No

RAM/ROM              : 6 GB / 64 GB

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I do not distribute prebuilt apks or modules
If you didn't build according to the [documentation](https://github.com/inotia00/revanced-documentation/wiki), I can't help
