### ISSUE TITLE
bug: Audio issue on videos every while

### ISSUE THREAD

**Issue by greengeckowizard** [inotia00/ReVanced_Extended#825]
### Type

Other

### Application

Youtube 18.14.41

### Bug description

When you open a video on YouTube it doesn't have audio every once in a while doesn't happen too frequently. 

### Steps to reproduce

Step 1. Go to any video 
Step 2.watch and there will be issue.

### Relevant log output

```shell
Not sure how to include I don't see option in the settings.
```

### Solution

Reopening Youtube or closing the video and Reopening

### Device Environment

Android 12 Samsung S10 Plus 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Attach a list of patches you include and a screen recording of when the issue occurs.

**Comment by greengeckowizard** [comment]
> Attach a list of patches you include and a screen recording of when the issue occurs.

The bug happens rarely so it's hard to pin point exactly when it occurs. But here's the patches I'm using 
![image](https://user-images.githubusercontent.com/34012548/233802545-74b5b57e-fbdf-43a8-886e-4fad2dd29f80.png)

**Comment by inotia00** [comment]
try to repatch latest sources

**Comment by inotia00** [comment]
Seems to be an outdated issue, so I'm closing it
Please patch again with the latest resources

**Comment by greengeckowizard** [comment]
Yeah it seems to be not doing this anymore thanks anyway for taking a look at it though.
