### ISSUE TITLE
bug: comments never show nor their number under some videos before clicking on the word comments

### ISSUE THREAD

**Issue by atervian** [inotia00/ReVanced_Extended#826]
### Type

Cosmetic

### Application

revanced 18.15.38
miui 14

### Bug description

Some videos like this one:
https://youtu.be/sGRw--AduNI
don't show the comments nor their numbers until the user click on the comments section to see all the comments.

The bug existed with the previous versions.

### Steps to reproduce

https://youtu.be/sGRw--AduNI

You have to click in the comments section under the video to show the comments.
Those videos with the bug don't give a preview of the comments nor their numbers.
Nonetheless you can't never tell how many comments they have.

### Relevant log output

```shell
none
```

### Screenshots or videos

https://youtu.be/sGRw--AduNI

![IMG_20230422_205754](https://user-images.githubusercontent.com/119813817/233801898-4eeb6533-9a69-4b68-a424-fd3713becfa4.jpg)

You can't see the number of comments nor guess if there are any comments.

But when you click on the comments section, all the comments appear.

![IMG_20230422_205838](https://user-images.githubusercontent.com/119813817/233801979-8c524c99-c78e-4843-9fa1-8554ce6c30f5.jpg)

### Device Environment

Miui 14.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Reproducible even on unpatched YouTube
So this is not an issue that ReVanced Extended needs to fix, it's an issue that Google needs to fix.
