### ISSUE TITLE
feat(patch): Endless video downloads

### ISSUE THREAD

**Issue by Frog20707** [inotia00/ReVanced_Extended#827]
### Application

YouTube

### Issue

When you start a video, it loads well for half a minute, then an endless download of the video that is not corrected begins

### Patch

 I don't know

### Motivation

I believe that this is a critical error that interferes with a comfortable pastime in the application

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/788
