### ISSUE TITLE
bug: Sponsorblock is unable to submit multiple segments

### ISSUE THREAD

**Issue by xrrxr** [inotia00/ReVanced_Extended#828]
### Type

Error at runtime

### Application

YouTube 18.06.41

### Bug description

`Preview the segment, and ensure it skips smoothly` is displayed when attempting to submit more than one segment.

### Steps to reproduce

1. Sponsorblock -> Enable `Show create new segment button` option
2. Submit a segment
3. Submit another segment

### Relevant log output

```shell
None
```

### Solution

Add a Preview segment before submit section in Sponsorblock

### Device Environment

Android 13

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
click preview button before submit a segment

**Comment by xrrxr** [comment]
> click preview button before submit a segment

e.g.
The segment I'm trying to submit is (00:00:05.000 to 00:00:10.000)
A existing segment is (00:00:00.000 to 00:00:10.000)

After clicking the preview button, only the existing segment is skipped, and then `Preview the segment, and ensure it skips smoothly` is displayed when attempting to submit the segment.
