### ISSUE TITLE
feat(patch): video download function

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#829]
### Application

YouTube

### Issue

If we download video the video downloaded only in YouTube app.

### Patch

App patch to download videos in phone specified given path to store in internal storage directly for share the video to others also and play in phone video player.

### Motivation

To download video in internal storage so we can share video to others and play in phone video player, without needing website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate with https://github.com/inotia00/ReVanced_Extended/issues/7
