### ISSUE TITLE
feat(patch): add search features in settings

### ISSUE THREAD

**Issue by venkat2305** [inotia00/ReVanced_Extended#83]
### Application

YouTube

### Issue

There are so many options . Navigating between then or to finding a specific setting is confusing and takes time 

### Patch

There are so many options . It would be great if there is a search button to search all the settings 

### Motivation

It would reduce a lot confusion 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
