### ISSUE TITLE
feat(patch): Re-add `hide-fullscreen-buttoncontainer`

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#830]
### Application

YouTube

### Issue

The feature has been removed for some reason.

### Patch

Basically re-add the `hide-fullscreen-buttoncontainer` option.

### Motivation

I've always used that feature to have an immersive experience when watching videos in full screen.
Its removal is a big downgrade in my opinion.

If someone asked to remove `hide-fullscreen-buttoncontainer`, they can simply don't enable the option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Kuddus73** [comment]
Oh wait, is `hide-quick-actions` the new `hide-fullscreen-buttoncontainer`?

**Comment by Hennadz** [comment]
There are a lot of interesting things 🙂

**Comment by inotia00** [comment]
yep `hide-quick-actions` patch works as `hide-fullscreen-buttoncontainer` patch

It was removed because it was a duplicate patch.
