### ISSUE TITLE
feat(patch): Long-tap playlist button doesn't work anymore (YouTube Server side)

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#832]
### Application

YouTube

### Issue

![Screenshot_20230423-012935425 (1)](https://user-images.githubusercontent.com/73917917/233811875-da5e57c2-5459-4a70-b1a8-2a7e806f8193.png)

Used to be able to long press on the Playlist icon to bring up the playlists list and add video to desired Playlist(instead of last chosen playlist)

Upon testing stock YouTube this functionality seems to be removed from YT. I'm not 100% sure though.
Can you please check and add it back as feature patch?

**EDIT:**
People in Reddit also noticed it's gone:
 [link](https://www.reddit.com/r/youtube/comments/12ugt82/has_anyone_else_lost_the_longpress_the_save/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)
[link2](https://www.reddit.com/r/youtube/comments/12w725h/tap_hold_to_save_into_playlist_not_working/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)
[link3](https://www.reddit.com/r/youtube/comments/12tu4sf/trouble_saving_videos_to_playlists_on_mobile/jh4gtvv?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)
Google removing QOL features...

**Comment by inotia00** [comment]
Long press add to playlist doesn't reproduce even on unpatched YouTube (v18.15.40, new layout)

yeah.. it looks like google removed this feature from server side

I can't roll back a feature I removed from the server side

**Comment by anyujinie** [comment]
> Long press add to playlist doesn't reproduce even on unpatched YouTube (v18.15.40, new layout)
> 
> yeah.. it looks like google removed this feature from server side
> 
> I can't roll back a feature I removed from the server side

Great.. YT removes another very useful feature for no reason. Why am I not surprised?

It saddens me that you say there is absolutely no way to restore this feature😔

**Comment by johnconner122** [comment]
It's only working in full screen.

**Comment by anyujinie** [comment]
People in reddit also noticed it's gone...

https://www.reddit.com/r/youtube/comments/12ugt82/has_anyone_else_lost_the_longpress_the_save/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

Google removing QOL features...

**Comment by johnconner122** [comment]
It's working again for me.
