### ISSUE TITLE
feat(patch): Combining hide-quick-actions and hide-button-container patches

### ISSUE THREAD

**Issue by MustafaErdqn** [inotia00/ReVanced_Extended#834]
### Application

YouTube

### Issue

When I hide the action buttons under the video player, when I take the video to the full screen, I see that the full-screen action buttons are still open, in fact, I think it would be more functional to turn both the full-screen buttons and the action buttons under the video with a single patch instead of turning them off and on separately.  don't you think it would be better?

### Patch

![Screenshot_20230423_093100_YouTube](https://user-images.githubusercontent.com/126149028/233823756-0ccb0484-b904-4c20-952d-bc21cdc1bfaa.jpg)
![Screenshot_20230423_092943_YouTube](https://user-images.githubusercontent.com/126149028/233823758-2c8c8e43-b192-4504-8cb1-653bc503d39b.jpg)
![Screenshot_20230423_094827_YouTube](https://user-images.githubusercontent.com/126149028/233824796-81dd0b44-333a-406f-835f-7f10248f12ec.jpg)
![Screenshot_20230423_094919_YouTube](https://user-images.githubusercontent.com/126149028/233824639-a549a3b8-6e11-431d-8470-e351615d80a3.jpg)

### Motivation

Ease of use and increase functionality

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Those two are in different settings (one is `Bottom player`, the other is `Fullscreen`)

Since each setting is patched on different bytecodes, it cannot be merged into one.
