### ISSUE TITLE
bug: The clip button is not hidden when I activate the hide action buttons option.

### ISSUE THREAD

**Issue by MustafaErdqn** [inotia00/ReVanced_Extended#835]
### Type

Error at runtime

### Application

YouTube v18.15.40

### Bug description

I usually turn off the unnecessary buttons because I don't use the under player buttons much, so when I activate the hide action buttons option, I saw that the clip button did not hide.

### Steps to reproduce

Step 1. Open YouTube app
Step 2. Activate Hide action buttons option in ReVanced Extended >> Bottom player menu
Step 3. Open any video in the app and the clip button at the bottom is still active.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230423_100127_YouTube](https://user-images.githubusercontent.com/126149028/233825522-3e6c4ef4-781b-4f53-8f9c-1939d0a02460.jpg)
![Screenshot_20230423_100101_YouTube](https://user-images.githubusercontent.com/126149028/233825524-6e228826-29d7-4469-9390-1e806f728218.jpg)

### Device Environment

Android 13, OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
no plans to fix
