### ISSUE TITLE
bug:  Repeat button in playlist cannot changed

### ISSUE THREAD

**Issue by DeMantuL** [inotia00/ReVanced_Extended#836]
### Type

Error at runtime

### Application

YouTube v18.15.38

### Bug description

I think this bug has been happening since yesterday and it hasn't been fixed for some reason, am I in the wrong layout or is there a layout update? It's in the playlist, when you want to repeat the symbol doesn't change, when you try the original, the symbol has changes such as thickening, while for extended there is no change between does not repeat, repeats the entire playlist, or only repeats the song

### Steps to reproduce

Go to a playlist that has many song lists
And there is a symbol like a circular arrow
Try to push that symbol

### Relevant log output

```shell
Not found
```

### Screenshots or videos

https://user-images.githubusercontent.com/128309944/233849837-2cf76d7f-2450-40b6-9284-e2201a647041.mp4

### Device Environment

Newest Android, MiUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Kuddus73** [comment]
Shouldn't this be closed as it was fixed with v2.171.3?

**Comment by inotia00** [comment]
ah reflected in revanced-patches-v2.171.3

**Comment by DeMantuL** [comment]
Nice, thanks guys
