### ISSUE TITLE
The ability to disable the black dark mode and re-enable the grey one

### ISSUE THREAD

**Issue by Techfromthepast123** [inotia00/ReVanced_Extended#837]
### Application

YouTube

### Issue

This patch should change the dark mode color back to the old grey one from 2021 and should be compatible with both the new & old UI's

### Patch

![old-youtube-dark-theme](https://user-images.githubusercontent.com/112059671/233858868-6f0ba92a-5116-4bfc-9fe0-ce2c88cb655b.jpg)
It should be this color

### Motivation

It should be considered because some people may not like the black dark mode and prefers the old grey one and I prefer the old grey darkmode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Techfromthepast123** [comment]
Some people say there are ways to bring it back but it requires patching which fails most of the time and it would be cool if this option was on youtube revanced's settings by default

**Comment by anyujinie** [comment]
The black one is better my man

**Comment by Techfromthepast123** [comment]
Nah the grey is better and we can have each opinion

**Comment by inotia00** [comment]
exclude `theme` patch and enable old layout

**Comment by Techfromthepast123** [comment]
How do I do that ?
