### ISSUE TITLE
bug: YouTube Channels Member Shelf is not working.

### ISSUE THREAD

**Issue by aryanmaulana7636** [inotia00/ReVanced_Extended#839]
### Type

Error at runtime

### Application

YouTube 18.15.40

### Bug description

When I want to join channel member, but it's blank even though was already turned off.

### Steps to reproduce

Step 1. Find any YouTube channels has join button.
Step 2. None of this page of YouTube channels member 

### Relevant log output

```shell
None
```

### Screenshots or videos

![Screenshot_20230424_155213_ReVanced Extended](https://user-images.githubusercontent.com/101686823/233948422-084274b6-f1be-4ac8-a0fd-93e391e2b2eb.jpg)
![Screenshot_20230424_155227_ReVanced Extended](https://user-images.githubusercontent.com/101686823/233948440-566a19ee-548e-4298-bb47-51371d419ac4.jpg)

### Solution

None

### Additional context

None

### Device Environment

Android 13, One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
not reproduced

Also, it is normal that this feature does not work in microg builds
