### ISSUE TITLE
feat(patch): add option to play all videos in channel

### ISSUE THREAD

**Issue by boognish-rising** [inotia00/ReVanced_Extended#84]
### Application

YouTube

### Issue

YouTube has progressively made it more and more difficult to play all of a given channel's videos/uploads at once. All I'm proposing is a patch to solve for YouTube. More recently removing this functionality from the platform. 

If there are limitations that make any of this (and/or the following) difficult or impossible to achieve or a different route needs to be taken in order to achieve it, by all means. I leave it up to you to decide whether this is a worthwhile endeavor in the first place and I trust your discretion implicitly. 

Thank you very much for everything you've done to continue carrying the torch and especially doing so in such a way that safeguards the project in ways that the original didn't. Everything everyone does to contribute is massively appreciated and I will gladly contribute in any way possible, financially or otherwise as soon as the opportunity to do so presents itself.

PS - I did perform a search for "play all" and saw nothing, but I apologize if there's a similar issue elsewhere in one of the other repos or with a slightly different issue title

### Patch

In classic YouTube/Google fashion, they love introducing/removing features that nobody wants or asked for - taking away the ability to easily play all videos from a channel is just one example of many across all of the services Google offers, but even if you just focus on YouTube and YouTube Music, there are more than enough examples to go around, especially when you also consider Google Play Music. That said, I'm really focusing specifically on YouTube here. It used to be easy, with a dedicated "Play All" button and then they took that away for the most part, however for a while you could still trick YouTube into playing all videos with some URL formatting hacks but it seems that most of those have been deprecated as well. It's difficult if not impossible, regardless of whether you're on desktop or not, but unless I'm mistaken, I don't see any way to play all videos on mobile beyond what is presented under the "popular" and/or "recently uploaded" sort-by criteria (under the "videos" tab on any channel's page).  It would be awesome if among many other firsts, YouTube ReVanced introduced this sort of functionality and not that it's in need of anything for the purposes of attracting users beyond what it already offers, those already using it stand to benefit, which I'll get into more in the *Motivation* section

### Motivation

 I imagine that beyond just myself, others, too would appreciate the ability to simply hit a "PLAY-ALL"  button and have a playlist with all of the videos from any given channel page instantly created/added to their playback queue. The ability to then save that playlist for easy access/reference later would be awesome as well, especially if it auto updated so that anytime you clicked on the saved playlist, it featured all of the channel's videos, including those uploaded after the playlist was originally saved. However, this is just "icing on the cake" bonus/extra stuff; I'd be more than happy, thrilled actually, if there was *any* sort of functionality that would help us achieve the ability to play all, even if that meant no ability to save and/or auto-update, etc. All of this being said, I have no idea what is required/ goes into making this a reality and am well aware that it's possible that no amount of time and effort could bring this to fruition if it's simply impossible to do with the current state of things. If this were the case then I understand and am sympathetic/sensitive to the limitations and confines necessary to observe and work within. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by boognish-rising** [comment]
Sorry for the typo

**Comment by boognish-rising** [comment]
If this is more appropriate to be submitted in a ReVanced repository rather than ReVanced Extended (or anywhere else for that matter), just let me know and I'd be happy to do so

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
