### ISSUE TITLE
feat(patch): hide Library tab

### ISSUE THREAD

**Issue by ianmatt** [inotia00/ReVanced_Extended#842]
### Application

YouTube

### Issue

Cosmetic

### Patch

If possible, please also add a patch to hide the Library tab

[v2.169.5](https://github.com/inotia00/revanced-patches/releases/tag/v2.169.5) already ads two patches hide-home-button, hide-subscriptions-button for selectively hiding Home and Subscriptions tabs

Thanks!

![lib2](https://user-images.githubusercontent.com/28786798/234166134-b5898ef7-9f38-44bf-bc5b-4af5f94f2c60.png)

### Motivation

Completeness...

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment]
Also option to hide navigation bar too.

#651

**Comment by s7san007** [comment]
Add a patch to hide the Explore tab too.

**Comment by inotia00** [comment]
In theory this is possible, but removing all the tabs in the navigation leaves an empty space

I didn't add a patch to remove the library tab, as the patch to remove the navigation bar hasn't been implemented yet.

**Comment by Metallifani666** [comment]
Im not hiding all the buttons from my navigation bar, only subscription and library if possible, and only keep the home button visible.

Like @ianmatt wrote, this would complete navigation bar customization.

PS: Thank you for all your hard work.

**Comment by ianmatt** [comment]
yes, same here, I only want to hide Library and if possible to add this one too in the hiding switches, great

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.173.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.2)
