### ISSUE TITLE
feat(patch): Hide empty bar

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#844]
### Application

YouTube

### Issue

hiding the empty bar is not possible after upgrading from v18.07.35
![example](https://user-images.githubusercontent.com/36302515/234176343-446c504b-b2ed-46a6-8184-f6fdd37453d0.jpg)

### Patch

same thing as custom seekbar color but for the other empty bar or just a patch to hide it and that's it

i like to hide the seekbar and the empty bar and make it appear only by tapping on the screen just like NewPipe

### Motivation

i can't change the color of the empty bar manually using MT Manager, last version i can change the color of the empty bar is v18.07.35, the new versions is not possible so a patch to hide the empty bar would be great

inline_time_bar_colorized_bar_empty_color_dark
![IMG_20230425](https://user-images.githubusercontent.com/36302515/234175891-f76c1edf-93df-4cc5-9e15-70d97c06b213.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by BrilliantlyEducated** [comment]
i like to hide the seekbar and the empty bar and make it appear only by tapping on the screen just like NewPipe


https://github.com/inotia00/ReVanced_Extended/assets/36302515/97229ecb-5f24-492a-b626-a3503dae94b0

**Comment by BrilliantlyEducated** [comment]
i like to hide the seekbar and the empty bar and make it appear only by tapping on the screen just like NewPipe

https://github.com/inotia00/ReVanced_Extended/assets/36302515/52439c27-61f9-4a86-bd9d-64a4ed5a42c2

https://github.com/inotia00/ReVanced_Extended/assets/36302515/3213aaf7-ff0c-447d-a48e-555731aba063

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
