### ISSUE TITLE
question: Dark / Black theme

### ISSUE THREAD

**Issue by Hennadz** [inotia00/ReVanced_Extended#845]
### Application

YouTube

### Description

Many people asked about dark theme instead of black. Every time was the answer to exclude the theme patch. But Youtube is then colored in jet black. The settings menu becomes really dark ReVanced Extended, RYD And SB.
I analyzed the files Colors.xml and I see that the Theme patch makes changes to where the original YouTube is still so black without the Theme patch.
I specifically patched with a lighter tone (ff222222) to show the differences.

This screenshot with applied patch (ff222222)
![20230424_234145](https://user-images.githubusercontent.com/130844239/234221207-468da990-ae69-4876-99f4-c901fa9e5c51.png)

Like this without a patch Theme
![Screenshot_20230424-234440_ReVanced Extended](https://user-images.githubusercontent.com/130844239/234223730-f7bfd411-1079-4f15-ae46-70cbda7cde89.png)

![Screenshot_20230425-114737_ReVanced Extended](https://user-images.githubusercontent.com/130844239/234224510-3fe08234-be24-494e-b36f-dec98f4c2c4d.png)

![Screenshot_20230425-111740_ReVanced Extended](https://user-images.githubusercontent.com/130844239/234224595-bbe4f422-4cb5-4b93-a78a-8364f6d3f0c6.png)

![Screenshot_20230425-111819_ReVanced Extended](https://user-images.githubusercontent.com/130844239/234224863-9719cb43-9b17-48d4-bb51-27274ea1b8ca.png)

I use Revancify, but checked with rvx-builder.sh.
It's not difficult for me to color YouTube in any color.But everywhere dark (ff212121) obtained only by entering the color code in options.toml file.
Or am I doing something wrong?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
You can use the dark theme through the following method.

1. Exclude `theme` patches
2. Turn on 'Enable old layout' in settings

※ In the new layout, the black theme is enforced on the server side, so the dark theme is valid only in the old layout.

If you followed this process, you can use the dark theme as in the attached screenshot

![0426073327737643](https://user-images.githubusercontent.com/108592928/234419159-ed4f1d07-5019-4cd7-9fa1-2e6c0d040eec.jpg)
