### ISSUE TITLE
feat(patch): Hide video preview in search history

### ISSUE THREAD

**Issue by No-Hammer** [inotia00/ReVanced_Extended#846]
### Application

YouTube

### Issue

Add patch for hide video preview in search history.
![photo](https://user-images.githubusercontent.com/31363294/234263985-e33cc714-9a05-4862-ae94-b6ac30ddd6eb.png)

### Patch

I attach two files, original and patched class, you can find changes by "hide_suggestion_search_preview".
[khh_v18.15.38_original.smali.txt](https://github.com/inotia00/ReVanced_Extended/files/11322049/khh_v18.15.38_original.smali.txt)
[khh_v18.15.38_patched.smali.txt](https://github.com/inotia00/ReVanced_Extended/files/11322050/khh_v18.15.38_patched.smali.txt)

### Motivation

I think that many users would like to get rid of these preview, so I see no reason to refuse a useful patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.196.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.1)
