### ISSUE TITLE
feat(patch): Display posts in "posts", even if they are hidden elsewhere

### ISSUE THREAD

**Issue by R0M4N0F5K7** [inotia00/ReVanced_Extended#847]
### Application

YouTube

### Issue

Usually I don't care about community posts, but I saw now that there is a dedicated category under "subscriptions". Having turned posts off in the revanced settings makes this category load endlessly. There seems to be a native flag that confides posts to this category though.

### Patch

Under "settings" at the end of the categories there is the option to select to generally only display videos, which will still and exclusively allow me to check them in the "posts" category. Downside here: This setting seems to reset to show "videos and posts" after every app restart.

![Screenshot_20230425-183853~3](https://user-images.githubusercontent.com/15329506/234347321-f8bcf3ab-03cb-4f74-944c-f3162ea5839e.png)

### Motivation

With the current revanced settings we can decide to hide posts completely or get them in every category. It would be neat if we could still check them in the posts category if we feel like it, while keeping them out of all other categories, where we only care about videos. Maybe just overwriting the native flag to display videos only (which seems to already deliver the desired functionality) would even save some resources compared to filtering them constantly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/323
