### ISSUE TITLE
feat(patch): the header should be applied according to the custom-branding-icon patch implemented.

### ISSUE THREAD

**Issue by bw003** [inotia00/ReVanced_Extended#85]
### Application

YouTube

### Issue

Just like youtube music where the header also changes to  red icon when applying the custom-branding-music-red patch. Same feature should be applied to youtube. It is possible as force-premium-heading patch also does kinda same thing.

### Patch

Just like youtube music where the header also changes to  red icon when applying the custom-branding-music-red patch. Same feature should be applied to youtube. It is possible as force-premium-heading patch also does kinda same thing.

### Motivation

Just like youtube music where the header also changes to  red icon when applying the custom-branding-music-red patch. Same feature should be applied to youtube. It is possible as force-premium-heading patch also does kinda same thing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by anil-al** [comment]
I do like Revanced icon but do not want to see it in the app header all the time. The original is plain and fits to the design. If this will be done, consider doing it optional.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
