### ISSUE TITLE
feat(patch): in-app updater

### ISSUE THREAD

**Issue by abdogm** [inotia00/ReVanced_Extended#850]
### Application

YouTube

### Issue

not an actual issue. its more like a feature request.

### Patch

I've been hinking about what if revance dextended had an in-app updater like when ever there an update, you will get a pop up message telling you there is an update available while displaying the current version and what is the latest version with the changelog, and a download button that will download the latest version for you by one of these two methods.
1. downloading the latest version from the app itself (should detect if its root or non-root variant).
2. opens the browser and redirect you to the page of where you can find the latest version.

(you might see grammar issues because english is not my native so sorry for that)

### Motivation

i always check if there is a new update or not but before doing that i was using an outdated version for a long time while i had no idea this app still getting updates

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/848

**Comment by abdogm** [comment]
> #848

then what about something like a telegram channel to post latest news/updates
that would be neat

**Comment by inotia00** [comment]
I already have a Github notification channel
https://t.me/revanced_extended_repo

**Comment by abdogm** [comment]
> I already have a Github notification channel https://t.me/revanced_extended_repo

then i guess i am living under a rock
thanks a lot and sorry if i was annoying or something 
much appreciated
