### ISSUE TITLE
feat(patch): ability to toggle sponsor block in Player

### ISSUE THREAD

**Issue by fedonr** [inotia00/ReVanced_Extended#851]
### Application

YouTube

### Issue

Sometimes the part of video where a product is reviewed is sponsored or youtubers brand itself it blocked by sponsor block.

### Patch

To be circumvent such issue a toggle button to switch on/off sponsor block in player itself would be great.

### Motivation

Issue itself made me wonder about it. Plus patches like Playback speed and Auto repeat implemented in player lead me to think about it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ganeshchk** [comment]
Yes, it would be really useful on some circumstances when we want to watch some specific parts (ie; intros, end cards etc. ) of a particular video but want to be remain blocked for others
