### ISSUE TITLE
question: <do you have a website? >: 

### ISSUE THREAD

**Issue by ibrahimashraf** [inotia00/ReVanced_Extended#852]
### Application

YouTube

### Description

Does this website related to your project?
https://revancedextended.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Hennadz** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/780
