### ISSUE TITLE
Suggestions about modifying Revanced extended settings layout

### ISSUE THREAD

**Issue by Mohammedibrahim15** [inotia00/ReVanced_Extended#855]
### Application

YouTube

### Description

![Screenshot_20230426_203816_app revanced android youtube_edit_80058032340907](https://user-images.githubusercontent.com/130897201/234672014-423e4114-b234-4d48-b4ec-057d255182bc.jpg)
![Screenshot_20230426_203813_app revanced android youtube_edit_80045581992993](https://user-images.githubusercontent.com/130897201/234672019-3a80e38a-c21f-4933-91fb-46939bf4bdfe.jpg)
Could Revanced extended layout be matched with official Revanced.. in official Revanced the main settings category is only 4 .. inside each of them there are list of settings included .. i think it is much more pretty and more organized. There is also lines of separation between each element.. unlike in RVX there is many settings categories with no line of demarcation . And the features exclusive to RVX could be put inside a category called Revanced Extended .. it is just a suggestion but RVX is excellent project 🥰

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
There are too many features in Extended to fit into four categories.

Even now, it has gone through a lot of refactoring of the setting UI, so it is close to impossible to roll back to the previous one.

If you prefer 4 category labels, just use the official ReVanced
