### ISSUE TITLE
feat(patch): Add Download button to Shorts

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#858]
### Application

YouTube

### Issue

Please add download button to Shorts. 

YouTube's  share menu to powertube takes too many annoying steps. Having to look for the PowerTube logo everytime in the share menu and it even changes it's position every time...
Adding a Download button to Shorts would make it much easier!

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
