### ISSUE TITLE
question: <title>: video stop

### ISSUE THREAD

**Issue by Yuukiiiz** [inotia00/ReVanced_Extended#859]
### Application

YouTube

### Description

my youtube videos are stopping and getting black from the nd, how can i fix this ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
turn on `Enable protobuf spoof`
