### ISSUE TITLE
feat(patch): Improve YouTube's Video Title

### ISSUE THREAD

**Issue by ImpenetrableNoble** [inotia00/ReVanced_Extended#86]
### Type

Cosmetic

### Application

YouTube version 17.49.37

### Bug description

Each long title video on YouTube show me three dots.

### Steps to reproduce

Improve YouTube's video title patch. 

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_20230101_115017](https://user-images.githubusercontent.com/104534608/210178809-022ffa18-f765-4308-8f72-33ad8ae05288.png)

### Solution

Resolve issues that deals with long titles that makes us see three dots. 

### Additional context

Three dots from each YouTube's title video I watch doesn't let me see the full title of the video.

### Device Environment

Android 12

Samsung Galaxy a21

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Eiskrem** [comment]
Good suggestion. This needs a fix indeed.

**Comment by inotia00** [comment]
Why is this bug? Is it not reproduced in Stock YouTube, but is it only reproduced in Revanced?

**Comment by Eiskrem** [comment]
It shouldn't be labeled as bug. But rather patch request.

**Comment by TheGoldenSun** [comment]
Apologies as I don't know how to change the label "bug" to "patch request"
on GitHub, is someone able to do it for me?

**Comment by Mohammed1520** [comment]
Is there any progress about this patch?

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
