### ISSUE TITLE
bug: <revanced>

### ISSUE THREAD

**Issue by Nate-Higgers666** [inotia00/ReVanced_Extended#860]
### Type

Error at runtime

### Application

2.166.24

### Bug description

Закрудает минуту видеоролика и далее бесконечная загрузка

### Steps to reproduce

Включить видео
Прогрузка-серая полосочка
Красная полоска догоняет серую и бесконеная загрузка

### Relevant log output

```shell
Что это такое
```

### Device Environment

Miui 12.5.5 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment]
And it was absolutely necessary to go with a racist username, wasn't it?
