### ISSUE TITLE
bug: <title> Patchers not working on inotia00 sources

### ISSUE THREAD

**Issue by baigrawaha** [inotia00/ReVanced_Extended#861]
### Type

Error while patching

### Application

YouTube 18.15.40

### Bug description

I have been using Revanced Manager and Rvx Revanced Builder. Both these patchers are patching fine with "revanced" sources. But when i am trying patching with 'inotia00" the patching fails. 

errors in revanced builder are in the following fields.

### Steps to reproduce

Step 1. launch Revanced Builder and set inotia00 as sources
step 2. Select any patch
step 3. bug will appear

### Relevant log output

```shell
`SEVERE: hide-shorts-button failed: app.revanced.patcher.patch.PatchResultError: 'hide-shorts-button' depends on 'settings' but the following error was raised: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)`
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment]
I just tested patching with revancify, 0 errors.

**Comment by inotia00** [comment]
cli, revancify, rvx-builder, ReVanced Manager all work fine
I don't know why you are failing to patch, so try the other methods provided
