### ISSUE TITLE
feat(patch): custom video buffer

### ISSUE THREAD

**Issue by OmerKurdi79** [inotia00/ReVanced_Extended#862]
### Application

YouTube

### Issue

For people who do not have a stable internet speed, they can watch YouTube clips more smoothly and face less interruptions due to poor internet conditions. 

### Patch

There was an option to select a pre-download percentage of videos in the YouTube Vanced app, so I want to see this option back again 

### Motivation

Maybe it's just me i don't know,
but it should be a useful option for everyone who suffers from bad internet around the world 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
