### ISSUE TITLE
не грузит видеоbug: <title>

### ISSUE THREAD

**Issue by 0werewolf0** [inotia00/ReVanced_Extended#863]
### Type

Other

### Application

17.28.35

### Bug description

видео показывает 10 секунд потом до безконечности его грузит! если сменить видео то происходит тоже самое!

### Steps to reproduce

1

### Relevant log output

```shell
1
```

### Screenshots or videos

![Screenshot_20230427_152635_YouTube](https://user-images.githubusercontent.com/52673216/234860411-cdcc04d4-9a62-4ab1-a812-f2b86ec0db8a.jpg)
![Screenshot_20230427_152628_YouTube](https://user-images.githubusercontent.com/52673216/234860417-1c6c045b-6c75-4696-be0e-8332cc2b3355.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
v17.28.35 is not supported
