### ISSUE TITLE
Revanced Extended autorotate bug: <title>

### ISSUE THREAD

**Issue by deep-l** [inotia00/ReVanced_Extended#864]
### Type

Cosmetic

### Application

Revanced Extended 18.15.40
POCO f3, miui 14

### Bug description

When rotating phone to the right (to horizontal) in full screen video, video doesn't rotate, when rotating phone to the left it's work.

Feature supposed to work with rotating lock switch in system settings.
When in settings i turn off rotation lock, turning phone to the right and left rotating video properly, but it's supposed to work with rotating lock on. 

### Steps to reproduce

I don't know 

### Relevant log output

```shell
N/a
```

### Screenshots or videos

N/a

### Solution

N/a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
YouTube's issue, not ReVanced Extended's issue

**Comment by Spacellary** [comment]
@inotia00 Is this a situation like this one? -> https://github.com/inotia00/ReVanced_Extended/issues/429#issuecomment-1459552898

**Comment by inotia00** [comment]
yep
