### ISSUE TITLE
feat(patch): Patch for older Youtube Versions

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#865]
### Application

YouTube

### Issue

Revanced Youtube is too laggy on my Thrash Phone.

### Patch

Patch Support for older version of Youtube (v16.xx.xx). I tried the original Youtube app v16.xx.xx and it still works so I hope its also possible to make revanced using that version.

### Motivation

A lot of people in developing countries use low-end budget phones. Those budget phones are too laggy to run the newest versions of Youtube (18.xx.xx).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Outdated versions are not supported. also, there are no plans to support it in the future.

**Comment by Stale-1** [comment]
> Outdated versions are not supported. also, there are no plans to support it in the future.

That's unfortunate, btw may I ask is there a way for me to use the Old patch version that supports Youtube 17.xx.xx in the ReVanced Manager on Android?

Does using the old patches also requires to use an older ReVanced Manager?
