### ISSUE TITLE
hide-cast-button patch is included when not selected

### ISSUE THREAD

**Issue by nitinn05** [inotia00/ReVanced_Extended#866]
### Type

Error while patching

### Application

Current version details
YouTube: 18.14.41
revanced-patches: 2.168.42
ravanced-integrations: 0.102.2

### Bug description

Using the `--exclusive -i` method to include specific patches. Even if the `hide-cast-button` patch is not included it gets applied automatically while the command promt shows patch skipped.

### Steps to reproduce

Patch using `--exclusive -i` method and skip `hide-cast-button`. The prompt shows patch skipped but actually gets included anyway.

### Relevant log output

```shell
-
```

### Device Environment

Android 12, Motorola

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Hennadz** [comment]
I confirm.

App: YouTube-18-15-40.apk
CLI: inotia00-cli-v2.21.0.jar
Patches: inotia00-patches-v2.169.5.jar
Integrations: inotia00-integrations-v0.102.6.apk

![Screenshot_20230427-201235_X-plore](https://user-images.githubusercontent.com/130844239/234938680-3cf53ea5-fdb2-444e-9019-acd0023ddf68.png)
However, the button in the settings is disabled.

**Comment by inotia00** [comment]
this is not a bug
If you include the `microg-support` patch, the `hide-cast-button` patch is also included (it has dependencies)

**Comment by consal** [comment]
> this is not a bug If you include the `microg-support` patch, the `hide-cast-button` patch is also included (it has dependencies)

So, it's impossible to have the cast button on a non-rooted phone?
