### ISSUE TITLE
Video is playing for like 10s, then infinite loading

### ISSUE THREAD

**Issue by Cnfnbcn** [inotia00/ReVanced_Extended#867]
### Type

Error at runtime

### Application

YouTube 18.05.34
Revanced patches 2.159.4
Revanced integrations 0.95.4

### Bug description

Start app, start any video or stream. For a while (10s to 60s) it plays as usual, then infinite loading happens.

### Steps to reproduce

1. Open revanced.
2. Start video.
3. Wait for 2 minutes.

### Relevant log output

```shell
I've no idea where logs are😐
```

### Solution

Restart app. Then happens again and again.

### Device Environment

Android 12, Realme UI 3.0, phone – RMX3370

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
protobuf-spoof

**Comment by Cnfnbcn** [comment]
> protobuf-spoof

What?

**Comment by inotia00** [comment]
enable `protobuf spoof` toggle
