### ISSUE TITLE
Play speed of 4x and 3.5x

### ISSUE THREAD

**Issue by andzzz3** [inotia00/ReVanced_Extended#868]
### Application

YouTube

### Issue

I want a little more variety in playback speed. Now, 3x is followed by 5x, but I want a 3.5 and 4.0. If possible, 6x and 8x would be great.

### Patch

about playback speed

### Motivation

I usually use 4x when I listen to the news on my PC.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
features already implemented
