### ISSUE TITLE
feat(patch): Disable new splash animation 

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#869]
### Application

YouTube

### Issue

Apparently YouTube for Android will soon have the splash animation originally deriving from their Android TV app.
https://www.androidpolice.com/youtube-new-splash-screen-android/#Echobox=1682353000

https://twitter.com/MasshiroTenmei/status/1649699965600694272

This animation will cause a longer app booting time and will take longer to get into the actual app and WATCH VIDEOS. That's what we are using YT for and not to watch fancy long animations.

Please add a patch that disables this animation.

**Comment by androidghosh** [comment]
An option to turn this patch on/off would be better

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)

Include `enable-new-splash-animation` and turn off `Enable new splash animation`
