### ISSUE TITLE
feat(youtube/overlay-buttons): Move Overlay Buttons to Bottom Players

### ISSUE THREAD

**Issue by Yola-cola** [inotia00/ReVanced_Extended#870]
### Application

YouTube

### Issue

I like the overlay buttons, but they take too much space in portrait mode.

![20230427_132727](https://user-images.githubusercontent.com/53379032/234948768-9e28c309-40ee-4563-adeb-e31992659ff1.jpg)
Like this ^

### Patch

![IMG_20230427_131949](https://user-images.githubusercontent.com/53379032/234944879-ab528ad0-3cc3-435d-96f9-dfa238f1dd9d.jpg)

My solution is to simply add the option to move them to the bottom player 

### Motivation

There's a lot of benefits for this.
No more pressing them by mistake.
The overlay hud would look much clearer
The bottom player download button would be useful again.
And it looks more visually pleasing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
