### ISSUE TITLE
question: <title>: video fullscreen

### ISSUE THREAD

**Issue by Khalie15** [inotia00/ReVanced_Extended#872]
### Application

YouTube

### Description

I put the video in fullscreen but then I leave the app for a few seconds and when I tap back on it it just get me out of fullscreen. And it happens everytime I switch apps even for a bit is there an option other than minimise playback because I don't want it to stay open whwn I switch apps but I want it to stay in fullscreen when I tap back on it just like the other apps

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
that's a recent YouTube change.

no option to keep fullscreen

**Comment by mexon86** [comment]
> that's a recent YouTube change.
> 
> no option to keep fullscreen

sorry for couple quote reply but so you cant make a patch for it ?
