### ISSUE TITLE
bug: Video stop and load infinitely 

### ISSUE THREAD

**Issue by mrgame12310** [inotia00/ReVanced_Extended#873]
### Type

Error at runtime

### Application

Revanced

### Bug description

When I watch a video after 30-90 seconds the video stop and show the thumbnail and load but if I restart the video where it stop it just continue and redo the same thing

### Steps to reproduce

Watch a video

### Relevant log output

```shell
Where do I get the log ?
```

### Solution

If possible any ?

### Additional context

I have activate spoof but nothing changes
Version: 17.30.34

### Device Environment

MIUI Global 13.0.9 Stable

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
repatch with latest resources and turn on `Enable protobuf spoof`

**Comment by mrgame12310** [comment]
I have a question I see so many site to revanced what is the real one pls ?

**Comment by inotia00** [comment]
All websites other than github are illegal

because i don't distribute prebuilt apk

read [documentation](https://github.com/inotia00/revanced-documentation/wiki)

and this comments https://github.com/inotia00/ReVanced_Extended/issues/848#issuecomment-1522512573
