### ISSUE TITLE
bug:With the latest patches captions are again shown at the top when activating Protobuf

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#875]
### Type

Cosmetic

### Application

Youtube 18.16.37

### Bug description

With the latest patches captions are again shown at the top when activating Protobuf

### Steps to reproduce

Set Protobuf on
Start captions
Captions is displayed at the top

![Screenshot_2023-04-28-11-59-40-821_app rvx android youtubf](https://user-images.githubusercontent.com/125223735/235119132-f3df4534-cb97-4f47-ac4d-0c2515294e05.jpg)

### Relevant log output

```shell
Na
```

### Device Environment

Android 11
Miui 12.5 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Hennadz** [comment]
Somehow through the restart it is unstable.

![20230428_144217](https://user-images.githubusercontent.com/130844239/235138939-26917987-980f-4de1-95c2-db270c5c1c54.png)

![Screenshot_20230428-144001_MyTube](https://user-images.githubusercontent.com/130844239/235138956-07f59f0b-a01e-42de-8cae-4df0f7724331.png)

Samsung Galaxy S9+
Android 10
YouTube v18.16.37
v2.171.1

**Comment by jhon1282** [comment]
Additional information :This issue is only for the first video, the next video often captions return to the bottom.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.171.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.171.2)
