### ISSUE TITLE
question: <title>: how to turn off background play in turn off screen

### ISSUE THREAD

**Issue by Kaaiauayahwhh** [inotia00/ReVanced_Extended#876]
### Application

YouTube

### Descriptions
How to turn off background play on turn off screen

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Settings > Background > Playback > off
