### ISSUE TITLE
bug: PowerTube recently often doesn't work...

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#877]
### Type

Error at runtime

### Application

Version 18.16.37 non-root

So recently I've been often times unable to download videos with PowerTube. It often time spits error, after letting me wait for around 10secs. It happens w MANY VIDEOS where it's unable to download:
![Screenshot_20230428-125306352 (1)](https://user-images.githubusercontent.com/73917917/235129757-3f877cbf-32b7-4132-9353-e73620b0aa8b.png)

Example video it can't download:
https://youtu.be/3ZY2DkJpeGc

**Comment by inotia00** [comment]
This is not a PowerTube repo
