### ISSUE TITLE
bug: YouTube music 'Exclusive Audio Playback' patch doesn't work

### ISSUE THREAD

**Issue by Issam28** [inotia00/ReVanced_Extended#878]
### Type

Error while patching

### Application

YouTube music

### Bug description

The patch "Exclusive Audio Playback" doesn't work. For some songs that have video. It will automatically play the video.

### Steps to reproduce

/

### Relevant log output

```shell
/
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This patch is no longer compatible with the latest YT Music
(yeah.. this patch is quite old)

Since a fix is impossible, I will remove this patch in the next release.

**Comment by Issam28** [comment]
Ok that makes sense. Thank you for your quick reply.

**Comment by inotia00** [comment]
never mind
I tested it a while ago and it's still a valid patch

![0428210836398725](https://user-images.githubusercontent.com/108592928/235144640-12a4e8fd-fb46-4ebf-ae9e-68c1c598106a.jpg)

Left image: when the patch is excluded
Right image: when the patch is included

You can see that `Don't play music videos` toggle has been added.

I misunderstood that this patch was a setting added to ReVanced Extended settings

so.. this is still a valid patch

**Comment by Issam28** [comment]
Oh I didn't know that there was a toggle for it. I can't test it now since the settings page is crashing so you may want to look into that as well.
