### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Cyxcix** [inotia00/ReVanced_Extended#879]
### Type

Other

### Application

Revanced Extended v18.15.40 And other versions

### Bug description

When entering a video, and keeping your eyes fixed on it for a few minutes, when suddenly the loading icon appears. 

![Icono de Carga](https://user-images.githubusercontent.com/123632625/235129093-80cf403e-b4f1-4ab7-a706-4bda0ee76744.gif)

### Steps to reproduce

null

### Relevant log output

```shell
null
```

### Screenshots or videos

![300x300](https://user-images.githubusercontent.com/123632625/235132030-1f110d71-6ac8-4389-bc11-0fa01f696c32.jpg)

https://user-images.githubusercontent.com/123632625/235105599-0fa18e45-35b7-47e7-86be-740b4fadffad.mp4

### Solution

null

### Additional context

My internet is 200 mb, I already tried uninstalling the APP and reinstalling it. I have even installed other versions, but it still gives the same result.

I don't think it's a problem with my device, since previously the progress bar didn't get stuck.

I have also uninstalled MicroG, but it still gives the same result.

I hope you can give me some solution, since this is what this beautiful community is about.

### Device Environment

My device is an OPPO Reno 6 Lite Model CPH2365 ColorOS 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
try turning on `Enable protobuf spoof`

**Comment by Cyxcix** [comment]
I don't know what happened here, I would swear I had deactivated and activated that option, and the error was not corrected.

It is the first thing that came out when I installed the latest version of revanced-extended, a message.

-Thank you.
