### ISSUE TITLE
feat(patch): Black Theme for Cast Pop-up

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#88]
### Application

YouTube Music

### Issue

As the title suggests, the cast option in YouTube Music is grey in colour while the entire other UI element is amoled black. A patch to make this theming uniform would be nice.

### Patch

An option or just making it the default theme in YouTube music just like the navigation bar.

### Motivation

The same way as the navigation bar was made black for uniformity, this would further that purpose if implemented.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceAppications** [comment]
![Screenshot_20230102-183422~2](https://user-images.githubusercontent.com/117499019/210235465-47cc678e-70f6-4d20-8593-a1cb6e201a91.png)

**Comment by ILoveOpenSourceAppications** [comment]
Is this doable or is it not possible @inotia00 ?

**Comment by ILoveOpenSourceApplications** [comment]
With `amoled` patch this patch request is completed. Hence closing this issue.

**Comment by inotia00** [comment]
lol I forgot this issue

**Comment by ILoveOpenSourceApplications** [comment]
Well, atleast it's implemented without you even requiring to remember about it. So all's good.
