### ISSUE TITLE
question: Are you going to bring back lift-vertical-video-restriction patch?

### ISSUE THREAD

**Issue by Yola-cola** [inotia00/ReVanced_Extended#883]
### Application

YouTube

### Description

I saw that you removed it in the previous patch and now some video don't play the video.

Are you gonna add it back or are you reworking it?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Yola-cola** [comment]
> `lift-vertical-video-restriction` patch has been designated as `Expermiental Flags` since it was first added.
> 
> Therefore, it is not strange if it is removed at any time
> 
> For most people the patch is not valid and there are no additional fixes so I just removed it

Well it work for me. I'm using a galaxy S9 videos with really low quality don't work with me without that patch. 
Is there a way I can add the patch back for personal use?

**Comment by inotia00** [comment]
It is difficult to re-implement the same patch as before, as it has also been removed from the crowdin resource

Instead, I could incorporate it into the `force-vp9-codec` patch

**Comment by Yola-cola** [comment]
> It is difficult to re-implement the same patch as before, as it has also been removed from the crowdin resource
> 
> Instead, I could incorporate it into the `force-vp9-codec` patch

That would be amazing thank you so much!

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.171.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.171.2)
