### ISSUE TITLE
feat(patch): Add Sponsorblock browser button to RVX

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#884]
### Application

YouTube

### Issue

So this is last thing OG Vanced has and RVX doesn't. It would be more convenient with it and not needed to copy and paste video url manually to sb.ltn.fi every time. Well not full url, only video ID part. For example, not this https://youtu.be/gSDtNkKPiDg, just this gSDtNkKPiDg. It doesn't work with full url.

![20230424_140357](https://user-images.githubusercontent.com/132079771/235179128-0983202d-3b4f-4aac-8738-8f8d0d1ef0a4.png)

![20230424_140431](https://user-images.githubusercontent.com/132079771/235179280-9a8fb9ec-04d2-4815-b180-a76abd6b2ff9.png)

### Patch

This button links to sb.ltn.fi to see more info about sponsorblock segments of that video.

### Motivation

It would make use of this app slightly more simple.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by NoMorePizza** [comment]
I have been told that RVX sponsorblock code follows stock Revanced code, so should I request this in ReVanced repo?

**Comment by inotia00** [comment]
It would be nice to leave the same patch request in the official ReVanced repo

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
