### ISSUE TITLE
bug: Put a space between address and bracket

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#886]
### Type

Cosmetic

### Application

Latest

### Bug description

It is not actually a bug but a typo

There should be a space between the word _address_ and the bracket to separate one word from another
![Screenshot_20230423_200605_YouTube](https://user-images.githubusercontent.com/130296934/235143791-349cda76-fa13-4ab5-9653-be3ba2d01b67.jpg)
Just add a space between the word address and the bracket for both the title and subtitle of the above option, example:
**Hide email address (handle)**
**Email address (handle) is shown**
**Email address (handle) is hidden**

### Steps to reproduce

Nothing

### Relevant log output

```shell
Nothing
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.171.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.171.2)
