### ISSUE TITLE
Video keeps on buffering 

### ISSUE THREAD

**Issue by IshuPrabhakar** [inotia00/ReVanced_Extended#887]
### Type

Error while patching

### Application

YouTube v18.08.39

### Bug description

When I play any video it plays smoothly for atleast 10 seconds after that it starts buffering for atleast 30-40 seconds to play again.

### Steps to reproduce

Step 1) Open patched YouTube app.
Step 2) tap on any video.
Step 3) play it atleast for 10 seconds.

### Relevant log output

```shell
-
```

### Device Environment

Android 12, Miui 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/781
