### ISSUE TITLE
bug: <title> Submitting sponsorblock segment at end of the video fails

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#888]
### Type

Error at runtime

### Application

Youtube v18.16.37
Patches 2.171.1

### Bug description

When I'm trying to submit a sponsorblock segment that ends at the very end of the video, nothing happens. After it failed, no more segments can be added, video has to be closed and opened to do so. Obviously I can't add segment that ends where video ends. None of this happens in stock ReVanced.

### Steps to reproduce

Step 1. Set a segment that ends at very end of the video, preview it, choose correct category and press ok.

### Relevant log output

```shell
None
```

### Screenshots or videos

For some reason I can't add screen recording.

### Additional context

I don't know how to add log output, sorry about that.

### Device Environment

Android 13 
One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
RVX's SponsorBlock code now completely follows the official ReVanced's code

Therefore, even if you report a SponsorBlock related issue here, there is nothing I can fix.

SponsorBlock-related issues that occur in RVX also occur in official ReVanced

Since SponsorBlock is completely rebased by ReVanced Team, you will need to report the issue to the ReVanced repo to be able to fix it.

**Comment by NoMorePizza** [comment]
Yeah but this problem doesn't occur on stock ReVanced.

**Comment by NoMorePizza** [comment]
> RVX's SponsorBlock code now completely follows the official ReVanced's code
> 
> Therefore, even if you report a SponsorBlock related issue here, there is nothing I can fix.
> 
> SponsorBlock-related issues that occur in RVX also occur in official ReVanced
> 
> Since SponsorBlock is completely rebased by ReVanced Team, you will need to report the issue to the ReVanced repo to be able to fix it.

Ok I understand but this problem doesn't occur on stock ReVanced.
