### ISSUE TITLE
question: <title>: 

### ISSUE THREAD

**Issue by LabBanana** [inotia00/ReVanced_Extended#889]
### Application

YouTube

### Description

I do not know how to filter a video on a channel by upload date. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
sort by oldest has been removed since YouTube v17.07.34 (server side)

**Comment by LabBanana** [comment]
Thanks a lot
