### ISSUE TITLE
Remove the buttons in the button container content

### ISSUE THREAD

**Issue by speedlorenzo12** [inotia00/ReVanced_Extended#89]
### Type

Cosmetic

### Application

The newest version

### Bug description

When you disable some buttons in the impostation remains a space (is in italian but dosen't matter)

### Steps to reproduce

Disable some buttons in the impostation of revanced 

### Relevant log output

```shell
Idk what is
```

### Screenshots or videos

![Screenshot_2023-01-02-15-57-25-860_app rvx android youtube](https://user-images.githubusercontent.com/111771663/210248023-d8335d6b-3a21-4ccb-b817-793dcc4b63c1.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Duplicated issue https://github.com/inotia00/ReVanced_Extended/issues/17
