### ISSUE TITLE
feat(patch): Removing buttons from Shorts player

### ISSUE THREAD

**Issue by Rafee-M** [inotia00/ReVanced_Extended#890]
### Application

YouTube

### Issue

There are certain elements like the search, camera and menu option and the sound option which might not be needed by every user and might help reduce clutter if removed.

### Patch

It'd help reduce clutter in the shorts player if the search, camera and menu button at the top right and the sound option at the bottom right could be hidden in the Shorts player 

Buttons to be hidden:
![Screenshot_2023-04-28-12-26-05-42_d11ae654701a5fadb313ea6fa9a6836f__01__01](https://user-images.githubusercontent.com/69535896/235282247-a71f1849-64f9-4b84-9cfc-e46865a8c618.jpg)

### Motivation

I feel like it would help provide a more cleaner and immersive experience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/151
