### ISSUE TITLE
feat(patch): Remove Local restriction(South Korea)

### ISSUE THREAD

**Issue by ymister** [inotia00/ReVanced_Extended#891]
### Application

YouTube Music

### Issue

In South Korea, I cannot use YTM. 
Can you remove this Local Restriction? 

### Patch

As I mentioned above, can you remove this Local Restriction? 

### Motivation

This will just helpful to people in South Korea only. :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/615
