### ISSUE TITLE
Hi my youtube keeps loading 

### ISSUE THREAD

**Issue by SauceyJay1209** [inotia00/ReVanced_Extended#893]
### Application

YouTube

### Description

Hi my youtube revanced extended keep buffering I have the same application  on my s20 ultra but on my s22 ultra it keep buffering and I can't find  out why I reset my phone to factory settings  and still didn't work but my s20 ultra works flawwless

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
turn on `Enable protobuf spoof`

**Comment by SauceyJay1209** [comment]
Thank you
