### ISSUE TITLE
feat(patch): Remove navigation button labels

### ISSUE THREAD

**Issue by evd27** [inotia00/ReVanced_Extended#894]
### Application

YouTube

### Issue

disable/remove navigation button labels. And also realign the icons' position towards the center area, so that it doesn't stay in the upper area of the tab after the labels get removed.

### Patch

![1682758102903__01](https://user-images.githubusercontent.com/87810818/235307845-cdd169b8-cf70-4c68-9a7a-8fbd3b384e74.jpg)

### Motivation

Makes the navigation tab more cleaner.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/651

**Comment by Metallifani666** [comment]
@inotia00 

I dont think this is a dublicate becausd #651 wants to get rid off everything, this includes the buttons, texts and the bar itself - everything.

While #894 only wants to hide the labels under the buttons.

**Comment by evd27** [comment]
@inotia00 , I'm sorry I didn't specify this properly. I didn't mean the tab buttons altogether. Only the words/labels under the icons.

**Comment by Spacellary** [comment]
@inotia00 This request is specifically only about removing the labels/text component of the buttons. The icons themselves should stay. I believe this isn't the same issue as referenced.

**Comment by inotia00** [comment]
I misunderstood, this is a valid issue
