### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by coccobello02** [inotia00/ReVanced_Extended#895]
### Application

YouTube

### Issue

I noticed a problem in youtube premium the last version 18.16.37
When I open a playlist with more than 200 videos, and I go to the menu of the playlist it shows me 200 videos at the time and it doesn't show the videos at the bottom. This is really annoying if you are looking for a specifc video at the bottom of the playlist. I'm adding the screenshots of an example

### Patch

![Screenshot_20230429_173552](https://user-images.githubusercontent.com/90071653/235311111-2e5b62fa-1ed7-4607-93b6-2baad0d03983.jpg)
![Screenshot_20230429_173602](https://user-images.githubusercontent.com/90071653/235311119-ba2ed043-1f81-4871-a764-406f70ec1c3b.jpg)
![Screenshot_20230429_173546](https://user-images.githubusercontent.com/90071653/235311125-3b88a184-a823-473b-acd9-2669c09e471e.jpg)

### Motivation

Problematic feature 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment]
🤦‍♂️

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/896
