### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by coccobello02** [inotia00/ReVanced_Extended#896]
### Type

Error while patching

### Application

Youtube premium 18.16.37

### Bug description

I noticed a problem in youtube premium the last version 18.16.37
When I open a playlist with more than 200 videos, and I go to the menu of the playlist it shows me 200 videos at the time and it doesn't show the videos at the bottom. This is really annoying if you are looking for a specifc video at the bottom of the playlist. I'm adding the screenshots of an example

### Steps to reproduce

1. Open a playlist with more than 200 video
2. Open a random video
3. Open the playlost menu at the bottom
4. You will notice than only 200 video appear at the time and you won't find the videos at the bottom of the playlist. For example if you open the vjdeo number 1, the last video you will see is number201 and you won't see videos number 210 or 230

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20230429_173602](https://user-images.githubusercontent.com/90071653/235311294-70cc8a8f-df6b-4388-97d6-e05a251c85b4.jpg)
![Screenshot_20230429_173552](https://user-images.githubusercontent.com/90071653/235311317-aa48ba78-c7fd-44ca-ab83-824861f48f83.jpg)
![Screenshot_20230429_173602](https://user-images.githubusercontent.com/90071653/235311321-63f86b5b-e277-4bdc-b64b-cf22e6317bf1.jpg)
![Screenshot_20230429_173546](https://user-images.githubusercontent.com/90071653/235311324-553205a9-1061-404c-a40d-5eb5e6b9774f.jpg)

### Solution

Make the playlist menu contain all the vjdeos of the playlist 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment]
This is a bug on youtube, not something that inotia00 can fix. I also have this bug when I browse a long playlist on youtube through Samsung Internet Browser, it stops at 200.

**Comment by coccobello02** [comment]
> This is a limitation on youtube, not something that inotia00 can fix. I also have this when I browse a long playlist on youtube through Samsung Internet Browser, it stops at 200.
> 
> I believe youtube have had this limitation at least for 2 decades.

On the version 18.15.38 it showed me all the videos and it did not have this issue.
It was last week. I had to update it cause of the message it appeared telling me to update. I didn't have any problems with that version.
Is there a way to keep the 18.15.38 version with deleting the pop up ad that tells you to update the app?

**Comment by inotia00** [comment]
If it reproduces on stock YouTube, this is an issue Google needs to fix.

If it worked fine on YouTube v18.15.40, try patching with YouTube v18.15.40

That version is also supported.

**Comment by coccobello02** [comment]
> If it reproduces on stock YouTube, this is an issue Google needs to fix.
> 
> If it worked fine on YouTube v18.15.40, try patching with YouTube v18.15.40
> 
> That version is also supported.

Can you explain what do you mean by :
"Try to patching with youtube 15.18.40"
I also tried that version by it shows be the pop up to update the app.
I want to use the version 15.18.38 eithout having that pop up. How can I do that
