### ISSUE TITLE
feat(patch): Always incognito

### ISSUE THREAD

**Issue by NeeRaj-2401** [inotia00/ReVanced_Extended#897]
### Application

YouTube

### Issue

currently when we switch to incognito, and app is inactive or being close for few duration than the YT automatically switches it back to normal mode.

### Patch

a patch that either switch the app to incognito on every start
or
a patch that prevents automatically switching of incognito to normal mode.

### Motivation

what if a person always wants to continue in incognito mode and manually switches for subscription feed for short period of time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
