### ISSUE TITLE
Need A Group/Channel Or App

### ISSUE THREAD

**Issue by adarshjayakumarofficial** [inotia00/ReVanced_Extended#899]
### Application

YouTube

### Description

 we need to check every day in extended website any update there or not I think if you are creating a channel on telegram that's so better so anybody can join the channel and they will get notification about the updates and if you want to say anything about that you can post there also.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
telegram group
https://t.me/revanced_extended

update notification channel
https://t.me/revanced_extended_repo

**Comment by adarshjayakumarofficial** [comment]
My current patch version is 2.171.2 ,i didn't see above 2.164.1 version in
the channel in telegram,I believe the channel is not up to date .. Is it ?
I will attach a screenshot of my patch details
