### ISSUE TITLE
Why doesn't 4k 60fps play correctly? 

### ISSUE THREAD

**Issue by MagicStyle2005** [inotia00/ReVanced_Extended#90]
### Application

YouTube

### Description

https://user-images.githubusercontent.com/121819829/210261679-8b6aafca-fc29-411e-8a3d-efb6230bbc51.mp4

4k 60fps gives me an error and lowers the quality to 480p always 

I have to make a movement to be able to have the video at 4k 60fps 

What is going to a video that is at 4k without 60fps... play the video and go back to the previous video that has 4k with 60fps to be able to play it at that quality 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Check for the same in vanilla YouTube

**Comment by MagicStyle2005** [comment]
> Compruebe si es lo mismo o no en Vanilla YouTube (stock YouTube)

I don't understand. Could you give me a more accurate explanation?

**Comment by inotia00** [comment]
Even if a video supports 4k 60fps, that doesn't mean you can use that option on your device as well.

If your device can't play a codec that supports 4k 60fps, you won't see this option
(depends on hardware specifications)

**Comment by MagicStyle2005** [comment]
> Incluso si un video admite 4k 60 fps, eso no significa que también pueda usar esa opción en su dispositivo.
> 
> Si su dispositivo no puede reproducir un códec compatible con 4k 60 fps, no verá 

> Incluso si un video admite 4k 60 fps, eso no significa que también pueda usar esa opción en su dispositivo.
> 
> Si su dispositivo no puede reproducir un códec compatible con 4k 60 fps, no verá esta opción (depende de las especificaciones del hardware)

Thanks for the help!!! .. clarify my doubt now ... This is very strange.. that's why I asked the question.. Thanks ☺️

**Comment by inotia00** [comment]
no problem
