### ISSUE TITLE
feat(patch): premium header

### ISSUE THREAD

**Issue by viveksharma55** [inotia00/ReVanced_Extended#900]
### Application

YouTube

### Issue

You forgot to add Premium header, speed icon on screen and option to remove or put icon on screen 

### Patch

Add Premium header and speed option on screen 

### Motivation

It's for look and feel 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
both patches are already exists
