### ISSUE TITLE
bug:  can't apply SponsorBlock because of missing override-speed-hook

### ISSUE THREAD

**Issue by Belphemur** [inotia00/ReVanced_Extended#901]
### Type

Error while patching

### Application

Youtube v18.16.37
Revanced Patches v2.171.2

### Bug description

Can't get the sponsorblock patch to apply using your fork of revanced-builder 

### Steps to reproduce

1. Let revanced-builder  download youtube 18.16.37
2. Choose sponsorblock as patch
3. Get an error while patching 

### Relevant log output

```
[builder] SEVERE: sponsorblock failed: app.revanced.patcher.patch.PatchResultError: 'sponsorblock' depends on 'sponsorblock-bytecode-patch' but the following error was raised: 'sponsorblock-bytecode-patch' depends on 'override-speed-hook' but the following error was raised: Failed to resolve VideoSpeedPatchFingerprint
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)

```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Issue is not reproducible

![Kiwi](https://user-images.githubusercontent.com/108592928/235325452-c39b865b-33cf-4d84-806d-880b86bc3d7d.png)


test environment
rvx-builder v3.9.1 (termux)
YouTube v18.16.37
revanced-patches-v2.171.2
revanced-integrations-v0.105.2

**Comment by Belphemur** [comment]
Interesting.

revanced-integrations-v0.105.0

rvx-builder v3.9.1 deosn't download the v0.105.2

**Comment by inotia00** [comment]
You may be using revanced-builder rather than rvx-builder, or you may have changed the source in settings

**Comment by Belphemur** [comment]
Ho I see what happened, both builder share the same settings file ... and it pointed to wrong source for revanced integrations.

Closing this, it's on me.

**Comment by inotia00** [comment]
yeah.. termux uses separate directory and separate settings json, but other platforms (Windows, Linux, Mac) don't
