### ISSUE TITLE
feat(patch): More options for sorting content

### ISSUE THREAD

**Issue by 4114nd3** [inotia00/ReVanced_Extended#902]
### Application

YouTube

### Issue

Lack of content exploring options.

### Patch

As the years passed by, Youtube gradually reduced options for users to sort content in diverse sections of their website. Notable examples were when they removed the option to reach oldest comments back in the days, or just recently when they removed the "sort by oldest" in the videos tab of channels and changed the mechanics of "sort by popular". It seems like Youtube doesn't want you to explore the website, but only to look for what is trending.
Would be nice to see more sort options for users.
Examples of sort options in the videos tab of the channels: more or less views, most liked or disliked, newest or oldest...
For comments: most liked or disliked, oldest or newest...
These are just some ideas.

### Motivation

This could serve for exploring and history purposes. For example, when finding a new channel, you can see how it started, what is the top content of this channel, know how the reception of some video was in the past by reading the oldest comments and so on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
