### ISSUE TITLE
bug: Hide subscribe button for Shorts shares same string to hide subscriptions tab in Crowdin

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#903]
### Type

Other

### Application

YouTube v18.16.37
ReVanced Patches v2.171.2

### Bug description

The string to hide the **Subscribe button** for Shorts shares the same string to hide the **Subscriptions tab** in Crowdin.
![Screenshot (606)](https://user-images.githubusercontent.com/127908708/235327842-010854d8-0f5e-419e-a806-c74d4a63311f.png)
I wanted to report this because one is a button inside shorts and the other is a tab and so we can't translate them differently if they share the same string.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate issue https://github.com/inotia00/ReVanced_Extended/issues/833
