### ISSUE TITLE
bug:Проблемы с воспроизведением видео

### ISSUE THREAD

**Issue by Saeyxris** [inotia00/ReVanced_Extended#904]
### Type

Error at runtime

### Application

YouTube ReVanced Extended 18.13.36

### Bug description

Каждый раз при воспроизведении видео, оно прогружается и зависает, смена качества и перезагрузка не решают проблемы, интернет на телефоне очень быстрый и хороший, в других приложениях такой проблемы нет и я свободно смотрю видео в разрешении 1440, без всяких лагов и зависаний

### Steps to reproduce

Я не знаю, как это исправить, надеюсь на разработчиков

### Relevant log output

```shell
Не знаю про выводы журнала
```

### Screenshots or videos

![Screenshot_2023-04-30-10-52-31-253_app rvx android youtube](https://user-images.githubusercontent.com/132149331/235334730-df6a1bd7-56ff-4ed6-8840-62b69366e2eb.jpg)
![Screenshot_2023-04-30-10-52-56-039_app rvx android youtube](https://user-images.githubusercontent.com/132149331/235334733-a73d2217-38a6-4661-873c-94af22f2bd0e.jpg)

### Device Environment

Android 12 SP1A.210812.016
MIUI 13.0.6 Global

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
v18.13.36 is unsupported version
