### ISSUE TITLE
bug: <title> downloading and you have to log out and log in to the app for it to complete every few minutes.

### ISSUE THREAD

**Issue by Aqeel931** [inotia00/ReVanced_Extended#905]
### Type

Error at runtime

### Application

V18.16 .48

### Bug description

There are problems with downloading videos. It stops  every 5 minute

### Steps to reproduce

I want to hide the forward 10 second buttons alone after letting them go 

### Relevant log output

```shell
There are problems with downloading videos. It stops
```

### Solution

Work p version similar to vanced

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/788
