### ISSUE TITLE
Android 7 -  Huawei p9 lite

### ISSUE THREAD

**Issue by kris0725pl** [inotia00/ReVanced_Extended#907]
### Application

YouTube

### Description

Hi...it is possible make version for android 7?
I have old phone huawei p9 lite :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The last version to support Android 7 is YouTube v17.34.36

but, since v17.34.36 is significantly outdated, I no longer support it.

Revancify supports unofficial patches for Android 6 & 7

Try patching through [Revancify](https://github.com/decipher3114/Revancify)
