### ISSUE TITLE
question: Cannot Add Fast Actions (Speed, Replay, Copy) Under Player

### ISSUE THREAD

**Issue by anil-al** [inotia00/ReVanced_Extended#908]
### Application

YouTube

### Description

Before the last patching, I was able to add speed and replay button under the player for fast accession but since you recommended clean installation, I reinstalled builder and patches chosen naturally has gone and I needed to choose anew. I cannot find from where to add these buttons in the settings so, I thought I haven't chosen it as patch. Can you name the patch and say where I can find those settings in ReVanced Settings?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
You can add it in Settings > ReVanced Extended > Overlay buttons

**Comment by anil-al** [comment]
> You can add it in Settings > ReVanced Extended > Overlay buttons

Which patch should I choose to add in builder because there's no overlay buttons options in settings anywhere right now.
