### ISSUE TITLE
question: Is there a reason for the removal of the "clientSpoofVersion" from options.toml?

### ISSUE THREAD

**Issue by Spacellary** [inotia00/ReVanced_Extended#909]
### Application

YouTube

### Description

It was still useful to set spoofing for older versions, and restore things like Sort by Oldest again, even if it broke RYD in doing some, some people would be willing to use it.

Is there a reason it couldn't be kept as option?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Spacellary** [comment]
Sorry, the Target still isn't on APKMirror so I didn't try just yet, but is `spoof-app-version` a replacement for this feature:?

**Comment by inotia00** [comment]
![spoof-app-version](https://user-images.githubusercontent.com/108592928/235349263-4182bbbf-c539-4c90-94cb-56ed2d6b8160.png)

`spoof-app-version` patch (old name: `enable-old-layout`) provides similar functionality

So I removed that option from options.toml

**Comment by Spacellary** [comment]
OH MY GOD YOU ARE A HERO WE DON'T DESERVE!

Thank you so much, this will help many folks that had trouble dealing with the options.toml!

**Comment by inotia00** [comment]
v18.16.39 is a valid version, but it hasn't been uploaded to APKMirror yet

In this case, I temporarily upload the unpatched APK (stock YouTube) to the [Telegram group](https://t.me/revanced_extended_chat/201069) 

btw v18.16.37 is also still on the support list, so you can try patching with v18.16.37 as well.

**Comment by Spacellary** [comment]
> v18.16.39 is a valid version, but it hasn't been uploaded to APKMirror yet

Thank you, I am playing around with the new custom icon patch! I am aware, but I'm doing my builds in https://github.com/Spacellary/ReVanced-Extended-Automated-Builds lately, I'll edit the .env config to use the v18.16.37 temporarely then, and build `latest` when it's uploaded to apkmirror.
