### ISSUE TITLE
bug: Videos stop playing after a minute or so

### ISSUE THREAD

**Issue by Idris110** [inotia00/ReVanced_Extended#910]
### Type

Error at runtime

### Application

YouTube ReVanced Extended : 
18.08.38

ReVanced patches :
2.164.12

ReVanced integrations :
0.99.12

### Bug description

The app was working absolutely fine until a few hours ago. Now when I watch a video it will pause and start buffering after about a minute without restarting. Playing another video will work but the same problem will happen after another minute. Except sometimes when it doesn't....

I updated everything, repatched, reinstalled, no changes.

### Steps to reproduce

Just play any video, you'll notice the bug.
If not, you're lucky, but not for very long.

### Relevant log output

```shell
//Not found
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
repatch with latest resources

**Comment by Idris110** [comment]
Where can I find those ?
I think its a issue with the micro g
