### ISSUE TITLE
bug: Channel popup menu color turned from black to grey

### ISSUE THREAD

**Issue by Metallifani666** [inotia00/ReVanced_Extended#913]
### Type

Cosmetic

### Application

YouTube 18.16.37
Patches: 2.171.3

### Bug description

This bug started all of a sudden after using the latest patches 2.171.3 for a while. This popup has been black all this time but it turned to grey after the latest patch.

### Steps to reproduce

1. Install the latest patch
2. Click on the 3 dots right next to the channel to bring the popup window
3. Keep clicking on those 3 dots randomly
4. Notice how at some point the popup menu turns from pure black to light grey

### Relevant log output

```shell
[patchlog.txt](https://github.com/inotia00/ReVanced_Extended/files/11361273/patchlog.txt)
```

### Screenshots or videos

![Screenshot_20230430_145007_ReVanced Extended](https://user-images.githubusercontent.com/131755431/235351660-8507faa7-7cec-435d-9b8d-d11cdea3d71a.jpg)

### Additional context

This bug started after the latest patch 1.171.3, patched with revancify. Cleared options.toml before patching as suggested in the patch notes.

All patches included except translation.

### Device Environment

Android 13 with OneUI 5.1.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is part of the old layout

`theme` patch does not fully support the old layout

After some time the new layout will be loaded from the server side, then all patches will work as intended in the new layout.
