### ISSUE TITLE
question: <play pause button not showing>: 

### ISSUE THREAD

**Issue by Junnu122** [inotia00/ReVanced_Extended#914]
### Application

YouTube

### Description

Play pause button doesnt appear in video in background notification

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Junnu122** [comment]
![Uploading Screenshot_20230430_151926.jpg…]()

**Comment by inotia00** [comment]
please check in unPatched YouTube as well

**Comment by Junnu122** [comment]
> 

I don't understand please explain where and how😶🥹🥺

**Comment by inotia00** [comment]
For example, if you patched with YouTube v18.16.39, check if the issue reproduces on an unpatched YouTube (stock YouTube) v18.16.39

You didn't even attach a screenshot, and you don't have a good enough explanation of what exactly the issue means

**Comment by Junnu122** [comment]
![Screenshot_20230430_151926](https://user-images.githubusercontent.com/132197331/235354334-8c384473-f8a2-479d-89bf-f75a1dbf3dc2.jpg)
This is the problem

**Comment by Junnu122** [comment]
![Screenshot_20230430_151926](https://user-images.githubusercontent.com/132197331/235354355-a1ccf35e-c834-4837-9920-d6690c7c528b.jpg)
This is the problem play pause isn't showing there

**Comment by Hennadz** [comment]
In mode PIP click the headphones icon

**Comment by inotia00** [comment]
It's an issue Google needs to fix, not an issue I can fix.
