### ISSUE TITLE
feat(patch): Can you re-enable the OverlayButtonsIcon option?

### ISSUE THREAD

**Issue by MustafaErdqn** [inotia00/ReVanced_Extended#915]
### Application

YouTube

### Issue

Hello,
I usually change the OverlayButtonsIcon option to "old" with options.toml and collect the apk, because I couldn't get used to the new overlay buttons, so the old button views looked better, I would appreciate it if you add this option again, thank you.

### Patch

OverlayButtonsIcon with options.toml

### Motivation

old overlay buttons look nicer to me

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Whenever I add a new resource to the overlay icon, it must support both the old and new icons.
However, I no longer have the original svg file and source for the old icons.

Impossible to restore it or continue support, so I dropped that option
There are no plans to restore it in the future
