### ISSUE TITLE
Bug:YTM issue with `share-button-hook`

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#916]
### Type

Error at runtime

### Application

YouTube Music 5.54.52

### Bug description

When sharing a song by searching it with the intention to download it , it shares the currently playing song instead of the searched one.

### Steps to reproduce

Play a song , search a different song then share it.

### Relevant log output

```shell
Don't know how to do it.
```

### Screenshots or videos

https://user-images.githubusercontent.com/64865031/235358297-1b2c2505-4428-4ed0-8ffb-3d6c614074e3.mp4

### Device Environment

Android 13 , MIUI 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is why the `hook-share-button` patch is designated as `Experimental Flgas`

Please do not report issues regarding patches flagged as Experimental Flags
