### ISSUE TITLE
protobuf-spoof patch on oldest YT-version

### ISSUE THREAD

**Issue by s7san007** [inotia00/ReVanced_Extended#917]
### Application

YouTube

### Description

Is it possible to implement the protobuf-spoof patch by manually editing the smali code (copy-paste) or something else? I need YouTube Vanced 16.02.35 with protobuf-spoof. A week ago 16.02.35 stopped working.
![Screenshot_20230430_173128](https://user-images.githubusercontent.com/130248949/235359179-f6871529-da7e-4bcc-87dd-cf6f41bf4169.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a ReVanced Extended repo, not a Vanced repo
