### ISSUE TITLE
Different package name for revanced extended

### ISSUE THREAD

**Issue by venkat2305** [inotia00/ReVanced_Extended#92]
### Application

YouTube

### Issue

This is not an issue

### Patch

To change the package name of the revanced extended so that we can have revanced og along with extended 

### Motivation

To change the package name of the revanced extended so that we can have revanced og along with extended 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![options](https://user-images.githubusercontent.com/108592928/210263304-13eb86d2-4ec5-4fae-bef9-9e22355af4a0.png)
This option is already provided

You can change the app name and package name by editing the `options.toml` file.

**Comment by venkat2305** [comment]
@inotia00 how can I do it with manager app?

**Comment by inotia00** [comment]
Revanced Manager does not provide a feature that edit options.toml

Use rvx-builder or revancify

**Comment by Sappurit** [comment]
Is it good? default 'Music_PackageName' = "app.rvx.android.youtube.music"  instead of app.rvx.android.apps.youtube.music 

Remove `apps` in the middle.

**Comment by inotia00** [comment]
I've never tested it like that
