### ISSUE TITLE
PowerTube Error

### ISSUE THREAD

**Issue by VanVuHoang** [inotia00/ReVanced_Extended#920]
### Type

Other

### Application

Youtube RVX 18.16.37 (Patches v2.171.4)

### Bug description

This error happens just recently, but I can't seem to download videos with PowerTube in Youtube RVX.

### Steps to reproduce

When the download button under a video is clicked, the PowerTube option will throw an error.

### Relevant log output

```shell
We're sorry... 
What happened? Unknown error x86: Fields [format_id, id, title, url] are required for type with serial name jussrfazar.youtube_dl.json. kotlinx.ServerJSONSingleSmall', but they were missing 
LOG OK 

Error 
AMELI---> Log stated at 1682915040177 1682915040232: AMELI—> URL 1682915040232: AM ELI—> https://youtu.be/IU_Iwh -po-4 1682915040232: AMELI—> Video id 1682915040232: AMELI—> IU_Iwh-po-4 1682915040653: AMELI—> Load URL 1682915040653: AMELI---> https://www.youtube .com/watch?v=IU_Iwh-po-4&has_verified=1&bpctr= 9999999999 1682915041392: AMELI--> StreamData decode 1682915041405: AMELI—> JSON Parsed 1682915041406: AMELI—> Dechiper Load problem 1682915044805: AMELI—> Exception: enc 1682915044805: AMELI---> java.lang.Exception: Could not parse deobfuscate function 1682915044805: AMELI---> Sorting AMELI > URL https://youtu.be/IU_Iwh-po-4 AMELI---> Detected extractor None AMELI > URL https://youtu.be/IU_Iwh-po-4 AMELI---> Detected extractor YouTube 
OK
```

### Screenshots or videos

![Screenshot_20230501-162428_PowerTube](https://user-images.githubusercontent.com/87590114/235411538-92617cf4-a635-40e8-b6a5-e46eababe44c.jpg)
![Screenshot_20230501-162444_PowerTube](https://user-images.githubusercontent.com/87590114/235411541-86698560-6df1-44c8-8ba3-85895003e790.jpg)

### Additional context

Affected videos seem to be those that are music-centric and AMVs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is not PowerTube repo
