### ISSUE TITLE
Is it possible To Add MicroG Support For More Google Apps?

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#922]
### Application

Other

### Description

Just wanna know if it is possible to have Non-root MicroG Support for more Google apps aside from Youtube and YT Music?

If it is possible, is there any plan in the future to make it happen?

I currently use Gbox on my Huawei 2/32GB and it is very laggy. Some features doesn't work as well because it is a Virtual Space.
Having MicroG Support for more Google Apps would definitely help a lot of low end huawei phone users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
'microg-support' patches exist for YouTube and YT Music

But other Google apps don't support `microg-support` patch

ReVanced Extended only supports YouTube and YT Music, so I don't plan to support other Google apps.
