### ISSUE TITLE
feat(patch): Make mMicrog to hide from launcher

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#923]
### Application

YouTube

### Issue

There is no way on that repo to add a issue there. So, I'm making it here. Please add a option to hide mMicrog from the App Drawer. It is there in Vanced Microg but not in mMicrog. Or implement it directly so that it shouldn't be shown in App drawer anymore.

### Patch

...

### Motivation

It will be a good patch for the Stock Android users as there is no way to hide apps in Stock like other UI.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MouhsenKamil** [comment]
It would be nice if the option to hide mMicrog from App Drawer, is available within the mMicrog app itself
This is how Vanced MicroG used to have.
