### ISSUE TITLE
Suggestion: Open Crowdin translation page for mMicroG

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#924]
I'd like to suggest opening a Crowdin translation page for mMicroG. This will allow users to use the app in their preferred language, making it more accessible and user-friendly.
Thank you for considering my suggestion.

**Comment by Sappurit** [comment]
Where to talk all about ReVanced Extended? Something like a forum or webboard...
I have a problem with the app.revanced.android.youtube_17.34.36 on Android 6.
Can the new mMicroG be replaced with the old com.mgoogle.android.gms_0.2.27.230755 ?
