### ISSUE TITLE
feat(patch): Option to remove Flyout menu options in search videos

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#925]
### Application

YouTube

### Issue

Remove menu options for search videos.

### Patch

![Screenshot 18 43 (Monday 01 05) msedge 391](https://user-images.githubusercontent.com/125728453/235456296-c1b76900-33cd-4c85-8fdb-f2b5eddeb67b.png)

### Motivation

These options are not needed to some users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Hennadz** [comment]
Not needed - do not press three dots.

**Comment by inotia00** [comment]
Reflected in [revanced-patches-2.181.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
