### ISSUE TITLE
bug: shorts button hidden in navigation even though `hide-shorts-button` patch was not included

### ISSUE THREAD

**Issue by Duypadora92** [inotia00/ReVanced_Extended#928]
### Application

YouTube

### Issue

![received_6076370742477003](https://user-images.githubusercontent.com/121789347/235482853-16ab25c6-2503-41b7-92f1-7e41899f4d61.jpeg)

### Patch

Patches v2.171.4
I did not select the patch to hide the Short button but the Short button still has no way to open.

### Motivation

I think it's indispensable for the Short button and the unbalanced bottom button interface

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.173.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.1)
