### ISSUE TITLE
feat(patch): Change default SponsorBlock mirror server

### ISSUE THREAD

**Issue by MatadorProBr** [inotia00/ReVanced_Extended#93]
### Application

YouTube

### Issue

SponsorBlock mirror server going down.

### Patch

This is more a suggestion for a patch that already exists (SponsorBlock) that a new patch suggestion, change default SponsorBlock mirror server to https://sponsorblock.hankmccord.dev

Why?
This Reddit post explains more about it: https://www.reddit.com/r/SponsorBlock/comments/ykel11/aggregated_alternate_servers/ or if you don't wanna read that Reddit post, just read the message below.

### Motivation

The mirror server (https://sponsorblock.kavin.rocks) is great but imagine if it goes down too? With this server that I suggested it will basically solve this issue since it checks if the main server (https://sponsor.ajay.app) is up and working normally and if not, it will check a list of servers (for now, only 2) and route the API from the most healthy server of that list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
looks good
I'll test it and give you an answer

**Comment by MatadorProBr** [comment]
> @inotia00 How about if u add a list of SponsorBlock server and it automatic check the working server to use

yeah probably this would be better in privacy, doesn't depend on someone, etc.

**Comment by inotia00** [comment]
Reflected in revanced-integrations-v0.91.2
thank you
