### ISSUE TITLE
question: Is it possible to implement/include a custom animated splash screen?

### ISSUE THREAD

**Issue by Spacellary** [inotia00/ReVanced_Extended#930]
### Application

YouTube

### Description

In the context of a new branding patch, is it curently possible to have animated splash screens?

We'd have resources to make new art and animations, depending on the requiriments and how it's implemented.

Not sure if you could briefly go over the technical workings of this.

Just want to know if it's possible the way branding works now, and of course we'd try our best to make the best result.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Implementing a custom splash animation is tricky

You need to create a splash animation (video) first, then split it into several frame-by-frame animated vector drawables.

Afterwards, you need to define animated vector drawables for each divided frame.

This is how splash animations work in Android 12+

I've done a splash animation for Vanced Extended before, but it took quite a while to implement
