### ISSUE TITLE
bug: <Buffering issue>

### ISSUE THREAD

**Issue by Ronakksingh** [inotia00/ReVanced_Extended#931]
### Type

Error at runtime

### Application

When we play video on youtube vanced after 2 or 3 minture it starts buffering, and when we start it back again it ,again start buffering after playing for sometime

### Bug description

I played so many video on diffrent network but problem was same 

### Steps to reproduce

Play any video and wait for it after some time it will start buffering 

### Relevant log output

```shell
Don't know
```

### Screenshots or videos

![Screenshot_20230502-113319_YouTube Vanced](https://user-images.githubusercontent.com/132331438/235590895-0131f0f1-e584-4d3f-aa68-c3dca4dc924f.jpg)

### Solution

No i don't know

### Additional context

Nothing 

### Device Environment

Android 11, Samsung galaxy m51

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is not Vanced repo
