### ISSUE TITLE
feat(patch): Allow custom spoof app version

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#932]
### Application

YouTube

### Issue

In Revanced Extended, if we change to old UI, we cannot choose the version to spoof. So I think add a feature for this is better

### Patch

![image](https://user-images.githubusercontent.com/70064328/235600914-7e9f99a4-5716-4332-aa5b-e5c20707044b.png)

### Motivation

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Already you can choose one of the following versions
-V17.41.37
-V17.30.34
-V17.06.35
-V16.08.35

what do you want?
