### ISSUE TITLE
question: <title>: 

### ISSUE THREAD

**Issue by Traktorist3d** [inotia00/ReVanced_Extended#933]
### Application

YouTube

### Description

Please tell me if it is likely that you implement the function of the time delay of the sound relative to the video, both in + and in -.  how it is roughly done in vlc.  this feature will allow you to easily watch revanced on systems with a DSP that adds audio delay during processing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Not in the plan
If you need that feature, use another YouTube client
