### ISSUE TITLE
YouTube does not login to mMicrog

### ISSUE THREAD

**Issue by User-noob2036876** [inotia00/ReVanced_Extended#934]
### Type

Other

### Application

This error appeared with V0.2.27.231613 version of mMicrog. It was logging in in the previous mMicrog version. Needs hotfix.

### Bug description

No application registers afterwards.

### Steps to reproduce

Jdjd

### Relevant log output

```shell
Hdhf
```

### Screenshots or videos

App crash without crashlog.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
uninstall and reinstall mMicroG and YouTube

**Comment by User-noob2036876** [comment]
> uninstall and reinstall mMicroG and YouTube
I tried it. No problems in first mMicrog version
