### ISSUE TITLE
feat(patch): Channel Blocker

### ISSUE THREAD

**Issue by Kotklumpen** [inotia00/ReVanced_Extended#937]
### Application

YouTube

### Issue

On YouTube, there are so many annoying channels that pop up all the time, whether it's in search or under the video you're watching, or even on the startpage.

### Patch

A feature like it already exists in the [Channel Blocker](https://addons.mozilla.org/de/firefox/addon/youtube-cleaner/) addon for Firefox would be a dream for the YouTube revanced extended app.

### Motivation

Often I have read and heard that this feature is desired by revanced community.
Unfortunately, it was not integrated bus dato.
So if someone can do it then the great inotia00.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
duplicate with https://github.com/inotia00/ReVanced_Extended/issues/260
