### ISSUE TITLE
Where is the custom branding icon at

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#938]
### Application

YouTube ReVanced 18.16.39

### Description

???????

![IMG_20230503_134532](https://user-images.githubusercontent.com/125992636/235848371-455c10fe-e23b-4e6a-a1ca-153410893db4.jpg)

![Screenshot_2023-05-03-13-45-45-026_app rvx android youtube](https://user-images.githubusercontent.com/125992636/235848403-f2d18d9f-45f7-40e4-826e-35f0dbf11f9a.jpg)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Hennadz** [comment]
https://github.com/inotia00/revanced-documentation/wiki/Options-Information-about-the-patch#if-you-want-a-custom-icon-only-available-on-cli
