### ISSUE TITLE
While installing new apk

### ISSUE THREAD

**Issue by rushabhT3** [inotia00/ReVanced_Extended#939]
### Type

Error while patching

### Application

I cannot new APK it shows that screenshot message: conflict with existing package ALWAYS 
![Screenshot_2023-05-03-12-46-10-04_3d73e98b1ad3bd2575f7a56513d89a0c](https://user-images.githubusercontent.com/41021094/235854339-658f35d9-f6cf-45b4-9bc9-9575bb0eea8c.jpg)
So I have to uninstall the revaced extended and then install the new APK but the settings I have to do again: cumbersome 

### Bug description

Annoying bug

### Steps to reproduce

Install the updated apk when older version already installed 

### Relevant log output

```shell
NA
There is no relevant output except the message in the screenshot.
```

### Device Environment

![Screenshot_2023-05-03-12-56-38-46_9492aa3750dca76abb7c25b39a5f1e8e](https://user-images.githubusercontent.com/41021094/235854989-5ab2d72f-7793-468a-a59d-19dd0e3fda22.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Uninstall any previously installed ReVanced or ReVanced Extended and try installing

**Comment by rushabhT3** [comment]
I am sorry but that is the issue. I have to uninstall for installing otherwise it won't install... I can uninstall and reinstall but like I said I have to set all the settings again... so maybe you can integrate the settings so that it will be the same as my current one or store it in some file maybe or fix the problem.

**Comment by rushabhT3** [comment]
I have only the revanced extended installed and no other version

**Comment by inotia00** [comment]
Yes because you downloaded the prebuilt apk
I never distribute prebuilt apk

Since the apk you download comes from an unknown source, no one knows who built it, which patches were applied, or whether it contains malware.

If you follow the guide provided in the [documentations](https://github.com/inotia00/revanced-documentation/wiki), you can resolve this issue.
And I don't provide any support for prebuilt apk
