### ISSUE TITLE
question: How to Enable Full-screen Buttons & Panels

### ISSUE THREAD

**Issue by christantoan** [inotia00/ReVanced_Extended#94]
### Application

YouTube

### Description

Sorry for the issue type to be Question as I'm not sure if this issue is properly a bug or not.

I want to enable the following buttons and panels on full-screen but couldn't find a way to do so.
![Screenshot_20230103-083319](https://user-images.githubusercontent.com/7300310/210301620-53392434-c89b-4d7a-be2e-e513825905ae.png)
![Screenshot_20230103-083350](https://user-images.githubusercontent.com/7300310/210301623-aebfd2e7-07cc-40dd-b12e-d605010cd119.png)
![iMarkup_20230103_083438](https://user-images.githubusercontent.com/7300310/210301627-fbf8eecb-bc5c-4b38-adae-601384a6e7b2.png)

I've tried to disable (or not patching) hide-fullscreen-buttoncontainer but they still wouldn't show up.
![IMG_20230103_112429_644](https://user-images.githubusercontent.com/7300310/210301763-8e898fb4-e916-4174-9031-2913d69032c4.png)

I've also tried clean reinstall as well as force stopping after changing the toggle.

Thank you in advance!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Presumably, this is the same bug reported in the past https://github.com/inotia00/ReVanced_Extended/issues/49
Unfortunately, no matter how hard I try, this bug is not reproducible, so I can't fix it right away.
