### ISSUE TITLE
feat(patch): 'hide-shorts-pivot-bar' removal

### ISSUE THREAD

**Issue by benharom** [inotia00/ReVanced_Extended#940]
### Application

YouTube

### Issue

ReVanced made a better implementation of the patch.
They've added 'spoof-app-version' where **17.01.35** version fixes the problem.

### Patch

The patch is not needed after ReVanced made a better implementation.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It is already implemented
Apply the patch to the latest resources
