### ISSUE TITLE
feat(patch): Take the whitelist patch back with oembed

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#941]
### Application

YouTube

### Issue

#918 In this issues, you have remove the whitelist patch. But why don't you use another way like oembed. Here is an example:
https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=dQw4w9WgXcQ&format=json
It will have response:
`{"title":"Rick Astley - Never Gonna Give You Up (Official Music Video)","author_name":"Rick Astley","author_url":"https://www.youtube.com/@RickAstleyYT","type":"video","height":113,"width":200,"version":"1.0","provider_name":"YouTube","provider_url":"https://www.youtube.com/","thumbnail_height":360,"thumbnail_width":480,"thumbnail_url":"https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg","html":"\u003ciframe width=\u0022200\u0022 height=\u0022113\u0022 src=\u0022https://www.youtube.com/embed/dQw4w9WgXcQ?feature=oembed\u0022 frameborder=\u00220\u0022 allow=\u0022accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\u0022 allowfullscreen title=\u0022Rick Astley - Never Gonna Give You Up (Official Music Video)\u0022\u003e\u003c/iframe\u003e"}`
Here, you can get the author name and author_url, which can be stored to the whitelist

### Patch

Whitelist patch

### Motivation

It will make the app powerful than ever

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This method is not ideal
The reason is as follows:

1. The channel name can be changed at any time
: When the channel name is changed, the whitelist does not work

2. It is too late to apply the whitelist after recognizing the channel name
: Whitelist works as intended only when it is applied at the level that receives the API

Whitelist implemented in Vanced uses YouTube API v1 (and recived each channel's unique code)

**Comment by YT-Advanced** [comment]
> This method is not ideal The reason is as follows:
> 
> 1. The channel name can be changed at any time
>    : When the channel name is changed, the whitelist does not work
> 2. It is too late to apply the whitelist after recognizing the channel name
>    : Whitelist works as intended only when it is applied at the level that receives the API
> 
> Whitelist implemented in Vanced and RVX uses YouTube API v1 (and recived each channel's unique code)

1. The whitelist can't work if the channel name change, but it is better than we don't have the whitelist. And how about the channel link ?
2. I think we have 2 way to solve this problem:
- Post the oembed request first then youtube's request
- When the video appear, the app will get video id, so let the app to check all of the video appear on the screen and mark what video should be excluded.

**Comment by inotia00** [comment]
If someone has implemented it, please leave a PR

**Comment by nochlab1** [comment]
> 

Hey did you have a chance to see if you can implement this?
Thanks

**Comment by YT-Advanced** [comment]
> If someone has implemented it, please leave a PR

Hmm, now I think I can do it but you are going to close this repos :( Sad

**Comment by YT-Advanced** [comment]
@nochlab1 Okay, I am doing it. And when inotia00 archive his repos, I will make a fully fork to continue his work

**Comment by nochlab1** [comment]
Thanks So much

> @nochlab1 Okay, I am doing it. And when inotia00 archive his repos, I will make a fully fork to continue his work
