### ISSUE TITLE
bug:백그라운드 재생시에>모바일 디스플레이 끄기>미디어 재생이 끊김.bug: Background playback>turn off mobile display>media playback cuts off.

### ISSUE THREAD

**Issue by sangmo0145** [inotia00/ReVanced_Extended#943]
### Type

Other

### Application

revanced extended v18.16.39

### Bug description

밧데리 절약 차원에서>백그라운드 재생>pip모드>모바일 디스플레이 끄기>미디어 재생 끊김.
이러한 점을 시급히 개발하여 주세요!!
To save battery > background playback > pip mode > turn off mobile display > media playback cuts off.
 Please develop these points urgently!!

### Steps to reproduce

bug: Background playback>turn off mobile display>media playback cuts off.

### Relevant log output

```shell
bug: Background playback>turn off mobile display>media playback cuts off.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by sangmo0145** [comment]
항상, 영상 시청에 감사를 드립니다.
저의 제출한 개선점을 개발하여 주시면 감사하겠습니다.
As always, thanks for watching the video.
 I would appreciate it if you could develop my submitted improvements.

**Comment by inotia00** [comment]
It depends on your OS's policy

**Comment by sangmo0145** [comment]
> OS의 정책에 따라 다릅니다.

위,글을 이해 못 하겠습니다.
Above, I do not understand the article.

**Comment by inotia00** [comment]
If you are using the latest Android version, YouTube may not run smoothly in the background due to your OS.

Just add YouTube or MicroG as battery optimization exceptions

This is an issue that is also reproduced on stock YouTube, so I can't solve it on my side.

Again, this is an issue related to your OS's policy.
