### ISSUE TITLE
feat(patch): Hide ticket shelf in related videos

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#946]
### Application

YouTube

### Issue

Similar to https://github.com/inotia00/ReVanced_Extended/issues/687 but for related videos.

![20230504_010944](https://user-images.githubusercontent.com/127908708/236084776-9ff262fe-36ff-4559-b608-263c88e11b41.jpg)

### Patch

A toggle to hide the shelf.

### Motivation

They look like ads and to make YT more clean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.173.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.2)
