### ISSUE TITLE
feat(patch): hide sort comments option

### ISSUE THREAD

**Issue by MondayNitro** [inotia00/ReVanced_Extended#948]
### Application

YouTube

### Issue

add a patch that removes sort comments option in the comments box

### Patch

![Screenshot_20230504-103545_Trebuchet](https://user-images.githubusercontent.com/87489540/236117914-8b917400-7615-4e43-9f69-fa43a5bc101e.png)

### Motivation

i never use this feature and i believe many users are like this too

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
