### ISSUE TITLE
feat(patch): add text copy features

### ISSUE THREAD

**Issue by Dangln** [inotia00/ReVanced_Extended#95]
### Application

YouTube

### Description

Is there a way to copy text?
Sometimes want to research a title or word or product etc but can't seem to copy any text

Thanks all

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This feature is not supported in ReVanced Extended.
If you want this feature, I'll change the label

**Comment by venkat2305** [comment]
I have requested this in the revanced repo https://github.com/revanced/revanced-patches/issues/1350

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
