### ISSUE TITLE
feat(patch): option to show buffer cache on seekbar

### ISSUE THREAD

**Issue by ANewDawn** [inotia00/ReVanced_Extended#950]
### Application

YouTube

### Issue

Currently the buffer cache only displays on seekbar when videos are previewd on home feed but doesn't display when video is being watched. It shows once video is tapped and overlay filter appears.

### Patch

![Screenshot_2023-05-04-14-14-37-852_app rvxb android youtube~2](https://user-images.githubusercontent.com/51456745/236217445-8b3e76f8-14a4-497b-a46f-80b9bcca4166.jpg)

![Screenshot_2023-05-04-14-14-50-405_app rvxb android youtube~2](https://user-images.githubusercontent.com/51456745/236217495-b5db3053-0021-4cbd-8610-9b9c5812ad79.jpg)

![Screenshot_2023-05-04-14-23-26-519_app rvxb android youtube~2](https://user-images.githubusercontent.com/51456745/236217885-238f2de6-d136-43f1-9cfb-828de61f2a2f.jpg)

### Motivation

Sometimes on poor connections is good to see the current buffer cache as videos can stall without being able to see if the video has been cached enough.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/67
