### ISSUE TITLE
feat(patch): option to hide add comment panel

### ISSUE THREAD

**Issue by ANewDawn** [inotia00/ReVanced_Extended#951]
### Application

YouTube

### Issue

An option to hide the add comment panel in the comments section to free up some space.

### Patch

![Screenshot_2023-05-04-14-29-19-205_app rvxb android youtube~2](https://user-images.githubusercontent.com/51456745/236220424-c1055ddf-63c3-40a0-b383-665fbb579c06.jpg)

### Motivation

For users who don't sign into an account the add comment won't be used. Option to hide it will be useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ANewDawn** [comment]
Hi @johnconner122

Do you know if this can be hidden with the user filter?

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
