### ISSUE TITLE
feat(patch): Add back the "custom-branding-icon-manual" patch

### ISSUE THREAD

**Issue by Spacellary** [inotia00/ReVanced_Extended#955]
### Application

YouTube

### Issue

The goal of this request is just to have an official place and to track progress and discuss the new implementation of this patch again when possible, if you really want to make changes to it.

It could still be left in, after all it's optional, and could already be used in all platforms, be it Windows, Linux, Android, Cloud (GitHub actions), etc...

<hr>

For context for users tha aren't aware:

```
2.173.1 patch notes:
remove custom-branding-icon-manual patch (as it is not an ideal method)
```

### Patch

custom-branding-icon-manual

### Motivation

_Just adding this but I know you already know the motivation haha:_

Although it could not be ideal, I and I guess a few more people, found it useful.

And I actually like the way it's implemented, as it allows you test alternative custom-branding patches quite quickly.

It's convenient to make a template for branding patches submissions.

<hr>

Didn't mean to annoy you too much, have a wonderful day!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Spacellary** [comment]
@IMXEren is also very interested haha

This is just so we have a way to track the issue 👍

**Comment by IMXEren** [comment]
Yes, unfamiliar with the options.toml file, I liked the patch. Requesting you to add it again.

**Comment by Spacellary** [comment]
> Yes, unfamiliar with the options.toml file, I liked the patch. Requesting you to add it again.

Tbf the options.toml iconPath setting is broken as far as I know haha

This patch actually fixed that CLI issue

**Comment by inotia00** [comment]
I'm not adding the `custom-branding-icon-manual' patch again, as I already have enough `custom-branding-icon` patches.

Instead, I integrated them into the `settings` and `music-settings` patches.

1. manually create a `branding` or `branding-music` folder in the directory where the CLI exists
2. include the `settings` or `music-settings` patch
3. it will works same as the `custom-branding-icon-manual` patch

**Comment by inotia00** [comment]
It has already been added to the commit, and will be reflected in the next release

**Comment by Spacellary** [comment]
Thank you!

Bit sad about the branding patches but my heart still wants, is there a downside for you adding them more? It seems to be a popular feature

**Comment by Spacellary** [comment]
Are we allowed to still make branding icon PRs?

**Comment by inotia00** [comment]
yeah leaving a PR is also good

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.173.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.2)
