### ISSUE TITLE
feat(patch): font color in theme patch

### ISSUE THREAD

**Issue by innuendofloyd** [inotia00/ReVanced_Extended#956]
### Application

YouTube

### Issue

options.toml allows custom darkThemeBackgroundColor, just for app background.

### Patch

When choosing a lighter background color, instead of pure amoled, it would be less eye strain to chose font color.

### Motivation

My eyes hurt really bad in both light and dark theme, e.g while reading comments or scrolling home page. 
So, at the moment I'm using #5b513f for darkThemeBackgroundColor in options.toml, which is better but not ideal.
Ideal could be #d1c9bb darkThemeBackgroundColor AND #000000 font color. Not possible now, because even if I change darkThemeBackgroundColor, font stays white so it's actually worse.
Thanks anyway
bye

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment]
Duplicate of #43 

@inotia00 You can close this one.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
