### ISSUE TITLE
feat(patch): Open links in other apps instead of external browser

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#957]
### Application

YouTube

### Issue

When I click a link to any website I have app downloaded for, e.g. Discord, Instagram, Patreon, and I have "enable external browser" patch selected, it opens the link in external browser instead of the related app. This patch would fix this issue.

### Patch

Option to make links open in related apps instead of external browser, when "enable external browser" patch is selected.

### Motivation

It would make use of RVX slightly more convenient. I don't know how difficult it is to add this feature but I would like to see it happening.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
That's the OS policy for Android 11+

Patches must be applied at the OS level, so even if you leave a request here, it will not be reflected.
