### ISSUE TITLE
feat(patch): Add toggle switch for all patches in settings

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#958]
### Application

YouTube

### Issue

When trying different patches, I have to repatch everytime if I want to remove or add some features like MaterialYou or translations.

### Patch

Add toggle switch in settings for all possible patches.

### Motivation

It would eliminate the need to repatch every time when trying new features.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
90% of the patches are already reflected in the settings toggle

The 10% of patches that are not reflected by the rest of the setting toggles are completely impossible as I need the YouTube source code.

But you can choose in the patching process, so it's not a big deal

**Comment by NoMorePizza** [comment]
> The 10% of patches that are not reflected by the rest of the setting toggles are completely impossible as I need the YouTube source code.

Got it, but thanks anyway.
