### ISSUE TITLE
question: Adding to playlist takes a long time

### ISSUE THREAD

**Issue by kwokshsee** [inotia00/ReVanced_Extended#959]
### Application

YouTube

### Description

I have both YouTube regular (i.e. unpatched) & YouTube ReVanced Extended installed on my phone, and notice that after clicking on the "Add to playlist" option, YT regular can pop up my long list of playlists almost immediately, put YT ReV Ext takes a long time. So, wonder if you guys could fix it 😊

Thanks for your attention. Have a nice day~

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment]
Try to clear Revanced's cache and try again.

**Comment by inotia00** [comment]
not reproduced
