### ISSUE TITLE
8x zoom is missing in extended 

### ISSUE THREAD

**Issue by Slowloris01** [inotia00/ReVanced_Extended#96]
8x zoom is available on original revanced but not revanced extended

**Comment by HoriKyoukosimp** [comment]
Clear youtube revanced extended data

**Comment by Slowloris01** [comment]
> Clear youtube revanced extended data

Not working tried on different phone also but in extended it is not working

**Comment by HoriKyoukosimp** [comment]
Weird

Mine work tho

**Comment by inotia00** [comment]
8x zoom is an option provided in the new layout, the new layout follows your Google Account status
(server side)

So this is not an issue with ReVanced / ReVanced Extended

**Comment by Slowloris01** [comment]
Solve Just use latest version of microg
