### ISSUE TITLE
feat(patch): hide comments label

### ISSUE THREAD

**Issue by kwokshsee** [inotia00/ReVanced_Extended#960]
### Application

YouTube

### Issue

YouTube app has too many toasts (pic attached), which pop up after you sent a reply/comment, added a video to a playlist, etc, and stay at the bottom of the screen for at least 2 to 3 seconds, during which you can do nothing with the app but waiting for three toast to disappear.

![Screenshot_20230505_193646](https://user-images.githubusercontent.com/131514580/236450251-63d2beb8-b16f-479e-86a0-f2ab554ca45d.jpg)

### Patch

Disable all toasts.

### Motivation

It saves everyone time~

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kwokshsee** [comment]
Sorry, WRONG pic attached. Here is the correct screenshot:
![Screenshot_20230505_192110](https://user-images.githubusercontent.com/131514580/236451388-46679162-c937-4f53-9cef-fa5cbd6d7fbe.jpg)

**Comment by inotia00** [comment]
already implemented as a patch
: `hide-snackbar` patch
