### ISSUE TITLE
bug: Notification with playback/media controls appears after playback starts.

### ISSUE THREAD

**Issue by manieKMP** [inotia00/ReVanced_Extended#962]
### Type

Other

### Application

Non-root ReVanced Extended v18.16.39, patches v2.173.1 (arm64-v8a, cli v2.21.0, integ. v0.107.1)

### Bug description

The notification with player/playback controls showing up when video is playing but the app isn't minimized. Previously, that notification would pop up only when video was paused and after minimizing the app.

### Steps to reproduce

Step 1. Open affected version
Step 2. Choose any video and play it
Step 3. Check notifications when video is playing (by default there should be an icon on status/notification bar and app controls in notification area)

### Relevant log output

```shell
Unknown
```

### Additional context

Previous version that isn't affected with this issue which I used and reverted to is v18.16.38, v2.171.2 (there's one, v2.171.4 that I skipped between updates and didn't tested).
Regular ReVanced (non-root, v18.16.37, v2.173.0, arm64-v8a, cli v2.21.0, integ. v0.107.1) doesn't seem to be affected with this issue (I wasn't able to reproduce it on that version).

### Device Environment

Lenovo Tab P11 with stock Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Metallifani666** [comment]
Can you please attach a screenshot? One with how it looked before and one with the bug, that would help a lot.

**Comment by manieKMP** [comment]
Unaffected version (Extended v18.16.38, v2.171.2, Regular ReVanced v18.16.37, v2.173.0 and og regular YT v.18.17.38) and older:
1. When video is playing app don't shows any notification (no icon nearby clock on top-left corner nor playback/media controls in panel)
![Screenshot_2023-05-05-18-09-38-484_1](https://user-images.githubusercontent.com/128844150/236517040-d4a71b74-2344-495e-b467-ec5ab843dcf4.jpeg)
2. When video is paused and the app is minimized, notification is triggered and shows as icon (nearby clock)
![Screenshot_2023-05-05-18-08-44-664_1](https://user-images.githubusercontent.com/128844150/236518108-d5a8bea1-d9c1-4d98-9117-6477834550df.jpeg)
And as playback/media controls
![Screenshot_2023-05-05-18-08-57-892_1](https://user-images.githubusercontent.com/128844150/236518449-3225660c-afb8-400f-914e-5d788c427cad.jpeg)

Unfortunately I'm unable to provide screenshots with an issue (I went back to Extended v18.16.38, v2.171.2) but:
In affected version (v18.16.39, v2.173.1) it's like combination of the screenshots above with video playback in foreground, where both parts of notification (icon and controls) are shown while watching a video.

**Comment by Metallifani666** [comment]
Hmm, interesting. Do you also have this same issue in unpatched v18.16.39? If yes then this might be one of those Google's A/B testing thingys.

**Comment by manieKMP** [comment]
Well, I don't recall to use that particular version apart from RVX and I don't think that play store "gives" me an update to it. From what I know, they like to skip some "numbers" when they provide updates (previous version of og YT probably had a lower number than extended one with issue, and today it jumped to 18.17.38), like with A/B testing, it's a mess. If it is really a part of A/B tests on that particular version then they doing a "good" job to mislead some users, because notification icons in YT are the same (my first though when I saw it was that I received response to the comment ;)).

Later or tomorrow I'll check v.2.173.2, household chores won't do themselves. ;)

**Comment by manieKMP** [comment]
Today I tested v18.16.39, v2.173.2, messing with settings etc. for about a half hour or so and the issue doesn't appeared (previously it popped "instantly").

Should I close this topic or leave it open for a while or it will be closed by someone else?

**Comment by inotia00** [comment]
If it has been fixed since updating to latest resources, this issue is probably an outdated issue

so.. let's close
