### ISSUE TITLE
feat(patch): Hide subscribe button under player

### ISSUE THREAD

**Issue by ANewDawn** [inotia00/ReVanced_Extended#965]
### Application

YouTube

### Issue

Option to hide the subscribe button below player

### Patch

![Screenshot_2023-05-05-17-25-18-125_app rvxb android youtube~2](https://user-images.githubusercontent.com/51456745/236514688-e3d8f15f-55bb-4d1b-8652-a204b80bb13e.jpg)

### Motivation

Subscribe button stands out too much. Option to hide it be helpful for users who don't sign in won't use it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
Enter `subscribe_button` in custom filter.

**Comment by ANewDawn** [comment]
> Enter `subscribe_button` in custom filter.

Thanks that did the trick. Is there a list of custom commands when can use to filter elements?

**Comment by Metallifani666** [comment]
> Enter `subscribe_button` in custom filter.

Where you put this line? I tried to add it in but it didn't hide it.
