### ISSUE TITLE
feat(patch): Remove bottom player buttons labels

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#966]
### Application

YouTube

### Issue

Remove the text from the buttons and leave just the icons.
Also remove the space of the removed text and center the icons inside the containers.

It's similar to https://github.com/inotia00/ReVanced_Extended/issues/894 but for bottom player buttons.

### Patch

![20230505_193342](https://user-images.githubusercontent.com/127908708/236540362-907d93df-4510-4e89-a7e1-9be7e8bb9066.jpg)

### Motivation

Buttons will take up less space and make YT cleaner.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Adity1243** [comment]
Go to revanced extended settings, choose bottom player then find in between experimental flags and turn swiches on which you want to remove.

**Comment by inotia00** [comment]
I already tried to implement this, but it gives me huge white space where the text used to be

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
