### ISSUE TITLE
feat(patch): hide seebar while double tapping on fullscreen 

### ISSUE THREAD

**Issue by rsaurav12** [inotia00/ReVanced_Extended#967]
### Application

YouTube

### Issue

Can we make seekbar hide while double tapping on fullscreen?
(I know we can hide seekbar but i don't want to fully hide it, i just want to hide while double tapping on fullscreen) 
![Screenshot_2023-05-06-02-35-24-394_app rvx android youtube](https://user-images.githubusercontent.com/53332518/236569355-e2507ebe-4f10-4121-b03b-258d403fe850.jpg)

### Patch

I described my patch request as much as I could in issue section 

### Motivation

I think seekbar has no good reason to show in fullscreen while double tapping to skip in videos everytime

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
