### ISSUE TITLE
question: Any way to use Old Overlay buttons in YT

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#968]
### Application

YouTube

### Description

Is there any way remaining to use the **Old Overlay Buttons** as you have removed it from **options.toml**. I haven't found any way. If I try to add it in **Options.toml**, it gives me an error. I pretty much like the O**Old Buttons**

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
refer https://github.com/inotia00/ReVanced_Extended/issues/915
