### ISSUE TITLE
bug: Unable to patch MicroG

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#969]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Vanced MicroG

### Bug description

It gives an Error at the runtime of patching.

Question: Why the builder is still Patching the **Vanced MicroG** as you have discontinued it. I think that the builder should now starts patching mMicroG with YT as I have made a post to **Hide Icon from Launcher** for mMicroG, not for Vanced one. 

### Steps to reproduce

Just start patching the MicroG and you will see

### Relevant log output

```shell
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
TypeError: Cannot read properties of null (reading '0')
    at getAppVersion (C:\snapshot\rvx-builder\wsEvents\getAppVersion.js:205:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebSocket.<anonymous> (C:\snapshot\rvx-builder\index.js:199:9)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
```

### Screenshots or videos

![2023-05-06_07h06_28](https://user-images.githubusercontent.com/93650504/236591547-701ff027-ccea-4335-a352-7318de33709e.png)

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Metallifani666** [comment]
Revancify also patches VancedMicroG. 😐

**Comment by inotia00** [comment]
mMicroG was not uploaded to APKMirror

So, you have to manually upload mMicroG APK locally.

![IMG_20230506_115054_153](https://user-images.githubusercontent.com/108592928/236594916-30d816c0-5233-4703-9c59-9be3dca30834.jpg)

1. Download mMicroG apk from [Github](https://github.com/inotia00/mMicroG/releases/latest) 
2. Upload to rvx-builder using the upload button
3. Proceed with the patch
