### ISSUE TITLE
feat(patch): sponsorblock on youtube music

### ISSUE THREAD

**Issue by HoriKyoukosimp** [inotia00/ReVanced_Extended#97]
### Application

YouTube Music

### Issue

Well

Because some of youtube music songs are in video format, sometimes they'll have some intro & things

I want youtube music to have sponsorblock (non-music segments) integrated into it

### Patch

Sponsorblock

### Motivation

Well

Not everyone really care about it but for me

Its kinda annoying to heard the intro all the time

Or even slience at the start or the end

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
reflected in [revanced-patches-2.190.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.4)

**Comment by Spacellary** [comment]
This is absolutely fantastic! 👏 🍻
