### ISSUE TITLE
Not working with ReVanced Manager 1.0.0

### ISSUE THREAD

**Issue by fuckkmv** [inotia00/ReVanced_Extended#970]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Apps don't show up under patcher section in the new version 

### Bug description

Same as above
Had to downgrade to 0.57 to get it back workjng again. 
It said No Apps while on 1.0

### Steps to reproduce

Update to 1.0
Set sources to inotia00

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
simple. it is not compatible with ReVanced Manager 1.0.0

**Comment by Lucasark** [comment]
> > simple. it is not compatible with ReVanced Manager 1.0.0
> 
> This is temporary right? Accidentally updated my manager without realizing it would break Extended support and I can't downgrade without resetting keystores as they incremented the version code.
> 
> On a slightly different (but related) note, have you considered forking the manager too, and offering an APK (with a different package name) so you can control its in-app updates to not run ahead of Extended?
> 
> Changing the package name would also allow people to easily have it installed alongside the original manager. Right now I have the manager installed on my main profile and also hacked in as a Samsung Dual Messenger app, rather then using Secure Folder or Work (as when installed to the Dual Messenger profile, it allows quickly installing the patched APK to the main profile still, whereas with Secure Folder or Work profiles, it's a slightly longer process to install an APK generated by a copy of the manager installed there to the main profile). HOWEVER, because I'm utilizing profiles, both copies are always the same version.
> 
> Offering your own fork with a changed package name on its own update schedule would not only bypass the need for utilizing profiles, but would also allow keeping an up to date version of the manager installed alongside a version compatible with whatever Extended is currently compatible with.

it is metioned on Step-by-Step

<img width="305" alt="image" src="https://user-images.githubusercontent.com/31750882/236694446-c114e915-00a0-42db-846d-9ace2a51a6c9.png">

**Comment by Lucasark** [comment]
> This is temporary right?

This is temporary right?

I dont think it will be update to 1.0.0 so soon.

On a slightly different (but related) note, have you considered forking the manager too, and offering an APK (with a different package name) so you can control its in-app updates to not run ahead of Extended?

I dont think it will be relevant because we already have one stable manager.

And, everythink else you said about installation steps is unecessary complicated, I think you should clean install and do default install

**Comment by inotia00** [comment]
I'm not a maintainer of ReVanced Manager, and I don't plan to create a fork of ReVanced Manager because I don't know how to handle flutter and dart.

**Comment by inotia00** [comment]
There are two ways to downgrade ReVanced Manager while keeping the keystore.

Common: backup keystore
==
ReVanced Manager 1.0.0 supports exporting keystores.

![rvm](https://user-images.githubusercontent.com/108592928/236696371-e77bd652-18da-49e0-bac3-dff4a1e1a6ec.jpg)

First, export the keystore to local storage.

Method 1. Forced downgrade using ADB
==
1. Install ADB on your PC.
2. Download ReVanced Manager 0.0.57.
3. After connecting your phone to your PC, open cmd in the directory containing the ReVanced Manager 0.0.57 apk and type:
```
adb install -d revanced-manager-v0.0.57.apk
```
4. Downgrade to ReVanced Manager 0.0.57 completed.
5. Open ReVanced Manager and check if everything works fine.

Method 2. Load keystore
==
1. Do not force downgrade, simply uninstall ReVanced Manager 1.0.0.
2. Install ReVanced Manager 0.0.57 and run it.
3. Install Files by Marc.
4. Open Files by Marc and move the backed up keystore to the following path
```
/sdcard/Android/data/app.revanced.manager.flutter/files/revanced-manager.keystore
```
5. Force close ReVanced Manager and reopen it.
6. Restoring keystore is complete.

**Comment by inotia00** [comment]
Unlike official ReVanced, ReVanced Extended does not provide a separate API
(Also, there are no plans to provide an API in the future)

As a result, my patch is no longer compatible with ReVanced Manager 1.0.0+

So.. you have to choose one of the following.
1. Keep using ReVanced Manager 0.0.57
2. Migrate main patcher to rvx-builder or Revancify
(I recommend Revancify)

**Comment by inotia00** [comment]
yeah.. Revancify is the most ideal

Pros
- Supports both official ReVanced and ReVanced Extended.
- You can edit options.json.
- Patching is much faster.
- Since the keystore is downloaded from github, you don't need to back up the keystore separately.
- After the patch is finished, Revancify removes all but necessary libraries from your device. Therefore, the size of the patch result is smaller.
(When YouTube patched with the official ReVanced Manager: about 140MB, when YouTube patched with Revancify: about 80MB)

Cons
- No GUI support.
- Termux uses about 800 MB of storage capacity when all required packages are downloaded.

**Comment by inotia00** [comment]
I'm not a maintainer of Revancify, but I'll answer the question as it's within the scope of my knowledge.

Q. All output APKs are signed by the same keys regardless of ReVanced/Extended and what device you generate them from?
A. Yes. The keystore is downloaded from Revancify's Git repository, so all apps patched through Revancify have the same signature.

Q. Will it remember the patches you select for each source independently?
A. Yes. An independent patch list is created for each source (json), and options.json is also saved in an independent file.

Subsequent questions are off-topic, so I'll lock the issue
For more information about Revancify, please contact the [Revancify Telegram](https://t.me/revancify)
