### ISSUE TITLE
question: <title>: 

### ISSUE THREAD

**Issue by Lapis-is-love** [inotia00/ReVanced_Extended#972]
### Application

YouTube

### Description

Hello.  where are the descriptions of all the channels?  I looked for this function in the settings and did not find it anywhere, now there is no description in any videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by Metallifani666** [comment]
![Screenshot_20230506_165711_YT](https://user-images.githubusercontent.com/131755431/236628724-7b15c862-e0b0-4084-aa6a-817e1027a562.jpg)

**Comment by inotia00** [comment]
Please fill out the following form

- YouTube version
- revanced-patches version
- list of patches to include or exclude
- screenshot of the issue

**Comment by Hennadz** [comment]
If there is a description in incognito mode, a new account will help you.

**Comment by inotia00** [comment]
This is a YouTube issue
