### ISSUE TITLE
feat(patch): Replace Built-In Share Menu with That of Device

### ISSUE THREAD

**Issue by anil-al** [inotia00/ReVanced_Extended#973]
### Application

YouTube

### Issue

YouTube has a share menu for videos that is very limited and definitely not helping for versatility whereas native share menus of devices tend to be inclusive and optimised for those devices needs such as screen size, reachability, fast actions that users choose to have.

### Patch

Disabling built-in share tool of YouTube and activating that of device instead.

### Motivation

Using fine-tuned experience of devices for a much used action.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/439
