### ISSUE TITLE
feat(overlay-buttons): Add more options / move to the left side

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#974]
### Application

YouTube

### Issue

If you are watching Youtube in FullScreen Landscape mode and holding the phone/tablet with one hand you would have to reach out to change video quality, Turn on/off Captions and Autoplay.

### Patch

![Screenshot_20230507_000309](https://user-images.githubusercontent.com/74855954/236634753-d5412aac-3818-4e9b-9e20-097a0bb655d7.jpg)

Add AutoPlay Toggle, CC Toggle and Video Quality in Overlay Buttons.
Add Ability to Move Overlaybutton to left side.

### Motivation

1) It will be easier to use Youtube in Fullscreen when using one hand regardless of peoples if the user is left or right handed.

2) If those options are included in the Overlay Button then people wouldn't need the "Enable Old Flyout Panel" Patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
In the Top Right we have all option you mentioned

**Comment by Stale-1** [comment]
@inotia00, I'd like to add some things.
1) Audio Track Selection in Overlay Button, Some videos have two Audio Tracks so it would make it easier instead of going to the flyout menu. 


![Screenshot_20230511_154341](https://github.com/inotia00/ReVanced_Extended/assets/74855954/299bbdf5-623d-48bf-b21c-5275f0a01183)

2) Maybe the Custom Speed Popup selection could be in two columns instead of One.

3) The Popup selection for Video Quality, Video Speed Selection, Caption Selection, Audio Track Selection could also be placed in left or right side instead of always in the Center.

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
