### ISSUE TITLE
Patches not pulled via RVManager 1.0.0 May 5th 2023

### ISSUE THREAD

**Issue by Shad0wSmurf** [inotia00/ReVanced_Extended#976]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

com.google.android.youtube_18.16.39-1537342912_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com

### Bug description

Patches UI does not compile list of source patches

### Steps to reproduce

Install RVManager V1.0.0

### Relevant log output

```shell
None
```

### Device Environment

Android 11 MIUI Global Mod - Redmi Note 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/970
