### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#977]
### Application

Other

### Description

Why in ReVanced manager v1.0.0.0 i can't use your patches?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/970
