### ISSUE TITLE
Revanced Extended new branding icon patch

### ISSUE THREAD

**Issue by STEK1337** [inotia00/ReVanced_Extended#978]
### Application

YouTube

### Issue

Hello, can you add this branding icon patch please
![image](https://user-images.githubusercontent.com/118012196/236651490-c2680f4d-20fd-4221-af87-54a9ce6a83b8.png)
Icon download link: https://www.dropbox.com/s/faj5b9bulzebxlx/New%20Revanced%20Icon%20Pack.zip?dl=0

### Patch

New icon for Revanced Extended

### Motivation

The icon is awesome, it suits Revanced Extended

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
In the CLI, you can change the icon you want

See the link below for more details
https://github.com/inotia00/ReVanced_Extended/issues/955#issuecomment-1536532265

**Comment by inotia00** [comment]
If you want to add a new icon patch, you have to leave a PR

PR example: https://github.com/inotia00/revanced-patches/pull/8
