### ISSUE TITLE
suggestion: Add options to disable either "current video quality snackbar" or "default video quality toast notification".

### ISSUE THREAD

**Issue by FlamySan** [inotia00/ReVanced_Extended#979]
### Application

YouTube

### Description

With Snack bar & Default Video Quality enabled, when you try changing to a certain video quality, both the toast & snack bar notification pops up on the screen. This can be avoided if toast notification for Default Video Quality patch is disabled or a toggle is added to do so. (Else if this specific snack bar can be removed, that'd be better)
![IMG_20230507_093154](https://user-images.githubusercontent.com/127960032/236657525-608902f3-f1a0-49df-9c9d-8759f8dedb25.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
To turn off toast messages
turn off: `Enable save default quality`

To hide the snack bar
turn on: `Hide snack bar`
