### ISSUE TITLE
feat(patch): Add the custom branding icon from ReVanced

### ISSUE THREAD

**Issue by MatadorProBr** [inotia00/ReVanced_Extended#98]
### Application

YouTube

### Issue

The icon design since some people like the original ReVanced icon that the ReVanced Extended icon.

### Patch

Create a patch that adds the possibility to use the ReVanced original icon on ReVanced Extended, probably with the ```custom-branding-icon-revanced``` name.

### Motivation

Some people like more the original ReVanced icon that the ReVanced Extended icon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Spacellary** [comment]
Maybe this could look interesting after they release their new ReVanced logo, which is likely to happen in the coming months.

**Comment by inotia00** [comment]
This patch has already been applied

refer the following guide
https://www.reddit.com/r/revancedextended/comments/134lqws/how_to_add_custom_icons_for_youtubeyt_music_using/
