### ISSUE TITLE
feat(patch): Option to disable certain codecs/ choose preffered video format

### ISSUE THREAD

**Issue by Shaarigan** [inotia00/ReVanced_Extended#980]
### Application

YouTube

### Issue

I got a quiet weird bug on my Android TV Box that prevents me from enjoying YouTube anymore. Playing the first Video works fine and everything is cool but after that, playing any other Video might has no sound until I use the scrubber, then everything works well again until the next Video starts and so on.

This also happens with stock YouTube so it is something they changed between 16.x.x (no issues) and 17.x.x (audio issues started to appear). Previously I ran the 16.x.x App until Google depreciated the App and I had no choice to update. Tried with your Extended 17.x.x App and it worked well with the spoofing option enabled because it reloaded the video once on start and so fixed the sound issue automatically but then I encountered the buffering bug that I can't seem to fix with any of the provided spoofing options, whether in 17.x.x nor any of the 18 versions.

After some weeks of investigation, it turned out to happen only at some videos while others play well. I guess YouTube is choosing different codecs and while VP9 has built-in hardware support, AV01 seems to be buggy on my device. This however is a problem of other devices as well, see FAQ from SmartTube:

`Q: AV01 does not play / Why is VP9 slow on my device?

A: Because AV01 is very new, most TVs and TV boxes not not offer hardware support and cannot play AV01 at all.

If your device has hardware support for a codec, videos using that codec should play smoothly. High resolutions might also be slow in VP9 on cheap TV boxes that don't officially support 4k. Your device probably can play VP9 videos even without hardware support, however this requires a powerful CPU to run smoothly. Fixing AV01 without hardware support is technically possible, but currently not planned and probably not efficient enough`

### Patch

It would be good to offer an option to select available codecs in video player settings so one could disable those codecs currently not supported on the given device. Any preset is used initially for each video

Maybe also offer a more fine grained video quality picker that shows the codec used as well. Any preset is used initially for each video; if the selected profile is not available, the next best available option is used. (1080p VP9 -> 720p VP9 and so on) You can still override the profile on each video individually within the player

![menu](https://user-images.githubusercontent.com/25051193/236679068-fb2f743d-ed2e-44e9-827e-ac1f50400efd.jpg)

### Motivation

Because AV01 is very new, most TVs and TV boxes not not offer hardware support and can play AV01 at all, however this requires a powerful CPU to run smoothly. Fixing AV01 without hardware support is technically possible, but probably not efficient enough.

The bug has been mentioned a few times on the net and I can guess there are other people having this issue as well. It'll help people on devices that don't support or have bugging support for whatever codec YouTube uses by default for audio playback, especially to support older devices

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
In setting, we have an option named 'Force VP9 Codec'. You can try turning on it

**Comment by Shaarigan** [comment]
> In setting, we have an option named 'Force VP9 Codec'. You can try turning on it

I already did that but it doesn't seem to always force it. It works on some videos but doesn't on others. As far as I get it, this option is only meant to allow unlicensed devices to play VP9, not to force YouTube to use it

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
