### ISSUE TITLE
question: <title>: 

### ISSUE THREAD

**Issue by Brigodir** [inotia00/ReVanced_Extended#981]
### Application

YouTube

### Description

При просмотре видео через обыкновенное приложение Youtube на смартфоне, после 30-50 секунд, видеоролик останавливается и начинает бесконечно грузиться. Если закрыть видео и снова открыть, то все будет нормально, до тех пор пока снова не пройдет 30-50 секунд просмотра.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] I have written the title and contents in English.

**Comment by Metallifani666** [comment]
You didn't write informative title, and you didn't write your contents in English.

**Comment by Brigodir** [comment]
When watching a video through an ordinary Youtube application on a smartphone, after 30-50 seconds, the video stops and begins to load endlessly. If you close the video and reopen it, everything will be fine until 30-50 seconds of viewing have passed again. Maybe it's because of the servers, the stream is so immersed.
