### ISSUE TITLE
feat(patch): bypass unavailable content in YTM?

### ISSUE THREAD

**Issue by pressRtowin** [inotia00/ReVanced_Extended#982]
### Application

YouTube Music

### Issue

I'm not sure if this is possible and I couldn't find any discussion about this when I tried searching, but it's it possible to bypass the "Content is unavailable" error in YTM for videos that play perfectly fine on YT but are blocked for some reason on YTM?

To be clear, this isn't content that isn't normally available in my region or anything. The videos play fine in YT. I have no idea why YTM marks these (seemingly random) tracks as unavailable. 

### Patch

See above.

### Motivation

This might actually give me a reason to use YTM. Right now, a bunch of playlists I'd like to listen to can only be played in YT due to a bunch of the tracks not being available on YTM.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
yep no plans to support, just use third party app
