### ISSUE TITLE
suggestion: Title and Description changes 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#983]
### Application

YouTube Music

### Description

Currently inside the manager the patch `hide new playlist button` is written as hide new playlist which doesn't identify it's purpose. It needs to be renamed accordingly. Also the patch description should be edited where 'Hide' should be 'Hides' and 'New Playlist' should be written within a singular quotation mark.
![Screenshot_20230508-122314~2](https://user-images.githubusercontent.com/117499019/236756324-dd3b60c8-2a94-4a72-a7b2-ebb68e724895.png)

The same should be followed inside the app as well:
![Screenshot_20230508-122443~2](https://user-images.githubusercontent.com/117499019/236757880-fd129dbd-d72c-4b45-9008-803ee2efb8e8.png)

Also there's inconsistencies when naming same or similar components. For instance, the home inside the music app is described as homepage and home screen. Whereas explorer is named as it is and the library is called library tab. A consistent pattern should be used while naming these. It can be just the titles like 'Home', 'Explorer, & 'Library' or add tab at end or page. I don't feel 'screen' as a suitable naming scheme but depending on your preference, a uniform naming scheme should be followed.
![Screenshot_20230508-123614~2](https://user-images.githubusercontent.com/117499019/236759460-57525c63-02d6-42bb-8639-b4e84f2f57d2.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.173.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.10)

**Comment by ILoveOpenSourceApplications** [comment]
Hey @inotia00, I don't think this is ready to be closed as many of my other suggestions haven't been considered or been done yet. I genuinely believe these changes are required for a more consistent and clear understanding. I have changed it into a check list so that after each one is done it can be checked out. I'm not saying this needs to be reopened as long as you'll consider making these changes.

**Comment by inotia00** [comment]
![contents](https://github.com/inotia00/ReVanced_Extended/assets/108592928/65e472b9-a186-4fcf-8ca2-aa9d4a6e49fa)
You edited the contents

open a new issue

**Comment by ILoveOpenSourceApplications** [comment]
Will do that then
