### ISSUE TITLE
bug: custom seekbar color doesn't work in playlists

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#984]
### Type

Cosmetic

### Tools used

ReVanced Manager

### Application

Youtube 18.16.39
Patches 2.173.4

### Bug description

I was watching a playlist and noticed that progress bar was red instead of custom color value. On video player custom color was working fine, it's only red when scrolling down the playlist.

### Steps to reproduce

Step 1. Include custom seekbar color patch
Step 2. Set a custom seekbar color value
Step 3. Seekbar color doesn't change in playlists, this only happens when scrolling down the playlist

### Relevant log output

```shell
None
```

### Screenshots or videos

I can't add screenrecording for some reason, so here is just screenshot.

![Screenshot_20230508_102938_ReVanced Extended](https://user-images.githubusercontent.com/132079771/236767673-7d056d3a-eef3-4bee-aad6-058e9459c5a1.png)

### Device Environment

Android 13
One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
![git](https://user-images.githubusercontent.com/108592928/236772256-7a9d20ed-dbe4-49af-8760-110c3be351d2.jpg)

![termux_Termux](https://user-images.githubusercontent.com/108592928/236772154-03a9300e-97b2-4887-8428-f290f2400f8f.png)

![result](https://user-images.githubusercontent.com/108592928/236772166-6554c4dd-e230-4146-af5a-c3aa690442e7.png)

 works fine

**Comment by NoMorePizza** [comment]
That's ReVanced builder right? I'm not familiar with it. I patched my RVX with manager and seekbar color doesn't change in playlist feed.

**Comment by NoMorePizza** [comment]
> ![git](https://user-images.githubusercontent.com/108592928/236772256-7a9d20ed-dbe4-49af-8760-110c3be351d2.jpg)
> 
> ![ttttttermux](https://user-images.githubusercontent.com/108592928/236772632-9143d7ad-aee8-4ca1-9c65-03ef52789bfe.png)
> 
> ![result](https://user-images.githubusercontent.com/108592928/236772166-6554c4dd-e230-4146-af5a-c3aa690442e7.png)
> 
> works fine

That ReVanced builder right? I'm not familiar with it. I patched my RVX with ReVanced manager and seekbar color doesn't change in playlist feed.

**Comment by inotia00** [comment]
As also mentioned in the changelog, the seekbar color of a playlist can only be changed via options.json

but ReVanced Manager doesn't provide the ability to change options.json

use Revancify
