### ISSUE TITLE
bug: <title> video stop working after 2 min

### ISSUE THREAD

**Issue by shoshohamadah** [inotia00/ReVanced_Extended#986]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Youtube v18.19.39

### Bug description

The video stops by itself after around 2 min of watching and then I have to re-open it to work again for another 2 min and so on.. 

That's how it looks and it stays like this even when my internet is fast and working well.. 
![Screenshot_20230508_120729_com vanced android youtube](https://user-images.githubusercontent.com/132890952/236784344-0bd79588-dc70-47cb-869a-557eb53bbcf5.jpg)

### Steps to reproduce

Open a video.. Wait 2 min.. It will stop working by itself

### Relevant log output

```shell
..
```

### Screenshots or videos

https://user-images.githubusercontent.com/132890952/236785733-8f905911-f000-496d-a9c4-ff3ebf5ecc88.mp4

### Device Environment

EMUI 12.0.1

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Metallifani666** [comment]
Enable `enable protopuf soof` and try again.
