### ISSUE TITLE
bug: seekbar tapping is laggy

### ISSUE THREAD

**Issue by ankitxcoding** [inotia00/ReVanced_Extended#988]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.16.39 and all previous versions also.

### Bug description

seekbar tapping not as smooth as revanced like when we tap on seekbar then there is little delay whereas in revanced there are not any delay, that works perfectly.

### Steps to reproduce

Step 1. Play any video.
Step 2. Try to forward video while tapping on seekbar.

### Relevant log output

```shell
I don't have.
```

### Screenshots or videos

https://user-images.githubusercontent.com/103440538/236825178-b31d2df8-0a4d-4c31-80b7-b97cb96f1c01.mp4

### Device Environment

Realme UI 3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Please add revanced-patches version

**Comment by ankitxcoding** [comment]
Enable Seekbar Tapping Patch v0.0.1
Using Revanced Manager v0.0.57

**Comment by inotia00** [comment]
repatch with latest resources (and clean install) and let me know result
