### ISSUE TITLE
feat(patch): add small overlay button icon option

### ISSUE THREAD

**Issue by EnzoDpch33** [inotia00/ReVanced_Extended#99]
### Application

YouTube

### Description

Hello I have a suggestion for revanced extended would it be possible to take the icons to copy the link quickly of revanced I find that of revanced extended too big
![Screenshot_2023-01-05-03-50-32-558_app revanced android youtube~2](https://user-images.githubusercontent.com/91429858/210690528-1d619a3d-4f49-477f-ac2f-c4996838bea5.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, I couldn't find the icon source used by ReVanced Team.
(The icon source currently used in ReVanced Extended is [Material Icons](https://fonts.google.com/icons?selected=Material+Icons))

If I can find the source of the icon they use, or if I can provide a small icon, I'll add it as an option.

Anyway, I'll change the label for this issue, as the `patch-request` label seems more appropriate.

**Comment by kazimmt** [comment]
> Unfortunately, I couldn't find the icon source used by ReVanced Team. (The icon source currently used in ReVanced Extended is [Material Icons](https://fonts.google.com/icons?selected=Material+Icons))

ReVanced one is Material Symbols

**Comment by inotia00** [comment]
reflected in revanced-patches-v2.153.6
