### ISSUE TITLE
bug: `Open library on app launch` delay

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#990]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.16.39
ReVanced Patches v2.173.4

### Bug description

With `Open library on app launch` enabled, the app will first open in the **Home** tab and after some delay it will move you to the Library tab.

It also happens if you've set your current homepage to subscriptions, the app will first open in the **Subscriptions** tab and then after a delay it will move to the Library tab.

https://user-images.githubusercontent.com/127908708/236866491-71b60657-db7a-4971-a235-f83c7c699e64.mp4

### Steps to reproduce

1. Enable `Open library on app startup`
2. Restart the app

### Relevant log output

```shell
N/A
```

### Solution

I think the delay is caused by the app checking first the `Change homepage to subscriptions` option and then `Open library on app startup`.

This can be solved by merging the options `Change homepage to subscriptions` and `Open library on app startup` into one.
And when you tap on the option, a window should open as does the `Spoof app version target` option and let you choose the tab you want as current.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
That's why the patch is named 'Open library tab on app startup', not 'Make library tab homepage'
