### ISSUE TITLE
What "key" can I use to change the background color when watching videos with theme patch?

### ISSUE THREAD

**Issue by lethinhrider** [inotia00/ReVanced_Extended#991]
### Application

YouTube

### Description

I changed the theme value in options.json like this:
```
{
  "patchName" : "theme",
  "options" : [ {
    "key" : "darkThemeBackgroundColor",
    "value" : "#212121"
  } ]
}
```
It works well in homepage and settings:
![1](https://user-images.githubusercontent.com/43519453/236894640-ae59f6db-c77f-4718-a620-e8f6140cb34f.jpg)
![2](https://user-images.githubusercontent.com/43519453/236894673-6f3fb6d4-9007-4af7-a6d8-3f65695fe38a.jpg)
![3](https://user-images.githubusercontent.com/43519453/236894690-8630de9a-117e-4960-9c95-b5577ba0ae85.jpg)

**But**...... when I click to watch a video, it's still black amoled theme:
![4](https://user-images.githubusercontent.com/43519453/236894808-8eba5049-184b-47cd-8520-4a2a76f7d5e8.jpg)

**Is there any other "key" I can use to change the background color when watching a video?**

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
That's a change for YouTube

With the new layout, YouTube enforces the theme for that part on the server side

**Comment by Hennadz** [comment]
>     "key" : "darkThemeBackgroundColor",
>     "value" : "#212121"

Invalid argument. Should be written in the form "value": "#ff212121"

**Comment by lethinhrider** [comment]
> 
> >     "key" : "darkThemeBackgroundColor",
> >     "value" : "#212121"
> 
> Invalid argument. Should be written in the form "value": "#ff212121"
> 

Can you explain more? Why do I have to add ff in front of the hex code? 
The color I chose is RGB(33,33,33) so the hex code will be #212121

**Comment by Hennadz** [comment]
Need a format ARGB (Alpha, Red, Green, Blue).
Here is an example of how colors are recorded (standard YouTube):
![Screenshot_20230509-200925_Apktool M](https://github.com/inotia00/ReVanced_Extended/assets/130844239/fccb5201-ed09-418c-beab-97aa488e344c)
Just do as I say if you need a dark theme in the new interface.

**Comment by lethinhrider** [comment]
> Need a format ARGB (Alpha, Red, Green, Blue).
> Here is an example of how colors are recorded (standard YouTube):
> ![Screenshot_20230509-200925_Apktool M](https://github.com/inotia00/ReVanced_Extended/assets/130844239/fccb5201-ed09-418c-beab-97aa488e344c)
> Just do as I say if you need a dark theme in the new interface.
> 
> 

Bad news, I did as you instructed but everything is still the same :(
![Screenshot_20230510-041049.png](https://github.com/inotia00/ReVanced_Extended/assets/43519453/2b452d1e-de7d-4f5a-a547-837d4c6d6cbc)

**Comment by Hennadz** [comment]
> Плохие новости

There is no bad news. You are doing something wrong.

![Screenshot_20230510-022548_Termux](https://github.com/inotia00/ReVanced_Extended/assets/130844239/444d5581-cbf3-44e2-a662-cab33129fdd5)

![Screenshot_20230510-021457_Termux](https://github.com/inotia00/ReVanced_Extended/assets/130844239/d299617d-4d2e-489c-a956-f9b595eaf9f3)


![Screenshot_20230510-024250_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/130844239/6832d6ac-293e-4369-8160-d78a004543cc)

![20230510_023141](https://github.com/inotia00/ReVanced_Extended/assets/130844239/7b67f234-441c-49ac-aaf6-b69061728832)
![Screenshot_20230510-024033_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/130844239/6a189531-2337-4bee-a0e0-03d9f663f037)

![Screenshot_20230510-025930_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/130844239/1e53e090-1536-4590-8ad4-f31ab1e723f6)

**Comment by Hennadz** [comment]
Have you tried turning off ambient mode?
https://support.google.com/youtube/answer/7385323

**Comment by lethinhrider** [comment]
> Have you tried turning off ambient mode?
> https://support.google.com/youtube/answer/7385323

The link you gave redirects me to the manual page to enable/disable Light and Dark theme:![Screenshot_20230510-174243.png](https://github.com/inotia00/ReVanced_Extended/assets/43519453/04f21ab5-4c48-4516-9bc6-8655beb91ca3)

**Comment by Hennadz** [comment]
Sorry. Correct link:
https://support.google.com/youtube/answer/12827017?hl=en&co=GENIE.Platform%3DAndroid

**Comment by lethinhrider** [comment]
> Sorry. Correct link:
> https://support.google.com/youtube/answer/12827017?hl=en&co=GENIE.Platform%3DAndroid
> 

It finally works, thank you very much. 
Has anyone suggested the idea of ​​automatically turning off Ambient mode when the user select the patch "theme"?
