### ISSUE TITLE
question: <title>: AV1 codec 

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#992]
### Application

YouTube

### Description

Can you able to patch YouTube revanced extended force AV1 codec just like force VP9 codec feature or add compatibility to those devices who dosent support this codec ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
As far as I know, the official YouTube Android client doesn't support the AV1 codec.

Use an alternative YouTube client

**Comment by odkrys** [comment]
It uses av1 codec. Confirmed on galaxy s23.

**Comment by Adity1243** [comment]
![image](https://user-images.githubusercontent.com/131557644/237008061-85073eff-9cac-434a-bd04-5ed55ff8da60.png)

See here its sender by someone in my 1440+ resolution not supported issue
