### ISSUE TITLE
feat(patch): Add crowdin contributor list credits to YT & YTM

### ISSUE THREAD

**Issue by okkidwi** [inotia00/ReVanced_Extended#994]
### Application

YouTube

### Issue

None

### Patch

This patch will make it easier for people to find out the crowdin translator contributors. Maybe you could add a list of usernames, profile links and the languages they translate on crowdin or just list the usernames and languages they translate

### Motivation

This patch will make it easier for people to find out the crowdin translator contributors

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
All types of applications where Crowdin translations are used, including YouTube Vanced, traditionally do not disclose Crowdin contributors

I also don't know why

I will also keep this 'tradition'
