### ISSUE TITLE
feat(patch): playlist infinite buffering 

### ISSUE THREAD

**Issue by unnobody** [inotia00/ReVanced_Extended#996]
### Application

YouTube

### Issue

Infinite buffering in playlists
(Yeah, i used buffer changing feature)

### Patch

Please fix it, if it's possible 

### Motivation

"Watch later" Playlist is a playlist

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
repatch with latest resources
