### ISSUE TITLE
feat(patch): theme problem

### ISSUE THREAD

**Issue by aadi-pc** [inotia00/ReVanced_Extended#998]
### Application

YouTube

### Issue

Hello. I have a problem in youtube vanced application. I downloaded  the latest version of YouTube Vanced with dark theme but after I used the app for sometime and closed and reopened, the theme became amoled black I dont know why that is happening. Then I tried on my brothers phone too and the same problem I'm having. Please patch this problem as soon as possible.(my phone - Redmi note 5 pro, brother's phone - Redmi note 6 pro). Thankyou

### Patch

#690
![Screenshot_2023-05-10-12-05-58-743_com vanced android youtube](https://github.com/inotia00/ReVanced_Extended/assets/99813707/4f61999e-2b7c-41df-9020-9f4b977f9839)
![Screenshot_2023-05-10-12-05-53-399_com vanced android youtube](https://github.com/inotia00/ReVanced_Extended/assets/99813707/ab959d3a-f591-413e-91b3-5b7925cd02fe)
![Screenshot_2023-05-10-12-06-18-383_com vanced android youtube](https://github.com/inotia00/ReVanced_Extended/assets/99813707/dc36e9a4-b798-45ae-a38f-12233e3329fe)

### Motivation

Because dark theme is better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is the ReVanced Extended repo, not the YouTube Vanced repo

Also I do not distribute prebuilt apk.
