### ISSUE TITLE
bug(protobuf-spoof): playing a clip will play the video from the start

### ISSUE THREAD

**Issue by Spacellary** [inotia00/ReVanced_Extended#999]
### Type

Error at runtime

### Tools used

CLI

### Application

RVX YouTube 18.16.39, **18.17.43**
Patches v2.173.4, **v2.173.8**

### Bug description

When trying to view a Clip, if the Protobuf Spoof toggle is enabled in the Miscellaneous settings, the Clips will not behave correctly, instead of playing the clipped portion properly it will just play the entire video.

When Protobuf Spoof is toggled off in the Miscellaneous settings, the Clips will behave correctly and play the clipped portion as expected.

### Steps to reproduce

1. include and enable the `protobuf-spoof` patch
2. create a clip or use [this test clip](https://youtube.com/clip/UgkxwESgF7YM5Q5_jxOLv-6UWbR7n0fLJQm3) I linked for example
3. try to play the clip and
* with Protobuf Spoof ON the video will play from the start
* with Protobuf Spoof OFF the video will play the correct section

### Relevant log output

```shell
Not applicable.
```

### Additional context

I understand this is likely a direct consequence of well... Spoofing the video playback. Just reporting the bug as it is, perhaps it's possible to isolate a fix for Clips.

This was reported in the subreddit and I also confirmed in my own application.

### Device Environment

Android 12, MIUI 13, Redmi Note 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.173.10](https://github.com/inotia00/revanced-patches/releases/tag/v2.173.10)

**Comment by Spacellary** [comment]
Thanks @inotia00 🙏💯
